### ISSUE TITLE
PouchDB Spatial

### ISSUE THREAD

**Issue by DrYSG** [pouchdb/pouchdb#1155]
The link to the Github PouchDB spatial project: http://pouchdb.com/external.html is broken, and I cannot find it in GitHub.

But I did find out recently that ESRI has released an Open Source Spatial GJSON database based on LevelDB. Would this be a candidate someday for PouchDB (similar to how PostGRESQL has  PostGIS add-on that can be added via the StackBuilder?

ESRI TerraFormer GeoStore: http://terraformer.io/geostore/

@DrYSG

**Comment by HarelM** [comment]
Sorry for posting on this old thread, but I wanted to know if geopouch is the go-to for using spatial queries over PouchDb - I saw that the last commit there is about a year old...
I would like to implement an offline get-near-by-points-of-interest and geo-search and am looking for the right browser database (I'm using Cordova and a regular site).
My repository is here:
https://github.com/IsraelHikingMap/Site/
Site is here:
https://israelhiking.osm.org.il/
I'm working on a branch called OpenLayers and am interested to know if PouchDB is the right solution for my needs (I'm using ElasticSearch in the server and not CouchDB, I hope this is OK).
Any insight will be appreciated :-)
