### ISSUE TITLE
use actual error objects

### ISSUE THREAD

**Issue by calvinmetcalf** [pouchdb/pouchdb#1167]
instead of objects that claim to be errors

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/cef1ded5712dea0256e8fe4d2c9ffaf48c891651

**Comment by hadrien-toma** [comment]
@au-phiware, do you know if `PouchError` or `CustomPouchError` are now exported somewhere?

**Comment by nolanlawson** [comment]
Check `src/packages/node_modules/pouchdb-errors`

**Comment by hadrien-toma** [comment]
Thank you @nolanlawson , I found this export :
```
export {
  UNAUTHORIZED,
  MISSING_BULK_DOCS,
  MISSING_DOC,
  REV_CONFLICT,
  INVALID_ID,
  MISSING_ID,
  RESERVED_ID,
  NOT_OPEN,
  UNKNOWN_ERROR,
  BAD_ARG,
  INVALID_REQUEST,
  QUERY_PARSE_ERROR,
  DOC_VALIDATION,
  BAD_REQUEST,
  NOT_AN_OBJECT,
  DB_MISSING,
  WSQ_ERROR,
  LDB_ERROR,
  FORBIDDEN,
  INVALID_REV,
  FILE_EXISTS,
  MISSING_STUB,
  IDB_ERROR,
  INVALID_URL,
  createError,
  generateErrorFromResponse
};
```
So, I don't figure how to import PouchError or CustomPouchError in an other project, could you help me to manage to do it?

**Comment by nolanlawson** [comment]
Those aren't really designed to be user-facing, so I don't think those things are exposed, sorry. You can just use a regular Error object, unless there's a reason you really need `PouchError`?

**Comment by hadrien-toma** [comment]
In fact, what I am now doing is :
```
let docId = "my_id"
try{
    await db.get(docId)
}catch(error){
    if((error.status !== undefined) && (error.status == MISSING_DOC)){
        console.log("There could be a PouchError meaning that the document with id " + docId + " does not exist.")
    }else{
        throw error
    }
}
```
But what I would like to do is something like :
```
let docId = "my_id"
try{
    await db.get(docId)
}catch(error){
    if((error instanceof PouchError) && (error.status == MISSING_DOC)){
        console.log("There is a PouchError meaning that the document with id " + docId + " does not exist.")
    }else{
        throw error
    }
}
```

**Comment by nolanlawson** [comment]
The more standard way of doing this is:

```js
if (error.status === 404) {
  // handle not found
} else if (error.status === 409) {
  // handle conflict
}
```

In userland code those two states are typically the only two you need to worry about; you shouldn't need a blanket `error instanceof PouchError`. Alternatively you can use this plugin to avoid dealing with 404s/409s entirely: https://github.com/pouchdb/upsert

**Comment by hadrien-toma** [comment]
Okay thank you, I will use this standard way. Thank you too for the plugin link, an other great one that you maintain^^. I am a really big fan of your projects you know!

**Comment by isumix** [comment]
I would also like to test the error with `instanceof CustomPouchError` operator. And use `CustomPouchError`  in typescript instead of delaring it myself.
