### ISSUE TITLE
Attachment api sucks

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#1251]
db.putAttachment(docId, attachmentId, rev, doc, type, [callback]);

is pretty terrible, in couchdb there has been proposals to change the api to allow

    db.put(blob, id, rev) 
    // or?
    db.put(blob, {id: id, rev: rev});

We also have the ability to store {some: 'json', with: aBlob}, which couchdb doesnt do. We need to have compatibility with couch and I want to be as flexible as possible, but seems like we could improve this

**Comment by nolanlawson** [comment]
Closing as I think the attachment API is actually pretty great these days. `blob-util` helps iron out some rough edges, and #2858 and #3758 are good follow-up issues.
