### ISSUE TITLE
Inconsistent behaviour during Chrome Heap Allocation Recording

### ISSUE THREAD

**Issue by TheAncientGoat** [pouchdb/pouchdb#1258]
db.allDocs({include_docs:true)} does not return all documents in databases with largish numbers of documents (300) when using Chrome's memory debugging dev tools, specifically the automatic heap allocation feature. Out of 300 documents, it returns between 220 and 273 random documents for me. This does not occur when {include_docs:false} is set.

 Not a show-stopping bug, but it does feel like it's exposing some underlying issue, and does make tracking down memory leaks in my application quite a bit more difficult.

**Comment by daleharvey** [comment]
So just tested this against 3.2.1 and consistently returned the same amount of docs I entered, fixed :)
