### ISSUE TITLE
trouble adding more than one attachment

### ISSUE THREAD

**Issue by briankj** [pouchdb/pouchdb#1287]
I'm able to add one attachment just fine.  I try to add another to the same document and I get "Document update conflict:name".  I've made sure the second attachment has a different attachment id than the first, but still it won't allow the second one to be attached to the same document.  To work around it for now I save the first attachment and then I save the second attachment with an underscore on the doc ID.  This works, but creates two separate documents in the db, one for each attachment.   

Code Snippet:

 db.put(xyzdPhoto, function (err, result) {
            //app.log('put 8');

            if (!err) {

                if (base64Photo)
                    attachPhoto(result);
                else {
                    app.logError(me + ' no base64Photo');
                    callback(true);
                    return;
                }
                
                function attachPhoto(result) {

                    var me = '|| fdcModel.put.attachPhoto || ';

                    var attachmentType;

                    modelsrv.putAttachment(result.id, result.rev, 'IMAGE', 'image/base64/jpg', base64Photo,
                    function () { //successfully attached image
                        if (base64Audio)
                            attachAudio(result,callback);
                        else
                            callback(false);
                    },
                    function (err) {
                        app.logError(me + err.msg);
                        callback(true);
                    });
                }

                function attachAudio(result,callback) {

                    var me = '|| fdcModel.put.attachAudio || ';

                    var IOS_AUDIO_ATTACHMENTTYPE = 'audio/base64/m4a'; //on iOS audio is converted from wav to m4a, read into a bufferArray, encoded to base64 and then put into a blob before it is attached.
                    var ANDROID_AUDIO_ATTACHMENTTYPE = 'audio/base64/amr'; //on Android audio is recorded as amr, read into a bufferArray, encoded to base64 and then put into a blob before it is attached.

                    if (app.runningOnDevice('Android'))
                        attachmentType = ANDROID_AUDIO_ATTACHMENTTYPE;
                    else
                        if (app.runningOnDevice('iOS'))
                            attachmentType = IOS_AUDIO_ATTACHMENTTYPE;
                        else 
                            attachmentType = 'audio/base64/unknown';
                    //NOTE: ran into a bug and had to add an uderscore to the docId to get the audio attachement to save.
                    modelsrv.putAttachment(result.id, result.rev + "_", 'AUDIO', attachmentType, base64Audio,
                    function () {
                        callback(false);
                    },
                    function (err) {
                        app.logError(me + err.msg);
                        callback(true);
                    });
                }
            }
            else {
                logError(me + "Failed to put document: " + xyzdPhoto._id, err);
                callback(true);                
            }
            //app.log('put 9');
        });

        //app.log('put 10');

    };

    this.putAttachment = function(docId, docRev, attachmentId, attachmentType, buffer,successCallback,failCallBack) {

        var me = '|| fdcModel.putAttachment || ';

        app.log(me + "docID: " + docId + '  docRev: ' + docRev + ' attachmntId: ' + attachmentId + 'attachmentType: ' + attachmentType);

        var bufferSize = buffer.length;

        app.log('putAttachment  buffer size in:' + bufferSize);

        if (bufferSize == 0) {
            app.log('No attachment');
            successCallback();
            return;
        }
      
        var blob = null;

        if (!app.runningOnDevice() || app.runningOnDevice('iOS')) {
            blob = new Blob([buffer]);
        }
        else {

            window.BlobBuilder = window.BlobBuilder || window.WebKitBlobBuilder ||
                 window.MozBlobBuilder || window.MSBlobBuilder;
            var builder = new window.BlobBuilder();
            builder.append(buffer);
            /*for (var i = 0; i < bufferSize; i++) {
                builder.append(buffer[i]);
            }*/
            blob = builder.getBlob(attacmentType);
        }
        
        app.log("putAttachment blob size out: " + blob.size);
        
        db.putAttachment(docId, attachmentId, docRev, blob, attachmentType, function (err, res) {
            //app.log("putAttachment 8: ");
            if (err) {
                app.logError(me + ' Failed to save attachment to the database! :message: ' +
                    err.message + " :name: " + err.name + " :status: " + err.status);
                failCallBack(err);
            }
            else {
                app.log('successfully saved attachment:: ' + res.ok + ' :: ' + res.id + ' :: ' + res.rev);
                blob = null;
                fdcApp.audioBuffer = null;                
                successCallback();
            }
        });

    };

**Comment by daleharvey** [comment]
Sweet cheers
