### ISSUE TITLE
Ability to replicate partial documents (without attachments)

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#1365]
Not ready to be implemented, needs designed

**Comment by DerekTBrown** [comment]
I dont think delta-pouch solves the problem (at least how I understand it).  What I think OP is looking for is a options.attachments for sync, which omits attachments when replicating a remote database.

**Comment by daleharvey** [comment]
dupe of https://github.com/pouchdb/pouchdb/issues/4362
