### ISSUE TITLE
Errors lose their stack

### ISSUE THREAD

**Issue by slaskis** [pouchdb/pouchdb#1371]
Since the errors was nicely consolidated to `PouchDB.Errors.X`-constants the stack traces of any exceptions are very unhelpful. Granted stack traces are not great in asynchronous code in general but right now they all point back to `lib/deps/errors.js` (or the dist equivalent) instead of the place where they occured thus losing the context of the error when debugging.

I see two solutions:

1. Use getters for the errors (assuming es5 is the target). This makes a very simple backwards compatible change by updating `lib/deps/errors.js` to use `__defineGetter__` or `Object.defineProperty()` instead.
2. Changing all the errors to functions instead. It will be a lot of edits but more <IE9 friendly.

**Comment by daleharvey** [comment]
I think we have fairly consistent error handling these days
