### ISSUE TITLE
changes with since=bigger_than_anything should not give last_seq: 0

### ISSUE THREAD

**Issue by neojski** [pouchdb/pouchdb#1389]
If you put since parameter bigger than last change then Pouch gives you last_seq=0. Try couchdb: http://localhost:5984/asfd/_changes?since=1000000000000000000. You'll get the same big number.

Small thing and looks like goodfirstpatch

**Comment by daleharvey** [comment]
Yeh this isnt going to be a sensible feature with couchmaster
