### ISSUE TITLE
db.allDocs doesn't exist

### ISSUE THREAD

**Issue by marfarma** [pouchdb/pouchdb#1407]
While testing my project against the current master branch, I noted the following unhandled rejections:

   [Q] Unhandled rejection reasons (should be empty): TypeError: 'undefined' is not a function (evaluating 'db.allDocs')

Here's the code in question: 

```
new PouchDB(PouchDB.allDBName(adapter), function (err, db) {
   ...

db.allDocs({include_docs: true}, function (err, response) {
    if (err) {
      callback(err);
      return;
    } // comments stripped
    all_dbs.unshift.apply(all_dbs, response.rows);
    accumulate(adapters, all_dbs);
  });
});
 ...
```

Stepping through the code, this is the exception:    

```
"Object function (fulfill, reject) {
    callback = function (err, resp) {
      if (err) {
        return reject(err);
      }
      delete resp.then;
      fulfill(resp);
    };

    opts = utils.extend(true, {}, opts);
    var originalName = opts.name || name;
    var backend = PouchDB.parseAdapter(originalName);

    opts.originalName = originalName;
    opts.name = backend.name;
    opts.adapter = opts.adapter || backend.adapter;

    if (!PouchDB.adapters[opts.adapter]) {
      throw 'Adapter is missing';
    }

    if (!PouchDB.adapters[opts.adapter].valid()) {
      throw 'Invalid Adapter';
    }
    var adapter = new Adapter(opts, function (err) {
      if (err) {
        if (callback) {
          callback(err);
        }
        return;
      }

      for (var plugin in PouchDB.plugins) {
        if (PouchDB.plugins.hasOwnProperty(plugin)) {
          // In future these will likely need to be async to allow the plugin
          // to initialise
          var pluginObj = PouchDB.plugins[plugin](self);
          for (var api in pluginObj) {
            if (pluginObj.hasOwnProperty(api)) {
              // We let things like the http adapter use its own implementation
              // as it shares a lot of code
              if (!(api in self)) {
                self[api] = pluginObj[api];
              }
            }
          }
        }
      }

      self.taskqueue.ready(true);
      self.taskqueue.execute(self);
      callback(null, self);
    });
    for (var j in adapter) {
      if (adapter.hasOwnProperty(j)) {
        self[j] = adapter[j];
      }
    }
    for (var plugin in PouchDB.plugins) {
      if (PouchDB.plugins.hasOwnProperty(plugin)) {

        // In future these will likely need to be async to allow the plugin
        // to initialise
        var pluginObj = PouchDB.plugins[plugin](self);
        for (var api in pluginObj) {
          if (pluginObj.hasOwnProperty(api)) {
            // We let things like the http adapter use its own implementation
            // as it shares a lot of code
            if (!(api in self)) {
              self[api] = pluginObj[api];
            }
          }
        }
      }
    }
  } has no method 'allDocs'"    
```

**Comment by mohammadhafiz** [comment]
hai can u answer my question. 

this is my service
application.service('Arrears', [
    function() 
    {
        var db = new PouchDB('http://192.168.1.155:5984/arrears');
        return {
            put: function (user) {
                var data = {
                  "_id": new Date().toString(),
                  "account_no": user.account_no,
                  "address": user.address,
                  "arrears": user.arrears,
                  "cases_id": user.cases_id,
                  "contact_no": user.contact_no,
                  "council": user.council,
                  "detail": user.detail,
                  "giant_id": user.giant_id,
                  "land_cass": user.land_cass,
                  "last_paid_ammount": user.last_paid_ammount,
                  "lastpayDate": user.lastpayDate,
                  "location": user.location,
                  "owner_id": user.owner_id,
                  "owner_name": user.owner_name,
                  "paid_until": user.paid_until,
                  "property_id": user.property_id,
                  "receipt_no": user.receipt_no,
                  "status": user.status,
                  "title_no": user.title_no,
                };
                
                return db.put(data);
            },
            
            get: function (user) {
                db.get(data)
            },
            
            allDocs: function (user) {
               var data = {
                  "_id": user.rows[i].doc._id,
                  "account_no": user.rows[i].doc.account_no,
                  "address": user.rows[i].doc.address,
                  "arrears": user.rows[i].doc.arrears,
                  "cases_id": user.rows[i].doc.cases_id,
                  "contact_no": user.rows[i].doc.contact_no,
                  "council": user.rows[i].doc.council,
                  "detail": user.rows[i].doc.detail,
                  "giant_id": user.rows[i].doc.giant_id,
                  "land_cass": user.rows[i].doc.land_cass,
                  "last_paid_ammount": user.rows[i].doc.last_paid_ammount,
                  "lastpayDate": user.rows[i].doc.lastpayDate,
                  "location": user.rows[i].doc.location,
                  "owner_id": user.rows[i].doc.owner_id,
                  "owner_name": user.rows[i].doc.owner_name,
                  "paid_until": user.rows[i].doc.paid_until,
                  "property_id": user.rows[i].doc.property_id,
                  "receipt_no": user.rows[i].doc.receipt_no,
                  "status": user.rows[i].doc.status,
                  "title_no": user.rows[i].doc.title_no
                }
            return db.allDocs(data)
            }
        }
    }
]);

can u give me code for me to call service into controller. 

application.controller('CreateManagementController', ['$mdSidenav', '$location', '$scope', 'Arrears',
    function($mdSidenav, $location, $scope, Arrears)
    {
        $scope.limit = 50;
        $scope.page = 0;
        $scope.theme = 'teal';

        $scope.put = function(user)
        {
            Arrears.put(user)
            .then(function(response) 
            {
                console.info(response);
            }).catch(function(error) 
            {
                console.error(error);
            })
        };
        
        $scope.menu = function()
        {
            $mdSidenav('menu').open();
        };
        
        $scope.reset = function()
        {
            $scope.query.$ = '';
        };
    }]);
