### ISSUE TITLE
iPhone and iPad problem with pouchDB

### ISSUE THREAD

**Issue by Kibo007** [pouchdb/pouchdb#1499]
PouchDB allDoc not working for iPad when I add to option { include_docs: }   it break only on iPad and iPhone on that line and write message in console:

"Attempted to assign to readonly property."

but in chrome I can get response perfectly. 

So my code:

``` javascript
function renderFromDB() {
                db.allDocs({include_docs: true}, function(err, response) { 
            var databaseResponse = response.rows;
            var sections = [];
                        for (var i = databaseResponse.length - 1; i >= 0; i--) {
                  sections.push(databaseResponse[i].doc);
                        };
                       $scope.sections = sections;
              // apply data to scope
             $scope.$apply();
        });
    }
```

**Comment by abmnukmr** [comment]
try to change adpater like this for ios ,
**var db = new PouchDB('mydatabase.db', {adapter: 'websql'});**
