### ISSUE TITLE
make sure all adapters use AbstractPouch.prototype.put/post

### ISSUE THREAD

**Issue by calvinmetcalf** [pouchdb/pouchdb#1526]
mainly for the http pouch, whats currently in AbstractPouch.prototype.put/post should got into AbstractPouch.prototype._put/_post and AbstractPouch.prototype.put/post should just call those, this would allow us to put all the option parsing in the same place and allow us to do stuff like pre update hooks, etc.  we'd need to do the same thing for httpPouch.get as well

**Comment by nolanlawson** [comment]
fixed by ef0944f72429915c7248689cc6950895de78982e
