### ISSUE TITLE
streams

### ISSUE THREAD

**Issue by calvinmetcalf** [pouchdb/pouchdb#1536]
here is my idea for streams, 

createReadStream and CreateWriteStream methods that return pipeable streams.  

Due to how streams work making the DB a readable stream is probably not the best way to do it, making the db object a writeable stream might be doable (and wouldn't conflict with #1530)

**Comment by daleharvey** [comment]
So yup, pretty clear that this is going to happen in plugin land at this point, no need for us to track it here
