### ISSUE TITLE
We should only enable nonce if we are fairly sure we are in ie

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#1586]
I hate browser sniffing, but adding nonce to everything is kinda annoying (and is causing bugs, although it shouldnt)

**Comment by daleharvey** [comment]
Actually we do need this in Firefox - https://travis-ci.org/pouchdb/pouchdb/builds/72126685

**Comment by nolanlawson** [comment]
Too bad - so sniffing didn't work?

**Comment by daleharvey** [comment]
Nope, it started failing the tests hard in chrome and firefox in the same way the tests failed when we had the caching bugs, ie random tests failing with unexpected results from http
