### ISSUE TITLE
Parse Error on Android 2.3

### ISSUE THREAD

**Issue by RangerRick** [pouchdb/pouchdb#1627]
I get the following error loading the latest PouchDB on Android 2.3 (with es5-shim):

`file:///android_asset/www/scripts/3rdparty/pouchdb-nightly.js: Line 3988 : SyntaxError: Parse error`

Line 3988 is:

`self.catch = promise.catch.bind(promise);`

I suspect the Android 2.3 javascript parser is bad at treating 'catch' as a property rather than a keyword.  I don't know if this is the 'correct' fix, but if I change that line to:

`self['catch'] = promise['catch'].bind(promise);`

...it runs for me without issue.

**Comment by ahutatatong** [comment]
I'm really lucky this issue has existed. thx. for fixing this one!
