### ISSUE TITLE
Server Sent Events

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#1653]
Not sure if we're using this but thought I'd put this up just incase.
I was investigating the support of Websockets with CouchDB and noticed they have support for Server Sent Events.
https://blogs.apache.org/couchdb/entry/apache_couchdb_1_3_0
https://issues.apache.org/jira/browse/COUCHDB-986

Server Sent Events support: http://caniuse.com/#feat=eventsource

**Comment by BigBlueHat** [comment]
Looks like Server Sent Events / EventSource is supported now, is that correct?
https://github.com/pouchdb/pouchdb/blob/master/lib/adapters/http/http.js#L951

**Comment by calvinmetcalf** [comment]
sort of, we were never able to test it due to issues with travis so while we were able to put the code in there are no guarentees it will actually work, do `db._useSSE = true` to enable it

**Comment by nolanlawson** [comment]
We disabled it because we couldn't get it working IIRC.

**Comment by calvinmetcalf** [comment]
@nolanlawson we could test it locally fine it was just travels we couldn't

**Comment by daleharvey** [comment]
So this is disabled and tracked in https://github.com/pouchdb/pouchdb/issues/2823
