### ISSUE TITLE
Map/reduce: return joined docs with _rev

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#1664]
This is a feature we might want to implement for map/reduce.  From the [CouchDB docs](https://wiki.apache.org/couchdb/HTTP_view_API#Querying_Options):

> The include_docs option will include the associated document. However, the user should keep in mind that there is a race condition when using this option. It is possible that between reading the view data and fetching the corresponding document that the document has changed. If you want to alleviate such concerns you should emit an object with a `_rev` attribute as in `emit(key, {"_rev": doc._rev})`. This alleviates the race condition but leaves the possibility that the returned document has been deleted (in which case, it includes the `"_deleted": true` attribute). Note: include_docs will cause a single document lookup per returned view result row. This adds significant strain on the storage system if you are under high load or return a lot of rows per request. If you are concerned about this, you can emit the full doc in each row; this will increase view index time and space requirements, but will make view reads optimally fast.

**Comment by daleharvey** [comment]
With us looking to migrate away from map reduce to pouchdb-find I dont think we should spend much effort on some of the more esoteric (and potentially inconsistent) map reduce features
