### ISSUE TITLE
PouchDB no longer syncs with Sync Gateway

### ISSUE THREAD

**Issue by wspringer** [pouchdb/pouchdb#1666]
I had this working for a while, and it was working fine, but at some point it stopped working. I can't tell exactly with which version it happened, but it surely isn't working now. My application works fine with CouchDB, but I need Sync Gateway to prevent different groups from seeing each others data.

While trying to figure out why it no longer works, I noticed that - if I'm using sync gateway - I get an error like the one below, copied from the Chrome debugger:

**Request URL:http://localhost:4000/sync/781EDD37-6ACB-4AAF-A2D9-A78FD02B5D21?revs=true&open_revs=[%222-82e1bd18fc21555cc778a9a2253cb78f%22]&attachments=true&_nonce=JIBQ0zcggauTPdth**
Request Method:GET
Status Code:406 Not Acceptable
Accept:application/json
Accept-Encoding:gzip,deflate,sdch
Accept-Language:en-US,en;q=0.8,nl;q=0.6
Cache-Control:no-cache
Connection:keep-alive
Content-Type:application/json
Cookie:SyncGatewaySession=d45dfff6ba61d5c36ae3a0101929e5dafa212e9e
Host:localhost:4000
Pragma:no-cache
Referer:http://localhost:4000/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36
Query String Parametersview sourceview URL encoded
revs:true
open_revs:["2-82e1bd18fc21555cc778a9a2253cb78f"]
attachments:true
_nonce:JIBQ0zcggauTPdth

**Response**
Connection:keep-alive
Content-Length:59
Content-Type:application/json
Date:Mon, 17 Mar 2014 08:48:25 GMT
Server:nginx/1.0.2
{"error":"Not Acceptable","reason":"Response is multipart"}

I'm using the latest version of PouchDB (on master) and tried both with beta2 and beta3 of Couchbase's Sync Gateway.

**Comment by jchris** [comment]
I think the first thing is to solve multipart, which we are tracking at #2832

**Comment by jchris** [comment]
I rebased some of this to master, but it's not encoding correctly: https://github.com/pouchdb/pouchdb/pull/3384

**Comment by jonniespratley** [comment]
Any update on this?

**Comment by jchris** [comment]
I think we can close it.
http://blog.couchbase.com/first-steps-with-pouchdb--sync-gateway-todomvc-todolite

On Friday, April 24, 2015, Jonnie Spratley <notifications@github.com> wrote:

> Any update on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/1666#issuecomment-96094278>.
>


-- 
Chris Anderson
http://www.couchbase.com
http://twitter.com/jchris
"Compromising before you even begin fighting is illogical." – Joshua Wong

**Comment by nolanlawson** [comment]
Still waiting for a green from Travis, just to make it official: https://travis-ci.org/pouchdb/pouchdb/jobs/59541777 The next release of CSG should make this green, right? :D

**Comment by jchris** [comment]
It should get about twice as green, with a focus on sync not remote-client.
And attachments don't work yet.

On Friday, April 24, 2015, Nolan Lawson <notifications@github.com> wrote:

> Still waiting for a green from Travis, just to make it official:
> https://travis-ci.org/pouchdb/pouchdb/jobs/59541777 The next release of
> CSG should make this green, right? :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/1666#issuecomment-96104369>.
>


-- 
Chris Anderson
http://www.couchbase.com
http://twitter.com/jchris
"Compromising before you even begin fighting is illogical." – Joshua Wong

**Comment by nolanlawson** [comment]
Ah dang, I was hoping you had implemented json support. Well, we definitely still need to get around to multipart support too.

**Comment by daleharvey** [comment]
Green for the first time ever :)

https://travis-ci.org/pouchdb/pouchdb/jobs/70516092

**Comment by jchris** [comment]
There's still plenty of room to increase the coverage.

**Comment by nolanlawson** [comment]
@jchris Those are only the replication tests, sadly. I know attachments especially need a lot of work. I've been slogging through the multipart stuff, but it would be ace if CSG just added `application/json` support for attachments. :)
