### ISSUE TITLE
getAttachment docs and possible enhancement

### ISSUE THREAD

**Issue by ssured** [pouchdb/pouchdb#1689]
I recently played with getAttachment. To my surprise it returned a Blob object, which I had to google for on what to do with that.

What turned out is (at least Chrome) can convert a Blob into a 'regular' URL, demonstrated by http://jsfiddle.net/yy7Zs/26/

- It would be awesome to update the docs and mention this behaviour
- maybe we can add `getAttachmentUrl` as an extra method. For local dbs this will return a `window.URL` generated url, for remote dbs it will return a direct url to the attachment. This way its easy to link up images and other resources, wherever they are stored.

**Comment by daleharvey** [comment]
This is now documented
