### ISSUE TITLE
Diagnose "Document update conflict"?

### ISSUE THREAD

**Issue by jprichardson** [pouchdb/pouchdb#1691]
I'm currently getting the `Document update conflict` error in Chrome (IndexedDB). My first update `put()` (second call to `put()`) works fine. Any subsequent call to `put()` (`> 2` times) fails with that error. 

Yes, the object has both an `_id` and `_rev`. I've also tried calling `put()` like

``` js
db.put(obj, obj._id, obj._rev, callback);
```

as well. But I still get the error. Any advice on how I can diagnose this problem? Thanks in advance.

**Comment by manaetches** [comment]
Thanks a million Nolan, works like magic!

**Comment by DarrylD** [comment]
@nolanlawson solution worked for me, a little messy but works since pouchdb has no better solution

**Comment by Third9** [comment]
Thanks a lot. @nolanlawson It's good~
I solved a problem thanks to you

**Comment by MacGWik** [comment]
Can this solution combine with $q.when ?

Because I've got a problem conflict 409 when Update data *using ionic tutorial from [here](http://gonehybrid.com/how-to-use-pouchdb-sqlite-for-local-storage-in-your-ionic-app/#comment-2676355561)

**Comment by nolanlawson** [comment]
@MacGWik `$q.when()` just wraps a promise, and every PouchDB API returns a promise. so yes, you can just wrap it.

In this case I'd also recommending using the `pouchdb-upsert` plugin, since it does the same thing with less code.

**Comment by Drakonos** [comment]
TypeError: Cannot read property 'size' of undefined
    at binaryMd5 (pouchdb-6.4.3.js:6790)
    at preprocessBlob (pouchdb-6.4.3.js:6857)
    at preprocessAttachment (pouchdb-6.4.3.js:6884)
    at pouchdb-6.4.3.js:6916
    at Array.forEach (<anonymous>)
    at preprocessAttachments (pouchdb-6.4.3.js:6897)
    at idbBulkDocs (pouchdb-6.4.3.js:7390)
    at PouchDB.idb_bulkDocs [as _bulkDocs] (pouchdb-6.4.3.js:8589)
    at PouchDB.<anonymous> (pouchdb-6.4.3.js:5044)
    at PouchDB.<anonymous> (pouchdb-6.4.3.js:2797)

        //create blob with array
	window.kacheln1 = new Blob([kachelnGeRechts], {
		type: 'text/plain;charset=utf-8'
	});

	window.kacheln2 = new Blob([kachelnGeLinks], {
		type: 'text/plain;charset=utf-8'
	});
	db.get(listitem.value).then(function(doc) {
		console.log(doc);
		db.put({
			_id: listitem.value,
			_rev: doc._rev,
			title: listitem.label,
			lmail: phpobj.email, //email adress
			_attachments: {
				'data1.txt': {
					content_type: 'text/plain',
					data1: kacheln1 
				},
				'data1.txt': {
					content_type: 'text/plain',
					data2: kacheln2 
				}
			}

		}).then(function (response) {
			console.log(response);
			console.log("update des Kunden erfolgreich");
		}).
		catch (function (err) {
			console.log('Fehler beim update...');
			console.log(err);
		});
	}).
	catch (function (err) {
		// handle any errors
	});

what is my failure?

**Comment by riyajahamedi** [comment]
You need to put "data" instead of "data1/data2",

'data1.txt': {
				content_type: 'text/plain',
				data: kacheln1 
			}

**Comment by maxdonetsk** [comment]
Hi guys, perhaps some of you could answer this question? Please have a look:
https://stackoverflow.com/questions/55531500/rxdb-document-update-conflict-error-409

**Comment by maxdonetsk** [comment]
Hi guys, perhaps some of you could answer this question? Please have a look:
https://stackoverflow.com/questions/55531500/rxdb-document-update-conflict-error-409
