### ISSUE TITLE
Syncing with CouchDB through Nginx reverse proxy

### ISSUE THREAD

**Issue by wspringer** [pouchdb/pouchdb#1701]
I'm trying to get PouchDB to connect to CouchDB through an Nginx reverse proxy. This is the relevant part of my nginx configuration:

```
        location /db/ {
            rewrite /db/(.*) /$1 break;
            proxy_pass http://127.0.0.1:5984;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Accept "multipart/mixed,application/json;q=0.9";
            proxy_redirect off;
        }
```

If I set up replication, then my changes are getting sent to CouchDB, but I never see the changes from CouchDB. 

Might be related to https://github.com/daleharvey/pouchdb/issues/346 ?

**Comment by lichtamberg** [comment]
Sorry to reopen this old ticket, but I have the same problem and I cannot get it working... 
My setup is as following: 

```conf
  location /couchdb {
    rewrite /couchdb/(.*) /$1 break;
    proxy_pass http://localhost:5984;
    proxy_buffering off;
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
  }
```
As you can see, I serve over /couchdb (and I cannot change it due to legacy systems which rely on it). Is there any option to get it running?

**Comment by nolanlawson** [comment]
Hi @lichtamberg, I've often used setups similar to yours, and similar to the one described in [the CouchDB docs](https://wiki.apache.org/couchdb/Nginx_As_a_Reverse_Proxy). What bug are you seeing?

**Comment by lichtamberg** [comment]
I get all the time following errors - and replication is not starting:

```
..id error Object { status: 0, name: "unknown", message: "getCheckpoint rejected with ", result: Object }

.. id error Object { status: 0, name: "unknown", message: undefined }
```
When I look into the object of the first error, under "results" -> "errors" => there are none... 

Don't know how to continue here? Do you maybe have a hint? thanks!
Btw we are serving /couchdb over https (and is plain http routed internally) - I think this shouldn't be a problem, we have several other services running like this also...?

**Comment by nolanlawson** [comment]
You might want to try asking on the pouchdb-dev mailing list; I’m pretty sure they get this question a lot: https://mail-archives.apache.org/mod_mbox/couchdb-dev/ <https://mail-archives.apache.org/mod_mbox/couchdb-dev/>

**Comment by avijeetnpi** [comment]
@lichtamberg : Did you find any solution as I am facing exact same issue.
