### ISSUE TITLE
API Documentation Improvements

### ISSUE THREAD

**Issue by virgie** [pouchdb/pouchdb#1715]
When I first used PouchDB and went through the API documentation, I thought there were some parts that weren't clear. To get a discussion going on this, here are some of my thoughts/suggestions for improving the API Documentation to make it more beginner-friendly.

1. Each code section should be in the same format, with information presented in this order: code, description, options, notes, example usage. This is mostly followed, but some sections such as "Delete Database" and "Create/Update a Document" show that options can be passed in, but doesn't list or explain any options within the section.
2. The usage of _rev in db.put() is not that clear. I think it should be explained whether _rev can be specified when creating a new doc, and if you can, what the purpose of that is.
3. You can infer how to pass in options by looking at the examples, but I think it would be helpful to explain in the beginning paragraph how to format the options.

**Comment by daleharvey** [comment]
We have seperate issues open for most of these and the rest fixed, cheers
