### ISSUE TITLE
iOS 7 Safari: db.info() method fails

### ISSUE THREAD

**Issue by mattsahr** [pouchdb/pouchdb#1744]
On iOS7 Safari (tested on an iPad) it seems like the PouchDB instance is happening...

    var db= new PouchDB('myDB');

but this method never returns anything...

    db.info(function(err,msg){
        // do something
    }); 

You can make a database.  You can access it (fetch the "adapter" property for instance), and in general the database object is there and available.  But db.info() doesn't work.

Here is a codepen of a basic case.
http://cdpn.io/xFDIt

**Comment by nolanlawson** [comment]
Seems to be an iframe-related issue. Closing.

**Comment by finchen** [comment]
hi. same issue on ios emulator only.
info() was returning the promise but no callback.

setting the size was the issue
```
new PouchDB('db', {adapter: 'websql', size: 100})
```

no sqllite plugin

**Comment by nolanlawson** [comment]
@finchen You can't set the size >50 on iOS.
