### ISSUE TITLE
When "destroy" tests fail, they incorrectly throw a TypeError

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#1772]
lib/adapters/http.js/api.destroy calls api.emit('error', err);

In the tests (e.g. test.basics.js, 'Remove a pouch'), this causes a TypeError because there is no event listener for 'error'. Should there be?

**Comment by daleharvey** [comment]
We have reworked this a lot and havent seen the typeError in a while, closing out but please reopen if still an issue
