### ISSUE TITLE
"too much recursion" in mergeTree

### ISSUE THREAD

**Issue by shimaore** [pouchdb/pouchdb#1786]
More precisely at [line 65](https://github.com/daleharvey/pouchdb/blob/master/lib/merge.js#L65):

        tree1[2].sort();

This is using the git version of PouchDB.

**Comment by nolanlawson** [comment]
@shimaore @tamasmajor Is this still happening in 3.3.1? I'm seeing a lot of people landing on this page from Google, so I'm guessing it's not fixed. But without a live reproducible test case, it's really tough to debug. :(

**Comment by shimaore** [comment]
@nolanlawson no idea :(  I think I had the issue with https://github.com/shimaore/pouchdb-calendar at the time but that project is way out-of-date wrt PouchDB.

**Comment by daleharvey** [comment]
Consolidating on one issue - https://github.com/pouchdb/pouchdb/issues/3225
