### ISSUE TITLE
More progress information in replication

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#1831]
Currently 
```
{ ok: true,
  start_time: Fri Apr 04 2014 18:03:59 GMT+0100 (BST),
  docs_read: 1,
  docs_written: 1,
  doc_write_failures: 0,
  errors: [],
  last_seq: 1 }
```

I think we have more information about how many docs we expect, although not certain

**Comment by jo** [comment]
Do we have the current update seq of the source? This would help in cases where the source seq changes during replication.

**Comment by jo** [comment]
Does PouchDB secretly supports the `update_seq` query param?

> `update_seq` (boolean) – Response includes an update_seq value indicating which sequence id of the database the view reflects. Default is false

**Comment by jo** [comment]
Aha: #2927

**Comment by daleharvey** [comment]
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/4089
