### ISSUE TITLE
figure out what to do about level alt

### ISSUE THREAD

**Issue by calvinmetcalf** [pouchdb/pouchdb#1900]
currently its easy for us to test level alt but its hard for somebody to use it, one option would be to break it out into a separate repo which can grap the parts of pouchdb that it needs and bundle it up into a self contained package to either include in a script tag or include with browserify.

**Comment by daleharvey** [comment]
Between the built versions we release and custom builds nolan is working on, I dont think we have had requests for doing much more than that, so closing out for now
