### ISSUE TITLE
Bigger kangaroo mascot

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#1902]
The new logo is awesome, but it's not immediately obvious that it's a kangaroo.  [This comment on Twitter](https://twitter.com/new_biel/status/451078231542611969) didn't surprise me; my girlfriend asked the same thing.

So I'm wondering: would it make sense to have another, larger kangaroo mascot in the main body of the landing page?  No need to take it out of the header; just a bonus kangaroo mascot in the hero area or something.

Some other JS projects with big mascots for inspiration:

* http://casperjs.org/
* http://emberjs.com/
* http://www.angularjs.org/

**Comment by daleharvey** [comment]
Closing out
