### ISSUE TITLE
circular promises in pouchdb creation

### ISSUE THREAD

**Issue by calvinmetcalf** [pouchdb/pouchdb#1940]
so PouchDB is a db, but also a promise for a db, in other word a PouchDB is a promise for itself, we get around this by remove the then and catch properties form the version of of the db we return through the pouch, but it means that in certain situations PouchDB will be a promise and in other it will not, and that in certain situations can set off circular promise resolution errors in promise resolvers. 

I need to figure out some tests to show the bad behavior and what some possible solutions might be.

The circular promise issue relates to [clause 2.3.1 in the promise spec](http://promisesaplus.com/#point-48) and means as a last resort we could clone the db object before we remove the then and catch method and fulfill the promise with it.

**Comment by denis-sokolov** [comment]
I am unable to use `pouchdb-server` ([full error traceback](https://gist.githubusercontent.com/denis-sokolov/052cfc75077bb4e77095/raw/1abf7fe49dfdd498393278b6ff7b9086e3c0df29/gistfile1.sh)):
```
TypeError: Object [object Promise] has no method 'on'
    at changes (.../node_modules/pouchdb-server/node_modules/express-pouchdb/lib/routes/changes.js:56:35)
```
The file in question uses pouch according to [the documentation](http://pouchdb.com/api.html#changes):
```javascript
req.db.changes(req.query).on('complete', function (complete) {
```

**Comment by calvinmetcalf** [comment]
@marten-de-vries in this example
```js
var PouchDB = require('pouchdb');
var Promise = require('bluebird');
var db = new PouchDB('test');
Promise.resolve().then(function () {
  return db; <-- a promise
}).then(function () { <-- db resolves
  return db; <-- same promise
});
```

since the db is a promise when you return it and then in the resoultion handler re return it you are doing the equivalent of 

```js
db.then(function () {
    return db;
});
```

which is a circular promise breaks the spec, in hind site having the constructor be a promise was a poor choice 

@denis-sokolov you issue is I believe unrelated as since you are able to use the changes method you have access to the correct pouchdb object, you should probably open a new issue

**Comment by denis-sokolov** [comment]
@calvinmetcalf, you are right, this is, indeed, completely unrelated, although looked a tiny bit similar. For future reference, it's now [an issue in `express-pouchdb`](https://github.com/pouchdb/express-pouchdb/issues/202).

**Comment by daleharvey** [comment]
Fix agreed on in https://github.com/pouchdb/pouchdb/issues/4057
