### ISSUE TITLE
"Try PouchDB" interactive REPL on home page

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#1991]
Had a discussion with @nolanlawson on IRC that led to the idea of a tool that shows a representation of a PouchDB database and lets you interact with it through a REPL.

The tool would consist of two parts:
- REPL Input (Something similar to http://try.mongodb.org/)
- Data representation (Something similar to Fauxton)

In the first use case as an aide for debugging you'd see it in your devtools.
This would be similar to when you poke around with resources e.g. Indexeddb

Second use case would be the same tool on a webpage where we can set up scenarios to help learn parts of the API.

One other thing, if you've ever used a tool like phpMyAdmin, it will allow you to change data with the GUI but will show you the command it executed.
Fauxton is almost there with it's API Reference but it'd be great to know exactly what was run, you can see this in the STDOUT when you run couchdb in a shell but it's not visible on Fauxton's UI.

If it would be possible to have Fauxton play a part in this that'd be great but I understand it might be too heavy for something like this.

Really late so this is lots of rambling but wanted to track this as it seems neat, will update later when I've had some sleep.

**Comment by nickcolley** [comment]
I've put together a little prototype of what I'm thinking: http://nickcolley.uk/try/

Let me know what you think.

cc @nolanlawson

**Comment by nolanlawson** [comment]
Dude, this is AMAZING. :dancer: 

One little bug I found: it would be nice if it stringified JavaScript objects (maybe formatted nicely? using `JSON.parse(obj, undefined, '  ')`?)

![screenshot 2015-02-15 18 01 45](https://cloud.githubusercontent.com/assets/283842/6205476/d5fd94b0-b53c-11e4-92a8-b2fb58e4b634.png)

This would be awesome to put in the guide. I would love to replace our `bl.ocks.org` links with this thing.

**Comment by nickcolley** [comment]
Yeah I noticed that. The other thing is that debug doesnt show up either I think they use a different way to call console.log. But it'd be great to be able to output those too conditionally.

I'll work on putting something into the actual site that degrades nicely for people not using javascript etc

**Comment by marten-de-vries** [comment]
On data representation:
- I agree Fauxton is too heavy, mostly because it would need to reload each time a change was made since it doesn't support the concept of listening for changes. As a static admin screen, [it works though](https://ma.rtendevri.es/fauxton).
- As for the ``allDbs()`` problem, the most stable way to handle it in a plug-in I found is using the webkit function and in firefox directly checking the underlying sqlite db: [code](https://github.com/marten-de-vries/pouchdb-fauxton-firefox-addon/blob/master/lib/getIDBDatabaseNames.js). (Although: https://github.com/marten-de-vries/pouchdb-fauxton-firefox-addon/issues/1).

**Comment by nickcolley** [comment]
Let's tackle them both separately for now. The work already done with fauxton is great so It's just the inline examples I think.

We can think about a lighterweight data rep later on :P

**Comment by nolanlawson** [comment]
This would be a great feature for a student project / Rails Girls Summer of Code / etc.
