### ISSUE TITLE
Get rid of cors server

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#2035]
its just messy, and I want to have the tests pick up COUCH_HOST

**Comment by nolanlawson** [comment]
Seems iPhone is the only browser that fails when we try to remove the CORS proxy: https://github.com/pouchdb/pouchdb/pull/4576

**Comment by daleharvey** [comment]
FINALLY - https://github.com/pouchdb/pouchdb/commit/2f7b57baca50e893a61c33f7de15835796f083a6

**Comment by nickcolley** [comment]
Epic work 👍 🎆🎇🎉🎊
