### ISSUE TITLE
Better way to configure adapters, and adapter plugins

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2049]
What I want is:

```html
<script src="pouchdb-nightly.js"></script>
<script>
  console.log(PouchDB.adapters); // http, https, idb, websql
</script>
<script src="pouchdb.memdown.js"></script>
<script>
  console.log(PouchDB.adapters); // http, https, idb, websql, memdown
</script>
```
Then, since we can potentially have tons of backends here, I want a better way to specify the `preferredAdapters` and HTTP fallbacks:

```js
var pouch = new PouchDB('foo', {
  preferredAdapters: ['websql', 'idb', 'localstorage'],
  fallback: 'http://mysite:5984/mydb'
});
```

**Comment by daleharvey** [comment]
@nolanlawson do you still think we should be doing this, I think custom adapters are primarily for either our testing use case or for specific setups (ie ios), especially as we can potentially be moving to using idb in webkit I think things like this are less needed / we can close this out, but if you really want it still can do so

**Comment by nolanlawson** [comment]
No, I think `PouchDB.preferredAdapters` should be an implementation detail. The new plugin API handles this very elegantly and users never need to explicitly mess with `PouchDB.preferredAdapters`.
