### ISSUE TITLE
level alt

### ISSUE THREAD

**Issue by calvinmetcalf** [pouchdb/pouchdb#2058]
ok different idea for making it, maybe what we could do is have the lever alt build copy over the lib folder from main pouchdb and then have the level alt index be

```js
var PouchDB = require('../lib');
PouchDB.adadpter('foo', require('./levelAlt');
module.exports = Pouchdb;
```

**Comment by daleharvey** [comment]
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/1900
