### ISSUE TITLE
404's and replicate complete event

### ISSUE THREAD

**Issue by astutesoftware** [pouchdb/pouchdb#2081]
When i do a remote to local replication my complete event fires before the data is updated to my local db.
I verified this by checking on the local db from another tab.
Here is what happens
1. replication starts
2. for each db the onchange and complete get called.
3. for each db a 404 is generated. This url however exists when you copy and open it in a browser.
format is GET http://xx.xx.xx.xx:5984/db-name/_local/bb3243737a5851fe646cfe8990cb2763?_nonce=0zRcCqIwSoe7KZwR 404 (Object Not Found) 
4. the db with maximum deletions/revisions seems to be the one to get the 404 last.
5. only when the 404's are done calling does the data appear in the local db.

What i have been trying to show the end user a screen saying "Hold on while we sync your data" and hide the screen when sync is finished.
In this case however if i go with the complete event the data has not quite arrived yet.

On a database with 40 revisions and 12 records. The completion event fires in approximately 2 seconds and the 404 finishes about 1 minute later on chrome.

I have tried using the cache:false and ajax false options as well.

**Comment by daleharvey** [comment]
Sweet, looks like issue was resolved, please reopen or file a new bug if there is anything else, thanks
