### ISSUE TITLE
Replication from Cloudant cause auth popup with Pouch 2.2.0 

### ISSUE THREAD

**Issue by ermouth** [pouchdb/pouchdb#2121]
Continuous replication from https://cloudwall.cloudant.com/cwmanual opens browser blocking auth modal when starts. Cancel helps and replication continues. 1.2, 1.4, 2.1 show no popup with this DB.

Pouch 2.2 tries to GET https://cloudwall.cloudant.com/?_nonce=... that need authorization.

**Comment by daleharvey** [comment]
Cloudant fixed the nonce issue at the least of these, can open a new issue for the path thing
