### ISSUE TITLE
Test in Android 4.4

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2154]

**Comment by daleharvey** [comment]
Gonna start with 4.4

**Comment by daleharvey** [comment]
Ok, working in 5.1, in 4.4 it times out almost immediately, fairly certain PouchDB itself is fine but installing the emulator now to be sure

**Comment by nolanlawson** [comment]
In emulators, I've always been able to get 100% green runs all the way back to 4.0.3. Saucelabs has been another story entirely.

**Comment by daleharvey** [comment]
Had multiple shots at getting this working in sauce and havent been able, with 4.4 starting to slowly decrease and >= 5 getting > 50% I think unless anyone has an incoming patch we dont need to track this

**Comment by nolanlawson** [comment]
I managed to test 4.4's WebView in Sauce for node-websql, but the emulator is very slow and flaky. I don't recommend it.
