### ISSUE TITLE
Investigate IDB corruption

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2157]
@ig3 mentioned [this](https://github.com/pouchdb/pouchdb/pull/2145#issuecomment-42228754) and I've also seen it [reported by users](http://stackoverflow.com/q/23443242/680742). I've seen it myself several times, and if I recall correctly, it's only ever been in IDB.  Typically I see it in Firefox.

Obviously we can never be as bulletproof as CouchDB, since we're beholden to the underlying database, but maybe there's a way we can try to reproduce corruption and either 1) report the bug to Mozilla devs, or 2) recover from it on our end.

**Comment by daleharvey** [comment]
So theres very little details to diagnose and > 7 months ago, closing out
