### ISSUE TITLE
levelalt valid function is invalid

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb#2159]
Scenario: 
1. Build pouchdb-localstorage-down.js
2. Run in JavaFX 8.0 WebView

Expected Result:
levelalt adapter is registered

Actual Result:
levelalt adapter is not registered

Reason for Bug:
```Java
LevelPouchAlt.valid = function () {
  return LevelPouch.valid();
};
```
Which then leads us to:
```Java
LevelPouch.valid = function () {
  return (process && !process.browser) || indexDB.valid();
};
```
Which makes no sense in JavaFX 8.0 WebView because we are in a browser (so the first part of the or will be FALSE) and there is no indexDB.

We need a different test.

BTW, for what it's worth I actually ran the test [here](https://github.com/no9/localstorage-down) in JavaFX 8.0 WebView and that test did pass. So localstorage-down does appear to work in JavaFX 8.0 WebView.

But the current valid test doesn't.

**Comment by daleharvey** [comment]
So leveldown pouch now does a simple `return true`, since there isnt a valid test in the abstract leveldown spec this is the best we can do really, its going to be up to the user to load the platform support correctly
