### ISSUE TITLE
Too high recursion error in firefox and safari windows

### ISSUE THREAD

**Issue by trokster** [pouchdb/pouchdb#2199]
Hi,

I've encountered this error upon replicating a high rev doc ( around 300 revs ): it gets stuck at tree1[2].sort(). I've seen this issue pop up a few times in the issues forum so I figured I'd try replacing native sort with a custom non recursive one.

( firefox 29, ubuntu. windows safari 5.1.7 )

It worked for firefox. Not sure how to validate solution.

Below is used alternate sort, copied from a gist I can't alas locate anymore:

function qsort(a, l, r) {
  // a: array to sort
  // l, r: optional array index array range

  // i: stack index, s: stack,
  // p: pivot index, v: pivot value,
  // t: temporary array item,
  // x, y: partion low/high

  var i, s, p, v, t, x, y;

  l = l || 0;
  r = r || a.length - 1;

  i = 2;
  s = [l, r];

  while (i > 0) {
    r = s[--i];
    l = s[--i];

    if (l < r) {
      // partition

      x = l;
      y = r - 1;

      p = l;
      v = a[p];
      a[p] = a[r];

      while (true) {
        while (
          x <= y &&
          a[x] != undefined &&
          (""+a[x]) < (""+v) )
          x++;
        while (
          x <= y &&
          a[y] != undefined &&
          (""+a[y]) >= (""+v))
          y--;
        if (x > y)
          break;
        t = a[x];
        a[x] = a[y];
        a[y] = t;
      }

      a[r] = a[x];
      a[x] = v;

      // end

      s[i++] = l;
      s[i++] = x - 1;
      s[i++] = x + 1;
      s[i++] = r;
    }
  }
}

my two cents.

**Comment by daleharvey** [comment]
Consolidating on one issue, we have mostly fixed these but want to keep one open https://github.com/pouchdb/pouchdb/issues/3225
