### ISSUE TITLE
Get document with changes for replication 

### ISSUE THREAD

**Issue by calvinmetcalf** [pouchdb/pouchdb#2212]
Nolans excellent Browser np demo really underscored how http connections take much longer then http transfers especially with cors. 

E.g. Getting a 5k file and then half the time Getting another 10k one is going to be slower then alway getting a 15k one. 

WWould it make sense to modify the replication algorithm to do changes with docs and attachments instead of fetching then separately?

**Comment by daleharvey** [comment]
We currently always fetch with attachments right now, needs improving but this isnt valid anymore
