### ISSUE TITLE
Filtered replication using a CouchDB view?

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2232]
Currently, if you want to do filtered replication from HTTP to Pouch, it doesn't scale well because the filter function has to run over every single document.  E.g. imagine you have a single database with hundreds of thousands of users.

Ideally you'd replicate from a stored view, and apparently this is going to be included in the rcouch merge.

I think, though, that we could do this ourselves.  Instead of fetching from allDocs for the generation 1 documents, we can just fetch from the view.  After that, the steps would have to be:

- fetch the view again
- check to see if any revs changed
- get the new revs

I think there are a lot of other steps in there that I missed, but in principle, I don't think there's any reason we couldn't do this.

**Comment by daleharvey** [comment]
Given our general shift is away from map / reduce, closing out any older feature requests on it for now
