### ISSUE TITLE
Replication of design docs

### ISSUE THREAD

**Issue by gpurgal** [pouchdb/pouchdb#2268]
Replication of a database with design docs is aborted with 'target.bulkDocs failed to write docs' error when replicating to CouchDB as non admin.
Creating design docs on CouchDB is restricted to admin users and AFAIK CouchDB does not replicate them when admin credentials are not included in the replication request.
Is there a way to omit replication of design docs other than filters? It's quite cumbersome to create such filter on every DB.

**Comment by stuartpb** [comment]
So, if we're replicating to a CouchDB instance with an account with admin privileges, we need to explicitly specify a `filter` function to filter out the design docs (such as `doc => doc._id[0] != '_'`)?

**Comment by nolanlawson** [comment]
Yes. Unfortunately this is a design decision (no pun intended) that we inherited from CouchDB.

**Comment by stuartpb** [comment]
What if (and this is a proposal that would apply to CouchDB) docs could have a `_local: true` that would suppress them from replication (but not eliminate them from the things the `_local/` ID prefix does, like `_all_docs` and views, unless they're already there by way of being a doc like `_security`)?
