### ISSUE TITLE
Add cdnjs link on PouchDB docs

### ISSUE THREAD

**Issue by indolering** [pouchdb/pouchdb#2307]
[pouchdb.com/learn.html](http://pouchdb.com/learn.html) does not list [cdnjs](http://cdnjs.com/libraries/pouchdb) as an option for using PouchDB.

**Comment by narainaDewasi** [comment]
hi @nolanlawson i am using pouchdb adapter indexeddb as like this
<script src="https://cdn.jsdelivr.net/npm/pouchdb@8.0.1/dist/pouchdb.indexeddb.min.js" defer></script>

is it right
its working on localhost but not on hosted site. showing some version problem
