### ISSUE TITLE
best practice for add or update, then continue?

### ISSUE THREAD

**Issue by judell** [pouchdb/pouchdb#2323]
My inclination was to do something like this:

``` javascript
    function postDoc ( db, doc ) {

        db.get ( doc._id )

        .then( function (err,resp) {
            if ( ! err )
                doc._rev = resp._rev;
            return db.post( doc );
        })

        .then(function(info){
            console.log("id of record: " + info.id);
            showDocs();
        })
    }
```

But when doc._id is 404 it's an error. That led me to:

``` javascript
    function postDoc ( db, doc ) {

        console.log ('try adding');

        db.post ( doc )

        .catch( function (error) {
            console.log(error);
            return db.get( doc._id );
        })

        .then ( function(_doc) {
            console.log('updating');
            doc._rev = _doc._rev;
            return db.post( doc );
        })

        .then(function(info){
            console.log("id of record: " + info.id);
            showDocs();
        })
    }
```

Which is lame in several ways. I know it's a philosophical question as to whether a 404 or 409 should trigger exception handling or not, in PouchDB's current Promise implementation they do, fair enough, but what's the recommendation for a clean way to write a method that adds or updates, then continues?

**Comment by cAstraea** [comment]
Can someone expand more on this subject please ? I feel like I'm not understanding this paradigm at all ....  I have a document with the id "balance" 
First time I run put all is good and the data is updated(inserted??) 
```
		var doc = {
    "_id": "balance",
		"amount": rewardI,
		"ts": new Date().toISOString()  
};
db.put(doc).then(function (response) {
  // handle response
  console.log("everything is 大丈夫");
  console.log(response);
}).catch(function (err) {
  console.log(err);
});
```
Why can't I update it the second time with new amount ???????????? 
I'm getting n {status: 409, name: "conflict", message: "Document update conflict", error: true, id: "balance", …}
