### ISSUE TITLE
put() has inconsistent arguments

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2344]
As reported [by Lukas Rieder](https://groups.google.com/forum/#!topic/pouchdb/pQUq-nOBPhQ):

>If I may, I've come across another potential problem: It seems to me that `db.put()` does not handle its arguments in a safe way. Let's consider the following:
>
>var doc = { _id: 'some-id', foo: 'bar' };
>var rev = 'some-rev'  // this was obtained by a get() somewhere
>db.put(doc, doc._id, rev);
>
>Apparently, PouchDB sees the `_id` in the document and hence does not look for it in the argument. It then considers `some-id` the revision, which fails, of course. Leaving out the second parameter works, but seems very fragile.

**Comment by daleharvey** [comment]
Closing as dupe https://github.com/pouchdb/pouchdb/issues/5154
