### ISSUE TITLE
Date/string conversion in websql adapter

### ISSUE THREAD

**Issue by yoorek** [pouchdb/pouchdb#2351]
When using websql adapter there is conversion from Date to string during save/read which is not issue for idb adapter. This code returns same result before and after save to database for IDB but different results for WEBSQL:

```
var obj = {}, db = new PouchDB('test', {adapter:'websql'});
obj.date = new Date();
console.log('Before put:', obj.date);

db.post(obj)
    .then(function (result) {
        return db.get(result.id);
    })
    .then(function (record) {
        console.log('After get:', record.date);
    });
```

Fiddle: http://jsfiddle.net/yoorek/v5fcw/

I can convert string to Date manually (and i do) but I think it's PouchDB job - What I Save Is What I Get

**Comment by arpitaggarwal** [comment]
@nolanlawson can we have overloaded implementation of `put` operation which save `Date` object instead of `String` in `IndexedDB` as it supports saving `Date` objects?

**Comment by arpitaggarwal** [comment]
@nolanlawson can we have overloaded implementation of put operation which save Date object instead of String in IndexedDB as it supports saving Date objects?

**Comment by garrensmith** [comment]
I think that is something you need to do in your app. You can overload the put yourself.

All misspelling thanks to my iPhone.
________________________________
