### ISSUE TITLE
Sync multiple attachments with couchdb 1.5.1 (412 Precondition Failed)

### ISSUE THREAD

**Issue by natcohen** [pouchdb/pouchdb#2358]
This issue has been noticed with pouchdb 2.2.3 and couchdb 1.5.1 (configured as mentioned in pouchdb documentation).

When adding multiple attachments to a same doc, when syncing with couchdb, I get the following: POST http://127.0.0.1:5984/clients/_bulk_docs 412 (Precondition Failed)
Response error: {"error":"missing_stub","reason":"id:FF72016D-EB39-139C-ABF6-C14B45AEB950, name:c=89809809?d=0123/bootstrap.css"}

I've added 4 files (jpeg, css and txt files) It is very strange because this id has a stub set to true.

**Comment by MWakas** [comment]
Hi @nolanlawson ,
I am facing the same issue on my side.I am using couch db 1.6.1 and facing the same error 412.I am working on Backbone.js and using couchdb.I have a doc with a lot of attachments,i am getting it through jquery ajax calls,doing some changes and when I tried to update it,the above error appears saying:
412,missing stub etc.
Can you please guide me how can I fix it.Your kind response will be very helpful.Thanks.

**Comment by nolanlawson** [comment]
@MWakas Attachments can go missing for a number of reasons, but most likely it's due to compaction. If this is happening because of the replicator, then that is definitely a bug in the replicator, but I'm not sure how that could happen, since the replicator ignores atts_since and replicates everything. Please provide a reproducible test case and we can see what we can do. :)

**Comment by MWakas** [comment]
Hi @nolanlawson thanks a lot for your kind response.I have the following initial use-case(#1) which was not working properly and then I tried another use-case(#2) in which I faced the above mentioned problem.
Use-Case#1:
                   I have 2 couch db's, one is at local machine(lets say "localApps") and other is at server(lets call it "serverApps"). There is a design_doc in "serverApps" db with a lot of attachments.When I did replication for the first time,this doc successfully copied/replicated to "localApps" db.Now suppose I added some fields and did some changes in the design_doc's attachments at the "serverApps" level and I want to get those changes to my local db through replication.But when I did replication it didn't copied those changes from "serverApps" to "localApps".I did read the ajax's response and it was saying: docs_read = 1, docs_write = 1; no_changes = true etc. I tried again and again but in vain.Is there any way to force the couchDB that whether there are changes in the doc or not,just replace the localApps's doc with the serverApps's doc.I am doing replication through jquery-ajax calls.

When the use-case#1 failed again and again.I tried the following use case of which I asked a question in this article.
Use-Case#2:
                    Instead of replication(because it was not working properly as mentioned in Use-Case#1) I tried to update the design_doc of "localApps" db.I first get the design_docs of both the db's and replaced the attachments of the localApps_design_doc with the attachmetns of serverApps_design_doc like following.
localApps-design_doc.attachments = serverApps-design_doc.attachments.
I did check the attachments of the localApps-design_doc in the debugger,they were successfully replaced.Also the id and rev# were fine but when I did PUT request to update,it goes to error function of the ajax-call and was saying 412,missing stub etc.Here is the code I am using.

var nationInfo = that.getNationInfo(); //This function returns the info's about nation.
var nationName = nationInfo["nationName"];
var nationURL = nationInfo["nationURL"];
$.ajax({
    url: 'http://' + nationName + ':oleoleole@' + nationURL + '/apps/_design/bell',
    type: 'GET',
    dataType: 'jsonp',
    success: function(result) {
        var nationDesignDoc = result;
        console.log(nationDesignDoc);
        $.ajax({
            url: '/apps/_design/bell',
            type: 'GET',
            dataType: 'json',
            success: function(appsResult) {
                var CommDesignDoc = appsResult;
                console.log(CommDesignDoc);
                CommDesignDoc._attachments = nationDesignDoc._attachments;
                //412 error occurs in the following PUT request.
                $.ajax({
                    type: 'PUT',
                    url: '/apps/' + CommDesignDoc._id + '/?rev=' + CommDesignDoc._rev,
                    data: JSON.stringify(CommDesignDoc),
                    async: false,
                    dataType: 'json',
                    success: function(response) {
                        console.log(response);
                    },
                    error: function(status) {
                        console.log(status); // It comes here mentioning the 412 error.
                    }
                });
            },
            error: function(err) {
                console.log(err);
            }
        });
    },
    error: function(error) {
        console.log(error);
    }
});

And here is the screenshot of the error: 
![412](https://cloud.githubusercontent.com/assets/10882476/11331679/a195a818-91df-11e5-9b08-0b70fc7a4e95.png)

Please give your thoughts on above issues.If you get some suggestions or alternative ways please tell me.thanks a lot.
