### ISSUE TITLE
Replication fails to emit useful error

### ISSUE THREAD

**Issue by nslater** [pouchdb/pouchdb#2377]
I'm replicating from a remote CouchDB database into PouchDB 2.2.3. This is my code:

```
print_error = (e) ->
  console.log "error", JSON.stringify e
  console.log e.stack
  console.log e.message
  console.log e.name
  true

db.replicate.from(address, {live: true})
  .on("error", print_error)
```

The `error` event fires, but the error message is very unhelpful. There is a delay of either 10 seconds, or (much less frequently) about 20 or 30 seconds, before the error event fires. The 10 second error has the JSON rendering `{}`; `e.stack` and `e.message` are undefined; and `e.name` is the string `"unknown_error"`.

The 30 second error has the following JSON rendering:

```
{"message":"batch processing terminated with error",
 "result":{"ok":false,"start_time":"2014-06-09T15:28:40.980Z",
           "docs_read":0,"docs_written":0,"doc_write_failures":0,
           "errors":[],"status":"aborted",
           "end_time":"2014-06-09T15:29:01.068Z","last_seq":0}}
```

In Issue #2295 I made a similar comment whilst debugging a similar issue. That turned out to be a bad CORS set up in CouchDB, and it was @calvinmetcalf who figured that out.

This time, CORS is set up correctly. Calvin also said, "if there is a leveldb error we will often just pass it strait up to you, leveldb has an annoying habit of passing empty objects as errors". It seems that this is happening again, at least in the 10 second case. The 30 second case is obviously more verbose, but still doesn't really provide enough information to be able to debug any further.

Do you have any idea why there's a timeout of (exactly) 10 seconds? And why sometimes this is longer, being around 20 or 30 seconds? (I haven't timed the longer one because it happens too infrequently.)

**Comment by daleharvey** [comment]
I am fairly certain that ghost instances of Pouch would be related to the lifetime of the extension, pouchdb doesnt do anything on startup, cancelling replication is well tested and we havent seen any othe reports

As for the error we have recently improved the CORS and various errors so hopefully they are instructive now, closing this out but please open another issue if you still see anything
