### ISSUE TITLE
Get tests passing in FirefoxOS

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2400]
Surprisingly they're not (at least on the FXOS 1.30 simulator).

**Comment by daleharvey** [comment]
<img width="316" alt="screen shot 2015-07-18 at 15 02 10" src="https://cloud.githubusercontent.com/assets/37787/8761674/0237e974-2d5e-11e5-9172-ee6d5a4fa17c.png">

Firefox OS uses identical gecko to firefox so I dont think we need to add this to automation, Firefox should catch any indexeddb bugs we have on firefox os

**Comment by nolanlawson** [comment]
Nice!
