### ISSUE TITLE
Canceling live replication causes "Possibly unhandled TypeError" when listening for uptodate event

### ISSUE THREAD

**Issue by jaabio** [pouchdb/pouchdb#2408]
hi,

while using pouchdb, i found that I'd get the following in console output when i:
 
start live replication, 
attach an `uptodate` event listener to the replication event emitter, 
then cancel replication.

Possibly unhandled TypeError: listener must be a function
&nbsp;&nbsp;&nbsp;at TypeError (<anonymous>)
&nbsp;&nbsp;&nbsp;at Replication.EventEmitter.removeListener (events.js:195:11)
&nbsp;&nbsp;&nbsp;...

i was able to stop the error by editing 
https://github.com/pouchdb/pouchdb/blob/2.3-release/lib/sync.js#L88-L102
like so (adding a check to make sure the listener is in fact still attached after removing it from `self.pull` but before removing it from `self.push`):

````
this.on('removeListener', function (event) {
    if (event === 'change') {
      self.pull.removeListener('change', pullChange);
      self.push.removeListener('change', pushChange);
    } else if (event === 'cancel') {
      self.pull.removeListener('cancel', onCancel);
      self.push.removeListener('cancel', onCancel);
    } else if (event in listeners) {
      if (typeof listeners[event] === 'function') {
        self.pull.removeListener(event, listeners[event]);
        if (typeof listeners[event] === 'function') {
            self.push.removeListener(event, listeners[event]);
        }
        delete listeners[event];
      }
    }
  });
````

i'm not familiar enough with pouchdb code to be confident this is a great solution.  nevertheless i hope it helps to clarify the issue and points in the direction of whatever the best fix might be.

**Comment by daleharvey** [comment]
`uptodate` is deleted - https://github.com/pouchdb/pouchdb/commit/937ef1f68c84e938ce470c8d03966aa917420587
