### ISSUE TITLE
Feature request: support for Cloudant Query

### ISSUE THREAD

**Issue by colinskow** [pouchdb/pouchdb#2422]
Cloudant just introduced an awesome new query system very similar to MongoDB. It would be very nice to also have this functionality build into a PouchDB plugin.

https://docs.cloudant.com/api/cloudant-query.html

**Comment by slawo** [comment]
this would be ++good

**Comment by nolanlawson** [comment]
Progress is being made: https://github.com/nolanlawson/pouchdb-indexes

**Comment by nickcolley** [comment]
:balloon: so excite

**Comment by nolanlawson** [comment]
pouchdb-find 0.1.0 is out: https://github.com/nolanlawson/pouchdb-find

**Comment by nickcolley** [comment]
Looking sweeet!

**Comment by colinskow** [comment]
It's a late Christmas present!!! Thanks Nolan, can't wait to play with it.

**Comment by daleharvey** [comment]
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/3538, it works, we can start the discussion about it being in core :)
