### ISSUE TITLE
Checkpointer shouldn't assume _changes ordering by seq

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2423]
As pointed out by @rnewson in #2404:

> If you are also concerned about when to checkpoint (if that's a thing in pouchdb even) then do so whenever you have processed N rows, rather than, as CouchDB does today, waiting for an update_seq to be => a previous value. That obviously requires the values to be numbers.

Currently the checkpointer does seem to assume that the `_changes` feed is always ordered by seq, which is probably part of the reason our tests are failing against Cloudant.

**Comment by daleharvey** [comment]
We just checkpoint at the end of a batch, and tests are working grand against couch master now

**Comment by rnewson** [comment]
nice.
