### ISSUE TITLE
Replication - when doc_ids is defined the changes feed is dependent on batch_size

### ISSUE THREAD

**Issue by jdelibas** [pouchdb/pouchdb#2426]
If a couchDB database has more than 100 documents and the specified ids in doc_ids exists beyond those first 100 then the documents specified will not replicate since the changes feed with only check up until the amount specified by the batch_size which defaults to 100.

So assuming couchDB database with 
```500 documents ```
and IDs as 
```001,002,003,....498.499,500 ```

```javascript
var db = new PouchDB('objects');
db.sync('http://couchdb:5984', {doc_ids : ['101','201','301']})
      .on('change', function (info) {
        console.log(info);
      }).on('uptodate', function (info) {
        console.log(info);
      }).on('complete', function (info) {  
        console.log(info);
      }).on('error', function (err) {
        console.log(err);
      });
```
This will not replicate any documents.

Unless batch_size is defined as the total size of the database it will only check the first 100. 

```javascript
db.sync('http://couchdb:5984', {batch_size : 500, doc_ids : ['101','201','301']})
```
This will replicate all three documents with the IDs ``` '101','201','301'.```

I think this is a fairly specific use case and this might be intentional because of that.

**Comment by daleharvey** [comment]
So I figured this behaviour has likely changed over 2 years, it looks to be working now and added a test to verify @ https://github.com/pouchdb/pouchdb/pull/5254

**Comment by daleharvey** [comment]
https://github.com/pouchdb/pouchdb/commit/07a7bca9611a45683ee99e49ea62f583cfa91364
