### ISSUE TITLE
Add 'dependentDbRegistered' event

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2438]
This is the only real way to fix https://github.com/nolanlawson/pouchdb-all-dbs/issues/2. I tried fixing it with the existing PouchDB events system, but it's not sufficient because I have to manually create a new database just to read from the local `dependentDbs` document, which sends us into an infinite loop because the `created` event keeps firing.

Ideally this event should fire before the dependent DB is created.

**Comment by daleharvey** [comment]
We have this now, although we are gonna try removing it
