### ISSUE TITLE
Calls to `info()` can break task queue

### ISSUE THREAD

**Issue by colinskow** [pouchdb/pouchdb#2454]
If I create a new DB on Cloudant, initiate replication, and then immediately poll for info, it generates a weird error.

```javascript
var PouchDB = require('pouchdb');

var remoteURL = 'https://user:pass@user.cloudant.com/pouchtest',
    remote = new PouchDB(remoteURL),
    local = new PouchDB('pouchtest', {'db': require('memdown')}),
    replicator = local.replicate.from(remoteURL, {live: true});

remote.info()
  .then(function(results) {
    console.log(results);
  })
  .catch(function(err) {
    console.log(err);
  })
  .then(function() {
    replicator.cancel();
    remote.destroy();
  });
```
About 30% of the time rejects with:
```
{ message: 'conflict', name: 'error', status: 500 }
```
Creating a new remote DB in Pouch is a synchronous call, yet obviously it requires a round-trip to the server and a certain amount of time to complete. Is it possible that the DB hasn't finished creating when it makes the info call?

I tested on a local instance of CouchDB and didn't have this problem. Perhaps creating a new remote DB should be asynchronous so I can wait until it is done before moving on.

**Comment by daleharvey** [comment]
So I created a test and its fully green, this is either fixed or an issue elsewhere, please reopen / file a new bug if you still see any issues, cheers

https://github.com/pouchdb/pouchdb/commit/ed6ee721cde154e168bce420e803fd155eecc676
