### ISSUE TITLE
Uncaught TypeError: Cannot read property 'seq' of undefined 

### ISSUE THREAD

**Issue by joanrocagas** [pouchdb/pouchdb#2456]
Hi, I'm getting this error in Chrome:
Uncaught TypeError: Cannot read property 'seq' of undefined   (pouchdb-nightly.js 2558)

```
var metadata = event.target.result;
```
metadata is undefined

My query is
```
self.db.query(function(doc) {
  if (doc) {
    emit(doc._id);
  }
}, {'reduce': false}, function(error, response) {
  $log.info('query');
  $log.info(error);
  $log.info(response);
});
```

**Comment by ArnaudValensi** [comment]
Hi,
I get the error in pouchdb v3.5.0 using it on an android phone with sqlite.
Actually it is on an app which is in production and I don't have many clue to be able to fix this error. Maybe someone can explain me what code in pouchdb is causing this error to help me in my investigations.

**Comment by nolanlawson** [comment]
@ArnaudValensi If you could offer a working test case (e.g. a sample app), that would be helpful. This issue describes an IndexedDB bug, so if it's occurring for you with the SQLite Plugin, then maybe you aren't actually using the SQLite Plugin? You can check by doing `db.info().then(console.log.bind(console))`

**Comment by ArnaudValensi** [comment]
@nolanlawson

From the log of the a user of my app which have the probleme.
```
info: 
Object
auto_compaction: false
db_name: "msgs"
doc_count: 217
sqlite_plugin: true
update_seq: 221
websql_encoding: "UTF-8"
__proto__: Object
```

In my code, I get some documents one by one using `get`, I change a field in it, before re-insert them one by one using `put`. I'm sorry, I don't have sample app because I don't know how to reproduce it happening sometime time to some of my users. 

I'm trying to reproduce but I don't know if I will be able to do it.

**Comment by nolanlawson** [comment]
@ArnaudValensi Could you try not using the SQLite Plugin? It's had some bugs recently and has not been passing the PouchDB test suite.

**Comment by ArnaudValensi** [comment]
@nolanlawson Yes I'll do that, thank you.

**Comment by ArnaudValensi** [comment]
@nolanlawson I don't know I to reproduce the problem but I got it again, I have some more log:
```
{"status":500,"name":"Error","message":"unknown"} 

error: true
message: "unknown"
name: "Error"
reason: "a statement with no error handler failed: [5] DB[31] prepare() SELECT sql FROM sqlite_master WHERE tbl_name = 'metadata-store' [database is locked]"
status: 500
```

I'm posting this just in case it can help you.
I will try with `androidDatabaseImplementation`

**Comment by daleharvey** [comment]
Recent occurence is a sepeate websql bug, looks like this on is indeed fixed
