### ISSUE TITLE
Conflict when using 2 tabs in the same browser

### ISSUE THREAD

**Issue by redgeoff** [pouchdb/pouchdb#2493]
I've been having a lot of fun playing around with pouchdb and really appreciate all the hard work that everyone has put into this project! I have however found what I think is a bug:

**Steps to replicate:**

NOTE: You must run the page via a web server to reproduce the problem.

1) Create bug.html:
````html
<html>
<body>
<script src="pouchdb.js"></script>
<script>
  var todo = null;
  var db = new PouchDB('todos');
  var remoteCouch = 'http://user:password@127.0.0.1:5984/todos';

  db.info(function(err, info) {
    db.changes({
      since: info.update_seq,
      live: true
    });
  });

  db.allDocs({include_docs: true, descending: true}, function(err, doc) {
    if (doc.rows.length == 0) {
      db.post({title: 'clean dishes'});
    } else {
      todo = doc.rows[0].doc;
    }
  });

  var opts = {live: true};
  db.replicate.to(remoteCouch, opts);
  db.replicate.from(remoteCouch, opts);

  function edit() {
    todo.title = 'take out trash at ' + (new Date()).toUTCString();
    console.log(todo);
    
    db.put(todo);

    // This doesn't solve the problem either
    // db.put(todo).then(function(response) {
    //   todo._rev = response.rev;
    // });
  }
</script>
<button onclick="edit()">Edit</button>
</body>
</html>
````

2) Visit the page the 1st time via a browser to complete the setup

3) In the first tab, visit bug.html

4) In the second tab, visit bug.html

5) In the first tab, click _Edit_

6) In either the console log for the first tab or the second tab you will see something like the following:
> PUT http://127.0.0.1:5984/todos/_local/0fad5c7ee13901e563fc0baa5925af28 409 (Conflict) pouchdb.js:4703
ajax pouchdb.js:4703
ajax pouchdb.js:880
(anonymous function) pouchdb.js:1246
(anonymous function) pouchdb.js:6906
(anonymous function) pouchdb.js:6783
(anonymous function) pouchdb.js:6906
(anonymous function) pouchdb.js:6745
(anonymous function) pouchdb.js:6732
(anonymous function) pouchdb.js:6906
(anonymous function) pouchdb.js:5421

You can repeat the test by starting over from step 3, but you need to refresh the pages in both tabs first.

This issue only appears to occur when you try it within two tabs in the same browser. If you repeat the process with two browsers, the conflict doesn't occur. Furthermore, if you repeat the process and instead serve the pages straight from the local filesystem e.g. file://bug.html then the conflict doesn't occur. My guess is that there is a problem with sharing the same IndexDB database instance between both tabs.
It's worth noting that it appears that the update is working even though the console reports an error.

This issue occurs with pouchdb version 2.2.3 and the latest code on github.

Any thoughts?

**Comment by daleharvey** [comment]
Closing, theres various issues here, the checkpoint ones should mostly be fixed by using couchdb style replication and the final solution would be https://github.com/pouchdb/pouchdb/issues/1852,
