### ISSUE TITLE
Edit adapters page to add new 100℅ passing projects

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2504]
SQLite Plugin on Android is passing; on iOS it just needs one more PR which should be merged in a week or two.

*DOWN modules known to pass:

* MEMDown
* SQLdown
* RiakDOWN
* RedisDOWN

**Comment by nickcolley** [comment]
Does this still need doing?

**Comment by nolanlawson** [comment]
No, I think we should not say they are officially supported, because we don't test them in Travis. Even if they pass now, they might not pass later. MemDOWN we can be sure of.
