### ISSUE TITLE
Support for update handlers/partial updates

### ISSUE THREAD

**Issue by redgeoff** [pouchdb/pouchdb#2510]
I quickly browsed the source and couldn't find a way to support [update handlers](http://wiki.apache.org/couchdb/Document_Update_Handlers) for [partial updates](http://wiki.apache.org/couchdb/Partial_Updates). My goal is to build a collaborative app that allows simultaneous editing of different attributes in the same document, e.g. one user modifies the values of a task and another user simultaneously changes the ordering of the tasks.

Is there another way to accomplish this with pouchdb? If not, can I help to add update handler support to pouchdb?

**Comment by daleharvey** [comment]
I think this is solved via the plugin approach, cheers :)
