### ISSUE TITLE
Add option to set withCredentials = false for ajax requests

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2513]
In `ajax-browser.js` we're setting `withCredentials` to be true every time. We need some way to programmatically set this, although TBH I have no idea how.

Without this feature, we won't be able to set up the npm-browser to replicate from skimdb.npmjs.com, since credentials will be set to false on that server.

**Comment by xMartin** [comment]
This is not limited to CouchDB configuration. For instance I have a setup with some auth proxy. How about renaming the issue to something like 'make `withCredentials` configurable' or something like that.

**Comment by anaran** [comment]
I arrived at this solution to make auth work for all my use cases (Firefox OS app, Desktop packaged app, served as hosted app via python -m SimpleHTTPServer

Using a customized xhr field I was able to debug this.

I leave the if statement in for historical background:

```
    var myXHR = function () {
      var request;
      if (false && /* false && */window.location.protocol == "app:") {
        request = new XMLHttpRequest({ mozSystem: true, mozAnon: true });
      }
      else {
        request = new XMLHttpRequest({ mozSystem: false, mozAnon: false });
      }
      return request;
    }
    var opts = {
      ajax: {
        xhr: myXHR,
        timeout: 30000
      }
    };
    var remoteOptionsDB = new PouchDB(destination + optionsDB._db_name, opts);
    var remoteDB = new PouchDB(destination + db._db_name, opts);
```

**Comment by nolanlawson** [comment]
woot, efe5dd8aa645e349a46a8e293703310c8da06ea2

**Comment by xMartin** [comment]
Nice, thanks!
