### ISSUE TITLE
Replication 'change' events should not fail if checkpointer fails

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2515]
Consider this SO question: http://stackoverflow.com/questions/24899938/pouchdb-how-to-verify-a-doc-is-replicated

Normally I'd recommend using the `'change'` event, but I noticed there's a potential race condition in the way it's currently implemented ([here](https://github.com/pouchdb/pouchdb/blob/1a839f022e235abacd07c12673bac81e8c027103/lib/replicate.js#L288)).

You can imagine the following sequence:

1. bulkDocs writes a batch of 50 docs to the remote DB
2. user loses connectivity
3. checkPointer fails to write
4. `'change'` event never fires

The user needs a way of knowing when docs were successfully written.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/fe4cc24dbe6a93ddc072c7dd3bacaec70120f74d
