### ISSUE TITLE
Inconsistent timeouts, unhelpful timeout error messages

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2562]
Just spent a good hour or so debugging this.

Apparently we have default timeouts set in like 3 different places ([here](https://github.com/pouchdb/pouchdb/blob/96687d6acfefcc42c1c7592f6fff9a4f2ce4917b/lib/adapters/http.js#L856), [here](https://github.com/pouchdb/pouchdb/blob/96687d6acfefcc42c1c7592f6fff9a4f2ce4917b/lib/adapters/http.js#L700), [here](https://github.com/pouchdb/pouchdb/blob/96687d6acfefcc42c1c7592f6fff9a4f2ce4917b/lib/adapters/http.js#L461), and [here](https://github.com/pouchdb/pouchdb/blob/96687d6acfefcc42c1c7592f6fff9a4f2ce4917b/lib/deps/ajax.js#L30) AFAICT) and when you get a timeout error, you just see a very unhelpful:

```
CustomPouchError {
  message: "writeCheckpoint completed with error", 
  result: Object, status: 500, 
  name: "unknown_error", 
  error: true…
}
```

I would like to start unifying all these timeouts and also provide a better error message that makes it clear how to increase the timeout.

**Comment by daleharvey** [comment]
Yup its a dupe, closing
