### ISSUE TITLE
Remove 'binary' buffer usage in Node

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2580]
We use this in both our tests and in the running code. Per [the docs](http://nodejs.org/api/buffer.html):

> 'binary' - A way of encoding raw binary data into strings by using only the first 8 bits of each character. This encoding method is deprecated and should be avoided in favor of Buffer objects where possible. This encoding will be removed in future versions of Node.

**Comment by daleharvey** [comment]
Got a pointer to where we are doing it incorrectly?

**Comment by nolanlawson** [comment]
Everywhere where we are calling `new buffer(someData, 'binary')` (too many to list; there are plenty). Supposedly it's deprecated, although it still works in iojs and Node 0.12, so I don't know how important this issue really is.

**Comment by calvinmetcalf** [comment]
they key is you should be specific about how you want the string to be
decoded, likely it's utf8

**Comment by daleharvey** [comment]
No longer deprecated - https://github.com/nodejs/node/pull/3441
