### ISSUE TITLE
New feature idea: {multipart: true}

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2584]
CouchDB lets you post a doc with multiple attachments using `multipart/form-data`. I want to expose this as an option you can either attach to http requests like put(), post(), and bulkDocs(), or when constructing the http Pouch itself.

Partly I want this so that we can test this behavior in PouchDB Server, and partly I want it because it's a good feature for users who don't want to have to base64-serialize attachments when they post them, which uses up more bandwidth.

**Comment by daleharvey** [comment]
We now do this under the hood and may introduce `inline` as an option
