### ISSUE TITLE
Trim down the pouchdb.min.js size

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2632]
Even gzipped, it's gotten a little big. (37.55KB for pouchdb-3.0.1.min gzipped.)

I can't really think of any way to make it smaller, except by removing functionality, though.

**Comment by daleharvey** [comment]
So I have been careful everytime I assume new code has been added, but somehow our build size has increased dramatically, I think this shall be a fat christmas release but I will be looking into getting us back down to a reasonable size for the next release

**Comment by daleharvey** [comment]
>  Yeah I am really shocked to see that we are up to 80KB. Last I checked it was 50. Something big must have been added recently to balloon the size.

Something is forcing buffers to be included, tried https://github.com/pouchdb/pouchdb/commit/9da2b479b303f47aa7fc1eb93a8ac2aab6f56119 but still getting included

**Comment by nolanlawson** [comment]
Ah no, it turned out the 30kb was from `leveldb.js`; that's fixed now. As for buffers, I dunno.

**Comment by nolanlawson** [comment]
Closing. It's as small as it's gonna get for now.
