### ISSUE TITLE
Parallelize allDocs() in idb

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2633]
Someone reported on IRC that allDocs() is a decimal order of magnitude slower in idb than in websql. I took a look, and it seems to be because of the lack of native joins in IndexedDB (can't wait for IndexedDB 2.0...).

Anyway, we can't make it as fast as WebSQL without native joins, but we can alleviate the pain by parallelizing the requests to the by-seq store.  Currently we iterate through the doc-store and then pick from the by-seq store sequentially.

**Comment by daleharvey** [comment]
Closing out old optimisation bugs that havent panned out / arent being worked on, as always can reopen if we start working on them :)
