### ISSUE TITLE
Cross-tab change events in same browser

### ISSUE THREAD

**Issue by andraz** [pouchdb/pouchdb#2637]
Is there a way to get cross-tab or iframe-to-parent event detection? Local onchange event emitter?

Data is getting shared, you can test this by opening this link multiple times:
http://embed.plnkr.co/t3bP7AftEcSTIl7iyiYX/preview

If you click on the buttons (change the data) first on one tab, then on the next, counter will continue from the same value as on the previous tab.

The problem is that the view does not get updated as the data changes. Is there a way to listen for such events?

**Comment by daleharvey** [comment]
Closing, we have this feature
