### ISSUE TITLE
sync uptodate event should include direction

### ISSUE THREAD

**Issue by dholth** [pouchdb/pouchdb#2638]
When calling sync() all the callbacks get a ({direction, change}) argument except the uptodate callback which just receives the change.

The consequence is that a sync() will get two uptodate events but it's not obvious which direction is up to date.

As an aside I found it confusing that the to/from callbacks have a different signature than the sync() callbacks, the former being called just with a change, the latter including the direction.

**Comment by daleharvey** [comment]
`uptodate` is deleted - https://github.com/pouchdb/pouchdb/commit/937ef1f68c84e938ce470c8d03966aa917420587
