### ISSUE TITLE
 Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by desertzebra** [pouchdb/pouchdb#2667]
ON FF31 I am getting the following warning/error:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
```

![eventemitter](https://cloud.githubusercontent.com/assets/2937826/4005460/fd8ea4f6-2991-11e4-852d-c894436aa543.jpg)

I am using PouchDB 3.0.1-prerelease and I haven't read up much on the EventEmitter so I have a couple of questions:
Is there a way to solve it, without manually changing(hacking) the defaultListeners value in EventEmitter?
Changing the default value to lets say 15 doesn't seem to be a big problem but is it close to normal behaviour?
Are there any problems that could be encountered by just increasing the default value and not solving some underlying problems, like queries not being closed properly or something?
Should there be an option somewhere(constructor) to set the maxListeners property when the PouchDB object is created?

**Comment by barbalex** [comment]
Sorry for warming up this old issue: I have the same problem but my code is only starting a change feed once. It adds 11 listeners though and that provokes a warning.

The solution seems to be to "increasing the max listeners".

How would I do that? I haven't found anything in the docs.

**Comment by nickcolley** [comment]
@barbalex judging on the above your problem is more likely a code issue, are you able to share the code that reproduces the error?

**Comment by barbalex** [comment]
@nickcolley you're probably right: I now made sure to check that no replication exists yet before creating one (by giving the replication a global variable and checking that it doesn't exist) and the error message has disappeared. Though I felt very sure replications were only initiated once before adding this...

**Comment by TinChip** [comment]
Cancelling any previous sync or replication through SyncHandler.cancel() before syncing again solves the problem in our case.
