### ISSUE TITLE
try/catch around JSON.parse

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2670]
It's not guaranteed that what we'll get back is JSON:

> robertkeizer> Question; Is there a reason why the requet function in lib/deps/ajax.js doesn't wrap the JSON.parse in a try/catch? Would a patch be accepted for that? I have a 401 error coming back and instead of a clean catch with a parse error the current system just stops the execution of the entire system.

**Comment by daleharvey** [comment]
Will be fixed by https://github.com/pouchdb/pouchdb/issues/4094
