### ISSUE TITLE
CouchDB proxy/plugin/patch that returns open revs with _changes

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2686]
Seems to be the only way to fix the problem of needing to do a separate GET for each doc during replication. Otherwise replication is sloooooow (https://github.com/pouchdb/pouchdb/pull/2685).

My idea:

* Write a Node proxy to stand in front of CouchDB. All it does is allow you to pass `revs=true` and `open_revs=whatever` to `_changes`. Then it includes the `_revisions` in the `_changes` feed (assuming you also set `include_docs=true`).
* Modify `replicate.js` so that it uses the `_revisions` if the `_changes` feed happens to contain it. Else it does the painful "one GET per doc". (Same if there are attachments.)

I don't want to wait for CouchDB/Cloudant to implement this. Right now replication is way too damn slow. We gotta get serious about this.

**Comment by daleharvey** [comment]
Fixed by `_bulk_get`
