### ISSUE TITLE
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2688]
IndexedDB. Seen in Travis. wtf?

```js
{ failures: 
   [ { message: 'InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. (http://127.0.0.1:8000/dist/pouchdb.js:2732)',
       title: '"before each" hook',
       stack: 'process.on/global.onerror@http://127.0.0.1:8000/node_modules/mocha/mocha.js:5879\n' } ],
  passed: 756,
  failed: 1,
  lastPassed: 'Test create attachment and doc in one go without callback',
  completed: true }
```

**Comment by memyselfandyasir** [comment]
facing this issue on firefox..

DOMException [InvalidStateError: "A mutation operation was attempted on a database that did not allow mutations."
code: 11
nsresult: 0x80660006
location: http://127.0.0.1:8080/js/jquery.js line 2 > eval:7786]

**Comment by nolanlawson** [comment]
Thanks for reporting! Can you provide a test case to reproduce?

**Comment by memyselfandyasir** [comment]
I am using bulkInsert to update documents(and add too).. will try to provide you a proper test case..
PS: it is working correctly on chrome

**Comment by daleharvey** [comment]
So all indication seems to be that this was due to private browsing more, this was the previous error firefox used to throw (it doesnt anymore) and havent seen this particular error in while, if anyone has any steps to reproduce then please reopen, cheers

**Comment by alxndrsn** [comment]
I'm seeing this error on Firefox 43 (non-private mode) with pouch 5.1.0 when trying to call `myPouchDb.put(...)`:

> ```DOMException [InvalidStateError: "A mutation operation was attempted on a database that did not allow mutations."
code: 11
nsresult: 0x80660006
location: file:///_snip_/pouchdb-5.1.0.min.js:8]```

Will see if I can get a decent test case.  N.B. while I'm not running FF in private mode, I am accessing HTML served directly from the local file system.

**Comment by nickcolley** [comment]
@alxndrsn can you also try spinning up a small [web server](https://github.com/indexzero/http-server#installing-globally) and try with that if you reproduce it,
I'm not sure database access works properly from the file system for security reasons.

**Comment by daleharvey** [comment]
I am actually surprised, was about to say the same but my small test case

```
<!doctype html>
<html lang="en">
  <meta charset="utf-8">
  <title>My Paste</title>
  <script src="http://cdn.jsdelivr.net/pouchdb/latest/pouchdb.js"></script>
  <script>
    var db = new PouchDB('testing');
    db.post({a: 'doc'}, function(err, doc) {
      console.log('I POSTED!', doc);
    });
  </script>
</html>
```
works fine in firefox and chrome from the filesystem, fairly certain replication will not work however as `ajax` definitely requires a origin, if you do find your bug please open an issue with it, cheers

**Comment by alxndrsn** [comment]
@nickcolley using a webserver doesn't seem to make a difference:

<img width="824" alt="screen shot 2016-01-05 at 16 58 52" src="https://cloud.githubusercontent.com/assets/191496/12121527/b43781ac-b3cd-11e5-9c39-19b8fd7b91c5.png">

**Comment by alxndrsn** [comment]
After simplifying my code, I've ended up with this:
```html
<html>
  <head>
    <script src="//cdn.jsdelivr.net/pouchdb/5.1.0/pouchdb.min.js"></script>
  </head>
  <body>
    <div><h1>check the console</h1></div>
    <script>
      var db = new PouchDB('test-db');
      db.destroy()
        .then(function() {
          db.post({})
            .then(function(res) { console.log('post-success', res); })
            .catch(function(res) { console.log('post-failure', res); });
        })
        .catch(function(res) { console.log('destroy-failure', res); });
    </script>
  </body>
</html>
```

...which unsurprisingly can be fixed by adding `db = new PouchDB('test-db');` before the call to `db.post` :-)

**Comment by nickcolley** [comment]
I believe this is the same as https://github.com/pouchdb/pouchdb/issues/4339#issuecomment-140666218, PouchDB will not reopen a database after it is destroyed.

**Comment by alxndrsn** [comment]
Looks like it.  Might be nice if the `db` object would reject method calls after `destroy()` has been called.

**Comment by nickcolley** [comment]
That issue is tracking that exact thing to make it clearer, if you fancy contributing you could have a go and we could help you out with if you've got any questions etc?

Back on topic, @myasirkhan can you see if the snippet @alxndrsn has posted is the same pattern that produced your error?
