### ISSUE TITLE
IE11: Simultaneous allDocs throwing InvalidStateError

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2695]
Talking with @wendall911 about this. We may have to sequentialize certain calls in IE to avoid this. Or report it to the IE team.

This line throws: https://github.com/pouchdb/pouchdb/blob/c8d56cadd0d27217ded4aab181ac34e15f7fbc77/lib/adapters/idb.js#L726

**Comment by daleharvey** [comment]
Closing as it looks like this isnt reproducable anymore
