### ISSUE TITLE
"once called more than once" during rapid fire queries

### ISSUE THREAD

**Issue by dholth** [pouchdb/pouchdb#2697]
I have a PouchDB application that's trying to combine the results of an allDocs and a secondary index query, ideally with a timeout when the view is being recomputed. It looks roughly like:
```
db.allDocs({a query}).then(...)
db.query('design/view').then(...)
$q.all([first, second])
```
At least on Firefox on the desktop this reliably produces 'once called more than once' errors at least on the second query; this is connected to an autocomplete widget and queries fire as fast as the user can type. Will try serializing the queries.

**Comment by daleharvey** [comment]
@dholth if you are still having problems can you reopen with STR, tried reproducing this as well and havent been able to as others havent either

**Comment by irnc** [comment]
The same error happened to me because `callback` can be called multiple times from `revsDiff`.

On error path of `revsDiff`, `callback` will be called multiple times from `ids.map` iterator.
