### ISSUE TITLE
Blob URLs don't work via ajax in Safari/iOS/Firefox

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2726]
This is not really our bug, but I'm logging it here so we can keep track of it. Since we take attachments pretty seriously, it would be best for us if they worked the same across all browsers.

Firefox throws 405s when you try to do an ajax request for a Blob URL. Safari/iOS returns the wrong content-type ("null").

Live example: http://bl.ocks.org/nolanlawson/3b18fbdda653f4e5f612

[Bug filed on Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1062368).

Bug filed on Safari: 18215114 (I cannot figure out how to share a link from Apple Bug Reporter).

**Comment by daleharvey** [comment]
Firefox bug is fixed :) webkit nightly still failing

**Comment by daleharvey** [comment]
@nolanlawson So still broken in webkit, but it doesnt affect pouch in any way right? close this one out?

**Comment by nolanlawson** [comment]
Yeah, this doesn't affect us, and I've filed the bug on them.
