### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'updateSeq' of undefined

### ISSUE THREAD

**Issue by mtford90** [pouchdb/pouchdb#2727]
At random points during execution of my tests I've started receiving the following error after upgrade to 3.0.3:

```javascript
Error: Uncaught TypeError: Cannot read property 'updateSeq' of undefined (http://localhost:63342/rest/node_modules/pouchdb/dist/pouchdb.js:1957)
    at global.onerror (http://localhost:63342/rest/node_modules/mocha/mocha.js:5738:10)
```

It's occuring here:

```javascript
function writeMetaData(e) {
      var meta = e.target.result;
      meta.updateSeq = (meta.updateSeq || 0) + updateSeq; // Here
      txn.objectStore(META_STORE).put(meta);
}
```

Any insights? Tends to happen when a secondary index is installed via PUT.

**Comment by daleharvey** [comment]
So havent been able to reproduce this, @mtford90 if you can still see this give us any help to reproduce then please reopen, but hopefully its a bug that has been fixed by now. thanks
