### ISSUE TITLE
Replication event emitter 'status' called ahead of actual GETs

### ISSUE THREAD

**Issue by dholth** [pouchdb/pouchdb#2728]
My PouchDB program uses `db.replicate.to(other).on('change', function(status) { // display progress bar });` to tell the user if replication is done. This event fires before the 4,000 GET requests that are required to get the actual content.

This event would be more useful to me if it fired after the content and not after the metadata was fetched. Or the db's own change emitter could be used for progress bars?

**Comment by daleharvey** [comment]
We now fire change events after the documents are confirmed written
