### ISSUE TITLE
Pouch DB for windows Phone 7 

### ISSUE THREAD

**Issue by shettyabhishek** [pouchdb/pouchdb#2757]
I am working on building an offline application which uses Pouch to Couch sync mechanism. 
I am currently using the latest version of PouchDB .The issue I am facing is the app does not seem to run on Windows Phone 7. Basically the syncing does not happen. Is there some specific attributes that I need to use for resolving this issue ?

Or is Pouch DB supported on Windows Phone 7

**Comment by daleharvey** [comment]
Gonna close this and have a single bug open for windows phone support - https://github.com/pouchdb/pouchdb/issues/3643
