### ISSUE TITLE
Issues with 'opts' in PouchDB.destroy()

### ISSUE THREAD

**Issue by marten-de-vries** [pouchdb/pouchdb#2762]
There are some traces of ``opts.name`` being supported in ``PouchDB.destroy()``. That support isn't fully there though: the destroyed event uses 'name' irrespective of opts.name being set (resulting in 'undefined' being emitted). I also had some trouble with the function not returning when opts.name was set and the database had a dependent database. Just removing ``opts.name`` support from ``.destroy()`` would be a possible fix too. (It's undocumented currently, and has probably been broken for quite some time.)

**Comment by daleharvey** [comment]
destroy is going

**Comment by marten-de-vries** [comment]
Yes, that solves this problem nicely. And most of this has probably already been fixed by the pre-deprecate work earlier anyway.
