### ISSUE TITLE
Safari 7.1 crash in test suite at 95%

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2789]
insert rage comic face here

![screenshot 2014-09-23 13 10 48](https://cloud.githubusercontent.com/assets/283842/4376326/973a205a-4344-11e4-8d20-5769e87371eb.png)

The damn thing just stops at 95%, even with the 3.0.6 fixes. Yes, I reset beforehand so the storage was cleared. Also, the UI gets chopped off, and you can't even open the web inspector. Good times.

![screenshot 2014-09-23 13 10 48](https://cloud.githubusercontent.com/assets/283842/4376336/b4b0d4ee-4344-11e4-891d-b5a8c4214803.png)

**Comment by daleharvey** [comment]
So we cant fix previous releases, they are released, this if fixed in master and dont think there is anything more we can do right? closing out

**Comment by nolanlawson** [comment]
yep, literally nothing we can do here
