### ISSUE TITLE
iOS 8 UIWebView warning: "Deprecated attempt to access property 'userAgent' on a non-Navigator object"

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2790]
Yeah yeah, we shouldn't even be accessing userAgent anyway. But we should fix this.

**Comment by daleharvey** [comment]
What is the easiest way to test within a `UIWebView`?

**Comment by nolanlawson** [comment]
Build a Cordova app I'd say.

**Comment by daleharvey** [comment]
I tested and didnt see it, noticed this got fixed in cordova - https://issues.apache.org/jira/browse/CB-6911
