### ISSUE TITLE
Document the ajax timeout

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2791]
Neither the default of 10 seconds nor how to change it are documented anywhere.

**Comment by daleharvey** [comment]
These are now documented @ http://pouchdb.com/api.html#create_database

**Comment by mikeymckay** [comment]
Did the timeout documentation disappear because I can't find it.

**Comment by mikeymckay** [comment]
In case anybody ends up here:
`database = new PouchDB("http://localhost:5984/thedatabase", {ajax:{timeout: 50000}})`
