### ISSUE TITLE
replication with attachments - websql stub bug

### ISSUE THREAD

**Issue by janl** [pouchdb/pouchdb#2798]
heya, we have a PouchDB that creates the `_bulk_docs` request below during replication

IIRC `stub: true` is only relevant in multipart requests, when the binary data follows the JSON “stub”, so a `_bulk_docs` request with `data:` and `stub: true` seems like a bug.

I’d have to leave it to @espy to provide a minimally reproducible case for this, but maybe you can spot things already. This is on the latest PouchDB release.

```
{
  "new_edits": false,
  "docs": [
    {
      "type": "inspectionphoto",
      "_id": "1008-3",
      "_rev": "3-3a210e2bd34ee12bd75c9a26766059ed",
      "_revisions": {
        "start": 3,
        "ids": [
          "3a210e2bd34ee12bd75c9a26766059ed",
          "67dce7388e4ecd4462430ace277e7710",
          "654a2ac9505fa2b5cb513d3f2d2e56c0"
        ]
      },
      "_attachments": {
        "793ab97f.jpg": {
          "content_type": "image/jpeg",
          "digest": "md5-3e9dfe41351f42724c5beb2af1957476",
          "data": "/9j/4AAQSk..."
        },
        "49CC8BFC-2A2A-481B-ACB4-FC053D5497A6.jpeg": {
          "content_type": "image/jpeg",
          "digest": "md5-401f42890be4425881cee3a084a6c6fa",
          "stub": true,
          "data": "/9j/4AAQSk..."
        }
      }
    }
  ]
}
```

**Comment by daleharvey** [comment]
@espy if you are still seeing this and have any hints towards reproducing please reopen, I have also been trying and havent managed at all. Closing out
