### ISSUE TITLE
Web Workers and Service Workers

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2806]
PouchDB currently does not work within a Web Worker or Service Worker thread across all browsers.

This is not something we can really solve, because the browser bugs are kinda unfixable from our end. But they're worth tracking.

| Browser | Status | Issue | Details |
| ---- | ---- | --- | ---- |
| Chrome | :heavy_check_mark:   | | |
| Chrome + WebSQL | :heavy_check_mark:/:x: | [434740](https://code.google.com/p/chromium/issues/detail?id=434740) | Retired in v39 |
| Firefox | :heavy_check_mark: | [701634](https://bugzilla.mozilla.org/show_bug.cgi?id=701634) | Fixed in v37 |
| IE | :x: | [866495](https://connect.microsoft.com/IE/feedbackdetail/view/866495) | No known workaround |
| Safari | :heavy_check_mark:/:x: | [434740](https://code.google.com/p/chromium/issues/detail?id=434740) | To be retired circa Safari v9 |

**Edit:** updated 2015-03 to note Chrome/Safari deprecations and Firefox fixes.

**Comment by AdrianoFerrari** [comment]
Does anyone know the status of this?

As far as I can tell, Firefox now supports idb in workers (https://bugzilla.mozilla.org/show_bug.cgi?id=701634 marked as RESOLVED).

**Comment by nolanlawson** [comment]
Apparently WebSQL worked before, but will soon not work in both Blink and Webkit: https://code.google.com/p/chromium/issues/detail?id=434740

**Comment by nolanlawson** [comment]
I updated the table above. Looks like the Firefox fix will land in v37!

**Comment by daleharvey** [comment]
Firefox and Chrome are good, ie and safari are plain unsupported at the moment so closing out

**Comment by nolanlawson** [comment]
The readme for worker-pouch also clarifies these incompatibilities: https://github.com/nolanlawson/worker-pouch

**Comment by swapnil0545** [comment]
Hi, I am using ydn-db library which is similar to pouch db.
We were using websql inside the webworker and it seems to not working since the Safari 9 update.
I can see that chrome has already dropped it support for websql inside webworker.
But I do not see any official apple/safari link saying that.
The indexedDB apis in Safari 8 were buggy, do we have a buglist which are there for Safari 9 indexedDB apis.
Any issues the pouch db users are facing for websql inside webworkers.

**Comment by nolanlawson** [comment]
@swapnil0545 See the [linked issue](https://code.google.com/p/chromium/issues/detail?id=434740) for discussion. Yes, it was removed in both Chrome and Safari. Since Safari doesn't expose `window.indexedDB`, `window.openDatabase`, or `window.LocalStorage`, there is no way to store data from inside a web worker on Safari.
