### ISSUE TITLE
Database explorer - Fauxton in devtools

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#2817]
Talked about this before on IRC but wanted to open an issue to ask for advice (sanity).

Saw this really awesome browser extension for firebase for inspecting the database.
https://www.firebase.com/blog/2014-09-30-vulcan.html

What would it take to get fauxton in the browser in a similar fashion. I wouldn't mind working on it, but thought it'd be best to ask how sane an idea it is.

:dancer:

**Comment by marten-de-vries** [comment]
Alright, so downloads are available on the Github pages, Chrome Web Store & after review should appear at addons.mozilla.org. Closing.

**Comment by locks** [comment]
@marten-de-vries could you edit your comment to include the links please?

**Comment by marten-de-vries** [comment]
For completeness:

Firefox: [github](https://github.com/marten-de-vries/pouchdb-fauxton-firefox-addon)
Chrome: [github](https://github.com/marten-de-vries/pouchdb-fauxton-chrome-extension) & [web store](https://chrome.google.com/webstore/detail/pouchdb-inspector/hbhhpaojmpfimakffndmpmpndcmonkfa)
