### ISSUE TITLE
Reenable SSE

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#2823]
about to be disabled in https://github.com/pouchdb/pouchdb/pull/2821/files

**Comment by daleharvey** [comment]
Closing sse got removed in https://github.com/pouchdb/pouchdb/commit/c36333a378aed91ee05813c486669a5b6c66a756,  I think would should look at reviving this or similiar on the back of streaming replication

**Comment by eallik** [comment]
Is SSE going to be re-added at some point?

**Comment by nolanlawson** [comment]
Probably not. However, you are encouraged to write a plugin if you like. :) CouchDB supports SSEs.

**Comment by EuAndreh** [comment]
@nolanlawson I'd like to implement that. I'm familiar with PouchDB+CouchDB, but I haven't contributed to anything, yet (just some typos in the docs).

Can you give me any tips on where to find similar code to guide me? (other than the [plugin-seed](https://github.com/pouchdb/plugin-seed)

**Comment by nolanlawson** [comment]
You might want to check out https://github.com/nolanlawson/pouchdb-authentication since it also does ajax requests (via (`require('pouchdb/extras/ajax')`). Other than that, the best advice I can give is to check out the Couch documentation for SSE: http://docs.couchdb.org/en/stable/api/database/changes.html#event-source

**Comment by EuAndreh** [comment]
Thanks, I'll try something up.

**Comment by jareware** [comment]
@EuAndreh did you ever get started with this?

**Comment by EuAndreh** [comment]
@jareware I did get started, but I ended up using websockets. 
 :/

**Comment by jareware** [comment]
OK, still interesting. With something like https://github.com/nolanlawson/socket-pouch or something else?

**Comment by EuAndreh** [comment]
socket-pouck, indeed.
