### ISSUE TITLE
Get console from running saucelabs / selenium instances

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#2824]
@admc / @sourishkrout any ideas about this? a large percentage of our failures are onliy via saucelabs and its fairly hard to debug from one side

**Comment by daleharvey** [comment]
Giving up on this

**Comment by daleharvey** [comment]
Heh this is going to be the only way to debug https://github.com/pouchdb/pouchdb/pull/4747

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/b933b9847c1855e65d26e8bca9fb9c250e853b5b

**Comment by nickcolley** [comment]
Thanks Dale! 🤓
