### ISSUE TITLE
Use multipart/mixed for attachments

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2832]
`multipart/mixed` is more efficient for sending attachments around, and plus Sync Gateway only supports that format (#2676 and #2681).

**Comment by jchris** [comment]
I think this is the place to discuss which implementation to test and how to test it. I think Apache CouchDB will use this if we support it so we maybe it's an easy first place to work on Sync Gateway interop.

I'd like to learn how to interact with the test automation, maybe this is a good chance to do it?

**Comment by nolanlawson** [comment]
Yep, currently non-org members won't have their PRs tested in Saucelabs, but all the non-Saucelabs tests will be run. Probably the most important thing here is to verify support for PouchDB Master as well as CouchDB 1.6, so it should be fine for now. After that, we can run the Sauce tests to verify the proprietary browsers.

**Comment by jchris** [comment]
Is this the change we should be testing? https://github.com/preplay/pouchdb/commit/296df7af184ef496681b517590415df7d3c200b5

**Comment by nolanlawson** [comment]
Yep, that looks right. TBH can't remember why I stopped working on it.

**Comment by nolanlawson** [comment]
https://github.com/preplay/pouchdb/commit/296df7af184ef496681b517590415df7d3c200b5 looks the same as 93b40b0d94b86516213b082ca4f3f6a9ac3e3e27 - maybe @preplay just rebased it?

**Comment by gabrielnau** [comment]
Sorry for the late reply, I didn't see the Github notification.
Yes indeed, I just rebased it against master.

**Comment by nolanlawson** [comment]
Started looking into multipart again. It's gonna be a mess.

First off, it appears CouchDB returns the content as gzip-encoded. Meaning I guess we'll need to bundle a gzip decoder with PouchDB so that we can actually decode that content?? Unless there's a good Blob-related hack we can use to make the browser do it (or something...).

Second, I'm stuck right now trying to actually decode multipart/mixed. If anybody can figure out how I'm supposed to decode a string like `'H4sIAAAAAAAAAwMAAAAAAAAAAAA=\n'` (which should be a base64-encoded, gzip-encoded string `"This is a base64 encoded text"`), then I'd be happy to hear how.

If anyone is curious, here is an example of a full multipart/mixed response from CouchDB, completely base64 encoded: https://gist.github.com/nolanlawson/5ecdce6ea62ecb7ded4c

**Comment by nolanlawson** [comment]
So in retrospect, the only reason we care about this is for CSG compatibility.

For CouchDB, the benefit is increased efficiency when replicating attachments. We lose those efficiency gains (imo) if we need to bundle a multipart parser and a gzip decoder with PouchDB.

We could solve this problem a lot more simply if we just avoided GETing a doc with `attachments=true` in the replicator, and instead just fetched each attachment in a separate request. All the modern browsers we support can do that for us, and give us the data in a nice simple arraybuffer format,

**Comment by daleharvey** [comment]
Fixed by https://github.com/pouchdb/pouchdb/commit/c6059d2717e1114fe723ffd4c6392344ae540f4d
