### ISSUE TITLE
MD5sums are not calculated quite right

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2836]
Brian Mitchell mentioned this in person to me. I'll try to get a more detailed bug report.

**Comment by mudcube** [comment]
@nolanlawson Double check to be sure, but this seems to be calculating correctly in the most recent PouchDB `l4wb7knXrV/BpNgQmbE+GA==`. Perhaps it's because of the SparkMD5 v2.0 upgrade recently?

**Comment by nolanlawson** [comment]
Could be. I'm gonna close this unless we can get some more details.

**Comment by jo** [comment]
Could it be that CouchDB calculates the digest of the compressed attachments and not the uncompressed ones?

I could imagine an issue with Pouch for documents including an attachment where we calculate a different digest getting in conflict. Then we'd store the conflicting revisions digest, and won't find the corresponding attachment. I am not sure if we use `atts_since` but once we start so, such problems could occur.
