### ISSUE TITLE
Implement _revs_limit

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2839]
ala Couch

**Comment by anaran** [comment]
Ah, so this might be the reason I cannot restore a previous revision after `db.remove(id);`
I can get `_revisions.ids` but all the revs are `missing` except for the final one, which is `ok` but has `"_deleted": true` and no doc fields available.

**Comment by anaran** [comment]
Using `doc._deleted = true; db.put(doc);` keeps all doc fields intact in the tombstone revision,
just like you said in #pouchdb.

Using `db.remove(id);` does not!

In both cases the previous revision becomes `missing` immediately, even without replication or further db activity.

**Comment by nolanlawson** [comment]
> Using `doc._deleted = true; db.put(doc);` keeps all doc fields intact in the tombstone revision,
just like you said in #pouchdb.
> 
> Using `db.remove(id);` does not!

This is intended behavior, and will be documented when the docs are updated soon.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/5832d03e2796b090ae2a844278577fe2d994d982
