### ISSUE TITLE
replicate with cloudant emit 'complete' event prematurely .

### ISSUE THREAD

**Issue by khanhlu2013** [pouchdb/pouchdb#2848]
I have 7000 doc to replicate from cloudant to local pouchdb

![screen shot 2014-10-12 at 12 38 06 am](https://cloud.githubusercontent.com/assets/5914159/4605455/af25742e-51e2-11e4-95b4-c60bdbacfd19.png)

. as you can see, it took me 3 page refresh/run to fully download 7000 products. on first run, replicate emit complete event when the 'total downloaded doc' = batch_size. on second run it emit complete event when total downloaded doc = 1000. the 3rd time it download the rest. 

. this only happen with cloudant. when i develop locally with Apache CouchDB 1.5.0, i don't experience this problem. Do i miss something?

**Comment by willholley** [comment]
This should be fixed with release 3.3.0 which includes support for Cloudant/BigCouch. Can you verify?

**Comment by khanhlu2013** [comment]
It is working for me now with 3.3.1 version
