### ISSUE TITLE
API feature request: getAttachment as URL string

### ISSUE THREAD

**Issue by ssured** [pouchdb/pouchdb#2858]
I use PouchDB to store images as attachments on documents. The regular use case is to let the browser render these images in a `<img>` tag by setting the `src` property.

There is no API method to easily figure out where to point the `src` to:
- for CouchDB you can construct the url manually: http://`server`/`dbname`/`docId`/`attachment`
- for PouchDB when getting a Blob and when there is support for http://caniuse.com/#feat=bloburls: `URL.createObjectURL`  https://developer.mozilla.org/en-US/docs/Web/API/URL.createObjectURL
- for PouchDB returning base64: use a data uri scheme, http://en.wikipedia.org/wiki/Data_URI_scheme

This can be implemented as an option in the current getAttachment code: `{asURL: true}`

Usage could look like:

```javascript
db.getAttachment('abc', 'image.png', {asURL:true}, function(err, url){
  $('img').attr('src', url);
});
```

**Comment by nolanlawson** [comment]
As of 1f24d8b, it's now possible to directly get Blobs/Buffers from all read APIs. Since this is the most efficient format, and since `blob-util` can convert to all other formats such as data URIs and base 64, I'm going to consider this issue fixed. :)

**Comment by ssured** [comment]
Cool stuff, nice addition and awesome you have an api for changing the default behaviour. This issue was about something a little different though. My request was for getting an url to an attachment. Say you store images as attachments, this url is what you put in the src of an img. The http adapter can, in most circumstances, give a direct url to the attachment on the server (when it is a stub), except for new unsaved attachments. Other adapters will always return blob-urls. I use this because my code does not know if it runs against a remote couchdb, or a local pouchdb (offline use case). Hope this explains my proposal a little more. Anyways, awesome work again, especially as this makes CSG compatibility better. Thank you so much!

**Comment by nolanlawson** [comment]
I don't think we will add such a thing to core, but a plugin world be welcome. :)  `db.type() === 'http'` and `db.getUrl()` are the methods you will want to use. (Yes, undocumented, but pretty stable nonetheless.)
