### ISSUE TITLE
Problem in retrreiving large no.of docs in pouchdb

### ISSUE THREAD

**Issue by rkphilip45** [pouchdb/pouchdb#2859]
I am using PouchDB for client storage of master data in browser to facilitate data entry in the application. It works fine for upto 700 records. I am preparing datalist (html5) for the user to select from and also get the corresponding name for code from PouchDB. When the no. of records are high say 5000 retrieing and preparing datalist is painfully slow or sometimes doesn'y happen at all.

I get the data through ajax call and insert as bulkDcos and create secondary index. Upto this it is ok.
I am storing 78000 approx records in pocuhDB in one go for one master and for others approx 250 and 650.
But retrieving is a problem.
Is there a limit in storage and retrieval of no.of records in PouchDB? If so what is the solution ?
If not where am i wrong?

**Comment by rkphilip45** [comment]
Sorry for the delay in writing Mr. Nolan Lawson. 
As of now we have come to the conclusion that PouchDB is not suitable for this particular application. Or may be the way i use it is not appropriate. Anyway i have moved ahead without PouchDB.
Using local forage has also been suggested to me though i have not tried that option. 

Thanks for your effort and suggestions.

**Comment by nolanlawson** [comment]
OK, sorry we couldn't help you!
