### ISSUE TITLE
Fetching a document never gets a response when all website cookies and data blocked in Safari

### ISSUE THREAD

**Issue by lyudmil** [pouchdb/pouchdb#2860]
I've only tried this in Safari.

## Steps to reproduce

1. Make sure to block all website data in Safari:
![screen shot 2014-10-13 at 3 08 10 pm](https://cloud.githubusercontent.com/assets/69157/4614682/ab2489a4-52e2-11e4-8691-4499d6445f90.png)

2. Run the following in the console:

```javascript
pouch = new PouchDB('my_little_test')
pouch.get('abc123', function(err, doc) { console.log(err.message, doc) });
```

This never logs anything.

## Expected behavior

1. Make sure to allow data in Safari:
![screen shot 2014-10-13 at 2 57 59 pm](https://cloud.githubusercontent.com/assets/69157/4614747/3a1e0eb4-52e3-11e4-8420-9a43db3a4d51.png)

2. Run the following in the console:

```javascript
pouch = new PouchDB('my_little_test')
pouch.get('abc123', function(err, doc) { console.log(err.message, doc) });
```

This should log the following:

    >> missing undefined

**Comment by daleharvey** [comment]
Yup, hopefully should be fixed now

**Comment by daleharvey** [comment]
(by https://github.com/pouchdb/pouchdb/commit/348ef3c3d0ad0ba35c0abadc452192161bd00714)
