### ISSUE TITLE
Add some kind of Travis/Sauce badge to the README

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2870]
I don't mind if we roll our own, but we really ought to be advertising how extensive our tests are. @daleharvey has done an amazing job, and it's because of all the tests that we've managed to built such a rock-solid library.

We can reuse the icons from [here](http://pouchdb.com/adapters.html#pouchdb_in_the_browser) and just make the table ourselves, right? Maybe use some other icons or text for concepts like auto-compaction or couchdb master.

**Comment by nickcolley** [comment]
Closing this as we've got a travis badge in the readme now.
