### ISSUE TITLE
Using leveldb, a document w/ given id can be added/removed/added and will end up w/ bogus _rev

### ISSUE THREAD

**Issue by ahizzle** [pouchdb/pouchdb#2888]
Hard to describe, easier to see with a test case (will attach).  In short, for a series of add/removes, I'm seeing this:

```
write 1, rev = 1-75fed657b5af548f149b15e6cc375780
del   1, rev = 2-c59710ebc34273fef729fce9c6234a7e
write 2, rev = 3-5f0bf741acee11f74258b9758cfc950c
del   2, rev = 4-599bcba33a628f0d06a4cd0ccb776524
write 3, rev = 4-599bcba33a628f0d06a4cd0ccb776524 <<<< HUH? 
del   3, rev = 1-a51015217be9f42878ab6f8919fe20a6
write 4, rev = 5-da11a5637893f1be9ffc98a580583619
Removing { _id: 'foobar', _rev: '5-da11a5637893f1be9ffc98a580583619' }
del   4, rev = 2-43fe1e0bb735005d955f81b54f1d959e <<<< should be 6-something
```

Here's where it gets weirder: If you then re-run the test against the same database (ie: don't blow it away between test runs), the next run finds the document and it is NOT deleted?!

`Existing doc for id is: { _id: 'foobar', _rev: '2-43fe1e0bb735005d955f81b54f1d959e' }`

Actually, even at the end of the test run it appears the last delete is straight-up failing to work. I can get it back from the DB, even though it should be a 404.

**Comment by daleharvey** [comment]
Fix landed
