### ISSUE TITLE
Minified Output: Provide a module name for the AMD define

### ISSUE THREAD

**Issue by jbest84** [pouchdb/pouchdb#2891]
Several libraries provide a named AMD module in their minified/built output (momentjs and snapjs to name a few). That seems to be the recommendation on requirejs.org (http://requirejs.org/docs/api.html#modulename). The problem we have is that we don't run built third party libraries through an AMD build process, because those libraries have already been built.

**Comment by daleharvey** [comment]
heh, 1 year anniversary, @nolanlawson given your recent foray into outputting a build for N + 100 different systems is there anything to do here or do we close this out? (I have no idea about amd / umd / etc)

**Comment by nolanlawson** [comment]
We build using the `-s` option with Browserify, which supposedly covers all bases with both AMD and UMD, so I'd say close it.
