### ISSUE TITLE
IE and WinJS: Docs becoming corrupted after startup when syncing with CouchDB

### ISSUE THREAD

**Issue by Rhywden** [pouchdb/pouchdb#2912]
I'm currently developing a WinJS app and, as usual during the development cycle, I'm restarting the whole thing quite often. This sometimes results in a partial corruption of the database. Basically, it looks like the delimiter between the fields isn't recognized or converted into something that isn't recognized.
Which results in some fields being pulled into the _id field. Basically looks like this in Futon:

![image](https://cloud.githubusercontent.com/assets/84586/4728306/bcc23042-5974-11e4-92f6-9b3c451b714d.png)

It's the three rows in the middle - take row 5, for example. That one had an _id of "chemie" and a field named "Chemie". Now both are in the id and when I try to select it, I get an Error: The selected document could not be retrieved.

I can retrieve the document in PouchDB, however. When I try to do so I can also see that it dropped the field named "type" - simply isn't there anymore.

I'm a bit unsure on how to replicate this behaviour, though.

Trying to delete it programmatically with the id yielded by javascript inside Pouchdb only results in the following error:

    {"status":404,"name":"not_found","message":"missing"}

But if I'm using the id displayed in Futon (the one with what I guess are UTF-8 char codes?) then I can actually delete them. And the deletion is synced to CouchDB.

Oh, one addendum: The fact that you're seeing the proper document with the id of "chemie" on my screenshot is just due to the fact that my program is searching for seed entries in the db - and if those don't exist then they're created. It does **not** mean that CouchDB or PouchDB creates duplicates which then become corrupted.

**Comment by daleharvey** [comment]
Unable to reproduce, if you can find some way to show the error that isnt specific to your setup please reopen / file a new bug, its possible ie indexeddb got fixed too
