### ISSUE TITLE
LevelDB: once called more than once

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2913]
Sorry for no test case, but this is in some closed-source code that will be opened soon. I'm mostly just filing this issue to remind myself to update it later with the test case.

LevelDB's `bulkDocs` has a race condition where if you're doing a massive amount of parallel puts/compaction/attachments, then the callback for `bulkDocs` gets called more than once. I assume this is somehow related to the code that says

```
      current++;
      inProgress++;
```

trace:

```
  2)  "after each" hook:
     Uncaught Error: once called  more than once
      at /Users/nlawson/workspace-node/pouchdb/lib/utils.js:418:13
      at /Users/nlawson/workspace-node/pouchdb/node_modules/argsarray/index.js:14:18
      at /Users/nlawson/workspace-node/pouchdb/lib/adapters/leveldb.js:715:38
      at process._tickCallback (node.js:419:13)
```

**Comment by daleharvey** [comment]
We merged in a bunch of fixes for this, I think its good, reopen if we see it again

**Comment by ssured** [comment]
This exact error pops up from time to time, pointing to https://github.com/pouchdb/pouchdb/blob/37fe1bc5a482b230fe9aa810a5419cbcde06da40/packages/pouchdb-utils/src/once.js#L9

Source of my errors are iOS Safari + FruitDown/LevelDB. In other browsers these errors do not appear in my rollbar logs. Possible cause could be that an ajax.timeout triggers the callback with an error. Later the XHR does complete and triggers the callback again.

**Comment by nolanlawson** [comment]
@ssurred let's keep discussion in #5486, thanks for opening a separate issue

**Comment by nolanlawson** [comment]
Oh wait seriously, you see "once called more than once"? Can you open a new issue with a test case to reproduce please?

**Comment by ssured** [comment]
@nolanlawson Well that's easier said than done... I'll keep an eye on these errors as they come up in the logs. For now I do not know where they originate, and I stated my hypothesis above. It is really weird, I hope to be able to reproduce one day. I even double checked my own code for not having the same error message... When the day is there I'll open a fresh issue!

**Comment by mohlsen** [comment]
Don't know if this is related, but I submitted https://github.com/pouchdb/express-pouchdb/pull/353 today and it failed on [Travis CI test](https://travis-ci.org/pouchdb/express-pouchdb/jobs/146200664) related to this issue.

```
  1)  "after each" hook for "#2913 massively parallel compaction":
     Error: ETIMEDOUT
      at onError (packages/pouchdb/lib/index.js:5154:18)
      at Request._callback (packages/pouchdb/lib/index.js:5196:14)
      at self.callback (packages/pouchdb/node_modules/request/request.js:200:22)
      at Timeout._onTimeout (packages/pouchdb/node_modules/request/request.js:775:12)
```
