### ISSUE TITLE
Replication busted if skipSetup true

### ISSUE THREAD

**Issue by rymohr** [pouchdb/pouchdb#2915]
Just upgraded to 3.0.6 from 2.x and I'm running into replication issues.  The pouch constructor promise never resolves so the replication waits indefinitely.

Pretty sure there should be a `callback(null, self);` call after this line yeah?

https://github.com/pouchdb/pouchdb/blob/275913631077f880a08f2524e8515034f468e579/lib/constructor.js#L147

**Comment by daleharvey** [comment]
This landed, thanks
