### ISSUE TITLE
In-memory key iteration for small DBs

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2922]
We all know that the localStorage adapter is the fastest for small DBs, which should prompt us to take those lessons into the Web SQL and IndexedDB and maybe even LevelDB adapters.

We can set some maximum number of IDs/seqs (say 100) and for databases that contain fewer than that number of documents/revisions, we hold all the IDs/seqs in memory for quicker iteration during `changes()`/`allDocs()`.

I think plenty of people are using Pouch to only store small bits of configuration data, and for those people holding the keys in memory would be a big win for performance.

**Comment by daleharvey** [comment]
Closing out old optimisation bugs that havent panned out / arent being worked on, as always can reopen if we start working on them :)
