### ISSUE TITLE
Allow update_seq option on allDocs query.

### ISSUE THREAD

**Issue by robertkeizer** [pouchdb/pouchdb#2927]
CouchDB supports this at the moment, but it seems PouchDB doesn't. http://docs.couchdb.org/en/latest/api/database/bulk-api.html#get--db-_all_docs

**Comment by daleharvey** [comment]
So I dont think we would say no to a patch for these, however I think our main focus is on getting `pouchdb-find` ready for production and for it to be handle these cases. So gonna close out. Thanks
