### ISSUE TITLE
Initial replication of 3 docs takes over 40 seconds

### ISSUE THREAD

**Issue by redgeoff** [pouchdb/pouchdb#2950]
My DB has 3 records (152 were deleted) and it takes over 40 seconds for the initial replication. Subsequent replications take under 2 seconds.

Steps to replicate:

1. Clear your cache (this is needed so that you don't have a pouch db already in your browser)

2. Visit http://bl.ocks.org/redgeoff/0c43bc7391aa0fb8c534

Note: the console will output `uptodate` when the replication has completed.

In looking at the network traffic, it appears that there are about 2 http requests similar to the following for all 155 _changes_. I can imagine a little overhead, but I would expect the exchange to go like:

1. Client says "Hello" to server and initializes the DB, connection, etc...

2. With a single http request, client asks for all updates and server responds with all updates. (Obviously, if there was a lot more data, this would have to paginated).

Am I using pouch wrong or is there a bug?

**Comment by daleharvey** [comment]
We have landed `_bulk_get` support, and and open bug about getting automated performance testing up (of which replication is our main indicator) so closing this out as dupe - https://github.com/pouchdb/pouchdb/issues/4152
