### ISSUE TITLE
LevelDB reports 404 immediately after 409

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2951]
If the database throws a 409, then I expect it to not throw 404s afterwards. I.e. if you just told me that I can't write a document because it already exists, then don't turn right around and tell me that same document doesn't exist.

This only throws in LevelDB, not in WebSQL or IndexedDB.

**Comment by TeeKz** [comment]
I'm having this issue on Cordova & SQLite.

**Comment by nolanlawson** [comment]
@TeeKz can you provide a test case to reproduce? 404s and 409s are a natural part of working with Pouch/Couch, and normally you should be trying to handle them.

If you don't want to handle them, though, you can use [pouchdb-upsert](https://github.com/pouchdb/upsert).

**Comment by TeeKz** [comment]
@nolanlawson I was able to pick up that much from the docs. I was using the upsert plugin but was getting stuck in an infinite 404 to 409 loop. As the start of this thread says, doesn't make sense. 

Realized I had included the Cordova SQLite.js file which I thought was needed for pouch to run sqlite. Removing it seemed to fix things!
