### ISSUE TITLE
Replication Issue with Cloudant

### ISSUE THREAD

**Issue by hrishiballal** [pouchdb/pouchdb#2953]
I am using PouchDB 3.0.6 and trying to sync to a cloudant DB in the browser. I have enabled CORS per Cloudant's instructions on : https://gist.github.com/chewbranca/0f690f8c2bfad37a712a 

Following is my sync function in Javascript
```javascript
function syncRemoteDB(projectname)
{
  var pname = 'c-'+projectname;
  var remotedb = 'http://urbanflowengine.cloudant.com/'+pname;
  var db = PouchDB('db-local'),
    opts = {
      live: false
    };
    console.log('In Web worker')
var sync = PouchDB.sync(db, remotedb, opts)
  .on('change', function (info) {
    // handle change
  }).on('complete', function (info) {
    // handle complete
  }).on('uptodate', function (info) {
    // handle up-to-date
  }).on('error', function (err) {
    // handle error
  });
}
```
When I use a web worker in Chrome to sync this database, I get a 405 not allowed (below), You can see that the database exists: http://urbanflowengine.cloudant.com/c-15c4bb1a2bf46857 

![screen shot 2014-11-07 at 05 53 36](https://cloud.githubusercontent.com/assets/1588744/4948976/c78fa0a6-6642-11e4-9387-a2db00b2ab76.png)

![screen shot 2014-11-07 at 05 53 47](https://cloud.githubusercontent.com/assets/1588744/4948977/cd250646-6642-11e4-8d1e-f15b702eb361.png)

I reached out to Cloudant support and they thought that the issue was with PouchDB and they suggested that this is happening because of the _nonce parameter. Is there a way to sync without the _nonce ? Has anyone else encountered Sync problems with Cloundant and what is the workaround. 

Thanks for the great work here!

**Comment by daleharvey** [comment]
So this is working against couchdb master at the least, cloudant will be converging to that, hopefully they have fixed this already but the only thing we can do is wait, closing out, cheers
