### ISSUE TITLE
Console logs inside Promise functions not working when adding data to DB

### ISSUE THREAD

**Issue by inblueswithu** [pouchdb/pouchdb#2954]
I'm on Ubuntu 14.04LTS. Using Google Chrome (38.0.2125.111 (64-bit)) & Firefox (33.0). I'm using the pouchdb.min.js (From commit e78a30f on Nov 5th 2014 at 9:02 am (UTC-0500)).
```javascript
    console.log("Trying to get to DB...");
    db.post(json).then(function(result) {
        console.log("DB insert Success");
        console.log(result);
    }).catch( function(error) {
        console.log("DB insert Failed!");
        console.log(error);
    });
```
The above code does not print either DB success/DB Failed instructions it just continues to next instructions afterward. I have seen very very few times it printed DB insert Success but don't kow how to replicate the same again to show the problem. _Most times even data insertions into the DB from Chrome are missing! It does not display any message but the db values which we want to be inserted would be nowhere._ Currently I have removed a local database with sync to a iriscouch db and using iriscouch DB directly. Like this, Sending data into the online database seems to be smooth in Firefox, still struggling with Chrome. Guess this should be some bug - [Suggested by nolanlawson over #pouchdb IRC]. 
Please lookinto this and reply. If need any info, please ask.

Thanks & Regards,
inblueswithu

**Comment by daleharvey** [comment]
And closed, cheers
