### ISSUE TITLE
PouchDB doesn't replicate deleted conflicted documents.

### ISSUE THREAD

**Issue by tyler-johnson** [pouchdb/pouchdb#2955]
Hello, I think I might have found a bug. It is my understanding that CouchDB bidirectional replication keeps two databases perfectly in sync which would include all deleted revisions and documents. PouchDB, on the other hand, fails to replicate any deleted conflicting revisions. This makes conflict resolution hard when syncing with a remote CouchDB.

Here is a JSFiddle that shows it failing:
* v3.0.6 - http://jsfiddle.net/appleifreak/h5arfeb3/1/
* v3.0.7-prerelease - http://jsfiddle.net/appleifreak/h5arfeb3/2/

This doesn't work with IndexedDB or CouchDB databases, nor does it work while using continuous replication. I might be seriously confused here, so please correct me if I am wrong.

I have a side question about Pouch, slightly unrelated to this issue. Pouch seems to choose the local copy as the winner over the remote copy during a conflict. Is there a way to reverse this while syncing so that the remote is always the winner?

**Comment by daleharvey** [comment]
Fixed and a test added in https://github.com/pouchdb/pouchdb/commit/ca1de673832aa35addbea93bee75412970f87113
