### ISSUE TITLE
Add startkeys and endkeys support to allDocs.

### ISSUE THREAD

**Issue by robertkeizer** [pouchdb/pouchdb#2956]
Couch has had this for a bit, and it would be really awesome if Pouch also had this feature.

A range of startkey / endkey pairs; I'm assuming this would mainly require changes to the adapters.

**Comment by daleharvey** [comment]
So I dont think we would say no to a patch for these, however I think our main focus is on getting `pouchdb-find` ready for production and for it to be handle these cases. So gonna close out. Thanks
