### ISSUE TITLE
PouchDB itself at PouchDB.com

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2960]
In the spirit of https://github.com/pouchdb/pouchdb/issues/2957, it might be kind of nice to just have PouchDB itself included in the PouchDB.com site. I often feel intuitively that I should be able to play with jQuery when I'm at jQuery.com, or play with Underscore when I'm at Underscore.com. Might as well.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/f030c96feab5353004aeb37f2563f50dd6655861
