### ISSUE TITLE
"uptodate" event is triggered before the end of a live replication

### ISSUE THREAD

**Issue by Kloadut** [pouchdb/pouchdb#2980]
Hi guys,

I noticed that in case of a large replication (like the first replication from a CouchDB with a lot of changes) the event "uptodate" is triggered multiple times during the pulling, even if the CouchDB remains unmodified during the whole operation.

For now, I use a "not-live" replication in the first place, but it is a bit annoying though.

Is this behaviour wanted or is it just a bug ? :)

**Comment by daleharvey** [comment]
`uptodate` is deleted - https://github.com/pouchdb/pouchdb/commit/937ef1f68c84e938ce470c8d03966aa917420587
