### ISSUE TITLE
Add interceptor path to pouch

### ISSUE THREAD

**Issue by auser** [pouchdb/pouchdb#2987]
I'm working through adding an interceptor path through for adapters. Specifically, I'm working through modifying the `utils.adapterFun()` method. 

The specific model is adding a chain of interceptors to modify an out-going request (aka in the `http` adapter or `websql` adapter, etc) and to modify an in-coming response.

Without going into too much detail (the _currently broken_ implementation can be found [here on my fork](https://github.com/auser/pouchdb/blob/feature/interceptors/lib/utils.js#L507-L583)), my tests look like:

```javascript
    it('Adds a request interceptor', function (done) {
      var db = new PouchDB(dbs.name);

      var interceptor = {
        request: function (req) {
          req.called = true;
          return req;
        }
      };

      writeDocs(db, JSON.parse(JSON.stringify(origDocs)), function () {
        db.interceptors.push(interceptor);
        db.get('1').then(function (res) {
          console.log('in get(0) ', res);
          res.called.should.equal(true);
          done();
        });
      });
    });
```

Effectively, I want the `request` interceptor to be called first and forward it's arguments on to the next promise. This can be set using promise chains (i.e. promise.then(function(){}).then(function(){})...

What I'm currently missing in the first iteration is the arguments themselves are not getting passed on, and if they are, they are not getting executed. I suspect the taskqueue will play a role here.

The tests can be found on [my fork here](https://github.com/auser/pouchdb/blob/feature/interceptors/tests/test.interceptors.js). All of the tests pass except for my new tests.

**Comment by daleharvey** [comment]
I would like something along these lines, but I am expecting it to look a little like per document hooks, either way the approach of intercepting outside of pouch has been sufficient up till now so closing out, cheers
