### ISSUE TITLE
Blob URL support detection is executed for every PouchDB instance

### ISSUE THREAD

**Issue by tomraithel** [pouchdb/pouchdb#2990]
Hi, 
we have multiple PouchDB instances on our site. Since I´ve updated to v3.x we now get multiple requests for the blob check (one for each instance):

```
GET blob:http%3A//foobar/827e077d-a803-448a-8f0f-4e2dd7d9d041 404 (Not Found) pouchdb-3.1.0.js:5731
The above 404 is totally normal. PouchDB is just detecting blob URL support.
♥ the PouchDB team 
```

So my question is, does pouchdb really need the blob check vor _every_ instance? It would also be nice if one could force pouchdb to omit the blob check since I know I don´t need it.

What do you think?

**Comment by amyou2005** [comment]
I got this too
'The above 404 is totally normal. PouchDB is just detecting blob URL support.'
how to fix it

**Comment by marten-de-vries** [comment]
@amyou2005 As the message explains, it's normal and you don't have to worry about it. Just ignore it.

**Comment by daleharvey** [comment]
It will also not show up in the next release :)

**Comment by marten-de-vries** [comment]
Ah, even better. I'm lagging behind. ;)

**Comment by amyou2005** [comment]
Thanks for answer all
