### ISSUE TITLE
Add direction to uptodate event

### ISSUE THREAD

**Issue by ssured** [pouchdb/pouchdb#2992]
When using `db.sync`, the event emitter injects a `.direction` property on the change event, see https://github.com/pouchdb/pouchdb/blob/08f170d7cadfb450f58ca210f393dbcd5e66d45f/lib/sync.js#L87-L89. 
I think it would be nice to inject the direction too on the `uptodate` event, but doing so might introduce a backwards compatibility issue.

**Comment by daleharvey** [comment]
`uptodate` is deleted - https://github.com/pouchdb/pouchdb/commit/937ef1f68c84e938ce470c8d03966aa917420587
