### ISSUE TITLE
Query operation "not" working with HTTP adapter

### ISSUE THREAD

**Issue by echo66** [pouchdb/pouchdb#2997]
Greetings!

I have a database (http://localhost:5984/mydb) and I can use get, post, put and remove as expected, both with IDB and HTTP adapters. But, when I use the HTTP adapter, 

```javascript
var db = new PouchDB('http://localhost:5984/mydb');
db.query({map:function(doc){emit(doc);}}, {reduce:false}, mylog)
```

I get a 401 with the following message: "You are not a db or server admin". Yet, if I use the IDB adapter, I get no error.

Note: I'm using the HTTP adapter because I need to use the authentication plugin.

**Comment by daleharvey** [comment]
Yup behaves as expected
