### ISSUE TITLE
Minified JavaScript should only contain ASCII

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3009]
So I ran into a really annoying bug today that was caused by downloading `pouchdb.min.js` from the site using `curl` without the proper binary flags.

This is easiest to illustrate with a screenshot:

![screenshot 2014-11-18 13 47 22](https://cloud.githubusercontent.com/assets/283842/5093813/7255a42e-6f29-11e4-9296-1e86ae0e1ca0.png)

Annoyingly, in the source code those `'\u0001'` strings are expressed in ASCII, but then Browserify or Uglify or somebody turns around and outputs unicode, which can get messed up if you don't download the minified javascript correctly.

This causes bugs in images like [this one](http://bl.ocks.org/nolanlawson/7f83a117ef005fc7fc15) and also map/reduce.

Let's please just output ASCII when we build the `pouchdb.min.js`.

**Comment by daleharvey** [comment]
Looks like our build only outputs ascii now
