### ISSUE TITLE
Complete fires prematurely, with low batch_size

### ISSUE THREAD

**Issue by scoughlin** [pouchdb/pouchdb#3014]
When syncing a 5MB database from Cloudant, with a batch_size of 40, “complete” fires after only 99 docs have downloaded, which kills the download before it’s done. Increasing batch_size to 100 killed the download at 40 docs.  Increasing the batch_size to 5000 fixes the issue, but I believe that is bad for low memory machines, and I will be unable to monitor the download as this causes the “change” event to fire only twice.  Using pouchdb-3.0.6.min.js

	  var nameDB = "curriculum";
	  var remoteDB = new PouchDB("https://[username]:[password]@[url]/" + nameDB);
	  var localDB = new PouchDB(nameDB);

	 var replication = PouchDB.replicate(remoteDB, localDB, {live: false, attachments: true, batch_size: 40, batches_limit: 500})
	  .on('change', function (info) {
			console.log('change event');
			console.log(info);
	  }).on('complete', function (info) {
			console.log('complete event');
			console.log(info);
	  }).on('error', function (err) {
			console.log('error event');
			console.log(err);
	  });

**Comment by tannerlinsley** [comment]
Seeing this on the latest version as well.  A higher batch_size is needed so it can "complete" after all docs are finished writing.

**Comment by willholley** [comment]
Can you still reproduce this in master? The latest release doesn't include the recent fixes for CouchDB 2.0 / Cloudant but we're almost there in the master branch.

**Comment by daleharvey** [comment]
Yup this was before we had full couchdb master support, as far as we can well this is now working great so please reopen if you see any issue. thanks
