### ISSUE TITLE
Pouchdb support for Titanium

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [pouchdb/pouchdb#3016]
I found pouchdb very helpful, fast in HTML5/Cordova app, but I wish to have with Appcelerator Titanium mobile app with sqlite backend. Can you please help how to make pouchdb to work with Appcelerator Titanium, we don't use Webview. 

Also found couchbase-lite version for Android and iOS. Do you recommend it over pouchdb?

**Comment by daleharvey** [comment]
@gopalakrishnan-subramani please reopen if you are still working on this and need anything from the pouchdb side, hopefully one of the various backends we have should work for you
