### ISSUE TITLE
Include document IDs on the change information during replication ?

### ISSUE THREAD

**Issue by Kloadut** [pouchdb/pouchdb#3020]
Hi guys,

I was wondering if it would be relevant to include IDs (and revisions ?) of changed documents during a replication. For now, available informations are : 
```json
{
  "doc_write_failures": 0, 
  "docs_read": 1, 
  "docs_written": 1, 
  "errors": [], 
  "last_seq": 1, 
  "ok": true, 
  "start_time": "Fri May 16 2014 18:23:12 GMT-0700 (PDT)"
}
```
(I don't know the status of the equivalent operation in CouchDB though)

I actually want to be able to get all the documents that have changed remotely, even if I run a two-way synchronization. For that purpose, the `changes` API won't fit and will give me all the changes.

**Comment by daleharvey** [comment]
I belive we do this now, but going to check + documentation before closing

**Comment by daleharvey** [comment]
Ok, the id and revision are in the change events, however undocumented, I have a pr open to document that now 

https://github.com/pouchdb/pouchdb/pull/4123
