### ISSUE TITLE
Chromium via file :// protocol pouchdb post fails silently

### ISSUE THREAD

**Issue by dodtsair** [pouchdb/pouchdb#3036]
This is probably an edge case, and more an FYI.  I am developing a browser only application using couchdb as the data storage.  Still putting the framing together.  I started adding in pouchdb the other day.  Since I have not had pouchdb working as of yet, I have been testing by opening the file in my browser.  Worked great, but once I called pouchdb's post api my call back was never called.  No error on the console.  This is probably a legitimate security implementation in Chromium.  But it would have been nice if pouchdb still called the call back with an error.

            var db = new PouchDB("user");
            var userDao = {
                create: function(newUser, cb) {
                    db.post(newUser, {}, cb);
                }
            };
            return userDao;

**Comment by daleharvey** [comment]
So we no longer fail silently, chrome and firefox both support indexeddb in file protocols now
