### ISSUE TITLE
Improve map/reduce performance

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3039]
I don't necessary love map/reduce, but it's currently our weakest point. And it makes sense to improve perf for two reasons:

1) It's all we got in terms of secondary indexes, for now.
2) Since it's built on `allDocs`/`bulkDocs`, any improvements there will spill over to map/reduce.

Been profiling the `temp-views` test, trying to figure out what's up. This seems to affect all three adapters. ([perf report](https://github.com/nolanlawson/pouchdb-perf-report-3.10))

*Edit:* tracking

* [X] autoCompaction can be done without an explicit doCompaction(). we can just do it in the same transaction as bulkDocs (map/reduce DBs are auto-compacted)
* [ ] doing allDocs(keys) in a single transaction could be beneficial for IndexeDB. I just learned from yathit that sorting the keys and then using a skipping cursor is actually faster than parallel get()s. and for websql of course we can use WHERE id IN (...)
* [X] putLocal could be faster in IndexedDB if we used a unique index rather than keypath, because we can let the database throw ConstraintErrors and catch them rather than doing an explicit get() before the put() *actually we can use add()*
* [ ] IndexedDB might be faster if we tried to merge the doc-store and by-sequence-store into a single store and use string concatenation for keys. then we could use a skipping cursor for allDocs/changes. also for IndexedDB, put()s seem incredibly slow. WebSQL doesn't have bulk insertions. maybe if we make some assumptions about the underlying store, we can improve perf there. (e.g. is it faster if we put() from lowest to greatest keys? need to ask a LevelDB expert)
* [ ] if the user is not emitting values, then map/reduce could do allDocs({include_docs: false}) and avoid fetching from the by-seq store at all. however currently there's no way to tell before we query, so we just query with include_docs: true. could be a way to encode that info in the _id
* [x] one promise queue per view would be nice for people who have >1 view

**Comment by nolanlawson** [comment]
A lot of progress has been made on this (e.g. https://github.com/pouchdb/mapreduce/issues/242 and https://github.com/pouchdb/mapreduce/issues/240). But we're still too slow.

As a real-world example, check out this attempt to create a full-text search index for Magic the Gathering cards: https://github.com/nolanlawson/pouchdb-quick-search/issues/22

Using the WebSQL adapter, it takes 11324ms to do the initial `bulkDocs` and then 227158ms to build the index: http://jsfiddle.net/0kzcd5sh/8/

Using raw WebSQL, both operations can be done in 2458ms http://bl.ocks.org/nolanlawson/5066da7b4df350089e50

This is a really extreme example, because WebSQL has native full-text support, whereas for pouchdb-quick-search we basically need to `emit()` for every token in every doc. But it paints a pretty stark picture of where we stand: 100x slower than raw WebSQL.

**Comment by nolanlawson** [comment]
More ideas:

* [ ] use a bloom filter for doc ids so bulkDocs doesn't need to check so many
* [ ] simplify `parseDoc()`
* [ ] keep winning doc in the `by-doc` store to avoid needing to read from `by-seq`
* [ ] for auto-compaction, do compaction once at the end instead of for every doc

**Comment by daleharvey** [comment]
We are moving towards deprecating map / reduce, so dont think we need to track this

**Comment by ivan-kleshnin** [comment]
@daleharvey does new (mongo-like) API aim to provide the same functionality with easier syntax or some "selected" subset of functionality?

In Mongo there is [`mapReduce`](https://docs.mongodb.com/manual/core/map-reduce/) so I guess they were enable to express all possible ops through JSON tree. Are there any links / conversations about how this new API may look like?

**Comment by nolanlawson** [comment]
You might want to check out: https://github.com/nolanlawson/pouchdb-find
