### ISSUE TITLE
Still some race conditions in leveldb.js

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3077]
Per @daleharvey [here](https://github.com/pouchdb/pouchdb/pull/3071#issuecomment-64968174):

> So there is still some failure around this area of code - https://travis-ci.org/pouchdb/pouchdb/jobs/42497567

**Comment by daleharvey** [comment]
So I am going to close this as there isnt any actual bug or symptoms here, anything mentioned I will be taking a look at while I am looking @ https://github.com/pouchdb/pouchdb/issues/3934 so duping to that
