### ISSUE TITLE
Selenium easy setup with chrome/firefox/phantomjs support proposal

### ISSUE THREAD

**Issue by vvo** [pouchdb/pouchdb#3095]
Hi, reading http://pouchdb.com/2014/11/27/testing-pouchdb.html I saw this:

```
I would love to see a project wrap up Selenium / ChromeDriver and possibly Cordova / Appium into a nice, well-documented module that installs and boots your browser(ish) platform of choice, ready to be driven by Selenium tests.
```

Well I made one: https://github.com/vvo/selenium-standalone

It downloads the right standalone selenium and chrome driver for you then exposes a command line or programmatic API to launchy/close it.

Do you think it would fit into the pouchdb test suite? So that we can remove this horrible 20mb vendor .jar.

Thanks.

**Comment by daleharvey** [comment]
https://github.com/pouchdb/pouchdb/pull/3233 for some node-webkit work

**Comment by daleharvey** [comment]
Merged in https://github.com/pouchdb/pouchdb/commit/bbf577d369763608f42d6eb8a7e67f2c79e0eb04
