### ISSUE TITLE
IndexedDB readonly transactions don't strictly run after readwrite

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3109]
Just noticed this issue: https://github.com/mozilla/localForage/issues/154

How is this not breaking our tests in Chrome? We have lots of tests that confirm that, for a readonly transaction in the callback of a readwrite transaction, the data was actually written. Kind of surprised that this hasn't come up.

**Comment by daleharvey** [comment]
This seemed to be fixed in canary and has never shown up as an issue in how we use idb, so closing out for now, cheers
