### ISSUE TITLE
Cloudant/BigCouch replication checkpoint loop

### ISSUE THREAD

**Issue by mryellow** [pouchdb/pouchdb#3133]
Using 3.2.0 tag, which is up-to-date with master branch for `replicate.js`, `sync.js` and `checkpointer.js` as of today. 

Having some issues that remain "strange" for me. Had a good look through the checkpointer code and all makes sense, revision numbers and sequence comparison seems to all be Cloudant friendly. Maybe something to do with how target/source agree on current/last/next checkpoint, both saving the wrong one maybe, I don't see the whole replication protocol picture well enough yet to get a solid lead on it....

After somehow corrupting the local database I've tried using `PouchDB.destroy` and manually removing the IDB store (FF), to get back to a clean slate, but problems persist. Suggesting the feed from Cloudant is confusing PouchDB somewhere along the line. We're going back to sequence 0 as expected but as it crawls through the changes issues arise at the same point each time.

The symptom I'm seeing is replication jumping back and forth between 2 checkpoint sequence numbers. The same 2 numbers each fresh attempt. Every few hits it will sometimes add a few documents to the `docs_read`, `docs_written` but just keeps going back and forth between these checkpoints. While occasionally it will go to another checkpoint before ending up back in the loop.

Was thinking a test which replicates a remote DB, then destroys the local version and re-attempts replication might duplicate it but haven't had consistent success duplicating the error with this approach. 

I guess something to do with a conflict halfway through the changes or something.... Just throwing this out there, will keep digging, if someone can point me in the right direction I'm happy to spend the time.

edit: CORs, live replication.

**Comment by daleharvey** [comment]
Ok, closing this off as a huge amount of cloudant changes have now been landed, as a general issues its being tracked in https://github.com/pouchdb/pouchdb/issues/136
