### ISSUE TITLE
Using pre-calculating md5 hash values for CouchDB attachments isn't a good idea

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb#3156]
__Executive Summary__: Please remove use of pre-calculated md5 hashes for attachments, especially in test.attachments.js.

#### Long Winded Version
CouchDB, as far as I understand it, doesn't guarantee anything about the digest returned for an attachment on a document other than if an attachment with the same name on the same document should change its content then the digest value will change. My understanding is that the guarantee is modeled after etags in HTTP/1.1 which are similar in their very restricted and scoped uniqueness guarantee.

Yet, in our tests, specifically in test.attachments.js, we depend on attachments on completely different CouchDB servers having the same digest. This blew up when we tested against the Windows release of CouchDB #3152 whose digest values were different than those on Linux.

The reason, I suspect, for the digest differences in this case is that the digest is calculated after compressing the content. So if the compression algorithm or its settings differ at all between two CouchDB servers then their digests will be different. This means that if the default compression settings in CouchDB ever change on Linux then all these tests will break.

So, put another way, if you are writing a test of attachments that depends on a pre-calculated md5 hash then you can be sure that you aren't testing what you think you are testing. :)

**Comment by daleharvey** [comment]
Yeh I dont see this as being an issue we want to clean up, we can add the windows hashes if needed
