### ISSUE TITLE
Detecting blob support times out after 10 seconds

### ISSUE THREAD

**Issue by SegFaultx64** [pouchdb/pouchdb#3166]
The attempt to detect blob support locks up for 10 seconds for me on chrome 39 without actually sending anything. This wastes tons of time and greatly slows down page load. It does not occur in incognito mode weirdly...

**Comment by nolanlawson** [comment]
Closing old bugs. Please reopen if this is still an issue.

**Comment by daleharvey** [comment]
actually closing :)
