### ISSUE TITLE
changes(): last_seq is wrong when descending=true

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3176]
This is a super edge case, so I didn't try to fix it in #3136. I doubt anybody's actually using descending changes, because I don't really get what the point is.

If you look at https://github.com/pouchdb/pouchdb/blob/27da22dce59e9815eb6374957682340b9ec1d59c/tests/integration/test.changes.js#L1091-L1276, you can just uncomment those `last_seq` lines and the tests will start breaking. IIRC they were broken in all three adapters.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/50ebc3c4a30294fcba9efd886bd2c1cec7bcf664
