### ISSUE TITLE
We really need to put in retry logic for Node

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb#3185]
Right now we have no retry logic in any network request we make in Node.js. The reason for this is that we use the request.js library and it has no built in retry logic. This is apparently considered a feature by the request.js folks. They view retry logic as something that should happen at a higher layer in the stack. This means that if a TCP/IP connection goes errant that requests just fail. 

There are libraries like requestretry which handle this for us.

I am seeing a lot of connection issues when running on Windows. But I also see them in our Travis tests. For example, I suspect that [this test](https://travis-ci.org/pouchdb/pouchdb/jobs/43902709) failed due to a spurious connection error and I'm seeing tons of these errors in the perf testing.

I am experimenting in the case of replication with using the retry flag but it ends up getting used a lot because spurious connection failures are constant (sometimes multiple times in the same bucket so the whole bucket has to be retried!).

Maybe my machine is just possessed but I really think we need to at least provide node.js users with the ability to use requestretry or equivalent.

BTW, this can be tested now by using our new performance tests. The skimdb test is particularly useful. Set the number of docs to a reasonably high number (say 2000 or so) and iterations to 1 and see how long before the whole replication fails. For me it's a few seconds.

**Comment by yaronyg** [comment]
BTW, I'm running tests and currently the cost every time a batch fails on a replication is around 26 seconds! I'm downloading batches of around 400 and I'll get a failure every 10 or 15 batches. With the retry logic I discuss here we wouldn't pay that cost at all.

**Comment by yaronyg** [comment]
For the record downloading skimdb over SSL is 2x slower with PouchDB than for CouchDB. Which, given the complete lack of optimizations in things like the data layer and in our batching isn't bad at all.

**Comment by csaroff** [comment]
Has this been solved?  I've been using a [retry module](https://www.npmjs.com/package/abacus-request) to wrap all of my [request's](https://www.npmjs.com/package/abacus-request) in and I'd like to do the same thing with my pouch requests.

**Comment by daleharvey** [comment]
So we have the ability to pass in a custom `ajax` option, which will let you make the request however you want, if there is another way that makes it easier to drop in one of these retry modules into requests place then please open a new issue for that, it would definitely be something we would like to take, but we wont be putting in automatic retries into pouch core itself so closing this out, cheers
