### ISSUE TITLE
Sync Error 

### ISSUE THREAD

**Issue by jspenc72** [pouchdb/pouchdb#3192]
I am getting this error when I try to sync a couchdb to an empty pouchdb.

The synchronization successfully copies several documents however continued attempts to retrigger the sync return the same error. 

Is there anyway to obtain the _id of the document that pouchdb is failing to write so i may begin to troubleshoot the issue?

{"other_errors":[{"name":"conflict"}],"result":{"ok":false,"start_time":"2014-12-16T21:43:19.034Z","docs_read":1,"docs_written":0,"doc_write_failures":1,"errors":[{"name":"conflict"}],"last_seq":603,"status":"aborting","end_time":"2014-12-16T21:43:21.681Z"}}

**Comment by jspenc72** [comment]
I am running 3.1. I will test against master soon to see if i can replicate the issue, I'm up against a product release and will get back to this as soon as i can.

**Comment by daleharvey** [comment]
Seems to have been a fixed bug, please reopen if you still have issues
