### ISSUE TITLE
Deprecate PouchDB.destroy

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#3197]
I think @calvinmetcalf argued in favour of this a while ago and I may have objected, however just been debugging an issue with a deleted database and its pretty complex tracking where we actually destroy stuff from, it has several methods of indirection and its a very minor use case.

I think we should mark it as deprecated in the next release, then remove it in the one after

**Comment by daleharvey** [comment]
```
      // return new PouchDB('mydb').then(function (db) {
      //   return db.destroy();
      // }).then(function () {
      //   return new PouchDB('mydb', {db: require('memdown')});
      // }).then(function (db) {
      //   return db.destroy();
      // });
      return PouchDB.destroy('mydb').then(function () {
        return PouchDB.destroy('mydb', {db: require('memdown')});
      });
```
So I am dumb, the commented out code fails with a circular promise resolution chain, they seem equivalent, any ideas what I am doing wrong? (cc @calvinmetcalf)

**Comment by nolanlawson** [comment]
I basically stopped using the "PouchDB is a promise for itself" style the first time I ran into this.

Why not just:

```js
return new PouchDB('mydb').destroy().then(function () {
  return new PouchDB('mydb').destroy();
})
```

**Comment by daleharvey** [comment]
Ah cheers, that worked great

**Comment by daleharvey** [comment]
Merged in https://github.com/pouchdb/pouchdb/commit/13b9fa3ae552a5b18b5c564ddaf8630d4890283d
