### ISSUE TITLE
Remove ajax-browser.js

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#3200]
I would like to remove ajax-browser.js, have http.js call request() directly, then replace request with a version of ajax-browser / browser-request that doesnt contain any pouchdb logic mostly to clean things up and make consistent error handling easier

**Comment by jchris** [comment]
@daleharvey this is something I can help with, maybe you can help me move faster. It looks like `utils.js` requires `./deps/ajax` and ajax-browser is swapped out via it's entry in `package.json` in the top-level "browser" field.

If I remove `ajax-browser` from the build by deleting that entry, and instead modify `package.json`'s browser field to use browser-request instead of request, would that be worth running the test suite against?

**Comment by daleharvey** [comment]
@jchris I looked around for the branch that I had started with this on but I cant find it, sorry. 

So the first thing I did was remove `require("ajax")` from ``http.js`, and and made all the `ajax(` calls go through a function that just sent it direct to `request`, it needed a little bit of logic from `ajax.js` like the default parameters but it should be mostly compatible. Then you can run the tests in node and get them passing.

I am not sure we will want to use "browser-request", if I remember it was a fair bit larger than our own wrapper with a bunch of polyfills for ie6 etc that we dont need, but when its passing in node its probably worth doing a test run with it so see how close it gets to passing and to check the build size to see if I am wrong about that. then we can either use browser-request or write our own

**Comment by jchris** [comment]
The new release of request is supposed to be browserify friendly, so I started out down that path but ran into an issue upgrading request. Also I think we would not used request via browserify anyway, b/c it is so heavy. (Lots of proxy logic etc that we don't need.)

So maybe it makes sense for me to test the browser-request path instead. But I'll be surprised if any of these turn out to have multipart support either.

I'm trying to exhaust options other than enhancing ajax-browser.js with multipart. It seems at least that we should only have to write the multipart code once, for the browser and node.

**Comment by daleharvey** [comment]
Yeh fully agree at not writing twice, have you got it to a point where it works in node with just request? at that point we can test browser-request but I expect we will want to write our own and it shouldnt be a huge amount of work

**Comment by jchris** [comment]
It already works with request. Do you mean remove ajax.js also?

Right now I think testing ajax.js plus browser-request is one step to
simplifying the dependency graph.

On Tuesday, January 20, 2015, Dale Harvey <notifications@github.com> wrote:

> Yeh fully agree at not writing twice, have you got it to a point where it
> works in node with just request? at that point we can test browser-request
> but I expect we will want to write our own and it shouldnt be a huge amount
> of work
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/3200#issuecomment-70755841>.
>


-- 
Chris Anderson
http://www.couchbase.com
http://twitter.com/jchris
"Compromising before you even begin fighting is illogical." – Joshua Wong

**Comment by daleharvey** [comment]
Yeh, I guess we dont need to remove `ajax.js`, I just figured the easiest way would be to do that, but ill see if I can take a quick shot at this today

**Comment by daleharvey** [comment]
https://github.com/pouchdb/pouchdb/pull/3425 is a quick one, browser-request failed straight away and I already know its too large so started with a from scratch one

**Comment by daleharvey** [comment]
I also found my previous shot at this - https://github.com/pouchdb/pouchdb/commit/f72e4c4b18014a7ca1efd6252bc570414226577d

**Comment by jchris** [comment]
It looks like these last two could both be merged? Eg they are not mutually
exclusive.

Nice work on the tiny xhr shim!

On Wednesday, January 21, 2015, Dale Harvey <notifications@github.com>
wrote:

> I also found my previous shot at this - f72e4c4
> <https://github.com/pouchdb/pouchdb/commit/f72e4c4b18014a7ca1efd6252bc570414226577d>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/3200#issuecomment-70819061>.
>


-- 
Chris Anderson
http://www.couchbase.com
http://twitter.com/jchris
"Compromising before you even begin fighting is illogical." – Joshua Wong

**Comment by daleharvey** [comment]
Yeh we may want to get the previous version merged after this is working, fixed my other test race issues so may get a chance at making this workable today

**Comment by nolanlawson** [comment]
Nice, much cleaner than before. a82c273d5e96146b366ce55780337d629eb169ba
