### ISSUE TITLE
Adapter defaulting to WebSQL and throwing error when IndexedDB is selected

### ISSUE THREAD

**Issue by Davidx7** [pouchdb/pouchdb#3202]
PouchDB defaults to websql and refuses to init IndexedDB "Adapter is missing", even tough IndexedDB works fine and I'm already using it as you can see in the screenshot. 

![screenshot 2014-12-17 16 03 43](https://cloud.githubusercontent.com/assets/3019963/5472193/b4575428-8606-11e4-832a-2e2281a5aa02.png)

When I use the normal IndexedDB object it works just fine. 
System: everything is in localhost, with the latest version of Chrome

UPDATE: 
After throwing a few times "Adapter is missing" error it actually deleted my entire IndexedDB database that I updated using the direct object. There wore no naming conflicts

**Comment by daleharvey** [comment]
This is working in our tests as expected, if you still see a problem and can check re: the above then please reopen, cheers
