### ISSUE TITLE
Get travis + saucelabs testing on pull requests

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#3203]

**Comment by nickcolley** [comment]
As a stopgap we could maybe make sure we don't have a false positive, can we detect if it's a pull request?

**Comment by daleharvey** [comment]
We specifically let them pass right now (https://github.com/pouchdb/pouchdb/blob/master/bin/test-browser.js#L83) because otherwise its confusing for a contributor to see their test failing when its fine. 

This hasnt bitten us yet in like 2 years, if there is something scary looking then I run the PR myself manually and if anything fails it will do so when merged, so going to close this out since it would need saucelabs to fix and doesnt seem like theres motivation
