### ISSUE TITLE
PouchDB should not assume that update_seq is numeric

### ISSUE THREAD

**Issue by glynnbird** [pouchdb/pouchdb#3220]
In CouchDB 1.6, a database's update_seq is represented as an integer e.g.

```
curl  http://127.0.0.1:5984/test
{"db_name":"test","doc_count":1,"doc_del_count":0,"update_seq":1,"purge_seq":0,"compact_running":false,"disk_size":4188,"data_size":287,"instance_start_time":"1418989168372529","disk_format_version":6,"committed_update_seq":1}
```

In Cloudant, update_seq is a string: e.g.
```
{"update_seq":"60-g1AAAAG9eJzLYWBg4MhgTmGQS0lKzi9KdUhJMtXLTMo1MLDUS87JL01JzCvRy0styQGqY0pkSJL___9_ViInqg4TnDqSFIBkkj1YEztIkzxck6EBbl0OIF3xYF1ojrPArSkBpKkeYRUxPspjAZIMDUAKqG8-hm24PQbRuACicT8pnoPoPADReR_Drbg9CNH4AKIR5MksAJ6Xjlg","db_name":"grid_42","sizes":{"file":394600,"external":920,"active":5941},"purge_seq":0,"other":{"data_size":920},"doc_del_count":0,"doc_count":4,"disk_size":394600,"disk_format_version":5,"compact_running":false,"instance_start_time":"0"}
```

As of CouchDB 2.0  update_seq is an array e.g.:
```
{"db_name":"ab","update_seq":[1,"g1AAAAFDeJzLYWBg4MhgTmHgz8tPSTV0MDQy1zMAQsMcoARTIkOS_P___7MSGXAqSVIAkkn2hFQ5gFTFE1KVAFJVT0BVHguQZGgAUkCF8wmrXABRuZ-wygMQlfcJq3wAUQl0J2MWAB5TVnc"],"sizes":{"file":38064,"external":101,"active":311},"purge_seq":0,"other":{"data_size":101},"doc_del_count":0,"doc_count":1,"disk_size":38064,"disk_format_version":6,"data_size":311,"compact_running":false,"instance_start_time":"0"}
```

----------------------

As it stands, PouchDB does things like this (changes.js):
```
opts.since = info.update_seq  - 1;
```
which clearly won't work with strings or array sequence numbers.

**Comment by willholley** [comment]
Just noting a couple of places where this breaks existing behaviour:
https://github.com/pouchdb/pouchdb/blob/master/lib/changes.js#L48
https://github.com/pouchdb/pouchdb/blob/master/lib/changes.js#L149
https://github.com/pouchdb/pouchdb/blob/master/lib/changes.js#L157

**Comment by willholley** [comment]
I'm not sure what the intended semantics of the uptodate event is https://github.com/pouchdb/pouchdb/blob/master/lib/changes.js#L157. @daleharvey any insight there? Just thinking about how to implement it without relying on sequence number comparison...

**Comment by willholley** [comment]
13:55 daleharvey: wilhol: uptodate is broken and in the process of being deprecated, so I wouldnt worry about it too much
13:56 daleharvey: however the semantics, as to be replaced by 'pause' are that the paused event fires when a live replication is up to date with the source and is waiting / polling for future changes
13:57 daleharvey: it seems like the -1 on the changes seq is already causing bugs

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/fc8abbea4ea762435428389bb1ff70e39761a9cf, woot thanks
