### ISSUE TITLE
Update angular-pouchdb link to new fork

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#3231]
Looks like the most uptodate is https://github.com/angular-pouchdb/angular-pouchdb 

http://pouchdb.com/external.html#framework_adapters

**Comment by nolanlawson** [comment]
Closing, since we now list about 5 angular pouchdb wrappers on the site. Which is not great, I realize, but I don't really know what else to do for now. Here's to hoping a clear winner (or maybe two winners) emerges soon.
