### ISSUE TITLE
Migrating to 3.2.0 with memory adapter makes my tests fail

### ISSUE THREAD

**Issue by jacargentina** [pouchdb/pouchdb#3237]
I can't find the reason for this: migrating from 3.1.0 to 3.2.0 (pouchdb.js AND pouchdb.memory.js) makes my jasmine tests fail.

I've found that a simple db.get(...) doesn't calls then(...) nor catch(...) on them

When trying to create the code to post here and help me find the solution, i've found that running my tests with grunt-contrib-jasmine they fail, but when saving to _SpecRunner.html and trying to debug on google chrome, all goes fine. May be there is something related to PhantomJS?

Anybody can help me with this?

**Comment by daleharvey** [comment]
As mentioned, they need to be matching versions between the plugins and the pouchdb version, closing this out, cheers
