### ISSUE TITLE
Data corruption in LevelDB

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb#3251]
I'm running in node.js. The program I wrote did a bunch of PUT requests. I then did a GET request and got a "wrong doc returned' error [here](https://github.com/pouchdb/pouchdb/blob/c816f7c7f5cdb5726a3095574a371827ccb19290/lib/adapters/leveldb.js#L336). The stack points to [here](https://github.com/rvagg/node-levelup/blob/213e989e2b75273e2b44c23f84f95e35bff7ea11/lib/levelup.js#L205).

If anyone is going to work on this bug then just send me your email address and I'll mail you a link to the corrupt DB file.

**Comment by daleharvey** [comment]
Closing as a dupe of https://github.com/pouchdb/pouchdb/issues/3251

**Comment by yaronyg** [comment]
@daleharvey you closed this bug as a dupe of itself. ?

**Comment by daleharvey** [comment]
Sorry I meant https://github.com/pouchdb/pouchdb/issues/3216
