### ISSUE TITLE
Firefox Developer Edition not working with PDB 3.2.0

### ISSUE THREAD

**Issue by hrishiballal** [pouchdb/pouchdb#3256]
I am trying to test PouchDB on Firefox Dev Ed. When I use the following html page

```html
<html>
<head>
</head>
<meta content="text/html;charset=utf-8" http-equiv="Content-Type">
<body>

  <script src="pouchdb-3.2.0.min.js"></script>
  <script>
  var db = new PouchDB('dbname');

  db.put({
    _id: 'dave@gmail.com',
    name: 'David',
    age: 67
  });

  db.changes().on('change', function() {
    console.log('Ch-Ch-Changes');
  });

  </script>
</body>
</html>
```
I get the following error in firefox: 
![screen shot 2014-12-24 at 23 09 32](https://cloud.githubusercontent.com/assets/1588744/5551389/f962bdc6-8bc1-11e4-8399-2a6916350ffb.png)

I am on latest firefox developer edition: 36.0a2 on a iMac

**Comment by daleharvey** [comment]
So this most definitely works, tests are passing and developer edition doesnt change gecko / dom at all, its purely a different set of dev tools, so closing out but if there is some previous issue you hit feel free to reopen
