### ISSUE TITLE
Unable to use memory adapter in an Ember CLI application

### ISSUE THREAD

**Issue by backspace** [pouchdb/pouchdb#3264]
Hey, I thought I’d try out the PouchDB in-memory adapter to see if it would speed up my acceptance tests. I’m unable to create any databases, though, they fail at [this line](https://github.com/pouchdb/pouchdb/blob/3.2.0/dist/pouchdb.memory.js#L16275):

    this.idb = new IDB(idbOpts);

In Chrome I get `object is not a function`, and in Firefox the exception starts with `require<.leveldown<`.

I created a [test application](https://github.com/backspace/ember-memory-pouch) to demonstrate the problem. I also [uploaded it to Heroku](http://ember-memory-pouch.herokuapp.com/).

Maybe a solution would be to import PouchDB and the adapter in a more module-y way, but I’m using [ember-pouch](/nolanlawson/ember-pouch), which doesn’t yet support that.

But this may all be moot (for me); am I right in my suspicion that the only different for the in-memory adapter in Chrome is that it doesn’t persist the database between browser sessions? If it’s the same IndexedDB store, it wouldn’t be any faster, right?

**Comment by daleharvey** [comment]
Not been reported in a while, so assuming working
