### ISSUE TITLE
Faster IndexedDB changes() using multi-get

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3282]
Been profiling IndexedDB, and I notice that the `changes()` calls during the `temp-views` test has this staircase pattern:

![screenshot 2014-12-27 14 14 32](https://cloud.githubusercontent.com/assets/283842/5562449/c522b968-8dd2-11e4-94a3-fdeee186a10f.png)

The staircase alternates between the `docStore.get(doc._id).onsuccess = function (event) {` line and the `function onsuccess(event) {` line, i.e. an alternation between the cursor iterating through the `by-seq-store` and fetching the metadata from the `doc-store`. The fact that each callback blocks the next callback is what leads to the staircase pattern.

From previous performance tests I've found that the IndexedDB iterator is just not very fast in any browser, and in fact the fastest thing to do is to just issue many simultaneous `get`s (probably due to a lack of context-switching from JavaScript to C). Since we have monotonically increasing `seq`s, we should be able to do this in `changes` instead of just iterating one-by-one.

**Comment by daleharvey** [comment]
Closing out old optimisation bugs that havent panned out / arent being worked on, as always can reopen if we start working on them :)
