### ISSUE TITLE
.changes({live: true, since:'now'}) does not trigger for all objects added with .bulkDocs in Firefox

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb#3283]
Here's a test case:
http://jsbin.com/haguyubeju/1/edit?html,console

It fails in latest Firefox stable on Mac OS X. While all other browsers I tested with log `"\"create\" event for id = 1"` as expected, Firefox does not.

Might be related to https://github.com/pouchdb/pouchdb/pull/3270#issuecomment-68211440

**Comment by willholley** [comment]
I think the problems identified in https://github.com/pouchdb/pouchdb/pull/3442 are related. Essentially, the call which sets up the changes listener is async. Depending on timing, this means that the documents inserted during the bulk_docs call might be saved before the listener starts. Worth testing this again once  https://github.com/pouchdb/pouchdb/pull/3442 is merged. Also https://github.com/pouchdb/pouchdb/issues/3450 might mitigate the problem.

**Comment by daleharvey** [comment]
Yup fairly sure this is related to https://github.com/pouchdb/pouchdb/issues/3450, closing as a dupe
