### ISSUE TITLE
Add documentation for _local docs

### ISSUE THREAD

**Issue by tlvince** [pouchdb/pouchdb#3289]
I came across `_local` docs in [3.0.0's changelog](http://pouchdb.com/2014/08/12/pouchdb-3.0.0.html) (corresponding [CouchDB docs](http://docs.couchdb.org/en/latest/api/local.html)), which seem useful for local configs.

Would it make sense to document them within the [guides](http://pouchdb.com/guides/) section?

**Comment by daleharvey** [comment]
fixed in https://github.com/pouchdb/pouchdb/commit/b900d441044aaca8152d51a4ee05a4a534c6a050
