### ISSUE TITLE
Test Android as a Cordova app using Appium

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3299]
It's a pain in the ass, but I actually got headless Android Appium Cordova tests working.

At a minimum, I would like to test Android 19 (4.4, Kitkat) in Travis. Arguably we should also test:

* Android 17 (JellyBean, 4.2, the most common)
* with the sqlite plugin, possibly on Android 15 (4.0.3), since that's the lowest we claim to support

**Comment by daleharvey** [comment]
Cordova tests are gone
