### ISSUE TITLE
Simpler changes API (maybe a plugin)

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3311]
Watching [this video tutorial](https://www.youtube.com/watch?v=erQMOUcAdXk), I was struck by how confusing it seems to be to just listen for changes.

It seems like what people want is some kind of simple broadcast event like `'added'`, `'deleted'`, and `'modified'`. I know we have similar events already, but they're not documented, so maybe this is a good time to discuss this.

Personally I would be +1 for removing the undocumented events and adding this as a plugin. In the case of Angular particularly, it seems like there would be value in having a plugin that does `$rootScope.$broadcast()`.

**Comment by daleharvey** [comment]
Yeh I think `pouchy` etc are doing a good job here
