### ISSUE TITLE
sync doesn't return a promise

### ISSUE THREAD

**Issue by rjharmon** [pouchdb/pouchdb#3315]
Sync should return a promise, else it doesn't plug into anything that expects the default backbone interface.

**Comment by daleharvey** [comment]
So we certainly have tests ensuring that db.sync returns a promise, do remember if you do a live sync though I dont believe it will be resolved until it is cancelled in some way, cheers

https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.sync.js#L163
