### ISSUE TITLE
WebPack related error: LevelUp package.json produces errors

### ISSUE THREAD

**Issue by andru** [pouchdb/pouchdb#3319]
When packaging PouchDB in an app with WebPack, the following error gets output. The current PouchDB npm release doesn't build because of a bug recently fixed (see #3287). The current github master allows it to proceed but it then hits the error below.

Unless I'm mistaken LevelUP shouldn't be required in the client? Can it be left out of the package altogether in a similar manor to the fix for #3287 ?

Is it ok to just add `levelup: false` to the `browser` section of `package.json` or should it be replaced with a browser compatible module?
```
ERROR in ./~/pouchdb/~/levelup/package.json
Module parse failed: /Volumes/Files/Projects/Harvest/app2/node_modules/pouchdb/node_modules/levelup/package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "name": "levelup",
|   "description": "Fast & simple storage - a Node.js-style LevelDB wrapper",
|   "version": "0.18.6",
 @ ./~/pouchdb/~/levelup/lib/util.js 102:30-56
```

**Comment by svnlto** [comment]
@daleharvey I've picked this up again with more recent versions of `webpack` and `pouchdb`. I've had to make some addition to PouchDB's `package.json` file to get it working this time round:

```json
"browser": {
  "levelup": false,
  "leveldown": false
}
```

**Comment by svnlto** [comment]
I had to remove the `noParse`. So now I'm facing another issue. Not quite sure if this is the right place tho..

```bash
WARNING in ./~/pouchdb/~/lie/~/immediate/dist/immediate.js
Critical dependencies:
1:440-447 This seem to be a pre-built javascript file. Even while this is possible, it's not recommended. Try to require to orginal source to get better results.
 @ ./~/pouchdb/~/lie/~/immediate/dist/immediate.js 1:440-447

WARNING in ./~/pouchdb-authentication/~/lie/~/immediate/dist/immediate.js
Critical dependencies:
1:440-447 This seem to be a pre-built javascript file. Even while this is possible, it's not recommended. Try to require to orginal source to get better results.
 @ ./~/pouchdb-authentication/~/lie/~/immediate/dist/immediate.js 1:440-447
````
/cc @nolanlawson @calvinmetcalf

**Comment by nolanlawson** [comment]
Can you provide a PR? I'm not too familiar with webpack, but we definitely want it to at least work in webpack.

As for the warnings, they don't seem too severe. :)

**Comment by timcash** [comment]
Trying to solve this for myself now. Any more tips @svnlto ?

**Comment by svnlto** [comment]
I should have a PR ready in the next couple of days. As to the warning, try the `noParse` config option:

```js
...
noParse: /lie\.js$/
...
```

**Comment by timcash** [comment]
great that removes the warnings, thanks!

**Comment by MattKunze** [comment]
Those steps get it working for me, but it still seems to be including a ton of stuff it doesn't need.

```js
var PouchDb = require('pouchdb/dist/pouchdb');
```
generates the same warning @timcash mentioned above, but shaves ~300K off the unminified bundle for me.

**Comment by MattKunze** [comment]
I created a simple repo to demonstrate: https://github.com/MattKunze/pouchdb-webpack

```
matt@ghee ~/tmp/pouchdb-webpack (master)$ webpack
Hash: aa2663b230d833a189fb
Version: webpack 1.5.3
Time: 1091ms
           Asset    Size  Chunks             Chunk Names
  dist-bundle.js  376864       0  [emitted]  dist
normal-bundle.js  677884       1  [emitted]  normal
   [0] ./normal.js 34 {1} [built]
   [0] ./dist.js 47 {0} [built]
    + 122 hidden modules
```

*normal.js* includes PouchDB as described above, *dist.js* requires the dist version. You can see the file size difference above.

So it seems like there is a workable solution, but it would be nice to have it work as a native require so any other shared dependencies aren't duplicated.

**Comment by nolanlawson** [comment]
So this issue is fixed; I can `webpack ./lib/index.js out.js` and it works fine.

For the JSON problem, the issue is that levelup is trying to directly load
its own package.json file, which is apparently a big contentious
issue in Webpack, and the standard solution is that app devs add their
own json loader, which is what Webpack devs themselves advocate (see
[here](webpack/webpack#378 (comment)) and [here](http://mattdesl.svbtle.com/browserify-vs-webpack)).

**Comment by MattKunze** [comment]
Confirmed that requiring pouchdb directly works now without any workarounds, but I'm still seeing the file size differences between requiring *lib/index.js* vs the dist bundle. The overhead is ~400kB (~150kB minified), so it's a pretty big difference

**Comment by nolanlawson** [comment]
Can you debug Webpack to see what it's including? Browserify has [disc](https://www.npmjs.com/package/disc), but I'm not sure if Webpack has anything similar.

**Comment by nolanlawson** [comment]
Also the reason the dist bundle is so small is because we spent a lot of time optimizing our Browserify build to remove stuff we don't need. Someone now needs to go through the same dance for Webpack. :)

**Comment by MattKunze** [comment]
Was there a PR where you optimized it for browserify? That might be a good place to start.

webpack lists the modules it's including, so it's easy to know what is being included. I'll see if there's a verbose option to browserify to get similar results that can be compared.

**Comment by nolanlawson** [comment]
Can't think of a particular one; there were lots of little ones that built up over time.

Basically all of those optimizations are expressed [in this code](https://github.com/pouchdb/pouchdb/blob/88336ad236926bffce41b40c7566febade6ef7d0/package.json#L105-L117). Things like disabling `leveldown` and `fs` are due to places in the Node code where we use those modules on the Node side but not on the browser side, so we can safely disable them during browserification.

Other things are more subtle to browserify, such as the fact that we sub out `version.js` for `version-browser.js` to avoid browserifying the entire `package.json` file. Ditto for `buffer`, which was a weird case where we could only avoid browserifying the entire Node `Buffer` module by using that `buffer-browser.js` trick.

**Comment by daleharvey** [comment]
Yeh the `package.json` isnt huge, but any large increase in size is usually due to `buffer`

**Comment by Dashed** [comment]
For posterity, webpack users, do:

```js
module: {
    loaders: [
        // https://github.com/pouchdb/pouchdb/issues/3319
        {
            test: /\.json$/,
            loader: "json-loader"
        }
    ]
}
```

**Comment by nolanlawson** [comment]
@Dashed Could you add this to the ["common errors" page](https://github.com/pouchdb/pouchdb/blob/master/docs/errors.md)? Might be really helpful to people.

**Comment by Dashed** [comment]
Good call. I amended the errors page.

**Comment by nickcolley** [comment]
If we config webpack on this repo will it solve that problem?

**Comment by nolanlawson** [comment]
@nickcolley No, webpack specifically says that this kind of stuff is supposed to be solved by the end-user. `¯\_(ツ)_/¯`
