### ISSUE TITLE
blobSupport is false in Chrome 39

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3326]
Follow-up to #3325.

I noticed blob support is still false even in Chrome Canary. Seems to be due to the 404, although I'm not sure why the blob url is giving us a 404. In Firefox/IE blob support is true.

**Comment by daleharvey** [comment]
Fixed by https://github.com/pouchdb/pouchdb/commit/fce1c97e6bfaa483e8af21b5244b437f040f43fb
