### ISSUE TITLE
Modularize, publish separate npm modules

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3338]
I know this is something that @jchris has mentioned, and it seems [pretty established as a best practice](https://twitter.com/Raynos/status/551243347994497024) for Node these days.

On the other hand, there is a limit to the usefulness of modularity, and it might end up being more trouble than it's worth. So I'm opening this issue to start the discussion.

As a first step, we could do something like:

* Publish `utils.js` as `pouchdb-utils`
* Publish `merge.js` as `pouchdb-merge`
* Then we can split out the adapters, so e.g. `pouchdb-idb-adapter`, `pouchdb-websql-adapter`, `pouchdb-http-adapter`, and `pouchdb-leveldb-adapter`
* Publish `replicate.js` as `pouchdb-replicate`

The only downside I can think of is the increased complexity when submitting new PRs (e.g. if it touches multiple repos) and also running the tests in Travis. For that, I think we could mimic the express-pouchdb and pouchdb-server tests, where `pouchdb` is a `devDependency` and then we just use `npm link` to run the PouchDB test suite.

**Comment by daleharvey** [comment]
So I have wanted this for a long time, but I have also had a real problem with how to manage testing across dependencies, the solution for pouchdb-server actually looks great, or we can just keep all the modules in one repo and test them that way,

**Comment by nickcolley** [comment]
Is this only worth doing for modules that have merit on their own?

**Comment by daleharvey** [comment]
Yeh its only worth doing for modules reusable outside pouchdb, replicator and http adapters specifically, it would only make things harder if we split them into multiple repositories, seperate modules inside the same repository would be much the same as it is now but with the benefit or reusability)

For things that are highly reusable being in their own repository may actually make things easier, less overhead if that is the only thing you are working on

**Comment by nolanlawson** [comment]
That's a good point; currently none of these things need to be used outside of PouchDB itself except maybe ajax/utils (speaking from experience writing some PouchDB plugins)

The adapters and replicator are currently not used by anything but PouchDB, although they may be used by PouchDB-like JavaScript libraries. So this would really be for the benefit of those libraries.

**Comment by marten-de-vries** [comment]
I think keeping the modules in the same repo, at least at first, gives us most of the benefits without the drawbacks. We would get the reuse & more clearly documented/defined interfaces between them, but not the extra testing setups, repositories and the like.

**Comment by jchris** [comment]
I like same repo also. Seen this movie before, same repo wins.

Some kind of way to set up different browserify entrypoints would be cool, so you could do this in your app:

     var pouch = require("pouchdb/min-android-4.js")` 

and get a lighter platform-specific build.

**Comment by nolanlawson** [comment]
If we want modules in the same repo, then [we're kinda already there](https://github.com/pouchdb/pouchdb/blob/fb3a8e0e0621dadcc565bb5f47ca21dfd18fa04d/lib/index.js).

I do like the platform-specific build idea, though. Although it would probably look more like a websql-only or idb-only kind of thing, or maybe a build without `replicate` or `query`. Maybe just a few different variations on `index.js` and then build separate files into `dist`? Lodash does something similar.

**Comment by nickcolley** [comment]
Still worried that this is just abstraction for the sake of abstraction since most of the modules will only be useful to PouchDB, it'll make it more complicated for people new to the codebase?

**Comment by nolanlawson** [comment]
@nickcolley So far, this has only been requested by "advanced" users, so we would probably hide it somewhere where only they would find it. :)

BTW calculated some build sizes (min+gz):

| type | size |
| --- | --- |
| base (assuming #3359 and #3360 ) | 45246 |
| idb-only | 39569 |
| websql-only | 40014 |
| no map/reduce | 41183 |
| no replicate/sync/ajax/http (local only) | 39034 |
| idb-only + no map/reduce | 35482 |

It's neat to see what we can get away with. A custom builder ala [lodash](https://lodash.com/custom-builds) or [jquery](http://projects.jga.me/jquery-builder/) would be ace.

**Comment by marten-de-vries** [comment]
@nolanlawson wrote:
> If we want modules in the same repo, then we're kinda already there.

There's a difference: it's still possible to publish modules that are kept into the same repo to npm so others can use them too. And when treating them as npm packages instead of just files, their interface freezes (mostly, you can always release a new major version), they often get at least some info about them in a ``README.md`` file, etc.

Different browserify entrypoints is a nice idea. Maybe add an http-only one so PouchDB can function as a JS CouchDB lib?

**Comment by nolanlawson** [comment]
ah okay, I get it now :)

**Comment by daleharvey** [comment]
> Different browserify entrypoints is a nice idea. Maybe add an http-only one so PouchDB can function as a JS CouchDB lib?

This is the main reason I wanted this, installing all of level when you just want a client lib is fairly annoying

**Comment by nolanlawson** [comment]
fixed by a3007450183a0b9dcc9852e6f4376efc65793a2b, we'll have docs published in pouchdb 3.5.0
