### ISSUE TITLE
Define adapter API

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3339]
Right now the adapter "API" is fairly strict, but informally defined. You can tease it out by reading the code for the four adapters, but it would be nicer if we had an official API, so people could write their own adapters.

In particular I think it might be useful to write a custom in-memory adapter as a replacement for the MemDOWN adapter. MemDOWN has served us well, but we can get a smaller footprint and a better "here's how to build a PouchDB adapter" showcase code by just writing a new adapter.

Another exciting possibility is a custom SQLite adapter for low-memory or exotic environments (e.g. embedded systems). Node+LevelUP+SQLdown+SQLite works fine, but it's been pointed out by @jacargentina that the performance isn't great, whereas we could make some very slim modifications to the WebSQL adapter and push more logic into the database, which should improve performance in general and especially for embedded systems.

**Comment by nolanlawson** [comment]
Also an adapter API would make more sense if we published the adapters (ala https://github.com/pouchdb/pouchdb/issues/3338).

**Comment by nickcolley** [comment]
What do you think to something like https://github.com/rvagg/abstract-leveldown ?

**Comment by nolanlawson** [comment]
I think we can avoid subclassing because we use more of the `utils` style.

**Comment by jchris** [comment]
@nolanlawson That in-memory adapter you talk about would be perfect for what I'm doing. I just want something that logs everything that crosses that API boundary.

**Comment by nolanlawson** [comment]
@jchris Actually the new debug feature will do exactly that; just do `PouchDB.debug.enable('pouchdb:api')`.

**Comment by jchris** [comment]
Is there a way to enable this when the tests are running? Would a pull request to enable it conditionally be useful?

**Comment by daleharvey** [comment]
Definitely, we generally try to match node vs browser env vars, so if you check for process.env.DEBUG in https://github.com/pouchdb/pouchdb/blob/master/bin/test-browser.js and pass it via the query string, then enable it based on that, would be perfect

**Comment by tokyo-jesus** [comment]
I am very interested in making this happen. If y'all are interested I can create some documentation and an example stand-alone adapter package.

**Comment by nolanlawson** [comment]
@tokyo-jesus Yes, if you would like to define the adapter API (and possibly create an in-memory adapter to implement it!) then that would be awesome. Currently the best working examples are:

* https://github.com/nolanlawson/socket-pouch
* https://github.com/nolanlawson/worker-pouch
* https://github.com/nolanlawson/pouchdb-replication-stream

**Comment by nolanlawson** [comment]
@tokyo-jesus Yes, if you would like to define the adapter API (and possibly create an in-memory adapter to implement it!) then that would be awesome. Currently the best working examples are:

* https://github.com/nolanlawson/socket-pouch
* https://github.com/nolanlawson/worker-pouch
* https://github.com/nolanlawson/pouchdb-replication-stream
