### ISSUE TITLE
attachment names with a leading underscore should throw an error

### ISSUE THREAD

**Issue by marten-de-vries** [pouchdb/pouchdb#3357]
Currently PouchDB doesn't, which could give problems when syncing with CouchDB. A test inspired by one of couchdb-harness's:
```javascript
var db = new require('pouchdb')('test')
db.put({
  _id: "bin_doc2",
  _attachments:{
    "_foo.txt": {
      content_type:"text/plain",
      data: "VGhpcyBpcyBhIGJhc2U2NCBlbmNvZGVkIHRleHQ="
    }
  }
}).then(console.log.bind(console)); // no error
```
The error that should be thrown is:
{name: 'bad_request', message: 'Attachment name can't start with '_''}

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/57bc143a3920ecf1925ffa346d2d83e80520683d
