### ISSUE TITLE
Prepend emoji to github description

### ISSUE THREAD

**Issue by klaemo** [pouchdb/pouchdb#3365]
I propose using the appropriately named pouch emoji :pouch: so that the description reads:

":pouch: PouchDB is a pocket-sized database. http://pouchdb.com/"

Alternatively: handbag :handbag:, briefcase :briefcase: or purse :purse: 

Why? Because it's fun.

**Comment by daleharvey** [comment]
Heh I tried to do this with a koala before but it didnt work

**Comment by klaemo** [comment]
A koala is cute too :) 
You have to use the `:koala:` style. I tried copy and pasting at first, but that didn't work.

**Comment by nickcolley** [comment]
:arrows_clockwise:
:arrows_counterclockwise:
:recycle:

**Comment by daleharvey** [comment]
Done! thanks

**Comment by nolanlawson** [comment]
+1000
