### ISSUE TITLE
Track February Release

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#3371]

**Comment by daleharvey** [comment]
Deprecate local_seq - https://github.com/pouchdb/pouchdb/issues/3367
Deprecate PouchDB.destroy - https://github.com/pouchdb/pouchdb/issues/3197

`uptodate` has already been deprecated, so a major version bump will be coming shortly, may as well get these all in

**Comment by nolanlawson** [comment]
buncha map/reduce perf improvements: https://github.com/pouchdb/mapreduce/pulls

**Comment by daleharvey** [comment]
So going to use this to track things we should mention in the release, news / interesting items etc

pouchdb-fauxton in the chrome store https://t.co/kTY866C5mV

**Comment by nolanlawson** [comment]
soon to be in the firefox store as well. can you pull some strings and accelerate that? ;)

worth mentioning pouchdb-find. I'm trying to find some time to keep improving it.

**Comment by daleharvey** [comment]
Woot, released
