### ISSUE TITLE
SecurityError DOM Exception 18 on Chrome for iOS on iPhone

### ISSUE THREAD

**Issue by jkndrkn** [pouchdb/pouchdb#3382]
Hi there. I really appreciate the work that goes into PouchDB. Working with it has been great so far. I've had one major issue with it so far, though.

I am using PouchDB 3.2.1 on a web application targeted for Chrome on iOS. The below error also appears in PouchDB 3.2.0.

When trying to create a connection to a local database on Chrome on iOS, PouchDB uses that browser's WebSQL database. This, however, fails intermittently with SecurityError: DOM Exception 18 when running the application on both iPhone 5 and iPhone 5s. I have not been able to reproduce this error on my iPad 5 yet.

I am creating a new PouchDB database as follows:

    var localDBName = "dbd8008497c6f368d";
    self.localPouch = new PouchDB(localDBName, {size: 50});

I have also tried setting size to 49, 1, and 0 and not setting size at all.

    Here is a stacktrace sourced from BugSnag:
    
    [native code]:4232 openDatabase
    http://192.168.1.144:8000/app/bower_components/pouchdb/dist/pouchdb.js:4232:48 openDB
    http://192.168.1.144:8000/app/bower_components/pouchdb/dist/pouchdb.js:4275:18 WebSqlPouch
    http://192.168.1.144:8000/app/bower_components/pouchdb/dist/pouchdb.js:5655:40
    [native code]:0 Promise
    http://192.168.1.144:8000/app/bower_components/pouchdb/dist/pouchdb.js:5570:28 PouchDB

Here is the code near line 4232 of pouchdb.js:

    var cachedDatabases = {};
    
    var openDBFunction = (typeof navigator !== 'undefined' &&
          navigator.sqlitePlugin &&
          navigator.sqlitePlugin.openDatabase) ?
        navigator.sqlitePlugin.openDatabase.bind(navigator.sqlitePlugin) :
          (typeof sqlitePlugin !== 'undefined' && sqlitePlugin.openDatabase) ?
        sqlitePlugin.openDatabase.bind(sqlitePlugin) :
          (typeof openDatabase !== 'undefined') ?
        openDatabase :
        null;
    
    function openDB(name, version, desc, size) {
      var db = cachedDatabases[name];
      if (!db) {
        db = cachedDatabases[name] = openDBFunction(name, version, desc, size);
      }
      return db;
    }

Refreshing the the browser page does not fix the issue. Neither does closing the browser tab and re-opening the page. The only way I can fix the issue is by force-quitting the browser and relaunching the application. However, this is not an acceptable workaround for our users.

This question is also posted to stackoverflow: http://stackoverflow.com/questions/27905453/overcoming-securityerror-dom-exception-18-in-pouchdb-on-mobile-chrome-for-ios

**Comment by daleharvey** [comment]
We see this very regularly in our automated tests for iphone, https://travis-ci.org/pouchdb/pouchdb/jobs/46726739, it looks like the same problem, we also pass intermittently, I dont know what causes it yet, but certainly one very keep to track down

**Comment by nolanlawson** [comment]
this issue has been reported before. it's not clear what's causing it, but it may be an iOS 8 issue. most likely somebody needs to write a detailed bug report and file it on webkit.

only workaround I'm currently aware of is to use the localstorage plugin, but only on Chrome for iOS. :(

BTW most of the iOS 8 bugs in IndexedDB/WebSQL have been catalogued in [this article and in the comments](http://www.raymondcamden.com/2014/9/25/IndexedDB-on-iOS-8--Broken-Bad).

**Comment by nolanlawson** [comment]
Trying to write a test to repro: http://bl.ocks.org/nolanlawson/2cf0c9839ea8b64439ba

Oddly I am getting DOM Exception 11 instead of 18. Can anyone else confirm? Or write a test that reproduces this error?

**Comment by jkndrkn** [comment]
@nolanlawson, yes. I also saw DOM Exception 11 on my iPhone 5s. Maybe try specifying different database names for each of the two tests?

**Comment by jkndrkn** [comment]
It looks like this issue has already been reported to Buzilla: https://bugs.webkit.org/show_bug.cgi?id=137760

**Comment by nolanlawson** [comment]
That bug was reported by me. :) It's for the WKWebView, and it seemed to be consistent rather than intermittent, so I suspect it's another issue.

I can report the DOM Exception 11 issue to the WebKit tracker, but do you have a live example that can repro the DOM Exception 18 issue (in Chrome for iOS)?

**Comment by jkndrkn** [comment]
I suspect that DOM Exception 11 might be expressing itself because you are passing the optional callback to openDatabase. I am currently working on a live example that can reproduce DOM Exception 18 but it is hard to know if it is working or not because DOM Exception 18 is intermittent -_-

**Comment by jkndrkn** [comment]
OK, this should work: http://bl.ocks.org/jkndrkn/fd0074554047c3c0d8ac

I changed the "size" to 50000000 (50 million instead of 5 million) and removed the callback. I was able to have Chrome in iOS show DOM Exception 18.

**Comment by jkndrkn** [comment]
I have filed a bug to the WebKit bug tracker using the above test case: https://bugs.webkit.org/show_bug.cgi?id=140443

If someone could review my entry to the bug tracker and suggest possible changes, I would very much appreciate it.

**Comment by nolanlawson** [comment]
Added a comment to your bug. Looks good to me; hopefully they will fix soon!

**Comment by jkndrkn** [comment]
Yay, thank you!

**Comment by jkndrkn** [comment]
OK, a related issue.

If I try to create a local database and DOM Exception 18 is thrown, I am unable to catch this error.

    try {
      self.localPouch = new PouchDB(localDBName, {size: 50});
    } catch(e) {
      alert(e); // The catch-block never gets called
    }

Any ideas on how I might handle this error?

**Comment by nolanlawson** [comment]
Try:

```js
var db = new PouchDB(localDBName, {size: 50});
if (!db.adapter) { // neither websql nor idb supported
  // fall back to http-only (no offline)
  db = new PouchDB('http://whatever')
}
```

The LocalStorage adapter should also automatically fall back from WebSQL to LocalStorage. Let me know if it doesn't, and I'll fix it.

**Comment by jkndrkn** [comment]
Thanks, I will try that. I'm pretty sure that execution halts near line 4232 of pouchdb.js when DOM Exception 18 is thrown, but I will double-check to be sure.

**Comment by jkndrkn** [comment]
Yes, that is indeed the case. Execution halts at `var db = new PouchDB(...`.

**Comment by nolanlawson** [comment]
Sounds like we should probably create a test DB in `valid()`, wrap it in a try/catch, and then delete it right afterwards.

**Comment by nolanlawson** [comment]
If you're interested in attacking this problem and providing a PR (I don't have time right now), the function to modify is [this one](https://github.com/pouchdb/pouchdb/blob/master/lib/adapters/websql/websql.js#L995-L997). It should return false if the database is throwing 11s or 18s, in which case it can fall back to the localStorage adapter or you can use `db.adapter` to detect brokenness.

**Comment by nolanlawson** [comment]
Crap, I forgot you can't delete databases in WebSQL. It is going to confuse the hell out of people to see an empty `_pouchdb_test_valid_websql` database floating around... >_<

Ugh. I'm not happy about this, but I guess some small number of people out there in the world have iPhones and some of them are using WKWebView/Chrome. :stuck_out_tongue:

**Comment by nolanlawson** [comment]
Since the WebKit bug hasn't gotten any responses yet, I filed on Chrome as well: https://code.google.com/p/chromium/issues/detail?id=453702

WKWebView I'm less worried about, because nobody's using it yet (e.g. Cordova). But Chrome for iOS has a pretty hefty market share, so it's irritating that we can't use either IndexedDB or WebSQL on it.

**Comment by nolanlawson** [comment]
Sorry @jkndrkn, but my attempted fix is breaking Safari, iPhone, and PhantomJS, so I'm not sure how to proceed. Any help would be appreciated.

**Comment by nolanlawson** [comment]
@jkndrkn I can't repro either bug anymore. I'm using Chrome 40.0.2214.69 in iOS 8.1.3 on an iPhone 6 Plus. Can you confirm whether it's working for you?

**Comment by jkndrkn** [comment]
@nolanlawson, thank you for continuing to look into this. I will try and see if I can reproduce using the latest Chrome and iOS on my iPhone test devices.

**Comment by jkndrkn** [comment]
So far unable to reproduce using iOS 8.1.3 on iPhone 5. I will ask other folks on my team to see if they can reproduce.

**Comment by nolanlawson** [comment]
Cool beans; I let the webkit and chromium devs know.

**Comment by jkndrkn** [comment]
I have had other folks on my team test on their iPhones and it appears to be fixed. One user running 8.1.3 and Chrome 39.X still experienced the DOM Exception 18 issue, but after upgrading to Chrome 40.X, clearing local data, and force-quitting, the exception went away and has not returned.

**Comment by soitgoes** [comment]
+1.  IOS Security Error DOM Exception 18 when requesting a size of 50 on version 5.3.2
