### ISSUE TITLE
Match CouchDB handling of GET somedoc?open_revs=true when somedoc doesn't exist

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#3395]
In CouchDB 1.x a call to open_revs=true on a non-existent document results in a crash - the response is a successful (200) response with junk in the body. In CouchDB 2.x this is fixed and the call correctly returns a 404 (see https://issues.apache.org/jira/browse/COUCHDB-2517) as you might expect.

PouchDB seems to match the broken behaviour of CouchDB 1.x and returns a 200 response but should probably return a 404 in this situation as well.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/45908f4fe888797ae600e4f591da770cab22be38
