### ISSUE TITLE
Revisit blob support in Chrome

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3397]
Based on discussion in [this Chromium issue](https://code.google.com/p/chromium/issues/detail?id=447836), it looks like we may be able to fix this bug in v37+ by making sure our transactions have the same scope (which means same object stores I guess?).

**Comment by nolanlawson** [comment]
I tested it out, and there doesn't seem to be a workaround. @inexorabletash informs me he doesn't think there's a workaround either.

**Comment by nolanlawson** [comment]
So TL;DR, we're not actually going to support native blobs in Chrome IndexedDB until that bug is fixed. So we'll need to update our docs.

**Comment by daleharvey** [comment]
https://github.com/pouchdb/pouchdb/commit/75cadbecfdb716bf9588d53f055f3913ad36398d
