### ISSUE TITLE
Better details in db.info()

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3398]
E.g.:

```js
{
  ...
  adapter: 'websql',
  websql_source: 'sqlite plugin'
}
```

or

```js
{
  ...
  adapter: 'idb',
  idb_blob_support: false
}
```

**Comment by nolanlawson** [comment]
BTW for anybody who wants to implement this, it should be super easy. You just change the `_info()` function in `websql.js` and `idb.js`.

**Comment by ScreenDriver** [comment]
:+1:

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/ac2895accde905c3d63e02e660b998e8d706c757
