### ISSUE TITLE
Does PouchDB use the HTTP OPTIONS method?

### ISSUE THREAD

**Issue by scoughlin** [pouchdb/pouchdb#3399]
Our off-line app uses pouchdb-3.2.0 and Cloudant.  When questioning Cloudant on a bill, they told me there were, "...a total of 591,069 requests on Dec19th . Of these, 278,721 of them are an HTTP OPTIONS method..."
Could these requests originate from PouchDB?
Thanks,
- Shawn

**Comment by marten-de-vries** [comment]
If you have enabled (and are using) CORS, then yes. Otherwise, no.

**Comment by nolanlawson** [comment]
Another good way to minimize the number of requests you make:

* Use the "every doc is a delta pattern" (allows us to optimize requests under the hood)
* Use [pouchdb-dump](https://github.com/nolanlawson/pouchdb-dump-cli) and [pouchdb-load](https://github.com/nolanlawson/pouchdb-load)

**Comment by yathit** [comment]
OPTIONS request has [Access-Control-Max-Age](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Max-Age), which should set about 10 minutes to cache in the browser so that it is not called every time CORS request make.

**Comment by daleharvey** [comment]
Unfortunately CORS cache only applies per url, we never make requests to the same url during replication so the cache is useless, the inability to reduce the number of OPTIONS requests we send is a flaw in the spec imo

**Comment by yathit** [comment]
OPTIONS is cached per origin. Chrome ignore max-age if set more than 10 minutes.

**Comment by daleharvey** [comment]
The preflight request cache is against the url, http://www.w3.org/TR/cors/#preflight-result-cache-0, http://stackoverflow.com/questions/12013216/how-to-apply-cors-preflight-cache-to-an-entire-domain links to a bunch of the mailing list history discussing the feature.

Closing out since there isnt anything we can do about this at the moment

**Comment by scoughlin** [comment]
Let's see if I understand this;
So... 
Cloudant has CORS turned on to allow PouchDB to PUT, GET, etc. because they have different origin domains. 

But...
This causes two Requests for almost every Request from PouchDB to Cloudant. One for the HTTP OPTIONS, and one for the GET or PUT or whatever. 

So...
If Cloudant allowed me to point a domain at their server and I turned off CORS on Cloudant. Would this solve the issue? Example: if my domain was www.shawn.com and I pointed cloud.shawn.com at Cloudant

Thanks! 
- Shawn

**Comment by nolanlawson** [comment]
Yes, that is called a CORS proxy. :) It's not a bad solution to the "too many requests" problem.

**Comment by daleharvey** [comment]
Requests on the same domain arent subject to CORS, so yes you would reduce all those OPTIONS requests.

However as far as I remember the origin takes into account the sub domain, your database and your website would need to be served from www.shawn.com (or any other domain, but it would need to be the same)

**Comment by scoughlin** [comment]
Well, as it turns out, Cloudant doesn't charge for HTTP Options Requests, so this was not the cause of my rather large bill. I may, however, still implement a CORS proxy. Thanks Nolan and Dale!
- Shawn

**Comment by scoughlin** [comment]
Still trying to determine why I have so many HTTP PUTs and POSTs to Cloudant. Does anyone know of a tool that can help me monitor the requests? WireShark, Charles and similar pcap-apps don't show individual PUTs and GETs, seeing the Sync as one transaction. Thanks!

**Comment by daleharvey** [comment]
Currently replication uses a huge amount of requests, working on reducing it but for now its expected, but not sure why you arent seeing seperate requests in wireshark, they are most certainly individual requests

**Comment by nolanlawson** [comment]
there are tips here for dealing with slow replication: http://pouchdb.com/2014/08/29/pouchdb-3.0.3.html

**Comment by scoughlin** [comment]
Thanks Nolan. 
I did find that a subdomain will not work without CORS. Any CORS alternatives? I'd love to cut down on those HTTP requests.

**Comment by nolanlawson** [comment]
@scoughlin The only alternatives are a CORS proxy or serving all your requests from the same subdomain... :(

**Comment by scoughlin** [comment]
On the numerous HTTP REQUESTS to Cloudant problem.
Are the Requests that only contain a 'nonce' necessary?
Example:
     "GET /families/?_nonce=qCbT0Ac6B0GSBlzc HTTP/1.1"
I see about 52% of my GET Requests are this type.

Thanks guys!
- Shawn

**Comment by nolanlawson** [comment]
@scoughlin  You can disable that by doing `{ajax: {cache: true}}`, but then you will probably start to see weird behavior in IE due to their aggressive caching. You can user-agent sniff for IE in those cases.

**Comment by scoughlin** [comment]
Implementing like this:
 new PouchDB(currentdb, {size: 10,ajax: {cache: true},cache: true});
didn't eliminate the _nonce requests.
Did I miss something?
Thanks,
-Shawn

**Comment by nolanlawson** [comment]
The option is on your remote pouch, not your local pouch.

```js
var local = new PouchDB('foo');
var remote = new PouchDB('http://site.com/db', {ajax: {cache: true}});
local.replicate.to(remote); // or whatever
```
