### ISSUE TITLE
Use pouchdb-upsert

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3410]
If we require this in both `pouchdb` and `pouchdb-mapreduce`, then it ought to reduce the overall build size, because the function won't be duplicated. Plus it's more modular.

**Comment by daleharvey** [comment]
https://github.com/pouchdb/pouchdb/commit/a258a54c6ac6797b12505b41a339e4e8acf465ee

**Comment by nolanlawson** [comment]
https://github.com/pouchdb/mapreduce/commits/1f67e2fc082cc138fccec3bbb9797d61a33c00c5
