### ISSUE TITLE
Adapter for sqlite only

### ISSUE THREAD

**Issue by m00g33k** [pouchdb/pouchdb#3416]
Hi, I know that pouchdb use sqlite automatically if its detected but I was thinking that it would be better if developers can force pouchdb to use sqlite. If no sqlite or sqlite plugin is detected, an error will occur. I believe this would be beneficial to mobile developers out there.

**Comment by nolanlawson** [comment]
I worry that might be confusing; do you think a solution like https://github.com/pouchdb/pouchdb/issues/3398 would be acceptable?

**Comment by m00g33k** [comment]
I believe there would be an instance that this would be needed badly. I'm currently developing a mobile application with large data and obviously using sqlite is inevitable. But solution #3398 would suffice my needs. Thanks! I hope I can contribute to this project someday somehow :+1:

**Comment by daleharvey** [comment]
Yeh, we are trying to stick to a one pouchdb core download as it makes providing support and choice for the end user easier, I have also filed another bug that I think would be useful for your purpose, to print the selected adapter as part of the debug log - https://github.com/pouchdb/pouchdb/issues/3417

Not sure we will be able to stick to a one download model forever, but I think we can resolve this one suitably for now without splitting them out
