### ISSUE TITLE
Implement _bulk_get aka _bulk_revs

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3424]
Counterpart to https://github.com/pouchdb/express-pouchdb/issues/196.

**Comment by nolanlawson** [comment]
It's debatable, though, whether we actually want to implement a `db.bulkGet()` or `db.bulkRevs()`. For local-local replication it doesn't offer any benefit, and may actually confuse users.

As a first pass, though, we can simply update `replicate.js` to use a server-side bulk endpoint if it exists.

**Comment by dholth** [comment]
See also https://github.com/dholth/pouchdb-bulk-get

**Comment by robertkeizer** [comment]
+1

**Comment by nolanlawson** [comment]
@daleharvey On the CouchDB side ([COUCHDB-2310](https://issues.apache.org/jira/browse/COUCHDB-2310)), there definitely seems to be an "intent to ship" in both 1.x and 2.x.

So how do you feel about adding `db.bulkRevs()`? I'm leaning towards implementing it at the PouchDB API level, i.e. not simply an endpoint on PouchDB Server that wraps `Promise.all` and `db.get`. Although most endusers will never use it themselves, it's nice for consistency's sake.

**Comment by daleharvey** [comment]
I am not so sure about this, if couchdb do add it then we probably have to for compat, but I think we would be able to spec and implement stream before this bulkrevs is ever released and replication-stream is a much more desirable end goal, going from what we have now to adding bulkDocs / bulkRevs (+detection) to adding Streaming + detection doesnt seem ideal

**Comment by nolanlawson** [comment]
So you think we should just jump directly to the replication-stream stuff?

**Comment by robertkeizer** [comment]
I'm finding that a middleware layer that performs the replication-stream stuff works fairly well. Have some hacky code working for express-pouchdb but need to clean it up before committing.

Personally I'd like to see Pouch implement this without replication-stream functionality as soon as couch has it.

**Comment by dholth** [comment]
_bulk_revs (a more efficient API that can replace the 1-at-a-time
GET API) is useful for replication, but it's not necessarily just
about replication. You might just want to get a lot of things with a
single call.


On Mon, Feb 9, 2015, at 08:50 AM, Robert Keizer wrote:
> I'm finding that a middleware layer that performs the
> replication-stream stuff works fairly well. Have some hacky code
> working for express-pouchdb but need to clean it up before committing.


> Personally I'd like to see Pouch implement this without
> replication-stream functionality as soon as couch has it.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/pouchdb/pouchdb/issues/3424#issuecomment-73510940

**Comment by daleharvey** [comment]
> You might just want to get a lot of things with a single call.

Hrm, I thought `allDocs` supported fetching multiple documents, doesnt look like so.

If couch implements it then we should, but in terms of focus for replication improvements I think -stream is the best thing to focus on, it is going to be very hard to implement any of these new changes well since they will be implemented at different times across different platforms, I think its worth focussing on what gets us the best bang for buck

**Comment by dholth** [comment]
Maybe it does. The thing I found irritating was that none of the proposed or existing _bulk_ APIs supported ALL of the parameters allowed in a GET request, they are arbitrarily different making them harder to learn.

**Comment by willholley** [comment]
@nolanlawson when testing against the CouchDB implementation, our attachment tests are failing. Looking specifically at suite2 test.attachments.js- local:http / Attachments replicate back and forth, I see the following requests around the failure:

without _bulk_get:

    GET http://localhost:2020/test_attach_remote/doc?revs=true&open_revs=[%221-67421d156cc0ba65d13b9c601c558381%22]&_nonce=1441282816675

   returns

    [{ "ok": {
	  "_id": "doc",
	  "_rev": "1-67421d156cc0ba65d13b9c601c558381",
	  "_revisions": {
	     "start": 1,
	     "ids": [
	        "67421d156cc0ba65d13b9c601c558381"
	     ]
	  },
	  "_attachments": {
	     "foo.txt": {
	        "content_type": "text/plain",
	        "revpos": 1,
	        "digest": "md5-UVHkefsf5MqAl/2ALjx5Zg==",
	        "length": 3,
	        "stub": true
	     }
	  }
    }}]

with _bulk_get:

     POST http://localhost:2020/test_attach_remote/_bulk_get?_nonce=1441284778447
     {"revs":true,"attachments":true,"binary":true,"docs":[{"id":"doc","rev":"1-67421d156cc0ba65d13b9c601c558381"}]}

returns

     {"results": [{
      "id": "doc", 
       "docs": [{
        "ok": {
         "_id":"doc",
         "_rev":"1-67421d156cc0ba65d13b9c601c558381",
         "_attachments":{
          "foo.txt":{
           "content_type":"text/plain",
           "revpos":1,
           "digest":"md5-UVHkefsf5MqAl/2ALjx5Zg==",
           "length":3,
           "stub":true
          }
         }
        }
       }]
     }]}

so the core information around the attachment looks the same.

However, when this is processed at https://github.com/pouchdb/pouchdb/blob/39da6013d74685189fcdf5bc2c617db5b76e88bd/lib/deps/docs/preprocessAttachments.js#L87, the docInfo object is very different.

without _bulk_get:

     	{
	  "metadata": {
	    "id": "doc2",
	    "rev": "1-67421d156cc0ba65d13b9c601c558381",
	    "revisions": {
	      "start": 1,
	      "ids": [
	        "67421d156cc0ba65d13b9c601c558381"
	      ]
	    },
	    "rev_tree": [
	      {
	        "pos": 1,
	        "ids": [
	          "67421d156cc0ba65d13b9c601c558381",
	          {
	            "status": "available"
	          },
	          []
	        ]
	      }
	    ]
	  },
	  "data": {
	    "_attachments": {
	      "foo.txt": {
	        "data": {},
	        "digest": "md5-rL0Y20zC+Fzt72VPzMSk2A==",
	        "content_type": "text/plain",
	        "revpos": 1,
	        "length": 3
	      }
	    }
	  }
	}

with bulk_get:

      	{
	  "metadata": {
	    "id": "doc2",
	    "rev": "1-67421d156cc0ba65d13b9c601c558381",
	    "rev_tree": [
	      {
	        "pos": 1,
	        "ids": [
	          "67421d156cc0ba65d13b9c601c558381",
	          {
	            "status": "available"
	          },
	          []
	        ]
	      }
	    ]
	  },
	  "data": {
	    "_attachments": {
	      "foo.txt": {
	        "digest": "md5-UVHkefsf5MqAl/2ALjx5Zg==",
	        "content_type": "text/plain",
	        "length": 3,
	        "revpos": 1,
	        "stub": true
	      }
	    }
	  }
	}

Note that when using _bulk_get, the attachment remains as a stub and the digest is different (but matches what was returned from the server in both cases).

**Comment by willholley** [comment]
I think the problem is simply that we don't call fetchAttachments for attachment stubs returned by _bulk_get

**Comment by nolanlawson** [comment]
_bulk_get will be released in pouchdb 5.0.0 and available in the next release of pouchdb server

**Comment by nolanlawson** [comment]
this is merged now

**Comment by dholth** [comment]
:-)

**Comment by dholth** [comment]
So this means PouchDB will attempt to use _bulk_get for replication now?

**Comment by willholley** [comment]
yep - if the endpoint is there, it will use it.

**Comment by ronyrun** [comment]
which couchDB version will work with _bulk_get  ?

**Comment by nolanlawson** [comment]
CouchDB 2.0+ (unreleased) and PouchDB Server 1.0.0. Cloudant soon.

**Comment by ronyrun** [comment]
Thank you @nolanlawson

**Comment by yaronyg** [comment]
@nolanlawson @daleharvey At the risk of sounding like a hopeless fan boy this is super cool! Thank you!!!!

BTW, as a side note today we did a demo using PouchDB with memdown on top of [node.ch](https://github.com/Microsoft/node-uwp) on top of [Windows IoT](https://dev.windows.com/en-us/iot) on top of a Raspberry PI 2. It worked super well! So my thanks only increases!

**Comment by nolanlawson** [comment]
@yaronyg woop woop! :)
