### ISSUE TITLE
Changes 'now' send old event onload of node-webkit app

### ISSUE THREAD

**Issue by Yimiprod** [pouchdb/pouchdb#3430]
I have created a node-webkit app using pouchdb as local db.

When i first load the app, the pouchdb changes, with since set to 'now' send the last event done on the precedent session.

Like if i delete an item in the db, close the app, then open it again, the changes send me the "delete" event for this item.

**Comment by daleharvey** [comment]
Yeh this has been an open issue for a while, we probably want to remove the `- 1` calculation we do in https://github.com/pouchdb/pouchdb/blob/master/lib/changes.js#L149, and see what that breaks

But theres already an issue open for this @ https://github.com/pouchdb/pouchdb/issues/2800 closing as dupe
