### ISSUE TITLE
can't replicate using couchdb procotol

### ISSUE THREAD

**Issue by scottwhite** [pouchdb/pouchdb#3433]
We have an app where we rolled are own sync server (reasons).  We have mobile clients using couchbase that are working without issue.  When I try to do a pull replication I kept getting a method missing error.  Seems in lib/replicate.js  the processDiffDoc is expecting an array back from a get by id call.  According to the couchdb protocol
http://docs.couchdb.org/en/latest/api/document/common.html#get--db-docid
It should not be an array.

Am I missing something?

**Comment by daleharvey** [comment]
The `open_revs` parameter causes an array to be returned, your server will need to implement that behaviour. 

```
$ curl -X GET http://127.0.0.1:5984/test/test?open_revs=all -H 'Accept: application/json'
[{"ok":{"_id":"test","_rev":"1-967a00dff5e02add41819138abb3284d"}}]
```

I am interested in the reasons you are writing your own server, it seems like there are (non erlang) couchdb implementations for pretty much any platform right now? its a hard thing to get right

**Comment by scottwhite** [comment]
Sweet thanks for the prompt reply, I didn't read enough.
This also helped
http://wiki.apache.org/couchdb/HTTP_Document_API

Our app is based off google big table (in google cloud platform).   We are using the client sync to save us from doing it there.  So the pain is only on the server side (and it's been fun).

We are using pouchdb to see if we can just use the same sync on the web as the mobile and save us some extra coding.

**Comment by scottwhite** [comment]
Sorry forgot to close
