### ISSUE TITLE
Remove db.close()

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3437]
It was never documented, and apparently it's unnecessary (follow-up to discussion in https://github.com/pouchdb/pouchdb/issues/3429).

**Comment by daleharvey** [comment]
So I remember we had a lot of problems implementing migrations that needed `close`, its small enough that I think its less hassle to keep it private and let it stay 

https://github.com/pouchdb/pouchdb/blob/master/tests/integration/browser.migration.js#L109

**Comment by SukantGujar** [comment]
@nolanlawson So when my express app which uses PouchDB shuts down, do I need to invoke `close` or not? Or is it completely safe to ignore PouchDB instances during quit?

**Comment by nolanlawson** [comment]
I don't understand what you mean. You mean when you shut down your server, is there anything special you need to do with PouchDB databases? The answer is no.

**Comment by SukantGujar** [comment]
Yes @nolanlawson. The application has an express server, which spawns up a PouchDB instance to store user sessions. So looks like we are good 😃.
Apart from this scenario, would there be any case where sudden shutdown of the host (server-side) or refreshing the browser (client-side) which can result in the PouchDB in an inconsistent state 🤔?

**Comment by nolanlawson** [comment]
Nope, PouchDB uses transactions on top of LevelDB for all its write operations, so you should be able to shut it down in the middle of a transaction and it'll be fine.

**Comment by jaredly** [comment]
A changes stream is terminated when the database is `close`d, correct? I want a way to cancel all changes streams from a database, and `close` seems like the thing.

**Comment by nolanlawson** [comment]
`close()` does not guarantee that the changes stream stops, no. Although I think in practice it does, at least for IDB, because it should throw an IDB error.

If you want to cancel all ongoing changes, then unfortunately you'll have to keep a handle on all changes and manually `.cancel()` them.

**Comment by jaredly** [comment]
:( ok, yeah, that's what I'm doing. Would be awesome to have a `cancelAllChanges` or something

**Comment by davedoesdev** [comment]
So `close()` is documented: https://pouchdb.com/api.html#close_database
Should it be okay to use?

**Comment by nolanlawson** [comment]
anything we document, we are committed to, so yeah
