### ISSUE TITLE
PouchDB 3.2.1 returned to defaulting to IndexedDB in a UIWebView on iOS

### ISSUE THREAD

**Issue by rsutphin** [pouchdb/pouchdb#3440]
In an iOS UIWebView, PouchDB 3.2.1 started selecting IndexedDB as the default adapter. It doesn't appear that this change was intentional; it arose out of the changes to [IdbPouch#valid](https://github.com/pouchdb/pouchdb/blob/3f9aaeeea6875128fb5151ac86bde82174aa5c90/lib/adapters/idb/idb.js#L1058-L1070) in commit 3f9aaee. The check was:

    return !isSafari && global.indexedDB && global.IDBKeyRange

And after 3f9aaee is:

    return !isSafari && typeof indexedDB !== 'undefined' && typeof IDBKeyRange !== 'undefined'

In a UIWebView, `isSafari` is false (`navigator.userAgent` is something like `"Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12B440 (5608898592)"`; no "Safari"), and `typeof indexedDB` and `typeof IDBKeyRange` are both `"object"`. The previous check worked to skip IndexedDB because the _value_ of `indexedDB` in a UIWebView is  `null`.

I haven't tested it, but I don't think that iOS Safari would have this problem — it does have the string "Safari" in its UA.

The effect of using IndexedDB on iOS is that database accesses just never resolve — no error, no data.

This change will affect Cordova applications using PouchDB. In my app, I'm planning to work around it by forcing WebSQL on iOS during setup.

**Comment by nolanlawson** [comment]
Can you submit a pull request? Looks like our `isSafari` check could be something like:

```js
var isSafari = typeof openDatabase !== 'undefined' &&
  /(Safari|iPhone|iPad|iPod)/.test(navigator.userAgent) &&
  !/Chrome/.test(navigator.userAgent);
```

**Comment by rsutphin** [comment]
Sure thing. PR is #3441.

**Comment by daleharvey** [comment]
Fixed by https://github.com/pouchdb/pouchdb/commit/929e1780ee63c54fefa8fc9c4c1671a48773c3f0
