### ISSUE TITLE
Inconsistent date deserialisation

### ISSUE THREAD

**Issue by mtford90** [pouchdb/pouchdb#3444]
Hi - I'm running PouchDB 3.2.1.

The following test succeeds:

```js
it('get date', function (done) {
    db.post({date: new Date()}).then(function (resp) {
        db.get(resp.id).then(function (doc) {
            assert.ok(doc.date instanceof Date);
            done();
        });
    }).catch(done);
});
```

However this one fails:

```js
it('query date', function (done) {
    db.post({date: new Date()}).then(function () {
        db.query({
            map: function (doc) { emit(doc._id, doc) }
        }).then(function (objs) {
            assert.equal(objs.rows.length, 1);
            assert.ok(objs.rows[0].date instanceof Date);
            done();
        }).catch(done);
    }).catch(done);
})
```

In the second case, the date field is a `string` rather than a `Date`. This should probably be consistent - i.e. both being dates?

**Comment by nolanlawson** [comment]
Yeah, you need to turn all your dates into strings/numbers before storing: https://github.com/pouchdb/pouchdb/issues/2351

**Comment by mtford90** [comment]
So saving down a `Date` object is essentially undefined behaviour then? Might it be a good idea to have a warning/error for this?

**Comment by nolanlawson** [comment]
Yes, we should probably add this to the [common errors](http://pouchdb.com/errors.html). A pull request would be very welcome! :)

**Comment by mtford90** [comment]
Good idea - on my todo list :)
