### ISSUE TITLE
iojs compatibility

### ISSUE THREAD

**Issue by jvanveen** [pouchdb/pouchdb#3462]
Hey there,

with iojs leveldown fails to build on the current version thats specified in pouchdb. See https://github.com/rvagg/node-leveldown/issues/141 (1.0.1 is fine). Not sure if it's api changed, but just noticing :-)

**Comment by calvinmetcalf** [comment]
so should we be upgrading to v1.0.1 of leveldown?

**Comment by jedrichards** [comment]
Everything seems ok with iojs `2.0.2` and leveldown `1.0.6` ...

**Comment by nolanlawson** [comment]
I just tested out the latest leveldown and levelup, and unfortunately the migration tests fail (as you might expect... it is a major version release of both!).

Really not sure what to do here. We don't want to stay stuck on old versions of levelup/leveldown for forever, so probably we need to add a migration step.

**Comment by nolanlawson** [comment]
So it turns out that we have iojs compatibility without updating levelup/leveldown, but I'll make another issue for that problem.

**Comment by jay915** [comment]
I have iojs v2.3.4 and pouchdb v3.6.0 and can not run it with leveldown. What should I do?

**Comment by nolanlawson** [comment]
Contribute a fix so we can upgrade to the latest leveldown? :wink:
