### ISSUE TITLE
Can't do a pouchDB.query, throwing an error.

### ISSUE THREAD

**Issue by Yimiprod** [pouchdb/pouchdb#3465]
Hi

I'm working on a node-webkit project, i have implemented pouchdb, not using it directly with node because i get a "No valid adapter found", so i call it in my index.html.

My db is sync with a distant couchdb

```
PouchDB.enableAllDbs = true;
var DB = new PouchDB(CONFIG.LOCAL_DB, {adapter: 'idb'});
PouchDB.replicate(CONFIG.LOCAL_DB, CONFIG.SERVER_DB, {continuous: true});
PouchDB.replicate(CONFIG.SERVER_DB, CONFIG.LOCAL_DB, {continuous: true});
DB.compact();
```

That's for the context.

Now my issue:
When i do a request like get / put / delete / allDocs, no problem.
But when i try a to do a query, i get that error:
```
Failed to execute 'objectStore' on 'IDBTransaction': The specified object store was not found.
    at Error (native)
    at addDeletedOrLocalIndex (app://shooting/bower_components/pouchdb/dist/pouchdb.js:2582:24)
    at next (app://shooting/bower_components/pouchdb/dist/pouchdb.js:3445:9)
    at IDBOpenDBRequest.req.onupgradeneeded (app://shooting/bower_components/pouchdb/dist/pouchdb.js:3449:5)
```
In console:
```
"{"status":500,"name":"error","message":"unknown","error":true,"reason":"AbortError"}"
```

The request i try to do is:
```
 Service.query = function () {
    var map = function (doc, emit) {
        if (!_.isEmpty(doc.mannequins)) {
            _(doc.mannequins).forEach(function (_idMannequin) {
                emit(doc._id, {_id: _idMannequin})
            });
        }
    };
    pouchDB.query({
            map: map
        },
        {
            startkey: Service.config.key,
            endkey: Service.config.key + '\uffff',
            include_docs : true
        })
        .then(function (resp) {
            console.log(resp);
        })
        .catch(function (err) {
            console.log(err);
        });
};
```

Thanks.

**Comment by nolanlawson** [comment]
Which version of Pouch are you using? And which version of node-webkit? Can you try this [node-webkit hello world](https://github.com/nolanlawson/node-webkit-pouchdb-demo) and see if it works on your machine?

**Comment by Yimiprod** [comment]
Node-webkit: 0.11.0
PouchDB: 3.2.1

Probably why i have to use it has a bower component, it work fine except when i try to use Query.

**Comment by nolanlawson** [comment]
Ugh, yeah, IndexedDB gets messed up sometimes in certain browsers. :disappointed: 
It's a problem.

Another reason I think it's safer to default to WebSQL, especially if you're running in Node Webkit where you have the luxury of using both. See tip number 8 here: http://pouchdb.com/2014/06/17/12-pro-tips-for-better-code-with-pouchdb.html
