### ISSUE TITLE
Views are not correctly supported in changes() apparently

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3466]
See [this SO question](http://stackoverflow.com/questions/28059854/listening-to-pouchdb-changes-in-particular-view-returns-all-documents/28071662?noredirect=1#comment44739531_28071662).

**Comment by robertkeizer** [comment]
Some what related #2928 ; I would absolutely love this feature. Not enough time in the day to get back to it though.

**Comment by nolanlawson** [comment]
they are supported, just poorly documented: 5b0d4d7cb6d005b61583808c623bd1c1422f7d74
