### ISSUE TITLE
Auto detection of supported adapter throws error.

### ISSUE THREAD

**Issue by jofomah** [pouchdb/pouchdb#3471]
Pouchdb throws an exception when `new PouchDB('dbname');` is called on a device or browser that does not support 'idb' which is the default adapter.

as a work around, i decided to force the adapter to default to 'websql' but this also throws an error on Firefox something like db[method] is undefined .....

i resolved this by using a manual check.

var options = opt || { auto_compaction: true };
if(hasWebSQL()){
    options.adapter = 'websql';
}else{
     options.adapter = 'idb';
}

i expect PouchDB to handle automatic detection of supported adapter, maybe am doing it the wrong way.

**Comment by nolanlawson** [comment]
It definitely shouldn't be throwing an exception. Which browser are you using? Do you have a live example?

To prove we're not crazy, [here are our automated tests](https://travis-ci.org/pouchdb/pouchdb/builds/48546697), which as you can see run in several non-IDB browsers (PhantomJS, Safari, iPhone).

**Comment by jofomah** [comment]
`new PouchDB('dbName');` threw exception when called on Chrome App packaged as Android App using CCA build tool. inserting the manual check, fixed that.

then when i run the following:

var options = {
     adapter: 'websql',
     auto_compaction: true
};
var db = pouchDB(dbName, options);
if (!db.adapter) {
   // Fallback to default
   db = pouchDB(dbName, { auto_compaction: true });
}

Works fine on Chrome but throw exception on Firefox version 35.0.1

hope this helps

**Comment by nolanlawson** [comment]
>  Chrome App packaged as Android App using CCA build tool

Can you provide the exception? And the Android version? Might be [this thing](http://pouchdb.com/errors.html#android_pre_kitkat).

To be honest, I've never tried to build a Chrome app as an Android app and never heard of anyone using PouchDB with such a thing. :/

> Works fine on Chrome but throw exception on Firefox version 35.0.1

Cannot reproduce. [Here's a live example.}(http://bl.ocks.org/nolanlawson/a69ea5a0184c446e9468) Maybe it's because you forgot to type `new PouchDB`?

**Comment by jofomah** [comment]
> Chrome App packaged as Android App using CCA build tool?
   i think you are right, it is could be [http://pouchdb.com/errors.html#android_pre_kitkat], the Android version is 4.2, sorry can't reproduce the exception message right now.

> Maybe it's because you forgot to type new PouchDB?
    Sorry, for not providing the full detail, am using angular-pouchdb and it does not require `new` 

the wrapper can be found here [https://github.com/angular-pouchdb/angular-pouchdb]

thanks.

**Comment by nolanlawson** [comment]
You might want to file a bug on angular-pouchdb. We don't officially support that library.

**Comment by jofomah** [comment]
Fair enough will do that. thanks.
