### ISSUE TITLE
db.changes() with filter eating full CPU

### ISSUE THREAD

**Issue by andru** [pouchdb/pouchdb#3473]
I'm building an application where data stores each subscribe to puch changes via a db.changes({live:true}) with a filter to only return docs of the relevant type.  i.e.

    db.changes({
        filter: 'place/onlyPlaces'
        ,live: true
        ,include_docs: true
        ,since: 'now'
      })
      .on('create', change => insert(change.doc) )
      .on('update', change => sync(change.doc) )
      .on('delete', function(change){ remove(change.doc) } )
      .on('change', change => console.info('Change!', change) )
      .on('error', err=>console.error(err) )

The design doc with filter function in this case is:

    {
      "_id": "_design/place",
      "_rev": "4-702d176d6121a266a1ebc9d8dfdd8fc3",
      "views": {
      },
      "updates": {
      },
      "filters": {
        "onlyPlaces": "function(doc, req){ return doc.type==='place' || doc._deleted===true; }"
      }
    }

This strategy has been working fine until I add a 5th store - i.e. 5 instances listening to db.changes, each with a different filter - at which point Chrome and Firefox both starting eating lots of cpu.

Is this a fault in my application design? Is db.changes({live:true}) expensive? Or is this a bug?

I've currently solved the problem by removing the `filter` and filtering for just the relevant changes with `lodash`. Without the `filter`, CPU usage is normal.

**Comment by nolanlawson** [comment]
Hm, we probably need to cache the design doc after we fetch it from the store. Do you have a live example to reproduce?

**Comment by andru** [comment]
Hm. This might be more complex than I thought. I chased it all the way down to just one instance of db.changes({live:true}) without a filter and it was still eating the CPU. In Chrome timeline it shows the adapter is stuck in a loop.
If I create a new database the behaviour stops. If I load the the old one it returns.

I'll try and reduce it down to something I can share.

**Comment by andru** [comment]
Until I can get an example to you, here's a snippet of the DevTools timeline output showing the adapter in a loop.

I should have mentioned by now that I'm on `3.2.1` :)

![image](https://cloud.githubusercontent.com/assets/30393/5987650/f1f2ec4e-a937-11e4-92bf-c49d1b6b6f43.png)

**Comment by nickcolley** [comment]
@andru you can also right click the records panel and save your timeline so someone can load it in as if they recorded it.

https://developer.chrome.com/devtools/docs/timeline#saving-and-loading-recordings

**Comment by daleharvey** [comment]
This should hopefully be fixed by https://github.com/pouchdb/pouchdb/commit/52225348190e89b20e9a10109bf2fc56ee753728, please reopen if you are still having issues, cheers
