### ISSUE TITLE
Get rid of manualDescEnd in idb.js

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3488]
Checking the behavior of IDBKeyRange, it seems we can just create a bound where the endkey is first and the startkey is second. Manually checking the end value is not necessary. Chalk it up to me being an IDB newbie when I wrote that code. :stuck_out_tongue:

**Comment by daleharvey** [comment]
Merged in https://github.com/pouchdb/pouchdb/commit/904c812b225ba8250cfd433a5ce74c20354ae030
