### ISSUE TITLE
Issues with Couchbase Sync

### ISSUE THREAD

**Issue by janober** [pouchdb/pouchdb#3490]
Try to get pouchDB working with Couchbase Sync. However it does not seem that easy. After having set up a reverse proxy because of the cors issue I thought everything should now be fine. However whenever I try to "post" a new document and then do a replicate I get : "Error: bulkDocs error"

The actual error in Couchbase sync is: BulkDocs: Doc "DA7523F5-4BA9-1120-8FFC-40A710BF636C" --> 400 Bad _revisions (400 Bad _revisions)

The data it sends is something like that:
{"new_edits":"false", "docs": [{"_id":"021274D7-9181-1C54-9D6E-8F53153A81AE", "_rev":"1-d0df4b85e95e05c951379b49bf3373c8", "date":"2015-02-03T01:01:21.164Z"}]}

Do not know if that is an issue is in PouchDB or Couchbase Sync. Was sadly not able to reproduce the same error message with curl. If I send the same data I get "409 Document revision conflict" even if I delete all the documents in the database and restart Couchbase Sync.
Have no previous experience with PouchDB nor Couchbase Sync so maybe I do something wrong but because I use the very basic example application I dont know what it should/could be.

Does anybody have a setup like that working and knows that it acutally works? Or does anybody have a similar issue?

**Comment by nolanlawson** [comment]
As mentioned on our [adapters page](http://pouchdb.com/adapters.html#pouchdb_over_http), we actually don't have perfect compatibility with Couchbase or Cloudant yet. We're working on it, but not quite there. Currently we only have fully passing tests in CouchDB 1.6, CouchDB master, and PouchDB Server.

The lingua franca of the *ouch community, though, is CouchDB. So probably the best bet for now would be to replicate from PouchDB to CouchDB 1.x, and then from that CouchDB to Couchbase Sync Gateway. Couchbase Sync Gateway can most definitely sync with CouchDB.

/cc @jchris since this is a new error I don't think we were aware of.

**Comment by jchris** [comment]
I think this is an issue in that Sync Gateway is expecting the bulk docs POST to look just like the one the CouchDB replicator makes. In some cases PouchDB uses a slightly different format (which CouchDB also accepts). I have seen this in the PouchDB test suite but I hadn't actually seen it in real world usage, so thanks for bringing it up.

I'm in the process of getting the PouchDB test suite to run against Sync Gateway, and it seems there are a handful of small things like this. I'm trying to fix most of them on the Sync Gateway side but some will require PouchDB patches.

ETA -- a couple of months, at least. It's slow going b/c there are so many permutations of how sync can be triggered etc. Do you mind posting a link or description of the example app / steps you took to get this error? Once I have the tests mostly working I'll circle back around with some app code, and yours could be first in line. :)

**Comment by nolanlawson** [comment]
Interesting. I know CouchDB accepts _bulk_docs with new_edits=false where you omit the _revisions (I have no idea what it does with it), but I'm pretty sure Pouch always generates the _revisions object. If we're doing it inconsistently, then yeah, I'd definitely like to fix Pouch-side.

**Comment by janober** [comment]
Really great to hear! After having so many problems and seeing that the cors issue is there since 1.5 years and a "fix" since almost exactly one year (that has not been merged, for I am sure good reasons, but still does not look good) made me really wonder if PouchDB & Couchbase Sync really work or ever will work together. Which is very sad because I think both projects really need each other to be successful. However really happy to see the very fast responses now!

I really did just use the most basic setup after having the reverse-proxy setup (or cors check deactivated in chrome). I used "angular-pouchdb"  and there the example "replicate". The code is here:
https://github.com/angular-pouchdb/angular-pouchdb/blob/master/examples/replicate/app.js

Thanks a lot for your help! And great projects btw! Really looking forward to to be able to use both of them together!

**Comment by pipsk** [comment]
Hi, are there any updates on this? We'we run into same issue while trying to sync with Couchbase.

**Comment by pipsk** [comment]
Just for info if, this started working with couchbase sync gateway 1.1.0 preview. No more bulkDocs errors.

**Comment by nolanlawson** [comment]
Cool!
