### ISSUE TITLE
PouchDB fails to add extra headers in the ajax option

### ISSUE THREAD

**Issue by mtford90** [pouchdb/pouchdb#3491]
e.g. the following test does not add the extra headers to the POST request:

```js
it('test ajax opts', function (done) {
    var db = new PouchDB('http://localhost:5984/db');
    db.post({x: 1}, {ajax: {headers: {'Authorization': 'Basic 123456'}}})
        .then(function (doc) {
            done();
        })
});
```

I'm about to dive into the PouchDB source - I imagine only the top level options of ajax are being merged - or the headers are being overwritten by an object with `Content-Type` etc at some point down the line.

**Comment by mtford90** [comment]
Ok I just had a quick shifties through the code and arrived at the `.put` method in `http.js.

It looks like `.put` and `.post` entirely ignore the ajax opts, instead constructing it from scratch:

```js
  // Add the document
  ajax({
    headers: host.headers,
    method: 'PUT',
    url: genDBUrl(host, encodeDocId(doc._id)) + params,
    body: doc
  }, function (err, res) {
    if (err) {
      return callback(err);
    }
    res.ok = true;
    callback(null, res);
  });
```
Was this intentional or would you accept a pull request adding this functionality?

Cheers.

**Comment by daleharvey** [comment]
I commented in the other bug, I believe they should be working when set globally but you are right it doesnt look like we have any code to set them individually, would definitely take a PR to have that supported, the format you posted looks perfect, this should have a new test in https://github.com/pouchdb/pouchdb/blob/master/tests/component/test.headers.js as well

**Comment by mtford90** [comment]
Interesting I couldn't get it to work globally either. I'll do some extra testing and submit a PR as soon as I can!

**Comment by mrded** [comment]
Attaching the headers globally doesn't work for me neither (pouchdb 3.3.1)

**Comment by yaronyg** [comment]
As a side note, the docs currently advertise support for using options.ajax on GET and it doesn't work. :(

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/3c964adbfb9a187af79d1685d63497bdc6b9ecc6
