### ISSUE TITLE
Ability to set global/per-database ajax options

### ISSUE THREAD

**Issue by mtford90** [pouchdb/pouchdb#3492]
e.g. in the case where `Authorization` headers are passed for every request, it would be nice to be able to set an `ajax` object that will be merged into the usual ajax options for every request. This could be global or on a per-database basis. At the moment I'm having to set these options in every request (and even that doesn't work in put/post as per #3491).

I'm willing to submit a pull-request for this feature :)

**Comment by daleharvey** [comment]
So this should work globally but looks like not per request, https://github.com/pouchdb/pouchdb/blob/master/tests/component/test.headers.js (the docs have been updated but not released to make it clearer)

**Comment by daleharvey** [comment]
@mtford90 btw sorry I forgot to say a PR would be very welcome :)

**Comment by daleharvey** [comment]
This now works globally and per request
