### ISSUE TITLE
March Release + News

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#3497]
So any news you think is blog worthy you can post in here, if there is a lot then we can do a new blog post, otherwise it reminds us to put it in the march release post

**Comment by daleharvey** [comment]
Keeping track of 

https://github.com/nolanlawson/pouchdb-phonegap-cordova
https://github.com/nolanlawson/pouchdb-ionic

**Comment by nolanlawson** [comment]
https://github.com/nolanlawson/pouchdb-nw
https://github.com/nolanlawson/pouchdb-atom-shell

**Comment by nolanlawson** [comment]
https://github.com/nolanlawson/pouchdb-chrome-app-hello-world

**Comment by daleharvey** [comment]
outdated
