### ISSUE TITLE
Know if this pouch instance made the change on sync

### ISSUE THREAD

**Issue by SegFaultx64** [pouchdb/pouchdb#3498]
It would be great if there was a way for replicate to fire an event that only happened on changes that came from the remote but were not yet reflected locally. A use case is two users editing the same database with it syncing to a remote.

**Comment by nolanlawson** [comment]
This gets brought up a lot; I believe `sync` objects have a `direction` variable? Really this just needs better documentation in `api.html` I think.

**Comment by nolanlawson** [comment]
fixed by 5813a69338abcccece39be8ae71f1df0f80f5e98
