### ISSUE TITLE
Re-enable assertions blocked by bugs in CouchDB master

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#3500]
Specifically, https://issues.apache.org/jira/browse/COUCHDB-2518 and https://issues.apache.org/jira/browse/COUCHDB-2522 are now fixed.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/199bc434726876c6c91071968a893a027b8d758b
