### ISSUE TITLE
Copying documents with attachments

### ISSUE THREAD

**Issue by rymohr** [pouchdb/pouchdb#3502]
CouchDB has a COPY api that makes it easy to copy a document and its attachments.  I looked for a similar api in PouchDB but didn't find one.  Is that by design or has there just not been any need for it?

http://docs.couchdb.org/en/latest/api/document/common.html#copy--db-docid

**Comment by daleharvey** [comment]
I think it just hasnt been particularly asked for, COPY is mostly useful in CouchDB to avoid the data transfer since it has to go over http, client side thats less of an issue, a client doing a copy will do pretty much the same thing we will

**Comment by rymohr** [comment]
Yeah, I'd imagine this is mostly an http issue though the abstraction could be helpful client side.  We need to duplicate a document that has dozens of attachments and without this we need to download each attachment and upload it as a new one.  Not fun with a slow connection or big attachments.

For now we can just manually handle the request but it would be nice to do it through pouchdb's api in case we ever ended up moving these documents client side.

I understand it's an isolated use case though so feel free to ignore it.

**Comment by daleharvey** [comment]
I do often keep forgetting that PouchDB can be used as a HTTP client to CouchDB as well as just on the client side, in that case implementing copy makes more sense. If anyone is up for implementing it then fairly sure we would want to add this

**Comment by rymohr** [comment]
Thanks Dale.  That's actually the only way we use it right now.  Still waiting for browser storage limits to be lifted and the prompts to be more friendly before we start using pouchdb as it was intended.  By sticking to the api it's an easy switch.

Works great as an HTTP client though! :+1:  All the projects on [kumu.io](https://kumu.io) are backed by a couchdb database managed through pouchdb through a rails proxy.  We're hoping pouchdb will eventually allow us to have local dev branches for each project.

**Comment by nolanlawson** [comment]
You could implement this as a PouchDB plugin. :) Or actually, doing HTTP requests directly in PouchDB is pretty easy, thanks to an (undocumented) API:

```js
db.request({
  method: 'POST',
  url: '_whatever',  
  body: {}
}).then(...);
```

**Comment by rymohr** [comment]
@nolanlawson thanks for the tip.  If the copy feature ends up being useful I'll look into wrapping it in a plugin.

**Comment by daleharvey** [comment]
Cheers
