### ISSUE TITLE
Make it clear what arguments are handed to events

### ISSUE THREAD

**Issue by tyler-johnson** [pouchdb/pouchdb#3503]
A bit of a nit-picky thing, but I wish the documentation online had what arguments were given to the replication events. I like to just read the PouchDB docs sometimes to help me form mental concepts for my next project. Seeing how I can use each event is a big part of that process.

Personally, I really like [Backbone's documentation](http://backbonejs.org/#Events-catalog) where each event is listed with their respective arguments.

**Comment by daleharvey** [comment]
Thanks for the pointer, this is mostly definitely lacking, half the events werent even documented until the last release, planning on improving them a lot in this one

**Comment by nolanlawson** [comment]
If you have some time, you could open a pull request on the documentation! :) It's right here: https://github.com/pouchdb/pouchdb/blob/master/docs/api.md

**Comment by tyler-johnson** [comment]
Okay, I've added it via #3513. Might need some tweaking from you guys though.

**Comment by tyler-johnson** [comment]
Upon a re-reading of the "paused" event explanation, it was really unclear to me when an error event occurs and when it does not. I had to read #3155 to understand and even then I'm still not totally sure.

Does the paused event only pass an error when pouchdb temporarily loses connection with the remote database?

**Comment by daleharvey** [comment]
> Does the paused event only pass an error when pouchdb temporarily loses connection with the remote database?

Yes, it will only fire when `retry:true` when the replication is paused due due to an error (likely network) and will start retrying

**Comment by daleharvey** [comment]
Im gonna get some updates to the guide for this release, but closing this out for the patch, cheers - https://github.com/pouchdb/pouchdb/commit/b7f66bf99d54e79ec3c4ac08060bf8d54a08b41e
