### ISSUE TITLE
Allow self-signed SSL certificates

### ISSUE THREAD

**Issue by bnjbvr** [pouchdb/pouchdb#3504]
I am using pouchdb, syncing to a remote couchdb instance which is hosted at a https URL.  The certificate is self-signed, because that's a personal server and I am trusting myself (!).  However, pouchdb (run under node) doesn't seem to work with this configuration, and it is rejecting all requests with a 400 status.  Inspecting the request options in http.js showed me that nodejs is emitting the error "unable_to_verify_leaf_signature", which is indicating that the SSL certificate is rejected.  A work around is to set NODE_TLS_REJECT_UNAUTHORIZED to 0 in the environment (bash or in node), but I would like to have a way to tell pouchdb it's fine to have self-signed SSL certificates.  Does that sound doable?

**Comment by nolanlawson** [comment]
This sounds like a `request` issue. Since PouchDB allows you to pass options to `request` under the hood, perhaps there is a `request` option that lets you allow self-signed certificates? Looks like this should work: https://www.npmjs.com/package/request#tlsssl-protocol

BTW to set ajax options, just do it when you construct the PouchDB:

```js
var db = new PouchDB('http://wherever', {
  ajax: {
    some: 'option'
  }
})
```

**Comment by calvinmetcalf** [comment]
The node https module which request uses does have this option

**Comment by bnjbvr** [comment]
Nice! However, option arguments are not transferred to the lowest level. The place that matters for my use case is there [0]. Simply adding opts the constructor does the trick. 

[0] https://github.com/pouchdb/pouchdb/blob/master/lib/replicate.js#L578

**Comment by bnjbvr** [comment]
For what it's worth, the opts to pass in such a situation are the following:
```
ajax: {
  rejectUnauthorized: false,
  requestCert: true,
  agent: false
}
```

**Comment by bnjbvr** [comment]
If you're fine with not having tests for this (I wouldn't know how to implement these), I can propose a one-line change pull request.

**Comment by daleharvey** [comment]
So we have discussed passing in options to the constructor via .replicate / .sync, but I havent seen a consistent way to handle the various use cases and there is a fairly clear right way to do this.

```
var db = new PouchDB('local');
var remote = new PouchDB('remote', {ajax: {rejectUnauthorized: false}});

db.sync(remote);
```

Does that work for you? The main way we test this currently is via https://github.com/pouchdb/pouchdb/blob/master/tests/component/test.headers.js, but if you have an idea for a patch without a test, get the patch up and we can figure out the test if the functionality looks like something we would merge

Cheers

**Comment by daleharvey** [comment]
We now support passing replication options in sync and request is updated so this should be good

**Comment by jkuester** [comment]
To future me, when I run into this problem again using newer versions of Pouch, the fix that worked when running on Node was:

```ts
import https from 'https';
const agent = new https.Agent({
  rejectUnauthorized: false,
});

const db = new PouchDB(
 remoteUrl,
  { fetch: (url, opts) => PouchDB.fetch(url, { ...opts, agent  }), }
);
```
