### ISSUE TITLE
mapreduce stops, with uncatchable errors, when a map function throws

### ISSUE THREAD

**Issue by ddouglascarr** [pouchdb/pouchdb#3515]
If you have a map function in a _design document, and that function throws, mapreduce stops indexing. It doesn't throw itself, and db.query().catch() doesn't do anything. (The db.query() promise just stays unresolved).

This is different to couchDB's behaviour. It just ignores map functions that throw and carries on indexing.

I observed this with the {adapter: 'websql'} options passed to PouchDB.

**Comment by nolanlawson** [comment]
related: https://github.com/pouchdb/mapreduce/issues/214

**Comment by ddouglascarr** [comment]
https://github.com/pouchdb/mapreduce/pull/262

**Comment by daleharvey** [comment]
Fixed upstream
