### ISSUE TITLE
Blog RSS feed

### ISSUE THREAD

**Issue by ScreenDriver** [pouchdb/pouchdb#3516]
Is there any reason why there is no RSS feed of the blog? It would be very nice because I read almost everything news related through RSS feeds.

**Comment by daleharvey** [comment]
No particular reason it just hasnt been implemented, I have done a jekyll blog with an rss feed before so should be ok to implement

**Comment by nickcolley** [comment]
@ScreenDriver if you want to have a go adding it I can help you contribute, otherwise if I get time I'll have a go.

**Comment by ScreenDriver** [comment]
How can I contribute? Is the source code of pouchdb.com also hosted on GitHub?

**Comment by marten-de-vries** [comment]
@ScreenDriver It's in the docs directory of the main repository. (https://github.com/pouchdb/pouchdb/tree/master/docs)

**Comment by ScreenDriver** [comment]
Ok, thank you. But it seems that it is static and written in Markdown? How can a dynamic RSS feed be generated when there is no server side dynamic like nodejs, Python, Java or something? I believe I overlook something.

**Comment by daleharvey** [comment]
You dont need to dynamically generate the rss feed, we regenerate the site (including potential rss file) when we add a new post, then publish it

https://github.com/agelber/jekyll-rss

looks to be one way

**Comment by marten-de-vries** [comment]
Fixed in 4d135c63efb3128a5e262eca345b451bf717a23e
