### ISSUE TITLE
Add endsince query option to _changes

### ISSUE THREAD

**Issue by robertkeizer** [pouchdb/pouchdb#3520]
This would be a useful feature for PouchDB to include, regardless of if CouchDB decides to include it or not.

https://issues.apache.org/jira/browse/COUCHDB-2571

The use case is fairly limited and is most likely not required once couchdb version 2 comes out with replicating views.

**Comment by daleharvey** [comment]
Doesnt look like there is movement on the couch bug, and since the long term aim is to replace the map reduce api with pouchdb-find I dont expect a lot of new map reduce features being implemented, closing this one out

(https://github.com/pouchdb/pouchdb/issues/3538)
