### ISSUE TITLE
Make PouchDB's browser request implementation requireable?

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#3524]
Noticed this discussion: https://github.com/hoodiehq/hoodie.js/pull/407#discussion_r24449680 over in hoodie land, not sure if we could help by making the pouchdb-request browser stuff it's own module?

Thought I'd note it incase we can help out! :+1:

**Comment by daleharvey** [comment]
Yeh part of the reason I did the split is because I wanted to use this externally, I was mostly waiting to see if we could get rid of require('blob'), but maybe can just inline it for now

What should we call it, b-request?

**Comment by nickcolley** [comment]
Think this is closed by
```
var ajax = require('pouchdb/extras/ajax');
```

?

**Comment by daleharvey** [comment]
yup, and https://github.com/pouchdb/pouchdb/issues/5128
