### ISSUE TITLE
Memory and Localstorage adapters don't work

### ISSUE THREAD

**Issue by corps** [pouchdb/pouchdb#3528]
Hey guys,

Ever since about 3.1, I've noticed that the memory and localstorage adapter were not working at all in my phantomjs tests.  Versions 3.2 - current head have the same issue.  It seems that both adapters actually end up just using the LevelUP indexeddb implementation, meaning that they neither work as fallbacks for older browsers nor are they usable in certain test environments (like phantomjs).

I have a simple demonstration here. http://bl.ocks.org/corps/1d285ffac2b6d67e895f

 It's kinda tricky because it's not possible to "remove" the native indexedDB from the environment to invoke the exceptions I'm seeing in CI, but the issue can be demonstrated in two ways:

1.  View the page.  Now reload.  Notice the 409, despite being "in memory"?  Check your resources tab on your browser: somedb and pouch-memory are now indexeddb databases.

2.  Open a debugger and reload the page.  I've added a single debugger in the offending constructor call that leads to an idb.open.  You can see that the opts.adapter is, in fact, memory, and that PouchDB.adapters['memory'] is set to use this the LevelPouchAlt that leads to using the LevelUP implementation.

Hopefully this is an easy issue to fix.  To be honest, I've tried digging deeper but the way that the actual adapter code gets assembled is somewhat confusing to me.

**Comment by nolanlawson** [comment]
Yup, I can confirm that the memory/localstorage plugins are both just using level.js. Probably a bug we introduced in d3bb6ea349371b4ff202927ea7c86cb001df62e6

**Comment by nolanlawson** [comment]
Hm, browserify seems to ignore `-r memdown:leveldown`, but it uses the `{browser: {leveldown: 'level-js'}}` option in the `package.json`.

**Comment by nolanlawson** [comment]
OK, figured it out. Got a fix.

**Comment by nolanlawson** [comment]
Scratch that, I didn't figure it out. And I don't have time to look into this right now. @calvinmetcalf any ideas?

Things I did figure out:

* I can get it to work if I put `{browser: {leveldown: 'memdown'}}` in the package.json
* `-r memdown` includes memdown, but doesn't link it to `leveldown`
* both `-r memdown:leveldown` and `-r leveldown:memdown` don't do anything anymore

**Comment by nolanlawson** [comment]
Nevermind, found a hack that fixes it.

**Comment by nolanlawson** [comment]
@corps If you don't want to wait for the next release, you can download the fixed versions of the plugins [from here](http://shrub.appspot.com/nolanlawson/pouchdb/www/20150212/).

**Comment by corps** [comment]
Ahh, that makes sense, now I understand the build process for the plugins.  Thank you so much for looking into this!

**Comment by nolanlawson** [comment]
Let's leave this issue open until the patch is merged. :)

**Comment by nolanlawson** [comment]
Fixed by 3229218b8633a41d9c2af5bdae849a52dcb84209
