### ISSUE TITLE
Cannot PUT _security doc with HTTP adapter

### ISSUE THREAD

**Issue by colinskow** [pouchdb/pouchdb#3529]
I am trying to PUT a _security document through the PouchDB http adapter and am getting the following error:

```js
var secDoc = {
  members: {
    names: ['test'],
    roles: []
  }
};
testDB.put(secDoc, '_security');
```

`{"status":400,"name":"bad_request","message":"Only reserved document ids may start with underscore."}`

Is there a way to make this work?

**Comment by colinskow** [comment]
Here is my temporary work-around, but it would be nice if PouchDB did this automatically every time a user puts a doc with _id `_security`.
```js
var request = require('superagent');
function putSecurity(db, doc) {
  var url = db.getUrl();
  return new Promise(function(resolve, reject) {
    request
      .put(url + '/_security')
      .send(doc)
      .end(function(error, res){
        if(error) {
          return reject(error);
        } else {
          return resolve(res.text);
        }
      });
  })
}
```

**Comment by marten-de-vries** [comment]
@colinskow This was recently discussed in #3522. In short, your workaround is indeed the best we offer currently. In #3525 alternative solutions are discussed at the moment.

**Comment by colinskow** [comment]
OK, it would also be nice to have this built-in to the PUT functionality in the HTTP adapter. It is the simplest for the developer. PouchDB simply needs to ommit the `_id` tag when the doc's name is `_security`.

When:
1) HTTP Adapter is being used
2) db.put has a second argument of `_security`
Adapter will automatically put to `/_security` while omitting the `_id` tag inside the doc.

Note:  `db.get('_security')` works out of the box.

http://docs.couchdb.org/en/latest/api/database/security.html

**Comment by marten-de-vries** [comment]
As I said in #3522, I don't agree. You can't post()/remove()/bulkDocs() a _security document & it's not replicated. The API appears to be the same on the surfuce in CouchDB but it's actually implemented separately IIRC. In my opinion, having a ``.getSecurity()``/``.putSecurity()`` makes more sense. For that, there is already pouchdb-security, but I hope that we'll get a more lightweight version for http databases only soon, since there does seem to be a demand.

**Comment by colinskow** [comment]
Core CouchDB functionality should be core PouchDB functionality also (and not a separate plug-in), at least with regards to the HTTP adapter. `get()` already works out of the box. Enabling `put()` to handle a doc called `_security` is intuitive to developers and couldn't possibly break anything since `_security` is a reserved name anyway.

The IndexDB/WebSQL/LevelDown adapters can continue to throw an error, since this mostly makes sense on a CouchDB server.

Documenting `request()` is definitely a good idea as it allows us to get many simple tasks done without plugins.

**Comment by colinskow** [comment]
If you guys agree with @marten-de-vries, feel free to close this. `db.request()` is doing the job fine for me.

**Comment by daleharvey** [comment]
> Core CouchDB functionality should be core PouchDB functionality also (and not a separate plug-in), at least with regards to the HTTP adapter.

For PouchDB we aim to support the common subset of functionality between couchdb and local instances. There is a huge amount of functionality that a http based couch supports in its api that we dont or will ever make sense in a local db. As it is any code you write with pouchdb you 'should' be able to switch between local and remote instances and have it guaranteed to work with extra functionality (like security) defined in plugins.

I think we may want to make an exception for "db.request", it is proving useful and it is somewhat clear that this will only work against a remote couch, putSecurity etc not so much

**Comment by daleharvey** [comment]
Closing out, and we can think about documenting db.request

**Comment by ARChilton** [comment]
I thought I would leave this comment in case anyone else was trying to put _security in future.
This plugin for nodejs works very well:

https://www.npmjs.com/package/pouchdb-security-helper

**Comment by peteruithoven** [comment]
Since pouchdb-security-helper doesn't seem compatible with Cloudant's security model and [colinskow`s workaround](https://github.com/pouchdb/pouchdb/issues/3529#issuecomment-74028571) didn't include authentication we had to look further. We came up with: 

``` js
const fetch = require('node-fetch');
function putSecurity(doc) {
  return fetch(`${url}/_security`, {
    method: 'PUT',
    body: JSON.stringify(doc),
    headers: {
      'Content-Type': 'application/json',
      Authorization: 'Basic ' + new Buffer(DB_USER + ':' + DB_PASS).toString('base64')
    }
  }).then(res => res.json());
}
```

**Comment by dpmccabe** [comment]
An updated superagent equivalent with auth looks like this (I'm using Typescript):

```typescript
import request from 'superagent';

async function putSecurity(db: PouchDB.Database<unknown>): Promise<void> {
  await request
    .put(`${db.name}/_security`)
    .auth('user', 'password')
    .send({
      members: { roles: ['_admin'] },
      admins: { roles: ['_admin'], names: ['some-other-admin'] }
    });
}
```

**Comment by BananaAcid** [comment]
Is there a native solution on puchdb by now (to be able to put _security)? This seems to limit the capabilities in PWAs.
