### ISSUE TITLE
Firefox is sad when page reloaded while .compact() is still running

### ISSUE THREAD

**Issue by dholth** [pouchdb/pouchdb#3531]
I have a database with, say, 10,000 items and I thought it might be a good idea to call .compact() when the page loads.

However if I reload the page in Firefox when this is still running, I get what appears to be one AbortError for each document in the database - as if the code from the last version of the now refreshed page is still running and finishing up producing errors. The database also becomes unresponsive on the new page.

**Comment by nolanlawson** [comment]
I think we just need to handle AbortErrors. Currently we don't have any `onabort`s in our code, because we didn't really know how to handle them.

By any chance do you have a live reproducible test case for this error? Would help narrow down what we can do.

**Comment by dholth** [comment]
This might do it. The database needs to have enough items that .compact() takes some time to run.

```
<script src="bower_components/pouchdb/dist/pouchdb.js">
<script>
var dbName = "db2a45b7fc3310b05";
var db = new PouchDB(dbName);
db.compact().then(console.log.bind(console));
</script>
```

**Comment by nolanlawson** [comment]
You could try auto-compaction too. It's more performant, especially if you're frequently doing compaction. Also it may get deprecated eventually.

**Comment by daleharvey** [comment]
The abort error was a bug in firefox that has since been fixed
