### ISSUE TITLE
Pouch broken in browserify

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#3533]
need to npm install es3ify for it to work it seems

**Comment by nickcolley** [comment]
I've encountered this but it's infrequent, if you run your build enough times it stops happening. Very confusing.

**Comment by doublerebel** [comment]
:+1: not working here without es3ify also

**Comment by RichardLitt** [comment]
I'm also getting this. Rerunning `gulp` seems to work, but it's annoying in that I have to manually check whether my build has worked each time I run it. 

My error:

```sh
Error: Cannot find module 'es3ify' from '/Users/richard/src/beagle/node_modules/beagle-pdf'
    at /Users/richard/src/beagle/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/richard/src/beagle/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/richard/src/beagle/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/richard/src/beagle/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/richard/src/beagle/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/richard/src/beagle/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:99:15)
```

Why it is calling from those places, I don't know - PouchDB is the only package in my `npm-shrinkwrap.json` file that uses es3ify.

Might be related to https://github.com/pouchdb/mapreduce/issues/170.

**Comment by nolanlawson** [comment]
If you update to PouchDB 3.5.0 this is fixed. :)

**Comment by nolanlawson** [comment]
Er wait you are on 3.5.0. One sec.

**Comment by nolanlawson** [comment]
yeah okay this is working for me with pouchdb 3.5.0, closing this issue. please reopen if still a problem. It seems like you have 3.4.0 in your shrinkwrap which is causing the issue.

**Comment by RichardLitt** [comment]
Sweet. Will let you know if it's a problem. Thanks!
