### ISSUE TITLE
CORS errors in Firefox 35.0.1

### ISSUE THREAD

**Issue by scoughlin** [pouchdb/pouchdb#3534]
Hey,
I'm using PouchDB 3.3.0.  I was getting CORS errors when trying to sync my PouchDB db with one of my databases on Cloudant in Firefox 35.0.1. I confirmed the CORS settings were correct with Cloudant, allowing the connections and only one of my databases was getting these errors. The others had none. 

Here's the error from Firefox;
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cpeipdev.cloudant.com/curriculum/7-12_m9_126?revs=true&open_revs=%5B%224-7b1fcb9b70f9ed71117750caa1c5616e%22%5D&attachments=true&_nonce=1423780558847. This can be fixed by moving the resource to the same domain or enabling CORS.

For that one database I had a batch_size option set like this:
PouchDB.replicate(url,db['curriculum'].database, { live: false, batch_size: 40000	})

Oddly, removing "batch_size: 40000" got rid of the CORS errors.

Do you think it was a coincidence?
Thanks,
- Shawn

**Comment by nolanlawson** [comment]
IIRC, Firefox OS CORS issues can be fixed by ensuring that the server allows `app://` URLs.

For instance, I had a Firefox OS app set up using Amazon S3 for storage, and the following configuration worked fine for me. Obviously you will have to edit it to match Cloudant's format, but hopefully it will help:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>http://*</AllowedOrigin>
        <AllowedOrigin>https://*</AllowedOrigin>
        <AllowedOrigin>app://*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <MaxAgeSeconds>2628000</MaxAgeSeconds>
        <AllowedHeader>accept</AllowedHeader>
        <AllowedHeader>authorization</AllowedHeader>
        <AllowedHeader>content-type</AllowedHeader>
        <AllowedHeader>origin</AllowedHeader>
        <AllowedHeader>referer</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

**Comment by nolanlawson** [comment]
BTW we (or somebody) really need to document these Firefox OS CORS issues in `errors.md`. This is the second time I believe this has come up.

**Comment by daleharvey** [comment]
This specified fx 35 which isnt Firefox OS, both cloudant and couchdb use `*` in their configuration which will work for `app://` urls so this is only valid for setting up cors via amazon or other servers.

Also we are removing `app://` urls in firefox os, so gonna close this out as a spurious cors issue, if we do see problems with `app://` urls again will take note of where the confusion is to document

**Comment by nolanlawson** [comment]
@daleharvey great news; that's gonna be really helpful. Wrote a mobile app awhile ago and was really surprised I had to jump through that hoop to get CORS working on FXOS.
