### ISSUE TITLE
AppCache for pouchdb.com never updates in Firefox

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3537]
No matter how many times I refresh, I never see the newest content when it gets published to pouchdb.com. I have to go into my Firefox settings and remove all the offline data for pouchdb.com. WTF appcache?

**Comment by nolanlawson** [comment]
I'm thinking of just getting rid of AppCache. I mean, I know we were trying to prove a point, but we're struggling with it so much, and anyway an API/blog site isn't really appropriate for AppCache.

**Comment by daleharvey** [comment]
Im on holiday now but will look at fixing when I get back, I suspect it is that nginx is caching the appcache requests

I most definitely dont want to get rid of appcache, 1. We are making a point, appcache and pouchdb are very much intertwined, having pouchdb power the data behind an appcache'd page is our primary use case right now. and 2. having the docs offline is incredibly useful, (3, it makes the site really fast)

We will switch to service workers when thats appropriate, but right now I would like to get this working

**Comment by daleharvey** [comment]
As far as I have seen firefox has been updating properly with the last few publishes
