### ISSUE TITLE
Merge pouchdb-find to core

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3538]
@daleharvey has suggested before that we deprecate temp views. I'd like to go one step further and deprecate map/reduce entirely.

My plan is this:

1. Finish up [pouchdb-find](https://github.com/nolanlawson/pouchdb-find), publish.
2. Modify the API docs to mention neither `query()` nor `find()`. Move the `query()` docs to mapreduce's README.
3. Modify the guide, adding a chapter about pouchdb-find. The map/reduce chapter can stick around, but we'll add a warning saying "don't use this thing unless you are an expert."

So the end-goal is that PouchDB has neither `query()` nor `find()` by default, but rather both are optional plugins. Benefits are:

* Modularity
* Smaller pouchdb-core size
* People are discouraged from using *either* map/reduce or pouchdb-find. Given that the slowest part of PouchDB by far is secondary indexes, and given that you can do pretty much everything you need to do with `allDocs` with much much better performance, I think this is reasonable.

What do y'all think?

**Comment by nickcolley** [comment]
I like this proposal.

I think the current query API mis-leads in a way since although it's the cleanest way to query it's not the most performant, in our usage in production we don't use it.

I think since the goal of [Mango](https://github.com/cloudant/mango) is to make it easier to query, it's  the better long-term thing to promote.

Of course my view is only half a cent ;)

**Comment by jfspencer** [comment]
I would contend to keep querying in core. Having pouch-find replace the
current query model would be awesome. In my production scenario there is a
great need for secondary indexes. We are migrating from a SQL backend and
secondary indexes have allowed us to blend relationships into our new
document schema in a very elegant way. Also when used correctly (and in
certain cases) secondary indexes are faster than allDocs, in one of my
common production cases about 5x faster. Also the recent improvements in
view build time has removed our last road block to maintaining a great end
user experience.

One other concern with moving querying to a plugin, would it still get the
same testing support as core?


On Saturday, February 14, 2015, Nick Colley <notifications@github.com>
wrote:

> I like this proposal.
>
> I think the current query API mis-leads in a way since although it's the
> cleanest way to query it's not the most performant, in our usage in
> production we don't use it.
>
> I think since the goal of Mango <https://github.com/cloudant/mango> is to
> make it easier to query, it's the better long-term thing to promote.
>
> Of course my view is only half a cent ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/3538#issuecomment-74389886>.
>


-- 

Cheers,


James

**Comment by nolanlawson** [comment]
@jfspencer Wow, thanks for the kind words about the recent performance improvements. I'm glad to know they paid off so much. Maybe you could write a guest blog post? :D

As for testing: it wouldn't change anything, because mapreduce is already a separate plugin (https://github.com/pouchdb/mapreduce), and it has generous tests. So the change would be to just stop bundling it with the main `pouchdb.js` file.

Have you taken a look at [pouchdb-find](https://github.com/nolanlawson/pouchdb-find)? I'm curious to know whether Mango queries would satisfy your current use-cases.

**Comment by jfspencer** [comment]
It would be fun to write a post! I am a converted CBL user. Working with
CBL in a hybrid environment is a nightmare. I didn't really start to
understand the couch environment until I stated implementing pouch.

Good to know about testing and that map/reduce is already a plugin.

I have looked through pouchdb-find. It will greatly reduce secondary index
management and make the application query API a lot more readable and
flexible. As soon as it leaves beta, I will begin implementing it.

I am also working on a project that is using pouch client side and mongo
server side. So having pouchdb-find will be epic for consistency.

On Saturday, February 14, 2015, Nolan Lawson <notifications@github.com>
wrote:

> @jfspencer <https://github.com/jfspencer> Wow, thanks for the kind words
> about the recent performance improvements. I'm glad to know they paid off
> so much. Maybe you could write a guest blog post? :D
>
> As for testing: it wouldn't change anything, because mapreduce is already
> a separate plugin (https://github.com/pouchdb/mapreduce), and it has
> generous tests. So the change would be to just stop bundling it with the
> main pouchdb.js file.
>
> Have you taken a look at pouchdb-find
> <https://github.com/nolanlawson/pouchdb-find>? I'm curious to know
> whether Mango queries would satisfy your current use-cases.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/3538#issuecomment-74394086>.
>


-- 

Cheers,


James

**Comment by marten-de-vries** [comment]
I like it.

One implementation concern:

I do need to figure out how to make ``pouchdb-list`` inject mapreduce if it's not already active on an object, meaning that some care would need to be taken while deprecating. (``allDbs()`` can be called without side effects meaning I could just use calling as feature detection in e.g. pouchdb-fauxton, ``query()`` does have side effects so that trick won't work reliably.)

**Comment by nolanlawson** [comment]
@calvinmetcalf has already achieved this trick with crypto-pouch (depends on filter-pouch), and I did it with pouchdb-replication-stream (depends on pouchdb-stream). Just bundle mapreduce with pouchdb-list, and if it's not declared on the object, add it yourself. I think that ought to work.

**Comment by marten-de-vries** [comment]
@nolanlawson It wouldn't if ``query()`` would be replaced by a stub that throws an error when called for some time. That was/is? the behaviour of ``allDbs()``. So let's not do that this time (or otherwise provide a way to work around it).

**Comment by nolanlawson** [comment]
We could also just remove `query()` outright. I'm not sure if our `allDbs()` trick was very helpful; the code will throw an error no matter what. And plus, that's what SemVer is supposed to communicate. :stuck_out_tongue:

**Comment by marten-de-vries** [comment]
That would work. :)

**Comment by daleharvey** [comment]
So I also think that we need querying shipped in core, also not sure its going to be possible to have it as plugin using native indexes that needs pretty tight integration with schema generation etc. 

However all aside, the first thing I think either way that needs to happen is `pouchdb-find` in the mono repo, I did https://github.com/pouchdb/pouchdb/pull/5476 mostly to get to grips with that but pouchdb-find is a little more complicated because we will still want to release the plugin file, it has gh-pages setup etc so Nolan how do you think is best to get this into the monorepo?

**Comment by nolanlawson** [comment]
I think the first thing we should do is move documentation to the main site; we need a guide page and an API page for pouchdb-find. As for gh-pages, that's just a little "learn you pouchdb-find" demo which can still live at the original repo; I see no reason to move it.

Once pouchdb-find is in the monorepo, it can still be released as a separate plugin and nothing needs to change from the user's point of view, so probably the most important thing is just moving documentation over. Also it may be nice to figure out how to merge two git repos so that we can give proper credit; it's a large project and there are many contributors.

**Comment by stuartpb** [comment]
Is this still happening? What's the timeline on ripping (back) out pouchdb-query in favor of pouchdb-find?

**Comment by stuartpb** [comment]
Also, if I'm reading https://cloudant.com/blog/mango-json-vs-text-indexes/ right, Cloudant Query (which, as I understand it, is the basis for Mango / PouchDB Find) is implemented as a layer *on top of* design documents with map/reduce view functions in CouchDB - how would a PouchDB without design-document-based map/reduce views reflect that?

**Comment by nolanlawson** [comment]
TBH I don't know if this is on the roadmap anymore. Ideally idb-next adapter would do this automatically under the hood (the current "use an entirely separate PouchDB for the secondary index" does not have a great perf profile and does not take advantage of native secondary indexes). In the it doesn't matter much if it's in core or not because it can easily be used as a plugin, and the entire core PouchDB repo is modularized anyway.

**Comment by stuartpb** [comment]
If that's the case then surely [this line](https://github.com/pouchdb/pouchdb/blob/master/docs/_includes/api/query_database.html#L15) should be removed from the documentation?

Also, how do secondary indexes work in a driver like idb-next without the pouchdb-find module's index-creation functions? Under what circumstances does it create them?

**Comment by nolanlawson** [comment]
At some point `query()` will probably be removed from core, at which point you will have a choice between `query()` and `find()`. Although again it really doesn't matter much since the whole thing is plugin-ized.

The idea behind idb-next is to use built-in IDB secondary indexes rather than constructing our own using separate DBs.
