### ISSUE TITLE
Exception inside event handler can break main thread

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3539]
From [IRC today](https://botbot.me/freenode/pouchdb/2015-02-14/).

```
Uncaught InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': 
    The database connection is closing.
```

```
MartinBroerse
hi Nolan, when I delete a record in Ember Pouch using my local CouchDB and never with the iriscouch there is a FindAll promise never resolving for this code:
11:02 am
deleteAuthor: function() {
11:02 am
this.modelFor('author').destroyRecord().then(function() {
11:02 am
this.transitionTo('authors');
11:02 am
}.bind(this));
11:02 am
},
11:03 am
How can I report something usefull to find this bug?
11:04 am
I can't reproduce it because it only seem to fail on fast systems.
11:05 am
Also the bug is not always there??
11:07 am
The error I get:
11:07 am
Uncaught Error: Assertion Failed: You can only unload a record which is not inFlight. `<myapp@model:post::ember876:B4626ECD-63F0-72EC-A223-FCB6CE81FA47>`
11:08 am
Uncaught InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
11:08 am
On the Pouch line: var transaction = idb.transaction(stores, 'readonly');
11:09 am
function allDocsQuery
11:12 am
nolanlawson
"The database connection is closing" is one of those IndexedDB errors that seems to be getting more prevalent
11:13 am
I have seen it a million times and have no idea how to debug it. :/
11:13 am
Does it only occur in Chrome?
11:13 am
MartinBroerse
Yes
11:13 am
nolanlawson
yup
11:13 am
Please make a reproducible test case and file the issue directly on pouchdb (not ember-pouch or relational-pouch)
11:13 am
I need to make a collection of these so I can show them to the Chromium devs and get their opinion
11:14 am
what makes me suspicious is that Firefox never, ever throws these errors
11:14 am
MartinBroerse
It seems th delete resolves but when you do allDocsQuet to fast is fails
11:15 am
function allDocsQuery
11:17 am
as I said I can't make a reproducible test. I you run a delete in https://github.com/broerse/ember-cli-blog 10 times running "ember s" against your local couchdb it will fail.
11:25 am
nolanlawson
MartinBroerse: you mean you destroy your database? that's a common cause of this error that I've seen.
11:26 am
daleharvey: appcache is preventing me from seeing the most recent version of pouchdb.com in firefox. very frustrating. I've refreshed like 12 times.
11:26 am
MartinBroerse
no a delete for one document
11:27 am
and the allDocsQuery errors
11:27 am
nolanlawson
why would the database connection be closing if you never destroy? very bizarre
11:27 am
are you, like, closing a bunch of tabs and reopening a bunch of tabs or something?
11:28 am
MartinBroerse
see source above this.transitionTo('authors');
11:29 am
nolanlawson
hm, without a live example, it's really tough to see what's going on :(
11:32 am
MartinBroerse
The promise for the destroyRecord resolves but the promise for de FindAll on the authors route never resolvers. Error in Pouch allDocsQuery line var transaction = idb.transaction(stores, 'readonly');
11:32 am
wilhol_away is now known as wilhol
11:32 am
you can take over my PC
11:36 am
or install https://github.com/broerse/ember-cli-blog with local CouchDB.
11:36 am
I can try to make an example that fails without a remote CouchDB
11:41 am
nolanlawson
MartinBroerse: okay, I'll try to run that
11:42 am
MartinBroerse
just create some authors and delete them again.
```

**Comment by nolanlawson** [comment]
So we just need to install https://github.com/broerse/ember-cli-blog, then create some authors and delete them in order to reproduce.

**Comment by nolanlawson** [comment]
https://github.com/broerse/idbd-test

**Comment by nolanlawson** [comment]
```
6:06 PM <nolanlawson> MartinBroerse: I figured it out. two separate errors here. one of them is either in your code or in ember-pouch; I'm not sure which
6:06 PM <nolanlawson> you might want to ask the #emberjs room what this means:
6:06 PM <nolanlawson> "Uncaught Error: Assertion Failed: You can only unload a record which is not inFlight"
6:06 PM <nolanlawson> because that is Greek to me :P
6:06 PM <nolanlawson> as for the IndexedDB error, that's something we can fix on our end. shouldn't be too hard
```

**Comment by nolanlawson** [comment]
So the error is that the user-supplied `'change'` listener throw as synchronous error, which causes us to kinda shut down in a bad way.

**Comment by broerse** [comment]
@nolanlawson it seems to be simple to generate the bug on localhost and maybe impossible on a real domain with the same code http://exmer.com/idbd-test/ ??? I also tested this behavior with npm's http-server on localhost.

**Comment by nolanlawson** [comment]
@broerse The actual error you are experiencing is:

   Uncaught Error: Assertion Failed: You can only unload a record which is not inFlight. `<myapp@model:post::ember876:B4626ECD-63F0-72EC-A223-FCB6CE81FA47>`

which is an Ember-specific error, and I don't understand what it means.

Our error is that, when the user code throws an error, IndexedDB shuts down. So there are two separate issues, but from your point of view, you'll be fine if you fix the Ember error.

Most likely the remote/local distinction is just a race condition. This doesn't seem to have anything to do with CouchDB.

**Comment by daleharvey** [comment]
so testing code with uncaught exceptions is not particularly fun

**Comment by broerse** [comment]
The newer version of Ember Pouch don't seem to have this bug anymore. Perhaps close this issue.

**Comment by daleharvey** [comment]
So yeh the ember part wasnt a pouch bug, however we do not handling exceptions thrown inside event handlers at the moment, its likely the fix would be something like

    process.nextTick(function() { self.emit('change'); });

However we already have people worrying about the semantics of when events are emitted so probably best to not rush into it, I have a test case that shows the breakage @ http://paste.pouchdb.com/paste/v624dm/, however, hard to write automated tests for

I dont think we need to consider it a bug, use code should not be throwing unhandled exceptions, but would be nice to fix

**Comment by daleharvey** [comment]
@yaronyg this is when we would a test that is looking for an uncaughtexception (I knew there was a reason somewhere)

**Comment by yaronyg** [comment]
But wouldn't it still be an error? In other words the test would be "We have hardened PouchDB so even when user supplied code does something stupid we don't fail" and then the new error handler code would catch if we were wrong. :)

Now if we WANTED the behavior to be "if the user does something stupid then we intentionally will allow it to throw because we want the user to know" then just specify a try/catch or promise catch and confirm you got the error. The code we added to handle unhandled promise rejections shouldn't get called because the test itself should have caught the error in order to prove it happened.

**Comment by daleharvey** [comment]
I think we specifically want this to not be caught (silently) and for it go back to the uncaughtexception handler so that it at least gets reported in the users console, so the test would be to add an uncaughtexception handler at the start of the test and tear it down etc

**Comment by yaronyg** [comment]
I'm missing something. Sorry. :( If I wanted to test that a function throws then in the test code I would wrap it with a try/catch and make sure that the catch got the exception I was expecting. Sorry for being thick but I'm not getting it.

**Comment by daleharvey** [comment]
if a user has 

```
db.changes.on('change', function() { 
  throw 'an error';
});
```

We do not want it to affect the execution of pouchdb, so we either try catch it or put it in a settimeout, if we try catch it the error is hidden from the user, we could use our own mechanism to give this back to the user, however if we setTimeout it then it will cause an unhandledException and be reported to the user by the environment, that is the standard way (ie:
```
   try { 
      setTimeout(function() { 
        throw 'an error';
      });
    } catch (e) { 
      console.error(e);
    }
```
So I think thats the way we should handle it

**Comment by daleharvey** [comment]
basically our `db.changes.on('change', function() { ` should function as close to `setTimeout` as possible as to make it easy / clear to the user whats going on

**Comment by yaronyg** [comment]
Gotcha! Now it makes sense. And the good news is, that the guards we put in won't affect this at all.

The reason is that near as I can tell there is nothing that can catch an exception thrown from inside of something like setTimeout from the outside but either uncaughtException on the process object in node or window.onerror in the browser. Now the guards we put in are just for unhandledRejection which won't be called in this case because Promises can't catch the exception either.

So the test for this just needs to hook the global uncaughtException/onerror handler during set up and then unregister during tear down and it's all good. But the new guard code shouldn't affect things one way or another.

**Comment by nolanlawson** [comment]
5df3d3659996d59af21c9c6f62619f7210eb44e1
