### ISSUE TITLE
Filtered replication progress

### ISSUE THREAD

**Issue by eforth** [pouchdb/pouchdb#3544]
I initiated a filtered replication between a Cloudant and pouchdb datastore. However I have no clue how to monitor the replication progress. I have attached the "onchange" event to the "sync" method which emits information about the pull and push direction. I also console logged information about the database.

PouchDB information:

db.info:      {"doc_count":487,"update_seq":487,"sqlite_plugin":false,"websql_encoding":"UTF-8","db_name":"doulaRoom","auto_compaction":false}

"onchange" event information:

change:  {"direction":"push","change":{"ok":true,"start_time":"2015-02-17T03:21:40.941Z","docs_read":0,"docs_written":0,"doc_write_failures":0,"last_seq":487,"errors":[],"docs":[]}}

Is there some way to find out the total documents to be synced to the PouchDB datastore?

**Comment by nolanlawson** [comment]
Yes, you can do `db.info` on both databases, which will return a `doc_count`. Then you can just compute how many documents have been replicated.

The NPM Browser app actually does this; you can see [the code](https://github.com/pouchdb/npm-browser/blob/aa5c5fe703f92eecc9dc3bc3c1ad9eed3e712f97/scripts/controllers/main.js#L20-L38) for an example.

Alternatively, the `last_seq`/`update_seq` numbers give you a high-level view of the number of modifications made to the remote database (deletions, modifications, conflicts, all that good stuff), which you can also use to calculate the completion percentage.

**Comment by nolanlawson** [comment]
Oh wait, filtered replication. Unfortunately, there's no way to do that, unless you do `allDocs`, filter your documents in memory, and count them up that way. Which will probably be pretty inefficient.

For the record, I don't usually recommend filtered replication at all; it usually isn't doing what you think it's doing (i.e. if you're trying to use it for access privileges, then [that's bad](https://github.com/nolanlawson/pouchdb-authentication#some-people-can-read-some-docs-some-people-can-write-those-same-docs)), and the performance is often not great. If you can just replicate an entire database without filtering, then that's usually better.

**Comment by eforth** [comment]
Thanks for the quick response Nolan. I have been evaluating two methods: per-user database and filtered replication but I was leaning towards per-user. Your response proves that per-user is the right method. Thanks again.

**Comment by nolanlawson** [comment]
Good choice; per-user DB is usually the best option for CouchDB.
