### ISSUE TITLE
Report db.adapter in the db.info()

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3567]
`db.info()` is a good place to stick all our debugging information, so it's kind of silly that it doesn't include the adapter (idb/websql/leveldb). Right now you have to get that from `db.adapter`, which is a quasi-standard API.

In Node.js, I also believe it doesn't report the underlying *DOWN adapter that's used (leveldown/MemDOWN/etc.). It would be nice if it did.

**Comment by daleharvey** [comment]
Closed by https://github.com/pouchdb/pouchdb/commit/01b305791dfb58c86f3a66a8ba4c75e4a5f555c8
