### ISSUE TITLE
error in replicator: docs.forEach is not a function

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3568]
Reported by @svnlto, somehow the replicator is requesting a doc with `open_revs=['1-x']`, which shouldn't even happen because first-gen docs should not be requested that way, and then the result is an object rather than an array. Cannot reproduce quite yet.

https://cloudup.com/cW-wlRaFCNe

```
pouchdb:api http://localhost:8888/data/userdb-622e706965636b40782d696f6e2e6465 +124ms allDocs success Object {total_rows: 40, offset: 0, rows: Array[40]}
vendor.js:23704 pouchdb:api http://localhost:8888/data/userdb-622e706965636b40782d696f6e2e6465 +3ms get 7654039ff1fae5d9280e8b2063018bf0 Object {revs: true, open_revs: Array[1], attachments: true}
vendor.js:23704 pouchdb:api http://localhost:8888/data/userdb-622e706965636b40782d696f6e2e6465 +76ms get success Object {_id: "7654039ff1fae5d9280e8b2063018bf0", _rev: "1-364414175717df854da6e985d1bef0a3", gender: "", firstname: ""â€¦}
storage.js:108 error TypeError: docs.forEach is not a function {result: Object, stack: (...), message: "docs.forEach is not a function"}
vendor.js:21891 Uncaught (in promise) TypeError: docs.forEach is not a function {result: Object, stack: (...), message: "docs.forEach is not a function"}(anonymous function) @ vendor.js:21891
pouchdb:api http://localhost:8888/data/userdb-622e706965636b40782d696f6e2e6465 +219ms get success Object {_id: "7654039ff1fae5d9280e8b2063000394", _rev: "1-fcd901e62adbf5e92fb1394a401b1a6a", gender: "", firstname: "", lastname: ""â€¦}
storage.js:108 error TypeError: docs.forEach is not a function {result: Object, stack: (...), message: "docs.forEach is not a function"}
```

**Comment by nolanlawson** [comment]
@svnlto Are you using auto-compaction or doing `compact()` at all? I'm trying to repro, but no luck so far. It looks like it could be a race condition related to compaction.

**Comment by nolanlawson** [comment]
I've tried to reproduce this in various ways, but I'm not succeeding. I know you said it was a fresh database with only generation-1 documents, so I tried replicating a database with 1 thru 1000 documents, with various combinations of compaction and replication. Couldn't reproduce.

**Comment by svnlto** [comment]
Just a hint, this only occurs on a setup that uses the couchperuser plugin. I've just tried this using various versions of stock couchdb and did not run into this issue.

I've created a docker instance that sets up the above couch instance. 

https://gist.github.com/svnlto/eac6c3aced6e2b816395

**Comment by nolanlawson** [comment]
Super awesome; thanks for your work to debug this. I should be able to look into this around tomorrow night or so, unless someone else wants to jump in on it. Starting to think it really is a couchperuser issue instead of a PouchDB issue...

**Comment by svnlto** [comment]
Bear in mind that this also needs `pouchdb-authentication` to be used. The setup is a little complex tbh..

**Comment by svnlto** [comment]
Also happy to pair on this btw.

**Comment by svnlto** [comment]
Terribly sorry.. it seems I've overlooked a part of my setup that has changed recently. We have nginx in front of couchdb and somebody tampered with the rewrite rules here..

You can close this issue.

**Comment by nickcolley** [comment]
Thanks for the follow up @svnlto! Glad you found the issue. :+1:

**Comment by nolanlawson** [comment]
Oh good, I thought I was going crazy for a second there! :stuck_out_tongue: Your bug seemed impossible.

You know what, though: while trying to repro it, I found another bug: https://github.com/pouchdb/pouchdb/pull/3570. So it's all good in the end. :)

**Comment by rvanzon** [comment]
sorry to comment on such an old thread. But I have the same problem, and can't figure out what is going wrong. @svnlto do you remember what was wrong with the rules?

It looks like the shim for _bulk_get doesn't have docs in the results in collapseResultsAndFinish()
