### ISSUE TITLE
Use pouchdb-promise

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3574]
I totally did not realize that @cwmma had written this: https://github.com/calvinmetcalf/pouchdb-promise. This can also make the plugins a lot cleaner. :)

**Comment by daleharvey** [comment]
We are getting very close to being able to drop Promise fallbacks, its just ie and old safaris now plus the next node release, I think we have it fairly clear by removing bluebird

**Comment by marten-de-vries** [comment]
Also, ``pouchdb-promise`` is unnecessary in the first place with ``pouchdb/extras/Promise`` being available.

**Comment by nolanlawson** [comment]
I tried to convince @calvinmetcalf to deprecate it, but he pointed out that it's kinda nice not to have to pull in all of pouchdb as an npm dependency.
