### ISSUE TITLE
fetching all _users

### ISSUE THREAD

**Issue by fgrs** [pouchdb/pouchdb#3576]
is there a way of getting all the users from _users db in couchdb?

**Comment by nolanlawson** [comment]
Sure, `_users` is just a database like any other one:

    curl "http://localhost:5984/_users/_all_docs?include_docs=true"

From PouchDB, you can access it like normal:

```js
var db = new PouchDB('http://localhost:5984/_users');
db.allDocs({include_docs: true})
  .then(console.log.bind(console))
  .catch(console.log.bind(console));
```

Does that help?
