### ISSUE TITLE
Changes since: 'now' retriving since update_seq-1

### ISSUE THREAD

**Issue by paramburu** [pouchdb/pouchdb#3579]
What is the default behavior for since in changes?

I have a localDB and remoteDB synced live:true.

When I do an allDocs from localDB and then monitor changes live:true and since:'now', I end up with the last document from allDocs going through changes creating a duplicate (getAllMessages gets all the docs and "delivers" them). Then, every time a reload the site I get the last message twice.

```javascript
this.getAllMessages().then(function () {
    localDB.changes({
        since: 'now',
        include_docs: true, // jshint ignore:line
        live: true
    }).then(function(changes) {
        var msg = changes.change.doc;
        _this.deliverMessage(msg);
    });
});
```

Seems to be doing the same as:

```javascript
this.getAllMessages().then(function () {
    localDB.info().then(function (info) {
        localDB.changes({
            since: info.update_seq - 1, // jshint ignore:line
            include_docs: true, // jshint ignore:line
            live: true
        }).then(function(changes) {
            var msg = changes.change.doc;
            _this.deliverMessage(msg);
        });
    });
});
```

Notice `info.update_seq - 1`. Works as expected with `info.update_seq` alone.

I've tried to see if I could find anything in the code but 'now' seems to be the same as info.update_seq. I don't know how this is happening.

I'm assuming this has something to do with syncing but haven't tested that far.

**Comment by nolanlawson** [comment]
This is something we changed recently to support Cloudant/Couch 2.0. Their sequence "numbers" aren't numbers anymore, so the old `update_seq - 1` trick doesn't work anymore.

I thought this issue with "changes firing one too many times" was fixed, but I guess not. I think the changes feed needs to know to skip the first one when it's in `"now"` mode.

**Comment by nolanlawson** [comment]
Hm yeah, I can't reproduce: https://github.com/pouchdb/pouchdb/pull/3580

Maybe it's fixed in master? Try http://pouchtest.com/nightly and see if that fixes it. Else can you post a live reproducible test?

**Comment by paramburu** [comment]
I'm so sorry I've wasted your time. You are right, it was fixed I just didn't find the issue before posting my problem.

I was using angular-pouchdb but didn't realized the dependencies were out of date.

Again, really sorry.

**Comment by nolanlawson** [comment]
Oh shoot, yeah, angular-pouchdb is usually a bit behind us. I wish there was a good way to fix that.
