### ISSUE TITLE
not working in mobile(ios) safari !

### ISSUE THREAD

**Issue by chandu0101** [pouchdb/pouchdb#3581]
I am using pouchdb 3.3.0 in my app , its working fine in chrome/firefox/safari on desktop and chrome android.

but on mobile(ios 8.1.3) safari i am getting following error while saving doc

```
{"status":500,"name":"Object","message":"unknown"}
```

**Comment by nolanlawson** [comment]
Can you provide more details? The 500 error is really high-level. If you open up a debugger in desktop Safari (go to preferences on your phone, choose Safari, then enable "Web Inspector," then connect your phone, then open up desktop Safari, then choose Develop, then choose your website), then you can set a breakpoint and print out the full error information.

Also, a live reproducible test case would be really helpful.

**Comment by chandu0101** [comment]
i debugged a little more!.  The actual reason is 
```
could not prepare statement (23 access to sqlite_master.type is prohibited)
```
i found the solution for this problem here http://git.yathit.com/ydn-db/issue/83/problems-with-schema-access-from-iphone

i don't know how private browsing enabled on my iphone!

@nolanlawson thanks for reply .

I am closing this issue :)

**Comment by nolanlawson** [comment]
Ah okay, that's good to know!
