### ISSUE TITLE
Pouch v3.3.1 Not working with the Ionic frame work on Ipad

### ISSUE THREAD

**Issue by indigoshade** [pouchdb/pouchdb#3587]
Hello The latest version of Pouch dose not work with The Ionic framework (http://ionicframework.com/) on iPad. Ionic is a Cordova / Angular mobile app framework. There most be some conflict with it and the Latest version.

The 3.2.0 Version of Pouch works great with this framework.

**Comment by nickcolley** [comment]
Hey @indigoshade!

Are you using any PouchDB plugins or just the standard library?

If you could share a live demo of the error that'd be helpful too if that's possible.

**Comment by nolanlawson** [comment]
Yeah, we've got a sample app using the Ionic framework, and it works fine. If you could try the sample app and tell us what's not working, that would be helpful: https://github.com/nolanlawson/pouchdb-ionic

**Comment by indigoshade** [comment]
Thank you I will try that out and report back. Love pouch.

**Comment by daleharvey** [comment]
Not reproduced
