### ISSUE TITLE
'create' event could fail when there are conflicts

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3595]
In the `changes()` feed, we have a `'create'` event. But currently it only fires if the change looks like this:

```js
['1-x']
```

However, it is possible that the change could look like this:

```js
['1-x', '1-y']
```

This could occur if two users create the same document with the same `_id` and then they are synced with conflicts.

I think this could show up in user code as a bad bug, if people are really depending on `'create'` to be the thing that informs them that a new document was created. Not sure what the solution should be, though.

**Comment by daleharvey** [comment]
Since we are removing it in https://github.com/pouchdb/pouchdb/issues/3833, closing this
