### ISSUE TITLE
Ajax headers are not being overriden correctly in setup.js

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3598]
Looking at the code, it seems like we have a bug. In `setup.js` we do:

```js
var subOpts = utils.extend(true, opts, db.__opts || {});
```

But if the `opts` are supposed to override the database's native opts, then shouldn't the order be reversed? Also, it would make me feel better if we were cloning, i.e.:

```js
var subOpts = utils.extend(true, {}, db.__opts, opts); // db.__opts is never undefined
```

This needs tests, though, and so far I've been unable to think of tests for the `ajax`/`headers`/stuff like that.

**Comment by daleharvey** [comment]
We no longer do this, I added seperate tests for the ajax headers stuff and am about to fix a related problem so it I see any issues will fix in there - https://github.com/pouchdb/pouchdb/issues/3491
