### ISSUE TITLE
Switch to soft destroy() in IndexedDB

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3599]
Due to errors like https://github.com/pouchdb/pouchdb/issues/2181, https://github.com/pouchdb/pouchdb/issues/3415 and https://github.com/pouchdb/pouchdb/issues/3539, I'm starting to think it would make sense to avoid `indexedDb.destroyDatabase` entirely. It just seems very unstable on a variety of browsers (remember all the race conditions in IE?).

We could avoid those headaches by just doing the same thing we do for WebSQL - i.e. destroy all the objectStores, without destroying the entire database.

**Comment by nolanlawson** [comment]
Of course this will need testing in various browsers to make sure it is a reasonable approach.

**Comment by marten-de-vries** [comment]
This would spell trouble for the Chrome and Firefox browser addons. Their ``allDbs()`` function depends on ``webkitGetDatabaseNames()`` (or a manually coded equivalent for Firefox). It's probably possible to find a workaround for that, but it's something to keep in mind.

**Comment by nolanlawson** [comment]
We should be able to fix the addons independently. Maybe we can empty the `objectStores` and then add a flag or something to the `meta-store` to say that the database is deleted?

**Comment by marten-de-vries** [comment]
That should work.

**Comment by daleharvey** [comment]
So we havent had problems with this in a while, getting to nailing down the last of the existing issues most of which werent due to destroy, so going to say we are ok with this for now. I would always prefer to get these bugs fixed upstream than to work around them.
