### ISSUE TITLE
need help with LevelDB

### ISSUE THREAD

**Issue by chino23** [pouchdb/pouchdb#3604]
Hi,

I'm currently trying to run PouchDB on leveldb using node.js.

So I have the pouchdb node module, ok. But when I do

````
var pouch = new PouchDB('./path/to/db');
````

It tells me that leveldown adapter can't be found.

Even if I install it and add

````
{db: require('leveldown')}
````

It doesn't work, telling me other errors (didn't self register)

I'm a bit lost when it comes to leveldb. So leveldb uses leveldown as standard adapter, but I can use others to replace it?

I've got it working with memdown but I need permanent storage, preferably in a file. Why doesn't the leveldown work, when it is set to the standard one?

**Comment by nolanlawson** [comment]
Are you using Windows? http://pouchdb.com/errors.html#windows_leveldown

**Comment by chino23** [comment]
I'm on Mac, but for some more detail, I try to run it in nwjs which is powered by io.js 1.2.0 at the moment.

**Comment by nolanlawson** [comment]
Ah okay, if I recall correctly, there were issues building LevelDB on io.js. Check out [the PouchDB-NW guide](https://github.com/nolanlawson/pouchdb-nw), which has a working app and instructions for using LevelDB, WebSQL, or IndexedDB (you have the option of all three).

**Comment by chino23** [comment]
Thanks @nolanlawson, that works great after using the nw-gyp build step.

One question: websql and indexeddb store the database file in the user library, so it's independent from reinstalling the app. leveldb however uses a file within the container, that means if I update the whole .app file on mac, the database would get deleted. 

Is there a way to store the leveldb data in the user library as well?

**Comment by nolanlawson** [comment]
I don't know. LevelDB lets you pass in whatever file you want, though, e.g. `new PouchDB('/path/to/file')`.

**Comment by chino23** [comment]
Ok. I think I'll have to stick to websql or indexeddb then so i can always have it in the users settings outside of the app.

As usual, thanks a lot for your quick and helpful support here! Please keep up the great work! :)
