### ISSUE TITLE
Better documentation for filtering on filters/query_params/doc_ids/views

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3608]

**Comment by sphaso** [comment]
Hey Nolan. While you work on the docs, I was wondering about writing a little blog post detailing my experience with filtered replication, what do you think?

**Comment by nolanlawson** [comment]
@spaso please do! Would love to have a guest blog post

**Comment by nickcolley** [comment]
:+1:  Would be great.

**Comment by sphaso** [comment]
Great! I have a first draft ready, will probably issue a PR in the weekend :)

**Comment by SinanGabel** [comment]
Hi!
It seems that with a filtered replication this works:
```
{
  _id: '_design/mydesign',
  filters: {
    myfilter: function (doc, req) {
      return doc.type === req.query.type;
    }.toString()
  }
}

# but this does not
{
  _id: '_design/mydesign',
  filters: {
    myfilter: function (doc, req) {
      return doc.key === req.query.type;
    }.toString()
  }
}
```
even though (assuming) the .key would be supposed to match .type
Is this on purpose?

Thanks,

Best,
Sinan

**Comment by nolanlawson** [comment]
@SinanGabel Yeah, there is no relationship between `req.query` and `doc`; you have to define that yourself.
