### ISSUE TITLE
Implement new 'location' option for SQLite Plugin

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3617]
Per https://github.com/brodysoft/Cordova-SQLitePlugin/issues/200. This is basically to avoid getting rejected from the App Store by Apple due to _\*insert hand waving\*_.

**Comment by brodybits** [comment]
Nice :+1:

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/82d8897635e118bd03e7d9a3f6b6adeaf053b255
