### ISSUE TITLE
Replication should use POST http method when doc_ids are passed as an option

### ISSUE THREAD

**Issue by stheobald** [pouchdb/pouchdb#3622]
Code exists with this intention, but the request is ultimately a GET.

https://github.com/pouchdb/pouchdb/blob/a4ce4c68654e0059a10be11840b84c796f3d63b2/lib/adapters/http/http.js#L791-L806

No specific test exists to check this behaviour. The code should be covered by:
https://github.com/pouchdb/pouchdb/blob/a4ce4c68654e0059a10be11840b84c796f3d63b2/tests/integration/test.replication.js#L1430-L1452

**Comment by nolanlawson** [comment]
How long is the URL that is created? Is it longer than 2,000 characters?

**Comment by nolanlawson** [comment]
Closing since it seems to have been taken care of by this test: https://github.com/pouchdb/pouchdb/commit/f1329a06819fe1a36900d59e706f6f2e24ebfa98#diff-9f91584129f9de3c58915515b5f05c43R1268
