### ISSUE TITLE
`processDiffDoc` doesn't follow API, throws error

### ISSUE THREAD

**Issue by r24y** [pouchdb/pouchdb#3624]
In [lib/replicate.js:239](https://github.com/pouchdb/pouchdb/blob/master/lib/replicate.js#L239), the results of a call to `get()` are handled as follows:

```
      return src.get(id, opts).then(function (docs) {
        docs.forEach(function (doc) {
          // ...
        });
        // ...
      });
```

However, the documentation for `.get()` states that the callback is invoked with one doc, implying that the correct code is as follows:
```
      return src.get(id, opts).then(function (doc) {
        // ...
      });
```

This breaks sync for me.

**Comment by nolanlawson** [comment]
When you pass in `open_revs`, it actually returns a list of docs. We have automated tests against many different databases (CouchDB, PouchDB Server, Cloudant) to confirm that it works this way.

What database are you using that returns a single doc when `open_revs` is passed in? Can you provide a live test to reproduce?

**Comment by baconscript** [comment]
Ah, it seems like `open_revs` isn't being passed in; either it's getting stripped out or it's not getting added in. It's pretty deep in my call stack so I'll have to investigate further.

I'll post a minimal test case soon.

**Comment by daleharvey** [comment]
Yeh we test this very thouroughly, if you have a case to reproduce please reopen, cheers
