### ISSUE TITLE
Force appcache update

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#3626]
I'm wondering if there's a better solution that current to update the appcache when a user visits the site.
Currently if you came from Twitter and had an older version cached you'd see no changes until you refreshed again.

I'd go as far as saying most people will not refresh.

**Comment by nolanlawson** [comment]
I think that's a pretty poor solution. Isn't the recommended solution to show a non-modal popup asking the user if they'd like to refresh?

Alternatively, we could just get rid of AppCache... :stuck_out_tongue:

**Comment by nickcolley** [comment]
I'm not suggesting to force a refresh, was hoping there was another way. The update indicator is a nice idea but just seems like a faff when we just want don't really want the user to control the version they're seeing..

(Could get rid of it yeah..)

**Comment by nolanlawson** [comment]
Adding Dash support (https://github.com/pouchdb/pouchdb/issues/3630) would be another way to make it work offline. ;)

**Comment by nickcolley** [comment]
Not interested in closed platform doc apps, so don't really consider that an alternative. :P

**Comment by nolanlawson** [comment]
Yeah, it's not a true replacement. Also we recently got this compliment, so we must be doing something right: https://twitter.com/sujayt/status/575398863151833089

**Comment by nickcolley** [comment]
I think we should go with the ol' "There's new stuff press me" notification.

**Comment by nolanlawson** [comment]
1c4f1f14e5b5c5fb5e3bf0e3794047157a84b4c9
