### ISSUE TITLE
Weird dotted outline in Firefox on tabs

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3627]
![screenshot 2015-03-10 10 32 52](https://cloud.githubusercontent.com/assets/283842/6578349/03385ad4-c71a-11e4-8d71-90b78c08e131.png)

@nickcolley I'm guessing this is a simple CSS fix, but I dug around a bit and wasn't sure what to do.

**Comment by ialbescu** [comment]
a {
   outline: 0;
}

https://css-tricks.com/removing-the-dotted-outline/

**Comment by nolanlawson** [comment]
Submit a PR? :D

**Comment by ialbescu** [comment]
Sorry, but I don't know understand what you mean.

**Comment by nolanlawson** [comment]
I'm asking if you would mind submitting a pull request. :) It looks like the fix should go in [https://github.com/pouchdb/pouchdb/blob/f4ab73c7a0a62a38145aaf3fa11948a606a35076/docs/static/less/pouchdb/navs.less](navs.less).

**Comment by ialbescu** [comment]
Hope this is what you want.

**Comment by nickcolley** [comment]
Dotted line is there for accessibility reasons, think we might be okay here to disable it, will review thanks for the contribution!

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/0e080b0896218d8a2e5b68a25bc53d15d07fb7bc
