### ISSUE TITLE
Wrong link domain on website

### ISSUE THREAD

**Issue by ialbescu** [pouchdb/pouchdb#3628]
Looking at Api documentation found here: http://pouchdb.com/api.html#query_database

I have click on the link from: Read the query guide for a good tutorial

That link goes to: http://localhost:4000/guides/queries.html instead of http://pouchdb.com/guides/queries.html

I think either the link is hardcoded or the deploy tool doesn't replace the local server with the production one.

**Comment by nolanlawson** [comment]
Thanks for reporting. Will fix!

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/377201224ac6af859ae81617a88a12ecad82c5e1
