### ISSUE TITLE
Contribute PouchDB/CouchDB docs to Dash

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3630]
[Dash](http://kapeli.com/dash) is an incredibly useful app, and I know a lot of developers who rely on it.

The fact that popular databases like MongoDB and MySQL are available by default, whereas CouchDB is not, makes me sad. :(

It looks like some work was done to solve this problem (https://github.com/SteveBenner/couchdb-dash-docset/issues/1) but nothing came of it. I downloaded the docs in question, and they are up-to-date with CouchDB 1.4.

I haven't looked into how to contribute the PouchDB docs, but since they're just HTML, it seems like it ought to be easy to do.

**Comment by vdclouis** [comment]
Cool initiative! I would like to see CouchDB and PouchDB on Dash. If I find some time I would love to help out!

**Comment by nolanlawson** [comment]
Cool, we'd love the help! :smiley:  You can build pouchdb docs from source by doing:

```
git clone https://github.com/pouchdb/pouchdb.git
cd pouchdb
npm install
BUILD=1 npm run build-site # HTML docs are now in /docs/_site/
```

You'll need to have ruby and jekyll installed beforehand (`gem install jekyll`).

**Comment by nolanlawson** [comment]
Took [a stab](https://github.com/nolanlawson/couchdb-dash-docset/commit/21113d75c1b25dd13cfc8fbbeaf1add5fcb23748) at updating the CouchdB docset generator, but ran into [a bug with the docs hosted on readthedocs.org](https://issues.apache.org/jira/browse/COUCHDB-2637).
