### ISSUE TITLE
Replication mechanism in 3.3.1 compared to 2.2.3 + "Maximum call stack size exceeded error" in 2.2.3

### ISSUE THREAD

**Issue by JohnAtWassa** [pouchdb/pouchdb#3635]
On Chrome (v35 Android and v40 on Mac) we used the following code with 2.2.3 to replicate from a CouchDB 1.5.0 database : 

```javascript
            PouchDB.replicate(remote, db, {
                filter: "myview/myfilter",
                since: lastSeq,
                include_docs: true,
                query_params: {
                    /* ... query_params ... */
                }
            });
```

It resulted to a single initial call like

```
GET /db/_changes?timeout=25000&style=all_docs&filter=myview/myfilter&1param=value1&since=0&limit=100&_nonce=W3L9aulYHc05DTKZ
```

It worked fine until a few days when PouchDB started to fail, displaying a "Maximum call stack size exceeded error". We assumed this was because the DB had become to big for PouchDB.

We tried to switch 3.3.1. The same replication code results in continuous calls like

```
GET /db/_changes?timeout=25000&style=all_docs&1param=value1&since=0&limit=100&_nonce=W3L9aulYHc05DTKZ
GET /db/_changes?timeout=25000&style=all_docs&1param=value1&since=100&limit=100&_nonce=W3L9aulYHc05DTKZ
GET /db/_changes?timeout=25000&style=all_docs&1param=value1&since=0&limit=200&_nonce=W3L9aulYHc05DTKZ
...
```

`_changes` is called multiple times, each time with the `since` parameter increased by the number of `batch_size`. Moreover, the filter name is not in the query anymore, so ALL documents are replicated.

Ultimately, replication fails with

**error: true, message: "Database encountered an unknown error”, name: "unknown_error”, status: "aborting”, status: 500**.

We tried the Promise syntax, but same result.

**Comment by nolanlawson** [comment]
Any chance you could provide a stack trace? Would be useful to see which method is calling itself over and over again. Probably the solution will be to just wrap it in a Promise, so that the call stack doesn't increase without bound.

**Comment by JohnAtWassa** [comment]
I was just told that removing the `include_docs` parameter seemed to make it work. I'm not at the office anymore but I will have a confirmation by Monday.

Anyway I'm not a JS developper myself so if you could tell me how to get the stack trace just in case the include_docs` solution do not work, I will be glad to provide it.

**Comment by nolanlawson** [comment]
If you look at the console in the Chrome Dev Tools, you should see a stacktrace. Else if you're not sure, if you could provide a live reproducible test case, that would help.

The `include_docs` thing might be a red herring. It could be that it's just adding enough extra requests to push it over the edge in particular browsers. Keep in mind that "maximum call stack exceeded" will vary from browser to browser, and even vary depending on how much memory your system has at the moment.

**Comment by nolanlawson** [comment]
> I was just told that removing the `include_docs` parameter seemed to make it work.

Which one? This is used in multiple places.

**Comment by JohnAtWassa** [comment]
> Which one? This is used in multiple places.

The one in the replicate function. It was on the docs for 2.2.3 but not for 3.3.1.

Actually after having tried replication without `include_docs`, no more error on 3.3.1 but all documents are replicated instead of only the ones that should be by the filter.

**Comment by JohnAtWassa** [comment]
Here's what's display in the Chrome console. My mistake, the version currently used in production was not 2.2.3 but 2.2.0.

Uncaught RangeError: Maximum call stack size exceeded pouchdb-2.2.0.min.js:2
r pouchdb-2.2.0.min.js:2
(anonymous function) pouchdb-2.2.0.min.js:2
o pouchdb-2.2.0.min.js:2
a.merge pouchdb-2.2.0.min.js:2
w pouchdb-2.2.0.min.js:1
t.onsuccess

**Comment by nolanlawson** [comment]
Can you use the non-minified version so that it prints out the function names? Back versions are available at https://github.com/pouchdb/pouchdb/releases

**Comment by JohnAtWassa** [comment]
OK I'll try that.

FYI the only way we found to bypass this issue is to stop replicating CouchDB.
We manually call `_all_docs` and then do the filtering locally in JS. This is really not the best solution but it's working and, because filtered replication is soooo slow in CouchDB, this is now much much faster.

**Comment by nolanlawson** [comment]
Using `allDocs()` is not a good solution, because you are not managing conflicts anymore... Yes, filtered replication is slow, but there are two solutions to that:

1) Filter from CouchDB A to CouchDB B, then do an unfiltered replication from B to PouchDB. You double your data server-side, but CouchDB can handle it.

2) Use streaming APIs like the pouchdb-load/pouchdb-dump plugins or pouchdb-replication-stream. In the future, we're also working to add a bulk API to make this automatic.

As for this particular issue, I suspect it is going to be a really easy fix, but the hard part will be finding the function that is calling itself too many times. Thank you for investigating and providing feedback, as I cannot reproduce. :(

**Comment by daleharvey** [comment]
We have done a whole bunch of work on this, expecting it to be fixed, thanks

**Comment by staxmanade** [comment]
I just got this error today.

```
Unhandled promise rejection RangeError: Maximum call stack size exceeded
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2067:23)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2057:32)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2070:29)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2070:29)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2070:29)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2057:32)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2070:29)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2070:29)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2057:32)
    at clone (http://localhost:8080/jspm_packages/npm/pouchdb@5.2.1/dist/pouchdb.js:2070:29)
```

**Comment by kuchenkiller** [comment]
Getting the error Maximum call stack size exceeded in Chrome and too much recursion in Firefox. Local PouchDB is working perfectly, connecting to a remote CouchDB also works. As soon as I do anything with the remote DB (put, post, synch) I get the too much recursion. Using Angular2 + Typescript, pouchdb v. 6.3.4.
I have a question on stackoverflow showing what I tried so far (https://stackoverflow.com/questions/45877953/pouchdb-too-much-recursion-stackoverflow-on-remote-connection). Any help would be apprechiated. Thanks
