### ISSUE TITLE
Local LRU Cache & Offline Storage with limited size?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#3641]
I would like that all clients store a database replica locally as a cache and offline storage. However, if the database is very large this becomes impossible. Is it possible to create a local replicate with a maximum size where least recently used items are automatically purged?

**Comment by nolanlawson** [comment]
`purge()` is not implemented, but you can simply `remove()` revisions you don't want anymore, and this is almost as good as purging. The database will keep a record of the doc ID itself, the fact that it's deleted, and the IDs of any revisions. So essentially a very tiny amount of metadata, and certainly not any of the attachments or the document body itself.

**Comment by daleharvey** [comment]
answered
