### ISSUE TITLE
Windows Phone support

### ISSUE THREAD

**Issue by Unkan** [pouchdb/pouchdb#3643]
We're currently attempting to port one of our cordova applications to windowsphone and we're using pouchdb for offline storage. Eventhough it is [supported](http://pouchdb.com/adapters.html#pouchdb_in_the_browser) we haven't been able to make it work, with our without the cordova sqlite plugin.

 I've created a sample project with the sqlite plugin installed and imported and attempted to get the snippet below to run on deviceready.

```javascript
function testdb(adapter) {
    var db = new PouchDB('test_db1', {adapter: adapter});
    db.put({_id: 'test', title: 'document'})
        .then(function(response){
            console.log('Attempting put with ' + db.adapter);
            console.log(response);
        })
        .catch(function(error){
            console.warn('Failed put with ' + db.adapter);
            console.log(error);
        });
    // db.destroy();
}
testdb('websql');
//testdb('idb');
```

With the 'websql' adapter the .then-promise times out and doesn't log anything and on the 'idb' adapter it logs the fail.

Are we just doing something wrong or is windowsphone currently not supported?

**Comment by nolanlawson** [comment]
Windows Phone ought to work. When you use it without the SQLite plugin, are you using IndexedDB or WebSQL? (Windows Phone does not have WebSQL.)

Alternatively, there is apparently an option in Windows Phone to [allow websites to store content](https://github.com/nolanlawson/pouchdb-phonegap-cordova/issues/1#issuecomment-76691014), which may be disabled on the phone you're using.

**Comment by Unkan** [comment]
I've tried with both IndexDB and WebSQL, with and without the sqlite plugin.

Using the `idb`-adapter the put fails with an error response of `No valid adapter found`.

I've checked the windows phone 8.1 emulator and it has the option enabled

**Comment by nolanlawson** [comment]
We will need more information. If you use the unminified pouchdb source code, you'll see a function called `valid()` that determines whether or not IndexedDB is valid (there is also one for WebSQL). I would be interested to see why Windows Phone reports itself as invalid.

Keep in mind that none of the PouchDB developers own a Windows Phone, and this is a free & open-source project with no commercial backing, so we are very grateful for any insights you can provide here. :)

**Comment by nolanlawson** [comment]
E.g. in [this file](http://cdn.jsdelivr.net/pouchdb/3.3.1/pouchdb.js), you would set a breakpoint on the `IdbPouch.valid` function, and then let me know why it says it's invalid.

**Comment by nolanlawson** [comment]
For the record, this issue never specified whether the phone was Windows Phone 8 or Windows Phone 7. We support Windows Phone 8 just fine (hell, I've run the tests myself on a real device), so I am inclined to just close this issue @daleharvey and suggest that we document which version of Windows Phone we support.

**Comment by nolanlawson** [comment]
Oh wait, we [already document](http://pouchdb.com/learn.html) Windows Phone 8+. This issue is done IMO:

**Comment by simran100** [comment]
Hi,I am getting PouchDb adapter undefined Error while running my  SAPUI5 project on windows 8.1 phone via visual studio. Can someone please help me out,what adapter should i use to run my project on windows 8.1 phone

**Comment by nolanlawson** [comment]
@simran100 I think we should be able to help you in https://github.com/pouchdb/pouchdb/issues/6205 :)
