### ISSUE TITLE
Ideas for student projects

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3644]
Last year, we had some success with bringing in some students to work on the project. @daleharvey was a great mentor, and I think overall it was a boon to PouchDB as well as to the students.

I've got some ideas for new features that could be explored by students, and which they might find interesting. In particular I'm trying to think of projects that are 1) self-contained, 2) well-defined, and 3) kinda fun! Here's what I have so far:

1) Write an in-memory adapter to replace MemDOWN. I.e. this would be an adapter at the level of `idb`/`leveldb`/`websql`. Benefits would include: lower filesize footprint (because MemDOWN browserifies too much), possibly better performance, and an opportunity to create the simplest possible PouchDB adapter. Also it would be a neat opportunity to try to build something to compete with [LokiJS](http://lokijs.org/).

2) Implement `purge()` (https://github.com/pouchdb/pouchdb/issues/802). This is super-well-defined and also highly needed. Would require modifications to all four adapters, so would give them an opportunity to learn about LevelDB/WebSQL/IndexedDB/Ajax.

~~3) Implement `multipart/mixed` (https://github.com/pouchdb/pouchdb/issues/2832) for compatibility with Couchbase Sync Gateway and faster attachment replication. Probably mostly Ajax-level stuff here.~~ this is fixed

4) Performance-tuning, benchmarks. Our current benchmark setup is a little weak. Would be nice to have more benchmarks against other players in this field (LocalForage, YDN-DB, Dexie.js).

5) [pouchdb-find](http://nolanlawson.github.io/pouchdb-find/), still got lots of work to do.

6) Native indexes for map/reduce for waaaaay better map/reduce performance (https://github.com/pouchdb/pouchdb/issues/2280). Kinda ambitious, but definitely a meaty project.

Other ideas?

**Comment by nolanlawson** [comment]
Other stuff that would be cool:

- figuring out the attachment memory issue (learn how to use the profiler tools!) (https://github.com/pouchdb/pouchdb/issues/3640)
- implement atts_since for better attachment replication performance (https://github.com/pouchdb/pouchdb/issues/2674)
- improve CORS performance for GETs - this is something where we got schooled by folks on the W3C mailing lists, so definitely there's some black-magic web stuff going on here that would be interesting to learn about (https://github.com/pouchdb/pouchdb/issues/3573)

**Comment by nolanlawson** [comment]
Website idea: @nickcolley has mentioned wanting to put the guide examples inline so you can run them from pouchdb.com itself.

**Comment by nolanlawson** [comment]
Another good one: fixing replication when more than one tab is open: https://github.com/pouchdb/pouchdb/issues/2493. Will require having some kind of global replicator or some way for replicators to acknowledge each other and ensure only one is running at a time.

**Comment by nolanlawson** [comment]
Cool plugin idea: a replicator that replicates all the non-leafs, so P/CouchDB basically becomes Git. All it would require is a fork of `replicate.js`.

**Comment by daleharvey** [comment]
Closing out, a lot of these are worked on etc
