### ISSUE TITLE
Avoid "Authentication Required" popup

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#3650]
I'm trying to use pouted-authentication. However, the problem is that when I create my database object I get a "Authentication Required" pop dialog before I get the change to perform a login.

Any suggestions on how to workaround this? e.g. don't do any server calls other than login when not authorised?

**Comment by nolanlawson** [comment]
I believe the solution to that setup is this: https://github.com/nolanlawson/pouchdb-authentication#everybody-has-to-be-logged-in-to-do-anything

**Comment by ronag** [comment]
That partly solves the issue. However, if you write the wrong username or password the dialog is shown upon login. Also login doesn't seem to set the auth cookie, so as soon as I try to do something after a successful login I get the dialog again.

**Comment by ronag** [comment]
According to https://code.google.com/p/chromium/issues/detail?id=31582 the dialog shouldn't be shown of wrong credentials are provided. However, that doesn't seem to be the case. Do we need to do something to trigger the proper  behaviour?

**Comment by nolanlawson** [comment]
Are you sure you're doing cookie authentication? Cookie authentication should not show a pop-up.

You have another issue where you ask about cross-domain cookie authentication. It is possible, but it's definitely hard to set up. You need to make sure that the Domain is specified in the cookie that gets sent back.

Honestly if you can avoid CORS at all (e.g. using an Nginx/Apache reverse proxy), then I would strongly recommend it. CORS will make your app slower (more requests than necessary), and it will cause headaches with authentication.

**Comment by ronag** [comment]
Changed to reverse proxy through express (https://cloudant.com/blog/cors-and-reverse-proxies-in-node-js-express/#.VQq4xTBurww).

Still get the popup on invalid username or password.

**Comment by ronag** [comment]
Ok. I solved it with the reverse proxy where I always set 'WWW-Authenticate' to 'None' if statusCode !== 200

**Comment by nolanlawson** [comment]
Awesome, so can I close this issue? :smiley:
