### ISSUE TITLE
Fragment links go to the wrong part of the docs

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3654]
Click this link: http://pouchdb.com/api.html#compaction

For some reason, it takes you to the Plugins section rather than the Compaction section. I think it's maybe because of the new promise/callback switcher.

**Comment by nickcolley** [comment]
Yeah If the page renders quick enough this shouldn't be a problem. https://github.com/pouchdb/pouchdb/issues/3625

Will try and fix this weekend :+1:

**Comment by daleharvey** [comment]
Fixed by https://github.com/pouchdb/pouchdb/commit/253609994e99911d4be6f3fa8971826335de1c0a
