### ISSUE TITLE
websql winningseq is often a floating point number

### ISSUE THREAD

**Issue by dholth** [pouchdb/pouchdb#3655]
Opened the Chrome database in sqlite3, and noticed many winningseq are a floating point number "1.0". Probably harmless but a little messy. Would fix by coercing before insert.

**Comment by nolanlawson** [comment]
Yeah, this is a TODO inside of websql.js. We accidentally save it as a string, which is not a problem because sqlite handles that for us when it joins. But really we should be using ints.

**Comment by nolanlawson** [comment]
I'm hesitant to do a database migration just for this little cleanup that isn't negatively impacting pouchdb's performance, but maybe we can fit it in the next time we do a proper migration.

**Comment by dholth** [comment]
Inserting new ones as proper ints would be more than sufficient.


On Sat, Mar 21, 2015, at 12:57 PM, Nolan Lawson wrote:
> I'm hesitant to do a database migration just for this little cleanup
> that isn't negatively impacting pouchdb's performance, but maybe we
> can fit it in the next time we do a proper migration.


> — Reply to this email directly or view it on GitHub[1].

>


Links:

  1. https://github.com/pouchdb/pouchdb/issues/3655#issuecomment-84389621

**Comment by nolanlawson** [comment]
That's the thing - they're ints in JavaScript, but by the time they get stored in SQLite, they become float-strings.

**Comment by daleharvey** [comment]
At this point it looks like it is not causing any harm, would accept a patch but no need to track
