### ISSUE TITLE
Replicate from local to remote with filters in ddoc

### ISSUE THREAD

**Issue by sphaso** [pouchdb/pouchdb#3658]
Hi, it's me again.           
I've solved (most of) my issues with filtered replication from remote to local, now I'm testing local to remote.
Some good ol' code.

Sync method:
```Javascript
localDB.sync(remoteDB, {
            live: true,
            retry: true,
            filter: 'app/by_user',
            query_params: { "agente": agent }
        })
        .on('change', function(result){
                result.change.docs.forEach(function(change) {
                    if(!change.deleted){
                        console.log("CHANGE!");
                        $rootScope.$apply(function(){
                            $rootScope.$broadcast('upsert', change);
                        });
                    }
                });
        });
```

Save method:
```Javascript
this.save = function(bolla){
            return localDB.get(bolla._id).then(function(doc){
                doc.DataEsposizione = bolla.DataEsposizione;

                return localDB.put(doc);
            });
        };
```

The problem:
this last promise returns "ok: true" and everything seems to be in order, but this local change never gets replicated to the remote DB. If instead of "localDB.put" I write "remoteDB.put" everything works. Of course I cannot use remoteDB.put because I'm writing an offline-first app.

Am I doing anything grossly wrong?
Thank you :)

**Comment by nolanlawson** [comment]
Can you write a live reproducible test case please? I don't see anything obviously wrong here, so it would be helpful to have a live example.

**Comment by sphaso** [comment]
Yes, of course, I just wanted to make sure I wasn't doing anything egregiously wrong first. Test coming up ASAP!

**Comment by sphaso** [comment]
Victory! 
As you suggested in the PR, the ddoc NEEDS to be replicated to the local DB for the whole syncing process to work. This was not really intuitive to me, since simply doing remoteDB.put works instead of localDB.put and my thought process was "the ddoc stays on the server, the client replicates back whatever the server gives to it". Bi-injectivity of ddoc rules was not necessary nor imposed (still, in my skewed understanding).
After many failed attempts at replicating from \ to with different rules I simply threw the towel and relaxed the replicating rules in my filter. That's the result:

```Javascript
function(doc, req) { if(doc._id == '_design/app' || doc.Agents && doc.Agents.indexOf(req.query.agente) > -1){ return true; } return false; 
}
```

It would be nice to have it clearly stated in the docs, as I imagine other people might run into the same issue (or I might be exceptionally dumb).
Thanks!

**Comment by nolanlawson** [comment]
You can also just explicitly put two ddocs in the separate databases. You're not dumb; the ddoc system is just really counterintuitive because it's mixing concerns (documents vs describing how those documents are synced). I have some updated queued for the docs, hopefully it will be clearer from now on, but if not, please feel free to amend the docs! :)

**Comment by sphaso** [comment]
Good point. By having the ddoc replicated I avoid writing it twice tho. 
I see there's already an issue regarding explaining filtered replications better. I'd like to write something about these issues so that others don't fall into the same trap, but you have more experience with the stack so I don't know how much I could add.
