### ISSUE TITLE
Move deps into separate npm package?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#3663]
Right now a lot of the plugins are basically re-implementing what's already in pouch, e.g. pouchdb authentication.

**Comment by nolanlawson** [comment]
It was discussed here: https://github.com/pouchdb/pouchdb/pull/3559#issuecomment-77088805. Seems reasonable, but a lot of work.

**Comment by nolanlawson** [comment]
also https://github.com/pouchdb/pouchdb/issues/3338

**Comment by daleharvey** [comment]
We have some bugs open for the individual modules (like https://github.com/pouchdb/pouchdb/issues/3524) we should just do this on a case by case basis
