### ISSUE TITLE
General question about performance.

### ISSUE THREAD

**Issue by ArnoBuschmann** [pouchdb/pouchdb#3667]
Hi,

PouchDB is a very interesting project, congrats!

I did a few experiments, such as adding/deleting 1000 docs (just one short key/value pair in it -> title: "Hello"). Both, adding and deleting 1000 docs takes about 25 seconds. Now I just want to know, if these are normal values? I used indexedDB in Chrome, CORS is enabled.

Cheers, Arno.

**Comment by calvinmetcalf** [comment]
depends on a lot of factors like how the code is set up and what your computer is like but one thing to keep in mind is that indexedDB and hence PouchDB are async and not all of the time it takes is actually time spend working, some of the time if spend waiting to hear back that the value was written to disk so it's a good idea to distinguish between performance and latency.  So writing 1000 docs one after the other might take a while, but it won't necessarily show down the app while it's doing so.

**Comment by ArnoBuschmann** [comment]
@calvinmetcalf thanks for your reply! Yes, with asynchronicity it's also a matter of design, how/if latency gets percieved. So optimistic updates might be good thing in such cases?

But what actually surprised me a lot was, that while deleting 1000 docs, calls to print db.info() to console were blocked, till the deleting was finished. Strange, somehow.

**Comment by nolanlawson** [comment]
If you use the bulk APIs, you will probably see a ~100x speedup.

**Comment by ArnoBuschmann** [comment]
@nolanlawson Oh yes, thanks for the hint, bulk works indeed great with creating docs! One question though with delete:

Using the bulk api I add
```javascript
_deleted = true
```
for each document. Thereafter db.allDocs() still shows them, guess I do something wrong at this point?
