### ISSUE TITLE
Remove attachement once synced with remote database?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#3668]
Is this possible? Without actually causing the remote database to delete the attachment as well.

**Comment by corps** [comment]
You could could a push only PouchDB, and listen for its change events (you can an event emitter from calling push or sync), then delete content locally once the relevant change event details that the attachment has been pushed.

**Comment by ronag** [comment]
But when I delete the event locally won't that deletion propagate to the server with the next sync?

**Comment by nolanlawson** [comment]
I think what you want is `purge()`, which is not implemented yet.

**Comment by natcohen** [comment]
@ronag I had the same problem with archives... I wanted to be able to delete a document locally while keeping it on the remote server (which is what you want to do with attachments). My suggestion would be to use a different document for your attachment and use this: http://stackoverflow.com/questions/23907966/couchdb-automatic-archiving

Read carefully the comments of the answer. It is a really nice solution! Thanks to 'skiqh'

**Comment by daleharvey** [comment]
Closing as a dupe - https://github.com/pouchdb/pouchdb/issues/802
