### ISSUE TITLE
Large Attachements?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#3670]
Is it possibly to work with attachments larger than system memory using pouchdb? i.e. does Pouch just stream the files to/from disk/remote or does it at some point read in entire files into memory?

**Comment by nolanlawson** [comment]
When possible and with certain APIs, it uses a Blob object, of which I don't know the internal implementation. I've actually been wondering this myself about Blobs; it would be worth testing in browsers that support native Blobs in IndexedDB (currently only Firefox and IE; Chrome has it in Canary). So you could test e.g. putAttachment/getAttachment in those browsers.

Note, though, that any API that renders the attachment as base64 will necessarily read it into memory. Currently replication uses such APIs.

**Comment by daleharvey** [comment]
Replication currently doesnt, blobs are disk backed in idb at the least so there shouldnt be much of a limit asides memory, open a bug if you run into an issue though
