### ISSUE TITLE
Loading of attachments with Android SQLite plugin is slow

### ISSUE THREAD

**Issue by kennyki** [pouchdb/pouchdb#3671]
I was carelessly using IndexedDB previously as a result of not waiting for the 'deviceready' before instantiating my database. However it worked well in storing and retrieving images.

I then made the changes to wait for 'deviceready', reinstalled the app and `db.info()` did reveals that it's using SQLite. Then it starts to take ~12-15 seconds to load one attachment on my Galaxy S2 (on Android 4.4.4). It's better in Sony Z3, taking ~2-3 seconds for one attachment but still, it's problematic.

Not sure if I have done anything wrong or missing something, here's an illustration:

1. PouchDB version 3.3.1
1. [SQLite plugin](https://github.com/brodysoft/Cordova-SQLitePlugin) version 1.0.6
1. the attachment is captured with phone camera in the size of ~1MB and stored as blob.

    ```
    blobUtil.imgSrcToBlob(picture.url).then(
      function success(blob) {
        db.put({
          _id: 'record/0',
          _attachments: {
            'picture/0': {
              content_type: blob.type,
              data: blob
            }
          }
        });
      }
    );
    ```

1. I needed URL instead of base64 when viewing, so I'm not using `{attachments: true}` when doing `allDocs()` but to load them afterwards:

    ```
    Object.keys(doc._attachments).forEach(function(attachmentId) {
      var start = (new Date()).getTime();
      db.getAttachment(doc._id, attachmentId).then(
        function success(blob) {
          var end = (new Date()).getTime();
          // end - start = ~12000-15000
          doc._attachments[attachmentId].url = blobUtil.createObjectURL(blob);
        }
      );
    });
    ```

Anyone facing similar issue? What is the correct approach to debug this further?

Thanks

**Comment by nolanlawson** [comment]
Cordova has to serialize everything to a string to communicate between JS and Java, so yeah, it's going to be slow. IDB or WebSQL would be better, or avoiding storing attachments in the database.

**Comment by kennyki** [comment]
Thanks for the clarification. I'll need to rethink about attachment storing solutions.
