### ISSUE TITLE
invalid link on API Reference page

### ISSUE THREAD

**Issue by coreylenertz** [pouchdb/pouchdb#3672]
In the section titled [Query the database](http://pouchdb.com/api.html#query_database), there is a link targeting "http://localhost:4000/guides/queries.html"

> Since views perform a full scan of all documents, this method may be slow, unless you first save your view in a design document. Read the **query guide** for a good tutorial.

This is an issue because the resource does not exist. I believe the intent was to point to an online resource.

**Comment by nolanlawson** [comment]
This is fixed in master but not published yet, thanks for reporting!
