### ISSUE TITLE
Http adapter should handle design documents containing another /

### ISSUE THREAD

**Issue by jo** [pouchdb/pouchdb#3680]
I have (accidently) created a design document with an id like `_design/foo/bar`, which completely broke the replication. Even after I deleted the document it still caused the replication to fail, understandably because the deleted revision has to be replicated, too.

The problem here is that the docid does not get properly escaped, resulting in a request to `/dbname/_design/foo/bar` instead of `/dbname/_design/foo%2Fbar`.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/49248fac87836978abf76cd08223c1376f8d67f0
