### ISSUE TITLE
Simulating startkey/endkey in changes?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#3684]
I'm building an application that uses a pattern similar to delta-pouch.

Seems to work so far. The only problem I have is that currently the `changes` stream listens to changes to all docs while I only care about changes within the `startkey` - `end key` range. This is somewhat inefficient using the http(s) adapter. 

Is there any way to emulate the `startkey` - `endkey` behaviour in the `changes` stream?

**Comment by daleharvey** [comment]
You can use a changes filter (partially documented @ http://pouchdb.com/api.html#changes) which can filter out changes that dont fall within your range on the server

**Comment by ronag** [comment]
Will a changes filter have any negative impact on performance when running locally?

**Comment by daleharvey** [comment]
If the filter runs locally it will be the same as running the full changes feed and filtering locally, if it runs on the server it will mean reduced HTTP traffic
