### ISSUE TITLE
Using reduce for calculating documents from deltas?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#3685]
Would it be feasible to calculate a documents from its deltas (i.e. delta-pouch) using a reduce view? i.e. does a reduce view run in id order?

The reason I'm looking into this is that a documents may have thousands of changes in which case calculating on demand with allDocs on the client is a bit slow...

**Comment by nolanlawson** [comment]
It would have a similar performance characteristic to just using allDocs. In PouchDB the output of a map function is cached, but the output of reduce is not.
