### ISSUE TITLE
active event only fired once, the first time live replication starts

### ISSUE THREAD

**Issue by jjd314** [pouchdb/pouchdb#3687]
When using live replication, the 'active' event is correctly fired only the very first time replication starts actively processing changes.  This is eventually followed by a 'paused' event, but then the next batch of replication does not fire the 'active' event (the 'change' events and the following 'pause' both fire).  This seems like it may have been intentional, since the emit('active') in inside a once() handler in replicate.js, but it is at odds with the documentation (and also with what one might expect, that 'active'/'pause' events come in pairs).  From inspecting the code, perhaps the emit('active') (and the if statement around it) should be moved to somewhere in startNextBatch? If so, then the state will also need to be reset to "pending" somewhere, perhaps in completeReplication.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/176321b9765982afb8599c4775e5f0272fea9416
