### ISSUE TITLE
Add AJAX support to GET requests

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb#3689]
This is a more limited version of #3491. I need AJAX (specifically headers and proxy) to work on GET requests so I can test some things out in a reproducible way for atts_since support. I'm finishing a PR for this now.

**Comment by nolanlawson** [comment]
https://github.com/pouchdb/pouchdb/commit/4481c954f0f2d003714f913f2d7ab8a8d9021ba3
