### ISSUE TITLE
EventEmitter leak when live replication with retry goes offline

### ISSUE THREAD

**Issue by dholth** [pouchdb/pouchdb#3699]
I'm replicating twice, once for each direction: local.replicate.from(remote); local.replicate.to(remote); with {live:true, retry:true}. When I go offline (see also handy desktop Chrome mobile emulation with network throttling) each retry seems to cause the replicator to add a new 'destroy' listener to the database. Soon it goes to 11 and stops working.

Happens when the backOff() method calls replicate() from setTimeout().

**Comment by dholth** [comment]
In related news, exceptions in the replication event handlers will cause the same problem. It may just be the same "needs to remove listeners" bug.

**Comment by dholth** [comment]
This bug is tricky because much of the replication state and callbacks are closures from inside the replicate() function itself. One way to fix:

- Trap all per-replicate() call callbacks with returnValue.on('newListener', // append listener to list). This should work as long as replicate() doesn't add any callbacks asynchronously.
- Remove 'newListener' listener when replicate() returns.
- Remove all collected listeners right before calling backOff() (the function that eventually calls replicate() again, which re-adds new versions of all the callbacks, and is causing the bug)
- Only allow ready(), which just makes sure the replication is canceled if either the source or target databases are destroyed, to be called once. I just assigned this.ready = // no-op function;  at the end of the ready function.

While I was testing this issue I noticed the retry timeout may not be reset correctly after replication restarts. It takes it a long time to try again after going off- and back on-line the second time.

**Comment by dholth** [comment]
It also leaks every time getChanges() is called from the replicator's onChangesComplete() handler, the changes feed wants to know when 'destroyed' happens on the source database, but the completed Changes doesn't stop listening.

**Comment by ctlacko** [comment]
:+1: It seems like Chrome does a decent job of mitigating this leak as you mentioned, but toggling live updates on/off in Firefox makes my Macbook go into testicle melt mode. I know that's not super helpful, but I can definitely reproduce this.

**Comment by dholth** [comment]
This should fix the problem, I've been using a similar fix privately to be able to use replication-with-retry. https://github.com/pouchdb/pouchdb/pull/3813

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/d8902a1825d3c60d0b0151b42569ee1bb6d283ff, thanks so much for the debugging and initial patches @dholth, we usually try to avoid taking over peoples patches however this ended up needing a fairly big fix, thanks @nolanlawson for all the work as well
