### ISSUE TITLE
progress bars

### ISSUE THREAD

**Issue by dholth** [pouchdb/pouchdb#3700]
PouchDB progress bar algorithm.

1. Fetch .info() of local and remote databases
2. Watch incoming change events. Divide last_seq from change event by update_seq of source database. This is the progress during replication.
3. When replication is paused there are no change events and last_seq from the last change event is often less than update_seq of the remote database (progress < 1). Assume paused with no error means progress == 1, or compare the doc_count of the local and remote databases.

**Comment by nickcolley** [comment]
This'd be a great plugin. :+1:

**Comment by nolanlawson** [comment]
Agreed, would love to see a plugin for this!
