### ISSUE TITLE
weird error with deleted document

### ISSUE THREAD

**Issue by chino23** [pouchdb/pouchdb#3708]
I have some weird error with a document.

After updating a few docs and then deleting all of them, one document was left in the database. I could see it in Futon. 

In Futon I can't delete it, or change it. And the weird thing is, it has no data, except for the rev and id.

````
{
  "_id": "test@yahoo.com_task_1d6a8ea5-fd14-47e3-9f90-83f594d38d4b",
  "_rev": "7-da72317174946f1b04342ece9c7d23b5",
  "value": {
    "rev": "7-da72317174946f1b04342ece9c7d23b5"
  },
  "key": "test@yahoo.com_task_1d6a8ea5-fd14-47e3-9f90-83f594d38d4b"
}
````

then when I go to edit doc in Futon, it get's even weirder:

````
{
  "_id": "test@yahoo.com_task_1d6a8ea5-fd14-47e3-9f90-83f594d38d4b",
  "_rev": "7-da72317174946f1b04342ece9c7d23b5",
  "_deleted": true
}
````

it shows the _deleted: true flag, which normally shouldn't be shown as it's an internal thing. Am I right?

Any idea how this is possible? Using adapter: websql

**Comment by nolanlawson** [comment]
Can you provide a live test to reproduce? Otherwise not sure what's going on here.

It kind of looks like you are running a map/reduce query and then putting the result of that into the database.

**Comment by chino23** [comment]
I can't reproduce it myself. I'm not sure what happened really.

Not using any map/reduce in the app. The last action was to delete all the docs. The way I do it is to get all the IDs and Revs into an array, and add the _deleted: true flag for it, and make a bulkDocs.

````
[...]
var documentsToBeDeleted = [];
                     
[...]

for(var i in res){
    documentsToBeDeleted.push({
        _id: res[i].doc._id,
        _rev: res[i].doc._rev,
        _deleted: true
});
}
[...]

db.deleteAll(documentsToBeDeleted)
    .then(function(){
        deferred.resolve();
});
````

where the deleteAll is just a call for bulkDocs which accepts the array.

Been using the exact same function for months and never had an issue. Bit puzzled here

**Comment by daleharvey** [comment]
I have tried reproducing and as far as I can tell this must have been a futon issue, cant see anything like it, please reopen if you still see any issue, cheers
