### ISSUE TITLE
Conflict 409 when updating a doc

### ISSUE THREAD

**Issue by natcohen** [pouchdb/pouchdb#3711]
I think I get the same error as this: https://github.com/pouchdb/pouchdb/issues/922 (I'm using PouchDB 3.4.0 and CouchDB 1.6.1)

Everything works as intended so it doesn't really bother me

When I update a doc, I get the following from chrome:

PUT http://127.0.0.1:5984/transport/_local/VXEYBNvxGIG34DxK8_GowQ%3D%3D 409 (Conflict)

Remote Address:127.0.0.1:5984
Request URL:http://127.0.0.1:5984/transport/_local/VXEYBNvxGIG34DxK8_GowQ%3D%3D
Request Method:PUT
Status Code:409 Conflict
Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://localhost:3000
Access-Control-Expose-Headers:Cache-Control, Content-Type, Server
Cache-Control:must-revalidate
Content-Length:58
Content-Type:application/json
Date:Wed, 08 Apr 2015 20:31:31 GMT
Server:CouchDB/1.6.1 (Erlang OTP/R16B02)
Request Headers
view source
Accept:application/json
Accept-Encoding:gzip, deflate, sdch
Accept-Language:fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
Authorization:Basic YWRtaW46MTIzNDU2Nzg=
Connection:keep-alive
Content-Length:69
Content-Type:application/json
Host:127.0.0.1:5984
Origin:http://localhost:3000
Referer:http://localhost:3000/index
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
Request Payload
view source
{_id: "_local/VXEYBNvxGIG34DxK8_GowQ==", _rev: "0-126", last_seq: 2}
_id: "_local/VXEYBNvxGIG34DxK8_GowQ=="
_rev: "0-126"
last_seq: 2

**Comment by nolanlawson** [comment]
409s are a normal part of dealing with PouchDB/CouchDB and you are expected to catch them. If you don't want to deal with them, then I recommend the plugin [pouchdb-upsert](https://github.com/pouchdb/upsert), else read up on the guide and everything is explained there. :)

**Comment by nolanlawson** [comment]
Please reopen if that doesn't answer your question

**Comment by daleharvey** [comment]
Also worth mentioning this is a conflict on a `_local` doc, that is something we write during replication so assuming you are syncing these databases, we handle the 409 in this case

**Comment by nolanlawson** [comment]
ah yeah missed that, good point. maybe we should log a reassuring message?

**Comment by natcohen** [comment]
I handle it but it seems that it comes from the replication...can't it be silent?

**Comment by nolanlawson** [comment]
Unfortunately browsers always log 40*s, so no...
