### ISSUE TITLE
View engine does not honor include_design:true

### ISSUE THREAD

**Issue by ermouth** [pouchdb/pouchdb#3712]
Design docs are skipped by Pouch view engine. So sometimes PouchDB view index results are inconsistent with CouchDB equivalents.

**Comment by nolanlawson** [comment]
Can you provide some examples? Not sure what you mean. Also this fix would go in the `pouchdb-mapreduce` project, not this one.

**Comment by ermouth** [comment]
```javascript
var db = new PouchDB("whereisddoc");
db.put({
  _id:"_design/test",
  options:{ include_design: true },
  views:{
    test:{
      map: (function(doc) {emit(doc._id, null)}).toString()
    }
  }
})
.then(function(){
    return db.query("test/test",{keys:["_design/test"]});
})
.then(function(res){console.log(res)});
```
This will print empty response for PouchDB. For CouchDB response will contain 1 row with ddoc.

**Comment by nolanlawson** [comment]
gotcha. yeah, that's a bug on pouchdb-mapreduce. we should probably fix it so people don't have to manually put an `if` statement to check for design docs. Wanna contribute the fix? :smiley:

**Comment by ermouth** [comment]
Well, thank you, but think I can’t – a) bit busy on cloudwall, b) not sure I understand clearly what impacts what inside Pouch.

To help someone who can: [pouchdb/mapreduce/blob/master/index.js#L453] (https://github.com/pouchdb/mapreduce/blob/master/index.js#L453) – this comparison drops _ddocs.

PS. Scrolling code discovered you now use hydrogen optimization safe try/catch. Wow!
