### ISSUE TITLE
In Changes, call db.removeListener('destroyed', onDestroy) before emitting 'complete'

### ISSUE THREAD

**Issue by dholth** [pouchdb/pouchdb#3713]
During replication the 'complete' event causes the PouchDB live/retry replicator to request a new Changes. This can cause db to have too many listeners. Try calling removeListener() (but not self.removeAllListeners()) before firing 'complete'.

**Comment by dholth** [comment]
Seems to help, but it would help more if replication would ensure all its changes feeds were cancelled before requesting a new one. Seems to be a bigger problem on iOS/WebSQL

**Comment by dholth** [comment]
The real fix for this bug seems to be to avoid throwing any exceptions in replication event handlers.

**Comment by daleharvey** [comment]
Also closing as dupe
