### ISSUE TITLE
live replication with retry should emit 'paused' event when already paused && error

### ISSUE THREAD

**Issue by dholth** [pouchdb/pouchdb#3714]
If replication is paused and the remote changes feed is disconnected, the live replication with retry does not appear to fire any event. Instead, it should fire some event, maybe just an extra "paused" event with the connection error. This would be used to tell the user that they are offline.

If replication stops while it is active the paused event does include the error, and appropriate feedback can be given.

**Comment by dholth** [comment]
Oh, it emits requestError. I'll just use that.

**Comment by daleharvey** [comment]
@dholth hrm the replication should fire a paused event with an error, if it doesnt its a bug, for fixing the requestlisteners it should be based on this and not requestError, which is just spuriously fired for failing requests

**Comment by dholth** [comment]
During a live replication with retry, if 'paused' and the remote changes feed is lost, the replication emits only the undocumented 'requestError' event. Instead, it should just emit ('paused', err). This matches what happens when replication is active and there is a similar connection error.

**Comment by nolanlawson** [comment]
As commented in https://github.com/pouchdb/pouchdb/issues/3716, I think we should just follow the documentation and actually emit the error in `paused`. From the docs:

> This event fires when the replication is paused, either because a live replication is waiting for changes, or replication has temporarily failed, with err, and is attempting to resume.

`requestError` is undocumented, so let's let it die a silent death.

**Comment by nolanlawson** [comment]
Er wait, this happens when it's already `paused`? Okay, so maybe we do need a separate event then. It would be odd if `paused` fired twice in a row with two different errors.

**Comment by nolanlawson** [comment]
> This matches what happens when replication is active and there is a similar connection error.

The `paused` event indicates a change from `active` to `paused`, so no, in my mind it's not the same thing. :) Emitting `paused` multiple times is confusing; let's stick with `requestError`.

**Comment by dholth** [comment]
In my mind it does make sense, paused (err), paused (even more paused,
err). requestError is a silly event.

It would make sense if 'paused' never included an error, otherwise you
need two kinds of error handling, one when active and one when not
active. What about using the regular error event, or is that reserved
for errors that make us give up? Or some new event on the off chance
that requestError is not the only retry-able error that we care about in
this general case? on('hiccup', function(err) { ... })

On Sun, Apr 12, 2015, at 12:21 PM, Nolan Lawson wrote:
>> This matches what happens when replication is active and there is a
>> similar connection error.


> The paused event indicates a change from active to paused, so no, in
> my mind it's not the same thing. :) Emitting paused multiple times is
> confusing; let's stick with requestError.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/pouchdb/pouchdb/issues/3714#issuecomment-92085110

**Comment by nolanlawson** [comment]
What if your app is using the `paused` and `active` events to show some kind of indicator of online/offline, though? It may break something that `paused` gets shown twice in a row.

I admit I'm not 100% sure either way, though. We may need a tiebreaker; @daleharvey what do you think?

**Comment by dholth** [comment]
Well, /my/ application is using Angular, so it only cares about the current state and not the events. The bug fix for your case would be to only take an action when you received the 'paused' event and were not already in the 'paused' state. At the moment the interested listener would have to keep track of that state.
