### ISSUE TITLE
Should replication object enter 'stopped' state when requestError and paused?

### ISSUE THREAD

**Issue by dholth** [pouchdb/pouchdb#3716]
In the backOff function,

```
  returnValue.emit('requestError', error);
  if (returnValue.state === 'active') {
    returnValue.emit('paused', error);
    returnValue.state = 'stopped';
    returnValue.once('active', function () {
      opts.current_back_off = opts.default_back_off;
    });
  }
```

It would be helpful if replication has a requestError while paused, it would still change to the 'stopped' state.

Since this block is gated on state === 'active', the function that resets current_back_off is not called when 'paused with requestError' then 'paused, reconnected to the changes feed'. Instead, current_back_off should be reset as soon as changes works, even if replication is 'paused' i.e. all caught up with the remote end.

**Comment by dholth** [comment]
Also, 'requestError' is not documented. Is it really necessary, or can we just always use ('paused', err)?

**Comment by nolanlawson** [comment]
It looks like `requestError` is designed to emit only during retry replication (because emitting `error` might cause other problems; it's a special name in Node event emitters). We should probably document it. Maybe you could help? :D

**Comment by nolanlawson** [comment]
Actually scratch that, according to the docs, the `err` should be emitted by `paused`.
