### ISSUE TITLE
db.remove not decreasing file size of Cordova SQLite DB

### ISSUE THREAD

**Issue by TeeKz** [pouchdb/pouchdb#3725]
Hey there - So I'm having an issue with my app continually getting larger and larger as I add and remove entries from PouchDB. 

PouchDB registers that I removed entries successfully and when I call `db.allDocs()` I see that the entry has been removed. I also have auto_compact enabled to ensure any leftover data is cleaned up. 

I've tried `db.destroy()` and re-opening, no success. I was hoping that using the `sqlitePlugin.deleteDatabase` and reopening a new PouchDB database under the same name would work.. but no success.

Any idea why `db.remove` is not actually removing all the document? 

Thanks!

**Comment by nolanlawson** [comment]
Compaction deletes the content of the deleted documents, but the revision IDs will still hang around, because we need to keep a record of changes that were made to the database. Normally this is not an issue because we're talking about storing a 36-char string for every document revision.

I'm not 100% sure if that's what you're talking about. If not, then maybe you don't actually have auto-compaction enabled. You can check by running:

```js
db.info().then(console.log.bind(console))
```

This will tell you if auto-compaction is enabled or not.

**Comment by nolanlawson** [comment]
Also another thing - depending on how you measure "size" of the database, you might be being mislead. SQLite usually doesn't actually reduce its size until it's forced to, and you can manually force it to do so by doing a "vacuum" operation.

Another possibility is that this is a bug in the SQLite Plugin. You can try using the built-in WebSQL database and see if the size grows in that case. Keep in mind that we test WebSQL/IndexedDB very thoroughly in our automated tests, but the SQLite Plugin is untested, and bugs have often been reported for it in the past.

**Comment by TeeKz** [comment]
Yes! Vacuum worked wonderfully!

The documents we are dealing with are rather large so I guess they were being hung onto. Our app was going from 14mb at install to over 200mb after a day or two of regular use. 

Thanks @nolanlawson

**Comment by nolanlawson** [comment]
Interesting, maybe we should look into doing vacuum automatically then. Never worked with it much myself.

**Comment by thomson02** [comment]
@t-kelly I am experiencing the same issue as you were. I am not familiar with the VACUUM command and how you would go above executing it via the SQLite Plugin. Would you be able to to provide a snippet of code to show how it is done?

**Comment by robwithhair** [comment]
@nolanlawson @t-kelly How would you run a vacuum command on the sqlite plugin?  I'm really struggling to find anything about how this would be done, or if it could be done through pouch?  How do you run a sql query from pouch?

**Comment by t-kelly** [comment]
Oh lord - It's been so long since I did this. From what I remember, you need to execute a raw SQL command, not anything associated with pouch?

**Comment by nolanlawson** [comment]
Yes, you need to VACUUM.
