### ISSUE TITLE
replication with couchDB: password security

### ISSUE THREAD

**Issue by chino23** [pouchdb/pouchdb#3734]
I'm setting up a remote couchdb server for lots of users, and each user will have it's own database with password protection.

Now when I want to sync the local pouchdb to the remote couchdb, I will have to set up the sync. The problem is, the connection is usually made by 

````
PouchDB.sync('mydb', 'http://user:password@127.0.0.1:5984/' + dbName);
````

I just don't want to store the password somewhere in plain text. 

The idea is, the user sets up an account, and the password will then be stored encrypted in some mysql database for app login credentials check. But then a couchdb database will be created with the username and the password chosen, but I don't want to put that plain password somewhere in the localstorage or pouchdb document so I can have the above code working.

Is there a way to connect to a remote couchdb without sending the plain password?

**Comment by ermouth** [comment]
Good strategy is to store credentials locally – but encrypted. You can ask user to enter some kind of PIN when he opens tab with an app. PIN is used to decrypt credentials – and if decryption succeds, replication starts.

**Comment by daleharvey** [comment]
In general when users login the password is checked and they get a token, often in the form of a cookie, if you do a login on the same domain as your database host the cookie will get sent automatically, the token validates the user and allows the requests to proceed.

There is https://github.com/nolanlawson/pouchdb-authentication which can help with auth against a plain CouchDB, I generally prefer to manage authentication in a proxy in front of couchdb

**Comment by daleharvey** [comment]
Few answers here

**Comment by jbotte** [comment]
dale, i would love to see an example / link to managing auth with a proxy

**Comment by mqtik** [comment]
@daleharvey what do you mean "manage authentication in a proxy in front of couchdb"?

**Comment by daleharvey** [comment]
@jbotte @mqtik Here is a simple example from a notes application I use

https://github.com/daleharvey/noted/blob/master/index.js#L64

Its using a made up passwordless email auth token thing, but that verification could be done for any of the standard auth techniques. It isnt really that disimiliar to how you would traditionally use a SQL database that your app talks to, you just authenticate requests before they hit the database

**Comment by daleharvey** [comment]
This particular app uses pouchdb on the server, but the following line that hits pouchdb-express-router could just as easily point to CouchDB
