### ISSUE TITLE
PouchDB not working in IE9

### ISSUE THREAD

**Issue by sannitesh** [pouchdb/pouchdb#3735]
My pouchDB app is not working in IE9 emulation mode. I don't see any errors in console. I have included following files in my app.

1. es5-shim.min.js
2. pouchdb-3.3.1.min.js
3. pouchdb.localstorage.min.js

And Here's that code which is not executing. It doesn't throw any error.

<pre>
<code>db.bulkDocs(glossary).then(function (result) {
            console.log("data inserted");
        }).catch(function (err) {
            console.log('Unable to insert into DB. Error: ' + err.name + ' - ' + err.message);
        });
</code>
</pre>

**Comment by nolanlawson** [comment]
PouchDB is not tested in IE9 and, to be frank, we should probably remove the mention on the site that  localstorage plugin may help it work there.

If you can provide any more info, that would be nice, but none of us are currently working on IE9 support. Sorry about that!

**Comment by nolanlawson** [comment]
Also you should be aware that the IE9 emulation mode is not the same thing as IE9. Sometimes it will silently swallow errors or throw errors when IE9 itself would not. The only way to know for sure would be to actually test in IE9 (e.g. using http://moden.ie)

**Comment by sannitesh** [comment]
Oh.. that's not good for us. Actually we are going to production next week. 

Here is the code which I was testing for IE9
https://github.com/sannitesh/PouchDB. 

Any help on this issue will be greatly appreciated! Thanks

**Comment by ermouth** [comment]
As far as I can recollect, Pouch 1.4 did work in IE9 – but it had very slow map/reduce and many issues in continuous replication. If I had only a week I would try to provide old Pouch for IE9.

**Comment by sannitesh** [comment]
Ok. I would like to try that option. But I couldn't find Pouch 1.4 version. If possible, can you please provide me that file?

Thanks

**Comment by ermouth** [comment]
http://jquerymy.com/kod/pouchdb-nightly.1.4.js
http://jquerymy.com/kod/pouchdb-nightly.1.4.ermouth.js
Latter has some bugfixes in .extend and replication – you can find source modifications searching `ermouth`.

Please, test them thoroughly before use – I did not use them in production. I‘d appreciate if you let me know was it helpful or not.

**Comment by nolanlawson** [comment]
PouchDB 1.4.0 is super old. I wouldn't recommend it.

What I would recommend is:

1. Get a real IE9 running in a virtual machine using http://modern.ie
2. Run your app
3. If you still don't see an error in a console, then step through `bulkDocs` in a debugger and see what's happening.

Most likely it's some small syntax error that we can fix. Also be sure to use the master version of  `pouchdb.localstorage.js`, which I've uploaded here: https://nolanlawson.s3.amazonaws.com/pouchdb/www/20150412/pouchdb.localstorage.js

**Comment by sannitesh** [comment]
Sure Nolan... I will try these options and let you know my findings. Thanks guys for your prompt response.

**Comment by sannitesh** [comment]
Hi Nolan,

I have installed IE9 and used localstorage version which was mentioned by you. When I tested my app, I didn't see any errors in a IE9 console. While debugging I found that it's not going inside bulkdoc() method of pouchdb or pouchdb.localstorage. I suspect promise code written in pouchdb is not working in IE9. Hope this makes sense. Any idea what's going on?

**Comment by nolanlawson** [comment]
That's weird; we're using a Promise shim (https://github.com/calvinmetcalf/lie). Unfortunately the information you've given isn't really enough to solve the problem... Can you step through the code and figure out which callback isn't firing? I'm really surprised that IE9 isn't displaying any errors. :(

**Comment by sannitesh** [comment]
Yeah.. no errors. So Promise.prototype.then() (Pouchdb.js line no.: 10184) returns a promise. Here is that promise

{
	state : [PENDING],
	queue : [],
	outcome : undefined,
	catch : function (onRejected) {    return this.then(null, onRejected);  },
	then : function (onFulfilled, onRejected) {    if (typeof onFulfilled !== 'function' && this.state === states.FULFILLED ||      typeof onRejected !== 'function' && this.state === states.REJECTED) {        return this;    }    var promise = new Promise(INTERNAL)
} 

After returning that promise, it does nothing.

**Comment by calvinmetcalf** [comment]
> While debugging I found that it's not going inside bulkdoc() method of pouchdb or pouchdb.localstorage

this says to me that likely there is an error somewhere else that isn't getting caught which is causing the promise to never be resolved, the promise is (likely) a red herring

**Comment by daleharvey** [comment]
If anyone requires having ie9 support and wants to get it up and running and working on saucelabs then that would be great, however doesnt look like there is a lot of motivation to fix this, we have support in 10 so closing this out
