### ISSUE TITLE
3.4.0 breaks node support for default fs adapter

### ISSUE THREAD

**Issue by cdaringe** [pouchdb/pouchdb#3738]
hi all:

here's the test script:

```js
// debuggins.js
PouchDB = require('pouchdb');
var pouch = new PouchDB('./');
```

running `node debuggins.js` produces no db file output.  Reverting back to 3.3.1 and earlier do not suffer this issue.  3.3.1- produce the expected file set, e.g. LOCK LOG MANIFEST etc.

node v12+, OSX mavericks

pouch is great.  :smile: keep up the great work!

**Comment by calvinmetcalf** [comment]
unable to confirm works fine with pouchdb 3.4.0 and iojs 1.6.2

**Comment by cdaringe** [comment]
i reproduced this multiple times yesterday.  reproducing today it worked.  most likely this is something fishy with my env.  closing until more reliably reproducible.
