### ISSUE TITLE
HTTP adapter does not emit events correctly

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3739]
I'm noticing this when I enable `test.events.js` for the http adapter ([currently it's disabled](https://github.com/pouchdb/pouchdb/blob/94cdebc8a978ce0dca5212decd24b9440d2146de/tests/integration/test.events.js#L3)). Many tests fail, and there are lots of race conditions (`done() called twice`, etc.).

In general I see two problems here:

1. We are trying to be far too clever with the event emitter stuff. I think it's fair to say that only @calvinmetcalf really understands [this code](https://github.com/pouchdb/pouchdb/blob/94cdebc8a978ce0dca5212decd24b9440d2146de/lib/adapter.js#L106-L149). (Or at least, I don't understand it. :confused:)
2. The `db.on('change'/'delete'/'update'/'create')` stuff (i.e. the `db` itself being a change emitter) is undocumented and should be removed, in my opinion. Let users explicitly create `changes()` objects if they want that.

Thoughts?

**Comment by daleharvey** [comment]
Closed by https://github.com/pouchdb/pouchdb/commit/800de8602796082e2b55dd4a12791478172f68db

**Comment by nolanlawson** [comment]
Crap, looks like delta-pouch was using this: https://github.com/redgeoff/delta-pouch/issues/47
