### ISSUE TITLE
Dependent DBs malfunction when using new PouchDB({name: 'foo'})

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3741]
The `new PouchDB('foo')` format works fine, but `new PouchDB({name: 'foo'})` actually causes many bugs. I have fixes tho, so no worries. :smiley:

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/e6ae618c36919ede15edd7a65938efa9f47de54d
