### ISSUE TITLE
Extending PouchDB with ES6 Classes (Babel)

### ISSUE THREAD

**Issue by akircher** [pouchdb/pouchdb#3743]
Not sure if this is an error with Pouch or Babel.  I am trying to extend PouchDB like so
```
export class Db extends PouchDB {
  constructor(...args) {
   super(...args)
  }
}
```
And I get the error below.  For some reason it looks like the constructor function is being called twice (when I put console.log statements inside, duplicate messages appear)
```
Uncaught (in promise) Error: bad collationIndex or unexpectedly reached end of input: a
 {stack: (...), message: "bad collationIndex or unexpectedly reached end of input: a"}
message: "bad collationIndex or unexpectedly reached end of input: a"
d62.n.parseIndexableString @ pouchdb3.3.1.min.js:10
(anonymous function) @ pouchdb3.3.1.min.js:11
(anonymous function) @ pouchdb3.3.1.min.js:11
pouchdb3.3.1.min.js:8 

Uncaught (in promise) 
Error: db isn't open {id: "idbNull", stack: (...), message: "db isn't open"}
id: "idbNull"message: "db isn't open"stack: (...)
(anonymous function) @ pouchdb3.3.1.min.js:8
F @ pouchdb3.3.1.min.js:77
e._info @ pouchdb3.3.1.min.js:8
(anonymous function) @ pouchdb3.3.1.min.js:7(
anonymous function) @ pouchdb3.3.1.min.js:1036
t.exports @ pouchdb3.3.1.min.js:10
(anonymous function) @ pouchdb3.3.1.min.js:10
(anonymous function) @ pouchdb3.3.1.min.js:1036.t.exports @ pouchdb3.3.1.min.js:1066
t.exports @ pouchdb3.3.1.min.js:10
(anonymous function) @ pouchdb3.3.1.min.js:11
(anonymous function) @ pouchdb3.3.1.min.js:11
```
As a workaround I am currently doing the below, which works fine for now
```
export class Db {
  constructor(...args) {
    //Hack because extends PouchDB doesn't seem to work
    var db = new PouchDB(..args)
    for (let key in db)
    {
        this[key] = db[key]
    }
    //Constructor prop is non-enumerable
    this.constructor = db.constructor
  }
}
```

Is this an issue with Pouch, Babel, or my code?

**Comment by nolanlawson** [comment]
PouchDB is not meant to be extended in that way. The constructor object itself is an EventEmitter and we're doing other fancy stuff that would break if you tried to extend it. :)

I'm not sure what you're trying to achieve by extending it, but maybe you would be interested in `PouchDB.defaults()`](http://pouchdb.com/api.html#defaults) or [pouchdb-wrappers](https://www.npmjs.com/package/pouchdb-wrappers) instead?

**Comment by nolanlawson** [comment]
Also @marten-de-vries could you please add a readme to pouchdb-wrappers? It seems very useful and I know we're depending on it for express-pouchdb, so a readme on the npm page would be helpful. :)

**Comment by calvinmetcalf** [comment]
Strictly speaking we could redo the pouchdb constructor to take advantage
of static class methods

**Comment by akircher** [comment]
+1 to @calvinmetcalf's  idea.  ES6 is the future and I believe it would be worthwhile to make Pouch compatible.  Obviously if its possible without a breaking change that would be ideal.

**Comment by nolanlawson** [comment]
Closing because the `PouchDB` constructor will probably never be usable this way. We have unfortunately invested too much into making `PouchDB` a catch-all for lots of different functionality: EventEmitter, Promise for itself, etc. Unfortunately it's just not likely to happen.
