### ISSUE TITLE
Tests: allow third-party adapters to use worker.js and bigimage.js in the tests

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3745]
Currently, when writing my own adapter plugin (socket-pouch), I had to basically copy these files into my own source tree, because otherwise the tests couldn't find them. Other than that, I could re-use the PouchDB test suite as-is.

**Comment by daleharvey** [comment]
@nolanlawson how would we do this? is it still needed?

**Comment by nolanlawson** [comment]
Nah, I don't really care that much. It's fine to do it manually.
