### ISSUE TITLE
Add edit button to website pages

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#3747]
Should be able to link up the pages to their github .MD equivalents, should get more people contributing!

**Comment by nolanlawson** [comment]
Yes absolutely :+1:

**Comment by nickcolley** [comment]
Related if someone want's to have a go before me:
(Keep in mind we don't use gh-pages so we'd have to hardcode the repo url)
https://github.com/jekyll/jekyll-help/issues/5

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/790c5e9e6008b53fcf44f9f32e9ba0032f9a89a8!
