### ISSUE TITLE
Remove double error stack

### ISSUE THREAD

**Issue by jo** [pouchdb/pouchdb#3748]
We currently forget write errors which happened in past batches: https://github.com/pouchdb/pouchdb/blob/master/lib/replicate.js#L187

**Comment by jo** [comment]
Pull: #3749

**Comment by jo** [comment]
It turns out that the assumption above is not true. The correspondent line is an artefact and can be removed.

**Comment by nolanlawson** [comment]
a3efd41732983ed66400fc14d736f08121e688a9
