### ISSUE TITLE
Minified code has problematic characters v 3.4.0

### ISSUE THREAD

**Issue by hsingh23** [pouchdb/pouchdb#3753]
The minified code has non utf8 character which makes it hard to use in a chrome extension.

I believe it is this part:
o.onsuccess=function(e){function o(){var e=a.id+"::",t=a.id+"::ï¿¿"

**Comment by calvinmetcalf** [comment]
you mean non ASCII characters?

**Comment by nolanlawson** [comment]
Duplicated by https://github.com/pouchdb/pouchdb/issues/3009.

Also I think the consensus was that we're not going to solve that problem in this repo. It really ought to be a feature in Uglify (`uglifyjs --ascii-only` or something).

**Comment by nolanlawson** [comment]
Well this is really irritating. Apparently Uglify *does* have [an option called `ascii_only`](https://github.com/mishoo/UglifyJS), but I cannot for the life of me figure out how to use it on the command line. Even a simple experimental JavaScript file like `module.exports = '\u0001';`; I can't figure out how to get it to uglify to ASCII-only. :confused:

**Comment by nolanlawson** [comment]
Ah wait, I see this issue. The character `\u0001` technically *is* ASCII. I think I went through this same thing back when I tried to fix #3009. Sad trombone sound.

**Comment by daleharvey** [comment]
Sorry I think my comment in #3009 was confusing, I would like to fix this, but either by transforming our output, fixing `ascii-only`, or doing `String.fromcharcodeat`, I would prefer to avoid having a detection that crashes pouch if the pasted code is wrong
