### ISSUE TITLE
Faster replicate from down server test

### ISSUE THREAD

**Issue by jo** [pouchdb/pouchdb#3755]
The [replicate from down server test](https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.replication.js#L3903) can be made faster if we set a small ajax timeout.

**Comment by nolanlawson** [comment]
:+1:, this is a really annoying thing during testing.

**Comment by jo** [comment]
Here is the PR: #3756

**Comment by nolanlawson** [comment]
aef8094
