### ISSUE TITLE
Node Buffers should return with content_type

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3758]
`getAttachment()` in Node.js doesn't return the Buffer's content-type, whereas in the browser it does. This leads to awkward situations in express-pouchdb and socket-pouch where we need to do both a `get()` and a `getAttachment()` in order to grab both the buffer and the content-type ([see express-pouchdb code](https://github.com/pouchdb/express-pouchdb/blob/master/lib/routes/attachments.js#L47-L62)). This is also risky, because it's possible (although unlikely) that the database could change in the interim between the two requests.

What's a good way to do this? Can we just attach a `type` to the `Buffer `object? Or should we introduce a breaking change where Node returns an object like:

```js
{
  buffer: new Buffer(...),
  type: 'image/png'
}
```

@calvinmetcalf thoughts on this?

**Comment by ermouth** [comment]
If you decide to return an object, I think you can add an option, that defines a format of returned data.

Something like `db.getAttachment("docid", "file.name", {format:"binary"})` – or `base64`, or `url`. Latter is objectURL, for browsers only.

Also I think to avoid breaking changes this method can have different name – something short, may be `db.file()`?

**Comment by nolanlawson** [comment]
There's already an open issue about that (#2858). I would be hesitant to add such a feature, though, because Blobs are the most efficient method, and if you want something else, you can always use `blob-util` to transform into base64 or binary strings or object URLs or data URLs or whatever you need.

**Comment by ermouth** [comment]
When I use Pouch in browser it‘s ok more or less. But if you have efficient converters right inside Pouch – why not use them as `.getAttachment` postprocessors to make end user life more sugary?

About node. When I use Pouch server-side, I need streams – and sometimes badly. So I have systems where Pouch co-exist with nano – because of streams. It‘s bit weird, dont‘t you think?

**Comment by nolanlawson** [comment]
> postprocessors to make end user life more sugary?

Hmm, but since this could also be done in a plugin, I think it's safer to say it doesn't belong in core. Also reduces code bloat. :smiley:

Plus `blob-util` is already pretty sugary; I mean, it's hard to beat `imgSrcToBase64String()`.

> When I use Pouch server-side, I need streams – and sometimes badly.

Agreed, `getAttachment()` definitely needs a streaming API for Node.js. Maybe when the W3C finalizes their streams spec, we can do it in the browser too.

**Comment by ermouth** [comment]
Well, in fact I have own implementation 😜 – http://cloudwall.me/os/docs/api.html#CW-thisdbatt- – it‘s a) `this`-unaware and can be shared between apps using currying; b) deallocates resources when app dies; c) augments native doc `_attachment` members with new properties lazily. 

It just returns requested `_attachment` member object with additional properties `url` or `data` or `blob`. This way is quiet practical and cozy for me.

**Comment by nolanlawson** [comment]
fixed by 2bd898d07fd23a21f000af713e0dd63983f1b4a8
