### ISSUE TITLE
Ajax error loading local files in iOS

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3763]
See https://github.com/nolanlawson/pouchdb-load/issues/11 for details. Since `pouchdb-load` now uses the ajax module from PouchDB itself, we can fix it here.

**Comment by nolanlawson** [comment]
This is still an issue.

**Comment by nolanlawson** [comment]
So the test to reproduce is to create a Cordova app with iOS 9 and then try to do something like:

```js
PouchDB.ajax('file://some_cool_file.txt', function (err) {
  console.log(err);
});
```

**Comment by daleharvey** [comment]
Being that `PouchDB.ajax` is not a supported API gonna close this out, will be fine to take a fix but we dont need to track as a pouchdb issue, especially as we remove pouchdb.ajax
