### ISSUE TITLE
Retry replication emits 'error' if started while offline

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3768]
This is a pretty bad bug; users aren't supposed to have to handle `'error'`s during "retry" replication unless something goes really horribly wrong. See [this SO question](http://stackoverflow.com/questions/29880471/pouchdb-database-replication-when-the-application-is-launched-offline) for context.

**Comment by nolanlawson** [comment]
Fix seems pretty straightforward. We need to add a test like [this one](https://github.com/pouchdb/pouchdb/blob/649e5ee9a5597597e1ad00b9c8e7605bc5f2da25/tests/integration/test.replication.js#L3053-L3115) to test that, even if the replication is started in offline mode, then the `'paused'` event is fired instead of the `'error' event. (We simulate offline by making `allDocs()` throw an error.

Then we just need to fix [replicate.js here](https://github.com/pouchdb/pouchdb/blob/649e5ee9a5597597e1ad00b9c8e7605bc5f2da25/lib/replicate.js#L54-L60) to make it do that when it's in `retry` mode. My hunch is it's just that `if` check that's broken.

**Comment by nolanlawson** [comment]
Ugh, okay, so the real bug here is that if you are offline and you use this format:

```js
new PouchDB('foo').replicate.to('http://mysite.com')
```

it will fail. whereas this will work:

```js
new PouchDB('foo').replicate.to(new PouchDB('http://mysite.com'))
```

**Comment by chrisschaub** [comment]
So, I need this fix in my app. The 5.1 pre-release seems to work. Is it fine to use the latest build instead of 5.0?

**Comment by nolanlawson** [comment]
Sure, otherwise we'll do our regular monthly release next week. :)

**Comment by nolanlawson** [comment]
fixed by https://github.com/pouchdb/pouchdb/commit/2afb03d1d1042814242d4a856b9a9f5c6a4842db
