### ISSUE TITLE
Saving record with bulkDocs on iPad skips one record

### ISSUE THREAD

**Issue by victordas** [pouchdb/pouchdb#3771]
Saving record with bulkDocs on iPad skips one record.

When tried with 1 record with bulkDocs, it shows zero record on iPad

iOS v8.3 (12F69)

PouchDB v3.3.1

Kindly, resolve soon.

**Comment by nickcolley** [comment]
Hey!

Any chance you could provide an example of the issue in code?

**Comment by victordas** [comment]
Thanks for replying. It's just simple code in angular app:
$rootScope.db.destroy().then(function(){
$rootScope.db = new PouchDB("CollNoSQL",{adapter:'websql', auto_compaction:true});
$rootScope.bulkDocs([object]).then(function(){
 $rootScope.allDocs().then(function(res){
console.log(res.total_rows) //0
})
})
}
)

**Comment by victordas** [comment]
$rootScope.clientCollection.destroy().then(function(){
                                    $rootScope.clientCollection = new PouchDB('ClientsNoSql', {adapter: 'websql'});
                                    var Promises = [];
                                    _.each(ismoResult.data, function(record, idx){
                                        console.log(record);
                                        var deferred = $q.defer();
                                        record._id = idx+"xxx";
                                        $rootScope.clientCollection.put(record).then(function(){
                                            console.log("PUT Result: "+idx, record);
                                            deferred.resolve();
                                        }).catch(function(err){
                                            console.log("PUT Error", err);
                                            deferred.reject(err);
                                        });
                                        Promises.push(deferred.promise);
                                    });

                                    $q.all().then(function(result){
                                        console.log("Result", result);
                                        $rootScope.clientCollection.allDocs({include_docs:true}).then(function(res){
                                            def.resolve({
                                                data:_.pluck(res.rows, 'doc')
                                            });
                                        });
                                    }, function(err){
                                        console.log(err);
                                    });
//                                    $rootScope.clientCollection.bulkDocs(ismoResult.data).then(function(result){
//                                        $rootScope.clientCollection.allDocs({include_docs:true}).then(function(res){
//                                            def.resolve({
//                                                data:_.pluck(res.rows, 'doc')
//                                            });
//                                        });
//                                    });
                                })

This code also fails. It doesn't store the first record

**Comment by nolanlawson** [comment]
You're using the SQLite Plugin, right? Have you tried using IndexedDB just to figure out whether it's a PouchDB problem or a SQLite Plugin problem?

Also:

```js
$rootScope.bulkDocs([object])
```

This does not look like valid javascript. `[object]`?

**Comment by victordas** [comment]
I'm afraid I tested all such scenarios.
My workaround is do a dummy transaction then run the bulkDocs()

It seems the first operation on the db is always a failure. As bulkDocs probably runs a batch put or post, hence the first record fails to save interestingly it's silent and without any errors

**Comment by nolanlawson** [comment]
Actually, I think I see the error:

```js
$rootScope.bulkDocs() // <-- this is not a PouchDB object
```

You need to do:

```js
$rootScope.db.bulkDocs()
```

**Comment by victordas** [comment]
I'm doing the right thing, that's just a typo. Sorry.

**Comment by nolanlawson** [comment]
Did you try using IndexedDB? Did you try clearing your app data completely?

```js
$q.all()
```

I think you mean `$q.all(Promises)`. Doing `$q.all()` will do nothing, I believe.

**Comment by nolanlawson** [comment]
Also try turning in [PouchDB debug logging](http://pouchdb.com/api.html#debug_mode). If you don't see a `bulkDocs` anywhere in the logs, then you are probably not actually inserting any documents:

**Comment by daleharvey** [comment]
I think its worth trying
```
$rootScope.clientCollection = new PouchDB('ClientsNoSql', {adapter: 'websql'}, function() { 
   ... start doing your things here
});
```
To see if this is a taskqueue related bug

**Comment by victordas** [comment]
daleharvey: Your solution also yield the same result.

nolanlawson: Regarding "$q.all()" I tried to let you know that I executed the put operation but still miss out on the first record. Let's stick to the following and try to resolve it.

    $rootScope.db.destroy().then(function(){
      $rootScope.db = new PouchDB("CollNoSQL",{adapter:'websql', auto_compaction:true});
      $rootScope.db.bulkDocs([object]).then(function() {
              $rootScope.allDocs().then(function(res){
             console.log(res.total_rows) //0
       })
      })
    })

**Comment by nolanlawson** [comment]
You're still not adding `.catch()` and I still don't know what `[object]` is. :)

So the more canonical Promise style is this:

```js
$rootScope.db.destroy().then(function(){
  $rootScope.db = new PouchDB("CollNoSQL",{adapter:'websql', auto_compaction:true});
  return $rootScope.db.bulkDocs([object]); // <-- what is [object] ???
}).then(function() {
  return $rootScope.db.allDocs();
}).then(function(res){
  console.log(res.total_rows);
}).catch(function (err) {
  console.log(err);
});
```

Notice that I only need a single `.catch()` to handle all promise errors, and I don't have the "pyramid of doom" where code steadily marches to the right. There's more info in [the PouchDB guide to async code](http://pouchdb.com/guides/async-code.html).

Also protip: in Github you can add syntax highlighting by putting three backticks followed by `js`. I've been adding syntax highlighting to your posts. :)

**Comment by victordas** [comment]
nolanlawson: that object could be anything. For example, [{a:1}].

My workaround is as follows:

        $rootScope.clientCollection.destroy().then(function(){
                                    $rootScope.clientCollection = new PouchDB('ClientsNoSql', {adapter: 'websql'});
                                    $rootScope.clientCollection.put({'doc':'dummy',_id:"A1"}).then(function(){
                                        $rootScope.clientCollection.get('A1', function(e,r){
                                            if(!e) {
                                                return $rootScope.clientCollection.remove(r._id, r._rev);
                                            } else {
                                                return true;
                                            }
                                        }).then(function(){

                                        });
                                    });
                                    $timeout(function(){
                                        $rootScope.clientCollection.bulkDocs(ismoResult.data).then(function(result){
                                            $rootScope.clientCollection.allDocs({include_docs:true}).then(function(res){
                                                console.log("All Done", res);
                                                def.resolve({
                                                    data:_.pluck(res.rows, 'doc')
                                                });
                                            });
                                        });
                                    },400);
                                });

That's not a good way to solve it but it works. And thanks for the tip. :)

**Comment by daleharvey** [comment]
So our test suite is passing on iDevices, this has to be a bug in either the angular pouchdb integration or some other part of the environment. @victordas if you can give narrow down any other part of what could be breaking with STR that would be great, http://paste.pouchdb.com/paste/b4xcwc/ is a code example of what you have that is failing and it works fine on the ipad as far as I have tested. But otherwise closing this out, cheers.
