### ISSUE TITLE
Highlandify PouchDB Changes stream

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#3772]
I'm trying to highlandjsify the PouchDB changes stream (https://github.com/caolan/highland/issues/292)

The problem is that highlandjs works best on pause/resumeable streams and I'm a bit unsure how to handle that.

My initial guess would be to `cancel` the changes on `pause` and save the `seq` from the complete event and use that as the `since` value when resuming.

Anyone suggestions or advice?

**Comment by ronag** [comment]
Initial attempt that kind of got stuck for now...

```
(options) => {
  let changes = this.changes(options)
  let seq = null
  
  const pushChange = (err, change) => {
    push(err, change)
    if (output.paused) {
      // Pause
      changes.cancel()
      changes = null
    }
  }
  
  const output = _((push, next) => {
    changes
      .on('change', change => pushChange(null, change))
      .on('error', err => pushChange(err))
      .on('complete', info => {
        if (changes) {
          // Not paused
          pushChange(null, _.nil)
        } else {
          // Paused
          seq = info.seq
        }
      })
  })
  
  const resume = () {
    changes = this.changes(Object.assign({}, options, {
      since: seq
    })
    
    output.resume()
  }
  
  const stop = () {

  }
  
  return Object.assign({}, output, {resume, stop})
}
```

**Comment by calvinmetcalf** [comment]
I believe you can use a standard node stream with highland in which case you can use https://github.com/calvinmetcalf/PouchStream

**Comment by ronag** [comment]
Perfect.
