### ISSUE TITLE
Missing Events Documentation

### ISSUE THREAD

**Issue by cdaringe** [pouchdb/pouchdb#3776]
Hi all!

http://pouchdb.com/ has an example right-off-the bat using a change listener.  I'm interested in using some pouch events!  However http://pouchdb.com/api.html#events is ~empty.  Are they stashed elsewhere, on a ToDo, or just inline'd with the associated docs that emit?

**Comment by nolanlawson** [comment]
The change events are in the `db.changes()` object. So you can find the events documented here: http://pouchdb.com/api.html#changes

**Comment by cdaringe** [comment]
Gracias!
