### ISSUE TITLE
Selective Sync / App stores etc

### ISSUE THREAD

**Issue by chrisschaub** [pouchdb/pouchdb#3784]
So, I have a field in each doc that denotes the doc 'type'. I want to only allow syncing for docs of a certain type. How would I do this? 

Also, I've built an iOS / Android app that uses pouchdb over sqllite with ionic, very cool stuff. My plan was to use couchdb server and create databases for each user of the app to allow them to sync their notes etc. across devices. Here's the interesting part: if I in-app purchase content on ios, download it and load it into pouchdb, if that user has an Android device, installs the app -- boom, pouch syncs with couch and the purchased content and user notes are synced. The question is, do you know of any appstore guidelines that prohibit this type of purchase -> sync across platforms? Thanks for any comments.

**Comment by nolanlawson** [comment]
Yep, you can use filtered replication to replicate certain doc types: http://pouchdb.com/api.html#filtered-replication

As for payment stuff, Apple doesn't care so long as you're using IAP and they get their 30%.

**Comment by daleharvey** [comment]
Question answered, if you have any more feel free, cheers
