### ISSUE TITLE
unable to use with a *down that uses uri style db names

### ISSUE THREAD

**Issue by calvinmetcalf** [pouchdb/pouchdb#3791]
specifically [this line](https://github.com/pouchdb/pouchdb/blob/56d4da155680ad960389b6ce2e924c91c41d32a8/lib/setup.js#L29) prevents using `postgres://localhost/sqldown?table=_pouchdb_test_db_testdb` as a db name

**Comment by nolanlawson** [comment]
I see that issue! One sec, got a fix...

**Comment by nolanlawson** [comment]
OK, with that commit ^ you should be able to run:

    SERVER=pouchdb-server \
      SERVER_ADAPTER=sqldown \
      SERVER_PREFIX=server_side_prefix \
      LEVEL_ADAPTER=sqldown \
      LEVEL_PREFIX=client_side_prefix \
      npm test

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/f91b6e8e18af1a8b0d4c08e5ace30ad623b3b0dc
