### ISSUE TITLE
Demo couchdb document

### ISSUE THREAD

**Issue by neojski** [pouchdb/pouchdb#3793]
I wanted to a demo document to my [revision tree visualizer](https://github.com/neojski/visualizeRevTree) but apparently there's [an issue with iriscouch](https://github.com/gr2m/CORS-Proxy/issues/30). Do we have any demo databases with CORS headers somewhere so that I can link them in my tool?

**Comment by daleharvey** [comment]
This is a bit old but not got any demos around right now, apologies
