### ISSUE TITLE
SQLite with crosswalk

### ISSUE THREAD

**Issue by Ti-webdev** [pouchdb/pouchdb#3794]
When I use PouchDB with { adapter: 'websql' } with [Cordova-SQLitePlugin](https://github.com/brodysoft/Cordova-SQLitePlugin.git) and [crosswalk](https://crosswalk-project.org/) 13.41.318.0
Then I see errors:

SQLitePlugin.js:171 OPEN database: _pouch_mydbname
SQLitePlugin.js:102 new transaction is waiting for open operation
SQLitePlugin.js:192 OPEN database: _pouch_mydbname failed, aborting any pending transactions
SQLitePlugin.js:79 Could not open database

CustomPouchError:
```js
{
  "status": 500,
  "name": "Error",
  "message": "unknown",
  "error": true,
  "reason": "Invalid database handle"
}
```

Maybe need use this [recomendations](https://github.com/litehelpers/Cordova-sqlite-storage#android-sqlite-implementation)? But how use it with PouchDB?
```js
var db = window.sqlitePlugin.openDatabase({
  name: "my.db",
  androidDatabaseImplementation: 2
})
```

P.S. Without crosswalk work fine

**Comment by sharky101** [comment]
@Ti-webdev I had to create a fork (https://github.com/iondrive/pouchdb) of 3.4.0 to use the `androidDatabaseImplementation` option.

**Comment by nolanlawson** [comment]
Yeah unfortunately the SQLite Plugin has some bugs these days. It used to pass our test suite, but does not anymore. See https://github.com/litehelpers/Cordova-sqlite-storage/issues/247 and https://github.com/litehelpers/Cordova-sqlite-storage/issues/255.

I would recommend to not even use the SQLite Plugin for now.

**Comment by nolanlawson** [comment]
BTW what `androidDatabaseImplementation` is basically giving you is the old implementation, before they decided to bundle SQLite itself with the plugin (which also adds MBs to your app size, by the way). The old implementation just uses the built-in Android SQLite APIs.

**Comment by sharky101** [comment]
@nolanlawson thanks for the info. Shame about the 50mb WebSQL limit in iOS webview.

**Comment by nolanlawson** [comment]
Closing because this is a bug in the SQLite Plugin. Hopefully it will get resolved soon.

**Comment by nolanlawson** [comment]
I've forked an older version of the SQLite Plugin here: https://github.com/nolanlawson/sqlite-plugin-fork
