### ISSUE TITLE
changes callback is invoked before put callback

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#3795]
Not sure if this is a bug or not. However, it is not the behaviour I expected or need.

If using a local database i perform a put while at the same time listening to the changes feed. The change callback will be called before the put callback.

```
const changes = localDB.changes({
    'since': 'now',
    'live': true,
    'include_docs': true
})
.on('change', () => console.log(2))
localDB.put(doc, () => console.log(1))
```
I expected this would print `1,2`, however instead it prints `2,1`.

**Comment by nolanlawson** [comment]
Yeah, the order of the callbacks is not specified anywhere. If you'd like to fix it, I'd accept a pull request, though. :) Your way does seem more intuitive.

**Comment by calvinmetcalf** [comment]
the reason is because the callback is guaranteed to be called async, but there is no such guarantee for the events so they can be called as soon as available.

**Comment by nolanlawson** [comment]
ooh, that's an excellent point. yeah, maybe we shouldn't try to make guarantees about the order of execution of async callbacks, since the event loop is hard to predict.

**Comment by ronag** [comment]
I still think you should guarantee that a "change" cannot happen until "put" has finished. The event loop is a problem with an implementation detail.

**Comment by calvinmetcalf** [comment]
@ronag the put is waiting for auto-compaction to finish before calling the callback right? Enforcing event order, especially will bulk docs, the http adapter, and concurrent updates will be a lot more complex then just making it clear that the event may be emitted before the callback, or it might not don't count on it either way.

**Comment by ronag** [comment]
Why is put waiting for auto-compaction while the changes doesn't?

**Comment by nolanlawson** [comment]
> Why does put wait for auto-compaction while the changes doesn't?

As of PouchDB 3.2.1, auto-compaction occurs in a single transaction with `put`/`post`/`bulkDocs`, so I don't think this is the case.

**Comment by daleharvey** [comment]
I dont think the auto compaction has much to do with it, its done before both the callback and the event. However this constraint is going to be almost impossible to guarantee for the http adapter, I also vaguelly remember we used to have the event notification afterwards and we changed it, if I change it around the tests start failing - https://github.com/pouchdb/pouchdb/blob/master/lib/adapters/idb/idb-bulk-docs.js#L132

@ronag maybe you can explain why you would like this guarantee and can come up with a solution that doesnt enforce the event order?

**Comment by ronag** [comment]
I got around this issue with a hack.
