### ISSUE TITLE
Replication: Include attachments when fetching generation one docs

### ISSUE THREAD

**Issue by jo** [pouchdb/pouchdb#3804]
As @karlwestin just found out attachments are fetched seperately, regardless if the doc is generation one.

CouchDB has [attachment support for views](https://issues.apache.org/jira/browse/COUCHDB-1923) (and therefore `_all_docs`) since 1.6.
So lets request with `attachments=true` and see if the data is returned and use it then. This should not break backwards compatibility.

**Comment by jo** [comment]
Pull is here: #3805

**Comment by nolanlawson** [comment]
fixed by 8f512b9149310ba06174ae9aeaf996ab787b2559
