### ISSUE TITLE
3.5.0 release

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#3806]

**Comment by nolanlawson** [comment]
Heh, nice one. Is it election season in Scotland? :)

Some suggested changes are in [this branch](https://github.com/pouchdb/pouchdb/tree/3806-nolan), then :+1:.

**Comment by nickcolley** [comment]
I fixed a link to http://pouchdb.com/api.html#apis-for-plugin-authors (was pointed at /api.html#apis-for-plugin-authors) in the GitHub release notes.

The content isn't on the site but presuming that's in progress, just a heads up. :dancer:

**Comment by nolanlawson** [comment]
published! http://pouchdb.com/2015/05/07/pouchdb-3.5.0-vote-for-pouchdb.html
