### ISSUE TITLE
Test 'Testing issue #48' has a minor typo(s)

### ISSUE THREAD

**Issue by AGBrown** [pouchdb/pouchdb#3810]
The typo doesn't break the test, but it does confuse the intent of the test (and makes the equivalent typescript test harder to write):

See [`'Testing issue #48'` test][test-510]:
```javascript
var docs = [
  { 'id': '0' }, { 'id': '1' }, { 'id': '2' },
  { 'id': '3' }, { 'id': '4' }, { 'id': '5' }
];
```

should have an `_` in front of `id`:

```javascript
var docs = [
  { '_id': '0' }, { '_id': '1' }, { '_id': '2' },
  { '_id': '3' }, { '_id': '4' }, { '_id': '5' }
];
```

If the test had tested the `id`s on the created documents, it (should) have failed.

(relates to AGBrown/pouchdb.d.ts#5)

[test-510]: https://github.com/pouchdb/pouchdb/blob/9890648/tests/integration/test.basics.js#L510 "test 'Testing issue #48' in test.basics.ts (line 510, 9890648)"

**Comment by nolanlawson** [comment]
fixed by d9782ad76827320940d25baa315f40d7684fb60b
