### ISSUE TITLE
Wait for PouchDB to be open in Angular

### ISSUE THREAD

**Issue by chrisschaub** [pouchdb/pouchdb#3814]
I have an Angular/Ionic app that relies on PouchDB. Works great, thanks!! I need to, when the app first starts, check if the database is ready for business. Any suggestions on the best way to do this are welcomed. It's one thing that sqllite/pouch plugins in cordova are available, but that doesn't mean the db is open.

**Comment by nolanlawson** [comment]
What do you mean, ready for business? You can always listen to the live `changes()` listener if you're waiting for changes to come in. E.g. this blog post was written with Angular in mind; it shows how you can use the changes feed to mirror PouchDB to an array (which presumably would be watched by Angular): http://pouchdb.com/2015/02/28/efficiently-managing-ui-state-in-pouchdb.html

**Comment by nolanlawson** [comment]
Also it's funny - I never thought about it before, but I suppose Ionic waits for the Cordova `deviceready` event before it loads all its directives and stuff? I'd assume so, because all that was hidden from me when I wrote an Ionic app.

**Comment by chrisschaub** [comment]
So, I can see the database starting up, opening, it can take a second or
two. So, Cordova fires the plugins, but it doesn't know about the database
being open and ready to query. I'm using this plugin
https://github.com/Narzerus/angular-permission to add a permission to a
route which returns the role "hasdata" if the user already has some data,
if not I direct them to a page where they can download it. But the default
angular route is firing based on deviceready/ionicready, but the database
is not. I'm trying to find a place to wait for the db to be fully ready
before I let the app start taking over. I guess I could do a

<script>
      // init db and wait in a loop checking mydb.info
      mydb = new....

      // now bootstrap angular
      window.ionic.Platform.ready(function() {
        angular.bootstrap(document, ['myapp']);
      });
</script>

that way i don't bootstrap the angular app until the db is ready. Right now
I'm start the db in a service and injecting it around my controllers as
needed.


On Fri, May 8, 2015 at 7:26 PM, Nolan Lawson <notifications@github.com>
wrote:

> Also it's funny - I never thought about it before, but I suppose Ionic
> waits for the Cordova deviceready event before it loads all its
> directives and stuff? I'd assume so, because all that was hidden from me
> when I wrote an Ionic app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/3814#issuecomment-100398989>.
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by nolanlawson** [comment]
Yeah, waiting for the callback from `mydb.info()` is a good approach. In general, everything with PouchDB is going to be heavily asynchronous due to how WebSQL/IndexedDB works, so you're probably going to find yourself writing code where you wait for a callback or resolved promise from PouchDB, and then only update the UI inside of that callback.

**Comment by nolanlawson** [comment]
Also, I would really take a look at that article and see if it helps you. :) Given the way Angular can "deep watch" an array, it's a pretty neat trick imo.

**Comment by daleharvey** [comment]
Sounds like this is solved
