### ISSUE TITLE
Promise tests

### ISSUE THREAD

**Issue by AGBrown** [pouchdb/pouchdb#3816]
Following an IRC comment from Nolan earlier this week ("*in general, we would like to migrate all tests to the promise format unless they are explicitly testing the callback API*") is it worth changing the style of promise tests (not necessarily retrospectively but certainly from this point forward). From what I can see all the PouchDB tests run using the mocha test runner, so there is no real effort required to do this. <sup>‡</sup>

For example:

```javascript
it('Add a doc with a promise', function (done) {
  var db = new PouchDB(dbs.name);
  db.post({test: 'somestuff'}).then(function (info) {
    done();
  }, done);
});
```

becomes:

```javascript
it('Add a doc with a promise', function () {
  var db = new PouchDB(dbs.name);
  return db.post({test: 'somestuff'});
});
```

This can be extended with [Chai as Promised](http://chaijs.com/plugins/chai-as-promised) to add support for more promise-based testing scenarios, or even just make the test code more descriptive. <sup>†</sup>

```javascript
it('Add a doc with a promise', function () {
  var db = new PouchDB(dbs.name);
  var promise = db.post({test: 'somestuff'});
  return promise.should.be.fulfilled;
});
```

The only real actions required here are to update package.json to add `chai-as-promised` in `devDependencies` and update the [contribution guide](https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md) to that effect.

<sup>‡</sup> Although from #3161 perhaps this isn't totally the case but the tests in the integration folder seem to depend on mocha/chai?
<sup>†</sup> *Note that [this SO answer](http://stackoverflow.com/a/22238204) suggests chai-as-promised needs mocha-as-promised - I am unsure if that is the case*

**Comment by nolanlawson** [comment]
Yep, the promise tests are definitely better than the callback tests. In the browser especially, if a callback test fails, it will just hang for forever with no error message (Mocha bug), whereas with promise tests it will always give useful information.

chai-as-promised and mocha-as-promised are no longer needed, since that functionality is now included in the latest versions of Mocha and Chai themselves.

**Comment by nolanlawson** [comment]
As for the `promise.should.be.fulfilled` and `promise.should.eventually.equal` stuff, I don't think any of us have ever actually used that. To me it's way clearer to write:

```js
return db.get('id').then(function (doc) {
  doc._id.should.equal('id');
});
```

etc. ...

**Comment by daleharvey** [comment]
So yup, as @nolanlawson said I think new tests we should try to stick to the fairly clean promise format, but no real need to go back and rewrite all of our tests, there is a bunch of them. I dont think we are needing much improvement to the test env as it currently has the promise testing covered
