### ISSUE TITLE
DB name starting with capital letter fails!

### ISSUE THREAD

**Issue by Davidx7** [pouchdb/pouchdb#3821]
When using Couchbase Lite and PouchDB together, when using databases that include/start with a capital letters, there will always be 400 Error. 

URL ```http://2313aba7-b452-4830-852d-d369ca6ce1bb:e07beefb-ec65-4812-9e35-574e27322352@localhost:5984/AssetBank```
Error 
```Failed to load resource: the server responded with a status of 400 (Bad request) http://localhost:5984/AssetBank/?_nonce=1431215783481```

It's the fault of Couchbase Lite because of the database naming convention
```Lowercase letters: a-z
Numbers: 0-9
Special characters: _$()+-/```

http://developer.couchbase.com/mobile/develop/training/build-first-android-app/create-manager-db/index.html

(Only added here so it can be placed in the documentation)

**Comment by nolanlawson** [comment]
Did you also open an issue on Couchbase lite? Else if it's something they don't plan on changing, it would be great if you added this to the "common errors" page. :)

**Comment by Davidx7** [comment]
The have no intention of changing this, at least for now. I talked to a member. They need it like this

**Comment by Davidx7** [comment]
Added to errors branch. It's a fair warning

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/697d48bfbc6dd907004d9325cf987cc2549856c7
