### ISSUE TITLE
Document backoff function

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3826]
As discussed in #3825, right now it's hard-coded in `replicate.js` to 2000 milliseconds. We could speed up the tests a lot and provide a nice feature for users if that was configurable.

Suggestion:
```js
replicate({
  live: true,
  retry: true,
  backoff: 1000 // <-- defaults to 2000
});
```

**Comment by nolanlawson** [comment]
Hah, I just realized we do have this option; it's just not documented.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/f76c53a7463641b625cd04f6fe7f2f07e750c735
