### ISSUE TITLE
Deprecations in PouchDB 4.0

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3834]
I think we're all itching to do a major release to get rid of some cruft, just trying to keep track of all the deprecations here:

* `uptodate`, `outofdate` events
* `PouchDB.destroy()`
* `update/create/delete` events
* `opts.onChange` (long deprecated)
* `opts.complete` (ditto)

**Update**: added `opts.onChange` and `opts.complete`

**Comment by zeroware** [comment]
What should I used in replacement for the update/create/delete events ?

**Comment by daleharvey** [comment]
The same logic used to generate the events from the change event could be done in content, some of the semantics of those events may not be possible to strictly adhere to in couchdb 2.0 though (in particular the distinction between create + update)

**Comment by calvinmetcalf** [comment]
@zeroware bear in mind that the events were fairly unreliable as couchdb tends to lump them together so even in couchdb 1.0 it's pretty hard to get a create in some instances.

**Comment by nolanlawson** [comment]
For some concrete examples, check out [this blog post](http://pouchdb.com/2015/02/28/efficiently-managing-ui-state-in-pouchdb.html) which has some code samples.

In general, they should all be easy to replace, but as @calvinmetcalf pointed out, I would avoid trying to distinguish between update/create (and you usually don't need to, notice that I don't in the blog post). There are just too edge cases that don't fit well, e.g. if two people create two documents with the exact same IDs, and thus you receive two revs that each start with `1-`, i.e. two separate "creation" events.

**Comment by ermouth** [comment]
I definitely missed something – what is the replacement for `PouchDB.destroy()`?

**Comment by daleharvey** [comment]
`new PouchDB('name').destroy()`

**Comment by nolanlawson** [comment]
Related to https://github.com/pouchdb/pouchdb/issues/3834

**Comment by daleharvey** [comment]
And released :) https://github.com/pouchdb/pouchdb/commit/f381b44ac49ee196bde628946e36f21be836f455
