### ISSUE TITLE
Reduce replicated DB setup time

### ISSUE THREAD

**Issue by eforth** [pouchdb/pouchdb#3836]
Our application syncs the user's database from cloudant to the mobile app using pouchDB. While I find the initial loading of the documents acceptable, I don't understand why after loading the documents in pouchdb it takes a few more minutes before I can actually retrieve data from the database.

What can I do to reduce time taken above?
Is it more performant to not store the views in the database?

**Comment by nolanlawson** [comment]
You can use [pouchdb-load](https://github.com/nolanlawson/pouchdb-load) for a quick initial replication. As for why it's slow to start up after the initial load, it's probably because your Cloudant database is read-only and thus we can't store checkpoints in it. Ideally you should at least enable storing `_local/` documents, which is what the checkpointer tries to do. Else it has to start from scratch each time.

**Comment by eforth** [comment]
How would I do that?

The url provided for sync has the appropriate privileges.

**Comment by daleharvey** [comment]
Your data should be available immediately once it has replicated, how much data are you replicating initially and how are you accessing it once you know that it has replicated?

**Comment by eforth** [comment]
On average, 2000+ documents are replicated between Cloudant and the mobile app during the initial login. A few images are included as well as the views. Once the replication is complete then the database is queried using views to provided the requested data.

**Comment by nolanlawson** [comment]
Ah okay, it sounds like it's `query()` that's slow, not the initial load.

`query()` takes awhile to warm up, especially if you are using temporary queries. You are strongly encouraged to read this: http://pouchdb.com/guides/queries.html

**Comment by eforth** [comment]
- The views are stored in the user databases
 - Queries are used because the document ID aren't suitable
 - Temporary queries aren't used

**Comment by nolanlawson** [comment]
Even normal queries can be slow if you have a lot of documents, or if your `map` function is very complex. Can you confirm that it's the `query()` operation that is slow?

**Comment by ermouth** [comment]
@eforth reasonable approach is to sync in chunks. Use `since` key, first replicate newest changes, then query them, then decrease `since`, replicate again and so on.

You‘ll got some overhead, but it won‘t stall.

**Comment by robertkeizer** [comment]
@eforth Unless you're not specifying the `stale` option when you're querying the view ([relevant docs](http://pouchdb.com/api.html#query_database)), the client side will be making sure the view is up to date.

If this is the case, I'd profile the system and see if view generation is what is taking so long.

Depending on how complicated your views are you might be able to optimize by modifying the [mapreduce package](https://github.com/pouchdb/mapreduce). In particular you can start to exclude documents from even running through the `map` function by modifying the `.changes` call that is made ( [link](https://github.com/pouchdb/mapreduce/blob/2df677bd527ce62db271480c1ce9a384c3f4cb00/index.js#L438) ). By passing in more information to the changes call, and modifying the changes function in the relevant adapter you can exclude documents from the view generation.

By default _all_ documents in the database will be run through the map function; This may not be what you're looking for. I had to optimize for this at about 5k documents.

A simple test of adding `stale: true` to your query should at the very least allow you to see if this is the issue.

**Comment by eforth** [comment]
Thanks guys for the help. I'm stilling tweaking and testing to optimize my code.

**Comment by daleharvey** [comment]
Yup, for now there is querying the live dataset, or trying to query partial local data with stale, otherwise this is just "speed up queries" which we already have, so closing as a dupe, cheers - https://github.com/pouchdb/pouchdb/issues/3039
