### ISSUE TITLE
Stop sync

### ISSUE THREAD

**Issue by chrisschaub** [pouchdb/pouchdb#3837]
So, I start sync but sometimes want to cancel it. Is there a way to do it with the existing db object? 

Something like ...

pDB.sync().cancel();

**Comment by nolanlawson** [comment]
There literally is a cancel method, yes. It should be in the documentation!

**Comment by nolanlawson** [comment]
If it's not, please submit a pull request. :)

**Comment by nolanlawson** [comment]
OK I was worried it wasn't documented, but it is in the API: http://pouchdb.com/api.html#replication and in the guide: http://pouchdb.com/guides/replication.html Let me know if that helps!
