### ISSUE TITLE
Proxy configuration and node 0.12

### ISSUE THREAD

**Issue by mainakae** [pouchdb/pouchdb#3838]
Hello all,

I'm working with Ubuntu 14.04 and node v0.12.2.

I've developed several applications using PouchDB to interact with CouchDB through HTTP, and have come to notice that while on node v0.10, PouchDB (or perhaps more accurately, "request") successfully used the environment variables ($HTTP_PROXY / $http_proxy...) to route request via the proxy, in the latest node version it is not longer the case. Even worse: when trying to manually force the use of a proxy, it throws an "TypeError: Request path contains unescaped characters.".

Fortunately, I've checked with the latest version of "request" and it definitely works right with node 0.12. I've manually updated pouchdb's package.json et voila: the problem is fixed. I haven't fully tested that nothing else is broken as a result of the version bump, though.

Summary: update "request" dependency on package.json to "~2.55.0" to fix proxy configuration with node version 0.12

**Comment by daleharvey** [comment]
Awesome, you have a commit up there with the fix, would you mind turning that into a PR?

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/fc48a9bff3cf04ab6a58424a0ab761b3debce341
