### ISSUE TITLE
"active" and "paused" fire too many times

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3852]
I finally have tests that actually simulate offline state: https://github.com/pouchdb/pouchdb/pull/3851. Unfortunately it reveals (as noted in https://github.com/pouchdb/pouchdb/issues/3848), that we fire the `'active'` and `'paused'` events way too many times.

Even if we never go offline, those active and paused events fire 5 times in that sample test, which indicates to me that it's just firing for every `'change'`. Definitely something we want to fix.

**Comment by nolanlawson** [comment]
I think in order to solve this problem, the entire replicator should probably be rewritten. I've gone in a couple of times and tried to get my hands dirty, but it's just too complicated. Really hard to tell what's going on in `replicate.js`.

**Comment by nolanlawson** [comment]
^ I've started writing some unit tests that I think ought to be fixed when this issue is fixed.

* If no retries occur, then there should be 1 active event and 1 paused event.
* If 1 retry occurs, then there should be 2 active events and 2 paused events.
* If 2 retry occurs, then there should be 3 active events and 3 paused events.

And so on. Right now there are like 10 active events and 10 paused events even with no retries. I don't know why.

**Comment by daleharvey** [comment]
So there have been a bunch of event changes and these tests seem to confirm the events are looking ok, if we see any more issues can open bugs for them directly, cheers - https://github.com/pouchdb/pouchdb/commit/a17be0693f325449ed7716d8dc49a7c3a0069b78
