### ISSUE TITLE
Re-trigger all documents

### ISSUE THREAD

**Issue by natcohen** [pouchdb/pouchdb#3855]
I would like to re-trigger all the documents. One solution would be to delete the instance and re-create it. Is there a way to trigger that without deleting/recreating (I can't find it in the API)?

**Comment by nolanlawson** [comment]
What do you mean by re-trigger?

**Comment by natcohen** [comment]
When I set for the first time the listener, all the documents are read. Is it possible to re-trigger this behavior (read all the documents through the listener) without releasing the listener and re-setting it?

**Comment by daleharvey** [comment]
@natcohen can you give us a code example of what you mean? I am still not sure what you mean by re trigger?

**Comment by natcohen** [comment]
In fact there is no code example I can provide...all what I do is create a listener as follow:

db.changes().on('change', function() {
  console.log('Change');
})
.on('change', function() {
  console.log('Create');
})
.on('update', function() {
  console.log('Update');
});

When I create it (the listener), all my documents already in my DB will be called. Is it possible to recreate this behavior (trigger update, change, create, delete... For all the documents in my DB) without recreating the listener? Hope it's clearer now...

**Comment by daleharvey** [comment]
So there is a good chance we shall be removing `.changes().on('create')` in the next release, however for change events yes, the only way to go through all the changes in the db again is to recreate the listener
