### ISSUE TITLE
offline only?

### ISSUE THREAD

**Issue by basiclaser** [pouchdb/pouchdb#3860]
Hi there, I'm looking to make a primarily offline note-taking application. Would PouchDB allow me to store notes locally in the browser without requiring any initial or frequent communication with a server? thanks

**Comment by nickcolley** [comment]
Yes! PouchDB will store your notes in the browser's local storage (http://pouchdb.com/adapters.html).

If you set up an application cache, http://www.html5rocks.com/en/tutorials/appcache/beginner/, you can then load the website without a network connection and everything will work as you'd expect.

**Comment by chino23** [comment]
By design, pouchdb is offline first. It only syncs to a remote server if you use the sync() function. You could easily use websql or idb as adapters and then have it ready just when the app starts.

**Comment by daleharvey** [comment]
Yup as has been said, Pouch will work offline only unless you specifically ask it to sync, closing this now but if you have any more questions feel free, cheers
