### ISSUE TITLE
Sync is calling paused but not active

### ISSUE THREAD

**Issue by resah** [pouchdb/pouchdb#3861]
Hi, 

I am trying to use an offline PouchDB and sync it to an online CouchDB if an internet connection exists.

                PouchDB.sync(_localDb, _remoteDb, {
                    live: true,
                    retry: true
                })
                .on('change', function(info) {
                    // sync running
                    $log.info('DB SYNC', info);
                    _online = true;
                })
                .on('complete', function(info) {
                    // replication was canceled!
                    $log.warn('DB SYNC CANCELED', info);
                    _online = false;
                })
                .on('active', function() {
                    // replication was resumed
                    $log.info('DB SYNC RESUMED');
                    _online = true;
                })
                .on('paused', function(error) {
                    // replication was paused, usually because of a lost connection
                    $log.warn('DB SYNC PAUSED', error);
                    // TODO: this event is fired twice, but never resumed with an
                    // `active` event. Not possible to handle the current state properly.
    //                _online = false;
                })
                .on('denied', function(error) {
                    // a document failed to replicate, e.g. due to permissions
                    $log.warn('DB SYNC DENIED', error);
                })
                .on('error', function(error) {
                    // everything else?
                    $log.error('DB SYNC ERROR', error);
                });

In online mode I want to use authentication so I have to know the current connection state. I tried to track this via events (`_online` variable), but when starting my application (while being online), the `paused` event was triggered twice. This was not revoked by `active` events (or any other event).

This means I am not able to track the current connection state of PouchDB. Is there another way to check that?

**Comment by nolanlawson** [comment]
The paused/active events currently fire too often; I'm working on fixing it. In the meantime, you can use this technique to check if the two databases are in sync: http://stackoverflow.com/a/29143448/680742

**Comment by nolanlawson** [comment]
Closing in favor of #3852, please reopen if that doesn't describe your issue.
