### ISSUE TITLE
Forcing `put()` when it conflicts

### ISSUE THREAD

**Issue by prust** [pouchdb/pouchdb#3864]
I was surprised to find that Pouch & Couch throw an error when a conflict happens and that there isn't a `force` option to force the conflicted record to save. I would like to force the `put()` so that a conflict is created and replicated to all nodes, so it can be resolved later (either in order to give the user more time to deal with the conflict or in order to allow the conflict to be resolved by someone else, such as a team leader).

I've looked at #2486 and [`upsert()`](https://github.com/pouchdb/upsert), but `upsert()` is only helpful when it's practical to programmatically merge doc revisions. In many cases, (differing text fields, for instance) it is safer and saner to present the conflicts to a human and allow the human to merge the conflict.

Even if I am constantly updating the UI with changes as they are synced, there is still the situation where someone is editing a property in a text input or textarea when a remote change for that property gets synced.

In order to force the conflict, I'm planning on using the `new_edits: false` option, but [the docs say](http://pouchdb.com/api.html#batch_create):

> Normally only the replication algorithm needs to do this.

This makes me nervous. Also, I will need to make up my own `_rev` (by incrementing the number at the beginning & appending a random uuid()), which also makes me nervous.

Is it safe to use the `new_edits: false` option like this? Am I missing a use-case or a best practice or another way to solve this problem? (one of my primary motivations for switching from our custom sync engine to Pouch was Pouch's ability to sync conflicts & resolve them anywhere... needless to say, I was a bit unpleasantly surprised to discover that "immediate" conflicts are treated differently than "eventual" conflicts)

**Comment by nolanlawson** [comment]
It's not safe to force-put a conflict with `new_edits: false` unless you are comfortable `get`ing the doc with `open_revs: 'all', revs: true` and modifying the `_revisions` object.

I can understand where you're coming from, though; sometimes it makes sense to just force-put a conflicting revision. Somebody ought to write a plugin to do this.

I am honestly coming up blank right now trying to find any documentation for PouchDB or CouchDB that describes how the `_revisions` object works. There are a lot of examples in [test.conflicts.js](https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.conflicts.js) though, if that helps.

**Comment by nolanlawson** [comment]
By way of example, here's a doc you can force-put with `new_edits: false` (from that test file):

```js
{
          _id: 'fubar',
          _deleted: true,
          _rev: '3-a3',
          _revisions: { start: 3, ids: [ 'a3', 'a2', 'a1' ] }
        }
```

It is a document whose rev is `3-a3`. Its immediate ancestor had rev `2-a2`. And that ancestor had `1-a1` as its ancestor. So if you wanted to force-push a conflict on top of that, you could generate a random hash, make the rev `4-<hash>`, and then the resulting doc would be:

```js
{
          _id: 'fubar',
          _deleted: true,
          _rev: '4-<hash>',
          _revisions: { start: 4, ids: [ '<hash', 'a3', 'a2', 'a1' ] }
        }
```

**Comment by prust** [comment]
thanks @nolanlawson, that's exactly the kind of input I was looking for, closing this issue. I particularly like the idea of writing this behavior as a plugin, so it can be re-used by others & more easily code-reviewed by others.
