### ISSUE TITLE
Replication workflow question

### ISSUE THREAD

**Issue by jofomah** [pouchdb/pouchdb#3880]
i want to know what happens when the following happens:

1. Document versions on Local and Remote DB have same revision number. e.g '2-xxxxxx'
2. Local version was updated while offline, revision number changed to '3-xxxxx'.
3. Remote version was also updated while local version was offline, revision number changed to '3-xxxx'.
4. if we resume replication, what happens, will there be a conflict, or will this be skipped assuming nothing changed because both have same version number, or will local or remote copy win?

Sorry if this a noob question but i have always wondered what will happen in this scenario.

**Comment by daleharvey** [comment]
Hey, no bother, certainly not a noob question. If they get the exact same version then the replication will skip fetching that version, there wont be a conflict and the local copy will be the winner on both nodes. In general we want to make sure that the versions are different (couch hashes content, pouch is random) to ensure the changed data is replicated.

**Comment by jofomah** [comment]
>  In general we want to make sure that the versions are different (couch hashes content, pouch is random) to ensure the changed data is replicated.

does that mean that currently there is no check to validate that both copies are same, before skipping and if local copy wins, does that means that local copy will be replicated to remote?

Thanks

**Comment by nolanlawson** [comment]
@jofomah Not quite, check out this comment: https://github.com/pouchdb/pouchdb/issues/2451#issuecomment-77386826

**Comment by jofomah** [comment]
@nolanlawson  thanks, i think that answers my question.
