### ISSUE TITLE
Filter keys from _attachments object

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3881]
As @daleharvey pointed out in https://github.com/daleharvey/pouchdb-express-router/pull/8, we should probably have some logic in PouchDB itself to filter out any keys that don't belong in `_attachments`, i.e. something other than digest, type, data, revpos, stub, etc.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/5bad545888057436e46c66f7a71442db0340ea76
