### ISSUE TITLE
Require javascript code from database

### ISSUE THREAD

**Issue by Ti-webdev** [pouchdb/pouchdb#3882]
Load JavaScript code from database as CommonJS module

My implementation [here](https://github.com/Ti-webdev/pouchdb-require). Please try it and give me feedback

**Comment by nickcolley** [comment]
What kind of use case is this? (I'm being dumb :P)

**Comment by marten-de-vries** [comment]
@nickcolley I could've used this implementing pouchdb-show/pouchdb-list/pouchdb-update. In fact, I have a similar (but not as complete/versatile) implementation I currently use: [couchdb-eval](https://www.npmjs.com/package/couchdb-eval).

**Comment by daleharvey** [comment]
Very nice, if you want to add to to the list of plugins that would definitely be a nice addition - http://pouchdb.com/external.html
