### ISSUE TITLE
Question: Using bluebird with pouchdb

### ISSUE THREAD

**Issue by jfspencer** [pouchdb/pouchdb#3887]
in the async guide on the pouch website it states 
- "You are free to integrate any Promise library you like with PouchDB, as long as it is compliant with the Promises A+ spec. Some libraries that fit the bill:"

This question may be naive, but, does this mean that including a different promise library will replace lie in non-ES6 compliant browsers or that it will hand off to the other libraries because they follow A+?

I am looking at using bluebird to squeeze out as much performance as possible.

Thanks.

**Comment by jfspencer** [comment]
If changing the package.son browser "bluebird": "lie" to "bluebird" : "bluebird" uses the bluebird library internally then there really isn't any performance difference, so I guess this is a moot point.

**Comment by daleharvey** [comment]
@jfspencer are you talking about the browser or node? in node we use bluebird, in the browser we use lie, we use both as polyfills so if global.Promise already exists then we will use whatever already exists

**Comment by jfspencer** [comment]
@daleharvey talking about the browser. Thanks for clarifying how other promise libraries integrate. much more simple than I thought. Thanks.
