### ISSUE TITLE
Long filename breaks build in Telerik Appbuilder

### ISSUE THREAD

**Issue by chrisschaub** [pouchdb/pouchdb#3892]
Just a nit really, but user's of Telerik's appbuilder will have issues with this filename in the source:

www/lib/pouchdb/docs/_posts/2014-10-26-10-things-i-learned-from-reading-and-writing-the-pouchdb-source.md

The name is so long that it breaks the build. Telerik like other "build services" uploads and uncompresses the files before build. Long filenames seem to give it problems. Not a bug obviously, just noting it in case somebody else tries to use the plugin built from source. Just remove the file and the build will not fail.

**Comment by nickcolley** [comment]
Looks like it'd be a good idea to nuke the entire /doc folder for your build.

We could put this into (https://github.com/pouchdb/pouchdb/blob/master/docs/_posts/2014-10-26-10-things-i-learned-from-reading-and-writing-the-pouchdb-source.md) http://pouchdb.com/errors.html if you want to contribute?

If you do, let us know if you need any help.

**Comment by daleharvey** [comment]
Yeh I think its worth having the issue for for googleability, but I dont think its a wide enough problem we need to add to the docs, telerik really need to be fixing that, cheers
