### ISSUE TITLE
PouchDB and electron

### ISSUE THREAD

**Issue by ricardonns** [pouchdb/pouchdb#3893]
Hello.

Been having an issue trying to use PouchDB and electron.
Always getting the error: "Error: leveldown not available".
That is strange because everything installed with npm just fine and the code is basically this:

```javascript
        var db = new PouchDB('database');
	var remote = new PouchDB('server/url');
	var rep = PouchDB.replicate(remote, db, {
	  live: true,
	  retry: true
	}).on('change', function(info){
		console.log('change:', info);
	}).on('paused', function () {
		console.log('I am Paused');
	  // replication paused (e.g. user went offline)
	}).on('active', function () {
		console.log('I am Active!!');
	}).on('denied', function (info) {
		console.log('Denied!!', info);
	  // a document failed to replicate, e.g. due to permissions
	}).on('complete', function (info) {
		console.log('Completed');
	  // handle complete
	}).on('error', function (err) {
		console.log('Error:', err);
	  // handle error
	});
```

thanks in advance

**Comment by nolanlawson** [comment]
I wrote a guide awhile back, when electron was still called atom-shell: https://github.com/nolanlawson/pouchdb-atom-shell

Basically I don't know anyone who's figured out how to get the LevelDB adapter to work with electronic yet. :) But thankfully there's still IndexedDB and WebSQL.

**Comment by ricardonns** [comment]
We made it by compiling the leveldown with the electron headers, but now we were having other issues where PouchDB wouldn't sync with couchbase sync-gateway when the database is big. Small buckets worked withouth any issue, but 700K docs wouldn't work. Altough we "forked" the master of PouchDB and made it work. The issue is connected to how the couchbase sync gateway uses the keys.

My colleague will open an issue with this and the changes we made to make it work. 

Right now everything is looking good with Electron/PouchDB/Couchbase, let's see how it goes from this point onward (the credentials used to sync are still to be tested).

**Comment by nolanlawson** [comment]
Cool, closing this issue then.

**Comment by nylki** [comment]
The problem seems to persist, any news on this @ricardonns @luiscamacho ?

**Comment by nolanlawson** [comment]
PouchDB via LevelDB works in Electron now AFAIK: https://github.com/nolanlawson/pouchdb-electron/issues/1#issuecomment-132310987

**Comment by nylki** [comment]
@nolanlawson 
I got levelDB now! Took some time to figure out how to rebuild which packages.
Using a modified version (changed version numbers) of this script now: https://github.com/Level/electron-demo/blob/master/package.json#L9

**Comment by cdaringe** [comment]
Confirmed.  I use it in the main and render process

**Comment by nolanlawson** [comment]
Yeah I recently wrote a better guide. Works great in my experience: https://github.com/nolanlawson/pouchdb-electron
