### ISSUE TITLE
Intermittent test failure: syncing two endpoints

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3894]
I'm seeing this one fail constantly in Travis:

```
 1) test.sync.js-local-http Test syncing two endpoints (issue 838):

     Uncaught missing
```

Really annoying to have to keep restarting Travis all the time.

**Comment by daleharvey** [comment]
Havent seen this in a while and tracking intermittents in https://github.com/pouchdb/pouchdb/issues/3934
