### ISSUE TITLE
3.6.0 release

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3906]
Not containing any open PRs; just bugfixes. I would like to release Monday or Tuesday if that suits everyone.

**Comment by nolanlawson** [comment]
I'm going to consider 6eddeb39a83a63b899f1e5a75d3249b8507b5076 a bugfix rather than a feature, because I'm pretty sure we meant to support this.

**Comment by nolanlawson** [comment]
Ack, who am I kidding; it is 3.6.0.

**Comment by nolanlawson** [comment]
The only PR I would like to sneak into this release is https://github.com/pouchdb/pouchdb/pull/3909. It bugs me to be inconsistent. We can't claim "performance improvements" using two completely different strategies.

**Comment by nolanlawson** [comment]
We just need to remove the mention of the inclined attachments and then this is good to go.

**Comment by daleharvey** [comment]
This got done
