### ISSUE TITLE
Using allDocs with keys on couchbase sync gateway retrieves full database

### ISSUE THREAD

**Issue by LuisCamacho** [pouchdb/pouchdb#3911]
Currently sync gateway don't accept the "keys" query parameter when getting all docs,

http://developer.couchbase.com/mobile/develop/references/sync-gateway/rest-api/database/get-all-docs/index.html

This causes the sync between pouchdb and CSG to fail on a large database (it gets ALL the docs instead of the specified on the "keys" parameter).

I solved this issue by forcing allDocs in http adapter to use the POST method, but maybe there is a clever way to do this only if we are talking to a CSG server.

https://github.com/LuisCamacho/pouchdb/commit/60f3d021b48d3a9c429f4d1a1fb1ffc1be448b98

**Comment by nolanlawson** [comment]
This seems like an issue that would be much easier to fix in CSG than in PouchDB. On our end, we need to support tricky browser bugs around max URL lengths, as well as some browsers caching POST requests. (Check out Safari; it caches POSTs.)

**Comment by LuisCamacho** [comment]
Ok, it seems that https://github.com/couchbase/sync_gateway/pull/668 solves this, so i guess you can close the issue.

**Comment by nolanlawson** [comment]
Oh cool! Can you update your version of CSG and see if that resolves the issue?
