### ISSUE TITLE
inline_attachments option for attachments in the http adapter

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3913]
Proposal (per me and @jo in https://github.com/pouchdb/pouchdb/issues/3911):

``` js
new PouchDB('http://example.com:5984/foo', {inline_attachments: true});
```

`inline_attachments` defaults to false. When false, the adapter will prefer to fetch attachments in separate requests, which can be more efficient for larger images because we avoid base64. Also, it supports Couchbase Sync Gateway properly.

When `inline_attachments` is true, then the adapter will prefer to use the `attachments=true` option and fetch the attachments as base64 strings, which can be useful for many small attachments (such as thumbnails).

**Comment by nolanlawson** [comment]
I would also be partial to calling the option `inline`, just to avoid a camelCase vs snake_case dilemma. :)

**Comment by jo** [comment]
I'm also in favour of `inline` :+1:

**Comment by ermouth** [comment]
To notice: inlining can significantly reduce replication costs when using Cloudant or Smileupps. They both charge for number of requests, not for amounts of data transfer.

**Comment by jo** [comment]
Good point

**Comment by daleharvey** [comment]
From @ermouth 
> 
> 
> Since it‘s not an issue, but a question, I‘ve discarded a template, sorry.
> 
> Upgrading from 3.3 to 5.4, I‘ve discovered, that now Pouch fetches attaches using separate requests. It‘s nice, since it reduces possibility of timeout on docs with lot of large attaches, also it reduces traffic.
> 
> Although, since Pouch does not check integrity of an attach received, any unreported error during transmission can have destructive effect.
> 
> If we, for example, have misconfigured proxy or rewrite in front of Couch, direct request to an attach may cause any answer but attach itself. This response will be stored in Pouch and then replicated back to Couch (if user changes doc in Pouch, surely).
> 
> Initial attach is totally destroyed in this case. Example isn‘t taken from thin air – I‘ve discovered it testing real configuration with rewrites. Also I know proxies, configured to add cache-control header to all images, and it may also break intended behavior.
> 
> So is there any way to fetch docs during sync in prev versions style? I mean an option or something to enforce Pouch 5.4+ make only application/json requests and fetch docs with attaches inlined?
>

**Comment by daleharvey** [comment]
Good point about the rewrites, I wonder if there is something we can do to prevent that, it isnt obvious off the top of my head.

However yeh having an option to use inline attachments is something we should probably support, it should be a fairly minor change

**Comment by ermouth** [comment]
>  if there is something we can do to prevent that

Compare length of received attach with .length in parent doc maybe?

**Comment by nolanlawson** [comment]
There is already an issue open for the `inline` option. Regardless, we
should check integrity when we DL.
