### ISSUE TITLE
Question: Detect cause of a given 'update' event

### ISSUE THREAD

**Issue by jacargentina** [pouchdb/pouchdb#3918]
I've setup a changes listener for changes on my pouchdb like this:

``` javascript
_localChanges = pouch_instance.changes({
  since: 'now',
  live: true,
  include_docs: true
})
.on('create', function(create) {
   // my custom code
})
.on('update', function(update) {
   // my custom code

   // How to detect when 'update' is coming from a local put(), or from a current replication processing

});
```

My question that from the on('update'): there is some way to differentiate between a local put() and one coming from a replication processing taking place? i mean, if there is some indication on the update event arguments, or in the pouch_instance object, etc ?

**Comment by nolanlawson** [comment]
No, there is no way to know. The best bet is to resolve the promise for your own local `put()s` and to note the `rev` you get back so you can keep track of revisions you added yourself. Else you can add some kind of metadata to the documents to note their origin.

**Comment by jacargentina** [comment]
Mmmmm...

On the first bet, which would run first?

````javascript
    // code saving the document to pouch
    pouch_instance.put(doc)
        .then(function(result) {
              // save rev somewhere to let _localChanges know this is a "local put"
              mycustomregistry.push(result.rev);           // HERE
        });
    ...
   // code handling the update event
    _localChanges = pouch_instance.changes({
       since: 'now',
       live: true,
       include_docs: true
    })
    .on('update', function(update) {
        // my custom code
        // this code will "see" mycustomregistry containing the just saved rev ?
        // or will it run before the line marked HERE ??
    });

**Comment by nolanlawson** [comment]
We cannot make any guarantees about what order those events will occur in, no.

Probably the best bet is to only listen for change events. Also FYI, the `'update'`/`'create'`/`'deleted'` events will be deprecated soon, so you should just listen to `change`.

**Comment by jacargentina** [comment]
Let me understand: even if i use the `change` event, i dont have guarantees, so my sample code is not an option? If so, which would be a valid option?

**Comment by daleharvey** [comment]
So the replication change events have a direction, you could possibly use the `.sync().on('change`, ...`

Alternatively you can keep a list of documents you are about to `.put`, any documents that hit changes and arent in that list are coming in remotely

```
var localChanges = {};
function myPut(doc) { 
  localChanges[doc.id] = true;
  return db.put(doc);
}

db.change().on('change', function(change) { 
  if (!(change.id in localChanges)) { 
    ... remote change, do your thing
  }
  delete localChanges[change.id];
});
```
This I think should work for the basic case, although can likely be broken, its a fairly commonly requested feature so we should think about how to provide it to users

**Comment by jacargentina** [comment]
I've seen that, at least on 4.0, the `create` event is not being fired; maybe because the documents on the server have `rev = "2_ xxxxx"` which pouch uses to say "it is an update", which is not the case here!

So, i need a way, by just looking at the `change` arguments to identify a new document vs. an updated document.

Any advice?

**Comment by calvinmetcalf** [comment]
@jacargentina I was never able to figure out that very question which is why we're removing them, sorry.

**Comment by nolanlawson** [comment]
@jacargentina You can fetch the revision tree of the document, then check the parent(s) to see if they're in your local database, which will tell you if the document is "new" from your perspective or not.

First, fetch all the revisions using `db.get('docid', {revs: true})`. It's kind awkward, but [there's some information here](http://stackoverflow.com/a/5000139/680742). (Ugh, somebody should write a plugin to `db.getRevisionTree()`.)

Second, check the parentage of the document one at a time, doing e.g. `db.get('docid', {rev: '1-x'})` to see if revision 1-x exists in your local DB. If it does, then the document is not new to you. If it doesn't, then the document is new to you.

**Comment by nolanlawson** [comment]
Actually wait, according to that StackOverflow, you can also add `revs_info: true` and it will tell you which ones are missing or not. I believe PouchDB supports this parameter.

**Comment by jacargentina** [comment]
I'm trying to put that on simple code. How must i handle the coming `doc._revs_info` to know if document is new or updated?

````javascript
    db.change().on('change', function(change) { 
      if (change.deleted === true) {
          console.log('the document is deleted');
      } else {
        db.get(change.id, { revs_info: true }).then(function(doc) {
           // How to handle...
           // doc._revs_info
        });
      }
    });
````
