### ISSUE TITLE
PouchDB takes 10-15 seconds to update 5,000 documents

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3921]
Prompted by [a SO question](http://stackoverflow.com/questions/30536760/pouchdb-about-3x-slower-inserting-4800-documents-over-websql/30560249).

Fastest combo seems to be WebSQL without auto-compaction (in Chrome anyway). No combo can update these docs faster than 5-10 seconds. I don't know if we've reached the theoretical limit of IndexedDB/WebSQL or the CouchDB revision tree model, but I hope not. I have not profiled yet.

[Live test](https://gist.github.com/nolanlawson/84028dcfcdc7a0e340b7).

Results for IndexedDB, no auto-compaction (Chrome 43):

```
initial bulkDocs: 13147.961ms
(index):58 allDocs: 4159.247ms
(index):65 bulkDocs (update): 16072.757ms
(index):58 allDocs: 3765.193ms
(index):65 bulkDocs (update): 14294.470ms
(index):58 allDocs: 3508.268ms
(index):65 bulkDocs (update): 18408.058ms
(index):58 allDocs: 4030.973ms
(index):65 bulkDocs (update): 15931.974ms
(index):58 allDocs: 4018.197ms
(index):65 bulkDocs (update): 17534.399ms
```

Results for WebSQL, no auto-compaction (Chrome 43):

```
initial bulkDocs: 9348.997ms
(index):58 allDocs: 119.222ms
(index):65 bulkDocs (update): 11301.562ms
(index):58 allDocs: 125.094ms
(index):65 bulkDocs (update): 13029.120ms
(index):58 allDocs: 188.741ms
(index):65 bulkDocs (update): 11270.408ms
(index):58 allDocs: 159.362ms
(index):65 bulkDocs (update): 11863.117ms
(index):58 allDocs: 161.994ms
(index):65 bulkDocs (update): 12099.767ms
```

**Comment by nolanlawson** [comment]
Profiled. `processDocs`, `updateDoc`, and `merge` seem to be the main culprits, on the JS side anyway. Chrome Dev Tools can be a little deceptive because they don't really show the time taken by IndexedDB/WebSQL.

**Comment by nolanlawson** [comment]
Also: wow, WebSQL allDocs is 40 times faster than IndexedDB allDocs.

**Comment by nolanlawson** [comment]
[updateDoc](https://github.com/pouchdb/pouchdb/blob/1f24d8ba81a532399e9774656e17de55ad13fa0f/lib/utils.js#L472-L525) is the function taking up an ungodly amount of self-time. Thankfully, I feel our unit tests are strong enough that we could take a hacksaw to this function and, as long as the tests pass, we can be sure we haven't broken anything.

**Comment by nolanlawson** [comment]
My analysis of a single `bulkDocs()` function (not `allDocs()`):

WebSQL:

![screenshot 2015-06-02 09 44 29](https://cloud.githubusercontent.com/assets/283842/7937300/4e41da3e-090d-11e5-9ca9-ecea54af532e.png)

IndexedDB:

![screenshot 2015-06-02 09 51 19](https://cloud.githubusercontent.com/assets/283842/7937302/4faecf12-090d-11e5-8dcf-612642facc36.png)

**Comment by nolanlawson** [comment]
IDB probably takes up a greater share of merge because we are forgetting to cache some value in the database (e.g. `winningRev`).

**Comment by nolanlawson** [comment]
I think it's fair to close this question. PouchDB still takes a considerable amount of time to update documents, but many of the most glaring performance problems have been fixed. I'll post some test results in the 4.0.1 blog post.

**Comment by nolanlawson** [comment]
So unfortunately the latest version of PouchDB does not improve the performance of this user's particular test by more than about 30%. Looks like we've still got some work to do.

Before (3.6.0):

```
initial bulkDocs: 6873.552ms
(index):58 allDocs: 2220.681ms
(index):65 bulkDocs (update): 7553.588ms
(index):58 allDocs: 1923.269ms
(index):65 bulkDocs (update): 8406.180ms
(index):58 allDocs: 2032.913ms
(index):65 bulkDocs (update): 7965.399ms
(index):58 allDocs: 2103.803ms
(index):65 bulkDocs (update): 8719.757ms
(index):58 allDocs: 2416.035ms
(index):65 bulkDocs (update): 9021.282ms
(index):79 Done
```

After (4.0.1-prerelease): 

```
initial bulkDocs: 6509.397ms
(index):58 allDocs: 2314.953ms
(index):65 bulkDocs (update): 7618.173ms
(index):58 allDocs: 2063.534ms
(index):65 bulkDocs (update): 7701.170ms
(index):58 allDocs: 2309.651ms
(index):65 bulkDocs (update): 7304.413ms
(index):58 allDocs: 2123.400ms
(index):65 bulkDocs (update): 7367.132ms
(index):58 allDocs: 2172.937ms
(index):65 bulkDocs (update): 6918.599ms
(index):79 Done
```

**Comment by jareware** [comment]
Still, significant improvement. :+1:
