### ISSUE TITLE
Can't set default prefix for the http adapter

### ISSUE THREAD

**Issue by slaskis** [pouchdb/pouchdb#3923]
I've tried setting up a few pouch "defaults" in my node app according to [this method](http://pouchdb.com/api.html#defaults) described in the docs:

```
exports.remote = PouchDB.defaults({
  adapter: 'http',
  prefix: exports.prefix
});

exports.admin = PouchDB.defaults({
  adapter: 'http',
  prefix: exports.prefix,
  auth: exports.adminAuth
});
```

But it seems like it ignores the prefix entirely. First it didn't automatically use the http adapter (which is why I added it). Then it still just tries to connect to "\_pouch_{name}".

Looking at `lib/setup.js` it seems like the prefix is a global variable set on the PouchDB constructor, and not an option which can be overridden, or am I reading it wrong?

Besides this, thanks for a wonderful library!

**Comment by nolanlawson** [comment]
I believe `prefix` was never designed to be used with the http adapter. How are you trying to use it?

**Comment by slaskis** [comment]
Oh, well I understood this part of the docs like it was pretty much meant for the http adapter:

> Note the special constructor option prefix, which appends a prefix to the database name and can be helpful for URL-based or file-based LevelDOWN path names.

I'm using it like above. I'm trying to DRY up my PouchDB instance options a bit with defaults. So then I can just do this in the rest of my code:

```
var PouchDB = require('./db').admin;

var db = new PouchDB();
// do things that require admin auth here...
```

**Comment by nolanlawson** [comment]
So if you have the prefix `'foo_'` and you create `new MyCustomPouchDB('http://mysite.com:5984/mydb')`, do you expect it to be transformed into `new PouchDB('http://mysite.com:5984/foo_mydb')`? Just checking to make sure I understand.

**Comment by slaskis** [comment]
Sorry for being a bit vague, trying again :)

I have set the default prefix using something like:

```
var AdminPouch = PouchDB.defaults({
  prefix: "http://couchhost.com/", 
  auth: {...}
});
```

and then create using 

```
var db1 = new AdminPouch('mydb1');
var db2 = new AdminPouch('mydb2');
``` 

which I then expect it to be transformed to

```
var db1 = new PouchDB('http://couchhost.com/mydb1', {auth: {...}});
var db2 = new PouchDB('http://couchhost.com/mydb2', {auth: {...}});
```

In my case it's because I use multiple dbs on the same host and this seemed like a clean way to only define that host once (as well as other things like auth).

**Comment by nolanlawson** [comment]
Yikes yeah, I think you would have to change the code in several places to allow for that. As I said before, we didn't really design `prefix` to be used for http pouches. Sorry for not being clear about that...

I think the best course here would be to just update the documentation to specify that that's not the intended use for `prefix`. Then you can simply do something like:

```js
var MY_HOST = 'http://couchhost.com/';
var db1 = new PouchDB(MY_HOST + 'mydb1', {auth: {...}});
```

**Comment by marten-de-vries** [comment]
@slaskis I wrote [http-pouchdb](https://www.npmjs.com/package/http-pouchdb) for this. It does the internal hacking @nolanlawson describes. That's technically unsupported, but we use it ourselves within pouchdb-server so if it breaks the chances it'll be fixed are quite good.

**Comment by slaskis** [comment]
@marten-de-vries hey, thanks for that tip. 

I've tried to move away from my hack to your slightly more official version but I can't get it to work (tried with PouchDB 3.6.0 and 3.5.0).

For some reason it tries to connect to `https://hostname.com/_pouch_abc/` where _abc_ is the db. It also responds with this:

```
{ status: 400,
  name: 'illegal_database_name',
  message: 'Database encountered an unknown error',
  error: true,
  reason: 'Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter.' }
```

And I just use it like in the example, like this:

```
// db.js
exports.remote = buildHTTPPouchDB(PouchDB, process.env.DATABASE_PREFIX);

// app.js
var PouchDB = require('./db').remote;

var db = new PouchDB('abc');
...
```

Is there a particular version of PouchDB you've used it with?

It seems to be almost the same issue I had above where it still adds the internal prefix even though it's using the http adapter. Except now it also has the URL in the name.

**Comment by marten-de-vries** [comment]
A workaround for that would be doing ``PouchDB.prefix = '';`` I think. Not sure why you're encountering this. Might be because of changes in newer pouch versions, might be because of your specific environment.

**Comment by slaskis** [comment]
Hmm, yeah that could work. It's too bad it's a global though as it wouldn't allow me to use both remote and local databases. Which I don't anymore so it should be fine for now.

**Comment by gr2m** [comment]
We have a similar use case at Hoodie where we want to abstract away if a CouchDB is used for data persistance or a leveldown adapter using PouchDB.

Something like that would make sense

```
MyPouch = PouchDB.defaults({prefix: 'https://couch.myapp.com'})
```

If `prefix` is a valid URL, then all databases initialised with `MyPouch` should use the `http` adapter, and the passed name should be prefixed with the passed url

Right now we use a small wrapper function

```js
function getDatabase (name) {
  if (config.db.url) {
    return new PouchDB(url.resolve(baseUrl, encodeURIComponent(name)))
  }
  return new PouchDB(name)
}
```

Would it worth adding this to PouchDB core? 

Maybe another approach would be remove the http adapter entirely from core, and if you want it, you can add it with something like 

```js
MyPouch = PouchDB.defaults({
  db: require('couchdown'),
  prefix: 'https://couch.myapp.com'
})
```

**Comment by gr2m** [comment]
from chat:

```
nolanlawson [10:34 PM] 
probably the only decent solution to this particular problem is to add an entirely new options, e.g.

[10:35] 
`PouchDB.defaults({http_prefix: 'https://couch.myapp.com'})`

[10:35] 
but just thinking about all the places you would have to change the code to make this work makes my head hurt :
```

**Comment by nolanlawson** [comment]
This is not a feature we currently support for the `http` adapter, and it would be very tricky to do. My recommendation is to wrap the `PouchDB` object if you want to do this.

**Comment by daleharvey** [comment]
I am gonna work on this

**Comment by daleharvey** [comment]
Added in https://github.com/pouchdb/pouchdb/commit/2b30ee1ab46f8268730976e3cb790df4e9659123

**Comment by gr2m** [comment]
That is awesome, thanks @daleharvey
