### ISSUE TITLE
Tests failing on Webkit nightly: null is not an object

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3929]
I just realized I can test Webkit nightly on a Mac. Dunno why I never tried it before.

Anyway, the tests are failing with:

```
null is not an object (evaluating 'obj.__flags')
```

I suspect this may be a Chai issue, because the bug is within `chai.js`. Seeing this in Webkit r185238.

**Comment by daleharvey** [comment]
It must have been a bad build, tested the latest webkit nightly and 100% (r187149)
