### ISSUE TITLE
[Question] Rollback from 3.3+ to 3.2.1

### ISSUE THREAD

**Issue by ermouth** [pouchdb/pouchdb#3931]
I experience __enormous__ amount of bugs with attachments and replication in versions of Pouch 3.3+. 

So can I roll back from 3.6.0 to 3.2.1 (that seem to be stable) without breaking DB structure?

Is DB structure of 3.2.1 compatible with 3.6.0?

**Comment by nolanlawson** [comment]
Yes, you ought to be able to: 3.2.1 was the last release with an IndexedDB migration: https://github.com/pouchdb/pouchdb/releases/tag/3.2.1

I would be interested to know more about these "enormous amount of bugs," so we can fix them. :)

**Comment by ermouth** [comment]
It seems that FF with 3.6.0 does not replicate design docs from Pouch to Couch.

**Comment by ermouth** [comment]
Also in FF I see messages on page reload, that IDB has unfinished transactions.

**Comment by marten-de-vries** [comment]
@ermouth For the first: are you certain you have the rights to write a design doc into CouchDB? Unless your CouchDB is in admin party mode, by default you don't. The second is normal browser behaviour, Firefox is just explicit about it. You can safely ignore it (except if you're tracking down a bug, maybe).

**Comment by ermouth** [comment]
@marten-de-vries You r right, session in Futon expired, so I just was not authorized. 

So disregard, my brains seem began to boil (
