### ISSUE TITLE
Cordova Database size limits & Sync duration with synced tombstones docs.

### ISSUE THREAD

**Issue by ronyrun** [pouchdb/pouchdb#3937]
Hello, 

I'm having an issue with the local database size limitation on HTML5 (Cordova) & Sync duration with tombstoned

1) On reconnect : The duration of the Synchonization is very long with the _delete:true tombstoned documents.
2) Because of the tombstones docs, the local database is getting to big for the 5Mb possible in WebSql.

Do you have any recommandation ?
Thank you for your amazing job.

**Comment by nolanlawson** [comment]
Did you try auto-compaction?

As for the database getting too big on iOS, the only real solution is the [SQLite Plugin](https://github.com/litehelpers/Cordova-sqlite-storage).

**Comment by ronyrun** [comment]
auto-compaction OK Thank you.
