### ISSUE TITLE
Feature request: expose collate in PouchDB.utils

### ISSUE THREAD

**Issue by ssured** [pouchdb/pouchdb#3938]
AFAIK pouchdb is used in the replication algorithms in PouchDB, and thus always loaded with PouchDB. Right now I import pouchdb and pouchdb-collate in my project. Just importing pouchdb and referencing `PouchDB.utils.Collate` would save me some bytes in my final product.

**Comment by marten-de-vries** [comment]
``PouchDB.utils`` isn't the right place for this (it shouldn't be used externally, even though some projects do), but it seems like a worthwhile addition to [the extras API](http://pouchdb.com/api.html#extras).

**Comment by nolanlawson** [comment]
@marten-de-vries This wouldn't make much sense in the extras API. If you require both pouchdb and pouchdb-collate and then browserify it, that will reduce the number of bytes. `extras` basically works the same way.

```js
// myfile.js
var PouchDB = require('pouchdb');
var collate = require('pouchdb-collate');
```

then

```bash
browserify myfile.js > output.js
```

Also technically PouchDB.utils is not user-facing and may someday be removed.

**Comment by marten-de-vries** [comment]
Oh, right. I reasoned there were different versions of pouchdb-collate & pouchdb involved so browserify couldn't dedupe them or something like that. Totally overlooked the obvious solution.

**Comment by ssured** [comment]
Thanks for the advice, I guess I'll have to learn myself a bit more browserify and create an own build!
