### ISSUE TITLE
Can I use pouchDB icon?

### ISSUE THREAD

**Issue by danielo515** [pouchdb/pouchdb#3939]
Hello,

I'm using Pouchdb in a project. Can I include the PouchDB icon on my main website? For example, as it is on the pouch website with other technologies at the very bottom (Couchdb and other icons). Of course proper attribution will be also added.

Thanks.

**Comment by daleharvey** [comment]
Hey Daniel

Sure the icon is available @
https://github.com/pouchdb/pouchdb/blob/master/docs/static/img/logo.svg

Cheers
Dale

**Comment by danielo515** [comment]
Thank you very much!

**Comment by nickcolley** [comment]
@danielo515 here's a link without the text: https://github.com/pouchdb/pouchdb/blob/master/docs/static/img/mark.svg

**Comment by danielo515** [comment]
that is exactly what I was looking for! But for now, since I don't have much icons to add to my footer I think I will stick to the one that has the text, because it is more informative. But, thank you very much.
