### ISSUE TITLE
Trouble Trapping for sync errors

### ISSUE THREAD

**Issue by TheDucc** [pouchdb/pouchdb#3947]
I have app the store data locally with pouchDB and syncs to a cloud couchDB.  I am trying to create a function that will reset user data if my couchDB gets obliterated.  I have to tools to reset the user data. Basically after I detect the the couchDB crash I 
  1: Stop the sync
  2: Force the user to re-login to the app.  
This give me the ability to create a new couchDB that will newly re-sync all the local pouch data to the active couchDB. 

I CANNOT figure out a way to actively trap this scenario.

    pDB.sync(remoteDBall, {
          live: true,
          retry: true,
    }).on('change', function (info) {
    }).on('active', function () {
    }).on('paused', function (error) {
      console.log('new pDB sync paused');
      //sometime pause throws an error, sometimes not.
      if(error) {
        console.log('with error');console.log(error);
      }          
    }).on('requestError', function (error) {
      if((error.status == 404 || error.status == '404') && error.message == 'missing' && utilityService.isOnline()) {
        console.log('JACKPOT!!!');
        $state.go('app.noSync', {}, {reload:true});
      }
    }).on('denied', function (info) {
      // This never hits
    }).on('error', function (err) {
      // This never hits       
    });

This works OK, if I delete the couchDB WHILE the sync is running.  I get an error in the requestError that gives me the 404 status with a missing message.

But if I turn off the device, and turn it back on.  The sync still fails but now with a message of "Database encountered an unknown error"; and a status of 500.

Which would not be that big of deal, except I get the same error message even when the sync works great.  I get it when a message 'sees' itself in both places without needing an update.  It also accompanies the error that says:
  "The above 404 is totally normal.  PouchDB is just detecting if the remote DS exists"

I will ignore for the moment that I get this message even when I know that the DB does not exist.

Can anyone offer some guidance on what I am doing wrong? I have been know to go down rabbit holes in the past.

dmd

**Comment by daleharvey** [comment]
Looking again, so this has actually change behaviour and now once you delete a database replication 'should' actually just carry on, possibly from scratch, that sounds similiar to what you want so maybe retest, either away if you want the client to know a database is to be deleted, you will need to notify it either via a new document or out of band, there is no way to detect it given the current api, apologies for taking so long to reply
