### ISSUE TITLE
Dirs & Builds

### ISSUE THREAD

**Issue by chrisschaub** [pouchdb/pouchdb#3952]
I'm using pouchdb, pouchdb-find,quck search. I'm assuming that I only really need the contents of the /dist directory, it's ok to ignore bin and lib dirs. There are some ios build issues related to .sh and .py files being included in builds, you get code signing errors. I'm assuming the min.js files only really need stuff in the dist dirs?

**Comment by nolanlawson** [comment]
If you are exclusively using them in the browser, then yes &ndash; you only need the `dist/` contents. `dist/` basically means "browser builds," at least in our style.

**Comment by chrisschaub** [comment]
thanks

On Thu, Jun 11, 2015 at 12:18 AM, Nolan Lawson <notifications@github.com>
wrote:

> If you are exclusively using them in the browser, then yes – you only need
> the dist/ contents. dist/ basically means "browser builds," at least in
> our style.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/3952#issuecomment-111000989>.
>



-- 
Christopher Schaub
http://chris.schaub.com
