### ISSUE TITLE
Race condition in clone

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3955]
From a Twitter comment: https://twitter.com/ermouth/status/608849583729467393

**Comment by willholley** [comment]
It looks like there are a few places where this could happen but I think the simplest solution would be to have argsarray deep clone objects before passing them on.

**Comment by daleharvey** [comment]
Added a test for this https://github.com/pouchdb/pouchdb/commit/ee770fefb7409b2955dc514121c2279f39d33632

**Comment by daleharvey** [comment]
Closed by https://github.com/pouchdb/pouchdb/commit/44b3429b4fe10d1f9a76d758e96ce3f51dde835e
