### ISSUE TITLE
Error 500: "unknown", a statement with no error handler failed

### ISSUE THREAD

**Issue by ArnaudValensi** [pouchdb/pouchdb#3956]
Hi,
I have this error:
```
{"status":500,"name":"Error","message":"unknown"} 

error: true
message: "unknown"
name: "Error"
reason: "a statement with no error handler failed: [5] DB[31] prepare() SELECT sql FROM sqlite_master WHERE tbl_name = 'metadata-store' [database is locked]"
status: 500
```
It happens rarely and randomly, but when it is happening I have to remove the db.

**Comment by nolanlawson** [comment]
What is the environment? Are you using the SQLite Plugin? What kind of device/browser/OS?

**Comment by ArnaudValensi** [comment]
Yes I'm sorry.
I have this error on a Samsung GS4, android 4.2.2. 
I'm using cordova SQLite plugin.
Pouchdb 3.5.0
and the default slqite implementation.

**Comment by nolanlawson** [comment]
Yep, I would not recommend using the SQLite Plugin on Android. It is slower and less reliable. On iOS it gives you the advantage of unlimited storage, though.

**Comment by ArnaudValensi** [comment]
Yes, but what I need is the unlimited storage. Do you think, I shouldn't use pouchdb/sqlite on a production app ?

**Comment by nolanlawson** [comment]
Android has unlimited storage on Android without the SQLite Plugin: http://pouchdb.com/faq.html#data_limits

**Comment by ArnaudValensi** [comment]
That's a good new, thank you !
