### ISSUE TITLE
Pre-populate or Pre-Filled SQLite DB in Ionic with PouchDB

### ISSUE THREAD

**Issue by jdnichollsc** [pouchdb/pouchdb#3960]
Hi guys! Is there an example of how to populate a database with PouchDB?

Thanks in advance.
Regards, Nicholls

**Comment by nickcolley** [comment]
Hey @jdnichollsc !

You could try using the pouchdb-load plugin: https://github.com/nolanlawson/pouchdb-load 

This allows you to load a dump of your database.

Hope this helps :dancer: 

Nick

**Comment by nolanlawson** [comment]
There's also the `createFromLocation` attribute, although it's only for the SQLite Plugin: http://pouchdb.com/api.html#create_database

**Comment by daleharvey** [comment]
Answered :)

**Comment by jdnichollsc** [comment]
I created a database in DB Browser for SQLite with a table with 4 records... but in my following example not appear (Android Phone) https://gist.github.com/jdnichollsc/f82592d6f303aaebfb9f

**Comment by ronyrun** [comment]
hi @jdnichollsc did you make it work ?

**Comment by jdnichollsc** [comment]
I could not :/
