### ISSUE TITLE
Tests failing against CouchDB 1.5.0

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3967]
Dunno if it's related to #3961, but I just decided to test CouchDB 1.5.0 for the first time in a long time, and I'm seeing plenty of failures in the attachment tests.

**Comment by nolanlawson** [comment]
Oh wait, this is to be expected. We're testing thing like `_all_docs` with `attachments=true`. I don't think this is related.

**Comment by daleharvey** [comment]
Yup, expected and I think we have got #3961 down to a chrome error, https://github.com/pouchdb/pouchdb/issues/3173 is open to document the minimum version for a full test run
