### ISSUE TITLE
An IndexedDB transaction that was not yet complete has been aborted due to page navigation

### ISSUE THREAD

**Issue by hrishiballal** [pouchdb/pouchdb#3973]
In Firefox, I am getting transaction aborted notification when using pouchdb. I was wondering what causes this error and mitigation for it. This is not seen in Chrome. 

![screen shot 2015-06-16 at 21 54 33](https://cloud.githubusercontent.com/assets/1588744/8194254/5d8aa154-1472-11e5-98a4-37c8bf852a4d.png)

**Comment by hrishiballal** [comment]
Did some more digging around and seems like a browser bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1147942 
Is this indeed the case?

**Comment by nolanlawson** [comment]
Looks like it. If there's a workaround, though, then we'd be happy to add it.

**Comment by daleharvey** [comment]
Yeh firefox has been doing this a while, it hasnt looked dangerous up till now, I dont think we need to workaround expect it will be fixed shortly, I am at a mozilla work week this week so will bug people

**Comment by daleharvey** [comment]
Will leave this open to track till the fix gets landed in firefox

**Comment by daleharvey** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1147942 got resolved, so this should stop happening in updated firefox's, as mentioned in the thread its harmless
