### ISSUE TITLE
Is there a way to get pojo from allDocs ?

### ISSUE THREAD

**Issue by mfilotto** [pouchdb/pouchdb#3975]

**Comment by nolanlawson** [comment]
Not sure what you mean? But you can get an array of documents using `result.rows.map(function (row) { return row.doc; });`

**Comment by mfilotto** [comment]
I was thinking of something like js-data [useClass](http://www.js-data.io/v1.8.0/docs/dsdefaults#useclass) that return a collection of custom instances
```javascript
db.allDocs({
  include_docs: true, 
  attachments: true,
  useClass: MyPojo
}).then(function (result) {
  // handle result
}).catch(function (err) {
  console.log(err);
});
```

**Comment by daleharvey** [comment]
@mfilotto I dont think either of us know what a Pojo is in this instance, the objects returned from pouch are plain json, any clarification?

**Comment by nolanlawson** [comment]
If you mean a JavaScript class like

```js
function Dog() {
  this.name = 'Rover';
}

Dog.prototype.bark = function () {
  console.log('woof, my name is: ' + this.name);
}
```

Then no, you will need to convert between plain json objects and your classes. I would also welcome a PouchDB plugin to do this. :)

**Comment by mfilotto** [comment]
@nolanlawson: Yes that's what I meant.
My use case is to mask pouchdb properties (_id and _rev) to my app

@daleharvey : pojo is an acronym that comes from java ecosystem and stands for Plain Old Java Object. Now also used for JavaScript

I finally used your transform plugin to do it.
I can make a plugin if you find it useful

**Comment by daleharvey** [comment]
Ah, yeh it seems unlikely we would be adding that to core, but using transform to do it sounds like a good idea, plugins are always welcome. Gonna close this out now though, cheers

**Comment by mfilotto** [comment]
Thanks for your help
