### ISSUE TITLE
PouchDb in memory adapter, dump into file

### ISSUE THREAD

**Issue by RPallas92** [pouchdb/pouchdb#3976]
Is it possible to dump the PouchDB (memory adapter)  content into a file, and restore it later?

**Comment by daleharvey** [comment]
Yup, sounds like https://github.com/nolanlawson/pouchdb-dump-cli is what you are looking for

**Comment by RPallas92** [comment]
Thank you, with this code:

var ws = fs.createWriteStream('output.txt');

db1.dump(ws).then(function (res) {
  // res should be {ok: true}
});
