### ISSUE TITLE
include_docs performances

### ISSUE THREAD

**Issue by aenario** [pouchdb/pouchdb#3998]
As discussed today with @nolanlawson, 

On Android with SQLite plugin, map reduce request are much slower when using include_docs.

**Comment by nolanlawson** [comment]
Yeah, I suspect this is due to the extra allDocs() query with "keys" when include_docs is used. "keys" is not terribly optimized and uses a separate transaction to fetch each doc. Also I suspect on Android that WebSQL  would be much faster than the SQLite Plugin.

**Comment by daleharvey** [comment]
So we have https://github.com/pouchdb/pouchdb/issues/4152 open that is tracking us improving how we manage tracking performance, also with us moving generally in the direction of pouchdb-find over map reduce, gonna close this out, if you were planning any work on this pease reopen, thanks
