### ISSUE TITLE
Allow to differ between websql and sqlite adapter

### ISSUE THREAD

**Issue by mlegenhausen** [pouchdb/pouchdb#4001]
Current it seems not possible to explicitly choose between `websql` or `sqlite` as storage target.

In my szenario I now want to replicate from `websql` to `sqlite` after the `deviceready` event.

Any ideas how to solve this issue?

**Comment by nolanlawson** [comment]
What is your use case? Would help to understand, so we can decide if/how we would add the new API.

As an aside, I am recommending to everybody to avoid the SQLite Plugin entirely unless you absolutely need it on iOS to avoid the storage limit. It's slower than WebSQL/IndexedDB, and is not currently passing our test suite due to recent bugs that have been introduced.

**Comment by mlegenhausen** [comment]
That was excatly the case why we need to use the SQLite plugin.

The use case was the migration from an previous used websql database to the database used by the sqlite plugin (after the device ready event). There are other possible use cases. Like using the iOS internal database for performance critical stuff and everything else stored in the sqlite database. Or using sqlite on iOS and websql on Android while having the sqlite plugin installed (keeping the build process the same without removing and readding the plugin the whole time).

We already solved the problem by keeping a reference and `window.sqlitePlugin` removing it from the `window` object and initialising the websql pouchdb instance. Then we readded the saved reference to window and instantiating the sqlite pouchdb instance. Then we were able to replicate from websql to sqlite.

**Comment by nolanlawson** [comment]
Long-term, I can tell you that my plan is to write a new IndexedDB adapter that works around Apple's broken implementation. (I'd wait for them to fix it, but I don't have the patience for WWDC 2016. :stuck_out_tongue: ) On WKWebView, IndexedDB has zero storage limits, and is much more stable than the SQLite Plugin, which is a third-party plugin that has had stability issues in the past (despite the heroic efforts of its sole maintainer).

The short-term solution is that you can rename `window.SQLitePlugin` to something else, then create a `new PouchDB()`, which will use WebSQL/SQLitePlugin depending on whether it finds that global variable. In that way you can solve your issue.

```js
var plugin = window.SQLitePlugin;
window.SQLitePlugin = undefined;
var pouch1 = new PouchDB('foo', {adapter: 'websql'}); // <-- websql
window.SQLitePlugin = plugin;
var pouch2 = new PouchDB('foo', {adapter: 'websql'}); // <-- sqlite plugin
```

**Comment by mlegenhausen** [comment]
Already done ;) That sounds good we already taking a look at WKWebView and hope the best. If possible I would remove the Plugin again when the storage limit constrains are removed.

**Comment by nolanlawson** [comment]
So it sounds like this is resolved. Let me know if the workaround doesn't work for you! :)
