### ISSUE TITLE
CouchDB master is failing

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4002]
There was a mention about an overhaul of the build system recently so assuming it broke how we launch

https://github.com/pouchdb/pouchdb/blob/master/bin/run-couch-master-on-travis.sh#L34

@janl any pointers on what the equivalent to startup couch like above is now? cheers

**Comment by janl** [comment]
This should still work. Can you point me to instructions on how to run the the test suite and what errors you are seeing? I’ll have a look then.

**Comment by daleharvey** [comment]
To run the test suite against couch master you start it with the above line and

    COUCH_HOST='http://127.0.0.1:15984' npm test

my git clone of couch needed to `rm -rf src` to start building again, otherwise https://gist.github.com/daleharvey/620fab43a66b92a5f61d happened, but got a checkout building now and should be able to see whats up

Added couch master to allowed failures also

**Comment by janl** [comment]
that looks like get-deps failing during configure

**Comment by daleharvey** [comment]
Yeh, although that was just a local checkout, was just mentioning in case that was something you noticed would want to fix on couch side, a clean checkout worked

It looks for the pouchdb tests that it may just be a timing issue, we do a sleep to wait for couch to start and it looks like it may take a little longer to start now

**Comment by daleharvey** [comment]
https://travis-ci.org/pouchdb/pouchdb/jobs/68684560 is an example of a failing run, building works fine, we dont see the start logs with the & but it cant connect

**Comment by daleharvey** [comment]
hrm, the exact same thing is working fine locally

**Comment by janl** [comment]
yay! :D

**Comment by daleharvey** [comment]
So the issue is a change in either couchdb or travis made failing to build the docs a full failure as instead of just a warning as it was previously

**Comment by daleharvey** [comment]
So I merged https://github.com/pouchdb/pouchdb/commit/9a0354fced16787a625d25255889905a0f71c56b with r=me since it was just infrastructure and it uncovered the fact that couchdb-master is actually failing now

**Comment by daleharvey** [comment]
https://travis-ci.org/pouchdb/pouchdb/jobs/70516090

```
test.changes.js-http #2569 Big non-live doc_ids filter:

     Something wrong with the request
```

**Comment by daleharvey** [comment]
ok, the _doc_ids bug should get fixed by https://github.com/apache/couchdb-chttpd/pull/42

**Comment by daleharvey** [comment]
Tested the above locally and all fixed, should hopefully get merged soon

**Comment by rnewson** [comment]
I've reverted the commit that broke this and will work with the couchdb team to fix the original issue without this side effect.

**Comment by daleharvey** [comment]
All fixed - https://travis-ci.org/pouchdb/pouchdb/builds/70525659, thanks :) 

We will notice regressions sooner next time, the tests werent being monitored due to a build issue

**Comment by rnewson** [comment]
fixed by enhancing couch_httpd's json_body function to match chttpd's which checks for undefined and throws a clean 400 bad request.

**Comment by rnewson** [comment]
and congrats on your 70,525,659th build, where does the time go?

**Comment by daleharvey** [comment]
Hah we have a 'lot' of builds (~40 per pull request) but I dont think those are totally sequential, thats a lot
