### ISSUE TITLE
PouchDB throws no adapter with sqlite3 plugin

### ISSUE THREAD

**Issue by darkyen** [pouchdb/pouchdb#4007]
```
document.addEventListener('deviceready', function () {
  cordovaReady = true;
  var contacts = new PouchDB( 'cache', {
        adapter: 'websql'
  });
});
```

Throws Error "Adapter is missing"

[Update]
Happens the same even without it.

Platform : WP 8.1

**Comment by darkyen** [comment]
The cause of that was how SQlitePlugin was detected probably from the latest version they globalize the SQLite3 object instead of SQLitePlugin

**Comment by nolanlawson** [comment]
Sorry, what do you mean? You mean it's no longer `window.SQLitePlugin`?

**Comment by darkyen** [comment]
Nope I got `window.SQLite3` instead of `window.SQLitePlugin` on WP 8.1, havent had time to check on androids.

**Comment by nolanlawson** [comment]
Okay, I will open up a PR.

**Comment by nolanlawson** [comment]
Actually wait, this is clearly a bug on the SQLite Plugin, since in their own docs they say `window.sqlitePlugin` is what it should be called. I'll open an issue over there.

**Comment by nolanlawson** [comment]
closing since this doesn't seem like a pouch issue

**Comment by darkyen** [comment]
Alright, awesome

**Comment by nolanlawson** [comment]
In the meantime you can also solve this issue by just doing `window.sqlitePlugin = window.SQLite3` assuming the API is still the same.

**Comment by darkyen** [comment]
yep thats what i ended up doing.
