### ISSUE TITLE
Pouch db does not correctly use Url escape coding for '[' and ']' characters

### ISSUE THREAD

**Issue by driak** [pouchdb/pouchdb#4008]
Hi when syncing with a remote couchdb our proxy refuses the http call from pouch because it does not correctly escape code '[' and ']' characters in the url query parameters, resulting in a 'bad request' response from the proxy.

These characters should be escape coded as %5B and %5D respectively.

(Couchdb itself accepts this, but the proxy seems to be more strict...)

A pouchdb call like:

var ids = [ '1E005B2C-283A-F84B-AC9F-7FD2AAE92846',
  '1EA36D92-D70B-40DD-A28F-8DD904570FC3',
  '2AC77D16-D7A9-81EA-9D52-23DE7DE45837',
  '3CF92D43-9FB5-3A4A-899C-A0927545DB27',
  '7DD6991A-3496-1999-8E6E-F289F64E0B3C',
  '8DC9A655-9762-2F00-A469-8AA0F4F027B8',
  '92A8FD46-43EC-F29F-AD2D-B33EC67363F7',
  '9B661AB5-6990-668B-B1A1-25D51CA47DAD',
  'BDF5BF13-819F-CF2A-876F-C7139FCBBD63',
  'F6610D2D-484E-9919-8024-E035E6F83374' ];

remotedb.replicate.to(localdb, {
                    doc_ids: ids
                });

results in :

http://localhost:5984/wi-pv-data/_changes?timeout=25000&style=all_docs&filter=_doc_ids&doc_ids=[%220361C544-88EC-CD75-827B-92192EDEBEED%22,%2246189006-6E2E-60AC-9451-845F620723D3%22,%22520C317A-CCC7-B006-9203-E3849A3DD1A6%22,%228498B6AE-9D3C-A0DB-8956-3E726523C19C%22,%229FACB6B2-DEBC-5183-AB88-050D0FE49AFA%22,%22A133CB74-E2D3-5C91-AB31-D4B814CADB7E%22,%22A6942D46-1E02-A7AC-B587-E14BD720C12B%22,%22BA6E3F04-3EC8-B321-8C43-EBBF6AB452D4%22,%22CE7CA098-751B-4FF8-A941-B5E4FC4FB5BC%22,%22E4128A59-B0C0-5689-BC78-A46F92323770%22]&since=0&limit=100

on which the proxy returns a 'Bad request':

Illegal request, responding with status '400 Bad Request': Illegal request-target: Invalid input '[', expected '+', query-char, '%', '&' or 'EOI' (line 1, column 75): /wi-pv-data/_changes?timeout=25000&style=all_docs&filter=_doc_ids&doc_ids=[%221E005B2C-283A-F84B-AC9F-7FD2AAE92846%22,%221EA36D92-D70B-40DD-A28F-8DD904570FC3%22,%222AC77D16-D7A9-81EA-9D52-23DE7DE45837%22,%223CF92D43-9FB5-3A4A-899C-A0927545DB27%22,%227DD6991A-3496-1999-8E6E-F289F64E0B3C%22,%228DC9A655-9762-2F00-A469-8AA0F4F027B8%22,%2292A8FD46-43EC-F29F-AD2D-B33EC67363F7%22,%229B661AB5-6990-668B-B1A1-25D51CA47DAD%22,%22BDF5BF13-819F-CF2A-876F-C7139FCBBD63%22,%22F6610D2D-484E-9919-8024-E035E6F83374%22]&since=0&limit=100

changing the call to:

http://localhost:5984/wi-pv-data/_changes?timeout=25000&style=all_docs&filter=_doc_ids&doc_ids=%5B%220361C544-88EC-CD75-827B-92192EDEBEED%22,%2246189006-6E2E-60AC-9451-845F620723D3%22,%22520C317A-CCC7-B006-9203-E3849A3DD1A6%22,%228498B6AE-9D3C-A0DB-8956-3E726523C19C%22,%229FACB6B2-DEBC-5183-AB88-050D0FE49AFA%22,%22A133CB74-E2D3-5C91-AB31-D4B814CADB7E%22,%22A6942D46-1E02-A7AC-B587-E14BD720C12B%22,%22BA6E3F04-3EC8-B321-8C43-EBBF6AB452D4%22,%22CE7CA098-751B-4FF8-A941-B5E4FC4FB5BC%22,%22E4128A59-B0C0-5689-BC78-A46F92323770%22%5D&since=0&limit=100

does pass the proxy and results in the expected response from Couchdb (server side)

**Comment by driak** [comment]
Temporarily solved for our specific case by relaxing our proxy's url validation rules, but there's no guarantee it will fail higher up on infrastructure not under our control.

Pouch url encoding should follow the url encoding rules outlined here...
https://tools.ietf.org/html/rfc3986#section-2.2

**Comment by daleharvey** [comment]
Got a patch up @ https://github.com/pouchdb/pouchdb/pull/4030, mostly to see if it breaks any existing tests, I dont really know of the best way to test this, any suggestions welcome

**Comment by daleharvey** [comment]
Thought of a test for this, should be ready to go, anyone want to +1 ? :)

**Comment by daleharvey** [comment]
(https://github.com/pouchdb/pouchdb/pull/4030 is the PR)

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/8eef9ab7865e32ae4fac152db3e59d7db1c69dbc
