### ISSUE TITLE
Firefox Private Browsing causes InvalidStateError / 500 Internal Error

### ISSUE THREAD

**Issue by rarkins** [pouchdb/pouchdb#4010]
PouchDB fails with a 500 Internal Error if launched with Firefox in Private Browsing mode.

From reading issues in other repositories (e.g. [here](https://github.com/mozilla/localForage/issues/70)), it sounds like indexedDB fails ungraciously when in a private window. Would it be appropriate for PouchDB to have a more advanced check for indexedDB support before attempting to use it?

**Comment by daleharvey** [comment]
I have added a more more visible warning for private browsing which is about the best we can do at the moment - https://github.com/pouchdb/pouchdb/commit/9ecf016aeb55bf228d7ac77cb39ca674dcd4c955

**Comment by oliviertassinari** [comment]
For anyone looking for a work-around to this issue, here is mine:
```js
  new Promise((resolve) => {
    const pouchdbOptions = {};
    let dbLocal = {};

    // ... Some iOS adapter detection.

    if (typeof window !== 'undefined' && window.indexedDB && /Firefox/.test(window.navigator.userAgent)) {
      const request = window.indexedDB.open('test_firefox_pm');

      /**
       * We are most likely under the buggy private mode.
       * IndexDB is not available.
       */
      request.onerror = () => {
        pouchdbOptions.adapter = 'localstorage';
        PouchDB.plugin(require('pouchdb-adapter-localstorage'));

        dbLocal = new PouchDB('db', pouchdbOptions);
        resolve(dbLocal);

        return true; // It's preventing `InvalidStateError` and `UnknownError` exceptions.
      };
      request.onsuccess = () => {
        dbLocal = new PouchDB('db', pouchdbOptions);
        resolve(dbLocal);
      };
    } else {
      dbLocal = new PouchDB('db', pouchdbOptions);
      resolve(dbLocal);
    }
  };
```

**Comment by nolanlawson** [comment]
I opened a new issue here fwiw: #5641
