### ISSUE TITLE
Can we expose lib/replicate/genReplicationId?

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb#4013]
I'd like to know changes in my local PouchDB database have not yet been synchronised to my remote database. My usecase: I want to tell my users, what local changes have not yet been synchronised. I'd like to use that for our "local changes" PouchDB plugin: https://github.com/hoodiehq/pouchdb-hoodie-local-changes

So I'd like to do something like this

```
var PouchDB = require('pouchdb')
var genReplicationId = require('pouchdb/lib/replicate/gen-replication-id')

var localDb = new PouchDB('mydb')
var remoteDb = new PouchDB('remoteDb') // would usually be a URL

localDb.put({_id: 'test'})
.then(function () {
  return localDb.replicate.to(remoteDb, { create_target: true })
})
.then(function () {
  return genReplicationId(localDb, remoteDb, {})
})
.then(function (replicationId) {
  return localDb.get(replicationId)
})
.then(function (localReplicationDoc) {
  // localReplicationDoc.last_seq should be 1
  console.log(localReplicationDoc)
})
```

I'd like to avoid `require('pouchdb/lib/replicate/gen-replication-id')`, as that's an internal that's likely to change. Instead, it'd be nice if we could expose this in a way that we can guarantee it won't change in future with a small unit tests, similar to what you do with the `require(pouchdb/extras/ajax)` etc. 

Would that be possible?

**Comment by daleharvey** [comment]
This sounds extremely useful although I think we would like to expose the actual id generated for the replication instead of having users generate their own, you used different options when you generated the id, in this case I think it would give the same id but thats an implementation detail I dont think users should be worried about

how about: 

```
var PouchDB = require('pouchdb')

var localDb = new PouchDB('mydb')
var remoteDb = new PouchDB('remoteDb') // would usually be a URL

localDb.put({_id: 'test'}).then(function () {
  return localDb.replicate.to(remoteDb, { create_target: true })
}).then(function (replication) {
  return localDb.get('_local/' + replication.id)
}).then(function (localReplicationDoc) {
  // localReplicationDoc.last_seq should be 1
  console.log(localReplicationDoc)
})
```

**Comment by gr2m** [comment]
thanks Dale!

I think your suggestion won't work, because I want to get the seq number of a replication without running the replication. Think of a use case where a user purposely wants to work on a local copy, and only when finished with all work, replicate to a central database. I'd like to tell the user which documents have been changed, without replicating the local changes.

Does that make sense?

Maybe instead of 

```js
localDb.replicate.to(remoteDb, { create_target: true })
```

we could add a method like

```js
localDb.replicate.getSeqNumberFor(remoteDb, { create_target: true })
```

**Comment by gr2m** [comment]
We are close to release our PouchDB plugin to get changed docs that have not been replicated to a remote db yet. But we have a naming problem :D Any help appreciated:
https://github.com/hoodiehq/pouchdb-hoodie-local-changes/issues/4

**Comment by daleharvey** [comment]
This is exposed now
