### ISSUE TITLE
Cannot find module './deps/docs/parseDoc'

### ISSUE THREAD

**Issue by dahjelle** [pouchdb/pouchdb#4016]
If I `npm install pouchdb/pouchdb` (to install the latest PouchDB from GitHub—not what I'd usually do, but pouchdb/plugin-seed does it), the `.npmignore` file will ignore all directories named `docs`, including `lib/deps/docs/`, which you probably want to include.

It looks like it was introduced in [this commit](https://github.com/pouchdb/pouchdb/commit/756e2226859b8be521e95d3312136f11e497c334#diff-0fd4ef892d9d4990033701887c2f9bcc).

**Comment by daleharvey** [comment]
hrm this is very weird, we dont have code in `/docs/` so the utils require is probably a typo, not sure why its not breaking things though, some code does go though utils.parseDoc

**Comment by daleharvey** [comment]
hah no, it is actually in a folder called `/docs/`, just a different one, nice catch cheers

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/e2805b41c59c55c19f5900a8c6f5ef4f57812273
