### ISSUE TITLE
Synchronization repetition between Couch and Pouch and Saving no data into local PouchDB 

### ISSUE THREAD

**Issue by ronyrun** [pouchdb/pouchdb#4020]
Hello, 

I have this behavior with my docs when I'm synchronizing the docs from a CouchDB Database : 

![syncpouchdb](https://cloud.githubusercontent.com/assets/7273443/8500113/7825d0ae-2199-11e5-865f-b08c70100df3.png)

Is there some configuration to improve this behavior ?

**Comment by ronyrun** [comment]
DB.changes({
                    continuous: true,
                    live: true,
                    since: 'now',
                    include_docs: true
                })

**Comment by daleharvey** [comment]
@roryrun are you manually synchronising that data? if so then yes in pouchdb we store the last checkpoint in replication and use that for 'since' to ensure you get changes that were made since the last sync. Is there any reason you arent using pouchdb's replication?

Either way sounds like you found your issue, but happy to follow up if you still have questions

**Comment by ronyrun** [comment]
Hello Dale, 
I'm using the PouchDB Replication.
That's why I'm asking about this behavior


localDB.sync(remoteDB, options)
                                    .on('change', onChange)
                                    .on('paused', onPause)
                                    .on('active', onActive)
                                    .on('denied', onDenied )
                                    .on('complete',onComplete )
                                    .on('error', onError);
                            }).catch(function(err) {
                                console.log(err);
                                $rootScope.$broadcast('sync-completed', err);
                            });

**Comment by ronyrun** [comment]
I made several changes with local scripts on my local DB client.
The options of Sync are : 
 batch_size : 1000, live: live,retry : true,

And with this batch_size, I've got only 1 sync Change occured at a time...
This means the replication is endless...... with a huge package of docs exchanged each time...



![capture](https://cloud.githubusercontent.com/assets/7273443/8530377/f4384cd8-2420-11e5-855b-5ec4ee957c6d.JPG)

**Comment by ronyrun** [comment]
I'm having a bulkdoc cancelled with the whole database there : 

![syncpouchdb3](https://cloud.githubusercontent.com/assets/7273443/8531290/8ccbb5de-2426-11e5-8583-b1d6dd566596.png)

**Comment by ronyrun** [comment]
Solved with "Since" LastSeq values !
