### ISSUE TITLE
indexedDB have a store to persist rows, pounchdb how?

### ISSUE THREAD

**Issue by longxianlin** [pouchdb/pouchdb#4027]
I have different class, 
Student, Course, Teacher.
How to save rows to different store in poucdb?
guild book not clear about this.

do like this:
new PouchDB("Student");
new PouchDB("Course");
new PouchDB("Teacher");
punnchdb == indexedDB storeobject?

**Comment by nickcolley** [comment]
A simple approach would be to store your data in one instance of PouchDB, with a type property e.g.:

```js
{
   type: 'student'
}
```

Then you can filter against that.

**Comment by daleharvey** [comment]
Yup, you can do 

```
new PouchDB("Student");
new PouchDB("Course");
new PouchDB("Teacher");
```

However you will not be able to write queries across those databases and will need to query them seperately, or you can do as @nickcolley suggested and put them all in the same database with a `type` field. If you have any more questions feel free
