### ISSUE TITLE
Old view files are kept around

### ISSUE THREAD

**Issue by Heshyo** [pouchdb/pouchdb#4032]
I have an app where a view has a specific definition, but now I want to return an additional info. Is it possible to simply update it?

I tried deleting the view then add it with the new definition, but it looks like it doesn't work.

**Comment by daleharvey** [comment]
@Heshyo apologies but will need more information to help you out with this, do you have a view stored in a design document? if so you should be able to update the design document the same way you would update any document in pouchdb, if you have deleted the previous version you should only need to `.put()` a new one

**Comment by Heshyo** [comment]
@daleharvey OK I simply tried what you said and it works. So basically I do
```javascript
database.get('_design/' + viewName, function (err, doc) {
	if (doc) {
		// Update the map function.
		doc.views[viewName].map = mapFunction.toString();
		database.put(doc, doc._id, function (err, response) {
			if (response) {
				// View was updated, next time I'll use it it will be repopulated.
			}
		};
	}
}
```

Now I notice when debugging in Chrome that the old view sticks around, when looking at the "Resources" pane (I still see the old _pouch_dbName-mrview-xxx), and a new view is created. I tried calling the ```database.viewCleanup``` but it looked like the old view was still there. Am I missing something?

**Comment by daleharvey** [comment]
Nope we should clean those out automatically for you, although I cant actually remember what does that, will rename the bug and take a look, thanks

**Comment by daleharvey** [comment]
So we have tests to ensure these databases are cleaned up, and all my local testing is working fine. I very much believe this is a bug with the chrome inspector (which I have seen a lot of times) that keeps an open handle and shows stale data.

If you still see problems after a reload then please reopen and if you had any code that can reproduce this it would be especially useful. Thanks
