### ISSUE TITLE
Issue in installing in android 4.0.3

### ISSUE THREAD

**Issue by manoj529** [pouchdb/pouchdb#4034]
I have tried to install the default pouchdb todo app in Samsung galaxy s duos Ie android 4.0.3, it didnt get installed and thorws error 

"there is a problem parsing the package"

the same app works on lenovo  mobile which runs on 4.4.4

**Comment by nickcolley** [comment]
Hey @manoj529 what are you using to package your app?

Is it possible to share the code with us?

**Comment by manoj529** [comment]
Thanks For the reply nickcolley.

I found the error,it is not with the pouchdb the error is with a parameter in config file with is restricting me from installing app.


i changed "android-minSdkVersion" value from 16 to 14 in config.xml,created a new apk file and it worked.
