### ISSUE TITLE
Best practices for loading design documents?

### ISSUE THREAD

**Issue by stuartpb** [pouchdb/pouchdb#4037]
I don't see anything about this in the docs, and I'm not sure where I should ask this, but what is the recommended way to handle introducing design documents in PouchDB?

This is the approach that seems most sensible to me:

- Keep a "version" property on the design document, which is incremented for every new release of the design doc. (This is distinct from `_rev`, which tracks every **seen** revision of the design document - `_rev` needs to be sequential through an instance's history, `version` does not.)
  - This allows you to introduce new views and other code to data using the same schema. For schema changes, you may similarly wish to version your database, with migrations through replication, but that's out of scope here.
- After the database is created in your code, do a `db.put()` of your design doc, with its `_design/`-prefixed `_id` and `version` field (but no `_rev`) into the database. (Each piece of code that instantiates the DB should really have no more than one design doc.)
- If the `put` succeeds (which will only happen once), then you just introduced your design doc (and probably also just created the database), and you should do a query on your views to start building them incrementally for all future document changes.
- If the `put` fails, check why: in the most likely case, where you got a 409 because the doc already exists, check what the `version` of the existing doc is.
  - If the `version` of the existing design doc is lower than the `version` you were going to add, add the `_rev` of the existing design doc to your new design document and re-do the `put` to overwrite it.
  - Otherwise, do nothing (this will be the branch 99% of your executions will go down).

**Comment by stuartpb** [comment]
Also, it would be nice if I didn't have to finagle design documents at *all* to save map/reduce data (namely because (de)serializing entails an `eval` which does not play well with Content Security Policies); I don't know if `query` exposes this already, but it would make this kind of thing *much* simpler if PouchDB just had some kind of "this is a view" flag to use when giving map/reduce functions to `query` that would cause it to serialize the function and use its serialized representation as the ID for the map data.

**Comment by daleharvey** [comment]
As you suggested is pretty much the way I have done in the past, keep a version in the code and check on startup.

pouchdb-find (http://nolanlawson.github.io/pouchdb-find/) is quite stable and doesnt require mangling design docs, it does a lot of the management for you, it does however still use map reduce internally so still uses `eval`, https://github.com/evidenceprime/pouchdb.mapreduce.noeval is a way to avoid using `eval`

We have plans to merge pouchdb-find into core possibly replacing map reduce, the pouchdb-find api does not require `eval` technically and could possibly use native indexes, however that is a large amount of work so wont be happening in the short term

Your idea of priming the design document with a real function is a good idea though, that sounds like something we should be able to do

**Comment by nolanlawson** [comment]
@daleharvey Actually it does not use `eval`. :) I managed to extract the eval stuff and put the rest into `abstract-mapreduce`, and that's what `pouchdb-find` is using.

**Comment by daleharvey** [comment]
oh nice, then yup sounds like the answer is to use `pouchdb-find` :) We will be moving pouchdb-find into core at some point - https://github.com/pouchdb/pouchdb/issues/3538

**Comment by rominf** [comment]
I want to extract a set of values from different branches of doc and join with other database.
