### ISSUE TITLE
Database encountered an Unknown Error when Syncing on poor quality Internet Connection

### ISSUE THREAD

**Issue by simonaberry** [pouchdb/pouchdb#4040]
A number of my application users are experiencing 'Database encountered Unknown Error '  when syncing (to Cloudant). I have managed to narrow down the common factor is typically when the internet connection for that client is very slow.  By changing to a faster connection with the exact same client the sync completes with no issues. 

I am not sure how the error handling works inside PouchDB, but I would hope that it would recovery gracefully from dropped packets and/or timeouts ??

Let me know if I can somehow provide more info.  I am using v3.6.0

**Comment by daleharvey** [comment]
So theres 2 main issues here, one has been fixed on master @ https://github.com/pouchdb/pouchdb/commit/931df967ef211ea12362b3afc6ee7f1570e89c8f, that is that we couldnt recover from errors well. The other is that we seem to be getting more 500 errors from cloudant recently and that is being investigated @ https://github.com/pouchdb/pouchdb/issues/4023, so closing this as a dupe
