### ISSUE TITLE
Request to add discussion on drop/rebuild of databases to Replication Guide

### ISSUE THREAD

**Issue by tohagan** [pouchdb/pouchdb#4041]
I'm looking at building a couple of systems where we periodically drop and rebuild CouchDb databases (source databases) that are then replicated to multiple client devices using PouchDb (target databases).

When a replicated source database is deleted and then rebuilt ... I'm wondering what happens when PouchdDb replication resumes?  Will it drop and rebuild the target database also?  How is this performed (maybe you can point me at some code). I'm wondering if it drops the SQLite/DbIndex database or deletes all docs and then starts replicating?  Perhaps doc deletions only happens when you're merging multiple replicated db's.  Maybe I need to write my own code to detect and action this scenario?  

Does it work safely if clients are running live replication when I drop and rebuild. If `retry` is `true`, will it still retry and auto-rebuild?

I've hunted for a while for answers to these question so really wishing it was in the [Replication Guide](http://pouchdb.com/guides/replication.html) as I think it's a common scenario.  I've also looked for answers on how CouchDb behaves but not found the answer. I'm assuming you'd duplicate this.

I'm aware of [this issue](https://github.com/pouchdb/pouchdb/issues/3999) that may be related.

**Comment by daleharvey** [comment]
So this is a curious use case that I have come across myself, the answer is no, when you drop your remote database, the local database will keep all of its contents and when replication resumes it will keep all of your old data and your new data

If you want to delete the data from both the source and target databases, you need to delete the actual documents, https://www.npmjs.com/package/pouchdb-erase is a plugin that will help you do that

**Comment by daleharvey** [comment]
I do think this is worth a note in the replication guide

**Comment by tohagan** [comment]
> when you drop your remote database, the local database will keep all of its contents and when replication resumes it will keep all of your old data and your new data

Ouch! So does that mean it will also replicate the old data back to the source if you start two way replication?

OK ... so what I think I'll have to do then is:

1. Add single doc to each new database with a unique UUID 
2. Prior to starting up replication check first to detect if the db was rebuilt by looking for this record
3. If it's changed (new database) then drop the local database and recreate it. 

To speed up the initial replication of a larger db, I may also need to ...

1. Create a PouchDb/Sqlite database on the server side using NodeJS thats a replication of the new CouchDb databae,
2. Zip it up and make it available for download as a file.
3. Client side downloads and unzips the SQLite database
4. Opens the database using `createFromLocation` option 
5. Restarts replication.  

Hope all this should work - any idea if this would create any issues?
Is there a simpler way? Plugin perhaps?

**Comment by daleharvey** [comment]
Yup the documents will replicate back, your exact scenario I hit while trying to make demos quite a few times.

Your use flow makes sense, I would consider instead of recreating it you can create a new one with a new name, the 'UUID' document can the name of the currently active database, but thats details.

And for initial bulk loading I would take a look at https://github.com/nolanlawson/pouchdb-load, we should hopefully get to the point where replication time is not significantly different from downloading, but we arent there yet

**Comment by tohagan** [comment]
You guys need a High-5 !!  Thanks Dale. Anywhere I can vote you up?

**Comment by tohagan** [comment]
Yeah makes sense to just make a new database name - works well for my use case.  We can also use another small 'master' database that just tracks active db instances. When an instance doc becomes `_deleted: true` we stop replicating the local instance and drop the local database.

**Comment by daleharvey** [comment]
Sounds like a plan, and for votes we totally accept them in the form of pull requests :) cheers

**Comment by tohagan** [comment]
LOL  :)

**Comment by daleharvey** [comment]
Cheers for the report, added a note to the guide in https://github.com/pouchdb/pouchdb/commit/8b112be7a425c9b7010dc0418211b8406f440dfb
