### ISSUE TITLE
implement HEAD method

### ISSUE THREAD

**Issue by Ti-webdev** [pouchdb/pouchdb#4046]
If we want _rev info only or check the document is exists, method HEAD does it.

PouchDB.head(document_id)

Another Implementations of head method:
https://github.com/dscape/nano#dbheaddocname-callback
http://mikepb.github.io/clerk/docs/clerk/0.8.0/clerk.DB.html#head

**Comment by karlwestin** [comment]
Looks doable to me
Was looking through the diff adapters it seems to me:
in IndexedDB we can make an interrupted 'GET' (we have the data at  line 329), https://github.com/pouchdb/pouchdb/blob/9a0354fced16787a625d25255889905a0f71c56b/lib/adapters/idb/index.js#L290-L329

LevelDB is the same, an interrupted GET https://github.com/pouchdb/pouchdb/blob/9a0354fced16787a625d25255889905a0f71c56b/lib/adapters/leveldb/index.js#L327-L343 (we have the data at 343)

WebSQL would have to go through the entire get https://github.com/pouchdb/pouchdb/blob/9a0354fced16787a625d25255889905a0f71c56b/lib/adapters/websql/index.js#L587

**Comment by karlwestin** [comment]
For HTTP, can just look at the GET method and do almost the same
https://github.com/pouchdb/pouchdb/blob/9a0354fced16787a625d25255889905a0f71c56b/lib/adapters/http/index.js#L311

One thing i don't really understand is why clerk allows options for this method? It seems to me that HEAD doesn't take any options https://wiki.apache.org/couchdb/HTTP_Document_API#HEAD. Is that right?

**Comment by daleharvey** [comment]
CouchDB at the least used to just implement HEAD as a GET and then strip the data, it would be easiest to implement it that way, however it seems like that can just as easily be done by user code. 

Whats the use case for adding this over just using `db.get` ? `HEAD` seems fairly specific to http implementations and so best implemented in pouchdb-server or pouchdb-express-router, We generally try to keep pouchdb core to shared database only api's and anything transport specific can be done on top

**Comment by marten-de-vries** [comment]
aside: ``HEAD`` is already auto-handled by express for express-pouchdb & pouchdb-express-router.

**Comment by daleharvey** [comment]
Awesome yeh I totally forgot express already handles that for us, a `.head` isnt going to be significantly faster than a `.get` and this is already the behaviour of `allDocs` and views, so closing this out

**Comment by ryanramage** [comment]
> nolanlawson: ryan_ramage: no, because the HEAD doesn't make much sense for indexeddb/websql/leveldb
> [09:11am] ryan_ramage: right, gotcha
> [09:11am] nolanlawson: although well, yeah, actually arguably it could be added
> [09:11am] nolanlawson: db.head() could be a thing. we could make the WebSQL/IDB fetches slightly more efficient by just giving a yes/no answer
> [09:11am] nolanlawson: interesting idea
> [09:11am] nolanlawson: file an issue?
> [09:12am] ryan_ramage: https://github.com/pouchdb/pouchdb/issues/4046
> [09:13am] nolanlawson: ryan_ramage: I'd say reopen; off the top of my head I believe we can write slightly more efficient queries to do a HEAD vs a GET
> [09:13am] nolanlawson: so it could be justified
> [09:13am] nolanlawson: IMO
> [09:14am] nolanlawson: e.g. it could be done in indexeddb without using a join; just by using a normal cursor on the by-seq store (or a getAll())
> [09:14am] nolanlawson: and in websql it could just be a simpler SQL query

**Comment by ryanramage** [comment]
@daleharvey @nolanlawson can this be reopened based on the above thread from irc?

**Comment by nolanlawson** [comment]
Yeah I would reopen it. I think it at least needs investigation to see if the perf benefit of doing a very very lite query on IDB/WebSQL/LevelDB justifies the addition of a new API. My suspicion is... yeah maybe? Especially for IDB if we can avoid the join and use `getAll()`.

**Comment by daleharvey** [comment]
I wouldnt be totally against a patch for this, but still not seeing much use cases where individual reads are too slow to warrant a full extra api, plus we are very much looking to speed reads up, so I dont think we need to track.
