### ISSUE TITLE
Filtered replication: delete docs in pouch that no longer pass the filter

### ISSUE THREAD

**Issue by fikkatra** [pouchdb/pouchdb#4047]
Let's say I'm building an application that displays the tasks that employees will be working on today. Each task has a category, e.g. 'masonry', 'plumbing' or 'electricity'. All tasks for all employees are stored in a couchdb.

The tasks are synched to the individual devices of the employees. When we replicate the tasks to pouchdb, we apply a filter so that only tasks that comply to the skills of the employee are stored in pouchdb. We apply this filter client-side, like this:

pouchDb.replicate.from(url, {
	filter: function (doc) {
		return doc.category === employeeSkill;
	}
	...

For example, let's say the dispatcher creates a task of category 'plumbing'. Employee Harry, who is a plumber, synchronizes this tasks and sees it displayed on his device. He does not see any 'electricity' tasks, because he doesn't know about electricity. So far so good.

Now for the tricky part:  let's say the dispatcher realizes he made a mistake: the task is actually an 'electricity' task. He updates the task to the new category. Here's the issue: eventhough the task is updated in couchdb, it will still remain on Harry's device. The task does not pass the filter on the device and hence it won't be updated. The desired behaviour is that the task is removed from Harry's device.

Is there a way to delete documents that do not pass the replication filter anymore? If not, do you guys see any workarounds? For now, I can only think of 2 ways: 

1): keep a list of 'previous categories' on each task and let a task pass the filter if one of its current or previous categories matches the employee's skill. This way, the task will be updated on Harry's device upon replication. Then, after the replication, do another loop over the documents and delete all tasks that do not match Harry's skill. But urgh...

2): create a seperate couchdb for each category. However, bookkeeping will get seriously complex. It will also make it difficult to handle employees with multiple skills (need to replicate multiple couchdb's) or tasks with multiple categories (same task stored in multiple couch dbs).

Quick note: it's not feasable to store ALL tasks on the device and only display the tasks that match the employee. First of all: it would mess up some map-reduce data (like _stats). Second, it would take up way too much space.

Any ideas would be much appreciated!

**Comment by daleharvey** [comment]
hrm, I dont think you need to keep track of recent categories, you could just delete all the local tasks that dont match the filter right? however the issue with that approach is if you change categories back to one that was previously deleted, the local deletion will replicate back

I dont think you need to create a seperate couchdb for each category, but how about creating a new local database for each set of categories the employee is subscribed to, so: 

```
var db = new PouchDB('employee_name_electricity');
db.replicate.from(main, {filter: filter...});
```

Whenever you change the categories, you wipe the old database and start using the new one, do you think that would work?

**Comment by fikkatra** [comment]
Hi Dale,

Thanks for the quick answer. The first suggestion cannot be done without synchronizing ALL tasks to the local database, i.e. ditching the replication filter and applying it only after replication has finished. Otherwise, the updated task won't be synchronized because it doesn't pass the filter. We'll be stuck with the stale task, and there's no way to know we should delete it. This approach is impossible for us: we cannot replicate all tasks to the local database (even if we delete most of them later), because of the size of the data (we have A LOT of data). That's the reason I suggested to keep track of recent categories, because the amount of data to sync (and to delete afterwards) is much more limited in that case.

The second suggestion, unfortunately, won't be feasable for us either. This implies a database wipe upon each and every synch, because locally there's no way of knowing when a category has been changed server-side, so we have to assume the worst. This would take much too long, again because of the huge amount of data (we're talking about 'initial sync' times of well over a minute).

On the bright side: we do not replicate back, synchronization is done one way, from couch to pouch, so maybe we can leverage that fact when searching for a solution.

**Comment by daleharvey** [comment]
Sorry I think I misunderstand how you are implementing this, with the first option (do a batch delete after sync) why would you want to sync updated items that dont match the filter? and if you wanted to you can only delete items that dont match the filter and dont have local updates to be replicated.

And also confused about the wiping the data on every sync, the client subscribes to A, so you have a filter for doc.category = A, you replicate into `new PouchDB('local_data_A')`, you carry on with that replication while the client is subscribed to A, then if the client subscribes to B, you go with a new database and new filter

**Comment by fikkatra** [comment]
it's not so much about the client changing categories, but more about the documents changing categories. That's why you still need to sync items that do not match the filter. If item X is of category A and you have it synced locally (because you're subscribed to A), but then item X changes category to B, you still want it synced, even though it doesn't match the filter anymore. If you don't sync it, item X will be stuck in your local database, with the (stale) category A, which is incorrect. A possible solution is to sync the item anyway, then delete the updated item because its new category doesn't match the client.

I ended up keeping a list of previous categories. A document matches the replication filter if the client is subscribed to either the current or one of the previous categories. Then, after the replication is complete, I delete the documents whose CURRENT category does not match the client's subscription (i.e. all documents that used to match the client, but do not anymore due to a category switch).

As we use one-way replication only, these local deletes are not synched back to the server. This solution works for us because it minimises the number of local deletes, as only documents that switched category are deleted.

**Comment by willholley** [comment]
This sounds like another requirement for single document purge (see #802).

**Comment by daleharvey** [comment]
Ah good call, sorry for missing that, sounds like a good workaround, purge would definitely help if you needed 2 way sync but for now it seems fixed, cheers
