### ISSUE TITLE
Clarify the Apache 2 license

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4052]
I've been super inconsistent about this myself, but I think it's time to wrangle all the licenses in our plugins and associated libs.

It's not necessary to add a "license" field to npm (really that holds no legal value, from what our lawyer at Squarespace has told me), but we should at least be consistent with the LICENSE file.

**Comment by daleharvey** [comment]
Can this be closed?

**Comment by nolanlawson** [comment]
Yup, I'm pleased for now. Should probably go through and add a LICENSE for all my plugins, but that's a personal TODO more than anything.
