### ISSUE TITLE
Private browsing mode

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4053]
This has been brought up by @bahmutov, but basically PouchDB is really unstable in a variety of browsers in incognito mode, most notably Firefox.

Every browser handles this stuff differently (throwing an error with you access IndexedDB, letting you use IndexedDB but then deleting stuff afterwards, etc.), and we don't really have a unified way of dealing with that. I honestly don't know what the right solution is. Ideal would be to fall back to in-memory, but currently the in-memory plugin is huge (>50KB), so that's an unreasonable solution. Also we need all the logic to detect private browsing in the various browsers, which is a huge undertaking in and of itself. Thoughts?

**Comment by nickcolley** [comment]
Feel like if we were to go with the detect private browsing it'd be great as it's own project for the community, this way it'd be easier to find contributors to a smaller microlib?

Definitely think it's a good idea to help devs out here and not leave them having to do the hard work detecting.

I think @daleharvey has suggested falling back to HTTP? But I the user is offline that's not great.

**Comment by nolanlawson** [comment]
Falling back to HTTP is arguably not great for private browsing, because presumably the user is trying to avoid any kind of persistence whatsoever. I wish we could just fall back to in-memory mode instead.

Maybe it's time to write a small custom in-memory adapter so we don't need the large MemDOWN one. Would be a great project for a new contributor as well.

**Comment by daleharvey** [comment]
I think we mostly just have to wait for https://bugzilla.mozilla.org/show_bug.cgi?id=781982 then, doing private browsing mode detection is going to be a rabbit hole (I think one of the points is that it is not supposed to be detectable)

**Comment by nolanlawson** [comment]
@bahmutov Can you confirm that the biggest issue you ran into was with Firefox? If so, then I agree with Dale that we should just wait for the Firefox bugfix.

**Comment by bahmutov** [comment]
Yup, @nolanlawson Firefox incognito is really the only one giving us troubles (we load memory adapter just in this case and switch).

**Comment by daleharvey** [comment]
I have cc'd myself on the Firefox bug so will know when this lands but seems we should close this since there isn't anything we can do about it otherwise

**Comment by openhouse** [comment]
Here is a jsfiddle for detecting private browsing that I find works on OSX: Chrome, Safari, Firefox iOS: Safari https://jsfiddle.net/Lj2fs5kr/

**Comment by jackkleeman** [comment]
FYI, Firefox let's you access indexeddb in private mode if you're calling from inside a WebWorker or SharedWorker. The data doesn't persist, of course, but the api works fine and I have pouchdb working with no issue.
