### ISSUE TITLE
Delete database docs don't match API

### ISSUE THREAD

**Issue by bedney** [pouchdb/pouchdb#4056]
So in using the `destroy` call, I found that a second parameter is indeed to the callback (I'm using the callback version) that will contain an 'ok' result (presumably if the database could be deleted).

However, the API docs only expose one parameter to the callback - 'error':

http://pouchdb.com/api.html#delete_database

Is this by design? Should I not be relying on the 2nd parameter, or is this just an error in the docs. I like knowing that the operation succeeded so I'd be in favor of keeping the parameter and just updating the docs.

**Comment by daleharvey** [comment]
This is an error in the documentation, https://github.com/pouchdb/pouchdb/commit/849e7cbdaa4495244cea8dcfde1b4d00752f9026 added the return value on purpose it was just missing an update for the documentation. 

Cheers, will be fixed, if you wanted to open a PR for that it would be very welcome

**Comment by bedney** [comment]
Added a PR. I used the same parameter names as I saw in other examples that had both an error and a response. I also added a response block showing that this call only returns an 'ok'.
