### ISSUE TITLE
Stateless Constructor

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4057]
So actually pretty excited about this idea, it fixes a large number of problems, basically the idea is that instead of doing any side effects in constructors, it becomes plain sync constructor that stores its params, the side effects of the constructor become part of the first call to the API, so for example the http api would do something like

```
function ensureSetup(name) { 
  // do setup stuff async
}

function HTTP(opts) { 
   this.opts = opts;
}

function get(id) { 
  return this.ensureSetup().then(function() {
    ajax();
  });
}
```

We can probably do the same thing as adapterFun to wrap all calls in the `ensureSetup`.

So first problem this solves is the inconsistency in how to handle errors in https://github.com/pouchdb/pouchdb/issues/4049, creating a http adapter while offline shouldnt be an error state in pouchdb, its what we are built for.

It also fixes the various issues we have had of how to deal with errors during construction and using pouchdb as a promise (https://github.com/pouchdb/pouchdb/issues/1940), ie the constructor always just works, errors are handled over the promise / callback api exposed by adapter methods.

It also makes long lived pouchdb objects far more reliable `pouchdb-server` has had to do basically this under the hood to open databases in order to ensure it can hold open a database for an extended period of time and I dont see the problem as unique to pouchdb-server

Its also backwards compatible and should change anything for 99% of end users, it will probably still justify a major version bump though

**Comment by nolanlawson** [comment]
I agree with every point here. Would be a lot simpler if errors didn't have to be caught in the constructor. Also we already deprecated the callback/promise response in the constructor (or at least, it's not documented anymore), so this would be a big win.

**Comment by calvinmetcalf** [comment]
making the pouchdb object no longer be a promise would be a really really big win as that was a big mistake on my part (though it's a super breaking change)

**Comment by daleharvey** [comment]
Closing as a dupe of original bug, dunno why I opened a new one for proposed fix, but yay on agreement

https://github.com/pouchdb/pouchdb/issues/4049
