### ISSUE TITLE
pouchdb doesn't seem to work with file-protocol and hash-urls

### ISSUE THREAD

**Issue by julmot** [pouchdb/pouchdb#4061]
I am using Firefox 41.0a2 (Developer Edition) and the latest version of pouchdb in a AngularJS application. My application runs fine in the file-protocol, even with hashbang-urls like `#/edit/someparam` (using inline routing `<script type="text/ng-template" ...`).

However I have a problem with pouchdb. I am inserting data to the database in the route `#/home`. When I click on a link on that page that redirects to `#/differentPath` and this route tries reading the data from the `#/home`-URL all is working great. But if I access the `#/differentPath`-route directly (F5 without clicking on a link) the database can't find any entry.

Are there any known issues with local file-protocol or hashbang-urls?

**Comment by daleharvey** [comment]
I am surprised it works at all with a file protocol you will need to serve from a web server for things to work though, the underlying technologies are broken in various ways served from the filesystem. You can start a simple server with 'python -m simpleHTTPServer' in the directory with your index.html

**Comment by julmot** [comment]
@daleharvey "PouchDB was created to help web developers build applications that work as well offline as they do online." I associate this with a local (offline) running application, therefore running under file-protocol. I'd like to build a local running app, without any server and later serving the files with e.g. NWJS

**Comment by julmot** [comment]
Could you please specifiy which technologies will break when using pouchdb from file-protocol? Maybe I can specificate only those to use, which are working.

**Comment by nolanlawson** [comment]
IndexedDB doesn't work at `file://`. IndexedDB is a core part of what makes PouchDB work.

However this doesn't mean you cannot use it with NW.js, Electron, Cordova, WinJS, or any of the various "local file" wrappers. All of those wrappers have workarounds to make IndexedDB functional. You just can't use `file://` yourself is all.

**Comment by daleharvey** [comment]
Yup, similiarly `ajax` doesnt work either, without either of those pouchdb doesnt do a whole lot, browsers dont consider running from the filesystem as part of the offline story, its either appcache / service workers or picking from the various wrappers @nolanlawson mentioned, apologies, I am not certain I agree either however it isnt something we can do a lot about.

**Comment by julmot** [comment]
@nolanlawson It seems to be not necessary to use a server (or workaround) in a NWJS application at all. In Chrome (and Chromium) the file-protocol works with pouchdb, therefore it will also work in a NWJS container (because of the engine Chromium). So what kind of workaround do you mean?

**Comment by daleharvey** [comment]
So browsers actually have changed their behaviour, indexeddb and pouchdb actually work in file urls now, however they behave differently, firefox seems to use the whole path (including any hashbang) as the `origin`, chrome just seems to use the file path

`ajax` however still will not work

**Comment by daleharvey** [comment]
@julmot As for NWJS etc, what the default chromium behaviour is doesnt particularly matter, they expose the same web standards (sometimes) but work on them to ensure that they work locally, sometimes they may run a server internally and sometimes not but that is designed to be hidden from the developer

**Comment by julmot** [comment]
@daleharvey It works for me with file-protocol in a NWJS application. You are right, in Firefox it doesn't when the hashbang changes. But because NWJS is using Chromium and Chromium handles it only by the file path, it works. However I understand that this is no issue of pouchdb, instead it's a scope issue from the browsers storage technology.
