### ISSUE TITLE
IndexedDB unsupported/prefixed on Windows 8.1 store apps

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4062]
Follow-up to https://github.com/pouchdb/pouchdb/issues/4051. Apparently there are lots of issues with IndexedDB in Windows.

> on 8.1 msIndexedDB is the property that supports indexeddb in windows javascript runtime.
> There a way documented here (If you are running into troubles with external pages ) https://msdn.microsoft.com/en-us/library/windows/apps/jj553412.aspx
> <meta name="ms-enable-external-database-usage" content="true"/>
> 
> The above works for windows, on windows phone 8.1 the story is different story, turns out WWAHost.exe completely ignores indexedDB unlike its windows 8.1 counterpart. http://blogs.windows.com/buildingapps/2014/07/02/writing-a-sqlite-wrapper-component-for-universal-windows-apps/
> So you have to use SQLite on windows phone.
> 
> And if you are using Windows or Windows Phone 8.1 C# webview its a different tale.
> 
> (I ended up using SQlite Plugin with cordova eventually there is also this https://github.com/MSOpenTech/cordova-plugin-indexedDB)

cc @darkyen

**Comment by nolanlawson** [comment]
Not sure we can fix this or if this is even relevant anymore.

**Comment by darkyen** [comment]
Its not relavent (::
