### ISSUE TITLE
How do you pre-populate a PouchDB database?

### ISSUE THREAD

**Issue by dilignt** [pouchdb/pouchdb#4063]
The documentation describes the `createFromLocation` for the SQLite Plugin which allows you to use a pre-populated sqlite database: http://pouchdb.com/api.html#create_database

How do you create a pre-populated pouchdb sqlite database file for using with this?  I don't want to use the pouchdb-load with a database dump file - I want to avoid having to load all the records as this takes too long and they have to be read to browser memory before this can occur.

The documentation clearly implies that this is possible, and I've done a lot of searching for this but I can't find out how to do it with a pouchdb sqlite database file.  In another thread I was told that the sqldown adapter for Pouchdb won't work because it creates a different sqlite format.  Is there another adapter that I can use, or is this actually not currently possible with pouchdb?

**Comment by nolanlawson** [comment]
I don't think there are any tutorials out there that describe how you can do it. I've also never done it. However, here's what I would do:

1. Write a web page that creates your PouchDB database, using the `{adapter: 'websql'}`.
2. Open the web page in Chrome
3. When it's done, go to where Chrome stores WebSQL data (for me on Mac, it's `~/Library/Application\ Support/Google/Chrome/Default/databases/http_mysite.com`)
4. Copy the sqlite database file into your app, then use `createFromLocation` to link to it.

In general, I would not advise this approach, because we have compatibility issues with the SQLite Plugin (it doesn't pass our tests anymore), and it is much slower than regular WebSQL/IndexedDB. So even though the `createFromLocation` may be faster than pouchdb-load/pouchdb-dump, your app will be slower and less reliable once the data is actually loaded. Plus you have to do all the work described above to create the .db file.

**Comment by daleharvey** [comment]
Cheers for the answer Nolan, closing this but if you have any more questions / discussion @dilignt feel free :)

**Comment by dilignt** [comment]
@nolanlawson thanks for the reply.  This approach is not practical for me - I've got dozens of collections and I can't identify the files against the tables in the chrome websql store - the filenames are just numbers so I can't find the right files.  Also, I need to be able to incorporate the procedure into a build process, and it's not feasible to do this manually every time I build.

The reason I'm using the SQLite plugin is to get around the browser websql size restrictions - I'd prefer not to use it but I don't know of another way.  Loading the data from json using db.bulkDocs is also too slow - it takes many seconds to load the json into the browser when the app starts, and then it takes a lot more time to populate pouchdb on the first invocation after installing the app, and this is only with 14mb of json, less than 10000 documents, and on quite a high end phone. 

I need to find a way that I can consistently build pre-populated databases when I build apps to get around this issue.  Maybe it's possible to build an adapter like sqldown to do this?

**Comment by nolanlawson** [comment]
@dilignt If you have a huge database and if you aren't using PouchDB<->CouchDB sync (which it sounds like you're not), then PouchDB may not be the right database for you. Have you considered using SQLite directly? Then your build process can just use SQLite itself.

As for your question of whether sqldown can be used - no, SQLdown uses a totally different schema model (based on LevelDOWN). To do what you want to do, you would need to implement the WebSQL API in Node.js using SQLite as a backend, and then open a pull request on PouchDB to allow it to talk to that API instead. It would be a huge undertaking (although not without value).

As for the issue of storage limits on iOS, it is an extremely annoying problem, and pretty much the only reason that the SQLite Plugin still exists. My long-term plan to solve it is to 1) wait for the WebKit team to fix IndexedDB, or 2) write a PouchDB adapter that uses Apple's broken IndexedDB. (Apple's IndexedDB in WKWebView has no storage limits.)

**Comment by nolanlawson** [comment]
Alternatively, you really can automate this process. You could use Selenium to open up a web page in Chrome or even PhantomJS and just copy the files over. Yes the files are a bit opaque, but I think it's possible to figure out which one is yours. :)

**Comment by dilignt** [comment]
@nolanlawson Actually I'm already a long way down the road of using PouchDB and it seems to be a lot more effort to replace it at this stage than to try and get PouchDB pre-populated.  I'm not using PouchDB<->CouchDB sync, because CouchDB is not quite right for our requirements - I ended up implementing our own PouchDB<->MongoDB sync on our CMS for our generic app schema which is a bit clunky but works quite well.  

For our smaller apps pre-population is less of an issue, but with larger schemas it is a real problem - fast start-up times are extremely desirable, and the delay loading all the json to the browser memory almost makes it seem like the app is broken.  We show a progress bar during all the db.bulkDocs so that is less critical but it still seems too long.  We also create a full-text index of all the app text for offline search, and this needs to be persisted in PouchDB as well and is usually by far the biggest collection.

The main problem with using chrome is that our app creates many different PouchDB collections and I can't figure out how to differentiate between them without actually reading the binary and recognising some of the document entries in amongst the binary data.  This is after running the whole app in the browser.  But as for your PhantomJS suggestion - maybe there is a way of invoking it for each single PouchDB collection automatically and with different environment each time that could separate out the websql databases, so it would be simple to copy it over - this seems worth investigating as it would be the simplest option.

Thanks for your suggestions - any others you can come up with will be gratefully received :)

**Comment by nolanlawson** [comment]
Yeah I know how important a quick start-up is; unfortunately we just haven't really spent enough effort on that. :(

**Comment by drm-code** [comment]
@nolanlawson I'm going to build an android app, it's going to be very simple app but I want it to work offline, with the data inside of it, it's going to content simple rows as database (max. 15 fields by document, some rating system, comments) do you think pouchdb will help me with that, I don't think that the app is going to manage a huge data I don't know we hope to start with 100 documents and maybe an increase of 10 or 15 documents monthly, regrads

**Comment by nolanlawson** [comment]
Yes, if you clean the cache, the database will go away. And yes, PouchDB can easily handle 15 rows of data, no sweat. :)

**Comment by farhadt0020** [comment]
I want to do this for my nwjs (node-webkit) app?
I've read your greate article https://pouchdb.com/2016/04/28/prebuilt-databases-with-pouchdb.html
But it dont have a solution for nwjs apps. 
Is there any way for load prebuild database in desktop apps.
Is it posible??
Thanks so much

**Comment by nolanlawson** [comment]
Yes, you can do this with https://github.com/nolanlawson/node-websql . You'd just have to figure out where to write the SQLite db file and how to put it there when the app starts. I admit I don't know enough about NW.js to be able to provide specific instructions, though.

**Comment by Thor-** [comment]
Hi

I use [node-websql](https://github.com/nolanlawson/node-websql) plugin to pre-build database for my mobile app as you described here [https://pouchdb.com/2016/04/28/prebuilt-databases-with-pouchdb.html](https://pouchdb.com/2016/04/28/prebuilt-databases-with-pouchdb.html). But index building still takes a lot of time. I know that pouch creates index for SQLite in separate files (file per index).

Is there any way to pre-build db indexes (SQLite)? Or may be to do some part of this task on server.

**Comment by nolanlawson** [comment]
Indexes are just separate database files with the prefix "mrview." You can
prebuild these and include them in your app on exactly the same way. You
just need to copy the extra DB files over.

-----
Nolan Lawson
http://nolanlawson.com
https://github.com/nolanlawson
