### ISSUE TITLE
Trigger 'change' events before resolving from `.put`

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb#4068]
When I run this test code

```js
db = new PouchDB('test')
db.changes({live: true, since: 'now'}).on('change', console.log.bind(console, 'change')); ''
db.put({_id: 'test'}).then(console.log.bind(console, 'put')); ''
```

I see the `put` log first, then the `change`. But I'd expect that the `change` event gets triggered before the Promise from the `.put` gets resolved. Any thoughts?

Context is that we want to add a `.hasLocalChanges()` method to https://github.com/hoodiehq/pouchdb-hoodie-store. And with the current behavior, I get this

```js
store = new Store('test')
store.add({id: 'test'}).then(function(obj) {
  store.hasLocalChanges(obj) // false, should be true.
})
```

`store.hasLocalChanges(obj)` is false above, because we listen to the changes feed and mark the object id as changed, but that code gets run after `store.add({id: 'test'})` resolves. See https://github.com/hoodiehq/pouchdb-hoodie-store/pull/21/files#r35374887

**Comment by nolanlawson** [comment]
Hm that's a tough one. We never specified the exact order of events, but I can see how that's a problem in your case.

I think a workaround would be to do:

```js
store = new Store('test')
store.add({id: 'test'}).then(function(obj) {
  setTimeout(function () {
    store.hasLocalChanges(obj) // should be true now?
  })
})
```

**Comment by gr2m** [comment]
Thanks @nolanlawson! We tried a few thinks to work around it from our side, and eventually built in the triggering of the events right into the `store.*` methods, and removed listening to `db.changes()` altogether. Here's our change for that: https://github.com/hoodiehq/pouchdb-hoodie-api/commit/87ec32c39adae0a49c9ced6cf13d9843739d334d

It's not ideal, but it works for us. If PouchDB would ever enforce the order of triggering events before the methods resolve, I'd happily change it back to our earlier solution, I think it's much more elegant and robust.

**Comment by daleharvey** [comment]
So yeh apologies, but this isnt particularly feasible with our current setup, changes have been designed to be async notifications, dealing with that above pouch is the best way imo
