### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4071]
Now that mapreduce is folded into pouchdb core, one of the things I really miss is the confidence that code coverage is at 100%.

I think we can get there, but it will take some discipline to go through the codebase, add `istanbul ignore` where it makes sense, extract out browser-only code (since we can't test coverage in the browser using istanbul), and of course add tests as well.

I'm willing to do the work to try to get us up to 100%, or at least as close as possible.

**Comment by nickcolley** [comment]
What percentage are we at the moment?

**Comment by nolanlawson** [comment]
BTW @daleharvey where is code coverage reported to? Can't seem to find it.

**Comment by daleharvey** [comment]
http://pouchdb.cloudant.com/coverage_results + http://pouchdb.cloudant.com/performance_results

**Comment by nolanlawson** [comment]
Hm, it doesn't seem to be storing the actual coverage number anywhere. I wish there was some way we could make Travis surface that information for every pull request.

**Comment by nickcolley** [comment]
Could try out something like https://coveralls.io/ which gives those kinds of stats.

**Comment by daleharvey** [comment]
@nolanlawson What do you do to figure out what exact lines are not being covered? I would like to get this to 100% so its easier to not regress it, even if we add some ignores for where there is browser specific stuff we can remove it when we start testing the browser implementation (and I would prefer to add ignores than tests that only exist for coverage purposes)

**Comment by daleharvey** [comment]
Also filed a bug to see why we dont see the source files in coveralls - https://github.com/lemurheavy/coveralls-public/issues/633

**Comment by daleharvey** [comment]
And we are at 100% - https://github.com/pouchdb/pouchdb/commit/79785ee234b77af36137969b73f5d80dd7f0b0e4
