### ISSUE TITLE
Feature: Multi server failover.

### ISSUE THREAD

**Issue by tohagan** [pouchdb/pouchdb#4090]
I envisage that many software teams will want to support having multiple CouchDb servers that mutually replicate each other and have PouchDb clients failover to the another server when they fail to connect. This is especially useful for "live" replication. One common scenario for this is Pouch <=> Intranet  <=> Cloud where we'd prefer to connect to a local intranet but if that is unreachable (e.g. we're outside Intranet) we'd like to auto connect to and sync with the Cloud replica server often via a different network interface (WIFI -> 3G).

**Issues**: 

- What happens when servers fail to replicate to each other? 

Probably needs a reminder in the docs that this server topology can increase the probability of generating CouchDb conflicts and that either (1) another service is required to resolve them or (2) they avoid updates (only perform insert/delete delta docs and use views to compute updates)

- "What connection sequence should be applied to the endpoint URLs?"  

Sometimes we just want to attempt to connect to the 1st available in a sequence and then fail permanently (e.g. for non-live replication where user initiates syncing or it runs on app startup). Other times we want to try to connect to servers in round robin or perhaps still allow permanent failure to occur after a number of recent attempts (count is reset when we succeed).

**Comment by nickcolley** [comment]
Doesn't CouchDB2.0 have support for clustered replication?

http://docs.couchdb.org/docs/couchdb/en/latest/cluster/index.html

>As of 2.0 CouchDB now have two modes of operations:
- Standalone
- Cluster

**Comment by nolanlawson** [comment]
This is definitely the future envisaged for CouchDB 2.x (i.e. the BigCouch merge). However I'm not sure I share the same vision for PouchDB Server.

I actually like that PouchDB Server is just a straightforward port of CouchDB 1.x, with all its single-node simplicity. It's actually not that hard to build a failover or sharding system yourself ([CouchDB Lounge](http://tilgovi.github.io/couchdb-lounge/) is a testament to that). And that cool thing is that, since PouchDB Server basically just mimics CouchDB 1.x in every way, there's nothing to stop you from using Lounge or building a similar thing. You could even have CouchDBs and PouchDB Servers freely mixed in a cluster.

That said, I don't know how @marten-de-vries or @daleharvey feel about that. I might be alone in believing that PouchDB Server should remain a simple CouchDB 1.x port.

**Comment by tohagan** [comment]
No this idea is not for clustered CouchDb 2.x nor for PouchDb server.  This is not failover at the server end which is what we think of traditionally for the "failover" term - rather it's at the client end where the client decides to switch servers. The reason is that the servers reside on entirely separate infrastructure (Intranet and Cloud) so there's no proxy or DNS to perform the failover.

I think I may be able to implement it using the events that PouchDb emits but it get messy as when I get a disconnect event I need to stop the live update and check that network is still UP and then attempt to connect to a different server. On Androids I can also examine which network interface type is UP (WIFI or 3G) and for some customers only use Intranet server if I'm on WIFI (some customers may use 3G + VPN to connect to their Intranet so this is not a perfect rule).

**Comment by daleharvey** [comment]
So its very unlikely we would be adding this to core pouchdb in the short term, however it mostly definitely should be possible use pouchdb in this way. If theres any features needed inside pouchdb to make it possible then please call them out, will take a look at the proposal and see if anything sticks out

**Comment by tohagan** [comment]
Yes I tend to agree that it's a rather specialised requirement and so perhaps does not really belong in core but might be a nice plugin if the right event hooks are in place. I'm working on a project that won't need it just yet but I suspect will in the longer term when we will look at adding the Intranet layer option. If I get the go ahead for that I'd like to contribute some plugin code and will run the ideas past you first.

Thanks as always for your excellent work!

**Comment by daleharvey** [comment]
I believe the correct hooks are in place, there are some issues with these currently (https://github.com/pouchdb/pouchdb/issues/4049 + https://github.com/pouchdb/pouchdb/issues/3852) However they are being worked on and assuming these are working correctly I believe you have enough information to determine whether and when you need to failover (basically look for `paused(err)` events)

If you need anything from pouchdb to get the plugin working feel free to file, I am gonna be working on the mentioned bugs shortly so they should be fixed soon.

Cheers
