### ISSUE TITLE
Support retry:true for non live replications

### ISSUE THREAD

**Issue by hrishiballal** [pouchdb/pouchdb#4092]
When I try to sync a large database with a Cloudant couchdb database, I am getting a 500 database encountered a unknown error. 

I tried to dig around a bit as to why it happens and the only thing I have currently is if a xhr call takes more than 10 seconds (9.97 to be precise), pouchdb times out. I did not take a screenshot (and currently my network is fine) but next time I get a 500 error, I will post the screen shot. Is there a timeout limit to connections during sync / replicate?

**Comment by nolanlawson** [comment]
Yep, the default is 10000 ms. You can increase the timeout using the `ajax.timeout` parameter: http://pouchdb.com/api.html#create_database

Also if you are using `retry` replication, it should automatically restart. Do you know if that's happening?

**Comment by hrishiballal** [comment]
Yes but the issue is that I dont want the "live" to be true as well. I want to replicate and keep on trying to replicate without the whole database being live. 
```javascript 
 opts = {
            live: false,
            retry: true
          };
```
The above code will not work, am I correct?

**Comment by hrishiballal** [comment]
Here is my use case: 
I have multiple couchdb databases. If the user is working Document 1 then Database 1 is synced. The user could decide to work on Document 2 (and database2 is synced) however, since they are not working on Document 1, there is no point in keeping the syncs alive for Database 1. Currently there is no way to "turn off" connections between couch and pouch.

**Comment by nolanlawson** [comment]
> The above code will not work, am I correct? 

`retry` is ignored if `live` is false, yes.

> in live sync environment how long is the connection kept "live", once the browser is closed? 

Replication stops as soon as the tab is closed.

It sounds like you do indeed want to be using non-live replication, but I think the issue is that you're not also handling errors yourself. In PouchDB currently there is no way to do `live:false` but `retry:true`.

A simple non-live retry mechanism would be something like this:

```js
function keepTryingToReplicate() {
  var backoff = 2000;
  function tryToReplicate() {
    return localDB.replicate.to(remoteDB).then(function () {
      backoff = 2000; // sucess, reset the backoff
    }).catch(function (err) {
      console.log('replication failed, retrying...', err);
      var oldBackoff = backoff;
      backoff *= 2;
      return new Promise(function (resolve) {
        setTimeout(resolve, oldBackoff);
      }).then(tryToReplicate);
    });
  }
  return tryToReplicate(); 
}
```

**Comment by simonaberry** [comment]
I think this is also explains  my issue #4040  

I will try the 'keepTryingToReplicate' route - thanks @nolanlawson
