### ISSUE TITLE
Eventemitter leak in changes() listener in replication (yes, again)

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4093]
Apparently we are still able to get memory leaks during replication if the server throws a 503 (https://github.com/nolanlawson/local-npm/issues/39). I have no idea how that's possible, though, since I thought we fixed and tested that in d8902a18. Maybe it doesn't work if you neglect to `cancel()` after an error?

**Comment by daleharvey** [comment]
So this should hopefully be fixed in https://github.com/pouchdb/pouchdb/commit/691df0d6b7fac08d8a281f169c2381f6424510d6
