### ISSUE TITLE
Remove undocumented/untested SSE code

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4103]
This code is not being used right now and is undocumented. Can we just get rid of it? cc @calvinmetcalf 

In the meantime, there's been lots of progress in things like replication over streams and over sockets (Thali project, pouchdb-replication-stream, express-pouchdb-replication-stream, pouchdb-dump, pouchdb-load, socket-pouch), so I think the need for SSE might have diminished somewhat.

Happy to keep https://github.com/pouchdb/pouchdb/issues/2823 open while we work on re-integrating it, though.

**Comment by daleharvey** [comment]
https://github.com/pouchdb/pouchdb/commit/c36333a378aed91ee05813c486669a5b6c66a756
