### ISSUE TITLE
Show code coverage numbers in Github PRs

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4107]
So right now we are running Istanbul coverage checks, but it's really hard to surface them because you need to dig deep into the Travis UI to find them. I would prefer to have the coverage numbers front-and-center.

I [asked around on Twitter](https://twitter.com/nolanlawson/status/627829374809542656), and apparently the best resource is indeed Coveralls (thx @nickcolley!) combined with [istanbul-coveralls](https://github.com/shinnn/istanbul-coveralls). Unfortunately Coveralls is down today for maintenance, but it seems really easy to set up; I've got some sample repos here:

* https://github.com/noopkat/avrgirl-stk500v2/blob/master/package.json
* https://github.com/hoodiehq/pouchdb-hoodie-sync/blob/master/package.json

After my recent PRs, our code coverage should be somewhere around 95% or 96%. Not amazing, but not bad either! I hope to make it even better by adding [fakeIndexedDB](https://github.com/dumbmatter/fakeIndexedDB) tests in Node so that we can actually cover our IndexedDB adapter.

(Follow-up to https://github.com/pouchdb/pouchdb/issues/4071)

**Comment by daleharvey** [comment]
I also followed up to add the badge to the repo, this is awesome :)

**Comment by nickcolley** [comment]
@daleharvey if you remove the space between them they'll line up. (lil nit)

**Comment by nolanlawson** [comment]
+1 for @nickcolley's suggestion. Looks great though!

**Comment by daleharvey** [comment]
Yeh ill sneak that change into the release blog post

**Comment by nickcolley** [comment]
Woop it's working and green :tada:

**Comment by nickcolley** [comment]
Just noticed https://coveralls.io/builds/3206189/source?filename=..%2Flib%2Fsetup.js the files are not accessible, wonder if we need to config that?

**Comment by nolanlawson** [comment]
@nickcolley Not sure what the fix is: https://github.com/lemurheavy/coveralls-public/issues/263
