### ISSUE TITLE
attachment tests failing against couchdb-master

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#4113]
Pulling this issue out of #4023 as I'm not sure it's related.

Since https://travis-ci.org/pouchdb/pouchdb/jobs/72304282, attachment tests are failing against couchdb-master. In my local environment, https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.attachments.js#L961 periodically fails when CouchDB returns a 200 response with an incomplete response body, e.g.

    {
        "results":[

Giving the timing, it seems likely that this is related to https://github.com/apache/couchdb-chttpd/commit/3866725ee99c6d89aff91ecb70a3b3cbbabaed8c (cc @kocolosk).

**Comment by willholley** [comment]
in case it helps, https://gist.github.com/willholley/5840e48f3ec4de620b10 is a HAR demonstrating the test failure (see the second call to _changes).

**Comment by willholley** [comment]
the problem seems to occur when feed=longpoll

**Comment by willholley** [comment]
opened https://issues.apache.org/jira/browse/COUCHDB-2767

**Comment by willholley** [comment]
COUCHDB-2767 is fixed and the attachment tests now pass for me locally.

**Comment by daleharvey** [comment]
Awesome, thanks for following this up
