### ISSUE TITLE
view compaction feature

### ISSUE THREAD

**Issue by martinsbalodis** [pouchdb/pouchdb#4118]
Currently pouchdb supports data compaction and view cleanup but there isn't a way to compact views. 

https://wiki.apache.org/couchdb/Compaction#View_compaction

**Comment by nolanlawson** [comment]
View compaction actually wouldn't make much sense in CouchDB, because we use an auxiliary PouchDB database which is already auto-compacted. There's no way currently to make them smaller, unfortunately.
