### ISSUE TITLE
Need to be able to cleanly instantiate more than one instance of PouchDB...

### ISSUE THREAD

**Issue by the-t-in-rtf** [pouchdb/pouchdb#4124]
There are a lot of use cases where you only want one instance of PouchDB at a time.  However, for test cases, the pattern of instantiating PouchDB when it is required is a problem.  We use PouchDB (and express-pouchdb) to mock CouchDB in our tests.  Our test runner expects to be able to spin up a clean instance of Pouch for each of a series of test cases.

Because PouchDB is instantiated when you `require` it, you can only ever get access to a single PouchDB instance.  Every test run beyond the first is working with the same instance.

This is a particular problem if any test runs perform write operations (add, update, delete).  Even something as simple as pulling in your test data is a problem. Depending on how you add the test data (we use `_bulk_docs`), you can easily end up with duplicates for any record that does not have an explicit `_id` value.

What I'm proposing is to split up require and instantiate throughout the codebase.  We are willing to contribute to a pull request to accomplish this, but only if there is a good chance it will be accepted.  Please review and let us know what you think.

**Comment by daleharvey** [comment]
Hey, cheers for the report, however I think there is some confusion here. PouchDB isnt instantiated as a singleton via require, its instantiated via its constructor. 

```
var PouchDB = require('pouchdb');

var db1 = new PouchDB('db1');
var db2 = new PouchDB('db2');
```

Is how you would start multiple databases, we do this a lot in our own tests (https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.replication.js#L100)

Is there something I am missing?

**Comment by the-t-in-rtf** [comment]
@daleharvey, individual databases are instantiated in that manner, but you only ever have one instance of PouchDB itself available.  The second test case that requires PouchDB will receive the existing instance, complete with any databases you have already created.

**Comment by daleharvey** [comment]
The PouchDB object doesnt have databases, it is used to construct them, if you create a database, add data to it, then create another database with the same name it will have that same data because the data is persisted, the constructor is create + open, it wont create a fresh instance if there is existing data.

You will need to wipe the databases between your test runs, we do that with https://github.com/pouchdb/pouchdb/blob/master/tests/integration/utils.js#L155 + https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.basics.js#L10. Of you can use the memory adapter.

Otherwise could you give an example of what you mean, still a little confused

**Comment by calvinmetcalf** [comment]
You can delete files from the require cache if you need to cleanly require
it,  delete required. cache['filepath.js']

**Comment by the-t-in-rtf** [comment]
Your statement that "you will need to wipe the databases between your test runs" confirms my point.  I have looked into the require cache solution, manually scrubbing the content between runs seems slightly less odious at least to me.

**Comment by the-t-in-rtf** [comment]
Just to clarify my last point, I mean that if PouchDB were just a means of constructing instances, I would expect to be able create as many databases with the same name as I like at a given time, and have them be distinct from one another.  This is obviously not the case.

**Comment by calvinmetcalf** [comment]
The pouchdb data lives on the file system the reason you can't create
instances with the same name is because the refer to the same data on the
file system

**Comment by the-t-in-rtf** [comment]
@calvinmetcalf, that baffles me, as this happens even when using in memory databases.  It also appears to directly contradict @daleharvey's assertion that PouchDB only creates databases.

**Comment by calvinmetcalf** [comment]
Ah, memdown  (the memory database) does do what you are taking about, and
no way to clear it judging from the code, may open a pull

**Comment by daleharvey** [comment]
@the-t-in-rtf the constructor will create + open existing databases. However I am surprised that 

```
var PouchDB = require('./lib').defaults({
  db: require('memdown')
});

var db = new PouchDB('db1');
var db2 = new PouchDB('db1');

db.post({some: 'data'}).then(function() {
  return db2.post({other: 'datas'});
}).then(function() {
  return db.allDocs();
}).then(function(res) {
  console.log(res);
  return db2.allDocs();
}).then(function(res) {
  console.log(res);
});
```

Creates a single store, looks like memdown has a global cache for this stuff - https://github.com/Level/memdown/blob/master/memdown.js#L7

However even if the instances did have seperate data, it still wouldnt work as expected against express-pouchdb, local pouchdb databases can hold open an instance but http only sees seperate requests, it either needs to cache the open databases (and persist the data) or create a new instance every request and no data would ever persist.

I think you would either need to spawn new servers per test (https://github.com/gr2m/spawn-pouchdb-server) or send a delete between them, those seem like the best options to me?

**Comment by the-t-in-rtf** [comment]
Thanks for helping track this down, @daleharvey and @calvinmetcalf.  I will close this one out and open an issue with memdown.

**Comment by the-t-in-rtf** [comment]
Just to comment, I'm already spawning new servers with their own temporary directories and settings, that doesn't help.  Deleting between tests seems to be the best option for now.

**Comment by the-t-in-rtf** [comment]
@daleharvey, it looks like the global cache and this specific behavior are intentional:
https://github.com/Level/memdown/pull/23

**Comment by calvinmetcalf** [comment]
see Level/memdown#39

**Comment by nolanlawson** [comment]
Yeah I implemented that because it brought MemDOWN closer to the leveldown "spec" and made `destroy()` finally work. (Before, we were just ignoring `destroy()` for MemDOWN because it wasn't implemented.)
