### ISSUE TITLE
Calling destroy() twice on the same database causes problems in PhantomJS

### ISSUE THREAD

**Issue by bedney** [pouchdb/pouchdb#4135]
This looks like a bug that was introduced in PouchDB 3.6.X and higher.

If I call destroy() twice in a row on the same database, on browsers it succeeds, but in PhantomJS 2.0 it fails. I think PhantomJS 2.0 still uses an old enough version of Webkit such that WebSQL is still being used.

You might think it's strange that I'm calling destroy() twice, but this was in a set of automated tests where I had a test for destroying the database as part of a whole suite of tests. In addition to the destroy() call there, I had an 'after' function, executed after all tests in the suite completed, that was also destroy()ing the test database as part of a cleanup process.

Since there were occasions when the destroy() test itself wasn't configured to be executed, I needed the one in the after() function to make sure to clean things up.

I've worked around this using a flag for now, so this bug isn't high priority.

**Comment by daleharvey** [comment]
hrm this is very strange, since it sounds like your test setup is fairly similiar to ours and we test in phantomjs too, will take a look but if you had a standalone code snippet that failed it would be super helpful

**Comment by nolanlawson** [comment]
@bedney When you say "twice in a row," do you mean:

```js
db.destroy();
db.destroy();
```

or

```js
db.destroy().then(function () {
  db.destroy();
});
```

?

Also do you see this in Safari by any chance? Safari, like PhantomJS, uses WebSQL, but the WebSQL implementation has some small differences.

**Comment by daleharvey** [comment]
@bedney We had another report of a similiar issue. Is there any chance you are reusing database instances after calling `destroy()` on them? ie something like 

```
    var db = new PouchDB('testing');
    db.post({a: 'doc'}, function(err, doc) {
      return db.destroy();
    }).then(function() { 
      return db.post({new: 'doc'});
```

or as @nolanlawson said 

```
db.destroy();
db.destroy();
```

If so then that really shouldnt work, every time you `db.destroy` and instance you need to create a `new PouchDB()` instance to start using it again (even if you are going to delete it straight away), sorry for not being clearer, looking into a patch that should make that more obvious

**Comment by bedney** [comment]
@daleharvey - Ah yes... that very well may be it. Unfortunately, I've been locked in 'demo land' for the last few days, rushing to get demos ready, so I haven't had a chance to look at this again... I'll do it today or tomorrow.

Thanks! And thanks to you and @nolanlawson and other contributors for the awesomeness that is PouchDB!

**Comment by daleharvey** [comment]
Ah cool, I will close this as a dupe of https://github.com/pouchdb/pouchdb/issues/4134 then, its not a thing we have ever purposefully supported although surprised to see that has 'worked' in previous versions. We can make it clearer that the db reference is stale

**Comment by bedney** [comment]
FYI, this was indeed the problem (trying to call `.destroy` more than once on the same handle). Thanks Dale!
