### ISSUE TITLE
Subtle migration bug for updated non-winning seqs

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4139]
So it turned out that when we fixed #3646, we actually didn't do the migration correctly, because I have a failing test that shows it's possible to reproduce the error in older versions of PouchDB (~3.2.0) and not have it fixed when you upgrade to the latest (91c64139fce8c0412840328b6b7a32c288605fb4).

Personally I don't think this is a big enough problem to justify writing the migration (lots of extra code, needs to basically read every document from the database and fix it), and the bug itself only comes up in very very unusual cases of multiple conflicts. Plus nobody has ever reported it before; I found it randomly while playing around with tests.

Still, I am documenting it here for posterity.

**Comment by daleharvey** [comment]
And documented for posterity, closing out, cheers
