### ISSUE TITLE
coveralls coverage reporting failing: XXX is not an object

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4142]
Our coverage reporting fails fairly regularly with this error, see https://travis-ci.org/pouchdb/pouchdb/jobs/74838103. Sounds like a bug in istanbul reporter

**Comment by nolanlawson** [comment]
yeah, it is a bug in coveralls as far as I can tell (not istanbul). Maybe best to just ignore it and wait for a fix from coveralls

**Comment by daleharvey** [comment]
Tracking it @ https://github.com/nickmerwin/node-coveralls/issues/80

**Comment by nolanlawson** [comment]
So since we upgraded to Travis containers, the new error is:

    FATAL ERROR: JS Allocation failed - process out of memory
    Aborted (core dumped)

My hunch is that Istanbul just uses up too much memory. Sadly we may need to switch back to not using containers.

**Comment by nolanlawson** [comment]
Supposedly Travis containers have more memory than the old non-containers, so surprised this is happening:

> The new containers have 2 dedicated cores and 4GB of memory, vs 1.5 cores and 3GB on our legacy infrastructure. CPU resources are now guaranteed, which means less impact from ‘noisy neighbors’ on the same host machine and more consistent build times throughout the day.

**Comment by daleharvey** [comment]
Ugh going to have to look into patching this myself, now we are at 100% would like PR's to start reporting this so we dont regress

**Comment by daleharvey** [comment]
So havent seen this in a long time
