### ISSUE TITLE
Move pouchdb-upsert into pouchdb itself

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4144]
There's no reason to keep it as a separate module anymore, now that mapreduce is no longer a separate module, and it's causing problems because it's trying to both 1) be a good plugin for average users, and 2) be a good component inside of PouchDB itself. E.g. see discussion in https://github.com/pouchdb/upsert/issues/7.

I would like to just copy-paste `upsert.js` into PouchDB's core code somewhere and maybe remove stuff we don't need (e.g. promise vs callback API - just support one or the other, whichever one is being used in PouchDB itself).

This may be a good first bug.

**Comment by nolanlawson** [comment]
95b1771348f7cbdbe6e665b6891af8599f00be18

**Comment by nolanlawson** [comment]
For everyone wondering what this issue means, it *does not mean that pouchdb-upsert is bundled with PouchDB itself*. That's never gonna happen, due to our desire to keep the API surface small. Please use the [pouchdb-upsert](https://github.com/pouchdb/pouchdb-upsert) plugin.

**Comment by tohagan** [comment]
Since the `upsert()` function is already included and used in PouchDB code under `lib/deps/upsert.js` and wiring up the plugin is ugly (`require()` is fine in NodeJS but not much use in Angular) can't we just add it as `PouchDb.prototype.upsert()`.  The fact that you needed it inside PouchDb is surely evidence enough that everyone else needs it too! 

I think we're talking 1-2 lines of code to integrate it and we move some unit tests and docs into core and a whole load of API coding pain goes away :).

**Comment by nolanlawson** [comment]
Even just exposing the "extras" API (e.g. ajax, checkpointer), has already caused some headaches for us; it made it difficult in the last release to juggle the new Rollup build system. @daleharvey and I are already considering removing it.

So yeah, I don't think the fact that it's in PouchDB itself is a strong justification for exposing it. It increases the overall API surface, which increases the stuff we have to maintain and makes it harder for new users to grok the codebase. Plugins aren't seamless, but it's the best we have right now.

As for `require()` in Angular/Ionic, Ionic 2 is moving to a system more like Angular 2's (i.e. with npm, TypeScript, transpilers, etc.), meaning it will be very easy to `require()` Node-style.

**Comment by tohagan** [comment]
Well I guess I just hack the plugin code into an Angular 1.x service of some kind.
