### ISSUE TITLE
Request support for new CSRF feature (COUCHDB-2762) added to CouchDb 2.0

### ISSUE THREAD

**Issue by tohagan** [pouchdb/pouchdb#4147]
As you're probably aware, CouchDb 2.0 [just announced](https://issues.apache.org/jira/browse/COUCHDB-2762) support for CSRF Protection. Would be nice to be able to enable this as a PouchDb feature. In my web wanderings I also notice this issue for the Drupal PouchDb module:
  - https://www.drupal.org/node/2470691

CSRF protection is a seriously needed security feature for Couch and I think it should be added to the roadmap for Couch 1.x as well so makes sense if Pouch/Couch both plan to support it.

I'm also unsure if you support CouchDB 2.0 yet (perhaps you might clarify this on the Guide Introduction?).  Thanks guys.

**Comment by tohagan** [comment]
Hmmm ... Maybe it's already in Couch 1.x  ... Just found this 

https://people.apache.org/~dch/snapshots/couchdb/20140715/new-docs-build/html/cve/2010-2234.html

**Comment by tohagan** [comment]
Nope ... https://issues.apache.org/jira/browse/COUCHDB-2762 ... This is BAD!

**Comment by tohagan** [comment]
And looks like it won't apply for READ operations: https://github.com/apache/couchdb-couch/pull/84

**Comment by tohagan** [comment]
Sorry for my ramblings ... Just trying to get my head around security best practice for using Pouch/Couch.  

I *think* the best option is to use Cookie Auth (not include user/password in URL) by using pouchdb-authentication. This should be [ok for mobile apps that use Pouch inside a webview](http://security.stackexchange.com/questions/90994/are-phone-apps-vulnerable-to-xss-or-csrf-webview-phonegap-chrometab)  and hence don't share cookies with other browsers.  For desktop web apps using Couch 1.x however, CSRF is still a major issue that IMHO still needs to be resolved.

**Comment by kxepal** [comment]
@tohagan backport to 1.x isn't a problem, should be easy to.

**Comment by garrensmith** [comment]
Since we just added support for the new CSRF work in Fauxton, I'm happy to take a stab at getting this working in PouchDB.

**Comment by daleharvey** [comment]
So I am not certain there is anything we need to do inside pouchdb? if you are using cookie authentication against couchdb shouldnt everything 'just work'?

**Comment by garrensmith** [comment]
After speaking to @daleharvey on IRC. I agree this isn't an issue for PouchDB right now. If a user logins in using basic auth then they cannot use the CSRF flag anyway. If they use [pouchdb-authentication](https://github.com/nolanlawson/pouchdb-authentication) then the CSRF is required for extra security. So the CSRF works need to go there.

**Comment by tohagan** [comment]
@daleharvey Normally relies on the client recording the xsrf header sent with initial login and resending it for all future requests in the same login session (same cookie) hence it needs specific client end support. This header can be in addition to the session cookie. Actually [there are many ways to implement it](http://stackoverflow.com/questions/20504846/why-is-it-common-to-put-csrf-prevention-tokens-in-cookies) and I'm not sure which flavour Couch 2.0 has implemented. 

My main concern is that several of the methods rely on having a Same Origin Policy on the server. However for PouchDb to work with mobile apps I need to remove this policy (CORS with Origin: *). If I then permit web browsers access to the same server *I think* I've got a CSRF security problem.

Finding documentation on the status of this in CouchDb 1.x has been confusing to the say the least. There was a [security bulletin](https://people.apache.org/~dch/snapshots/couchdb/20140715/new-docs-build/html/cve/2010-2234.html) noting the problem in an early version of CouchDb and claiming it as "fixed". But what exactly they fixed is unclear given that we are now fixing it again in Couch 2.0 .

**Comment by tohagan** [comment]
@garrensmith Yes that makes sense.

**Comment by kxepal** [comment]
@tohagn CouchDB 1.x fixed CSRF issue partially using [referer check](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#Checking_The_Referer_Header) on the POST requests only for specific endpoints.

The new implementation for 2.0 used [double submit cookie](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#Double_Submit_Cookies) method and expand protector on all endpoints and also on PUT/DELETE requests.

**Comment by tohagan** [comment]
@kxepal thanks that clarifies things. Found new [http Section 3.3.4](http://docs.couchdb.org/en/latest/config/http.html) that describes the new 2.0 feature and that will need a client end support mod to implement double submit cookie method for [pouchdb-authentication](https://github.com/nolanlawson/pouchdb-authentication)

**Comment by tohagan** [comment]
On closer reading of [http Section 3.3.4](http://docs.couchdb.org/en/latest/config/http.html), I now think this *does* belong in PouchDb core as an option to be enabled because it's managing a different cookie (and matching header) that is independent from the session cookie (though perhaps stored on Couch as part of the session state? @kxepal do you know this?).  

Arguably it could be a separate plugin but I think it should be encouraged to be used in the future and hopefully it will be implemented in CouchDb 1.x as well. Probably also requires an additional header to be added to the CouchDb CORS configuration and so tools like [add-cors-to-couchdb](https://github.com/pouchdb/add-cors-to-couchdb) might need a patch.

**Comment by kxepal** [comment]
@tohagan Correct. There is special CouchDB-CSRF cookie that holds the token and it's completely separate from auth cookie. You can protect anonymous users with CSRF as well as if come other auth provider is used. But that token isn't stored anywhere: the implementation follows REST principles (state over request) and while client could provide well signed and not expired token CouchDB will accept it - all the same as for auth cookie.

**Comment by kxepal** [comment]
Need to note, that it's possible to make CSRF protection mandatory, so if PouchDB will implement it support in plugin, that plugin may eventually became required one, not optional.

**Comment by kxepal** [comment]
@tohagan https://github.com/apache/couchdb/pull/334

**Comment by tohagan** [comment]
@kxepal  Excellent!! Thanks.

**Comment by garrensmith** [comment]
I've been thinking about this today and playing around with some ideas. As @tohagan said, this header isn't related to authentication. Its a separate cookie designed to protect against CSRF. I actually think it would be handy to support this directly in PouchDB. This would then add an extra layer of protection for anyone using PouchDB.

**Comment by tohagan** [comment]
"so if PouchDB will implement it support in some plugin, that plugin may eventually become required one, not optional."  .. So perhaps a reasonable strategy might be to implement a plugin initially with the option to merge it into core once it's known to be stable and when latest Couch 1.x and 2.x both support CSRF.  

IMHO, I think it should be an option (for performance tuning ) that is turned off by default (for backward compatibility) but *encouraged to be used*.  You could do this in a section on "Security Best Practice" in the Guide that has a simple rule-like outline structure: "when this case ... do that" ... so that both beginners and advanced users get it consistently right via a check list.

**Comment by kxepal** [comment]
@tohagan It shouldn't hurt performance a lot since it's all about receive one additional cookie and send one additional header. No any complex logic on client is required.

**Comment by glynnbird** [comment]
As recent changes to the Cloudant Dashboard now set a CRSF cookie, users who log into the Dashboard and then try to use PouchDB to interact with Cloudant are seeing 403 errors with a `CSRF Cookie/Header mismatch` error. This is because the cookie set by the Dashboard is being passed back to the server by PouchDB!

**Comment by rnewson** [comment]
The reason for the separate header is so you can gain CSRF protection before authenticating. Happy to discuss any and all details of integrating the new CSRF protection into pouchdb.

**Comment by garrensmith** [comment]
[Here](https://github.com/garrensmith/pouchdb/tree/csrf) is the initial work I've done on this. I won't be able to do any more this week. Its still very rough, the code needs some serious love. At this stage I was just trying to get it working. The Node.js driver works and I think it should work for the web but I couldn't get the tests to work so I couldn't prove it.

**Comment by daleharvey** [comment]
Adding https://issues.apache.org/jira/browse/COUCHDB-2797 for reference, as @garrensmith has pointed out in the ^ PR this cant work for CORs. Its fairly likely that pouchdb wont need to change for CSRF to be added to Couch

**Comment by daleharvey** [comment]
So CouchDB has switched to only do CSRF validation on form submission (https://issues.apache.org/jira/browse/COUCHDB-2797), pouchdb only deals with application/json so this is no longer needed, Cheers

**Comment by rnewson** [comment]
:beer:
