### ISSUE TITLE
API to check database usage/size

### ISSUE THREAD

**Issue by joshongit** [pouchdb/pouchdb#4148]
Is there any pre defined API to check used size of the database? (Irrespective of adapters)  It will be useful to restrict the storage or make call of compact() or viewCleanup()

If already raised by someone please ignore it.

**Comment by daleharvey** [comment]
It has been raised sadly however it is not possible, inside leveldb we have access to the filesystem and could implement this, however indexeddb and websql have no such capabilities, we could track some data ourselves but it would be unreliable. 

There is work being done on this for the web, http://www.w3.org/TR/quota-api/ so hopefully soon you will be able to check quota size from that side soon.

Apologies

**Comment by yaronyg** [comment]
For whatever it's worth (and it a'int much) we will have to implement something like this for the Thali project. But because we only run in Node.js we only need this to work with LevelDB. So our solution won't be generic. :(

**Comment by joshongit** [comment]
Thanks for the reply @daleharvey   So the only option is wait for quota-api :)

**Comment by nolanlawson** [comment]
There is also the pouchdb-size project, but it only works for leveldown-based PouchDBs (i.e. Node.js): https://github.com/marten-de-vries/pouchdb-size
