### ISSUE TITLE
Memory and LocalStorage adapters doesn't work on IE

### ISSUE THREAD

**Issue by rafaelsteil** [pouchdb/pouchdb#4150]
The memory and localstorage adapters doesn't work on IE (tried on IE9) due to its lack of the "name" property in functions. It is possible to workaround it using the followig code:

```diff
--- a/pouchdb.localstorage.original.js
+++ b/pouchdb.localstorage.js
@@ -152,6 +152,10 @@ function LevelPouch(opts, callback) {
     ));
   }

+  if (typeof leveldown.name == "undefined") {
+    leveldown.name = leveldown.toString().match(/^function\s*([^\s(]+)/)[1];
+  }
+
   if (typeof leveldown.destroy !== 'function') {
     leveldown.destroy = function (name, cb) { cb(); };
   }
```

The exact same code should be applied on memory.js

_ps: I was going to create a proper pull request, but some of the tools to run all tests didn't install on my machine, so I created this issue just to have it on record_

**Comment by nolanlawson** [comment]
Hey @rafaelsteil, thanks for the issue! If you do go ahead and create a PR, it will actually run our tests on Travis, so you don't have to worry about stuff installing locally or not. :)

Can you confirm that this is the only issue on IE9? I admit I've never gotten the test suite to fully pass on IE9, so I'm not sure. (We test IE10 in Travis, so it's A-OK in that version at least.)

**Comment by daleharvey** [comment]
Happy to take any pull requests, but with ms dropping support for anything below 11 (https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support) I think its sensible for us to only actively track issues affecting the supported browsers so closing out, cheers
