### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by kesavan49** [pouchdb/pouchdb#4153]
When syncing with remote database i facing problem pouchdb throws error

 Uncaught Syntax Error: Unexpected end of input

google network console show status cancelled.

**Comment by nolanlawson** [comment]
It looks like your CouchDB server is not returning content of type `application/json`. Are you using a proxy in front of CouchDB?

Also it would be really helpful if you posted screenshots or something. It's hard to debug if we can't see the full stacktrace or what you're seeing. :)

**Comment by kesavan49** [comment]
Hey nolanlawson,
               Thanks for your reply. Yes, we are using an nginx web server in front of couchdb. I digged the issue further and found out couple of things. The "Unexpected end of input" is because the replicated document is being completely JSON. Some values are being added to the document. I tried to test this with couchDB replication. I have a local couchDB server and remote couchDB server and the pouchdb. When  i try to replicate directly from remote server to pouchdb, the replicate crashes with above stated error for the document not being JSON. I tried to replicate same database to my local couchdb server and the replication is success with following status

{
   "_id": "pouch_test",
   "_rev": "3-0e45c65516f7388edc8c64cc52d4a61e",
   "source": "http://<remote_server>/<db>",
   "target": "http://<local_server>/<db>",
   "owner": "admin",
   "_replication_state": "completed",
   "_replication_state_time": "2015-08-12T12:36:11+05:30",
   "_replication_id": "6fc39464fa60eb52545c66649ea545b6",
   "_replication_stats": {
       "revisions_checked": 182,
       "missing_revisions_found": 182,
       "docs_read": 182,
       "docs_written": 130,
       "doc_write_failures": 52,
       "checkpointed_source_seq": 74883
   }
}

    After this I tried to replicate the same database to a newly created database in the remote server, and that worked with doc_write_failures : 0 . From what i can understand, the pouchdb replication is not handlig the error while couchdb replication handles this. And i still have got no clue what manipulates the document while syncing and why it happens only when it replicates over internet. I am attaching couple of files i downloaded (Non JSON files) and some screenshots along with this


request : 

me@mymachine:~$ curl -g "http://server/db/4f27e610812c37b786da3d53ad05f000?revs=true&open_revs=%5B%222-2a4a55aa9c624baaacba0e2a16761775%22%5D&_nonce=14393"

response :

--56125b8490881106b114a9287adc8fa9
Content-Type: application/json

{"_id":"4f27e610812c37b786da3d53ad05f000","_rev":"2-2a4a55aa9c624baaacba0e2a16761775","_deleted":true,"_revisions":{"start":2,"ids":["2a4a55aa9c624baaacba0e2a16761775","7b3776b6c1327cf02ec24e5229ede64e"]}}
--56125b8490881106b114a9287adc8fa9--


Another response:

![22](https://cloud.githubusercontent.com/assets/11057888/9244508/6616c22a-41b9-11e5-96b8-296795678f65.png)

**Comment by nolanlawson** [comment]
So it appears that somehow your nginx proxy is returning `multipart/related` content, not `application/json` content, which PouchDB does not support. PouchDB communicates this fact to CouchDB via the `Accept: application/json` header, which your nginx proxy will need to forward.

My recommendation is to try to attach your web application *directly* to CouchDB, see what the requests/responses look like, and then verify that your nginx proxy is doing exactly the same thing. For the record, I've used [the CouchDB instructions for nginx](https://wiki.apache.org/couchdb/Nginx_As_a_Reverse_Proxy#Reverse_proxy_for_a_subdirectory) and it's worked for me.

**Comment by kesavan49** [comment]
Hi @nolanlawson  
  Thanks for your response. The problem was with the network i am using here. When i changed to different network, everything seems be working fine. The firewall or route or something in the middle is manipulating the data that is being pulled from the server. I am sorry that i raised a bug before checking my network issue
