### ISSUE TITLE
pouchdb replicate to pouchdb

### ISSUE THREAD

**Issue by alvin0618** [pouchdb/pouchdb#4163]
Hi guys, I am new in couchdb and pouchdb. I created a mobile web app (Android) and use pouchdb as local storage. 
I want to keep sync both data between 2 device in the same local network when internet was down (offline).
Is there anyway to replicate pouchdb to pouchdb between 2 mobile web apps devices ?

**Comment by nickcolley** [comment]
Hey!

If you can put a local network into your environment you could have a local pouchdb server, this would replicate to your server external to your local network, then if your internet goes down your apps don't worry because they were always using this middle man.

```
                +---------+                                                                                                              
                | Couchdb |                                                                                                              
                +----+----+                                                                                                              
                     |                                                                                                                   
                     |                                                                                                                   
                     v          Outside World                                                                                            
  +--------------------------------------+                                                                                               
                     |          Local Network                                                                                            
             +-------v---------+                                                                                                         
       +---->+  PouchDB|Server +<----+                                                                                                   
       |     +-----------------+     |                                                                                                   
       |                             |                                                                                                   
       |                             |                                                                                                   
       |                             |                                                                                                   
+------+--------+         +----------+----+                                                                                              
|PouchDB(WebApp)|         |PouchDB(WebApp)|                                                                                              
+---------------+         +---------------+                                                                                              
```

If you're looking for a solution to sync directly between two of your apps *without* a server inbetween, there's not currently something for that.

I don't think this is possible with a web app in a browser, however if you're using Phonegap/Cordova to wrap your app it is technically possible.

One way could be to use https://github.com/nolanlawson/pouchdb-replication-stream with https://github.com/nolanlawson/pouchdb-replication-stream but I have no idea how performant that would be!

```
              +---------+                  
              | Couchdb |                  
              +----+----+                  
                   |                       
                   |                       
                   v          Outside World
+--------------------------------------+   
                   |          Local Network
       +-----------+------------+          
       |                        |          
+------v-------+   Ble  +-------v-------+  
|PouchDB(WebApp+<------>+PouchDB(WebApp)|  
+--------------+        +---------------+  
```

One related project is PeerPouch which uses WebRTC (P2P) but I believe that needs a server to perform an initial handshake: https://github.com/natevw/PeerPouch -- It's also out of date so probably wont work with latest PouchDB :(

I'd suggest if you can, focus on a good solo offline experience if possible.

**Comment by alvin0618** [comment]
Hi nickcolley, thanks for the comment.
Yes, I'm looking for solution without local server in between the local network.
And you have mentioned Phonegap/Cordova is technically possible, can you give me some clue on this?

**Comment by nickcolley** [comment]
You could have your two devices communicate via bluetooth https://github.com/don/BluetoothSerial and https://github.com/nolanlawson/pouchdb-replication-stream, I'm out of ideas otherwise, hopefully someone else can pitch in.

**Comment by nolanlawson** [comment]
@nickcolley Actually the Thali project just recently wrote a PouchDB-based Bluetooth syncer for Android Cordova apps: https://github.com/thaliproject/Thali_CordovaPlugin/releases/tag/story-0-android /cc @mattpodwysocki

**Comment by daleharvey** [comment]
In some web environments (chrome apps, firefox apps, cordova apps) you can spawn a web server that using the tcp socket api, you could then using https://github.com/pouchdb/pouchdb-express-router as a reference have a web server that will replicate over http in the local network.

This was one of the first experiments done with pouchdb, however there isnt a huge amount of maintained projects to do it yet, however most of the plumbing should be around, I would definitely take a look at the webRTC and bluetooth projects around pouchdb to get a start

**Comment by daleharvey** [comment]
So yup, there are various examples for this, especially now Nolan has put up worker / socket pouch which should be great examples to follow from, if theres anything needed in pouchdb itself to help then feel free to open an issue about it, but this seems closed for now, thanks

**Comment by rjsteinert** [comment]
Does anyone know of any examples of doing PouchDB replication over Bluetooth? With support for [this proposal in the Web Bluetooth issue queue](https://github.com/WebBluetoothCG/web-bluetooth/issues/231) we could make offline P2P replication of PouchDB databases possible with native web.
