### ISSUE TITLE
Referer header required.

### ISSUE THREAD

**Issue by dimitarkolev** [pouchdb/pouchdb#4174]
I get this error trying to connect to couchdb from nodejs? I have CORS for couchdb enabled.
```
pouchdb:adapter Picked adapter: http +0ms
  pouchdb:adapter Picked adapter: http +10ms
  pouchdb:api http://127.0.0.1:5984/documents +6ms request { method: 'POST',
  url: '_index',
  body: { index: { fields: [Object] } } }
  pouchdb:api http://127.0.0.1:5984/documents +29ms request { method: 'POST',
  url: '_index',
  body: { index: { fields: [Object] } } }
  pouchdb:api http://127.0.0.1:5984/documents +10ms request error { [bad_request: Something wrong with the request]
  status: 400,
  name: 'bad_request',
  message: 'Something wrong with the request',
  error: true,
  reason: 'Referer header required.' }
  pouchdb:api http://127.0.0.1:5984/documents +1ms request error { [bad_request: Something wrong with the request]
  status: 400,
  name: 'bad_request',
  message: 'Something wrong with the request',
  error: true,
  reason: 'Referer header required.' }
{ [bad_request: Something wrong with the request]
  status: 400,
  name: 'bad_request',
  message: 'Something wrong with the request',
  error: true,
  reason: 'Referer header required.' }
```

**Comment by daleharvey** [comment]
Can you give a code example of what you are going, I feel like this may be a misleading error on the couchdb side

**Comment by kxepal** [comment]
CouchDB requires Referer header on POST /db requests. It was a part of basic CSRF protection from old days.

**Comment by daleharvey** [comment]
just `POST`? not seeing it with `PUT`

**Comment by daleharvey** [comment]
hrm, not seeing it on `POST` either

```
[debug] [<0.20299.6>] 'POST' /testing/_bulk_docs {1,1} from "127.0.0.1"
Headers: [{'Accept',"application/json"},
          {'Connection',"close"},
          {'Content-Length',"39"},
          {'Content-Type',"application/json"},
          {'Host',"127.0.0.1:5984"}]
[debug] [<0.20299.6>] OAuth Params: []
[info] [<0.20299.6>] 127.0.0.1 - - POST /testing/_bulk_docs 201
```

This is 1.6.1

**Comment by kxepal** [comment]
Just POST. More proper implementation is added in 2.0 and will be backported to 1.x.x branch.

**Comment by dimitarkolev** [comment]
Here is a code example 		
```
database.documents = new PouchDB(databaseAddress + '/documents');
		database.documents.createIndex({
			index: {
				fields: ['meta.layout']
			}
		}).then(...something...).catch((err) => { console.log err; });
```
If I got it right, i have to install couch 2.0 ?

**Comment by kxepal** [comment]
@dimitarkolev no, not right: CouchDB 2.0 just implements different CSRF protection with different behavior which is not (afaik) supported by PouchDB.

**Comment by daleharvey** [comment]
@dimitarkolev Yeh fairly certain you are right, just validating now

@kxepal as posted above, this is unlikely anything to do with CSRF

**Comment by kxepal** [comment]
@daleharvey I didn't say that it applies for all POST requests, just `/db` one.

**Comment by daleharvey** [comment]
@kxepal and they arent posting to `/db`, they are posting to `/db/_index`

@dimitarkolev yup, pouchdb-find / mango only works on CouchDB 2.0 or Cloudant, `_index` isnt available on CouchDB 1.6

**Comment by kxepal** [comment]
@daleharvey since there is no `/db/_index` handler, it counts _index as document id and fails to POST. Anyway, just provide Referer header here and you're fine.

**Comment by nolanlawson** [comment]
@kxepal If y'all plan on doing a 1.6.2 or 1.7.0, it would be awesome to implement a stub for `_index` and return a more helpful error message. :) I myself have gotten confused by that error message a number of times, even while I was implementing `pouchdb-find`.

**Comment by kxepal** [comment]
@nolanlawson it's hardly to return anything else here since at first we check headers for valid data: content-type, referer, authorization and only if everything is valid proceed the document resource logic. 

However, for 1.7 we'll replace referer with backported from 2.0 CSRF implementation, but for backward compatibility you'll have to handle this case somehow anyway /:

**Comment by daleharvey** [comment]
for the purpose of this bug, CSRF is irrelevant, we cannot post to `_index` because it doesnt exist, adding a referrer is not going to help anything except give another error message.

@dimitarkolev sorry for the side track, but yup you need to install Couch 2.0 to use `pouchdb-find`

Will discuss CSRF in the relevant thread
