### ISSUE TITLE
EventEmitter possible memory leak with 4.0.0

### ISSUE THREAD

**Issue by natcohen** [pouchdb/pouchdb#4176]
I didn't make more tests but I just upgraded from 3.6.0 and got this message at the initialisation:

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

I don't use 11 listeners (afaik) so I'm wondering if it's a bug or a change that make my code creating 11 listeners...

FYI never had this message with 3.6.0

**Comment by nolanlawson** [comment]
Yup, this is a known issue and is fixed by https://github.com/pouchdb/pouchdb/commit/691df0d6b7fac08d8a281f169c2381f6424510d6. We will release a 4.0.1 soon; in the meantime you can do `PouchDB.setMaxListeners(20)` and it will fix the warning. Sorry about that!
