### ISSUE TITLE
Calling Error constructor with incorrect context

### ISSUE THREAD

**Issue by tyler-johnson** [pouchdb/pouchdb#4180]
I was getting a very strange unhandled 404 missing rejection today and in my attempt to track it down, I came upon this. I think (although I'm not certain) the incorrect context is being passed to the error constructor when errors are being generated. Strangely, when I fixed this line, the unhandled error disappeared.

https://github.com/pouchdb/pouchdb/blob/master/lib/deps/errors.js#L7

It is:

```js
Error.call(opts.reason);
```

It should be:

```js
Error.call(this, opts.reason);
```

**Comment by nolanlawson** [comment]
@calvinmetcalf any ideas? I'm not familiar with that corner of JavaScript inheritance.

**Comment by daleharvey** [comment]
@tyler-johnson would be super useful if you could help us to get to the point of reproducing the same issue, how is it being caused? It does look like your change would be a correct one

**Comment by tyler-johnson** [comment]
So it turns out that the 404 error was a race condition giving me a false positive and is not effected by this.

Nonetheless, this is still an incorrect use `Error.call()`. While the line probably isn't doing anything bad, it should be either removed or changed to call with the correct context.

**Comment by daleharvey** [comment]
So I cant detect that this causes any problems, we manually set `reason` etc so I think it doesnt actually matter, but probably best to use it correctly if this change doesnt cause any failures

**Comment by nolanlawson** [comment]
fixed by 5e2a3ac6e100673a21e4d1d409db7ffacf35a8dc
