### ISSUE TITLE
PouchDB Replicate From Fails in Safari on iOS 8.4.1

### ISSUE THREAD

**Issue by jopierce** [pouchdb/pouchdb#4184]
Device: iPad Air 2 128gb wifi
OS: OSX 8.4.1
App: Safari
Using the example code provided here: http://pouchdb.com/api.html#replication with debugging enabled
I get the following output in Safari's console when I try to replicate from a remoteDB: 

[Log] pouchdb:http GET http://10.10.111.60:5984/orders/ +0ms
[Log] pouchdb:api http://10.10.111.60:5984/orders +555ms id
[Log] error:  (dashboard.controller.js, line 81)
PouchError
column: 0
error: true
line: 0
message: "Database encountered an unknown error"
name: "unknown_error"
result: Object
stack: "ThrowerFunction@[native code]"
status: 500
__proto__: PouchError
constructor: function PouchError(opts) {
toString: function () {
__proto__: Error

This code works perfectly fine in Safari for Mac OSX, Chrome, Firefox, Edge and weirder than that, it works in the iOS simulator running iOS 8.3.

Let me know what additional info you need to help find this bug.
Thanks.

**Comment by nolanlawson** [comment]
Unfortunately "Database encountered an unknown error" is the error PouchDB throws when there's some  *other* error that's the true culprit. Can you take a look at the console/network tab and see if there's any HTTP request that failed?

Also a screenshot may be helpful.

**Comment by jopierce** [comment]
Well.. Now I feel foolish.
The error actually was network related. I'm not used to building apps with CORS enabled, rather we normally proxy. The iPad wasn't on the internal VPN and since it was making requests directly, not through a proxy, they were just flat out failing.

So you can go ahead and close this.
Thanks for responding so quickly!

**Comment by nolanlawson** [comment]
Glad it was easy to fix! I've been burned by CORS errors too; we don't report them very well in PouchDB atm. :/
