### ISSUE TITLE
Better error message when CouchDB doesn't have CORS configured

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4189]
Currently it's very hard to figure out when you forgot to enable cors, because the error message you get is something like `unknown error 500`.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/ac56d71cac049fd026ee1e8918bcb82d31192018

**Comment by anaran** [comment]
I don't think this issue fixes the scenario I describe in #4256 where the firefox os app is to blame and the error message sends people off to investigate their couchdb server CORS settings instead.
