### ISSUE TITLE
Remove vuvuzela

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4195]

**Comment by daleharvey** [comment]
@nolanlawson you had a test PR open for this, its fairly guaranteed to save a good amount of speed by removing it entirely, the issue is that we generate far too much metadata

https://github.com/pouchdb/pouchdb/blob/master/lib/deps/docs/updateDoc.js#L30 is currently defaulted to 1000, which is tons, but should be small enough to safely json.stringify, when I run https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.replication.js#L192 I can see we still have a 5000 long array in the metadata which means something is broken.

if rev_limits is like 10 then we should have a very small amount of metadata that would be very safe to write, if we dont then it is another bug, taking a look into it now

**Comment by nolanlawson** [comment]
So we now have the revs_limit correctly set to 1000, and I ran another PR trying to get rid of it, and it seems like sadly it's here to stay, unless we want to decrease the max any further: https://github.com/pouchdb/pouchdb/pull/4336

I think we should close this issue for now; running `disc` on PouchDB i can see that vuvuzela takes up <1% of the total browserify size, and although it's a performance drain, we can still experiment with using string length heuristics to avoid the try/catch deoptimization.
