### ISSUE TITLE
Do we need a roadmap?

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4198]
Hoodie has one (https://github.com/hoodiehq/discussion/issues/38), and it makes me wonder if it affects our contributor numbers, that nobody knows what we plan to do. In fact I tend to act kind of randomly, working on whatever I find interesting in a given weekend, but maybe it would make more sense to try to organize our trajectory, at least for the near future.

Thoughts?

**Comment by nickcolley** [comment]
I think if we want to try and get more contributors (myself included) we can try to be more inclusive.

I think a roadmap would be good to be able to try and focus efforts with multiple people?

If people know what the long term goals are we could encourage them to help out or help them get to the point where they can.

Also hype.

**Comment by nolanlawson** [comment]
My personal long-term goals:
- crazy good perf
- runs everywhere JS runs
- easy to install, no more leveldown headaches

More practically:
- finish pouchdb-find
- make queries faster
- make replication faster

**Comment by nickcolley** [comment]
Along side your `runs everywhere JS runs` I think we should update the website to reflect that pouchdb is universal(isomorphic) and move towards pushing pouchdb-server.

I'd also like to help moving pouchdb-finds documentation into the site making it a first class citizen if that's where we want to take it.

**Comment by nolanlawson** [comment]
Yeah I agree with that direction for pouchdb-find, but I want to give it a bit more polish first. Also we should think about when/how we remove mapreduce and publish it as a separate plugin. I'd be happy to do that for a 5.0 or 6.0, since pouchdb-find is pretty close already.

**Comment by daleharvey** [comment]
Yeh I have always been wary of roadmaps, I dont like contributors having expectations put on them but a general listing of what peoples focus's are would be helpful.

Personally my main priorities:

 * 0 bugs
 * faster replication
 * faster indexes
 * fix compaction story (auto_compact by default)
 * PouchDB playground / try pouchdb etc

**Comment by nickcolley** [comment]
Putting purge in here since it's pretty important. https://github.com/pouchdb/pouchdb/issues/802

**Comment by nolanlawson** [comment]
Gonna close this for now; we have #4257 and we do tend to do a monthly "what's everyone working on" thing.
