### ISSUE TITLE
Download user flow

### ISSUE THREAD

**Issue by zaccolley** [pouchdb/pouchdb#4199]
At the mo when you press the 'Download v4.0.0' button it downloads the file straight.

Would a better flow to have it link to the different set-up options and have the download link on that page? This way the user knows what options they have.

Kinda like how jQuery does their download flow: https://jquery.com/download/

Might be wrong but thought I'd do an issue anyway so what people thought.

Perhaps make it a 'Install' button rather than download?

**Comment by nickcolley** [comment]
I like this a lot actually! We could have an install page which explains how to download via npm, etc all the options.

**Comment by daleharvey** [comment]
(removing tag as its for contributions with clear guides written)

Yeh I am always forgetting where I can find the cdn links for pouchdb, or the various storage adapters etc, I think a download page that gave instructions to the various methods would be very useful

**Comment by nolanlawson** [comment]
+1 to this idea. Would help with https://github.com/pouchdb/pouchdb/issues/4202 as well.

**Comment by nolanlawson** [comment]
985f548f2cbd818ed0158ad8f97da31c79485654
