### ISSUE TITLE
Ensure we're actually respecting revs_limit, stemming to 1000

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4204]
Follow-up to https://github.com/pouchdb/pouchdb/issues/4195 and https://github.com/pouchdb/pouchdb/pull/4196. We have `revs_limit` hard-coded to 1000, but it seems that in the case of `new_edits=false`, we're not actually applying it, so it's possible to get revision histories > 1000.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/13e9c18dce44d90366d902a2e5ba2f34184d5887
