### ISSUE TITLE
Trial Slack

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#4207]
Had a few thought about starting a Slack community for PouchDB.

I've been using Slack in the Hoodie community and it feels a lot more personal, and a real sense of community allowing anyone to jump in and chat.

My main motivations mirror that of WordPresses decision to move to using Slack: https://make.wordpress.org/chat/

Had some interest from others to help out with the initial integration.
https://twitter.com/balupton/status/636516862918946816

I'd propose we set it up internally then when it's all set update the website and make some noise, if we want to continue using IRC we could explore bridging to Slack.

**Comment by daleharvey** [comment]
I think we should get the bridge up asap, we have the server the website is hosted on to deploy it, How about you setup the slack room etc and once that is done I will setup the bridge and then we can publish it, I would prefer to not start off with fragmented discussions

@janl @gr2m Any pointers on getting the slack bridge up and running?

**Comment by nickcolley** [comment]
Yeah I was thinking we get it running just with us before advertising it, once it's working we can invite people. :+1:

**Comment by kxepal** [comment]
@daleharvey Hood.ie uses https://github.com/hoodiehq/slack-irc-duplex to bridge with IRC. Also, they have https://github.com/hoodiehq/slackin to simplify user registration.

**Comment by nickcolley** [comment]
Looks like pouchdb.slack.com is already registered, I wonder if anyone here's made that team?

**Comment by daleharvey** [comment]
Heh yeh apparently I made it in January

**Comment by daleharvey** [comment]
ok, bridge is up and running :)

**Comment by nickcolley** [comment]
@daleharvey have you got my email, can you invite me? :dancers:

**Comment by daleharvey** [comment]
You can invite yourself :) http://slack.pouchdb.com/

**Comment by kxepal** [comment]
@daleharvey 
> Missing admin scope: The token you provided is for an account that is not an admin. You must provide a token from an admin account in order to invite users through the Slack API.

):

**Comment by daleharvey** [comment]
Yeh noticed that, I cant figure out how to make the bot an admin

**Comment by daleharvey** [comment]
Figured it out, should be working now - http://slack.pouchdb.com/

**Comment by daleharvey** [comment]
And slack is up and running :) https://github.com/pouchdb/pouchdb/commit/243758c51f6ee906af0d4821fe891577058cab6b

**Comment by kulshekhar** [comment]
http://slack.pouchdb.com/ has been throwing a 502 for several days now. Is there regular activity on slack to warrant signing up?

**Comment by nickcolley** [comment]
@kulshekhar as a workaround you can join our IRC channel #pouchdb on freenode, thanks for reporting the issue!
