### ISSUE TITLE
Couch master failing in Travis again

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4209]
The error I see is:

```
 1) suite2 test.replication.js-local-http #3999-1 should not start over if last_seq mismatches:
      AssertionError: expected '2-g1AAAAG7eJzLYWBg4MhgTmHgz8tPSTV0MDQy1zMAQsMcoARTIkOS_P___7MygKxcoAC7mbmJWZpFIk4NSQpAMskeRU9SmnGSpbkFbj0OID3xKHpMTJLMzBPx2JMA0lMP1sOcyAjWY55oYm5pmYypA6cpeSxAkqEBSAENmo9ku1mKeZqlEQF9CyD69mclMhBQeQCi8j5hlQ8gKpF8ZWBobJJsmYKpKwsA9CRvdg' to not equal '2-g1AAAAG7eJzLYWBg4MhgTmHgz8tPSTV0MDQy1zMAQsMcoARTIkOS_P___7MygKxcoAC7mbmJWZpFIk4NSQpAMskeRU9SmnGSpbkFbj0OID3xKHpMTJLMzBPx2JMA0lMP1sOcyAjWY55oYm5pmYypA6cpeSxAkqEBSAENmo9ku1mKeZqlEQF9CyD69mclMhBQeQCi8j5hlQ8gKpF8ZWBobJJsmYKpKwsA9CRvdg'
      + expected - actual
     
      at source.put.then.then.catch.then.then.then.mismatch (/home/travis/build/pouchdb/pouchdb/tests/integration/test.replication.js:2501:36)
      at Array.0 (/home/travis/build/pouchdb/pouchdb/node_modules/lie/lib/index.js:88:21)
      at nextTick (/home/travis/build/pouchdb/pouchdb/node_modules/lie/node_modules/immediate/lib/index.js:61:18)
      at process._tickCallback (node.js:448:13)
```

**Comment by nolanlawson** [comment]
[Example log](https://travis-ci.org/pouchdb/pouchdb/jobs/76944090)

**Comment by kxepal** [comment]
mmm...
```
'2-g1AAAAG7eJzLYWBg4MhgTmHgz8tPSTV0MDQy1zMAQsMcoARTIkOS_P___7MygKxcoAC7mbmJWZpFIk4NSQpAMskeRU9SmnGSpbkFbj0OID3xKHpMTJLMzBPx2JMA0lMP1sOcyAjWY55oYm5pmYypA6cpeSxAkqEBSAENmo9ku1mKeZqlEQF9CyD69mclMhBQeQCi8j5hlQ8gKpF8ZWBobJJsmYKpKwsA9CRvdg' to not equal '2-g1AAAAG7eJzLYWBg4MhgTmHgz8tPSTV0MDQy1zMAQsMcoARTIkOS_P___7MygKxcoAC7mbmJWZpFIk4NSQpAMskeRU9SmnGSpbkFbj0OID3xKHpMTJLMzBPx2JMA0lMP1sOcyAjWY55oYm5pmYypA6cpeSxAkqEBSAENmo9ku1mKeZqlEQF9CyD69mclMhBQeQCi8j5hlQ8gKpF8ZWBobJJsmYKpKwsA9CRvdg'
```

```
>>> expected = '2-g1AAAAG7eJzLYWBg4MhgTmHgz8tPSTV0MDQy1zMAQsMcoARTIkOS_P___7MygKxcoAC7mbmJWZpFIk4NSQpAMskeRU9SmnGSpbkFbj0OID3xKHpMTJLMzBPx2JMA0lMP1sOcyAjWY55oYm5pmYypA6cpeSxAkqEBSAENmo9ku1mKeZqlEQF9CyD69mclMhBQeQCi8j5hlQ8gKpF8ZWBobJJsmYKpKwsA9CRvdg'
>>> actual = '2-g1AAAAG7eJzLYWBg4MhgTmHgz8tPSTV0MDQy1zMAQsMcoARTIkOS_P___7MygKxcoAC7mbmJWZpFIk4NSQpAMskeRU9SmnGSpbkFbj0OID3xKHpMTJLMzBPx2JMA0lMP1sOcyAjWY55oYm5pmYypA6cpeSxAkqEBSAENmo9ku1mKeZqlEQF9CyD69mclMhBQeQCi8j5hlQ8gKpF8ZWBobJJsmYKpKwsA9CRvdg'
>>> expected == actual
True
```

Are you sure that these seqs are compared correctly? Because they are identical.

**Comment by daleharvey** [comment]
Yeh the test is that they are not supposed to be identical

**Comment by kxepal** [comment]
Ah. Error message confused me.
Have you tried to wait for new updates then? Much likely timeout issue because travis is mostly slow.

**Comment by daleharvey** [comment]
nah its not a race, failing locally and we are reasonably good about not having races in our tests

**Comment by kxepal** [comment]
Read a test code...it seems like at this assertion document was successfully replicated and checkpoint reflects the right state of things - replication is doc, last_seq recorded in checkpoint. If you expected there something else, then it is a race. Or just wrong test.

**Comment by nolanlawson** [comment]
Not sure if it helps, but you can find the exact moment that the CouchDB master tests started failing: [this build](https://travis-ci.org/pouchdb/pouchdb/builds/76943852) was successful, then then [this build](https://travis-ci.org/pouchdb/pouchdb/builds/76944063) was the first one to fail. This corresponds to commit https://github.com/pouchdb/pouchdb/commit/70761f2c6003e91f8a886a1d5968c34cb27dc047, which was 6 days ago, so maybe there was a CouchDB commit around the same time that caused this?

**Comment by nolanlawson** [comment]
Note to self: we should probably log the CouchDB commit when we check it out from git. Kinda disappointed that our logs don't have it.

**Comment by daleharvey** [comment]
Was just discussing this on irc, but the way couch is split into seperate repos that auto update, the couchdb commit doesnt help much (the couch repo hasnt been touched in 18 days, but was certainly a couch commit that broke the test)

**Comment by daleharvey** [comment]
Test is failing because https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.replication.js#L2454 is failing the `last_seq` test, something must have change the last_seq format but that isnt a valid test to be doing to start with

**Comment by kxepal** [comment]
4 days you say...for the last 4 day we...
1. Changed seq format: https://github.com/apache/couchdb-fabric/pull/28
2. Set Etag for views: http://git-wip-us.apache.org/repos/asf/couchdb-chttpd/commit/129cdf93 
3. Updated mochiweb server over two minor releases
4. Applied various mailbox fixes for couch_replicator
5. Provided cluster wide database compaction
+ some other minor changes.

**Comment by kxepal** [comment]
@daleharvey well, https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.replication.js#L2454 will only work for 1.x and those who have numeric seq format. That's not true for 2.0 and Cloudant and not surprise that this check will be false.

**Comment by daleharvey** [comment]
yeh cheers the last_seq format change will do it, was a bad test, got a fix up for it

**Comment by daleharvey** [comment]
@kxepal btw couchdb master is running extremely slowly, its taking like 2 seconds to run a test that runs in 200ms on couchdb 1.6 - https://gist.github.com/daleharvey/4df4f873ecde5825084e

**Comment by kxepal** [comment]
@daleharvey 2.0 is notable slowly than 1.x and getting slower for every node in cluster. That's a price for cluster internal routines.

**Comment by daleharvey** [comment]
@kxepal I figured 2.0 would be slower, but it seems to have taken a huge slowdown in the last 3 weeks, https://travis-ci.org/pouchdb/pouchdb/builds/74585643 is a build where the test run in node took 10 minutes, its now 28 minutes in node

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/ecd6bd65c45af3e0dba898d3a7e101b9386f3f46

**Comment by kxepal** [comment]
@daleharvey That's interesting observation, thanks. cc @robertkowalski ^^^

**Comment by robertkowalski** [comment]
looks like the addition of couch_epi:


https://dl.dropboxusercontent.com/u/1809262/flame-epi.svg

**Comment by robertkowalski** [comment]
it is 3 times in the graph and always blocking, taking almost 21% of the new request time

**Comment by robertkowalski** [comment]
(for a simple get of a doc)

**Comment by robertkowalski** [comment]
the timeframe fits with the addition of couch_epi

**Comment by rnewson** [comment]
couch_epi performance impact has been remediated.
