### ISSUE TITLE
413 Request Entity Too Large - During replication

### ISSUE THREAD

**Issue by ronyrun** [pouchdb/pouchdb#4210]
Hello I have this issue. I tried to update more than 600 docs and then : 
pouch.localDB.replicate.to(pouch.remoteDB, options)

![image](https://cloud.githubusercontent.com/assets/7273443/9544455/3da99e10-4d81-11e5-8a99-defeb89e30ed.png)

DO you know how can I manage this pb ?

**Comment by nolanlawson** [comment]
Does it work if you break it up into two separate requests?

**Comment by kxepal** [comment]
@ronyrun Basically, you need to reduce size of your request body or increase allowed body on nginx side.

**Comment by ronyrun** [comment]
Thank you @nolanlawson & @kxepal

Hi If I reduce it with length 200, it's OK.
but I'm using the function : 
pouch.localDB.replicate.to(pouch.remoteDB, options) which launch the request for me.

**Comment by nolanlawson** [comment]
Check the options for replicate; you can tweak the batch size to make or smaller or larger. The default is 100, so either you've increased it or we have a bug. :) 

http://pouchdb.com/api.html#replication

**Comment by ronyrun** [comment]
Hi,
The batch size is configured to 150

**Comment by ronyrun** [comment]
I solved this issue with this Nginx config : client_max_body_size 20M; 
Thank you !

**Comment by bgold0** [comment]
Hmm i'm just trying to replicate 1 document and I am getting this error:

    {"error":"too_large","reason":"the request entity is too large","status":413,"name":"too_large","message":"the request entity is too large","result":{"ok":false,"start_time":"2016-10-05T19:33:39.358Z","docs_read":1,"docs_written":0,"doc_write_failures":1,"errors":[],"status":"aborting","end_time":"2016-10-05T19:33:40.081Z","last_seq":31}}

Said document is definitely not larger than a few MB, does anyone know what I can do?

**Comment by nolanlawson** [comment]
You can reduce your batch size during replication; that should help.
