### ISSUE TITLE
Add Slack to the website

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#4212]
Need to lower the barrier to getting involved, have the form on the site etc.

**Comment by nickcolley** [comment]
Steps to solve this:

1. Build the site using the instructions from CONTRIBUTING.md (https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md#building-pouchdb-documentation)
2. Add a link to the footer under 'Discuss' to http://slack.pouchdb.com/

That's it, as always let me know if you have any questions regarding solving this, cheers.

**Comment by nolanlawson** [comment]
I put the wrong issue number on the way in, but fixed by 031f7dbde487537723185e0733f58ef6292c47e6
!
