### ISSUE TITLE
MEMdown const usage

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#4215]
Not sure if this relevant to anything but while trying to debug some hoodie tests I came across this:

https://github.com/Level/abstract-leveldown/blob/02e19475f6eafc81d5fd0b854bffc57b6e7d3a6c/is-leveldown.js#L1

Which fails in IE10

**Comment by nolanlawson** [comment]
Looks like they added ES6 stuff to abstract-leveldown, but it's not browserifying correctly?

**Comment by nolanlawson** [comment]
I can confirm by checking https://wzrd.in/standalone/memdown@latest. This is an abstract-leveldown or a browserify bug or something.

**Comment by nolanlawson** [comment]
Or maybe it is our responsibility to ES5ify stuff when we build it? But then again, that wouldn't help Hoodie, because they are using WebPack IIRC.

**Comment by nolanlawson** [comment]
I filed an issue on abstract-leveldown. Let's fix it over there.
