### ISSUE TITLE
Use getAll() instead of IndexedDB cursors where possible

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4235]
We can take advantage of the new IndexedDB 2.0 method `getAll()`, already shipping in Chrome, and use it instead of `IDBCursor`s where possible. It ought to be much faster.

I envision this as basically a shim over the cursor API (which we never want to use when we can avoid it), with a feature detection check to switch between the two depending on browser support.

This could especially be a boon to `allDocs()` and `changes ()`, and could help us turn that "IndexedDB is 40x slower than WebSQL" into something more like 20x. (Will still probably be slower because we don't have native joins.)

**Comment by nolanlawson** [comment]
I made a mistake in that blog post. `getAll()` is implemented in Firefox as well as Chrome.

**Comment by nickcolley** [comment]
Related: http://discourse.wicg.io/t/indexeddb-2-0-performance-improvements/916/3

**Comment by nickcolley** [comment]
Would love to give this a go, but have no experience with indexedDB. Let me know what you think.

**Comment by nolanlawson** [comment]
I think anybody who's interested in learning more about IndexedDB could take this up. :)

**Comment by inexorabletash** [comment]
And ping me if you've got any questions. (Spec author and implementer) - happy to help.

**Comment by nolanlawson** [comment]
Thanks @inexorabletash! Will give this a shot soon.

**Comment by nolanlawson** [comment]
@inexorabletash I looked into this today, but unfortunately it looks like `getAll()` is not going to meet our needs without a lot of extra tweaking. The basic issue is that, when we query our `objectStore`s, we often need to add some additional criteria to the `IDBKeyRange` based on either a secondary index on that `objectStore` or an index on another `objectStore` (a join). And since these properties can't be known in advance, there are only two solutions:

1. Read the entire database into memory, or risk reading a large portion of it into memory, and then filter what comes back (bad)
2. Optimistically use `getAll()` with the assumption that most of the objects returned will fit our secondary criterion (a good bet, actually), and then follow up with subsequent `getAll()`s in the rare case where we haven't fetched enough objects.

To be specific, I can cite two examples where this came up:

1. The `allDocs()` API, which iterates over the `by-doc` store (document metadata), but needs to skip any metadata that indicates the document is deleted
2. The `changes()` API, which iterates over the `'by-seq'` store (document revisions) but needs to skip any docs where the `rev` is not the `winningRev` based on the corresponding metadata in the `by-doc` store (essentially a join plus a secondary index on the joined store)

So it seems like for `allDocs()` it will be doable, although we'll have to put in a considerable amount of elbow-grease to work around the case where the initial result contains deleted documents (especially if users are supplying `skip` and `limit`, i.e. slices). For `changes()` it looks like it won't be possible without a join API.

Another strategy that occurred to me is to use `getAll()` more like a batched cursor rather than a single-shot query. E.g. if the user asks for 100 rows, then we fetch 10 at a time instead of one at a time, but keep our existing filtering logic in place. This might be more flexible, while still giving us performance gains.

One thing about the API I found a bit strange: in the case where we want *both* the keys and the values, then we need to do both `getAll()` and `getAllKeys()` and then wait for the two asynchronous results to come back. It would be nice to have a single query that did both. (I also noticed Firefox has exposed `mozGetAll()`, but not `mozGetAllKeys()`, so without feature flags, we wouldn't yet be able to use `getAll()` where we also needed `getAllKeys()`.)

**Comment by inexorabletash** [comment]
Thanks for looking at this. A couple of quick (and not useful) tidbits:

For `getAll`/`getAllKeys` combined you could issue both simultaneously and wait the second to come back. This would be two callbacks (vs one) but still better than potentially 100s or 1000s, which is what `getAll` (etc) are intending to avoid. Still, yeah, we could look at a combined `getAllKeysAndValues`

For moz... yeah, there's no prefixed mozGetAllKeys on IDBObjectStore. But (like Chrome) if you enable an experimental setting you get all four methods unprefixed, which is how they'd ship. In FF, go to `about:config` then search for `dom.indexedDB.experimental`

**Comment by nolanlawson** [comment]
Thanks for the feedback! I think this has been sufficiently discussed, and most likely we won't really be able to take advantage of `getKeys()` until we rewrite the IDB adapter, but we'll keep this discussion in mind.
