### ISSUE TITLE
Fix CouchDB master tests in container-based Travis

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4239]
CouchDB master is now permafail due to not correctly installing all the necessary apt packages. Details here: https://github.com/pouchdb/pouchdb/pull/4194#issuecomment-136490995

Probably we are just missing some crucial packages that need to be installed. Travis has some docs here http://docs.travis-ci.com/user/migrating-from-legacy/.

**Comment by daleharvey** [comment]
ok found the issue, we cant install spidermonkey

Disallowing packages: libmozjs185-dev

If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process

**Comment by daleharvey** [comment]
Opened an issue for it @ https://github.com/travis-ci/apt-package-whitelist/issues/1104

**Comment by daleharvey** [comment]
Upstream bug fixed and starting to see green couch master builds now https://travis-ci.org/pouchdb/pouchdb/builds/78731393
