### ISSUE TITLE
PouchDB Server is permafail in Firefox

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4240]
https://github.com/pouchdb/pouchdb/commit/9c03e0f212b3a23e4d72962be2545382caaa3090 put PouchDB Server into permafail. Details are scarce (https://github.com/pouchdb/pouchdb/pull/4217#issuecomment-136177286), but basically you should be seeing an ESOCKETTIMEDOUT for `window.eval`. You can repro by running:

    SERVER=pouchdb-server CLIENT=selenium:firefox npm t

Oddly this cannot be reproduced in Chrome or PhantomJS in my testing.

**Comment by nolanlawson** [comment]
Error:

```
=>  { lastPassed: 'issue #2393 update_seq after new_edits + replication',
  failures: [],
  passed: 610,
  failed: 0,
  browser: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0' }
{ [Error: [eval("window.results")] ESOCKETTIMEDOUT] code: 'ESOCKETTIMEDOUT' }
Doh, tests failed
```

Nothing interesting in Firefox itself except timeouts.

**Comment by nolanlawson** [comment]
More data points:
* it happens with and without the proxy
* it happens with a stock pouchdb-server (i.e. using pouchdb 4.0.0 on the server side)

**Comment by nolanlawson** [comment]
This is definitely a Selenium bug, because I can't reproduce if I just use `npm run dev` and open the tests in Firefox.

**Comment by daleharvey** [comment]
The issue is pouchdb-server isnt sending the correct Content-type on JSON responses
```
$ curl -v -X PUT http://127.0.0.1:6984/testing
* About to connect() to 127.0.0.1 port 6984 (#0)
*   Trying 127.0.0.1...
* Adding handle: conn: 0x7fc9d4004400
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fc9d4004400) send_pipe: 1, recv_pipe: 0
* Connected to 127.0.0.1 (127.0.0.1) port 6984 (#0)
> PUT /testing HTTP/1.1
> User-Agent: curl/7.30.0
> Host: 127.0.0.1:6984
> Accept: */*
>
< HTTP/1.1 201 Created
< X-Powered-By: Express
< Location: http://127.0.0.1:6984/testing
< Content-Type: text/plain; charset=utf-8
< Content-Length: 12
< ETag: W/"c-xgQX3hTxD8e0kVuo9iMlIg"
< Vary: Accept-Encoding
< Date: Wed, 02 Sep 2015 13:49:27 GMT
< Connection: keep-alive
<
{"ok":true}
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by daleharvey** [comment]
When we have a live changes feed, we manually abort it, we have already received the data and we manually parse it, but firefox throws a top level exception about not being 'well formed', this somehow screws with selenium and causes it not to respond anymore

**Comment by daleharvey** [comment]
I am not quite sure why this only seems to happen when `PouchDB.utils.ajax` is overridden

**Comment by nolanlawson** [comment]
Excellent catch; I think the part of the code that needs modification is this: https://github.com/pouchdb/express-pouchdb/blob/master/lib/routes/changes.js#L5-L102

**Comment by daleharvey** [comment]
If I add a Content-Type there then it looks to be passing, not certain its the best fix as this isnt sending the right content-type anywhere, not just changes requests

**Comment by nolanlawson** [comment]
Wow, I didn't believe you at first, but you're right. pouchdb-server returns text/plain for everything.

The fix for that would be here: https://github.com/pouchdb/express-pouchdb/blob/874bbce238b0202899c4a16756d1ee946503d690/lib/utils.js#L188-L202

**Comment by daleharvey** [comment]
And fixed
