### ISSUE TITLE
PUT on replication

### ISSUE THREAD

**Issue by hrishiballal** [pouchdb/pouchdb#4247]
I upgraded to PouchDB 4.0.1 and since PouchDB 4.0, I am seeing a additional PUT being sent everytime I replicate. (Username and databasename blurred) 

Is there a reason for this? Is this by design? How can this be turned off? 

![cloudant-error](https://cloud.githubusercontent.com/assets/1588744/9615206/a7e1f992-50ee-11e5-8662-772710f7f424.png)

**Comment by daleharvey** [comment]
The reason for the PUT is to attempt to store a checkpoint on the server so we can resume replication from the correct place between restarts, it has been the behaviour in pouchdb for a quite a long time and there is no way to turn it off although if you give the database replication permissions then it will succeed and your replications will be more stable

**Comment by hrishiballal** [comment]
OK thanks, but when I use Pouchdb 3.6 it does not give a 403 forbidden on Cloudant, this is happening in 4.0.1 , did something change in this behavior?

**Comment by hrishiballal** [comment]
Actually it is trying it a couple of times, it succeeds the first time: 
![first](https://cloud.githubusercontent.com/assets/1588744/9644120/6432dc14-51bd-11e5-8fc1-6bd53a3f1cfd.png)
Second time I am getting a cookie header mismatch: 
![second](https://cloud.githubusercontent.com/assets/1588744/9644119/643208f2-51bd-11e5-852f-bbb0694b6c40.png)
