### ISSUE TITLE
'paused' event not firing during sync

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#4251]
As [reported on Slack](https://pouchdb.slack.com/archives/general/p1441187392000733), calling db.sync does not generate a 'paused' event.

This appears to be a regression in 4.0.1 compared to 4.0.0.

**Comment by ng-** [comment]
Also, db.sync().once('paused') does not appear to be working in 4.0.0.  For now I am just using sync.on and counting manually but it is a bit annoying.

**Comment by daleharvey** [comment]
So I am very confused, There is no code https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.sync.js at handling the `paused` / `active`` events, however I have definitely used them previously - https://github.com/daleharvey/done/blob/gh-pages/js/done.js#L120

**Comment by daleharvey** [comment]
So testing, apparently this worked between 3.3.0 and 3.6.0, but not before or after

**Comment by daleharvey** [comment]
In so far as I can tell, it looks like this worked completely accidently, there are not tests for it or code that directly handles the situation, it worked between 3.3 and 3.6 and there arent any particular commits around 3.6 that would indicate it breaking, frankly confused.

So for now I just think we implement it, I dont think `active` and `paused` can just forward the replication events, sync is only paused when both replications are paused, I will probably look at fixing the other bugs related to active / paused before I do this one (https://github.com/pouchdb/pouchdb/issues/3852)

**Comment by colinskow** [comment]
I think it is also important to add a test for `active` event during sync.

**Comment by daleharvey** [comment]
our events are undertested which is why this regressed, I will be copying across https://github.com/pouchdb/pouchdb/commit/a17be0693f325449ed7716d8dc49a7c3a0069b78 as the tests for sync and add a few more

**Comment by colinskow** [comment]
Here's a simple Node test, which is successfully isolating the issue:

```js
var PouchDB = require('pouchdb');
var expect = require('chai').expect;

describe('PouchDB Sync Events', function() {

  var remoteDB = new PouchDB('http://localhost:5984/pouchdb_event_test');
  var localDB = new PouchDB('pouchdb_event_test');

  var doc1 = {
    _id: 'doc1'
  };

  var doc2 = {
    _id: 'doc2'
  };

  var previous = Promise.resolve();

  var sync, rev1, rev2;

  var activeDeferred = Promise.defer();
  var pauseDeferred = Promise.defer();

  it('should fire active and paused events on sync', function(done) {
    previous
      .then(function() {
        return Promise.all([remoteDB.put(doc1), remoteDB.put(doc2)]);
      })
      .then(function(results) {
        console.log('documents put to remote');
        rev1 = results[0].rev;
        rev2 = results[1].rev;
        sync = PouchDB.sync(remoteDB, localDB, {live: true, retry: true})
          .on('active', function() {
            console.log('Active fired');
            activeDeferred.resolve();
          })
          .on('paused', function() {
            console.log('Paused fired');
            pauseDeferred.resolve();
          })
          .on('complete', function() {
            console.log('Sync cancelled');
          });
        console.log('sync started');
        return activeDeferred.promise;
      })
      .then(function() {
        return pauseDeferred.promise;
      })
      .then(function() {
        console.log('Sync done');
        return Promise.all([remoteDB.get('doc1'), remoteDB.get('doc2')]);
      })
      .then(function(results) {
        console.log('Checking results');
        expect(results[0]._rev).to.equal(rev1);
        expect(results[0]._id).to.equal('doc1');
        expect(results[1]._rev).to.equal(rev2);
        expect(results[1]._id).to.equal('doc2');
        sync.cancel();
        return Promise.all([remoteDB.destroy(), localDB.destroy()]);
      })
      .then(function() {
        console.log('test complete');
        done();
      })
      .catch(function(err) {
        console.error('Error', err);
        done(err);
        return Promise.all([remoteDB.destroy(), localDB.destroy()]);
      });
  });

});
```

**Comment by colinskow** [comment]
Pull request:
https://github.com/pouchdb/pouchdb/pull/4360

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/473c98755197463945459ea296d152235afa1087
