### ISSUE TITLE
add haproxy to the travis.yml

### ISSUE THREAD

**Issue by robertkowalski** [pouchdb/pouchdb#4255]
Hi folks,

we recently added haproxy to the CouchDB `dev/run` script, it looks like the testsuite fails/runs endless because of it:

https://github.com/apache/couchdb/commit/587646f1fec6f665f70c97c24f3eef95780b409a

for us developing Couch it is super useful, but I am afraid we have broken your build :(

I think you just have to add `haproxy` to the top of your travis.yml, somewhere there: https://github.com/pouchdb/pouchdb/blob/master/.travis.yml#L22

**Comment by daleharvey** [comment]
We talk to 15984, tested adding this and it doesnt make a difference so we are good I think, the failures were an unrelated travis issue and now mostly passing, cheers
