### ISSUE TITLE
explainCors-browser message is misleading in Firefox OS App

### ISSUE THREAD

**Issue by anaran** [pouchdb/pouchdb#4256]
https://github.com/pouchdb/pouchdb/blob/ac56d71cac049fd026ee1e8918bcb82d31192018/lib/deps/ajax/explainCors-browser.js#L5
suggests the couchdb server is not properly set up, but it is in my case.

I had to use the following instead to get couchdb _session cookie to work in my privileged Firefox OS App, which has systemXHR permission:

```javascript
    var myXHR = function () {
      var request;
      if (window.location.protocol == "app:") {
        request = new XMLHttpRequest({ mozSystem: true, mozAnon: true });
      }
      else {
        request = new XMLHttpRequest({ mozSystem: false, mozAnon: false });
      }
      return request;
    }
    var opts = {
      ajax: {
        xhr: myXHR,
        headers: { 'Cookie': cookie }
      }
    };
    var remoteDB = new PouchDB(destination + db._db_name, opts);
```

**Comment by mnewmedia** [comment]
I also get this error, and i have enabled cors. I get this message **only when i stop the live Synchronisation**.

**Comment by nickcolley** [comment]
Hey folks, sorry about the confusion, you can track this issue over here: https://github.com/pouchdb/pouchdb/pull/4190

**Comment by anaran** [comment]
@nickcolley At first I thought this isssue is a duplicate of issue #4190, but that's a pull request, not an issue report.

Therefor, shouldn't this issue remain open, until 4190 comes up with a better solution?

Else people will deem this issue closed, unless they read all the fine print.

**Comment by daleharvey** [comment]
We use issues and PR's pretty much interchangably, would have probably been easier to open a new issue once it got reported on the PR, but the discussion is already there and its easier to have the discussion in a single place.

**Comment by daleharvey** [comment]
And that discussion should really be here in fact you were right, confusing to be reviewing PR's that arent in progress, but yeh we can soften the error message and not show it in situations where it certainly isnt a cors issue (we can test whether the url matches document.host I think)

**Comment by nolanlawson** [comment]
According to https://github.com/pouchdb/pouchdb/pull/4190#issuecomment-137144008 there's no way to detect a CORS error from some other error. I'm thinking we might want to just remove the warning.

**Comment by anaran** [comment]
@daleharvey `document.host` ?
How about

```
>> location.protocol
<- "app:"
```

**Comment by daleharvey** [comment]
@anaran we can use document.host to verify the requested origin is not the current one, therefore CORS, the systemXhr confusion is a Firefox OS issue though and should likely be fixed there

**Comment by nickcolley** [comment]
Can we check for CORs headers?

**Comment by daleharvey** [comment]
Nope, its specifically designed to not be able to do that

**Comment by darobin** [comment]
Just a thought (that may well be entirely stupid): a CORS error is likely to only happen the first time that Pouch is used for a given domain, if syncs have worked before it's unlikely that CORS is the culprit. Maybe Pouch could store some form of `neverSynced` flag that it would clear on the first successful sync. If there's an error and syncing has never worked, CORS could be suggested?

**Comment by daleharvey** [comment]
That works as a test, but I think its a bit much work and complexity, we just wanted to give people a nudge in the right direction since it was an issue that comes up a lot, hopefully this fixes it enough for now

https://github.com/pouchdb/pouchdb/commit/f05e41206e61824a85461f24a654998f79d99342

Cheers for the feedback all
