### ISSUE TITLE
Add <input type="file"> example to the attachments guide

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4265]
Just had a heck of a time trying to explain to a user how to convert `<input type="file">` to a Blob usable by PouchDB. Took me forever to realize that a File *is* a Blob ([source](https://developer.mozilla.org/en-US/docs/Web/API/File)).

Anyway, I think this would be a neat demo for the attachments guide. Would be nice to also have a http://bl.ocks.org to go along with it; maybe just a nice little page where you can upload a file and it will store it in PouchDB, and then the page will show the file type and file size.

**Comment by nolanlawson** [comment]
So this issue would involve two major things:

1. A modification to the [attachments guide](http://pouchdb.com/guides/attachments.html), maybe after the "Image attachments" section, since that already had a pretty good example of working with images. The source code is [here](https://github.com/pouchdb/pouchdb/blob/master/docs/_guides/attachments.md).
2. A bl.ocks.org page (which is just a Github gist) containing an `index.html`; the guide already has plenty of them, so you can just copy-paste from that. You can make the `index.html` page do whatever you want, but try to make it fit the style of the other examples in the guide. :)

In order to work with the docs, you'll need to:

1. Clone PouchDB's source code
2. Install jekyll (`gem install jekyll`, may require `sudo`)
3. `npm install`
4. `npm run build-site`, which will then make it available at `localhost:4000`

**Comment by ntwcklng** [comment]
The example won't work on bl.ocks.org so i created a [JS Bin](https://jsbin.com/xerofo/edit?js,output)

**Comment by nickcolley** [comment]
@ntwcklng great work so far, what happened with your example in bl.ocks.org? Just thinking if we can fix it it'd be more consistent.

**Comment by ntwcklng** [comment]
Okay, i found a solution. Because the the Gist is loaded in an iframe, we only can access the elements with something like `document.querySelector("iframe").contentWindow.document.body.querySelector("#div")`
Should i update the example and create a working bl.ocks.org demo?

**Comment by nolanlawson** [comment]
Love the kitty! A few suggestions:

1. when you `putAttachment()`, there's no need to specify the `size`; PouchDB will infer that automatically.
2. I think it is maybe a bit confusing to add the `uploadedFile` variable, since it contains the same properties as `getFile`. Can we just work with `getFile`?
3. I tested out the `bl.ocks.org` issue, and it seems like we can work around it by waiting for the `DOMContentLoaded` event. E.g. see a working example here: http://bl.ocks.org/nolanlawson/26063cd7ba06d4b689e5

Other than that, this example look great, and I would love to see it added to the guide. Nice work! :)

**Comment by ntwcklng** [comment]
Nice, many thanks for the feedback!
I've made an updated bl.ocks.org example and made the code (hopefully) more readable.

**Comment by nolanlawson** [comment]
fixed by https://github.com/pouchdb/pouchdb/pull/4324
