### ISSUE TITLE
We modify the users document when they .put

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4273]

**Comment by daleharvey** [comment]
So this only fails when you try to save an object with a property `hasOwnProperty` because the clone will early return due to https://github.com/pouchdb/pouchdb/blob/master/lib/deps/clone.js#L9

**Comment by daleharvey** [comment]
So this is probably super easy or super hard, I tried copying the current jquery code but that breaks down with a `constructor` property

**Comment by daleharvey** [comment]
Ok will describe this in more detail. So users pass in objects to pouchdb to save, we do not want to modify those users objects with our metadata so we clone the object. Currently this works fine except when users give us weird objects that have 'constructor' or 'hasOwnProperty' user defined properties, you can see a failing test @ https://github.com/pouchdb/pouchdb/blob/4273/tests/integration/test.basics.js#L1020

Currently this fails because we copy and old version of jquery's clone in https://github.com/pouchdb/pouchdb/blob/master/lib/deps/clone.js, specifically we check for 'hasOwnProperty' property existing and if it is there, do not clone the object. If we try upgrading to the latest jquery clone, it also fails this time due to the `constructor` property, you can see the failure @ http://jsbin.com/bipedorimo/edit?js,console

Been trying a few different clone implementations right now, none seem to be able to handle this case

**Comment by daleharvey** [comment]
So https://www.npmjs.com/package/clone will strip the object of all these properties (possibly the way we might want to go)

**Comment by daleharvey** [comment]
Changing `clone.js` to 

```
  module.exports = function(obj) {
  if (typeof obj !== 'object') {
    return obj;
  }
  return Object.assign({}, obj);
};
```
Passes our test, but fails somewhere else in attachments, which will be fun

**Comment by daleharvey** [comment]
ok, test that is failing is `issue 2803 should throw 412 part 3` because `issue 2803 should throw 412 part 1` modified the contents of `binAttrDoc`

**Comment by daleharvey** [comment]
dumb mistake, Object.assign is shallow

**Comment by daleharvey** [comment]
and JSON.stringify will not work because we use this function to clone various things that include functions. Also assuming we need clone for `_attachments` where we would like to save blobs directly in indexeddb

**Comment by ermouth** [comment]
When I made custom PouchDB fork after known events, I had to embed two cloners to solve this problem. One works fine for Safari (I experirenced troubles with .constructor in it), and second – in other browsers.

This approach is far from being elegant, but it works, at least for my tasks.

**Comment by daleharvey** [comment]
Yeh I was about to go down that route, mostly because I didnt want to touch the clone function myself and was assuming one would support these things out the box, but got a fix for this now - https://github.com/pouchdb/pouchdb/commit/c5c43cb4124b5cb92e3d25faa28fa00ca54d6682

**Comment by nolanlawson** [comment]
All of this cloning (especially of binary data) can't be great for performance, but I guess it's better to be safe and not give users surprising results in case they do mutate the objects after storing them. So yeah, let's do it.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/338ccf97140ee8b8a8d25ca7dc0f52bdebf518b6
