### ISSUE TITLE
Gender Specific Language

### ISSUE THREAD

**Issue by Charlotteis** [pouchdb/pouchdb#4278]
Running [alexjs](https://github.com/wooorm/alex) over pouchdb I found some gender specific language we could get rid of. I will do that now!

**Comment by daleharvey** [comment]
So replying to https://github.com/pouchdb/pouchdb/pull/4279#issue-105024186

The documentation ones were pretty clear but the blog post instances less so, in those cases we referring to someone who fairly sure identifies themselves as cis male, is it still better to use gender neutral by default there? seems sensible

Not entirely sure what the suitable replacement for crazy in this context is? 

And the last issue is one of those is a quote, assuming that part should be reworded a little to not be a quote to remove it

**Comment by Charlotteis** [comment]
For the `pouchdb-levels-up` post, if Nick identifies as Male I see no real need to change it. If unsure, 'they' never hurts.

```diff
- What would have sounded like a crazy dream
+ What would have sounded like a dream
```

```diff
- Or whatever other crazy combination you can cook up!
+ Or whatever other combination you can cook up!
```
---
For the `secondary-indexes` post:
```diff
- the doc ID will be a crazy string
+ the doc ID will be a string
```

```diff
- he described it as "crazy slow."
+ they described it as "crazy slow."
```

Not sure what to do with that last one there with regards to the 'crazy'. Perhaps we leave it in as it is a quote? I'd rather get rid of it but I'm not sure on a good alternative.

**Comment by nolanlawson** [comment]
Sounds like you've made a lot of headway here; good to close the issue @Charlotteis ?

**Comment by Charlotteis** [comment]
Yup! Thanks @nolanlawson :)
