### ISSUE TITLE
Timing of .changes() events & promises

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb#4286]
In PouchDB's current implementation, events by `.changes()` are triggered _after_ a promise of methods like `.put`, `.post` etc that cause the change resolve

Example:

```js
var db = new PouchDB('test')
db.changes({ since: 'now', live: true }).on('change', function () { console.log('change triggered') })
db.post({}).then(function () { console.log('promise resolved') })
// promise resolved
// change triggered
```

I would expect that "change" events would be triggered as they happen, and the promise gets only resolved afterwards.

The timing [caused an issue with our Hoodie APIs](https://github.com/hoodiehq/pouchdb-hoodie-api/issues/54). We used to listen to PouchDB's .changes() feed to keep state of changes in the local database that have not yet been replicated to a remote database, a typical offline first usecase. 

Due to the timing of events vs. promise settlements, we saw this

```js
store.add({id: 'test'}).then(function() {
  store.hasLocalChanges('test')
  // should be true, but is false at this point, because "change"
  // events are triggered before "store.add" resolves.
})
```

We [worked around the issue](https://github.com/hoodiehq/pouchdb-hoodie-api/pull/56/files) by not listening to the `.changes()` feed at all, and instead triggering all the events ourselves when the respective methods like `store.add`, `store.remove` etc are called. I hated this change and it keeps causing problems that woudln't exist if we simply could listen to `.changes()` events instead.

So from our perspective it would be worth to look into how PouchDB is implementing the events vs. promise settlements, and if it's possible to change the order of them. I could imagine it wouldn't even break tests, but it would potentially break apps which depend on the current timing, so this change, if possible & accepted, would need a major version bump.

If you could point me to the right places where events are triggered and promises of `.post` etc are resolved, that'd be much appreciated.

**Comment by gr2m** [comment]
Okay, I found out that the issue most likely is, that `db.changes` needs an intialisation, but once that is done, the events get triggered before the promise gets resolved. 

This behaves as expected

```js
var db = new PouchDB('test')
db.changes({ since: 'now', live: true }).on('change', function () { console.log('change triggered') })
setTimeout(function () {
  db.post({}).then(function () { console.log('promise resolved') })
})
// change triggered
// promise resolved
```

**Comment by gr2m** [comment]
More information. My question in nutshell is the order of event triggered / promise resolved is different here:

```js
var db1 = new PouchDB('test1')
db1.changes({ since: 'now', live: true }).on('change', function () { console.log('db1 change triggered') })
db1.post({}).then(function () { console.log('db1 promise resolved') })
// db1 promise resolved
// db1 change triggered

var db2 = new PouchDB('test')
db2.changes({ since: 'now', live: true }).on('change', function () { console.log('db2 change triggered') })
setTimeout(function () {
  db2.post({}).then(function () { console.log('db2 promise resolved') })
})
// db2 change triggered
// db2 promise resolved
```

Note: the order of example 1 is only wrong on the first run. When run again, the order is correct

```js
// when run again, order is correct
var db1 = new PouchDB('test1')
db1.changes({ since: 'now', live: true }).on('change', function () { console.log('db1 change triggered') })
db1.post({}).then(function () { console.log('db1 promise resolved') })
// db1 change triggered
// db1 promise resolved
```

**Comment by gr2m** [comment]
I've tried @nolanlawson's patche here, but the issue remains:
https://gist.github.com/nolanlawson/116aaa2600642b5a55ab

**Comment by gr2m** [comment]
closing this issue because my comments are more confusing than helpful right now

**Comment by nolanlawson** [comment]
What about

```
var changed;
var posted;

function checkDone() {
  if (changed && posted) {
    // both callback were called, do something...
  }
}

db.changes({live: true}).on('change', function (change) {
  changed = true;
  checkDone();
});
db.post({}).then(function (res) {
  posted = true;
  checkDone();
});


```

**Comment by manikandan07081995** [comment]
@nolanlawson  In my case data change asynchronously happen, Even DB.sync completed. How can I set changes completion sync completed?
