### ISSUE TITLE
Minor enhancement to sync() to support to/from replication options (e.g. filters)

### ISSUE THREAD

**Issue by tohagan** [pouchdb/pouchdb#4289]
Would be nice if the sync() opts could include to/from specific options that are combined with the other "root" options.  Here's the code change to sync() 

      var optsPush = utils.extends({}, opts, opts.to);
      var optsPull = utils.extends({}, opts, opts.from);
  
      // deleted are not strictly needed 
      delete optsPull.to;  
      delete optsPull.from;
      delete optsPush.to;
      delete optsPush.from;

      this.push = replicate(src, target, optsPush);
      this.pull   = replicate(target, src, optsPull);

**Comment by daleharvey** [comment]
Yup, right now you can do this by constructing seperate db object, but agree that we should add this, and probably should have done instead of pass all the options to both db's

**Comment by nickcolley** [comment]
@tohagan if you have the time do you fancy doing a PR? Let us know :)

**Comment by tohagan** [comment]
Yes sorry I should have done that :). 

FYI ... I've just watched [Nolan's videos on Pouch internals](https://www.youtube.com/watch?v=ven5f4wCE4k).

**Comment by nickcolley** [comment]
I didn't mean any pressure just if you were interested we could help out! :+1:

**Comment by tohagan** [comment]
I'm going to have a crack doing a PR for this one as I need it rather badly for an app.

Did you want test to be added to tests/integration/test.sync.js or somewhere else?
Not sure it will be an integration test.

**Comment by daleharvey** [comment]
I think `tests/component` would be a good place for this, we just need to test that the correct options get sent to the constructor

**Comment by tohagan** [comment]
Sure ... I wonder if that might be the case.  Thanks Dale.

**Comment by tohagan** [comment]
Dale .. what are you using for spying on function calls?

I'm used to using Jasmine 2.x that has spy features but you're using Mocha for unit testing.

You could add [Sinon](https://github.com/mochajs/mocha/wiki/Spies).
But would need to add this lib to your package.json

**Comment by nolanlawson** [comment]
We're not using spies, but I'm fine with adding Sinon as a devDependency if you really want it for the tests.

**Comment by daleharvey** [comment]
Yup sorry I missed you in IRC but thats totally fine by me

**Comment by tohagan** [comment]
Well after all that messing around looks like Sinon won't work because the replicate() function defined inside sync.js is already bound - so too late for a spy() to work.  Can't think of a way to unit test that - but I checked using console.log() that correct options are being set and it's fairly trivial change.  Will PR a slightly improved version.

**Comment by tohagan** [comment]
And I also changed the code to use opts.push and opts.pull rather than to/from

**Comment by tohagan** [comment]
Note that since Sinon failed to deliver it was not added by this PR - so no package.json change.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/2849b2599e60c1ed9512b4fb0168772d57ff0145
