### ISSUE TITLE
Dont show cors message when xhr has aborted

### ISSUE THREAD

**Issue by OleRoel** [pouchdb/pouchdb#4300]
With CouchDB 4.0.1 I see a lot of CORS messages in Chrome and FF when checking for changes on remote DB with:

```javascript
db.changes({
        since: 'now',
        live: true,
        include_docs: true
      }).on('change', function(change) {...});
```

In the browser console I see the CORS messages only in conjunction with XHR requests polling for changes:

http://1.2.3.4/couchdb/my_user_db/_changes?timeout=15000&style=all_docs&feed=longpoll&since=3391&limit=99&_nonce=1441809968578

The request header looks like:
```http
GET /couchdb/my_user_db/_changes?timeout=15000&style=all_docs&feed=longpoll&since=3396&limit=100&_nonce=1441811168273 HTTP/1.1
Host	1.2.3.4
Accept	application/json
Origin	http://localhost:3333
User-Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2498.0 Safari/537.36
Referer	http://localhost:3333/
Accept-Encoding	gzip, deflate, sdch
Accept-Language	de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
Cookie	csrftoken=6zzhnMx3qJT63AHlC7AdfwSuvvayPugX; AuthSession=dXNlci00QUZRMEctOGUxMDA0ZDktOTZkOS00Y2U3LTkxMWEtYTQ5N2NhNWQ0ZjVjOjU1RjA0QkE2Ov_tRTIPFUC_Ed-TGgfqk8pdwaeo
```

My guess is, that `Access-Control-Request-Method` and `Access-Control-Request-Headers` my be missing in the request header.

All other request to the remote CouchDB are looking fine.

**Comment by nickcolley** [comment]
Hello @OleRoel !

You can check here for steps to make sure CORs is sorted: http://pouchdb.com/errors.html#no_access_control_allow_origin_header

If that doesn't work can you copy paste any errors you're having in your dev tools console?

Thanks!

**Comment by OleRoel** [comment]
@nickcolley 

CORS is enabaled on CouchDB. All requests from PouchDB to my CouchDB instance go through except the _changes requests. I also changed the headers entry in the cors section to fit the example in [No 'Access-Control-Allow-Origin' header](http://pouchdb.com/errors.html#no_access_control_allow_origin_header). So everything should be set up as described in that link.

I am sorry, but I have no more logs to show here, since the only statement I see in the console is the one described in the common errors link. The output happens whenever the [changes](http://pouchdb.com/api.html#changes) callback fires.

Since some CORS header entries seems to be missing in the _changes request I would think that there is a bug in the XHR code.

**Comment by OleRoel** [comment]
Here is a recorded request/reponse HTTP header pair for a request blocked by CORS:

Request:
```http
GET /couchdb/my_user_db/_changes?timeout=15000&style=all_docs&feed=longpoll&since=3495&limit=100&_nonce=1441867287996 HTTP/1.1
Host: 1.2.3.4
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:39.0) Gecko/20100101 Firefox/39.0
Accept: application/json
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://localhost:3333/
Origin: http://localhost:3333
Cookie: csrftoken=C0KdaDVXFgN2Noy2YbASHDaf8JXtyUyD; sessionid=3g66elhq2vtps8fx49ms8uy2e744eqdt; AuthSession=dXNlci00QUZRMEctOGUxMDA0ZDktOTZkOS00Y2U3LTkxMWEtYTQ5N2NhNWQ0ZjVjOjU1RjEyNzBBOu3zUHz5xytOIEE8h3ZCB8JNDYsH
Connection: keep-alive
```

Response:
```http
HTTP/1.1 200 OK
Server: nginx/1.9.0
Date: Thu, 10 Sep 2015 06:45:35 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: must-revalidate
Access-Control-Expose-Headers: Cache-Control, Content-Type, Server
Access-Control-Allow-Origin: http://localhost:3333
Access-Control-Allow-Credentials: true

{"results":[

],
"last_seq":3495}
```

FF says (in German):
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://1.2.3.4/couchdb/my_user_db/_changes?timeout=15000&style=all_docs&feed=longpoll&since=3495&limit=100&_nonce=1441867287996. (Grund: CORS-Anfrage fehlgeschlagen).

Google Translate translates:
Source Cross (Cross-Origin) blocked request: The same source rule prohibits reading of the external resource on http://1.2.3.4/couchdb/my_user_db/_changes?timeout=15000&style=all_docs&feed=longpoll&since=3495&limit=100&_nonce=1441867287996. (Reason: CORS request failed).

The same happens in Chrome. And I am extremly confused now.

**Comment by daleharvey** [comment]
You are seeing the responce though? is your application broken in any other way? it looks like the error is being misreported (which happens with CORS)

**Comment by OleRoel** [comment]
@daleharvey 
Yeah, I think it must be a false positive and the bug lies somewhere in my code. What makes me wonder is that FF reports the problem as a CORS issue in the console besides the message comming from PouchDB. Is there a way to emulate CORS blocking in Javascript?

I am absolutely fine if this issue gets closed, since I seem to be the only one with this problem.

**Comment by OleRoel** [comment]
I can reproduce the CORS message creating an object in PouchDB, then replicating from remote CouchDB, then enabling live sync. An object with the same id already exists on the remote DB.
After a while a CORS message is spit out while syncing.

When I do a sync without a prior replication every object synced to my local PouchDB seems to create a CORS message. I have a change handler enabled, but commented out the code inside it.

The test is running with the PouchDB In-memory adapter


The sync still creates a lot of network traffic for minutes(?) after a full replication.

**Comment by daleharvey** [comment]
yeh I am fairly certain that request is just being aborted and then the browser (and us) will misreport it as a cors error

I meant are you seeing an actual bug, are there things not being synced etc? if its just a console warning showing up, there is a good chance that there is nothing wrong

**Comment by OleRoel** [comment]
I am quite certain that this is not a bug, but only a lot of irritating messages written to the console. The sync actually happens. I will confirm this tomorrow and report here, what my findings are.

**Comment by daleharvey** [comment]
ok, I am fairly certain there is bug where we still misreport cors errors when we manually abort your CORS request, but it would be useful to know if the browser is also misreporting them, Ill do a test tomorrow too

**Comment by OleRoel** [comment]
The cors messages are not showing up anymore. This happens after doing a compaction on CouchDB and enabling auto_compaction on PouchDB. I had an object which blew up from some KB to 2 MB data with > 40 revisions and took at least 10 second processing (-> writing to in memory database) after replication on a MBP (it brought iPad and Android to standstill for at least 10 minutes). I think that this certain object was the culprit for my problems with CORS and perfomance.

Currently I am learning Couch/PouchDB internals the hard way.

**Comment by ssured** [comment]
I experience the same new CORS messages as OleRoel describes.

When breakpointing, I could track down one situation. When a replication is cancelled, this line
https://github.com/pouchdb/pouchdb/blob/22ed9da3f1677a4f7b99db93db44df495bd25dd1/lib/deps/ajax/request-browser.js#L193 will call https://github.com/pouchdb/pouchdb/blob/4ed6704f78fb75d80475390e40e2d86bf3e6d7f5/lib/deps/ajax/ajaxCore.js#L96

To me this seems as if PouchDB is too eager to explain an XHR error as a CORS problem

**Comment by daleharvey** [comment]
Yup, edited the title and will get that fix

**Comment by ssured** [comment]
Awesome +1

**Comment by daleharvey** [comment]
So this got fixed by introducing heartbeat, it used to be we would manually kill the connection after TIMEOUT seconds with an error that was indistinguishable from CORS, but we no longer do that - https://github.com/pouchdb/pouchdb/commit/db6eadc3dee6109381319a829955fc8d3137c107
