### ISSUE TITLE
Is database creation in Node fully synchronous?

### ISSUE THREAD

**Issue by danse** [pouchdb/pouchdb#4301]
I am using Pouch in a test suite, and tests fail always the first time i run them _with a new database name_. Here i am talking about a local name, as in:

    var db = new PouchDB('test-database-1')

When run the second time with the same database name, they will succeed. Before the second run, database files will already be present in the file system. I think that the cause of the first failure might be that some parts of database creation are not fully synchronous, and thus they do not happen before the rest of the test suite runs. Is it possible, or am i totally on the false track?

I am using Pouch `3.6.0` and Node `0.10.38`, i can provide any kind of details if helpful

**Comment by jo** [comment]
The PouchDB constructor is asynchronous and returns a promise, which delays further api calls until the database is ready. How does your test look like?

**Comment by daleharvey** [comment]
As @jo said the database creation (at the level below pouchdb) is asynchronous virtually all the time, however pouchdb exposes a synchronous constructor and will automatically handle any of the async details behind the scenes.

You should never need to worry about the timing of db creation and 'var db = new PouchDB('test')` should work every time, there are problems with the promise api exposed by the pouchdb constructor so I would recommend not using that or the callback mechanism and only using the sync constructor.

The sync constructor is very well tested however, so I dont think what your seeing is an obvious bug, if you could provide any more details about what and how its failing it would be very helpful, thanks

**Comment by danse** [comment]
Luckily i am working on open source so i can directly point to the issue. The test suite [here](https://github.com/eHealthAfrica/sense-dispatch/pull/19) is failing. In the test suite i am [creating a database](https://github.com/danse/sense-dispatch/blob/9adac351746f25da0f886d3867de9bc7d3e6d0e4/test/main/lib.js#L92) and adding a fixture, and trying to fetch my fixture again [right after this](https://github.com/danse/sense-dispatch/blob/9adac351746f25da0f886d3867de9bc7d3e6d0e4/test/main/lib.js#L98). The test fails just when it is run the first time.

Before going ahead with this i should probably update to the latest version of Pouch

**Comment by danse** [comment]
I updated to the last version and got an error about the use of `finally` in my fixture code ... i experimented a bit with the promise implementation and found the correct way to handle the case of a missing document in a chain of promises in the set up code, that was the cause of the issues. Thanks a lot for the fast response! Now struggling with #4131 :wink:
