### ISSUE TITLE
PouchDB hangs when disk is full

### ISSUE THREAD

**Issue by flimzy** [pouchdb/pouchdb#4309]
This may be an issue with other methods, but I've only tried it with `info()`.  Here's my sample code:

    var PouchDB = require('pouchdb');
    PouchDB.debug.enable("*");
    db = new PouchDB('flashback');
    db.info(function() {
        console.log("in callback")
    })

A successful run looks like this on the JS console:

> pouchdb:adapter Picked adapter: idb +0ms  
> pouchdb:api flashback +19ms info  
> pouchdb:api flashback +151ms info  
> pouchdb:api flashback +2ms info success Object {doc_count: 0, update_seq: 0, idb_attachment_format: "binary", db_name: "flashback", auto_compaction: false…}  
> pouchdb:api flashback +1ms info success Object {doc_count: 0, update_seq: 0, idb_attachment_format: "binary", db_name: "flashback", auto_compaction: false…}  
> in callback

If I do the exact same thing with the disk full:

> pouchdb:adapter Picked adapter: idb +0ms  
> browser.js:112 pouchdb:api flashback +23ms info

Naturally, I'm not expecting PouchDB to function when the disk is full. But if it's at all possible to detect the failure, that would be good, if that's possible.  In a worst-case scenario, perhaps a timeout could be a last resort?

FTR, I'm using Chromium 43.0.2357.124 on Debian Linux 8.1.

**Comment by daleharvey** [comment]
Yup its a bug that we dont respond to this properly, we have a bug tracking this with tests etc so duping against that one, cheers - https://github.com/pouchdb/pouchdb/issues/4018

**Comment by flimzy** [comment]
Thanks, @daleharvey. I searched, but somehow missed that duplicate bug.
