### ISSUE TITLE
Firefox: specify persistent storage

### ISSUE THREAD

**Issue by scottmtp** [pouchdb/pouchdb#4315]
Firefox has a non-standard API for specifying persistent storage when opening an IndexedDB. It would be helpful to expose this in PouchDB.

See:
https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/open

**Comment by scottmtp** [comment]
I updated the PR to fix the line length in case that's helpful. Also, it is not clear to me how I'd be go about testing this change, but if anyone has thoughts about how to test, I'd be happy to update the PR with tests as well.

**Comment by daleharvey** [comment]
This is pretty much impossible to test so I am happy enough without a test, this is great thanks. One thing that will likely need following up is a note in the documentation.

https://github.com/pouchdb/pouchdb/commit/eeb6a242ac63f52b44606e956b5d3aec5750c331

Thanks
