### ISSUE TITLE
sync()/replication() - A race condition with API design can miss subscribed events

### ISSUE THREAD

**Issue by tohagan** [pouchdb/pouchdb#4317]
I think there is a race condition due to the API design of both `PouchDB.replicate()` and `db.sync()`. 

This is because you configure and *start* the replication before you get a chance to subscribe to the emitted events. Hence there is the real risk of missing an event like 'completed', 'error', 'denied' or 'change'.  The solution is to introduce a `start()` method that allows the developer to delay emitted events until the subscriptions have completed and only permit the replicate() and sync() methods to *configure* the replications not execute them. 

Example API v1: 

     var rep = PouchDB.replicate('mydb', 'http://localhost:5984/mydb', {
       live: true,
       retry: true
     }).on('change', function (info) {
       // handle change
     }).on('paused', function () {
       // replication paused (e.g. user went offline)
     }).on('active', function () {
       // replicate resumed (e.g. user went back online)
     }).on('denied', function (info) {
       // a document failed to replicate, e.g. due to permissions
     }).on('complete', function (info) {
       // handle complete
     }).on('error', function (err) {
       // handle error
     })
     
     rep.start();   // Start replication only once the on() events are ALL subscribed.
  
     rep.cancel(); // whenever you want to cancel 

Same for the `sync()` example.

**Comment by tohagan** [comment]
A short term fix for the current API would be to introduce a timeout delay to starting replication that would cure the problem imperfectly but pragmatically for most current software that depends on the current APIs.

**Comment by tohagan** [comment]
Hmm ... Since `start()` now returns the Promise you might also want it to return the cancellation handle.

     var rep = PouchDB.replicate('mydb', 'http://localhost:5984/mydb', {
       live: true,
       retry: true
     }).on('change', function (info) {
       // handle change
     }).on('paused', function () {
       // replication paused (e.g. user went offline)
     }).on('active', function () {
       // replicate resumed (e.g. user went back online)
     }).on('denied', function (info) {
       // a document failed to replicate, e.g. due to permissions
     }).on('complete', function (info) {
       // handle complete
     }).on('error', function (err) {
       // handle error
     });
     
     var instance = rep.start();   // Start replication only once the on() events are ALL subscribed.
  
     instance.cancel(); // whenever you want to cancel

**Comment by tohagan** [comment]
FYI ... I'm currently building a generic wrapper class around that will allow me to stop/start syncing and maintain event subscriptions between start()/cancel()/start() as the API permits restarting when the configuration changes. I'm now not using sync() as I need tighter control on filtering and events that the current API does not offer.  It will have options to either run in different modes:

- remote mode = Remote DB, No replication, Watch/Proxy db.changes() events
- local mode = Local DB, No replication, Watch/Proxy db.changes() events
- sync mode = Local and Remote DB, start up with single pull replication (load) then live push & pull (sync), Watch load pull events then watch sync push/pull replication events

The key things I got out of this experience:

- Need to set different filters (and options) on push and push side of the sync() #4289 . 

- Need to detect when a live sync has initially completed. This typically indicates when an app is ready to start as otherwise it may have an incomplete copy of the remote dataset. Thanks for #4266  answer Dale.  

- Found this subscription race condition issue. 

- Need to be able to start() ... then safely cancel() then start() again without loosing event subscriptions.  Needs some care with redesign of this API.

- Need to ignore start() when starting or already started, Need to ignore cancel() when already cancelled or cancelling - but still return Promises from these that work or else throw/reject() to prevent this.

**Comment by nolanlawson** [comment]
> A short term fix for the current API would be to introduce a timeout delay to starting replication that would cure the problem imperfectly but pragmatically for most current software that depends on the current APIs.

Actually a delay is not necessary; it's just necessary to ensure that anytime any one of those events are emitted, it's in the *next* turn of the event loop. I.e. a simple fix would be:

```
PouchDB.prototype.replicate = function () {
  var handler = ...;
  setTimeout(function () {
    // do everything that may emit here
  });
  return handler;
}
```

So rather than change the API to add `start()`, I think we should be able to just track down the bug that is causing events to be emitted too early. Do you have a test case to repro, or do you know which event it was that was firing too early?

**Comment by tohagan** [comment]
Firstly, my conclusion was based purely on code inspection (I don't have any test case proof) as yet. 
It would need some considerable work on my part to create a stress/regression test that would induce the race condition. 

My main reasoning was that you should always follow this pattern for event subscription:

A. Create handle.
B. Register events on handle
C. Start emitting events

The current API design looked like it could not guarantee B then C.  However, your fix looks like it will avoid the need to change the API and still make this guarantee so that's excellent!  Phew!

I wonder if you might consider introducing an option like `{ autostart: true }`  that defaults to `true`. This would then be backward compatible with current API but not force the developer to rely on the next event loop behaviour by allowing them to set this value to `false` and later calling `handle.start()`:

PouchDB.prototype.replicate = function () {
  var handler = ...;
  if (opts.autostart)  {
    setTimeout(handler.start);
  }
  return handler;
}

Future code maintenance would IMHO be safer by not relying on the next turn' behaviour as this is not evident from the API and I think it could lead to bugs that are hard to reproduce or identify if the subscription was separated from creating the Replication object.  I think the developer guide certainly would need a warning if you rely on this.

**Comment by nolanlawson** [comment]
Thanks, and I definitely appreciate somebody giving the code a deep look, and this is indeed one of those weird obscure-ish JavaScript edge cases.

`setTimeout(function () {}, 0)` or `process.nextTick(function () {})` in Node definitely don't incur a performance cost; they just say "finish up whatever is left in this turn of the event loop and then wait for the next tick of the loop to do something else". In this case, the "whatever is left" ends up being all the user's `.on()` and `.once()` calls.

In general I'm hesitant to add a new option, because it complicates the API and I'm not sure it's solving a problem most users will face. The behavior described above is pretty standard Node EventEmitter stuff, and I've yet to see a user get confused because they did something like

```js
var changes = db.changes({live: true});
$.ajax('foo.com', function () {
  requestAnimationFrame(function () {
    img.onload = function () {
      // do a bunch of other async stuff...
      changes.on('change', function () {...})
    };
  });
});
```
I.e. usually people just immediately attach the `.on` listeners. And if they did do something weird like the above, then they might miss some events, and I don't think they'd be surprised by that.

**Comment by nolanlawson** [comment]
OK, so I just confirmed that there is indeed no race condition. [This part of the code](https://github.com/pouchdb/pouchdb/blob/d9e9726f6cc3a9b7a1b00408d9e333c586b5a64a/lib/utils.js#L93-L138) wraps all adapter calls, so PouchDB doesn't even start any of its adapter-specific `changes()` logic until the current turn of the event loop has finished.

**Comment by tohagan** [comment]
Excellent .. Thanks.
