### ISSUE TITLE
Unable to upgrade Travis to container-based due to OOM in Istanbul

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4321]
We would like to upgrade to the new container-based Travis system, but unfortunately Instanbul fails with an out-of-memory. See https://github.com/pouchdb/pouchdb/pull/4312#issuecomment-139645784 and https://github.com/pouchdb/pouchdb/pull/4250 for the backstory.

**Comment by nolanlawson** [comment]
Jobs that reproduced this:

* https://travis-ci.org/pouchdb/pouchdb/jobs/79838632
* https://travis-ci.org/pouchdb/pouchdb/jobs/78384248
* https://travis-ci.org/pouchdb/pouchdb/jobs/78384249

**Comment by nolanlawson** [comment]
@daleharvey What's the status of this? Did we file an issue on Travis? Can't remember.

**Comment by daleharvey** [comment]
hrm I thought we did but cant find it, either way the legacy infrastructure is completely busted right now so we will likely need to upgrade even if it means losing coverage for now

**Comment by nolanlawson** [comment]
:(

**Comment by daleharvey** [comment]
And upgraded - https://github.com/pouchdb/pouchdb/commit/203044c9824d8eb444640df12a8ea1b69260103e
