### ISSUE TITLE
node v4, my tests do no longer succeed

### ISSUE THREAD

**Issue by oliviertassinari** [pouchdb/pouchdb#4322]
I have created a [repository](https://github.com/oliviertassinari/pouchdb_bug) to reproduce the bug in a simpler case.
The test on [travis](https://travis-ci.org/oliviertassinari/pouchdb_bug) fail with a timeout.
I have no idea why.

**Comment by calvinmetcalf** [comment]
Try adding this to the .travis.yml
https://github.com/nodejs/node/issues/2798#issuecomment-139356961

**Comment by nolanlawson** [comment]
This should also be fixed in 4.0.2 when we have the new leveldown prebuilds, so you won't even need to recompile leveldown from scratch anymore.

**Comment by oliviertassinari** [comment]
- `CC=clang CXX=clang++ npm_config_clang=1` [fail](https://travis-ci.org/oliviertassinari/pouchdb_bug/builds/80014661)
- `CXX=g++-4.8` [fail](https://travis-ci.org/oliviertassinari/pouchdb_bug/builds/80014985)

> This should also be fixed in 4.0.2
Awesome

**Comment by oliviertassinari** [comment]
I can't make it work with the gcc options. I'm gonna use `memdown` for running my test.
Should probably be faster too.
Thanks for your help.
