### ISSUE TITLE
destroy() doesn't (always?) accept an options argument, as documented

### ISSUE THREAD

**Issue by flimzy** [pouchdb/pouchdb#4323]
The `destroy()` method is [documented](http://pouchdb.com/api.html#delete_database) to take two optional arguments:

    db.destroy([options], [callback])

However, when I pass an options argument, my code crashes.  The documentation does mention that the `ajax` key in `options` is only used for remote databases, so I tried doing the same with a remote database call, and I get the same result.  Is the `options` argument now obsolete, and should it be removed from the documentation?  Or am I somehow using it incorrectly?

Note that I'm passing an empty options argument, and I would expect this to simply be ignored, the same as it is when passed to `new PouchDB()`.  But maybe that's an unwarranted expectation?

My code:

    var PouchDB = require('pouchdb');
    var db = new PouchDB("testdb")
    db.destroy({}, function() {
        console.log("in the callback")
    })

And the output:

    $ nodejs ./x.js 

    /home/jonhall/go/src/github.com/flimzy/go-pouchdb/node_modules/pouchdb/lib/adapter.js:806
        callback(null, resp || { 'ok': true });
        ^
    TypeError: object is not a function
        at /home/jonhall/go/src/github.com/flimzy/go-pouchdb/node_modules/pouchdb/lib/adapter.js:806:7

And my code with a remote db call instead of local:

    var PouchDB = require('pouchdb');
    var db = new PouchDB("https://xxxx:xxxx@xxxx.iriscouch.com/asdf")
    db.destroy({}, function() {
        console.log("in the callback")
    })

And the very similar (but more verbose) output:

    $ nodejs ./x.js 

    TypeError: object is not a function
        at /home/jonhall/go/src/github.com/flimzy/go-pouchdb/node_modules/pouchdb/lib/adapter.js:806:7
        at /home/jonhall/go/src/github.com/flimzy/go-pouchdb/node_modules/pouchdb/lib/adapters/http/index.js:1033:7
        at onSuccess (/home/jonhall/go/src/github.com/flimzy/go-pouchdb/node_modules/pouchdb/lib/deps/ajax/ajax-core.js:51:5)
        at Request._callback (/home/jonhall/go/src/github.com/flimzy/go-pouchdb/node_modules/pouchdb/lib/deps/ajax/ajax-core.js:118:7)
        at Request.self.callback (/home/jonhall/go/src/github.com/flimzy/go-pouchdb/node_modules/pouchdb/node_modules/request/request.js:123:22)
        at Request.emit (events.js:98:17)
        at Request.<anonymous> (/home/jonhall/go/src/github.com/flimzy/go-pouchdb/node_modules/pouchdb/node_modules/request/request.js:877:14)
        at Request.emit (events.js:117:20)
        at IncomingMessage.<anonymous> (/home/jonhall/go/src/github.com/flimzy/go-pouchdb/node_modules/pouchdb/node_modules/request/request.js:828:12)
        at IncomingMessage.emit (events.js:117:20)

Note that if I eliminate the options argument to `destroy()`, in both cases the code works as expected.

**Comment by nolanlawson** [comment]
Thanks for reporting! This was fixed by https://github.com/pouchdb/pouchdb/commit/2995c925fa57f8996be09a337803a5f4b6b3b3a1 and will be released in 4.0.2.

**Comment by flimzy** [comment]
Ah great, thanks!

A point of clarification: If I understand that diff properly, opts is never actually used in destroy(), is this correct? I suppose it's being accepted only to provide consistency with the other method signatures?

**Comment by daleharvey** [comment]
Thats true, there were previously no options used in destroy, in https://github.com/pouchdb/pouchdb/commit/3c964adbfb9a187af79d1685d63497bdc6b9ecc6 however we have added the ability to specify `ajax` options pertaining to the deletion request

**Comment by flimzy** [comment]
That's what I needed to know. Thanks. :)
