### ISSUE TITLE
HTTP Stateless constructor is a breaking change

### ISSUE THREAD

**Issue by colinskow** [pouchdb/pouchdb#4325]
I use PouchDB's HTTP constructor to create databases and then expect that database to be there. It goes against semantic versioning to bring this in now.

It would be much better to enable this through an option, e.g. `{ stateless: true }` to avoid breaking existing builds made for PouchDB "~4.0.0".

Here is a test that passes with 4.0.1 but fails with 4.0.2:

```js
'use strict';

var BPromise = require('bluebird');
var PouchDB = require('pouchdb');
var request = require('superagent');
var expect = require('chai').expect;

describe('PouchDB create and destroy', function() {

  it('should correctly create and destroy a database', function(done) {
    var testDB = new PouchDB('http://localhost:5984/pouchdb-destroy-test');
    testDB
      .then(function() {
        return checkDBExists('pouchdb-destroy-test');
      })
      .then(function(result) {
        console.log('Database should exist');
        console.log(result);
        expect(result).to.equal(true);
        return testDB.destroy();
      })
      .then(function() {
        return checkDBExists('pouchdb-destroy-test');
      })
      .then(function(result) {
        console.log('Database should NOT exist');
        console.log(result);
        expect(result).to.equal(false);
        done();
      })
      .catch(function(err) {
        done(err);
      });
  });

});

function checkDBExists(dbname) {
  var finalUrl = 'http://localhost:5984/' + dbname;
  return BPromise.fromNode(function(callback) {
    request.get(finalUrl)
      .end(callback);
  })
    .then(function(res) {
      var result = JSON.parse(res.text);
      if(result.db_name) {
        return BPromise.resolve(true);
      } else {
        return BPromise.resolve();
      }
    }, function(err) {
      if(err.status === 404) {
        return BPromise.resolve(false);
      } else {
        return BPromise.resolve();
      }
    });
}
```

**Comment by daleharvey** [comment]
So I cant think of a test that you can do that would go purely via the public api that would cause a test failure which is why this is arguably not a breaking change, if you go around pouchdb to test the internal implementation then yeh its definitely a change in behaviour but not in the API.

The next release will be a 5.0 for sure, if you do depend on the current behavior then you can switch to `testDB.info().then(function() {`, apologies for the hassle

**Comment by nickcolley** [comment]
This also breaks

https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/tests/specs/clear.js

https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/clear.js

**Comment by nolanlawson** [comment]
I tend to agree with Dale; the pattern

```js
new PouchDB('foo').then(function (db) { ... })
```

or

```js
new PouchDB('foo', function (err, db) { ... })
```

i.e. the database being a promise for itself, has been undocumented for a long time because we plan on removing it. It causes issues with circular dependencies in some promise implementations (e.g. bluebird) and was not a great design choice. 

So technically 4.0.2 is not a breaking change, but I agree it seems to have caused you some headaches - sorry about that. Does `new PouchDB('foo').info()` solve the issue?

**Comment by nickcolley** [comment]
Not sure if it's related but I'm updating the hoodie tests to 4.0.2 and getting a new failure here:

https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/tests/specs/clear.js

https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/clear.js

**Comment by colinskow** [comment]
So if I do do `new PouchDB('https://mydb.cloudant.com').info().then(...)` does that make exactly one HTTP request? I'd like to do it in the most efficient way possible.

I had been going off your docs which say "This method creates a database or opens an existing one."

**Comment by nolanlawson** [comment]
`info()` doesn't do exactly one request - it does one to create the database, then an extra one to get `info()`.

If you'd like to do the most efficient possible thing, then I recommend just doing the "create if doesn't exist" operation yourself. You can even use PouchDB's ajax implementation using `require('pouchdb/extras/ajax')`.

**Comment by colinskow** [comment]
Thanks Nolan!

**Comment by nolanlawson** [comment]
So it seems like the stateless constructor is also breaking [New Relic](https://discuss.newrelic.com/t/promise-instrumentation-and-cached-promises-pouchdb/29160) and Hoodie apparently. Do we need to just do a better job of documenting the change, or is this worth looking into a bit more?

**Comment by daleharvey** [comment]
So yeh we know whats up with the hoodie code, would be good to get more details on what the problem with NewRelic is. @colinskow are you working on NewRelic.

From the report, the major issue is that people are still consider the PouchDB constructor a promise and that is straight up broken

**Comment by omsmith** [comment]
@daleharvey on my phone, explained the NR issue in slack though

**Comment by omsmith** [comment]
(https://pouchdb.slack.com/archives/general/p1442357947001570)

**Comment by daleharvey** [comment]
If there is anything Pouch can do to make the instrumentation NR is doing easier, please file a new issue, closing this one out for now though, we have an issue for the hood.ie usage @ https://github.com/pouchdb/pouchdb/issues/4339

**Comment by colinskow** [comment]
I've just been creating databases manually with an HTTP request where it is important. The issue did break some code, but was easy to fix.
