### ISSUE TITLE
Enabling cors on iriscouch

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [pouchdb/pouchdb#4328]
Hello PuchDb,

We are testing PouchDb and are enthusiastic sofar. We also need to enable cors on iriscoach but this seems to be not so straight forward. We tried the code below but this does not seem to work. Support is appreciated.
(iriscoach only seems to support a community support. That is why we put our request here.)

curl -X PUT https://mario@delafini.com:mario123@delafini.iriscouch.com
/_config/httpd/enable_cors -d '"true"'

curl -X PUT https://mario@delafini.com:mario123@delafini.iriscouch.com
/_config/cors/origins -d '"*"'

curl -X PUT https://mario@delafini.com:mario123@delafini.iriscouch.com
/_config/cors/credentials -d '"true"'

curl -X PUT https://mario@delafini.com:mario123@delafini.iriscouch.com
/_config/cors/methods -d '"GET, PUT, POST, HEAD, DELETE"'

curl -X PUT https://mario@delafini.com:mario123@delafini.iriscouch.com
/_config/cors/headers -d '"accept, authorization, content-type, origin, referer, x-csrf-token"'

Kind regards,
Mario

**Comment by daleharvey** [comment]
@MarioVanDenEijnde Can you post the full request and responce headers that are causing things to fail?

https://github.com/pouchdb/add-cors-to-couchdb may also be useful

**Comment by MarioVanDenEijnde** [comment]
Hello Dale,

Thanks for the reply.
I think I have posted the complete curl above.
After submitting there is no response. Not sure what to expect though.
Can you try and tell me what is wrong (or right)?

Kind regards,
Mario

**Comment by daleharvey** [comment]
Oh sorry I thought you meant CORS was failing after this, the problem here is that you need to encode the @ your username as it gets interpreted as part of the url

    curl -X PUT 'https://mario%40delafini.com:mario123@delafini.iriscouch.com/_config/cors/credentials' -d '"true"' -v

Also you should not post your password on here, its a public site so I suggest changing it asap, cheers

**Comment by MarioVanDenEijnde** [comment]
Hello Dale,

The response is: <"error":"bad_request","reason":"invalid_json">

Please advise,

Kind regards,
Mario

**Comment by daleharvey** [comment]
@MarioVanDenEijnde I posted the command successfully I quoted before you changed the password successfully, and as previously mentioned there is https://github.com/pouchdb/add-cors-to-couchdb which means you dont need to run the curl commands yourself.

It would be useful if you posted exactly what you did, and exactly what went wrong when posting for help, and some of this you are going to need to debug by yourself

Cheers

**Comment by MarioVanDenEijnde** [comment]
Hello Dale,

I have renamed the password back to mario123 and tried your line of code. But no luck.

But before we go into that can you explain how to use the "add-cors-to-couchdb"

I created a Html page.
Included the scripts:
<script src="Scripts/AddToCors/bin.js"></script>
<script src="Scripts/AddToCors/index.js"></script>

And called the script:
<script>
add-cors-to-couchdb http://delafini.iriscouch.com -u mario%40delafini.com -p mario123
</script>

Is this the way to go?
I only get errors.

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
```
<body>
<script src="Scripts/AddToCors/bin.js"></script>
<script src="Scripts/AddToCors/index.js"></script>

<script>
	add-cors-to-couchdb http://delafini.iriscouch.com -u mario%40delafini.com -p mario123
</script>
</body>

```

**Comment by MarioVanDenEijnde** [comment]
Sorry. Should not be closed.

**Comment by nickcolley** [comment]
Hey Mario,

It needs to be run from the command line https://github.com/pouchdb/add-cors-to-couchdb#usage

**Comment by MarioVanDenEijnde** [comment]
Hello Nick,

Something obvious for you is not clear to me.;-(

I open the command box on my PC
I point to the folder where I extracted the add-cors-to-couchdb
I write: add-cors-to-couchdb http://delafini.iriscouch.com -u mario@delafini.com -p mario123

I think I miss some basics.

Please advise.

Kind regards,
Mario

**Comment by daleharvey** [comment]
@MarioVanDenEijnde you can leave the bug closed and carry on the conversation, this isnt a pouchdb bug

```
$ curl -X PUT 'https://mario%40delafini.com:mario123@delafini.iriscouch.com/_config/cors/credentials' -d '"true"' -v
* Adding handle: conn: 0x7fa081004400
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fa081004400) send_pipe: 1, recv_pipe: 0
* About to connect() to delafini.iriscouch.com port 443 (#0)
*   Trying 72.2.115.203...
* Connected to delafini.iriscouch.com (72.2.115.203) port 443 (#0)
* TLS 1.0 connection using TLS_RSA_WITH_AES_128_CBC_SHA
* Server certificate: *.iriscouch.com
* Server certificate: DigiCert SHA2 Secure Server CA
* Server certificate: DigiCert Global Root CA
* Server auth using Basic with user 'mario@delafini.com'
> PUT /_config/cors/credentials HTTP/1.1
> Authorization: Basic bWFyaW9AZGVsYWZpbmkuY29tOm1hcmlvMTIz
> User-Agent: curl/7.30.0
> Host: delafini.iriscouch.com
> Accept: */*
> Content-Length: 6
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 6 out of 6 bytes
< HTTP/1.1 200 OK
* Server CouchDB/1.5.0 (Erlang OTP/R15B03) is not blacklisted
< Server: CouchDB/1.5.0 (Erlang OTP/R15B03)
< Date: Wed, 16 Sep 2015 10:01:10 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 7
< Cache-Control: must-revalidate
<
"true"
```

That is working as expected

**Comment by MarioVanDenEijnde** [comment]
Hello Dale,

You are probably right.
When I put your line in the command box I get "'https" not supported.
And when I replace ' with " it says host not found.

I don't want to be a burden but I would appreciate help. Using command line or using curl.
Now I am stuck.

Kind regards,
Mario

**Comment by daleharvey** [comment]
@MarioVanDenEijnde open a clean shell, copy and paste 

    curl -X PUT 'https://mario%40delafini.com:mario123@delafini.iriscouch.com/_config/cors/credentials' -d '"true"' -v

and copy and paste the full output of the shell into https://gist.github.com/ and share it here, that may help see what is up

**Comment by MarioVanDenEijnde** [comment]
```
C:\Program Files (x86)\cURL\bin>curl -X PUT 'https://mario%40delafini.com:mario1
23@delafini.iriscouch.com/_config/cors/credentials' -d '"true"' -v
* Protocol "'https" not supported or disabled in libcurl
* Closing connection -1
curl: (1) Protocol "'https" not supported or disabled in libcurl
```

**Comment by daleharvey** [comment]
@MarioVanDenEijnde what happens when you do?

    curl -X PUT "https://mario%40delafini.com:mario123@delafini.iriscouch.com/_config/cors/credentials" -d '"true"' -v

**Comment by daleharvey** [comment]
this is a problem with sending curl commands on windows, I dont have a lot of experience with that

**Comment by MarioVanDenEijnde** [comment]
```
C:\Program Files (x86)\cURL\bin>curl -X PUT "https://mario%40delafini.com:mario1
23@delafini.iriscouch.com/_config/cors/credentials" -d '"true"' -v
* Hostname was NOT found in DNS cache
*   Trying 72.2.112.168...
* Connected to delafini.iriscouch.com (72.2.112.168) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: C:\Program Files (x86)\cURL\bin\curl-ca-bundle.crt
  CApath: none
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.0 / DHE-RSA-AES256-SHA
* Server certificate:
*        subject: C=US; ST=New York; L=New York; O=Nodejitsu Inc.; CN=*.iriscouc
h.com
*        start date: 2015-07-29 00:00:00 GMT
*        expire date: 2016-08-10 12:00:00 GMT
*        subjectAltName: delafini.iriscouch.com matched
*        issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*        SSL certificate verify ok.
* Server auth using Basic with user 'mario@delafini.com'
> PUT /_config/cors/credentials HTTP/1.1
> Authorization: Basic bWFyaW9AZGVsYWZpbmkuY29tOm1hcmlvMTIz
> User-Agent: curl/7.39.0
> Host: delafini.iriscouch.com
> Accept: */*
> Content-Length: 6
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 6 out of 6 bytes
< HTTP/1.1 400 Bad Request
< Server: CouchDB/1.5.0 (Erlang OTP/R15B03)
< Date: Wed, 16 Sep 2015 11:29:23 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 48
< Cache-Control: must-revalidate
<
{"error":"bad_request","reason":"invalid_json"}
* Connection #0 to host delafini.iriscouch.com left intact
```

**Comment by MarioVanDenEijnde** [comment]
Hello Dale,

I have been googling but no answers.

I am happy to use the github but I miss the basics:
Something obvious for you is not clear to me.;-(

I open the command box on my PC
 I point to the folder where I extracted the add-cors-to-couchdb
 I write: add-cors-to-couchdb http://delafini.iriscouch.com -u mario@delafini.com -p mario123

Can you advise?

Kind regards,
Mario

**Comment by daleharvey** [comment]
@MarioVanDenEijnde also need to change the quoting on the json parameters, so 

    curl -X PUT "https://mario%40delafini.com:mario123@delafini.iriscouch.com/_config/cors/credentials" -d "\"true\"" -v

**Comment by MarioVanDenEijnde** [comment]
Hello Dale,

It looks like this worked. Can you check?
In my app I now get the message "No 'Access-Control-Allow-Origin' header is present on the requested resource"
I have read this somewhere. Can you advise?

Kind regards,
Mario

**Comment by daleharvey** [comment]
@MarioVanDenEijnde this isnt a support channel, you are going to need to start attempting to debug your own problems at some point

When asking questions you need to specify the full problem, as I asked multiple times before to debug the problem we would need the full request and response headers.

**Comment by MarioVanDenEijnde** [comment]
Hello Dale,

Joyfully I can report syncing with irisCouch is working.

May I thank you very very much.

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
Hello Dale,

Can I drop 1 question:
It seems when opening the PouchDb inspector in Chrome the sync is not working anymore and I get the message that CORS is not enabled.
Without opening the inspector everything is working fine.
I also expected to see the local database in the inspector but the inspector is not showing anything.

Should I stay away from the inspector?

Kind regards,
Mario

**Comment by nolanlawson** [comment]
Mario: if you install Node.js for Windows: https://nodejs.org/en/

And then go to the command line and run

```
npm install -g add-cors-to-couchdb
add-cors-to-couchdb http://me.iriscouch.com -u myusername -p mypassword
```

It should work on Windows.

As for the Inspector, it won't show anything if there's no data in the database due to CORS errors.
