### ISSUE TITLE
Bower Version

### ISSUE THREAD

**Issue by deliriousrhino** [pouchdb/pouchdb#4331]
For release 4.0.2 I believe ths bower version is incorrect. It is set to 
```
"version": "4.0.3-prerelease",
```

**Comment by nolanlawson** [comment]
Supposedly bower just looks for the git tag. I don't understand why it's not working for 4.0.2.

**Comment by nolanlawson** [comment]
jsdelivr is messed up, too. Latest is 4.0.2-prerelease, probably due to that accidental publish I did: http://cdn.jsdelivr.net/pouchdb/latest/pouchdb.min.js

Whatever. I say we wait for 5.0.0.

**Comment by nolanlawson** [comment]
Hopefully Bower should be fixed by the 4.0.3 release.
