### ISSUE TITLE
Use shorter prefixes in the LevelDB adapter

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4334]
We are using keys like `'document-store'` in [the leveldb adapter](https://github.com/pouchdb/pouchdb/blob/1df290b0e070d2e57cc0942d8dd18a1c0071598f/lib/adapters/leveldb/index.js#L39-L44) when we could just be using `'a'`, `'b'`, `'c'`, etc. This is kind of a waste of space; we should migrate to a shorter prefix system.

**Comment by Charlotteis** [comment]
@nolanlawson Verbose names mean that people can actually understand the code, 'a' 'b' 'c' means I have no idea what it's referring to just by looking at it? However, I'm not exactly sure where those 'document-store' strings come from and where else they are used? You may well be right, I just want to make sure we're not leasing some good info :)

**Comment by nickcolley** [comment]
Think he means like `var DOC_STORE = 'd';` vs `var DOC_STORE = 'document-store';`

**Comment by Charlotteis** [comment]
Yeah I get that. My question being what is 'd'. Where will we see 'd', will the user ever see 'd' in an error message and have no idea?

**Comment by nolanlawson** [comment]
Users will only see the 'a' 'b' 'c' etc. if they look at the underlying representation of the database, which for LocalStorage/FruitDB would mean the LocalStorage/IndexedDB tabs in the browser Dev Tools, and for LevelDB... well, I never even figured out how to inspect a LevelDB database. :stuck_out_tongue:

 E.g. for the localstorage adapter, it currently looks like this:

![screenshot 2015-09-15 11 28 20](https://cloud.githubusercontent.com/assets/283842/9881221/ecf36bc0-5b9c-11e5-94b1-334cfccedc52.png)

I'd say it's already pretty unintelligible with the `pouch_testdbÿdocument-storeÿ...`; it probably won't be much worse if that `'document-store'` becomes `'a'`.

**Comment by Charlotteis** [comment]
Makese sense!

**Comment by nolanlawson** [comment]
Since this would require a migration, I'm reluctant to do it. Also not sure it would be a huge perf win. Closing for now
