### ISSUE TITLE
bower update pouchdb

### ISSUE THREAD

**Issue by ronyrun** [pouchdb/pouchdb#4345]
bower.json : 

 "dependencies": {
  ...
    "pouchdb": "4.0.3",
  ...
  },

concerning last PouchDB version, I have a bower error :

[3:52 PM] ronyrun: bower update pouchdb
bower pouchdb#4.0.3       ENORESTARGET No tag found that was able to satisfy 4.0.3

**Comment by nolanlawson** [comment]
```
bower cache clean
bower info pouchdb | grep version
```

This is giving me 4.0.3. Please let me know if you still have an issue!

**Comment by ronyrun** [comment]
no more issue
