### ISSUE TITLE
Deprecate returnDocs in favor of return_docs

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4346]
Ala https://github.com/pouchdb/pouchdb/pull/4338, I would like us to be consistent about our naming conventions for options. `camel_case` is what we use almost everywhere (because it fits the CouchDB conventions), but there are odd exceptions, the last of which (I believe) being `returnDocs` (see [changes()](http://pouchdb.com/api.html#changes)). 

I think we should support both `returnDocs` and `return_docs` but mark `returnDocs` for deprecation in the docs.

**Comment by nolanlawson** [comment]
So basically this would involve making a similar change to https://github.com/pouchdb/pouchdb/pull/4338, except in this case we also need to add a deprecation notice to the docs, because `returnDocs` has been documented for awhile.

**Comment by nolanlawson** [comment]
By the way the deprecation notice should go in [api.html](http://pouchdb.com/api.html), which can be modified [here](https://github.com/pouchdb/pouchdb/edit/master/docs/_includes/api/overview.html). Just find the part about `returnDocs` and add a note that it's now `return_docs`.

**Comment by xelawafs** [comment]
Hey Nolan,

I guess you mean the returnDocs bit can be modified under the changes section on api.html which is [here] (https://github.com/pouchdb/pouchdb/blob/master/docs/_includes/api/changes.html). Given it a try and submitted a [commit](https://github.com/pouchdb/pouchdb/commit/b015b2c2c8956b5fa0be55e93fd51a7989d643ad)

**Comment by christopherreay** [comment]
https://en.wikipedia.org/wiki/CamelCase ?????????????????????

**Comment by nickcolley** [comment]
yo @christopherreay , I think Nolan just typoed when he said 'camel_case' he meant 'snake_case'.

CouchDB uses snake_case and since PouchDB is trying to be as compatible as possible here we're trying to make the options similar too.

Hope that makes sense :+1:

**Comment by christopherreay** [comment]
it says "firsttimeusers" in one of the tags....

pity. I use a mix of camelAndSnake_forComplexNames, lol.

Great tool guys, thank you so much.

On 13 October 2015 at 15:54, Nick Colley <notifications@github.com> wrote:

> yo @christopherreay <https://github.com/christopherreay> , I think Nolan
> just typoed when he said 'camel_case' he meant 'snake_case'.
>
> CouchDB uses snake_case and since PouchDB is trying to be as compatible as
> possible here we're trying to make the options similar too.
>
> Hope that makes sense [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/4346#issuecomment-147739928>.
>



-- 

Be prepared to have your predictions come true

**Comment by bdchauvette** [comment]
I took a stab at fixing this issue today (see pull request above), but I'm guessing I screwed up somewhere, as a few of the CI builds are failing. 

I don't think that they're failing because of code that I touched, but TBH I'm not 100% sure...

#firstTimerProblems :see_no_evil::sweat_smile:

**Comment by daleharvey** [comment]
Yup as mentioned the tests are just not 100% reliable and usually need a restart or 2 our of the 50 runs, the PR was great, this is fixed in https://github.com/pouchdb/pouchdb/commit/609cfc2ed5b4f1fb7887c68739343f4c021c47c3, thanks

**Comment by bdchauvette** [comment]
Ok, awesome!

Great project btw :D
