### ISSUE TITLE
bower update don't work since 4.0.2

### ISSUE THREAD

**Issue by saturnlevrai** [pouchdb/pouchdb#4347]
Sorry, but since 4.0.2, i cannot use bower to update pouchdb.
Here is log : 
bower pouchdb#>=4.3.0            ENORESTARGET No tag found that was able to satisfy >=4.3.0

Additional error details:
Available versions: 4.0.1, 4.0.0, 3.6.0, 3.5.0, 3.4.0, 3.3.1, 3.3.0, 3.2.1, 3.2.0, 3.1.0, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.2, 2.1.1, 2.1.0, 2.0.2, 2.0.1, 2.0.0, 1.1.0, 1.0.0, 0.0.18, 0.0.17, 0.0.16, 0.0.10

Thx in advance to your help.

**Comment by nickcolley** [comment]
Hey @saturnlevrai !

Can you try:
```bash
bower cache clean
bower info pouchdb | grep version
```

And update this issue with what you get? :+1:

**Comment by saturnlevrai** [comment]
Hi @nickcolley .
Here is result of bower info pouchdb after clean :

bower info pouchdb | grep version
  version: '4.0.3',
Available versions:
You can request info for a specific version with 'bower info pouchdb#<version>'

Clean revolve my issue. Thx a lot ! and sorry to disturb for this :(

**Comment by nickcolley** [comment]
Don't apologise, it's cool!

Glad you've got it sorted.
