### ISSUE TITLE
Use offline/online events to skip the retry timeout

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#4349]
Based of a discussion in Slack https://pouchdb.slack.com/archives/general/p1442503616001903

Currently we will retry based on a timeout, however we could listen to the offline/online events and restart the timer for replication.

Would make it feel more responsive.

I understand that offline/online events are very lacking but if there's no downsides it's probably worth thinking about.

**Comment by gr2m** [comment]
We used the browser's online/offline events in Hoodie, but it's somewhat confusing, especially when you develop locally. Also the implementation between Chrome / Firefox / Safari is very different if I remember correctly.

I think we still use it in Hoodie, but we only use it to send a test request to the server and then react depending on the response of that request

**Comment by jareware** [comment]
I would imagine that's the suggestion here as well, to simply cut the wait for the next retry short, but otherwise keep the logic as-is.
