### ISSUE TITLE
Problem with czech encoding

### ISSUE THREAD

**Issue by mfeuermann** [pouchdb/pouchdb#4351]
Hello 

I have problem with special chars in key definition

db.query('poi/byCategory', {
			  limit: 50,
			  key : 'zřícenina' 
			}).then(function (res) {

			}).catch(function (err) {
			  // some error
			});

If i using words without this characters, its working fine...
Im using CouchDB remotely... 

Can you help me where can be problem ?

With regards 
MF

**Comment by daleharvey** [comment]
Cheers for the report, will try to take a look shortly, if you want to debug this yourself and have any questions then happy to

**Comment by daleharvey** [comment]
@mfeuermann also would be super useful if you could say what is happening that you consider broken

**Comment by daleharvey** [comment]
@mfeuermann this seems to be working as expected, do you have any more details on what the failure is? 

Wrote a test up @ https://github.com/pouchdb/pouchdb/commit/1ea6786476ec8abbb620f7ca8edf2328d1ae5b32

**Comment by mfeuermann** [comment]
Hello 

in database there is docs with key "zřícenina" (i can list rows in Futon with right encoding)
If i place map function with condition word (zřízenina) directly to view in couchdb, it works fine 
(i have all docs contains zřícenina)

If i try to query all records with "zřícenina" from pouchdb 

db.query('poi/byCategory', {
limit: 50,
key : 'zřícenina' 
}) 

result is empty... 

If i change keys in docs from "zřícenina" to "zricenina", everythink working fine...

**Comment by daleharvey** [comment]
@mfeuermann Here is a test you should be able to run http://paste.pouchdb.com/paste/azjo7b/, you need CORS enabled (https://github.com/pouchdb/add-cors-to-couchdb) on a couch running at localhost:5984. Does that test pass for you?

**Comment by mfeuermann** [comment]
Hello @daleharvey 

your example working fine, problem is propably on my site...
My data in couchDB are inserted by PHP script.

If i place data by pouch and query by pouchDB it working fine...
Problem is if i put data by PHP to couchDB (in futon is right diacritics) and trying query from pouch...

Marek

**Comment by cdaringe** [comment]
couchdb will mutate your urls.  i created [couchdb-urlify](https://www.npmjs.com/package/couchdb-urlify) which i use to set my db names before putting them into pouch, and thus into couch. it will even send me an error if i'm in violation :)

**Comment by cdaringe** [comment]
you might check it out using the [assert](https://www.npmjs.com/package/couchdb-urlify#assert) method

**Comment by daleharvey** [comment]
Ok so looks like no bug here, cheers
