### ISSUE TITLE
Bower install of previous release not working.

### ISSUE THREAD

**Issue by ronyrun** [pouchdb/pouchdb#4353]
C:\Users\User\Dev\app>bower uninstall pouchdb
bower uninstall     pouchdb

C:\Users\User\Dev\app>bower install pouchdb@4.0.1
bower pouchdb#4.0.3             cached git://github.com/pouchdb/pouchdb.git#4.0.3
bower pouchdb#4.0.3           validate 4.0.3 against git://github.com/pouchdb/pouchdb.git#4.0.3
bower                        ENOTFOUND Package pouchdb@4.0.1 not found

C:\Users\User\Dev\app>bower install pouchdb@4.0.2
bower pouchdb#4.0.3             cached git://github.com/pouchdb/pouchdb.git#4.0.3
bower pouchdb#4.0.3           validate 4.0.3 against git://github.com/pouchdb/pouchdb.git#4.0.3
bower                        ENOTFOUND Package pouchdb@4.0.2 not found

C:\Users\User\Dev\app>bower install pouchdb@4.0.0
bower pouchdb#4.0.3             cached git://github.com/pouchdb/pouchdb.git#4.0.3
bower pouchdb#4.0.3           validate 4.0.3 against git://github.com/pouchdb/pouchdb.git#4.0.3
bower                        ENOTFOUND Package pouchdb@4.0.0 not found

**Comment by nolanlawson** [comment]
```
bower cache clean
bower install pouchdb#4.0.2
bower install pouchdb#4.0.1
bower install pouchdb#4.0.0
```

This works fine for me.

**Comment by ronyrun** [comment]
OK on my side also thanks
