### ISSUE TITLE
Support Event Source changes feed

### ISSUE THREAD

**Issue by Ti-webdev** [pouchdb/pouchdb#4355]
As best way of changes feed I want use [event source](https://couchdb.readthedocs.org/en/1.6.1/api/database/changes.html#event-source) changes feed

**Comment by daleharvey** [comment]
We previously did support SSE, however it had (minor) compatibility issues and provided no benefit, pouchdb does not expose these apis and what powers `db.changes()` is an implementation detail, is there any specific reason for SSE you have?

**Comment by Ti-webdev** [comment]
Its need for minimize overhead13:42, 21 сентября 2015 г., Dale Harvey <notifications@github.com>:We previously did support SSE, however it had (minor) compatibility issues and provided no benefit, pouchdb does not expose these apis and what powers db.changes() is an implementation detail, is there any specific reason for SSE you have? —Reply to this email directly or view it on GitHub.

**Comment by daleharvey** [comment]
minimise what overhead? there is no difference in the amount of data transferred between using longpoll vs sse, the only difference is the reconnection time between 2 polling requests when you are doing a live changes feed over http (ie no difference to replication).

**Comment by daleharvey** [comment]
So at the least our current focus will be fully streamable replication, we get not benefit from sse in our current state, but will most definitely take another look when that becomes available, gonna close this out for now

**Comment by myroslav** [comment]
Reconnection time is not the only drawback. The overhead of setting up new TCP connection is not trivial. Even if new polling request reuses TCP connection (with keepalives, or SPDY), the overhead is in frontend server processing this new request. 

SSE are ones that are "used when data hit the queue". And when connection is idling, to maintain the connection through proxies and firewalls there are multiple approaches, from TCP keepalives, to heartbeats, that require one packet to send heartbeat and one ack packet back to confirm the transmission.
