### ISSUE TITLE
Faulty listener removal in lib/sync.js

### ISSUE THREAD

**Issue by colinskow** [pouchdb/pouchdb#4361]
In `lib/sync.js` there is a function `removeAll` that seems faulty. It is checking for a `event in listeners`, but listeners will always be an empty object because it isn't used anywhere else in the code.

```js
  var listeners = {};
  var removed = {};

  function removeAll(type) { // type is 'push' or 'pull'
    return function (event, func) {
      var isChange = event === 'change' &&
        (func === pullChange || func === pushChange);
      var isOtherEvent = event in listeners;

      if (isChange || isOtherEvent) {
        if (!(event in removed)) {
          removed[event] = {};
        }
        removed[event][type] = true;
        if (Object.keys(removed[event]).length === 2) {
          // both push and pull have asked to be removed
          self.removeAllListeners(event);
        }
      }
    };
  }
```

I didn't want to mess with this in my PR because I don't understand it well, but it could be the cause of memory leaks.

**Comment by colinskow** [comment]
Made some improvements with https://github.com/colinskow/pouchdb/commit/ba060685179fb3c8f016eb7a3402ea8e8a450c2a but this really needs to be tested for memory leaks. Also not sure what to do with `event in listeners` which is useless.

**Comment by colinskow** [comment]
I think this is going to be fixed when https://github.com/pouchdb/pouchdb/pull/4363 is merged.

**Comment by daleharvey** [comment]
Done
