### ISSUE TITLE
Authentication hook required inside live replication retry loop to support offline ->online -> offline -> online state changes

### ISSUE THREAD

**Issue by tohagan** [pouchdb/pouchdb#4364]
Currently to implement cookie authentication (and potentially other token based authentications) we have a couple of implementation options:

**Option 1**. login() then sync()

I think this is what current [pouchdb-authentication](https://github.com/nolanlawson/pouchdb-authentication) db.login() example shows.

- Perform cookie auth when **online**  (db.login())
- Now start up live sync() that watches for when you go offline.

- Assumes user is initially online when app starts up 
- Fails if they are initially offline (no hook to initiate db.login() in retry loop)

**Option 2**.  Wait until the remote db is online then sync

- Fails if the server or network subsequently goes offline.
- sync() will retry and attempt to reconnect but cookie session may have timed out.

**Option 3**. Perform login as a callback hook or authentication adapter 

- Register an authentication provider plugin (like an adapter) with remote db instance (note that different db instances may require different authentication so just registering it with PouchDb is not the best solution).
- Start up live db.sync() or db.replicate() and supply authentication options as part of sync() or replication() options. 
- PouchDb replication retry loop now always initiates authentication (even the 1st time).

Now works if app state changes from **offline** -> **online** -> **offline** -> **online** as the authentication is reapplied each time the replication goes online. We're no longer juggling multiple retry loops. 

Idea: If we're using [Cordova's Network Information plugin](https://github.com/apache/cordova-plugin-network-information), the replication retry loop might be able to leverage it's "online" event - or there might be a way for the app to inform the sync handle that this event has occurred.

**Comment by tohagan** [comment]
If I'm wrong and this is possible with existing  pouchdb-authentication then perhaps the sample code should demonstrate how.

**Comment by daleharvey** [comment]
So I think the easiest solution for this is Option 1, the application attempts to authenticate when it starts up, if it cannot do so, it waits until at some point it thinks it can (via online events) and once it has done so it initiates the sync. 

An authentication hook seems like a more complicated version of that but doesnt provide a whole lot of value, it gets the retry mechanism but aside from that?

**Comment by tohagan** [comment]
Then AFAIK you can't use anything other than basic auth with PouchDb offline apps which is rather disappointing and may be a show stopper for many apps. My main point was that Options 1 and 2 are unworkable.

Please prove me wrong by supplying sample code that can handle the state transitions from offline -> online -> offline -> online that will use cookie authentication and preserve the same database instance or replication/sync handle. I don't see how you can do this since the current 'active' event hooks only does not wait to complete the function and if you're cookie auth token has expired you're replication just died so now what?

**Comment by daleharvey** [comment]
You can retry the sync again once you have successfully authed

```
var syncObj = null;

function ensureAuth() { 
   // does authy things
}

funtion startSync() { 
  ensureAuth.then(function() { 
    syncObj = db.sync(remote, {retry: true, live: true});
    syncObj.on('paused', function(err) { 
      if (err && failedAuth(err)) { 
        syncObj.cancel();
      }  
    });
    syncObj.on('complete', function() { 
      syncObj = null; 
      startSync();
    });
  });
}

// Will probably want to do this in a setTimeout too
// online events arent particularly reliable
window.addEventListener('online', startSync); 
```

`retry` is built via the public api, building the same functionality with different hooks or behaviour should hopefully be fairly easy, The common case for this seems so far that auth is a user triggered process, sync happens while the user is logged in and if they are logged out then they need to relogin again in order to start syncing

**Comment by tohagan** [comment]
Thanks Harvey.  That make it a bit clearer.  I think pouch-authentication docs could use a code sample like this.

I understand that for many apps, the user initiates the sync and can assume that they are online at the time to key in and immediately confirm their login credentials. Not so in my apps. I encrypt and store them locally and can "login in" the user offline.

**Comment by tohagan** [comment]
Happy to close this if you think we're done :) .

**Comment by nickcolley** [comment]
@tohagan thanks for the great issue as usual! :+1:

**Comment by tohagan** [comment]
Thank @nickcolley ... Never sure if I'm just pestering too hard.

**Comment by tohagan** [comment]
Here's the code from [replicate.js line 245](https://github.com/pouchdb/pouchdb/blob/master/lib/replicate/replicate.js#L245) that calls backOff()` that fires an emit('pause', error)` event. 

      var non403s = allErrors.filter(function (error) {
        return error.name !== 'unauthorized' && error.name !== 'forbidden';
      });
      if (non403s.length > 0) {
        var error = allErrors.pop();
        if (allErrors.length > 0) {
          error.other_errors = allErrors;
        }
        error.result = result;
        backOff(opts, returnValue, error, function () {
          replicate(src, target, opts, returnValue);
        });
      } else {
        result.errors = allErrors;
        returnValue.emit('complete', result);
        returnValue.removeAllListeners();
      }

This is the only place where 'pause' returns an error. It sends this event when there is at least one non 403 error which I'm assuming means that we had one of [these http error codes](https://wiki.apache.org/couchdb/HTTP_status_list).  In contrast, if we get a 403 unauthorized/forbidden from a validation doc and *no other errors* then this will cause the replication/sync to complete. 

**Observation 1**: I'm not convinced that the `if (non403s.length > 0)` condition is correct. I would have thought that *any* 403 error should cause the replication to stop (e.g. complete) because if you get any 403's the replication can then **never succeed**.   I guess what happens at the moment is that it will backOff and retry and then just get a single 403 and then complete with that error. We'd also get the original errors reported via 'error' event inside `backOff()`.

I think that this design assumes that validation docs in the server should have been replicated into the client to acts as a client side prechecks to validate changes prior to them being pushed to the server as otherwise they would **cause all future replications to fail**. Validations that depend on ctxUser may not work very well client side unless you replicate _user or at least current userCtx somehow.  Is that what local validation docs do? What am I missing?  

      var all403s = allErrors.filter(function (error) {
        return error.name === 'unauthorized' || error.name === 'forbidden';
      });

      if (all403s.length > 0) {
        result.errors = allErrors;
        returnValue.emit('complete', result);
        returnValue.removeAllListeners();
      } else { 
        var error = allErrors.pop();
        if (allErrors.length > 0) {
          error.other_errors = allErrors;
        }
        error.result = result;
        backOff(opts, returnValue, error, function () {
          replicate(src, target, opts, returnValue);
        });
      }

**Observation 2**  failedAuth() will very rarely if ever be true except in the extremely rare case where we get at least one non-403 and the 1st error is a 403.  Right?

So I think I should be just testing for a failedAuth() only in the 'complete' event by checking `error.name === 'unauthorized'` in `result.errors` and then attempting a db.login() then db.sync().  If the login fails with a `403 unauthorized` we should abort the replication. If we get another error we should retry the login .. ideally with backoff (Perhaps the backoff is not really needed as 403 followed by non403 would probably be very rare).

**Comment by tohagan** [comment]
I think I've answered Q1.   I've had a deeper read of the CouchDb replication and what I assume PouchDb does is emit a 'denied' event [replicate.js line 87](https://github.com/pouchdb/pouchdb/blob/master/lib/replicate/replicate.js#L87) for each bulk_docs write failure (e.g. validation docs exceptions). This only occurs once as the local seq number is then advanced so we don't retry replicating it - even if it failed with an error.

**Comment by tohagan** [comment]
I can't yet make this work until this patch is applied:

* https://github.com/pouchdb/pouchdb/issues/4592

**Comment by nolanlawson** [comment]
@tohagan If you have a patch, could you please open a pull request? Would be nice to see if it passes/fails in Travis. :)

**Comment by tohagan** [comment]
Hi Nolan ... I eventually code an Angular service layer on top of Pouch on the assumption that this feature would not be available. It handles many other things including this state change.

**Comment by daleharvey** [comment]
I think he meant for #4592, lets close this out and keep dependency bugs as their own, thanks

**Comment by tohagan** [comment]
Sorry guys ... Now I get it (Duh!).   No I've not coded a patch for #4592 . Feeling a bit frustrated that due to project deadlines I'm lacking the time at present to contribute more to your projects.
