### ISSUE TITLE
Attachments : status: 412, name: "missing_stub" - unknown stub attachment with digest ****

### ISSUE THREAD

**Issue by ronyrun** [pouchdb/pouchdb#4370]
During a bulkDocs with 1 doc which has an `attachment` I encounter this error : 

`CustomPouchError {status: 412, name: "missing_stub", message: undefined, error: true, reason: "unknown stub attachment with digest md5-ZQl5f/si95KZxhbuYZ/WrQ=="}`

I tried to loop with dB.put and I have the same error.

here is the doc I tried to bulk of put : 

![image](https://cloud.githubusercontent.com/assets/7273443/10130227/c897dd40-65c6-11e5-9c8a-ae24a64048ff.png)

the local-store table is empty...

**Comment by colinskow** [comment]
See if you can write a test with as little code as possible to reproduce this bug. Did you try it with various browsers?

**Comment by ronyrun** [comment]
Do you know a jsfiddle like area with pouchDB lib available ?

**Comment by daleharvey** [comment]
I have http://paste.pouchdb.com/, you can just set the pouchdb version to 4.0.3 or whatever you want in there

**Comment by ronyrun** [comment]
thx

**Comment by ronyrun** [comment]
OK, I implemented some tests, and they are working when I'm creating before a doc1 with attachment and then copying it in a another doc with attachment. (http://paste.pouchdb.com/paste/48006x/)

But in my case I receive the doc + attachments from remoteDB.change

here is what I do : 
```javascript

var docsToBulk = []
pouch.remoteDB.changes({
                            include_docs: true,
                            returnDocs: true,
                            attachments : true,
                        })

.on('change', function (remoteChange) {
docsToBulk.push(remoteChange.doc);
})
.on('complete', function(remoteChange) {
localDB.bulkDocs(docsToBulk);  //error here
})

```
I still get this error when trying to save the result of a remoteDB.changes
![image](https://cloud.githubusercontent.com/assets/7273443/10150652/e3c0574e-6640-11e5-9158-594875d85af1.png)

**Comment by colinskow** [comment]
Try
```js
pouch.remoteDB.changes({
                            include_docs: true,
                            returnDocs: true,
                            attachments : true,
                            binary: true
                        })
```

and see if that makes any difference. Otherwise it is most likely a bug in PouchDB. But you should be able to get around it by requesting changes without the attachments and then fetching them manually.

**Comment by colinskow** [comment]
Also, `returnDocs` will only work on non-http databases.

**Comment by ronyrun** [comment]
I implemented a 2nd Pouch DB to control Changes and I don't get any error : 
http://paste.pouchdb.com/paste/0any37/

I'm using a distant CouchDB database on my app.
Then I think the problem could on the couchDB side (Apache CouchDB 1.5.0).

**Comment by ronyrun** [comment]
OK, as far as I can see, I have nothing stored in the **attach-store.**
So this error is normal because I try to put in my localDB a doc with Attachment without any digest stored in the **attach-store** of my LocalDB.

Then the question is how to get the digest ??

**Comment by ronyrun** [comment]
OK I close this issue as it should be normal to have only change info when we use db.changes.
I solved it by a get of the doc._id and then it's OK.
