### ISSUE TITLE
db with http adapter creates local filesystem presence without path option

### ISSUE THREAD

**Issue by cdaringe** [pouchdb/pouchdb#4382]
Hi all:

I need all of my dbs to be placed into an app directory, but per the current docs, cannot.  E.g., if I need a DB at `/my/path/db` to be a client for couch at `http://www.my-db-host/db`, I am unable to.  I would be willing to implement if someone would do the honors of giving me some pointers where in the stack the local instance gets generated.

Thanks!

Chris

**Comment by nolanlawson** [comment]
Happy to hear that you want to contribute, but can you provide more details on what you want to do? Kind of confused about your use case and the problem you want to solve. How can a local filepath be a client for a remote database?

**Comment by cdaringe** [comment]
Arg, sorry there.  [_I found it_](https://github.com/cdaringe/pouchy/commit/1c72f356970d3c6f89c285c1e1968df9bdec40ab).  It was all me!  I really threw myself for a loop.
