### ISSUE TITLE
Race condition cloning test is faily

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4400]
This test (https://github.com/pouchdb/pouchdb/commit/ee770fefb7409b2955dc514121c2279f39d33632) is faily for socket-pouch because the constructor takes awhile to start up, so here is the sequence of events:

1. user calls `new PouchDB()`
2. socket.open
3. user calls `db.put(doc)`
4. user mutates their doc after a `setTimeout()` of 2
5. socket opened, adapter done setting up
6. task queue does the adapter's `put()` logic with the tampered doc
7. test fails

IMO a better test would be if the user mutates the document *immediately after calling db.put()*. But for PouchDB to pass that test, we would need to aggressively clone immediately for every API call (synchronously).

As a side note, I think these particular tests are kinda dumb because as long as you write clean code, this issue should never come up. But I guess we are at the point with the development of PouchDB that most of the remaining issues to resolve are minor ones with niche value.

**Comment by daleharvey** [comment]
Its niche but it can lead to extremely confusing errors when it does get hit, I really do wish this was something just built into JS. 

The point of that commit was exactly to clone before giving control back to the user however the setup flow is fairly tricky, so yeh hopefully it just means moving the clone earlier to fix, having the doc modified sync probably is a better test

**Comment by daleharvey** [comment]
I took a look, changing the test to modify immediately is still passing as well, `toPromise` and `adapterFun` arent super easy to follow, I would like to improve them however this was changed to (fairly aggressively) clone the documents within the same tick before the user had the chance to modify them and it looks like it is doing so.

Is socket-pouch intercepting the API calls before it gets to this point and letting the user modify data? it seems like that is what must be happening

**Comment by nolanlawson** [comment]
`socket-pouch` has its own `toPromise` and `adapterFun`; maybe that's the issue? In any case I'll try to take a look at this when I get a chance.

**Comment by nolanlawson** [comment]
Seems fixed in 5d0bf2b59aea82ec8296a6c6b0aeb2ac5a953296, can't really complain, so closing.
