### ISSUE TITLE
Relationships with PouchDB (SQLite)

### ISSUE THREAD

**Issue by kevinnascimento** [pouchdb/pouchdb#4409]
Hi Guys,

According to the documentation, you can use SQLite with PouchDB.

However, Can I create tables and make relationship between them rather than work with docs?

**Comment by nolanlawson** [comment]
No, PouchDB can use SQLite under the hood (via WebSQL or SQLdown), but you still need to communicate using the PouchDB API rather than calling directly to SQLite.

**Comment by nickcolley** [comment]
If you're set on relationships you could look at https://github.com/nolanlawson/relational-pouch also.

**Comment by kevinnascimento** [comment]
@nickcolley Can I use with SQLite Cordova Plugin?

Thanks for help me.

**Comment by nolanlawson** [comment]
Yes, search for "sqlite plugin" here: http://pouchdb.com/adapters.html#pouchdb_in_the_browser

**Comment by nickcolley** [comment]
Keep in mind that any use of PouchDB is not compatible with standard SQL queries etc, as it is just using SQL as the datastore.
