### ISSUE TITLE
Upgrade Firefox in Travis

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4410]
Opening a generic issue about this. I tried to solve it in https://github.com/pouchdb/pouchdb/pull/4403, but frustratingly, could not figure out at all how to get Travis to actually upgrade from Firefox 31.

**Comment by nolanlawson** [comment]
Will fix in #4403

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/2457a2b2d91d080a18ec10720fd6531cd6db3b08
