### ISSUE TITLE
PouchDb personalized CRUD

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [pouchdb/pouchdb#4415]
Hello PouchDb team,

Can you put me in the right direction:
We have PouchDb on our mobile devices.
We have CouchDb on the server.
We want to introduce personalized CRUD which means User A only reads(/writes) his own items on Mobile and Desktop.

How do both Mobile and Desktop know the CouchDb synchronized items belong to User A.

Which tutorial or Docs should I read about this (did not find it yet).

Kind regards,
Mario

**Comment by agozie** [comment]
The solution is to have a database per user. Create a db and a user for
each account on Couchdb, set the user as the db member and admin. Sync to
the Couchdb database from Pouchdb with the user details.

**Comment by daleharvey** [comment]
Yup, if your users only have access to their own data then a database per user is generally the easiest option in this situation, there are a few tools to help for this, https://github.com/etrepum/couchperuser, or https://github.com/pouchdb/pouchbase etc, Cheers
