### ISSUE TITLE
Replication: Replicate only latest version

### ISSUE THREAD

**Issue by hrishiballal** [pouchdb/pouchdb#4416]
Hi Team, 
I have a query around replication from Couch to Pouch. I am coming from the point of view of optimizing bandwidth usage. 

If a document is deleted, only the tombstone is replicated for that document id. Suppose document 1 has a large amount of JSON data (e.g. 1.5 MB) and during update only a couple of strings have changed. 

Pattern 1: document 1 in Couch -> Updated with new JSON data -> replicate -> two versions transferred, therefore approx 3MB bandwidth used.

Pattern 2: document1 in Couch -> delete that document -> create a new document with same ID -> replicate -> Since only tombstones are replicated, in this case only 1.5MB of data will be transferred 

So pattern 2 is a more bandwidth efficient pattern in that lesser data will be transferred. 

Can someone please guide?

**Comment by kxepal** [comment]
Pattern 1 looks wrong: only latest revision (and conflicts) are replicated. So it's 1.5 MB.

**Comment by hrishiballal** [comment]
Thanks for your reply, in case of initial replication, all versions need to be transferred so wouldn't pattern 2 be more efficient in case of initial replication?

**Comment by kxepal** [comment]
Even for initial replication, only latest revisions are replicated, so it cannot replicate your document before update and after, unless you already run continuous replication

**Comment by hrishiballal** [comment]
OK understood. Thanks for this.
