### ISSUE TITLE
rendering from blob versus live stream

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [pouchdb/pouchdb#4417]
Hello PouchDb team,

Test case iPhone:
We save an image as blob attachment in local PouchDb.
From the local dataBase we render it on the mobile.
We experience that this takes longer then render from a live stream.

The blob is created from the live stream and thus use the same sizes.

We use the "blobUtil.imgSrcToBlob" to store the image.
And we use the following code to read from the local store:
```
.then(function (doc) {
	console.log("1");
	console.log(doc);
	return db.getAttachment('TtPicture', 'TtPicture.png');
})
.then(function (blob) {
console.log("2");
	var url = URL.createObjectURL(blob);
	var img = document.getElementById('DidYouKnowPictureUrlImg');
	img.src = url;
```
Can you advise if we have to live with it? Or should I use a different approach.

Kind regards,
Mario

**Comment by nolanlawson** [comment]
Yeah, reading a blob from the filesystem (or SQLite) is indeed slower than reading it from memory. You might want to check out this graphic on "latency numbers every programmer should know": https://gist.github.com/hellerbarde/2843375

The standard fix is to read the blob into memory before the user needs it, then create a blob URL using `createObjectURL()`. As long as you don't call `revokeObjectURL()`, that URL will be cached by the browser and ready to serve.

**Comment by MarioVanDenEijnde** [comment]
Hello Nolan,

OK. "read the blob into memory before the user needs it"
Can you giv me a hint how to do this?

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
Hello Nolan,

Small question: It seems I cannot put a createObjectURL emmidiately after the putAttachment.
Is this true?

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
Hello Nolan,

I cannot figure it out:
We save the blob as an attachment (for offline usage)
How do we get the blob in memory and call the image with every pagerefresh from the memory.

I suppose we call getAttachment to get the blob
then we do a createObjectURL to get the url to the blob
And we use the url as img.src with every page refresh

But when we do it this way the load is still much longer then when we load the image from the internet.

Am I missing something?
Where and how do I put the blob into memory?

Please advise.

Kind regards,
Mario

**Comment by nickcolley** [comment]
Have you got a code example of your issue to debug? Having trouble figuring out the issue from your description.

:+1:

**Comment by MarioVanDenEijnde** [comment]
Hello Nick,

(You probably can tell I am a newbie ;-)
The solution below is as follows:
1. Using an ajax call I receive the source Image url -> localStorage.recipesPictureUrl
2. From this ajax call I run updateRecipePicture where I check if a doc is already there or not
3.  if doc is there I remove the existing attachment (if any) and run updateRecipePictureAttachment to update the doc with the attachment
4.  if doc is not there I run newRecipePictureAttachment to create doc together with attachment
5. After attachment is saved I call getRecipePicture to show image.
6. And with every page refresh I only call getRecipePicture  in $(document).ready



```
		function getRecipePicture(){ 
			new PouchDB('RecipeData')
			.then(function (db) {
				db.get('RecipePicture', {attachments: true})
				.then(function (doc) {
					console.log(doc);
					return db.getAttachment('RecipePicture', 'RecipePicture.png');
				})
				.then(function (blob) {
					localStorage.recipeUrl = URL.createObjectURL(blob);
					var img = document.getElementById('RecipesPictureUrlImg');
					img.src = localStorage.recipeUrl;
				})
				.catch(function (err) {
					console.log(err);
					loadRecipeImage() //* this function loads the source image url using an ajax call
				});
			});
		}
		
		function updateRecipePicture(){
			new PouchDB('RecipeData')
			.then(function (db) {
				// check if document exists and then remove attachment
				db.get('RecipePicture', {attachments: true})
				.then(function (doc) {
					localStorage.revDocRecipe = doc._rev;
					return db.removeAttachment('RecipePicture', 'RecipePicture.png', localStorage.revDocRecipe)
					.then(function (result) {
						updateRecipePictureAttachment();
					})
					.catch(function (err) {
					  console.log(err);
					});
				}).catch(function (err) {
					console.log(err);
					newRecipePictureAttachment();
				});
			});
		}
		
		function updateRecipePictureAttachment(){
			new PouchDB('RecipeData')
			.then(function (db) {
				if (typeof localStorage.recipesPictureUrl !== 'undefined' && localStorage.recipesPictureUrl !== null){
				db.get('RecipePicture')
					.then(function (doc) {
					console.log(doc);
					localStorage.revDocRecipe = doc._rev;
					return blobUtil.imgSrcToBlob('http://my-personaltrainer.nl' + localStorage.recipesPictureUrl+ '?w=' + localStorage.maxWindowSize);
					})
					.then(function (blob) {
						return db.putAttachment('RecipePicture', 'RecipePicture.png', localStorage.revDocRecipe, blob, 'image/png');
					})
					.then(function (result) {
						getRecipePicture();
					})
					.catch(function (err) {
						console.log(err);
						loadRecipeImage();
					});
				}
				else{
					loadRecipeImage();
				}
			});
		}
		
		function newRecipePictureAttachment(){
			new PouchDB('RecipeData')
			.then(function (db) {
				if (typeof localStorage.recipesPictureUrl !== 'undefined' && localStorage.recipesPictureUrl !== null){
					db.put({
						_id: 'RecipePicture'
					})
					.then (function (returnBlob){
	  					return blobUtil.imgSrcToBlob('http://my-personaltrainer.nl' + localStorage.recipesPictureUrl+ '?w=' + localStorage.maxWindowSize);
					})
					.then(function (blob) {
						return db.putAttachment('RecipePicture', 'RecipePicture.png', localStorage.revDocRecipe, blob, 'image/png');
					})
					.then(function (result) {
						getRecipePicture();
					})
					.catch(function (err) {
						console.log(err);
					});
				}
				else{
					loadRecipeImage();
				}
			});
		}
		
	// End of RecipePictureUrl information -------------------------------------------------------------
	
	
    $(document).ready(function () {
    
        localStorage.maxWindowSize = window.screen.height;
    	if(localStorage.maxWindowSize < window.screen.width){
    		localStorage.maxWindowSize = window.screen.width;
    	}			
    	getRecipePicture();

	});

```
Kind regards,
Mario

**Comment by nolanlawson** [comment]
So yeah, fetching a Blob from PouchDB is always going to be slower than having it in-memory. What I mean by "load into memory" is simply "read it out of PouchDB," which you are doing.

Another way to make your operation faster is to use `getAttachment()` instead of `get()` with `{attachment: true}`, or to add `{binary: true}`. Typically PouchDB works faster if you pull out Blobs directly instead of pulling out base64 strings and then converting them into Blobs.

**Comment by MarioVanDenEijnde** [comment]
Hello Nolan,

OK. Thanks.

Kind regards,
Mario
