### ISSUE TITLE
PouchDB stickers

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4426]
I've gotten multiple requests for some PouchDB stickers. I don't even know the first thing about ordering/designing laptop stickers, though.

Anyone have any ideas? @nickcolley? I could chip in if we wanted to order a bunch.

**Comment by daleharvey** [comment]
@maxogden Where do you get the hex stickers from? it seems like we should go with them, they fit together really well

**Comment by nickcolley** [comment]
I'd be willing to chip in, the logo is vector so would be straight forward to get printed.

It'd be cool to have a standard die-cut style logo and maybe the hex too?

**Comment by nolanlawson** [comment]
Hex sounds great.

**Comment by nickcolley** [comment]
Looks like http://hexb.in/ is the place, I'd have to put together a hex sticker, looks like they're using https://www.stickermule.com/user/1069012065/stickers to distribute them

**Comment by ukmadlz** [comment]
If your going with the Hex standard, I can get a batch printed in the UK to distribute in the EU? I've just finished running @hackference and just had hexi's made, so don't mind doing it and sending them to people to give out?

You can thank @michellephung and @willholley for me piping up

**Comment by michellephung** [comment]
+1 for making stickers!

+1 for logo 
+0.75 for hex

**Comment by robertkeizer** [comment]
I've used stickermule a few times and like the result.

I would love it if any artwork used could be made available so that I ( and others ) could make their own orders.

**Comment by nickcolley** [comment]
Hey @robertkeizer,

Right now you can grab the logomark here http://pouchdb.com/static/img/mark.svg

![http://pouchdb.com/static/img/mark.svg](http://pouchdb.com/static/img/mark.svg)

Which should work for a diecut sticker.

If you need any adjustments specific for stickers let me know. :+1:

**Comment by nolanlawson** [comment]
If anyone wants to do that, that would be great
