### ISSUE TITLE
Loop through docs

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [pouchdb/pouchdb#4427]
Hello PouchDb Team,

Is there a simple way to loop through doc's in the db.allDocs function to get the doc elements?

Kind regards,
Mario

**Comment by nickcolley** [comment]
Do you mean like:

```js
db.allDocs({
  include_docs: true
}).then(function (result) {
  var docs = result.rows.map(function (row) {
    return row.doc;
  });
  console.log(docs);
}).catch(function (err) {
  console.log(err);
});
```

**Comment by nolanlawson** [comment]
Yup, that looks right to me, thanks @nickcolley.

**Comment by MarioVanDenEijnde** [comment]
Hello Nolan,

Thanks. Thats it.
Can I read these kind of tricks somewhere?

Kind regards,
Mario

**Comment by nolanlawson** [comment]
Hi Mario,

The [PouchDB guide](http://pouchdb.com/guides/) is a good place to start. Also if you look through our [blog posts](http://pouchdb.com/blog/) you'll find lots of useful stuff. Probably the blog posts you'll find most useful are http://pouchdb.com/2015/02/28/efficiently-managing-ui-state-in-pouchdb.html and http://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html
