### ISSUE TITLE
Getting error when deleting document

### ISSUE THREAD

**Issue by natcohen** [pouchdb/pouchdb#4429]
I'm using pouchdb 5.0.0 with chrome (sync with couchdb 1.6.1) and get the following (in browser) error when I delete a doc:

POST http://127.0.0.1:5984/transport/_bulk_get?revs=true&attachments=true&_nonce=1444198104314 400 (Bad Request)

It deletes the doc but sends this error...

**Comment by daleharvey** [comment]
Thats not an error, this is pouchdb attempting to use the new _bulk_get api, it will give an error if it talks to a server that doesnt support _bulk_get and fallback if it is not available

**Comment by nickcolley** [comment]
@daleharvey do we explain that error like we do for the replication checkpoint checks?
