### ISSUE TITLE
Explain normal 40x's in console.info when _bulk_get API is not supported

### ISSUE THREAD

**Issue by janraasch** [pouchdb/pouchdb#4435]
Since as of right now the _bulk_get API is not supported by most CouchDB services out there in the wild, it would be nice to have an explanation in the browser console for the http error a user receives when the _bulk_get API is not supported by the remote. Similar to #2835.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/e164a33739be1f61b560266668950f71499eb1ef
