### ISSUE TITLE
Data loss using PouchDB 3.3.1

### ISSUE THREAD

**Issue by jannone** [pouchdb/pouchdb#4437]
I'm having problems with data loss using PouchDB in an app made with Ionic Framework over Cordova. It uses local persistence only; server synchronization is not in use.

It's hard to find the root of the problem, because it happens very sporadically, and there are no clear steps to reproduce. I myself have never witnessed it, having only received reports about it.

What might be happening?

**Comment by agozie** [comment]
Any harm updating to the latest?

**Comment by daleharvey** [comment]
There has been one report of attachments being corrupted when updating from 1.8 to 4, that is the only issue we have seen reported recently that I can remember.

What is the type of dataloss? is the entirely database unreadable or is is part corruption, there have been issues in chrome where data has become unaccessible, this seems to be an issue with the underlying storage as its been no longer possible to open the database at all when it happens, but similiar been almost impossible to reproduce

**Comment by nolanlawson** [comment]
What adapter are you using? Sqlite plugin?

**Comment by jannone** [comment]
@agozie Not sure, but if I did that, I wouldn't have any guarantee that the issue would be fixed on my app... would have to wait for reports. It would be more reassuring if I could figure out the root cause. If not possible to identify, then yes, I would try a newer version and hope for the best.

@daleharvey It seems that the entire database just vanishes

@nolanlawson Just using standard initialization: 
```var localDB = new PouchDB("database-name");```

**Comment by nolanlawson** [comment]
Would be helpful to know about what device/browser you're using. I've heard reports of iOS just randomly deleting WebSQL data, for instance, but only if the device is really running out of storage.

**Comment by jannone** [comment]
@nolanlawson That's right, it is iOS. I guess there is nothing more I can do, other than upgrading to latest and using the sqlite plugin. The only issue I have now is migrating existing websql records to sqlite records... I can't seem to find an option to instantiate PouchDB for each settings, so that I could read records from one instance and replicate them to another instance.

**Comment by jannone** [comment]
Should I create a new ticket for instantiating PouchDB with an option to *not* use cordova sqlite plugin?
Reason is that I will migrate existing websql users to sqlite and update to latest PouchDB.

**Comment by nolanlawson** [comment]
I wouldn't trust the SQLite Plugin *more* than WebSQL. The SQLite Plugin does not even pass the PouchDB test suite due to bugs in the implementation.

Another option is to use the FruitDOWN adapter, which has unlimited storage: http://pouchdb.com/api.html#extras

If you would like to open an issue or a PR to add an option not to use the SQLite Plugin, though, that sounds good too.

**Comment by daleharvey** [comment]
SQLLite plugin issue
