### ISSUE TITLE
"Error: DEPTH_ZERO_SELF_SIGNED_CERT" doing a replication

### ISSUE THREAD

**Issue by SkullMasher** [pouchdb/pouchdb#4439]
Hello everyone,

I came across this error trying to replicate from my couchdb server who uses self signed certificate generated with the command from the [Arch wiki](https://wiki.archlinux.org/index.php/Couchdb#Creating_a_self-signed_certificate).

This issue has already been discussed on the request project [here](https://github.com/request/request/issues/418). But I don't really know how to implement one of the two solution in pouchdb.

**Comment by daleharvey** [comment]
Sorry for taking so long to see this, if you need to pass options to request you can do: `new PouchDB('name', {ajax: { strictSSL: false}});` as documented @ http://pouchdb.com/api.html#create_database
