### ISSUE TITLE
Quick find in 50.000 documents

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [pouchdb/pouchdb#4443]
Hello PouchDb team,

We want to build an App that uses a user input to search through about 50.000 documents.
What would you suggest:
- A remote service data call or use local PouchDb?
- use TypeAhead or the PouchDb Find plugin?

The request is fast performance.
Like to hear your advise.

Kind regards,
Mario

**Comment by agozie** [comment]
You may refer to http://pouchdb.com/2015/09/01/pouchdb-4.0.1-gotta-go-fast.html.

**Comment by MarioVanDenEijnde** [comment]
Hello Agozie,

I have read the article and understand. 
One of my concerns is that we have to "maintain" the 50.000 documents in a practical way. At the moment we use an SQL database as a source to keep the 50.000 up to date. So we need to be able to sync the source to a global Database that will take care of the sync to the local (mobile) apps.

Do you have any ideas on this?

Kind regards,
Mario

**Comment by agozie** [comment]
@MarioVanDenEijnde, a clear explanation of what you want to do will help.

**Comment by MarioVanDenEijnde** [comment]
Hello Agozie,

We have an SQL database where we keep 50.000 records up to date.
We want to build an app where the user can query through the 50.000 records (enter a search query which returns compliant records).
At this moment we are investigating the possibility to put the 50.000 records local on the mobile in a local database. So the 50.000 records become 50.000 LocalDb documents.

The question is how do we get and maintain the local dataStore. 
So together with the question: which would be the fastest experience for the user: PouchDB or your suggestions like  YDN-DB
But also which syncing mechanisme would be the most practical. SQL <-> CouchDb <-> PouchDB
(Or SQL <-> AWS-S3 <-> YDN-DB)

Am I clear now?

Like to hear your thoughts.

Kind regards,
Mario

**Comment by nolanlawson** [comment]
Hi Mario, as stated in that blog post, PouchDB is really not optimized for fast searches or indexes, especially over 50,000 documents. In your case I would definitely recommend YDN-DB or Dexie+IndexedDBShim.

PouchDB is optimized for syncing and versioning; if your 50,000 documents are not frequently changing (which it sounds like), then you will probably just run into performance problems with PouchDB.

**Comment by nolanlawson** [comment]
Closing, btw these sorts of questions are fine, but they are probably more appropriate for IRC, Slack, or Google Groups.
