### ISSUE TITLE
allDocs() and "sum"

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [pouchdb/pouchdb#4446]
Hello PouchDb team,

Is there an easy way to sum values in an allDocs list ? Now I do a for each like below but somehow it does not feel right.

```
				db.allDocs({
				include_docs: true,
				binary: true
				}).then(function (result) {
				var docs = result.rows.map(function (row) {
				return row.doc;
				});
				var sum = 0;
				for (var key in docs) {
					if (docs.hasOwnProperty(key)) {
					sum += parseInt(docs[key].ChallengeCount);
					}
				}
				return sum;
				}).then (function(sum){
				console.log(sum);
```
Kind regards,
Mario

**Comment by nickcolley** [comment]
Hey Mario,

I'd do something like:

```js
var sumOfDocs =
  result.rows
    .map(function (row) {
      return row.doc.ChallengeCount;
    })
    .reduce(function (prevCount, nextCount) {
      return prevCount + nextCount;
    }, 0);
```

So we're maping our rows to return an array of the ChallengeCount, then we use reduce to add them all together.

**Comment by MarioVanDenEijnde** [comment]
Hello Nick,

Your suggestion seems to work fine. Thanks.
But now I have got a related issue.
In a "find" function I created an index which created a design doc in the database.
And because this design doc does not have the element "ChallengeCount" I have an "undefined" in the array and thus the SumOfDocs returns a NAN.

How can I make sure I only get "numbers" in the sum?

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
Hello Nick,

I have captured it like this. If there is a better way please advise:
```
				var sumOfDocs = result.rows.map(function (row) {
				if (typeof(row.doc.ChallengeCount) != "undefined"){return parseInt(row.doc.ChallengeCount);}
				else{return 0;}
				})
				.reduce(function (prevCount, nextCount) {
				return prevCount + nextCount;
				}, 0);
				return sumOfDocs;

```
Kind regards,
Mario

**Comment by nickcolley** [comment]
This might be nicer:

```js
var sumOfDocs =
  result.rows
    .filter(function (row) {
      return row.doc.ChallengeCount;
    })
    .map(function (row) {
      return parseInt(row.doc.ChallengeCount);
    })
    .reduce(function (prevCount, nextCount) {
      return prevCount + nextCount;
    }, 0);
```

Hope that helps :+1:

**Comment by MarioVanDenEijnde** [comment]
Hello Nick,

OK. Thanks.
Interesting how we can use the filter. Can you advise where I could read more filter options?

In another case I would like to group data on dates and sum the values per date.
Can you give a hint how we would achieve this?

Kind regards,
Mario

**Comment by nolanlawson** [comment]
@MarioVanDenEijnde `filer()` is a built-in JavaScript array method, have a look here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

**Comment by MarioVanDenEijnde** [comment]
Hello Nolan,

In another case I would like to group data on dates and sum the values per date.
 Can you give a hint how we would achieve this?

Kind regards,
Mario

**Comment by nolanlawson** [comment]
@MarioVanDenEijnde https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce or just add them using the `+` operator.

**Comment by MarioVanDenEijnde** [comment]
Hello Nolan,

I have created an issue on my present code design. Can you take a look and comment on that please?
https://github.com/pouchdb/pouchdb/issues/4472

Kind regards,
Mario
