### ISSUE TITLE
leveldown not available error message result of swallowing helpful errors

### ISSUE THREAD

**Issue by cdaringe** [pouchdb/pouchdb#4447]
# problem statement
`'leveldown not available'`.  But... but, it should be! Why not?  I have leveldown installed globally and locally?

PR comin' in hot, for at least detecting one of the errors that has bit more more than a couple times

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/c22bc9d4e4e8c92ac021f027adbc518c9e263aaa
