### ISSUE TITLE
putting a document with attachments fails to pass authentication headers

### ISSUE THREAD

**Issue by tyler-johnson** [pouchdb/pouchdb#4450]
The following should fail, assuming that the database `mydb` has at least one member in the security document.

```js
var db = new PouchDB("http://localhost:5984/mydb", { 
  auth: { username: "admin", password: "12345" }
});

db.put({
  "_id": "doc",
  "title": "Legendary Hearts",
  "_attachments": {
    "att.txt": {
      "content_type": "text/plain",
      "data": new Blob(['Is there life on Mars?'], {type: 'text/plain'})
    }
  }
});
```

It seems the issue is the default request header fields are being replaced by the multipart request headers, instead of being merged.

https://github.com/pouchdb/pouchdb/blob/master/lib/adapters/http/index.js#L667
https://github.com/pouchdb/pouchdb/blob/master/lib/adapters/http/index.js#L145

**Comment by daleharvey** [comment]
Yup, confirmed we a test 

  it('4450 Test headers are sent correctly on put', function() {
    var db = new PouchDB('http://127.0.0.1:' + PORT);
    var opts = {auth: {username: 'foo', password: 'bar'}};
    return db.put({
      _id: 'doc',
      _attachments: {
        'att.txt': {
          content_type: 'text/plain',
          data: new Buffer(['Is there life on Mars?'], {type: 'text/plain'})
        }
      }
    }).then(function() {
      should.equal(headers.authorization, 'Basic Zm9vOmJhcg==');
    });
  });

**Comment by daleharvey** [comment]
hrm, as far as I can tell our close is shallow

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/6a10dff0734f29910eb296d4b3b777b9f1232357
