### ISSUE TITLE
Switch to ES6 modules and Rollup

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4456]
Well, this would be a pretty ambitious change, but it seems like it would be well worth it for the gains in size lost: https://twitter.com/Rich_Harris/status/653186863755304960

TLDR: the more we modularize our code, the bigger it gets, when we use Browserify anyway. [Rollup](https://github.com/rollup/rollup) seems to do the right thing and just include all the imports in the same function scope, vastly cutting down on the per-module boilerplate.

Sadly, though, those size gains would only apply to the distributed bundle. For npm/node/browserify/webpack, we'd now need to build a version for that as well as a browser version, since npm doesn't support ES6 modules. So ironically anybody using a "modern" setup like Browserify or Webpack would end up with a larger build than someone just clicking the "download" button. But I guess the argument is that they too should just switch to Rollup.

The only thing I'm *not* sold on is fully switching over to ES6, e.g. for every little utility function. My experience with Babel is that it ends up adding a lot of cruft, for instance a simple statement like `for foo of bar {}` ends up requiring an entire `Symbol` shim. But for the ES6 modules at least, it may be worth it.

**Comment by daleharvey** [comment]
Closing as a dupe - https://github.com/pouchdb/pouchdb/issues/4652

**Comment by nolanlawson** [comment]
My bad, sorry!
