### ISSUE TITLE
xCode return this alert method not found getBlobAsBase64String

### ISSUE THREAD

**Issue by silverwings** [pouchdb/pouchdb#4463]
When i analyze a project in xCode that use PouchDb, i return this error in SQLlightPlugin.m 
Method definition for getBlobAsBase64String:widthlenth not found

**Comment by daleharvey** [comment]
@silverwings I dont have much experience with xCode or its code analysing but this doesnt seems to be pouchdb related? the sqlightplugin is a seperate project (https://github.com/lite4cordova/Cordova-SQLitePlugin?)
