### ISSUE TITLE
Local documents are not handled the same via put or bulkDocs

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4464]

**Comment by daleharvey** [comment]
Ok, so this mainly came up because I was hitting issues removing our `http.put` which is a bunch of duplicated code that is increasing bugs + code size.

We should not have semantic differences when writing via bulkDocs vs writing via a put, put(doc) should be identical to bulkDocs([doc]) but because of https://github.com/pouchdb/pouchdb/blob/master/lib/adapter.js#L226 they are not.

I think we should remove all of the `put/get/deleteLocal` functions, we can add something when merge is called on them to make sure we dont keep large revision trees on them to maintain the optimisation and we will remove a fairly large chunk of code, have a much more consistent api and still be optimised

**Comment by daleharvey** [comment]
It looks like we would remove somewhere between 5 and 10k from the code base by doing this, but migration is going to be a hassle

**Comment by nolanlawson** [comment]
Yeah I looked into normalizing `_local` vs non-local docs across idb/websql/leveldb and it was a huge hassle and added a ton of code, so I abandoned it. Just a hunch, but we might lose as many bytes from idb/websql/leveldb as we remove from http...

**Comment by daleharvey** [comment]
I dont think we are on the same page in terms of normalising, I mean if we removed all the special handling of local documents into a seperate store we would handle the documents the same way and remove a bunch of code and things should still work, then we could add a small exception in to the rev tree handling that maintained the optimisation of not storing big trees for local docs. 

I still think that would work, but the improvement would be mostly aesthetic and it would be a very complicated change considering the migration, so maybe not worth it.

But I didnt take into account we also handle these in bulkDocs @ https://github.com/pouchdb/pouchdb/blob/master/lib/deps/docs/processDocs.js#L44, so this bug is invalid, hopefully at the least we can still get rid of the special casing in the front end and only handle it in one place

**Comment by nolanlawson** [comment]
Oh I agree it's an issue; I just mentioned why I figured it may trip you up once you go down that path. Definitely the usage should be normalized.
