### ISSUE TITLE
PouchDb sync only 100 last documents

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [pouchdb/pouchdb#4471]
Hello PouchDb team,

If one day the local Db needs to be decreased in size and we want to keep the last x documents. How would we do this?

Kind regards,
Mario

**Comment by daleharvey** [comment]
We do no currently support purge which would be the usual way to do this, the other is to replicate your database into a new one, but only since the last 100 items

**Comment by MarioVanDenEijnde** [comment]
Hello Dale,

OK. Understand. But is running out of storage capacity eventually not a sure case for everyone?
Am I missing the necessity? Or is this on your roadmap but not yet planned in time?

Kind regards,
Mario

**Comment by nolanlawson** [comment]
`purge()` is on the roadmap, yes: https://github.com/pouchdb/pouchdb/issues/802
