### ISSUE TITLE
_bulk_get sometimes requests an empty docs array

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4474]
This is a nice optimization we could sneak in; if the `docs` array is empty, there is no point in sending the `_bulk_get` request:

<img width="670" alt="screenshot 2015-10-15 15 35 46" src="https://cloud.githubusercontent.com/assets/283842/10525397/87f72c02-7352-11e5-8561-c48a2c0ce4d1.png">

Might even be a good first commit.

**Comment by daleharvey** [comment]
fixed in https://github.com/pouchdb/pouchdb/commit/8132c76b0a79b75a1ca7f19d1b85943869f6e47d
