### ISSUE TITLE
documentation: Use allDocs() to read many docs example typo

### ISSUE THREAD

**Issue by carloshanson** [pouchdb/pouchdb#4488]
On http://pouchdb.com/guides/bulk-operations.html in the **Use allDocs() to read many docs** section, there is a close bracket instead of a close curly brace in the Felix kitten function.

**Comment by daleharvey** [comment]
Good catch cheers, if you wanted to open a PR to fix it would be happy to accept (you can edit it directly in github) otherwise it will get picked up shortly, thanks

**Comment by daleharvey** [comment]
Fixed by https://github.com/pouchdb/pouchdb/commit/e77eeb25da7cfbc7d136a52ceec88ca39b6abd24
