### ISSUE TITLE
Add more users to the "who's using us" page

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4494]
Known projects/products:

* Plunkr 2 (unreleased) https://twitter.com/plnkrco/status/641436637512245249
* Drupal 8 Relaxed Web Services: https://www.drupal.org/project/relaxed
* Standard Analytics science.ai platform: http://www.standardanalytics.io/

Any others we're missing? I feel like the list hasn't been updated in awhile.

**Comment by marten-de-vries** [comment]
I stumbled upon http://delta.octavore.com/ today, which lists PouchDB in its credits section.

**Comment by daleharvey** [comment]
hospital.io

**Comment by nolanlawson** [comment]
https://pokedex.org ;)

**Comment by nolanlawson** [comment]
fixed by bd64d75d8e397e5199ee26bd0be424747929d0c6
