### ISSUE TITLE
Same-origin request to CouchDB via a proxy, but explainCors seems to be called anyway

### ISSUE THREAD

**Issue by browndav** [pouchdb/pouchdb#4501]
In https://github.com/pouchdb/pouchdb/blob/master/lib/deps/ajax/ajaxCore.js#L95, it looks like `origin` and `options.url` are compared to determine if `options.url` is prefixed by `origin`. As the test is written, it looks like it may be reversed.

I'd expect `options.url.indexOf(origin) === 0` to mean that `origin` *is* a prefix of `options.url`, and therefore the origin is the same. Did someone mean `!==` here by chance?

**Comment by daleharvey** [comment]
Yup you are right, that was a silly mistake, thanks for filing

**Comment by nolanlawson** [comment]
fixed by 6d75df9dbfaf49c4546ef24517777d65e9216ef5
