### ISSUE TITLE
Android storage data growing indefinitely

### ISSUE THREAD

**Issue by paulieo10** [pouchdb/pouchdb#4503]
Hello,

I am using PouchDB to synchronize data between a Cordova (Ionic) app (Android) and a CouchDB instance via a NodeJS proxy. I am not specifying an adapter and the default being used is IndexedDB.  I have got the synchronization working successfully, however the Apps storage data seems to be growing indefinitely. The data is growing each time PouchDB is checking for changes, I know this because I am logging out each request in the proxy and this coincides with the data size increasing.

Any ideas? I must be doing something wrong as I can't believe this is normal as surely it would be pretty unusable.

BTW, I have tried compaction but this seems to have no effect at all. 

Here is a sample of the code I am using:

```javascript
var headers = {
 ajax: {
 cache: false,
 timeout: 10000,
 headers: {
 'x-access-token': localStorageService.get('token')
 },
 }
 };

 var faamdb = new PouchDB('gr3');
 var remoteDB = new PouchDB(<URL>, headers);

 var syncFaamdb = PouchDB.sync(faamdb, remoteDB, {
 live: true,
 retry: true,
 back_off_function: function (delay) {
 if (delay === 0) {
 return 1000;
 }
 return delay * 3 > 60000 ? 60000 : delay * 3; // At least try every minute
 }
 }, {
 ajax: headers
 }).on('change', function (info) {
 console.log('handling change');
 }).on('paused', function () {
 console.log('replication paused (e.g. user went off-line)');
 }).on('active', function () {
 console.log('replicate resumed (e.g. user went back on-line)');
 }).on('denied', function (info) {
 console.log('a document failed to replicate, e.g. due to permissions');
 }).on('complete', function (info) {
 console.log('handle complete');
 }).on('error', function (err) {
 console.log('handle error');
 });
```

**Comment by nolanlawson** [comment]
Hm, without looking at your database it's difficult to know what's going on here.

How many documents are in your database? How do you know the size is increasing?

One way I would debug this: go into Chrome Dev Tools (follow instructions [here](https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging)), click the "Resources" tab, click "IndexedDB," and see where PouchDB is adding data every time you call `changes()`. It could be that we are creating too many `_local` docs?

**Comment by paulieo10** [comment]
Hi, thanks for the response. 

I only have 4 very simple documents in the database and they shouldn't be any bigger than a couple of Kb. I have left the app running for a few hours and the data is already up to ~3MB. It is the App storage data that is increasing (I am assuming this is the database but can't be sure as I don't believe you can query the size of an IndexedDB). I see the app data increasing by following these steps on an Android phone: ```Settings -> Application Manager -> "select the app" -> "look at the Data under the Storage header" ```.

I am not calling ``` changes() ``` myself but I assume the continuous sync is doing this for me?

I have looked at the IndexedDB via dev tools but I don't see any reference to any ``` _local  ``` docs.

**Comment by paulieo10** [comment]
Oh sorry, I can see ```_local docs ```. 

The database looks OK, I have the following:

- document-store = 3 docs
- by-sequence = 5 docs (I guess these include any revisions)
- local-store = 2 docs

Any further ideas?

**Comment by paulieo10** [comment]
The CouchDB which contains the replicated data is only 16.1 KB.

**Comment by paulieo10** [comment]
Just worked out the issue! Lots of wasted time...

Turns out every ```_changes ``` call that was being made was being cached due to me setting the ``` ajax.cache ``` flag to ``` false ```. Turns out the documented issue with IE is also relevant to Cordova (Android). The actual database was not growing at all.

My mistake, although I do think the flag is pretty badly named and seems a bit of reverse logic to me. At some point I must of thought I obviously don't want the calls cached so I will set the ``` ajax.cache ``` flag to ``` false ``` (granted I didn't read the documentation correctly). So you have to set ```ajax.cache: true``` to essentially turn caching off. Perhaps it should be renamed to something like ```ajax.preventCache```

**Comment by daleharvey** [comment]
@paulieo10 `cache: false` is the default and means we append a random string to each url to ensure we do not receive cached data (ie as you expect it). That does mean that you will get lots of unique urls which if they are being cached per url may add up, but pouchdb itself does not do any caching of requests

**Comment by daleharvey** [comment]
Closing this out, looks like it isnt a pouchdb issue

**Comment by nolanlawson** [comment]
For the record there was a great [SO answer from Joshua Bell at Google](http://stackoverflow.com/a/33352050/680742) that explains how IndexedDB will resize when it feels like it, even if you explicitly `compact()`.
