### ISSUE TITLE
PouchDB Failing within Atom

### ISSUE THREAD

**Issue by ShMcK** [pouchdb/pouchdb#4514]
I'm getting the following error when trying to startup PouchDB within an Atom package. 

This is likely an Atom issue, however, I thought I should check here first for any obvious errors. Atom does not allow write permissions within a package. However, there is talk of [PouchDB working within Atom](https://discuss.atom.io/t/storage-limits-with-pouchdb-and-electron/20509) on the discussion boards.

```
err {type: "OpenError", name: "OpenError", cause: Error: IO error: database/LOCK: No such file or directory at Error (native), message: "IO error: database/LOCK: No such file or directory"}
```

Simple code, taken from the demo: 

```
const PouchDB = require('pouchdb');

let db = new PouchDB('database');

function dbInit() {
  console.log('seeding db...');
  console.log(db);

  let todo = {
    _id: 'mydoc',
    title: 'test'
  };
  db.put(todo).then(function(response) {
    // handle response
  }).catch(function(err) {
    console.log(err);
  });

  db.get('mydoc').then(function(doc) {
    console.log(doc);
  }).then(function(response) {
    // handle response
  }).catch(function(err) {
    console.log(err);
  });
}

dbInit();
```

**Comment by nickcolley** [comment]
Hey @ShMcK !

Did you check out https://github.com/nolanlawson/pouchdb-electron ?

I've also had LOCK issues when trying to open the database when a instance of my app is already running, could you check that your database isn't already being used by something else?

**Comment by ShMcK** [comment]
Yes, I've applied the postInstall script from `pouchdb-electron`, though I'm not sure if it's necessary.

Under resources in Chrome Dev Tools there are no IndexedDB, Web SQL or Session Storage instances. Is there another way to check if any databases are already running?

**Comment by ShMcK** [comment]
After restarting Atom (rather than reloading it), it seems to be working now.

Thank you!

**Comment by ShMcK** [comment]
Strangely, it worked once, and after restarting the same error came back.

**Comment by ShMcK** [comment]
Fixed. It seems the issue was with the database path not compiling correctly from Typescript to JS.

**Comment by Alecyrus** [comment]
@ShMcK Hi, bro. Could you please give me more details about how to solve this ?
