### ISSUE TITLE
Reconsider defensive cloning, or make it optional

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4516]
Yes, users might do this:

```js
db.put(mydoc);
mydoc.mutateEverythingGrrrrr = 'lolwut';
```

And to protect against that, we do a defensive deep clone.

But this means that we are paying a tax for every put(), even if users are being good Cub Scouts and not mutating.

I'm especially concerned about this for Blobs, because that's a huge price for large binaries, and I'm not sure it's even necessary because I believe Blobs are immutable.

**Comment by daleharvey** [comment]
This isnt the only reason, we set _rev_tree on the object that represents the document, if we removed the clone it would mean every write would modify the document. We would definitely have to rework it to not do that (its tested, so dont need to worry about breaking it https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.basics.js#L1030, the comment there should be removed).

If we fixed it to not do that then I would be ok with removing the protection against users modifying their own documents

**Comment by nolanlawson** [comment]
Ah yeah, that's a good point. In that case, at least a shallow clone seems like something we need to do every time. But I'm still wary about the Buffer/Blob cloning.

**Comment by nolanlawson** [comment]
Closing because it's more important to be correct than to be fast.
