### ISSUE TITLE
Document bulkGet()

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4519]
The bulkGet() API is currently undocumented, but since it's technically user-facing, it ought to be.

**Comment by nolanlawson** [comment]
Some background on bulkGet():

* https://github.com/pouchdb/pouchdb/pull/3783
* https://github.com/pouchdb/pouchdb/pull/4169
* https://github.com/apache/couchdb-chttpd/pull/33
* https://issues.apache.org/jira/browse/COUCHDB-2310

**Comment by willholley** [comment]
I'm not entirely convinced - we don't document all the APIs used only for replication (e.g. revs_diff) and I don't think it's very useful as a standalone endpoint.

**Comment by kxepal** [comment]
PouchDB users cannot use bulkGet from their apps for good deeds? It useful not only for replication use case.

**Comment by willholley** [comment]
Appreciate that it might be useful but it's not something I've heard people ask for outside of replication and we don't document the other replication-related endpoints (maybe we should?).

If we do add documentation, we should provide some guidance around when to use _bulk_get vs  other bulk fetch methods (e.g. POST to primary/secondary index with multiple keys).

**Comment by daleharvey** [comment]
We document revsDiff - http://pouchdb.com/api.html#revisions_diff, I believe we document everything considered public facing (aside from this of course), I do think this needs documented

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/c9143d64dbdd381bf969bd5066d0cee6a4c2fcf7
