### ISSUE TITLE
Can I override pouch logging with my own log function?

### ISSUE THREAD

**Issue by AshokPitambar** [pouchdb/pouchdb#4520]
Hi ,

I am developing app on device which uses pouch and want to have my own logging function which overrides the pouch logging and uses my log function.Currently I'm using latest version V5.0.0 of pouch and I see that there are many console.log in the code spread across
whole code.

Does pouch has support for this? If not are there any plans to do it.

Regards,
Ashok

**Comment by daleharvey** [comment]
Yup, replied to your email but for completeness, here is an example of how to override console.log in the browser, the same applied for .warn or .error - http://stackoverflow.com/questions/9216441/intercept-calls-to-console-log-in-chrome
