### ISSUE TITLE
report-coverage job failing

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4522]
It's been failing for some time, but we didn't notice because it was ignored.

Failure seems genuine:

```
  1) test.views.js-local-http destroy using prototype:
     AssertionError: expected [ '_pouch_testdb+suffix' ] to have a length of 0 but got 1
      at tests/mapreduce/test.views.js:694:49
```

**Comment by nolanlawson** [comment]
Yeah okay this is exactly the commit that broke it: https://github.com/pouchdb/pouchdb/commit/94c7276adfe0ce36b6471874cb60d5bdbcebdacf

**Comment by daleharvey** [comment]
Fixed by https://github.com/pouchdb/pouchdb/commit/4473f6775b3b41f667c6259f6b6db0d25b02bfb5
