### ISSUE TITLE
A doc put twice appears only once in changes feed

### ISSUE THREAD

**Issue by nono** [pouchdb/pouchdb#4526]
Hi,

I'd expect that if a document is put twice with te same fields, it still appear twice in the change feed. For example, in this coffee example, we got one change for 'dummy', then one 'change' for 'doc-put-twice', and then one change for 'dummy-bis'. The change for 'doc-put-twice' is the second one (rev starts by 2-).

```coffee
#!/usr/bin/env coffee

PouchDB = require 'pouchdb'
db = new PouchDB '/tmp/pouch'
setTimeout (-> console.log 'done'), 100

doc =
    _id: 'doc-put-twice'
    docType: 'file'
    size: 42
    tags: []
db.put _id: 'dummy', ->
    db.put doc, (err, res) ->
        console.log res
        doc._rev = res.rev
        db.put doc, (err, res) ->
            db.put _id: 'dummy-bis', ->
                opts =
                    since: 0
                    live: true
                    include_docs: true
                    returnDocs: false
                db.changes(opts)
                    .on 'change', (info) ->
                        console.log info
                    .on 'error', (err) ->
                        console.log 'error', err
```

**Comment by nolanlawson** [comment]
This is actually per design of the CouchDB changes feed; changes to the same doc are collapsed during replication and when you read from the changes feed.

If you would like to know about all changes, you can use `style: 'all_docs'` in your `changes()` options, and then fetch those revs using `get({rev: '1-xxx'})`. There is also the [full-sync plugin](https://github.com/nolanlawson/pouchdb-full-sync) which will replicate non-leaf nodes as well as leaf nodes. Let me know if that helps!

**Comment by nono** [comment]
OK, thank you for the explanation.
