### ISSUE TITLE
bulk_get should not require rev property for each doc

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#4530]
In the CouchDB / CSG implementation, rev is an optional parameter for each document (e.g. from the example at https://github.com/apache/couchdb-chttpd/pull/33):

    {"docs": [{"id": "good-doc"}]}

should return :

    {
        "results": [
        {
            "docs": [
                {
                    "ok": {
                        "_id": "good-doc",
                        "_rev": "1-967a00dff5e02add41819138abb3284d",
                        "_revisions": {
                            "ids": [
                                "967a00dff5e02add41819138abb3284d"
                            ],
                            "start": 1
                        }
                    }
                }
            ]
        }

However, in PouchDB / IndexedDB, this currently results in an error:

     {
        "results": [
        {
            "docs": [
                {
                    "error": {
                        "error": true,
                        "message": "Invalid rev format",
                        "name": "bad_request",
                        "status": 400
                    }
                }
            ]
        }

**Comment by nolanlawson** [comment]
Yeah, that's weird. I thought we had that working; it should basically just do a `post()` for each one.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/aea279a26c3b214ab37c82175ea612036a8fd74b
