### ISSUE TITLE
November release

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4535]

**Comment by gut4** [comment]
Can this include custom builds https://github.com/pouchdb/pouchdb/pull/4452?

**Comment by daleharvey** [comment]
I think @nolanlawson + @nickcolley want to do a little more work on that, but we do monthly train releases and dont hold them up to get features in, that particular feature will likely go on the website as soon as its ready however

**Comment by daleharvey** [comment]
Done
