### ISSUE TITLE
Automate our Github release uploads

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4537]
I realized recently that there's actually an API to do this, so we don't need to do it manually. Would be nice to add to `run-publish.sh`.

**Comment by kartikagarwal1993** [comment]
@nolanlawson Is there any documentation I can refer to while automating the process. I don't know what all needs to be done while publishing pouch db releases on github. While digging the code I found following comment which should be responsible for publishing releases on github
https://github.com/pouchdb/pouchdb/blob/master/bin/release.sh#L53

**Comment by nolanlawson** [comment]
Yup release.sh is the code, and `CONTRIBUTING.md` describes the release steps... essentially we would just need something to do the manual steps (renaming `pouhdb.js` to `pouchdb-VERSION.js`, uploading the files to the appropriate github release). Admittedly I'm not sure it can be entirely automated though because someone still needs to fill in the release notes, but I'm assuming GitHub still allows it to stay in a "draft" state?

This might be a tricky one to solve because it's much easier if you have write access to the GitHub releases...
