### ISSUE TITLE
Allow user to disable heartbeat for replication

### ISSUE THREAD

**Issue by garethbowen** [pouchdb/pouchdb#4538]
A feature was added in #4490 to allow disabling of the heartbeat for changes feeds by passing `heartbeart:false` option. The replicate api also has a `heartbeat` option however the `false` value is never passed through to the underlying changes feed. This is due to the value failing the condition

```js
if (opts.heartbeat) { ...
```

[source](https://github.com/pouchdb/pouchdb/blob/master/lib/replicate/replicate.js#L376-L378).

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/9506c3a1a2880aae739d8a846edce070f7ed9aea
