### ISSUE TITLE
Add a timeout option to replication

### ISSUE THREAD

**Issue by garethbowen** [pouchdb/pouchdb#4540]
I'm using server side filtered replication which can be very slow, particularly when replicating since `0` in a large remote database. Furthermore I'm using live replication with a heartbeat to keep the databases synced. In both of these cases the default 30 second timeout is too short. Add an option to replication to override the default changes feed timeout.

**Comment by daleharvey** [comment]
Fixed by https://github.com/pouchdb/pouchdb/commit/9cc5d0c4eb1dc935eb7ddec6e27e819917e1f2f2
