### ISSUE TITLE
_bulk_get request error response

### ISSUE THREAD

**Issue by czb** [pouchdb/pouchdb#4542]
This proposal is based on

http://stackoverflow.com/questions/33500721/post-from-pouchdb-to-couchdb-via-iis-arr-reverse-proxy-ends-with-502-3-bad-gate

As it is now you check if the response is 4XX and if so you know that you cannot use '_bulk_get' because the server does not support it. Should not you accept any error as indication that the server does not like '_bulk_get'? I mean, I did not ask PouchDB to make '_bulk_get' requests so why should I deal with error messages coming from that request?

In this particular case I get 502 error and PouchDB treats it as an error that should be thrown. To me you should just accept that you got an error from the server and deactivate '_bulk_get' requests. 

What do you think about it?

PS: I am sure the same goes for other check requests.

**Comment by daleharvey** [comment]
Yeh a reverse proxy is fairly common and in this case it seems like 5XX deactivating bulkGet also would be sensible. pull requests would be very welcome

In this case the code is, https://github.com/pouchdb/pouchdb/blob/master/lib/adapters/http/index.js#L325

We would want to make sure that the rounded error status is either 4 or 5

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/c10f156307a18758e193a7fd1c5dc42d917e9768
