### ISSUE TITLE
PouchDB Closes and cannot open 

### ISSUE THREAD

**Issue by Xanatos007** [pouchdb/pouchdb#4544]
Hi,

Please help. After upgrading to iOS 9.1 Safari is closing PouchDB database automatically after a few minutes of inactivity. Refresh of the web page fixes this but you loose data from the current screen. We noticed it closes after switching off the iPad or iPhone while the app the running for a few minutes. We see the following error in the console,

r {message: "database has been closed", name: "Object", status: 500, error: true, toString: function}

A new PouchDB(...) does not reopen it. Please help as it's affecting our production users. This is running on a web page. We use PouchDB to cache data from the server. Our process is to create a service order using this data, while users are inspecting equipment for a service order in the iPad there's inactivity with the application. The iPad will turn off when they go back to continue working then hitting the save button the error shows since it can't update the DB with the data captured. 

Thanks in advance. 

Raj

**Comment by nolanlawson** [comment]
Which adapter are you using? WebSQL? Fruitdown? SQLite plugin? Is this a Cordova app or is it regular Safari? WKWebView or UIWebView?

**Comment by Abrissirba** [comment]
I'm not using PouchDB but I have the same problem for my own project where I'm using WebSQL to cache data in safari on IOS 9.2.

**Comment by nolanlawson** [comment]
If anybody can reproduce, please provide steps to reproduce and open a new issue. Otherwise we can't really do much... :(

**Comment by paulfrench** [comment]
We've seen this as well on ios9.1+ using the indexedb shim supported by websql.

Any ideas how to circumvent?

**Comment by nolanlawson** [comment]
Sorry, but without steps to reproduce, it's impossible to tell why this is happening. It sounds like a bug in Safari. If you can consistently reproduce, then please file a bug on WebKit (https://bugs.webkit.org/) or if it truly is a bug in PouchDB, then please re-file here with detailed steps to reproduce.

If I had to venture a hunch, I'd say you exceeded the 50MB limit and Safari is cutting you off permanently. Unfortunately browsers do not provide great mechanisms to mitigate problems with quota being exceeded.

**Comment by nolanlawson** [comment]
BTW we do not support the IndexedDBShim (https://github.com/axemclion/IndexedDBShim); at least, we do not test it in our continuous integration tests..

**Comment by fishgoh0nk** [comment]
I'm also having this issue - i'm not using pouchDB, but I am using indexedbshim - however, i believe the issue is with webkit/websql as the error is passed from native code back to the shim the that DB has been closed. The steps required the device to go into a period of inactivity (sleep the iPad for a full 10-15 minutes), then on the time request execution put a break point in any error handlers of the request execution code, there most likely is one returned from the execution.

**Comment by paulfrench** [comment]
Yes, I believe you are correct, we also think the problem is in websql where ios closes the websql database after a period of some inactivity.  We had to add some extra code in the shim where when there is a transaction error and the cause code is zero (error unknown) we attempt to re-open the database. So far this seems to have solved the problem.

**Comment by erik127** [comment]
I experience the same behaviour on iOS 9.2.1, using Pouchdb 5.3.1. I find it hard to reproduce though. I left an iPad inactive overnight and the next morning I could submit a form to Pouch fine. An hour later it stopped again and I see the attached error in the console.
Is there a way to open the database again at the moment the form is submitted? I'm not experienced with WebSQL.
Or perhaps I could use the indexeddb adapter instead webSQL or is IDB still too buggy on Safari?

**Comment by nolanlawson** [comment]
If anyone has steps to reproduce, please provide them. I've never seen this error in the wild, and this is the first I'm hearing of it.

And yes, we haven't vetted IndexedDB on iOS yet, although it does look promising.

**Comment by erik127** [comment]
Hi Nolan, I worked around it at the moment, so I can't reproduce in my current app. I made a simple test page that does nothing but PUTting a doc to Pouchdb at the push of a button. That works fine, no errors. I'll add some more logic from the app where I saw it, like authentication and syncing. Maybe that had to do with it.
Anyway, before I worked around it I could not reproduce consequently, but it went like this:
Navigated to the app in Safari (iOS 9.2.1).
Logged in using PouchDB-Authenticate.
Put a document (customer fills out form, which get put in Pouchdb)
Leave the iPad idle for a while
Fill out a new form and press submit
error 500, reason: 'database has been closed' pops up in console.

The app is a one page app (apart from login). So between filling out different forms and submitting there was no page refresh.
The strange thing is that sometimes after idle time of an hour, I got the error but also after leaving it overnight I got no error.

**Comment by daleharvey** [comment]
So this looks like a bug with the underlying OS, that it closes the connection at some time and the browser isnt maintaining it and just giving back an error. We can work around this in pouch by ensuring an active connection and we do so in the http and new indexeddb adapter but not in the existing idb / websql / leveldb adapters

**Comment by erik127** [comment]
I managed to reproduce yesterday. The first 10 tries, I didn't have an error. The id's of the docs are a timestamp. The eleventh try I got the error at the time as is displayed in the browser alert. So between the last two tries there was about 1h35. That was not the longest interval though. I didn't catch the console output as I didn't have the ipad connected. But the error description was in the alert, so it would be the same same as I posted above.
![img_0044](https://cloud.githubusercontent.com/assets/10899468/16691979/40a48188-452f-11e6-8461-71ec9348f921.PNG)
![screen shot 2016-07-08 at 17 19 29](https://cloud.githubusercontent.com/assets/10899468/16692100/9b8655d6-452f-11e6-83f2-4287ab7e1a12.png)

Below is the page I used for the test
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script> 
  <script src="https://cdn.jsdelivr.net/pouchdb/5.3.1/pouchdb.min.js">
  </script>
  <script src="/plugins/pouchdb-5.3.1.js"></script>
  <script src="/plugins/pouchdb.authentication.js"></script>
  <script>
  $(document).ready(function(){
  
  var db = new PouchDB('test');
  var remoteCouch = new PouchDB('https://xxxxxxxxx/couchdb/test', {skipSetup: true});

  var sync = function(){
   PouchDB.sync(db, remoteCouch, {
      live: true,
      retry: true
    }).on('change', function (info) {
      console.log('a change occured');
    }).on('paused', function () {
      console.log('replication paused (e.g. user went offline)');
    }).on('active', function () {
      console.log('replicate resumed (e.g. user went back online)');
    }).on('denied', function (info) {
      console.log('a document failed to replicate (e.g. due to permissions'+ info);
    }).on('complete', function (info) {
      console.log('sync complete');
    }).on('error', function (err) {
      console.log('There is an error syncing: '+err);
    });
 };

var authenticate = function(){
remoteCouch.getSession(function (err, response) {
  if (err) {
    console.log(err);
    if (err.name === 'unauthorized') {
      console.log("error 401, user not authorized");
      window.location="/";
    } else if (err.status === '500'){
      console.log("error 500");
    }
  } else if (!response.userCtx.name) {
    window.location="/";
  } else {
    console.log(response.userCtx.name+' is the current user');
    sync();
  }
});
}
authenticate();
  
  console.log("Last refresh at: "+new Date().toISOString());
  
  var test = function() {
    var testEntry = {
      _id: new Date().toISOString(),
      title: "test"
    };
    db.put(testEntry, function callback(err, result) {
      var testTime = new Date().toISOString();
      if (!err) {
        console.log("No error at: "+testTime); 
        $(".result").html("No error at: "+testTime)
      } else {
        console.log("Error = "+err.reason+" at "+testTime);
        alert("Error = "+err.reason+" at "+testTime);
        $(".result").html(err.reason+testTime)
      }
    });
   }

  $("#test").click(function(){
    test();
    });

  })

</script>
</head>
<body>
  <input type="button" id="test" value="Test">

  <div>
  <span class="result"></span>
  </div>
</body>
</html>

**Comment by daleharvey** [comment]
@erik127 There was a problem posting your example page, http://gist.github.com is useful for posting them.

**Comment by erik127** [comment]
Ah thanks, that didn't go as I expected.
Here is the link to the gist: 
<script src="https://gist.github.com/erik127/0548a456e89b130cb1c8d78cf1faafeb.js"></script>

**Comment by daleharvey** [comment]
Also switching this to an enhancement, the closed database is getting reported back to the user and can be reopened when not using the shim at least which is a reasonable behaviour when the database connection gets closed beneath us, we can retry opening the database automatically if someone wanted to write the patch for that however it that will also be the behaviour when we release the new indexeddb adapter (which will work on ios)

**Comment by baversjo** [comment]
@daleharvey When my app sleeps for a while on iOS 12 and Pouch 7.0.0 with idb adapter, I get a very similar type of error:

1. `An internal error was encountered in the Indexed Database server`
2. `Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. transaction@[native code] openTransactionSafely`

Would it be possible to reopen the connection in this case? 
Is this something that you think will be resolved in the new indexdb adapter that's currently in the works?
And lastly, do you think I can temporarily work around by catching this error and trying to reconnect with a `new PouchDB('my_db')` ?
