### ISSUE TITLE
Spurios CORS warnings

### ISSUE THREAD

**Issue by marcelgoya** [pouchdb/pouchdb#4545]
I just upgraded to the new version and I'm constantly getting the following warning:

PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header

I've enabled CORS and it worked fine with 5.0.0. I'm also experiencing a never ending loop during the sync now

**Comment by nickcolley** [comment]
There was a patch to CORS https://github.com/pouchdb/pouchdb/issues/4501 that might be why you're getting a behaviour change, maybe there was a mistake there.

Can you provide a code snippet to demonstrate the never ending loop for sync?

**Comment by marcelgoya** [comment]
Sure, below my code. It normally fires up the complete listener but he's getting into a loop between active and changes. I don't know if this is only a CB related problem or a general one.

```
       var localDB = pouchDB(window.userId, {
			auto_compaction: true
		});

		$rootScope.sync = localDB.replicate.from('https://' + window.userId + ':' + window.password + '@mydomain.com:4984/default', {
			live: false,
			retry: true,
			since: 0			
		}).on('change', function(changes) {
			console.log('PouchDB syncing inital changes');
		}).on('paused', function(err) {
			console.log('PouchDB inital sync paused');
		}).on('active', function() {
			console.log('PouchDB inital sync active');
		}).on('complete', function() {
			console.log('PouchDB inital syncing complete');
                 
                       // Do something

		}).on('denied', function() {
			console.log('PouchDB inital sync denied');
		}).on('error', function(err) {
			console.log('syncing error: ');
			console.log(err);			
		});
```

**Comment by daleharvey** [comment]
So the never ending loop is very likely https://github.com/pouchdb/pouchdb/issues/4542, I will rename this and look into the CORS issue though, not the first time that has been reported

**Comment by daleharvey** [comment]
Removed in https://github.com/pouchdb/pouchdb/commit/56da7075224da9b74981308c898c69e66a92ee2e
