### ISSUE TITLE
Different behavior with CouchDB in reduce function

### ISSUE THREAD

**Issue by copyhold** [pouchdb/pouchdb#4556]
As you see on screenshots in CouchDB key always includes all key elements as it comes from view. While in Pouch it seems limited by group_level.

![reduce](https://cloud.githubusercontent.com/assets/42069/11032390/d3ef2016-86e3-11e5-9e2f-6112401be259.png)

pls confirm.

**Comment by nolanlawson** [comment]
So you're saying the bug is that if you add `group_level` to the options, then the keys disappear?

**Comment by copyhold** [comment]
ehh...
may be, I didn't check other cases.

**Comment by nolanlawson** [comment]
If you could provide a live test to reproduce, it would be very very helpful.

**Comment by nolanlawson** [comment]
Do you think this could be related to https://github.com/pouchdb/pouchdb/issues/4578?

**Comment by nolanlawson** [comment]
should be fixed by 8b1a50bad9993dda7fcf0f4729f2841c0c36b542 / https://github.com/pouchdb/pouchdb/pull/4878, please reopen if I'm wrong about that.
