### ISSUE TITLE
withCredential error on PDB 5.1.0

### ISSUE THREAD

**Issue by hrishiballal** [pouchdb/pouchdb#4558]
I call remote database like so: 
``` javascript
var remotedb = 'https://' + couchusername + ':' + couchpassword + '@cloudantuser.cloudant.com/' + dbname;
```
and then use db.replicate.from(remotedb) to sync the remote db to local db. 

When I upgrade to pouchdb 5.1, I am getting a error saying that remote database is private and a dialog box asking to enter credentials below. 
How do I set the credentials for remote databases with the code above?  I have set the cors properly and also have created users, it works with PDB 5 but does not with 5.1

![cloudanterror](https://cloud.githubusercontent.com/assets/1588744/11039610/6c079aa6-8700-11e5-9d67-7522be64251f.png)

**Comment by hrishiballal** [comment]
Never mind, I got it like so: 
``` javascript
  var remotedb = new PouchDB('https://cloudantusername.cloudant.com/' + dbname, {
  auth: {
    username: couchusername,
    password: couchpassword
  }
  });

**Comment by hrishiballal** [comment]
I am seeing this error again after clearing out the cache.

**Comment by janraasch** [comment]
Same here.

**Comment by daleharvey** [comment]
Ok this seems very similar to https://github.com/pouchdb/pouchdb/pull/4567

Basically on _bulk_get requests were were accidently stripping the headers that got sent. Is there any chance you could check against the latest master and confirm this is fixed?

**Comment by janraasch** [comment]
yup. That must have been it. master - 3011e714633238eb4c4c74280346010bb190c8e5 works fine for me.

**Comment by daleharvey** [comment]
That is awesome thanks, fixed by https://github.com/pouchdb/pouchdb/commit/3011e714633238eb4c4c74280346010bb190c8e5

**Comment by janraasch** [comment]
Hi @daleharvey, is there an ETA for this?

**Comment by nickcolley** [comment]
@janraasch PouchDB is normally released monthly so if someone has time soon I imagine a new release will go out soon.

**Comment by janraasch** [comment]
Sounds great. Thank you very much for letting me know, @nickcolley.
