### ISSUE TITLE
Memory leaking problem with WKWebView

### ISSUE THREAD

**Issue by wilk** [pouchdb/pouchdb#4562]
Hi there!

I've just opened a new issue on the WKWebView plugin (https://github.com/Telerik-Verified-Plugins/WKWebView/issues/192).
As you can see, the problem is when the database is replicated from a remote server.

Is this a common problem?
Do you have any suggestions to workaround it?
Is it possible that PouchDB caches some big objects during the replication process?

The specs of the application are on that issue.

**Comment by daleharvey** [comment]
We shouldnt be holding on to any memory, we keep very little in memory and it is all bounded, taking a heap snapshot in chrome for http://www.npm-browser.com doesnt show any leaks

**Comment by wilk** [comment]
Clear!

Probably, the entire issue is correlated to WKWebView and for nothing with PouchDB... but you know, it's always better asking ;)

Thanks again for answering!

Cheers
Wilk

**Comment by daleharvey** [comment]
ok cool, will close this out, if you do see any problems on the pouchdb side please reopen or file a new issue, cheers
