### ISSUE TITLE
Link to Firefox Inspect should point to github

### ISSUE THREAD

**Issue by ryanolsonx** [pouchdb/pouchdb#4573]
When browsing documentation, I found a link in http://pouchdb.com/guides/databases.html that directed me to download an add-on for Firefox.  This link resulted in a 404 and on the mozilla side, I was unable to find anything with PouchDB.

**Comment by daleharvey** [comment]
Yup it seems to have disapeared from the addons listing, the source and an xpi is still available @ https://github.com/pouchdb/pouchdb-fauxton-firefox-addon

**Comment by marten-de-vries** [comment]
The extension can't pass the addons.mozilla.org requirements without significant modifications to Fauxton; that's not something I have time to do, so hosting the .xpi on Github is the only solution at the moment. Points raised by the a.m.o. reviewer were:
> 
> Your version was rejected because of the following problems (but mostly due to 4-7):
>
> 1) Native APIs: ZeroClipboard should not be needed in Firefox, as copy/paste can be handled with native APIs. Can you remove this in the next version? Similarly, Firefox supports native promises, but you are including a third party implementation.
>
> 2) Please let us know which version of require.js you are using, we need this to verify that the bundled require.js is the actual require.js.
>
> 3) In lib/main.js, you are calling postToPage recursively on a timeout if an exception occurs. If the exception does not magically go away, then you'll end up in an endless loop. Please fix this method to either handle the catch differently, or avoid retrying after a few times.
>
> 4) I'm getting a lot of errors TypeError: can't access dead object. This happens when visiting http://pouchdb.com/, open the pouch db devtools panel, then switching to a different website. I'm also getting the message "window.controllers is deprecated. Do not use it for UA detection". Maybe you can do something to avoid that.
>
> 5) I get a lot of flashing content in the devtools panel when loading, kind of like it can't decide if the page contains databases or not. The UI is also very large for me, .It would be nice if you could make the experience more smooth for users of this add-on.
>
> 6) In resources/pouchdb-fauxton/data/generated/fauxton/js/pouchdb-offline.js there seems to be code that redirects XMLHttpRequest to a local port. Can you explain why this is needed?
>
> 7) I get an untrusted connection and finally bad gateway on https://pouchdb.com/ so I cannot test this. Please either provide a different site for testing or fix the gateway error. If possible I would prefer a demo outside of pouchdb.com, so I can more easily see how remote content is being handled.

**Comment by daleharvey** [comment]
Ok, we should send the links directly to your xpi then, yeh some of those seem like they shouldnt even be problems (compatibility issues)

**Comment by marten-de-vries** [comment]
For as long as it works, we could. Firefox is moving towards [blocking 3rd party addon installs](https://wiki.mozilla.org/Addons/Extension_Signing) too though (not that I can really fault them for that), and native APIs will become blocked at some point (required for the ``allDbs()`` implementation).

**Comment by daleharvey** [comment]
The link on github is broken, @marten-de-vries are you planning on putting the .xpi back up and we switch the link to github (while it still works) or should we remove it altogether?

**Comment by marten-de-vries** [comment]
I just fixed the links, but I don't have the time to get the addon up to the latest mozilla guidelines for addons (no native stuff mostly). So if it hasn't already, even the manually downloaded xpi will stop working soon. Unless/Until someone else takes up the project, I vote we remove it from the list.

**Comment by daleharvey** [comment]
Ok thanks, yeh I tried the xpi our and that isnt working for me any more. Given the upcoming changes from Moz I think thats for the best too until someone wants to take up that work, filed PR @ https://github.com/pouchdb/pouchdb/pull/5255, cheers

**Comment by daleharvey** [comment]
Removed in https://github.com/pouchdb/pouchdb/commit/ac39b91752c3e54ac4bc265cffeaf06c536a34bb
