### ISSUE TITLE
Coerce options which should be numbers to number

### ISSUE THREAD

**Issue by wheresrhys** [pouchdb/pouchdb#4578]
e.g limit is ignored in the following 
```
db.query(`${indexName}/index`, {
    limit: "4"
})
```
Either this should error/warn or coerce to a number (which would be nice as these values will often come from url query strings), but just getting ignored isn't particularly helpful.

**Comment by daleharvey** [comment]
For a simple case like this, I think coercing them would be fine, cheers for the report, if you wanted to make PR for it would be very happy to help

**Comment by wheresrhys** [comment]
Great. I'll have a go some time in the next few days. If a value can't be
coerced to a number what are your thoughts on behaviour. I'd favour
erroring - particularly as its wrapped in the safety of a promise - but a
warning seems reasonable too

**Comment by daleharvey** [comment]
Yup if we are given a value and expecting a certain type then I would throw an error. One thing I would like to mention is that the check should be done as deep as possible to where it is actually used and not checking on the way in. I think that way has a lot of benefits

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/112faf9945e8fc746cff20f62df47a5e4f4425a6
