### ISSUE TITLE
Ability to disable Changes feed timeout

### ISSUE THREAD

**Issue by garethbowen** [pouchdb/pouchdb#4583]
For "live" changes feeds it's useful to be able to disable the timeout altogether. Currently if you pass `{timeout:false}` this fails a truthy check and the timeout is defaulted. Instead check if a value is set to any value before defaulting.

Disabling the timeout in replication should just work once the Changes implementation is patched. Check that it's working as expected and update the replication documentation.

Prior art for this option is the `heartbeat` option which takes a number or `false` to disable.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/877f29850bcf332f16663bcc3e47bb5ba59cbfbb
