### ISSUE TITLE
is "parent" a reserved word ???

### ISSUE THREAD

**Issue by simonaberry** [pouchdb/pouchdb#4585]
It appears that if you put a document that has a field called "parent", this is set to null ?

so when I do 

```javascript
strat.parent =  "proj/credits/strat/pj_f50tzfsb/st_b081h44y";
strat.parent2 = strat.parent;
companyService.saveDoc(strat); // calls a get+put
```

and then I inspect the data actual document i see
```javascript
{
  "_id": "proj/credits/strat/pj_f50tzfsb/st_2x7bkv9s",
  "name": "SImon Test",
  "active": true,
  "do": 2,
  "$$hashKey": "object:1344",
  "children": [],
  "parent": null,
  "parent2": "proj/credits/strat/pj_f50tzfsb/st_b081h44y",
  "_rev": "4-7fc60b4800741094e8bd3b93ba510067"
}
```

using .parent *used* to work ok, but i guess this has changed recently ?

**Comment by daleharvey** [comment]
It seems to still be working fine for me - http://paste.pouchdb.com/paste/1mvb0c/

Is there possibly a problem with conflicts going on? or possibly a race condition / some problem causing `.parent` to be null

**Comment by simonaberry** [comment]
Funnily enough it works for me OK on the initial create /put, but on the update it fails...






On Tue, Nov 17, 2015 at 7:45 AM -0800, "Dale Harvey" <notifications@github.com> wrote:












It seems to still be working fine for me - http://paste.pouchdb.com/paste/1mvb0c/



Is there possibly a problem with conflicts going on? or possibly a race condition / some problem causing .parent to be null

**Comment by simonaberry** [comment]
so yes it was a  non-pouchdb issue, you may close. Thanks for the help
