### ISSUE TITLE
db.sync() pause event does not forward errors sent by db.replicate() pause events

### ISSUE THREAD

**Issue by tohagan** [pouchdb/pouchdb#4592]
The replicate `backOff()` function can fire a `'pause'` event with an error arg:
  https://github.com/pouchdb/pouchdb/blob/master/lib/replicate/backoff.js#L38

However this error is not sent to the db.sync() 'pause' events.

```
  function pushPaused() {
    self.pushPaused = true;
    if (self.pullPaused) {
      self.emit('paused');
    }
  }
  function pullPaused() {
    self.pullPaused = true;
    if (self.pushPaused) {
      self.emit('paused');
    }
  }
```

Code should be ...

```
  function pushPaused(err) {
    if (err) self.emit('error', err);
    self.pushPaused = true;
    if (self.pullPaused) {
      self.emit('paused');
    }
  }
  function pullPaused(err) {
    if (err) self.emit('error', err);
    self.pullPaused = true;
    if (self.pushPaused) {
      self.emit('paused');
    }
  }
```

Arguably it perhaps should also report if 'push' or 'pull' sent the error.

**Comment by tohagan** [comment]
I had a look at the option of sending the error via the existing pause event like replicate() does but it get messy since you only want to fire a single 'pause' when both push and pull have paused so you might miss getting an important error. For example: push/pull Replication objects could fire any number of pause/active events with errors and yet never fire a pause event because they were not paused at the same time.  Safer to just emit errors as they happen. This perhaps alters the current API in that some devs may have assumed that only a single error can be emitted by sync() which is the current behaviour.

**Comment by daleharvey** [comment]
So thinking about this, not sure this is an error. `paused` and `active` are sugar to give the state of the sync as a whole, not the individual replications and as an api it doesnt really make sense for it to do so, if you need to determine the error state of the individual replications you can do so with `sync.push.on('paused', ....` + `sync.pull.on('paused', ....`

**Comment by daleharvey** [comment]
So we can discuss whether we want to improve the api here or not, but its definitely not a bug, reclassifying

**Comment by dharders** [comment]
@daleharvey I think the confusion stems from the [documentation](https://pouchdb.com/api.html#sync) example code stating that db.sync.on('paused') handler is passed an err object, which is not true. It never gets passed. 

Is the db.sync.push, db.sync.pull a stable/public API ? 

This would be handy for my situation as I prefer to use the sync() API over the replicate() API to not double up on event handlers for two way replication. I could then opt-in to double up for the 'paused' event only with your above solution. 

I like this idea. I'm off to test it...
