### ISSUE TITLE
Replicate uses different adapter

### ISSUE THREAD

**Issue by Phil-Ba** [pouchdb/pouchdb#4593]
During replication pouchdb seems to use a different adapter than I configured it with. Currently I have an in-memory adapter configured for my unit tests. However, when I try to replicate to or from a remote database, pouchdb switches the adapter. Heres the relevant lines from the log:

'%cpouchdb:adapter %c**Picked adapter: memory**%c +158ms',
'sync from start' _<- log from me before db.replicate.from call_
'%cpouchdb:adapter %c**_Picked adapter: websql_**%c +1ms', 
'sync from ok' _<- log from me after db.replicate.from call_

Observed in 5.1.0

**Comment by Phil-Ba** [comment]
As a sidenote, this was working correctly with 5.0.0. I just tested it.

**Comment by nolanlawson** [comment]
How are you replicating? Normally if you do:

```js
PouchDB.sync('foo', 'bar');
```

then there is some magic to determine what "foo" and "bar" mean. whereas if you do:

```js
var db1 = new PouchDB('foo', {adapter: 'memory'});
var db2 = new PouchDB('foo', {adapter: 'websql'});
PouchDB.sync(db1, db2);
```

Then PouchDB knows exactly which databases you're talking about.

**Comment by Phil-Ba** [comment]
Basically its like this
```
var db1 = new PouchDB('foo', {adapter: 'memory'});
dp1.replicate.to('http://someIp:port/dbname'):
```

**Comment by nolanlawson** [comment]
Hm, I'm not quite understanding your problem. Can you maybe provide a sample HTML page to reproduce? We have tons of unit tests to test replication between custom adapters, and I've never seen this come up, with any combination of `replicate.to`/`replicate.from`/`sync`.

**Comment by Phil-Ba** [comment]
I cant reproduce the problem anymore, so I will close the issue. Maybe my karma server wasnt reloading properly during the test runs.
