### ISSUE TITLE
ReferenceError: Can't find variable: PouchDB

### ISSUE THREAD

**Issue by Elalala** [pouchdb/pouchdb#4597]
I am new to PouchDB and I have been encountering this error. 

This also appears: Failed to load resource: the server responded with a status of 404 (Not Found)

Btw, I'm using ionic framework and I am using this tutorial: http://pouchdb.com/guides/setup-pouchdb.html

I'm running it through safari :(

**Comment by DanailMinchev** [comment]
Are you using Linux/Mac? Check the file permissions and change them to by read by all:

`chmod o+r pouchdb-5.1.0.js`

**Comment by nolanlawson** [comment]
It sounds like the `pouchdb.js` file is not being loaded. Please make sure that it is at the correct location on your computer. If you look in the Safari "network" tab, you will see failed network requests, including JavaScript files that failed to download.
