### ISSUE TITLE
new boy hear can you help

### ISSUE THREAD

**Issue by marcus7777** [pouchdb/pouchdb#4607]
update:
https://github.com/pouchdb/pouchdb/wiki/A-simple-put-get-example

**Comment by nickcolley** [comment]
Hey Marcus!

You can have a look at the guide on the website here: http://pouchdb.com/guides/updating-deleting.html

I've linked to a specific page about updating and deleting documents, hopefully that helps.

Alternatively if you'd prefer something more complete you could try the getting started tutorial which means you'll end up with a small app that works: http://pouchdb.com/getting-started.html

I'm going to close this but feel free to reopen if you have any other questions.

Nick

**Comment by marcus7777** [comment]
sweet thanks nick
