### ISSUE TITLE
debug mode doesn't work in a web worker

### ISSUE THREAD

**Issue by josete89** [pouchdb/pouchdb#4612]
Hello,

I've found an issue using the debug mode. In our app we have a sync process that run in a web worker  and in a determinate moment we need activate the debug mode for verify the data of requests. When we activated the debug mode pouchdb always return an error because the userColor function uses the document and isn't available in the web worker.

Thanks for you time! The library it's awesome.

Kind regards!

**Comment by nolanlawson** [comment]
Hm, interesting! I'd say this is a bug in [debug](https://github.com/visionmedia/debug), though. I'm kinda surprised it hasn't been filed yet, but I'll go ahead and file it.

**Comment by nolanlawson** [comment]
see https://github.com/visionmedia/debug/issues/240
