### ISSUE TITLE
Pouchdb 5.1.0 fails sync with authorization header

### ISSUE THREAD

**Issue by josete89** [pouchdb/pouchdb#4613]
In version 5.1.0  We've found an error when start the replication process. We've setup a proxy for see the headers sent in the requests and we've seen in in the bulkGet pouchdb don't send the Auth header, and obviously Couched returns 401.

Thanks a lot!

**Comment by willholley** [comment]
Are you using CORS? If so, can you check the response to the pre-flight request - specifically, the contents of the "Access-Control-Allow-Headers" response header. If this does not contain "authorization", then the subsequent request will not send an auth header.

Lastly, does your server-side database support bulk_get (i.e. is CouchDB 2.0 or PouchDB-Server)? If not, I think the 401 response is ok as it will cause PouchDB to fall back to compatible behaviour. If the server does support bulk_get, I'd expect the preflight response to be different and allow the client to forward the authentication header.

**Comment by josete89** [comment]
Thanks for the answer! It's seems I haven't Couchdb 2.0 that it's the problem!

**Comment by chanes-probe** [comment]
I am also seeing this issue with 5.1.  Request headers are being set correctly in other places but not with _bulk_get.  To fix, I modified line 1191 in pouchdb.js from 
`headers: host.headers` 
to 
`headers: api.getHeaders()`

**Comment by willholley** [comment]
@chanes-probe what server are you replicating against and does my comment to @josete89 apply? PouchDB attempts to query _bulk_get to see whether the server supports it - if it doesn't then I wouldn't expect authentication headers to be sent.

**Comment by daleharvey** [comment]
This was fixed in https://github.com/pouchdb/pouchdb/commit/3011e714633238eb4c4c74280346010bb190c8e5
