### ISSUE TITLE
Ajax timeouts during replication aren't reported to 'error' listener

### ISSUE THREAD

**Issue by andiih** [pouchdb/pouchdb#4614]
Background:
I was getting occasions failures in synchronising with cloudant. After talking to their support they mentioned they could see client timeout in their logs. 

"From our logs we could only see a single 500 during the provided timespan. The 500 was a GET request to the following: [url removed] which timed out on our end. In addition we can see HA Proxy termination codes: CD and CC  showing the client abort the request during data transfer and prior to establishing the connection respectively. However, these make up less than 1% of the requests during this period." 

This made me look at the timeout options and surfacing and catching such errors.

To Replicate the Issue
To demonstrate, set the timeout value to something ridiculously low: I used the following as an options object for both the local db (on which the sync is executed) and the db.replicate.from call (secondary issue - where should I set the timeout for this operation, its not clear from the docs what applies where hence the belt and braces setting?)

(timeout:1, ajax: {timeout:1}}

the result is seen in the pouchdb debug stream
```

pouchdb-5.1.0.min.js:9 PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
pouchdb-5.1.0.min.js:10 pouchdb:api https://my.remote.example.com/database +20ms allDocs error o {status: 500, name: "unknown_error", message: "Database encountered an unknown error", error: true}
pouchdb-5.1.0.min.js:10 pouchdb:api pig +30ms allDocs Object {include_docs: true, attachments: true, startkey: "ProductGroup/Home/", endkey: "ProductGroup/Home/~"}
pouchdb-5.1.0.min.js:10 pouchdb:api pig +7ms allDocs Object {include_docs: true, attachments: true, startkey: "ProductGroup/Home/", endkey: "ProductGroup/Home/~"}
pouchdb-5.1.0.min.js:10 pouchdb:api https://my.remote.example.com/database +34ms allDocs error o {status: 500, name: "unknown_error", message: "Database encountered an unknown error", error: true}
pouchdb-5.1.0.min.js:10 pouchdb:api pig +6ms get recentlySelected
```

however, neither the .on('error',function(){}) or .catch(function(){}) are called with these errors so we can't surface the issues to the user or take any actions.

(Note that CORS is enabled - no errors are shown if I have a sensible timeout)

**Comment by nolanlawson** [comment]
This seems like a good first patch, because it's easy to reproduce using the `{ajax: {timeout: 1}}` trick you describe.

**Comment by anowak** [comment]
With PouchDB 5.3.1 it works for me, i.e. after setting `{ajax: {timeout: 1}}` my error handler gets invoked with `unknown_error`.

**Comment by nolanlawson** [comment]
Excellent! If we can reproduce it, then we can fix it. :) By any chance can you create a jsbin or something to demonstrate the issue?

**Comment by daleharvey** [comment]
Yeh I am not certain what the bug is here, we have a test that a down server returns an `ETIMEDOUT` @ https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.replication.js#L4460

Requests cancelled by the client are not supposed to propogate errors, that is the polling triggering a new request and not an error.

An example of the bug / how to trigger it would be great here, thanks

**Comment by daleharvey** [comment]
Not certain this is a bug, client terminating the requests are expected when pouchdb is polling from time to time, if you still have an issue please reopen with more information for us to reproduce, thanks
