### ISSUE TITLE
Dynamic HTTP headers

### ISSUE THREAD

**Issue by dylancwood** [pouchdb/pouchdb#4620]
Hi pouchsters,

Thank you for your continued efforts to improve and maintain this amazing tool! 

I would like to gage community support for adding a feature to allow manipulation of HTTP headers prior to sending any request to a remote datastore. This can be further generalized to "_allow manipulation of AJAX request options prior to sending request_".

## What
To be specific, I would like to be able to add a HAWK authentication signature to the HTTP headers. The signature is a hash of the request properties and a client-generated nonce, so it needs to be generated on each request. 

## Why
In order to utilize our existing authentication layer, we would like to place a reverse proxy in front of our couch datastores. The reverse proxy will authenticate the request, and possibly perform additional authorization at the datastore or document level, then forward the request on to the couch datastore. 

## How
Allow a new constructor configuration option `ajax.beforeSend` that can be a function, with the following signature:
```js
   /**
    * @param {object} reqOpts is (a clone of?) the current request options object
    * @return {object|Promise} a modified reqOpts object, or a promise that will resolve to a modified reqOpts object
   function(reqOpts) {
      ...
   }
```
If this options is set, it will be called from [line 162](https://github.com/pouchdb/pouchdb/blob/7ce4b660ffe9c8809ecfc46d19ec2c659a83dad0/lib/adapters/http/index.js#L162) of _adapters/http/index.js_ as follows:
```
//helper function to make ajax request as a `thenable` action
var makeRequest = function(reqOpts) {
    return utils.ajax(reqOpts, callback);
}
var beforeSendRes = Promise.resolve(reqOpts);

if (typeof ajaxOpts.beforeSend === 'function') {
    beforeSendRes = ajaxOps.beforeSend(clone(reqOpts));
}

// if beforeSendRes is not thenable, assume it is a modified request obj
if (typeof beforeSendRes.then !== 'function') {
        beforeSendRes = Promise.resolve(beforeSendRes);
}

return beforeSendRes.then(makeRequest);
```

## Discussion
1. Maybe some options should be protected? If so, we can pass a filtered object to `beforeSend`, then extend the result of `beforeSend` with the protected options.
1. Maybe an event-driven system would be more appropriate here, to avoid accidental overrides of the `ajax.beforeSend` option.
1. Allowing async manipulation of the `reqOpts` is not required by my use case, and we could see performance benefits and simplified code by assuming that `beforeSend` is a synchronous function.

**Comment by daleharvey** [comment]
The thali project had the same requirements, so we have that ability now, you can do 

```
function myAjax() { 
   ... whatever you want to do
}

new PouchDB('name', {ajax: myAjax});
```

Does that fulfill your requirements? you can also `require("pouchdb/extras/ajax")` to call the original after modifying args / creating the headers

**Comment by dylancwood** [comment]
Thanks @daleharvey!

Looking at the [source](https://github.com/pouchdb/pouchdb/blob/7ce4b660ffe9c8809ecfc46d19ec2c659a83dad0/lib/adapters/http/index.js#L148), I don't see where the `myAjax` function would ever be evaluated. I also threw together a little [jsfiddle](http://jsfiddle.net/p6ru1cm5/1/) to test that, and I get `Error: function myAjax(){...} is not an object`. 

I looked through the `request` docs (the library used for the pouchdb `utils.ajax` object), and don't see any way to add pre-request processing (remember, I need to generate the signature on each request, not just when the pouch object is instantiated). 

**But, there is good news in all this!** It looks like `request` directly supports adding HAWK auth headers to each request. I just need to use an object like this on intialization:
```
var pouchOpts = {
  ajax: {
    hawk: {
      id: 'dh37fgj492je',
      key: 'werxhqb98rpaxn39848xrunpaw3489ruxnpa98w4rxn',
      algorithm: 'sha256'
    }
  }
};

var db = new PouchDB('name', pouchOpts);
```

I have not tested this yet, but it should meet my needs. Closing the issue.

PS: The Thali project is awesome!

**Comment by nolanlawson** [comment]
@daleharvey I believe I removed that option. My personal feeling is that if you need to override XHR with custom behavior, then the best bet is to replace `window.XMLHttpRequest` before importing PouchDB (same as for `window.Promise`).

@dylancwood Glad to know you found a solution, though! :)
