### ISSUE TITLE
PouchDB example script for Tonic-powered npm's "Try it out" link

### ISSUE THREAD

**Issue by fiatjaf** [pouchdb/pouchdb#4625]
Trying to use the imported "pouchdb" package in tonicdev.com's environment yields the following error: `Error: the 'leveldown' package is not available. install it, or, specify another storage backend using the 'db' option`. I've read somewhere that other packages relying on "leveldown" are also having this problem and Tonic is fixing it.

However, since I was trying to make PouchDB work there and was able to do so using the memory adapter, I thought that maybe it would be useful to have a complete PouchDB tutorial/example ready to be edited and run by new (and existing, why not?) users on Tonic's environment.

**Comment by nickcolley** [comment]
I think it's because leveldown requires a native build step on install, this would be really good to let people use though.

**Comment by boucher** [comment]
Hey there, just came across this and thought I'd let you know that if it wasn't working before, require("pouchdb") should be working now: https://tonicdev.com/npm/pouchdb  (it may be a bit slow right now, we're working on that issue).

**Comment by nolanlawson** [comment]
fixed by e84bd71dea558113ce1bcf43eb99f0c69ce594f0
