### ISSUE TITLE
Filtered changes API ignores deleted docs

### ISSUE THREAD

**Issue by raymatos** [pouchdb/pouchdb#4628]
Sorry to reopen this, but im having a similar issue

```js
db.changes({
                    live: true,
                    since: 'now',
                    include_docs: true,
                    filter: '_view',
                    view: collectionName + '/collection'
                }).on('change', function (change) {
                if (change.deleted) {
                  // change.id holds the deleted id
                  _internalDelete(change);
                } else { // updated/inserted
                  // change.doc holds the new doc
                  _internalAddEdit(change.doc);
                }
              }).on('error', logger.error);
```

By adding a filter and an view, deleted documents are not being caught in the change event. However if i were to remove the filter then it works.

Using version 5.1.0

**Comment by nolanlawson** [comment]
Deleted documents do not appear in a filter function, unless you delete using `put()` rather than `remove()`. There are details here: http://pouchdb.com/api.html#filtered-replication

Quote from the docs:

> Deleting filtered docs: When you use filtered replication, you should avoid using remove() to delete documents, because that removes all their fields as well, which means they might not pass the filter function anymore, causing the deleted revision to not be replicated. Instead, set the doc._deleted flag to true and then use put() or bulkDocs().
