### ISSUE TITLE
CORS Authentication Errors for OPTIONS on iOS.

### ISSUE THREAD

**Issue by thedracle** [pouchdb/pouchdb#4633]
When doing a sync against CouchDB, we receive several "Failed to load resource: Request header field Authorization is not allowed by Access-Control-Allow-Headers."  errors in the console.

It is entirely intermittent, and some OPTIONS requests succeed with no problem.

This doesn't occur on Android syncing against the very same server.

Our CORS configuration appears to be correct for our CouchDB server.

**Comment by dryajov** [comment]
What version of CouchDB? I'm on 1.6.0 and seeing a similar issue, I believe it's related to https://issues.apache.org/jira/browse/COUCHDB-2027. Would love to know if there's a workaround.

**Comment by nickcolley** [comment]
Definitely looks like a CORs error, double check http://pouchdb.com/errors.html#no_access_control_allow_origin_header

For convenience you can try https://github.com/pouchdb/add-cors-to-couchdb

Hopefully this helps, let me know :+1:

**Comment by thedracle** [comment]
We've allowed CORS support with add-cors-to-couchdb, and when Android is syncing from the exact same database, with the exact same CORS configuration, for the exact same collection, we are receiving these errors.

They seem to be occurring intermittently, and only on some subset of the OPTIONS request.

OPTIONS that result in a 204 actually seem to be the ones that resolve, where as ones that return a 200 with a JSON content body are the ones that are producing this CORS issue.

It only seems to happen on collections that have multiple revisions of documents.

**Comment by nolanlawson** [comment]
So this only occurs on iOS? Does it occur in Safari, UIWebView, or WKWebView?

**Comment by thedracle** [comment]
Our main testing environment is iOS, Pouch 5.1, and UIWebView. We tried WKWebView with similar intermittent errors occurring on OPTIONS.

It also occurs on 5.0, but not on 3.6.0.

**Comment by nolanlawson** [comment]
Can you provide a live reproducible test case? I realize it's difficult to test because you need a live running CouchDB, but if we can't reproduce then we can't really fix it.

BTW if this only occurs on iOS (and not Android), I wonder if it's actually a Safari bug. If you're able to reproduce consistently, we might be able to file a bug on WebKit and have them look into it.

**Comment by ronyrun** [comment]
I encounter this issue with Cloudant as well.
On PouchDB 5.0.0 with SAFARI : on the loading of 500 docs  I didn't encounter any issues.

On PouchDB 5.0.0 with a IOS 9 device : I get the  "Failed to load resource: Request header field Authorization is not allowed by Access-Control-Allow-Headers." errors in the console.

Especially when I do a loop of : 
```
remoteDB.get(doc._id, {attachments: true})); //with doc containing an attachement.
```

**Comment by nolanlawson** [comment]
Seems related to https://github.com/pouchdb/pouchdb/issues/4633. Basically checking for `_bulk_get` is giving us lots of problems.

**Comment by ronyrun** [comment]
this post is the #4633.

**Comment by nolanlawson** [comment]
sorry I meant https://github.com/pouchdb/pouchdb/pull/4773

**Comment by ronyrun** [comment]
I think it's OK with the new  version. let me confirm that to you

**Comment by daleharvey** [comment]
Not been seeing this recently
