### ISSUE TITLE
Compacting may increase db size in some cases.

### ISSUE THREAD

**Issue by OsamaAbbas** [pouchdb/pouchdb#4634]
Hi there,

I was trying to compare bulk insert vs individual puts to decide which is better for large sets of data, there was some insteresting results by the way, but I have found a strange behaviour. Compacting `db.compact()` may increase database filesize in some cases.

Steps to reproduce:

0. I'm using pouchdb with node.js. (Ubuntu 14.04, SSD; if this matters).
1. Try to insert some 20k rows by calling `db.put(doc);`. You'll get 6 MB database or so.
2. Now compact your database. **Check its size, in my case it was increased**.
3. Do compact again. It will decrease to its normal size.

Check this gist: https://gist.github.com/OsamaAbbas/afac29ba779c43414c1f

How to use:
`node strange.js one-by-one 20000` to insert 20k rows.
`node strange.js compact` to compact.

**Comment by nolanlawson** [comment]
IndexedDB and WebSQL (dunno which one you're using) are both unpredictable when it comes to size. They may resize themselves automatically at any time and for any reason. In WebSQL/SQLite, you can use the VACUUM command to do it early; in IndexedDB you just have to wait.

**Comment by OsamaAbbas** [comment]
Thank you for your reply. by the way I used pouchdb on node.js.

**Comment by nolanlawson** [comment]
Yep, this applies to LevelDB as well. It compacts when it wants to.

**Comment by rjsteinert** [comment]
Wowsers. Thought I was going crazy :P

**Comment by rjsteinert** [comment]
From my tests, auto-compaction can have a dramatic affect on the database size (in a good way) while running compact (even twice) actually increases the size of the database. Perhaps after running the compact function IndexedDB eventually cleans up and usage is at the same level as if you had been running with auto-compaction on?

Script I'm using for testing -> https://gist.github.com/rjsteinert/3429baff17d6070f19d64df6c1efbd36
