### ISSUE TITLE
Error 500 with CORS warning

### ISSUE THREAD

**Issue by simonaberry** [pouchdb/pouchdb#4643]
I am getting repetitive 500 errors (v5.1.0) and would appreciate some guidance on how to debug further. 

```
Uncaught (in promise) e
error: true
message: "Database encountered an unknown error"
name: "unknown_error"
result: Object
doc_write_failures: 0
docs_read: 0
docs_written: 0
end_time: Tue Dec 08 2015 21:00:53 GMT+0200 (SAST)
errors: Array[1]...
ok: false
start_time: Tue Dec 08 2015 20:14:09 GMT+0200 (SAST)
status: "aborting"
status: 50
```
followed by a warning 
```
PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
```

but I definitely have cors enabled 

```
curl --user XXX:XXX xxxx.cloudant.com/_api/v2/user/config/cors 
{
  "enable_cors": true, 
  "allow_credentials": true, 
  "origins": [
    "*"
  ]
}
```

this happens periodically, but especially when offline. I am canceling the sync as follows when offline is detected:

```
// on startup / online detected:
sync.company = db.sync(companyUrl, {live: true, retry: true})...

// if offline detected
console.log('offline detected - stopping sync');
if (sync.company) sync.company.cancel();
```

but am also seeing this error
```
offline detected - stopping sync
TypeError: o.company.cancel is not a function
    at e (vendor.js:62)
    at Object.fn (vendor.js:62)
    at n.$digest (vendor.js:5)
    at n.$apply (vendor.js:5)
````
(code has been minified)

inspecting the `sync.company` object i see it is a promise.... but the docs show that you should be able to call cancel() ??

http://pouchdb.com/api.html#sync

not sure if the sync cancel is in any way related to the 500 error, but thought it would be worth mentioning

**Comment by simonaberry** [comment]
so figured out the cancel()/promise issue.... the docs say 
```
var sync = PouchDB.sync('mydb', 'http://localhost:5984/mydb', {
  live: true,
  retry: true
}).on('change', function (info) {
  // handle change
}).on('paused', function () {
  // replication paused (e.g. user went offline)
}).on('active', function () {
  // replicate resumed (e.g. user went back online)
}).on('denied', function (info) {
  // a document failed to replicate, e.g. due to permissions
}).on('complete', function (info) {
  // handle complete
}).on('error', function (err) {
  // handle error
});

sync.cancel(); // whenever you want to cancel
````

but I think this should rather be 

```
var sync = PouchDB.sync('mydb', 'http://localhost:5984/mydb', {
  live: true,
  retry: true
});

sync.on('change', function (info) {
  // handle change
}).on('paused', function () {
  // replication paused (e.g. user went offline)
}).on('active', function () {
  // replicate resumed (e.g. user went back online)
}).on('denied', function (info) {
  // a document failed to replicate, e.g. due to permissions
}).on('complete', function (info) {
  // handle complete
}).on('error', function (err) {
  // handle error
});

sync.cancel(); // whenever you want to cancel
````

??

**Comment by ronyrun** [comment]
I encounter errors on ANDROID device (ionic)

with PouchDB 5.1.0

![image](https://cloud.githubusercontent.com/assets/7273443/11715282/e2072da4-9f40-11e5-9ecf-f19ccf4d8903.png)

and getting this error : 

![image](https://cloud.githubusercontent.com/assets/7273443/11715287/fd15d5a0-9f40-11e5-93a1-54ceaf99573e.png)

**Comment by nolanlawson** [comment]
Does this only occur with Cloudant? Which browser does it occur in?

Also please please please post screenshots of the Network panel containing the original error, because the "CustomPouchError - 500 - Database encountered an unknown error" gives us zero information.

**Comment by nolanlawson** [comment]
@simonaberry what is `o.company.cancel`? Nowhere in the PouchDB codebase do we have a `.company`.

**Comment by nolanlawson** [comment]
@simonaberry those two code snippets are equivalent, and we have many many unit tests to verify that, e.g. [this one](https://github.com/pouchdb/pouchdb/blob/fab33221c80c01b9eeee2f6ad63fa97b88f54888/tests/integration/test.sync.js#L388-L391)).

**Comment by simonaberry** [comment]
As I have multiple pouchdbs (one is called 'company') I am using a object to keep this tidy

````
var sync = {
	company : null,
	people : null
};

//start sync
sync.company = db.company.sync(companyUrl, {live: true, retry: true});  //db.company is a PouchDB

//cancel sync
if (sync.company) sync.company.cancel();
```

**Comment by simonaberry** [comment]
Regarding cancel():

I see that the unit test either rejects or resolves the promise inside the 'on'  handlers. 

In my case I am also listening  for the 'change' event (to update the sync progress indicator). I don't know why, but I thought that I shouldn't be resolving anything inside the 'change' handler as I expect multiple and ongoing 'change' events. (but now am questioning this decision). 

As a result I am have this when I inspect the sync object if I use a chain
<img width="240" alt="screen shot 2015-12-13 at 6 31 21 am" src="https://cloud.githubusercontent.com/assets/5033446/11765540/97042034-a164-11e5-82e6-a0f1b0f76266.png">

but this when I break the chain
<img width="309" alt="screen shot 2015-12-13 at 6 26 49 am" src="https://cloud.githubusercontent.com/assets/5033446/11765543/a6f6050c-a164-11e5-9f8b-fd56479ca735.png">

with
<img width="299" alt="screen shot 2015-12-13 at 6 28 38 am" src="https://cloud.githubusercontent.com/assets/5033446/11765546/affa5072-a164-11e5-946f-6d5510f408ab.png">

**Comment by simonaberry** [comment]
I have only tried with Cloudant. I will do some tests with a local couch and see what happens

I also got this error today, which may or may not help?

```
offline detected - stopping sync
online detected - starting sync
(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit. 11
  EventEmitter.addListener	
  EventEmitter.once	
  Changes	
  AbstractPouchDB.changes	
  eventFunction	
  EventEmitter.emit	
  Changes.notify	
  api._changes	
  Changes.doChanges	
  Changes	
  AbstractPouchDB.changes	
  getChanges	
  onChangesComplete	

  EventEmitter.addListener	
  EventEmitter.once	
  Changes	
  AbstractPouchDB.changes	
  eventFunction	
  EventEmitter.emit	
  Changes.notify	
  api._changes	
  Changes.doChanges	
  Changes	
  AbstractPouchDB.changes	
  getChanges	
  onChangesComplete	
```

**Comment by simonaberry** [comment]
here is the full Network screenshot:
<img width="1355" alt="screen shot 2015-12-13 at 9 24 28 am" src="https://cloud.githubusercontent.com/assets/5033446/11766002/6b5246ac-a17b-11e5-9ede-1d79af0bffce.png">

**Comment by simonaberry** [comment]
I have tested with a local CouchDB instance, and still get the CORS error, although not nearly as much....
<img width="1628" alt="screen shot 2015-12-13 at 12 38 39 pm" src="https://cloud.githubusercontent.com/assets/5033446/11766566/9bc2053c-a196-11e5-9efa-0ece56fb9367.png">

**Comment by ronyrun** [comment]
Does this only occur with Cloudant? Which browser does it occur in?

Yes on Cloudant, 
I'm on Android Ionic Framework, then I assume it's Chrome.

**Comment by Sturgelose** [comment]
@ronyrun, some info here because I'm also using Ionic framework for my app and had also huge problems with CORS.

The CORS problem comes form the Cross-Origin Resource Sharing. The thing is that if you are running your app using the command `ionic serve`, of course you will see that the app runs in chrome and all the files are changed on the fly. However there is where you have the problem: because there is a local server serving you the files, there is a man in the middle (even if it's in your computer).

Then CORS has problems because it's sharing the code with this man-in-the-middle server and it does changes, when the origin of the call comes from your browser, so total crash by CORS.

So, if you want to check, run the app from the emulator, or directly from an android or ios phone and you should see that there is no problem :) (You can still debug the app in android from chrome using remote debugger in chrome)

In order to fix that in the browser you can setup a proxy, or setup CORS in the server(as you did). However, I have had a problem that recently, you can't allow a CORS header to be * as it crashes, mostly because authentication and CORS issues (it might be your problem). So, maybe try to use what Ionic provides: http://blog.ionic.io/handling-cors-issues-in-ionic/, check the section "Setting up the proxy server". You can also try some plugins from GoogleChrome or even completely disable CORS using the `--disable-web-security` flag in Chrome.

Hope this bit of info helps!

**Comment by ronyrun** [comment]
hi @Sturgelose thx for your answer.

the problem that  I encounter occures only on device and not on the local desktop Chrome.
I encounter this cors issue only with the 5.1.0 and not with the 5.0.0

**Comment by mlegenhausen** [comment]
I have the problem on a local system with pouch-server and a local http connection. After excatly 30 seconds of no changes in the database the connection gets closed with an error 500. It seems there is no heartbeat that keeps the connection alive even if I set the heartbeat manually.

**Comment by ParsaAkbari** [comment]
To chip in here I am observing a similar problem to @ronyrun,
I am using Ionic and the app works fine both locally and within the chrome browser on the device, however when building and installing the apk the error occurs.
I am using the 'replicate.from' method to sync with a couchdb instance.

**Comment by ronyrun** [comment]
OK, 

With 5.1.0

![image](https://cloud.githubusercontent.com/assets/7273443/11909935/dc6f706e-a5ed-11e5-8c61-5b1feae5c81e.png)

![image](https://cloud.githubusercontent.com/assets/7273443/11909914/aee43f58-a5ed-11e5-9c38-b3124e6b8103.png)


![image](https://cloud.githubusercontent.com/assets/7273443/11909925/ca82f0f6-a5ed-11e5-9a23-4553db1aed7e.png)


![image](https://cloud.githubusercontent.com/assets/7273443/11909929/d144362a-a5ed-11e5-87a4-85f6b4e9961e.png)

**Comment by nolanlawson** [comment]
@ronyrun It looks like your user became logged out? I really can't tell, because I don't see the response from the server. Sorry I can't help more.

**Comment by ronyrun** [comment]
I opened a ticket on the cloudant side

**Comment by BenRayner** [comment]
I'm encountering the same problem with Cloudant. PouchDB, Ionic Framework and Cloudant. Application works correctly when serving through the browser and replicates with Cloudant but when it is deployed to an actual device PouchDB fails to replicate with an error 500. CORS is enabled in the Cloudant account.

![1](https://cloud.githubusercontent.com/assets/859897/11923527/1aaded8a-a7f9-11e5-9bdf-2137f1fdb53c.png)
![2](https://cloud.githubusercontent.com/assets/859897/11923530/1ee75a30-a7f9-11e5-8f15-4d897079602a.png)

**Comment by BenRayner** [comment]
Not sure if it helps but I managed to get it working using pouchdb-authentication library but I had to mangle it a little. First as per Cloudants docs I had to set Content-Type to application/x-www-form-urlencoded while calling pouchdb-authentication's login function but that would just produce this error from Cloudant:

![req](https://cloud.githubusercontent.com/assets/859897/11924033/a2355652-a7ff-11e5-9943-c1793dea461f.png)

I ended up modifying pouchdb.authentication.js login function to look for the 'application/x-www-form-urlencoded' content type and encode the credentials in the request body as 'name=' + username + '&password=' + password' instead of '{ name : username, password : password };'

Deploying the app still produces some errors
![result](https://cloud.githubusercontent.com/assets/859897/11924113/76b81108-a800-11e5-82e7-963bf13e5d1c.png)

However, replication with the remote Cloudant DB is successful. Is there a better way to go about this?. Thanks.

**Comment by jmd90** [comment]
Hello again, seems like it really wasn't a problem by PouchDB/ CouchDB. I've overseen that another server is running on the same ip adress, so there was a conflict.

Thanks for your reply.

Kind regards

John

**Comment by ronyrun** [comment]
@nolanlawson we don't get any response from the server.
We encounter a Cors issue throw by PouchDB.
`PouchDB: the remote database may not have CORS enabled.If not please enable CORS`

I think we get this error on a _bulk_get query attempt from Pouch to Cloudant.
Also, even if I blanked some confidential information.

We can see that the green log and the cloudant link are truncated : 

![image](https://cloud.githubusercontent.com/assets/7273443/11927906/04642068-a7d0-11e5-83c1-f162d3d8235a.png)

**Comment by shahzainb** [comment]
Hi, we're receiving the same issues on this ticket. Got a hybrid app running PouchDB with live replication, and we get the same CORS issues. The remote DB is on Cloudant with CORS enabled if that helps.

If you need example code, feel free to ask.

Thanks.

**Comment by nolanlawson** [comment]
I still don't understand what's going on, because no one has provided a test case, but my hunch is that this is a Cloudant bug related to accessing the non-existent `_bulk_get`.

**Comment by kabus202** [comment]
Yep same issue here, with 5.1.0 also with nightly. I use my own couchdb server. When my  op resumes (iOS) i get this message --> {"status":500,"name":"unknown_error","message":"Database encountered an unknown error","error":true}

**Comment by ronyrun** [comment]
@nolanlawson is there any trick for testing in order to cancel the _bulk_get calls ?

**Comment by octopitus** [comment]
Got the same issue with 5.1.0. Remote server using pouchdb-server. Although CORS enabled.

**Comment by nolanlawson** [comment]
Gentle reminder: "me too", "+1", etc. does not get the issue resolved any faster. What does: providing a reproducible test case. E.g. a minimal Cordova project that reproduces the bug.

@ronyrun No, you cannot. We didn't plan for the case where simply doing the request would cause a modal popup to appear.

**Comment by kabus202** [comment]
@nolanlawson This is how you maybe can reproduce it:

ionic:

var changes = db.changes({
        since: 'now',
        live: true,
        include_docs: true
      }).on('change', function(change) {

        onChange(change);

        // handle change
      }).on('complete', function(info) {
        // changes() was canceled
      }).on('error', function (err) {
        console.log(JSON.stringify(err))
      });

when i close the app ( and screen goes out and when i reopen the app i'm getting this error in console).

Maybe it can help.
kab

**Comment by alexander-entin** [comment]
Below is a full example demonstrating the issue (or maybe another one). Run it in Chrome, wait 30 sec and you'll get 500 and sync will be stopped. Running the same against a remove DB on another domain also gives CORS warning. So, the warning is somewhat confusing and irrelevant.
```javascript
<script src="//cdn.jsdelivr.net/pouchdb/5.1.0/pouchdb.min.js"></script>
<script>
	PouchDB.debug.enable('*')
	var localDb = new PouchDB('test')
	// PouchDB is running on localhost:
	// npm install -g pouchdb-server
	// pouchdb-server
	var remoteDb = new PouchDB('http://localhost:5984/test')
	localDb.sync(remoteDb, { live: true })
</script>
```

**Comment by ronyrun** [comment]
@alexander-entin  I don't think this is related.

**Comment by ronyrun** [comment]
I started a ionic project in order to reproduce the issue.
I added the crosswalk, and Whitelist Plugin 

replicate.to, sync and change are working properly with 5.1.0.

I'll continue the tests.

**Comment by ParsaAkbari** [comment]
@nolanlawson  @ronyrun I have a testcase working here.
https://bitbucket.org/pakbari/pouchdb_testcase/src

Things work fine on:
Google Chrome Desktop Browser
Google Chrome Android Browser

Status 500 unknown error when running:
Firefox
APK Build Android

Would be interesting to try running on iOS.

Really simple testcase, all the code is contained within
js/app.js
templates/colleges.html
index.html

**Comment by mnewmedia** [comment]
Don't have the time to read everything. But I also had CORS error and thow in what i found out. 

Fix for all POST requests are failing, but GET are working:
I changed CouchDB settings from `WWW-Authenticate = Basic realm="Administrator"` to `WWW-Authenticate = Other realm="App"`and all worked fine again.

Also if you use Cordova IOS below V4 you cannot use `cordova-plugin-whitelist` 1.1 you have to upgrade the cordova ios platform or downgrade the plugin to v1.0.0

Also add this new meta tag to your index described in cordova-plugin-whitelist.

I also read that CORS is get active when server1 makes a request to server2. But when you deployed your app there is only 1 server running, so there should not be any cors problem. Then it's most likely something other like authentication.

So I hope this stuff may helps somebody.. If not give u a sample application with a sample database.
You may need 1 hour for setting this up. But else it's almost impossible to help.

I can look more into this in about 2 weeks, till then good luck with this stupid cors stuff..

**Comment by ParsaAkbari** [comment]
@mnewmedia 
I have a testcase (see above) with minimal sample application & database:
https://bitbucket.org/pakbari/pouchdb_testcase/src

"If you use Cordova platform ios below 4.0.0" don't think this applies here.

Node version: v5.0.0
Cordova version: 5.4.1
CouchDB version: 1.5.0
PouchDB version: 5.1.0
Ionic CLI: 1.7.12
Ionic: 1.2.2
AngularJS: 1.4.3

Just to make things clear, the testcase above works fine when run in browser both on desktop and on mobile device. But if built to APK there is an error.

**Comment by ParsaAkbari** [comment]
@nolanlawson noticed using the db.info command that the database on my phone is using UTF-16 websql_encoding compared to running the application in browser which uses UTF-8 websql_encoding.

Perhaps this could be causing the problem, updated test case to include this additional information, this should be really easy for you to replicate.

https://bitbucket.org/pakbari/pouchdb_testcase/src

**Comment by ParsaAkbari** [comment]
@nolanlawson 
I noticed that encoding for websql on device is UTF-16 whereas this is UTF-8 (functional) when running off APK on device (non functional)

see updated test case here:
https://bitbucket.org/pakbari/pouchdbtestcase/src

Running ionic on chrome desktop works fine.
Running ionic on chrome mobile works fine.
Running ionic as APK on android device, doesn't work.
Running ionic on firefox desktop doesn't work.

**Comment by ParsaAkbari** [comment]
@nolanlawson I noticed that websql_encoding is UTF 16 on APK build and UTF 8 when running on desktop browser, perhaps this is relevant.

I have an updated testcase here:
https://bitbucket.org/pakbari/pouchdbtestcase/src

CORS settings on couchdb are here (need admin access to view):
http://pastebin.com/KxNkUwib

Running ionic on chrome desktop works fine.
Running ionic on chrome mobile works fine.
Running ionic as APK on android device, doesn't work.
Running ionic on firefox desktop doesn't work.

**Comment by simonaberry** [comment]
@nolanlawson simple test case showing the error 

https://plnkr.co/edit/b68N4G8KeSZSkSQUCBoP?p=preview

I get the CORS warning in Chrome, FF && IE

**Comment by ronyrun** [comment]
@simonaberry did you try with the new version 5.1.2 ?

**Comment by simonaberry** [comment]
I can confirm that the warnings are not present when using 5.2.0  (see same plunker)

Yay!

**Comment by ronyrun** [comment]
I confirm it too

**Comment by mnewmedia** [comment]
Me too, Never was happier about a release of PouchDB ;)
