### ISSUE TITLE
How to use PouchDB in web workers

### ISSUE THREAD

**Issue by trungtin** [pouchdb/pouchdb#4644]
Sorry for this dumb question, but I know that PouchDB is work is web workers, right? But I have searched around Internet, and PouchDB site, but nowhere ever say how to actually do it. I have include pouchdb script file but PouchDB constructor is not exists is `self.PouchDB` of web workers, only in window.PouchDB.

**Comment by nolanlawson** [comment]
Do this:

```
// my-web-worker.js
importScripts('/path/to/pouchdb.js');
// now pouchdb is available as a global PouchDB object
```

There are also easier ways to do this if you use e.g. Browserify to bundle your JavaScript. There is also [worker-pouch](https://github.com/nolanlawson/worker-pouch) which will give you most of the benefits of web workers without having to manage web workers at all. Good luck!
