### ISSUE TITLE
Tutorial/blogpost on using PouchDB in a web worker

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4646]
Somebody should do this, because web workers are complicated and hard. E.g. see https://github.com/pouchdb/pouchdb/issues/4644 for how people get confused by them.

The very fact that you have to do `importScripts` and that you have `self` instead of `window` makes web workers a daunting environment for JS newbies.

**Comment by nolanlawson** [comment]
If anybody wants to take this up, I would love a blog post that explains step-by-step how to use PouchDB inside a web worker, using:

1. Vanilla JS (i.e. `importScripts()`).
2. [worker-pouch](https://github.com/nolanlawson/worker-pouch) (easy mode! although it doesn't run 100% inside of the worker, so take it with a grain of salt)
3. browserify
4. webpack
5. ember/etc.?

Also bonus points for screenshots showing how to debug it!

Writing a PouchDB blog post is easy by the way. All the blog posts are kept at https://github.com/pouchdb/pouchdb/tree/master/docs/_posts.

Steps:

1. Open up an issue proposing the blog post if you need help getting ideas or structuring it.
2. Add yourself as an author to https://github.com/pouchdb/pouchdb/blob/master/docs/_data/authors.yml. (Make sure you have a [Gravatar](http://en.gravatar.com/).
3. Add a new blog post with the date that you expect it will be published (we can always change it later).
4. Write something!
5. Run `npm run build-site` and you will always have a fresh version of the site at localhost:4000. You may need to Cmd-Shift-R or Ctrl-Shift-R (hard refresh) to see the latest version, since we use AppCache.

**Comment by bhanuc** [comment]
I am up for it. Will submit a PR within a Week (at max).

**Comment by nolanlawson** [comment]
@bhanuc Awesome! :) ping us on IRC if you need any help.

**Comment by daleharvey** [comment]
Hrm apologies, was going to assign it however it seems like you need to be within the organisation in order to do so

**Comment by bhanuc** [comment]
Its fine. Anyways I was thinking to create todo list implementation with storage being offloaded to webworkers in each implementation (VanillaJS, Worker Pouch, browserify etc ). I am open to other suggestions also

**Comment by bhanuc** [comment]
@nolanlawson  I am currently working on the examples to write the article, and have worked out two todo-list app using vanillajs and pouch-worker. The code is available here - https://github.com/bhanuc/pouchdb-worker . Any critical feedback regarding complexity, style and content is welcomed. Anyways I will improve the design later

**Comment by nolanlawson** [comment]
@bhanuc That is some exceptional work! I looked over your code, and I only have a few small gripes:

* Most of our examples in the API/docs/blogposts use 2-space instead of 4-space indentation.
* `PouchWorker` should be `pouchWorker`; it's a standard JavaScript style to only use `CapsCamelCase` for constructors (e.g. `new CapsCamelCaseThing()`)
* Instead of just `onmessage = ...`, I think `self.onmesage = ...` is clearer (`self` is always the worker itself)
* Another style thing: we usually don't put `else` on its own line

Otherwise, it's looking great! I'm looking forward to the post. :)

**Comment by virattara** [comment]
Still open?

**Comment by githubSathishkumar** [comment]
@bhanuc so is it done? merged?
