### ISSUE TITLE
Few million docs on IndexDB

### ISSUE THREAD

**Issue by liratanak** [pouchdb/pouchdb#4648]
Dear,

It sound like a crazy idea that building offline app, with few million of records/docs.
That user can search/view/edit/create then synced from any devices.

I have tried around 30k docs that synced from CouchDB.
That take really much time on sync even > 10mn ( solved by pouch-dump )
But it does take around 80MB of store on the browser, which is not possible in mobile.

I would like to ask for suggestion is this kind of possible or this is really crazy ?
Really appreciate for suggestion and idea.
Thanks

Sincerely,
Liratanak

**Comment by nolanlawson** [comment]
Hi there,

In general I would not advise using PouchDB to store 30k documents. The way to think about it is this:

Do you really expect users to individually modify 30k documents and to care about individual changes to 30k documents? Each document has its own revision history, so as a developer, imagine managing 30k git repos. You probably won't manage so many even across your lifetime.

I'd say to either 1) group those documents into smaller units of "sync" that make sense, or 2) use an alternative database like Dexie/LocalForage/YDN which can store more data without the overhead of a versioning model (at the expense of being able to intelligently sync those documents).

**Comment by liratanak** [comment]
Dear @nolanlawson,

Thanks for your suggestion,
I would follow your advice.
