### ISSUE TITLE
Remove allDocs() optimization from the replicator

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4651]
As pointed out by @willholley, this optimization will actually fail in the possible (albeit unlikely) case that there are two conflicts made to the first generation, e.g. `1-x` and `1-y`. Since this optimization is no longer necessary after the `_bulk_get` fix, I suggest we include it as a _breaking change_, since it could cause unreasonable slowness for users who are still on CouchDB <1.7 or PouchDB Server <1.0.

Also obviously we should wait for CouchDB 1.7 to be released before publishing it. :)

**Comment by nolanlawson** [comment]
Calling this a bug because it technically can lead to lost data in rare cases.

**Comment by nolanlawson** [comment]
Marking as "has test case" because this is easy to repro. Insert two docs to two DBs with the exact same ID, then sync them. Then sync that to a third DB. Since they have two `1-` revisions but the hash is different (e.g. `1-x` and `2-x`), only one will be synced to the third DB.

Another way to repro is to do `bulkDocs` with `new_edits=false` and insert the conflicting gen-1 docs that way.

**Comment by daleharvey** [comment]
Its been removed, there is fallout but a bug filed for that

**Comment by willholley** [comment]
@daleharvey the optimisation is still there but attempts to skip any documents that have conflicts. We should still remove it completely as/when we can reasonably require `_bulk_get` support on the server.

Assuming the fallout bug you refer to is #5799, I don't believe this is a new bug, but an old one uncovered by the test case added in #5767, though after a few hours of debugging I still haven't identified the cause. In short, I think #5767 needs to be fixed even if we do fully remove the allDocs optimisation.
