### ISSUE TITLE
Tests themselves should be built by Browserify

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4655]
This is one of those small annoying things that has added to the technical debt of the project. It's part of the reason we've been unable to remove cruft from `PouchDB.utils`.

Instead of having a bunch of separate `test.whatever.js` files that are directly injected into `tests/integration/index.html`, I'd like to bundle them up into a single test bundle. This will free us to fully clean `PouchDB.utils` and remove weird globals from the tests.

I also see it as a housekeeping requirement for #4652.

**Comment by nolanlawson** [comment]
Also to be clear, this cookie has been licked - I'm working on this.

**Comment by daleharvey** [comment]
So this would definitely clean up the tests but I am a little worried that we will not be testing the built package of PouchDB, browserify has been fairly stable so may be worth taking the risk but the tests being built the way they are because they give us a lot of confidence `pouchdb.js` works, be nice if there was a way to get the best of both worlds

**Comment by nolanlawson** [comment]
That's a good point. I think it would be worthwhile to add an extra test that's just a smoke test and uses the built `pouchdb.js`. (or better yet, `pouchdb.min.js`, since that's what most folks will use)

**Comment by nolanlawson** [comment]
Giving up on this because it's too ambitious. Also I'm starting to realize that there is value in testing both Browserify and Webpack builds (see #4701) instead of just crossing our fingers and hoping that the build file works as-is.

In the future I'd be happy to see a `test-bundle.js` or something, but it should still get `PouchDB` from `window.PouchDB` rather than `require('../lib')`.
