### ISSUE TITLE
Confusing handling of failing request (in Node)

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb#4658]
replyWithError errors request, instead of returning a 500 server error problem is that CouchDB turns this into a 400 in [ajaxCore.js:104](https://github.com/pouchdb/pouchdb/blob/56da7075224da9b74981308c898c69e66a92ee2e/lib/deps/ajax/ajaxCore.js#L89) because response is not set. That calls `exports.generateErrorFromResponse` in [error.js](https://github.com/pouchdb/pouchdb/blob/6c14a1a6df52ce5d06c89bd006c3d96c09183bfe/lib/deps/errors.js#L187-L251) with an error { message: 'Ooops', status: 400 }, which then calls errors.getErrorTypeByProp('status', 400, undefined) which returns an error:

```js
{
  name: "bad_request",
  message: "Missing JSON list of 'docs'",
  status: 400,
  error: true
}
```

Because the `Missing JSON list of 'docs'` is the first error defined for status code 400 ([keys[0]](https://github.com/pouchdb/pouchdb/blob/6c14a1a6df52ce5d06c89bd006c3d96c09183bfe/lib/deps/errors.js#L196))

```js
var nock = require('nock')
var PouchDB = require('pouchdb')

nock('http://example.com')
  .get('/test/')
  .reply(200, {})
  .get('/test/test')
  .replyWithError('Ooops')

var db = new PouchDB('http://example.com/test')
db.get('test').catch(console.log)

// { [bad_request: Missing JSON list of 'docs']
//   status: 400,
//   name: 'bad_request',
//   message: 'Missing JSON list of \'docs\'',
//   error: true }
```

Run with latest PouchDB (5.1.0) & nock (3.4.1) in node 4.2.2

**Comment by gr2m** [comment]
I don’t know what the best way is to handle that, but the `Missing JSON list of 'docs'` error is really confusing. Maybe you have an idea?

**Comment by gr2m** [comment]
Just for reference, when you run into this bug, try debugging the value of `res` here: 
https://github.com/pouchdb/pouchdb/blob/master/lib/deps/errors.js#L201

**Comment by wilk** [comment]
I got the same error while replicating the DB and shutting down the internet connection (during the replication).
The last call of PouchDB is timed out and PouchDB actually doesn't get paused but it finish with that error.
Handling this error is hard and I expected to got PouchDB paused, not in an error state, or at least not with a so common error (400).

PouchDB 5.1.0
Replicating a remote db into a local one without live sync.

**Comment by PaulMest** [comment]
This has caused me a lot of confusion since the error returned in the console is completely unrelated to the actual underlying problem. You can see this by modifying the order of the keys in allErrors in [errors.js:164](https://github.com/pouchdb/pouchdb/blob/9c25a2351c51507e75b5a785a1fcb2c6dad66c33/src/deps/errors.js).

The error returned in the console will change from:
`Possible Unhandled Promise Rejection (id: 0):
Missing JSON list of 'docs'`

To:
`Possible Unhandled Promise Rejection (id: 0):
_id field must contain a string`

FWIW, this is my setup:

Client: iOS Simulator
* React Native
* SQLite
* PouchDB 5.3.1

Development Server: Mac OS X
* CouchDB 1.6.1

**Comment by nolanlawson** [comment]
I can confirm that this is an error message we are throwing, and not one that CouchDB is throwing ([source](https://github.com/pouchdb/pouchdb/blob/9c25a2351c51507e75b5a785a1fcb2c6dad66c33/src/deps/errors.js#L30)).

I'm happy if anybody wants to merely change it to say "failed _bulk_docs request" or something similar.

**Comment by daleharvey** [comment]
So I dont like all the assumptions and roundabout code we have in `generateErrorFromResponse`, it should make far less assumptions about the errors and pass through as much as possible, this is hiding large amount of debug information from users

**Comment by daleharvey** [comment]
Duping to https://github.com/pouchdb/pouchdb/issues/5214, its the same issue really
