### ISSUE TITLE
Reproducing template in README version out of date.

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#4660]
At the moment the template uses 3.x.x, I've made a small fork with that changed to 'latest'

https://gist.github.com/nolanlawson/816f138a51b86785d3e6

https://gist.github.com/nickcolley/241eed77e73328de4aa1

Not sure if we want to pin the dependency here though.

**Comment by daleharvey** [comment]
I think latest is totally fine for this case, the first thing we want to check is whether the bug exists on latest / master

**Comment by daleharvey** [comment]
@nickcolley I dont want to steal this, preemptive :+1:  on changing it to latest

**Comment by nickcolley** [comment]
Was thinking if @nolanlawson bumps his gist it's a bit less confusing but can open a PR if you want :)

**Comment by nolanlawson** [comment]
My bad, totally missed this issue. Bumped to latest, also using non-min instead of min.

**Comment by nickcolley** [comment]
Sweet thanks :ship:
