### ISSUE TITLE
Can't Access to Remote Database via hybrid App

### ISSUE THREAD

**Issue by jmd90** [pouchdb/pouchdb#4663]
Hello Everybody,

i have the issue that i can't connect to my remote Database. I'm using Ionic to create a Todo App which should store data offline in a SQLite DB and syncs whenever the Application goes online to a Remote Couch DB. If i try it with the ionic serve command, i can access to the remote database, only if i use localhost instead of my ip address.

To the background. I 've set up a CouchDB via windows installer. I also enabled CORS and put the IP binding to 0.0.0.0.

I'm getting the following Warnings / Errors:
Warning:
PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header

Error:
Uncaught in Promise: CustomPouchError 
message: "Database encountered an unknown error"
name: "unknown_error"
status: 500

The Code inside of my Controller:

angular.module('contactCtrl', ['contactService', 'pouchConnService'])

  .controller('contactCtrl', function ($scope, contactsList, pouchDBConnectionService, $ionicPlatform) {
    $scope.data = {showDelete: false},
      $scope.contactList = [];

    $ionicPlatform.ready(function () {

      $scope.localDB = pouchDBConnectionService.initDB('contacts', true);
      $scope.localDB.info().then(console.log.bind(console));
      $scope.remoteDB = pouchDBConnectionService.initDB('http://myipadress:5984/contacts');
      $scope.remoteDB.info().then(console.log.bind(console));

    })
    $scope.addContact = function () {
      $scope.contactList = contactsList.add();
    }

    $scope.deleteContact = function (index) {
      $scope.contactList = contactsList.delete(index);
    }
    $scope.debug = pouchDBConnectionService.enableDebugging(true);
  })

Do anybody have an idea why i cant access to my database?

**Comment by ParsaAkbari** [comment]
https://github.com/pouchdb/pouchdb/issues/4643#issuecomment-164867829
Sounds like a very similar problem.

**Comment by jmd90** [comment]
What do you mean with are things broken? If i start my app with ionic serve everything is okay because i think the localhost adress is the right one. Problem is if i start my app over an android emulator or a real Device. Then im getting the error as mentioned in my first post.

King regards jmd

**Comment by ParsaAkbari** [comment]
"What do you mean with are things broken?"
Click on the link in my original post please.

**Comment by nolanlawson** [comment]
The PouchDB errors you're seeing are likely red herrings. You should check the Network tab of the debugger to see what error you are getting back from the server. Most likely it is that the server is unreachable or that CORS isn't fully enabled or that Windows Firewall is blocking or something like that.

If you're not sure how to debug Android devices, Google has a good explanation here: https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging

**Comment by ParsaAkbari** [comment]
@nolanlawson  

Maybe I have misunderstood, but I dont see how it could be windows firewall as these are errors which occur in the android application and NOT when running on the chrome web browser (either on Desktop or on the device).
Correct me if I am wrong, but remote debugging isn't going to help because the bug doesn't occur when testing on chrome. Only when running the apk.

**Comment by nolanlawson** [comment]
@ParsaAkbari You can debug Android WebViews using the steps described, even if the WebView is running in an Android app (APK).

**Comment by jmd90** [comment]
If I check the Network Tab in Google Chrome i get the following picture.
![error](https://cloud.githubusercontent.com/assets/15338106/11926869/6febeb8e-a7c8-11e5-9912-6bfefa09a7df.PNG)

I already suppose that it could be sth. with the firewall, because as already mentioned in the ionic serve mode it works perfect, just if i want to start from a device/emulator I'm getting these errors.

**Comment by xuantain** [comment]
Hi @nolanlawson,

I build my app from Ionic and need to work on both Browser and Device (Android & iOS). I use PouchDB to store localDB on device.
When I run my app on Browser then it can connect and sync to remote database normally, but on Device then it does not work.
I took a picture to describe the error:
![pouchdb_error_on_android](https://cloud.githubusercontent.com/assets/8766500/17587537/37a10bea-5ff3-11e6-8275-f0fafe32a90f.png)

It seems the url link to resource is not correct. I'm getting these errors.

Thanks.

**Comment by ParsaAkbari** [comment]
@xuantain it could be a permissions issue, for example make sure that you add 
`<access origin="*"/>`
to config.xml

**Comment by xuantain** [comment]
Thanks @ParsaAkbari It already there on config.xml. I do not know why :/

**Comment by nolanlawson** [comment]
@xuantain From the screenshot it looks like the HTTP request at the bottom is failing. Perhaps the path is wrong? I don't see the full URL so it's hard to know.

When you're building a mobile app, you have to make sure that you can access the URL of your database _from the device_. E.g. when you're developing on your PC, `localhost` will work, but on a phone it will not because it doesn't have a connection to your PC.

**Comment by xuantain** [comment]
@nolanlawson I update the error picture to show you full URL
![pouchdb_error_on_android](https://cloud.githubusercontent.com/assets/8766500/17611105/778e6074-606e-11e6-9b21-72b6b948abc6.png)

The URL with "https" and port "6984". I can login to the CouchDB server, but when I sync DB between localDB and remoteDB by PouchDB then it occurs that error.

This is my source code for processing:
```javascript
var remoteDBOptions = {
        ajax: {
          cache: false,
          timeout: 10000
        },
        auth: {
          username: user.name,
          password: user.password
        }
      };
var pouchDBOptions = {
        adapter: 'websql',
        iosDatabaseLocation: 'default'
      };

var remoteDB = new PouchDB(dbUrl + '/' + dbName, remoteDBOptions);
var localDB = new PouchDB(dbName, pouchDBOptions);

localDB.sync(remote, {
        live: true,
        retry: true
      }).on('active', function () {
        $log.debug('PouchDBService:syncFunc:active');
      }).on('error', function (err) {
        $log.debug('PouchDBService:syncFunc:fail', err);
      });
```

After that, I can not get any information or DB from remoteDB.

**Comment by ParsaAkbari** [comment]
@xuantain 
Perhaps this will help?
http://docs.ionic.io/docs/cordova-whitelist

**Comment by xuantain** [comment]
Yes, I installed it but still have these errors :)

**Comment by dhameer** [comment]
@xuantain did installing the cordova whitelist plugin solve it?

**Comment by reyvhernandez** [comment]
@dhameer yap i got same issue, fixed by installing cordova-plugin-whitelist
