### ISSUE TITLE
Can't turn of Debug mode in cordova/phonegap

### ISSUE THREAD

**Issue by thetruesoft** [pouchdb/pouchdb#4664]
Dear team,

I am trying to turn of debug mode when deploying cordova app but it did not work. 
I test on all browser and there's no pouchdb log any more. But in cordova, there are still huge amount of log that prefix: "pouchdb:api"....

These logs obviously make the app slower. 

Any one has faced this issue and any solution so far.

Thanks
<img width="1857" alt="screen shot 2015-12-19 at 2 11 31 am" src="https://cloud.githubusercontent.com/assets/15723877/11911948/db021468-a5f5-11e5-8d3a-2cdd64220ac9.png">

**Comment by daleharvey** [comment]
So debug mode is turned off by default, did you specifically enable it? `PouchDB.debug.disable()` should turn the logging off

**Comment by thetruesoft** [comment]
@daleharvey , I enable it before. Now I am deploying the app so I did turn it off. 
As I see it only turn of on browsers. When I build cordova app and view log in Xcode, all pouch:api logs are still show up.

**Comment by nolanlawson** [comment]
@thetruesoft enabling/disabling of logs gets saved to LocalStorage. You need to clear out LocalStorage in order for it to go away, or do `PouchDB.debug.disable()`.

On a fresh install in a browser with data cleared, you shouldn't see any logs. You can clear out your browser's data in the settings, or by opening up a private window.

**Comment by thetruesoft** [comment]
@nolanlawson ,
Thanks for you reply BUT here's the thing. 
I am running pouchDB in Cordova app (NOT browser). 
I did have PouchDB.debug.disable() and I've tested and seen all browser are working fine and not more debug log on browsers. BUT all debug logs are still show up when I run Cordova app.

**Comment by nolanlawson** [comment]
@thetruesoft Cordova apps have LocalStorage as well. And they also persist data unless you uninstall the app. Also I assume this is an Android app?

Follow the instructions here (https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging) and look in the Storage -> LocalStorage section of the Chrome Dev Tools, and I guarantee that you will see that debugging is enabled in LocalStorage. Deleting LocalStorage will fix the problem.

**Comment by thetruesoft** [comment]
@nolanlawson ,
I am working on Cordova iOS app. I did uninstall completely the app on iOS device and build it again. 
The phenomena is the logs gone for the first time I run the app after uninstalling. Then I close the app, open it again and the logs show up 

I also using Safari to view log and debug iOS app. It's almost like Chrome dev tools for Android.

**Comment by nolanlawson** [comment]
@thetruesoft I'm fairly positive that somewhere in your code you are setting `debug(true)`. Can you provide a small reproducible test case?

**Comment by duydao** [comment]
I have the same effect with ionic/cordova as well, but when running the app in the browser.

I've enabled the debug mode, and disabling it doesn't work. I still see a debug entry in the local storage, but with an empty string as value. I guess deleting the item from the local storage would stop the debug messages.

**Comment by nolanlawson** [comment]
Yes, it would, that's right.
