### ISSUE TITLE
 suite2 test.replication.js-local-http Test live push checkpoint

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4678]

**Comment by daleharvey** [comment]
https://travis-ci.org/pouchdb/pouchdb/jobs/97945071

**Comment by daleharvey** [comment]
This one I have been seeing forever, so going to take a look now

**Comment by daleharvey** [comment]
Ok I think I have found it, the calls to `db.replicate` and `db.changes` can kick off concurrent constructions, this is something we try to protect against but have never fix it 100% so for now we can ensure the database is created before kicking off both of those functions, doing a run of 40 to make sure its fixed.

**Comment by daleharvey** [comment]
So I can workaround it in the test, 40 runs showed it not coming up again but it did seem there might be more with the same symptoms and we really should be handling this so looking at fixing it proper

**Comment by nolanlawson** [comment]
Nice work! I've been seeing this fail constantly as well.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/1cbcaeef98bcd3b6c817417db409dae13206eea2
