### ISSUE TITLE
Immediately cancelling replication causes segfault

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4679]
https://travis-ci.org/pouchdb/pouchdb/jobs/97955573

**Comment by daleharvey** [comment]
```
*** Error in `/home/travis/.nvm/versions/node/v0.12.9/bin/node': free(): corrupted unsorted chunks: 0x00007fd044002cb0 ***
Aborted (core dumped)
```

Pretty interesting

**Comment by daleharvey** [comment]
Started noticing a pattern, these all seem to happen in test.sync.js, or after ' Test immediate replication canceling'

**Comment by daleharvey** [comment]
Changed the title to the unlikely sounding but true bug, merged https://github.com/pouchdb/pouchdb/commit/f471a78426599636e40770b58280d4b7c58ea818 to skip the offending tests to give us some time to fix this

**Comment by daleharvey** [comment]
I did a large test run again, problem still exists across all versions of node.js - https://travis-ci.org/daleharvey/pouchdb/builds/132496526

**Comment by daleharvey** [comment]
Ugh gonna look into this again, @mikeal does this sound familiar at all? basically it seems like when we do

```
var req = request(opts);
req.abort();
```
We see either request throw an error
```
 1) test.changes.js-http it handles a bunch of individual changes in live replication:
     Error: socket hang up
      at onError (packages/pouchdb/lib/index.js:5095:18)
      at Request._callback (packages/pouchdb/lib/index.js:5137:14)
      at self.callback (packages/pouchdb/node_modules/request/request.js:200:22)
      at Request.onRequestError (packages/pouchdb/node_modules/request/request.js:831:8)
      at Socket.socketOnEnd (http.js:1624:9)
      at _stream_readable.js:944:16
```
or a segfault, sometimes the segfault doesnt even seem to be inside request code, but it only happens directly after this sync `abort` happens
```
node: ../deps/leveldb/leveldb-1.18.0/db/dbformat.h:99: leveldb::Slice leveldb::ExtractUserKey(const leveldb::Slice&): Assertion `internal_key.size() >= 8' failed.
```

This didnt always happen, it seemed to get introduced sometime around the end of last year, but it is affecting all versions here. 

Will try to narrow it down and hopefully get a request only case that fails but that sounds unlikely, it seems like the `abort` is somehow affecting other io that node is currently working on.

**Comment by daleharvey** [comment]
https://github.com/request/request/issues/2065 looks like it has some issues with the same use case, although its not causing a segfault

**Comment by daleharvey** [comment]
Another fun data point, I cant reproduce locally, so it may only be an issue in linux

**Comment by daleharvey** [comment]
Nope :(

**Comment by daleharvey** [comment]
Also being that these segfaults sometimes seem to hit level, @rvagg or @juliengruber have any ideas?

**Comment by rvagg** [comment]
If the problem exists across all versions of Node then it's very likely to be a compiled addon .. presumably leveldown. Can you give us some hints about what this is doing that's different from your other tests? What might it be doing with level that's novel in this case?

/cc @ralphtheninja

**Comment by daleharvey** [comment]
So the only thing this is doing differently from the current relatively stable tests is that whenever we add tests that do something along the lines of 
```
var req = request(opts);
req.abort();
```
We start getting intermittent segmentation faults that sometimes point to errors in leveldb, such as https://travis-ci.org/daleharvey/pouchdb/jobs/132496534

``` ✓ Test sync cancel

node: ../deps/leveldb/leveldb-1.18.0/db/dbformat.h:99: leveldb::Slice leveldb::ExtractUserKey(const leveldb::Slice&): Assertion `internal_key.size() >= 8' failed.

bin/test-node.sh: line 50:  5881 Aborted                 (core dumped) ./node_modules/.bin/mocha $BAIL_OPT --timeout $TIMEOUT --require=./tests/integration/node.setup.js --reporter=$REPORTER --grep=$GREP $TESTS_PATH
```

Notice the fail is after "Test sync cancel", right now my only guess is that the http modules abort is doing something funny with some io code path that is shared with level, but getting it to reproduce aside from intermittently on a huge test run is really hard

**Comment by rvagg** [comment]
Very interesting, can you give us a quick tl;dr on how to run the test suite and only hit the tests that might cause failure? I don't particularly want to get stuck yak shaving just to get to the heart of this. (no promises that I'll actually be able to take a look cause my backlog is kind of huge, but @ralphtheninja may be interested).

**Comment by ralphtheninja** [comment]
It wouldn't surprise me if this is related to iterators not finishing up properly, but it's just a guess and I don't like guessing ;)

@daleharvey Any chance of getting that core dump? Preferably with a debug compiled leveldown.

**Comment by daleharvey** [comment]
So I have a branch with the relevant tests unskipped @ https://github.com/pouchdb/pouchdb/tree/4679-try, `npm install && GREP=test.sync.js npm test` runs about the minimum you need to reproduce, it needs a couchdb server running and the easiest way to do that is `npm install pouchdb-server && pouchdb-server -p 5984`

I will work on getting the core dump now

**Comment by daleharvey** [comment]
Heh I have been running `while npm test; do :; done` for like an hour, I can get node errors in osx but no segfaults on osx or linux, maybe will try debugging the osx fail and see if that helps
