### ISSUE TITLE
PhantomJS perma-fail

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4686]
I'll try to take this up. I think it's due to the slow new Travis infra.

**Comment by nolanlawson** [comment]
I can repro if I run Ubuntu 12.04 LTS Server Edition in a VirtualBox. I will follow up.

```
{ browser: 'Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34',
  failures:
   [ { stack: null,
       message: 'timeout of 100000ms exceeded. Ensure the done() callback is being called in this test.',
       title: 'target doesn\'t leak "destroyed" event' } ],
  lastPassed: 'source doesn\'t leak "destroyed" event',
  passed: 984,
  failed: 1 }
```

**Comment by nolanlawson** [comment]
It's a local:http failure. WEINRE isn't providing any useful info. Still debugging.

**Comment by nolanlawson** [comment]
I've seen this exact same error in Firefox on Travis using localstorage plugin, so I _know_ that phantom is just revealing a race condition here.

**Comment by nolanlawson** [comment]
Another reason I know is because if you look at the last few builds, the `TYPE=mapreduce` tests for phantomjs are always passing. It's just the main tests that are failing.

**Comment by daleharvey** [comment]
Somehow https://github.com/pouchdb/pouchdb/commit/2f7b57baca50e893a61c33f7de15835796f083a6 magically fixed this
