### ISSUE TITLE
PouchDB replication fail Cloudant with 400

### ISSUE THREAD

**Issue by bebbi** [pouchdb/pouchdb#4692]
From a replicate call to Cloudant
db.replicate.from(dblink, {"doc_ids": docIdArr})
I'm getting the error
    error: true
    message: "Something wrong with the request"
   name: "bad_request"
   reason: "filter parameter must be of the form `designname/filtername`"
The call produced by pouch is
https://somename.cloudant.com/dbname/_changes?timeout=25000&style=all_docs&filter=_doc_ids&doc_ids=[%22R54I%22]&since=0&limit=100&_nonce=1450566287885

(that's 3.6.0, but I tried 5.1.0 with same effect).

I verified on Cloudant API docs that _doc_ids is a builtin filter for Cloudant too, and have raised a ticket. The full answer I got from support was

"doc_ids" is to be used only when filter is set to _doc_ids, while filter is name of filter function from a design document to get updates. Details can be found here: https://docs.cloudant.com/database.html#get-changes
But I didn't find you have any filter set up. Regarding the filter function, please refer to the API Doc: https://docs.cloudant.com/design_documents.html#filter-functions

I have followed up but didn't hear back. So I'm posting this here to see if there was any more experience with this issue?

**Comment by nolanlawson** [comment]
Sounds like this is a subtle difference between Cloudant and CouchDB. I seem to remember running into this when I tried to get the tests passing against Cloudant.

**Comment by ermouth** [comment]
Cloudant‘s API is indeed not fully compatible with latest CouchDB. Workaround is a filter function, say, in design doc `_design/sync`, like

```javascript
filters: {
	byId: function (doc, req){
		if (!req.query || !req.query.idlist) return false;
		var a = (req.query.idlist+"").split(",");
		if (a.indexOf(doc._id) > -1) return true;
		else return false;
	}
}
```
and then replicate by _id list using
```javascript
db.replicate.from(CouchDB_URL, {
	query_params:{
		filter :"sync/byId",
		idlist: ids.join(",") // ids is an array of _ids
	}
})
```

**Comment by willholley** [comment]
@ermouth is correct (and the Cloudant docs are not). There should be a CouchDB 2.0 compatible Cloudant release in the coming weeks but until then you'll need to define a custom filter function.

**Comment by bebbi** [comment]
Thanks all, and @ermouth and @willholley for the confirmation.

**Comment by tdupard** [comment]
Hi Will do you if the Cloudant compatible release made it yet? I have yet to find a working example of pouchDb replication to Cloudant with a view filter, are you aware of any?

**Comment by nolanlawson** [comment]
The latest (6.x) ought to be Cloudant compatible. If there are any remaining issues please file them as new bugs. :)
