### ISSUE TITLE
Webpack ignores request-browser.js

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4700]
See https://github.com/nolanlawson/pouchdb-async-storage/issues/6 and https://github.com/pouchdb/pouchdb/pull/4695.

Webpack is trying to browserify `request` itself instead of using our `request-browser.js`, which causes failures.

**Comment by nolanlawson** [comment]
Well, I am working on writing a test for Webpack build, and discovering that https://github.com/pouchdb/pouchdb/commit/f95aca6147402d82a23633c2e42d0a9911564333 actually broke Webpack. So it's good we're testing this.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/e586068e6486474ab210e50223d45c1bb82663c1
