### ISSUE TITLE
PouchDB doesn't let me destroy a database 

### ISSUE THREAD

**Issue by xDinomode** [pouchdb/pouchdb#4707]
Simply opening the database (var db = new PouchDB("myDB");) causes the following exception's:

Uncaught NotFoundError: Failed to execute 'objectStore' on 'IDBTransaction': The specified object store was not found.

And

Failed to open indexedDB, are you in private browsing mode?

I'm using version 5.1.0 
I want to call db.destroy() but it won't let me. I can create/destroy a new database but not this one specifically.

**Comment by nolanlawson** [comment]
Which browser are you using? It's possible that somehow your file system got corrupted, or you need to clear out the IndexedDB data to try again.

(I wish there was a way for PouchDB to solve that, but these are often bugs at the browser level.)

**Comment by xDinomode** [comment]
I'm using [electron](http://electron.atom.io/). It uses chromium but it's a stripped down version that doesn't have options to clear out the indexeddb database (as far as I can tell).  Perhaps I have to use raw indexeddb to clear it out somehow..sigh.

**Comment by daleharvey** [comment]
`indexedDB.delete_database('_pouch_yourdbname')` should work hopefully, if there is nothing sensitive in your database it would be great if you could upload the database files from your profile somewhere

**Comment by xDinomode** [comment]
@daleharvey oh thanks! btw it was 

    indexedDB.deleteDatabase("_pouch_yourdbname");

**Comment by nolanlawson** [comment]
@xDinomode that's exactly what `db.destroy()` does... not sure why it failed for you. could be a bug in Electron

**Comment by daleharvey** [comment]
`db.destroy` requires us to open the database before we call destroy, once we switch to the stateless constructor we "might" be able to do a `deleteDatabase` directly, but not so sure with `dependentDbs`
