### ISSUE TITLE
Inserting a new document with an invalid _rev succeeds (against local databases)

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#4712]
Against local databases, the bulkDocs function allows insertion of documents with invalid _revs.

For example:

    var db = new PouchDB("test");
    db.bulkDocs([{_id:"foo2",_rev:"1-bar"}]).then(function(results) { console.log(results);});

results in:

    [ { id: "foo2", ok: true, rev: "2-f126b7c8c8c80fa0d7bd8d989d38cd56" } ]

I'd expect a conflict error in this case. Presumbably, the invalid rev is being used to generate the incremental revision (2-f...) and treated like an update.

**Comment by willholley** [comment]
it seems that CouchDB 1.6.1 behaves in the same way:

     $ curl 'http://127.0.0.1:5984/revtest' -XPUT
     {"ok":true}

     $ curl 'http://127.0.0.1:5984/revtest/_bulk_docs' -H 'Content-Type: application/json' --data-binary '{"docs":[{"_id":"foobar","_rev":"1-123"}]}'
     [{"ok":true,"id":"foobar","rev":"2-9af8fdb20d72f07cc94e26da4857e3ae"}]

however, Cloudant / CouchDB 2.0 correctly return an error:

     $ curl 'http://127.0.0.1:15984/revtest' -XPUT
     {"ok":true}
     
     $ curl 'http://127.0.0.1:15984/revtest2/_bulk_docs' -H 'Content-Type: application/json' --data-binary     '{"docs":[{"_id":"foobar","_rev":"1-123"}]}'
     [{"id":"foobar","error":"conflict","reason":"Document update conflict."}]

@janl / @kxepal is the CouchDB 2.0 behaviour expected / correct?

**Comment by willholley** [comment]
This also occurs with single doc insertions:

     var db = new PouchDB("test");
     db.put({_id:"foo",_rev:"1-bar"}).then(function(results) { console.log(results);})

returns:

     {ok: true, id: "foo", rev: "2-fb61ce36c134030c8ad3923c259cd60f"}

**Comment by kxepal** [comment]
cc @rnewson here as well, but for me new 2.0 behaviour is correct and the right.

**Comment by daleharvey** [comment]
Fixed by https://github.com/pouchdb/pouchdb/commit/70271ec769c6bc93909ee315f98ec1ac72ab1862
