### ISSUE TITLE
postinstall task to fix people who depend on pouchdb master

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4732]
Since we're now transpiling our code, we'll need to do the build as a `postinstall` in order not to break people who add:

```
"pouchdb": "pouchdb/pouchdb"
```

to their `package.json`.

**Comment by nolanlawson** [comment]
Or `prepublish` i guess: https://docs.npmjs.com/misc/scripts

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/2be37213b03c5d5da1d79bf8b714dd8fba8c09d1
