### ISSUE TITLE
plugins are broken

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4738]
In current master, it's broken if you try to do `require('pouchdb/extras/fruitdown')` because we failed to test it in CI.

**Comment by daleharvey** [comment]
Verified working in https://github.com/pouchdb/pouchdb/commit/3b1723de5bfda66df502b628df62c33b64579f2e

**Comment by mciparelli** [comment]
In 5.2.0 it looks like it's trying to find `../lib/plugins/localstorage` but the only folder with the plugins inside `lib` is called `extras`

**Comment by nolanlawson** [comment]
I can confirm we screwed this up in 5.2.0. We should probably release a 5.2.1 right away. No idea how this slipped through.

**Comment by nolanlawson** [comment]
Yeah, okay, the `require.resolve()` test doesn't test anything, other than that Node can find the file. Unfortunately it seems we can't test it without just loading all the code

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/011a6f2ecb002085e9491a89af5bcf0e17226285
