### ISSUE TITLE
Link up more headings with anchor tag style headings

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#4743]
Mainly in the [Guides](http://pouchdb.com/guides/) section I've found myself having to tell people to look for a certain section, it'd be great if we could extend the same anchor headings we use in the other sections of the site so we can link directly to parts of the Guide.

Steps:
1 . Clone the PouchDB repo and build the site locally. (See https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md)
2 . Find headings (You can start in Guides) and replace them with anchor headings
For example the following markdown (https://github.com/pouchdb/pouchdb/blob/master/docs/_guides/index.md#what-is-pouchdb)
```markdown
What is PouchDB?
------
```
Would be replaced with
```
{% include anchor.html title="What is PouchDB?" hash="what-is-pouchdb" %}
```
3 . Submit a PR and we'll get it merged!

Feel free to post any questions relating to solving this.

**Comment by Arslanbekov** [comment]
Hi! This my first PR :)
I did everything right?

**Comment by daleharvey** [comment]
Cheers for the writeup @nickcolley and thanks for picking it up @Arslanbekov, fixed by https://github.com/pouchdb/pouchdb/commit/92f6398cd159a240a48fd0558ddb7418f6046b0a
