### ISSUE TITLE
Warning about enable CORS

### ISSUE THREAD

**Issue by dflourusso** [pouchdb/pouchdb#4752]
I already have the CORS enabled and the application works normally, but i'm getting this warning:
> PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header

How to disable this warning?

**Comment by nickcolley** [comment]
Hey @dflourusso can you tell us what version of PouchDB you're using? Thanks

**Comment by daleharvey** [comment]
@dflourusso We have removed this warning in the unreleased version, we will have a new release shortly (probably monday)

**Comment by dflourusso** [comment]
Version **5.1.0**

**Comment by dflourusso** [comment]
Thank's :)
