### ISSUE TITLE
Error working with cordoba-sqlite-storage to do a very simple query

### ISSUE THREAD

**Issue by speedpursuer** [pouchdb/pouchdb#4754]
Hello,

First I have to use sqlite because the WKWebView I need to use doesn't support the recommended websql. 

Pouchdb works great for all the functions except query - I created an index on a field and did query again the index. It works when there is any doc found but fails when no result is returned with the error below, which makes the app totally cracked:

message: "undefined is not an object (evaluating 'r.type')"

stack: "mycb@http://localhost:12344/plugins/cordova-sqlite-storage/www/SQLitePlugin.js:412:17↵callbackFromNative@http://localhost:12344/cordova.js:286:63↵http://localhost:12344/cordova.js:1103:35↵nativeEvalAndFetch@http://localhost:12344/cordova.js:1111:13↵nativeCallback@http://localhost:12344/cordova.js:1100:38

The problem doesn't exist in websql - it just returns an empty array in the promise for my app to handle. I also tested on UIWebview but have the same issue. So it seems to have something to do with the adapter between pouchdb and sqlite. I have tried with pouchdb-find and it works exactly the same - only broken when NO doc is found.

Versions: 
cordoba-sqlite-storage 0.7.14
pouchdb 5.1.0

Look forward to your help. Thanks a lot!

**Comment by daleharvey** [comment]
It sounds like you have found a reproducible issue which is a lot further than a lot of people with problems around here :) the code we have was built and is tests against websql and we havent been able to keep up with support for the sqlite plugins, if you were able to debug this further it would be a huge help :) finding what query causes that to throw would be a huge step

**Comment by nolanlawson** [comment]
Short answer: this is a bug in the SQLite Plugin. Please file it over there: https://github.com/litehelpers/Cordova-sqlite-storage

Another solution is to use an older version of the SQLite Plugin before it basically stopped working: https://github.com/nolanlawson/sqlite-plugin-fork

**Comment by nolanlawson** [comment]
Longer answer: the SQLite Plugin is not terribly reliable these days. I recommend the FruitDOWN adapter or regular WebSQL instead. Avoiding the SQLite Plugin is a very good idea.

**Comment by speedpursuer** [comment]
Thanks Nolan for your information! Really helpful! I just tried the old version of SQLite Plugin and everything works great! It's for sure the bug comes from the Plugin. 
Thanks again!
