### ISSUE TITLE
Pouch is broken when running in iOS WebView when built with Cordova/PhoneGap

### ISSUE THREAD

**Issue by trygve-lie** [pouchdb/pouchdb#4756]
This issue has been discussed and solved on [slack](https://pouchdb.slack.com/archives/general/p1452128234003441) but this is the essential issue:

The following does not create a database in iOS (WebView) when built with Cordova/PhoneGap:

```js
var db = new PouchDB('myDB');
```

The above code does work when running it in Safari on the same iOS device. The following does also work when build for Android (WebView) with Cordova/PhoneGap. 

Iow: this is Cordova / PhoneGap iOS WebView specific issue. The rest of this issue refer to this environment only.

The above code will not create a database, and the `created` event will not fire. Appending an adaptor for specific telling Pouch to use ex websql does not work either. None of the API methods will perform correctly either.

Ex, doing a simple insert will fail silently:

```js
db.put({_id: 'test'}).then(function(result) { 
    console.log('I wrote', result); 
});
```

Though, trying to create a database this way:

```js
var db = new PouchDB('myDB', function(err, db) { 
    console.log(err, db);
});
```

yelds the following error message:

```sh
"TypeError: cordova.fireWindowEvent is not a function. (In 'cordova.fireWindowEvent(opts.name + "_pouch", {})', cordova.fireWindowEvent' is undefined);"
```

Removing [this block](https://github.com/pouchdb/pouchdb/blob/master/src/adapters/websql/index.js#L521) and [this block](https://github.com/pouchdb/pouchdb/blob/master/src/constructor.js#L170) does resolve the issue and Pouch works as expected.

A big thank you to @daleharvey for helping out debugging and resolving this issue on slack!! Mucho tusen takk!

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/b94f4b8827af3cb6da30272ec0061d8f06a29ade, Mange takk til deg :)
