### ISSUE TITLE
Support filters for logging

### ISSUE THREAD

**Issue by AgDude** [pouchdb/pouchdb#4758]
I would like a way to enable logging for only long-running queries. I can also see the use case where I might want to enable logging on only a single database, or only for very specific queries I know are critical.

A nice way so support this might be some sort of pluggable formatter/handler which would receive every message in object form and decide what to do with it. This would also make it easy to send logs to a backend service.

Any sense of what it would take to implement something like this? I see you are using https://github.com/visionmedia/debug for logging, which wants a string, so there would need to be an intermediary function to take a data object and string format, to put it into debug.

**Comment by nickcolley** [comment]
Hey @AgDude 

One slightly hacky idea might be to intercept console.log and filter against that... http://tobyho.com/2012/07/27/taking-over-console-log/

Otherwise I wonder if you could use the Performance Web APIs

Apart from this you could create a plugin https://github.com/pouchdb/plugin-seed to do it.

**Comment by AgDude** [comment]
Thanks for the reply. Using a regex against console.log is going to add too much overhead. This is running on mobile devices. I would like to catch the statements before they are ever sent to console.log.

I haven't looked closely yet, but I had assumed that the logging is taking place deep enough that I won't be able to change it with a plugin.

**Comment by daleharvey** [comment]
If you are looking for logging specific queries and databases, that seems like the type of logging that would be handled by your application? ie 

```
log('starting a query');
db.find(....)
```

What specifically would you be looking for from pouchdb? code examples may help, cheers

**Comment by AgDude** [comment]
If I enable debug, I get log output something like this:
`pouchdb:api my_database +2s bulkDocs success `

I would like to be able to intercept this data, so a log handler function would get an object like:
```{
db: 'my_database',
action: 'bulkDocs',
status: success,
time: 2000
}```

The default logging handler would put this into a string and send it to `debug`. But I might write a handler like this (really, these should be two separate handlers, and this api would accept and array of log handlers).
```
function(log){
  if ( log.time > 600 ){ console.log(...)}
  else if ( db: 'importantdb' && log.time > 100 ){ 
    $http.post(...);
    myLogDB.put(log);
  }
}
```
I would also like to do this in a way that minimizes overhead introduced by the default logging.

**Comment by daleharvey** [comment]
That looks like something super useful, but debug is not for timing things, it seems like the best thing would be to write a wrapper for those functions you particularly care about, something like:

```
function instrument(fun) { 
  return function() { 
      var start = Date.now();
      return fun.call(...arguments).then(function() { 
      var time = Date.now() - start;
      .... do your logging here
      return val;
    }
  });
}
```

**Comment by daleharvey** [comment]
So I think this is definitely something best done outside of PouchDB, I dont see any value in adding hooks to pouchdb when you can time the functions you need to yourself, cheers
