### ISSUE TITLE
all tests need a rebuild before testing

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4762]
I think with the extra compile step there are going to be a few of these. We can just put `npm run build` before test component however its a long build process

@nolanlawson in the work you are doing in https://github.com/pouchdb/pouchdb/pull/4741, would it be possible to split out the build steps so if we only need the babel conversion we can do only that, then only build `pouchdb.js` and a seperate one to do all the fruitdown and the plugins etc

**Comment by daleharvey** [comment]
Just making note that `npm test` needs this too

**Comment by nolanlawson** [comment]
Not sure what you mean by this? In Travis, we always do an `npm run build` after `npm install` (it's a `prepublish`, so it happens automatically), and for `npm run dev`, the whole codebase is rebuilt anytime a single file changes.

My idea for a workflow here was that, if you were just testing Node-related stuff (i.e. you didn't have `npm run dev` running), you'd just run `npm run build` before you do `npm t` or whatever your test step is. Doing it automatically would be nice for development, but it'd be hard to stop Travis from needlessly running the build twice.

**Comment by daleharvey** [comment]
It wasnt for travis was meaning local workflows, its confusing to have to know which tests you need to do a `npm run build` before or not, I think `npm install && npm test` should basically always work. I have the PR for fixing it up now though

**Comment by nolanlawson** [comment]
`npm install` will automatically do `npm run build`, yeah. The only really tricky one is the unit tests, since those need `npm run build-as-modular-es5`, which was a dirty hack, but I couldn't figure out a better way.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/443cd66992337093ec963a61d1d3d333d63c6a4b
