### ISSUE TITLE
(cordova) IOS 9 - FruitDown - TypeError: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by ronyrun** [pouchdb/pouchdb#4771]
Hello, 

I encounter this error when I try to do a:

```javascript
factory.localDB.allDocs({
                            include_docs: true,
                            attachments:true,
                            binary:true,
                        })
```

![capture d ecran 2016-01-09 a 23 38 21](https://cloud.githubusercontent.com/assets/7273443/12218810/2e6fcc04-b72a-11e5-9bd7-045e20e76a3a.png)

I use the FruitDown adapter on a IOS 9 Device with WkWebview.
PouchDB 5.1.0 with Cordova Ionic on a IOS9 device.

![capture d ecran 2016-01-10 a 00 30 40](https://cloud.githubusercontent.com/assets/7273443/12219013/889224c8-b731-11e5-9f03-f983ab11a987.png)

With SAFARI it is working properly.

What can I use for a Cordova IOS 9 app ?

regards

**Comment by ronyrun** [comment]
Working properly on the nightly

**Comment by trygve-lie** [comment]
Sounds like you are hitting this issue: https://github.com/pouchdb/pouchdb/issues/4756

**Comment by daleharvey** [comment]
Yup looks like it here, cheers, closing as a dupe - https://github.com/pouchdb/pouchdb/issues/4756, we will be doing a release likely tomorrow

**Comment by ronyrun** [comment]
Can't wait for it Dale :)

**Comment by kentongray** [comment]
so just as an extra note, I'm having the exact opposite problem get this error on safari on the desktop but not on iOS simulator safari. Will see if I can get more info for a test case
