### ISSUE TITLE
HTTPPouch does not work in strict mode with Browserify

### ISSUE THREAD

**Issue by quarterto** [pouchdb/pouchdb#4777]
`js-extend` isn't CommonJS, but because it attaches to the window in non-strict mode HTTPPouch can reference it. With Browserify, the bundle runs in strict mode and every module runs in a function, so `js-extend` can't attach to the window and HTTPPouch ends up throwing `TypeError: extend is not a function`. I'm submitting a pull request there so it plays nicely with CommonJS.

**Comment by quarterto** [comment]
vmattos/js-extend#5

**Comment by daleharvey** [comment]
Thats awesome, thanks for the PR against js-extend, it got merged and we have updated the dep in https://github.com/pouchdb/pouchdb/commit/eae7b0320830040543aa54ed2588c93a2e0cbcd2 so should be good to go. Cheers

**Comment by quarterto** [comment]
Thanks for this! Is there any ETA on the next release?

**Comment by nolanlawson** [comment]
Merged in 5.2.0! :)
