### ISSUE TITLE
Upgrading database?

### ISSUE THREAD

**Issue by peteruithoven** [pouchdb/pouchdb#4786]
IndexedDB has support for easy upgrades between database versions: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#Creating_or_updating_the_version_of_the_database
How would this be handled in PouchDB? 

[Dexie.js](http://dexie.org/) for example has a upgrade method: 
https://github.com/dfahlander/Dexie.js/wiki/Version.upgrade%28%29

The same request for localForage: https://github.com/mozilla/localForage/issues/117

**Comment by nickcolley** [comment]
Hey @peteruithoven !

You could try this pouchdb-migrate plugin if you need to update your data structure https://github.com/eHealthAfrica/pouchdb-migrate

Generally PouchDB's core sticks to CouchDB's api with a few exceptions so features like this are best in plugins etc.

**Comment by peteruithoven** [comment]
Awesome! Thanks for the tip.
