### ISSUE TITLE
2 documents are not sync, even tho I'm using sync() function.

### ISSUE THREAD

**Issue by joaku** [pouchdb/pouchdb#4787]
Hello,
I have a document in local database in Couchdb and the same document in a remote database in Couchdb either.

After I sync both databases, without filters, this documents are not syncing.

var couchDB = new PouchDB('http://localhost:5984/localdb');
var devDB = new PouchDB('http://xxx.xx:5984/remotedb');

couchDB.sync(devDB, {live: true,retry: true});

--
In debDB the document is like this:
{
   "_id": "94206b62ba6z",
   "_rev": "2-0ba053ab023230bf2930240c0c6cecb2",
   "event_id": "8d665de3-ae58-4813-817a-898ba69eff34",
   "tipo_entrada": "GENERAL",
   "estado": 1,
   "fecha": "Thu Jan 07 2016 22:15:05 -0300",
   "folio": "TICKET CINE PUERTA",
   "fecha_limite": ""
}

But, in couchDB, I updated my document

{ "_id": "94206b62ba6z", 
"_rev": "1-4294bccabbe9769af1900aa62913dece", 
"event_id": "8d665de3-ae58-4813-817a-898ba69eff34", 
"tipo_entrada": "GENERAL", 
"estado": "0", 
"fecha": "0", 
"folio": "TICKET CINE PUERTA", 
"fecha_limite": "" 
}

I have no idea why they are not sync. This is not the only document. They are dozens like this.

Is important to know that when I'm Sync, the connection is not stable.

**Comment by nickcolley** [comment]
Hey @joaku , if you're syncing two remote databases (both on a server) you could set them up to replicate with each other directly rather than setup a client side script to sync them.

https://wiki.apache.org/couchdb/Replication

**Comment by joaku** [comment]
Hello @nickcolley, one of the database is connecting via mobile bandwidth. Therefore, I don't have a static IP.
Thats why I need to set a client side script to sync them. Any ideas?

**Comment by joaku** [comment]
Is there any method to recompare what is synced and what is not? I don't undersntand why if they have the same id, they are not even comparing for changes.

Maybe I have to call a cancel to the replication, or maybe replicate again? I'm kinda lost, same as my data.

Kind regards!

**Comment by daleharvey** [comment]
@joaku do you see any errors?
```
sync.on('complete', function(result) { console.log('complete', result); });
sync.on('error', function(err) { console.log('error', err); });
sync.on('change', function(change) { console.log('change', change); });
```
What do you see when you add these handlers?

**Comment by nolanlawson** [comment]
@joaku Do you have any conflicts? Try using `db.get('docid', {conflicts: true}`.

**Comment by joaku** [comment]
Honestly, I really don't understand how conflicts work or are solved. I thought it wad random.

var couchDB = new PouchDB('http://localhost:5984/localdb');
var devDB = new PouchDB('http://xxx.xx:5984/remotedb');

devDB.get('docid', {conflicts: true});
returns:
{
_id: "94206b62ba6z"
_rev: "2-0ba053ab023230bf2930240c0c6cecb2"
estado: 1
event_id: "8d665de3-ae58-4813-817a-898ba69eff34"
fecha: "Thu Jan 07 2016 22:15:05 -0300"
fecha_limite: ""
folio: "TICKET CINE PUERTA"
tipo_entrada: "GENERAL"
}

couchDB.get('docid', {conflicts: true});
returns:
{
_id: "94206b62ba6z"
_rev: "1-4294bccabbe9769af1900aa62913dece"
estado: "0"
event_id: "8d665de3-ae58-4813-817a-898ba69eff34"
fecha: "0"
fecha_limite: ""
folio: "TICKET CINE PUERTA"
tipo_entrada: "GENERAL"
}

**Comment by nolanlawson** [comment]
Hm, in this case, it looks like the two database have two different versions of the document (the `_rev` is different). So that tells me that the replication didn't complete or didn't happen.

**Comment by willholley** [comment]
it does suggest that the document in the local CouchDB is not an ancestor of the document in the remote CouchDB. For each document can you show the rev history:

     db.get('docid', {revs:true})

also, it may be obvious but does the client have write permissions on the local CouchDB?

**Comment by joaku** [comment]
Hello,
It is important to say, that if I incresed the options.batch_size to 1000, hundreds of documents got lost. Therefore, thats why it is not syncing correctly. When the batch_size es at 100, most of the time it syncs correctly, but some of the documents don't.
How can I rerun a full sync, so all the documents that get lost, are checked again?

Thanks guys!

**Comment by willholley** [comment]
that smells fishy - the batch size shouldn't affect the correctness of the sync. Are you sure that the client has write permissions on both source and target databases (so that replication checkpointing occurs correctly)?

**Comment by willholley** [comment]
I wonder if this is another symptom of #4963

**Comment by daleharvey** [comment]
There have been a few fixes around this area and since we havent heard back assuming fixed, please reopen if you continue to see problems and if you could include steps to reproduce the issue it would help a huge amount, thanks
