### ISSUE TITLE
Problems Syncing Many Records from CouchDB over Internet Connection

### ISSUE THREAD

**Issue by OthelloVentures** [pouchdb/pouchdb#4790]
Here's the scenario:

I have a CouchDB server in the cloud somewhere. I'm syncing down a large-ish database 1150 records, with the standard batch size of 100. I'm watching the changes feed and the first 5 or 6 go fine, with 100 records being loaded at a time. Then, I start to get "errors": in some batches, I may get the error/warning message "the remote database may not have cors enabled" 20 or 30 times, and those records are missing while the rest of the records from that batch come down correctly. CORS is definitely enabled on the server. For some reason, this does not trigger the error event handler. The PouchDB database then assumes that the sync has completed correctly, and any further attempts to sync do not update records. If I turn the batch size down to 25, things seem to work correctly.

I have been able to trigger this behavior on 5.1.0, which generates the issue and the warning message, and 5.2.0 which generates the issue, but no warning message.

**Comment by willholley** [comment]
dropping _change is worrying. Are you able to share a HAR / network trace of the failing replication? Are there any errors in the remote CouchDB log?

**Comment by aeharding** [comment]
Are your proxying the couch through nginx or something like that?

**Comment by OthelloVentures** [comment]
No, it’s a straight shot.

**Comment by garethbowen** [comment]
This sounds like it might be related to #4963 where individual requests failing doesn't fail the batch.

**Comment by daleharvey** [comment]
https://github.com/pouchdb/pouchdb/commit/5f75054527425fc6cb1db0dbb623943648b3f162 is also a possible suspect, without anymore clarification about reproducing the error we have to assume one of those has / will fix it, if you still see an issue please reopen / file a new bug with more details, thanks :)
