### ISSUE TITLE
Cant sync using filter. Syncs all records any way

### ISSUE THREAD

**Issue by Alekserok** [pouchdb/pouchdb#4791]
var filter =  function (doc) {
                return doc.name === 'name'};
            database.sync(remoteDatabase, {live: true, retry: true, filter:filter});

**Comment by nolanlawson** [comment]
@Alekserok I'm sorry, but I can't reproduce (see tests in #4794). Can you find a test to reproduce, e.g. a sample HTML page that shows the error?

**Comment by nolanlawson** [comment]
confirmed working as intended in https://github.com/pouchdb/pouchdb/pull/4794

**Comment by nolanlawson** [comment]
Please reopen if you can find a reproducible test case! Thanks for reporting.
