### ISSUE TITLE
Add note to db.remove about its implication for filtered replication?

### ISSUE THREAD

**Issue by anaran** [pouchdb/pouchdb#4796]
http://pouchdb.com/api.html#delete_document
features db.remove first, but that is not advisible when using
http://pouchdb.com/api.html#filtered-replication

Should db.remove be recommended over db.put with _deleted: true?

If so, perhaps provide a link under db.remove to
http://pouchdb.com/api.html#filtered-replication
?

**Comment by nolanlawson** [comment]
Yep! It probably is a good idea to add a warning in there. Many people have run into this.

**Comment by anaran** [comment]
Are there scenarios where db.remove would be preferable to db.put with _deleted = true ?

**Comment by nolanlawson** [comment]
fixed by ec2d06a7da1d63b159cfcca72ca0b76897f9a7a8

**Comment by nolanlawson** [comment]
And to answer your question: yes, sometimes it's just simpler to `remove()`, and maybe you do want it to be ignored by filtered replication for some reason, or maybe you want to be sure that you're not unnecessarily storing extra fields (which can happen with `put()`)... but in your case, you're fine without `remove()`.
