### ISSUE TITLE
PouchDB objected exported as "PouchDB$1"

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4801]
Aesthetically this just bugs me. It also is Rollup's way of telling us that we are implicitly using a global `PouchDB` reference somewhere. So it's something we ought to fix.

![screenshot 2016-01-17 23 29 52](https://cloud.githubusercontent.com/assets/283842/12383297/55e4a1ee-bd72-11e5-87fd-5adf2714ef14.png)

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/9465e43c479d7976474e6bfa476e6f96d21e101e
