### ISSUE TITLE
slow query times using persistent views

### ISSUE THREAD

**Issue by dryajov** [pouchdb/pouchdb#4817]
I'm writing a browser based music player app, and running into issues with initial query times. Currently, it seems like views are rebuild every time the page loads (is that intended?), which makes loading some 350+ songs plus 2 playlists pretty slow. Here is the timing of the queries:

Timing gettracksbyplaylist Random: 3002.020ms - (15 tracks)
Timing gettracksbyplaylist ltj bukem: 5942.710ms - (6 tracks)
Timing gettracksbyplaylist default: 10631.650ms - (358 tracks)

Here is the code that loads the tracks by playlist:

```            
return this.db.query(this.views.views[names.GET_PLAYLISTS_BY_NAME],
                {
                    startkey: name,
                    endkey: name,
                    include_docs: true,
                    stale: 'update_after'
                }).then(function (res) {
                    console.timeEnd('Timing ' + names.GET_TRACKS_BY_PLAYLIST + ' ' + name);
                    return res.rows.map(function (document) {
                        return document.doc;
                    });
                }).catch(function (error) {
                    console.error(error);
                });
```

As I understand it, I am using a persistent view, which should make things faster. 

Also, I understand that a possible improvement would be to use pagination (which I intend on doing anyways), however, limiting the query results to 50 records, doesn't feel like it is improving performance in any perceivable way (tho, I havent measured it), also, the fact that it takes 5 secs to retrieve 6 records is... troubling.

Here is the debug output from the initial load:
[pouch_view_first_load.txt](https://github.com/pouchdb/pouchdb/files/102645/pouch_view_first_load.txt)

I'm pretty new to pouch, so I wouldn't be surprised if I was doing something stupid, however, if the performance issues lie within pouchdb itself, I wonder what is the best way to solve this, I can probably use `allDocs()` and the filter the result manually, however, it would be nice not having to do that.

I'm using chrome 48.0.2564.82 (64-bit) and pouchdb v5.1.0
Thanks in advance.

**Comment by nolanlawson** [comment]
Sadly slow secondary indexes are a known issue (I know they're slow; I wrote them :smiley:), and the current proposed fix is native secondary indexes, which will probably arrive when we rewrite the IndexedDB adapter. Been tracked a few different places, including here: https://github.com/pouchdb/pouchdb/issues/3775

For now, I would advise using Dexie or YDN-DB if you need very flexible query capabilities. They are "closer to the metal" and capable of faster queries.
