### ISSUE TITLE
Windows 10 apps cache GET requests

### ISSUE THREAD

**Issue by byudaniel** [pouchdb/pouchdb#4827]
Edge within a Windows 10 app is caching AJAX GET requests. Strangely, Edge on its own is not having this issue. As a result of this issue, it endlessly POSTs to the _bulk_docs endpoint with an old revision number for the checkpoint document.

The fix is to add the Edge within an app useragent to the shouldCacheBust logic. I'll post a pull request later tonight.

For reference, here is the useragent I have within a Windows 10 app: `"Mozilla/5.0 (Windows NT 10.0; Win64; x64; MSAppHost/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586"`.

**Comment by nickcolley** [comment]
Hey @byudaniel,

How are you getting on with this, let us know if you need any help.

We already sniff Edge in this instance: https://github.com/pouchdb/pouchdb/commit/a1dcfcb73dad6350e64999e41e6fb9cb3e3777a0#diff-3bf8492dbd9abe8bc2d9bf8f19b13a18R35

This makes me think we should also work on getting Edge tested in CI.

Since Edge is being actively developed, we should also post a bug to Microsoft.

**Comment by nolanlawson** [comment]
Sounds like [our cache-busting user agent sniffer](https://github.com/pouchdb/pouchdb/blob/f80a9586555cf2a008f2c08f9382c436b78bcd7e/src/deps/ajax/prequest-browser.js#L11-L14) does not properly detect Edge. Want to submit a PR? :D

And yes, we should absolutely test Edge in CI.

**Comment by nolanlawson** [comment]
(@nickcolley the URL you pasted is for detecting IDB Blob support, not GET caching of ajax requests)

**Comment by nickcolley** [comment]
@nolanlawson yeah just saying we already sniff Edge so you can see how we've done it.

Might be worth making a util or something so it's shared.

**Comment by Yougz** [comment]
I'm experiencing some issues with a Win10 app too. I guess it's related, but I'm not sure: the updateCheckPoint function triggers an infinite loop. ( 409->try again->409->try again->etc... ) I think the get() is cached and always return an old revision number of the checkpoint.

The app works great on other platforms.

**Comment by nickcolley** [comment]
@Yougz good to know, should get a fix in for this soon sorry for the delay ;)

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/94d1fe0583ba3f7a2929067849c33387c5b6d654
