### ISSUE TITLE
Slow behavior on a Cordova App during View building.

### ISSUE THREAD

**Issue by ronyrun** [pouchdb/pouchdb#4851]
Hello,

I'm having a slow behavior with the "view building"  on PouchDB. 

With my ionic app, when the view is built (after insertion of ~1500 docs)
 It takes 40 seconds to build the view.
During the view build, the ionic/cordova App is freezed and unusable

Is there a way to improve the view creation (with bulks I don't know) ? 

When looking at the debug console, I can see that view docs are created one by one.
the begining : 

![image](https://cloud.githubusercontent.com/assets/7273443/12647889/b9c38aaa-c5d7-11e5-9a08-fbcc47a54444.png)

the end : (40 s later) 

![image](https://cloud.githubusercontent.com/assets/7273443/12647907/d51a7192-c5d7-11e5-9c15-3abd32a6a67b.png)

**Comment by nolanlawson** [comment]
Slow view building is a known issue. It'll hopefully be solved in the future by #3775.

For the time being, I do not advise using PouchDB for large secondary indexes. I advise using Dexie or YDN-DB instead.

**Comment by ronyrun** [comment]
Thank you.
