### ISSUE TITLE
extras/checkpointer and extras/generateReplicationId also need browser switches

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4858]
This is a quite annoying problem that I just realized still exists for plugins like `pouchdb-load`.

**Comment by nolanlawson** [comment]
The fact that nobody has noticed this until now (and the release has been out for a month) tells me that I may be the only person on the planet actually using the `extras` API.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/b14ac3b491a728488d88788ca54cf6f597a15531
