### ISSUE TITLE
Code style guide is not enforced by jshint anymore

### ISSUE THREAD

**Issue by sgenoud** [pouchdb/pouchdb#4871]
The maintainer of JShint has decided to take it in a direction where it focuses on and do not implement coding style, see this [SO answer](http://stackoverflow.com/questions/23097316/how-can-i-make-jshint-indent-options-work)  (and the post it links to)

Why does that matter? Because pouchdb relies on jshint to enforce its coding style. Typically with the current version used the indent of 2 spaces does not show up in the posttest phase.

jshint proposes to use jscs for the task: http://jscs.info/overview, seems good enough to me (I spent a bit of time running it on the project: https://github.com/pouchdb/pouchdb/compare/master...sgenoud:adding-jscs I guess we should probably ignore the style for the comments (that adds lots of not that necessary changes).

**Comment by nickcolley** [comment]
This sounds good to me, wonder if this'd be a decent time to explore the option of using 'standard' etc?

**Comment by sgenoud** [comment]
> wonder if this'd be a decent time to explore the option of using 'standard' etc

I am not sure I understand want you mean, can you explain me?

**Comment by nickcolley** [comment]
We've changed our linting and code style a few times, if we used something like https://www.npmjs.com/package/standard we wouldn't have to maintain this side of the project.

**Comment by daleharvey** [comment]
I do think it would be preferable to have a single tool to handle this, `semistandard` may be ok although we could never use `standard` and worried about `semistandard` being similiarly obnoxious. Using `eslint` directly also seems like a possibility.

**Comment by marten-de-vries** [comment]
eslint config file I use for pouchdb plugins, of which the code style is relatively similar I think: https://github.com/pouchdb/pouchdb-plugin-helper/blob/master/eslint (no support for ES6 import/export, see https://github.com/pouchdb/pouchdb-plugin-helper/blob/master/eslint-test for an example of that, but that one's too broad, because also other ES6 features are supported.)

**Comment by nolanlawson** [comment]
What's wrong with just pinning our JSHint version where it is? Not sure there's always a burning need to "upgrade" every dependency, especially if they start going in a wildly different direction.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/d2d339f722e365cb797dcd6d25f355db0e8f911b

**Comment by sgenoud** [comment]
Nice!

**Comment by nickcolley** [comment]
Thanks @sgenoud for getting this going :+1:
