### ISSUE TITLE
PouchDB with facebook in-app browser

### ISSUE THREAD

**Issue by standup75** [pouchdb/pouchdb#4881]
The new facebook in-app browser seems to not work well with pouchDB. To work around this issue, I sniffed the UA-String and reverted to localstorage is I am in the facebook in-app browser:

    if (/FBIOS/.test(navigator.userAgent)) {
      useLocalStorage()
    } else {
      usePouchDBStorage()
    }

Is this a known issue?

**Comment by nolanlawson** [comment]
Most likely Facebook's in-app browser on iOS is using WKWebView, which yes, is a known issue. The only current known workaround is to use the FruitDOWN adapter or the localstorage-down adapter.

Bug on WebKit: https://bugs.webkit.org/show_bug.cgi?id=137760
