### ISSUE TITLE
Unable to use "/" in db name when replicating using node/leveldown

### ISSUE THREAD

**Issue by cdaringe** [pouchdb/pouchdb#4885]
leveldown tries to find `/dbroot/dbnameLeftOfSlash/dbnameRightofSlash`.  well the name of the db is `dbnameLeftOfSlash/dbnameRightOfSlash`, and is a valid CouchDB name.  Oh no!

:/

**Comment by cdaringe** [comment]
ideally, i want to be able to provide a db name and a path for the leveldb store.  my db name is in all actuality `xyz`, but I have to send it through a proxy `someroute/xy` to get to my couch instance.

**Comment by nolanlawson** [comment]
Can you encode the `/` character? Otherwise, yeah, it sounds like you need to have a proxy to fix this issue. AFAIK CouchDB doesn't even allow slashes in DB names, and for LevelDOWN it's a big security issue as well, since it allows you do stuff like `foo/../../etc/password`, so I'd recommend just stripping it or encoding it if you can.

Please reopen if I misunderstood your issue.

**Comment by cdaringe** [comment]
hey @nolanlawson

> Can you encode the / character? 

we did find a way around the problem, but encoding the character wouldn't really address the root of the problem.  the root of the problem that i was trying to convey was that CouchDB permits the `/`, and PouchDB does not.  i was thinking that LevelPouch could possibly  provide a means to handle the case.  i.e. suppose the constructor call was `new Pouchdb(url, opts)`.  if opts.name` was `my/store` and `name = 'http://url.com/couchroot/my/store'`, LevelPouch could encode the file system cached store as `'my%2Fstore'`, and `/`'s would still effectively be supported.

may not be worth the effort.

anyway, my solution was to not construct with a `url` at all as I had been previously. instead, i just construct with a db name, then use the `.replicate(...)` API, which offers the same effect.

something to consider, but definitely an edge case!

thanks!

**Comment by nolanlawson** [comment]
Yeah, I think the "LevelDB database name is a file path" pattern is too deeply ingrained to remove now. Hopefully the edge case wasn't such a pain to work around. :)
