### ISSUE TITLE
use PouchDB.utils.uuid() in Getting Started Guide

### ISSUE THREAD

**Issue by kidwm** [pouchdb/pouchdb#4887]
To replace `new Date().toISOString`.

**Comment by daleharvey** [comment]
Sorry, `PouchDB.utils` is a private and unsupported api, we are looking to remove its usage and get rid of it in future versions its mostly just around for historical reasons but we definitely dont want to promote its usage.

**Comment by kidwm** [comment]
Thanks for explanation.
How about opening an issue to track the progress of the deprecating of `PouchDB.utils`?

**Comment by daleharvey** [comment]
I for some reason thought there already was one, but I cant find it so yes that would be great, thanks :)
