### ISSUE TITLE
Get the status of the synchronization

### ISSUE THREAD

**Issue by natcohen** [pouchdb/pouchdb#4889]
Not a bug but a feature...

My couchdb is 100MB and the first time my app starts, it has to download the whole content. The problem is that the user has no clue whether the app is stuck or not. Is it possible to get the amount downloaded and the amount left when synching?

**Comment by nolanlawson** [comment]
There are two good solutions:

1. Use the `.on('change')` event, compare the `seq` against the value from `remoteDB.info()` to see the progress of replication, or
2. Use [pouchdb-load](https://github.com/nolanlawson/pouchdb-load) to split up your database into static files, then as you download you can manage yourself the replication progress.

I agree this is a problem, and I eagerly await someone writing a simple plugin to show replication progress, but I haven't seen anyone do that yet. :/

**Comment by natcohen** [comment]
@nolanlawson before this feature gets lost, is there any list of 'good to have' plugins we could add it to?

**Comment by nolanlawson** [comment]
Not that I know of. I keep trying to remind myself to work on it, but then I end up with 50 other things to do. :P

**Comment by nickcolley** [comment]
@natcohen I'll put this on my todo list.

**Comment by natcohen** [comment]
@nickcolley Awsome, thanks!
