### ISSUE TITLE
Add async/await examples to the docs

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4891]
In addition to promise/callback examples, add async/await examples. Make promises the default, but give people the option if they're interested in async/await.

I'm currently working on this. About half done so far.

**Comment by marten-de-vries** [comment]
Nice idea. Might be handy to include a node about not forgetting to mark the containing function with ``async`` somewhere. This'll probably be the introduction to the syntax for quite a few readers.

**Comment by nickcolley** [comment]
are async/await definitely going to ship in browsers? I'm wary of promoting overuse of language features that might not even ship.

**Comment by nolanlawson** [comment]
async/await is already shipping in Edge: https://blogs.windows.com/msedgedev/2015/09/30/asynchronous-code-gets-easier-with-es2016-async-function-support-in-chakra-and-microsoft-edge/

**Comment by daleharvey** [comment]
They have been in Firefox for a while now I think

**Comment by nolanlawson** [comment]
According to [the esnext compat table](http://kangax.github.io/compat-table/esnext/), they are only in Edge currently. Just tested FirefoxDevEdition and confirmed.

**Comment by nolanlawson** [comment]
3acb34dad1fd24206a6e3dbe318ff355f91e6e8f
