### ISSUE TITLE
fix btoa$1 error for non-ascii characters (such as Cyrillic)

### ISSUE THREAD

**Issue by unpete** [pouchdb/pouchdb#4903]
function `btoa$1(str)`  rise DOMException "The string to be encoded contains characters outside of the Latin1 range" if str contains non-ascii characters.
Replace `btoa(str)` to `btoa(unescape(encodeURIComponent(str)))` fixes this error

**Comment by daleharvey** [comment]
Great catch, could you post any example code which highlights the issue?

**Comment by unpete** [comment]
https://jsfiddle.net/oknosoft/dvjfzjev/

```javascript
var db = new PouchDB("https://fakepath.net/", {
	auth: {
  	username: "guest",
    password: "password"
    }						
});
```
all ok, but:

```javascript
var db = new PouchDB("https://fakepath.net/", {
	auth: {
  	username: "Иванов И.И.",
    password: "Секрет"
    }						
});
```
rises error

**Comment by nolanlawson** [comment]
Could you open a PR with this change? Looks like the place to put the change would be [this line of code](https://github.com/pouchdb/pouchdb/blob/21e1346e11e611f1d312f468a711389038b04287/src/adapters/http/index.js#L150).

**Comment by unpete** [comment]
Probably, the change in [that line of code](//github.com/unpete/pouchdb/blob/4903-btoa-outside-latin1/src/deps/binary/base64-browser.js#L6). PR will be added after the testing.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/e45e7a04567025085a92a6ad0d95d59d68b84321
