### ISSUE TITLE
batch_size and live problem

### ISSUE THREAD

**Issue by raminbp** [pouchdb/pouchdb#4906]
Hi
I'm new to pouchdb and i tried to write a small piece but i couldn't find out what's the relationship between batch_size and live options.

i have : 

```
db.replicate.to('http://127.0.0.1:5984/glogger', {
      // live: true,
      since: 'now',
      retry: true,
      batch_size: 3,
    });

for (var i = 0, i < 90; i++) {
    db.post({
      msg: Math.random(),
      timestamp: new Date().getTime(),
      type: 'someType'
    });
}
```
I expected that after each 3 post replication would happen but i was wrong. i tried {live: true} and it replicates on each change. i'm sure i missed a concept here. what should i do if i need that db replicate to a remote after every x number of changes?

**Comment by daleharvey** [comment]
`batch_size` is a configuration for an internal details of the replication, it changes the size of the batches that are used dusing replication. If you use live replication then the replication will happen immediately as the changes are made, if you want to delay them then you have to not use live replication and trigger replication when you want it to happen.

Cheers

**Comment by raminbp** [comment]
Ok , but i don't understand the usage of batch_size, correct me if i'm wrong: 
if i set "live" to false and  for e.g i have 30 changed records, assuming that batch_size is 3, pouchdb replication requests 10 times (each with 3 records)?

**Comment by daleharvey** [comment]
Not exactly but its quite confusing, the changes will be read continuously with an undefined number of requests, once we have received > `batch_size` records then we will process them in one batch, this means with a batch_size of 3 we `should` be sending 10 `bulkDocs` writes with 3 records each.

**Comment by raminbp** [comment]
ok , thank you
