### ISSUE TITLE
PouchDB all of the sudden "missing_id" when using put

### ISSUE THREAD

**Issue by lordgreg** [pouchdb/pouchdb#4913]
Hi.

I'm currently creating a new Ionic2 project in which, I've successfully implemented PouchDB. Everything was working until I haven't called `destroy`. Afterwards, I've ran `this.db = new PouchDB(DB_NAME);` and everything was working as it should.

But now, all of the sudden, I can't save document in my DB at all.

Here's my code (please keep in mind this is ng2/typescript project, meaning the code is... typescript :)):

1. I call the function `this.storage.saveSingle({ _id: 'user', username: 'test', created: Date.now() });`
2. Within the function, I check if my item is there with `console.info('creating new doc', item);` where `item` is our param. 
3. console shows it properly:
![image](https://cloud.githubusercontent.com/assets/480546/13200147/53be86ca-d83c-11e5-9d98-b2012646fede.png)
4. calling `put`:
```
          this.db.put(
            { item },
            (err, res) => {
              if (err) {
                console.info('error creating new doc', err);
                reject(err);
              }
              if (res) {
                console.info('new doc created', res);
                resolve(res);
              }
            }
          );
```
5. always getting missing_id error:
`CustomPouchError {status: 412, name: "missing_id", message: "_id is required for puts", error: true}`
6. clearing browser cache or closing it didn't help.
7. testing it in other browsers brought the same `missing_id` result

To tell you the truth... I'm clueless at the moment. What did I wrong?

**Comment by lordgreg** [comment]
Please, don't mind this ticket. 

I was passing object within object for db.put parameter. -.- 

```
this.db.put(
            { item },
```

should be

```
this.db.put(item,
```

**Comment by brettins** [comment]
I actually had the same typo, so thanks :+1:  :)

**Comment by mieszko4** [comment]
I was getting the same error when passing `_idx: 0`
