### ISSUE TITLE
Support the WebSQL adapter in Node

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4915]
Lots of folks have trouble building LevelDB for various environments (Windows, IoT, etc.). Occasionally this had led them to the extreme measure of using something like [SQLdown](https://github.com/calvinmetcalf/SQLdown), which is unfortunate because it tends to be pretty inefficient due to using LevelDB-esque queries over SQLite.

To solve this problem, I recently reimplemented WebSQL in Node.js over [sqlite3](https://github.com/mapbox/node-sqlite3), and called it [node-websql](https://github.com/nolanlawson/node-websql). Using this, we can now offer our users an easier way to install PouchDB in Node, in case LevelDB is giving them troubles.

I anticipate this opens up PouchDB to more usage on resource-constrained devices, especially since SQLite is a well-established standard there, and typically easier to install than LevelDOWN (efforts like [leveldown-mobile](https://github.com/Level/leveldown-mobile) notwithstanding).

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/edcfd13bec4539fdf2f3d34f2fcc6b97499422d0
