### ISSUE TITLE
Remove deprecated PouchDB.destroy() from the guide

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4917]
Just realized that `PouchDB.destroy()` is still hanging out in the guide: http://pouchdb.com/guides/compact-and-destroy.html. it's been removed since v5.

**Comment by AntonioVdlC** [comment]
Hi @nolanlawson 
I can give it a try tomorrow! I went over the contribution guidelines but, as this is my first contribution ever, I will probably need some guidance along the way. I'll let you know if I have issues resolving this issue!

**Comment by daleharvey** [comment]
Yup looking at grep it looks like that is the only instance so it just needs removed, thanks and if you have any problems feel free to ask

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/194ea5dd52d4e46aa1068a13f1b6a7c5a05b82a2
