### ISSUE TITLE
Documentation: note that startkey/endkey reverse when desending=true

### ISSUE THREAD

**Issue by lordgreg** [pouchdb/pouchdb#4920]
Hi.

I've just realized, after few days, that... 

1. when using id prefix search
```
      opts.startkey = 'test';
      opts.endkey = 'test\\uffff';
```

2. and trying to use 
```
opts.descending = true;
```

You will get empty array. I just found an [SO](http://stackoverflow.com/questions/30952341/pouchdb-startkey-endkey-not-returning-docs) question with answer, if using startkey & endkey with combination of descending parameter, you should switch startkey and endkey, so that startkey becomes endkey and vice versa.

Please add this info into documentation for future reference or users, who'd like documents returned  or add automatically startkey and endkey reversing mehanism inside PouchDB.

:+1:

**Comment by nolanlawson** [comment]
This information is already at http://pouchdb.com/2014/04/14/pagination-strategies-with-pouchdb.html

Maybe we could provide a link to that? Or add a note at http://pouchdb.com/api.html#batch_create saying that `descending` reverses the order of start/end?

**Comment by nolanlawson** [comment]
BTW the reason we can't change this behavior is that it would be a breaking change, and this is how CouchDB does it, and our goal is to implement CouchDB as-written. :)

**Comment by jkt001** [comment]
Hi, is it ok if I work on this issue? Should be a quick one to add the note. Thanks!

**Comment by nickcolley** [comment]
@jkt001 go for it! Let us know if you need any help :+1:
