### ISSUE TITLE
Remove old revision after sync()

### ISSUE THREAD

**Issue by Grafikart** [pouchdb/pouchdb#4931]
PouchDB store an history of every action (deletion, addition..). This is nice for syncing data with a remote database but a problem would appear over time if pouchdb is used on mobile for instance. 

Is there a way to clean pouchdb after a syn() ? Something like "don't keep old revisions".

Couldn't find this feature in the documentation and I think it would be nice to lighten the local database when using only one remote.

**Comment by jpetaux** [comment]
Have you try the function db.compact() ?

**Comment by Grafikart** [comment]
Oh didn't knew compact was doing this my bad.

**Comment by daleharvey** [comment]
You can also create a database with `new PouchDB('name', {auto_compaction: true})` in which the old revisions will automatically be deleted (its mentioned briefly in http://pouchdb.com/api.html#create_database)

**Comment by Grafikart** [comment]
Yeah it's a bit too brutal since it will break the sync ability. I'll compact after every successfull sync it seems safer

**Comment by daleharvey** [comment]
auto compaction wont kill sync ability, we run our full test suite with auto_compaction turned on
