### ISSUE TITLE
no conflict on updating a deleted document

### ISSUE THREAD

**Issue by henksmeba** [pouchdb/pouchdb#4932]
Hi, first of all I would like to thank you for this great piece of software.

I would like to know if the following situation is a bug or if I don't understand something. When I have a remote and local db that are in sync and both go offline. If the remote deletes a document (through put > _delete: true) and the local updates a document shouldn't there be a conflict when going back online?

```javascript
var PouchDB = require('pouchdb');

var local = new PouchDB('local');
var remote = new PouchDB('remote');

remote
  .put({_id: 'test', name: 'test'})
  .then(function(response){
    return remote.sync(local);
  })
  .then(function(){
    return local.get('test').then(function(doc){
      doc.name = 'test update local';
      return local.put(doc);
    })
  })
  .then(function(){
    return remote.get('test').then(function(doc){
      doc._deleted = true;
      return remote.put(doc);
    })
  })
  .then(function(response){
    return remote.sync(local);
  })
  .then(function(){
    return remote.get('test', {conflicts: true}).then(function(doc){
      console.log('remote doc', doc);
    })
  })
  .then(function(){
    return local.get('test', {conflicts: true}).then(function(doc){
      console.log('local doc', doc);
    })
  })
  .catch(function(err){
    console.log(err);
  })
```

**Comment by daleharvey** [comment]
So a conflict is a leaf revision that is not deleted, you have created a leaf but because it is deleted couchdb and pouchdb treats the conflict as being resolved. Flagging items as deleted with your own flag may work for your case if that behaviour doesnt work for you

**Comment by daleharvey** [comment]
Feel free to ask any more questions here or in new issues, closing this out though, cheers
