### ISSUE TITLE
TypeError: changes.results is undefined

### ISSUE THREAD

**Issue by 2i** [pouchdb/pouchdb#4949]
Hi, sometimes I get the mentioned error at 
https://github.com/pouchdb/pouchdb/blob/f3a72ea84c951a815f8dd7a002fb11aa17b82543/src/replicate/replicate.js#L290 in Firefox 44. 
I only recognized this when enabling the option “break on exceptions” in the developer tools.  When I let the debugger continue with the execution the exception is not logged in the console. Maybe this has something to do with the „unkown_error“ which rarely appears, but this is purely speculative.

**Comment by nolanlawson** [comment]
Sorry, what's the exception you get? Providing some code or a screenshot would be very helpful here.

**Comment by nolanlawson** [comment]
Are you talking about https://github.com/pouchdb/pouchdb/issues/4967 ?

**Comment by daleharvey** [comment]
We havent seen this reoccur and havent heard back about how to reproduce, if you are still seeing this and can provide more steps to reproduce if you could reopen with more information that would be great, thanks
