### ISSUE TITLE
Resource interpreted as Script but transferred with MIME type text/plain

### ISSUE THREAD

**Issue by do7a15** [pouchdb/pouchdb#4958]
i get this error when sync data : 
"Resource interpreted as Script but transferred with MIME type text/plain"

i am using phonegap and angularjs

**Comment by nolanlawson** [comment]
This is just a warning and doesn't impact your app (typically). But the way this is happening is probably because you have a script with a `.txt` extension or something. I'm also not sure what platform you're using (iOS/Android), but that would influence it as well.
