### ISSUE TITLE
removeDocs feature exist?

### ISSUE THREAD

**Issue by katopz** [pouchdb/pouchdb#4959]
From my understand `bulkDocs` is `update`, `allDocs` is `read` and `removeDocs` should be `delete`.

So is that `removeDocs` exist somewhere?

Thanks

**Comment by nickcolley** [comment]
Hey @katopz,

For bulk deletions you would add the property _deleted: true to your documents.

See http://pouchdb.com/api.html#batch_create (search for 'Bulk update/delete')
