### ISSUE TITLE
Map/reduce calls map() function twice for every document

### ISSUE THREAD

**Issue by ssured** [pouchdb/pouchdb#4967]
Hello,

For debugging purposes I put a console.log inside a map function. To my surprise the function was called double the number of records in my database, so I made https://jsbin.com/totemituja/2/edit?html,js,console to test what happens.

It seems that if you query an unindexed view, then the view is triggered to build. If you query again while building the index, the index is built again. In the fiddle you can observe this behaviour as the DB contains 10 records, it's queried twice and runs the map function 20 times.

Kind regards

**Comment by nolanlawson** [comment]
That's definitely a bug. Thanks for reporting!

**Comment by colinskow** [comment]
By the way in Safari I'm getting `"WebSQL threw an error"` when loading the JSBin, so that is something else to look into.

**Comment by ssured** [comment]
Pretty weird, I could not quickly find the cause of that error, but I'm having it too in Safari

**Comment by nolanlawson** [comment]
^ This is undoubtedly a JSBin issue since they use iframes.

**Comment by nolanlawson** [comment]
^ Issue fixed, thanks for the test case!

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/45156c5bcf5c6ebbfb049c4234611636bb8220d8
