### ISSUE TITLE
Filtered replication using a view is not working in PouchDB 5.3.0

### ISSUE THREAD

**Issue by burggraf** [pouchdb/pouchdb#4970]
No matter what I try, I cannot get replication to work using a view.  Using a filter works, but it's super slow, so I'd like to use a view, which should be fast.

Here's some sample code:

`var PouchDB = require('PouchDB');

PouchDB.replicate('https://myuser:mypass@mydomain.cloudant.com', 'localdb', {
  'filter': '_view',
  'view': 'mydesign/myview'
}).on('change', function (info) {
  console.log('change...' + JSON.stringify(info));
}).on('paused', function () {
  console.log('paused');
}).on('active', function () {
  console.log('active');
}).on('denied', function (err) {
  console.log('denied: ' + JSON.stringify(err));
}).on('complete', function (info) {
  console.log('complete: ' + JSON.stringify(info));
}).on('error', function (err) {
  console.log('error: ' + JSON.stringify(err));
});
`

**Comment by burggraf** [comment]
Note:  this works against an instance of pouchdb-server, but not against Cloudant.

**Comment by burggraf** [comment]
According to this:  https://docs.cloudant.com/database.html#get-changes, Cloudant doesn't have a "view" parameter when calling their _changes feed.  Does this mean that views are not supported with Cloudant replication?

**Comment by daleharvey** [comment]
It doesnt look like it, @garrensmith any ideas?

**Comment by garrensmith** [comment]
@willholley will know more about this than me. 

All misspelling thanks to my iPhone

**Comment by willholley** [comment]
Cloudant doesn't support the _view option for replication / _changes yet (though it's coming very soon). However, using a view filter in this way is no faster than a standard filter function - CouchDB just uses the `map` function of the view as the filter so it's really just a way of reducing code duplication.

It sounds like what you're really after is [COUCHDB-2824](https://issues.apache.org/jira/browse/COUCHDB-2804) which would enable a materialised view to be used to accelerate _changes filtering. I don't know that anybody is actively working on it so you might try prodding the CouchDB community to pick it up.

**Comment by daleharvey** [comment]
Thanks for the clarification Will + Garren

Closing out

**Comment by jareware** [comment]
Just hit this as well... should the docs be updated to note that this won't work against Cloudant, or just wait till it's supported?

In the meantime, will user filters instead. :+1:
