### ISSUE TITLE
replicate from remote database not completed

### ISSUE THREAD

**Issue by do7a15** [pouchdb/pouchdb#4974]
replicate from remote database not completed
var opts = { live: true, retry: true };
var getall = db.replicate.from(remotedb, opts);

getall.on('change', function (info) {
								  console.log("change : "+ info);
								}).on('paused', function (err) {
									console.log("paused : "+err);
								}).on('active', function (err) {
									console.log("active : "+err);
								}).on('denied', function (info) {
								  console.log("denied : "+ info);
								}).on('complete', function (info) {
								  console.log("complete : "+ info);
								}).on('error', function (err) {
								  console.log("error : "+ err);
								});

**Comment by daleharvey** [comment]
Does the complete event not fire? when using `live: true` in your replication it is expected that `complete` should never fire as it never finished, it waits for new changes, if you want to be notified when the replication starts waiting for new changes you can use `.on("paused", ...`

**Comment by do7a15** [comment]
i will remove : opts = { live: true, retry: true };
because i want to get data only and i will use : on complete
you explained me this point
Thanks

**Comment by daleharvey** [comment]
Awesome, closing out then, thanks :)
