### ISSUE TITLE
PouchDB doesn´t recognize a different user

### ISSUE THREAD

**Issue by todotresde** [pouchdb/pouchdb#4976]
I am using PouchDB 5.3 with Couchbase Sync Gateway 1.2, with the sync function. If I login using a user that has access to 2500 documents, it sync them to my device, but, if I logout and login with the other user, that has access to only 1 document, PouchDB doesn´t recognize this change, and keep data on my device.

If PouchDB is able to sync changes on both sides, should be able to recognize when the user change?

**Comment by daleharvey** [comment]
Nope, PouchDB has no concept of users whether from couchdb / couchbase etc.
In this case you will have to delete the database when the user logs out to
prevent access, or implement per user encryption

Cheers
Dale

**Comment by todotresde** [comment]
Thanks Dale!
