### ISSUE TITLE
The mandatory websql dependency causes issues in some environments

### ISSUE THREAD

**Issue by vjrantal** [pouchdb/pouchdb#4991]
Currently, the websql package is listed as a dependency and means that if that package (and all the packages it depends on) doesn't build, the installation of pouchdb package fails.

We are using pouchdb together with https://github.com/jxcore/jxcore and when using the SpiderMonkey version, the websql package doesn't install (because sqlite3 doesn't build against the SpiderMonkey engine).

A proposal would be to make websql an optional dependency similar to leveldown so that this issue could be avoided.

**Comment by nolanlawson** [comment]
bf9acf51353be93fcf0bd0d7205b8ef134480176
