### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by Vishwas87** [pouchdb/pouchdb#4993]
Good morning,
Could you help me with this scenario ? 

_------ Database Info ------_
1) **Total Docs**: 59893
2) **Fetch Docs (query)**: 2119

_------ Query -----_
```
console.time("Query");
db.allDocs({
        startkey:"1000000008074",
        endkey: "1000000518074\uffff",
        include_docs: false    
}).
then(function(res){
    console.timeEnd("Query");
    console.log(res);
});
```
_----- PouchDB Version 3.6.0 ------_
**Query: 6583.429ms**
_----- PouchDB Version 5.3.1 ------_
**Query: 33626.537ms**

Am I doing something wrong?
Thank you for your help and for your masterpiece

**Comment by Vishwas87** [comment]
Sorry I solved by my self.
It seems version 5.3.1 is slower with the web-developer console opened. 
Thank you for your time.

**Comment by nickcolley** [comment]
@Vishwas87 thanks for sharing :+1:
