### ISSUE TITLE
'One to many' live replication is not working

### ISSUE THREAD

**Issue by abellion** [pouchdb/pouchdb#5007]
Hello,

I'm trying to implement a one to many sync. One locale database synced with one or more remote database. All work well with one remote but from two remotes the live replication is not working. No error message appear, just the _active_ and then the _paused_ events fires.

My databases are synced only if I refresh my app, so when the sync() function is called.

My code is very simple and minimalist : 
```javascript
var a = new PouchDB(dbs['client']);
var b = new PouchDB(dbs['server'], {ajax: {cache: false}});

var handler = PouchDB.sync(a, b, {'live': true, 'retry': true})
.on('error', function(e) {
	console.log("ERROR FOR " +dbs['server']+ " : ", e);
}).on('denied', function(e) {
	console.log("DENIED FOR " +dbs['server']+ " : ", e);
}).on('change', function(r) {
	console.log("CHANGE FOR " +dbs['server']+ " : ", e);
}).on('paused', function(e) {
	console.log("PAUSED FOR " +dbs['server']+ " : ", e);
}).on('active', function(e) {
	console.log("ACTIVE FOR " +dbs['server']+ " : ", e);
}).on('complete', function(e) {
	console.log("COMPLETE FOR " +dbs['server']+ " : ", e);
});
```

On Chrome Version 49.0.2623.110 (64-bit), Mac OSX El Capitan
Working on Ionic app served with the builtin `ionic serve` command.

TY.

**Comment by nolanlawson** [comment]
Did you enable CORS on your CouchDB application? Do you see any CORS errors in the console? Also in your code I only see one remote...

**Comment by abellion** [comment]
Yes CORS is enabled, no errors in the console. 
This code is inside a loop ;)

**Comment by abellion** [comment]
Note that with a one to one sync (which work well), when I change something from the local, i've got successively the following events : 
 
- _active_ with a push direction
- _paused_
- _active_ with a pull direction
- _paused_
- _active_ with a push direction
- _paused_

With a one to many sync only the two first events fires for each remote.

**Comment by nolanlawson** [comment]
Is it possible you're running into the 6-8 network request limit that most browsers have? If you see many hanging requests in the Dev Tools Network tab, then that could be the issue.

**Comment by daleharvey** [comment]
So there isnt enough information to diagnose this, I took a look around and created a test based off your description which is passing. Closing this out, if you continue to see issues please reopen or file a new bug. Thanks
