### ISSUE TITLE
WebKit Nightly broken due to CouchDB-related ETag bug

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5010]
...but not broken in Safari latest. So we have a chance to catch this bug before it goes live.

~~I haven't been able to write a small reproducible test case yet. It's very tricky to nail down.~~ _see test in WebKit bug below_

To reproduce, run the tests with `http://127.0.0.1:8000/tests/integration/?grep=suite2%20test\.replication\.js-http-http` and notice that once you get into the `#3999` you start to get test failures. This only occurs in WebKit Nightly and Safari Technical Preview.

Note that this is not IndexedDB- or WebSQL- related. It seems to be HTTP-related. Also note that the bug is reproducible in CouchDB 1.6 but not PouchDB Server, so it may be related to the ETag (PouchDB Server doesn't use it).

**Comment by nolanlawson** [comment]
Managed to reproduce and filed an issue on WebKit: https://bugs.webkit.org/show_bug.cgi?id=156048

**Comment by nickcolley** [comment]
@nolanlawson thanks for putting this together! Hope it's not too hard for them to fix :+1:

**Comment by nolanlawson** [comment]
Had a chat about this with @janl and @rnewson in IRC today. Seems it's more of a CouchDB bug than a WebKit bug. In the meantime we can workaround it by enabling the `_nonce` hack for Safari GETs.

I think we should definitely implement the workaround before Safari ships, because CouchDB 1.6.x is going to be out there in the wild for some time.

**Comment by nolanlawson** [comment]
So for anybody interested in fixing this, the fix would be to change [the cache-busting logic](https://github.com/pouchdb/pouchdb/blob/94d1fe0583ba3f7a2929067849c33387c5b6d654/src/deps/ajax/prequest-browser.js#L11-L16) so that it applies to both IE/Edge and Safari, regardless of whether the request was a GET or a POST.

**Comment by schamp** [comment]
I could take a stab at it, if it's as straightforward as it looks, it would be good practice contributing.

**Comment by nolanlawson** [comment]
@schamp That's awesome! :) I updated the instructions above to make it a little clearer, but to confirm, the old behavior would be:

| Method | Safari | IE/Edge |
| --- | ---- | --- |
| GET | no cache-bust | cache-bust |
| POST | cache-bust | no cache-bust |

Whereas the new behavior would be:

| Method | Safari | IE/Edge |
| --- | ---- | --- |
| GET | cache-bust | cache-bust |
| POST | cache-bust | no cache-bust |

**Comment by nickcolley** [comment]
@schamp go for it! We're over at http://slack.pouchdb.com/ or irc://freenode.net/#pouchdb if you want to ask a quick question :smile_cat:

**Comment by daleharvey** [comment]
Fixed by https://github.com/pouchdb/pouchdb/commit/df0841ab38794fc2418f6a74a4e545cc245c6e37
