### ISSUE TITLE
Live Syncing more than 5 databases

### ISSUE THREAD

**Issue by coolcorey** [pouchdb/pouchdb#5012]
I have been spent a few weeks trying to root out the cause of some issues I have been having syncing 6 or more databases. Turns out, 5 is the magic number. I want to provide you the full test code and some databases, if you could let me know how, that would be great.

Okay, so, it seems that if you sync more than 5 databases, replication (push and pull? but definitely pull) will just stop. If you reload the page, without canceling sync and destroying the partially replicated databases, the replication will continue, and finish. It is also my experience, although my test code doesn't show this yet, that in either case (before or after refresh and completed pull replication), changes made to the local databases don't get pushed. But, one thing at a time! 

The halting replication is really (or maybe only) obvious in databases that have lots of docs. When I sync more than 5 databases, the database that has 819 docs, will pull 300 or 500 docs and stop.

I have my own CouchDB (latest version), but I also have a Cloudant, and both produce the same results. 

What should I provide to help debug this?

**Comment by nickcolley** [comment]
Could potentially be you're hitting the maximum parallel requests? Which is 6 in many browsers.

http://www.stevesouders.com/blog/2008/03/20/roundup-on-parallel-connections/

**Comment by coolcorey** [comment]
Oh my lord. That would make a lot of sense...

**Comment by daleharvey** [comment]
So yeh you are almost certainly hitting the parallel requests issue, however we should be falling back from that gracefully, we should never get in a position where we havent fully replicated but think we have, that sounds a lot like we arent handling errors correctly

**Comment by daleharvey** [comment]
The first step to debugging is a failing test, if you have a public database somewhere and can reproduce the problem consistently then that would be ideal, from that it is a case of figuring out what the actual mistake is and we can usually generate a smaller consistent test from that, and fix it.

**Comment by coolcorey** [comment]
I could set up a public database to test against. Would you need my code too?

**Comment by daleharvey** [comment]
Yeh the code to reproduce would be ideal, especially stripped into only the code that shows the problem if possible

**Comment by coolcorey** [comment]
Here is the test code. I am sending the database url in an email.

To create the databases:
```
var pouchdb = require('pouchdb');

var docs = [];
var databases = ['employees', 'events', 'venues', 'companies', 'shifts', 'signups', 'emails'];

for(var i=0;i<500;i++){
  docs[i] ={
    name: 'test Thing ' + i
  }
}

for(var i=0;i<databases.length;i++){
  (new pouchdb('http://xxx.xxx.xxx.xxx:5984/testforgithub-'+databases[i])).bulkDocs(docs).then(function (result) {
    console.log('Docs inserted', docs.length);
  }).catch(function (err) {
    console.log(err);
  });
}
```

To cause the issue:
```
<script src="bower_components/angular/angular.min.js"></script>
<script src="bower_components/pouchdb/dist/pouchdb.min.js"></script>

<script>

var app = angular.module('dbViewer', []);

app.service('dbService', function($rootScope){

  var databases = [{
    name: 'employees',
    sync: null,
    local: null,
    live: true
  },
  {
    name: 'events',
    sync: null,
    local: null,
    live: true
  },
  {
    name: 'venues',
    sync: null,
    local: null,
    live: true
  },
  {
    name: 'shifts',
    sync: null,
    local: null,
    live: true
  },
  {
    name: 'signups',
    sync: null,
    local: null,
    live: true
  },
  {
    name: 'emails',
    sync: null,
    local: null,
    live: true
  },
  {
    name: 'companies',
    sync: null,
    local: null,
    live: true
  }];

  function binarySearch(arr, docId) {
    var low = 0, high = arr.length, mid;
    while (low < high) {
      mid = (low + high) >>> 1; // faster version of Math.floor((low + high) / 2)
      arr[mid]._id < docId ? low = mid + 1 : high = mid
    }
    return low;
  }

  function onDeleted(id, database) {
    var index = binarySearch($rootScope[database], id);
    var doc = $rootScope[database][index];
    if (doc && doc._id === id) {
      $rootScope.$apply(function(){
        $rootScope[database].splice(index, 1);
      })
    }
  }

  function onUpdatedOrInserted(newDoc, database) {
    var index = binarySearch($rootScope[database], newDoc._id);
    var doc = $rootScope[database][index];
    if (doc && doc._id === newDoc._id) { // update
      $rootScope.$apply(function(){
        $rootScope[database][index] = newDoc;
      })
    } else { // insert
      $rootScope.$apply(function(){
        $rootScope[database].splice(index, 0, newDoc);
      })
    }
  }

  function fetchInitialDocs(database) {
    return window.PouchDB(database).allDocs({include_docs: true})
      .then(function (res) {
        $rootScope.$apply(function(){
          $rootScope[database] = res.rows.map(function (row) { return row.doc; });
        })
      });
  }



  var liveSync = function(database, databasePath){
    console.log('Syncing', database.name, 'to', databasePath + database.name);

    database.local = new window.PouchDB(database.name);

    database.sync = window.PouchDB.sync(database.name, databasePath + database.name, {
        live: database.live,
        retry: true
      }).on('change', function (info) {
        console.log('Change', database.name);
      }).on('paused', function () {
        console.log('Paused', database.name);
      }).on('active', function () {
        console.log('Active', database.name);
      }).on('denied', function (info) {
        console.log('Denied', database.name);
      }).on('complete', function (info) {
        console.log('Complete', database.name);
      }).on('error', function (err) {
        console.log('Error', database.name, err);
      });

    fetchInitialDocs(database.name)
      .then(function(){
        database.local.changes({live: true, since: 'now', include_docs: true})
          .on('change', function (change) {
            if (change.deleted) {
              // change.id holds the deleted id
              onDeleted(change.id, database.name);
            } else { // updated/inserted
              // change.doc holds the new doc
              onUpdatedOrInserted(change.doc, database.name);
            }
          }).on('error', console.log.bind(console));
      }).catch(console.log.bind(console));
  }

  this.start = function(){
    console.log('Loading databases...');
    for(var i=0;i<databases.length;i++){
      liveSync(databases[i], 'http://xxx.xxx.xxx.xxx:5984/testforgithub-');
    }

  }
  this.stop = function(){
    console.log('Unloading databases...');
    for(var i=0;i<databases.length;i++){
      if(databases[i].sync && databases[i].local){
        databases[i].sync.cancel();
        databases[i].local.destroy();
        $rootScope[databases[i].name] = [];
        console.log(databases[i].name);
      }else{
        console.log('Sync or Local is null');
      }
      window.PouchDB(databases[i].name).destroy();
    }
  }
})


app.controller('dbController', function($scope, $rootScope, dbService){
  $scope.start = function(){
    dbService.start();
  }
  $scope.stop = function(){
    dbService.stop();
  }
})

</script>


<body ng-app="dbViewer">

  <div ng-controller="dbController">
    <button ng-click="start()">Connect</button>
    <button ng-click="stop()">Disconnect</button>
    <hr>
    Emp {{$root.employees.length}}
    Ven {{$root.venues.length}}
    Evt {{$root.events.length}}
    Sft {{$root.shifts.length}}
    Sgn {{$root.signups.length}}
    Eml {{$root.emails.length}}
    Cmp {{$root.companies.length}}
  </div>

</body>
```

**Comment by coolcorey** [comment]
Let me know if that is all straight forward enough. I don't want this to be too much of a chore to understand.

**Comment by abellion** [comment]
It seems we've got the same issue ! #5007

**Comment by coolcorey** [comment]
And it isn't patchable. If you want a workaround that will work for nearly 90% of browsers, this is working for me so far!

[socket-pouch](https://github.com/nolanlawson/socket-pouch)

**Comment by nolanlawson** [comment]
@coolcorey Thanks for the clarification! However, please don't post large blocks of code in GitHub issues; it makes it harder to read and doesn't help us reproduce.

What would help us reproduce in this case would be a full HTML page that live-reproduces the error. Unfortunately posting some Angular code is not very helpful, because we don't know e.g. what version of Angular you're using, etc.

In general, this sounds like the max parallel connections issue, which is a known issue with PouchDB/CouchDB replication and indeed the only existing solution is `socket-pouch`. Please reopen if it turns out the error is something else, and if so please also post a reproducible test case.

**Comment by altrusl** [comment]
Hello guys
Workaround with websockets looks good unless you need HTTPS and nowdays you need it almost always - socket-pouch does not support SSL and does not seem to be going to

Right now to handle more then 5 database i'm gonna to use semaphores to limit number of simultaneously synchronizing databases (any better ideas?)
Shouldn't this functionality be built into the PouchDB with configuration parameter of max number of synchronized databases?

**Comment by coolcorey** [comment]
Can you front the socket-pouch instance with an SSL proxy nginx server?

**Comment by altrusl** [comment]
Technically? Yes i can, thank you for this solution

So it's gonna be a long workaround: PouchDB - Node.js with socket-pouch - Nginx SSL Reverse Proxy - CouchDB  for simple native PouchDB - CouchDB connection with more then 5 databases using sync().

By the way, if i use different subdomains for each remote database like db1.my-domain.com, db2.my-domain.com etc which resolve to the same IP - will that work?

**Comment by altrusl** [comment]
>  RFC 2616 – Hypertext Transfer Protocol
> 8.1.4 Practical Considerations
> Clients that use persistent connections SHOULD limit the number of simultaneous connections that they maintain to a given server. A single-user client SHOULD NOT maintain more than 2 connections with any server or proxy.

**Comment by altrusl** [comment]
Another possible workaround - Apache/Nginx proxy to CouchDB with forced HTTP/2?
HTTP/2 supports much more simultaneous requests.

**Comment by coolcorey** [comment]
> Technically? Yes i can, thank you for this solution
> 
> So it's gonna be a long workaround: PouchDB - Nginx SSL Reverse Proxy - Node.js with socket-pouch - CouchDB for a simple native PouchDB - CouchDB connection with more than 5 databases using sync().
> 
> By the way, if i use different subdomains for each remote database like db1.my-domain.com, db2.my-domain.com etc which resolve to the same IP - will that work?

I bet that would work too.
