### ISSUE TITLE
Cannot increase the timeout on replication GETs made through bulkGetShim

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#5042]
I'm trying to change the timeout of individual document GETs in a replicate call against a remote CouchDB server.

At https://github.com/pouchdb/pouchdb/blob/master/src/deps/bulkGetShim.js#L85, the `ajax.timeout` option is not passed from the supplied `opts` object.

It seems that the default option (set when initially calling `new PouchDB('name', { ajax: { timeout: N } })` is not passed either.

The only value that gets used is the default of 10 seconds.

Am I missing something in my configuration, or is this a bug?

**Comment by ig3** [comment]
I am seeing the same thing with bulkGetShim and http adapter. I added an ajax option to bulkGetShim call to db.get (I haven't looked at your commit) but this isn't sufficient.

db.get from bulkGetShim creates a lot of GET requests for documents and attachments. In my case, with default replication settings, several hundred (10 to 30 attachments per document). While I can eliminate or increase the timeout on GETs from bulkGetShim, these GETs also block other requests, including the next request for _changes, which has a 25 second timeout. So, unless everything downloaded by bulkGetShim completes in under 25 seconds, the GET on _changes times out.

**Comment by ig3** [comment]
Sorry - clicked the wrong button...

**Comment by alxndrsn** [comment]
@ig3 In the meantime, can you increase the 25s timeout using the `options.replicate` on your `PouchDB.replicate()` call?  You might also benefit from decreasing `options.batch_size` as well.  
ref. https://pouchdb.com/api.html#replication

**Comment by nolanlawson** [comment]
fixed by https://github.com/pouchdb/pouchdb/pull/5043
