### ISSUE TITLE
Update doc for SQLite plugin @ https://pouchdb.com/adapters.html

### ISSUE THREAD

**Issue by jitendranair** [pouchdb/pouchdb#5047]
The code below, under the section "SQLite plugin for Cordova/PhoneGap"
@ https://pouchdb.com/adapters.html does not work for PouchDB(Version5.3.1)
with Cordova-sqlite-storage(Version 1.2.0) :

var db = new PouchDB('myDB', {adapter: 'websql'});

I had to use 'location' key to make in work:

var db = new PouchDB('myDB', {adapter: 'websql', location:'default'});

NOTE: As mentioned here https://github.com/litehelpers/Cordova-sqlite-storage, using the 'default' value for the 'location' key.

**Comment by nolanlawson** [comment]
Yep, this is a fix we just put into master. Another solution is an alternative to the SQLite Plugin, which I wrote to avoid these kinds of issues in the future: https://github.com/nolanlawson/cordova-plugin-sqlite-2

It works out-of-the-box with PouchDB, no extra configuration required. And it's faster. :)
