### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by andreujuanc** [pouchdb/pouchdb#5048]
Hello,

I have an error only the first time i sync remote and local db. I cant find why, the stack trace does give me much detail on were it is failing or why. First error I know it's normal, bu second one is an exception: Database encountered an unknown error. It only happens the first time, ie, i clean cache, cookies, everything, and then sync. Next sync after first error does not produce this exception.

Leave log here.

Thanks!

_stacktrace exported to external gist_: https://gist.github.com/nolanlawson/f64c70e4fed07f0f699c507e4700d72c

**Comment by mryellow** [comment]
Not sure if it's the same but after being away for 2 weeks I return to find replication spitting "Database encountered an unknown error" for half the documents trying to be retrieved. Deleting the local database doesn't help. Production version is fine however on localhost Chrome fails, doesn't seem to be a CORs issue... Firefox functions correctly locally. Hits are coming back 200 but then trigger a 500 error in PouchDB.

**Comment by mryellow** [comment]
Could be I was flooding Chrome, or some deprecated documents were somehow causing the issue. I've filtered out a bunch of documents and the errors have gone with them. Can't be certain what the actual cause was in my case.

**Comment by nolanlawson** [comment]
Unfortunately the 500 error is the least helpful error message we can show to users, so yeah, it's impossible to say what the actual underlying issue is (CORS? timeouts?). In the case of the original poster, I'd say it's almost undoubtedly a CORS error, so you may want to look into [add-cors-to-couchdb](https://github.com/pouchdb/add-cors-to-couchdb).

**Comment by andreujuanc** [comment]
Its not cors. Im working this weekend on the project again, so ill try to repro this in separate project.

**Comment by trygve-lie** [comment]
Are you proxying through node.js or something like this: https://cloudant.com/blog/cors-and-reverse-proxies-in-node-js-express/#.Vx_AuVZ97J8 ?

If so, could you try to add a custom http agent to the http client doing the backwards request. Something like this:

```js
const agent = new http.Agent({
    keepAlive: true,
    maxSockets: 40,
    maxFreeSockets: 10,
    timeout: 60000,
    keepAliveMsecs: 30000
});
```

I did run into these issues lately and I'm doing this kind of proxy in node and found the issue to be with the number of sockets in node and not withing the browser.

**Comment by daleharvey** [comment]
Hopefully some of the help here worked, but cant fix without reproducing, if you are still seing problems please reopen or file a new bug, cheers
