### ISSUE TITLE
Android/Desktop Browser: CORS in pouchDB based App.

### ISSUE THREAD

**Issue by NitzDKoder** [pouchdb/pouchdb#5059]
Newbie to PouchDB..

Setup:
Android/Desktop Browser App with 

PouchDB <--> CB SyncGateWay <--> CouchBase Server.

Browser throws error:

    "ERROR: XMLHttpRequest cannot load http://SYNCGATEWAY/data/. Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains the invalid value ''. Origin 'null' is therefore not allowed access."

	
**Configured the Sync Gateway to allow all/specific domain IPs to access it, but unsuccessful (* - allow all Origin IPs) .**

What will be the **orgin** while request? 

How should be the SyncGatway Cors config to support Android app and Desktop Broswer.?

http://developer.couchbase.com/documentation/mobile/1.2/develop/guides/sync-gateway/configuring-sync-gateway/config-properties/index.html#cors-configuration

Thanks

Nithin

**Comment by nolanlawson** [comment]
Sorry, this sounds like more of a Sync Gateway question and I admit I'm not sure how to enable CORS in Sync Gateway.

In CouchDB, you can enable CORS by using https://github.com/pouchdb/add-cors-to-couchdb. In PouchDB Server, it's enabled by default. Maybe you can use one of those to get started, and then configure CORS later?

Also maybe this blog post can help you: http://blog.couchbase.com/first-steps-with-pouchdb--sync-gateway-todomvc-todolite

Please also try the Couchbase support if you need further assistance.

**Comment by Harashikage** [comment]
Same Issue Observed on my end.
Tried the default getting started Todo app. Synced the app to the Server via CB SyncGateway.
On sync the Request Header > has the Local url for the 'ORIGIN' and gateway for the 'HOST'. The Sync Gateway was Configured for the Specific ORIGIN URL.
But the Response Header > 'Access-Control-Allow-Origin'>  is Null and the request is throwing a 204 No Content .
The Sync Gateway was configured for the specific origin / all URLs still same problem.

**Comment by NitzDKoder** [comment]
@jchris your thoughts on this pls?

**Comment by NitzDKoder** [comment]
in my setup CORS was applied in wrong SyncGate..ate my 2 days..everything works now..
