### ISSUE TITLE
ajax in browser returns unknown error on timeout

### ISSUE THREAD

**Issue by ig3** [pouchdb/pouchdb#5061]
On timeout, in node, ajax returns error ETIMEDOUT with status 400 but in the browser ajax returns an unknown error.

request-browser returns an empty error and a response with statusCode: 0. In ajaxCore, this is resolved to an unknown error.

**Comment by nolanlawson** [comment]
Yeah it would be nice to unify those error messages. I think status code 0 is normal, because the browser is explicitly _not_ trying to reveal the actual source of the message (same for CORS errors).

**Comment by ig3** [comment]
Status code 400 Bad Request isn't ideal. Per HTTP 1.1 spec it is:
> The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications. 

A timeout is not a situation where the client should not repeat the request and it can occur in cases where the request hasn't been sent to the server so no implication the server hasn't understood.

Status code 408 Request Timeout is a little closer:
> The client did not produce a request within the time that the server was prepared to wait. The client MAY repeat the request without modifications at any later time. 

At least this is a timeout but it is not the server timing out the request and it arises in situations where the request hasn't been sent to the server so nothing to do with how long the server is prepared to wait.

The only other specified timeout error is 504 Gateway Timeout, but this would only be appropriate if it were produced by the server.

It seems there is no HTTP status code that indicates a timeout at the client. The timeout may occur before the HTTP protocol exchange begins or regardless of the status if it has begun so an error that does not include status code or with status code 0 might be better options.

I am more concerned with the error than the status code. 'Unknown error' is particularly unhelpful. ETIMEDOUT seems appropriate. Consistency with node is good but in this case, perhaps node sets status code inappropriately and should be overridden.

For me, a more specific error from ajax is a step towards dealing with timeouts during replication which seems to be the subject of multiple issues here and is problematic in several of my applications.

**Comment by nolanlawson** [comment]
fixed in #5062
