### ISSUE TITLE
Is replication `batch_size` affected by attachments

### ISSUE THREAD

**Issue by jo** [pouchdb/pouchdb#5080]
> options.batch_size: Number of documents to process at a time. Defaults to 100. This affects the number of docs held in memory and the number sent at a time to the target server. You may need to adjust downward if targeting devices with low amounts of memory (e.g. phones) or **if the documents are large in size (e.g. with attachments)**. If your documents are small in size, then increasing this number will probably speed replication up.

Since attachments aren't fetched inline anymore is this still valid?

**Comment by nolanlawson** [comment]
No, it's not.

**Comment by jo** [comment]
OK, I'll fix the docs then.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/1a7d7e7cf08591288128985556da20c9995b52a3

**Comment by ig3** [comment]
In my experience, the number and size of attachments is still relevant.

The comment (not the altered part) is subtly incorrect: the batch_size is not the number of documents processed in a batch - it is the number of change feed items processed in a batch. Each change feed item has a single document ID, so in this sense it refers to a single document, but it may have multiple revisions and each revision will be synchronized. The distinction is significant if the document size is significant or if the document revisions have significant number or size of attachments. There may be many conflicted revisions to synchronize.

Neither the number of document revisions nor the number of attachments are considered when determining whether a batch has reached the batch_size limit - only the number of change feed items is considered. Thus attachments are not relevant to batch_size, but this is not to say that the number or size of attachments is not relevant to the network and memory resources required to process a batch.

While attachments are no longer fetched inline, they are still fetched. getAllDocs returns all the document revisions in the batch that require synchronization, including their attachments, unless I am misunderstanding the code. 

While I haven't updated the version of PouchDB I am using for a couple of weeks now, so don't have the latest changes, I am still seeing memory utilization significantly impacted by number and size of attachments and batch_size, using the http adapter. For example, when I try to replicate a database with on the order of 100 large attachments per small document, I find that memory is exhausted with the default batch size and, in fact, sometimes even with batch_size set to 1, particularly where there are unresolved conflicts in the database.

There are also issues with timeouts related to the number of documents and attachments fetched in a batch. These can be mitigated with the recent changes allowing ajax option to be passed through synchronize, but they are not trivial. The time required to process a batch, including fetching attachments, can be reduced by reducing batch_size.

While attachments don't affect "batch_size", they do affect "batch size", if by "batch size" one means the time and memory required to process the batch.

I might change the comment to something like:

Number of change feed items to process at a time. Defaults to 100. This affects the number of docs and attachments held in memory and the number sent at a time to the target server. You may need to adjust downward if targeting devices with low amounts of memory (e.g. phones) or if the documents and/or attachments are large in size or if there are many conflicted revisions. If your documents are small in size, then increasing this number will probably speed replication up.

**Comment by jo** [comment]
Thank you very much for providing details, @ig3! Do you plan to make a pull request with the doc change above?

**Comment by ig3** [comment]
A pull request is easy enough but I think it will be best for someone else to consider the situation and decide what to do, including the wording of the comment, if it is to be changed again. I'm not good at concise but a concise comment is more likely to be understood and helpful.

@jo - Does what I say make sense to you? Does it seem correct? I have only had a quick glance at the getAllDocs code and may be misunderstanding it. In particular, I would like to be clear about how getAllDocs handles getting multiple revisions of a document with attachments - is a copy of the attachments returned with each revision? Even if they are unchanged? I will have a look, eventually, but time is hard to come by...

If you like my suggestion, I would be happy for you to submit a PR with it, revised as you think appropriate. For the moment, I will leave it to your discretion.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/95d0ba407e7c19410d148acd6806be1bdad95979
