### ISSUE TITLE
http://pouchdb.com/blog is down

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5084]
So I upgraded to ElCap, which forced me to reinstall jekyll, and now apparently when I build the web site, this page is empty: http://pouchdb.com/blog.

All the blog posts are still there; it's just that the list of blogs is empty now.

**Comment by nolanlawson** [comment]
BTW the way to reproduce this error is:

1. check out the code
2. `sudo gem install jekyll redcarpet pygments.rb`
3. `npm install`
4. `npm run build-site`
5. open http://127.0.0.1:4000

I can reproduce this locally. Haven't figured out what's wrong yet. :confused:

**Comment by fivetanley** [comment]
Do you know the last known good version of jekyll used to build the site?

**Comment by yuloh** [comment]
I'm trying to reproduce this locally.  I opened a separate issue to change the highlighter and markdown libraries since they are deprecated.  Recently Github Pages switched to Jekyll 3 which changed a lot.

**Comment by paul-howard** [comment]
Yup. I can reproduce the problem locally and confirm that it's related to the pagination gem.

To fix it:

1. Add the line `gems: [jekyll-paginate]` to `docs/_config.yml`
2. `> gem install jekyll-paginate`
3. `> npm run build-site`
4. Refresh the blog page. Posts now visible!

**Comment by nolanlawson** [comment]
https://github.com/pouchdb/pouchdb/pull/5089
