### ISSUE TITLE
Enable GZIP for website assets

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#5088]
Compressing https://pouchdb.com/static/css/pouchdb.css could save 50KiB (82% reduction).
Compressing https://pouchdb.com/static/img/icons.svg could save 4.8KiB (53% reduction).
Compressing https://pouchdb.com/static/js/stickyfill.min.js could save 3.5KiB (63% reduction).
Compressing https://pouchdb.com/static/img/icon-edit.svg could save 934B (50% reduction).
Compressing https://pouchdb.com/static/js/code.min.js could save 813B (52% reduction).
Compressing https://pouchdb.com/static/img/mark.svg could save 720B (62% reduction).

Report can be seen at https://developers.google.com/speed/pagespeed/insights/?url=pouchdb.com

**Comment by daleharvey** [comment]
Yeh will take a look at this, cheers

**Comment by nickcolley** [comment]
Thanks :+1:

**Comment by anubes** [comment]
Hello

**Comment by nickcolley** [comment]
Hey @anubes :smile: 

If you need help feel free to [raise a new issue](https://github.com/pouchdb/pouchdb/issues/new) or you can chat with us over at [IRC](https://www.irccloud.com/invite?channel=pouchdb&hostname=irc.freenode.net&port=6697&ssl=1) or [Slack](http://slack.pouchdb.com/)

**Comment by daleharvey** [comment]
Ok all done :)

**Comment by nickcolley** [comment]
Thanks @daleharvey big performance boost from that! :D
