### ISSUE TITLE
pouchdb.com home page layout broken

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5094]
https://pouchdb.com/ has the editable title which isnt supposed to display on the home page

@nickcolley Any chance you could point out where the bug is here? you're probably the most familiar with that area

**Comment by nickcolley** [comment]
Right so the logic to show that title is here: https://github.com/pouchdb/pouchdb/blob/master/docs/_layouts/default.html#L63

Maybe the page.url has changed.

I wonder if we need to be more careful about website deploys hmm.

**Comment by nolanlawson** [comment]
https://github.com/pouchdb/pouchdb/pull/5150
