### ISSUE TITLE
Inconsistency beetween PouchDB and CouchDB result

### ISSUE THREAD

**Issue by JacquesBonet** [pouchdb/pouchdb#5095]
Hello,

I have a problem a consiscency result when I do a request with PouchDB connected to CouchDB and directly CouchDB.

**Here my CouchDB view:**

```
   "views": {
       "date": {
           "map": "function (doc) {\n  return   emit(doc.date);\n}"
       }
```

**Here my CouchDB request**

```
curl -X GET 'http://127.0.0.1:5984/a_a_com/_design/index/_view/date?startkey="03/11/2016"'
{"total_rows":3,"offset":1,"rows":[
{"id":"1F5B32FB-4A3B-67A6-8C93-34B124AECE8F","key":"04/25/2016","value":null},
{"id":"08752CC3-A2AA-F419-AE19-C3BD7CD9E7B8","key":"2016-04-25T15:46:17.567Z","value":null}
]}
```

**Here my PouchDB request**

```
this.db.db.query('index/date', { starkey: "03/11/2016"}).then(function (res) {
         console.log( res)
         let a = JSON.stringify(res)

      })
```

![image](https://cloud.githubusercontent.com/assets/173393/14795835/a60e1a46-0b2a-11e6-84b7-8655e07482fb.png)

The date attribute in the 3 couchDB documents have the following values:

```
   "date": "2016-04-25T15:46:17.567Z",
   "date": "04/25/2016",
   "date": "02/10/2016",      <---- Not matched on CouchDB, matched on PouchDB
```

Any idea of the problem?

Best regards.

Jacques

**Comment by nolanlawson** [comment]
There is a typo in your PouchDB query: `starkey` instead of `startkey`.

Let me know if that resolves it!

**Comment by JacquesBonet** [comment]
Yes your right.

Its ok, no problems.

Thks a lot.
