### ISSUE TITLE
Deleting local database in Electron

### ISSUE THREAD

**Issue by nylki** [pouchdb/pouchdb#5099]
For deleting local databases while in development you [recommend a chrome extension](https://pouchdb.com/guides/databases.html#deleting-your-local-database). Although [Electron](http://electron.atom.io/) is basically chromium, I don't think you can use/install chrome addons.

What would be the best way to delete traces of local databases with electron?

**Comment by nickcolley** [comment]
Hey @nylki 

With Electron you could use the Node.js adapters rather than the browser adapters like in the following example https://github.com/nolanlawson/hello-electron-with-pouchdb

This data should show up in the file system so you can delete them there.

**Comment by nickcolley** [comment]
Had a look at the docs, potentially this could work for you?

http://electron.atom.io/docs/v0.32.0/api/session/#sessionclearstoragedataoptions-callback

**Comment by nylki** [comment]
> "With Electron you could use the Node.js adapters rather than the browser adapters like in the following example https://github.com/nolanlawson/hello-electron-with-pouchdb"

Unfortunately I have to use the browser scope, because I need pouchdb-authentication to work properly. which doesn't work properly inside node.

> Had a look at the docs, potentially this could work for you for clearing browser based storage?
> http://electron.atom.io/docs/v0.32.0/api/session/#sessionclearstoragedataoptions-callback

Thanks! This looks like the proper way to do it. I'll try it out later. But damn, I should have read Electron's documentation more thoroughly. so thanks for digging it up :)

**Comment by nolanlawson** [comment]
pouchdb-authentication is just a thin layer for communicating with CouchDB. It doesn't even require a local database; it just uses PouchDB's ajax module and makes HTTP requests.

You can use the browser-style PouchDB for authentication, and then use the Node.js style one for storage. This demo app has an example showing how you can use both types simultaneously: https://github.com/nolanlawson/hello-electron-with-pouchdb

**Comment by nylki** [comment]
@nolanlawson cool, wasn't aware you could easily mix them!
