### ISSUE TITLE
node6 is permafail

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5102]
All node tests, likely due to the 6x release

**Comment by daleharvey** [comment]
So https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.attachments.js#L1268 is failing because the new version of node is generating different digests

**Comment by nolanlawson** [comment]
very confusing since those digests match what's output by both CouchDB and spark-md5. 😕

**Comment by nolanlawson** [comment]
might be related: https://github.com/nodejs/node/pull/5522

**Comment by daleharvey** [comment]
Changed the title since we fixed travis putting it on 5

**Comment by omsmith** [comment]
Fix for test failures in #5107 

You'll also see C/JS stack traces printed until https://github.com/Level/leveldown/pull/280 is available

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/3d7d49738afa9678a2c2231af9e1072e2d227257
