### ISSUE TITLE
Endless replication when using reverse-proxy.

### ISSUE THREAD

**Issue by SukantGujar** [pouchdb/pouchdb#5116]
The setup -
PouchDB 5.3.2 in Chrome, Nodejs server and DB is CouchDB 1.6.1 brand new setup with Admin party enabled. The entire stack is running on a single machine as of now, so everything is localhost.

In nodejs, I am using express to serve static app contents and a reverse proxy to hook up `/db` endpoint with the CouchDB server. The proxy code is pretty run of the mill -

```
	// Bind /db to couch DB backend
	var DATABASE_URL = 'http://localhost:5984';

	// middleware itself, preceding any parsers
	app.use(function(req, res, next){
		var proxy_path = req.path.match(/^\/db(.*)$/);
		if(proxy_path){
			var db_url = DATABASE_URL + proxy_path[1];
			console.log("db_url: " + db_url);
			req.pipe(request({
			uri: db_url,
			method: req.method
			})).pipe(res);
		} else {
			next();
		}
	});
```

In the browser, I have started a pull replication from a remote DB (via reverse-proxy) to local Pouch DB...
` self.replicator = self.localDB.replicate.from(remoteURL, { live: true, retry:true});`
Code abbreviated for brevity, will add more if required.
This results in an endless series of replication calls. The replication never finishes, and my remote DB bloats from a mere 8.1 K to 1 MB in no-time. The local DB also starts to bloat. Looking at the data, I can see that the design docs accumulate and cause the bloat.
Most likely, this may be caused by the CouchDB setup at my end. But I am not super sure and would appreciate any help in debugging this.
I have attached Fiddler trace with this issue, which might contain something useful to get to the bottom of this. To inspect this in Fiddler, simply rename to .saz and import the session.
[EndlessReplicationLog.saz.zip](https://github.com/pouchdb/pouchdb/files/244561/EndlessReplicationLog.saz.zip)

.

**Comment by SukantGujar** [comment]
This turned out to be an issue with the reverse-proxy logic, which was ignoring query string parameters. There is surprising lack of the right way to do this with `request` on the internet. Anyways, here's the fix which worked for me -
`req.pipe(request({ qs:req.query, uri: db_url })).pipe(res);`
This ensure that the query string parameters are preserved along with the other parts of the request while being sent to the DB server.

**Comment by RonCan** [comment]
Hi @SukantGujar I'm using the exact same setup as yours. Even after using qs, the replication doesn't stop at my selector: {type: "Agent"} and goes on to replicate Office type and other type resources. Could you help?

**Comment by SukantGujar** [comment]
@RonCan I found the root cause by perusing the CouchDB client request logs. If you are on Windows, it helps to run CouchDB from `Start CouchDB` shortcut, which lets you see the logs in the terminal that opens up. Otherwise (if you are running it as a Service) you would need to find the logs from CouchDB installation path which are not live. No idea how to do this in other platforms.
So assuming you can collect the connection logs, the next step is to capture the logs in a non-proxy setup where the replication works fine. In my case, I wrote some code to change as few records as possible to trigger replication and capture the logs. Then repeat the same with proxy in between and compare them. Its important to compare the entire request, including URLs. In my case this comparison quickly revealed the issue of missing QS portions in the requests. If this doesn't give you much, you should then compare the responses being sent back as well.
Hope you are able to resolve the issue.
