### ISSUE TITLE
Test (c|p)ouchdb server for people to use

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5117]
So while we have paste.pouchdb.com (and can use jsbin etc) to test pouchdb on the client, its still quite a bit of effort to get to a point where a new use can test pouchdb syncing. They need to pick an online service (not a lot of choices) go through the whole sign up, possibly configure etc.

I would like to maintain an online, admin party, cors enable server that people can test sync with immediately. I have the domain pouchbase.com that I was planning to put it up on. 

Opening this issue so people can discuss issues / use cases with it before I code it and get it online

**Comment by daleharvey** [comment]
So one issue is peoples databases conflicting, if someone writes a demo that says `new PouchDB('http://pouchbase.com/demo')` then multiple people use that url at the same time, their apps are going to conflict. 

I am thinking that when you go to http://pouchbase.com is presents you some randomly generated database name and suggests you use that, this means there is less magical routing involved and still lets us use the site for cases where we do want to share the database with multiple people

**Comment by daleharvey** [comment]
oh and just to clarify, the databases on this server will be wiped every night or something along those lines, its not to be confused with a production hosting, just a test bed

**Comment by nolanlawson** [comment]
I still think the name PouchBase is a bit confusing (if nothing else, kinda sounds like we are offering a PouchDB™ Official Hosting), but I definitely agree that having something that's quick and easy to set up is best.

That said, I kinda feel like `npm install -g pouchdb-server` is not too far from the ideal. Might scare people who are afraid of the command line, but I'm hearing less and less complaints from e.g. Windows users, especially after the recent leveldown-prebuilt fixes. So when we rewrite the "getting started" guide, it might be good to mention both pouchdb-server and pouchbase.

**Comment by nickcolley** [comment]
Love the idea of having a test bed, would make it a lot easier for newcomers to get started with sync.

Agree that the name could be confusing, first thing that springs to mind is a PouchDB Couchbase (http://www.couchbase.com/)

**Comment by daleharvey** [comment]
Yeh the name is somewhat tongue in cheek with couchbase / firebase, but as it is not a production / serious service, just a test bed I think it will be fine, either way can move to a new name if needed

**Comment by daleharvey** [comment]
So I have pretty much written this (its like 20 lines of code) however I have one worry left, in node we dont do anything special to prevent map reduce queries from doing basically anything they want right? Not worried on the server since this will be ran inside a container, but if someone chucks up `rm -rf` in a map function and convinces someone else to pull it down and execute it they can wipe the users data right?

Its a little bit of a stretch, if someone convinces you to download arbitrary code and run it they can always wipe your data, but it doesnt seem like by just using a database that should be possible

**Comment by daleharvey** [comment]
If the above is true, then considering just rejecting design docs from the server

**Comment by daleharvey** [comment]
So I put this up today - https://pouchbase.com/, no need to keep tracking here, happy to hear any feedback :)
