### ISSUE TITLE
Performance regression in leveldb adapter between 5.2.1 and 5.3.0

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5118]
Reported by @omsmith in Slack:

> (5.3.0): Statistical profiling result from isolate-0x2286d90-v8.log, (34612 ticks, 21 unaccounted, 0 excluded).
> (5.2.1): Statistical profiling result from isolate-0x3392d90-v8.log, (12535 ticks, 2 unaccounted, 0 excluded).

The culprit was determined to be 0ddeae6b6c44fa12b83c5348df6947e3ce28c28c.

> My tests run ~34s with that commit, and ~9s with it reverted

I'm also suspicious of 4cccf617bce67351123a842f12ff0e694587f111. It seems to have introduced a new compaction requirement in leveldb that runs for every write operation. But according to @omsmith's tests, 0ddeae6b6c44fa12b83c5348df6947e3ce28c28c is the real cause.

**Comment by nolanlawson** [comment]
Reason I'm still suspicious of that other commit is:

> FYI, doesn't seem to effect WebSQL (used https://pouchdb.com/2016/03/04/pouchdb-5.3.0-sqlite-support-in-node.html), is ~30s with or without the change. Plain LevelDB (write to disk) is effected similarly to using memdown. I'll work on a perf test

 0ddeae6 ought to affect all adapters, whereas 4cccf61 only affects the leveldb adapter.

**Comment by omsmith** [comment]
Thanks for following up, sorry I haven't gotten back with a perf test yet.
Just have a lot going on right now, but I'll get it figured.

**Comment by nolanlawson** [comment]
@omsmith Can you provide some idea of what your performance test did? I'm trying to reproduce with our own performance tests, and not really succeeding.

**Comment by nolanlawson** [comment]
I looked into https://github.com/pouchdb/pouchdb/commit/4cccf617bce67351123a842f12ff0e694587f111 but can't determine conclusively whether or not it's a performance regression.

**Comment by nolanlawson** [comment]
#5121

**Comment by omsmith** [comment]
Here's the best I could come up with in short order, which is just sort of mirroring the type of stuff that is going on in our test suite. We do the cleanup between each test, maybe load in some new data before a particular test, run some queries (probably far less than 100, but it exposed it so didn't continue tweaking). We hit all indices between tests to make sure their up to date after clearing docs. Part of our application does a stale read (we tap index on write) hence why I included `stale: 'ok'` here, but that doesn't really seem to change much for this test case.

```bash
omsmith osmith-ubuntu-t1700 | Tue May 03 at 08:25:03 | git perf-revert
/home/omsmith/dev/pouchdb ~ git checkout master && npm run build-node && node ../../pouchdb-perf/test.js
Switched to branch 'master'
Your branch is up-to-date with 'upstream/master'.

> pouchdb@5.3.3-prerelease build-node /home/omsmith/dev/pouchdb
> bash bin/build-node.sh

Wrote lib/index.js
things: 27400ms
omsmith osmith-ubuntu-t1700 | Tue May 03 at 08:25:41 | git master
/home/omsmith/dev/pouchdb ~ git checkout perf-revert && npm run build-node && node ../../pouchdb-perf/test.js
Switched to branch 'perf-revert'
Your branch is up-to-date with 'origin/perf-revert'.

> pouchdb@5.3.3-prerelease build-node /home/omsmith/dev/pouchdb
> bash bin/build-node.sh

Wrote lib/index.js
things: 11920ms
```

```js
'use strict';

const PouchDb = require('../dev/pouchdb/lib');

const db = new PouchDb('testdb', { db: require('memdown') });

function setup() {
	return Promise.all([
		db.put({
			_id: '_design/foo',
			language: 'javascript',
			views: {
				bar: {
					map: "function(doc) { if ('baz' === doc.docType) { emit(doc.quux); } }"
				}
			}
		})
	]);
}

function insertDocs() {
	return Promise.all([
		db.post({ docType: 'meh' }),
		db.post({ docType: 'meh' }),
		db.post({ docType: 'meh' }),
		db.post({ docType: 'meh' }),
		db.post({ docType: 'meh' }),
		db.post({ docType: 'meh' }),
		db.post({ docType: 'meh' }),
		db.post({ docType: 'baz', quux: 1 }),
		db.post({ docType: 'baz', quux: 2 }),
		db.post({ docType: 'baz', quux: 3 }),
		db.post({ docType: 'baz', quux: 4 }),
		db.post({ docType: 'baz', quux: 5 }),
		db.post({ docType: 'baz', quux: 6 }),
		db.post({ docType: 'baz', quux: 7 }),
		db.post({ docType: 'baz', quux: 8 })
	]);
}

function query() {
	return db.query('foo/bar', { keys: [1, 3, 5, 7], include_docs: true, stale: 'ok' });
}

function cleanup() {
	return db
		.allDocs({ include_docs: true })
		.then(docs => docs.rows.filter(row => !row.id.match(/^_design/)))
		.then(rows => rows.map(row => { row.doc._deleted = true; return row.doc }))
		.then(docs => db.bulkDocs(docs));
}

function tapIndex(index) {
	return db.query(index, { limit: 1 });
}

function tapIndices(ddoc) {
	const docName = ddoc._id.split('/')[1];
	return Promise.all(
		Object.keys(ddoc.views).map(viewName => tapIndex(`${docName}/${viewName}`))
	);
}

function tapAllTheThings() {
	return db
		.allDocs({ include_docs: true, startkey: '_design', endkey: '_design0' })
		.then(res => res.rows.map(row => row.doc))
		.then(ddocs => Promise.all(ddocs.map(tapIndices)));
}



function test(n, m) {
	const doInsertDocs = () => insertDocs();
	const doTapAllTheThings = () => tapAllTheThings();
	const doQuery = () => query();
	const doQueryMany = (n) => {
		let p = Promise.resolve();
		while (n--) {
			p = p.then(doQuery);
		}
		return p;
	};
	const doDoQueryMany = () => doQueryMany(m);
	const doCleanup = () => cleanup();

	let p = setup();
	while(n--) {
		p = p
			.then(doInsertDocs)
			.then(doTapAllTheThings)
			.then(doDoQueryMany)
			.then(doCleanup)
			.then(doTapAllTheThings);
	}
	return p;
}

console.time('things');
test(10, 1000).then(() => console.timeEnd('things'), e => { console.error(e); console.error(e.stack); });
```

**Comment by omsmith** [comment]
Where `perf-revert` is https://github.com/pouchdb/pouchdb/compare/master...omsmith:perf-revert

**Comment by omsmith** [comment]
Just FYI, from reading IRC - my particular stake here isn't urgent. Was just looking at updating PouchDB again and thought I'd try to follow up (I'd ran into this before and got distracted). I can sit happily on 5.2.1. Our real-world usage is just PouchDB with the HTTP adapter - we use PouchDB for swapping in alternative adapters locally or in testing (such as memdown), having the well-formed interface, and it's always nice to use projects with such a great community.

I suspect this must be affecting others, as you say a 9MB ddoc is not common, but they obviously haven't noticed as of yet. Helps that it's seemingly limited to leveldb storage mediums.

Anyway, don't want to screw @garethbowen over unnecessarily if something else can be figured out since he seems to be leveraging PouchDB-specific functionality more, and would probably have a greater need of tracking latest versions. Hard to see what sort of midway solution there would be though.

**Comment by nolanlawson** [comment]
Thanks very much for the test!

27400ms vs 11920ms is a pretty big performance difference, and your test looks very similar to the `persistent-views` test in our own perf suite, in that it uses a small ddoc and queries it many times. In my mind, that's still closer to what most folks' use case is like.

I also talked with @garethbowen and it sounds like they would be able to reduce the size of the ddoc, which is a reasonable compromise IMO.

**Comment by nolanlawson** [comment]
1bff500
