### ISSUE TITLE
allDocs: descending: true, returns empty rows

### ISSUE THREAD

**Issue by nylki** [pouchdb/pouchdb#5126]
Not sure if this is pouchdb or generally couchdb related, but I found the following rather strange:

I have a simple database with doc _ids including timestamps, for example:

`round_1462295466986_anonymousplayer`, `round_1462295476921_anonymousplayer`, etc.

I want to get the 100 newest docs (the ones with a bigger timestamp value),
so I thought using the `descending: true` option would be the best idea.

Ascending works fine:

```.js
     remoteDB.allDocs({
      startkey: 'round_',
      endkey: 'round_\uffff',
      limit: 100,
      /*descending: true,*/
      include_docs: true
    }).then((docs) => {
      // docs.rows has entries
      console.log(docs);
    })
```

But if I uncomment the `descending`, the rows are empty. What am I doing wrong?

**Comment by nolanlawson** [comment]
When you do `descending: true`, you need to reverse the `startkey` and `endkey`. You may want to read: http://pouchdb.com/2014/04/14/pagination-strategies-with-pouchdb.html

Let me know if that helps! :)

**Comment by nylki** [comment]
@nolanlawson That helped!
After reading https://pouchdb.com/api.html#batch_fetch I thought that the `descending` option does the end/start-key switching itself, thats probably where my confusion came from:
> note that the order of startkey and endkey is reversed when descending:true.

Maybe wording it "note that the order … *has to be reversed* …" would have made it clear to me.

Anyways, thanks for the blog link again, I remember reading that entry a while ago and am always delighted how well you documented PouchDB :)
