### ISSUE TITLE
Remove buffer.toArrayBuffer() usage

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5140]
This was apparently dropped in `buffer` but we are still using it: https://github.com/feross/buffer/issues/90

See test failures in: https://github.com/pouchdb/pouchdb/pull/5135

**Comment by nolanlawson** [comment]
Marking this as "help wanted" because it should be a pretty easy fix. Presumably if they dropped `to.ArrayBuffer()`, they replaced it with something else we can use. So it's just about doing the research and figuring out what the new API is.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/8f55544440dcfa543b3f580388aefb0e35fae6e5
