### ISSUE TITLE
CustomPouchError while replicating the database

### ISSUE THREAD

**Issue by varunsikka** [pouchdb/pouchdb#5143]
I get this below error often when I replicate the couchdb to pouchdb. It happens while replication and not all documents are replicated. I am not able to get this. Can you guys help me with this.

The message below is copied from Chrome console.

```
CustomPouchError {status: 500, name: "unknown_error", message: "Database encountered an unknown error", error: true}
error
:
true
message
:
"Database encountered an unknown error"
name
:
"unknown_error"
status
:
500
__proto__
:
Error
constructor
:
PouchError(opts)
toString
:
()
arguments
:
[Exception: TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context. at Function.remoteFunction (<anonymous>:3:14) at Object.InjectedScript.callFunctionOn (<anonymous>:124:124)]
caller
:
[Exception: TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context. at Function.remoteFunction (<anonymous>:3:14) at Object.InjectedScript.callFunctionOn (<anonymous>:124:124)]
length
:
0
name
:
""
prototype
:
Object
__proto__
:
()
<function scope>
__proto__
:
Object
```

**Comment by daleharvey** [comment]
@varunsikka Hi, can you possibly give us more information about the bug, possibly try and reproduce it in a minimal way that you can share? at a wild guess from your error it seems like something may be modifying the Object prototype, but its pretty much impossible to tell from just that error, Thanks

**Comment by daleharvey** [comment]
We cant debug this without more information so closing out, if you are still seeing a problem then please reopen with more information and ideally steps for us to reproduce the error, Thanks
