### ISSUE TITLE
Filtered replication doesn't record progress unless change is returned

### ISSUE THREAD

**Issue by garethbowen** [pouchdb/pouchdb#5145]
I use filtered replication to reduce the number of records replicated to Pouch. When a change passes the filter function the doc is replicated to Pouch and the local seq is updated which future replications use as the `since` parameter so already filtered changes can be skipped over.

However when no changes are returned the seq is not updated so subsequent replications use the old value for `since`. This means each doc can be run through the filter function multiple times until a change is made that passes the filter.

For example if the couchdb seq is 2000 and the local seq is 1000 the replication request will look something like...

```
.../_changes?style=all_docs&heartbeat=10000&filter=medic%2Fdoc_by_place&id=7E7633CB-C6CD-D85D-9ABD-1C6B7570F000&since=1000&limit=100
```

Then the server runs all the changes from 1000 to 2000 through the filter and responds with...

```json
{
  "results":[],
  "last_seq":2000
}
```

pouchdb then ignores the response as there are no `results` to update.

Modify pouchdb to store the `last_seq` from the changes response in the replication checkpoint so replication starts from the new seq next time.

**Comment by nolanlawson** [comment]
fixed by https://github.com/pouchdb/pouchdb/commit/f1989ce6361193f1e213cb0b17e7dab4f2a8451c
