### ISSUE TITLE
webkit failed to execute ‘db.put’

### ISSUE THREAD

**Issue by 7demo** [pouchdb/pouchdb#5147]
For some reasons,  My workmate make a C++ software with the plugin webkit.  It can load the website which is developed with js/html/css.

When the chrome load the website, the pouchdb works well. However,  the pouchdb does`t work well when the software load the website. The webkit verision:

`(WinodwsNT 6.2; WOW64) AppleWebkit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36 `

My code : 

`var room = new PouchDB("room");`
`room.put({
		_id : user.courseId, //
		uid : user.uid //
	}).then(function (data) {
		console.log(data)
	}).catch(function (err) {
		console.log(err)
	})`

the 'room' is ok. But when i save somes datas, the err is coming: 

`{'status':500, 'name':'indexed_db_went_bad', 'message':'unknow','reason':'Failed to open indexedDB, are you in private browsing mode?'}`

At first, I think the webkit can`t make the indexDB work. Howerver , i make a test:

`window.indexedDB = window.indexedDB || window.mozIndexedDB || window.webkitIndexedDB || window.msIndexedDB;	
var request = indexedDB.open("MyTestDatabase", 3)`

Then , the 'request' is ok!

Who can give me some tips?(my pouchdb is '5.3.2')

**Comment by daleharvey** [comment]
So if the webkit looks like Safari (which I think it does from the UA, we test @ https://github.com/pouchdb/pouchdb/blob/master/src/adapters/idb/index.js#L970) then it will actually be using WebSQL not IndexedDB, so you will likely want to verify which.

From the failure it sounds like it starts working then breaks? if so then the only thing I could think of is that it is using safaris broken indexeddb implementation, if its not that then I dont think there is much we can know without further debugging.

Closing this as its pretty certainly not a pouchdb bug but an environment issue, but if you think there are things we can help with please feel free to carry on posting in here, thanks
