### ISSUE TITLE
Feature request: handle rate limiting proxies 

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#5149]
I'd like to explore how PouchDB can better handle situations where the target server has some kind of rate limiting (usually a 402 or 429 response).

It might be that the back_off/retry functionality for live replications handles this already but rate limiting is a little different in that we would want to retry individual requests within a replication attempt (rather than fail the replication) and it would need to apply to non-live replications as well.

Another approach would be to plug something in at the ajax/requests level along the lines of https://github.com/FGRibreau/node-request-retry. Any thoughts on the design/approach would be very welcome. Also, if there are strong feelings around whether this should be in the core vs a plugin that would be good to know.

**Comment by willholley** [comment]
some relevant work in CouchDB - https://github.com/apache/couchdb-couch-replicator/pull/38

**Comment by daleharvey** [comment]
So I am not particularly for having retry logic done at the request level, its hard to show that to the user in any meaningful way and makes it fairly easy to hide errors, we already have retry code and I think its best any improvements go into the current code. `retry` should already handle this, it will count any `4xx` that isnt 403 as an error and retry, we do however definitely need to make retries work for non live replications, there is an existing issue open for that @ https://github.com/pouchdb/pouchdb/issues/4092

**Comment by daleharvey** [comment]
Since we already have a bug open for #4092 and it seems like that is the only thing we need to support rate limiting proxies, closing this out, cheers
