### ISSUE TITLE
Navigation is stuck over content

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#5161]
Reported by https://twitter.com/nekrtemplar

![](https://pbs.twimg.com/media/CibUjrlUoAAAZQ7.jpg)

Full twitter thread: https://twitter.com/nekrtemplar/status/731783145461297153

My suspicion is that Chrome Beta is behaving weird with the position: sticky polyfill.

**Comment by daleharvey** [comment]
Yeh I took a look at this, tried switching to another polyfill and seen the exact same problem, I can reproduce on chrome beta, I think the only option to fix is remove the polyfill

**Comment by daleharvey** [comment]
So yeh, its gonna be a while for chrome to support position sticky, will just have to hope chrome beta fixes this

**Comment by nolanlawson** [comment]
fixed in https://github.com/pouchdb/pouchdb/pull/5337
