### ISSUE TITLE
PouchDB + PouchDB Server incorrectly replicates _local documents

### ISSUE THREAD

**Issue by Ampakinetic** [pouchdb/pouchdb#5164]
I'm trying hard to solve a problem where PouchDB (talking to a PouchDB-express endpoint) goes into a massive loop trying to replicate _local documents (even though the docs say _local docs don't replicate) and I've added a replication filter to try and stop it but to no avail.

The requests come back with status 409 conflicted. Eventually the sync stops, after trying around 5000 times to sync 3 x _local docs. 

This problem didn't used to happen with earlier versions of Pouch and it's driving nuts trying to get the old functionality back.  Can someone give me some pointers as to where to look?  I'd be happy to provide further info as required.

I'm running 5.3.2 on both the server and the browser.

**Comment by nolanlawson** [comment]
That is really odd. Local documents should definitely not replicate.

Are you using pouchdb-server or express-pouchdb? Can you provide a small test case to reproduce? We have a pretty exhaustive test suite, and I don't think we've ever run into the issue where a _local doc tried to replicate, so if you can provide a test case, that would greatly improve the chances that we can identify and fix it.

**Comment by nolanlawson** [comment]
It would also help to know if you see this behavior in CouchDB as well, or if it only occurs in PouchDB Server.

**Comment by dharders** [comment]
@Ampakinetic this sounds very similar to an issue I had recently. 

Are you sure the _local docs are trying to sync()? This was my first thought when I saw ~10000 xhr requests (over a 2 minute loop before settling) with a doc _id of _localXXX. But closer inspection showed that this was just sync() doing its thing (ie trying to get the SERVER _localXXX docs to bring the 2 dbs in sync. 

However, a bug was found recently in replicateTo() which lead to similar behaviour that you are describing. #5167 and #5157. 

Check out PR #5180 for the one line change to try in your code to see if that fixes your issue.  

processPendingBatch(batches.length === 0 && changesOpts.live);

**Comment by nolanlawson** [comment]
FYI we are also tracking this issue in #5157, but currently we're not able to find a reproducible test case. Everybody says `processPendingBatch(batches.length === 0 && changesOpts.live);` fixes the issue, but we need a test to prove it...

**Comment by nolanlawson** [comment]
closing in favor of https://github.com/pouchdb/pouchdb/issues/5196, please move discussion over there
