### ISSUE TITLE
VOTE: scoped packages vs prefixed packages

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5165]
Breaking this out from #5162 to summarize the arguments and vote.

#### Pro-[scoped packages](https://www.npmjs.com/private-modules) (e.g. `@pouchdb/foo`)

* Don't have to manage npm owners across multiple packages
* Only we can publish `@pouchdb/foo`, communicates 1st-party vs 3rd-party
* Used by Angular2 and (soon) Hoodie
* We could lead the charge on scoped packages and appear more forward-thinking
* Prefixed might make us look antiquated in the future

#### Pro-prefixed packages (e.g. `pouchdb-foo`)

* `@pouchdb/foo` is unfamiliar and hard to type
* Scripts can manage multi-package owners for us anyway (https://github.com/lerna/lerna/issues/38#issuecomment-180593549)
* npm orgs aren't free for OSS yet, need to share one username and switch credentials when we publish (then upgrade to an org later when npm supports it)
* Prefixes are still more widespread – `ember-`, `react-`, `babel-`, `lodash.`, etc.
* Private modules break some non-npm tools – Artifactory, local-npm, Sinopia
* We already have lots of prefixed modules - `pouchdb-ajax`, `pouchdb-promise`, `pouchdb-server`, `express-pouchdb`, etc. Unclear whether to rename or retain; we'd probably end up with a mixed bag.
* **New**: Apparently you [can't search](https://twitter.com/ag_dubs/status/730808109237731328) for scoped packages in npmjs.com yet (compare [this page](https://www.npmjs.com/package/@nymag/dom) and [this page](https://www.npmjs.com/search?q=nymag+dom)).

Let's put it to a vote. Please give a :+1: to the one you want in the next two comments.

If I missed any arguments pro or against, please let me know and I'll edit this post.

**Comment by nolanlawson** [comment]
**Scoped packages**

**Comment by nolanlawson** [comment]
**Prefixed packages**

**Comment by nolanlawson** [comment]
My personal preference is to go with the simpler and known solution for now: prefixed packages. Swimming upstream is awkward and has unknown unknowns, and I just can't get over how much I like the idea of typing `npm install pouchdb-browser` compared to `npm install @pouchdb/browser`.

I doubt prefixed packages will ever make us look antiquated, because there are still ~250,000 packages using the older convention. If it ever gets so unfashionable we really hate it, we can switch over when npm supports free OSS orgs and then do a major version bump.

**Comment by bradley-holt** [comment]
@nolanlawson You said:
> Prefixed might make us look less antiquated in the future

Is this correct, or did you mean to instead say the following instead?
> Scoped might make us look less antiquated in the future

**Comment by nolanlawson** [comment]
Typo, fixed it.

**Comment by nolanlawson** [comment]
New con for scoped packages: apparently you can't search for them in npmjs.com yet.

**Comment by andrew** [comment]
Scoped packages don't show up in many of the npmjs.com apis or search making them hard for regular users to find.

**Comment by mikeal** [comment]
The standard that I've seen is that packages that are mostly only useful internally and aren't really meant to be much of a reusable component outside the project would use scoped package prefixes. Plugins or other modules that might be useful outside would be prefixed or just have a unique name.

**Comment by nolanlawson** [comment]
@mikeal That's interesting. Maybe we can use `@pouchdb/` for packages we intend to be private-ish (we will have a few such "util" modules in the new arch). The annoying part is switching npm credentials, but we could just publish everything using the `pouchdb` username.

**Comment by timoxley** [comment]
@mikeal that may just be that people are more comfortable experimenting with scopes when it's mainly for internal use.

**Comment by mikeal** [comment]
@timoxley I think it's also important to remember that scoped packages still *look* like they are internal, so if you want people to adopt the components without the entire package the name is part of the DX and expectations.
