### ISSUE TITLE
_bulk_get does not provide any noticeable performance for me. PouchDB 5.3.2 / CouchDB 2.0

### ISSUE THREAD

**Issue by dharders** [pouchdb/pouchdb#5167]
I've read great things about the new `_bulk_get` API endpoint, so I upgraded my CouchDB server from `1.6.1` to the `dev 2.0` branch to take advantage.

However, my tests so far have shown `sync() with 2.0` to be just as 'chatty' as 1.6.1.

My database has ~3000 docs (many 1st revision). When I `sync()` for the **first** time, there are approx **10,000** xhr requests **using v1.6.1** before my chrome dev network tab settles (very chatty!).

Using the new v2.0 branch, first time `sync()` takes approximately...**9,500** xhr requests before settling (not much of an improvement, and negligible time difference to v1.6.1).

Closer inspection of the network activity shows that the `_bulk_get` endpoint is reached (quite early), just after an _all_docs response returned ~3000 docs in one go. So I get my data pretty quick (~5 seconds), but then...

The next ~9500 xhr requests are a repetition of these 3 over and over:

- GET http://192.168.1.190:5984/testdb/_local/Tl02KOzWrRiwlIunoChEhw%3D%3D?
- POST http://192.168.1.190:5984/testdb/_bulk_docs
- POST http://192.168.1.190:5984/testdb/_revs_diff

... with increasing rev 0-1, rev 0-2, rev 0-3..., taking approx 2 mins to complete.

**Q: Is this expected behaviour ? Or is there a bug with sync() ?**

I seem to have my data straight away, but the repeating GET, POST, POST seems very inefficient. For a {live: true} sync, it also **prevents any changes being replicated OUT (to server)**, until the entire ~9500 GET, POST, POST dance is finished. So essentially data changes are not propagated to other connected users for the first 2 minutes, which is frustrating. Data changes IN (from server) still appear immediately, as expected, while the dance is happening! 

Strangely, I've also noticed that if I change some data then refresh my page before the 2 minute GET, POST, POST dance is complete, the changes are pushed out immediately to other connected users and there is no background G.P.P dance beginning again, and all my data seems to be synced.?

More background:

`var localDB = new PouchDB('testdb', {revs_limit: 100, adapter: 'websql', auto_compaction: true});
 localDB.sync('http://192.168.1.190:5984/testdb', {
                live: true,
                retry: true,
                batch_size: 10000
            })...
`
PouchDB 5.3.2
CouchDB 2.0@dev (and 1.6.1)
Tested with Chrome v50.0.2661.102 m Win7 and Safari iPad OS 9.2.1

**Comment by dharders** [comment]
Some progress...

I swapped out `PouchDB 5.3.2` for an earlier version (`PouchDB 5.2.0`) and found the undesired behaviour to disappear.

`PouchDB 5.2.0` is the latest version I could find that **does not** suffer from the long GET, POST, POST dance. With the same database as above, `sync()` with CouchDB 1.6.1 completes after ~630 xhr requests. `sync()` with  CouchDB 2.0 completes after only **85** xhr requests!

(so the _bulk_get performance improvement is definitely evident in this version of PouchDB )

So something **was introduced in PouchDB 5.2.1** and is still present in the latest version (5.3.2 at this time of writing) that significantly degrades sync performance.

I'm trying to narrow down this bug by looking at the source code now, but a lot of it is over my head. 

Anyone keen to chime in ?

**Comment by dharders** [comment]
OK, I think I have found the offending line of code:  [commit f3a72...](https://github.com/pouchdb/pouchdb/commit/f3a72ea84c951a815f8dd7a002fb11aa17b82543)

**src/replicate/replicate.js** LINE 278

`processPendingBatch(changesOpts.live);`
should be
`processPendingBatch(batches.length === 0);`

as it was back in PouchDB 5.2.0.

I don't know the ramifications of changing this, or the reasons it was changed to begin with, but it indeed fixes my sync() performance with the latest `Pouch 5.3.2`. 

Any PouchDB guru's care to comment ?

**Comment by sballesteros** [comment]
I think that there is a PR related to that: https://github.com/pouchdb/pouchdb/pull/5157

**Comment by dharders** [comment]
Thanks, I just noticed it too. Your comment came through just as I was commenting on it.

Hopefully they can get a fix for the current test failures. I'll leave this issue open still, as someone may have a better solution or provide a valid reason for keeping the `changesOpts.live` code.

**Comment by dharders** [comment]
Actually, I think the new code should be:

`processPendingBatch(batches.length === 0 && changesOpts.live);`

to satisfy `processPendingBatch(false)` needed for **non**-continuous replications (PR #4753).

@bbenezech Since you were the original author of PR #4753 and have a deeper understanding of the reasoning behind your changes, can you please comment on the validity of my suggestion ?

(further discussion here #5157 if it helps ! )

**Comment by nolanlawson** [comment]
@dharders It does indeed seem that https://github.com/pouchdb/pouchdb/pull/5157 fixes the issue. As for reducing chattiness with `_bulk_get`, you could also try increasing the batch size.

**Comment by dharders** [comment]
Thanks for the tip @nolanlawson ! Yes, increasing the batch size does definitely reduce chattiness I've found in my tests. (although, this particular example already had `batch_size: 10000` with a DB of only ~3000 docs, so they were all gobbled up in one request!)

The title of this issue is somewhat misleading now that we have (hopefully) fixed the replicateTo() performance regression bug.

With the fix `processPendingBatch(batches.length === 0 && changesOpts.live);` in place, **I definitely do see a performance improvement** (in xhr request reduction).

I noticed you created a PR #5180 with my suggestion and are currently waiting for Travis test results. If all is good with the tests, I'm happy to close this issue, as I do see a performance improvement with _bulk_get with this fix in place!

**Comment by dharders** [comment]
Looks like the Travis tests have passed successfully for your PR #5180  @nolanlawson 

Good to close this issue, or wait until merge ?

**Comment by nickcolley** [comment]
@dharders looks like there needs to be a failing test to be added to the PR before it can land, so I'd just leave this open until then and we can close it out for you.

Thanks again for your contributions 👍  😄

**Comment by daleharvey** [comment]
And landed
