### ISSUE TITLE
one-direction sync makes unexpected POST request to end-point

### ISSUE THREAD

**Issue by cdaringe** [pouchdb/pouchdb#5169]
hi all:

i have a db set to sync in one direction, remote-to-local.  that is, it's download only!  to enforce that the sync happens in only one direction (and that some naughty hacker doesn't mess with my db configuration), i even route all my pouchdb traffic through a proxy and make sure that only GETs happen from the client!

however, check out the network activity i see _from the client_:

```js
post /coinstacdb/down/computations/_bulk_docs {} 404 (23ms)
get /coinstacdb/down/computations/_changes {"timeout":"25000","style":"all_docs","heartbeat":"5000","since":"1","limit":"100"} 200 (8ms)
get /coinstacdb/down/computations {} 200 (12ms)
```

it does a *post*!  is that _expected_? perhaps that's a requirement of `couchdb`.  anyway, this is not a bug report, just a help request.  you guys rock.

thanks

**Comment by daleharvey** [comment]
During replication PouchDB will try to write `_local` documents to store a checkpoint of replication progress, it should fallback ok if that request fails

**Comment by cdaringe** [comment]
hmm.  interesting.  in this case, its `POST db/_bulk_docs`'ing when being asked to replicate down.  seems to still work OK, but it does seem _odd_ that it would even try a POST vs just the `GET` which follows immediately after.

**Comment by daleharvey** [comment]
We try to store the checkpoints on both sides of the replication, source and target, it helps reliability. Gonna close this out but if you have any more questions feel free
