### ISSUE TITLE
[Warning] ArrayBuffer is deprecated in XMLHttpRequest.send(). Use ArrayBufferView instead

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5174]
Seeing this in safari tech preview @ https://github.com/pouchdb/pouchdb/blob/master/src/deps/ajax/request-browser.js#L211

**Comment by nolanlawson** [comment]
That's really annoying. I'd prefer to use `'blob'`, but that breaks in pre-4.4 Android.

**Comment by nolanlawson** [comment]
I'm wondering if we can safely using `arraybufferview` or if that will cause bugs in older browsers. Unfortunately this would need to be tested in pre-4.4 Android manually because SauceLabs doesn't have any (usable) pre-4.4 emulators.
