### ISSUE TITLE
Attachments empty after storing in Android

### ISSUE THREAD

**Issue by RonCan** [pouchdb/pouchdb#5175]
I'm using the following code to persist docs with attachments:

```js
      for (var i = 0; i < results.length; i++) {
        blobUtil.imgSrcToBlob(results[i]).then(this.gotBlob).catch(function (err) {
          // image failed to load
        });
        // console.log('Image URI: ' + results[i]);
      }

   //gotBlob func
  gotBlob(blob) {
    var text = "";
    var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    for( var i=0; i < 7; i++ )
    text += possible.charAt(Math.floor(Math.random() * possible.length));

    this.claim._attachments[text+".png"] = {
      content_type: blob.type,
      data: blob
    }
    // ladies and gents, we have a blob
    this.photos.push(blobUtil.createObjectURL(blob));
    console.log(this.photos);
  }

   // Built the claim object with attachments, now persist

    return this._db.post(claim);
```
I can see the claim object with attachments before persisting but after I persist and retrieve using

`return this._db.allDocs({ include_docs: true, attachments: true})`

I can see the _attachments key but it's empty, what am I doing wrong?

EDIT 1: I'm using the SQLite-Plugin-2

**Comment by nolanlawson** [comment]
Is there any chance you could provide a small test case to reproduce? It would also be helpful to know if this occurs only with the SQLite Plugin 2, or if it also occurs if you switch to regular WebSQL (i.e. uninstall the SQLite Plugin 2).

**Comment by nolanlawson** [comment]
Oh, and is this iOS or Android? Which version?

**Comment by daleharvey** [comment]
We have android tested in CI and passing, we would need more information to debug this. If you are still seeing an error and can give us more information then please reopen with str and we will take a look. thanks
