### ISSUE TITLE
PouchDB incompatible with Latest Electron version which runs on Node 6.1

### ISSUE THREAD

**Issue by singhshashi** [pouchdb/pouchdb#5176]
I tried PouchDB with the latest version of Electron (1.1.0) which use Node 6.1 and it seems it is incompatible with it. Just getting a db.info() throws the error "Module version mismatch: Expected 48 got 47" 

You can see what I did at https://youtu.be/R0aVXmJ8B7o?t=154

**Comment by nolanlawson** [comment]
Did you follow the steps described in https://github.com/nolanlawson/pouchdb-electron ? Most importantly, did you rebuild leveldown for Electron?

If so, then yeah, this is definitely a bug.

**Comment by singhshashi** [comment]
No, let me do that and report back. However, in my electron project I was able to use pouchdb without following that step. This was happening when I was using Electron v0.36 and I was using pouch in the renderer process and not the main process, so I guess not in the node context.

**Comment by nolanlawson** [comment]
You always have to rebuild leveldown if you want to use PouchDB in the node context (in the browser context there's no need to build anything).

**Comment by singhshashi** [comment]
Well, that makes sense. Then this does seem like a bug, because pouchdb throws the error when used in the browser context, as you can see towards the end of the video that I made. Looking at the source, I see that require('leveldown') is throwing this error. Let me dig a little deeper and see if I can do anything to resolve this.

**Comment by singhshashi** [comment]
Ok. While I was using pouchdb in the renderer process, it was using the leveldb adapter, probably because instead of referencing a pouchdb.js in a webpage, I was requiring the pouchdb in a separate file in my react app. Following the postinstall steps that you have described at https://github.com/nolanlawson/pouchdb-electron for the latest version of electron, helped resolve the issue as I am not getting the error anymore. So I guess this is not really a bug.
