### ISSUE TITLE
iOS, block application while opening database

### ISSUE THREAD

**Issue by rberthome** [pouchdb/pouchdb#5183]
Hi, 

I'm working on an ionic app, I use PouchDB to store my data in order to have an offline mode. 
I'm currently having trouble with the iOS version. 

When I open my dataBase with this command : 

>  `
> new PouchDB('XXXXXXDB', {adapter : 'websql', auto_compaction : true, revs_limit : 1, location:'default', iosDatabaseLocation:'default'})
> `

I have this in my logs : 

> `
>  2016-05-20 18:14:47.225 SGNews[6944:187465] OPEN database: _pouch_laMatinaleDB
>  2016-05-20 18:14:47.225 SGNews[6944:187465] new transaction is waiting for open operation
>  2016-05-20 18:14:47.227 SGNews[6944:187495] Good news: SQLite is thread safe!
>  2016-05-20 18:14:47.230 SGNews[6944:187465] DB opened: _pouch_laMatinaleDB
> `

This is telling me that the database was opened, but I have no return from the promise. This makes my app blocked, even my spinner is not moving.

To reproduce this issue, I open and close my app until I get it. 

I know that is a pretty awful way, but some people who use it normally have the same problem. 

I use the 5.3.2 release version. (Everything is great on Android)

**Comment by nolanlawson** [comment]
It appears you are using SQLite Plugin (aka SQLite Storage). We do not officially support it due to bugs.

You may want to try my SQLite Plugin 2 instead: https://github.com/nolanlawson/cordova-plugin-sqlite-2

Let me know if that helps. If not, I recommend filing an issue on SQLite Storage.

**Comment by rberthome** [comment]
I got an answer from issue for Cordova-sqlite-storage I use. ([Cordova-sqlite-storage issue opened](https://github.com/litehelpers/Cordova-sqlite-storage/issues/482#issuecomment-224029268))

They told me to look after  **location** and **iosDatabaseLocation** options. After reading more about it, I found that location for iOS is still available even if it's deprecated. So, I think there is some troubles when you set **location** and **iosDatabaseLocation** in the same options. I did this in order to not have to test the platform an just have one line of code for opening my database.

After I separate the **location** and **iosDatabaseLocation**, it seems to be great.
