### ISSUE TITLE
web_sql_went_bad error on Chrome in iOS

### ISSUE THREAD

**Issue by capesean** [pouchdb/pouchdb#5197]
### Chrome on iOS

When I create a new PouchDB in iOS I can't use it. If I inspect the object, I see i t has `status: 500` with `name: web_sql_went_bad`, `message: unknown` and `reason: SecurityError`. Is this a known issue?

Here's a demo: https://jsfiddle.net/98at8jt9/

**Comment by nolanlawson** [comment]
Vanilla PouchDB currently does not support Chrome/Firefox/Opera on iOS due to WKWebView bugs (see https://github.com/pouchdb/pouchdb/issues/5079 for details). The workaround is to use the `fruitdown` adapter or fallback to in-memory or http.

**Comment by nolanlawson** [comment]
OTOH we should probably detect WebSQL as invalid instead of throwing a runtime error when you try to use WebSQL.

**Comment by nolanlawson** [comment]
See: https://github.com/pouchdb/pouchdb/pull/5198

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/f3a7a1633455bd7095d238baf50c510c0f20a768
