### ISSUE TITLE
clone function doesn't properly handle webworkers/serviceworkers

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5200]
I'm trying to add an API to worker-pouch like so:

```js
var db = new PouchDB('name', {
  adapter: 'worker',
  worker: new Worker('worker.js')
});
```

This would allow users to use their own WebWorker/ServiceWorker with worker-pouch. Unfortunately I can't, because the clone() algorithm isn't smart enough to leave workers alone, and instead tries to clone them.

I propose adding a check for simple objects. We used to do this, and I'm not sure why we removed it.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/pull/5201
