### ISSUE TITLE
Node 6 is causing Security context: 0x8de4eac9fa9 <JS Object>#0# error

### ISSUE THREAD

**Issue by aaronmcohen** [pouchdb/pouchdb#5202]
## Environment 

node 6.2 on Linux (Fedora and Ubuntu)

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

LevelDB

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

PouchDB and CouchDB Server

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

Steps to reproduce:
1. nvm install 6.2
2. npm install pouchdb pouchdb-upsert
3. const PouchDB = require('pouchdb');
4, PouchDB.plugin(require('pouchdb-upsert'));
5. const db = new PouchDB('test');

Result:

````
==== C stack trace ===============================

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: leveldown::Batch::Init()
 3: leveldown::Init(v8::Local<v8::Object>)
 4: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: 0x9a998b
 7: 0x9a9f31
 8: 0x7257f0961b
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x8de4eac9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x7258940864] (this=0x18b2155eab21 <an Object with map 0x98a27e75c21>#1#,module=0x38a741cd3881 <a Module with map 0x98a27e17e49>#2#,filename=0x38a741cd3859 <String[103]: node_modules/leveldown/build/Release/leveldown.node>)
````

**Comment by daleharvey** [comment]
Thanks for the report, this is fixed in https://github.com/pouchdb/pouchdb/commit/d72ede4ff769d0170980dfd8cdc9a6b714e69c60 and we will be doing a release shortly so updating when that happen will get rid of the deprecation warnings

**Comment by cdaringe** [comment]
thanks @daleharvey!  appreciate the quick follow up!  i don't mean to pester, however, can you clarify if i should expect hours/days/weeks for the upcoming release?

**Comment by nolanlawson** [comment]
We typically do releases on the first Monday of the month, so 5.4.0 should arrive by June 6th.
