### ISSUE TITLE
npm test -> change file -> npm test flow broken

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5203]
Just away to go to bed, however was looking at doing a PR, I changed some code in `packages/pouchdb-adapter-leveldb-core/src/index.js` then reran npm test and got the same failure, looking at the source it didnt pick up my changes, I would expect npm test to deal with that and rebuild as necessary

**Comment by nolanlawson** [comment]
I'll fix this.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/327f677ec8a24ca477af0f4af8d58e93851e5131
