### ISSUE TITLE
Deleting an attachment doesn't work

### ISSUE THREAD

**Issue by ajithmjose** [pouchdb/pouchdb#5221]
### Environment (Node.js/browser/hybrid app/etc.)

Angularjs & rest services based web application

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

IE11/Chrome/Firefox

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

IndexedDB

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

My backend is running on weblogic sever , it is exposed as a rest service to supply the data. 

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

Background:

In my web application I am able to store pdf and images as attachment using pouchdb into the underlying in-browser database.

Issue:

When I try to delete the stored attachment then the 'removeAttachment' function doesn't seem to work. The attachment data is still available within the IndexedDB and it never gets deleted and my application can still access it. 

My code to delete the attachment is below:
 
db.removeAttachment(id, attachmentTitle, rev)
   .then(function(){})
   .catch(function (err) {
          console.log(err);
    });

Any clue why the remove Attachment doesn't work. I have no issues in creating an attachment or reading an attachment.

**Comment by daleharvey** [comment]
@ajithmjose We have tests covering `removeAttachment` and they are all working fine, could you provide any more information as to why this is failing for you? is your document in conflict at all? are you seeing any errors when trying to delete the attachment?

Here is a test case I wrote (runnable @ http://paste.pouchdb.com/paste/tz8svs/) and I cant see this failing

```
    var db = new PouchDB('testing_' + Date.now());
    var file = {content_type: 'text/plain', data: 'TXl0ZXh0MQ=='};
    var doc = {_id: 'mydoc', foo: 'bar', _attachments: {'mytext': file}};
    db.put(doc).then(function (res) { 
      return db.removeAttachment('mydoc', 'mytext', res.rev);
    }).then(function () { 
      return db.get('mydoc', {attachments: true});
    }).then(function (doc) { 
      console.log(doc);
    });
```

Cheers
Dale

**Comment by daleharvey** [comment]
`removeAttachment` is most definitely working so its sounds like either an edge case or something wrong in your application code, either way we cant look into anything without further details. Hopefully you have found a fix in your code, if you are still seeing issues with pouchdb then please reopen with more details / ideally a failing case, otherwise closing out, thank you
