### ISSUE TITLE
[Q] PouchDB + Cordova + IOS + live Sync => UIBackgroundModes key for APP STORE

### ISSUE THREAD

**Issue by ronyrun** [pouchdb/pouchdb#5222]
### Environment
PouchDB + Cordova hybrid app + IOS + live Pouch Sync

### platform 
Cordova hybrid app 

### UIBackgroundModes key for APP STORE

Hello I implemented PouchDB on an IOS mobile APP with a Background plugin in order to let the PouchDB live Sync operate.

When uploading an hybrid mobile app for ITUNES / APP STORE.
We can define what background actions are used.

![image](https://cloud.githubusercontent.com/assets/7273443/15533562/72af0514-2265-11e6-84ae-88ca1c28a0e7.png)

Do we need to declare some "sync actions for the background mode here " ?

Thank you.

**Comment by daleharvey** [comment]
I think this is a question between cordova and the itunes store, I really dont think it has much do with pouchdb? Closing out although feel free to discuss in here more

**Comment by ronyrun** [comment]
Hello, it has with the Sync of PouchDB :)
I don't know about  the apple store acceptance on this point concerning sync on the Background Mode.
