### ISSUE TITLE
Rename pouchb-adapter-indexeddb to pouchdb-adapter-idb

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5224]
Based on discussion with @daleharvey I think the best move in terms of naming for the multi-package architecture would be to use `pouchdb-adapter-idb` for the current one, and `pouchdb-adapter-indexeddb` for the new one.

This would be nice because all the other adapters have a package name that matches their "adapter name" (i.e. what you see when you do `new PouchDB('foo').adapter`), except for `indexeddb` currently (which has an adapter name of `'idb'`). Since we haven't released this yet, we can still freely change the adapter name, so now is the time to make a decision.

I'm suggesting `pouchdb-adapter-idb` and `'idb'` for the old one and `pouchdb-adapter-indexeddb` and `'indexeddb'` for the new one (i.e. what we've called `idb-next`).

**Comment by nolanlawson** [comment]
The alternative is to call it something like `idb-next` or `idb2` which I think is ugly if we plan on maintaining the new one for the long term.

**Comment by daleharvey** [comment]
Im 👍 on that, will do the PR since I need to get used to this stuff

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/bf9ff55722b5ab6c756a9fb5ea6b8b33dae08958

**Comment by nolanlawson** [comment]
post facto :+1:
