### ISSUE TITLE
PouchDB throwing unhandled rejection on replicate in Node.js

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb#5238]
### Environment (Node.js/browser/hybrid app/etc.)

Node.js

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

N/A

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

LevelDB

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

None (really)

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

I was testing what would happen if I tried to issue a replicate.to pointed at a remote database that wasn't even listening for connections. I successfully received an error event (which in itself was odd since live: true but that's another issue) but my global process.on('unhandledRejection') handler in node still picked up a unhandled rejection! Just for chuckles I even added a catch which did catch the reject BUT I still get an unhandledRejection event!

```javascript
var PouchDB = require('pouchdb');

var dbPath = "foo";

var DefaultPouch = PouchDB.defaults({
  prefix: dbPath
});

process.on('unhandledRejection', function (err, p) {
  console.trace(err);
});

var badUrl = 'http://127.0.0.1:2342/db/foo';

var ajaxOptions = {
  live: true,
  retry: true,
  skip_setup: true
};

var remoteDB = new DefaultPouch(badUrl, ajaxOptions);
remoteDB.replicate.to('foo')
    .on('paused', function (err) {
      console.log('Got paused with ' + err);
    })
    .on('active', function () {
      console.log('Replication resumed');
    })
    .on('denied', function (err) {
      console.log('We got denied on a PouchDB access, this really should ' +
        'not happen - ' + err);
    })
    .on('complete', function (info) {
      console.log('complete - ' + info);
    })
    .on('error', function (err) {
      console.log('Got error on replication - ' + err);
    })
    .on('change', function (info) {
      console.log('change - ' + info);
    })
    .then(function (stuff) {
      console.log('then - '  + stuff);
    })
    .catch(function (err) {
      console.log('catch - ' + err);
    });
```

**Comment by yaronyg** [comment]
Thanks to the fantabulous bluebird longStackTraces (which I saw @nolanlawson use) I found the proximate source of the bug which is the promise call [here](https://github.com/pouchdb/pouchdb/blob/0e0fa45df87e7e5ab14601fd98260c09304f4582/packages/pouchdb-core/src/changes.js#L79). Which is odd because there is clearly a catch clause there (the second complete). I tried to disable that complete and sure enough the uncaught promise rejection went away.

I tried various variants on catch and they all get called (e.g. the catch is triggered) but the unhandled promise exception doesn't go away. :( So the problem doesn't seem so much to be the promise emitted by Changes as something that is triggered somewhere by that promise. I'll continue to investigate tomorrow.

**Comment by yaronyg** [comment]
The bug is caused by the catch handler [here](https://github.com/pouchdb/pouchdb/blob/0e0fa45df87e7e5ab14601fd98260c09304f4582/packages/pouchdb-core/src/changes.js#L81) who then calls complete which emits an error event [here](https://github.com/pouchdb/pouchdb/blob/0e0fa45df87e7e5ab14601fd98260c09304f4582/packages/pouchdb-core/src/changes.js#L35). The problem is that there is no listener for that error event which causes node.js, which treats events called 'error' specially, to throw an exception which is then caught by the promise framework who treats it as a reject and returns it back at the catch handler who, of course, doesn't have its own catch handler and so we get an unhandled promise rejection.

There are a bunch of ways to solve this bug:

Option 1 - We can wrap the contents of [this function](https://github.com/pouchdb/pouchdb/blob/0e0fa45df87e7e5ab14601fd98260c09304f4582/packages/pouchdb-core/src/changes.js#L33) in an 'if (callback)' thus skipping all the emits if there is no callback. This is based on the assumption that nobody else should be listening but the listeners [here](https://github.com/pouchdb/pouchdb/blob/0e0fa45df87e7e5ab14601fd98260c09304f4582/packages/pouchdb-core/src/changes.js#L42). But I'm not sure if that is intended.

Option 2 - We can wrap [this line](https://github.com/pouchdb/pouchdb/blob/0e0fa45df87e7e5ab14601fd98260c09304f4582/packages/pouchdb-core/src/changes.js#L35) in a check for listenersCount and if 0 then we can skip emitter error. This is probably the cleanest solution but it works one way in Node 10 and 12 and a different way in newer versions of Node. I can't say that I particularly like the idea of putting in Node.js version specific code. (This has to do to changes in listenerCount()).

Option 3 - We can wrap [this line](https://github.com/pouchdb/pouchdb/blob/0e0fa45df87e7e5ab14601fd98260c09304f4582/packages/pouchdb-core/src/changes.js#L35) (the same one as above) in a try catch and just swallow the exception. Seems... icky.

Option 4 - We can add an empty catch handler to [this promise](https://github.com/pouchdb/pouchdb/blob/0e0fa45df87e7e5ab14601fd98260c09304f4582/packages/pouchdb-core/src/changes.js#L81).

Option 5 - We can put an else on [this if](https://github.com/pouchdb/pouchdb/blob/0e0fa45df87e7e5ab14601fd98260c09304f4582/packages/pouchdb-core/src/changes.js#L42) that will set an empty event listener for error if there is no defined callback (which there isn't in this case).

Of all the options I think 5 is probably the cleanest since it's the easiest to understand. There is a potential for an error, there is potentially no listener for it, we don't want that, so we make sure there is a listener. Heck, we can event simplify 5 and skip the 'if' check and instead always register an empty error listener.

**Comment by daleharvey** [comment]
So https://nodejs.org/api/events.html#events_error_events

```
When an error occurs within an EventEmitter instance, the typical action is for an 'error' event to be emitted. These are treated as a special case within Node.js.

If an EventEmitter does not have at least one listener registered for the 'error' event, and an 'error' event is emitted, the error is thrown, a stack trace is printed, and the Node.js process exits.
```

**Comment by daleharvey** [comment]
Thanks for the thorough investigation. I think #2 is the cleanest option, its unfortunate that the api has changed but it should be fairly trivial to fallback and that code is one of the areas I am most worried about in terms of complexity, its really hard to understand or even follow the indirection of the callback / event flow and I am fairly worried about adding to it. an `if (hasListeners) { emit(....` is very clear whereas the options certainly seem less clear.

But if there are complexities in the implementation I am missing, feel free to PR whichever method you feel is best, thanks for looking into this

**Comment by yaronyg** [comment]
No problem. I'm happy to go with 2. But what should we do in the case that we aren't running in node at all (e.g. the browser)? I assume we should emit?

I'm also adding 
```Javascript
process.on('unhandledRejection', function (err) {
  console.error(err);
  throw err;
});
```
To node.setup.js and it does work (caught two tests that are emitting unhandled rejections) but in the test results only one test (4049 retry while starting offline) is marked as having failed even though I can see in the log that 3356 throw inside a filter is also failling. I'm not sure what's going on. Investigating.

**Comment by daleharvey** [comment]
If browserify is doing its job then I believe `self.listenerCount` should exist in the browser as well and we should use the same logic, I think we should only do something different if you run into problems

**Comment by daleharvey** [comment]
Yeh I can see 

```
EventEmitter.prototype.listenerCount = function(type) {
  if (this._events) {
    var evlistener = this._events[type];

    if (isFunction(evlistener))
      return 1;
    else if (evlistener)
      return evlistener.length;
  }
  return 0;
};

EventEmitter.listenerCount = function(emitter, type) {
  return emitter.listenerCount(type);
};
```
In pouchdb.js

**Comment by yaronyg** [comment]
Yeah, that is the new variant. So I'll stick in the logic that says that if it's old node use the old variant otherwise just use new for everyone else.

**Comment by daleharvey** [comment]
So ignore me if this was what you were planning anyway, but feature detection seem good here (over checking node versions etc) 

```
function listenerCount(ee, type) { 
  return 'listenerCount' in ee ? ee.listenerCount(type) : EventEmitter.listenerCount(ee, type);
}
```

**Comment by yaronyg** [comment]
In regards to test 3356 the problem is that if a promise manages to encompass two exceptions and has a catch handler then essentially one exception is 'lost' and the other gets turned by the promise framework into a rejection which is then caught by the promise catch handler. This is why even though test 3356 IS tripping unhandledRejection, Mocha doesn't see this as an error.

I have a work around but it's nasty. What I did was adding the following to node.setup.js:

```Javascript
process.on('unhandledRejection', function (err) {
  console.error('unhandledRejection: ' + err);
  throw err;
});

process.on('uncaughtException', function (err) {
  console.error('uncaughtException: ' + err);
  throw err;
});
```

The unhandledRejection handler catches the uncaught rejection and by throwing it will trigger the uncaughtException handler who then brings the whole process down and ends the test. Which is obviously kind of sucky since we would much rather just have mocha tell us the test has failed and continue. 

But since the whole point of sticking this into node.setup.js is to catch unhandled rejections where we aren't expecting them it isn't clear to me how to do better without some even nastier voodoo. For example, we could stick a global variable into each and every test and have the unhandledRejection handler call that global variable but um... yuck.

So is this hack acceptable or is there a nicer way to handle this mess?

**Comment by daleharvey** [comment]
oh sorry you were asking about how to test it before, sorry I thought you were investigating other uncaughtexceptions, can you write a test which attaches the exception handler at the start and cleans it up afterwards so it doesnt have side effects on other tests like so?

```
it('tests', function() { 

  function exceptionHandler() { 
    ....
    process.removeListener('uncaughtException', exceptionHandler);
    done();
  }
  process.on('uncaughtException', exceptionHandler);

**Comment by yaronyg** [comment]
That is fine for tests we expect to behave badly. But what I was trying to do was to catch tests that we didn't know were behaving badly. That's why I wanted to register unhandledRejection for *all* tests. Doing that, as I mentioned above, already helped me find two existing tests that are behaving badly. This is a general protection. The only complication is that in some cases (e.g. tests with catch in their main flow) the unhandledRejection will get swallowed (this is what happens with the test titled "3356 throw inside a filter") so that is why I needed to add the uncaughtException globally as well since it's the only way I know short of hooking every test to make sure that the unhandledRejection error can't be swallowed (and hence hidden) by the test itself.

I suppose we could have a rule that says that any test which has a catch MUST set (and then unset) uncaughtException but that is going to be an extremely brittle rule that is likely to be forgotten. Where as by setting the global handlers we don't depend on anything doing anything right to find these kinds of bugs.

**Comment by daleharvey** [comment]
So last time I looked at this there was complications around the fact that I believe mocha has some of its own code that interferes with this, however making sure our tests dont hide uncaught exceptions is a seperate issue of fixing this one we know we are throwing so want to open a new bug about it and we can discuss in there? cheers

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/48692ce7b72017420caa780d52e5f8fe703a3eac
