### ISSUE TITLE
Slow Sync with cloudant in IONIC2, Angular2 Project

### ISSUE THREAD

**Issue by ralph-fuechtenkort** [pouchdb/pouchdb#5248]
### Environment (Node.js/browser/hybrid app/etc.)

IONIC2.beta7 (Angular2.rc1) on Chrome, Android 5.1  and IOS 9.3
### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

s.a.
### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

WebSql at IOS, Chrome, IndexedDb at Android
### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

PouchDb and Cloudant shared server
### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

I experience very slow sync, especially on Android for some databases. Actually the databases only contain a few (5-10) documents now. Is it possible that indexes have an influence on the sync behave? On one database i needed 10 index to allow filters for the user (usingPouchdb.find). I use standard settings but increased timout to 60,000 already as our connection here in PH ist not that good usually.  The doc sizes of the affected type is 5k. Using the debug mode and some console logs i saw:
1. after initial sync the paused evet is called
2. i receive still Error timeout events
I have the feeling that the sync works better on IOS than on Android but that maybe just a feeling.

I have no idea how to prceed drilling down the problem. Any help appreciated.
Thanks in advance

**Comment by nolanlawson** [comment]
Indexes don't influence sync. How slow exactly are we talking? BTW slow replication is a known issue, and will be fixed with _bulk_get which is slowly being rolled out on Cloudant. You can also try pouchdb-load or socket-pouch for a faster solution. Another fix is to use a proxy to avoid CORS because CORS necessarily adds overhead.

**Comment by ralph-fuechtenkort** [comment]
Hi,
thanks for the amazing fast answer :)
I would say it can take up to an hour. I am not sure but i have the feeling that sometimes its only syncing on app new start. When exactly does the paused event occur and when should it be automatically resumed?
Thanks and Greets

**Comment by daleharvey** [comment]
The `paused` event fires during a `live: true` replication either when the replication has finished processing all current documents and is waiting for new changes, or when the server is currently inaccessible (when you go offline) and is waiting for a reconnection to resume

**Comment by ralph-fuechtenkort** [comment]
Thanks for the answer, i guessed already. It seems to work great now.

**Comment by cquillen2003** [comment]
I am having the same issue building an Ionic 2 app with Cloudant and PouchDB.  Syncing a small Cloudant DB is taking 4-5 minutes or longer.

Also, it appears something else is wrong.  Even after the "paused" event fires, there are network requests still firing rapidly.  About 2-3/second to _bulk_docs and _revs_diff, but none to _changes.  So, after about 10 minutes or so, my app has created over 10,000 requests and transferred more than 10 MB.

**Comment by colinskow** [comment]
I have no idea how Ionic2 would possibly interfere with PouchDB replication. The first step would be to run a benchmark from inside Ionic and also outside (on the same hardware/connection) to see if it makes a difference.

**Comment by baststar** [comment]
@cquillen2003 @colinskow same with ionic1/superlogin/no cloudand.

**Comment by colinskow** [comment]
@baststar https://github.com/nolanlawson/pouchdb-replication-stream in my benchmarks speeds up initial replication quite a bit.

**Comment by dharders** [comment]
@cquillen2003  What version of PouchDB are you using?  

That sounds similar to an issue I was having (#5196) , but was fixed in 5.4.0 via #5199. If you're using 5.4+ then I'm not sure.
