### ISSUE TITLE
Deprecate new PouchDB('name', function() or new PouchDB().then

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5251]
These are broken (at least .then is, by design) and havent been documented nor recommended for a long time, they are also a source of large complexity in the codebase so I think its time to get rid of them.

Given their undocumented status and that we tell people to not use them I would usually just rip them out and not regard it as a breaking change, however I still see the occasional code that does use it. So I think we should put in a deprecation notice (prior to the release) then take them out after

**Comment by marten-de-vries** [comment]
Note: if/when this happens, [this hack in express-pouchdb](https://github.com/pouchdb/express-pouchdb/blob/master/lib/db-wrapper.js#L28) can be removed. And I'd probably need to check pouchdb-wrappers behaviour.

**Comment by daleharvey** [comment]
Will wait for https://github.com/pouchdb/pouchdb/pull/5236 to land then put in the deprecation notice

**Comment by nolanlawson** [comment]
fixed in https://github.com/pouchdb/pouchdb/pull/5319
