### ISSUE TITLE
Lerna not correctly installing leveldown optionalDependency

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb#5257]
The current testing instructions defined [here](https://github.com/pouchdb/pouchdb/blob/master/TESTING.md) could be made more friendly through the addition of two bits of information in the node.js section:

1. Start with npm install
2. Then 'npm install leveldown' so the tests will 'just work'

**Comment by daleharvey** [comment]
Yeh I have had to do this a couple of times but not all the time which was weird. I thought it was something `lerna` should take care of however `npm install` is all that should need for the tests to just work, either leveldown needs added to the root package.json or if its supposed to be picked up already we should figure out why it isnt

**Comment by yaronyg** [comment]
I just ran a clean test on my mac and I got an error that leveldown wasn't there. Leveldown is also not in the package.json. I thought of adding it as a dev dependency but I wasn't sure if that was even strictly true since there are other adapters the tests can run on. That's why I thought it would be easiest to just make it an instruction so that those who know they are doing something fancy can do that without having to deal with downloading something like leveldown.

**Comment by daleharvey** [comment]
So I think it would be good to hear what @nolanlawson thinks since he made that change, but I would very much prefer to make the flow for new / general contributors as easy as possible than having optimisations for niche use cases

**Comment by nolanlawson** [comment]
I have no idea why leveldown wouldn't be installed correctly. My guess is that it has to do with leveldown being an optional dependency in the `pouchdb` repo, but I'm not sure.

FWIW I have never run into this problem and I don't see why `leveldown` would need to be installed at the root level. However it is true that you need to `npm install` first; that's pretty standard with any Node project but could use documenting.

**Comment by yaronyg** [comment]
Repo:
1. Have a clean directory with no node_module directories anywhere upstream of it, probably a good idea to also run 'npm list -g leveldown' to make sure leveldown isn't installed globally.
2. 'git clone https://github.com/pouchdb/pouchdb.git'
3. cd pouchdb
4. npm install
5. npm run build
6. npm run test

Expected result: Tests run
Actual result: The tests fail at 'test.all_docs.js-local Testing all docs' because 'the 'leveldown' package is not available.'

Expected Result: Tests run
Actual Result: The tests fail after running 24 of them on the test "test.all_docs.js-local Testing all docs' with the error that the leveldown package is not available.

This makes sense as the root package.json doesn't contain leveldown.

The Lerna point is interesting. I am new to Lerna but I would have expected it to have edited the package.json after being run in bootstrap but nothing seemed to change.

**Comment by daleharvey** [comment]
> This makes sense as the root package.json doesn't contain leveldown.

The tests pick up pouchdb from `test/utils.js` @ https://github.com/pouchdb/pouchdb/blob/master/tests/integration/utils.js#L329, that points to `packages/pouchdb` which has a leveldown dep @ https://github.com/pouchdb/pouchdb/blob/master/packages/pouchdb/package.json

This is also working in CI with no additional `npm install leveldown`, I feel like this may be a similiar to the problem I was seeing with websql installs, still looking into it

**Comment by daleharvey** [comment]
An yeh, I just did a complete clean build and it worked as expected, I have seen this bug as well a bunch of times but just dont understand whats happening

**Comment by yaronyg** [comment]
@daleharvey Just to be clear, is the expected result that the package.json in the root of the project would be re-written by lerna to include all the dependencies from the child packages?

**Comment by daleharvey** [comment]
No, `npm prepublish` calls` npm build` which calls `lerna bootstrap`, `lerna bootstrap` will install the dependencies of sub packages - https://github.com/lerna/lerna#bootstrap

**Comment by thejameskyle** [comment]
@daleharvey This the leveldown dep? https://github.com/pouchdb/pouchdb/blob/master/packages/pouchdb-adapter-leveldb/package.json#L17

**Comment by thejameskyle** [comment]
Oooh, its this issue again https://github.com/lerna/lerna/issues/121

**Comment by daleharvey** [comment]
So I havent seen this in a while, I very occasionally get the leveldown version mismatch, but not it failing to install entirely

**Comment by nolanlawson** [comment]
I've still never seen this. Then again I use Node 5 as my default and rarely change it, maybe that could have something to do with it?

**Comment by daleharvey** [comment]
I have been on node5 the whole time as well, lets close it out and hope it was a glitch in the transition

**Comment by yaronyg** [comment]
For those running into similar problems I don't get a repro when I use node 6 and apparently @daleharvey and @nolanlawson are using node 5 and not having a problem. So this appears to just be an issue for node 4. So um... don't use node 4.
