### ISSUE TITLE
Need to detect unhandled rejections in tests

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb#5260]
# Problem
Bug #5238 wasn't detected because we do not have any general mechanism for telling when we have unhandled rejections. 

# How to solve it?
We can put a process.on('unhandledRejection') handler into node.setup.js which would then apply to all the node tests. In really simple cases this can work. The unhandledRejection handler just throws an exception, this gets picked up by Mocha who then marks the test as failed. This is what happened with the test '4049 retry while starting offfline' before we fixed #5238.

The problem is that some tests are explicitly testing exceptions and using catch. Unfortunately if two exceptions are thrown at the same time one gets hidden. So if we have an (expected) exception in the test which, in the process of handling that exception should have an unhandled rejection then the unhandledRejection handler will catch it but when it throws the new exception will be caught by the promise framework along with the old one and both will be turned into a single failure that is then caught by the test which 'passes' since it was expecting an exception. An example of this behavior is the test '3356 throw inside a filter' (again, before #5238 was fixed).

There is a fix but it's ugly. We can also add a 'uncaughtException' handler. When the unhandledRejection throwsthis will trigger uncaughtException. If uncaughtException throws that will kill everything. This approach worked to detect the issue with 3356 above. But the downside is that when this mechanism is tripped that's it, the entire test run is over. Ideally we would have a way to communicate with Mocha what is going on, mark the test as failed and then move on.

But how can we do that without requiring us to mark up each and every test so that some global variable gets set that the handlers can trip and that the test would then pick up?

**Comment by daleharvey** [comment]
I believe a way we could do this is have a global uncaught exception handler, but in tests that are specifically testing uncaughtexception we remove the global handler, use our own, then restore it at the end of the tests, this could likely even be combine with registering our own handler

```
it('tests', function(done) { 
  testUtils.registerUncaughtListener(myFun);
  .... do test
  testUtils.removeUncaughtListener(myFun);
  done();
});
```

Where `registerUncaughtListener` handles the removal of the global listener and `removeUncaughtListener` readds it, would something like that work?

**Comment by yaronyg** [comment]
When would we ever have a test that was intentionally trying to produce an unhandled rejection? It's like having a test showing that we reliably produce a null pointer exception. :) It sorta defeats the point. So my guess is that we can just register the global handlers and call it a day. But we still have to decide if we are o.k. with the tests completely failing in the case that an unhandled rejection is detected. Working around that would require us to hook directly into the test framework.

**Comment by daleharvey** [comment]
I am totally ok with the tests halting if we hit some unwanted assertion that we are hoping to never actually hit

**Comment by yaronyg** [comment]
Okee dokee. In that case I feel a PR coming on. Note that we don't need to do any special work for individual tests that want to use the unhandled rejection event since anyone can use testUtils as you showed above to register and then unregister.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/b9ad08279812ab14f017873cae712ae02ba3fd76
