### ISSUE TITLE
bulkDocs times out if trying to update more than 25 docs

### ISSUE THREAD

**Issue by RonCan** [pouchdb/pouchdb#5261]
### Environment (Node.js/browser/hybrid app/etc.)

Node.js

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Chrome

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

N/A

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

Cloudant

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

If I try to update more than 25 docs in a single go with bulkDocs, everything starts timing out using

`var db = new PouchDB(config.CouchDBRoot,{ajax: {timeout: 20000}});`

If I do 5-10 everything works fine but as soon as I go above that things become predictable with more calls timing out. I'm running pouchdb@5.3.2

**Comment by willholley** [comment]
The most likely thing is that your timeouts are legitimate - probably a combination of large documents and high latency to Cloudant. Have you tried moving your Cloudant account to a cluster closer to you? Is there a problem with PouchDB that results from the timeouts?

**Comment by daleharvey** [comment]
Yeh if you are doing a bulkDocs request to a live server, we are just sending a HTTP request and if its times out there isnt really anything we can do about it, feel free to carry on conversation in here but it doesnt sound like a pouchdb bug so closing out

**Comment by RonCan** [comment]
Yeah the time out comes from `request` module. Is there anything like a reasonable timeout? I tried with `200 seconds` it still times out. Do I have to do it on hit and trial?
