### ISSUE TITLE
Add option to replicator to ignore deletions

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5263]

**Comment by colinskow** [comment]
How would this work technically @daleharvey ?

**Comment by daleharvey** [comment]
I have pinged the CouchDB mailing list about this, I have some preliminary ideas

> I would like to add an option to PouchDB replication that only replicates
> the currently active documents but still handles deletions properly, so
> basically implementing a filter that ignored any deleted doc with the
> ability to pass in a query parameter that is the update_seq at the time the
> replication started so deletions after the replication started are still
> passed. The idea is that deletions that happen before the replications
> start are not transfered, but docs after that all operate as normal.
> 
> One possibility is that PouchDB can write a design document with the filter
> and deal with all this itself, thats some extra complexity with the
> downside of how slow filters are. Another is that PouchDB can do this
> filtering client side, while we would still be transferring data we dont
> need, ignoring them coming out of the changes feed is hugely cheaper than
> fully processing them.
> 
> However having something built in on the couch side would be a nice bonus
> here, would this be covered by the functionality mentioned here?

**Comment by daleharvey** [comment]
So I am thinking, 1. I dont want to do automated design doc handling, ie `.sync(url, {deletions: false})` would automatically create a design doc with the deleted filter we want and users that. it just sounds like a nightmare.

If we do the filtering in the replicator its fairly trivial implementation wise and will still likely be a significant impact performance wise, we will need to pull down a bunch of changes that we dont need but that isnt the major cost of replication, if we end up getting an in built filter provided by couchdb for this then its also possible that we can be forwards compatible and just add the filter param to the replication.

**Comment by daleharvey** [comment]
Also ideally I would like to get our performance tests doing something more before working on this

**Comment by willholley** [comment]
CouchDB 2.0 supports ad-hoc filtering of _changes via query selectors which works around the ddoc requirement. However, I can't think of a way to implement this behaviour on the client in a world without incremental / collatable sequence numbers using the standard replication algorithm.

Maybe we could use an alternative replication strategy which uses a combination of _all_docs (or a query) to get historical non-deleted data + a live _changes reader to get change from 'now' (cc @glynnbird @bradley-holt)

**Comment by iAmAnkeeta** [comment]
@daleharvey Is there any update on this? We have have about 6000 documents in Cloudant and about 4500 deleted docs. When we try to replicate from, it also replicates the deleted documents. Is there a way to exclude deleted documents when replicating from the Cloudant/Couchdb?

**Comment by JoeOsterfeld** [comment]
I have the same issue as described above. Please advise.
