### ISSUE TITLE
Cancel behavior on replication does not appear to work as specified in the docs

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb#5264]
### Environment (Node.js/browser/hybrid app/etc.)

Node.js

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

N/A

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

LevelDB

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

N/A

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

```Javascript
var PouchDB = require('pouchdb');

var dbPath = "foo";

var DefaultPouch = PouchDB.defaults({
  prefix: dbPath
});

var badUrl = 'http://127.0.0.1:2342/db/foo';

var ajaxOptions = {
  live: true,
  retry: false,
  skip_setup: true
};

var remoteDB = new DefaultPouch(badUrl, ajaxOptions);
var cancel = remoteDB.replicate.to('foo')
    .on('paused', function (err) {
      console.log('Got paused with ' + err);
    })
    .on('active', function () {
      console.log('Replication resumed');
    })
    .on('denied', function (err) {
      console.log('We got denied on a PouchDB access, this really should ' +
        'not happen - ' + err);
    })
    .on('complete', function (info) {
      console.log('complete - ' + info);
    })
    .on('error', function (err) {
      console.log('Got error on replication - ' + err);
      cancel.cancel();
    })
    .on('change', function (info) {
      console.log('change - ' + info);
    })
    .on('cancel', function (info) {
      console.log('cancel - ' + info);
    });
```

So the docs state "complete (info) - This event fires when replication is completed or cancelled. In a live replication, only cancelling the replication should trigger this event." So my expectation is that when I call cancel in the error function above that the replication will cancel and I'll get a complete event. But I don't. In fact, what does seem to happen is that a new event that isn't even listed in the docs, cancel, is what actually gets called.

So we have a bug but I'm not sure what the bug is exactly.

Possible Bug 1.a - The specs are wrong. We should specify that complete won't be called on cancel() for live replications but the cancel event will be emitted.

Possible Bug 1.b - The specs are right. Calling cancel() should trigger a call to complete but for some reason they aren't and we need to fix that.

Possible Bug 1.c - My code above is somehow wrong and I need to read the specs better or avoid typos.

So is it 1.a or 1.b or 1.c?

BTW, given the example in the docs for changes I'm assuming it's 1.b but I thought I would ask.

And there is also:

Possible Bug 2 - Should we document the existence of the cancel event on the PouchDB object?

**Comment by daleharvey** [comment]
The `error` event is "completed with an error"

> This event is fired when the replication is stopped due to an unrecoverable failure.

Calling cancel doesnt do anything because the replication is already stopped, this is intentional but we may want to clarify the docs

**Comment by yaronyg** [comment]
O.k. that makes sense then. I did find the docs a bit confusing but now that you have explained it, it makes sense. I think what threw me is that the info event that complete gets includes "errors" and the text said 'completed or cancelled' and in my head (I know, a scary place) I read cancelled as meaning "replication has been ended" (which would include errors) and not as "the cancel method was called" (which would not). I'll close for now because, really, we have enough other issues to deal with and since I seem to be the only person to have raised this issue we can probably assume I'm just slow.
