### ISSUE TITLE
Add options to define custom _id field when creating database

### ISSUE THREAD

**Issue by Alsciende** [pouchdb/pouchdb#5270]
Feature Request: add an option when creating a database to change the default `_id` key that is used to define the ID of a document.

**Comment by daleharvey** [comment]
So this is something we inherited from CouchDB and is an assumption baked into a huge amount of our codebase, all of our and couch* documentation, book etc so it is something that is very unlikely to change however I am wondering what your use case is, do you have a predefined structure and you would like to pick out one of the fields or is there another reason?

**Comment by Alsciende** [comment]
Thank you for your answer. I've never used CouchDB, and I don't intend to. I'm testing PouchDB because it has a Promise interface and looks very mature.

I'm working with an API that returns records with a unique key `code` (for example, https://netrunnerdb.com/api/2.0/public/cycles or https://netrunnerdb.com/api/2.0/public/packs). So I'd like the database to use this `code` key as ID. Right now I parse the data and create a `_id` key from the `code` key, before importing it via `bulkDocs`.

Would it be possible to define a "proxy" ID key? `_id` would remain the real ID key internally, but it would be mapped on `code` when the documents are imported or exported?

**Comment by Alsciende** [comment]
FWIW, this option is supported by ForerunnerDB: https://github.com/Irrelon/ForerunnerDB#specifying-a-primary-key-up-front. That's why I was excepting to see it in PouchDB :)

**Comment by daleharvey** [comment]
It wouldnt be particularly easy, PouchDB has a single public API that is used by both users and the replicator, the replicator depends on documents having an id and a revision so any replicator would also need changing work in order to be able to understand the format of the data that is being produced.

**Comment by nickcolley** [comment]
I think this should be done at a higher level than PouchDB, keeping PouchDB as close to CouchDB avoids too much scope growth.

**Comment by daleharvey** [comment]
Yeh while I dont think we need to be totally stuck to CouchDB api's decisions that we dont agree with, supporting this would break most tools that operated on Pouch / CouchDB data including the replicator. It would introduce a lot of confusion and complexity for a relatively minor convenience. For a database that didnt need to worry about compatibility I think its a nice feature, but not for Pouch, Thanks for reporting and discussing it
