### ISSUE TITLE
Remove irc bots

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5274]
> <nolanlawson> daleharvey: can we move the bots to a #dev channel? Feature request from @jan :)

I am really against a `dev` channel, I was against CouchDB doing it, I believe it fragments the conversation unnecessarily and neither couch or pouchdb have enough traffic to have to split it up.

I have configured the bot to not have to join / leave, and only send messages about commits to master (+ PRs), these are fairly recent changes so may not have noticed the effect. With that the bot is going to be sending about 3 messages a day to IRC (https://github.com/pouchdb/pouchdb/graphs/commit-activity), I find it useful to get the notifications when code is written to master, but if nobody else does then I can do it via other means. So please feel free to 👍 (remove bots) or 👎(keep bots) this issue as a vote or have your say. Cheers

cc @nolanlawson @janl

**Comment by nickcolley** [comment]
Just to confirm, a :+1: means you're *for* removing bots?

**Comment by daleharvey** [comment]
lol I realised that was totally confusing, I originally meant my 👍 to keep bots, but realised it was 👍 'ing an issue to remove them, so clarified 👍 to remove bots, 👎 to keep them. Although as with mono repo its not a totally binding vote, just figuring out the general feelings, if you feel strongly either way then please comment

**Comment by daleharvey** [comment]
So I have reduced these further (they are now notices and not messages) given the lack of volume of these and lack of opposition going to keep them running for the time being

**Comment by nolanlawson** [comment]
Late to the vote, but I'm fine with this solution. Much less noisy!
