### ISSUE TITLE
LevelDB bulkDocs() should be one atomic transaction

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5276]
Not sure if this was opened elsewhere, but for performance and durability reasons, Level writes should be done in a single batch() operation. /cc @yaronyg @mattpodwysocki

**Comment by daleharvey** [comment]
yup its opened with a ton of into from @yaronyg  @ https://github.com/pouchdb/pouchdb/issues/3224, closing as a dupe since that one has a lot of info
