### ISSUE TITLE
Pouchdb support for other database.

### ISSUE THREAD

**Issue by akash-pal** [pouchdb/pouchdb#5282]
### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

How to make PouchDb work with MongoDb or Mysql database? Is it necessary to use CouchDb

**Comment by nickcolley** [comment]
Hey @akash-pal 

You can check out the supported Node.js adapters here: https://pouchdb.com/adapters.html#pouchdb_in_node_js

Going to close this out but if you need any more help please reopen! 😸 

Nick
