### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb#5286]
### Environment (Node.js/browser/hybrid app/etc.)

Node.js

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

N/A

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

N/A

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

N/A

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

Repro:

2. 'git clone https://github.com/pouchdb/pouchdb.git'
3. cd to pouchdb
4. npm install

Result: A failure when NPM tried to get pouchdb-merge

See the full failure log at : 
https://gist.github.com/yaronyg/1d5ef7767fafe9638ab19f450cb572bc

**Comment by daleharvey** [comment]
I am getting the same with `pouchdb-md5` - https://gist.github.com/daleharvey/43b6973d0108ba462a1b5d2a3b238e3b

**Comment by daleharvey** [comment]
ok looks like this was fixed in https://github.com/pouchdb/pouchdb/commit/5dc245a6a4fbc492d400935d0934487d2a91a654, local build and travis both fixed
