### ISSUE TITLE
PouchDB assumes user have lerna installed globally

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb#5288]
The build command in scripts just calls 'lerna bootstrap' which is lovely if you have it installed globally but not so useful if you don't. I will submit a PR that changes this to node_modules/lerna/bin/lerna.js.

**Comment by nolanlawson** [comment]
Scripts inside of `package.json` know to use `node_modules`, so this shouldn't be an issue unless there's something odd with Windows going on. What shell do you use BTW?

**Comment by yaronyg** [comment]
This bug was a bug on my part. I was confused. That's why I closed it. BTW, I do all my work on a Mac, not windows. Since I have to develop for both iOS and Android it was easier to just standardize all my dev tools on the Mac.
