### ISSUE TITLE
Sync Issue

### ISSUE THREAD

**Issue by 3nvy** [pouchdb/pouchdb#5291]
Hey there,

Why would like to know if theres a way to sync between local and remote db's only some specific documents, and only some specific attributes in each document, instead of the default behavior that syncs every document and attribute ?

Best Regards,
3nvy

**Comment by nickcolley** [comment]
Hey @3nvy 

Sounds like you want to do a filtered replication https://pouchdb.com/api.html#filtered-replication

In CouchDB (and PouchDB) there is a concept of a design document, this can give you a partial representation of your database (like a view).

Here's a blog post describing hopefully something similar to what you're trying to achieve 😄 

https://pouchdb.com/2015/04/05/filtered-replication.html

Going to close this out but if you still have an issues feel free to reopen it! 👍

**Comment by 3nvy** [comment]
oh thks a lot, gonna try that aproach :D 

Thks for the help ;)
