### ISSUE TITLE
SQLite Plugin 1 (aka Cordova SQLite Storage) broken in 5.4.0

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5293]
This was a bug that crept in to 5.4.0 because we don't test SQLite Plugin in CI:

> WebSQL threw an error – Error: Sorry first openDatabase argument must be an object — SQLitePlugin.js:25

**Comment by nolanlawson** [comment]
#5294 is the fix, or users can also switch to https://github.com/nolanlawson/cordova-plugin-sqlite-2 which is the one we officially support.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/b600bdd249946aa9eeabefbe868d9987c9240723
