### ISSUE TITLE
Move pouchdb-collate and pouchdb-collections into core

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5295]
With the new monorepo setup, this should be a slam-dunk. There's no reason to have these as a separate repo.

BTW I found [this awesome Lerna tool](https://github.com/lerna/lerna/pull/173) that can import a separate Git repo _with version history_! Thanks @hzoo. :)

**Comment by nlfiedler** [comment]
Are the functions from pouchdb-collate exposed in pouchdb core now? The other module is deprecated, but I can't find how to use this API within PouchDB 6.3.4. I see the functions in the code, but they are not exposed? Guides and API docs don't talk about it either.

**Comment by daleharvey** [comment]
They are in the pouchdb repo to be used by pouchdb core, but they are not part of the pouchdb core api, if you want to use them you need to do so directly, closing since they are in the repo
