### ISSUE TITLE
Support NativeScript SQLite

### ISSUE THREAD

**Issue by colinskow** [pouchdb/pouchdb#5300]
NativeScript seems like a really valuable platform. We can use PouchDB as a backend for native apps too! All we have to do is massage the WebSQL adapter to also work with [nativescript-sqlite](https://github.com/NathanaelA/nativescript-sqlite).

The syntax is slightly different from the Cordova version, but I think it would be a trivial amount of work to create an adapter.

**Comment by nolanlawson** [comment]
I absolutely want to enable this. In fact, if you know how to write the native bindings for SQLite, you can easily hook it up using SQLite Plugin 2 or the [custom API to node-websql](https://github.com/nolanlawson/node-websql#custom-sqlite3-bindings), which is what SQLite Plugin 2 uses under the hood anyway.

I feel, though, that this is best solved outside of PouchDB core. A module like `pouchdb-adapter-node-websql` shows that it's possible to have a third-party module for this. I encourage you 100% to build one. :)

**Comment by CliffS** [comment]
@colinskow Did anything progress on this?  I would love to be able to use PouchDB inside a NativeScript application.
