### ISSUE TITLE
Support For Sync Between MyServer and CouchDb

### ISSUE THREAD

**Issue by akash-pal** [pouchdb/pouchdb#5301]
Hi, I have been been using PouchDb with Cloudant in cordova and the syncing is very fast. 

PouchDb FAQ Says:
-------------------------
PouchDB cant sync with MongoDB/MySQL/my current non-CouchDB database
as  backend needs to speak the CouchDB replication protocol.

However there is a way to replicate the changes made in couchDb with mysql https://www.npmjs.com/package/couchdb-to-mysql

My Question is; Is there a way to replicate the changes made in mysql to replicate within couchDb? 
Here 
https://gist.github.com/cfaulkingham/1097796 
is an implementation but am not sure whether this will work.

**Comment by daleharvey** [comment]
It isnt something that is or will be supported by pouchdb / couchdb in the short term, mysql has no concept of revisions, it will be possible to have PouchDB <-> CouchDB <-> My custom couch to mysql sync that handles business / revision logic <-> MySQL, and there may be some tools around to help you do that although unlikely to be generic as they are fundamentally different data models. Closing this out as its something that isnt going to be tracked by us, but feel free to continue discussing in here

**Comment by akash-pal** [comment]
PouchDB <-> CouchDB <-> My custom couch to mysql sync that handles business
/ revision logic <-> MySQL

is exactly what I am looking for. How do I go about doing this? Is there
some material which I could refer to.

Especially this portion My custom couch to mysql sync that handles business
/ revision logic <-> MySQL



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=akashpa93@gmail.com&idSignature=22>

On Wed, Jun 8, 2016 at 1:43 AM, Dale Harvey <notifications@github.com>
wrote:

> It isnt something that is or will be supported by pouchdb / couchdb in the
> short term, mysql has no concept of revisions, it will be possible to have
> PouchDB <-> CouchDB <-> My custom couch to mysql sync that handles business
> / revision logic <-> MySQL, and there may be some tools around to help you
> do that although unlikely to be generic as they are fundamentally different
> data models. Closing this out as its something that isnt going to be
> tracked by us, but feel free to continue discussing in here
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/5301#issuecomment-224399830>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJv3Wymo6o5_FLK_Kb8pNE_4gm_B93d9ks5qJdEFgaJpZM4IwR3W>
> .
>



-- 
*Thanks & Regards*
*Akash Pal*
*Hybrid Application Developer*
*Zensar Technologies Ltd.*
*Pune, India*
*Contact: +91 8927453732*

*
<https://mailtrack.io/trace/link/be00191ca2995b9cc64b063e77fc8e9460561ce0?url=https%3A%2F%2Fin.linkedin.com%2Fpub%2Fakash-pal%2F6b%2Fb0a%2F435&signature=ce1579020c604d12>*

**Comment by akash-pal** [comment]
PouchDB <-> CouchDB <-> My custom couch to mysql sync that handles business / revision logic <-> MySQL

is exactly what I am looking for. How do I go about doing this? Is there some material which I could refer to. 

Especially this portion My custom couch to mysql sync that handles business / revision logic <-> MySQL

**Comment by nolanlawson** [comment]
Check out https://github.com/kesla/mysqldown although your mileage may vary because we've never tested it.

**Comment by nolanlawson** [comment]
Also keep in mind you cannot access MySQL directly e.g. to update/delete fields so be very careful with this approach

**Comment by akash-pal** [comment]
Thank you, I am basically looking for  one time replication . So update/delete should not be an issue as of yet.

**Comment by akash-pal** [comment]
How should I use https://github.com/kesla/mysqldown to achieve 
My custom couch to mysql sync that handles business / revision logic <-> MySQL
I checked the readme of https://github.com/kesla/mysqldown and didnt get anything.

**Comment by nolanlawson** [comment]
`var db = new PouchDB('http://mysqldbsomewhere', {db: require('mysqldown')})`

**Comment by nolanlawson** [comment]
`var db = new PouchDB('http://mysqldbsomewhere', {db: require('mysqldown')})`

Also see: https://pouchdb.com/adapters.html#pouchdb_in_node_js

**Comment by vahidreza** [comment]
@akash-pal
Did you find a way to do what you meant to do?

**Comment by akash-pal** [comment]
No I wasnt able to, if u are going with couchdb then u have to you couch base server.
or else you can custom logic of using timestamps to sync data between your server and your app.
