### ISSUE TITLE
LevelDB adapter needs error handling on allDocs callback

### ISSUE THREAD

**Issue by stockulus** [pouchdb/pouchdb#5309]
### Environment (Node.js/browser/hybrid app/etc.)
ReactNative
### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)
iOS Simulator, During development / (Reload 
### Adapter (IndexedDB/WebSQL/LevelDB/etc.)
LevelDBAdapter AsyncDown
### Please describe your issue. Test cases (e.g. JSBin) are very helpful!
If you app offten writes to PouchDB in ReactNative during development, it can happen, that a record is not correctly stored in PouchDB (Key stored, Value not) After Reload it causes a Problem in allDocs function of the pouchdb-adapter-leveldb-core, because there is no check for Error on read. 

I'd suggest to add an Error check there, it should not harm anyone. Pull Request will follow.

Christoph

**Comment by daleharvey** [comment]
So this needs to be fixed by https://github.com/pouchdb/pouchdb/issues/3224
