### ISSUE TITLE
Error/conflict when creating a new doc with _rev

### ISSUE THREAD

**Issue by jeqq** [pouchdb/pouchdb#5317]
I'm trying to create 9 **new** documents in an **empty** PouchDB database (with `bulkDocs()`), 8 docs without `_rev` and one with `_rev`. All documents are created, beside the document with the `_rev` field because of the conflict error. This problem started with the version `5.0.0` of PouchDB and I think changes that produces it are described here: https://pouchdb.com/2015/10/06/pouchdb-5.0.0-five-years-of-pouchdb.html

Doc value (this is an entity I'm using for testing in Drupal with Relaxed module):

```
{
  "@context": {
    "_id": "@id",
    "@language": "en"
  },
  "@type": "entity_test_mulrev",
  "_id": "1da2a674-4740-4edb-ad3d-2e243c9e6821",
  "_rev": "1-e4af2d5d944d64db082b484bc1088d1a",
  "en": {
    "type": [
      {
        "value": "entity_test_mulrev"
      }
    ],
    "user_id": [
      
    ]
  }
}
```
The erros I get for this doc is `Document update conflict` (status 409). 

Is this a PouchDB bug? Or I'm missing something? At least I know that I can create this document in CouchDB and I also need to create new docs with `_rev` in PouchDB. Any help will be welcome. Thanks!

**Comment by daleharvey** [comment]
The only way to create new documents with a revision in pouchdb is with `new_edits: false`, the fact you used to be allowed was a bug that was fixed in https://github.com/pouchdb/pouchdb/issues/4712

**Comment by jeqq** [comment]
Thanks @daleharvey! But now (when using `new_edits: false`) I get an `Invalid rev format`, `1-e4af2d5d944d64db082b484bc1088d1a` (from my example) seems to be a valid PouchDB format.

**Comment by daleharvey** [comment]
You need a `_rev` field for each document with `new_edits: false`, so if you are doing 8 new writes (without a rev) and inserting one doc with a rev, they will need to be seperate requests with the appropriate new_edits

**Comment by jeqq** [comment]
I got it, thanks!
