### ISSUE TITLE
Save inline attachments - documentation error

### ISSUE THREAD

**Issue by natcohen** [pouchdb/pouchdb#5324]
In "Save an inline Blob/Buffer attachment" and "Save many attachments at once" callback examples in the [website](https://pouchdb.com/api.html#save_attachment), the object sent has one `_attachments` inside another `_attachments`

**Comment by daleharvey** [comment]
Good catch, thanks for reporting, fixed in https://github.com/pouchdb/pouchdb/commit/bb79aa5d31384336a88c98aa59dd0d0a07210a10
