### ISSUE TITLE
RFC: Breaking changes in 6.0.0 (discussion)

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5342]
If we're going to do a breaking change, let's cram as many breakages in as we can.

Slated:

- Remove `new PouchDB().then()` (https://github.com/pouchdb/pouchdb/pull/5319)
- Remove `db.put(doc, id, rev)` (https://github.com/pouchdb/pouchdb/pull/5311)
- `extras` API

Others we want to sneak in? Now would be the time. (Edit this comment to add more!)

**Comment by daleharvey** [comment]
I think we should consider removing `lie` in the browser builds I know its not the largest dep in the world however it seems to be standard practice to leave the edge case polyfills up to the user

**Comment by nolanlawson** [comment]
I would like to make both lie and debug into optional plugins with the plugin system, if possible. If not, then yeah, removing it makes sense by now. Promises are in all major browsers and I see many other libraries that require users to bring their own polyfills.

**Comment by nolanlawson** [comment]
Let's drop Bower support as well.

**Comment by daleharvey** [comment]
👍 on all counts

**Comment by nickcolley** [comment]
In agreement about leaving it up to the user to polyfill Promises, but we should consider how we communicate it to newcomers..

**Comment by nolanlawson** [comment]
@nickcolley: Edge+, Android 5+, etc are the new minimum requirements. IE10+, Android 4+ etc "with a polyfill". Unless we can make lie a custom build

**Comment by daleharvey** [comment]
The squelching errors PR's can somewhat be considered breaking as the return values are going to be different

**Comment by daleharvey** [comment]
So we couldnt do this for `6.0.0`, however inspired by https://github.com/pouchdb/pouchdb/issues/5172

We have had a large amount of confusion over `complete` and `error` events in changes / replication / sync forever. I am wondering if we want to just remove them?

`db.changes().then()` and `db.changes().catch()` are semantically identical but far more obvious, its not obvious that `error` and `complete` are termination events mostly because the idea of termination events is not a common concept. 

Would we lose any use cases by doing this?

**Comment by daleharvey** [comment]
Also @yaronyg, can we safely get rid of https://github.com/pouchdb/pouchdb/blob/master/packages/pouchdb-adapter-http/src/index.js#L138 ? would like to get rid of any undocumented / untested functionality and it sounds like this functionality would be replaced by https://github.com/pouchdb/pouchdb/issues/5322 anyway

**Comment by nolanlawson** [comment]
@daleharvey I think mixing promises and event emitters will likely cause
more confusion than before. If anything, we should just simplify our
events; since we added `retry` replication a lot of them don't make sense
anymore (e.g. `denied` is basically `error`, and `error` never fires).

I think confusion about `active` and `paused` stems from them firing too
frequently, due to wonkiness in the replicator itself IMO.

**Comment by daleharvey** [comment]
`denied` is specifically not an error, its expected behaviour that some documents may get rejected by a `validate_doc_update` and replication should continue as normal, but some clients wanted to know when that happened. `error` is still required for `retry: false`. It would be nice to get `active` and `paused` to work more consistently.

However we still get questions fairly often about whether `complete` should be called with an error, or when `error` should be called / does it stop replication, this is totally clear when you use promises and the remaining events happen in a way that people are more familiar with.

This is a big change so not going to push hard on it, but I think its something worth keeping in mind when future issues come up / potential nudging when we look at the documentation

**Comment by nolanlawson** [comment]
`complete` should probably not call with an error; instead that should be
an `error`. Otherwise `error` does nothing with `retry`.

**Comment by daleharvey** [comment]
Yeh complete is only triggered on successful termination, I just meant that isnt looking obvious to users of the api as far as I can tell

**Comment by yaronyg** [comment]
@daleharvey I believe that code was used for an older version of Thali. Right Thali has switched to a model where everything we do with PouchDB is documented and on the website. :)

**Comment by nolanlawson** [comment]
I would like to remove `prefix`. It's buggy and wonky and people can just write their own wrapper functions to do the same thing. E.g. see the fact that `prefix`+http broke @yaronyg's setup.

**Comment by yaronyg** [comment]
If we take the prefix argument to its logical conclusion then shouldn't we remove defaults all together? After all aren't defaults just a way to skirt around having to create a custom constructor? I would guess that the most common use of defaults is prefix so if prefix is going then why not just take out defaults all together?

**Comment by nolanlawson** [comment]
That's a great point. You could also argue for `adapter` and `db` being useful features, but the new custom builds make that fairly obsolete.

I would be happy to remove both `defaults()` and `prefix` in a one-two punch. It would remove an enormous amount of code and encourage people to just write their own wrapper functions, which are more flexible and don't require any help from the core team.

OTOH `PouchDB.defaults()` does seem to be in [wide use in the ecosystem](https://github.com/search?l=javascript&q=PouchDB.defaults&type=Code&utf8=%E2%9C%93). It may be worth writing a separate module that does what `PouchDB.defaults()` does (it's really just constructor extending + EventEmitter extending).

**Comment by nolanlawson** [comment]
As noted in https://github.com/pouchdb/pouchdb/issues/5384 I would also like to remove `db` from the documentation. It is an internal API and doesn't need to be documented anymore.

**Comment by yaronyg** [comment]
I think it really goes to the core of PouchDB's philosophy. Is it batteries included or lego pieces?

**Comment by yaronyg** [comment]
As a side note I tried an exercise where I stopped using default and instead created a custom wrapper that could take a 'new' and use it where I used PouchDB. That blew up pretty quickly. The reason is that Express-PouchDB tests objects to see if they are PouchDB objects by using the defaults property (kind of ironic given the conversation thread). Also it expects to work on the PouchDB object directly before actually calling new. So to make Express-PouchDB work I would have to essentially create my own custom release of PouchDB just to support something like prefix (or db for that matter). Seems kind of extreme.

**Comment by nolanlawson** [comment]
@yaronyg As discussed in Slack, we can make [the defaults() code](https://github.com/pouchdb/pouchdb/blob/fb77927d2f14911478032884f1576b770815bcab/packages/pouchdb-core/src/setup.js#L108-L137) into a separate plugin, easy peasy. No need to ship it in PouchDB core.

As for "batteries included" vs "lego bricks," it's both. :) `pouchdb` package is batteries-included, plugins are lego bricks. `defaults()` could very well be a "default plugin," although since it's used by such a small minority of users, I'd rather not.

Basic rule of thumb: if we expect <10% of users will use a feature, then it should be an optional plugin. `defaults()` definitely fits that bill IMO.

**Comment by nolanlawson** [comment]
As for checking for `.defaults()` to determine if something "is" a `PouchDB` object, yeah, we should probably change that in express-pouchdb.

**Comment by daleharvey** [comment]
I am not entirely sure about removing `defaults` and `prefix`, I think we could clean up both of those bits of code, however they are pretty much required when using pouchdb in node, which isnt insignificant, we use them to run our own test suite, I have used them in every server (neither of those I can find in the search results), as does hoodie etc.

However they are mostly useful in node and less useful in the browser, I would definitely be 👍 on decoupling the code if its possible, it may be tricky because as mentioned the server implementation depends on these features being exposed by PouchDB and a wrapper is not always a feasible solution

**Comment by yaronyg** [comment]
Prefix in particular is critical because CouchDB itself distinguishes between a DB's name and it's on-disk location. Right now Express-PouchDB replicates that functionality with prefix. So we really can't remove prefix, as @daleharvey said, the best we can do is move it around. Is it worth the effort?

**Comment by nolanlawson** [comment]
Good point; I forgot about that detail. So in fact I’m kind of surprised that 5.4.0 didn’t break express-pouchdb due to the http adapter changes. Or maybe it did?

**Comment by yaronyg** [comment]
@nolanlawson this is the problem I'm running into. At least until @garrensmith started fixing things none of the test infrastructure for either PouchDB-Server or Express-PouchDB could even run! We had broken it some time ago and near as I can tell nobody really noticed. It seems to me that before we do a release of PouchDB we really need to make sure we can still successfully run tests on our major dependent projects like Express-PouchDB.

**Comment by daleharvey** [comment]
express-pouchdb / pouchdb-server were green until my squelching errors patch. We do check we can run the test suite against them on every PR (their own tests suite setup may be broken however), however non core projects do not block patches from landing if they are not green. We want to minimise contribution burdens and not have every pouchdb contributor responsible for a larger set of projects that their patch may break

**Comment by nolanlawson** [comment]
Yeah, we made a decision awhile ago to add pouchdb-server and express-pouchdb to the allowed failures. For better or for worse, it’s not considered core to PouchDB and therefore needs to be maintained by those who are interested.

**Comment by yaronyg** [comment]
@daleharvey yeah the issue is that their own test suite setup was broken. But I do understand the priorities and they are clear. Which is why once I finish up some of my own internal testing on Thali I'll be turning my attention back to express-pouchdb and pouchdb-server as I can't check in my PR for Thali until I get the bug with replication going on forever in express-pouchdb fixed.

**Comment by garrensmith** [comment]
I don't think we should make it a requirement for pouchdb pr's to pass on pouchdb-server. But I think we can clean up pouchdb-server a lot by making it a monorepo. I'll try and tackle that over the next few weeks and see how it goes.

**Comment by yaronyg** [comment]
@garrensmith what do you mean by making it monorepo? There isn't much in pouchdb-server so do you mean moving that code into pouchdb's monorepo or combining pouchdb-server and express-pouchdb?

**Comment by nolanlawson** [comment]
@yaronyg The current plan is to move express-pouchdb into the pouchdb-server repo. There are also lots of tiny modules that could be made part of that monorepo.

**Comment by garrensmith** [comment]
Yes. That should hopefully make the test setup cleaner. It will also make maintaining it a lot easier. 

All misspelling thanks to my iPhone

**Comment by yaronyg** [comment]
@garrensmith so does that mean I should give up on https://github.com/pouchdb/express-pouchdb/pull/329 until the monorepo change is made or do you intend to check in https://github.com/pouchdb/express-pouchdb/pull/342 first? I only ask because 329 is blocking our entire test framework for Thali. :(

**Comment by garrensmith** [comment]
I want to get all the tests passing first before I start on the monorepo.
So I would like to get PR342 merged first, its just one failing test then
we are good to go. Hopefully that will help you.

**Comment by garrensmith** [comment]
I've just published express-router 1.0.5 with all tests passing. That should hopefully help you @yaronyg

**Comment by yaronyg** [comment]
@garrensmith THANK YOU! I'll get to this once I dig out of email.

**Comment by nolanlawson** [comment]
We should remove the `optionalDependencies`, because they're weird and flaky and users now have a better option, which is `pouchdb-browser`.

**Comment by nolanlawson** [comment]
There's a TODO in the HTTP adapter; we should probably do this too:

    // TODO: Remove `skipSetup` in favor of `skip_setup` in a future release

**Comment by daleharvey** [comment]
Yeh same with `return_docs`, I totally thought I already did that but doesnt look like it

**Comment by nickcolley** [comment]
For some of the deprecations could we consider doing https://github.com/facebook/jscodeshift to help people migrate their codebase?

**Comment by nolanlawson** [comment]
If I have time I might write a codeshift. Another way to mitigate the `skip_setup`/`return_docs` problem is to emit a warning if they're using the deprecated API and then remove the warning after a few releases.

**Comment by nickcolley** [comment]
I like the deprecation with a warning approach the React community does that too, I'd be up for writing a codeshift transform, seems interesting. :)

**Comment by nolanlawson** [comment]
Let's remove SQLite Plugin support from `pouchdb-adapter-websql`. The validation detection is too error-prone, and if users are writing Cordova apps, they have full access to the global context and can inject whatever they want, so our validation code is useless. We can write a separate `pouchdb-adapter-cordova-sqlite-plugin` instead that extends `pouchdb-adapter-websql-core`.

**Comment by nolanlawson** [comment]
I've created [pouchdb-adapter-cordova-sqlite](https://github.com/nolanlawson/pouchdb-adapter-cordova-sqlite). So there's no more need to support Cordova SQLite in PouchDB core. We should remove it.

**Comment by nolanlawson** [comment]
Let's remove `db` as well. It's an internal detail of `pouchdb-adapter-leveldb-core`, and I don't really feel like documenting and therefore validating any of the experimental PouchDB backends like RiakDOWN/RedisDOWN/etc. because they never seemed very well-maintained to me, nor did they solve any real-world problems (although they were interesting experiments). Currently the only *DOWN adapters that matter IMO are the ones we maintain ourselves (MemDOWN, FruitDOWN, LocalStorageDOWN), which are currently exposed via `adapter` and not `db` anyway. Also if anyone does get the motivation to create a new *DOWN adapter, they can use the quasi-secret `db` option under the hood but then expose `adapter` to users.

**Comment by nolanlawson** [comment]
Just occurred to me that if we are removing `extras` then we also might as well remove `dist/pouchdb.memory.js`, `dist/pouchdb.fruitdown.js`, `dist/pouchdb.localstorage.js` etc. These things can be imported from the separate plugins.

OTOH this would raise the question of what packages are worth doing a UMD build for. Currently we only provide a UMD of PouchDB itself and of the adapter plugins, but maybe we should do it for each package? I.e. should each package have a `dist` directory?

**Comment by nolanlawson** [comment]
As for removing `lie`, I'm not convinced that it's a good idea, now that I think about it. If users want to provide their own global `Promise` polyfill, fine, we'll use that. But by outright removing `lie` we're introducing a lot of potential confusion, bugs, and documentation changes just to save 1.5kB. Also that 1.5kB could be even smaller if I opened a PR on `immediate` to use ES6/Rollup.

**Comment by nolanlawson** [comment]
Let's move `pouchdb-http` out of core as well. I don't see any reason to have it in the monorepo when things like `pouchdb-memory` and `pouchdb-adapter-cordova-sqlite` are third-party. I would also like to add mapreduce to it since it's annoying not to have it.

**Comment by vicentedealencar** [comment]
> OTOH this would raise the question of what packages are worth doing a UMD build for. Currently we only provide a UMD of PouchDB itself and of the adapter plugins, but maybe we should do it for each package? I.e. should each package have a dist directory?

@nolanlawson, have you seen [npmcdn](https://npmcdn.com/)?

**Comment by nolanlawson** [comment]
Sure, doing a UMD build for each package and pushing it to npm would make it easy to download those bundles from npmcdn. You already can do this today for that main PouchDB package: https://npmcdn.com/pouchdb/dist/pouchdb.js

**Comment by daleharvey** [comment]
Should we go for a 6.0 release? not hugely fussed about whether removing lie makes it or not, and `pouchdb-http` etc arent part of the core api so less relevant. Happy write up the release etc. I know major version bumps arent free, but I think these changes are relatively minor and I think we have mitigated them well

**Comment by daleharvey** [comment]
So as for lie, one issue I have with removing it is still having to polyfill it in node but removing from the browser. It looks like node introduced `Promise` in `0.12`, `0.10` ends LTS in October so I think in October we just remove all promise polyfill code and assume its there by default, we can add a check to give the user a clear message if it isnt defined.

**Comment by nolanlawson** [comment]
I believe we should move `pouchdb-http` out of core. It makes more sense as a third-party lib IMO.

According to caniuse.com, promises are [still at 74% support globally](http://caniuse.com/#feat=promises); I would be hugely opposed to removing lie just to save 1.5kB. I also don't think removing it simplifies the code at all, since we've already isolated all Promise code to pouchdb-promise.

I know it's been awhile since a release, but I would prefer a little more time to remove things like the `extras`, which add on to the build time and increase our API surface. I plan on doing a 5.4.6 this week in order to get recent patches in; can I have a little bit of extra time before 6.0.0?

**Comment by nolanlawson** [comment]
I think that's enough discussion. Let's move on to https://github.com/pouchdb/pouchdb/issues/5586.

**Comment by nolanlawson** [comment]
Please let me know if I missed anything in #5586, otherwise I consider that the final list for 6.0.0.
