### ISSUE TITLE
Leveldown adapter rejecting with `true`

### ISSUE THREAD

**Issue by swashcap** [pouchdb/pouchdb#5343]
### Environment (Node.js/browser/hybrid app/etc.)

[Electron](https://github.com/electron/electron) @ 1.2.2

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

n/a

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

LevelDB

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

CouchDB

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

PouchDB is returning a Promise that rejects with the value `true` in the case of Level/leveldown#291. This isn’t a PouchDB bug, necessarily, but it would be nice to have a reasonable error message – something along the lines of leveldown not being built for the environment’s version of V8.

**Comment by nolanlawson** [comment]
Have you reinstalled leveldown for electron? Where is the error thrown? Is this a regression or a preexisting bug?

**Comment by cdaringe** [comment]
This is purely a `leveldown`+`electron` bug :(.  leveldown#291 is now closed... but pretty much the electron folks need to square up with node internals.  if anyone else suffers this, it is mitigable by using `node-websql` vs. leveldown

**Comment by daleharvey** [comment]
Nice thanks

**Comment by cdaringe** [comment]
I was wrong. `websql` and `leveldown` tank in latest electron. noooooooooooo 🔥 :rage3:
