### ISSUE TITLE
Missing Test for PR #5199 - fix excessive long replication loop

### ISSUE THREAD

**Issue by dharders** [pouchdb/pouchdb#5345]
PR #5199 was merged and released in 5.4.0 without a test. Discussion in #5196 seemed to indicate that a test would be difficult to write.

I've created a test, [test.replication_perf_regression.js](https://github.com/dharders/pouchdb-replication-perf-regres-test/blob/master/test.replication_perf_regression.js), that seems to catch the performance regression.

I have run the test on 5.2.x through to 5.4.x and it behaves as expected (i.e. Passes 5.2.0, Fails 5.2.1 through to 5.3.2, Passes 5.4+) as the regression was introduced in 5.2.1 and fixed in 5.4.0.

The test works by counting the number of GET requests to the remote `_local/` endpoint, used for replication/checkpointing. A failure occurs when the number of GET requests to the remote `_local/` endpoint are greater than the number of docs replicated. The bad performing code would only flush 1 change per batch and not enable the `pendingBatch.changes` buffer to fill up before the `startNextBatch()` cycle commenced.

I would create a PR, but as a first-time contributor I'm having issues building / running npm test on my dev environment (Windows 7 x64) after a simple git clone, npm install (I will create another issue for this).

It should be easy to modify [test.replication_perf_regression.js](https://github.com/dharders/pouchdb-replication-perf-regres-test/blob/master/test.replication_perf_regression.js) to fit PouchDB's way of testing as I based the test on [another PouchDB test, test.read_only_replication.js] (https://github.com/pouchdb/pouchdb/blob/master/tests/component/test.read_only_replication.js)

As requested @nolanlawson

**Comment by daleharvey** [comment]
This looks great, 2 minor nits is that we use 2 space tabs, and `_local_GET_count ` would be `localGETCount` but the rest looks great. I know you have been having issues getting your local setup completely passing but if you are confident this test will pass then please open a PR and we can see what travis says

**Comment by nolanlawson** [comment]
Awesome, awesome work. I looked over the test, and it looks great except that it may be a bit difficult to run in our test suite as-written. In particular our test suite doesn't normally set up a `pouchdb-express-router` and then count the number of `GET` requests that way; it just talks to the local CouchDB or other server. So you would need some other way to count the requests. (Sometimes we overload `db.get` to do this, but it's a bit wonky TBH.)

OTOH I kind of like this approach; it's very clean and we could at least just run it in our node tests. You could rename it `node.replication_perf_regression.js` and then put it in `tests/integration` and it would run only in Node. It also seems pretty self-contained, and I like that it just starts up the express-router and then shuts it down afterwards. I'm +1 adding it to the test suite.

**Comment by dharders** [comment]
Thanks for the feedback !

I'll try get a PR out today...

**Comment by dharders** [comment]
And done. PR #5353

**Comment by daleharvey** [comment]
@nolanlawson Ths test is based on https://github.com/pouchdb/pouchdb/blob/master/tests/component/test.read_only_replication.js, that and the other tests @ `/tests/components/` generally set up their own server to test against

**Comment by daleharvey** [comment]
Merged in https://github.com/pouchdb/pouchdb/commit/4d2380d061755f0c6b9666b067d447080c81dd66, thanks
