### ISSUE TITLE
Issue with PouchDB on Android with Ionic

### ISSUE THREAD

**Issue by laurenkyla** [pouchdb/pouchdb#5350]
### Environment (Node.js/browser/hybrid app/etc.)

Ionic using Pouchdb and Pouchdb-find

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Android 

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

Not specifying an adapter, If I specify one the code returns no data

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

https://www.smileupps.com/store/apps/couchdb

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

My app works fine on IOS although sometimes can be slow on first login. On Android the app hangs on login sometimes with no error. I connected to Chrome debug tools and I get the following error:

InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. With the logcat running it just sitting on the login screen loading with no errors registering in Logcat. 

I have found that the database when compacted is less than 1MB but left alone for a few days can quickly become 10MB. Auto compaction is turned on. 

I get successful replication messages of local to remote.

I turned on cleanup indexes and that is throwing an error:

{"status":500,"name":"case_clause","message":"Database encountered an unknown error","error":true,"reason":"{[{<<\"fields\">>,{[{<<\"name\">>,<<\"asc\">>},{<<\"_id\">>,<<\"asc\">>}]}}]}"}

I also got a stack trace error

  615                      v8  I  1: /* anonymous */(aka /* anonymous */) [file:///android_asset/www/lib/pouchdb/dist/pouchdb.min.js:~9] [pc=0x3574f9cc] (this=0x5b0080c9 <undefined>,e=0x684dbca1 <JS Arra
                               y[51]>,t=0x38a207f5 <an Object with map 0x3d322cd1>,n=1000)
  615                      v8  I  2: r(aka r) [file:///android_asset/www/lib/pouchdb/dist/pouchdb.min.js:9] [pc=0x630aad0c] (this=0x5b0080c9 <undefined>,e=0x38a0b725 <an Object with map 0x5...
  615                    libc  F  Fatal signal 11 (SIGSEGV) at 0xfbadbeef (code=1), thread 681 (Chrome_InProcRe)
 13119                  DEBUG  I  *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
 13119                  DEBUG  I  Build fingerprint: 'samsung/j13gxx/j13g:4.4.4/KTU84P/J100HXCU0AOI1:user/release-keys'
 13119                  DEBUG  I  Revision: '3'
 13119                  DEBUG  I  pid: 615, tid: 681, name: Chrome_InProcRe  >>> com.thisisjamhot.helpmedoit <<<
 13119                  DEBUG  I  signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr fbadbeef
 13119                  DEBUG  I  r0 5a8393a8  r1 fffffffe  r2 00000000  r3 fbadbeef
 13119                  DEBUG  I  r4 58273c9c  r5 5825b1c8  r6 58273c9c  r7 5a0d3c48
 13119                  DEBUG  I  r8 5a839b7c  r9 5a839d80  sl 58273c9c  fp ffff0fa0
 13119                  DEBUG  I  ip 02a94001  sp 5a839448  lr 570cdaeb  pc 57a5ece0  cpsr 40070030
 13119                  DEBUG  I  d0  746e657272754320  d1  2079726f6d656d4d
 13119                  DEBUG  I  d2  65636f7270202d42  d3  6f2074756f20730a
 13119                  DEBUG  I  d4  705b205d393a736a  d5  6130333678303d63
 13119                  DEBUG  I  d6  7428205d63306461  d7  623578303d736968
 13119                  DEBUG  I  d8  0000000000000000  d9  0000000000000000
 13119                  DEBUG  I  d10 0000000000000000  d11 0000000000000000
 13119                  DEBUG  I  d12 0000000000000000  d13 0000000000000000
 13119                  DEBUG  I  d14 0000000000000000  d15 0000000000000000
 13119                  DEBUG  I  d16 3f9eb0959d3d6449  d17 3fae1ee94df4fa3f
 13119                  DEBUG  I  d18 4000000000000000  d19 3fc67dae86d53980
 13119                  DEBUG  I  d20 3fc5528670f6093a  d21 bf66bd24acae58da
 13119                  DEBUG  I  d22 3fc5d527743d6f6b  d23 4160000000000000
 13119                  DEBUG  I  d24 3f134d99dc60c074  d25 4000000000000000
 13119                  DEBUG  I  d26 3ffd455b11785213  d27 3f90c68c14bcc493
 13119                  DEBUG  I  d28 bf90c68bc95634d9  d29 bfc896800000001b
 13119                  DEBUG  I  d30 3ff0000000000000  d31 416312d000000003
 13119                  DEBUG  I  scr 22000013
 13119                  DEBUG  I  backtrace:
 13119                  DEBUG  I  #00  pc 01223ce0  /data/app-lib/com.thisisjamhot.helpmedoit-1/libxwalkcore.so
 13119                  DEBUG  I  #01  pc 00892ae7  /data/app-lib/com.thisisjamhot.helpmedoit-1/libxwalkcore.so
 

Could that be causing a problem on android? 

Thanks in advance.

**Comment by nolanlawson** [comment]
Usually what's happening in cases like this is that the browser/device became corrupted somehow. I've seen it happen with IndexedDB on Chrome all the time, although it's incredibly tricky to reproduce.

Sadly the solution in these cases is usually just to delete all browser data (in Chrome Canary you can do this with Dev Tools -> Application -> Clear Storage). In the case of Ionic, you can just uninstall and reinstall the app.

If that's _not_ the issue, could you report the Android version and whether or not you're using the Crosswalk WebView?

**Comment by laurenkyla** [comment]
I have tried removing the application, uninstalling, clearing data. I had crosswalk installed at one point and have now removed it and I have been trying to use Cloudant intead of Smileapps but i get no results on my queries on IOS with Cloudant they work fine calling them in the browser. I'm getting nowhere with Android. I previously couldn't get cloudant to work which is why I moved to Smileapps. I have had a working app for 6 months with no problems on smileapps but I had to make some updates to push notifications (not the database) and these errors started occurring just in android but taking longer and longer to load on IOS.  

I tried with an empty database and just one record but it does not return it with Cloudant, no errors I just get an empty result. 

Am I missing something? 

Thanks again

**Comment by laurenkyla** [comment]
Ok got it working on both android and IOS with fresh Cloudant database. It won't work with a replicated database so it really must be that the original database has become corrupted. It would be good to find out how but here's hoping it doesn't happen again. 

Thanks

**Comment by daleharvey** [comment]
This happens a lot with opening the same database in different versions of the browser (profile downgrades), but in the situation you arent doing that its an indexeddb bug and nothing we can do in pouch to fix it, if you still have the database then opening a bug on chromium may be useful, thanks
