### ISSUE TITLE
How to handle nested arrays?

### ISSUE THREAD

**Issue by Renader** [pouchdb/pouchdb#5354]
### Environment (Node.js/browser/hybrid app/etc.)

Browsers

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

I'm not too familiar neither with pouchdb nor with document databases in general. But since this sync feature is magnificent I decided to use it. I have a database where user can store sets. Each set contains some basic informations and an array of subitems. Now I have the scenario that I want to edit a single subitem. Since the subitem has by default no unique identifier I'm struggling. on how to update the nested element. 

Is it possible to add another unique `_id` to each subitem when i create the objects? Or is my application design just wrong for this? I have a list screen, then a detail screen with an edit form. The edit-form only knows about the subitem. 

Since the subitems may be identical i can not use the content as unique identifier.

Thanks for any hint. And again: Great Job i really like PouchDB!

```

let set = {
                "_id": 213,
                "_rev": 1123,
                "title": "some set",
                "someText": "blahblahblah",
                "subitems": [
                    {
                        "title": " Some title",
                        "desc": "some desc"
                    },
                    {
                        "title": " another title",
                        "desc": "another desc"
                    },
                    {
                        "title": " blah title",
                        "desc": "blah desc"
                    },
                    ...
                ]
            };
```

**Comment by daleharvey** [comment]
You should add some form of identifier to the inner menu items if you want to update them, pouchdb treates the whole object as a single distinct object and doesnt do anything special with its contents. 

Closing this out as its not a pouchdb bug to track, but feel free to ask more questions if you want

**Comment by Renader** [comment]
@daleharvey thank you! I'll split my model up and store all sets and subitems in separate databases. This will limit my issues and improve the possibility to updated single sub items, especially with revision handling per subitem. **Or do you think this'd be bad practice?** Because for every _"get all sub items for set-xy"_ request i have to iterate across all stored sub-items.

**Comment by nolanlawson** [comment]
@Renader If you're constantly updating every document in your database and there are hundreds or thousands of them, then yeah it may be a bad design. If you want, you can keep the single document and then use [map reduce queries](http://pouchdb.com/guides/queries.html) for this.

**Comment by kierandesmond** [comment]
Hi All,
Thanks in advance for your help.

How would I go about querying a multiple level deep document. 

e.g.

` employers : { emp_23423432432 : { ........, cost_centres : { cc_12312312: {  activities: { act_1232312: {  } } } }`

Working with some deep documents with no real success with map reduce. I was thinking that the DB structure might need to be flattened using a pointer table to reference the other elements like cost_centres.

Some help & opinions would be  very welcome.

Thanks
Kieran
