### ISSUE TITLE
(Docs) markdown regression due to typography overhaul

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5359]
As noted on Twitter: https://twitter.com/optikfluffel/status/743462052849680384

It appears that anywhere we include an alert block, the markdown gets lost immediately afterwards. Since I didn't have time to look into this, I just reverted fdbaaf08e233e2b58de89981a596a505a256cd60. in a branch and did `npm run publish-site` as a hotfix. It's still broken in master.

/cc @nickcolley Sorry for not noticing this during the PR

**Comment by nolanlawson** [comment]
You can see this on both the custom.html page and the adapters.html page (it's particularly bad there).

**Comment by nickcolley** [comment]
Normally I've found this happens when there's whitespace issues. E.g. making sure there's no indentation and markup is on one line normally fixes these kinds of things.

Will try and sort this soon if someone else doesn't suss is out

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/1c4475fea51f6b8017212bf58955003c9706022e
