### ISSUE TITLE
special characters make chrome say: CORS requests are not allowed 

### ISSUE THREAD

**Issue by luxlux** [pouchdb/pouchdb#5361]
SHORT:
I have problems with special characters, which make chrome say: it's a CORS problem. but it isn't.

### Environment (Node.js/browser/hybrid app/etc.)
Browser & CouchDB

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)
Chrome on Mac 51.0.2704.84
Chrome on Android (WebView)

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)
IndexedDB

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)
CouchDB

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

I use pouchDB i.e. to store and transport data scanned from barcodes. It works well so far.
But now i have a problem. When scanning some internet stamp barcode from "Deutsche Post" i get something like this: DEA!,`כF�-y000010643307  (The codes are hex encoded). 
As soon as i have saved one of these codes using couch DB i always have a problem with syncing. Chrome console says:

pouchdb-5.4.2.min.js:8 
_XMLHttpRequest cannot load_ http://myserver.de:5984/new_products/DEA%12!%01%2C%60%D7%9B%00F%1A%EF%BF%…0%00%00?revs=true&open_revs=%5B%222-ddb09db0b5f22943f7e19fac0eef34c5%22%5D. _Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource._

But it is no Cross origin request.
I guess its a problem of encoding on the transport. Possibly a special character is the problem.

In CouchDB Webinterface Database overview the document key will be shown as:
"DEA\u0012!\u0001,`כ\u0000F\u001a�\u0000\u0001\u0000\u0000-\u0001\u0011y\u0000\u0000\u0000000010643307\u0000\u0000\u0000\u0000\u0000"

Unfortunately i can also not open the detail view of this document in couchDB webinterface. When i try this it tries to open this URL:
http://myserver.de:5984/_utils/document.html?new_products/DEA%12!%01%2C%60%D7%9B%00F%1A%EF%BF%BD%00%01%00%00-%01%11y%00%00%00000010643307%00%00%00%00%00

As result i get an alert:
> Error: The document could not be retrieved
> no response

The Problem with the XMLHttpRequest seams to begin at the place where the grey background ends:

`http://myserver.de:5984/new_products/DEA%12!%01%2C%60%D7%9B%0`0F%00F%1A%EF%B....

Why? When I try to open the URL on chrome until this character, i get a response from couchDB server. But if i add the next character (the "0") to the URL my request will be handled only as a search request.

**Comment by daleharvey** [comment]
Yeh chrome has a big problem with null characters in urls (http://venturebeat.com/2015/09/18/these-16-characters-crash-google-chrome/) we have seen this before with our map reduce implementation, I believe the only way around it is to avoid them

**Comment by luxlux** [comment]
Thanks for the quick feedback, daleharvey.

So what would you say should i do?
Substitute every 0 in keys with something else?
With what?
(possibly problematic for sorting)

**Comment by daleharvey** [comment]
its not the 0, but `%00`, which is the null character, I do think you will need to replace it, its not valid in chrome urls, remember I filed the bug against chrome 2 years ago - https://bugs.chromium.org/p/chromium/issues/detail?id=356924

**Comment by daleharvey** [comment]
And closing, as not a pouchdb bug, but if you have more questions feel free
