### ISSUE TITLE
v5.1.0 regression: Repeatedly checking for remote checkpoint.

### ISSUE THREAD

**Issue by gillez** [pouchdb/pouchdb#5379]
### Environment (Node.js/browser/hybrid app/etc.)

Browser running PouchDB with Couchbase Server via Couch Sync Gateway

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Chrome and Safari

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

default

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

Couchbase

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

When replicating a Couchbase database using PouchDB v5.0.0 and below, I get the following messages a couple of times:

pouchdb-5.0.0.min.js:9 GET https://localhost:4984/mydb/_local/LUNtUWldUuw9xS_mFgfzdg%3D%3D?_nonce=1466437383136 404 (Not Found) 
The above 404 is totally normal. PouchDB is just checking if a remote checkpoint exists.

As the message says, this is normal when initially replicating a database.

However, on PouchDB v5.1.0 and above, this message is repeated continuously every time a sync is attempted, i.e. every couple of seconds.

I believe this is a regression, but if it is deliberate behaviour, please let me know.

Thanks,
Giles

**Comment by daleharvey** [comment]
This was a specific change https://github.com/pouchdb/pouchdb/issues/5145, before `5.1.0` we didnt update the checkpoint if there were no changes to process however that meant reprocessing a potentially large amount of documents repeatedly. 

However a possible improvement would be to check that the checkpoint actually needs updating before doing so

**Comment by gillez** [comment]
Hi Dale, thanks for the explanation.  Do you think the possible improvement that you suggest is easy to do and would it cause any issues?

**Comment by daleharvey** [comment]
It should be reasonably easy to implement that improvement, you can see in the previous patch where the code would need edited, mostly https://github.com/pouchdb/pouchdb/commit/f1989ce6361193f1e213cb0b17e7dab4f2a8451c#diff-1b1f318b599e364220cdb8ac006c238bR307 would need to check the last_seq vs the previously stored one

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/0d384e848f0ec5238c2f816393b5535ae2bb0d6e
