### ISSUE TITLE
option to specify DB path when creating pouch db

### ISSUE THREAD

**Issue by ambercool99** [pouchdb/pouchdb#5383]
### Server : Local DB, No Server here

How can i specify the path when creating DB in Android/IOS?
if Not...
whats the default path for DB storage in Android/IOS app.

**Comment by nolanlawson** [comment]
IndexedDB/WebSQL by default are stored where browser data is stored; I forget off the top of my head, but I believe it's under `databases` or something. In general you're not supposed to modify that; it's considered browser-internal data. And you cannot modify it.

Another option is to use the SQLite Plugin or SQLite Plugin 2, which gives you more direct native access to the database file. The SQLite Plugin 2 docs have [lots of info](https://github.com/nolanlawson/cordova-plugin-sqlite-2#where-is-data-stored) about where data is stored.

SQLite Plugin 1 gives you the `location` option which allows you to specify a custom location, whereas SQLite Plugin 2 only lets you store it in one place. Let me know if that info helps!
