### ISSUE TITLE
Response for preflight has invalid HTTP status code 405

### ISSUE THREAD

**Issue by AvraamMavridis** [pouchdb/pouchdb#5397]
### Environment (Node.js/browser/hybrid app/etc.)

Browser

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Chrome, Version 51.0.2704.103 (64-bit)

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

CouchDB

### Description

I have enable cors in CouchDB

<img width="1180" alt="screen shot 2016-06-24 at 06 26 45" src="https://cloud.githubusercontent.com/assets/283690/16327910/b4b72230-39d4-11e6-93dc-6a5795161ef9.png">
<img width="1172" alt="screen shot 2016-06-24 at 06 27 03" src="https://cloud.githubusercontent.com/assets/283690/16327911/b4b92c1a-39d4-11e6-84db-14eb16ca4128.png">

And I am trying to a simple `PUT`

```
db.put({
  _id: 'anid',
  title: 'Something'
}).then(function (response) {
  PouchDB.sync('localdb', 'remotecouchdb');
}).catch(function (err) {
  console.log(err);
});
```

But I am getting **Response for preflight has invalid HTTP status code 405**  Any help highly appreciated :)

**Comment by nolanlawson** [comment]
This occurs when you need to enable CORS in CouchDB. Please check out https://github.com/pouchdb/add-cors-to-couchdb <https://github.com/pouchdb/add-cors-to-couchdb> and https://pouchdb.com/errors.html#no_access_control_allow_origin_header <https://pouchdb.com/errors.html#no_access_control_allow_origin_header> .

**Comment by avraam-mavridis-sociomantic** [comment]
https://github.com/pouchdb/add-cors-to-couchdb worked greatly. I forgot to close it. Thx.
