### ISSUE TITLE
How do you deal with offline copy of remote server?

### ISSUE THREAD

**Issue by ceremcem** [pouchdb/pouchdb#5419]
This is a question, rather than a bug report. 

How does PouchDB deal with synchronization stuff? I mean, what if the remote database has a size of 1234GB? Will PouchDB sync all of the documents into the **browser**?

**Comment by dharders** [comment]
> Will PouchDB sync all of the documents into the browser?

By default, it will _attempt_ to. Of course, there are browser storage limitations, so you'll no doubt hit a wall at some point. 

I think you're after [Filtered Replication](https://pouchdb.com/api.html#filtered-replication)

**Comment by ceremcem** [comment]
Yes, probably that's the facility I was looking for. Thank you.
