### ISSUE TITLE
bad js-extend ver in package.json?

### ISSUE THREAD

**Issue by chanes-probe** [pouchdb/pouchdb#5430]
Starting in 5.4.0, package.json has
 `   "js-extend": "0.0.1",`
where previously it had
`    "js-extend": "1.0.1",`

This is showing up in the release download zips and also when I install via npm.  I don't see the bad version number in the git history so I speculate it has something to do with the build process?

**Comment by chanes-probe** [comment]
Actually I see the diff occurring in commit c4264ba8a6de4a4c16607e14d7b60e77c8b6f311 if I checkout out the tag 5.4.0 and commit c61d0b7bcfdbe15b9149705fd238ddfebefb34fa if I checkout tag 5.4.4.  It's just not in master..

**Comment by nolanlawson** [comment]
Thank you; it's a typo. We'll fix it.

**Comment by nolanlawson** [comment]
^ https://github.com/pouchdb/pouchdb/pull/5431

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/abdeb1c15e8ec25679463044dea87fc3c8569684
