### ISSUE TITLE
How can I get /_session document? 

### ISSUE THREAD

**Issue by ceremcem** [pouchdb/pouchdb#5461]
I need to make some actions based on session information, but I can't use appropriate plugin right now (https://github.com/nolanlawson/pouchdb-authentication/issues/110).

How can I get "https://example.com/_session" document via `db.get()` or something? 

## Which doesn't work: 

```
db = new PouchDB 'https://example.com/mydb'

err, res <- db.get '/_session'
err, res <- db.get '_session'

**Comment by daleharvey** [comment]
The plugin is the way to get it, you can either use the plugin or direct xhr calls to the url, the pouchdb api purely exposes the storage related apis of couchdb, not the application level things

**Comment by ceremcem** [comment]
Hmm. Ok, thank you.
