### ISSUE TITLE
Error in attachments

### ISSUE THREAD

**Issue by matikbird** [pouchdb/pouchdb#5464]
i'm getting a really odd error when I try to get the attachment.

```
  getfile: function(id, file){
            db.get(id, {attachments: true}).then(function(doc) {
              return doc;
          }).then(function(here) {
            return db.getAttachment(here.id, file, here._rev);
// tried also with {rev: here._rev}
          }).catch(function(err){
            console.log("error :(");
            console.log(err);
          });
          }, 
```

This is what I get:
**_DOMException: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
    at Error (native)_**

To put an attachment, I use:

```
 db.get(id).then(function(doc) {
            var buf = new Buffer(base64, 'base64'); 
            console.log(doc)
            //tried also with buf instead of base64 var
             db.putAttachment(doc._id, 'cover.png', doc._rev, base64, 'text/plain').then(function(res) {
                  console.log(res);
              }).catch(function(err){ return console.log(err); });
           }).catch(function(err){ return console.log(err); });
```

Now, the return of the db.get actually shows the attachment there, like so:
![screenshot_2016-07-11_01-40-40](https://cloud.githubusercontent.com/assets/12424545/16720045/8346c048-4708-11e6-8ae6-ad6d00539c37.png)

But I can't use it..
This is really weird

**Comment by injectless** [comment]
This is the object that returns **_db.getattachment_();**
![screenshot_2016-07-11_01-46-05](https://cloud.githubusercontent.com/assets/12424545/16720118/5064d4f2-4709-11e6-98e2-c651b9e42469.png)

**Comment by nolanlawson** [comment]
Hi, I already gave a brief comment in https://github.com/pouchdb/pouchdb/issues/2876#issuecomment-231768406, but in case that doesn't solve your issue, could you please post a test to reproduce? Based on screenshots and code samples it seems possible to reproduce, but we don't have enough information here to work with. Also it would be helpful to know what browser/adapter/OS you're using.

**Comment by injectless** [comment]
I decided to not use attachments until 0.2v, thanks for your fast reply tho, @nolanlawson 

I'm working on an open source project based on PouchDB, like an "Office" but with web-technologies, here's a screenshot:
![screenshot_2016-07-11_20-43-01](https://cloud.githubusercontent.com/assets/12424545/16750442/24a7300e-47a8-11e6-840b-69e1b217ab7b.png)

I'll let you know in a few weeks when I release the code on Github so you can reproduce it if you want.
