### ISSUE TITLE
Weekly meeting notes, Tuesday 12 July 2016

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5470]
The goal of this issue is to jot down meeting notes from today's weekly meeting. Please feel free to comment below, even if you missed the meeting. 😃 This issue should be closed in a few days or so.

[Full IRC log](https://botbot.me/freenode/pouchdb/2016-07-12/?msg=69519005&page=2)

## Where/when

IRC/Slack, 4pm-5pm UTC

## Attendees

- @daleharvey 
- @nolanlawson

### Status report

- Dale: spending most time on triage, want to get to 0 open bugs
- Dale: many of the bugs are unactionable
- Nolan: let's use the "needs reproducing" and "has test case" labels for those
- Dale: issue template should tell users to do `PouchDB.debug.enable('*')`
- Nolan: also mostly spending time on triage, 40% of bugs are plugins or non-Pouch projects

### Upcoming releases

- Nolan: roadmap in my mind is 6.0.0 which is a big deprecation release, then 7.0.0 which is idb-next
- Dale: yes, pouchdb-find support in idb-next will take a long time
- Nolan: yes, pouchdb-find should be developed in tandem to idb-next
- Nolan: three things I want to do for idb-next: 1) evaluate perf, 2) evaluate compat, take up [idb-iegap](https://github.com/dfahlander/idb-iegap) if necesary for Edge, 3) implement migration plugin (or maybe just use `replicate()`?)
- Dale: I can help with migration

### Documentation

- Nolan: docs have fallen into a bit of disrepair, would do it myself but these are good "first issues"
- Dale: almost half our open issues are improvements to the docs
- Nolan: "getting started" needs a refresh, want to shoot a new video using Digital Ocean + Docker + CouchDB instead of IrisCouch (now defunct)
- Dale: good plan, IrisCouch is out of date
- Nolan: need docs/guide on pouchdb-find too, general docs cleanup
- Nolan: ultimate problem is we need new blood and a clear roadmap
- Nolan: I'd like to start a weekly Hangout rather than IRC meeting and start hammering out a roadmap
- Nolan: the Hoodies do this, seems to work
- Dale: ok, need to renegotiate time if doing a Hangout

### Weekly Hangout

(discussion about time zones, Nolan is PST and Dale is GMT, eventually settle on 6pm UTC every Monday)
- Nolan: I'll work on a blog post about the new roadmap and Hangout meeting, we can market the Hangout via Twitter for now
- Dale: doing an initial one with a twitter announcement then writing a blog post about it sounds great
- Dale: gonna be some noise with this idb-next PR, managed to get github / travis in a bit of a mixup
(cheers all around, meeting adjourned)

**Comment by dariocravero** [comment]
This open collaboration approach is amazing guys! Well done!! :D
