### ISSUE TITLE
PouchDB.plugin() should throw a helpful error if you pass in the wrong type

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5471]
I've done this so many times to myself, it's not even funny:

```js
var PouchDB = require('pouchdb-core')
  .plugin('pouchdb-adapter-memory')
  .plugin('pouchdb-adapter-http')
  .plugin('pouchdb-replication');
```

Of course what I meant to do was:

```js
var PouchDB = require('pouchdb-core')
  .plugin(require('pouchdb-adapter-memory'))
  .plugin(require('pouchdb-adapter-http'))
  .plugin(require('pouchdb-replication'));
```

When you make this mistake, though, you get a really unhelpful error about "Adapter is missing." I wasted a lot of time trying to hunt it down before realizing I passed in a string to `plugin()` instead of an object/function like it's supposed to take.

I believe we should throw a more helpful error inside of `PouchDB.plugin()`. In particular, if you pass in a non-function (i.e. an object) that doesn't have any `Object.keys()` (i.e. length of 0), then it's probably an invalid plugin and we should throw. This should guard against similar mistakes.

See [Plugin API](http://pouchdb.com/api.html#plugins) and [Custom Builds](https://pouchdb.com/custom.html) for more info on how this is supposed to work.

**Comment by nolanlawson** [comment]
For first-timers who want to tackle this, you would need to add a test to `test.basics.js`, and also modify the `plugin` code here: https://github.com/pouchdb/pouchdb/blob/9e370d492ed1aba57db069ca98205eb50de6ad92/packages/pouchdb-core/src/setup.js#L45-L54

**Comment by nolanlawson** [comment]
The test should probably only run in Node.js; you can check for this by doing `if (typeof process !== 'undefined' && !process.browser)`.

**Comment by nolanlawson** [comment]
If you'd like any help with this issue, please come to the PouchDB Slack channel (http://slack.pouchdb.com/) and ask for help; otherwise the best source of information for getting started is in `CONTRIBUTING.md` and `TESTING.md`.

**Comment by nolanlawson** [comment]
As for how to write a Mocha test that checks that an error is thrown, I like to use this pattern:

```js
doSomethingThatOughtToThrow().then(function () {
  throw new Error('expected an error here!')
}, function (err) {
  should.exist(err);
});
```

^ This will fail if the function in question _doesn't_ throw an error.

**Comment by eraserxp** [comment]
Hi Nolan. I would like to work on this.

**Comment by nolanlawson** [comment]
Hi @eraserxp please go ahead. :)

**Comment by wholien** [comment]
Hey, this doesn't seem like it's been touched in a while. Can I take it? Interested in contributing, but if @eraserxp is still on it then I'll look at something else.

**Comment by nolanlawson** [comment]
By all means! :) First one to submit a PR wins. ;)

**Comment by wholien** [comment]
@nolanlawson any clue on how to `doSomethingThatOughtToThrow()` ? My code (https://github.com/pouchdb/pouchdb/compare/master...wholien:5471-plugin-error#diff-59ca71ccb9844015956805543881c67dR1118) doesn't end up triggering the error. I've also tried `db.info()`, as well as ruling out some other ones (such as `PouchDB.plugin(...)` as it's not a function). Any tips would be appreciated

**Comment by nolanlawson** [comment]
Because of the way Promises work in Mocha, I think you'll need to wrap the beginning part in `return Promise.resolve().then(function () { /* put your code here */})`. Although honestly I'm surprised, because I think if a synchronous error gets thrown there, that Mocha would normally fail...

**Comment by nolanlawson** [comment]
Fixed in https://github.com/pouchdb/pouchdb/pull/5569/commits, thank you @wholien !
