### ISSUE TITLE
Error: IndexedDB Adapter not supported in iOS 10

### ISSUE THREAD

**Issue by marcelgoya** [pouchdb/pouchdb#5472]
Since iOS 10 has full support for all IndexedDB features, it would be nice if we could use it instead of WebSQL

**Comment by daleharvey** [comment]
I am working on an indexeddb adapter specifically with ios support in mind @ https://github.com/pouchdb/pouchdb/issues/5207, the current implementation of indexeddb on ios is still failing tests

**Comment by marcelgoya** [comment]
Awesome, thanks for letting me know
