### ISSUE TITLE
websql size limit

### ISSUE THREAD

**Issue by chino23** [pouchdb/pouchdb#5473]
I can't find any info on the size limit on websql on chrome.

https://pouchdb.com/faq.html only talks about the main adapter, being IDB, which is basically limitless (= hdd space).

Since websql seems to be so much damn faster than idb, i'm unfortunately stuck with it.

Is there a limit in size I have to worry about?

**Comment by nolanlawson** [comment]
Yes, there is a limit to WebSQL in Chrome. You can find that information here, cheers; http://www.html5rocks.com/en/tutorials/offline/quota-research/

**Comment by chino23** [comment]
Thanks Nolan, as always quick to reply with helpful infos.
