### ISSUE TITLE
Very slow to query a simple reduced view

### ISSUE THREAD

**Issue by natcohen** [pouchdb/pouchdb#5475]
### Environment (Node.js/browser/hybrid app/etc.)

Browser - PouchDB 5.4.5

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Chrome

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

Default

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

CouchDB 1.6.1

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

I'm using a view in CouchDB that does the following:

```
function(doc) {
   if(doc.type == 'cover' && doc.invoice){
     if(doc.invoice.accounted){
       emit([doc.entityID, doc.invoice.currency], doc.invoice.date);
     }
   }
   if(doc.type == 'damPayment' || doc.type == 'isoInvoice' || doc.type == 'payment'){
     if(doc.accounted){
       emit([doc.entityID, doc.currency], doc.date);
     }
   }
}
```
And is reduced using:
```
function (key, values, rereduce) {
   var date = '1800-01-01T00:00:00.000Z';
   for(var int = 0; int < values.length; int++){
      if(date < values[int]){
         date = values[int];
      }
   }
   return date;
}
```
In CouchDB this view takes few milliseconds to display (I have about 3500 docs and the result is 30 docs) but with PouchDB it's taking 60 to 120 seconds and chrome takes 50% of my CPU (on windows 10 - task manager)

Here is what I do to get the view in the browser:

`pouch.query('last_accounted', {group: true}, (err, doc)=> {...`

FYI this is not the only view that's taking long to display but this one takes the longest. I'm wondering if it has to do with the 'reduce'.

**Comment by daleharvey** [comment]
We dont cache the output of reduce, so in your case this query is running through all the documents emitted by the map (it looks like most of them?) and running the reduce on them. 

What is that reduce asking for in english terms? seems like it could be done without the reduce

**Comment by natcohen** [comment]
Well... Trying to get the max date. Should I do this in memory?

**Comment by daleharvey** [comment]
if you had an index ordered by date then it would be fast, so something like:
```
var cover = (doc.type == 'cover' && doc.invoice && doc.invoice.accounted);
var payment = ((doc.type == 'damPayment' || doc.type == 'isoInvoice' || doc.type == 'payment') && doc.accounted);

if (cover || payment) { 
  emit(doc.date);
} 
```

**Comment by daleharvey** [comment]
If you can figure out how to construct that query against http://nolanlawson.github.io/pouchdb-find/ I would recommend it, right now it will still incur the cost of building the index, but we are looking to remove it, its also a simpler way to build the indexes

**Comment by daleharvey** [comment]
And it sounds like you may know, but just in case, the first time a query runs it builds the entire index so it can be very slow, subsequent reads are cached on disk so should be fast, its best to test a second read at least

**Comment by natcohen** [comment]
Right... I knew about the index creation.

Your proposed solution doesn't really help because the purpose of the reduce is to group my results! I will try to play with the different solutions.

**Comment by natcohen** [comment]
@daleharvey I maybe missed it but I think it would be good to write it somewhere that reduce results are not cached and that it will be very slow.

**Comment by natcohen** [comment]
@daleharvey You said in this thread "but we are looking to remove it (ndrl building the index), its also a simpler way to build the indexes". I can't find any discussion about removing the index creation (btw it would be awesome) so where can I track this?

**Comment by nolanlawson** [comment]
This is what the "idb-next" adapter is designed to solve. In PouchDB 6.0.0 we'll ship an experimental `pouchdb.next.js` that you can play with, and hopefully in 7.0.0 we'll be able to ship it as the default adapter.

See https://github.com/pouchdb/pouchdb/issues/5207
