### ISSUE TITLE
pouchdb mangles base64 on `db.get(id, {attacments: true})`

### ISSUE THREAD

**Issue by Jan-Jan** [pouchdb/pouchdb#5480]
Thank you for PouchDB!

### Environment (Node.js/browser/hybrid app/etc.)

React-native

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

iOS (react-native)

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

WebSQL

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

CouchDB (replication works)

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

I upload a jpg in base64 to CouchDB (with `content_type` either `text/plain` or `image/jpeg`).
I look inside CouchDB (using _utils), the attachment is the correct base64 encoding.
CouchDB syncs with PouchDB
However, on the react-native side, when I do
```
db.get(id, {attachments: true})
```
Then the resulting `doc`'s `_attachments`'s `data` contains a different string (ie, it appears to have been mangled).

**Comment by daleharvey** [comment]
Is there any chance you could write minimal application that reproduces this bug? Bugs like these are very environment specific so its hard for us to see what is happening without being able to reproduce, cheers

**Comment by nolanlawson** [comment]
PouchDB does not officially support React Native. Are you using a third-party plugin? My guess is that the bug lies in the plugin itself. https://github.com/stockulus/pouchdb-react-native ?

**Comment by Jan-Jan** [comment]
Thanks for getting back to me.

Actually I'm using https://github.com/carbureted/react-native-pouchdb

I will attempt to write minimal application reproduce it, and revert asap.

**Comment by Jan-Jan** [comment]
My apologies, I've not been able to get this going for you in a minimal application.
I've reimplemented everything from https://github.com/carbureted/react-native-pouchdb into https://github.com/stockulus/pouchdb-react-native -- now I can't even get basic syncing working :'(

I will revert if I think it is a PouchDB rather than pouchdb-react-native error.

**Comment by nolanlawson** [comment]
There is also a way to use SQLite on React Native you can try: https://github.com/pouchdb/pouchdb/issues/3787#issuecomment-234618747

But in general we don't have 1st-class support for RN; just some folks who put together third-party adapters.
