### ISSUE TITLE
Sync downloads attachments multiple times on Safari

### ISSUE THREAD

**Issue by ssured** [pouchdb/pouchdb#5482]
### Environment (Node.js/browser/hybrid app/etc.)

Browser

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

both
Safari iOS 9.3.2 -> fruitdown, bot on a real device and in simulator
Safari OSX 9.1.1 -> websql

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

CouchDB 1.6

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

When syncing a remote database with Safari, syncs took longer than on other android devices. This made me look into what happened in the logs. To my surprise the sync re downloaded attachments from my app multiple times. This happens in documents with 100+ attachments, maybe with less, but I am still investigating.

I'm on this to narrow the problem down. Attached is the server `_log` from iOS syncing to a production DB. Tomorrow I'll try to replicate this behaviour with a smaller db. No other dbs were connected or syncing during these logs.

https://gist.github.com/ssured/fd9ccad81c65f3b8f539fc94d9d227de

In the logs I checked 8 attachments, each belonging to another document:

`t5b2c/thumb%7Cpng` is downloaded 1 time
`tusnw/thumb%7Cpng` is downloaded 1 time
`tbrmd/thumb%7Cpng` is downloaded 2 times
`tf6x1/thumb%7Cpng` is downloaded 3 times
`t7ru0/thumb%7Cpng` is downloaded 4 times
`tv8eu/thumb%7Cpng` is downloaded 5 times
`tdnhx/thumb%7Cpng` is downloaded 3 times
`t0tgm/thumb%7Cpng` is downloaded 3 times

This completely makes no sense to me, yet... Maybe someone can help? What could be happening?

Please let me know what more info could be useful

**Comment by nolanlawson** [comment]
Hm, this tells me there is probably either a bug in the WebSQL adapter or in the FruitDOWN adpater. Does it happen in both of them?

And yeah, if you can make a small reproducible app to show what's going on, that would be really helpful. I imagine it's an md5summing issue, but it's hard to debug without a test case. Thanks!

**Comment by ssured** [comment]
Till now I have not found the real cause, but some indicators:

- This issue seems not affected by the adapter. I get breaks in almost every browser-adapter combo.
- Latency probably has something to do with it. Localhost performs better than a beefy remote server

My current hypothesis is that the DB I am syncing is just unlucky to hit some limits; just too many attachments in too little document. Which made me look into #5375. To my surprise the code there does not execute when I replicate from a remote HTTP to a local db (indexeddb, websql or fruitdown).
I manually replaced the `fetchAttachments` function below to test. This did not log anything to the console

```
    function fetchAttachments(doc) {
      var atts = doc._attachments;
      var filenames = atts && Object.keys(atts);
      if (!atts || !filenames.length) {
        return;
      }
      // we fetch these manually in separate XHRs, because
      // Sync Gateway would normally send it back as multipart/mixed,
      // which we cannot parse. Also, this is more efficient than
      // receiving attachments as base64-encoded strings.
      function fetch() {

        if (!filenames.length) {
          return null;
        }

        var filename = filenames.pop();
        var att = atts[filename];
        var path = encodeDocId(doc._id) + '/' + encodeAttachmentId(filename) +
          '?rev=' + doc._rev;

        window.openFilesCount = (window.openFilesCount || 0) + 1;
        console.log('fetching', window.openFilesCount, path);
        return ajaxPromise(opts, {
          method: 'GET',
          url: genDBUrl(host, path),
          binary: true
        }).then(function (blob) {
          if (opts.binary) {
            return blob;
          }
          return new PouchPromise(function (resolve) {
            blobToBase64(blob, resolve);
          });
        }).then(function (data) {
          window.openFilesCount -= 1;
          console.log(' fetched', window.openFilesCount, path);
          delete att.stub;
          delete att.length;
          att.data = data;
        });
      }

      // This limits the number of parallel xhr requests to 5 any time
      // to avoid issues with maximum browser request limits
      return new PromisePool(fetch, 5, {promise: PouchPromise}).start();
    }
```

My thought now are that rate limiting of attachment downloading during replication is not properly managed. The amount of concurrent connections causes ETIMEDOUT errors, which then triggers another replication of the document?

That's it for today... Hope someone can confirm this too? Thanks

**Comment by ssured** [comment]
Ok so I have a temporary fix; setting the `ajax: {timeout: 60000}` option on the constructor seems to work (at least in the Simulator). Tomorrow I'll test on an actual device.

I also quickly made a global concurrency limit in pouchdb-ajax, which (together with the timeout) seems to fix the problem. Some handles on rate-limiting seems the way to go for me.

Thanks for all your endless work on PouchDB, its more than awesome!

**Comment by ssured** [comment]
I am testing with handling concurrency, by replacing https://github.com/pouchdb/pouchdb/blob/ca05e22a0f5dc8a38839cc8029cca7da171a9d06/packages/pouchdb-adapter-http/src/index.js#L529-L545 with https://gist.github.com/ssured/2b9e26ef797ee7db17ac13bcd2d2a78f

Right now I am pretty sure the number of connections is the exact problem. The DB consists of 20 documents, where 12 of those contain 200 small png attachments. This leads to 2000+ open connections when syncing. Browsers handle this very different. Chrome seems mostly fine (works on desktop and tablet). Safari is not so pleased and cancels some connections, both on desktop and mobile.

Current approach I am trying now is browsersniffing for Safari. If Safari is detected, I do a special one-by-one document sync for all documents containing more than one attachment. My hopes are that circumvents the issue at hand.

BTW. I used to use pouchdb-dump, which is awesome, but again Safari cannot handle 30mb dump files...

**Comment by ssured** [comment]
Closing in favor of #5486
