### ISSUE TITLE
Feature request: add _id to 404/409 response

### ISSUE THREAD

**Issue by ssured** [pouchdb/pouchdb#5490]
### Environment (Node.js/browser/hybrid app/etc.)

All
### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

All
### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

All
### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

All
### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

For debugging & logging purposes it would be nice to reference the `_id` of documents in various `???PouchError` objects. Errors like `CustomPouchError {status: 404, name: "not_found", message: "missing", error: true, reason: "missing"}` are sometimes helpful, but I often have the need to know which document it was. Same holds for a 409 conflict.

I know I could fix this by adding more granular error checking, but when quickly coding I am often lazy and only add a `.catch(=>)` at the end of a promise chain.

**Comment by ssured** [comment]
BTW this holds less for the HTTP adapter, where you can always use the network tab of your browser. For the local adapters this comes in quite handy, as it is hard to traceback what happens in your indexeddb/websql/localstorage.

**Comment by daleharvey** [comment]
There are some situations where we add information like this to error response, I think easing debugging would be a good thing here

**Comment by danielo515** [comment]
In an async world this is definitively a help.

**Comment by ZeroNine00** [comment]
Have someone a workaroubd for this ?  I need the info for 404 to see which request was failed

**Comment by daleharvey** [comment]
For a workaround, you can pass the information around when you call the `get`

```js
db.get(id).then(gotDoc).catch(notFound.bind(id));
```

**Comment by ZeroNine00** [comment]
Sorry can you  explain your workaround a little bit more ? 
At the moment I have only Callbacks ... 

for (var i = 0; i < aEntries.length; i++) {
// Here I need a check against pouchdb
// Somethine like this ? 	thatDocument._oUiComp._opdbmat.get(aEntries[i].key.matnr).then().catch(notFound.bind(id));
}

**Comment by daleharvey** [comment]
You need to add context to the error callback that tells the function what id you were originally looking for, my `.bind` version wont actually work, but its a common requirement in javascript especially when dealing with loops, http://stackoverflow.com/questions/750486/javascript-closure-inside-loops-simple-practical-example may help

**Comment by ZeroNine00** [comment]
thx,

I tried with 

var funcs = [];
			
```
			for (var i = 0; i < aEntries.length; i++) {
				funcs[i] = thatDocument._oUiComp._opdbmat.get.bind(this,aEntries[i].key.matnr, thatDocument.validateMatNrPosOnSave);
			}
			
			for (var j = 0; j < aEntries.length; j++) {
					funcs[j]();
			}
```


But I get this error from pouchdb.

Cannot read property 'isReady' of undefined a

**Comment by alxndrsn** [comment]
+1 for adding `_id` to 404s.  Is there any obvious reason why it would be difficult or controversial to implement?  If not, I might have time next week.

**Comment by alxndrsn** [comment]
Potential patch for the IDB adapter at https://github.com/pouchdb/pouchdb/compare/master...alxndrsn:include-id-in-404?expand=1.

It doesn't really feel like the correct place to be fixing this, so if anyone's got any guidance it would be appreciated.  This patch took me less time to write than I spent debugging an app to find the ID of a missing doc, so I'm very interested in getting this issue closed.

**Comment by ssured** [comment]
@alxndrsn I like the simplicity and I'd love to have this included as an 'undocumented unofficial feature'. Maybe we can rename the property as `err.__unofficial_document_id = id` to help us out here and indicate that this will change... Very messy but practical solution IMHO.

**Comment by daleharvey** [comment]
https://github.com/alxndrsn/pouchdb/commit/4542c8a4690a134138a7c750e80c7e192778ae01 has fixed this for 404's, if anyone wanted to follow that commit and test / fix for 409's it should be straightforward

**Comment by alxndrsn** [comment]
@daleharvey I intend to tomorrow 😄

**Comment by daleharvey** [comment]
And done, thanks @alxndrsn  :) 

https://github.com/pouchdb/pouchdb/commit/3bba74a80d00d42af75b9651557c58e92f3b02cf
