### ISSUE TITLE
Using PouchDB in Electron.

### ISSUE THREAD

**Issue by thefakegm** [pouchdb/pouchdb#5496]
### Environment (Node.js/browser/hybrid app/etc.)

Electron version 1.2.8

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Not applicable

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

I've tried them all.

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

Not applicable.

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

Hey guys,

I'm having trouble with PouchDB in electron. I'm want to use PouchDB in the main process as opposed to the renderer. But I'm not sure if it is working. If I use new PouchDB(path) I get the following error: Module version mismatch. Expected 48, got 47. This wasn't that unexpected, I have had this happen before. 

Then I tried using websql. That gives no errors (as far as I can see) but if I try to debug the database with something as simple as db.info().then(console.log.bind(console)) I get nothing. I tried this in a test script which I ran in Node and that worked fine.

I also tried installing sqlite3 and building the binaries for linux using electron-rebuild. Which didn't improve anything as far as I noticed. 

Here is a link to my github project:  https://github.com/thefakegm/GifDB

to run this just 

npm install
npm run watch
npm start
PouchDB lives in src/util/database.js

I used intellij for the debugging of the app.

What I want to accomplish is having PouchDB run in the main process. I know I can make this work in the renderer process but that seems like bad practise.

If you need anything more from me just ask.
Thanks in advance for any advice.

**Comment by blmarket** [comment]
some of pouchdb dependency contains native node modules, but they are built against your node version which may be different with your electron version. so you should make...

1. recompile your module against electron version([document](http://electron.atom.io/docs/tutorial/using-native-node-modules/)), or
2. update your node version to match with electron (maybe painful in some times...)

personally I'm using `postinstall` script to recompilation.

**Comment by thefakegm** [comment]
@blmarket I tried the postinstsall script and it worked, thank you!

For anyone who stumbles across this.

1. Install node-gyp with ```npm install --global node-gyp```
2. Add a postinstall script to your package.json. I used to following.

```cd node_modules/leveldown && HOME=~/.electron-gyp node-gyp rebuild --target=1.2.6 --arch=x64 --dist-url=https://atom.io/download/atom-shell``` 

Change the ```-target=``` to your electron version.

That did the trick for me. 

Thanks again!

**Comment by daleharvey** [comment]
Awesome, thanks for the help @blmarket, if theres anything pouchdb can do to make this easier then happy to see a PR, but sounds like this needed for the electron side. Cheers
