### ISSUE TITLE
rereduce always = false in reduce

### ISSUE THREAD

**Issue by matteogrolla** [pouchdb/pouchdb#5497]
Hi,
     if I understood well from
https://pouchdb.com/2014/06/17/12-pro-tips-for-better-code-with-pouchdb.html
  (you probably don't need reduce) and
https://github.com/pouchdb/pouchdb/issues/2941

reduce are recomputed every time from the outputs of map
This impacts the way I'd like to model documents:
Using the bank example (http://guide.couchdb.org/draft/recipes.html) couchdb suggests to index the individual transaction as docs and get the balance using a view.
My problem with this approach on couch is that if I have a lot of transactions they all have to be summed up every time I want the balance, even if nothing changed since last time.
On Couch, which uses b-tree to compute the reduce, nothing needs to be computed if if no transaction were added since last time I viewed the balance and only few computation need to be done if few transactions were added.
Please tell me if I've got it right and what's the suggested way to model the bank example in pouch (or if it's possible to model it efficently)

### Environment (Node.js/browser/hybrid app/etc.)

(Write here.)

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

(Write here.)

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

(Write here.)

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

(Write here.)

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

(Write here.)

**Comment by daleharvey** [comment]
You are right, the recipe in that document doesnt really apply to pouchdb, our map reduce functionality is not as comprehensive as CouchDB's and in future we will be looking more towards `pouchdb-find` as a replacement for map reduce (https://github.com/nolanlawson/pouchdb-find). For your example I would depending on your requirement still keep a transaction log, but also manually keep track of the sum in a seperate document.

**Comment by matteogrolla** [comment]
Thanks Dale,
  can you elaborate more on your proposed solution?
the summary document is affected either by local edits and from edits coming from replication and to be consistent with the transaction log (also in case of conflicts) the summary document must be  locally generated from the transaction log. 
So it seems to me that I have to implement something similar to the couchdb solution where the reducer output keeps track of the mapper outputs that contributed to it and can be built incrementally using other reducer output.
If there's a simpler solution that is efficent and uses the trahsaction log being consistent with it please let me know
