### ISSUE TITLE
ETIMEOUT error arises often

### ISSUE THREAD

**Issue by ceremcem** [pouchdb/pouchdb#5498]
### Environment (Node.js/browser/hybrid app/etc.)

Browser 
### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Chrome, FF on Windows, Linux (Debian)
### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

No local db is used (http)
### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

Cloudant
### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

Similar to https://github.com/pouchdb/pouchdb/issues/5114 , after a while, `ETIMEOUT` error arises. I removed the local database instance, the error still persists. 

One interesting thing is that, I can not see the welcome message when I visit https://example.cloudant.com (it tries to load forever) and when I restart my browser, everything starts working again. 

Versions are: 

```
    "pouchdb": "^5.4.5",
    "pouchdb-authentication": "^0.5.3",
```

**Comment by ceremcem** [comment]
I created many javascript instances which displays given views directly from database and watches for changes on their own. 

I suspected that these instances causes many concurrent connections and this hits the browser limit. So I removed these component's `db.changes().on('change', function....` parts, everything seems to work ok. 

If this is the case, then 

# Proposal: 

PouchDB seems to open one request per  `db.changes().on('change', function...` call. It should create only one request and fire all functions registered via `.on('change, ` function.

**Comment by daleharvey** [comment]
So how many changes requests are you making? its possible for Pouch to deduplicate these under the hood however its a fairly large amount of work considering pouchdb's underlying architecture whereas it should be easier for the application to do so. In general I lean towards pouchdb doing what the user tells it to which gives pouchdb less complexity and leaves more flexibility for the user to optimise for their use case as opposed to things changing under the hood.

**Comment by ceremcem** [comment]
There were 6 visual components at that time (but I didn't plan to dictate any limit on that). 

It's your call, but I would expect a `console.log` warning at least.

**Comment by ceremcem** [comment]
I started to get these `ETIMEOUT` errors very frequently. What is the limit in request frequency?

**Comment by anowak** [comment]
The HTTP 1.1 spec says the limit is 2 connections per domain. However, browser vendors seem to be more [liberal](http://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser/985704#985704). No official documentation on the topic is to be found though.

**Comment by nolanlawson** [comment]
Closing, please provide a test case to reproduce if you can and then we'll reopen. Thanks!

**Comment by tengfei-blacksketch** [comment]
```
const path = require('path')
const express = require('express');
const PouchDB = require('pouchdb-node');
const expressPouchDB = require('express-pouchdb');

const app = express();

app.use(expressPouchDB(PouchDB));
app.listen('5984');
```


```
curl 'http://localhost:5984/fetchman/' -X PUT -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'Content-Length: 0' --compressed
curl 'http://localhost:5984/fetchman/projects' -X PUT -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' --data-binary '{"_id":"projects","localId":"d18ace80-68e3-11e8-91f8-ff639fd327a6","state":[]}' --compressed
curl 'http://localhost:5984/fetchman/_changes?include_docs=true&feed=longpoll&heartbeat=10000&filter=_doc_ids&since=1&limit=25' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' --data-binary '{"doc_ids":["projects"]}' --compressed
```

**ETIMEOUT !!!!!**
