### ISSUE TITLE
Gives error while uploading Attachment

### ISSUE THREAD

**Issue by subhashisrouth** [pouchdb/pouchdb#5507]
I am uploading an Image using `<input type="file" id="noteImage" />`, I am new to pouchdb and building a todo note app just for demo. I successfully added a new doc but I can not add a attachment to a existing doc , it gives error as `error
:
true
message
:
"Some query argument is invalid"
name
:
"badarg"
reason
:
"Attachment is not a valid base64 string"
status
:
500`

BUT my image is  base64  string as I am using FileReader, below is my code snippet, plz HELP.

```
var pdb = new PouchDB('pouchnotes');
var noteObj = {};
noteObj._id = new Date().getTime() + ''; 
noteObj.text = "Some Value";
pdb.put(noteObj, function(error, response) {
								if (error) {
									console.log(error);
									return;
								} else if(response && response.ok) {
									//console.log(response.id);
									
									// put the attachment image field
									var noteImageField = document.getElementById("noteImage");
									
									if (noteImageField.files.length) {
										var reader = new FileReader();
										
										/* 
										Using a closure so that we can extract the 
										File's data in the function.
										*/
										reader.onloadend = (function(file){
											return function(e) {
												pdb.putAttachment(response.id, file.name, response.rev, e.target.result, file.type);
											}
										})(noteImageField.files[0]);
										reader.readAsDataURL(noteImageField.files[0]);
										
										
										
									}
									
									
								
								}
							});   
```

**Comment by ermouth** [comment]
DataURL has intro like `data:yourdoc/mimetype;base64,`. You should truncate it.

**Comment by nolanlawson** [comment]
Yep, @ermouth is correct, PouchDB only takes base64 strings or Blobs, not data URLs.

There's an easier way, though, which is to just directly pass in `noteImageField.files[0]`; you don't need to do any of the FileReader stuff yourself because the File object is already a Blob. In fact in our guide we have a live HTML example of doing exactly this: https://pouchdb.com/guides/attachments.html

Hope that helps, cheers.

**Comment by subhashisrouth** [comment]
Thanks. Yeh, It's Working.
