### ISSUE TITLE
Replication gets messed up if CouchDB connection has options specified in classes (worked in 5.3.2, broken in 5.4.0+)

### ISSUE THREAD

**Issue by rpiaggio** [pouchdb/pouchdb#5508]
### Environment (Node.js/browser/hybrid app/etc.)

Browser.

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Chrome.

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

Default (IndexedDB?).

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

CouchDB.

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

``` js
    function DBOptions(name, adapter, revs_limit, ajax, auth, db, auto_compaction) {
        this.name = name;
        this.adapter = adapter;
        this.revs_limit = revs_limit;
        this.ajax = ajax;
        this.auth = auth;
        this.db = db;
        this.auto_compaction = auto_compaction;
    }

    function AjaxOptions(timeout, headers, withCredentials, skip_setup, cache) {
        this.timeout = timeout;
        this.headers = headers;
        this.withCredentials = withCredentials;
        this.skip_setup = skip_setup;
        this.cache = cache;
    }

    function AuthOptions(username, password) {
        this.username = username;
        this.password = password;
    }

    var local = new PouchDB("test2");
    var remoteOptions = new DBOptions(undefined, undefined, undefined, new AjaxOptions(undefined, undefined, undefined, true, undefined), new AuthOptions('user', 'pass'), undefined, undefined);
    console.log(JSON.stringify(remoteOptions));
    // Prints: {"ajax":{"skip_setup":true},"auth":{"username":"user","password":"pass"}}
    var remote = new PouchDB("http://localhost:5984/test2", remoteOptions);
    // If this is used instead, everything works fine!
    // var remote = new PouchDB("http://localhost:5984/test2", {
    //     ajax: {skip_setup: true},
    //     auth: {username: 'user', password: 'pass'}
    // });

    setTimeout(function () {
        local.put({_id: "0000ff22-1203-4a28-b8b3-60ff577e28cb", number: 1, name: 'A'});
    }, 2000);

    local.replicate.to(remote, {live: true, retry: true})
        .on('paused', function (err) {
            console.warn(err);
        }).on('error', function (err) {
            console.error(err);
        });
```

When replication starts, it will fail repeatedly with `400 (Bad Request)`:
![image](https://cloud.githubusercontent.com/assets/1895643/17226320/46d9a2b2-54df-11e6-8d37-cb186c21543d.png)

If the request is analyzed:
![image](https://cloud.githubusercontent.com/assets/1895643/17226367/85794798-54df-11e6-8e30-c804dfe2fad9.png)

We can see there is a `docs` section in the `_revs_diff` POST, which probably shouldn't be there (it isn't there in 5.3.2).

I don't know if this functionality is supposed to be supported, it was working on 5.3.2. Please let me know if it shouldn't be used. In the meantime I can `JSON.parse(JSON.stringify(remoteOptions));`, which works.

**Comment by nolanlawson** [comment]
Yeah we typically only accept regular JavaScript objects for stuff like this, and we did change our cloning algorithm in 5.4.x which is what would cause the error. I'd say it's an unsupported feature to have custom classes that look like regular JS objects; instead it's best to write your own `toJSON()` function (or `JSON.parse(JSON.stringify(obj))` should work too, or use TypeScript since it will convert to plain JS objects (I believe).

Closing as a wontfix, sorry that you ran into such a tricky bug though!

**Comment by rpiaggio** [comment]
Ok, thank you. In particular I'm using Scala.js with this facade https://github.com/chandu0101/scalajs-pouchdb, which uses said objects for the options. I will do a PR in that project then to fix that, now that we know it's unsupported.

BTW: is it unsupported for all other methods that take `options` or just for creating a `new PouchDB`?
