### ISSUE TITLE
Occasional 'downgrading to WebSQL' on Chrome

### ISSUE THREAD

**Issue by jefbarn** [pouchdb/pouchdb#5512]
### Environment (Node.js/browser/hybrid app/etc.)

Browser, Pouch 5.4.5

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Chrome 52

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

IndexedDB

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

CouchDB 1.6

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

I've been developing my app using Chrome (latest 52) and occasionally Pouch will decide to 'downgrade' my database even though it's never been opened using WebSQL.  Has anyone else seen issues like this?
It is very intermittent (maybe every 50 page loads, or every couple days), so hard to reproduce.
Could it be tied to Chrome's auto-update?

**Comment by nolanlawson** [comment]
That's really strange. That should only ever happen if you had explicitly created a PouchDB database using WebSQL at one point or another. You'll see this if in LocalStorage PouchDB has stored a value with something like "websql_database_name_foo".

PouchDB may be deciding to consider the IndexedDB on Chrome invalid if you switch your user agent during development. Maybe you were running in "emulate iPhone" mode?

**Comment by jefbarn** [comment]
Ah yes, that's it!  I occasionally hit the 'mobile mode' button to test the page look and if I refresh while in that mode it triggers the switch. Wasn't aware that mode changed the user agent.
Thanks for the help!
