### ISSUE TITLE
Bad handling of credentials on Android 6.0

### ISSUE THREAD

**Issue by danielo515** [pouchdb/pouchdb#5518]
### Environment (Node.js/browser/hybrid app/etc.)

Browser.  PouchDB 3.4.1-prerelease
### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Android Browser. Version 51.0.2704.81
### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

I think it is using IndexedDB, because I'm not using any plugin.
### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

Cloudant
### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

On Android 6.0 seems that Pouch is not managing correctly the credentials. Looking at the debugger console it tries to start syncing before asking for credentials. On any other platform ,PC browser, 'Android 4.4' (chrome or firefox) it works fine, it first asks for credentials, and then it tries to start syncing. 
But on Android 6.0 I get an error 500 even before I can write my username and password. Here is the exact error:

``` js
o {status: 500, name: "unknown_error", 
    message: "Database encountered an unknown error", error: true}
```

If I inspect the network tab of the dev tools I can see olny one request, and it is not even to cloudant, it's to `blob:content%3A///...`

I have the same problem with firefox, and I tried have disabled the Data Saver.

**Comment by willholley** [comment]
that's a pretty old version of PouchDB. Do you get the same issues with the latest release?

**Comment by danielo515** [comment]
I have updated to the latest revision. You were right, the error has changed :smile: 

```
{
    "code": "ETIMEDOUT",
    "status": 0
}
```

**Comment by danielo515** [comment]
My question is, if it timed out... why pouchdb does not try again after a while?

**Comment by willholley** [comment]
what request is it that times out? Are you able to share the code that triggers it and/or a trace of the HTTP requests?

**Comment by danielo515** [comment]
Ok... I feel like I'm making some advance. Because I was starting to doubt if I was writting the password correctly on my phone's keyboard I went to cloudant.com and I logged in. "Ok, password is correct" I though. My surprise when I opened again the tab were my application (web app) was and synchronization was happening! Seems like pouchdb took the cookie cloudant set and it started using it. 

Now my question is, how can I achieve the same result without having to log into cloudant first? This works fine on my laptop, even on my work laptop where I did never logged in into cloudant

**Comment by willholley** [comment]
Are you pre-emptively sending auth details with PouchDB or relying on the challenge form Cloudant to force the browser to prompt? When you initialise PouchDB you can pass a username and password, or you could look at https://github.com/nolanlawson/pouchdb-authentication.

**Comment by danielo515** [comment]
> Are you pre-emptively sending auth details with PouchDB or relying on the challenge form Cloudant to force the browser to prompt? 
I'm relying on Cloudant forcing the browser to prompt 😅 

> When you initialise PouchDB you can pass a username and password, or you could look at https://github.com/nolanlawson/pouchdb-authentication.

I would prefer to stick to just PouchDB. What are the advantages of pouchdb-authentication over setting username and password on PouchDB ?

Thank you very much for all your help so far.

**Comment by willholley** [comment]
pouchdb-authentication allows you to use cookie authentication and login/logout without recreating the PouchDB object. It also has methods for creating/managing users (which may be superfluous to you). Alternatively, you can always just make a http request to `https://myaccount.cloudant.com/_session` using JavaScript to sign in the user using cookie auth.

**Comment by danielo515** [comment]
>pouchdb-authentication allows you to use cookie authentication and login/logout without recreating the PouchDB object.

That is very convenient. I have to admit that it is very tempting to use the library, but I'm not sure if I want to pay 40k extra on the weight of the application. 

> It also has methods for creating/managing users (which may be superfluous to you).

It is at this point, but I have plans to provide a storage service, so maybe managing users would come in handy.

>Alternatively, you can always just make a http request to https://myaccount.cloudant.com/_session using JavaScript to sign in the user using cookie auth.

And rely on browser prompt? This will require to wait the user to log in, and then once the cookie is set create the remote DB and start sync, right?

**Comment by willholley** [comment]
you don't need to rely on the browser prompt to POST to `_session` - you just need to perform a [form POST with the `name` and `password` values](https://docs.cloudant.com/authentication.html#cookie-authentication). This is what pouchdb-authentication is doing [here](https://github.com/nolanlawson/pouchdb-authentication/blob/master/lib/index.js#L86).

**Comment by danielo515** [comment]
>you don't need to rely on the browser prompt to POST to _session - you just need to perform a form POST with the name and password values. This is what pouchdb-authentication is doing here.

Thank you again @willholley 

I assume that doing the POST after the creation of the remote database will not work. I mean, I have to make the POST, wait to the cookie to be set and then I can create the remote database which will sync correctly. Right?

**Comment by willholley** [comment]
@danielo515 you should be able to create the remote database object before fetching the cookie, but sync requests will fail unless you specify basic auth credentials or you make a successful request to the `_session` endpoint (in which case the browser will automatically pick up the cookie).

**Comment by danielo515** [comment]
Hello @willholley 
What I'm doing now is: 

1. Wait for user interaction, until that no remotedb is created or logging attempt is made.
1. I ask the user for credentials (username and password)
1. I create a new pouchdb instance with those credentials.
1. I sync the newly created pouchdb database with the local one.

I'm not sure if that is the correct way. Is it Ok to create a new remote database on each logging attempt ? I suppose the garbage collector will pick the old instance if I remove the reference to it, but I'm not sure if Pouchdb keeps any internal reference or if this is even a good practice.

Thanks and regards!

**Comment by willholley** [comment]
@danielo515 that sounds fine to me.
