### ISSUE TITLE
pouchdb with websql adapter not creating a database in nwjs child process

### ISSUE THREAD

**Issue by drunksaint** [pouchdb/pouchdb#5525]
### Environment (Node.js/browser/hybrid app/etc.)

node.js
### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

child_process spawned from nwjs
### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

websql
### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

couchdb
### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

Hi, when I create a child process from the main nwjs process,

`cp = require('child_process').fork('child_proc_file.js');`

and try initializing a pouchdb with the node websql adapter in the child process,
child_proc_file.js:

```
var PouchDB = require('pouchdb');
PouchDB.plugin(require('pouchdb-adapter-node-websql'));
//also tried replacing the above line with require('pouchdb/extras/websql');
var localDB = new PouchDB('testdb', {adapter: 'websql'});
```

I get the following error:

```
xx/app/node_modules/websql/lib/sqlite/SQLiteDatabase.js:65
    var sql = query.sql;
                   ^

TypeError: Cannot read property 'sql' of undefined
    at doNext (xx/app/node_modules/websql/lib/sqlite/SQLiteDatabase.js:65:20)
    at checkDone (xx/app/node_modules/websql/lib/sqlite/SQLiteDatabase.js:52:7)
    at xx/app/node_modules/websql/lib/sqlite/SQLiteDatabase.js:59:7
    at Statement.<anonymous> (xx/app/node_modules/websql/lib/sqlite/SQLiteDatabase.js:28:14)
```

I tried looking at the source code in SQLiteDatabase.js, the callback in line 50 didn't seem to return and the loop was executing beyond the array length of 'queries' leading to the undefined query object. also, there seemed to be an extra rollback query after the array 'queries' was exhausted if that helps.

**Comment by nolanlawson** [comment]
Can you provide a small test app to reproduce? The ideal app would allow us to easily run this on the command line ourselves. Just a "hello world" app would be great.

I admit that I personally tried to get node-websql running inside of a NW.js app but never succeeded: https://github.com/nolanlawson/pouchdb-nw-hello-world. I was only able to get it to work for Electron.

**Comment by drunksaint** [comment]
Hi @nolanlawson 
I've made a simple test case here: https://github.com/drunksaint/pouchdb-nwchildproc
Instructions are in the readme. Let me know if you have problems running it.

**Comment by drunksaint** [comment]
Hi @nolanlawson 
Did you have any luck reproducing the problem?
If you aren't able to get the output from child process on your os, I've added a new branch "windows" to the above repo which might be what you need.

**Comment by nolanlawson** [comment]
I haven't had time yet to look at this, sorry. It's marked "has test case," meaning once I get through the rest of my backlog I will try to look at it. In the meantime you are encouraging to write a PR if you can. :)

**Comment by nolanlawson** [comment]
OK I see the problem now. You are trying to run the `websql` adapter inside of a Node child process. Since Node does not have websql, it is trying to use [https://github.com/nolanlawson/node-websql](https://github.com/nolanlawson/node-websql) which needs to be recompiled for environments like Node webkit.

Actually in the past I have been unable to get this to work with NW.js (see [this example](https://github.com/nolanlawson/pouchdb-nw-hello-world)), but NW.js should have instructions for building native modules, in this case `sqlite3` which you will have to rebuild. Good luck!

Also keep in mind that PouchDB offers many many other ways to use backends, for instance IndexedDB, WebSQL, and LevelDB, which may be easier for you than running SQLite.

**Comment by nolanlawson** [comment]
Hm strange I was able to get this working with Electron, but not NW.js: https://github.com/nolanlawson/hello-electron-with-pouchdb

You may need to do some research with e.g. https://github.com/nwjs/nw.js/wiki/Build-native-modules-with-nw-gyp

**Comment by nolanlawson** [comment]
Hm also I was unable to get it to work with Windows. Seems the `sqlite3` package has a lot of compat issues.
