### ISSUE TITLE
Zip example is not working 

### ISSUE THREAD

**Issue by flik** [pouchdb/pouchdb#5526]
I have downloaded the pouchdb-getting-started-todo.zip. from 
https://pouchdb.com/getting-started.html

but it is not working...

### Environment (Node.js/browser/hybrid app/etc.)

(Write here.)

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

(Write here.)

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

(Write here.)

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

(Write here.)

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

(Write here.)

**Comment by daleharvey** [comment]
How is it not working? did you follow the subsequent instructions to run the website from a web server `python -m SimpleHTTPServer` ? I just downloaded the zip and it appears to be working for me when I access it from http://127.0.0.1:8000/

**Comment by Chima1707** [comment]
@flik Please give proper description of any error you encounter, so that people will guild you properly

**Comment by pjhampton** [comment]
Not working, as in the todos are not persisting? This is because it doesn't work out of the box when you download **pouchdb-getting-started-todo.zip**. It's a tutorial that you have to work through and then they will persist.

**Comment by nolanlawson** [comment]
@pjhampton Did you install CouchDB? Without it, data will only be saved locally in the browser.

**Comment by pjhampton** [comment]
@nolanlawson I believe it is @flik with the issue. I'm just saying that the folder **pouchdb-getting-started-todo.zip** wouldn't work (as in persisting) straight away.

**Comment by flik** [comment]
@pjhampton I have added the code as it is described in the main page. https://pouchdb.com/getting-started.html 
Modified index.html and app.js 
But when I entered anything and press enter button textbox clear and not showing anything on the page.
and I am not getting any error.

**Comment by pjhampton** [comment]
@flik Hmm, strange. Can you please create a repo and push it to Github? Send us the link and maybe we can advise further. I could replicate this issue 8 days ago I'm afraid.

**Comment by flik** [comment]
https://github.com/flik/pouchdb-getting-started-todo here is the repo

**Comment by pjhampton** [comment]
Hi @flik 

I just cloned this and ran with the following process:

```
$ git clone https://github.com/flik/pouchdb-getting-started-todo.git
$ cd pouchdb-getting-started-todo
$ python3 -m http.server
```

and it works fine:

![screen shot 2016-09-27 at 12 20 11 pm](https://cloud.githubusercontent.com/assets/8960296/18871313/c507e78c-84ac-11e6-9946-b289372465fc.png)

  1. Are you making sure that you are running:

**Python 2**
```
python -m SimpleHTTPServer 8000
```

or 

**Python3**
```
python3 -m http.server
```

 2. Are you sure you have all the required dependancies installed?

**Comment by flik** [comment]
It is strange. Can you send me the link of required dependencies ?

**Comment by pjhampton** [comment]
I just realized you are linking it via CDN. This has me pretty stumped.

Does your browser support it: https://pouchdb.com/adapters.html#pouchdb_in_the_browser ?

**Comment by flik** [comment]
Now, It is working. May be net was not loading remote header file.

**Comment by pjhampton** [comment]
Cool, glad this is resolved for you 😄
