### ISSUE TITLE
http://slack.pouchdb.com/ returns with a 502

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#5532]
reported by https://github.com/pouchdb/pouchdb/issues/4207#issuecomment-237810713

**Comment by daleharvey** [comment]
Sorry about that, got it up again and told Nolan / irc how to fix it

**Comment by fasiha** [comment]
Same currently :-/

**Comment by brunoreis** [comment]
Unfortunately, 502 is there again.
