### ISSUE TITLE
How to Simulating the functions avg, max, min, and count on PouchDB?

### ISSUE THREAD

**Issue by santclear** [pouchdb/pouchdb#5533]
Does anyone know how to create aggregate functions, for example avg, sum, max and min on PouchDB database. I created a simple application to test the PouchDB. I'm still not figured out how to run these commands. Thanks in advance.

For example. How do you get the highest, lowest or average for the "number" field?

* My main Ionic 2 component

```
import {Component} from '@angular/core';
import {Platform, ionicBootstrap} from 'ionic-angular';
import {StatusBar} from 'ionic-native';
import {HomePage} from './pages/home/home';
declare var require: any;
var pouch = require('pouchdb');
var pouchFind = require('pouchdb-find');
@Component({
    template: '<ion-nav [root]="rootPage"></ion-nav>'
})
export class MyApp {
    rootPage: any = HomePage;
    db: any;
    value: any;
    constructor(platform: Platform) {
        platform.ready().then(() => {
            StatusBar.styleDefault();
        });
        pouch.plugin(pouchFind);
        this.db = new pouch('friendsdb');
        let docs = [
            {
                '_id': '1',
                'number': 10,
                'values': '1, 2, 3',
                'loto': 'fooloto'
            },
            {
                '_id': '2',
                'number': 12,
                'values': '4, 7, 9',
                'loto': 'barloto'
            },
            {
                '_id': '3',
                'number': 13,
                'values': '9, 4, 5',
                'loto': 'fooloto'
            }
        ];
        this.db.bulkDocs(docs).then(function (result) {
            console.log(result);
        }).catch(function (err) {
            console.log(err);
        });
    }
}
ionicBootstrap(MyApp);
```

**Comment by santclear** [comment]
Hello @nolanlawson, Could help me in this matter? I have read a lot about mapreduce, but can not find the solution to this problem yet :-(

In the last question I had, you and your friend helped me a lot. It was very motivating. Now, I'm looking delve more in this technology.

**Comment by nolanlawson** [comment]
The built-in _stats function does exactly this: https://wiki.apache.org/couchdb/Built-In_Reduce_Functions#A_stats

Unfortunately it doesn't include the average, but you can calculate that from the sum and the count. If you're still not sure what to do, here is an example custom _reduce function that gives you an average: https://wiki.apache.org/couchdb/Built-In_Reduce_Functions#A_stats

**Comment by nolanlawson** [comment]
I'm going to close since this is more of a tech-support question than an issue with PouchDB. If you need more help I recommend using the Google Groups or the IRC channel.

I understand that it's currently very difficult to do median/average/etc. in PouchDB but we kind of inherited that from CouchDB and don't have a better API currently than map/reduce; sorry about that. Another option is to simply read the whole thing into memory with `allDocs()` and then just use lodash or vanilla JavaScript.

**Comment by santclear** [comment]
Got it. Thank @nolanlawson by this explanation. It's exciting to have this support!
Best regards.

**Comment by santclear** [comment]
Only to contribute. An answer to this question was given in:http://stackoverflow.com/questions/38779998/how-to-simulating-the-aggregate-functions-avg-sum-max-min-and-count-on-pouch

**Comment by mqtik** [comment]
Correct me if I'm wrong, but pouchdb-find it's designd exactly to avoid using **query()** due to performance issues.

**Comment by mqtik** [comment]
(please, correct me if i'm wrong, @nolanlawson)
