### ISSUE TITLE
sync() causes 401 Errror triggering Browser's Authentication Popup

### ISSUE THREAD

**Issue by lanluu** [pouchdb/pouchdb#5534]
### Environment (Node.js/browser/hybrid app/etc.)
Hybrid/Html
### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)
Chrome
### Adapter (IndexedDB/WebSQL/LevelDB/etc.)
IndexedDB
### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)
Couchbase via Sync Gateway
### Please describe your issue. Test cases (e.g. JSBin) are very helpful!
I am using PouchDB to synchronize data between my App (Hybrid/Web) and Couchbase Sync Gateway. The authentication is via Cookie. In case the Sync Gateway's Cookie is expired or deleted, an Authentication Popup is displayed, as the response's header from Sync Gateway contains WWW-Authenticate. How can I prevent this Authentication Popup of Browser? How can I catch such 401 error at 'sync()'? The fact is that the error is not bubbled to 'denied', 'complete' or 'error'.

I think you already fixed this bug (see also #4276 and #5421), but it still appears by me. I am using version 5.4.5. I also tried the latest Nightly Build but it did not help. Do I understand something wrongly?

Thank you so much for building cool PouchDb and your support :-) !

**Comment by nolanlawson** [comment]
This is already fixed in https://github.com/pouchdb/pouchdb/commit/0e14d2213cebe5798c0e34d5faab21b815cc6427 but hasn't been released yet. I'm going to do a 5.4.6 this weekend which should fix it. Thanks for reporting!

**Comment by lanluu** [comment]
Thank you for such cool info, Nolan. I am really excited to try the new version soon.
