### ISSUE TITLE
Couchbase Sync Gateway: filtered replication giving 400 error

### ISSUE THREAD

**Issue by gillez** [pouchdb/pouchdb#5537]
### Environment (Node.js/browser/hybrid app/etc.)

browser

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Chrome

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

IndexedDB

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

Couchbase via Sync Gateway

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

Hi,

Syncing pouchdb to my Couchbase database through sync gateway is working fine.  However, when I add a filter design doc to my database and specify this in sync, I get the following 400 error:

pouchdb-5.4.5.js:7640 GET https://localhost:4984/mydb/_changes?timeout=25000&style=all_docs&heartbeat=10000&filter=sync_filter%2Fsync_filter&project=null&since=0&limit=100 400 (Bad Request)

I am adding the filter function in the following way:

    function addFilterIndex_sync() {
      var designDoc = {
        "_id": "_design/sync_filter",
        "filters": {
          "sync_filter": function(doc, req) {
            return true;
          }.toString()
        }
      };

      database.put(designDoc).then(function (result) {
      }).catch(function (err) {
        if (err.status != 409) {
          // some error (maybe a 409, because it already exists?)
          console.log("Add filter index error ", err.status, ": ", err);
        }
      });
    }

As you can see, the filter just returns true, so all docs should get through.

I am calling sync as follows:

      syncHandle = database.sync(remoteDatabase, {
        live: true, 
        retry: true,
        filter: 'sync_filter',
        query_params: { 'project': project }
      }).on('denied', function (err) {

(I'm passing a parameter, but not actually using it in the filter function at the moment).

I'm sure I'm doing something silly, but please can you tell me what?

Thanks for the help,
Giles

**Comment by nolanlawson** [comment]
I'm fairly sure Couchbase Sync Gateway doesn't support that feature. Also please note that PouchDB does not support CSG with 100% API support and there are many known bugs. In fact we kinda-sorta caution people against using it here: https://pouchdb.com/adapters.html#pouchdb_over_http

**Comment by gillez** [comment]
Thanks for the reply Nolan, very useful.  

Do you know how easy it would be to migrate from my current method of PouchDB <=> CSG <=> Couchbase, to incorporating CouchDB into this?   Is it straightforward or would it require a complete rethink?  Also, can I please just clarify what exactly you mean?  Do you mean PouchDB <=> CouchDB <=> CSG <=> Couchbase?  Or do you mean replacing CSG and Couchbase with CouchDB?  I.e. just PouchDB <=> CouchDB?  We also use Couchbase Lite to talk to the same Couchbase bucket from an OSX app so I'm not sure how this would fit into CouchDB.  

I have also asked the question about filters on the Couchbase forum, after your reply to my Slack post.  They say that channels should be used for filtering.  I already use channels on a more permanent basis (i.e. which projects does the user have access to) rather than dynamically (which project is active now?)

Thanks for your help,
Giles

**Comment by nolanlawson** [comment]
Yes sorry, I meant PouchDB <=> CouchDB <=> CSG <=> Couchbase. Unfortunately CouchDB is sorta our lingua-franca, although I'm not sure how well this applies to Couchbase Lite because their reference server is CSG I believe. You could also try Cloudant Sync instead.

Another option is to just avoid filtered replication entirely; I typically try to do one-user-per-db or one-role-per-db because it ends up being less complicated when it comes to syncing, but YMMV. As for CSG channels, I really don't know much; our reference implementation is CouchDB which doesn't have channels.

**Comment by daleharvey** [comment]
Closing in favour of https://github.com/pouchdb/pouchdb/issues/5820
