### ISSUE TITLE
Update handlers

### ISSUE THREAD

**Issue by jmatsushita** [pouchdb/pouchdb#5542]
This is a follow up of #2510 which has somewhat steered away from the original request. 

Update handlers are a core feature of CouchDB: http://docs.couchdb.org/en/1.6.1/couchapp/ddocs.html#update-functions

As mentioned in the old wiki:
```
To invoke a handler, use one of:

- a PUT request against the handler function with a document id: /<database>/_design/<design>/_update/<function>/<docid>
- a POST request agasint the handler function without a document id: /<database>/_design/<design>/_update/<function>

[...] unlike document validators, the user's intent must be clear by calling this individual handler explicitly.
```

Right now I work around the lack of support in PouchDB (which I also use in node.js to connect to CouchDB) by using `nano` instead and in particular the [`atomic` function](https://github.com/dscape/nano#dbatomicdesignname-updatename-docname-body-callback).

Would you only consider adding this to PouchDB if PouchDB itself implemented update handlers? If this is a CouchDB only feature then is that a reason to only enable it via a plugin (which I don't think exists so far)?

Thanks for your time and the awesome project!

**Comment by willholley** [comment]
The primary benefit of update handlers is that they don't require a round-trip of the document from server -> client -> server which can be costly if latency is high/docs are large. PouchDB is typically embedded in the client so this seems much less important. However, there is a plugin at https://github.com/pouchdb/pouchdb-update which will give you the functionality.

Update handlers CouchDB do not do anything that a client couldn't do (update_handlers don't provide atomic transactions, for instance) - if you have a 3-tier application it's generally more efficient to move logic from an update_handler into a more efficient/scalable app tier. To that end, there is some discussion in the CouchDB dev community about moving the feature out of the core database.

**Comment by daleharvey** [comment]
Yup exactly, pouchdb aims to be a compatible implementation of couchdb but only for the core storage functionality. All of the 'couchapp' functionality has been specifically left out as most are only / more relevant for server implementations, there is a plugin for `pouchdb-update` as linked however (its used in `pouchdb-server`, which aims for full couchdb compatibility)

Cheers for the issue, but closing out as we wont be implementing this in core, thanks

**Comment by jmatsushita** [comment]
Hi there,

I understand your point, but I'm not saying that PouchDB should implement the CouchDB update functions, just that PouchDB as a client should allow to post documents to CouchDB's update handlers. I think we're not the only one which use PouchDB as a CouchDB client too. There are a many API calls that are remote specific.

What this means for me in terms of developer experience, is that I have to use another couchdb client (`nano` which supports update handlers) side by side with PouchDB... :/

Cheers,

Jun

**Comment by jmatsushita** [comment]
Sorry I read rapidly the first time and thought the plugin wouldn't work
with Couch. I'll give it a shot, thanks!
