### ISSUE TITLE
Couchbase Sync Gateway + Pouchdb: Initial sync creates 1000s of requests

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [pouchdb/pouchdb#5547]
Hello,

I'm using Couchbase Sync Gateway 1.3 and Pouchdb 5.4.5. If I have many documents on the server and start an initial sync, I noticed that PouchDB creates one request for every single document, which of course is very inefficient.
Here are screenshots of the first few requests (I tried creating an HAR file, but it got too big...):
https://www.dropbox.com/s/fg08d87sp4lvty2/screen1.png?dl=0
https://www.dropbox.com/s/5t57ynsoh3n1lrb/screen2.png?dl=0
I noticed that one of the first requests is one to _bulk_get?revs=true, which fails with 406 Not Acceptable:
{"error":"Not Acceptable","reason":"Response is multipart"}
Maybe this causes the problem?

**Comment by hermitdemschoenenleben** [comment]
do you think that this is a bug or are multipart responses just not implemented? In other words (as the current behavior is a deal-breaker for me), is this something easy to fix?

**Comment by nolanlawson** [comment]
Couchbase Sync Gateway does not have full support for PouchDB and might never have it, since we have not had many PRs from Couchbase folks, and the PouchDB maintainers are primarily interested in maintaining compatibility with CouchDB. YMMV

**Comment by hermitdemschoenenleben** [comment]
In the last weeks I investigated the problem further and found out that the problem seems not to be linked to CSG, but apparently is caused by PouchDB's general replication protocol:

1) When performing a two-way replication with a server, pouch basically starts two independent replications that do not interact. If the pull replication fetches documents from the remote DB, the push replication afterwards makes a _revs_diff call to the remote server in order to find out whether to upload these documents again. If both replication processes communicated with each other, this call could be avoided, as PouchDB already knows that the document with [id, rev] was just fetched and doesn't have to be uploaded.
What makes things much worse is the fact, that when the pull replication fetches many documents at the same time, this doesn't result just in one _revs_diff call but in many small ones. Thus, when you have a fresh instance PouchDB that syncs for the first time with a server that has a lot of documents (let's say 500), this easily causes 50 unnecessary _revs_diff calls, although (with a high enough batch size) just a single _all_docs call was performed.
In order to avoid this, PouchDB could keep track of (id, rev) pairs it has received from the remote server and filter the corresponding documents before uploading (I'm currently trying to implement this as a plugin, but in my opinion that's something worth to be included  in PouchDB). This filter would have to be persistent until the next checkpoint is written.

2) PouchDB always saves its checkpoints to both databases. As I learned in the IRC (thanks daleharvey!) the motivation behind this is to detect whether the remote database was deleted or not. Of course this leads to many requests to the remote server, too, that are not necessary if the user knows that the remote database never gets deleted. As this is a special use case, it's probably best to implement this as a plugin that implements another version of Checkpointer. 

3) There is a third problem though that really is caused by CSG: CSG always uses multipart/mixed for _bulk_get, which is as I learned not well supported by the browsers and thus can't be handled by pouch. This actually can't be solved in PouchDB (however I found a workaround for cordova apps: it's possible to plug in a custom XHR that performs HTTP calls by means of java libraries).

**Comment by daleharvey** [comment]
Closing in favour of https://github.com/pouchdb/pouchdb/issues/5820

**Comment by mjosephd** [comment]
Just noticed there are some commits 10 days ago, does that mean this should be reopened? @xiaoyvr @daleharvey

**Comment by mjosephd** [comment]
Just noticed there are some commits 10 days ago, does that mean this should be reopened then @xiaoyvr @daleharvey
