### ISSUE TITLE
Expose `db.options` (options that were passed to constructor)

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb#5548]
from Slack Chat:

```
gregor [4:51 PM]  
Is there a way to read out the default options from a `PouchDB` constructor?

[4:51]  
Say I do `var MyPouchDB = PouchDB.defaults({prefix: 'foo'})`, can I get `'foo'` from `MyPouchDB`?

[4:52]  
The way we do this right now is `new PouchDB('foo', {skip_setup: true}).__opts.prefix` and that’s a hack I’d love to avoid

nolanlawson [4:53 PM]  
yeah it's definitely a hack

[4:53]  
we need to expose the `name` and the `opts` in a nice API somehow. it's a desired feature that we haven't gotten around to yet

gregor [4:53 PM]  
okay I’ll create an issue
```

^^ feel free to rephrase the issue to your liking

**Comment by daleharvey** [comment]
I have added `.name` in https://github.com/pouchdb/pouchdb/pull/5435, needs a review

Adding `.opts` or `.options` sounds fine, although I would like https://github.com/pouchdb/pouchdb/issues/5231 fixed probably at the same time

**Comment by gr2m** [comment]
@daleharvey #5435 and #5231 are both done now. Okay if I start working on a pull request that adds `.options` to PouchDB instances? So we would have something like this:

```js
var MyPouch = PouchDB.defaults({foo: 'bar'})
var db = new MyPouch('mydb')

console.log(db.options)
// {foo: 'bar'}
```

I would say we don’t set `db.options.name` as it is already exposed at `db.name`

**Comment by daleharvey** [comment]
@gr2m yup that sounds great

**Comment by gr2m** [comment]
I promise I get to that :) If someone else wants to beat me to it, please do, just comment below. I’m happy to help out!
