### ISSUE TITLE
All Firefox jobs are failing in Travis

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5561]
This started recently. Looks like somehow either 41.0.1 isn't being installed, or it isn't being picked up.

This might be a good moment to try just switching to a later version of Firefox anyway. It's already on 48.

**Comment by daleharvey** [comment]
Yeh I noticed permanent failures on an unexpected patch recently and didnt connect the dots, looking into this, not as easy as updating to latest it looks like :(

**Comment by nolanlawson** [comment]
#5564 doesn't seem to be working... :(

**Comment by Lyoness** [comment]
My pleasure! 💖🎉

**Comment by daleharvey** [comment]
And all fixed, thanks @nolanlawson + @Lyoness https://github.com/pouchdb/pouchdb/commit/85599e3d2aa505343f43c461f9c0edbfe44b803c
