### ISSUE TITLE
Electron Production "Document is not defined" error

### ISSUE THREAD

**Issue by bgrayburn** [pouchdb/pouchdb#5565]
### Environment (Node.js/browser/hybrid app/etc.)

Electron in production after webpack on main thread

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Electron

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

Couchdb

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

Couchdb

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!
Getting the following error in the main thread after going to production. Trying to make a narrower test case might be tricky because I'm pretty new to webpack, but I can give it a go if necessary.

```
Error: document is not defined
    at Function.useColors (\\vboxsrvEditor-win32-x64\resources\app\webpack:\~\debug\browser.js:42:1)
    at enabled (\\vboxsrv\Editor-win32-x64\resources\app\webpack:\~\debug\debug.js:83:1)
    at \\vboxsrv\Editor-win32-x64\resources\app\webpack:\~\pouchdb\lib\index.js:2687:1
    at \\vboxsrv\Editor-win32-x64\resources\app\webpack:\~\pouchdb\lib\index.js:2705:6
    at new PouchDB (\\vboxsrv\Editor-win32-x64\resources\app\webpack:\~\pouchdb\lib\index.js:2659:1)
    at PouchDB (\\vboxsrv\Editor-win32-x64\resources\app\webpack:\~\pouchdb\lib\index.js:2624:1)
    at initDB (\\vboxsrv\Editor-win32-x64\resources\app\webpack:\app\util\dbUtil.js:39:21)
    at resetDB (\\vboxsrv\Editor-win32-x64\resources\app\webpack:\app\util\dbUtil.js:91:3)
    at \\vboxsrv\Editor-win32-x64\resources\app\webpack:\app\util\dbUtil.js:97:28
    at Array.forEach (native)
```

ln39 of dbUtil.js looks like this `const db = PouchDB('http://localhost:5984')`

**Comment by nolanlawson** [comment]
Leveldown is known to have issues on Windows. Are you sure this isn't a leveldown issue rather than a CouchDB issue? You reported "CouchDB" as your adapter.

Also in your trace it looks like the error is not coming from PouchDB but rather from the `debug` module, which PouchDB is using. Are you running PouchDB inside of a web worker with debugging enabled? The `debug` module does not support this; there's an issue open here: https://github.com/visionmedia/debug/pull/241

**Comment by bgrayburn** [comment]
Thanks @nolanlawson 
In re: to leveldown, Since I'm using a remote db, it shouldn't use leveldown at all right?

I'm running it in Electron's main thread, but I've found a few libraries don't properly recognize that environment and mistake it for the browser, I'll bring this up on the debug repo. Thanks again!
