### ISSUE TITLE
http adapter: PouchDB.preferredAdapters does not get updated

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb#5567]
``` js
var PouchDB = require('pouchdb-core')
PouchDB.plugin(require('pouchdb-adapter-http'))
PouchDB.preferredAdapters
// []
```

I expected `['http']`. It works as expected with the leveldb and memory adapters.

Is this a bug?

**Comment by gr2m** [comment]
I found these lines: https://github.com/pouchdb/pouchdb/blob/master/packages/pouchdb-adapter-http/src/index.js#L955-L956

Why do you set 3rd `addToPreferredAdapters` argument to false for the `http` adapter?

**Comment by nolanlawson** [comment]
`preferredAdapters` should really be called `preferredLocalAdapters`. It's the list of adapters that gets tried, one at a time, when you do `new PouchDB('foo')`. E.g. in the browser it's `['idb', 'websql']` and in Node it's `['leveldb']`.

**Comment by gr2m** [comment]
I guess the conflict I have is that the prefix option now can be a URL, so new PouchDB('foo') can use http, if prefix was set with PouchDB.defaults()

But it still makes sense, I guess I can find another way to figure out if a PouchDB Core constructor was defaulted to use a URL and loaded the http adapter as plugin. Feel free to close :)

**Comment by nolanlawson** [comment]
Hm, if that's the case then the http adapter should invoke based on the full database name (prefix + name), not just the name. Sounds like a bug.

**Comment by gr2m** [comment]
It is invoking correctly, I'd just like to know if a PouchDB constructor will invoke the http adapter by default

**Comment by nolanlawson** [comment]
It's not really specced, and I don't think you can force it. Maybe we should be more explicit about this.

**Comment by gr2m** [comment]
Yeah I don’t have a better idea right now. But it’s not a blocker, I can work around it for Hoodie

**Comment by nolanlawson** [comment]
Closing for now, seems there are workarounds that are good enough
