### ISSUE TITLE
http adapter: should PouchDB encode the database name?

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb#5574]
Let’s say I want to create a database called `user/123` with PouchDB using the http adapter.

```js
var dbName = 'user/123'
var MyPouchDB = PouchDB.defaults({prefix: 'http://localhost:5984/'})
MyPouchDB.plugin(require('pouchdb-adapter-http'))

var db = new MyPouchDB(dbName)
db.info().catch(console.log.bind(console))
// logs not_found error
```

The problem is that it sends a request to `GET http://localhost:5984/user/123/`, it is not encoding the database name. 

I would expect this to happen within PouchDB, instead of me needing to do 

```js
var db = new MyPouchDB(encodeURIComponent(dbName))
```

What do you think?

**Comment by gr2m** [comment]
I think it’s as simple as a `encodeURIComponent(opts.db)` in https://github.com/pouchdb/pouchdb/blob/master/packages/pouchdb-adapter-http/src/index.js#L106

Would you accept a pull request for that? Note this might potentially break people’s code, in case they already encoded their database names

**Comment by gr2m** [comment]
this is related: https://github.com/pouchdb/pouchdb/commit/94c7276adfe0ce36b6471874cb60d5bdbcebdacf

**Comment by gr2m** [comment]
Okay I think I  got it, PR incoming 🚀

**Comment by daleharvey** [comment]
As far as I remember, we require the user to encode the `/` because I am not sure there is a way for us to differentiate when the `/` is part of the name, or when couchdb is hosted under a path, very possible I am misremembering something though

**Comment by KlausTrainer** [comment]
What about using something like this in order to check if the database name` is already URI encoded:

```javascript
function isURIEncoded(dbName) {
  return !(dbName === decodeURIComponent(dbName));
}
```

**Comment by daleharvey** [comment]
That doesnt address the issue, how to we differentiate `new PouchDB('http://foo.com/user/123');` from `new PouchDB("http://foo.com/db/mydatabase")`?

**Comment by gr2m** [comment]
see my pull request here: https://github.com/pouchdb/pouchdb/pull/5580

It only encodes the database name if `options.prefix` is a URL, which I guess makes sense, and it resolves the issue for us at Hoodie, where we just pass on a `PouchDB` constructor that should always behave the same, no matter what adapter is used

**Comment by nolanlawson** [comment]
fixed by https://github.com/pouchdb/pouchdb/pull/5580
