### ISSUE TITLE
sqlite-plugin not detected with ionics wkwebview

### ISSUE THREAD

**Issue by mnewmedia** [pouchdb/pouchdb#5579]
### Issue
According to the [wkwebview issue](https://github.com/driftyco/cordova-plugin-wkwebview-engine/issues/8) pouchdb doesn't detect the drop-in replacement [cordova-plugin-sqlite-2](https://github.com/nolanlawson/cordova-plugin-sqlite-2) and throws `adapter missing`.

I know nolan moved the sqlite stuff to [pouchdb-adapter-sqlite](https://github.com/nolanlawson/pouchdb-adapter-cordova-sqlite). can i use this plugin already in 5.4.5? maybe it's already solved with this changes..

Off-topic isn't a issue template in this style nicer? not so many big headers, looks more compact.

### Info
- **Environment:** cordova with [ionics new version of wkwebview](https://github.com/driftyco/cordova-plugin-wkwebview-engine)
- **Platform:** iOS (maybe also Android not testet)
- **Adapter:** websql [cordova-plugin-sqlite-2](https://github.com/nolanlawson/cordova-plugin-sqlite-2)
- **Server:** doesn't matter

**Comment by nolanlawson** [comment]
Yes, you should use [pouchdb-adapter-cordova-sqlite](https://github.com/nolanlawson/pouchdb-adapter-cordova-sqlite) because we are dropping support for it in core PouchDB.

Trying to detect SQLite in WKWebView/UIWebView/Android/etc. while also detecting support within the browser proved way too tricky, so it was easier to just move it to a separate repo. In that repo it is assumed that you are using the Cordova plugin and know what you're doing (as opposed to the browser, which is an unknown environment).

Please let me know if that helps; you should be able to use that plugin as-is with PouchDB 5.4.5, cheers.

**Comment by ozexpert** [comment]
One problem with the PouchDB. 

I have this code
```
PouchDB.plugin(PouchAdapterCordovaSqlite);
var localDB = new PouchDB('dbname', { adapter: 'cordova-sqlite'});
```

Still gives me an error 

```
2016-08-21 21:14:14.644 Project[3964:79991] pouchdb:adapter Picked adapter: cordova-sqlite +0ms
2016-08-21 21:14:14.644 Project[3964:79991] pouchdb:adapter Picked adapter: websql +1ms
```

no matter what adapter i use, it somehow is looking for `websql`. 
I tried with different adapters like `idb` but same..

**Comment by ozexpert** [comment]
because of this, it just fails with https://github.com/driftyco/cordova-plugin-wkwebview-engine

**Comment by ozexpert** [comment]
Hmm. i see... 
Just figured out.. for remote db with the URL, it should use http or https adapter, but was using websql adapter. 

defining adapter to use 'https' fixed the issue.

**Comment by mnewmedia** [comment]
For me it also worked without defining `https` adapter. I used this as setup:
`db.remote = new PouchDB('https://url/db', {skipSetup: true});`

But defining stuff we know, is always better!

**Comment by daleharvey** [comment]
@mnewmedia btw I do prefer your style of issue template, if you wanted to open a PR to switch to that style it would be great :)

https://github.com/pouchdb/pouchdb/blob/master/ISSUE_TEMPLATE.md is the file, I would like an extra field at the end that asked a how to reproduce the issue
