### ISSUE TITLE
how can I save messages of IM

### ISSUE THREAD

**Issue by Hsinky** [pouchdb/pouchdb#5582]
hey,budy, I create a web IMapp, it will use local storage,but,the API “db.get(docId, [options], [callback])” could not meet the needs,I want to get messages of somebody,For example,I got some messages from user A and user B, when I open my app and  chat with user A, I should  load these messages  from user A,but, I don't know the api "db.put(doc, [docId], [docRev], [options], [callback])" how can save it,please heap me!Thanks!

**Comment by garrensmith** [comment]
You can do that via [map/reduce](https://pouchdb.com/api.html#query_database) or using [PouchDB-Find](https://github.com/nolanlawson/pouchdb-find). 

This isn't the best place to ask questions. Rather try the mailing list or the slack channel. See the [discuss](https://pouchdb.com/) section on the website.

**Comment by Hsinky** [comment]
@garrensmith Thanks for your help! I wish you can add 'PouchDB-Find',because I'm afraid that they  won't be updated anymore!

**Comment by garrensmith** [comment]
PouchDB-Find will be updated. Its just finding the time to work on it.
