### ISSUE TITLE
Putting a new document with a _rev field should not return a 409

### ISSUE THREAD

**Issue by danielo515** [pouchdb/pouchdb#5600]
### Environment (Node.js/browser/hybrid app/etc.)

Tested on browser

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Chrome

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

Doesn't matter, happens locally

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

When you try to put a **new** document with an invalid revision field (this could happen for several reasons, being one of them making a "copy" of a document) Pouch returns a 409 error. This error is misleading because there is no actual conflict, is just an invalid usage of the put method. To differentiate between actual conflicts and invalid usages you have to perform a `get`petition and listen for a 404 error, which could be resource consuming. It would be useful to return an specific error for this kind of situation.

Any workaround is welcome. Maybe using the upsert plugin?

**Comment by daleharvey** [comment]
Yeh this is specific behaviour for compatibility with CouchDB - https://github.com/pouchdb/pouchdb/issues/4712 + https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.basics.js#L1042), so you could ask CouchDB about changing its behaviour, however I think either way we will want to return whatever couch does

**Comment by danielo515** [comment]
Hello @daleharvey , #4712 explains why updating my Pouch version broke some of my application workflow.

I will indeed ask couchDB as about changing this behavior, but I don't see why Pouch should take the same wrong decisions. As long as you return an error it should be enough.

**Comment by danielo515** [comment]
I just opened the issue on couch issue tracker

https://issues.apache.org/jira/browse/COUCHDB-3107?jql=project%20%3D%20COUCHDB

**Comment by daleharvey** [comment]
In general we try to follow CouchDB behaviour so that people do not need to worry which backend they are using, they can expect the same results

**Comment by daleharvey** [comment]
If CouchDB change their behaviour then we will do, however in the meantime we will follow their behaviour here so closing this out, cheers
