### ISSUE TITLE
Design decision: Separate regions for different users

### ISSUE THREAD

**Issue by RonCan** [pouchdb/pouchdb#5601]
### Environment (Node.js/browser/hybrid app/etc.)

Node.js

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

(Write here.)

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

(Write here.)

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

Cloudant

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

I'm creating a new PouchDB instance like this:
`var db = new PouchDB(config.someCloudantDb);`
in my db.js which is required in different modules of my node app. Now a user has the ability to switch to `config.someOtherCloudantDb` while all the other users who haven't changed the region should get results from `config.someCloudantDb`. I'm new to NodeJs so I don't know how to handle this situation.

**Comment by nolanlawson** [comment]
I'm sorry, I'm having trouble understanding this question. Do you mean you want a user to be able to log in to two accounts simultaneously? Or to be able to log out and log in as another user?

**Comment by nolanlawson** [comment]
Without more details, hard to answer the question, so gonna close. Please reopen as necessary.
