### ISSUE TITLE
Unexpected 409 Conflict while using latest winning _rev

### ISSUE THREAD

**Issue by dharders** [pouchdb/pouchdb#5606]
### Environment (Node.js/browser/hybrid app/etc.)

Browser

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Chrome

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

WebSQL

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

CouchDB 2.0-RC4

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

Pouch 5.4.5

I have always assumed with PouchDB that if I first `db.get()` then use that returned document  to `db.put` back into the database (after modifying it) was a safe operation, as it **should already contain the latest winning revision**. 

```javascript
localDB.get('docXYZ').then((doc) => {
   doc["deletedDateTime"] = Date.now();
   doc["_deleted"] = true;
   return localDB.put(doc);
}).then((doc) => {
   console.log(doc);
}).catch((err) => console.log(err));
```

But recently I found a few documents in my database that returned **409 Conflicts** when running the code above (with different doc._id's of course). **Note:** I do not have live replication running, so no-one else could be updating the same document simultaneously

Running `localDB.get('docXYZ', {`**`conflicts: true`**`})` showed that there were no existing conflicts (i.e. `_conflicts` array was not present).

After much head-scratching I found after running `localDB.get('docXYZ', {`**`open_revs: 'all'`**`})` it returned an array of length 2. The first (position 0) was showing a different __higher__ `_rev: 7xxx` number than that was returned by the standard `localDB.get` with no options. The second (position 1) was showing the earlier `_rev: 4-xxx`.

Using the __higher__ `_rev: 7xxx` with `localDB.put()` yielded the same 409 conflict message.

- Is this normal PouchDB behaviour and I've just made wrong assumptions ?
- Could it be that this is the result of a mongrelled db that has been replicated from CouchDB 1.6 -> 2 ->1.6 -> 2 ?
- Can I add a new field at the same time as setting `_deleted: true` ?
- Could anything else be causing this 409 ?

I know you'd like an easy way to reproduce this error, but I've found it quite difficult, although my db is currently in this state now and could be privately shared if req'd.

**Comment by dharders** [comment]
> Can I add a new field at the same time as setting _deleted: true ?

After a bit of experimenting, it seems that the answer is that you shouldn't. It can work, but doesn't always (as in my case).

If I update my doc in two steps, it works. Strange. i.e.

```javascript
localDB.get('docXYZ').then((doc) => {
   doc["deletedDateTime"] = Date.now();   
   return localDB.put(doc);
}).then((doc) => {
  return localDB.get('docXYZ');
}).then((doc) => {
   doc["_deleted"] = true;
   return localDB.put(doc);
}).then((doc) => {
   console.log(doc);
}).catch((err) => console.log(err));
```

This code succeeds without any 409's. I guess I could combine the extra `get()` and `put()` into a `remove()` to clean it up a little.

**Before I close this**, can any PouchDB gurus confirm that you shouldn't add anything else to the document when deleting via the `_delete: true` method ? 

If yes, I'll just have to update my codebase on my original (incorrect?) assumption that you could.

**Comment by dharders** [comment]
Hmmm, this issue just popped up again and the above solution was just masking the real issue I think.

I haven't been handling conflicts with this test db/app. But like I stated above, I thought that if there are no conflicts with the current doc, then I'd expect a put() to succeed if given the latest _rev.

Looking at the Couch docs there is also a `deleted_conflicts` param, which using this directly (outside of PouchDB) ended up showing the conflict reported in the `open_revs` call (position 0).

Is `deleted_conflicts` supported by PouchDB ?

**Comment by willholley** [comment]
@dharders you should be able to add custom fields to a document at the same time as deleting it. If you're able to write a failing test, that would be very helpful.

**Comment by dharders** [comment]
>  If you're able to write a failing test, that would be very helpful.

It's quite tricky to reproduce, but i'll see if I can reverse engineer my current db state.

@willholley Is it possible that revision hashes could clash if I were setting the doc contents to exactly the same as an old doc, hence the 409? i.e. are pouch rev hashes based on the contents like couch ?

**Comment by willholley** [comment]
PouchDB just uses uuids for the _rev values so they should not clash. CouchDB uses a combination of the doc content and it's history, so again, you should not get clashes unless they represent exactly the same point in a rev tree.

**Comment by dharders** [comment]
I'm struggling to write a failing test for this.

I'm gonna close this issue out. I'll reopen if I ever find the real reason, or work out how to reproduce. For now I'll just use my workaround, which hasn't failed me yet!
