### ISSUE TITLE
Execute views in sandbox when in Node.js

### ISSUE THREAD

**Issue by KlausTrainer** [pouchdb/pouchdb#5612]
For e.g. pouchdb-server it would be cool to have at least some sense of sandbox when executing views. Node.js provides the [`vm`](https://nodejs.org/dist/latest/docs/api/vm.html) module, which we should make use of, maybe.

**Comment by KlausTrainer** [comment]
This has been fixed with https://github.com/pouchdb/pouchdb/commit/5fb785da788ea6688953a2179b5f69416636ede4.

**Comment by nolanlawson** [comment]
This has been fixed for filter/view in pouchdb-core (i.e. `changes()`) but not yet in map/reduce.

**Comment by daleharvey** [comment]
And done https://github.com/pouchdb/pouchdb/commit/1e011ab0cbc8dd07e1d08d84a7d586f7ddea3b92
