### ISSUE TITLE
[Doc] All Replication Algorithm links broken

### ISSUE THREAD

**Issue by pbowyer** [pouchdb/pouchdb#5614]
On https://github.com/pouchdb/pouchdb/wiki/Replication-algorithm all links are broken - two result in 404's, the other goes to the repository homepage.

Sorry, I have no replacement links to suggest.

**Comment by willholley** [comment]
thanks for highlighting this - I've updated the wiki to fix the links.

**Comment by pbowyer** [comment]
Thanks, but the middle link is still broken for me: https://github.com/couchbaselabs/TouchDB-iOS/wiki/Replication-Algorithm redirects to https://github.com/couchbaselabs/TouchDB-iOS.

There is no wiki present for that repository - perhaps it is hidden and only visible to organisation members?

**Comment by willholley** [comment]
apologies - should now be fixed.
