### ISSUE TITLE
Unicode 2028 character, IOS  and Cordova-sqlite-storage corrupts the database

### ISSUE THREAD

**Issue by Ronnnn** [pouchdb/pouchdb#5618]
### Environment, Browser/platform
iOS app with ionic
does not occur in browser or on Android

### Adapter
WebSQL with sqlite plugin - but only occurs with sqlite in iOS

### Please describe your issue
Try to store any string in the database containing the unicode paragraph (2029) or unicode carriage return (2028). 

### Resulting error:
Whenever trying to open the database, the console will report this error: syntaxerror: unexpected EOF
No more details are given.

### More background information here:
http://timelessrepo.com/json-isnt-a-javascript-subset
http://www.fileformat.info/info/unicode/char/2028/index.htm
http://www.fileformat.info/info/unicode/char/2029/index.htm
https://github.com/litehelpers/Cordova-sqlite-storage/issues/147

### Known bug
~~This is a known error in the underlying sqlite engine (https://github.com/litehelpers/Cordova-sqlite-storage), and for some reason will not be fixed in the MIT or Apache 2.0 licensed version. This is the version that is recommended to use with pouchdb so it directly effects it.~~ As noted by @nolanlawson his fork [cordova-plugin-sqlite-2](https://github.com/nolanlawson/cordova-plugin-sqlite-2) should be preferred to use with pouchdb. I'm using it in my project already, but the bug still affects it. The bug resides in the Json Parse in Cordova-ios, so probably special measures are required to work around it in the sqlite storage engine.

Ultimately the bug comes from Cordova-ios:
https://issues.apache.org/jira/browse/CB-9435

So why report it here also then? Because in my opinion this bug is severe and should be documented more properly and warned for. At this point it is affecting our production app rendering the app completely useless whenever anyone types a carriage return in unicode. Immediately after storing that data the app is completely broken and unresponsive. Furthermore it's not unthinkable that there also might be a possible solution for this by changing some escaping behaviour in Pouchdb.

### What now?
~~It would be very nice if we could use this bugreport to accumulate workarounds for the problem. Some documentation could be updated. And maybe some (optional) escaping could be added to Pouchdb to prevent this issue.~~
Hopefully the bug can be fixed in [cordova-plugin-sqlite-2](https://github.com/nolanlawson/cordova-plugin-sqlite-2)

**Comment by nolanlawson** [comment]
Have you tried [cordova-plugin-sqlite-2](https://nolanlawson.com/2016/04/10/introducing-the-cordova-sqlite-plugin-2/)? I know it supports unicode characters, because I wrote it myself and it should work just fine.

**Comment by Ronnnn** [comment]
@nolanlawson Yes I am using your fork [cordova-plugin-sqlite-2](https://github.com/nolanlawson/cordova-plugin-sqlite-2) version 1.0.4 in my project. Just double checked everything and I've **never** included cordova-plugin-sqlite in the history of the project. Sorry about the confusing by quoting the original fork.
Do you want me to report this bug in the -2 fork then?

**Comment by nolanlawson** [comment]
Yes please, this is a bug in cordova-plugin-sqlite-2 and not in PouchDB. In fact it looks like the bug is somewhere in the Objective-C portion of the code, since it only affects iOS.

**Comment by nolanlawson** [comment]
Ah wait I see now https://issues.apache.org/jira/browse/CB-9435. So I guess this is a problem that Cordova itself needs to fix.

**Comment by Ronnnn** [comment]
Yes that's the source of the problem, but Cordova says: **Resolution: Won't Fix**. What now?

So, if the bug will be there forever, then why don't inform the users of PouchDB+cordova-plugin-sqlite-2+ios about this? The issue is pretty severe because anyone can easily break the database layer by just inserting that character deliberately or not. I've encountered this issue with my live app resulting in mayor data loss for some of my users. 

Suggestion: don't close this issue but label it as 'documentation'

**Comment by nolanlawson** [comment]
Sure, I'm happy to have it documented. Alternative, if you can think of some way to fix it within cordova-sqlite-plugin-2, then I'll happily accept a pull request.

Long-term, this issue will be fixed by Safari 10 finally having non-broken IDB support, so we can finally move on to using IDB 6 years after the spec was proposed.

**Comment by brodybits** [comment]
FYI I think this is also an issue on cordova-android 6.0.0 (installed by Cordova 6.4.0 CLI), raised in cordova/cordova-discuss#57.
