### ISSUE TITLE
Docs - 6.0.3 Changelog -> Custom builds link 404s

### ISSUE THREAD

**Issue by dharders** [pouchdb/pouchdb#5639]
### Issue
Simple doc fix required for Changelog. Custom builds link currently 404s.

### Info
- Docs: Changelog 6.0.3

### Reproduce
Click the **Custom Builds** link on https://github.com/pouchdb/pouchdb/releases/tag/6.0.3 and it 404s, as this resolves to https://github.com/pouchdb/pouchdb/blob/6.0.3/custom.html, which 404s.

### Fix
Change [docs/_posts/2016-09-05-pouchdb-6.0.0.md#L90-L105](https://github.com/pouchdb/pouchdb/blame/0be25cdc809339b7cb44b943ccfef46af17b400b/docs/_posts/2016-09-05-pouchdb-6.0.0.md#L90-L105)

From `... see [Custom builds](/custom.html)` 

To `... see [Custom builds](https://github.com/pouchdb/pouchdb/blob/master/docs/custom.md)`

Don't forget there are two instances (one on line 90, one on line 105)

**Comment by nolanlawson** [comment]
My bad, will fix.

**Comment by nolanlawson** [comment]
This is fixed now, thanks for reporting: https://github.com/pouchdb/pouchdb/releases/tag/6.0.3

**Comment by dharders** [comment]
I probably should have submitted a PR, but wasn't even sure if the doc linked directly to the Releases page, or if it required manual entry on your behalf (I've never made/tagged a release on github before).

Thanks for your awesome work!

**Comment by nolanlawson** [comment]
It's okay; there's no way to open a PR because the problem was in the "releases" page, which is not managed by Git. :)
