### ISSUE TITLE
Firefox private browsing mode: detect invalid IDB

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5641]
Follow-up to #5632.

The idb adapter's `valid()` function should return false inside of Firefox private browsing, because IDB ends up throwing an error if you try to use it. There has to be some way to detect private browsing.

**Comment by daleharvey** [comment]
So `info()` isnt ideal, however any detection of this is broken by design (private browsing is supposed to be undetectable) and the fix for firefox is being actively worked on @ https://bugzilla.mozilla.org/show_bug.cgi?id=781982, so not sure this is worth working around

**Comment by nolanlawson** [comment]
Noting that I just tested in Edge 15 (beta), Safari 10, Chrome 54, and Firefox 50. Results:

* **Chrome and Safari**: Private browsers can still use IndexedDB
* **Firefox**: IDB throws `onerror` event on the `indexedDB.open()` request with `"A mutation operation was attempted on a database that did not allow mutations."`.
* **Edge**: `typeof indexedDB === 'undefined'`

I consider this a bug on Edge. I'm surprised to see it wasn't filed, so I filed one: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9968399/

**Comment by nolanlawson** [comment]
The test case is fairly easy, just do:

```js
new PouchDB('foo').info().catch(console.log.bind(console))
```

in Firefox in private browsing

**Comment by JustinDrake** [comment]
Can I confirm that PouchDB completely fails in Firefox and Edge private mode?

I'm building a privacy-centric application that heavily uses Pouch, so that suck :(

**Comment by nolanlawson** [comment]
@JustinDrake Yes, confirmed. You will need to use the in-memory adapter as a fallback if you would like to support Edge and Firefox private browsing.

**Comment by jackkleeman** [comment]
@nolanlawson have you tried using PouchDB in a worker/sharedworker in firefox private mode? Because it's working for me, using idb adapter. I don't think it persists to disk though
