### ISSUE TITLE
Lots of sync problems from IE 11 with getting started project lin,king to CouchDB

### ISSUE THREAD

**Issue by opaulet92** [pouchdb/pouchdb#5647]
### Issue

Hello, I have a problem (that's why this issue :) ). In fact, I have a problem with IE 11. I've done a lot of search from google and from guithub and I don't arrive to find an answer.
Ok, I got the "pouchdb-getting-started-todo" from the PouchDB website. I followed the tutorial. When I use the project from IE, I hav differents problems
### Info

I'm using python v3.5.2 (python -m http.server with Git Bash).
I'm using CouchDB v1.6.1 and I can visualize flow with Erlang.
I'm using PouchDB v6.0.4
### Reproduce

Like the tutorial, I launch the python server from the project directory.
After, I launch "http://localhost:8000" from IE 11 on a Windows 10. I arrive on the website. 
Here, all is OK.
Bug 1 : 
After that, I write a "todo" and there is nothing in CouchDB (see Erlang). If a refresh IE page, It happens nothing.
The bug from developer mode is : 
message : batch processing terminated with error
name : "unknown"
status : "aborting"
If I launch the same URL from Chrome on a Windows 10, and that I write a "todo", there is the todo from CouchDB.

Bug 2 : 
Sometimes, if I refresh multiple times the IE page, the error above disappear. 
I white a "todo" and there is nothing in CouchDB (see Erlang). If a refresh IE page, the loading of this page is too long.

Bug 3 : 
Sometimes, if I refresh the IE page, I have a loop of PUT request (with local document) on CouchDB (see Erlang).

All of these errors are only from IE 11, and not from Chrome.
Do we need something from PouchDB or CouchDB to not have all of these problems ?

Thanks a lot.

**Comment by nolanlawson** [comment]
PouchDB should work fine in IE11; we have tests that run in IE10. Out of curiosity do you get the same problems in Edge?

Unfortunately it's difficult to diagnose your problem based on the description. Some screenshots or a clear test to reproduce would help. Also keep in mind that IndexedDB has improved a *ton* since IE11 and is known to have some race conditions and bugs (I work on the Edge team).

**Comment by nolanlawson** [comment]
Please reopen if you have a test case to reproduce; I'm closing old issues, thanks
