### ISSUE TITLE
Performance: rootToLeaf() elapsed time is growing

### ISSUE THREAD

**Issue by hepiyellow** [pouchdb/pouchdb#5650]
### Issue

I am new to pouchDB, I just made a little experiment with many fast updates of a single field in a single document. (about 1000 updates, with 50ms interval),
and I noticed bad performance. 
Chrome dev tools profiler pointed at the rootToLeaf() function, and when I added manual elapsed  time measurement, to the rootToLeaf code, I have noticed that the time grows as I make more updates.
Starting from 0-1 milliseconds for a fresh new document, after 1000 updates the elapsed time is about 80 ms per update. Which is a blocker(unusable) for me )-:

I found in [this similar issue](https://github.com/pouchdb/pouchdb/pull/4185) a quote 

> it tends to traverse the whole rev tree even when that's not strictly necessary

Seems like an explanation to what I was experiencing.
### Info
- Environment: React app with typescript, webpack,
- Platform: Chrome
- Adapter: WebSQL ?? (default)
- Server: CouchDB 1.6.1_2
- Mac OSX El Capitan
### Reproduce

My db initialization is:

```
var localDB = new PouchDB('local_test1');
var remoteDB = new PouchDB('http://localhost:5984/test1');

localDB.sync(remoteDB, {
    live: true
}).on('change', function (change: any) {
    // yo, something changed!
}).on('error', function (err: any) {
    // yo, we got an error! (maybe the user went offline?)
});
```

I used ektrop to make the updates from my local java server.
The couchdb is running locally too.

The document I was updating looks something like this:

```
{
  "_id": "doc1",
  "_rev": "1-c86ecaa16d11ae496cb69f596b39610f",
  "name": "count-345",
  "age": "5"
}
```

I updated only the name field.

I thought of trying the in-memory adapter (since it is what I intend to use later on), but it seems that this issue is unrelated to that.

**Comment by nolanlawson** [comment]
So yes, PouchDB has some poor performance profiles if you are making lots of small changes to a single document. You can work around this by setting the revs limit to 1 and/or using auto-compaction, but in general it's not a database that's optimized for that kind of workflow.

If you are making lots and lots of tiny changes to a single doc, and if you don't need sync features that allow you to keep track of the entire document change history, then you may want to look into something like LocalForage or Dexie instead. (Note that I'm not trying to dismiss your issue; just saying that Pouch has certain inherent strengths and weaknesses, and you've identified a weakness. :smiley:)

**Comment by willholley** [comment]
just a thought. In Cloudant, we added an option to defer stemming at write time (so it only occurs during compaction). Would that be a useful optimisation for Pouch?

**Comment by nolanlawson** [comment]
Yeah that sounds like a useful change. Might be tricky though because we have compaction as well as auto-compaction, but presumably the stemming could go in either one.

@hepiyellow In your benchmark are you doing lots of `put()`s or are you using `bulkDocs()`? It is well-known that `bulkDocs()` is much more efficient than doing lots of small `put()`s.

**Comment by hepiyellow** [comment]
Well i am doing lots of single updates and not a bulkDocs on purpose. Thats my usecase.

**Comment by nolanlawson** [comment]
@hepiyellow Yeah PouchDB is really, really not optimized for this use case. You may want to look into operational transforms, e.g. ShareJS.

**Comment by nolanlawson** [comment]
Adding "needs reproducing" label because it's not clear to me there's a test case
