### ISSUE TITLE
Headers are squashed together in "Plugins" page

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5654]
For some reason this page (external.html/external.md) has its headers squashed together. No other page seems to have this issue.

A quick fix may be to just include some `&nbsp;`s in there, but it'd be nice to fix it everywhere since it might occur on some other pages as well.

![screenshot 2016-09-08 09 47 46](https://cloud.githubusercontent.com/assets/283842/18358341/72213c24-75a9-11e6-868d-c9982558d8b7.png)

**Comment by williambelle** [comment]
I can't reproduce this on the branch `pouchdb:fix-docs-markdown`.

Commit 3a10e6e1d8cceef36dea594ed5c43f6bf03f569d should do the trick.

Can you retest please ?

**Comment by nolanlawson** [comment]
Yup, you're right; this is fixed in master. I must have had an old version because of AppCache. Thanks!
