### ISSUE TITLE
Custom builds documentation needs a step-by-step guide for node novices

### ISSUE THREAD

**Issue by hrishiballal** [pouchdb/pouchdb#5655]
### Issue
Documentation about custom builds cannot be understood.

### Info
I am trying to create a custom browser build of Pouch and following the documentation does not help. I am node novice and I don't understand completely how to build custom builds.  The custom build has the following documentation: 
```javascript 
npm install pouchdb-browser 
```
And then has node.js code on how to use it. 

Can someone update how to create a custom build in a step by step guide? Or it would be nice if every release bundles uglified and minified a pouchdb-browser.min file that can be directly used in a browser.

**Comment by nolanlawson** [comment]
What are you trying to do? On this page (https://pouchdb.com/custom.html) we also include source code for pouchdb-browser, which is literally just

```js
var PouchDB = require('pouchdb-core')
  .plugin(require('pouchdb-adapter-idb'))
  .plugin(require('pouchdb-adapter-websql'))
  .plugin(require('pouchdb-adapter-http'))
  .plugin(require('pouchdb-mapreduce'))
  .plugin(require('pouchdb-replication'));
```

There are also examples at https://github.com/nolanlawson/pouchdb-http and https://github.com/nolanlawson/pouchdb-memory. Do those help? If not, please open a PR to add additional information to our docs! 😃

**Comment by nolanlawson** [comment]
Without more details, gonna close this issue, please reopen as necessary.
