### ISSUE TITLE
pouchdb module exports wrong jsnext:main

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5659]
This is a subtle issue, but because the `pouchdb` module is actually a Rolluped version of several other modules, when you `npm install` it, if you then try to use its `jsnext:main`, you'll find you're missing some modules because currently it points to `src/index.js`, which contains references to modules like `pouchdb-core` which are not included in `package.json`.

The fix is to simply use Rollup to build an es6 output as well as a cjs output, and then to make `jsnext:main` point to that.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/a0e171261a1c1e5e9315f59476eb2270dd6d9891
