### ISSUE TITLE
Corrupted revision IDs

### ISSUE THREAD

**Issue by Luukvdo** [pouchdb/pouchdb#5693]
### Issue
I have been running PouchDB 5.4.3 in a duration test which had 5 ARM-based devices using the Node.js version of PouchDB and 1 server running Ubuntu Server 14.04.4 LTS with CouchDB 1.5.0. This duration test has run for about 2 months.
This duration test had a script running which entered data into the server database. Each of the devices had the same Node.js script which would report back if the device received the data pushed from the server.

One of the devices started acting weird after about 1 month. It started spamming the CouchDB server log with the following lines:
```
[Thu, 11 Aug 2016 08:45:01 GMT] [error] [<0.27370.211>] Badarg error in HTTP request
[Thu, 11 Aug 2016 08:45:01 GMT] [info] [<0.27370.211>] Stacktrace: [{erlang,list_to_integer,
                                     ["db1ffac7952e3d97f6965d9d'575d5d9",16],
                                     []},
                                    {couch_doc,parse_revid,1,
                                     [{file,"couch_doc.erl"},{line,163}]},
                                    {couch_doc,
                                     '-transfer_fields/2-lc$^1/1-1-',1,
                                     [{file,"couch_doc.erl"},{line,275}]},
                                    {couch_doc,
                                     '-transfer_fields/2-lc$^1/1-1-',1,
                                     [{file,"couch_doc.erl"},{line,275}]},
                                    {couch_doc,transfer_fields,2,
                                     [{file,"couch_doc.erl"},{line,275}]},
                                    {couch_httpd_db,'-db_req/2-fun-3-',1,
                                     [{file,"couch_httpd_db.erl"},{line,343}]},
                                    {lists,map,2,
                                     [{file,"lists.erl"},{line,1224}]},
                                    {couch_httpd_db,db_req,2,
                                     [{file,"couch_httpd_db.erl"},
                                      {line,342}]}]
[Thu, 11 Aug 2016 08:45:01 GMT] [info] [<0.27370.211>] {IP} - - POST /data/_bulk_docs 500
[Thu, 11 Aug 2016 08:45:01 GMT] [error] [<0.27370.211>] httpd 500 error response:
 {"error":"unknown_error","reason":"badarg"}
```
As you can see the revision that gets posted (`db1ffac7952e3d97f6965d9d'575d5d9`) contains a single quote which the CouchDB server is unable to parse. I have been searching in the CouchDB database and found the revision should actually be `db1ffac7952e3d97f6965d9d7575d5d9`.

While investigating further I found the following 'troublesome' revisions:
- `db1ffac7952e3d97f6965d9d'575d5d9` which should be `db1ffac7952e3d97f6965d9d7575d5d9`
- `686e51b814f316215'92ada696f21550` which should be `686e51b814f316215792ada696f21550`
- `67740094ec51'd2725391ebbb06264c7` which should be `67740094ec517d2725391ebbb06264c7`

I also found some revisions with a single quote of which I couldn't find the original revision anymore:
- `5d1e63445a9414875'950542d5dd02fb`
- `99ec7e57270a9794bf3b5'8f3865cc7a`
- `65343539e20d5650'c87b70d3ad71168`
- `27bb2e7e68d483f2aa04f'1e7fbf9773`

A pattern begins to show: all of the revisions which got 'corrupted' originally had a 7 which got replaced with a single quote.

Now, as I said before; there were 5 devices running in this test. However, only one of them had this issue. Also, many revisions containing a 7 were not affected. It seems like this is a very rare issue, but, in my opinion, a relatively serious one because it stops PouchDB from replicating.

### Info
- Environment: Node.js
- Platform: ARM
- Adapter: LevelDB
- Server: CouchDB with Nginx as a reverse-proxy

### Reproduce
The code can be found in [this](https://gist.github.com/Luukvdo/3577b61b85557b1c9600d2037e6ee81a) gist. It's definitely not the best code but it did the job I wanted it to do.

The server has a database called data with the following design document:
```
[
  {
    "_id": "_design/replication_filters",
    "filters": {
      "replication_test": "function(doc, req) { if(!doc.device) { return false; } return doc.device== req.query.device; }"
    }
  }
]
```

Every half hour a record got inserted into the database using this script:
```bash
#!/usr/bin/env bash

counter=0;

while true;
do
    let counter=counter+1;
    randomInsert=$(( (RANDOM % 5) + 1));
    curl -s -X PUT http://127.0.0.1:5984/data/test_server_$(date +"%s") -d '{"device":'${randomInsert}',"created_at":"'$(date +"%s")'","updated_at":"'$(date +"%s")'"}' -k >/dev/null;
    sleep 1800;
done;
```

**Comment by nolanlawson** [comment]
Hm, are you able to reproduce this consistently using the script you provided? I've never heard of such an issue, but I wonder if it's related to LevelDB stability. Either way, I find the results very surprising.

**Comment by Luukvdo** [comment]
Not consistently unfortunately. It only seems to happen very, very rarely.

I looked into it a bit more and found another device which had a revision ID which got corrupted:
`c04d6e66282698837d1fa869(e601798` which should be `c04d6e66282698837d1fa8698e601798`

Interesting here is that this time there is a `(` which should have been an `8`.

I went digging some more and decided to look at the ASCII table.
When looking at the binary representations, you can see this:
`'` is `00100111`
`7` is `00110111`

`(` is `00101000`
`8` is `00111000`

The fourth bit changed in both instances.
To me it seems more likely this is a either a hardware failure or a deep-level software failure. We designed the device in-house so we will be running some tests to confirm that suspicion.

I'll close this for now. Thanks for looking at the issue anyway :)
