### ISSUE TITLE
Ionic + pouchDB method_not_allowed 405 error

### ISSUE THREAD

**Issue by bgold0** [pouchdb/pouchdb#5699]
### Issue

I am getting the following error when trying to retrieve documents from remote pouchDB database:

>{"error":"method_not_allowed","reason":"Only GET,POST,HEAD allowed","status":405,"name":"method_not_allowed","message":"Only GET,POST,HEAD allowed"}

### Info
- Environment: Hybrid App // Ionic Emulation
- Platform: iOS
- Adapter: SQLite
- Server: Cloudant

### Reproduce

I am currently using pouchDB version 6.0.4, and I am connecting to a cloudant remote couchdb database like so:

    var remote_templates = new PouchDB('https://user:password@name.cloudant.com/database');

    remote_templates.allDocs({
      include_docs: true,
      attachments: true
    }).then(function (result) {
      // handle result
      console.log(JSON.stringify(result));
    }).catch(function (err) {
      console.log(JSON.stringify(err));
    });

I have this in my ionic config.xml file: `  <access origin="*" />`

And I have CORS enabled in cloudant.

I am using the Xcode emulator by doing the following command:

    ionic emulate ios --livereload --target=iPad-2

I have absolutely no clue why this is happening or how to fix it. Any guidance would be GREATLY appreciated as I can't really do much else without fixing this problem.

**Comment by nolanlawson** [comment]
Did you find a solution for this? Just curious.

**Comment by bgold0** [comment]
I was being stupid and called my design view and not strictly the database in `new PouchDB`.
