### ISSUE TITLE
Remove Old Revision when update ?

### ISSUE THREAD

**Issue by Nishanth2** [pouchdb/pouchdb#5704]
### Info
Pouchdb
- Adapter: (IndexedDB.)

Hi,
Is there any way to delete the old revision from indexdb on browser storage ?
i tired  using  
new PouchDB('time', {revs_limit: 1, auto_compaction: true})

But still I see all the revision in my browser indexedDB .

i am using a real time update on database on every seconds when user logged in , so it's goes more than thousands of revision in my db ,

So is there any other way to deal with it ?..

like  when updating the new revision remove the old one ?

**Comment by nolanlawson** [comment]
@Nishanth2 Hm, did you refresh IndexedDB? Sometimes the Chrome Dev Tools will show old data unless you right-click and choose refresh. Otherwise it should indeed delete old revisions.

**Comment by Nishanth2** [comment]
@nolanlawson  Yes You are Right  , It's related to chrome dev tool and Even I found exactly Whats the problem !.   IF I use only Pouchdb  and Set i  to  new PouchDB('time', {revs_limit: 1, auto_compaction: true})
It works Perfectly Fine everytime I updated seconds it stores only 1 doc with new revision number ,

But The problem start when i add this line 
  this.remote = 'http://localhost:5984/time';
let options = {
      live: true,
      retry: true,
      continuous: true
    };
this.timedb.sync(this.remote, options)

So when the couchdb sync it gets all the revision in the pocuhdb indexdb !

Looks like I need to limit the revision even for couchdb .. I am just searching now for it < how to fix this issue

**Comment by nolanlawson** [comment]
You have to set revs_limit in the CouchDB settings, yeah.

So can we close this issue?

**Comment by Nishanth2** [comment]
@nolanlawson   But I coudn't find out how to set revs_limit on CouchDB ,

Anyway You can close this issue ..

Thank You

**Comment by daleharvey** [comment]
https://wiki.apache.org/couchdb/HTTP_database_API its the `_revs_limit` option

Beware that the downside of reducing revs_limits is that you are more likely to introduce conflicts when you are offline for any period of time, the revsLimit is basically the amount of changes you can make to a document offline before it counts as a conflict

**Comment by Bohooslav** [comment]
> https://wiki.apache.org/couchdb/HTTP_database_API its the `_revs_limit` option
> 
> Beware that the downside of reducing revs_limits is that you are more likely to introduce conflicts when you are offline for any period of time, the revsLimit is basically the amount of changes you can make to a document offline before it counts as a conflict

The link doesn't work for me. I will appreciate any update. Thanks

**Comment by Terreii** [comment]
> > https://wiki.apache.org/couchdb/HTTP_database_API its the `_revs_limit` option
> > Beware that the downside of reducing revs_limits is that you are more likely to introduce conflicts when you are offline for any period of time, the revsLimit is basically the amount of changes you can make to a document offline before it counts as a conflict
> 
> The link doesn't work for me. I will appreciate any update. Thanks

Here you go: https://docs.couchdb.org/en/3.2.2/api/database/misc.html#db-revs-limit
