### ISSUE TITLE
Broken markdown on "Map/reduce queries" doc page

### ISSUE THREAD

**Issue by eljenso** [pouchdb/pouchdb#5709]
### Issue
Some sections on the doc page "Map/reduce queries" are not well formated.

### Info
- Environment: browser
- Platform: Chrome

### Reproduce
Visit https://pouchdb.com/guides/queries.html and look at text below first blue box.

**Comment by pjhampton** [comment]
Yep, this is the same on the https://pouchdb.com/adapters.html page. It seems to be something wrong with the last deploy and my commit (#5691).

Working on it now 😰

**Comment by nickcolley** [comment]
@pjhampton (just encase you haven't got the chance yet) try putting the html on one line with no whitespace between tags...

**Comment by pjhampton** [comment]
Thanks for the tip @nickcolley!! 😄 
Unfortunately, no dice.

**Comment by willholley** [comment]
https://pouchdb.com/guides/attachments.html similarly affected :(

**Comment by pjhampton** [comment]
@nickcolley @willholley 

Yeah, this seems to have leaked throughout the website. I can't help but think the HTML is messing with Jekyll's markdown rendering processing. I'm really not sure. I have tried a couple of things.

Should we (I) convert this markup to html? Possibly the other way around.

**Comment by willholley** [comment]
it looks like it was https://github.com/pouchdb/pouchdb/commit/5c8289bb4d1c53cd89e7ba4a8f355b2773b0c196#diff-e3e2a9bfd88566b05001b02a3f51d286 that broke things. Just digging into why...

**Comment by pjhampton** [comment]
@willholley could it just be for the reason that it is no longer on one line like @nickcolley suggested?

**Comment by willholley** [comment]
@pjhampton no, it's the extra divs added in that commit. Perhaps there's a different resolution to the issue that was attempting to fix (#5495)
