### ISSUE TITLE
Secure sync between App and DB

### ISSUE THREAD

**Issue by linvi** [pouchdb/pouchdb#5715]
More than an issue, it is a question. In all the documentation that I read, the sync between a client and a database.

I am trying to build a cordova application. To ensure the security of the database, I need to ensure that the app does not store the database url in plain.

Therefore I thought I would synchronize with the following architecture : 

**PouchDB (App/Client)** -> **Node Server** -> **CouchDB**

Where **Node Server** will store the URL/credentials of the CouchDB.

Does PouchDB provide such feature?
If yes could you point me to the documentation as I was not able to find it.

Thank you for your help.

**Comment by mszajner** [comment]
You could create server.js like this:
`var socketPouchServer = require('socket-pouch/server');

socketPouchServer.listen(5985, {
    pouchCreator: function (dbName) {
		return new PouchDB(dbName, {
            url: 'http://couchdb_user:couchdb_pass@couchdb_host:couchdb_port'
        });
  }
}, function () {
    console.log('server started!');
});
`
But how do You secure connection between your Application and Node Server?

**Comment by nolanlawson** [comment]
Yes, you can set up a proxy server using Node/Nginx/Apache/etc. and then proxy between your client side and your CouchDB. Any HTTP proxy server will do; here is a guide on Nginx: https://wiki.apache.org/couchdb/Nginx_As_a_Reverse_Proxy
