### ISSUE TITLE
Is it possible to skip the setup for a local DB ?

### ISSUE THREAD

**Issue by akofman** [pouchdb/pouchdb#5716]
### Issue
Hello! 👋
With remote database it is possible to configure the skip_setup option but not with local database. In that case, is there an other way to check if a database already exists ?
Thanks !

### Info
- Environment: hybrid app
- Platform: iOS
- Adapter: WebSQL
- Server: none

### Reproduce
`new PouchDB('myDB', { 'skip_setup': true });`

**Comment by nolanlawson** [comment]
There is currently no way to tell a local database to skip its setup, no. You can use the [pouchdb-all-dbs](https://github.com/nolanlawson/pouchdb-all-dbs) plugin however which can tell you which DBs exist and which ones don't. Please reopen if this doesn't address your concern!

**Comment by akofman** [comment]
Yep I finally used that plugin. Thanks.
