### ISSUE TITLE
support _selector filter in the replicator

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#5717]
### Issue

CouchDB 2.0 adds a [new way](https://docs.couchdb.org/en/2.0.0/api/database/changes.html#selector) of filtering `_changes` based on the Mango query language. This is significantly more efficient than JavaScript based filtering (up to 10x in my tests), so it would be useful for Pouch's replicator to support it. The CouchDB replicator supports it (though it isn't yet documented) by adding a `"selector"` field to the replication doc/option. This instructs the replicator to POST to `_changes?filter=_selector` with the selector in the body.
### Info
- Environment: all
- Platform: all
- Adapter: HTTP
- Server: CouchDB/Cloudant
### Questions
1. Is it acceptable to support this for the HTTP adapter only, at least as a first pass?
2. ~In time it would be good to support this in PouchDB local adapters as well. Any thoughts as to how we might manage the dependency on PouchDB-find?~ PouchDB-find is now integrated into the monorepo so this should be more straightforward

Also a reminder that we'll need to update the checkpointing logic to account for the selector.

**Comment by ronag** [comment]
Also the '_design' filter would be useful!

**Comment by jefbarn** [comment]
If anyone wants to experiment with this...

```
PouchDB.plugin((PouchDB) => {
  let pouchReplicate = PouchDB.replicate

  PouchDB.replicate = (source, target, repOptions) => {

    let sourceAjax = source._ajax
    source._ajax = (ajaxOps, callback) => {
      if (ajaxOps.url.includes('_selector')) {
        ajaxOps.url = ajaxOps.url.replace('filter=_selector%2F_selector', 'filter=_selector')
        ajaxOps.method = 'POST'
        ajaxOps.body = {
          selector: repOptions.selector
        }
      }
      return sourceAjax(ajaxOps, callback)
    }
    return pouchReplicate(source, target, repOptions)
  }
})
```

then you can...

```
     replication = PouchDB.replicate(remote, local, {
        filter: '_selector',
        selector: {
          collection: {
            $in: [
              'sites',
              'structures',
              'people',
            ]
          }
        }
      })
```

**Comment by burggraf** [comment]
@jefbarn can you explain exactly how to implement this as a plugin?  I'd like to try this out.

**Comment by jefbarn** [comment]
@burggraf the 'implementation' is posted above, just those 10 lines of code.  However, it is a naive patch, it simply overrides some methods in the pouchdb http adapter, so there is no error checking and only works with remote couchdb server.
A proper implementation for this should probably wait until pouchdb-find is integrated into pouchdb (#6020) then it could support both local and remote dbs.

**Comment by burggraf** [comment]
@jefbarn I mean -- which file should this code be placed in, and precisely where?

**Comment by jefbarn** [comment]
@burggraf You add the code directly to your own js file.
Here's the gist:
https://gist.github.com/jefbarn/47e8d658059df9def7e235e8f4ea8725

**Comment by burggraf** [comment]
@jefbarn gotcha.  thanks so much.

**Comment by jo** [comment]
Here is the Erlang code btw: https://github.com/apache/couchdb-couch/pull/162/files

**Comment by garrensmith** [comment]
Not that pouchdb-find has landed into the monorepo we should be able to leverage this code https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-find/src/adapters/local/find/in-memory-filter.js to do the work locally in pouchdb

**Comment by jo** [comment]
Hi @jefbarn thanks for your patch!

I have tried it and it works. Basically. But one thing does not work: I cannot [abort a live replication](https://gist.github.com/jo/c818e9147e38ee2fe39cc938a37e451e). It seems that XMLHttpRequest (or PouchDB's wrapper) handles `abort` differently when using post requests.

Does anybody has a clue whats going on?

**Comment by willholley** [comment]
the PR for this is now merged and will be in the next PouchDB release.

**Comment by MohitKumar1991** [comment]
Is this in the production release now ?

**Comment by jo** [comment]
yes it is

**Comment by prakashsys** [comment]
Can I use a selector approach for live sync between CouchDB and PouchDB?
