### ISSUE TITLE
Question: intercept AJAX requests globally

### ISSUE THREAD

**Issue by pavel** [pouchdb/pouchdb#5722]
### Question
How to intercept AJAX requests made to a remove CouchDB instance by Pouch globally?
For example handle `401` response globally to redirect a user to a login page.
I tried to find this in docs with no luck.

### Info
- Environment: browser
- Platform: desktop
- Server: Remote CouchDB

**Comment by nolanlawson** [comment]
This seems to be a duplicate of #5607 and/or #5322; please reopen if those issues don't address your concern.
