### ISSUE TITLE
We are now mistakenly shipping leveldown in pouchdb-adapter-leveldb-core

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5730]
Check the dependencies here: https://www.npmjs.com/package/pouchdb-adapter-leveldb-core . This should not contain leveldb because e.g. the memdown adapter does not need it.

Looks like this snuck in with the changes to dynamically check `require()` statements and generate the `dependencies` from that. I noticed due to a failed install on (what else) a Windows machine.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/1ad929b06e48f95563f1decb34d7ee5b7ce9f66f
