### ISSUE TITLE
Fix fuzzy tests

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5732]
I've seen the fuzzy tests fail on Travis very infrequently. I suspect these failures are related to https://github.com/nolanlawson/local-npm/issues/129#issuecomment-250307462.

Clearly this is something we should try to track down, since sync is one of the core value propositions of PouchDB.

**Comment by willholley** [comment]
I can reproduce a failure using seed = 1474113962061. Investigating...

**Comment by daleharvey** [comment]
hrm, I thought the seed system wasnt working which was why I wasnt investigating, but yeh the fact these fail is a definite bug somewhere

**Comment by willholley** [comment]
@daleharvey correct - the seed system isn't working, but that seed produced a failure. I think getting the test actions to be deterministic is a prerequisite to fixing, though.

**Comment by willholley** [comment]
it seems that removing the[ explicit seedrandom](https://github.com/pouchdb/pouchdb/blob/master/tests/fuzzy/test.fuzzy.js#L20) initialisation in tests.fuzzy.js (which already occurs in [node.setup.js](https://github.com/pouchdb/pouchdb/blob/master/tests/integration/node.setup.js#L9)) makes the test actions deterministic in node.

**Comment by willholley** [comment]
with the PR at https://github.com/pouchdb/pouchdb/pull/5748, the seed 1475508413973 is reliably failing for me now. A full debug log of the failing test run is available at: https://gist.github.com/willholley/edef2ed13a4837548b3619bca12876d4. I also added some logging around the test actions performed. These are included in the log referenced above but, if you're interested in the test actions only, they're available at https://gist.github.com/willholley/442ccc1b5fe1ac4cd1d9e761b24dc7f6.

**Comment by willholley** [comment]
I narrowed this down a bit. If `actionCount` in the test is set to 39, the test passes (with the seed above). If it is `40` it fails. The 40th action is a doc removal.

[Debug](https://gist.github.com/willholley/d3489871b54787d4b4893a51250446a3) and [action](https://gist.github.com/willholley/75519551482bfdf13a1518a8542d75e7) logs for the failing run with 40 actions added as gists.

**Comment by willholley** [comment]
I'm pretty sure that the issue for my breaking run above is PouchDB not replicating rev-1 conflicts correctly. The test [explicitly creates](https://github.com/pouchdb/pouchdb/blob/master/tests/fuzzy/test.fuzzy.js#L61) this situation and it's a [known issue](https://github.com/pouchdb/pouchdb/issues/4651) that Pouch doesn't correctly handle it.

**Comment by willholley** [comment]
just to confirm, removing [this line](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-replication/src/getDocs.js#L169) fixes the test. Mystery solved. In terms of a short term fix, I think we could either:
 - skip the `getRevisionOneDocs` optimisation if bulkGet is detected. This won't help our tests against Couch 1.6 etc.
 - change the test to generate conflicts at > rev-1. This changes the meaning of the test a bit.
 - remove/make optional the `getRevisionOneDocs` optimisation.

**Comment by daleharvey** [comment]
I am mostly chuffed that this was finding genuine reproducable bugs :) 

> skip the getRevisionOneDocs optimisation if bulkGet is detected. 
> This won't help our tests against Couch 1.6 etc.

Doing this and running the fuzzy tests against 2.0 seems like a good approach, need to look into the performance impact of removing the optimisation entirely, however this seems safe to do for now.

**Comment by willholley** [comment]
I still don't quite understand the failing test. At least, I'm struggling to create a standalone reproduction of it. I can identify the action which breaks things (the final `db.remove()`) and removing the allDocs optimisation definitely fixes it, but the actions to get the db into the state which breaks are more involved than just the final 6 steps in the test run.

**Comment by willholley** [comment]
nvm - got it failing now :)

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/8f0d7d2248ed46bffb9350ce50a033113241ae8f
