### ISSUE TITLE
Enhancement: Support for Fluture (Futures)

### ISSUE THREAD

**Issue by Shard** [pouchdb/pouchdb#5733]
I have been using [Fluture](https://github.com/Avaq/Fluture) of late for interacting with PouchDB as opposed to Promises and I think it would be a great thing if there could be more native support for Futures available.  While Futures wouldn't be the ideal choice for everyone, people programming in a functional/[fantasy-land](https://github.com/fantasyland/fantasy-land) javascript enviroment or wanting  more control of their promises would feel right at home.

There is a small [package](https://github.com/futurize/futurize) for converting Promises to Flutures that could be made into a Pouch plugin to convert at Promises to Futures at runtime but it would seem more ideal from a code bloat perspective if it could done at build time.

I would be interested in writing a PR for an alternative build that exposes futures instead of promises but I wanted to check if this is something that should be done as a separate repo/plugin instead.

**Comment by nickcolley** [comment]
Hey @Shard that sounds really cool, and would be perfect as a plugin!

Let us know if you need any help with that, a good start could be https://github.com/pouchdb/plugin-seed 👍
