### ISSUE TITLE
md5sum ID for replication checkpointer can begin with '.'

### ISSUE THREAD

**Issue by dharders** [pouchdb/pouchdb#5735]
### Issue
I have a CouchDB 2.0 server behind an __nginx__ reverse proxy and have replicated many times with success. 

However, very occasionally I noticed an issue where replication was failing and found that it was when the Checkpointer md5sum doc id for the remote `/_local/` endpoint started with a `.` 

eg `db.example.com/db/_local/.ySigrUu3ztR0dJfrtzZ3A%3D%3D`

I receive a `403 Forbidden` on the OPTIONS pre-flight followed up with the PouchDB error `writeCheckpoint completed with error, status 0`.

I ended up tracing this issue to my __nginx config__ blocking access to all files beginning with '.' for security reasons (i.e. system files, hidden files) as protection if 'secret' files were accidentally copied to a 'public' folder.

I ended up changing my nginx location regex to only allow files beginning with '.' if prefixed with '/_local/' by changing:
```
location ~ \/\. { deny all; }
```
to
```
location ~ (?<!\/_local)\/\. { deny all; }
```

This configuration seems to work for now as long as I don't create any document id's beginning with '.', which I have control over so shouldn't be an issue.

I found the PouchDB `generateReplicationId(src, target, opts)` function responsible for calculating the md5sum:

```javascript
// can't use straight-up md5 alphabet, because
// the char '/' is interpreted as being for attachments,
// and + is also not url-safe
md5sum = md5sum.replace(/\//g, '.').replace(/\+/g, '_');
return '_local/' + md5sum;
```

From above it looks like the occasions I was hit with the 403 was likely due to a leading `/` being replaced by a `.`

Were these replacement characters (`. and _`) chosen for a special reason ? Could we change the `.` to a `$` or similar ?

My current setup is working so I was a little reluctant to post this issue and looking at the CouchDB docs it looks like Document Id's don't have any restrictions (apart from encoding '/' to '%2F', from what I could see), unlike DB names which must not start with a '.' or '_'.

So I guess I'm after confirmation that this behaviour is by design (and stick with my current nginx solution) or any tips on where this may bite me in the future ?

### Info
- Environment: All
- Platform: All
- Adapter: All
- Server: CouchDB 2.0 , nginx reverse proxy
- PouchDB 6.0.5

**Comment by daleharvey** [comment]
Hrm, while choosing another identifier seems reasonable here, I dont think `.` is particularly special. However changing this is problematic due to backwards compat, if we change the checkpoint id generation then existing checkpoints will not be found

**Comment by dharders** [comment]
> due to backwards compat, if we change the checkpoint id generation then existing checkpoints will not be found

Good point!

I'll close this out and reopen if a related issue pops up again in the future. Thanks!
