### ISSUE TITLE
PouchDB should emit a warning if you insert an attachment without a content_type

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5736]
This is nearly always a bug (e.g. see https://github.com/pouchdb/pouchdb/issues/5726).

We should do a `console.warn` if this happens. (Not an error, because people may be replicating from CouchDBs they have no control over, where the type is omitted for whatever reason.)

**Comment by jasuch** [comment]
Hi! :)

Can I help with this? I really want to start in Open Source projects and I feel confortable for doing this.

**Comment by daleharvey** [comment]
Yup defiitely, at a guess the code that needs changed will be in https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/adapter.js#L782 and https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/adapter.js#L232

As this is a warning we dont have a decent way to test this so manually verifying it should be fine, but make sure that both db.bulkDocs and db.putAttachment do the same, there is some more help @ https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md and if you hit any questions feel free to ask, thanks :)

**Comment by pecey** [comment]
Is anyone still working on this? Or I would like to take this up.

**Comment by jpmllr89** [comment]
Same here. Willing to work with others, too.

**Comment by willholley** [comment]
@pecey @jpmllr89 please feel free to have a go and submit a PR. If you have questions/comments then just go ahead an ask in this thread.

**Comment by MBFlewelling** [comment]
Hello, I'd be interested in working this if help is still needed

**Comment by nolanlawson** [comment]
@MBFlewelling Yes please feel free to take this up. :)

**Comment by PavanBahuguni** [comment]
I would like to take up the issue.

**Comment by nolanlawson** [comment]
fixed in https://github.com/pouchdb/pouchdb/pull/5826, sorry that someone grabbed it before you!
