### ISSUE TITLE
Rolling Up PouchDB

### ISSUE THREAD

**Issue by danbucholtz** [pouchdb/pouchdb#5738]
### Issue
PouchDB cannot be rolled-up using RollUp if I am utilizing the `jsnext:main` option, and using the `browser` version.

### Info
Browser environment

### Reproduce
I built a very small application that that basically runs rollup against pouchdb.
```
git clone git@github.com:danbucholtz/rollup-commonjs.git
git checkout test8 (the branch I am using for this test)
npm install

open node_modules/pouchdb/package.json, ensure jsnext:main to point to ./lib/index.es.js (it does not as of Sept 29th)

npm run test
```

The command will error out with an error message indicating the following:

```
ERROR:  Module /Users/dan/Dev/rollup-commonjs/node_modules/js-extend/extend.js does not export extend (imported by /Users/dan/Dev/rollup-commonjs/node_modules/pouchdb/lib/index-browser.es.js)
```

I think the fix would be this:

```
import jsExtend from 'js-extend';

var extend = jsExtend.extend;

// continue using extend everywhere as before
```

I have tried to find this in the `pouchdb` repo to update and test but I am having a hard time locating where I need to make the changes.

Thanks,
Dan

**Comment by nolanlawson** [comment]
You'll need to ignore commonjs modules. One extremely easy solution is to use this plugin, which ignores commonjs modules and only pays attention to es6 modules: https://github.com/nolanlawson/rollup-plugin-node-resolve-auto

Please let me know if this answers your question; if not you'll need to use rollup-plugin-node-resolve and configure it to tell it exactly which modules to ignore (such as `js-extend`) and which ones to use.

**Comment by danbucholtz** [comment]
Doesn't it need those files that are being skipped, though?

Full disclosure, we are using Rollup in Ionic and we're still just learning about it.  We are seeing some issues with commonjs libraries.  I wonder if this will help us out.

Thanks,
Dan

**Comment by danbucholtz** [comment]
No dice with that plugin.  I was already using the `node-resolve` rollup plugin as well as the `commonjs` plugin.  I removed both and made a vanilla test with your plugin. It didn't work unfortunately.

The code for the latest example is on `test9` branch.

The repo is very simple.  It is literally this

```
import PouchDB from 'pouchdb';

console.log('PouchDB: ', PouchDB);
```

and then the rollup config.

```
var rollup = require('rollup');
//var nodeResolve = require('rollup-plugin-node-resolve');

// use nolans plugin
var nodeResolve = require('rollup-plugin-node-resolve-auto');

//var commonjs = require('rollup-plugin-commonjs');

rollup.rollup({
  entry: './dist/index.js',
  plugins: [
    nodeResolve({
      module: true,
      jsnext: true,
      browser: true
    }),
    //commonjs()
  ]
}).then( function ( bundle ) {
  // Generate bundle + sourcemap
  return bundle.write({
    format: 'iife',
    moduleName: "mybundle",
    dest: './dist/bundle.js'
  });
}).then(function() {
  console.log('Bundling complete');
}).catch(function(err){
  console.log("ERROR: ", err.message);
  process.exit(1);
})
```



To run it easily, just follow the steps below.
```
git clone git@github.com:danbucholtz/rollup-commonjs.git
git checkout test9 (the branch I am using for this test)
npm install

open node_modules/pouchdb/package.json, ensure jsnext:main to point to ./lib/index.es.js (it does not as of Sept 29th)

npm run test
```

Thanks,
Dan

**Comment by Bouzmine** [comment]
@nolanlawson Doesn't work on my side neither.

**Comment by danbucholtz** [comment]
We are tracking this on the ionic side of things @Bouzmine.  We successfully were able to roll this up today.  Not in the way we (Ionic) would like, but at least it can be done.  Our findings are that it would be a challenge to provide defaults that work for all libs with Rollup.  Cases like rolling up PouchDB can be solved with providing custom named exports.

Thanks,
Dan

**Comment by nolanlawson** [comment]
This should be working in PouchDB 6.0.7 now.
