### ISSUE TITLE
ReferenceError: Can't find variable: Yr

### ISSUE THREAD

**Issue by avishekjana** [pouchdb/pouchdb#5742]
### Issue
I've implemented Pouchdb in my Rails application. In rails development environment it's working seamlessly. But while using in production environment the pouchdb-6.0.4.min.js file is giving this error "ReferenceError: Can't find variable: Yr" in line no. 5933. And as the library file is not loading the next error i'm getting in web console is "ReferenceError: Can't find variable: PouchDB". Is there any solution for this?

### Info
- Environment: Ruby on Rails application in Production
- Platform: Major web browsers (Chrome/FF/Safari etc.)
- Adapter: WebSQL

**Comment by garrensmith** [comment]
You need to enable source maps so you can see what is happening. 

All misspelling thanks to my iPhone.




On Fri, Sep 30, 2016 at 8:58 AM +0200, "Avishek Jana" <notifications@github.com> wrote:












Issue



I've implemented Pouchdb in my Rails application. In rails development environment it's working seamlessly. But while using in production environment the pouchdb-6.0.4.min.js file is giving this error "ReferenceError: Can't find variable: Yr" in line no. 5933. And as the library file is not loading the next error i'm getting in web console is "ReferenceError: Can't find variable: PouchDB". Is there any solution for this?

Info


Environment: (Node.js/browser/hybrid app/etc.)
Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)


Reproduce



Write the steps for others to reproduce issue here. Providing a code example, links to a repository or a live example (JSBin etc) are even more helpful.

**Comment by nolanlawson** [comment]
Yes, please use pouchdb.js instead of pouchdb.min.js and see if you can provide a screenshot or the exact line that's failing.

My guess is that this is not a PouchDB error but is a user error; maybe your `map()` function references a variable that doesn't exist?

**Comment by avishekjana** [comment]
I fixed the problem temporarily by using PouchDb CDN file, and it's working fine. Ok now let me try this with normal pouchdb.js file.

**Comment by nolanlawson** [comment]
Sounds like this was a build issue. Closing, please reopen as necessary.
