### ISSUE TITLE
Best approach on handling large dataset for offline-first Mobile Apps (Cordova)

### ISSUE THREAD

**Issue by m00g33k** [pouchdb/pouchdb#5755]
### Issue
So I'm using Ionic v2 and using Pouch for mobile development using sqlite. Data coming from a REST API which contains something like this:
```
{
  "record-id": "2332255",
  "record-name": "record-ABC-XTY",
  "record-items": [
    {
      "item-id": "456454",
      "item-name": "item-XADD",
      "category": "Cat1",
      "subcategory": "Subcat1",
      "location": "LocationXYZ",
      "owner": "Person1",
      "data-rows": [
        {
          "row-name": "sampleRowName1",
          "row-value": "ABC-XASS"
        },
        {
          "row-name": "sampleRowName2",
          "row-value": "ABC-XASS"
        }
      ]
    },
    {
      "item-id": "654645",
      "item-name": "item-BNSSA",
      "category": "Cat2",
      "subcategory": "Subcat2",
      "location": "LocationABC",
      "owner": "Person2",
      "data-rows": [
        {
          "row-name": "sampleRowName1",
          "row-value": "ABC-XASS"
        },
        {
          "row-name": "sampleRowName2",
          "row-value": "ABC-XASS"
        }
      ]
    }
  ]
}


```
Now as you can see, the *record-items* could contain 100,000 items or more (est json size: 32mb). Right now I'm lost on which approach should I take. Optimized data handling is crucial and I don't know what PouchDB approach is better. Here are some of my thoughts.

1.  Save the whole JSON data as one entry for PouchDB. But I'm worried that it will take up a large memory when retrieved and will make that application slow. 
2.  Chunk the record-items by one pouch entry record and retrieve it individually. I'm not sure if this is better in terms of overall performance but PouchDB record will probably be larger (?).

Also, there will be sorting, fetching all data (only the _ids and few fields just to show a list of all results) and searching.

### Info
- Environment: Ionic V2
- Platform: Android
- Adapter: sqlite
- Server: None

### Reproduce
(Not applicable)

**Comment by natcohen** [comment]
This is an issue tracker and not a support platform... You should post on stackoverflow instead!

To quickly answer your question, option 2 is the way to go (I started with option 1 and my app became extremely slow because it was always dealing with this huge document). You can use views or pouchdb find in order to fetch the data (specific fields) you need.

**Comment by m00g33k** [comment]
Apologies, my bad. Will close this issue. I hope the creators can delete this. Thanks for the advice btw!
