### ISSUE TITLE
document update conflict even with correct _id and _rev fields

### ISSUE THREAD

**Issue by toumiGit** [pouchdb/pouchdb#5757]

**Comment by toumiGit** [comment]
I insert a document {_id : X, _rev: Y}, then delete it.
when i insert a new document with X as _id X then when i delete it then I have 409 document update conflict

**Comment by willholley** [comment]
@toumiGit can you provide a bit more information as per the issue template? What environment/backend datastore are you using? can you provide a reproducible test case?

PouchDB does have [CI tests](https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.basics.js#L287) that cover this situation, so a reproduction would really help.

**Comment by nolanlawson** [comment]
Please reopen if you have tests to reproduce, thanks!
