### ISSUE TITLE
debug package used by pouchdb is not compatible with webpack

### ISSUE THREAD

**Issue by episage** [pouchdb/pouchdb#5770]
### Issue
I use `react-boilerplate` which uses `webpack` as a bundler. `pouchdb` uses `debug` package which has `browser` and `main` properties in `package.json`. Unfortunately `webpack` doesn't pick up `browser` property and tries to load `fs`, `net` and other, `node` specific modules from `node.js` file. Please read the issue in `Links` section below.

### Info
- Environment: browser
- Platform: any browser
- Adapter: any
- Server: any

### Reproduce
Install `https://github.com/mxstbr/react-boilerplate` then:
`npm i pouchdb --save`
put `import PouchDB from 'pouchdb';` in `app.js`

### Links
Issue on `react-boilerplate` with reproduction:
https://github.com/mxstbr/react-boilerplate/issues/1007#issuecomment-252863702

**Comment by singhshashi** [comment]
I read the issue you linked to and it seems it was an issue with the webpack setup of that project https://github.com/mxstbr/react-boilerplate/issues/1007#issuecomment-254193058 

If this is resolved, then I guess you could close this issue.
