### ISSUE TITLE
PUT with _conflicts instead of 409

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#5772]
Related to #5771.

Is there a way for `put` or `bulkDocs` to behave similar to how the replicator works, i.e. it does arbitrary conflict resolution and adds to the `_conflicts` array instead of returning 409?

**Comment by daleharvey** [comment]
If you specify `new_edits: false` in your bulkDocs request you can insert new conflicts, the tests may give you enough of an idea how to do this, search for `new_edits` in https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.conflicts.js

**Comment by ronag** [comment]
@daleharvey: I've tried playing around with it but I'm still confused how that should work. The tests also doesn't show anything related to `_conflicts`.

May I ask for a hint or two? http://stackoverflow.com/questions/40046504/create-or-update-with-conflicts-instead-of-409
