### ISSUE TITLE
multiple Pouch DB (one way) to CouchDB sync

### ISSUE THREAD

**Issue by sidn041** [pouchdb/pouchdb#5774]
HI,
I need to submit data from multiple mobile apps. in my mobile app I am planning to use pouchdb to store the document, later I want this document to sync to couchdb one-way only.
what will happen if I submit data from multiple apps ? will pouch db create same document ID and overwrite data in couchDB ?

**Comment by ronag** [comment]
See, http://wiki.apache.org/couchdb/Replication_and_conflicts

**Comment by sidn041** [comment]
Thanks, let me try to explain my scenario,
I have 4+ mobile device all using pouchDB oneway Sync, 
they will update to same CouchDB.
most of the times these devices will be off network, when they come in network they will  sync to couchDB at different times.
is it possible that these multiple PouchDB can create document with same "ID" ?
which means on CouchDB they will be overwriting each other instead of just creating new document.

**Comment by ahaus** [comment]
You can create your own "ID" (_id) for the document on the device/mobile which includes some device specific information (e.g. device id, username etc.).
