### ISSUE TITLE
Conflict in _local when updating database

### ISSUE THREAD

**Issue by webnoob** [pouchdb/pouchdb#5777]
### Issue
When calling a method like db.bulkDocs() I'm getting something like:

> http://myhosted.couchdb.com:5984/userdb-6938/_local/H73d9PBjwCczSUMy4NZ6bA%3D%3D 409 (Conflict)

It doesn't happen all the time and sometimes when saving 100 items, I'll get one or 2 but other times I have a couple of dozen show up. I don't get an error on the bulkDocs call, it's just something I see in the console after the bulkDocs call has been made.

My main question is: Is this actually a problem or something that should be ignored? I understand document conflicts but this isn't something I can handle as it seems to be made by pouchDB.

### Info
- Environment: (Browser
- Platform: Chrome
- Adapter: WebSQL
- Server: CouchDB

### Reproduce
I'm calling the following with between 5 and 100 items.

try {
      await db.bulkDocs(toBeSaved)
    } catch (err) {
      errorCallback(err, importObj)
    }

Here are som examples of the errors I get
```
index-browser.js?e981:7118 PUT http://myhosted.couchdb.com:5984/userdb-693131/_local/0R6FJaZsHZyV5_h2VG0IGg%3D%3D 409 (Conflict)
index-browser.js?e981:7118 PUT http://myhosted.couchdb.com:5984/userdb-693131/_local/0R6FJaZsHZyV5_h2VG0IGg%3D%3D 409 (Conflict)
index-browser.js?e981:7118 PUT http://myhosted.couchdb.com:5984/userdb-693131/_local/0R6FJaZsHZyV5_h2VG0IGg%3D%3D 409 (Conflict)
index-browser.js?e981:7118 PUT http://myhosted.couchdb.com5984/userdb-693131/_local/0R6FJaZsHZyV5_h2VG0IGg%3D%3D 409 (Conflict)
index-browser.js?e981:7118 PUT http://myhosted.couchdb.com:5984/userdb-693131/_local/0R6FJaZsHZyV5_h2VG0IGg%3D%3D 409

index-browser.js?e981:7118 PUT http://myhosted.couchdb.com:5984/userdb-693131/_local/hPV1Tym7ETIw5bcyruMG7w%3D%3D 409
index-browser.js?e981:7118 PUT http://myhosted.couchdb.com:5984/userdb-693131/_local/hPV1Tym7ETIw5bcyruMG7w%3D%3D 409 (Conflict)
```

**Comment by daleharvey** [comment]
Are you doing any replications? in particular parallel replications?

**Comment by webnoob** [comment]
I'm calling sync(), that's all.

**Comment by daleharvey** [comment]
ah, its very doubtful that its something you need to worry about, however I am going to look a little at this before closing, a single sync should not be generating conflicts as far as I remember

**Comment by webnoob** [comment]
Well it seems to be causing the error I've posted in my original post so I
do need to get it sorted because it prevents replication at times.

Thanks for your efforts.

**Comment by daleharvey** [comment]
Can you post a full code sample of your failure?

**Comment by webnoob** [comment]
Hmm, I don't think I can post a full working example as the app is quite
widespread however the methods of connecting to the database and making a
call are in my op.

**Comment by webnoob** [comment]
Oh hang on sorry. This is a different issue to the one I was thinking. I actually managed to sort this issue as I was causing a replication on each call to the db which caused issues. I'm replicating after doing a load of bulk ops now. 

Sorry for causing confusion and not closing the issue (I forgot I asked here)
