### ISSUE TITLE
Replication hangs with larger attachments

### ISSUE THREAD

**Issue by ahaus** [pouchdb/pouchdb#5779]
### Issue

When I add a document with a larger attachment (e.g. 4 MB) the replication from pouchdb to couchdb hangs. pouchdb tries to push the document in an endless loop which also hinders to replicate newer documents. This applies to inline attachments as well as when I use. doc.putAttachments(..)
### Info
- Environment: (Node.js/browser/hybrid app/etc.)
  React Native 0.34
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
  iOS 9.x, Android 5.x, Android 6.x
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
  Asyncstorage (pouchdb-adapter-asyncstorage)
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)
  Couchdb 1.61
  ### Reproduce
  
  Create a document with a larger attachment (e.g. 4 MB image) and try to sync to a remote database.

**Comment by ahaus** [comment]
It looks like it starts with image in size of 1.5 - 2MB

**Comment by nolanlawson** [comment]
Yeah the replication protocol does not handle such large images very well. Unfortunately you will have to break it up into smaller images or write your own replication logic to fix this. I'm not aware of any streaming solution for attachments in PouchDB/CouchDB currently.

**Comment by nolanlawson** [comment]
The only way we could fix this ATM would be to modify CouchDB's replication protocol to allow streaming or chunking of attachments.

**Comment by nolanlawson** [comment]
A simple test case to reproduce would be helpful since this may be React Native or asyncstoragedown specific.

**Comment by der-ede** [comment]
So is this where the boundaries are right now, attachments with >1mb or so?
Like can you give some specifications since the reference manual states ambiguously that attachments should not be used at all but also that they've gotten better since then...

Regards
