### ISSUE TITLE
continuous change feed

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#5781]
I would like to request support for `feed=continuous` (http://docs.couchdb.org/en/2.0.0/api/database/changes.html#continuous). Which seems to be more efficient than the regular option.

I've noticed that there is an undocumented `opts.continuous` option. However, for some reason it uses `feed=longpolling`? https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-http/src/index.js#L786

**Comment by daleharvey** [comment]
`opts.continuous` is a mirror of `opts.live`, `opts.live` being easier to spell. If you want to take a look at what it means switching to `continuous` over `longpoll` under the hood then it could possibly be an improvement, however the extra request being made for longpoll while we are mostly idle hasnt been shown to be much of a performance issue up till now

**Comment by IamCarbonMan** [comment]
I'd like to request that this be reopened. [hoodie-server](https://github.com/hoodiehq/hoodie-server/issues/534#issuecomment-275507942) apparently uses this parameter in replication, which has improved performance over `feed=longpoll`.
