### ISSUE TITLE
bulkDocs with json files around 100mb gives ever ECONNRESET

### ISSUE THREAD

**Issue by mnewmedia** [pouchdb/pouchdb#5786]
### Issue
BulkDocs with json files around 100mb gives every single time `ECONNRESET`. I have the feeling that this is windows or couchdb 2 related. If anybody has tipps what I could try, I will try it. I will testit later with couchdb 1 and report again.

### Error
```js
 PouchDB: error updating status Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)
```
### Info
- PouchDB Version: 6.0.7
- Environment: (Node.js 5.5.0 - 6.90)
- Platform: (Windows 10)
- Adapter: (http)
- Server: (CouchDB 2.0 on Windows)

### Reproduce
- Make a dummy JSON file with some dummy docs, till it is arround 100mb.
- readJSON
- db.bulkDocs(docs);
- you have the error, every single time you do that.

**Comment by willholley** [comment]
@mnewmedia this sounds like a timeout or CouchDB error. Are there any related errors in the CouchDB log? 

As an aside, 100MB is very large for a single request (I thought CouchDB actually restricted this to 64MB by default), so you may want to consider smaller batches anyway.

**Comment by mnewmedia** [comment]
@willholley nothing in the logs.
86MB worked, 97MB failed.

Since it also fails with curl:
```
{"error":"too_large","reason":"the request entity is too large"}
```
it's not a pouchdb issue, so closing it. If I ever find out more I will report.
