### ISSUE TITLE
X-Couch-Full-Commit: false

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#5787]
CouchDB supports the `X-Couch-Full-Commit` for bulkDocs. Feature request?

**Comment by daleharvey** [comment]
PouchDB supports setting custom headers in its ajax requests, 

```js
var db = new PouchDB('http://.....', {
  ajax: { 
    headers: { 'X-Couch-Full-Commit': true }
  }
});
```

**Comment by daleharvey** [comment]
https://github.com/pouchdb/pouchdb/pull/5763 is also worth following for support for this type of ajax customisation
