### ISSUE TITLE
PouchDB as an offline LRU cache?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#5790]
I would like to use PouchDB as an offline document (no attachments) cache for our clients. However, since the entire remote database won't fit onto the client. We would like to have some form of scheme where:

- Clients write (`put`, `allDocs`) to LevelDB.
- Client read (`get`, `bulkDocs`) from LevelDB. If not found fallback to CouchDB. Cache the retrieved value in LevelDB.
- LevelDB replicates to the CouchDB.
- Remove least recently used items from LevelDB when size exceeds a limit.

Is this possible somehow? Can it be done seamlessly, i.e. code that currently uses the http adapter would work as is?

**Comment by daleharvey** [comment]
So 90% of that can be done with a custom wrapper around pouchdb, however the main issue would be the lack of purge, right now without that you cant reduce the size of the database without copying it over to a new database

**Comment by daleharvey** [comment]
https://github.com/pouchdb/pouchdb/issues/802 is the issue in question

**Comment by nolanlawson** [comment]
Have you seen https://github.com/squarespace/pouchdb-lru-cache ?

**Comment by ronag** [comment]
@nolanlawson: Yes, but it's unfortunately only for attachements. Not documents.

**Comment by ronag** [comment]
@nolanlawson: Does it work with documents and replication?

**Comment by nolanlawson** [comment]
No, sorry

**Comment by daleharvey** [comment]
So this can be done with a wrapper that switches out the databases in the absence of purge, and we have a bug tracking purge (https://github.com/pouchdb/pouchdb/issues/802 so closing this
