### ISSUE TITLE
EventEmitter leak with removeAllListeners()

### ISSUE THREAD

**Issue by jareware** [pouchdb/pouchdb#5791]
### Issue
The docs (https://pouchdb.com/api.html#changes) state `changes()` returns an EventEmitter (http://nodejs.org/api/events.html#events_class_events_eventemitter), but using `removeAllListeners()` during a cancel seems to leak EventEmitters

### Info
- Environment: browser
- Platform: tested on Chrome & FF
- Adapter: n/a
- Server: n/a

### Reproduce

```js
import PouchDB from 'pouchdb';
const db = new PouchDB('event_emitter_leak_test');
let changes;

function test() {
  if (changes) {
    changes.removeAllListeners(); // <- this seems to be the issue
    changes.cancel();
  }
  changes = db.changes({ live: true })
}

setInterval(test, 100);
```

This quickly gives the familiar error:

    (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

...but commenting out the `removeAllListeners()` call runs without errors ad infinitum.

Why would anyone use `removeAllListeners()` manually here? Good question. I did it because I didn't see the docs or the source (on a cursory glance) saying that `cancel()` also cleans up all listeners, so I thought what harm could it do to be extra sure. :)

I tried to look at the related code but couldn't immediately tell why this works the way it does.

I could at least put up a tiny PR for the docs about this?

**Comment by nolanlawson** [comment]
I agree, this seems like a docs issue. We manage listeners ourselves; no need to call `removeAllListeners()`.

**Comment by jareware** [comment]
Added a tiny docs PR for this!

Still not sure why an *additional* call to freeing up resources actually causes those resources to be retained, but probably doesn't matter.

**Comment by daleharvey** [comment]
Fixed in docs
