### ISSUE TITLE
_bulkDocs always includes _conflicts=[] --> error from couchbase sync gateway

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [pouchdb/pouchdb#5793]
### Issue

When inserting new documents into a database and then synchronizing it with couchbase sync gateway, this error occurs:

> 2016-10-22T21:41:19.973+02:00     BulkDocs: Doc "okifiergzuedih9i19k9" --> 400 user defined top level properties beginning with '_' are not allowed in document body (400 user defined top level properties beginning with '_' are not allowed in document body)

The reason for this is that the inserted documents have a property _conflicts=[] set, which couchbase sync gateway does not allow. For testing I removed these properties using a wrapper for XMLHttpRequest and then it worked.

I suppose this was introduced with a new version of PouchDB, but I'm not able to test it right now because I can't get older versions of PouchDB to work with rollup.
### Info
- PouchDB 6.0.7
- Environment: ionic app in the browser
- Platform: Chrome
- Server: Couchbase sync gateway 1.3

**Comment by willholley** [comment]
this is likely related to https://github.com/pouchdb/pouchdb/commit/8f0d7d2248ed46bffb9350ce50a033113241ae8f. I'll need to investigate further but it's curious that CSG throws errors that CouchDB doesn't. It suggests a compatibility issue in CSG.

**Comment by nolanlawson** [comment]
Please see https://github.com/pouchdb/pouchdb/issues/5795#issuecomment-256090033 ; CSG support is very buggy and I wouldn't really recommend it. PouchDB's test suite only has 100% support for CouchDB 1.x, CouchDB 2.x, and PouchDB Server. Anecdotally Cloudant also seems to work well because it's largely identical to CouchDB 2.x.

**Comment by daleharvey** [comment]
Will leave this open since there is a fix in progress

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/ef1db281fdea6524aa85f1cefa1550efa8d9e3c3

**Comment by snej** [comment]
Hi, Couchbase developer here (though I work on Couchbase Lite, not Sync Gateway)

>the inserted documents have a property `_conflicts=[]` set, which couchbase sync gateway does not allow.

I'm not aware of this property; I don't think it's one of the allowed "magic" meta-properties in the versions of CouchDB that we based our API support on. Where is this property documented?

**Comment by nolanlawson** [comment]
@snej If you fetch a doc with `?conflicts=true` you'll get the `_conflicts` object: http://docs.couchdb.org/en/2.0.0/api/document/common.html?highlight=conflicts

**Comment by willholley** [comment]
I think the seemingly undocumented behaviour is that CouchDB allows all [special fields](https://wiki.apache.org/couchdb/HTTP_Document_API)
to exist in document bodies at write time - it just ignores any fields that are meaningless in that context.

**Comment by snej** [comment]
Ah, I did not know that.
But why would the replicator try to push a document with a `_conflicts` property? That property only makes sense when _received_.

**Comment by willholley** [comment]
@snej that was due to a bug in PouchDB, fixed whilst addressing this issue.

**Comment by willholley** [comment]
@snej for more context, PouchDB uses `_all_docs` as an optimisation to fetch documents with only one revision (I think CBL has a similar optimisation?). However, documents could have conflicts at the root - i.e. multiple `1-` revisions, which we weren't replicating. Using `_bulk_get` instead removes the need for this optimisation/fixes the problem, but until that's widely deployed, we pass `conflicts=true` to `_all_docs` and, if a document has conflicts, fall back to individual document fetches. Unfortunately, we weren't stripping out the `_conflicts` field from the `_all_docs` results so it leaked into the corresponding `_bulk_docs` call.

**Comment by snej** [comment]
@willholley Yes, Couchbase Lite has the same optimization for use with CouchDB. Sync Gateway supports `_bulk_get`, so you can use it there, as Couchbase Lite does.
