### ISSUE TITLE
Problems with couchbase sync gateway's document expiry

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [pouchdb/pouchdb#5795]
### Issue
When an empty pouchdb synchronizes with a csg bucket that has expired documents in it, pouchdb tries to push these documents back to the server after recieving them.

Here is how I understand the problem:
New versions of couchbase sync gateway implement document expiry that is triggered if the property _exp is set. This expiry is purely local, i.e. it is not replicated: docs in a connected pouchdb are not deleted, but calling GET db/doc_id after expiry returns "missing"; so does _rev_diff when specifying the latest revision. However, fetching db/doc?open_revs=rev123 returns the document, even after expiry (the same goes for _bulk_get).

When synchronizing an empty pouchdb with a csg bucket that has expired documents in it, pouchdb specifies open_revs and thus recieves the expired documents. Afterwards it calls _rev_diff which returns "missing", thus pouchdb is uploading the documents again.

I don't know much about pouchdb's internals, but I think this could be fixed by calling /db/doc_id and /db/_bulk_get using the [show_exp](http://developer.couchbase.com/documentation/mobile/current/develop/references/sync-gateway/rest-api/index.html#operation---db---doc--get) parameter: When this parameter is set, "missing" is returned instead of the expired documents.

### Info
- Environment: Ionic app
- Platform: Android
- Server: CSG 1.3
- PouchDB 6.0.7

**Comment by willholley** [comment]
This sounds like a CSG problem if it doesn't adhere to the CouchDB replication protocol. PouchDB doesn't explicitly support CSG (at least, I don't know of any active contributors develop/test against it), so perhaps these kind of incompatibilities are best addressed with a plugin.

**Comment by nolanlawson** [comment]
There has been very little effort in the past few years to maintain CSG support. I'm starting to wonder if we should just not even mention it on the website anymore.

**Comment by hermitdemschoenenleben** [comment]
yes, you are right, it's better to address this problem with a plugin. I'll look into that.

**Comment by daleharvey** [comment]
Closing in favour of https://github.com/pouchdb/pouchdb/issues/5820
