### ISSUE TITLE
slack.pouchdb.com is unavailable!

### ISSUE THREAD

**Issue by crzidea** [pouchdb/pouchdb#5797]
[slack.pouchdb.com](http://slack.pouchdb.com) is unavailable at the time. Is it still alive?

**Comment by nolanlawson** [comment]
Yeah it just goes down from time to time. It's up again now.

**Comment by nolanlawson** [comment]
@daleharvey I had to manually restart it. Maybe we should just set up a cron job or something?

**Comment by martinhbramwell** [comment]
Right now it is showing the default nginx page.

**Comment by fwiwDev** [comment]
It is showing the default nginx page again...

**Comment by Terreii** [comment]
If I remember it correctly, then the Chat was moved to [CouchDBs Slack](https://couchdb.apache.org/#chat).
