### ISSUE TITLE
PouchDB source is not UTF-8 encoded when minified

### ISSUE THREAD

**Issue by slhck** [pouchdb/pouchdb#5798]
### Issue

Chrome does not load PouchDB's minified file because it is not UTF-8 encoded.

When I try to use PouchDB's `.min.js` version in my extension, I get:

```
Could not load file 'src/js/pouchdb-6.0.7.min.js' for content script. It isn't UTF-8 encoded.
```
### Info
- Environment: Chrome Extension
- Platform: Chrome Version 54.0.2840.71 (64-bit) on OS X 10.10
### Reproduce
- Download `pouchdb-6.0.7.min.js`
- Try to load it in Google Chrome extension `manifest.json` file under `content_scripts`

The non-minified version works without problems.

**Comment by nolanlawson** [comment]
The reason this is happening is because Uglify converts e.g. `"\u0000"` to a literal `\0` (null terminator) character. I have often tried to find a way to disable this behavior or undo it but wasn't able to.

**Comment by slhck** [comment]
I see, thanks.

Do you think it makes sense to file a feature request for Uglify, or a bug report for Chrom(e|ium)?

**Comment by nolanlawson** [comment]
I could reasonably see it as either one. Alternatively we could write our own UTF8 encoder on top of our Uglify process but it's a lot of work just to support Chrome extensions.

**Comment by slhck** [comment]
Hm. Perhaps a naïve suggestion, but I suppose a simple `s/\0/\u0000/g` doesn't do it?

**Comment by daleharvey** [comment]
I would give it a try :) A bug upstream to either chrome or uglify sounds like a good idea though, this has come up more than once

**Comment by nolanlawson** [comment]
There's both 0, 1, and 2 characters in teh source.

**Comment by nolanlawson** [comment]
Closing because this is really an Uglify bug rather than a PouchDB bug, and I don't think we need to go to the effort of fixing it since users can fix it themselves e.g. by using their own minifier on `pouchdb.js`.

**Comment by katlimruiz** [comment]
fyi, this is still happening when I tried to insert a pouchdb-8.0.1.min.js into a chrome extension.

Using VSCODE, I saved it with encoding Western ISO 8859-1, and it worked.

**Comment by garethbowen** [comment]
I don't think this is a bug in uglify but an option that can be overridden. It looks like in the [doMinify function](https://github.com/pouchdb/pouchdb/blob/4c92c946b1de8600ac338ff78c2c2bf4ef7910b7/bin/build-utils.js#L31) the `terser.minify` function takes a second argument which can include `{ format: { ascii_only: true } }`. This _should_ fix the utf8 issue but I have no idea what unintended consequences it may also cause. More information here: https://github.com/mishoo/UglifyJS/issues/2368

@katlimruiz Are you able to look into this further and possibly provide a PR?

**Comment by katlimruiz** [comment]
It seems promising.

I compared the output of packages/node_modules/pouchdb/dist/pouchdb.min.js before and after, and it generated the characters in Unicode format.

Example
<img width="1114" alt="image" src="https://github.com/pouchdb/pouchdb/assets/1009107/9ed7f420-af60-4fdd-81d6-dcf72bd342ae">

I'll create a PR

**Comment by garethbowen** [comment]
Merged.
