### ISSUE TITLE
Pass already serialised objects?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#5803]
Is it possible (as an optimisation) to pass already searilzed docs to PouchDB? Currently I'm kind of doing `db.put(JSON.parse(str))` which is a bit silly since Pouch will have to stringify it...

**Comment by danielsun174** [comment]
I think pouchdb has to unserialize the objects anyway because it still needs the _id and the _rev value.

**Comment by nolanlawson** [comment]
PouchDB doesn't always stringify objects. When we pass it to IndexedDB, we do pass in true JS objects. However we do clone the objects to avoid various issues with Dates, recursion, etc.

This is not a planned feature and is not known to have a significant performance impact anyway AFAIK.
