### ISSUE TITLE
Object {status: 0, name: "unknown", message: "batch processing terminated with error", result: Object}

### ISSUE THREAD

**Issue by webnoob** [pouchdb/pouchdb#5810]
### Issue

I'm getting the error in the title when clearing my local storage and then triggering a replication with the remote server.
### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB
### Reproduce
1. Use chromes clear storage option
2. Trigger a replication with a database that exists remotely.

Full object error:

`Object
message
:
"batch processing terminated with error"
name
:
"unknown"
result
:
Object
doc_write_failures
:
0
docs_read
:
0
docs_written
:
0
end_time
:
Wed Oct 26 2016 18:50:13 GMT+0100 (GMT Daylight Time)
errors
:
Array[0]
last_seq
:
0
ok
:
false
start_time
:
Wed Oct 26 2016 18:50:12 GMT+0100 (GMT Daylight Time)
status
:
"aborting"
__proto__
:
Object
status
:
0
__proto__
:
Object
`

**Comment by mnewmedia** [comment]
I also often clear storage using chrome, reload the site and start again a sync. And I never had this issue. Maybe you should provide some more information about what exactly you are doing, so we can reproduce the issue.

**Comment by webnoob** [comment]
Ok, glad to hear it's just me. I've created a paste bin with my db api and the code I'm using to trigger the error: http://pastebin.com/Z2qkKPW4

You'll notice the console logs and then this is the error I get:

> REPLICATING!!!
> POST http://dev.myserviceplanner.com:5984/userdb-61/_bulk_get?revs=true 400 (Bad Request)
> GET http://dev.myserviceplanner.com:5984/userdb-61/_local/j0FXHfifg2B1n6PzMVO0xA%3D%3D? 404 (Object Not Found)
> POST http://dev.myserviceplanner.com:5984/userdb-61/_bulk_get?revs=true net::ERR_CONNECTION_RESET
> REPLICATION ERROR:::
> Object {status: 0, name: "unknown", message: "batch processing terminated with error", result: Object}
>

**Comment by webnoob** [comment]
Hmm, looking at the CouchDB website and focusing on the Bad Request error, I'm wondering if there is some bad data that it doesn't like coming back.

The bulk API says Bad Request are invalid data: http://docs.couchdb.org/en/2.0.0/api/database/bulk-api.html

**Comment by webnoob** [comment]
Ah, could it be linked to this: https://github.com/pouchdb/pouchdb/issues/5501

**Comment by webnoob** [comment]
Ok, I've enabled debug logs in couchDb and have some more information on this now. I'm getting this:

> [Wed, 26 Oct 2016 22:54:02 GMT] [debug] [<0.342.0>] 'POST' /userdb-3132/_bulk_get?revs=true {1,1} from "86.0.17.188"
> Headers: [{'Accept',"application/json"},
>           {'Accept-Encoding',"gzip, deflate"},
>           {'Accept-Language',"en-US,en;q=0.8"},
>           {'Connection',"keep-alive"},
>           {'Content-Length',"1578"},
>           {'Content-Type',"application/json"},
>           {'Cookie',"ASP.NET_SessionId=t4vyfeepqryqu5jau3p0vxas; __RequestVerificationToken=_ZeiAeeXE0LpWDaUFcEH7s--nDhRnZVx9YXeNGSbAVoaB-gbSRVm528lqrKo6oYXYx_5aII6YrOStqGXDZjJVvVajTUB7XTtUnd6rU8BWi81; _ga=GA1.2.415264765.1475684703; AuthSession=MTI6NTgxMTM0MDc6SmWyQczFrzzGBn7yzDt5w0xhQFA"},
>           {'Host',"dev.myserviceplanner.com:5984"},
>           {"Origin","http://localhost:8080"},
>           {'Referer',"http://localhost:8080/"},
>           {'User-Agent',"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"}]
> [Wed, 26 Oct 2016 22:54:02 GMT] [debug] [<0.342.0>] OAuth Params: [{"revs","true"}]
> [Wed, 26 Oct 2016 22:54:02 GMT] [debug] [<0.342.0>] timeout 600
> [Wed, 26 Oct 2016 22:54:02 GMT] [debug] [<0.342.0>] Successful cookie auth as: "12"
> [Wed, 26 Oct 2016 22:54:02 GMT] [debug] [<0.342.0>] Minor error in HTTP request: {bad_request,
>                                                   <<"Referer header must match host.">>}
> [Wed, 26 Oct 2016 22:54:02 GMT] [debug] [<0.342.0>] Stacktrace: [{couch_httpd,validate_referer,1,
>                                      [{file,"couch_httpd.erl"},{line,423}]},
>                                  {couch_httpd_db,db_doc_req,3,
>                                      [{file,"couch_httpd_db.erl"},{line,532}]},
>                                  {couch_httpd_db,do_db_req,2,
>                                      [{file,"couch_httpd_db.erl"},{line,234}]},
>                                  {couch_httpd,handle_request_int,5,
>                                      [{file,"couch_httpd.erl"},{line,318}]},
>                                  {mochiweb_http,headers,5,
>                                      [{file,"mochiweb_http.erl"},{line,94}]},
>                                  {proc_lib,init_p_do_apply,3,
>                                      [{file,"proc_lib.erl"},{line,240}]}]
> [Wed, 26 Oct 2016 22:54:02 GMT] [info] [<0.342.0>] 86.0.17.188 - - POST /userdb-3132/_bulk_get?revs=true 400
> [Wed, 26 Oct 2016 22:54:02 GMT] [debug] [<0.342.0>] httpd 400 error response:
>  {"error":"bad_request","reason":"Referer header must match host."}
>

**Comment by webnoob** [comment]
Ok, think I've sorted it. The Referer header error got me thinking about CORS so I was looking into how I'd set it up (which I'd done manually) and I didn't have the headers set. I've used the script here: https://github.com/pouchdb/add-cors-to-couchdb and ensured all CORS options are present and it appears to be working properly now 👍

**Comment by willholley** [comment]
`{"error":"bad_request","reason":"Referer header must match host."}` suggests a CORS issue. Can you confirm that you've configured CORS and other CouchDB requests are working?

> I can refresh a few times sometimes and it will work and replicate the data properly.

would indicate that CORS isn't the problem, but it certainly seems like it. Which version of CouchDB are you using?

**Comment by webnoob** [comment]
I also thought CORS so I checked all the settings and ran the CORS setup package @nolanlawson created and I did indeed get a couple of clears / replications working but then it stopped (so just assume it was a lucky couple of tries). This is my CORS setup:

![image](https://cloud.githubusercontent.com/assets/10404747/19756639/05d7821a-9c16-11e6-9a1b-51f1d13b0037.png)

I'm using couch: 1.6.1 and pouch: 6.0.7

**Comment by bfredo123** [comment]
Thx webnood for linking this to 5501. I have the exact same settings for cors. Using 1.6.1 and 6.0.7 just like you.

If anyone has any idea, that would be great!

**Comment by bfredo123** [comment]
Digging in my own logs in debug mode, I think I have found the fix: when declaring the remoteDb to sync with, I removed the "http://" prefix. So:

remoteDB = new PouchDB("192.1.2.3:5984/mydb");

instead of:

remoteDB = new PouchDB("http://192.1.2.3:5984/mydb");

I no longer have the minor error "Referer header must match host."

Hope this helps

**Comment by bfredo123** [comment]
Too bad, my last post was a wrong good news: removing "http://" just does not hit the server, and I thought it was working because I could see the data from my local db.

So I still having the same issue, with the following in the couchdb.log:

[Fri, 28 Oct 2016 16:51:34 GMT] [debug] [<0.128.0>] 'POST' /mydb/_bulk_get?revs=true {1,1} from "192.168.0.4"
Headers: [{'Accept',"application/json"},
          {'Accept-Encoding',"gzip, deflate"},
          {'Accept-Language',"fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4"},
          {'Connection',"keep-alive"},
          {'Content-Length',"247"},
          {'Content-Type',"application/json"},
          {'Cookie',"_ga=GA1.1.348589215.1476629340"},
          **{'Host',"192.168.0.4:5984"},**
          {"Origin","http://192.168.0.4:8100"},
          **{'Referer',"http://192.168.0.4:8100/"},**
          {'User-Agent',"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"}]
[Fri, 28 Oct 2016 16:51:34 GMT] [debug] [<0.128.0>] OAuth Params: [{"revs","true"}]
[Fri, 28 Oct 2016 16:51:34 GMT] [debug] [<0.128.0>] Minor error in HTTP request: {bad_request,
                                                  <<"Referer header must match host.">>}
[Fri, 28 Oct 2016 16:51:34 GMT] [debug] [<0.128.0>] Stacktrace: [{couch_httpd,validate_referer,1,
                                  [{file,
                                    "c:/cygwin/relax/APACHE~2.1/src/couchdb/couch_httpd.erl"},
                                   {line,423}]},
                                 {couch_httpd_db,db_doc_req,3,
                                  [{file,
                                    "c:/cygwin/relax/APACHE~2.1/src/couchdb/couch_httpd_db.erl"},
                                   {line,532}]},
                                 {couch_httpd_db,do_db_req,2,
                                  [{file,
                                    "c:/cygwin/relax/APACHE~2.1/src/couchdb/couch_httpd_db.erl"},
                                   {line,234}]},
                                 {couch_httpd,handle_request_int,5,
                                  [{file,
                                    "c:/cygwin/relax/APACHE~2.1/src/couchdb/couch_httpd.erl"},
                                   {line,318}]},
                                 {mochiweb_http,headers,5,
                                  [{file,
                                    "c:/cygwin/relax/APACHE~2.1/src/mochiweb/mochiweb_http.erl"},
                                   {line,94}]},
                                 {proc_lib,init_p_do_apply,3,
                                  [{file,"proc_lib.erl"},{line,239}]}]
[Fri, 28 Oct 2016 16:51:34 GMT] [info] [<0.128.0>] 192.168.0.4 - - POST /mydb/_bulk_get?revs=true 400
[Fri, 28 Oct 2016 16:51:34 GMT] [debug] [<0.128.0>] httpd 400 error response:
 {"error":"bad_request","reason":"Referer header must match host."}

**Comment by ermouth** [comment]
@bfredo Seems you load the page from 8100 port, and your page tries to send POST to 5984 port.  You can‘t do it, CouchDB forbids this kind of requests regardless of your CORS settings. 

https://github.com/apache/couchdb-couch/blob/master/src/couch_httpd_db.erl#L546
https://github.com/apache/couchdb-couch/blob/master/src/couch_httpd.erl#L424

You can a) make both page and DB live on the same port, b) use for example nginx reverse proxy in front of CouchDB to modify Referer header (I hope something like `proxy_set_header Referer $host;` can help).

**Comment by webnoob** [comment]
@ermouth I've just tried making sure my local host and remote server and using the same port and this doesn't seem to have helped. I don't have time to get the logs right now but do you have any other thoughts?

**Comment by bfredo123** [comment]
@ermouth: many thanks for helping, however I am running everything on the same machine:
- Couchdb (port 5984)
- Ionic framework (port 8100)
- web browser

@all: I have upgraded to CouchDB 2.0.0 and sync seems to work like a charm now. I have seen in the release notes of 2.0.0 a few things about bulk_get.

**Comment by webnoob** [comment]
@bfredo123 I'll give that a go, sounds like good news!

**Comment by bfredo123** [comment]
Glad to hopefully help!

btw I am a CouchDB newbye, and the only way I found to transfer my data from 1.6.1 to 2.0.0 was to do a replication. But the views and design docs did not replicate, so I had to copy and paste the by hand one by one. I you have a better approach I am interested!

**Comment by ermouth** [comment]
@webnoob What I see in your logs: `{'Host',"mysite.com:5984"}, {'Referer',"http://localhost:5984/"}`

Your `Host` and `Referer` headers are actually different, despite you think they are same.

**Comment by webnoob** [comment]
Yes I know but CORS  is on so it shouldn't matter.

**Comment by derBinder** [comment]
Is there a way to fix this without upgrading to CouchDB 2.0?

**Comment by nolanlawson** [comment]
Can anyone provide a test case to reproduce? I'm struggling to understand what the issue even is here. There's been a lot of discussion but it's not clear to me why the CouchDB 2 upgrade fixed things, or if this is even CORS-related.

@derBinder It's possible your issue is something entirely different since error code 0 is a generic CORS issue; you may need to use https://github.com/pouchdb/add-cors-to-couchdb

**Comment by webnoob** [comment]
@nolanlawson I'll try and put something together. I seemed to get this issue when I had data on my server then deleted the application data from chrome. It would then struggle to get all the data back. I'll see if it's still happening over the next couple of days.

**Comment by derBinder** [comment]
@nolanlawson 
CORS is setup correctly. 
I am getting the "Object {status: 0, name: "unknown", message: "batch processing terminated with error", result: Object} " error  when i am doing a replication **from** CouchDB 1.6.1 **to** a local PouchDB.

The error seems to happen while checking if the _bulk_get API is supported.

`HTTP400: ERROR: The request could not be understood by the server due to malformed syntax.
(XHR): POST - http://172.16.25.64:5984/test/_bulk_get?revs=true`

### Info
- Environment: browser / UWP
- Platform: Edge
- Adapter: IndexedDB/
- Server: CouchDB 1.6.1

**Comment by willholley** [comment]
@derBinder it's expected that the test for `_bulk_get` returns a 4XX error on platforms that don't support it - Pouch should then fall back to standard GET /db/doc?revs=true&open_revs=['foo'] requests. Can you try enabling [PouchDB debug mode](https://pouchdb.com/api.html#debug_mode) to see where it actually fails?

**Comment by derBinder** [comment]
It fails at the last call, which is `POST - http://localhost:5984/test/_bulk_get?revs=true`. After this error, the replication stops and won't finish.

```
%cpouchdb:adapter %cPicked adapter: idb%c +2s color: goldenrod color: inherit color: goldenrod
pouchdb-6.0.7.js (139,17)
%cpouchdb:adapter %cPicked adapter: http%c +1ms color: dodgerblue color: inherit color: dodgerblue
pouchdb-6.0.7.js (139,17)
%cpouchdb:adapter %cPicked adapter: idb%c +1ms color: darkorchid color: inherit color: darkorchid
pouchdb-6.0.7.js (139,17)
%cpouchdb:api %chttp://admin:admin@localhost:5984/test%c +1ms color: forestgreen color: inherit color: forestgreen id
pouchdb-6.0.7.js (139,17)
%cpouchdb:api %ctestPouch%c +0ms color: forestgreen color: inherit color: forestgreen id
pouchdb-6.0.7.js (139,17)
%cpouchdb:api %chttp://admin:admin@localhost:5984/test%c +1ms color: forestgreen color: inherit color: forestgreen id
pouchdb-6.0.7.js (139,17)
%cpouchdb:http %cGET http://localhost:5984/test/%c +1ms color: crimson color: inherit color: crimson
pouchdb-6.0.7.js (139,17)
%cpouchdb:http %cGET http://localhost:5984/%c +16ms color: crimson color: inherit color: crimson
pouchdb-6.0.7.js (139,17)
%cpouchdb:api %ctestPouch%c +2ms color: forestgreen color: inherit color: forestgreen id
pouchdb-6.0.7.js (139,17)
%cpouchdb:api %chttp://admin:admin@localhost:5984/test%c +3ms color: forestgreen color: inherit color: forestgreen id success 175768705db91b8362388f990945d7cctest
pouchdb-6.0.7.js (139,17)
%cpouchdb:api %ctestPouch%c +2ms color: forestgreen color: inherit color: forestgreen id success 57F3978F-BE43-B38D-8436-4E891D137C63
pouchdb-6.0.7.js (139,17)
%cpouchdb:api %chttp://admin:admin@localhost:5984/test%c +0ms color: forestgreen color: inherit color: forestgreen id success 175768705db91b8362388f990945d7cctest
pouchdb-6.0.7.js (139,17)
%cpouchdb:api %ctestPouch%c +8ms color: forestgreen color: inherit color: forestgreen id success 57F3978F-BE43-B38D-8436-4E891D137C63
pouchdb-6.0.7.js (139,17)
%cpouchdb:api %ctestPouch%c +28ms color: forestgreen color: inherit color: forestgreen get _local/gR_nWwn5SuQJLbfa9ZUj.A==
pouchdb-6.0.7.js (139,17)
%cpouchdb:api %ctestPouch%c +1ms color: forestgreen color: inherit color: forestgreen get error {"status":404,"name":"not_found","message":"missing"}
pouchdb-6.0.7.js (139,17)
   "%cpouchdb:api %ctestPouch%c +1ms"
   "color: forestgreen"
   "color: inherit"
   "color: forestgreen"
   "get"
   "error"
   {
      [functions]: ,
      __proto__: { },
      error: true,
      message: "missing",
      name: "not_found",
      status: 404
   }

%cpouchdb:http %cGET http://localhost:5984/test/_changes?timeout=25000&style=all_docs&heartbeat=10000&since=0&limit=100%c +15ms color: crimson color: inherit color: crimson
pouchdb-6.0.7.js (139,17)
%cpouchdb:api %ctestPouch%c +10ms color: forestgreen color: inherit color: forestgreen revsDiff [object Object]
pouchdb-6.0.7.js (139,17)
   "%cpouchdb:api %ctestPouch%c +10ms"
   "color: forestgreen"
   "color: inherit"
   "color: forestgreen"
   "revsDiff"
   {
      [functions]: ,
      __proto__: { },
      bf7f8a3d338c5ec059ce394afa00308e: [ ],
      bf7f8a3d338c5ec059ce394afa000736: [ ],
      bf7f8a3d338c5ec059ce394afa002177: [ ],
      bf7f8a3d338c5ec059ce394afa004083: [ ]
   }

%cpouchdb:api %ctestPouch%c +3ms color: forestgreen color: inherit color: forestgreen revsDiff success [object Object]
pouchdb-6.0.7.js (139,17)
   "%cpouchdb:api %ctestPouch%c +3ms"
   "color: forestgreen"
   "color: inherit"
   "color: forestgreen"
   "revsDiff"
   "success"
   {
      [functions]: ,
      __proto__: { },
      bf7f8a3d338c5ec059ce394afa00308e: { },
      bf7f8a3d338c5ec059ce394afa000736: { },
      bf7f8a3d338c5ec059ce394afa002177: { },
      bf7f8a3d338c5ec059ce394afa004083: { }
   }

%cpouchdb:http %cGET http://localhost:5984/test/_changes?timeout=25000&style=all_docs&heartbeat=10000&since=6&limit=100%c +2ms color: crimson color: inherit color: crimson
pouchdb-6.0.7.js (139,17)
%cpouchdb:api %chttp://admin:admin@localhost:5984/test%c +6ms color: forestgreen color: inherit color: forestgreen allDocs [object Object]
pouchdb-6.0.7.js (139,17)
   "%cpouchdb:api %chttp://admin:admin@localhost:5984/test%c +6ms"
   "color: forestgreen"
   "color: inherit"
   "color: forestgreen"
   "allDocs"
   {
      [functions]: ,
      __proto__: { },
      conflicts: true,
      include_docs: true,
      keys: [ ]
   }

%cpouchdb:http %cPOST http://localhost:5984/test/_all_docs?conflicts=true&include_docs=true%c +7ms color: crimson color: inherit color: crimson
pouchdb-6.0.7.js (139,17)
%cpouchdb:api %chttp://admin:admin@localhost:5984/test%c +7ms color: forestgreen color: inherit color: forestgreen allDocs success [object Object]
pouchdb-6.0.7.js (139,17)
   "%cpouchdb:api %chttp://admin:admin@localhost:5984/test%c +7ms"
   "color: forestgreen"
   "color: inherit"
   "color: forestgreen"
   "allDocs"
   "success"
   {
      [functions]: ,
      __proto__: { },
      offset: 0,
      rows: [ ],
      total_rows: 4
   }

%cpouchdb:api %chttp://admin:admin@localhost:5984/test%c +12ms color: forestgreen color: inherit color: forestgreen bulkGet [object Object]
pouchdb-6.0.7.js (139,17)
   "%cpouchdb:api %chttp://admin:admin@localhost:5984/test%c +12ms"
   "color: forestgreen"
   "color: inherit"
   "color: forestgreen"
   "bulkGet"
   {
      [functions]: ,
      __proto__: { },
      docs: [ ],
      revs: true
   }

%cpouchdb:http %cPOST http://localhost:5984/test/_bulk_get?revs=true%c +2ms color: crimson color: inherit color: crimson
pouchdb-6.0.7.js (139,17)
HTTP400: FEHLERHAFTE ANFORDERUNG: Die Anforderung konnte vom Server aufgrund ungültiger Syntax nicht verarbeitet werden.
(XHR): POST - http://localhost:5984/test/_bulk_get?revs=true
SCRIPT7002: XMLHttpRequest: Netzwerkfehler 0x800c0007, Von der angegebenen Ressource sind keine Daten verfügbar.
index.html
%cpouchdb:api %chttp://admin:admin@localhost:5984/test%c +2ms color: forestgreen color: inherit color: forestgreen bulkGet error [object Object]
pouchdb-6.0.7.js (139,17)
   "%cpouchdb:api %chttp://admin:admin@localhost:5984/test%c +2ms"
   "color: forestgreen"
   "color: inherit"
   "color: forestgreen"
   "bulkGet"
   "error"
   {
      [functions]: ,
      __proto__: { },
      message: undefined,
      name: "unknown",
      status: 0
   }
```

**Comment by willholley** [comment]
@derBinder I'm confident that sync generally works against CouchDB 1.6 - we have good test coverage - so this must be something about your environment. Are you using any proxy between the browser and CouchDB? What does the Chrome network tab show as the error?  It definitely seems odd that there's a `net::ERR_CONNECTION_RESET` there.

**Comment by derBinder** [comment]
@willholley  There is no proxy between my browser and CouchDB.
It is a direct replication from my local CouchDB to the PouchDB.

This is my testcase:
```
   PouchDB.replicate('http://admin:admin@localhost:5984/test', 'testPouch').on('change', function (info) {
        // handle change
        //console.log('*** PoucbDB *** replicateFrom: source : ' + sourceDb + '  -->   target : ' + targetDb + ": CHANGE");
    }).on('paused', function (err) {
        // replication paused (e.g. replication up to date, user went offline)
        console.log('*** PoucbDB *** replicateFrom: source : ' + sourceDb + '  -->   target : ' + targetDb + ": PAUSED");
    }).on('active', function () {
        // replicate resumed (e.g. new changes replicating, user went back online)
        console.log('*** PoucbDB *** replicateFrom: source : ' + sourceDb + '  -->   target : ' + targetDb + ": ACTIVE");
    }).on('denied', function (err) {
        // a document failed to replicate (e.g. due to permissions)
        console.log('*** PoucbDB *** replicateFrom: source : ' + sourceDb + '  -->   target : ' + targetDb + ": DENIED");
    }).on('complete', function (info) {
        // handle complete
        console.log('*** PoucbDB *** replicateFrom: source : ' + sourceDb + '  -->   target : ' + targetDb + ": COMPLETE: Docs written: " + info.docs_written);
    }).on('error', function (err) {
        // handle error
        console.log('*** PoucbDB *** replicateFrom: source : ' + sourceDb + '  -->   target : ' + targetDb + ": ERROR");
    })
```
The Chrome network tab shows this:

![networktab](https://cloud.githubusercontent.com/assets/23222389/21310718/deb4b930-c5e3-11e6-850d-b2d4863639e0.PNG)

**Comment by willholley** [comment]
@derBinder As stated earlier, it's expected the `_bulk_get` request fails with a 4xx error against CouchDB 1.6. The messages in the logs look to be mixed up with logging from your application - can you try reproducing it in a stand-alone / minimal application? Also, does the same error occur in other browsers?

**Comment by derBinder** [comment]
@willholley It is already a standalone application. There are just the console.logs i added.
When i remove those lines, the code looks like this:

index.html
````
<!DOCTYPE html>
<html lang="de">
  <head>
    <script language="javascript" type="text/javascript" src="pouchdb-6.0.7.js"></script>
    <script language="javascript" type="text/javascript" src="index.js"></script>
  </head>
  <body>
      <button onclick="replicate();">Replicate</button>
  </body>
</html>
````

index.js
````
PouchDB.debug.enable('*');
var db = new PouchDB('testPouch');

window.onload = function() {
    db.destroy();
};

function replicate() {
    db = new PouchDB('testPouch');
    PouchDB.replicate('http://admin:admin@localhost:5984/test', db.name);
}
````

The existing Pouch gets destroyed on page load and a Couchdb Database gets replicated with a click on the button.

I can reproduce the error 7 of 10 times when i run the application in Microsoft Edge.
I tried the same application in Chrome, the error does happen in like 1 out of 50 tries.

**Comment by willholley** [comment]
@derBinder I can't reproduce this locally. Does it make any difference what the content of the database to sync is?

**Comment by willholley** [comment]
short of having a reproducible test case, the best I can suggest is to try and catch the error as it's thrown internally in PouchDB to see why the retry isn't happening. You should get an error at https://github.com/pouchdb/pouchdb/blob/6.0.7/dist/pouchdb.js#L10091 after which it should fall back to individual document GETs.

**Comment by derBinder** [comment]
The error is get there looks like this:

![bulk](https://cloud.githubusercontent.com/assets/23222389/21314544/f5e3b37c-c5f7-11e6-98e9-af2067a827d8.PNG)

You excpect a status 4xx or 5xx, but it's 0.

**Comment by willholley** [comment]
thanks @derBinder. Are you able to break on/identify the line which throws the error?

**Comment by derBinder** [comment]
@willholley 
https://github.com/pouchdb/pouchdb/blob/6.0.7/dist/pouchdb.js#L9600 
The xhr.status is 0 and timedout is **false**.

The xhr object looks like this:
![xhr](https://cloud.githubusercontent.com/assets/23222389/21315254/8db99da8-c5fb-11e6-9733-cfc4102a5ee5.PNG)

**Comment by daleharvey** [comment]
So if we receive a status an error status other than 4XX/5XX here we will error out of the call entirely @ https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-http/src/index.js#L346

Maybe worth changing that to just say we dont support bulk get if there is any error, thinking about it, if the server doesnt support bulk_get, its also likely to not set cors correctly on that route which would trigger a 0 status

**Comment by willholley** [comment]
@derBinder if you change https://github.com/pouchdb/pouchdb/blob/6.0.7/dist/pouchdb.js#L10094 to remove the 4xx/5xx check, does sync work? It would also be interesting to grab the `curl` command for one of the failing requests according to the Chrome dev tools to see if it can be reproduced standalone.

@daleharvey agree that we should probably just fall back in response to any error for simplicity. However, Travis covers older Couch versions so I think CORS behaves as expected against `_bulk_get`, at least in some Couch 1.6.1 environments. That the problem is intermittent is strange as well.

**Comment by derBinder** [comment]
@willholley Without the 4xx/5xx check the replication works.
 The log shows this message after the _bulk_get call 

> "The above 0 is totally normal. PouchDB is just detecting if the remote supports the _bulk_get API."

The `curl` command should be this:
```
curl --data "{id: 'bf7f8a3d338c5ec059ce394afa000736', rev: '2-1e943836ccfbbe5e24361111cbe13899'}" http://admin:admin@localhost:5984/test/_bulk_get?revs=true
```
The answer:
```
{"error":"bad_request","reason":"Referer header required."}
```

**Comment by willholley** [comment]
@derBinder if you right click on the failed request in Chrome dev tools, you can can to `Copy -> Copy as cURL` for the complete curl command.

**Comment by derBinder** [comment]
@willholley Ah, got it.

```curl "http://localhost:5984/test/_bulk_get?revs=true" -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Origin: http://localhost:81" -H "Accept-Encoding: gzip, deflate, br" -H "Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36" -H "Content-Type: application/json" -H "Accept: application/json" -H "Referer: http://localhost:81/" -H "Connection: keep-alive" --data-binary "^{^\^"docs^\^":^[^{^\^"id^\^":^\^"bf7f8a3d338c5ec059ce394afa000736^\^",^\^"rev^\^":^\^"2-1e943836ccfbbe5e24361111cbe13899^\^"^},^{^\^"id^\^":^\^"bf7f8a3d338c5ec059ce394afa00308e^\^",^\^"rev^\^":^\^"2-1e943836ccfbbe5e24361111cbe13899^\^"^}^]^}" --compressed```

**Comment by willholley** [comment]
@derBinder and does running that reproduce the error on the command line?

**Comment by derBinder** [comment]
I posted the response above.
`{"error":"bad_request","reason":"Referer header must match host."}`

That's a HTTP 400, maybe XHR changes the status to 0?

**Comment by willholley** [comment]
@derBinder that just indicates a malformed request. Can you post the output of the curl command generated by Chrome (which includes the referrer header)?

**Comment by derBinder** [comment]
Is it this?

Request headers:
```
POST /test/_bulk_get?revs=true HTTP/1.1
Host: localhost:5984
Connection: keep-alive
Content-Length: 180
Accept: application/json
Origin: http://localhost:81
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/json
Referer: http://localhost:81/
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
```

Response headers:
```
HTTP/1.1 400 Bad Request
Server: CouchDB/1.6.1 (Erlang OTP/R16B02)
Date: Mon, 19 Dec 2016 14:35:00 GMT
Content-Type: application/json
Content-Length: 67
Cache-Control: must-revalidate
Access-Control-Expose-Headers: Cache-Control, Content-Type, Server
Access-Control-Allow-Origin: http://localhost:81
Access-Control-Allow-Credentials: true
```

**Comment by willholley** [comment]
sorry - for some reason Chrome doesn't include a Host header in it's cURL output. Try:
```
curl "http://localhost:5984/test/_bulk_get?revs=true" -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Origin: http://localhost:81" -H "Accept-Encoding: gzip, deflate, br" -H "Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36" -H "Content-Type: application/json" -H "Accept: application/json" -H "Referer: http://localhost:81/" -H "Connection: keep-alive" --data-binary "^{^\^"docs^\^":^[^{^\^"id^\^":^\^"bf7f8a3d338c5ec059ce394afa000736^\^",^\^"rev^\^":^\^"2-1e943836ccfbbe5e24361111cbe13899^\^"^},^{^\^"id^\^":^\^"bf7f8a3d338c5ec059ce394afa00308e^\^",^\^"rev^\^":^\^"2-1e943836ccfbbe5e24361111cbe13899^\^"^}^]^}" --compressed -H "Host: localhost:81" -v
```

**Comment by derBinder** [comment]
```
{"error":"bad_request","reason":"Referer header must match host."}
<!DOCTYPE html>
<html lang="de">
  <head>
    <script language="javascript" type="text/javascript" src="pouchdb-6.0.7.js"></script>
    <script language="javascript" type="text/javascript" src="index.js"></script>
  </head>

  <body>
      <button onclick="replicate();">Replicate</button>
  </body>

</html>
```

**Comment by willholley** [comment]
@derBinder are you really getting HTML back in response to that curl command? If so, do you know why that might be?

**Comment by derBinder** [comment]
@willholley yep, i get the error and HTML back. I don't know why. Do you have an idea?

**Comment by willholley** [comment]
@derBinder what's serving the HTML? Can you make sure verbose mode is set for curl?

**Comment by derBinder** [comment]
@willholley The server is Apache 2.
The curl i copield is the same you posted above, it contains the -v.

**Comment by willholley** [comment]
@derBinder what happens if you stop apache2 during the test?

**Comment by derBinder** [comment]
@willholley I get this response

> {"error":"bad_request","reason":"Referer header must match host."}
curl: (7) Failed to connect to localhost port 81: Connection refused

**Comment by willholley** [comment]
hmm - I wonder if the curl command is malformed. I think this is going to be tricky to debug without a reproduction outside the browser, so perhaps we just make the change mentioned above and handle any error by falling back to fetching individual docs.
