### ISSUE TITLE
Creating a CouchDB returns too early

### ISSUE THREAD

**Issue by cboden** [pouchdb/pouchdb#5813]
### Issue

I believe .info() on a new database seems to return before CouchDB does.
### Info
- Environment: (Node.js)
- Adapter: (none)
- Server: (CouchDB)
- Version: 5.3.2 - 6.0.7
### Reproduce

This bug is intermittent and does not happen every time but I have been able to reproduce it myself a lot. My code looks like this:

``` javascript
const
  PouchDB = require('pouchdb'),
  baseUser = new PouchDB('http://localhost:5984/base-user', {skip_setup: true});

module.exports = (userId) => {
  const userDb = new PouchDB('http://localhost:5984/' + userId, {skip_setup: false});

  // (both methods fail)
  return PouchDB.replicate(baseUser, userDb);
  return userDb.info().then(() => PouchDB.replicate(baseUser, userDb));
};
```

When I call that function sometimes I get a 404 from the replicate call that `userDb` is missing, sometimes it works. This seems to happen with a concurrency >= 3. If I do a manual HTTP request to PUT the userDb and then use PouchDB to replicate it works 100% of the time.

**Comment by daleharvey** [comment]
What data is being returned? it doesnt seem particularly possible from the code, its straight returning data from couchdb, either couch gives us the data or it fails - https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-http/src/index.js#L370

**Comment by nolanlawson** [comment]
Closing, please reopen if you can find a failing test case and also please let us know which version of CouchDB we're talking about. Thanks!
