### ISSUE TITLE
PouchDB.defaults({prefix}) misses `/` separator unless port is set

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb#5814]
### Issue

Write the description of the issue here
### Info
- Environment: Node.js (tested on v6.9.1)
- Adapter: http
- Server: n/a
### Reproduce

This logs `Error: getaddrinfo ENOTFOUND example.comfoo example.comfoo:80`

``` js
const PouchDB = require('pouchdb').defaults({
  prefix: 'http://example.com'
})
const db = new PouchDB('foo')
db.info().catch(console.log)
```

If I replace `http://example.com` with `http://example.com:80` the error does not occur

**Comment by gr2m** [comment]
I did a quick research and I think the right fix will be to assure that `opts.prefix` ends with `/` before [this line](https://github.com/pouchdb/pouchdb/blob/9fc98515983bd25f6abca9a61768bb17a9440649/packages/node_modules/pouchdb-adapter-http/src/index.js#L91)

A test would go into [tests/integration/test.http.js](https://github.com/pouchdb/pouchdb/blob/9fc98515983bd25f6abca9a61768bb17a9440649/tests/integration/test.http.js#L201). The test would look similar to the one above, but with `testUtils.adapterUrl('http', '').replace(/\/$/,'')`

Happy to let someone new work on this and to give guidance

**Comment by gr2m** [comment]
Nolan said to better put it into https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.defaults.js

**Comment by gr2m** [comment]
This is still a problem, I think we just run into it again via https://github.com/hoodiehq/hoodie-server/issues/542

**Comment by gr2m** [comment]
congrats on pushing 7.0! I can’t help out right now I’m sorry, the bug was around for so long, I think we can fix it after

**Comment by daleharvey** [comment]
Gave it a quick fix :) https://github.com/pouchdb/pouchdb/commit/fa772c1d0690495aee83e15147359a5a72081abc
