### ISSUE TITLE
mismatch pouchdb

### ISSUE THREAD

**Issue by foozzi** [pouchdb/pouchdb#5815]
node version - v7.0.0
npm version - 3.10.9
OS - os x el capitan
error message:
`[Error: Module version mismatch. Expected 47, got 46. This generally implies that leveldown was built with a different version of node than that which is running now.  You may try fully removing and reinstalling PouchDB or leveldown to resolve.]`

**Comment by jrop** [comment]
Have you tried running `npm rebuild`?

**Comment by foozzi** [comment]
@jrop yes, i'm trying this.
i solved this problem after install and require - "require-rebuild":
and insert this line
`require('require-rebuild')();`
after:
```js
var BrowserWindow = require('browser-window');  // Module to create native browser window.
var ipcMain = require('electron').ipcMain;
var PouchDB = require('pouchdb');
db = new PouchDB('./data');
```
like this:
```js
require('require-rebuild')();
var BrowserWindow = require('browser-window');  // Module to create native browser window.
var ipcMain = require('electron').ipcMain;
var PouchDB = require('pouchdb');
db = new PouchDB('./data');
```
and 
`rm -rf node_modules && npm install`

**Comment by daleharvey** [comment]
Looks like your sorted, closing out

**Comment by jrop** [comment]
@foozzi Have you looked into [electron-rebuild](https://github.com/electron/electron-rebuild)?  I ran into this issue a while back using electron with native modules, and added `electron-rebuild` to my build process.
