### ISSUE TITLE
attachments structure/grouping question

### ISSUE THREAD

**Issue by marktheis** [pouchdb/pouchdb#5824]
Hi. I was wondering how flexible the _attachments object is.

Is it possible to group attachments or add custom key/values to attachments?
For example:
```
db.put({
  _id: 'mydoc',
  _attachments: {
    group1: {
      'myattachment.txt': {
        a_key: 'value',
        content_type: 'text/plain',
        data: 'aGVsbG8gd29ybGQ='
      },
      'myattachment2.txt': {
        a_key: 'value',
        content_type: 'text/plain',
        data: 'aGVsbG8gd29ybGQ='
      }
    },
    group2: {
      ...
    }
  }
});
```

I'm only going to save attachments via the inline method.

If neither of the above is possible, how would I go about grouping them? atm I can only come up with adding a prefix to the attachment name.

### Info
- Environment: Node.js
- Adapter: WebSQL

**Comment by nolanlawson** [comment]
No, if you attach any special data to attachments then it's not guaranteed to get stored anywhere. Different replication backends or adapters will probably drop that data. If you have extra data to store, you should store it outside of the `_attachments` object.
