### ISSUE TITLE
The `back_off_function` does not reset its delay when it comes back online

### ISSUE THREAD

**Issue by kelvinj** [pouchdb/pouchdb#5828]
### Issue
The `back_off_function` does not reset its delay when it comes back online.

I would expect the back off to start from scratch each time I go offline.

### Info
- Environment: browser
- Platform: checked on Chrome & FF
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce

```js
                localDB.sync(remoteDB, {
                    live: true,
                    retry: true,
                    back_off_function: function (delay) {
                        if (delay === 0) {
                            console.log('back off delay: 1000');
                            return 1000; // start with 1 second
                        }

                        if (delay < 10000) {
                            console.log('back off delay: ' + delay * 1.2);
                            return delay * 1.2; // increase a little bit at a time
                        }

                        console.log('back off delay: 10000');
                        return 10000; // don't go over 10 seconds
                    }
                })
```

1. Begin syncing
2. Go offline and monitor console
3. Note the increase in delay being logged
4. Go back online
5. Go offline again
6. Note the delay picks up where it left off

**Comment by daleharvey** [comment]
hrm, it seems like from https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-replication/src/backoff.js#L18 that is what it is supposed to do

**Comment by kelvinj** [comment]
@daleharvey so it's _not_ supposed to reset the backoff although you've come back online?

Perfectly possible, although to me it would make more sense if it did.

**Comment by regystro** [comment]
@daleharvey then I think either the code or the explanation at https://pouchdb.com/api.html#customizing-retry-replication is mistyped:

> The first time a request fails, this function will receive 0 as input. The next time it fails, 1000 will be passed in, then 3000, then 9000, etc. When the user comes back online, the delay goes back to 0.

With the shown code the last sentence never applies.

Please, have a look at it, since I was expecting the same behaviour that @kelvinj said based on the documentation. Thank you!!

**Comment by daleharvey** [comment]
Sorry I meant from my understanding of that code it seems like the backoff should reset, and if the docs say so then its definitely a bug, a test / fix would be happily accepted

**Comment by regystro** [comment]
Well, from what I can tell having a look at the code (https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-replication/src/backoff.js#L25) and doing some tests, it seems that when the connection is reestablished, returnValue never gets the 'active' state required to trigger backoffTimeSet() and reset the delay counter.

Once the connection is lost, the state goes from 'pending' to 'stopped'. And once is reestablished state is 'paused' and hence triggers removeBackOffTimeSet, but never gets the 'active' value.

So, as you (@daleharvey) said, the code at backoff.js also seems OK to me, The 'state' is what's not passed / updated properly.
