### ISSUE TITLE
I use it in electron (vue2.0),but I met a problem

### ISSUE THREAD

**Issue by zuijiaoluo** [pouchdb/pouchdb#5831]
### Issue
index.js?e89a:5170 Uncaught (in promise) Error: TypeError: Path must be a string. Received undefined: unable to import leveldown

this._status = 'opening'
  this.db      = new DeferredLevelDOWN(this.location)
  dbFactory    = this.options.db || getLevelDOWN()
  db           = dbFactory(this.location)

dbFactory is not a function
### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

### Reproduce
Write the steps for others to reproduce issue here. Providing a code example, links to a repository or a live example (JSBin etc) are even more helpful.

**Comment by nolanlawson** [comment]
This looks like an Electron issue related to building leveldown. You need to recompile it in order to work: https://github.com/nolanlawson/pouchdb-electron

Please let me know if this solves your issue, cheers.
