### ISSUE TITLE
Fix for #4868 prevents firing of `destroyed` event after `close()`

### ISSUE THREAD

**Issue by shimaore** [pouchdb/pouchdb#5833]
Thinking over the changes in #4868 I came up with new tests for test.events.js that break when `close()` and `destroy()` are interleaved on the same database.

I'm working on writing proper tests for these cases, and a clean solution for `constructor.js` and `setup.js`.

**Comment by nolanlawson** [comment]
closing; let's keep issue discussion in #4868
