### ISSUE TITLE
Make ajax a fetch polyfill

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5835]
So currently our http adapter makes requests that conform to the `request` api with a promise wrapper, I would like to switch that so we use the fetch api in pouchdb and `ajax` polyfills that for unsupported browsers / node. 

In https://github.com/pouchdb/pouchdb/pull/5763 we will be exposing this API so I would much prefer to be exposing a standard than our custom lib, also this means if you are targeting modern browser, and for everyone in future the whole of `ajax` can just be deleted which is a nice reduction of code

**Comment by daleharvey** [comment]
I think this should probably done on its own then I can rebase https://github.com/pouchdb/pouchdb/pull/5763 on top of it, doing them together sounds complicated

**Comment by nolanlawson** [comment]
As part of removing `lie`, I would be in favor of just using global `fetch()` and telling users that they need a fetch polyfill (or perhaps providing a version of Pouch with a polyfill build in, although it's likely to be quite big).

Is this possible though given that we don't have a cancellation API on fetch() yet?

**Comment by daleharvey** [comment]
Yup, thats the main reason I have been holding off on this is that there isnt a way to cancel requests as standard, I just add an abort method to the promise @ https://github.com/pouchdb/pouchdb/pull/5763/files#diff-ba0c1fc7897f873adc56b947f15f6534R166, but we should be able to just do the same hack with normal fetch then fix it when cancel happens

Yeh I wasnt sure whether we should just use fetch and ask users to polyfill, it would be the consistent approach when we start doing that with promises but it has slightly less support, would lean on the edge of agreeing

**Comment by nolanlawson** [comment]
Alternatively, we could make the main `pouchdb.js` contain the polyfills, then `pouchdb-lite.js` could remove them (ala #5804). If the default is the "everything but the kitchen sink" then beginners are much less likely to get confused.

**Comment by daleharvey** [comment]
Just reminding myself of what cancellation with fetch is going to look like https://github.com/tc39/proposal-cancelable-promises/blob/master/Cancel%20Tokens.md#example

**Comment by nolanlawson** [comment]
What's blocking this now? Since `FETCH=1` mode is fully passing all our tests, seems we can just prefer `fetch()` and fall back to `XMLHttpRequest()` rather than the other way around.

**Comment by cdaringe** [comment]
cancellation is really cleanly implemented with observers.  it would probably mean a couple more light deps, but worth consideration
