### ISSUE TITLE
PouchDB + Angular2 initial sync returns no data

### ISSUE THREAD

**Issue by rrubio** [pouchdb/pouchdb#5837]
### Issue
On initial browser load db.sync doesn't seem to return any data. However, if i reload the browser then data is available.

### Info
- Angular 2 (typescript)
- running on Mac
- Platform: (Chrome/FF/Safari/)
- Adapter: (IndexedDB)
- Server: (CouchDB/Cloudant/)

### Reproduce

Under my data service "contractor" -

```js
    let options = {
      live: true,
      retry: true,
      continuous: true,
    };

    let sync = this.db.sync(this.remote, options);
```

This is what i get with a console.log(sync) -

```js
{  
   "canceled":false,
   "push":{  
      "_events":{  
         "complete":[  
            null,
            null,
            null
         ]
      },
      "cancelled":false,
      "state":"pending",
      "_readyCalled":true,
      "_addedListeners":true
   },
   "pull":{  
      "_events":{  
         "complete":[  
            null,
            null,
            null
         ]
      },
      "cancelled":false,
      "state":"pending",
      "_readyCalled":true,
      "_addedListeners":true
   },
   "pushPaused":true,
   "pullPaused":true,
   "_events":{  

   }
}
```

Function fetching data - 

```js
getDocuments(){

    return new Promise(resolve => {
 
      this.db.allDocs({
 
        include_docs: true,
        limit: 30,
        descending: true
 
      }).then((result) => {

        this.data = [];

        let docs = result.rows.map((row) => {
          this.data.push(row.doc);
        });
 
        this.data.reverse();

        resolve(this.data);
        
        this.db.changes({live: true, since: 'now', include_docs: 
          true}).on('change', (change) => {
            this.handleChange(change);
        });

      }).catch((error) => {
 
        console.log(error);
 
      }); 
 
    });
 
  }
```

Will upload code to git today.

**Comment by nolanlawson** [comment]
Are you updating your Angular views within the Promise callback? I'm not familiar with Angualr 2, but in Angular 1 you have to call `$rootScope.$apply()`.

It sounds like your view is based on the initial state of the data, but not the _updated_ state. This would explain why you see empty views on first load, but then need a refresh to see the updated state.

You may also be interested to read this article on how to synchronize PouchDB with any view library: https://pouchdb.com/2015/02/28/efficiently-managing-ui-state-in-pouchdb.html

**Comment by rrubio** [comment]
That makes sense! thank you, I'll look into that and update this issue on my findings.

**Comment by dharders** [comment]
Angular 2 change detection is generally pretty good. But I've found cases, especially with asynchronous callbacks, where change detection hasn't kicked in.

Angular 2 uses zone.js under the hood. So whenever I experience something like you're describing I use `zone.run()` (think of it as `$rootScope.$apply()` for version 2):

```typescript
import { NgZone } from '@angular/core'
...
// inject NgZone into your component/service constructor
constructor(private zone: NgZone) {}

// then update your variable(s) within this.zone.run()
this.db.changes({live: true, since: 'now', include_docs: true})
  .on('change', (change) => {
    this.zone.run(() => {
      this.handleChange(change);
    });
});
```

I had to do this with earlier versions of Angular 2 (i.e beta and RC). Not too sure if it still applies, so YMMV ;)

**Comment by rrubio** [comment]
Hi Guys,

You were both on the money! thank you. I ended up running the following under it's own function and it works.

`initDB() {
    this.zone.run(() => {});
}`

**Comment by thiagobackadelino** [comment]
MUITO OBRIGADO!   ainda preciso entender melhor o NgZone  mas passei pelo mesmo cenário das alterações não refletirem na view, mas como dharders explicou agora esta OK

**Comment by jdprosser** [comment]
Thankyou dharders, your zone example above resolved my issue.
angular@5.2.5
pouchdb@6.4.3
