### ISSUE TITLE
Test broken in firefox nightly

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5845]
Seems like a basic failure, trying to write data to a read only error object but want to see if I can get this tested in CI so it doesnt get sprung on us in future

**Comment by daleharvey** [comment]
Ok, so even though we specify Firefox 48 in travis its actually testing Firefox 38, I figured out how to get travis to use a later version https://github.com/pouchdb/pouchdb/pull/5846/commits/93638432735e707c5d3edb8defb0084411c2d1a3 but its broken as Firefox 47 had some breaking change for selenium, now it seems like geckodriver is supposed to be the fix for this, however as far as I can tell https://github.com/vvo/selenium-standalone/ is installing geckodriver but still not working

@vvo is there anything we are supposed to do anything to get Firefox >= 47 work?

**Comment by nolanlawson** [comment]
Last I saw geckodriver only works with Firefox 48+. But I didn't test with selenium-standalone; I tested with another Selenium implementation.

**Comment by vvo** [comment]
@daleharvey Did no try geckodriver for myself using last selenium-standalone. Sorry.

**Comment by nolanlawson** [comment]
travis stuff has been largely fixed, we are now testing in firefox 47 which is new enough
