### ISSUE TITLE
add-cors-to-couchdb https://aname.cloudant.com -u aname -p apass

### ISSUE THREAD

**Issue by ninebang** [pouchdb/pouchdb#5847]
### Issue

From "pouchdb-getting-started-todo/" directory run :
add-cors-to-couchdb https://myname.cloudant.com -u myname -p mypassword
Gives
[Error: status 403 {"error":"forbidden","reason":"server_admin access is required for this request"}

On cloudant Dashboard, I configure CORS so Databases will accept requests from these domains:
All domains ( * )

### Info
- Environment: (Node.js/browser)
- Platform: (Chrome/FF/Safari)
- Server: (Cloudant)

### Reproduce
add-cors-to-couchdb https://myname.cloudant.com -u myname -p mypassword

**Comment by willholley** [comment]
Cloudant uses a different API from CouchDB to set up CORS, so this is expected. Instead of using `add-cors-to-couchdb`, you can do:

```
curl `https://myname.cloudant.com/_api/v2/user/config/cors` -u myname -p mypassword -H 'Content-Type: application/json' -X PUT -d '{"enable_cors": true, "allow_credentials": true, "origins": ["*"] }'
```
