### ISSUE TITLE
Does view generation yield?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#5849]
If I'm using PouchDB e.g. with the leveldb adapter and I kick of a new view against a db with 100k documents. Will PouchDB:

- Yield the event queue?
- Use up 100% cpu?

Basically what I'm asking is whether I can reliably run PouchDB in the same nodejs process as e.g. a http server?

**Comment by nolanlawson** [comment]
This is something that ought to be profiled. Even an async database like PouchDB necessarily does some amount of work on the main thread, so the number is not 0% of 100% blocking but instead somewhere in between.

If I had to guess, I would say that it will maybe be around 10% but this is something you should profile. However I can say that yes, view generation will yield periodically to the event loop.

You could also ask this question on the Google Groups mailing list to see if anyone would be interested in running a benchmark. Please reopen if this doesn't answer your question! :)
