### ISSUE TITLE
PouchDB continuous replication fails inside of a service worker

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5851]
This could just be me making a dumb mistake, but I could not get live+retry replication working inside of a service worker.

I tried both Chrome and Firefox, as well as CouchDB 2.0.0 and PouchDB Server, and saw the same result. See the repo for steps to reproduce: https://gist.github.com/nolanlawson/f2de83e04af18eae84aba1457e4b76f0

I'll try to look into this when I get a chance.

**Comment by KlausTrainer** [comment]
I can confirm this.

Looks like the replication won't progress. That is, it keeps retrying to fetch a (non-existent) local document. Running the same code in the main thread works as expected.

**Comment by KlausTrainer** [comment]
Also, running it in a Web Worker works as expected.

**Comment by KlausTrainer** [comment]
Looks like the problem is that you're relying on the global scope. As far as I can remember, this used to work, however. But the spec is pretty clear on that: https://www.w3.org/TR/service-workers/#service-worker-global-scope-interface

I think both Firefox and Chrome implemented changes to make the global scope more short-lived, which has been discussed before. See Jake's [service worker meeting notes](https://jakearchibald.com/2016/service-worker-meeting-notes/).

Doing e.g. something like this will work:

```javascript
importScripts('pouchdb.js')

function replicateToServer() {
  var db = new PouchDB('my_db')
  var remoteDB = new PouchDB('http://127.0.0.1:1337/test')

  db.put({_id: 'test_' + Date.now()}).then(() => {
    var replication = db.replicate.to(remoteDB, {
      live: true,
      retry: true
    }).on('uptodate', () => {
      console.log('uptodate')
      replication.cancel()
    }).on('complete', () => {
      console.log('complete')
    }).on('error', console.error.bind(console))
  })
}

replicateToServer()
```

**Comment by nolanlawson** [comment]
Ugggg I should have thought of that. I was even at the Service Worker working group F2F, and this has been a huge discussion inside of the Edge team. For some reason I just assumed that if the global scope became problematic, the error message would be more obvious.

Thanks for looking into this. I'll modify my example and try again. @jkleinsc you may be interested in Klaus' comment above.

**Comment by jkleinsc** [comment]
@nolanlawson  Thanks for following up on this.  I believe this validates the fact that you can't have a long lived/live sync in a SW and instead need to rely on background sync(https://wicg.github.io/BackgroundSync) and the Push API (https://w3c.github.io/push-api/) to managing syncing within a SW.

**Comment by nolanlawson** [comment]
@jkleinsc Yep, that seems about right to me. Alternatively you can have a `changes()` listener inside of the main thread. Since IDB has transactional guarantees, this is safe. Of course it leads to some UI blocking but should be minimal if you're only listening to changes in order to ping the service worker.
