### ISSUE TITLE
IndexDB Destroy, IE/Edge Errors

### ISSUE THREAD

**Issue by CentricStraaten** [pouchdb/pouchdb#5864]
I have written code to destroy multiple databases. In Chrome everything is working as expected. Internet Explorer/Edge throws errors while destroying some of the databases:

> Database has a global failure UnknownError
>
>{ABORT_ERR: 20, code: 11, constructor: DOMException {...}, DATA_CLONE_ERR: 25, DOMSTRING_SIZE_ERR: 2, HIERARCHY_REQUEST_ERR: 3, INDEX_SIZE_ERR: 1, INUSE_ATTRIBUTE_ERR: 10, INVALID_ACCESS_ERR: 15, INVALID_CHARACTER_ERR: 5, INVALID_MODIFICATION_ERR: 13, INVALID_NODE_TYPE_ERR: 24, INVALID_STATE_ERR: 11, message: "InvalidStat...", name: "InvalidStat...", NAMESPACE_ERR: 14, NETWORK_ERR: 19, NO_DATA_ALLOWED_ERR: 6, NO_MODIFICATION_ALLOWED_ERR: 7, NOT_FOUND_ERR: 8, NOT_SUPPORTED_ERR: 9 ...}
>
> {"status":500,"name":"indexed_db_went_bad","message":"unknown","reason":"Failed to open indexedDB, are you in private browsing mode?"}

Can anyone help me to solve this issue?

- Environment: AngularJS
- Platform: IE 117/Edge
- Adapter: IndexedDB
- Server: PouchDB

```
function removeDatabases() {

	var promises = [];

	angular.forEach(databases, function (value, index) {
		promises.push(removeDatabase(value));
	});

	return $q.all(promises);
}
```
```
function removeDatabase(name) {

	var deferred = $q.defer();

	new PouchDB("Deemas." + name).destroy().then(function () {
		console.log("ddb " + name + " deleted");
		deferred.resolve();
	}).catch(function (err) {
		console.log(err);
		deferred.rejected();
	});

	return deferred.promise;
}
```

**Comment by nolanlawson** [comment]
Could you please provide a live reproducible test case (e.g. an HTML file hosted on bl.ocks.org) ? Otherwise it's difficult to reproduce because this is a tricky case.

I work on the Edge team and we'd definitely appreciate a test case to show the error. Most likely it is a bug in IE/Edge and not a bug in PouchDB (unless PouchDB can work around it somehow).

**Comment by CentricStraaten** [comment]
I already fixed the issue. I changed the removeDatabase method for use with IE/Edge

```
        function removeDatabaseIE(name) {
            databases[name] = pouchDB('Deemas.' + name, {
                auto_compaction: true,
                revs_limit: 1
            });

            var database = databases[name];
            console.log("delete ddb" + name);
            indexedDB.deleteDatabase('Deemas.' + name);

            return database.allDocs().then(function (result) {
                $q.all(result.rows.map(function (row) {
                    database.remove(row);
                })).then(function () {
                    console.log('create Deemas.' + name);
                    return databases[name] = new pouchDB('Deemas.' + name, {
                        auto_compaction: true,
                        revs_limit: 1
                    });
                });
            });
        }
```
This alternative routine solved my problem.

**Comment by nolanlawson** [comment]
thanks, FWIW this issue is also being tracked internally via this bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/988204/

**Comment by VladyslavGoloshchapov** [comment]
thank you @CentricStraaten - that helped. I actually came to same solution - but without specifying 

`                   auto_compaction: true,
                        revs_limit: 1`

But that is very important. Thanks, again.

@nolanlawson  can you add this topic to the guides section of documentation? or at least a link to this page.
