### ISSUE TITLE
Multiple processes accessing same database?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#5865]
What is the behaviour when pointing several PouchDB instances running in different processes against the same path? (LevelDB)

**Comment by nolanlawson** [comment]
The behavior is undefined and it is not recommended.

**Comment by ewnd9** [comment]
@nolanlawson What about [multi-proces-access section](https://github.com/Level/levelup#multi-process-access) in `levelup` repo?

**Comment by nolanlawson** [comment]
PouchDB has in-memory optimizations currently that probably negates that.

-----
Nolan Lawson
http://nolanlawson.com
https://github.com/nolanlawson
