### ISSUE TITLE
pouchdb 6 prebuilt sqllite db problem

### ISSUE THREAD

**Issue by vahidreza** [pouchdb/pouchdb#5866]
hi @nolanlawson ,
thanks for your great efforts. actually i try to implement the [pouch db prebuilt sample](https://pouchdb.com/2016/04/28/prebuilt-databases-with-pouchdb.html) in my cordova application but when I ge the db object it returns 0 documents, although I myself have populated the database with some documents and I can see them with a sqllite db browser but the plugin returns 0 documents every time I initialized pouchdb.
I susspect if pouchdb cannot access the copied version and creates a new file all by itself.
how can this be reviewed?

**Comment by vahidreza** [comment]
hi
I found out the problem.
If you use pouchdb-5.0.2 everything's ok but if you use pouchdb-6.0.6.min it doesn't work.
can you resolve the issue ?

**Comment by nolanlawson** [comment]
I suspect what's going on here is that in PouchDB 6.0.0 we dropped support for automatic Cordova SQLite databases; you need a separate adapter now. Also the `_pouch_` prefix is gone. Please see https://github.com/pouchdb/pouchdb/wiki/Breaking-changes for details.

Also please reopen if this does not describe your issue. Thanks!

**Comment by nolanlawson** [comment]
And yes I see now that the blog post should be updated; I'll open an issue for that.

**Comment by nolanlawson** [comment]
@vahidreza Please see https://github.com/pouchdb/pouchdb/pull/5878 for updated instructions for PouchDB 6.
