### ISSUE TITLE
PouchDB.debug on Ionic2 RC1

### ISSUE THREAD

**Issue by meeximum** [pouchdb/pouchdb#5871]
### Issue
I get an transpile error, when trying to enable debug

> Property 'debug' does not exist on type 'Static'.

```
import * as PouchDB from 'pouchdb';
PouchDB.debug.enable('*');
```

### Info
- Environment: Ionic2 RC1
- Platform: Visual Studio Code
- Adapter: websql
- Server: none

### Reproduce
```
npm install pouchdb --save
npm install @type/pouchdb --save
```

**Comment by nolanlawson** [comment]
This appears to be a typings error? My hunch is that you would need to fix https://www.npmjs.com/package/@types/pouchdb or add the typings to your own project

**Comment by meeximum** [comment]
ok, thx for your help
