### ISSUE TITLE
Get all active tasks

### ISSUE THREAD

**Issue by derBinder** [pouchdb/pouchdb#5881]
### Issue
I want to check if my pouchDB is busy (e.g. is there a replication or indexer running), but I couldn't figure out how.
I tried to check `db.taskqueue` but the queue is empty. Is this the right way?
Is there a way to get all active tasks like the CouchDB-call `_active_tasks`?

### Info
- Environment: UWP-App (C#) WebView (HTML / JS / CSS)
- Platform: Edge 
- Adapter: idb
- Server: CouchDB

**Comment by nolanlawson** [comment]
This is currently not supported, but sounds like a reasonable request.

**Comment by rpiaggio** [comment]
I'm very interested in this functionality. So, I'm just adding a comment so that it's not closed as stale. Thank you!

**Comment by gr2m** [comment]
@rpiaggio you should make it real then :) I don’t think anyone else will pick it up, it’s been open for a long time

**Comment by daleharvey** [comment]
I think this is probably best written on top of pouchdb, the lifecycle of processes is very different between the server and the client so active_tasks doesnt map great, it can be done using the current api which makes it a good candidate for a plugin
