### ISSUE TITLE
Master branch is broken (Safari issue?)

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5900]
Travis is failing on master right now. Seems all Safari and iPhone builds are broken.

**Comment by nolanlawson** [comment]
Example of broken build: https://travis-ci.org/pouchdb/pouchdb/builds/176740704

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/7088f3fa2d49a4ba901967f36e47de5aa2a91c12
