### ISSUE TITLE
fetch-based ajax implementation is untested

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5902]
Our fetch-based ajax implementation is completely untested. I am 99% sure there are bugs in Service Workers and Web Workers due to this, but we won't know until we add a test for it.

**Comment by nolanlawson** [comment]
As it turns out, there are a _lot_ of bugs, and they're different bugs in Chrome vs Firefox. :confused: This commit above is just to show that I've started working on it at least.

**Comment by nolanlawson** [comment]
So, Chrome fails with a CORS error for an attachment PUT, Firefox returns a 0-length `.blob()` for an attachment GET, WebKit fails with a "Preflight response is not successful," and Edge fails with "TypeMismatchError." So this is apparently not a browser bug but I'm not sure why it's failing just yet.

**Comment by nolanlawson** [comment]
n/m, I found the fix

**Comment by daleharvey** [comment]
So probably tonight I plan on making a patch that makes fetch our primary api for making requests, `ajax` will become purely a fetch polyfill (and fetch -> request for node) as a dependency of https://github.com/pouchdb/pouchdb/pull/5763

**Comment by nolanlawson** [comment]
:+1:

**Comment by nolanlawson** [comment]
For "PouchDB Lite" I am running with the assumption that users will have to polyfill Promise/fetch/Map/Set/Blob themselves, at which point I think we can get down to a sub-20KB minified size.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/f0e0e0c86212d6e28eb37ebf76a9dc14972b3623
