### ISSUE TITLE
SauceLabs tests should be run even for non-contributors

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5905]
SauceLabs has now introduced the ability to run tests even for non-contributors, but you have to change the config to get it to work. This would prevent regressions like #5900.

@halkeye showed me how to do this, but I haven't yet merged it because I'm swamped with a bazillion other things. But here's a sample PR: https://github.com/nolanlawson/html5workertest/pull/15

**Comment by halkeye** [comment]
@nolanlawson travis is going to be deprecating this functionality, so its probably worth closing this again :(

**Comment by gr2m** [comment]
We just make the saucelabs credentials visible to make them run for pull requests

**Comment by daleharvey** [comment]
Yeh I wanna get to this one shortly

**Comment by daleharvey** [comment]
Working now :)

**Comment by nickcolley** [comment]
This is awesome 👏
