### ISSUE TITLE
question about your latest blog post

### ISSUE THREAD

**Issue by avidanyum** [pouchdb/pouchdb#5910]
Your blog post https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html was extremely helpful.  I come from java.  I feel like you are the only one who understands me as all around I see `promises` code which does not use the benefits of `return` value and `throwing`.  There is another thing which is bothering me.  It's hard to debug in `IDE` promises (not that its easy callback) but does that bug you also? I mean as the code is asynchronous I can't just `step forward` with the debugger i have to put breakpoints all over the place to understand whats going on in code i'm maintaining.  I wonder if that bugs you as well, I mean I had debugging capabilities in the past, why loose such a good weapon I had in the past...  (not that its specific to promises, but coming to write in async mode brings up this..)

**Comment by nolanlawson** [comment]
Yes it is painful to debug. Chrome Dev Tools is making it easier to debug async code if you use async/await. Here’s a video: https://www.youtube.com/watch?v=HF1luRD4Qmk <https://www.youtube.com/watch?v=HF1luRD4Qmk>

Cheers,
Nolan
