### ISSUE TITLE
PouchDB syncing of attachments on React Native

### ISSUE THREAD

**Issue by ddolheguy** [pouchdb/pouchdb#5915]
Hi All,

Firstly I know this issue is specific to React-Native and the Async Storage adapter but I was hoping someone might have an idea of how to help.  The question does have relevance to how PouchDB works.

**Problem:**
I'm using (https://github.com/stockulus/pouchdb-react-native) which uses PouchDB-core and upon a "sync" from CouchDB (v2.0) of a document with attachments (5 x images of roughly 40KB each), Pouch returns them as of data type BLOB which doesn't seem to be supported in React native.

Firstly, has anyone actually got attachments to work via sync from CouchDb and React Native with PouchDb? If so (and I'm assuming they might have used base64, how since PouchDb always seems to return BLOB's upon sync).

Secondly, is there any way to get PouchDB to provide base64 instead?  I realise this is the worst performance option, but I can't find another solution at this stage.

Any help at all would be SO much appreciated.

**Comment by ddolheguy** [comment]
I'm closing this issue as after hours and hours of research I've been able to find a solution and will create a PR for the above project to solve BLOBS :)

**Comment by der-ede** [comment]
Hi @ddolheguy,

I cannot seem to get auto syncing attachments to work at all in RN.

Blob or base64 would not be an issue, since it can be converted. But I am not getting syncing at all. 
No matter what options I provide (tried all that are listed in pouched.com) it is not automatically synced.
Only thing working is when I actually 
```
remoteDB = new PouchDB(cloudantUrl + databaseName + '/', {ajax: {cache: false}})
```
