### ISSUE TITLE
Reduce Travis flakiness

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5930]
Based on an informal audit of Travis builds (i.e. me pointing and clicking to restart tests for the past few days), our most faily tests seem to be iPhone and IE. If we can find ways to make these tests less likely to fail I would be super happy.

Some stuff I'm trying out:

1. Reducing memory usage (#5926, #5921)
2. Testing out different browser/OS combos (#5928)

I would really love if our test suite were reliably green/red rather than being nearly guaranteed to have a false negative on any given run.

**Comment by nolanlawson** [comment]
Occasionally I also see `No output has been received in the last 10m0s` for the Firefox builds. I believe this is due to not being able to find the installed Firefox 48.0.

**Comment by nolanlawson** [comment]
Might be related to https://github.com/pouchdb/pouchdb/pull/5898, but IE10+Win8.1 tests are _super_ flaky these days. I might have to deep-dive to see what's up.

**Comment by nolanlawson** [comment]
Wow, our build is really trolling us right now. On a typical run I have to restart like 6 jobs.

**Comment by nolanlawson** [comment]
OK, I'm fairly certain https://github.com/pouchdb/pouchdb/commit/4eb786b702f0db9fb2db049c71f29d7acbf18fc4 regressed us on IE10. Tests rarely seem to want to pass for that browser now.

**Comment by daleharvey** [comment]
Looking into this now, firefox seems far more faily than others, however I am seeing a fair amount of fails across the board as well so doing a large travis run @ https://github.com/pouchdb/pouchdb/pull/5967 and once we know / can get node stable then ill look at firefox

**Comment by nolanlawson** [comment]
I think it's reasonable to close this now. Done a lot of work here recently.
