### ISSUE TITLE
Safari websql buggy replication after recreating database

### ISSUE THREAD

**Issue by aeharding** [pouchdb/pouchdb#5943]
### Issue

After recreating a DB in safari, replicating data doesn't work.

I can consistently recreate this issue, but it's really hard to debug why this is happening since it's silently failing. :(

Something also weird. In the web inspector, I cannot click the "Storage" button to open the tab on my app after doing the above. I can open the storage inspector when on google.com though.

Another weird thing: It seems that if I edit add some documents to the db in safari after the issue arises and wait a long time (2-5 minutes), the db will start syncing and working well.

### Info
- Environment: Browser
- Platform: Safari 10.0
- Adapter: WebSQL
- Server: CouchDB 2.0.0

### Reproduce

1. Create a local DB in safari, replicate some data into it.  Default adapter (websql) and size: 50.
2. Destroy the local db.
3. Immediately after resolving I recreate the db (with the same name), same as step 1.
4. Refresh the page. If you don't refresh the page and immediately try (5), it will work fine.
5. Try to replicate with the same data from (1). This silently fails and PouchDB keeps polling the remote DB's index endpoint (returning `{
couchdb: "Welcome",
version: "2.0.0",
vendor: {
name: "The Apache Software Foundation"
}
}`.

Note that while I can create new stuff in the local DB, the replication doesn't work.

**Comment by aeharding** [comment]
Another clue: PouchDB seems to sync a batch of docs (I'm using couchDB 2.0) and then starts going through the weird couchdb `/` polling described above.

**Comment by nolanlawson** [comment]
Are you deleting the DB using `db.destroy()` or via the Safari Web Inspector UI?

The reason I ask is because PouchDB technically does not _delete_ the WebSQL database; instead we just DELETE all tables. This is due to limitations in the WebSQL API itself. If you manually delete DBs in the Web Inspector, then weird stuff might happpen.

OTOH if you can repro this just with code (e.g. maybe write a jsbin/codepen to show what's happening?) that would be super helpful. :)

**Comment by aeharding** [comment]
I'm calling `db.destroy().then(create)`, where `create()` is just doing `db = new PouchDB(config)`.

I'm definitely looking into recreating with some code. Just thought I'd get this out there first if anyone else has come across this. Thx @nolanlawson!

**Comment by aeharding** [comment]
I tried some more debugging, and I was unable to replicate the problem using this code and a local CouchDB 2.0 database. I even tried proxying the database under /db/ using nginx:
https://gist.github.com/aeharding/abed2faac14073d9733c665c62ce87aa

Later I did some more investigation in the problem by enabling debugging. This is one strange error I get:
![image](https://cloud.githubusercontent.com/assets/2166114/20637254/7fcb43fc-b347-11e6-87a9-008da7e10341.png)

Notice the [object Object].

And here's the network tab. Notice that /appcache/index.html's initiator index-browser.js:
![image](https://cloud.githubusercontent.com/assets/2166114/20637260/a2410db8-b347-11e6-8d01-c03ca2eac69b.png)

Any help is appreciated! I'll keep investigating.

**Comment by nolanlawson** [comment]
@aeharding Are you running a proxy in front of CouchDB? That error you posted seems like it should only be possible if the server returns HTML instead of JSON, which CouchDB itself never does AFAIK.

**Comment by nolanlawson** [comment]
If you double-click that error response you'll probably see an HTML page from nginx saying "error happened, here's the error"

**Comment by aeharding** [comment]
The weird thing is in the network tab it's showing requesting `/appcache/index.html`.

I'm curious if the iOS 10 indexeddb implementation would make this problem disappear. Do you know the easiest way to force indexeddb for Safari?

**Comment by nolanlawson** [comment]
I am guessing that the issue here is not WebSQL-related but rather Safari network-related. Safari has some interesting caching techniques that tend to be hard to work around especially if you've built your own proxy in front of CouchDB (trust me – making your Couch proxy work correctly is easier said than done).

You can test IDB in Safari by changing `pouchdb.js` so that the `IdbPouch.valid()` function for IndexedDB just returns true. Note that in an upcoming release of PouchDB we will probably enable IDB for Safari 10+.

**Comment by aeharding** [comment]
@nolanlawson you were on the right track! The issue was the Application Cache fallback in webpack-offline. Because Safari does not support service workers, it falls back to AppCache. This is fine, although I proxy CouchDB under `/db/` and therefore any non `2xx` requests will subsequently be cached and served index.html (I have a fallback in the appcache for my SPA).

This is a limitation of the Application Cache, and is yet another reason for browser vendors to hurry up and support Service Workers! :)

My fix was simply disabling Application Cache in webpack-offline. Another possible workaround would be to make a separate subdomain for CouchDB, but I'm lazy. :)

Super hard to debug, although seems obvious now. :/
