### ISSUE TITLE
IE/Edge: suppress spurious "Failed to open IndexedDB" warnings

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5949]
Well, we thought we had nailed down all the IE/Edge bugs, but apparently this one slipped through because we are just logging it without throwing an actual error.

If you run our test suite, or run a local-only version of the tests like [this one](https://bl.ocks.org/nolanlawson/raw/9af8f79637b6f0d553ee121ef6fdd428/), and if you look in the console, you will see tons of errors which are invoked by the `onerror` event of the `indexedDB.open()` request. I can repro this in IE11 and even in an Insider version of Edge (14965.1001).

![2016-11-26 14_11_26-mocha - microsoft edge](https://cloud.githubusercontent.com/assets/283842/20644233/d59bf5d8-b3e2-11e6-8e8c-d825fc48577a.png)

This doesn't repro in latest Firefox, latest Chrome, or even Safari 10 (using IDB, not WebSQL).

It's definitely a race condition, because it seems I can get rid of it by just wrapping all open/close/destroy calls in a task queue and spacing them out with `setTimeout(fn, 100)`, but obviously that's an unsatisfactory solution. Sadly `setTimeout(fn, 0)` doesn't actually fix the problem, so I don't know if the "IDB is okay to call again" event is even observable from JavaScript.

Occasionally the error is thrown in the `onabort` instead. In the onabort case `e.target.error` is `DOMError: "Unknown Error"`. In the case of `onerror` there is no error (!); instead there's just `e.target` which is the IDB with a readyState of "done" and a result of 0. It seems `onsuccess` was already called though, which is why the error doesn't get propagated to PouchDB consumers.

Obviously I'll share these findings with the rest of the Edge team, but it's worth documenting here so that PouchDB users/contributors at least are aware.

/cc @aliams

**Comment by nolanlawson** [comment]
Also it behooves us to try to fix this on the PouchDB side of things, because IE11 will likely never get the fix since its only in maintenance mode.

**Comment by nolanlawson** [comment]
Hm, seems the only fix I can find is to just _not_ log the error. Perhaps we need to just ignore `onerror` events in IE/Edge, lest we confuse the user.

**Comment by nolanlawson** [comment]
Hm occasionally `e.target.error` is null, occasionally it's `DOMError: AbortError`.

**Comment by nolanlawson** [comment]
Filed a new issue on this: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9978479/

**Comment by aliams** [comment]
Thank you @nolanlawson for filing the issue!

**Comment by nolanlawson** [comment]
Updated the issue name. The real bug on our end is that we are logging these spurious errors that are intended to help people trying to understand Firefox private browsing errors. For IE/Edge we should just ignore them.

**Comment by ramanjitsingh** [comment]
@nolanlawson - Do you mean we should ignore these error in IE? will pouchDB version 6.1.1 work normal (without any errors) in IE/Edge or IE 11? PouchDb is still showing up this error in latest version.
I am using pouchDB 6.1.1 in IE 11 IE Edge and facing same issue **"Failed to open IndexedDB, are you in private browsing mode?"**

**Comment by nolanlawson** [comment]
In my tests the PouchDB test suite still passes even though the console is full of these errors. I wasn't aware though that it was different in PouchDB 6.1.1.
