### ISSUE TITLE
Api docs for PouchDB.adapter()

### ISSUE THREAD

**Issue by trubit** [pouchdb/pouchdb#5969]
### Issue
Add API docs for PouchDB.adapter() function.

Api docs all missing mention of adapter function, but its havily used. Also there is 3rd option, which may be not known.

https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/setup.js#L35

We can then use this info in typings for pouchdb as here:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13024#pullrequestreview-10928204

**Comment by nolanlawson** [comment]
It's sort of a hidden method, but by now it's ingrained enough that it should probably be documented. It would break the ecosystem to change it.

**Comment by nolanlawson** [comment]
The third option is a boolean telling us whether to add it to the "preferredAdapters" list or not, which is basically just a way to distinguish http from the other (local) adapters.
