### ISSUE TITLE
leveldown fails to compile in Raspberry Pi

### ISSUE THREAD

**Issue by markdturner** [pouchdb/pouchdb#5970]
### Issue
Could not locate the bindings file. leveldown.node: unable to import leveldown

### Info
- Environment: Node.js
- Platform: Raspbian on ARM
- Adapter: LevelDB
- Server: PouchDB

### Reproduce
I'm having a hard time reproducing the issue myself as it works no problem on several different types of devices, including another Raspberry Pi. The installation in question is on a Raspberry Pi running a node application. When the application starts it instantiates three Pouch databases in the same way and they all fail due to an issue importing leveldown. The link to the stack trace is here: http://pastebin.com/NEVN6XZs

```
//config.dbServer.userDB = 'vs-users'
app.localUsersDB = new PouchDB(config.dbServer.userDB);
app.localRecordingsDB = new PouchDB(config.dbServer.recordingDB);
app.localSubjectsDB = new PouchDB(config.dbServer.subjectDB);

console.log(app.localUsersDB);
```

**Comment by nolanlawson** [comment]
It's very likely that leveldown doesn't work on a Raspberry Pi. You might want to try the `node-websql` adapter instead which uses the node `sqlite3` project under the hood. Another alternative is https://github.com/nolanlawson/pouchdb-adapter-fs although it's not really production-ready.

**Comment by nolanlawson** [comment]
It's also possible that you could recompile leveldown for Raspberry Pi but that's really a leveldown/Raspberry question rather than a PouchDB question.

**Comment by nolanlawson** [comment]
leveldown claims that it supports raspberry pi but I don't know what needs to be done to make it work: https://github.com/Level/leveldown/blob/62aa9084d2d5d8aca114441384025f93e013ff87/README.md#tested--supported-platforms

**Comment by the-t-in-rtf** [comment]
> You might want to try the node-websql adapter instead which uses the node sqlite3 project under the hood. 

@nolanlawson, This issue and [this yarn bug](https://github.com/yarnpkg/yarn/issues/2496) both block installation of pouchdb via a package manager.   Your suggestion wouldn't help with that part unless you're willing to make leveldown an optional and/or dev dependency.  Any chance of that?

**Comment by nolanlawson** [comment]
@the-t-in-rtf that seems to be a separate issue from the Raspberry Pi issue described above.

One easy fix may be: if you're only using PouchDB in the browser, you can use `pouchdb-browser` instead of `pouchdb` package, which doesn't contain leveldown.

Unfortunately if you are using yarn and need leveldown then you might have to wait for https://github.com/yarnpkg/yarn/issues/2496 to be fixed.
