### ISSUE TITLE
Invalid Adapter for IE 11

### ISSUE THREAD

**Issue by tshad** [pouchdb/pouchdb#5972]
I am having an issue with IE 11.  When trying to initialize my database I get an "Invalid Adapter" error.

The code I am using is:

DB_Images = new PouchDB('images');

The error comes from:

  if (!PouchDB.adapters[opts.adapter] ||
      !PouchDB.adapters[opts.adapter].valid()) {
    throw new Error('Invalid Adapter: ' + opts.adapter);
  }
This is in puchdb-6.0.7.js but I also get the issue using an older version (5.4.4).

This works fine in all other browsers.

Thanks,

Tom

**Comment by nolanlawson** [comment]
Are you in private browsing mode? We run automated tests in IE10 and all the tests pass. Maybe you've put IE11 in IE9 mode?

**Comment by tshad** [comment]
I am using IE11.  Other's here have no problem.

There seems to be some setting or maybe IndexDB is not there?

As far as I know, I don't have it running in IE9 mode.  I looked up private browsing mode and that seems to be for the life of the browser and I can make this happen over and over.

**Comment by nolanlawson** [comment]
Can you open the F12 tools, reload, and show a screenshot of the console? Most likely the error is in there. Else you will have to add debug statements to the `IdbPouch.valid` function to see why it's returning as invalid. Or if you could provide a live test case, that would be helpful. :)

We run our full test suite on IE10, we've tested it many times in IE and Edge, I work on the Edge team at Microsoft, and I've never seen this issue... but I'd be happy to help if you can provide more details. :)

**Comment by tshad** [comment]
OK.

I am running on PouchDB 5.44.  

I did try to load 6.1.1 to see if that helped, but it stops on the first new PouchDB call.

        return DB_WorkIssues = new PouchDB(DBNAME_WorkIssues, { auto_compaction: true })

Here is what was in the Console for the adapter issue:

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
Index
HTML1300: Navigation occurred.
Index
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
Index
pouchdb:adapter Picked adapter: undefined +0ms

**Comment by nolanlawson** [comment]
I'm sorry, we would need a live HTML page and more information about which version of IE, which version of Windows, etc. I'm testing PouchDB in Windows 10 on IE11 right now and the full test suite is working just fine...

**Comment by tshad** [comment]
Hi Nolan, 

As I had mentioned, I don't have a problem with IE11 on Windows 10 per se. It works fine on the machine at home. 

And it worked on my machine at work for awhile and than it didn't. 

So a live HTML page really wouldn't work. 

Thanks, 

Tom

**Comment by nolanlawson** [comment]
In that case, I'm a bit confused about how to reproduce this error... any details you can provide would be extremely helpful. It's hard to fix if we can't reproduce the error. 😦

**Comment by tshad** [comment]
I agree. 

I can't reproduce the error on my other machines or on any other machine. 

There is something about IE on my machine that has the problem. It is almost like the database is not there or the adapter is not there (or accessible). But until I started using pouch, I didn't even know about it. 

It isn't the machine itself, since chrome, firefox and safari work fine. 

So I have no idea how to tell you what is missing. It is just that the error is saying it can't find the adapter, whatever that means. 

Thanks, 

Tom

**Comment by tshad** [comment]
I did try this:

 if (!window.indexedDB) {
      window.alert("Your browser doesn't support a stable version of IndexedDB. Such and such feature will not be available.");
   }
and did get the alert in IE 11.

I just don't know why.  But I assume that whatever is causing this issue is also cause the adapter issue.

**Comment by nolanlawson** [comment]
Are you running IE11 in another docmode? Or do you have some kind of extension that is disabling IndexedDB? Is your IT configuration shutting it down for some reason? IDB was shipped in IE10 and should definitely be available in IE11.

**Comment by tshad** [comment]
That is the problem.  It used to work. I don't know if there is some setting that would disable it or enable it.  Nothing in the IT configuration is shutting it down as far as I know.  Is there some setting that turns it on or off?  It works on other machines in the office so unless it disappeared from IE11, I don't know what is happening.

**Comment by tshad** [comment]
Accidently closed the issue.

**Comment by tshad** [comment]
I found that I also have the same problem (Adapter error) on the IPad (the original one) when using Firefox and Chrome.  Safari works fine.

**Comment by nolanlawson** [comment]
The Firefox/chrome issue on iOS is undoubtedly unrelated. See:
https://github.com/pouchdb/pouchdb/issues/6235#issuecomment-280172368

-----
Nolan Lawson
http://nolanlawson.com
https://github.com/nolanlawson
