### ISSUE TITLE
Testing against couchbase

### ISSUE THREAD

**Issue by gedw99** [pouchdb/pouchdb#5977]
I noticed that we are testing against St big couch,but not Couchbase.

Any reason why we don't ?

I am using PouchDB with Couchbase sync gateway.

**Comment by willholley** [comment]
@gedw99 see #5820. We did have CSG as a test target in Travis for a long time but none of the core contributors work with it and nobody else has stepped up to maintain compatibility, which is getting increasingly difficult as CSG diverges from CouchDB.
