### ISSUE TITLE
Cancel all live replications

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb#5979]
For end-to-end testing, I’m starting a server in the background and then use selenium/saucelabs to make sure the app features work as expected. 

The server [starts listening to changes on a DB](https://github.com/hoodiehq/hoodie-account-server-api/blob/c941c1d23b8830df5bb0b99f1f81661d0a65b8c4/lib/utils/start-listening-to-account-changes.js#L6) somewhere deep in it’s sub-dependencies. 

The problem now is that the process which runs the tests gets stuck because it’s kept open by the open socket that PouchDB opened when using CouchDB (http adapter) as PouchDB’s backend. Note that there is no such problem when using levelDB or memory as adapter.

I wonder if PouchDB keeps track of all open change sockets / requests and if there is a way to cancel them all at once? So I could do something like this?

```js
server.on('stop', function () {
  PouchDB.cancelAllReplications()
})
```

If there is no such thing right now, any idea for a workaround?

**Comment by gr2m** [comment]
My current workaround looks like this:

```js
// keep state of continuous replications and changes in order to clean up on server stop
var liveChangesAndReplications = []
PouchDB.prototype.changes = (function (originalChanges) {
  return function changesPatchedForHoodie (options) {
    var changes = originalChanges.apply(this, [options])
    if (options.live || options.continuous) {
      liveChangesAndReplications.push(changes)
    }
    return changes
  }
})(PouchDB.prototype.changes)
PouchDB.replicate = (function (originalReplicate) {
  return function replicationPatchedForHoodie (source, target, options) {
    var changes = originalReplicate.apply(this, [source, target, options])
    if (options.live || options.continuous) {
      liveChangesAndReplications.push(changes)
    }
    return changes
  }
})(PouchDB.replicate)

server.on('stop', function () {
  liveChangesAndReplications.forEach(function (changesOrReplication) {
    changesOrReplication.cancel()
  })
})
```

Any thoughts?

**Comment by nolanlawson** [comment]
PouchDB does not keep track of all live replications, and I believe this can be done in userland. Every replication/sync operation returns a handler that is both an EventEmitter and has `cancel()` methods on it that you can call. So users can merely keep track of these objects; it could even be implemented as a PouchDB plugin.

In your case it sounds like your sub-dependency could solve this by ensuring that all access is done through some kind of PouchDB adapter. Another solution we are looking into is #5322 which would allow you to intercept all ajax requests and sub in your own implementations. I believe both of these can cover your use case; if not please reopen!

**Comment by AlpineTech** [comment]
Testing PouchDB 6.3.4 in Chrome...

I've tried to stop live replication with the cancel method, but the replication still continues afterwards.

**Comment by gr2m** [comment]
@AlpineTech can you create a new issue please and follow the instructions in the issue template? That will improve the chances a lot that someone will be able to help you :)
