### ISSUE TITLE
Self Signed SSL Certificate gives error on PouchDB sync despite adding options to avoid that

### ISSUE THREAD

**Issue by web-snake** [pouchdb/pouchdb#5980]
### Issue
Self Signed SSL Certificate gives error on PouchDB sync despite adding options to avoid that

### Info
- Environment: Ionic 2
    Cordova CLI: 6.3.1
    Ionic Framework Version: 2.0.0-rc.1
    Ionic CLI Version: 2.1.4
    Ionic App Lib Version: 2.1.2
    Ionic App Scripts Version: 0.0.36
    ios-deploy version: 1.9.0
    ios-sim version: 5.0.9
OS: Mac OS X Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

- Platform: Chrome
- Adapter: WebSQL
- Server: CouchDB

### Reproduce
I have a CouchDB hosted on my server with a self signed certificate,
I've confirmed at https://www.digicert.com/help/ that the SSL certificate checks out in every way except that it is unauthorized, i.e. self signed.
I see here that PouchDB has a way to allow self signed certs to work:
https://github.com/pouchdb/pouchdb/issues/3504
But the solution mentioned there doesn't work in my case when trying to sync a DB from Couch to Pouch when I'm using ionic serve using Chrome ...
I get the following error:

> OPTIONS https://{my_ip_address}:6984/{my_db}/ net::ERR_INSECURE_RESPONSE

I also get a similar error when using Safari with ionic serve:

> Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “{my_ip_address}” which could put your confidential information at risk.

I can confirm that the PouchDB sync works fine when syncing with a Cloudant DB by just changing the URI and I can confirm that my CouchDB on my server seems healthy when interacting with curl ( using -k ) and when using Futon ( after ignoring the warning about a self signed cert )

My code looks like this:

`this._db = new PouchDB('my_db', { adapter: 'websql' });

this._remote_db = new PouchDB("https://{username}:{password}@{my_ip_address}:6984/{my_db}",{
  ajax: {
      rejectUnauthorized: false,
      requestCert: true,
      agent: false
}});

this._db.sync(self._remote_db,{
  ajax: {
      rejectUnauthorized: false,
      requestCert: true,
      agent: false
  }});`

**Comment by willholley** [comment]
I think the workaround in #3504 only applies to nodejs - for Ionic/Chrome you'd need a different solution, not specific to PouchDB. Perhaps try the workaround suggested [here](http://stackoverflow.com/questions/34780045/on-ios-in-ionic-hybrid-app-how-to-bypass-certificate-check-using-self-signed)?

**Comment by web-snake** [comment]
OK, great, thanks
