### ISSUE TITLE
db.put() - Transaction timed out due to inactivity during 

### ISSUE THREAD

**Issue by CentricStraaten** [pouchdb/pouchdb#5983]
### Issue
I have a queue with multi db.put() commands. After a while i receive a transaction timed out message which causes a close on the indexdb. The remaining db.put() commands in de queue fail because of this. How do i avoid a time out?

**Comment by nolanlawson** [comment]
Sorry, I'm not sure I understand what the issue is. Can you provide some sample code or ideally a full project to reproduce the issue? What do you mean by "a time out"?

**Comment by CentricStraaten** [comment]
I have a worker that handles data. I use output.notify(result) in the worker to send the result to the function calling the worker. Then i want to write this data to the indexDB using PouchDB. When the worker is ready, not all changes are submitted to the database. I receive a time-out. I could solve this problem when i could use PouchDB in the worker. But that`s not possible?

`(function () {
    'use strict';

    angular
    .module('app.services')
    .factory('syncFactory', ['$window', '$q', '$log', 'WorkerService', 'pouchDB', 'offline', 'queueFactory', 'settingFactory', '$http', function ($window, $q, $log, WorkerService, pouchDB, offline, queueFactory, settingFactory, $http) {
        var service = {
            sync: sync,
            closeDatabases: closeDatabases,
            submitQueue: submitQueue
        };

        var baseUrl = window.location.protocol + "//"
            + window.location.hostname
            + (window.location.port ? ':' + window.location.port : '');

        var databases = [];
        var syncDatabases = ["allocation",
                        "assemblyline",
                        "assemblysection",
                        "customerlocation",
                        "contract",
                        "document",
                        "equipment",
                        "employee",
                        "equipmentpartused",
                        "installedequipmentpart",
                        "installedequipmentmodel",
                        "region",
                        "sparepart",
                        "sparepartsmodule",
                        "jobcard",
                        "jobcarditem",
                        "jobcardplanning",
                        "jobcardtimesheet",
                        "regionequipmentmodel",
                        "regionequipmentmodelpart",
                        "regionequipmentpart"];
        var syncWorkerPromise = null;

        var workerContext = {
            baseUrl: baseUrl,
            databases: databases,
            syncDatabases: syncDatabases
        };

        init();

        return service;

        function init() {
            syncWorkerPromise = WorkerService.createAngularWorker(['input', 'output', '$log', '$http', '$window', function (input, output, $log, $http, $window) {
                output.notify(0);
                var fetchSize = 250;
                var counter = 0;
                var updateActions = new Array();
                var host = $window.location.origin;

                //Fix (blob)url for EDGE/IE, IE does not support blob URL's
                if (host === 'blob://' ||  !host) {
                    host = input.baseUrl;
                }

                importScripts(host + '/scripts/deemas/models/LiveEntity.js');

                var addUpdateAction = function (apiName) {
                    updateActions[updateActions.length] = function () {
                        var deferred = eval('$q').defer();
                        var runUpdate = function (sinceid) {
                            $http.get(host + '/api/' + apiName + '?sinceId=' + sinceid + "&count=" + fetchSize, {
                                responseType: "json"
                            }).then(function (response) {
                                var responseData = response.data;
                                if (!responseData || !responseData.length) {
                                    deferred.reject();
                                    return;
                                } 
                                for (var i = 0; i < responseData.length; i++) {
                                    var result = new Deemas.Models.LiveEntity(apiName, responseData[i]);

                                    // todo place update - insert here!

                                    console.log(counter++);

                                    output.notify(result); 
                                }
                                if (responseData.length < fetchSize) {
                                    deferred.resolve();
                                } else {
                                    runUpdate(responseData[responseData.length - 1].Id);
                                }
                            }, function (reason) {
                                console.log("reason", reason);
                                deferred.reject();
                            });
                        };
                        runUpdate(0);
                        return deferred.promise;
                    };
                };

                angular.forEach(input.syncDatabases, function (value, index) {
                    addUpdateAction(value);
                });

                var update = function (i) {
                    if (i < updateActions.length) {
                        // run update action
                        updateActions[i]().finally(function () {
                            // update progress
                            output.notify((i + 1) / updateActions.length * 100);
                            i++;
                            // next update action
                            update(i);
                        });
                    } else {
                        output.resolve();
                    }
                };

                update(0);
            }]);
        }

        function submitQueue() {
            queueFactory.submit().then(function () {
                console.log("submitted all offline changes");
            });
        }

        function closeDatabase(name) {
            databases[name] = pouchDB('Deemas.' + name, {
                //adapter: 'worker',
                auto_compaction: true,
                revs_limit: 3
            });

            return databases[name].close().catch(function (err) {
                $log.error("closeDatabase ", err);
            });
        }

        function closeDatabases() {
            var promises = [];
            angular.forEach(syncDatabases, function (value, index) {
                promises.push(closeDatabase(value));
            });
            console.log('databases closed');
            return $q.all(promises);
        }

        function abortTransactions() {
            $q.reject();
            console.log('cancelled previous transactions');
        }

        function sync() {
            abortTransactions();

            var deferred = $q.defer();

            queueFactory.submit().then(function () {
                    syncWorkerPromise.then(
                        function success(angularWorker) {
                            return angularWorker.run(workerContext);
                        },
                        function error(reason) {
                            $log.error('syncWorkerPromise' + reason);
                            deferred.reject(reason);
                        }
                    ).then(
                        function success() {
                            deferred.resolve();
                        },
                        function error(reason) {
                            $log.error('syncWorkerPromise' + reason);
                            deferred.reject(reason);
                        },
                        function notify(result) {
                            if (!isNaN(result)) {
                                deferred.notify(result);
                            }
                            else {
                                databases[result.apiName] = pouchDB('Deemas.' + result.apiName, {
                                    //adapter: 'worker',
                                    auto_compaction: true,
                                    revs_limit: 3
                                });

                                //select database
                                var database = databases[result.apiName];

                                //set index
                                result.data._id = "" + result.data.Id;

                                if (result.apiName === "document") {
                                    $http({
                                        method: 'GET',
                                        url: '/api/document/' + result.data.Id
                                    }).then(function (response) {
                                        result.data.Data = response.data;
                                        database.get(result.data._id)
                                        .then(function (currentItem) {
                                                result.data._rev = currentItem._rev;
                                                if (result.data.DateModified > currentItem.DateModified || (result.data.DateModified != null && currentItem.DateModified == null)) {
                                                    database.put(result.data)
                                                        .then(function () { deferred.notify('success'); })
                                                        .catch(function (err) {
                                                            $log.log(err);
                                                            deferred.reject('error');
                                                        }
                                                    );
                                                }
                                        });
                                    }).catch(function (err) {
                                        $log.log(err);
                                        deferred.reject('error');
                                    });

                                } else //synchronize Record
                                {
                                    database.get(result.data._id).then(
                                        function (currentItem) {
                                            //set revision
                                            result.data._rev = currentItem._rev;

                                            if (result.data.DateModified > currentItem.DateModified || (result.data.DateModified != null && currentItem.DateModified == null)) {
                                                database.put(result.data)
                                                    .then(function () { deferred.notify('success'); })
                                                    .catch(function (err) {
                                                        $log.log(err);
                                                        deferred.reject('error');
                                                    });
                                            }
                                            else {
                                                deferred.notify('success');
                                            }
                                        }
                                    ).catch(function (reason) {
                                        database.put(result.data)
                                            .then(function () { deferred.notify('success'); })
                                            .catch(function (err) {
                                                $log.log(err);
                                                deferred.reject('error');
                                            });
                                    });
                                }
                            }
                        });
            }).catch(function (err) {
                $log.error('queueFactory: ' + err);
                deferred.reject('error');
            });

            return deferred.promise;
        }
    }]);
})();`

**Comment by CentricStraaten** [comment]
I receive the following error message

> 869 Uncaught DOMException: Failed to execute 'index' on 'IDBObjectStore': The transaction has finished.

**Comment by nolanlawson** [comment]
Hi, thank you for the additional info, but could you please provide additional information:

* **Browser/OS** where you see this issue
* **a live test case to reproduce or small sample app.** pasting code into GitHub is a lot of work for maintainers because we have to copy-paste it into a real site/app. I've moved your code to a gist.

**Comment by CentricStraaten** [comment]
Hi, I already solved my issue by refactoring the script. Thx anyway

**Comment by amagyar** [comment]
@CentricStraaten I'm having TimeoutError, how did you fixed it? Thanks

**Comment by hdoedens** [comment]
Hi, I also encoutered the timeout after a few minutes of constant `db.put()` requests. And sometimes only this error: 
```
pouchdb.js:2939 Database has a global failure DOMException: Transaction timed out due to inactivity.
```
I switched to a CouchDB instance and then I get the following error after a minute or so:
```
PUT http://localhost:5984/liedbase/BGT_hebreeen_4_14 net::ERR_INSUFFICIENT_RESOURCES pouchdb.js:9743
```
I suspect that Chrome is trying to generate too many request at parallel. 

Background: I am building an electron app with CouchDB and I am trying to load a bit over 20.000 documents from txt files into the database (txt files are 4,4MB altogehter)

**Comment by hdoedens** [comment]
This is my code (simplified but working). When I add some `console.log` statements, I can see that all books are read into memory, but not single db call has been made. When I delete some files to read, all files are read into memory as well, but then the program starts to load them into the database.
```
require('node-dir').files(__dirname, function(err, files) {
    for(pi=0; pi<files.length; pi++) {
        path = files[pi]
        console.log('processing: ' + path)
        if(path.indexOf('bible') > -1) {
            var pathparts = path.split(pathlib.sep)
            var book = pathparts[pathparts.length - 1].substring(0, pathparts[pathparts.length - 1].indexOf('.'))
            var data = fs.readFileSync(path, 'utf8');
            var lines = data.split(/\r?\n/g)
            for(var i=0; i<lines.length; i++) {
                var line = lines[i];
                lineparts = line.split(/(\d+)(?=[a-zA-Z])/)
                for(var p=2; p<lineparts.length; p+=2) {
                    dbFactory.post({
                        "book": book,
                        "verse": parseInt(lineparts[p-1]),
                        "text": lineparts[p]
                    });
                }
            
            }
        }
    }
});
```

**Comment by eboily** [comment]
Also encountered this issue on Chrome 58 (but not on Safari) after a few minutes of constant `db.put()` requests. Is there a way to increase the timeout delay?
