### ISSUE TITLE
Event handlers are not being removed after unsuccessful replications

### ISSUE THREAD

**Issue by DanielMaly** [pouchdb/pouchdb#6004]
### Issue
I'm getting a `(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.` when performing a lot of unsuccessful replications with a remote database one after another. I'm using retry:false, as I need to be able to control the attempts manually through my code but I wait for a replication to fail or timeout before starting a new one. Unsuccessful replications are a common scenario if my user is not connected to the internet.

One issue seems to be that a replication creates an 'onDestroyed' handler in `Replication.prototype.ready` that it doesn't remove if it doesn't complete successfully. Another such handler is being created in `AbstractPouchDB.changes`, although I'm not sure whether it's part of the cause or just a trigger for the warning.

### Info
- Environment: React Native but in theory it should be environment independent.
- Platform: iOS/Android
- Adapter: Any
- Server: CouchDB

### Reproduce
Attempt to sync a database with a non-existent or non-running endpoint several times in succession waiting for each replication to fail before launching a new one.

**Comment by nolanlawson** [comment]
By any chance do you have a code snippet that can reproduce this problem? Feel free to write one using `pouchdb-adapter-memory` since it shouldn't matter what the underlying adapter is.

In the past we have had lots of memory leaks related to event emitters + sync and I wouldn't be surprised to find a few more.  Some examples of tests we've written to check for leaks are [in this file](https://github.com/pouchdb/pouchdb/blob/9abef3a162f9a117497aaca9c3273d20cf7bb23c/tests/integration/test.events.js), but perhaps there is some combination of options that is not covering the particular issue you're running into. Either way, it'd be really helpful if we could reproduce this! :)

**Comment by DanielMaly** [comment]
Reproduced in 6.1.0:

`var PouchDB = require('pouchdb');

PouchDB.plugin(require('pouchdb-adapter-memory'));
var localDB = new PouchDB('myDB', {adapter: 'memory'});
var remoteDB = new PouchDB('http://nonexistent.com');

setInterval(function() {
	console.log('Attempting sync');
	PouchDB.sync(localDB, remoteDB, {
		batch_size: 150,
		retry: false,
		timeout: 1000
	})
}, 3000);`

**Comment by DanielMaly** [comment]
Were you able to reproduce this on your end?

**Comment by nolanlawson** [comment]
I can reproduce, thanks. Here is [a live repro](http://bl.ocks.org/nolanlawson/raw/f7621f20296ae1fc996a74f61e433fb6/) and [a gist](https://gist.github.com/nolanlawson/f7621f20296ae1fc996a74f61e433fb6)

**Comment by DanielMaly** [comment]
Any progress on this? The warnings are extremely annoying in my particular environment (React Native shows a huge red screen) and I've had to resort to overriding console.error to get rid of them. I believe this is a simple fix for someone who knows the inner workings of Pouch.

**Comment by nolanlawson** [comment]
Sorry, I've been working on other stuff. This issue is welcome to anyone who would like to submit a PR. 🙂

**Comment by alxndrsn** [comment]
I still see `(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.` using the gist at https://gist.github.com/nolanlawson/f7621f20296ae1fc996a74f61e433fb6 with PouchDB version bumped to `6.4.3`.
