### ISSUE TITLE
Replace js-extend with Object.assign (with polyfill)

### ISSUE THREAD

**Issue by andrew-aladev** [pouchdb/pouchdb#6012]
Hello. We are trying to use [forever agent](https://github.com/thaliproject/forever-agent/blob/master/index.js) as an option for `ajaxCore -> request.js`. `js-extend` tries to make a deep copy of this agent. Sometimes it is possible, but sometimes it creates a recursion overflow, because existing `freeSocket` is a circular object.

I am sure that we should not use deep copy of `request.js` options. `http.Agent` is just an simple example.

I've replaced `packages/node_modules/pouchdb-utils/src/jsExtend.js` with [`Object.assign`](https://github.com/sindresorhus/object-assign/blob/master/index.js) and `npm run test-node` passed.

I see failed unit tests: `Test two levels merging`, `Test multilevel merging`, `Test if non object argument raises exception`. I've tried to find a reason for these tests but I failed. It looks like all `extend` calls does not require multilevel merging and non object exception.

Can you replace `js-extend` with `object-assign`?

**Comment by nolanlawson** [comment]
Can you provide a failing test case so we can understand what's failing about jsExtend? And yes, we are interested in removing our polyfills, so replacing jsExtend with Object.assign isn't out of the question.

**Comment by andrew-aladev** [comment]
```
var jsExtend = require('js-extend');

var circular = {};
circular.circular = circular;

var defaults = { a: null };
var options  = { a: circular };
console.log(Object.assign({}, defaults, options));
console.log(jsExtend.extend({}, defaults, options));

defaults = { a: circular };
console.log(Object.assign({}, defaults, options));
console.log(jsExtend.extend({}, defaults, options));
```

>{ a: { circular: [Circular] } }
{ a: { circular: [Circular] } }
{ a: { circular: [Circular] } }
Maximum call stack size exceeded

Please look [here](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-http/src/index.js#L171).

`var reqOpts = extend(clone(ajaxOpts), userOpts.ajax, options);`

We are passing our custom agent as an `ajax` option. But `ajaxOpts` already has another agent. If both agents are circular - it will create a hang and resursion overflow. This exception appears randomly because both http agents can be circular or not circular depends on it's usage. But pouchdb shouldn't ever try to merge these objects.

Please look at these options `ajaxOpts`, `userOpts.ajax` once again. They don't want to be merged with deep copy. They wants just `Object.assign`. I can see that all pouchdb project don't need a deep copy. I think all `extend` calls can be replaced with `Object.assign`.

**Comment by nolanlawson** [comment]
Thanks, I agree we can probably replace jsExtend with an Object.assign+polyfill. I think we are only ever using it for the shallow copy, not the deep copy.

**Comment by andrew-aladev** [comment]
Thank you. It works good.

**Comment by willholley** [comment]
It turns out we need deep copy/merge for the request headers, but perhaps we can treat this as a special case.
