### ISSUE TITLE
rocksdb adapter?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#6032]
http://rocksdb.org based on LevelUp.

**Comment by nolanlawson** [comment]
Yep, any *down adapter can be used as a PouchDB adapter; you would just need to author something like this: https://github.com/pouchdb/pouchdb/blob/3e6df5d4e989fafd2c581b4de597da2437273234/packages/node_modules/pouchdb-adapter-memory/src/index.js (replace memdown with rocksdb)

The `db` interface is not documented but fairly stable by now.

**Comment by nolanlawson** [comment]
Closing because this is not something we intend to support as first-class but can be solved in userland
