### ISSUE TITLE
Cannot read _rev of undefined

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#6035]
```js
/Users/ronagy/Projects/github/nxtedition/nxt-deepstream/node_modules/pouchdb-node/lib/index.js:1510
  var changeList = [{rev: doc._rev}];
                             ^

TypeError: Cannot read property '_rev' of undefined
    at Object.processChange (/Users/ronagy/Projects/github/nxtedition/nxt-deepstream/node_modules/pouchdb-node/lib/index.js:1510:30)
    at onGetWinningDoc (/Users/ronagy/Projects/github/nxtedition/nxt-deepstream/node_modules/pouchdb-node/lib/index.js:4668:29)
    at /Users/ronagy/Projects/github/nxtedition/nxt-deepstream/node_modules/pouchdb-node/lib/index.js:4712:11
    at /Users/ronagy/Projects/github/nxtedition/nxt-deepstream/node_modules/pouchdb-node/lib/index.js:3037:9
    at /Users/ronagy/Projects/github/nxtedition/nxt-deepstream/node_modules/pouchdb-node/lib/index.js:2868:13
```

Not sure where this error originates from?

**Comment by ronag** [comment]
I think this happened after I did a `bulkDocs` with `new_edits: false` with docs that didn't have a `_rev`.

**Comment by willholley** [comment]
ok, so maybe we need to protect against that - it shouldn't be possible to insert documents with a `_rev`

**Comment by nolanlawson** [comment]
Can you provide a full repro? It should not be possible to have documents with undefined `_rev` in this case.

**Comment by drunksaint** [comment]
Hi, we have encountered this issue almost 50-60 times. How we handle it currently is that we delete the pouchdb and re-replicate from remote couchdb.

**Comment by daleharvey** [comment]
Will need to have some more information + steps to reproduce to be able to do anything here

**Comment by julianhille** [comment]
Might be the same as: https://github.com/pouchdb/pouchdb/issues/4518 i added there a script which easily reproduces it here.
