### ISSUE TITLE
ReactNative SQLite error: UNIQUE constraint failed: attach-store.digest

### ISSUE THREAD

**Issue by noradaiko** [pouchdb/pouchdb#6037]
Hi, thanks for making such a great library!
I'd like to post an issue regarding `pouchdb-adapter-websql-core`.

### Issue
Can't store multiple documents with same attachment data.
The replication process retrieves docs from `_changes` feed so multiple attachments are potentially saved at once.
If these have same md5 digest, it will produce an error: `UNIQUE constraint failed: attach-store.digest`.
Seems like `saveAttachment` is ignoring existing attachment but not working in this case:
https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-websql-core/src/bulkDocs.js#L302

I guess the reason is that attachments are stored in `forEach` loop where each process doesn't wait for storing the previous attachment:
https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-websql-core/src/bulkDocs.js#L212

### Info
- Environment: ReactNative
- Platform: iOS
- Adapter: SQLite Adapter for ReactNative (It's my module)
- Server: CouchDB

### Reproduce
Sync with multiple attachments with same md5digest.
I encountered this problem while making a SQLite adapter for ReactNative.

**Comment by nolanlawson** [comment]
My suspicion is that this is related to the ReactNative SQLite adapter and not PouchDB. The reason I suggest that is that we have run our full test suite using:

- [node-websql](https://github.com/nolanlawson/node-websql)
- WebSQL on Chrome and Safari
- [cordova-plugin-sqlite-2](https://github.com/nolanlawson/cordova-plugin-sqlite-2)

However [react-native-sqlite-storage](https://github.com/andpor/react-native-sqlite-storage) is based on [Cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage) which in my experience has had many bugs and has often failed our test suite (it's largely why I wrote cordova-plugin-sqlite-2).

Could you please run your same test in another SQL-esque implementation (WebSQL, node-websql, cordova-plugin-sqlite-2) and see if the issue persists? If not, then I would guess it's related to react-native-sqlite-storage.

Alternatively, if you can find a test that fails in regular WebSQL, then please provide that test and we will fix it in `pouchdb-adapter-websql-core` asap. :) You may also be interested to see our existing [attachment replication tests here](https://github.com/pouchdb/pouchdb/blob/587ba8f4df4b6fcf32a8fd015f8c7ebadd8f280d/tests/integration/test.attachments.js#L3262).

**Comment by noradaiko** [comment]
I made another SQLite module for react native which code base is borrowed from your [cordova-plugin-sqlite-2](https://github.com/nolanlawson/cordova-plugin-sqlite-2).
It works pretty well!
https://github.com/noradaiko/react-native-sqlite-2

Thanks

**Comment by nolanlawson** [comment]
Hey, that's awesome! I was hoping it would be useful to extend and use in
other environments. :)

-----
Nolan Lawson
http://nolanlawson.com
https://github.com/nolanlawson

**Comment by nolanlawson** [comment]
I added a mention of your project to the [node-websql readme](https://github.com/nolanlawson/node-websql).

By the way, do you still consider it "unstable for storing PouchDB's attachments" (as you say in the readme?). I've run PouchDB's attachment test suite against node-websql and cordova-plugin-sqlite-2 (both Android and iOS) and it passes, so it may be something wrong with the React Native bindings?

**Comment by noradaiko** [comment]
I'm glad!

I mean that it's unstable with `react-native-sqlite-storage`.
I've tested storing attachments with `react-native-sqlite-2` and `UNIQUE constraint` error didn't occur.
The difference from cordova-plugin-sqlite-2 is only bridging between JS and native.
There's also a little patch for avoiding Android's problem truncating string including `\u0000`.
I'd like to run the test suite but I have to learn testing RN.
