### ISSUE TITLE
PouchDB nightly builds stopped on December 18th

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6038]
The build server may be stuck: http://pouchtest.com/nightly/index.html

**Comment by nolanlawson** [comment]
fixed now

**Comment by k-j-kleist** [comment]
The domain "pouchtest.com" seems to have been grabbed by namecheap.com

Maybe the wiki page "https://github.com/pouchdb/pouchdb/wiki/PouchDB-nightly-build" should be updated/deleted?
