### ISSUE TITLE
Include id with bulkDocs() results even in case of conflicts?

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6039]
I'm not sure if this matches the CouchDB behavior or not, but [Ben Nadel lays out a pretty good case](https://www.bennadel.com/blog/3200-retrying-bulk-updates-in-pouchdb-using-a-recursive-promise-chain.htm) for why it's annoying that the response to `bulkDocs()` doesn't include the original ID for conflicted documents. You essentially have to keep track of the request as well as the response object, which is a lot of bookkeeping.

If we were to implement this, and if CouchDB didn't support it, then we'd have to do the bookkeeping ourselves, but it may be worth it. Unless folks feel this is fine being solved in plugin-land.

**Comment by willholley** [comment]
I'm pretty sure CouchDB [does return id alongside errors](http://docs.couchdb.org/en/2.0.0/api/database/bulk-api.html#bulk-documents-transaction-semantics) so hopefully this is straightforward.

**Comment by nolanlawson** [comment]
@willholley Yep it does, the new test confirms same behavior between Couch and Pouch modulo some weirdo subtle differences that we may want to fix (e.g. `ok: true` even for errors, `error: "conflict"` instead of `error: true`).
