### ISSUE TITLE
Website: Precache documentation / guides

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6049]
Currently our website uses _both_ Service Worker and AppCache, which is kind of silly. Furthermore, the service worker works as a "try network, then cache" mode which means that it doesn't fullfill the same function as Service Worker because it doesn't cache the whole site offline.

I would recommend either removing App Cache entirely or making it a fallback. We can use something like [appcache-nanny](https://github.com/gr2m/appcache-nanny) to provide programmatic access to appcache (under the hood, it works by creating an iframe) and then removing the appcache reference from `index.html`. We could also use something like [sw-toolbox](https://github.com/GoogleChrome/sw-toolbox) to simplify our current approach; I would like us to just pre-cache all content except maybe for images.

**Comment by nickcolley** [comment]
I think we changed the Service Worker to that behaviour because caching the whole site was unreasonable for the amount of pages we have, but maybe the file size is not too big.

Just thinking about people's data plans etc.

**Comment by ig3** [comment]
My understanding was that if both AppCache and ServiceWorker were used and a browser supported both then AppCache would be ignored. Is this not the case generally?

From [Using Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers):
> if you use AppCache and SW on a page, browsers that don’t support SW but do support AppCache will use that, and browsers that support both will ignore the AppCache and let SW take over.

**Comment by daleharvey** [comment]
Yup I tested that when the patch landed, appcache is being used as a fallback right now, they arent both being done at the same time. 

Nick and I discussed the change in behaviour of prefetching vs caching when this landed, I think we could do with prefetching a few more things, the API and the mostly static docs and maybe just the first 5 blog posts?

**Comment by nolanlawson** [comment]
> Yup I tested that when the patch landed, appcache is being used as a fallback right now, they arent both being done at the same time.

My bad! Yeah I'm fine with increasing the precached docs or even just keeping it the same. I thought it was a mistake.

**Comment by daleharvey** [comment]
I can see the API docs and the Guides especially being useful precached, I often open a tab for a tutorial before say getting on a train and going through it but we dont need to gather every blog post ever written and we probably need to change the logic so that if a guide page does fail to download it doesnt invalidate the entire service worker
