### ISSUE TITLE
Firefox IDB data corruption: InvalidStateError

### ISSUE THREAD

**Issue by ig3** [pouchdb/pouchdb#6050]
### Issue
Opening PouchDB database in the browser fails with InvalidStateError from the indexedDB.open call in the following, within function init 

```
  var req;
  if (opts.storage) {
    req = tryStorageOption(dbName, opts.storage);
  } else {
    req = indexedDB.open(dbName, ADAPTER_VERSION);
  }

```

### Info
- Environment: browser (Firefox)
- Platform: Firefox on Windows
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
I don't know what caused the invalid state. On the one client where it occurs, it occurs each time the page/app loads.

I would like to implement a recovery from the invalid state but don't have much information at this point, nor access to the failing client.

I would like to be able to reset the database. The PouchDB API provides db.destroy() but this depends on having successfully opened the database and opening the database is failing due to the InvalidStateError.

Deleting the set of IndexedDB databases created by PouchDB using browser features is problematic for business users. Interfaces for deleting the databases are browser specific and non-trivial.

Are there suggestions for how to recover from this state?

**Comment by nolanlawson** [comment]
I admit I've seen this happen in Firefox before (it's happening in Firefox on my own machine, lol) and seems to be a bug in Firefox's implementation for which there's no workaround except to blow away all data for that website.

Other than that I'm not sure how to proceed with this. If you can get the user to provide their Firefox user data (e.g. on mac it's under `~/Library/Application\ Support/Firefox/Profiles/<profile>.default/storage/default/<site name>` then you could provide that to Mozilla in a bug report.

**Comment by nolanlawson** [comment]
I note that on my own machine I'm getting `NotFoundError: The operation failed because the requested database object could not be found. For example, an object store did not exist but was being opened` which seems different from your error.

**Comment by ig3** [comment]
Thanks Nolan. I'm planning to try indexedDB.deleteDatabase. I think PouchDB used to have a function to delete a database without having an open database handle. Is there still something there? I would prefer to use a PouchDB function that would work regardless of the database type.

Do you know if I can copy the user's database to my development system somehow? Not something I have tried but I would be interested to see what state it's in.

**Comment by nolanlawson** [comment]
The only way to do so is to ask the user to copy the files from their file system and send them to you. There's no method anymore to delete a database without a `PouchDB` handle but you can do a manual `deleteDatabase` if you are confident it won't interfere with any Pouch code.

**Comment by BrunoDeBarros** [comment]
I've just come across this; seems like it's just Firefox in Private Browsing mode. It doesn't let IndexedDB load, it throws an InvalidStateError.

@ig3 Is it possible that that's what your user was doing?

**Comment by chaseadam** [comment]
> I admit I've seen this happen in Firefox before (it's happening in Firefox on my own machine, lol) and seems to be a bug in Firefox's implementation for which there's no workaround except to blow away all data for that website.

It seems if any of the indexed DBs are corrupted, firefox will fail to continue to load other indexed DBs. I had to clear out the whole storage directory.

**Comment by DannyHinshaw** [comment]
In case anyone finds this while writing a firefox extension. The solution for me was to only allow pouchdb calls from background.js
