### ISSUE TITLE
Q: Listener / Event for conflicts

### ISSUE THREAD

**Issue by t-knapp** [pouchdb/pouchdb#6054]
### Question
Is there a possibility in PouchDB to listen for some conflicts coming up after sync with one or more CouchDB Server? I saw, that some events 'change', 'active', etc. were fired if some sync related actions begin/end. 

Before I implement some polling stuff for detection of conflicts, I'll rather ask here. Another solution could be listening to 'change' events and analyse the contained changed documents.

Thanks and kind regards
Tobias

**Comment by nolanlawson** [comment]
> Another solution could be listening to 'change' events and analyse the contained changed documents.

I believe this is the only option; I'm not aware of a CouchDB API to only listen for changes.

**Comment by t-knapp** [comment]
I wrote some code in the onChange listener method for detection of confilicts. This works. Thank you.

**Comment by cdroulers** [comment]
@t-knapp What did your conflict detection code end up looking like?
