### ISSUE TITLE
doMigrationOne requires leveldown directly

### ISSUE THREAD

**Issue by andrew-aladev** [pouchdb/pouchdb#6065]
Our application can use `leveldown` or `leveldown-mobile`. But `pouchdb-adapter-leveldb/src/migrate.js` is going to require `leveldown` directly.

In `pouchdb-adapter-leveldb/src/index.js` we have a guard that makes us sure that `leveldown` exist:

```
var leveldown = opts.db;
if (!leveldown) {
  leveldown = requireLeveldown();
  if (leveldown instanceof Error) {
    return callback(leveldown);
  }
}
var _opts = assign({
  db: leveldown,
  migrate: migrate
}, opts);
```

In `pouchdb-adapter-leveldb-core/src/index` we are going to call `opts.migrate.doMigrationOne(name, db, afterDBCreated);` and this call with require `leveldown` directly. But we still have a valid `leveldown` in `opts.db`.

**Comment by nolanlawson** [comment]
For a new application, do you need the migration logic? That migration logic is in place essentially for code written before 2014 or so (iirc).

If you'd like to use `leveldown-mobile` as an adapter, you can create a custom adapter using `pouchdb-adapter-leveldb-core` and specify that it doesn't run the migration code by not passing in `migrate`. Here are some examples:

* [pouchdb-adapter-memory](https://github.com/pouchdb/pouchdb/blob/f6f7acf3108b267f8410a6f70ef1575363efd4d4/packages/node_modules/pouchdb-adapter-memory/src/index.js)
* [custom adapter in pouchdb-server](https://github.com/pouchdb/pouchdb-server/blob/3ae11d838108e5d898ee51ad7f2bfe05b2fbdbbb/lib/customLevelAdapter.js)

**Comment by nolanlawson** [comment]
Also in the current version of the code, `migrate` lives in `pouchdb-adapter-leveldb` not `pouchdb-adapter-leveldb-core` so anything extending `pouchdb-adapter-leveldb-core` shouldn't have to worry about core.

**Comment by andrew-aladev** [comment]
Ok. We will implement custom adapter.

**Comment by yaronyg** [comment]
@nolanlawson We don't need the migration code but it is still a bummer that it does the wrong thing if one is using the db option to enable an alternate level down DB. But I suppose we are past due for creating leveldown-mobile-jxcore.

**Comment by nolanlawson** [comment]
@yaronyg if you depend on custom migration logic you can also pass in `opts.migrate`. if `opts.migrate` is falsy then it will ignore it.
