### ISSUE TITLE
in-database total_rows cache

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6068]
Once https://github.com/pouchdb/pouchdb/issues/6055 is fixed, we can replace the previous in-memory optimization with a proper in-database optimization that actually works across threads.

**Comment by nolanlawson** [comment]
My current thinking is to just use the meta store and roughly use the same code add before but attaching the docCount to the database instead of in-memory

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/4a1b4e4b6ac7a46b306a7df6870b9e346ba2fea6
