### ISSUE TITLE
Clustered setup?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#6069]
Does PuchDB support clustering similar to CouchDB 2.0?

**Comment by willholley** [comment]
It doesn't support clustering in the same way but you could do CouchDB 1.x-style clustering with PouchDB servers behind a load balancer with bi-directional replication between databases. Out of curiosity, why not use CouchDB if you need a cluster?

**Comment by nolanlawson** [comment]
Closing, @willholley answered the question :)

**Comment by rjsteinert** [comment]
I've started to spec out some tests for a `pouchdb-cluster` API that is unopinionated about the network but is intended to work nicely with P2P APIs such as the upcoming [cordova-plugin-nearby-connections](https://github.com/Tangerine-Community/cordova-plugin-nearby-connections) plugin or maybe someday something like [hyperdiscovery](https://github.com/datproject/hyperdiscovery).

**Comment by rjsteinert** [comment]
Here's [the start](https://github.com/Tangerine-Community/pouchdb-cluster/blob/master/test/pouchdb-cluster_test.html#L53) of me noodling around with what the API usage might look like. I'll work on this a bit more before [Offline Camp in Grants Pass, Oregon this weekend](http://offlinefirst.org/camp/).
