### ISSUE TITLE
Replication issues

### ISSUE THREAD

**Issue by danielo515** [pouchdb/pouchdb#6081]
### Issue
This issue is not new, I have opened an [issue on stackoverflow](http://stackoverflow.com/questions/41131456/pouchdb-is-not-pushing-documents-on-desktop-but-pull-works) and also one [on the google boards](https://groups.google.com/forum/#!topic/pouchdb/CtUYsv2JDiE) which seems to be pretty dead.

**TLDR**; Syncrhonization was working before (versions prior to 5.4), and after an update the syncrhonization [of my project](https://noteself.github.io/online) stopped working. I can not say that synchronization does not work at all, because documents are being pulled from the remote DB, although they are not being pushed. The weird thing is that it is working on mobile browsers perfectly both ways (pull and push).
 
After some days of research I found some evidences about where the problems is, but I have no idea why. This is how I do it:

In order to start synchronization what my project does is `PouchDB.sync(localDB, remoteDB)` where localDB and remoteDB are PouchDB instances.
In one inspirational moment I opened the java-script console and I typed:  `localDB.sync(remoteDB)` and documents started flowing both ways. 
I reviewed the documentation and seems that `PouchDB.sync` accepts two strings, while the shortcut method accepts both a PouchDB object and a string. Documentation says that both methods are equivalent but seems that it is not true. 

### Info
- Environment: Browser
- Platform: Chrome/FF/Android
- Adapter: idb on the problematic browsers
- Server: Cloudant

### Reproduce

I'm using `PouchDB.sync(localDB,remoteDB)` instead of `localDB.sync(remoteDB)`, which causes documents to be pulled from the remote db but not being pushed.

**Comment by danielo515** [comment]
Surprisingly the synchronization fix survives between browser reloads, but it is something that has to be done per database, separately. So it looks to be some kind of persisted metadata about the database being synced.

**Comment by danielo515** [comment]
Ok, I found the actual problem.
I'm using a replication filter:

```js
$TPouch.database._db.sync(remoteDB, {
                    live: true,
                    retry: true,
                    filter: 'TiddlyPouch/tiddlers'
})
```

Which, should be this one (but now I'm not sure about anything)

```js
{
  "_id": "_design/TiddlyPouch",
  "_rev": "1-25057c99e40abff042e6bd1c28117844",
  "views": {
    "skinny-tiddlers": {
      "map": "function(doc){     A function not related with this}"
    }
  },
  "filters": {
    "tiddlers": "function(doc, req) {  return doc.hasOwnProperty('fields') }"
  }
}
```

I reviewed the documents on the DB, and all of them has a fields property. In fact, If I do the following in the console:

```js
$TPouch.database._db.get('AnoAnal').then((f) => console.log(f.hasOwnProperty('fields')))
// true
```

What's wrong with my filtered replication?

**Comment by willholley** [comment]
I can't see anything obviously wrong with the filter. How are you observing that no documents are being pushed to the server? Are there no `_bulk_docs` requests from PouchDB? It may be worth turning on debug logging in Pouch to see if that sheds any light on the problem.

**Comment by danielo515** [comment]
Hello @willholley, 
Thank you for your answer. 
The most obvious way to notice it is that documents from the server appear on my app, but not the other way around :smile:

Another way that I noticed is by some status flag that I have on my page. I have some function subscribed to the sync events (pause, completed, syncing...) that updates that flag. When I first open the app Y can see the status of syncing, wich fetches documents from the  server, then it goes to pause, and no matter how many new documents I add, it stays on pause state. 

I would love to activate the debug mode to see what could be happening. How can I do it?

**Comment by danielo515** [comment]
Hello @willholley, 
Thank you for your answer. 
The most obvious way to notice it is that documents from the server appear on my app, but not the other way around :smile:

Another way that I noticed is by some status flag that I have on my page. I have some function subscribed to the sync events (pause, completed, syncing...) that updates that flag. When I first open the app Y can see the status of syncing, wich fetches documents from the  server, then it goes to pause, and no matter how many new documents I add, it stays on pause state. 

I would love to activate the debug mode to see what could be happening. How can I do it?

**Comment by willholley** [comment]
@danielo515 if you're just comparing document state between the server and client, it's worth checking to see if the document is conflicted on the server (`GET` the document and pass `conflicts=true` as a query parameter). A common cause if perceived sync issues is when a document has been updated by multiple clients - for one of those clients the state on the server doesn't appear to change because a conflict is introduced when they sync. 

Regarding debug mode, https://pouchdb.com/api.html#debug_mode has the details.

**Comment by danielo515** [comment]
Dear @willholley , I have activated the debug mode succesfully, but I'm not sure about what to look for, everything seems to be normal.
Where do you suggest me to run de query including `conflicts=true` ? On the server or the client?

I just realized one weird behavior:
The purpose of the filter was to avoid index documents (AKA design documents with views) being synced to the server. When I ran synchronization manually on the console, all the documents, including the view which contains the filter where synchronized to the server. Now if I create a brand new PouchDB instance and point it to that same remote database (the one containing the filters) the synchronization issues do not happen. Mi guess is that having the documents that do not pass the filter already on the remote database prevents Pouch from trying to synchronize them , therefore the filter never triggers and that prevents the sync issues. Looks like the first time the filter stops a document from being replicated locks the upstream sync for all the docs. Does that make sense?

**Comment by danielo515** [comment]
I think I have found the problem.
Let me dig a bit and I will explain what I think the problem is.

**Comment by nolanlawson** [comment]
When you filter with `sync()` it actually applies the filter in both directions (server -> client, client -> server). Is that what you ran into?

**Comment by danielo515** [comment]
Dear @nolanlawson and @willholley , the sync issues were caused because the design document that was being used for filtering did not exist on the local database. It was hard to debug because:

- It was an old document and was being used before on the lcoal databases. Some databases kept an old copy of it and therefore they worked
- O the newer databases the document did not exist, but synchronization was happening on one-way, this confused me a lot. Is this normal?

I consider this issue resolved, so you can answer me my last question or not ( I will appreciate it if you do) but I will close it.

Thanks and regards

**Comment by willholley** [comment]
thanks @danielo515 - that makes sense and I'm sorry it took so long to get to the bottom of the problem. `sync` is just a wrapper around 2 independent replications to/from the remote database so if one fails, it doesn't stop the other.

However, both the scenarios you describe ([filter function doesn't exist](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/changes.js#L234), database doesn't exist) should cause Pouch to throw/raise an error. Can you confirm that is the case (if not, perhaps we need to improve test coverage around this)?

**Comment by danielo515** [comment]
Hello @willholley I never saw any error about the filter not existing on one of the databases. My setup was (simplified)

```js
local = new Pouchdb('myDb');
remote = new Pouchdb('https://user.cloudant.com')
remote.put( { the design document containing the filter, that does not pass the filter itself })
local.sync(remote, {live: true, retry:true, filter:'mydesigndoc/filtername'})
```

so the path is 
PouchDBLocal --> PouchDBRemote --> cloudant

Maybe the problem is that the design document exist on the PouchDB instance that points to the remote location, but not on the local one , so there is no error but neither sync in one of the ways. Does this make sense?

**Comment by willholley** [comment]
@danielo515 I think you'd need to explicitly listen to the error events as in the [example in the docs](https://pouchdb.com/api.html#sync).

**Comment by danielo515** [comment]
Dear @willholley , I do have a specific error event listener, but I never saw an error of that type. Maybe because I didn't put enough attention.
