### ISSUE TITLE
Data Overhead in Sync witch CouchDB

### ISSUE THREAD

**Issue by t-knapp** [pouchdb/pouchdb#6087]
### Issue
In CouchDB I have about 1.500 documents that take 300 KB of storage. I follow a strategy of composed documents for the sake of conflict prevention and easy conflict solving. This means that every attribute is a separate document and the applications logic merges these documents together for visualisation in UI etc. I know, that there is an overhead of data stored in the CouchDB for this decomposition, but for the sake of easy merge strategies, I can deal with it.

The main issue I'll report is that PouchDB Sync takes around 90 seconds and uses about 21 MB of XHRs for a initial sync with CouchDB.

Why does PouchDB generate that much overhead? I know, there are Revisions and Sequences to be exchanged between CouchDB and PouchDB but I was not aware of that much "overhead"-data.

### Info
- Environment: Browser, later Cordova Hybrid App
- Platform: Chrome on Windows 7
- Adapter: PouchDBs default
- Server: CouchDB 2.0.0 on Windows 7

### Reproduce
Clear application storage in Chrome and reload site.

Kind regards
Tobias

**Comment by nolanlawson** [comment]
Hm, I am surprised it would take that long to sync. Can you provide a Chrome trace? (Timeline -> Right click -> Save timeline data ). Typically for CouchDB 2.0.0 it should be using the new `_bulk_get` API and that should vastly cut down on the time.

Another option is to use [pouchdb-load](https://github.com/nolanlawson/pouchdb-load) but we're trying to make this plugin less and less necessary for first load, and for CouchDB 2.0.0 it shouldn't be necessary.

**Comment by t-knapp** [comment]
I attached the Chrome Timeline with captured Network Traffic. The file size is about 170 MB.
[TimelineRawData-20170103T083055-t-knapp-pouchdb-issue-6087.zip](https://github.com/pouchdb/pouchdb/files/681829/TimelineRawData-20170103T083055-t-knapp-pouchdb-issue-6087.zip)


I also attached two chunks of information provided by the CouchDB server I use.

`GET http://127.0.0.1:5984/attributebased`
```json
{
	"db_name": "attributebased",
	"update_seq": "1995-g1AAAAFfeJzLYWBg4MhgTmEQTM4vTc5ISXLIyU9OzMnILy7JAUoxJTIkyf___z8riYGBEZ-6JAUgmWQPU2qGT6kDSGk8SGnifnzqEkDq6mFGmuJRmscCJBkagBRQ9fysxLME1S6AqN2flfiEoNoDELX3wc5gJqj8AUQ50HdPswDjAXMB",
	"sizes": {
		"file": 18404932,
		"external": 306044,
		"active": 614414
	},
	"purge_seq": 0,
	"other": {
		"data_size": 306044
	},
	"doc_del_count": 150,
	"doc_count": 1456,
	"disk_size": 18404932,
	"disk_format_version": 6,
	"data_size": 614414,
	"compact_running": false,
	"instance_start_time": "0"
}
```

`GET http://127.0.0.1:5984/`
 ```json
{
	"couchdb": "Welcome",
	"version": "2.0.0",
	"vendor": {
		"name": "The Apache Software Foundation"
	}
}
```

And a screenshot of CouchDB Fauxton DB overview.
![couchdb-fauxton](https://cloud.githubusercontent.com/assets/6977154/21602109/f217c8ce-d190-11e6-8578-a3c147ad3800.png)

Kind regards
Tobias

**Comment by nolanlawson** [comment]
@t-knapp in your trace I'm seeing a `readMetadata()` call (`readMetadata @ /C:/Code/RescueWave-PouchDB/lib/pouchdb-6.1.0.js:6121) that takes 32 seconds. This is extremely slow; do you have a single document with lots and lots of changes/conflicts?

Also your trace doesn't include network data (did you tick the "network" box?) so it's hard to see where the data overhead is coming from. Can you take a re-trace?

**Comment by nolanlawson** [comment]
OK I see the stairstep pattern now. Can you try using `{batch_size: 500}` or `{batch_size: 1000}`? right now you're using the default of 100 whereas you may get better throughput using a larger batch size, if your documents are small.

**Comment by t-knapp** [comment]
@nolanlawson Thank you! Using `{batch_size: 1000}` boosts synchronisation speed by factor 10 (obviously b.c. 100 x 10 = 1000 :smile:). It also decreased the amount of data transmitted over the network. 

Synchronisation takes arround 10 seconds and produces around 4.4 MB of XHR/HTTP.

>  I'm seeing a readMetadata() call (readMetadata @ /C:/Code/RescueWave-PouchDB/lib/pouchdb-6.1.0.js:6121) that takes 32 seconds. This is extremely slow; do you have a single document with lots and lots of changes/conflicts?

No, I don't think I have a lot of conflicts. I have a few documents with resolved conflicts. The longest revision tree has revision count of 40.

I attached the Chrome Timeline with `{batch_size: 1000}` to complete the picture.
[TimelineRawData-20170104T082843-t-knapp-pouchdb-issue-6087-batch_size-1000.zip](https://github.com/pouchdb/pouchdb/files/684113/TimelineRawData-20170104T082843-t-knapp-pouchdb-issue-6087-batch_size-1000.zip)

Thank you!

**Comment by nolanlawson** [comment]
Awesome, glad to hear! Seems 10 seconds is fairly acceptable for such a large amount of date (1500 documents).
