### ISSUE TITLE
Cross domain error with webpack dev server react

### ISSUE THREAD

**Issue by DinakaranS** [pouchdb/pouchdb#6098]
Hi,

I am trying to use Pouchdb to sync my react web application to couchbase. But facing below isssue,

XMLHttpRequest cannot load http://xx.xx.xx.xx:4984/api/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access 

The couchbase server is present in AWS.

I have added header in my webpack but no luck.

header: {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'GET,OPTIONS,HEAD,PUT,POST,DELETE,PATCH',
            'Access-Control-Allow-Headers': 'origin, x-http-method-override, accept, content-type, authorization, x-pingother, if-match, if-modified-since, if-none-match, if-unmodified-since, x-requested-with',
            'Access-Control-Allow-Credentials': 'true'
        }
Changed other combination of headers also, but still getting the same error.

**Comment by KlausTrainer** [comment]
Hi @DinakaranS!

Looks like your problem is related to configuring CORS in Couchbase server. We don't provide support for Couchbase server here, though. That's why I'm closing the issue. Please feel free to create a new one if you experience any problem that's specific to PouchDB!
