### ISSUE TITLE
allDocs fol _local docs

### ISSUE THREAD

**Issue by gine** [pouchdb/pouchdb#6105]
Why do you not implement an option to permit to use allDocs for _local docs?

I have an _id on _local doc where a part is the _id of a normal doc. A normal doc can have more than one 
_local docs. I would like to get allDocs({_local:trye, startkey: 'foo', endkey: 'foo\uuuu'}) of a documents with only one query.

**Comment by KlausTrainer** [comment]
Hi @gine!

Local docs are mostly an internal API that's meant to be used for keeping track of replication state, and not much else. Beyond that, we probably don't want to promote (and support) that feature, as it would likely make things more complicated than needed. I do see that there are situations where it seems desirable to use local docs. However, in most (if not all) cases there are better ways to solve the problem.

**Comment by nolanlawson** [comment]
We don't support such a query and probably never will, unless CouchDB does. In the meantime you can use a "master" `_local` doc to track everything.

**Comment by gine** [comment]
Yep i did with it but this mean that pouchdb is not a library to abstract the browser storage. it make only a part of abstraction and then it make sync operation easy. 

Thanks anyway.

**Comment by ettorebevilacqua** [comment]
Hy, you can use another pouchDb for that job that is not sync but is used only for local storage like you need , in this use case , you can use that for storage bussines logic of application, of course like that you can use query that you have request, other advantage in separate db is you can clean more easly the dbs that you use. 

;)
