### ISSUE TITLE
Remove special-casing of http adapter

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6106]
Right now the HTTP adapter has a lot of funky custom behavior and is not truly a standalone adapter in the same way that idb/websql/leveldb are. We should audit our use of `db.type() === 'http'` and see if these can be abstracted out into a more generic API that adapters like worker-pouch/socket-pouch/webrtc-pouch could also take advantage of.

I also wonder if it's a good time to create a hook for the parsing of adapters, since the whole magical "if it starts with `http` then it's http" thing is also an instance of special-casing.

Related: #6104

**Comment by nolanlawson** [comment]
https://github.com/pouchdb/pouchdb/pull/6199 demonstrates that the adapter in `pouchdb-replication-stream` also needs this feature. Perhaps for now all three adapters should just return `http` for their type... :confused:

**Comment by nolanlawson** [comment]
Proposal:

- Remove `db.type()` entirely (in a major version release; let's be safe and consider it breaking)
- Add `db._remote`, which is a boolean that if `true` indicates that the adapter crosses some expensive boundary (http, web socket, worker boundary, etc.) and thus deserves some special treatment.

At this point, the three adapters in question (worker-pouch, socket-pouch, and pouchdb-replication-stream) can just add `._remote = true` and that will handle the rest.

**Comment by cellog** [comment]
FYI, PouchDB is throwing a db.type deprecation warning inside index-browser.js with latest stable pouchdb
