### ISSUE TITLE
emitter.setMaxListeners() cannot be set for levelChanges

### ISSUE THREAD

**Issue by NNemec** [pouchdb/pouchdb#6123]
### Issue
EventEmitter has maxListeners set to 10 by default. PouchDB.changes() creates a new listener on each call which can be used up to 10 times or extended by setMaxListeners. So far so good.

With LevelDB, however, all these external EventEmitters listen to the same global EventEmitter that is stored in an internal variable 'levelChanges' inside the LevelDB adaptor code and cannot be accessed from the outside.

Setting up more then 10 change watchers on the same PouchDB causes a warning to be created that can only be silenced by the global EventEmitter.defaultMaxListeners - which somehow defeats its purpose.

### Info
- Environment: Node.js
- Platform: OSX / Electron
- Adapter: LevelDB
- Server: none

### Reproduce
* create single PouchDB using LevelBD backend
* set up at least 11 change() eventemitters (Possibly with one listener each)
* see on console: "Warning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit"

**Comment by nolanlawson** [comment]
Seems like a true bug. We should have some way of allowing access to the LevelDB event emitter. I believe this applies to the IDB/WebSQL changes emitters too, BTW.

**Comment by explorigin** [comment]
I ran into this, this weekend.  I'm trying to use db.changes to keep certain ViewModels up-to-date.  Naturally this can lead to a lot of subscriptions to db.changes.

I'd be in favor of this running when having a debugging flag but it's pretty annoying in general.

**Comment by daleharvey** [comment]
You can `db.setMaxListeners()` @ https://pouchdb.com/errors.html#event_emitter_limit
