### ISSUE TITLE
Replication state error

### ISSUE THREAD

**Issue by mkazlauskas** [pouchdb/pouchdb#6126]
### Issue
![error](https://i.imgur.com/qjhE9ox.png)
![stacktrace](https://i.imgur.com/cI1vqE1.png)

### Info
- Environment: Browser, pouchdb v6.1.0
- Platform: Chrome
- Adapter: Whatever is default on Chrome
- Server: Replicates with CouchDB server
- Setup: Using [app-pouchdb](https://github.com/PolymerElements/app-pouchdb)

### Reproduce
No idea, seems to happen randomly. It seems to be a live replication issue. It attempts to retry indefinitely with the same error. Any ideas on why it might be happening at all?

**Comment by nolanlawson** [comment]
Hmm, I don't think I've ever seen this issue reported. Do you have a live repro to demonstrate by any chance?

**Comment by mkazlauskas** [comment]
Sorry, I don't know how to reproduce so can't make a demo. For me it seems pretty random.
