### ISSUE TITLE
Request: startkey/endkey options for 'changes'

### ISSUE THREAD

**Issue by NNemec** [pouchdb/pouchdb#6129]
### Issue
Batch fetching via 'allDocs' allows very efficient selection via startkey/endkey. Unfortunately, the 'changes' command does not support anything similar, so an explicit filter function or view is necessary.

Ideally, 'changes' should have identical filtering options as allDocs & query as far as these make sense.

**Comment by nolanlawson** [comment]
`opts.since` and `opts.limit` are the similar pattern for `changes()`. Unfortunately there is no equivalent of `endkey` however, but you can still paginate.
