### ISSUE TITLE
Request: keyprefix for query/allDocs/changes

### ISSUE THREAD

**Issue by NNemec** [pouchdb/pouchdb#6130]
### Issue
Probably the most common way to structure IDs for efficient querying is by a hiearchy, in which case, many queries will be for IDs that start on a certain prefix. Specifying this by startkey/endkey requires an awkward '/xFFFF' at the end of the endkey argument. Even worse: internally, each filtering operation requires two string comparisons where a prefix comparsion can be done in half the time.

Offering a new 'option.keyprefix' as alternative to startkey/endkey would be convenient and allow an easy optimization within the engine.

**Comment by daleharvey** [comment]
We are planing to move away from using map / reduce as our primary query interface and replacing it with http://nolanlawson.github.io/pouchdb-find/ so I dont think we will be making improvements to the map reduce api at this time

**Comment by NNemec** [comment]
I understand that query will become obsoleted by pouchdb-find.
Does the new pouchdb-find also obsolete startkey/endkey in allDocs and changes?
From what I can find about pouch-db, it offers a great way to create and used secondary indices, but the most efficient way will remain to structure the primary index (_id) in such a way that the most important queries can be done without secondary indices. If that is true, my request for optimizing primary-index retrievals would remain relevant.
If you agree, I would suggest to remove "query" from the title and description and then reopen this issue.

**Comment by NNemec** [comment]
Sorry, I just saw that the very first example of pouchdb-find does actually show exactly the use-case of startkey/endkey. Please ignore my previous comment...
