### ISSUE TITLE
Pouchdb got 404 when send _local request

### ISSUE THREAD

**Issue by CBingY** [pouchdb/pouchdb#6131]
### Issue
First time pouchdb sync data from couchdb, there're some 404 error which told "The above 404 is totally normal. PouchDB is just checking if a remote checkpoint exists."
And after that, couchdb's db disk size increase.

### Info
- Environment: (browser)
- Platform: (Chrome.)
- Adapter: (IndexedDB)
- Server: (CouchDB)
- pouchdb5.4.5 couchdb 1.6

### Reproduce
It sent some requests like GET http://xxxx.com/test_db/_local/AOd9U2DhzJL5plWcxi8B1A%3D%3D?&_nonce=1484127575124 and get the 404 return.
But when I run the request on browser alone, I got the data return.
I don't understand why got 404 because the request was supposed to have data return.
And why after these operation, the couchdb disk size had increase? 
Can you help?

**Comment by daleharvey** [comment]
The 404 means the checkpoint doesnt exist, subqequently PouchDB creates it (which will affect disk size) and if you check in the browser it will now exist, you will be able to see the subsequent PUT in the network log as well
