### ISSUE TITLE
total_rows in filtered pagination

### ISSUE THREAD

**Issue by cynrichuys** [pouchdb/pouchdb#6134]
### Issue
`total_rows` seems to not take into account if entries are filtered out. Might be related to #1172

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce

```
db.query('index', {
    startkey: [status],
    endkey: [status, {}],
    skip: 0,
    limit: 100
});
```
with the index having key `[status, creationDate]` in order to _filter_ on state and _sort_ by creation date.

My index has 18 entries, of which 9 have status `NEW`. The response of the query above with this status is however

```
{
  offset: 0,
  rows: Array[9],
  total_rows: 18
}
```

I would however expect `total_rows` to be equal to 9. Is this expected behaviour? If it is, I guess I need a second reduce query that counts the filtered entries in order to set up (filtered) pagination?

**Comment by nolanlawson** [comment]
`total_rows` is not intended to change based on filtering; it is intended to show the total number of non-deleted, non-local documents. This is consistent with CouchDB's behavior.

If I'm wrong please reopen, but I believe CouchDB should do the exact same thing. :)

**Comment by felix9ia** [comment]
How to solve it instead of closing it

**Comment by karlwestin** [comment]
I think it was closed because it's more of a question than a bug :)

one trick I've done before is to do one query in parallell with `include_docs: false` and use this as to get the count

**Comment by felix9ia** [comment]
If this is the case
```
[
{name: a1},
{name: a2},
{name: a1},
]
```

```
{
selector: {
name: 'a1'
},
limit: 1
}
```
`total_rows` will return `3`, because `total_rows` is doc size.

I thought of a way to create a view, 
```
// Map
function(doc) {
    emit(doc.name, 1);
}

// Reduce  select count
```
query in parallell with this view by
```
key: ['"a1"']
```
it will return 2, done!

#### but 
`limit` and `skip` will affect performance………………
