### ISSUE TITLE
Persistent queries fail to synchronize with CouchDB

### ISSUE THREAD

**Issue by tonowie** [pouchdb/pouchdb#6135]
## Issue
Persistent design docs fail to sync with CouchDB when view is defined by named function. I have based my implementation on [this article](https://pouchdb.com/2014/05/01/secondary-indexes-have-landed-in-pouchdb.html). I try to add design doc and use existing function => the function has name. Promise executes `then` as if all was fine but view is never delivered to CouchDB server and app keeps trying to sync forever.
To be fair it seems like some incorrect handling of error by CouchDB - it does not allow me to save such view in Fauxton yet it does not report any error there. But Pouch still behaves very weird and I suspect that the failed GET request in logs should cause the promise to fail instead of succeed,

### Info
- Environment: browser
- Platform: Chrome 55.0.2883.87 / Win7
- Adapter: IndexedDB
- Server: CouchDB 2.0.0 + replicated locally by PouchDB 6.1.1

### Reproduce
To reproduce first setup CouchDB (127.0.0.1:5984) to have something to sync with. Code below will log that index was created and then forever these lines

> GET http://127.0.0.1:5984/testdb/_local/W.qZNfM8N_IilwygkqIjKw%3D%3D? 404 (Object Not Found)
> test.js:3 replication resumed [object Object]
> test.js:3 replication paused undefined

The code that reproduces the problem

```javascript
//log function
function log(item) {
  console.log(item);
}

var dbName = 'testdb';
//declare database
var localDB = new PouchDB(dbName);
// define sync
localDB.sync(new PouchDB('http://127.0.0.1:5984/' + dbName), {
  live : true,
  retry : true
}).on('change', function(change) {
  log('database changed '+change);
}).on('paused', function(info) {
  // replication was paused, usually because of a lost connection
  log('replication paused '+info);
}).on('active', function(info) {
  // replication was resumed
  log('replication resumed '+info);
}).on('error', function(err) {
  // totally unhandled error (shouldn't happen)
  log('replication crashed '+err);
});

// function to avoid boilerplate code when creating design doc
function createDesignDoc(name, mapFunction) {
  var ddoc = {
    _id: '_design/' + name,
    views: {
    }
  };
  // HERE THE FUNCTION IS SERIALIZED TO STRING TOGETHER WITH IT'S NAME
  ddoc.views[name] = { map: mapFunction.toString() };
  return ddoc;
}

// function used to create the index
function index(doc) { emit(doc.name); }

// create the design doc
var ddoc = createDesignDoc("badindex", index);
// and save it
localDB.put(ddoc).then(function () {
  log('created index!');
}).catch(function (err) {
  log('index failed..' + err);
});
```

**Comment by willholley** [comment]
It looks like this is because your map function is named. In the article, the functions passed to `createDesignDoc` are anonymous, which is required by CouchDB.

Previously, these views would have been accepted by CouchDB but never processed. CouchDB 2.0 add new validation to reject malformed design documents, including those with named map/reduce functions. PouchDB [should probably have the same validation](https://github.com/pouchdb/pouchdb/issues/4599) to prevent design documents getting added locally, though documents could be rejected for other reasons e.g. user defined validation functions on the remote database.

If a single document cannot be synced, I'd expect PouchDB to raise an (error?) event but continue to sync.

As a fix, try:
```
var ddoc = createDesignDoc("badindex", function(doc) { emit(doc.name); });
```

instead of:
```
var ddoc = createDesignDoc("badindex", index);
```

**Comment by tonowie** [comment]
Thanks for explicitly adding the workaround. I should have probably done that myself, instead of just stating that the issue is with handling of named views.
