### ISSUE TITLE
Create DB on given path in Application Data of Android APP

### ISSUE THREAD

**Issue by ambercool99** [pouchdb/pouchdb#6136]
### Issue
Is there a way to create DB on given path in Application Data of Android APP

### Info
I am using PouchDB library to create DB in an Android Application (Android M).
the DB is created on private Database path on Application.

As Android M has Auto backup feature(which i don't want to disable) my DB files gets backed up.
and when i uninstall and Install Application, the Backed Up DB files get restored.

For Android Auto backup feature, refer: 
https://developer.android.com/guide/topics/data/autobackup.html

### Reproduce
it is reproducible with Any Android M App.

**Comment by nolanlawson** [comment]
PouchDB when using websql/indexeddb has no control over the storage location. You would need http://github.com/nolanlawson/pouchdb-adapter-cordova-sqlite to solve this problem, and I believe only https://github.com/brodysoft/Cordova-SQLitePlugin/ allows you to specify the exact file location. (For cordova-plugin-sqlite-2 I made the decision to always save data to `files/`. I'm not sure how this interacts with Android's backup.)
