### ISSUE TITLE
Allow iterable to be passed to e.g. `keys`

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#6148]
Currently this doesn't work:

```js
const map = new Map()
await db.allDocs({ keys: map.keys() })
```

Instead the following must be done:

```js
const map = new Map()
await db.allDocs({ keys: Array.from(map.keys()) })
```

**Comment by nolanlawson** [comment]
This is something I'd prefer not to support; it would greatly complicate the codebase to have to handle iterables. Currently the codebase isn't even written in ES6; it's written in ES5.
