### ISSUE TITLE
Firefox 39 not working

### ISSUE THREAD

**Issue by sphaero** [pouchdb/pouchdb#6149]
### Issue
Firefox 39 doesn't work. Erroring on "Failed to open indexedDB, are you in private browsing mode?" while the browser isn't in private mode.

### Info
- Environment:browser
- Platform: Firefox 39
- Adapter:  Default (IndexedDB)
- Server: NA

### Reproduce
Reproduced using:
```
<html>
<body>
<script src="http://cdn.jsdelivr.net/pouchdb/6.1.1/pouchdb.min.js">
</script>
<script>
  var db = new PouchDB('my_database');
</script>
</body>
</html>
```

**Comment by nolanlawson** [comment]
Is there any chance you can capture the error itself? That error is a generic error we throw when the database throws a generic error.

Also, out of curiosity, why Firefox 39? It's on version 50 now...

**Comment by daleharvey** [comment]
Yup, 39 is long unsupported, esr is 45 which is the furthest back we would really consider tracking. If you find an issue and have a patch for it then would be happy to take a look but we dont need to track this.
