### ISSUE TITLE
use _ensure_full_commit during replication over HTTP

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#6150]
### Issue
The CouchDB replication protocol asks that implementations call `_ensure_full_commit` following upload of a batch of changes to ensure CouchDB commits the data to persistent storage. PouchDB doesn't currently do this and probably should.

### Info
- Environment: all
- Platform: all
- Adapter:  HTTP
- Server: CouchDB

**Comment by daleharvey** [comment]
At most this should be an option but in general I would prefer to avoid, its a pretty major leaky abstraction and would add to our already busy HTTP traffic. Is `ensure_full_commit` not a CoucDB configuration? either way an extra call to actually do the writes that we just did is something Couch needs to take care off

**Comment by willholley** [comment]
yep - delayed commits is a CouchDB configuration option (I believe in 2.0 it defaults to `false`, so there is less risk of data loss). I think it's reasonable to skip `_ensure_full_commit` to avoid additional requests but wanted to make sure that was a conscious / documented design decision and not an oversight.

**Comment by daleharvey** [comment]
Yeh very happy to defer CouchDB configuration to couch
