### ISSUE TITLE
.changes doesn't report conflicts with options.conflicts:true

### ISSUE THREAD

**Issue by kiyanovsky** [pouchdb/pouchdb#6155]
### Issue
I'm listening for changes via db.changes function with {conflicts:true} option. And it doesn't report conflicts. Example [screenshot](https://screencast.com/t/v3TUaU4F).

As you can see, rev db.changes() doesn't report conflict for rev 16-a88, which is reported by following allDocs() results.

Is it a bug?

### Info
- Environment: (browser)
- Platform: (Chrome)
- Adapter: (IndexedDB)
- Server: (CouchDB)

**Comment by nolanlawson** [comment]
It seems we only have [one test](https://github.com/pouchdb/pouchdb/blob/1f2ad877f1641d6c95dd4295c8bff31bcec38a3e/tests/integration/test.changes.js#L2141-L2215) where we do `changes()` with `conflicts: true`, and it also has `style: 'all_docs'` which is what I believe the replicator uses. So it's quite possible there's a bug.

Any chance you could post a full repro? E.g. just a JSBin showing exactly how you called the `changes()` API to reproduce would be helpful. :smile:

**Comment by kiyanovsky** [comment]
Sure, [this example](https://jsfiddle.net/kiyanovsky/bp1j5dfz/8/) reproduces the issue.

**Comment by kiyanovsky** [comment]
If I add an option {include_docs: true} in changes(), then it reports conflicts, as [here](https://jsfiddle.net/kiyanovsky/bp1j5dfz/9/).

So this is not an issue, thou I did not want to get a doc ;-)

Thank you, Nolan!
