### ISSUE TITLE
Query - 401 unauthorized error

### ISSUE THREAD

**Issue by liamlevesque** [pouchdb/pouchdb#6161]
### Issue
This is probably a newb problem. I'm trying to run a simple query on a public database, but it keeps returning this error:
401: unauthorized - with message - "You are not a db or server admin." 

I'm logged in as a user (not an admin) when this happens. (I'm using pouchdb-authentication to handle login, sessions, etc..) 

I'm probably doing this all wrong, but here's my query code:

      var map = function(doc) {
	emit(doc.grade); 
       };

	app.db.query(map, function(err, response) { 
	   if (err) {
	      console.log(err);
	   }

	  if (response) {
		console.log(error);
	}
	});

Any help would be appreciated.

### Info
- Environment: browser
- Platform: Chrome
- Adapter: ?
- Server: Couchdb

**Comment by willholley** [comment]
CouchDB requires `admin` permissions to add map/reduce indexes, which is what PouchDB attempts to do if you explicitly specify a map/reduce function when calling `query()`. Are there existing indexes you can use or, if the server is CouchDB 2.0, perhaps you can use [pouchdb-find](http://nolanlawson.github.io/pouchdb-find/)?

**Comment by liamlevesque** [comment]
Aha - that was the part that was confusing me. I can create an index manually as an admin and then reference that using my query from the client. Thank you for clarifying that for me!
