### ISSUE TITLE
Will pouch merge overlapping changes streams?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#6169]
e.g. in the following scenario will Pouch reuse existing change streams?

```js
const changes0 = db.change(({ since: update_seq, live: true })
setTimeout(() => {
  const changes1 = db.change(({ since: 'now', live: true })
  const changes2 = db.change(({ since: 'now', live: true })
}, 1000) // changes0 is at 'now' after 1000ms
```

Theoretically these 3 could be merged into one.

**Comment by nolanlawson** [comment]
No it doesn't merge them. I don't believe we have any plans to, either, because it would be a very complicated code change and users can do this themselves in their own code.
