### ISSUE TITLE
Docs on checkpoints with explanation

### ISSUE THREAD

**Issue by oliverjanik** [pouchdb/pouchdb#6175]
I've been analyzing PouchDB traffic to our CouchDB servers and one thing that caught my eye is that PouchDB seems to be issuing a **lot** of requests like this `GET _local/7nCSpUgJqHpt0gIY7JVczA%3D%3D?`
They seem to make up up to 50% of all requests. I could not find any explanation but after a bit of google PouchDB seems to call these *checkpoints*.

Is there a documentation on why they're needed a possibly a way to tweak that behavior?

As it stands PouchDB saturates 6 max connections per domain on Chrome for us and I can see other important requests being stalled because of that.

In our use case we have up to 10 concurrent Pouches syncing against CouchDB server. Halving the amount of requests could go a long way if possible. We're quite a bit of replication lag (2 mins in peak) that we're trying to get to the bottom of. Thank you for any info.

**Comment by nolanlawson** [comment]
I believe you can have fewer checkpoints written by increasing the `batch_size`. If you increase the `batch_size` do you see the number of requests go down?

> In our use case we have up to 10 concurrent Pouches syncing against CouchDB server

Do you mean 10 PouchDBs on the same client or 10 total users?

**Comment by oliverjanik** [comment]
It's 10 total users with that particular database. They're local pouchDBs that are set up to replicate to a couchDB remote.

I found this thread from a while ago: https://github.com/pouchdb/pouchdb/issues/2514

You were concerned about the performance. As per the thread, If we can guarantee that remote is never wiped can we configure PouchDB to do local checkpoints only? Is that assumption correct?

**Comment by nolanlawson** [comment]
Hm if it is indeed a performance boost (50% of requests is a lot), then we could add a feature to the `replicate()` API, `skipRemoteCheckpoints`. @daleharvey ?

**Comment by oliverjanik** [comment]
Can you give me a any pointers where in the codebase this is? Maybe I can fork it and comment this out to test it?

**Comment by daleharvey** [comment]
So we have been getting a lot of reports about too many replication checkpoint requests, we did some work on this before to reduce but it may need to be looked at again. Skipping remote checkpoints is an option we can add but it would be not be safe so it shouldnt be default and I would like to see us be as efficient as possible in a default configuration

**Comment by oliverjanik** [comment]
@daleharvey What do you mean by not safe? What can fail? Under what circumstances would it fail? Can you please explain the corner cases?

**Comment by nolanlawson** [comment]
The main corner case is that someone deletes their server-side CouchDB and then creates a new one with the same name. In that case you'd need to know that you're at a different checkpoint now that the database is a new one.

**Comment by oliverjanik** [comment]
I think I understand that issue. In our case we have full control over servers and databases. Any other reasons for remote checkpoints?

**Comment by lucidNTR** [comment]
@oliverjanik   i just found out the checkpoint docs are not pouch specific but also part of the official protocol: https://docs.couchdb.org/en/3.2.2/replication/protocol.html

this should explain all open questions.
