### ISSUE TITLE
pouchdb-ajax fails on jest testing

### ISSUE THREAD

**Issue by lgraziani2712** [pouchdb/pouchdb#6181]
### Issue

I wanted to test my code, who uses pouchdb-browser, with pouchdb-memory. But I get this error:

```bash
export default require('request');
^^^^^^
SyntaxError: Unexpected token export
  at transformAndBuildScript (node_modules\jest-runtime\build\transform.js:320:12)
  at Object.<anonymous> (node_modules\pouchdb-ajax\lib\index.js:11:15)
  at Object.<anonymous> (node_modules\pouchdb-adapter-http\lib\index.js:7:32)
```

Chaging the line to `module.exports = require('request');`. Fixed my error.

The crazy thing is that I use babel-jest, and it only complains there, in that specific file 😨.

### Info

- Environment: NodeJS
- Platform: babel-jest
- Adapter: pouchdb-memory > pouchdb-ajax
- Server: N/A

### Reproduce

1. `git clone https://github.com/LucianoGraziani/pouchdb-memory-jest.git`
2. `yarn install` or `npm install`
3. `npm test`

**Comment by nolanlawson** [comment]
Can you provide a test case to reproduce? I don't understand how this can happen.

The actual published `pouchdb-ajax/lib/index.js` file is pure commonjs; there is no `import` or `export` anywhere in there: https://unpkg.com/pouchdb-ajax@6.1.1/lib/index.js

**Comment by nolanlawson** [comment]
Also how are you using `pouchdb-browser` with `pouchdb-memory`? Technically those two packages are both presets (not plugins), i.e. you cannot plug one into the other, although you could plug `pouchdb-adapter-memory` into `pouchdb-browser`.

**Comment by LucianoGraziani** [comment]
I mocked `pouchdb-browser` with `pouchdb-memory`.

I use them as the tutorials saids:

```js
import PouchDB from 'pouchdb-browser';

const db = new PouchDB('mydb');
```

The mock file has this:

```js
import PouchDB from 'pouchdb-memory';

export default PouchDB;
```

I don't know what dependency uses PouchDB Ajax as dependency, didn't find it at the PouchDB memory deps.

The only thing I know is that pouchdb-memory uses old versions.

**Comment by LucianoGraziani** [comment]
BTW, in the repository I shared I don't mock anything, I just import from pouchdb-memory.

**Comment by LucianoGraziani** [comment]
Seeing this visualization repository http://npm.anvaka.com/#/view/2d/pouchdb-memory, I can correct myself: it uses the lastests versions.

@nolanlawson https://unpkg.com/pouchdb-ajax@6.1.1/package.json has this line: `"jsnext:main": "./src/index.js",`

When using babel I guess it uses jsnex:main, instead of main. But then, why complain about that specific import, when are a lot of them in other files.
