### ISSUE TITLE
Couchbase Sync-gateway sync error

### ISSUE THREAD

**Issue by lucapale** [pouchdb/pouchdb#6182]
### Issue
Synchronization with CouchBase Sync-Gateway sends a .../{db}/_user%2F{userid} request which is not available on the public port of Sync-Gateway.
This is sent continuously and slows down all the app with the continuous errors.

### Info
- Environment: Ionic 2
- Platform: all
- Adapter: all
- Server: Couchbase

### Reproduce
```
this.remote_db_options = {
        include_docs: true,
        attachments: false,
        crossDomain: true,
        withCredentials: true,
        skipSetup: true,
        ajax: {
          cache: false,
          timeout: 10000,
          headers: {
            'Content-Type': 'application/json',
          }
        }
      }
this.sync_db_options = {
      live: true,
      retry: true
    };
//set Cookie name - works for ios - workaround for android and web using a proxy server
if (isNativeiOSApp) {
      this.cookie_name = "Cookie";
} else {
      this.cookie_name = "ProxyCookie";
}
this.remote_db_options.ajax.headers[this.cookie_name] = "";
this.db = new PouchDB(this.local_bucket);
let remote_db = new PouchDB(this.sync_server, this.config.remote_db_options);
this.syncHandler = this.db.sync(remote_db, this.sync_db_options)
```

**Comment by lucapale** [comment]
I found a small bug in the code. Index.js line 8716:
`// Couchbase Sync Gateway emits these, but we can ignore them
      /* istanbul ignore if */
      if (change.id == "_user/") {
        return;
      }`

should instead be:
`// Couchbase Sync Gateway emits these, but we can ignore them
      /* istanbul ignore if */
      if (change.id.indexOf("_user/")!= -1) {
        return;
      }`

Because the change.id received from SyncGateway is "_user/userid".
Thanks
Luca

**Comment by gine** [comment]
i think this happens to me too. I will try to test your solution on my end.

**Comment by willholley** [comment]
this should probably be:
```
if (change.id.indexOf("_user/") === 0) { return; }
```

as we shouldn't exclude changes with an id of e.g. `mydoc_user`.

**Comment by lucapale** [comment]
Yes, correct. Thank you.

**Comment by lucapale** [comment]
I found out that using Roles in SyncGateway requires also a similar modification like the Users, so the correct function now should be:
`if (change.id.indexOf("_user/")===0 || change.id.indexOf("_role/")===0) { return; }`
Bye,
Luca

**Comment by gine** [comment]
Thanks, works to me too.

**Comment by daleharvey** [comment]
Closing as couchbase, explained in https://github.com/pouchdb/pouchdb/issues/5820
