### ISSUE TITLE
DDOS-ed by PUTs from IE11

### ISSUE THREAD

**Issue by sphaero** [pouchdb/pouchdb#6190]
### Issue
Seeing many "PUT /db/ccstore/_local/rhiaLfaM.A6XR68SMk_PsQ%3D%3D HTTP/1.1" 409 340 "http://xxx.xxx.xxx.xx/" "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko"
calls on the backend (pouchdb-express).

Just some stats from today:
```
  15647 195.212.43.146
  16822 156.83.1.18
  24472 156.83.1.19
  31150 37.17.215.129
  37339 144.43.250.51
  40175 82.148.222.202
 164995 217.68.49.85
 233967 85.149.28.70
 252125 213.207.107.222
```
I've also filtered for useragents and found:
```
234339 "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko"
171605 "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
467129 "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
57458 "Mozilla/5.0 (Windows NT 6.1; Win64; x64; Trident/7.0; rv:11.0) like Gecko"
```
Hence my suspicion for IE.

### Info
- Environment: Backend: Node.js pouchdb 6.1.1/browser: 6.1.1
- Platform: Backend UbuntuLTS/ IE
- Adapter: defaults
- Server: PouchDB Express (2.2.0)

### Reproduce
I just can't reproduce it myself :(

The backend is nothing more than:

    app.use('/db', pouchDBApp);

and some custom posts in the db, ie:

```
app.post( '/save/persoon', jsonParser, function ( req, res ) {
    if (!req.body) return res.sendStatus(400);
    var data = req.body;
    if ( data.ctime && data.contactdetail && data.naam ) {
        mailPersoonSubmission(data);
        ccstore.post( data )
        .then( function( res ) {
            return res.json( res.id );
        })
        .catch( function ( err ) {
            return res.sendStatus( 500 );
        }); 
    } else {
        return res.sendStatus(404);
    }
});

The frontend is calling this:
```
        PouchDB.replicate( this.ccstore.remoteDb, this.ccstore.db)
            .then( function ( result ) {
                    this.ccstore.db.query( 'data/by_type', { 
                    key: 'persoon',
                    include_docs : true 
                } )
                .then( function( res ) {
                        this.ccstore.syncFromRemote(); // replicate from remote to local
                        this.d3_init( res );
                        this.ccstore.changes();   //listen for changes
                    }.bind( this ) )
                .catch( function (err) {
                    dbg("getAllForType err", err);
                    if ( err.status > 499 ) {
                        alert( 'Waarschijnlijk werkt deze app niet op jouw systeem? Probeer een nieuwere browser zoals Chrome of Firefox. Deze app werkt ook niet als de browser in "Privé" modus staat.' );
                    }
                    this.d3_init( [] );
                }.bind( this ));
            }.bind(this) )
            .catch( function(err) {
                console.log("REPLICATION ERROR", err);
            } );
```

**Comment by nolanlawson** [comment]
Looks like there is some odd bug in IE11 on Windows 10. In the test suite we only test IE10 on Windows 8.1. Thanks for reporting!

**Comment by nolanlawson** [comment]
Are you using a proxy in front of express-pouchdb? If you use CouchDB can you reproduce the bug?

**Comment by saubaer** [comment]
We ran into the same issue i guess.
For the test we used a plain CouchDB 1.6.1 hosting 2 databases and a simple html test page using pouchdb 6.2.0:
```
    var db1 = new PouchDB('http://hyperion:5984/pouch1');
    var db2 = new PouchDB('http://hyperion:5984/pouch2');

    db1.replicate.to(db2, {
      live: true,
      retry: true
    });

    db2.replicate.to(db1, {
      live: true,
      retry: true
    });

    setInterval(function() {
      db1.post({
        foo: 'bar'
      }, function() {
        console.log(arguments);
      });
    }, 1000);
```
When opening the page in chrome we do see GETs and PUTs to the local documents URL in server log.
Opening the page in Edge on windows 10, we also see GETs and PUTs to the local documents URL, the GETs have "?&_nonce=1497013457629" added to the URL.
Opening the page in IE11 on windows 10, I do not see the GETs in server log at all, resulting in 409s on the PUT requests.
The developer tools of IE11 do show GET requests with an added "?" but no "&_nonce" parameter and they state the results is served from cache which obviously results in the wrong revision being set.
Maybe IE11 is so smart it removes the "@_nonce" since the first key/value pair of the query string is empty?

Following client versions where used in case it matters:
Windows 10 pro
Version: 1703

IE11
Version: 11.332.15063.0
Updateversion: 11.0.42

Edge
Microsoft Edge 40.15063.0.0

**Comment by onearmfrog** [comment]
Same thing here -
We're running CouchDb on Unix/EC2 with Nginx as an https reverse proxy.
Pouchdb is used on the browser.

Using IE11, I'm getting bombarded with 409 errors on Fiddler.
We're using live sync with retry.

I've tried rolling back to from 6.3.4 to 6.2.0.

Here's a screenshot from a fiddler log:
![couch](https://user-images.githubusercontent.com/1443156/28304245-5ea1ae1c-6b9f-11e7-8601-a21eb9d96fd0.PNG)
