### ISSUE TITLE
Authentication cookie does not get detected

### ISSUE THREAD

**Issue by HitomiTenshi** [pouchdb/pouchdb#6191]
### Issue
Authentication cookie does not get detected on newer Chrome browsers and Edge.

### Info
- Environment: browser
- Platform: Chrome 56 - dev 57 / Edge 38.14393.0.0
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
- Create a database with permissions, e. g. `users` role for both admins and members
- Create a user with a `users` role
- `npm install pouchdb` 6.1.1 (or 6.2.0 pre)
- `npm install pouchdb-authentication`

Use this code to reproduce the issue:

```
async connect(): Promise<void> {
    var localDb = new PouchDB("mydb");
    var remoteDb = new PouchDB('http://localhost:5984/mydb');

    await remoteDb.login('batman', 'brucewayne');

    localDb.sync(remoteDb, {
      live: true,
      retry: true
    }).on('error', (error: any) => {
      console.log('Major error occured:');
      console.log(error);
    });
}
```

I'm using TypeScript 2.1.5

# What currently happens

On Chrome the login function succeeds but the sync gets an error.
![chrome_2017-01-30_16-23-57](https://cloud.githubusercontent.com/assets/7304212/22428760/8c0063d8-e708-11e6-8e11-5d445de2c6b1.png)

On Edge the login function already throws an error:
![applicationframehost_2017-01-30_16-26-39](https://cloud.githubusercontent.com/assets/7304212/22428885/02261f1c-e709-11e6-9dd7-d2f354b50c8a.png)

# What's supposed to happen

PouchDB should detect the Auth Cookie and sync properly. It does work and detect the cookie on Internet Explorer 11 and Firefox 51.

**Comment by HitomiTenshi** [comment]
I wrote my own login with angular 2's HTTP Module, contacting _session with a POST using my credentials. (pretty much the same way you did in the pouchdb-authentication library)

I still get the same problem with the same browsers. The Set-Cookie does not get detected by pouchdb on Chrome 56+ and Edge 38.

**Comment by willholley** [comment]
does it work if you specify credentials in the URL rather than use cookie authentication? If so, it may be fixed by https://github.com/pouchdb/pouchdb/pull/6159

**Comment by HitomiTenshi** [comment]
Yes, it works if I use the authentication header instead of relying on cookie authentication.

Adding this line to the ajax headers works: `Authorization: 'Basic ' + window.btoa(user.name + ':' + user.password)`

Here's hope for #6159 fixing this issue.
