### ISSUE TITLE
Changes feed not cancelling event listener on cancellation

### ISSUE THREAD

**Issue by tomjmul** [pouchdb/pouchdb#6192]
Using PouchDB 6.1.1

When repeatedly subscribing and unsubscribing to a local db changes feed, I eventually get a warning in the devtools console shown below

![screen shot 2017-01-30 at 19 40 38](https://cloud.githubusercontent.com/assets/1492253/22438497/2c2d2fe2-e724-11e6-9ec6-08dd864bc9ec.png)

It would appear that the change operation is setting up an event listener somewhere but not removing it when I call ` changeFeed.cancel()`

This is the function that gets called on cancel, which doesn't seem to do very much at all.

```
Changes$2.prototype.cancel = function () {
  this.isCancelled = true;
  if (this.db.taskqueue.isReady) {
    this.emit('cancel');
  }
};
```

**Comment by mnewmedia** [comment]
I'm also facing this, but was unshure if it's really not my fault ;)

**Comment by ronag** [comment]
hm, I might have faced this as well.
