### ISSUE TITLE
_changes stops sending poll request to CouchDB after network interruption

### ISSUE THREAD

**Issue by ramotswa** [pouchdb/pouchdb#6197]
Hello! 👋

### Issue
I am working on a system that is listening for changes on a local CouchDB and then do some action. Something fairly straight forward, and it works most of the time. I have recently seen that if I run my app and watch my network tab, I can see the long poll requests being made to Couch. Great. However - if I put my computer to sleep, and then come back, those requests stop being sent. I am assuming that my 'putting computer to sleep' == 'network interruption' - but happy to be corrected with that. Has anyone ever come across something like this before?

### Info
- Environment: AngularJS, PouchDb v 6.0.5 (via bower).
- Platform: (Mac OS Sierra 10.12.2 iMac etc)
- Adapter: (CouchDB)
- Server: (CouchDB)

### Reproduce
Start your favourite app that listens to couchdb changes.
Watch the network time to see the longpolls requests
Put your computer to sleep
Wake it up again and change something in the db. 
For me, the longpoll doesn't respond with a result.

Very simple code;
```
var db = new PouchDB('http://localhost:5984/myDB');
db.changes({
          include_docs: true,
          continuous: true,
          since: 'now'
         }).on('change', function (change) {
           doMyStuff();
          return change;
        });
```

Any pointers would be much appreciated.

**Comment by ramotswa** [comment]
Update: It seems the offending line (although most probably by design) is the area around 10682 (at least in version 6.0.5 in pouchdb.js.
i.e.
```
 // In case of an error, stop listening for changes and call
 // opts.complete
            opts.aborted = true;
            opts.complete(err);
``` 

The logic it seems is that if there is an error sending the _changes xhr request, the code will never try again (?) and even if it does the code at 10648: 

```
 if (opts.aborted) {
            return;
          }
```
will always ensure that we cannot continue. Is there a way to not let it do that? 
Thanks

**Comment by willholley** [comment]
@ramotswa I think you'd need to handle this explicitly in your application - detect when the network becomes available and restart the sync.
