### ISSUE TITLE
pouchdb-dump-cli does not support attachments

### ISSUE THREAD

**Issue by filionf** [pouchdb/pouchdb#6198]
### Issue
When exporting a database with attachments, pouchdb-dump-cli result in the following error
`this._get is not a function`
The issue can also be found here: https://github.com/nolanlawson/pouchdb-dump-cli/issues/14

### Info
- Environment: Node.js
- Platform: Windows
- Adapter: writableStream/http
- Server: CouchDB

### Reproduce
Run the following command on a database that has attachments.
`pouchdb-dump http://localhost:5984/mydb > dump.txt`

**Comment by daleharvey** [comment]
pouchdb-dump-cli is not a part of pouch core, needs filed on https://github.com/pouchdb-community/pouchdb-dump-cli

**Comment by filionf** [comment]
That is fine. This issue has been resolved differently since then (with the _remote flag)
