### ISSUE TITLE
pouche db windows plugin error

### ISSUE THREAD

**Issue by simran100** [pouchdb/pouchdb#6205]
### Issue
Hi,I am getting PouchDb adapter undefined Error while running my  SAPUI5 project on windows 8.1 phone via visual studio. Can someone please help me out,what adapter should i use to run my project on windows 8.1 phone

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

### Reproduce
Write the steps for others to reproduce issue here. Providing a code example, links to a repository or a live example (JSBin etc) are even more helpful.

**Comment by nolanlawson** [comment]
It should work out-of-the-box with the IndexedDB adapter. Can you verify that `window.indexedDB` is available? Also is this in the browser or in a Windows Web App or...?
