### ISSUE TITLE
eslint allows improper spacing, braces, and gutter width

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6209]
At the very least, our gutter should be 100 (used to be 80). Right now it's not enforced, so our code has gotten too wide.

Also, forms like this are accepted:

```js
if(foo){
  bar();
}
```

And:

```js
if (foo) bar();
```

Both should be disallowed.

**Comment by nolanlawson** [comment]
To fix this, we would need to modify the `eslintrc` file to have the new conditions, and then modify the code anywhere that it fails the test.

**Comment by DanielLyons178** [comment]
I would like to try this if it's as simple as adding a max-len rule with code option as 100 to eslintrc. If you could elaborate on the proper bracing form should be I could look at that too.

**Comment by nolanlawson** [comment]
Hey @DanielLyons178, you should absolutely feel free to attack the maxlen issue first. In fact it may be best to separate this into different commits to make it easier to understand.

For the braces issue, we just want a space after `if` and a space after the `)` as well. Also we should disallow single-line `if` statements – braces are required. I don't really know the eslint commands to get this to work, but it should require just a little bit of research in the eslint docs. :)

**Comment by DanielLyons178** [comment]
Thanks for the info! I will tackle this tomorrow.
