### ISSUE TITLE
Investigate using IndexedDB Observers for change events

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6212]
This has landed in Chrome Canary: https://github.com/WICG/indexed-db-observers

We should experiment and see if this can replace our localStorage-based events. In theory this system should work but only across tabs but also across Web/Service Workers while our current system does not.

**Comment by dmurph** [comment]
open up again? Or maybe when we start the origin trial for observers?

**Comment by dmurph** [comment]
This is on the roadmap for this year. We want to simplify the design & remove the transaction option from the spec, and make it so each observer can observe a single range.

We're planning on updating the spec more to allow 'batching', so more than one transaction's changes can be included in a change list. This will make it possible for this feature to work with tab suspension / serialization if that ever happens.
