### ISSUE TITLE
How long will a pouchdb instance last in the browser?

### ISSUE THREAD

**Issue by DictumMortuum** [pouchdb/pouchdb#6214]
Hello all,

First of all I would like to thank you for creating pouchdb, I have been using it for many of my personal projects, as I find couchdb as a backend really easy to use and install.

This is not really an issue, but a question. Let's say that I create a pouchdb instance (without syncing it with a couchdb backend) and PUT some docs into it - will that instance last in my browser and persist across browser restarts? My understanding is that my documents and databases will persist, unless I clean the cache of my browser. I have been pondering about my question for some time, but I would like to share my thoughts - maybe I'm missing an important detail or I'm overlooking something.

The idea is to create a tool that is usable from the browser, without the need to install a couchdb instance and add a syncing mechanism on demand - only when there is need to save your progress.

Regards,
Dimitris

**Comment by pubkey** [comment]
Hi @DictumMortuum 
The pouchdb-instance lives in the js-process as long as you do not close the tab/window. It's just a js-object.

I think your question is, how long the data is persistent.
This depends on some things:
- Which browser
- Which adapter (localstorage/indexedDB/websql)
- how big is the database

In the near future, there is the `StorageManager.persist`-[API](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/persist) which asks the browser for permission to store data persistent.
For google-chrome, I recommend you to read [this](https://developers.google.com/web/updates/2016/06/persistent-storage)

**Comment by DictumMortuum** [comment]
Hello @pubkey ,

Thank you for your answer, you saved me from doing work that wouldn't be any good since persistent data is not reliable at the moment.

I guess I'll have to wait for the persistent APIs.

Regards,
Dimitris

**Comment by pubkey** [comment]
@DictumMortuum Do you use pouchdb for browser, node or electron or anything else?
Because the inpersistent-data problem is only on the browser.

**Comment by DictumMortuum** [comment]
@pubkey I'm currently using it for the browser.

**Comment by nolanlawson** [comment]
Yep basically the data is persisted to disk. Most browsers rarely if ever delete IDB data, but per the spec they are allowed to unless you declare it as persistent. Details here: https://developers.google.com/web/updates/2016/06/persistent-storage
