### ISSUE TITLE
Numerics if null becomes NaN after a get

### ISSUE THREAD

**Issue by tshad** [pouchdb/pouchdb#6218]
I am writing a value to pouch using parseFloat.

The value is null in Pouch, but when I do a get, the doc shows the value as NaN.

Is there a way to bring it back as a null?

Thanks,

Tom

**Comment by nolanlawson** [comment]
PouchDB stores data exactly the same way `JSON.stringify()` converts data. So NaN is not preserved:

```js
> JSON.stringify({foo: NaN})
'{"foo":null}'
```

You will need to sanitize the float before storing it in the database, or when you read it if you want null instead of NaN you could do:

```js
var myNumber = stored.num === null ? null : parseFloat(stored.num)
```

**Comment by nolanlawson** [comment]
Please let me know if that answered the question; if not, please reopen. :smiley:
