### ISSUE TITLE
Pouch incorrectly does encodeURIComponent of _id when PUTing  _local docs

### ISSUE THREAD

**Issue by akircher** [pouchdb/pouchdb#6220]
### Issue
Pouch incorrectly does encodeURIComponent of _id when `PUT`ing  _local docs.  This encoding is correct when it is `GET`ing _local docs.  For example:

`GET http://localhost/account/_local/qyZEoOWW0OruKWQGVSnAnA%3D%3D?`
`PUT http://localhost/account/_local%2FqyZEoOWW0OruKWQGVSnAnA%3D%3D`

Notice the `_local/` vs `_local%2F`.  I also see an extraneous `?` at the end of the `GET`.

I am using 6.0.4.  Apologies if this was recently fixed or if this is intended behavior.  If the latter, I would love to know the reason.

### Reproduce
This happens during normal syncing with CouchDB.

**Comment by willholley** [comment]
https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-http/src/index.js#L48 looks like it should do the right thing - does it occur with PouchDB 6.1.2?
