### ISSUE TITLE
Replication checkpoints use JSON.stringify, which is not stable

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6226]
See also: https://github.com/nolanlawson/pouchdb-find/issues/252

Doesn't matter if we sort the keys; the JSON.stringify API does not guarantee consistency.

**Comment by nolanlawson** [comment]
Hardest part is ensuring backwards compat but may be possible.

**Comment by willholley** [comment]
Interesting one. Could we fall back to the naively-generated checkpoint id if the stable checkpoint id doesn't exist? So long as we remember the decision for the lifetime of the Checkpointer object, the overhead would just be one additional request per db/browser session, I think?

**Comment by nolanlawson** [comment]
Maybe. I'm also fine with just writing a new hash algorithm and taking the perf hit with existing clients.

BTW I also don't want us to bring in all of [json-stable-stringify](https://github.com/substack/json-stable-stringify) because we don't actually need the JSON format, and it's a fairly big dep.

**Comment by nolanlawson** [comment]
related: #6255
