### ISSUE TITLE
PouchDB governance

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6229]
This topic came up at the CouchDB Dev Summit (https://github.com/janl/couchdb-next/issues/49). There was broad consensus that we'd like to have a more formal governance model because:

1. It instills more confidence in the CouchDB+PouchDB combo (CouchDB is already under ASF)
2. Formalizes how we make decisions
3. Formalizes how we can accept donations/funding

Some promising options seem to be the [JS Foundation](https://js.foundation/) and [Open Collective](https://opencollective.com/), but this is a good time to discuss this at the community level since it would affect the whole project.

Raw notes from the summit:

```
- Open Collective / Patreon / Linux Foundation?
- Concerned about ASF  (re: jira etc)
- Generally onboard with idea of governance
- 3-5 people on call to judge reimbursements
- Gregor can help with the Open Collective setup
- New “JS foundation”, more aware of JS ecosystem (are members of W3C)
```

**Comment by garrensmith** [comment]
The JS Foundation looks interesting. They don't seem to have formal structures on how each project  which is probably a good thing.
