### ISSUE TITLE
Missing update_seq option

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#6230]
CouchDB has support for the `update_seq` option in e.g. [all_docs](http://docs.couchdb.org/en/2.0.0/api/database/bulk-api.html).

This seems to be missing in PouchDB?

**Comment by daleharvey** [comment]
To summarize, we would like to add an option to allDocs so that

```
db.allDocs({update_seq: true}).then(result => { 
   result.update_seq is set correctly
}
```

**Comment by jo** [comment]
Also important for `db.query`.
