### ISSUE TITLE
iOS Chrome broken for PouchDB (iOS 9.x) ?

### ISSUE THREAD

**Issue by dharders** [pouchdb/pouchdb#6235]
### Issue
PouchDB does not work out of the box on iOS Chrome (Pouch 6.1.2, iOS 9.3.5, Chrome 56.0.2924.79)
The same code works fine on iOS Safari. I assume this is to do with the WKWebView implementation and its (lack of) support for data storage. 

I remember reading (not in official docs, but a GH issue somewhere) that possibly the FruitDown adapter will help in this instance.

Is this just how it is for iOS Chrome users until everyone is on iOS 10+ and WKWebView issues are solved ? Or is there a bug in PouchDB ?

### Info
- Environment: Browser
- Platform: iOS Chrome
- Adapter: Letting PouchDB decide
- Server: None, local only

### Reproduce
```javascript
<script src="//cdn.jsdelivr.net/pouchdb/6.1.2/pouchdb.min.js"> </script>
  <div id="output"></div>
  <script>
  var db;
  try {
    db = new PouchDB('my_database');
    db.info().then(function (result) { 
      log('PouchDB version ' + PouchDB.version);
      log(result);      
    }).catch(function (err) { log(err); }); 
  } catch (e) {
    log('Exception: ' + JSON.stringify(e));
  }
  function log (obj) {
    var text = JSON.stringify(obj);
    var o = document.getElementById('output')
    o.innerHTML += text + '<br>';
  }
  </script>
```
The above works for me in iOS Safari, printing the PouchDB version 6.1.2 and db info.
But it does not work in iOS Chrome. iOS Chrome throws an exception: line 8, column 8203 in pouchdb.min.js, which points to an Invalid Adapter exception. Am I correct in assuming that all iOS users < iOS 10, using Chrome iOS (with WKWebView) require the FruitDown adapter to have PouchDB work ? Or is something else going on ?

**Comment by dharders** [comment]
I should also point out that adding:
```javascript
<script src="https://github.com/pouchdb/pouchdb/releases/download/6.1.2/pouchdb.fruitdown.min.js"></script>
db = new PouchDB('my_database', { adapter: 'fruitdown' });
```
solves the issue for iOS Chrome.

This issue was more of a question: Is this the recommended way ?
 i.e. detect exception, then pull-in fruitdown adapter and run new Pouch(...) again.

**Comment by nolanlawson** [comment]
Yes, if you need to support iOS Chrome on iOS <= 9, then that's the only way.

There was [a bug in WKWebView](https://bugs.webkit.org/show_bug.cgi?id=137760) before iOS 10 where WebSQL was not available and IndexedDB is of course not up to snuff. The workaround is to use pouchdb-adapter-fruitdown or pouchdb-adapter-localstorage as a fallback.

BTW I noticed this was not listed on https://pouchdb.com/errors.html . This would be a great opportunity to submit a pull request to add it to the list of common errors. :)
