### ISSUE TITLE
db tasks not fulfilling

### ISSUE THREAD

**Issue by furstenheim** [pouchdb/pouchdb#6241]
### Issue
I'm able to create the db but no task is ever fulfilled or rejected. The code is very simple, it is just

`
    var pouchDb = require('pouchdb')
    db = new pouchDb('some-db', {size: 50}) // some db which has been used in the past
    db.get(key, {revs_info: true}, callback)
`

The callback is never called, if I debug db I see that the taskqueue increases in each petition and they are never consumed, also isReady is marked as false.

It is important to say that the code has been ran in several computers and this bug only happens in one of them. Moreover, it only happens with Chrome. What is more, if the website is opened in private mode then there is no issue at all. Also, if the same code is run in different urls then it only happens in one of them (always the same one).

That said, it is of course impossible for me to provide any means of reproducing the error.

Do you have any idea of what it could be?

**Comment by nolanlawson** [comment]
@furstenheim It's possible that the local Chrome IndexedDB database got corrupted. If you clear the browser data and then try again, what happens?

**Comment by furstenheim** [comment]
@nolanlawson clearing the browser data fixed the problem. Any idea what could have happened and how to avoid it?

**Comment by ermouth** [comment]
@furstenheim I experienced exactly same symptoms once, and twice I had data corruption. All three cases were about underlying storage integrity. Try to check (including surface check) you disk.

**Comment by furstenheim** [comment]
@ermouth How can I check the storage integrity (I'm using Ubuntu). BTW, in the developer's console in application IndexedDB I can check the store keys and there doesn't seem to be anything faulty with them.

Enabling debug, PouchDB.debug.enable('*'), I get:
```
pouchdb:adapter Picked adapter: idb +0ms
browser.js:123 pouchdb:api my-db +24ms get my-key 
Object {revs_info: true}
```

But nothing else

**Comment by nolanlawson** [comment]
To check the storage integrity you would have to find where Chrome/Electron is storing the IndexedDB data (which is a LevelDB file). Then you may want to open an issue on Chromium about it.

I've heard lots of feedback about IDB data corruption in Chrome but I'm not sure anyone has submitted rock-solid test cases to the Chromium team so they might not have fixed it yet.

**Comment by daleharvey** [comment]
Not a lot we can do at this point about idb durability
