### ISSUE TITLE
Sorting with selector $exists uses the wrong index

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6266]
_From @dolfje on September 8, 2016 10:27_

When trying to sort on a field that is only selected by the $exists selector, gives an error.

> testDB = new PouchDB('test');
> testDB.createIndex({index: {fields: ["test"]}}).then(function() {
>  return testDB.put({_id: ""+Math.random(), "test": 5});
> }).then(function() {
>   return testDB.find({selector:{"test": {$exists: true}}, sort: ["test"]});
> }).then(function(ret) {
>   // Expect result, only get 
>   //Error: Cannot sort on field(s) "test" when using the default index
> });`

_Copied from original issue: nolanlawson/pouchdb-find#212_

**Comment by nolanlawson** [comment]
_From @dolfje on September 8, 2016 10:47_

I think the checkFieldsLogicallySound is wrong. There is checking if the index can be used. But that only works when the indexes are one of '$eq', '$gt', '$gte', '$lt', '$lte'. So $exists isn't added there. I've added $exists temporarely to logicalMatchers and my function works. Although I have to be honest, I don't have enough knowledge about the code base, to know the implications.

Also the code for isInvalidNe in that function does nothing. Because the hasLogicalOperator is false when $ne is used. So that part of the code cannot be triggered with $ne.

**Comment by nolanlawson** [comment]
_From @dolfje on September 8, 2016 12:43_

And also $regex should be added to the logicalMatchers variable

**Comment by nolanlawson** [comment]
_From @yoonwaiyan on December 14, 2016 14:54_

Any update on this issue? I'm having the same problem here, trying to sort based on a "date" field but getting the same error even after using indexes:

```
    expenses.createIndex({
      index: {fields: ['date']}
    }).then(function (result) {
      console.log("created index", result);
      return expenses.find({
        selector: {
          date: {'$exists': true}
        },
        sort: ['date']
      }).then(function (result) {
        console.log("result", result);
        dispatch({
          type: GET_ALL_EXPENSES,
          payload: result.rows
        });
      }).catch(function (err) {
        console.log("err", err);
        dispatch({
          type: GET_ALL_EXPENSES,
          payload: []
        });
      });
    }).catch(function (err) {
      console.log("index error", err);
    });
```

**Comment by nolanlawson** [comment]
_From @htrampe on January 6, 2017 20:2_

Same problem here - any ideas?

**Comment by flamusdiu** [comment]
I have ran into the same problem. If you get the error, usually refreshing the page makes the error go away. It seems to be missing something on the first load (which doesn't get destroyed when you refresh so it doesn't error out).

Is there a different way to pull X number of sorted results?

**Comment by raphadko** [comment]
Note that this issue also happens when using the $type selector filter.

**Comment by raynoppe** [comment]
I am still getting this issue when trying to sort. 

Setting the index:
`PouchDBService.setIndexes = () => {
	DB.createIndex({
		index: {
			fields: ['type', 'date']
		}
	}).then(function (result) {
		console.log('index', result);
	// I get confirmation that the index exists.
	}).catch(function (err) {
	// ouch, an error
	});
}`

My query:
`const results = await DB.find({
			selector: {
				$and: [
					{ type: 'event' },
					{ date: { '$exists': true } }
				]
			},
			fields: ['type', 'date'],
			sort: [{ date: 'desc' }]
		});`

Error I get:
Possible Unhandled Promise Rejection (id: 0):
Cannot sort on field(s) "date" when using the default index
Error: Cannot sort on field(s) "date" when using the default index

**Comment by hco** [comment]
I think that this is a bug that should be fixed, and should not be marked as wontfix.

But maybe I am missing something here.

**Comment by rmdwirizki** [comment]
I got this working by adding a **gt: null** with _and_ selector like :

```javascript
this.db.products.createIndex({
  index: { fields: ['name'] }
}).then(() => {
  return self.db.products.find({
    selector: {
      $and: [
        { name: {'$gt': null} },
        { name: {'$exists': true} }
        // works on $regex too
        // { name: {'$regex': new RegExp('ndo', 'i')} }
      ]
    },
    sort: [{'name': 'desc'}],
    limit: 10
  });
})
```

**Comment by mythsmith** [comment]
Thanks @rmdwirizki! This worked for me also.

**Comment by popod** [comment]
Why closing this issue ? I think this should be resolve without workaround as shown before..

**Comment by njt1982** [comment]
@rmdwirizki - This worked for me on my regex query.

I think this work around indicates a bug... I agree with @popod

**Comment by Shemyatenkov** [comment]
I've solved this problem on my side, using JS function sort. Like this:
```
        db.find({
            selector:   {element_type: ET_PROJECT},
        }).then(function(res) {
            res.docs.sort(function(a, b) {
                if (a.fieldname > b.fieldname)
                    return 1;
                if (a.fieldname < b.fieldname)
                    return -1;
                return 0;
            });
            // ... here we can use res.docs sorted
        });
```

**Comment by daleharvey** [comment]
As a note, this also fails against CouchDB / Mango

```
    it('Sorts with exists wtf', function () {
      var db = context.db;
      return db.bulkDocs([
        {_id: 'a', foo: 'a'},
        {_id: 'b', foo: 'b'}
      ]).then(function () {
        return db.find({
          "selector": {"foo": {$exists: true}},
          "sort": ["foo"]
        });
      }).then(function (resp) {
        resp.docs.should.deep.equal([
          {"_id": "a", "foo": "a"},
          {"_id": "b", "foo": "b"}
        ]);
      }).catch(function (resp) {
        console.log(resp);
        throw resp;
      });
    });
```

@willholley is there a reason for this, is it a bug that needs fixed in both?

**Comment by willholley** [comment]
@daleharvey I'd expect that to work against CouchDB so long as an index is created on `["foo"]` (sort always needs an index). It looks like the test doesn't create an index; does it fail with a missing index error or does the assertion fail?

**Comment by daleharvey** [comment]
ok yup you are right, 

```
    it('sorts correctly - foo exists wtf', function () {
      var db = context.db;
      var index = {
        "index": {
          "fields": [{"foo": "desc"}]
        },
        "name": "foo-index",
        "type": "json"
      };
      return db.createIndex(index).then(function () {
        return db.bulkDocs([
          {_id: 'a', foo: 'b'},
          {_id: 'b', foo: 'a'},
          {_id: 'c', foo: 'c'},
          {_id: '0', foo: 'd'}
        ]);
      }).then(function () {
        return db.find({
          "selector": {"foo": {$exists: true}},
          "fields": ["foo"],
          "sort": ["foo"]
        });
      }).then(function (resp) {
        console.log(resp);
        resp.docs.should.deep.equal([
          {"foo": "a"},
          {"foo": "b"},
          {"foo": "c"},
          {"foo": "d"}
        ]);
      });
    });
``` 

works against couch, fails against pouch, cheers

**Comment by popod** [comment]
No more activity, but I think this should be resolved as said in my previous comment.

@nolanlawson @daleharvey what about this issue ?

**Comment by mikilion** [comment]
I encountered same issue with selector $regex
