### ISSUE TITLE
can't use index with $or operator

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6271]
_From @noradaiko on March 9, 2016 10:23_

Getting usable index not found error on running the code below:

``` JavaScript
db.createIndex({
  index: {
    fields: ['updatedAt', '_id']
  }
}).then(function() {

  return db.find({
    selector: {
      _id: {
        $gte: 'note:',
        $lte: 'note:\uffff'
      },
      $or: [
        { markdown: { $regex: regex } },
        { title: { $regex: regex } }
      ],
      updatedAt: {
        $gt: null
      }
    },
    sort: [
      { updatedAt: 'desc' }
    ]
  });

}).then(function(result) {
  console.log(result);
}).catch(function(e) {
  console.log(e);
});
```

```
Error: couldn't find a usable index. try creating an index on: updatedAt, $or, _id. Make sure that only $eq, $gt, $gte, $lt, and $lte are used for the indexed fields.
```

It seems that `$or` is incorrectly determined as a field.
Or, am I using `$or` wrong way?

_Copied from original issue: nolanlawson/pouchdb-find#165_

**Comment by nolanlawson** [comment]
_From @garrensmith on March 9, 2016 10:30_

Thats a bug. Thanks for reporting.

**Comment by nolanlawson** [comment]
_From @carlosmbolanos on March 19, 2016 13:37_

Same here.
@noradaiko, Did you find a workaround for this?

**Comment by nolanlawson** [comment]
_From @noradaiko on March 20, 2016 21:28_

@carlosmbolanos Using `query` for now

**Comment by mattjennings** [comment]
I am having this issue. Using pouchdb with angularjs 1.4, Chrome v59. I can query off my index properly until I include an $or in the selector, then it forces me into using the default index.
