### ISSUE TITLE
No view error the first time, but works fine afterward.

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6272]
_From @5amfung on February 22, 2016 20:54_

I'm trying to following the suggestion in http://pouchdb.com/2014/05/01/secondary-indexes-have-landed-in-pouchdb.html to start building the index as soon as the index is created.  However, I always get the following error first time when indexeddb is empty.  It's always the first time with an empty indexeddb.  It works afterward.

```
not_found: ddoc folders_view has no view named folders_view
```

Code

```
    let viewName = 'folders_view';
    this.db.createIndex({
        index: {
            ddoc: viewName,
            name: viewName,
            fields: ['name']
        }
    }).then(result => {
        if (result.result === 'created') {
            this.db.query(viewName, { stale: 'update_after' });
        }
    }).catch(console.error.bind(console));
```

_Copied from original issue: nolanlawson/pouchdb-find#163_

**Comment by nolanlawson** [comment]
Yeah, seems like a bug. Thanks for reporting!

**Comment by nolanlawson** [comment]
_From @malfusion on November 2, 2016 20:41_

Is this bug fixed? I keep running into the same issue once in a while. Is there any way we can be notified when the index views are ready to be used? A hook maybe?

**Comment by rvanzon** [comment]
I have the problem with a simple:

```javascript
db.createIndex({
      index: {
        fields: ['type']
      }
    })
```
is there a workaround maybe?

**Comment by rvanzon** [comment]
If I add `ddoc: 'search'` I get:

`"ddoc search has no view named idx-01781f92d7830b6faacfc00254833392"`

No doc with _id  idx-01781f92d7830b6faacfc00254833392 exists.

**Comment by garrensmith** [comment]
Could you give us some detailed steps to reproduce.

All misspelling thanks to my iPhone.
________________________________
