### ISSUE TITLE
Can't use regexex modifiers for $regex

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6274]
_From @mfilotto on February 14, 2016 8:53_

Would be nice to have a way to set case insensitive modifier with $regex
A mango DSL limitation I guess ?

_Copied from original issue: nolanlawson/pouchdb-find#158_

**Comment by nolanlawson** [comment]
_From @garrensmith on February 14, 2016 11:29_

It should be standard regex. So pouchdb-find is JavaScript regex and mango is erlang regex. So that should work. If it doesn't a failing test would really help us fix it. 

All misspelling thanks to my iPhone

**Comment by nolanlawson** [comment]
_From @mfilotto on February 14, 2016 21:2_

Here is the code to do the exact test they have in Mango
Do you prefer a PR ?

```
    it('should do a regex search with case sensitive modifier ', function () {
      var db = context.db;
      var index = {
        "index": {
          "fields": ["name"]
        }
      };
      return db.createIndex(index).then(function () {
        return db.find({
          selector: {
            name: {$gte: null},
            series: {$regex: "(?i)Mario.*"}
          },
          sort: ['name']
        }).then(function (resp) {
          var docs = resp.docs.map(function (doc) {
            delete doc._rev;
            return doc;
          });

          docs.should.deep.equal([
            { name: 'Donkey Kong', rank: 7, _id: 'dk', series: 'Mario',
              debut: 1981, awesome: false },
            { name: 'Luigi', rank: 11, _id: 'luigi', series: 'Mario', debut: 1983, awesome: false },
            { name: 'Mario', _id: 'mario', rank: 5, series: 'Mario', debut: 1981, awesome: true },
            { name: 'Yoshi', _id: 'yoshi', rank: 6, series: 'Mario', debut: 1990, awesome: true },
          ]);
        });
      });
    });
```

**Comment by nolanlawson** [comment]
_From @garrensmith on February 15, 2016 10:5_

That regex is how erlang does it. For that to work in pouchdb you need to follow these rules

https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions#Advanced_searching_with_flags

**Comment by nolanlawson** [comment]
_From @mfilotto on February 15, 2016 20:35_

You're right the right pattern would be more like `/mario.*/i`
The problem is that RegExp constructor splits modifiers/flags from the rest of the pattern :
`new RegExp(pattern[, flags])` 

So maybe pouchdb-find could extract that part from `userValue` and call the constructor with modifiers here : 
https://github.com/nolanlawson/pouchdb-find/blob/0458b74d445457c55bc01096a19c3e35e6115045/lib/adapters/local/find/in-memory-filter.js#L188

**Comment by nolanlawson** [comment]
_From @garrensmith on February 16, 2016 6:57_

Nice catch. This is a nice first fix if you want to do the work? I'm happy to help you where you need.

**Comment by nolanlawson** [comment]
_From @mfilotto on February 16, 2016 11:10_

@garrensmith OK I'm on it

**Comment by nolanlawson** [comment]
_From @mfilotto on February 20, 2016 1:33_

@garrensmith need help, I have a hard time running tests.
They reach my couchdb but fail with error `Something wrong with the request`
My db is launched from a docker-compose up : https://github.com/mfilotto/docker-geocouch.git
Any idea ?

**Comment by nolanlawson** [comment]
_From @garrensmith on February 20, 2016 14:56_

You need to use CouchDB 2.0 or if you using docker from `klaemo/couchdb:2.0-dev`. You most have only 1 node running ideally on port `15984` You also need to enable cors by running this https://github.com/nolanlawson/pouchdb-find/blob/master/bin/enable-couchdb-cors.sh

**Comment by nolanlawson** [comment]
_From @mfilotto on February 21, 2016 22:31_

@garrensmith ok I'll try this config

**Comment by nolanlawson** [comment]
_From @natcohen on March 4, 2016 6:26_

@mfilotto any news about this?

**Comment by nolanlawson** [comment]
_From @mfilotto on March 7, 2016 20:35_

@natcohen I'm stuck with the docker env.
I can't have `klaemo/couchdb:2.0-dev`working to replay all the tests

**Comment by nolanlawson** [comment]
_From @natcohen on March 7, 2016 21:27_

@mfilotto unfortunately not into docker stuff...can't you install the normal version? Or even test it on cloudant? Maybe @garrensmith can help with docker

**Comment by nolanlawson** [comment]
_From @mfilotto on March 7, 2016 22:8_

Here is my reflexion for that feature.
It would be nice to add modifiers but I face several interrogations.

My first approach is to parse the given string and extract the modifier if the pattern of the string is something like `'/pattern/modifier'`

This could be easilly done. But it is semanctically wrong in regard to the [RegExp Javascript object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) that can be created eather through a `constructor('pattern', 'modifier')` or with a litteral notation`/pattern/modifier`

But if we accept litteral notation how the users will dynamically create that notation ?

Do you think that we can accept the notation `'/pattern/modifier'` anyway ?

**Comment by nolanlawson** [comment]
_From @natcohen on March 7, 2016 23:20_

I think that it would be a good start to accept the literal notation

**Comment by nolanlawson** [comment]
_From @colinskow on May 11, 2016 8:32_

For a local PouchDB query you can simply pass in a Javascript object `/mario/i`. I'll ask Cloudant support how they handle flags since it isn't in the documentation.

**Comment by nolanlawson** [comment]
_From @garrensmith on May 11, 2016 8:35_

I don't think we can. Underneath Regex for Cloudant Query/CouchDB mango is
just erlang regex. So it will always be a little different compared to
javascript regex.
https://github.com/apache/couchdb-mango/blob/master/src/mango_selector.erl#L496

**Comment by nolanlawson** [comment]
_From @colinskow on May 11, 2016 9:4_

I verified that I can pass in a literal Javascript regex object to a local `pouchdb-find`, but of course that won't work with Cloudant or CouchDB.

**Comment by nolanlawson** [comment]
@colinskow That sounds like a reasonable workaround; you can just use regular regexes for local and string regexes for remote. Closing unless someone thinks there's a fix we can reasonably do for this.

**Comment by nolanlawson** [comment]
_From @colinskow on May 16, 2016 0:2_

There are two REGEX flags that Erlang and Javascript have in common, `i` for case insensitive and `m` for multiline.

In Erlang this is accomplished by prefixing the regex string with `(?im)`. This is invalid in Javascript and will throw an error. In Javascript there is no way to set flags directly from the regex string.

What I want to do for local is search for `(?[flags])` at the beginning of the string, and convert to Javascript regex.

For remote search, if the user passes in a Javascript regex object with flags `i` or `m` set, it will convert this to an Erlang string.

How does that sound @nolanlawson ?

**Comment by nolanlawson** [comment]
_From @colinskow on May 16, 2016 0:2_

See: http://stackoverflow.com/questions/37157723/cloudant-query-couchdb-mango-how-to-set-regex-flags

**Comment by nolanlawson** [comment]
> What I want to do for local is search for (?[flags]) at the beginning of the string, and convert to Javascript regex.

Hmmm, I'd kinda prefer to have a more foolproof method. Can we accept a JavaScript regex and then convert it to a string and possible an Erlang regex string as necessary? When you call `.toString()` on a JavaScript regex, it seems we can determine whether it's case-insensitive or not:

```
> /foo/i.toString()
'/foo/i'
```

**Comment by nolanlawson** [comment]
_From @colinskow on May 19, 2016 22:53_

I think the goal is to have the behavior as similar as possible across both Cloudant/CouchDB 2.0 and local PouchDB.

In Cloudant:

``` json
"series": {
      "$regex": "(?i)mario"
    }
```

will do a case insensitive search for "mario". We should translate this to Javascript so it will work on a local `pouchdb-find`. And if the user passes a Javascript RegEx object to a remote `find`, we can check for the `i` and `m` flags and convert it to an Erlang expression.

We'll never be able to guarantee that Erlang and Javascript regexes will perform exactly the same, but we can support major use cases where the API is equivalent.

**Comment by nolanlawson** [comment]
_From @llin96 on June 23, 2016 3:4_

I test this and it works

``` javascript
var regexp = new RegExp(keyword, 'i');
{name: {'$regex': regexp}};
```

**Comment by nolanlawson** [comment]
_From @rhysdavies1994 on November 24, 2016 6:30_

thank you @llin96! this may be handy on the readme until a built-in solution is implemented?

**Comment by manikandan07081995** [comment]
@nolanlawson  My requirement is to search without insensitive.I follow as you said "(?i)mario".But i got error like this "**Invalid regular expression: /(?i)Mario.*/: Invalid group**".Kindly give any suggestion on this issue.

Extra Info: I have created the ionic Web app.I am using CouchDB and PouchDB for data.Fetch records from pouchDB using "db.find" with selector.Search data in pouch insensitive case.

**Comment by Prabuganesan** [comment]
@manikandan07081995 Try this for pouchdb find

**var regexp = new RegExp(keyword, 'i');
{name: {'$regex': regexp}};**

If you want to find in couchdb then try this

**{ name:$regex: "(?i)prabu.*" }**
