### ISSUE TITLE
Combining multiple selectors makes the query really slow

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6275]
_From @martinwoitzik on February 13, 2016 16:53_

Hi there,
I'm developing an app with Ionic where you can filter different kind of lists. The list of items was saved via PouchDB and has about 20.000 JSON-entries - each with all kind of attributes like title, description, color, year, type, manufacturer etc.
Unfortunately the filtering of items takes really long when I add more than one filter-attribute. For example I want to sort the list by title/ ascending combined with filtering for a specific year and a high rating. So my find-query looks something like this:

``` javascript
db.find({
  selector: {
     'title': { $gt: null },
     'year': { $eq: 2005 },
     'rating': { $gt: 3 }
  },
  limit: 20,
  sort: [{'title': 'asc'}]
});
```

Testing this query in Chrome (desktop) sometimes takes more than 10 seconds to complete (on a mobile device, depending on it's CPU you have to wait for about a minute or longer!) - even if I build an index right before doing the query. It doesn't really matter if there is an index only on "title" available or on all three of the given attributes. 
When I execute the query with only one attribute the execution time is ok (about 50-200ms).

Is this a problem with the pouchdb-find plugin or with WebSQL or am I doing something completely wrong? Or are 20.000 items just too much to handle on local-databases? (hopefully not!)

_Copied from original issue: nolanlawson/pouchdb-find#157_

**Comment by nolanlawson** [comment]
_From @martinwoitzik on February 15, 2016 20:43_

Does anyone have a suggestion on this issue?

**Comment by nolanlawson** [comment]
The problem with joining selectors in `pouchdb-find` is that it will run one selector on the database, and the other in-memory. I believe you can structure your query such that the most expensive selector is run first (and therefore not in-memory), but you may need to use `$and` in order to get this to work.

BTW if you enable debug mode, you can see how the query is being compiled, which gives you some insight into it.

**Comment by nolanlawson** [comment]
_From @martinwoitzik on February 16, 2016 9:51_

I tried the $and operator. But it doesn't seem to improve anything. No matter which selector I put first.
I also read about $and in the Cloudant Documentation and it says that you don't have to set it explicitly because it will be applied implicitly for multiple selectors.

Are there any other options I could try?

**Comment by nolanlawson** [comment]
My suggestion would be to use pouchdb-find only for the thing that's indexed, and then do the other stuff in-memory yourself using JavaScript. Otherwise add a new index on `[year, title, rating]`.

TBQH the fact that pouchdb-find does stuff in-memory that the user can just as easily do him/herself in JavaScript was perhaps a design failure, because it hides aspect of the query that will inevitably be slow due to the proper index not having been created.

**Comment by nolanlawson** [comment]
_From @renato on April 15, 2016 19:57_

@nolanlawson It currently runs one selector on the database and the other in-memory, but will it change in the future (passing the `$and` conditions to the backends)?

**Comment by nolanlawson** [comment]
Unfortunately it is modeled after the CouchDB Mango query engine, which does not do the optimization you describe. So the answer sadly is no.

To work around this, you can use map/reduce to index on multiple values in an array (`emit([foo, bar, baz])` and then query those values.

**Comment by nolanlawson** [comment]
_From @Antoniomm80 on April 21, 2016 12:27_

Hi all
We were facing a similar issue. We managed to fix it by changing the order of the fields when creating the index.

If we create the index like this

```
localDB.createIndex({
                  index: {
                    fields: ['timestamp','type','chatId']
                  }
                })
```

our find call takes around 30 seconds for retrieving 100 registers but changing the order of the fields array to

```
localDB.createIndex({
                  index: {
                    fields: ['chatId','timestamp','type']
                  }
                })
```

does the trick and the find call only takes 0,4 seconds.

**Comment by nolanlawson** [comment]
@Antoniomm80 Yes, if you can put your fields that narrow down the number of records _first_, then your query will perform much better. Most likely your chatId narrows down the search field much more than timestamp or type.

**Comment by nolanlawson** [comment]
Closing because some queries are just going to be slow; it's important to optimize indexes/queries

**Comment by useitsoftware** [comment]
We are facing similar problems with a single index item query, please reopen, over 2.5 seconds for 40 registries.
The index creation:

`this.db.createIndex({
            index: {
                fields: ['type']
            }
        }).then(function (result) {
            console.log(result);
        }).catch(function (err) {
            console.log(err);
        });`

the querying:

  ```
getBy(type: String) {
        let context = this;
        this.db.find({
            selector: {type: {$eq: type}}
        }).then(function (result) {
            console.log(res);
        }).catch(function (err) {
            console.log(err);
        });
    }

```

**Comment by garrensmith** [comment]
Which backend are you using? Can you try without creating an index first.

**Comment by useitsoftware** [comment]
none, using pouchDB as a purely local database.
