### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'startkey' in undefined(…)

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6277]
_From @agozie on January 29, 2016 12:18_

I upgraded to 0.9.0 from 0.7.0. I started getting this: `TypeError: Cannot use 'in' operator to search for 'startkey' in undefined(…)` for this query :
 `db.find({
        selector: {
          tID: this.test.tID,
          due: {
            $exists: true
          },
          terms: {
            $exists: true
          }
        }
      })`
What am I doing wrong please?

_Copied from original issue: nolanlawson/pouchdb-find#153_

**Comment by nolanlawson** [comment]
_From @garrensmith on January 29, 2016 12:52_

I'm not sure. If you could add a failing test in a PR I can then take a look. 

All misspelling thanks to my iPhone

**Comment by nolanlawson** [comment]
_From @andrewdep on March 3, 2016 1:22_

I'm seeing this too... Did you figure out what was going wrong, @agozie?

**Comment by nolanlawson** [comment]
_From @natcohen on May 18, 2016 18:33_

Have the same problem here...

**Comment by nahueld** [comment]
I'm having this issue on a filter like this:
```
{
	"selector": {
		"productName": /.*/,
		"categories": {
			"$elemMatch": {
				"$in": ["Oficina", "Resmas"]
			}
		},
		"brand": {
			"$in": ["LEDESMA"]
		}
	},
	"limit": 10,
	"skip": 0
}
```
for some reason seems to happen when trying to use 2 $in clauses

**Comment by sadrodin1376** [comment]
Hi,
I'm having this issue on this selector:
`{'$or':[{asker:{'$in':ids}},{sureties:{'$elemMatch':{'$in':ids}}}]}`
