### ISSUE TITLE
Document pouchdb-collate on pouchdb.com

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6299]
Currently the documentation for this module only lives at http://github.com/pouchdb/collate . But since that repo has been moved over here, it should be documented on pouchdb.com instead.

**Comment by letsila** [comment]
Hi @nolanlawson, I'll be glad to help on this. Where and how should I start?

**Comment by letsila** [comment]
I've just installed the docs locally via all the steps on the building docs guide and it seems that the pygments highlighter doesn't work anymore on Jekyll 3.1.3. It's causing the doc build failed.
<img width="1163" alt="screen shot 2017-06-18 at 13 47 34" src="https://user-images.githubusercontent.com/4066051/27260133-bf6fa2ba-542c-11e7-8af9-2e19009b0d0d.png">
