### ISSUE TITLE
Promises and Pouchdb

### ISSUE THREAD

**Issue by tshad** [pouchdb/pouchdb#6305]
I am using PouchDB to handle some local database processing and I am having an issue setting up my promise to work correctly.

 In essence I have the following:

MY CODE
...
   }).then(function () {
      return initialize();
   }).then(function () {
      return _**updateWorkIssuesJson();**_
   }).then(function () {
      return showTasks();
   }).catch(function (err) {
      showMsg("Error in defineDBs: " + err);
   }) 
 
END MY CODE

 In "initialize" I have a couple of async routines that read from the PouchDB database. I turned initialize into a promise to stop it from going to "updateWorkIssuesJson" and then "showtasks" before initialize was finished. But it still jumps out of initialize before it is finished. All I did was create an anonymous routine and put a couple of "Deferred" statements in the but it still jumps out when it hits the Async routines.

Also, ReloadWorkIssues also has a bunch of calls to pouch.

I am trying to make sure all of the code in the initialize function is done before the code jumps to the the updatworkIssuesJson function.  But everytime I hit a pouch command, it jumps outside of the promises.

 Am I doing something wrong?

 My code is a little large but it really isn't the issue.

 I just took the "initialize" function and made it variable that has the function in it and added the promise (deferred) code around it.

MY CODE

var initialize = function () {

   _**var deferred = new $.Deferred();**_

 if (CTL_HiddenFirstTime.val() == "True") {
      var updated = [];
      CTL_HiddenFirstTime.val("False");

      return DB_WorkIssues.allDocs({ include_docs: true, descending: false }, function (err, response) {
         data = response.rows;
         itemp = 0;

         **_for (var i = 0; i < response.total_rows; i++) {_**
            if (data[i].doc.IsDeleted || data[i].doc.IsWorkIssueInserted || data[i].doc.IsWorkIssueUpdated || data[i].doc.IsLogInserted) {
               DirtyFlag = true;
               updated[itemp++] = data[i];
            }
         }
         CTL_HiddenJsonWorkIssues.val(JSON.stringify(updated));
      }).then(function () {
         return DB_Certificates.allDocs({ include_docs: true, descending: false }, function (err, response) {
            data = response.rows;
            updated = [];
            itemp = 0;

            for (var i = 0; i < response.total_rows; i++) {
               if (data[i].doc.IsUpdated) {
                  DirtyCertFlag = true;
                  updated[itemp++] = data[i];
               }
            }
            CTL_HiddenJsonCertificates.val(JSON.stringify(updated));

            if (DirtyFlag || DirtyCertFlag) {
               GetDirtyRecords();
            }

            ReloadWorkIssues();
         });
      });

   }
   else if (CTL_HiddenSyncWorklist.val() == "True") {
      CTL_HiddenSyncWorklist.val("False");
      ReloadWorkIssues();
   }

   **_deferred.resolve(null);
   return deferred.promise();_**
} 

END OF MY CODE

 I have breaks in my code and I am at the first "for" statement and then it jumps to the "updateWorkIssuesJson" function then back again.

 Is there something else I need to do?

 Thanks,

 Tom

**Comment by mnewmedia** [comment]
Reading your issue hurts my eyes ;) Please take 5 minutes and look into [Mastering-Markdown](https://guides.github.com/features/mastering-markdown/) to learn how to format you issue a bit better.

**Comment by garrensmith** [comment]
@mnewmedia, I do agree the original issue is hard to read, but I don't think telling someone they have to fully understand markdown before they can submit issues is correct. It doesn't create a welcoming and open community.

I've done a quick format of the issue below for clarity.
@tshad for future reference whenever you have a code block, always surround it with ` ``` ` and it will be formatted nicely.


I am using PouchDB to handle some local database processing and I am having an issue setting up my promise to work correctly.

In essence I have the following:

```
}).then(function () {
return initialize();
}).then(function () {
return updateWorkIssuesJson();
}).then(function () {
return showTasks();
}).catch(function (err) {
showMsg("Error in defineDBs: " + err);
})
```

In `initialize` I have a couple of async routines that read from the PouchDB database. I turned initialize into a promise to stop it from going to `updateWorkIssuesJson` and then `showtasks` before initialize was finished. But it still jumps out of initialize before it is finished. All I did was create an anonymous routine and put a couple of "Deferred" statements in the but it still jumps out when it hits the Async routines.

Also, `ReloadWorkIssues` also has a bunch of calls to pouch.

I am trying to make sure all of the code in the `initialize` function is done before the code jumps to the the `updatworkIssuesJson` function. But everytime I hit a pouch command, it jumps outside of the promises.

Am I doing something wrong?

My code is a little large but it really isn't the issue.

I just took the `initialize` function and made it variable that has the function in it and added the promise (deferred) code around it.

```
var initialize = function () {

var deferred = new $.Deferred();

if (CTL_HiddenFirstTime.val() == "True") {
var updated = [];
CTL_HiddenFirstTime.val("False");

  return DB_WorkIssues.allDocs({ include_docs: true, descending: false }, function (err, response) {
     data = response.rows;
     itemp = 0;

     **_for (var i = 0; i < response.total_rows; i++) {_**
        if (data[i].doc.IsDeleted || data[i].doc.IsWorkIssueInserted || data[i].doc.IsWorkIssueUpdated || data[i].doc.IsLogInserted) {
           DirtyFlag = true;
           updated[itemp++] = data[i];
        }
     }
     CTL_HiddenJsonWorkIssues.val(JSON.stringify(updated));
  }).then(function () {
     return DB_Certificates.allDocs({ include_docs: true, descending: false }, function (err, response) {
        data = response.rows;
        updated = [];
        itemp = 0;

        for (var i = 0; i < response.total_rows; i++) {
           if (data[i].doc.IsUpdated) {
              DirtyCertFlag = true;
              updated[itemp++] = data[i];
           }
        }
        CTL_HiddenJsonCertificates.val(JSON.stringify(updated));

        if (DirtyFlag || DirtyCertFlag) {
           GetDirtyRecords();
        }

        ReloadWorkIssues();
     });
  });
}
else if (CTL_HiddenSyncWorklist.val() == "True") {
CTL_HiddenSyncWorklist.val("False");
ReloadWorkIssues();
}

deferred.resolve(null);
return deferred.promise();
}
```


I have breaks in my code and I am at the first `for` statement and then it jumps to the `updateWorkIssuesJson` function then back again.

Is there something else I need to do?

Thanks,

Tom

**Comment by garrensmith** [comment]
Looking at your code @tshad, I think you fully understand how promises work and that is your main issue. I think a better way to write your initialize function is to use [Promise.all](http://bluebirdjs.com/docs/api/promise.all.html). You are also mixing callbacks and promises which can be really confusing.

So your initialise function should look something like this:

```
function initialise () {
   var promises = []
   if (CTL_HiddenFirstTime.val() === "True") {
      var allDocsPromise = DB_WorkIssues.allDocs().then(/*leaving out all this code to save space */)
      promises.push(allDocsPromise)
   } else if (CTL_HiddenSyncWorklist.val() === "True") {
      CTL_HiddenSyncWorklist.val("False");
       var anotherPromise = ReloadWorkIssues();
       promises.push(anotherPromise);
  }

   return Promise.all(promises);
}

```
That way the promise will only resolve once ALL your async functions are complete. I've completely oversimplified your code, but hopefully that helps you.

Also this is a great article to help you with promises. https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html

Finally don't use `$.Deferred()` they are not real promises. Rather use the built in PouchDB Promise or Bluebird.js

**Comment by garrensmith** [comment]
Closing since its not a pouchdb issue.

**Comment by nolanlawson** [comment]
@garrensmith In the future: you can edit anybody's comments as long as you're an owner of this repo. I do it all the time when folks forget to add formatting, or sometimes I use `<details>/<summary>` if they paste long console output.

@tshad Garren's right, and also FWIW your question would probably be a good one for StackOverflow if you're still stuck. Promises are hard to work with, and mastering `Promise.all()` can be very tricky especially if you're more used to synchronous code.

**Comment by tshad** [comment]
I understand why the issue might look like a promise and not a pouch issue but the question had to do with pouch and it really is both, I believe.  I agree that I am new to promises.  I was using Deferred because that was what I found first.  I am going to change it to a promise next.

But my question had to do with putting your promise inside of a promise.  Was that causing my issue?

Everything was running fine until I called your alldocs promise.

I thought that the original call to initialize would not continue until it was resolved.  But it went to the updateWorkIssuesJson as soon as I called your alldocs promise.

I didn't know if it was a promises issue or an alldocs issue.

Should I not call a promise chain inside of another promise?

Thanks.

**Comment by nolanlawson** [comment]
Hi @tshad, sorry if the response came across as harsh. It's just that we see lots of folks struggling with promises and often their issues stem from a misunderstanding of promises rather than a misunderstanding of PouchDB _per se_. That's why I strongly recommend [we have a problem with promises](https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html); I've heard from many folks that it's useful even if it's a long read. I've known folks who have even organized classes/workshops around it. 🙂 It explains why `Deferred` is not recommended and how to use `Promise.all()`.

`allDocs()` returns a promise. It's fine to return a promise from within `.then()` but mostly the problem you're going to run into is that you're wrapping an entire promise change inside of `Deferred` which is a not-very-promisey pattern (it's used more for wrapping promises around *non-promise-based* code). I.e. it essentially forces you to treat promise-based APIs as if they are callback-based APIs which tends to lead to lots of bugs.

Your code is a bit complex, but here is some advice to help you out:

1. Remove Deferred entirely, just return a promise
2. Inside of your `.then()` functions (i.e. `.then(function () {/* RIGHT HERE */})`) check to see if you always call `return` or not. If you don't call `return` then it is almost always a programmer error.

Also again, a better venue would probably be StackOverflow or the slack.pouchdb.com since these kinds of conversations can be very difficult on GitHub. But I hope my comments have helped!

**Comment by tshad** [comment]
Hi @nolanlawson,

Your comments did help.

I did convert the defers to promises and it stopped jumping out to the outside promise chain before it was done.

But you mentioned being able to do a promise in a promise and I tried that with your promise (allDocs) and it hits the allDocs statement then jumps straight to the resolve and out to the outer promises (updateWorkIssuesJson) and them back to the (for loop).  Do I need to put something in the allDocs function to prevent that?

Here is the code (two promises and a promise chain).

var initialize = function () {
   return new Promise(function (resolve, reject) {
      resolve("Done with Initialize");
   });
};

var SetAnyUpdatedRecords = function (message) {
   return new Promise(function (resolve, reject) {
      var updated = [];

      DB_WorkIssues.allDocs({ include_docs: true, descending: false }, function (err, response) {
         data = response.rows;
         itemp = 0;

         for (var i = 0; i < response.total_rows; i++) {
            if (data[i].doc.IsDeleted || data[i].doc.IsWorkIssueInserted || data[i].doc.IsWorkIssueUpdated || data[i].doc.IsLogInserted) {
               DirtyFlag = true;
               updated[itemp++] = data[i];
            }
         }
         CTL_HiddenJsonWorkIssues.val(JSON.stringify(updated));
         return;
      }).then(function () {
      }).catch(function (err) {
         showMsg("Error in SetAnyUpdatedRecords: " + err);
      });
      resolve();
   });
};

...
   }).then(function () {
      return initialize();
   }).then(function(message) {
      return SetAnyUpdatedRecords(message);
   }).then(function () {
      return updateWorkIssuesJson();
   }).then(function () {
      return showTasks();
   }).catch(function (err) {
      showMsg("Error in defineDBs: " + err);
   })

When I get into the SetAnyUpdateRecords promise, I find that "message" doesn't have the message I passed, but that would be a promise question.

Thanks,

Tom

**Comment by garrensmith** [comment]
Sorry Tom, we can't help you any further. You need to use stackoverflow or something else. This is for actual PouchDB issues, bugs and future work. 
You just need to read up on promises and you should come right.

All misspelling thanks to my iPhone.




On Mon, Mar 6, 2017 at 8:14 PM +0200, "tshad" <notifications@github.com> wrote:












Hi @nolanlawson,


Your comments did help.


I did convert the defers to promises and it stopped jumping out to the outside promise chain before it was done.


But you mentioned being able to do a promise in a promise and I tried that with your promise (allDocs) and it hits the allDocs statement then jumps straight to the resolve and out to the outer promises (updateWorkIssuesJson) and them back to the (for loop).  Do I need to put something in the allDocs function to prevent that?


Here is the code (two promises and a promise chain).


var initialize = function () {

return new Promise(function (resolve, reject) {

resolve("Done with Initialize");

});

};


var SetAnyUpdatedRecords = function (message) {

return new Promise(function (resolve, reject) {

var updated = [];
  DB_WorkIssues.allDocs({ include_docs: true, descending: false }, function (err, response) {
     data = response.rows;
     itemp = 0;

     for (var i = 0; i < response.total_rows; i++) {
        if (data[i].doc.IsDeleted || data[i].doc.IsWorkIssueInserted || data[i].doc.IsWorkIssueUpdated || data[i].doc.IsLogInserted) {
           DirtyFlag = true;
           updated[itemp++] = data[i];
        }
     }
     CTL_HiddenJsonWorkIssues.val(JSON.stringify(updated));
     return;
  }).then(function () {
  }).catch(function (err) {
     showMsg("Error in SetAnyUpdatedRecords: " + err);
  });
  resolve();



});

};


...

}).then(function () {

return initialize();

}).then(function(message) {

return SetAnyUpdatedRecords(message);

}).then(function () {

return updateWorkIssuesJson();

}).then(function () {

return showTasks();

}).catch(function (err) {

showMsg("Error in defineDBs: " + err);

})


When I get into the SetAnyUpdateRecords promise, I find that "message" doesn't have the message I passed, but that would be a promise question.


Thanks,


Tom

**Comment by tshad** [comment]
You probably won't answer this one but I did what was suggested and I put together as well as researched promises and I cannot find anything that handles my scenario.

I used a sample set of promises that work perfect until I add the pouch allDocs call in.

It works fine when I chain directly on the allDocs call.  But Nolan said we could put a promise in a promise but that does not seem to be the case.

The reason I have it set up the way I do and why it would be difficult to use Promise.All() is because I don't want the promises executing all at one.  I want one promise to follow another.

I stripped everything out only showing one promise that has your pouch call in it.  May this cannot be done.

Here is my promise with console.logs in them so you can see the path.

My promise:

```
let cleanRoom = function () {
   return new Promise(function (resolve, reject) {

      console.log("starting cleanRoom");
      console.log("starting DB_WorkIssue.alldocs");
      DB_WorkIssues.allDocs({ include_docs: true, descending: false }, function (err, response) {
         data = response.rows;
         itemp = 0;

         console.log("at For Loop in allDocs");

         for (var i = 0; i < response.total_rows; i++) {
            if (data[i].doc.IsDeleted || data[i].doc.IsWorkIssueInserted || data[i].doc.IsWorkIssueUpdated || data[i].doc.IsLogInserted) {
               DirtyFlag = true;
            }
         }
         console.log("exiting allDocs");

         return;
      }).then(function () {
         console.log("inside then function after alldocs");
      }).catch(function (err) {
         console.log("inside catch");
         showMsg("Error in cleanRoom/allDocs: " + err);
      });

      console.log("exiting cleanRoom")
      resolve('Cleaned The Room');
   });
};

```
All it does is call the allDocs method and then in the function look to see if any records have been updated.  Then it can continue on.

But that is not what is happening.

Here is the chain:

```
   }).then(function () {
      return initialize();
   }).then(function (prMessage) {
      **return cleanRoom();**   <--- my promise
   }).then(function (result) {
      return removeGarbage(result);
   }).then(function (result) {
      return winIcecream(result);
   }).then(function (result) {
      console.log('finished ' + result);
   }).then(function () {
      console.log("starting UpdateworkIssuesJson");
      return updateWorkIssuesJson();
   }).then(function () {

``` 
the results:

```
tasksmain.js:165 starting cleanRoom
tasksmain.js:166 starting DB_WorkIssue.alldocs     <-- Pouch call
tasksmain.js:188 exiting cleanroom                        <-- exits promise
tasksmain.js:195 inside removeGarbage                 <-- I don't want it to do this until Pouch call is done.
tasksmain.js:202 inside winIceCream
taskspouch.js:91 finished Cleaned The Room remove Garbage won Icecream
taskspouch.js:93 starting UpdateworkIssuesJson
tasksmain.js:182 inside then function after alldocs   <-- now back to the pouch function call (way too late.
tasksmain.js:171 at For Loop in allDocs
tasksmain.js:178 exiting allDocs                    <--- Pouches chain
taskspouch.js:96 starting showTasks

```
The question is - the original promise chain is working as it is supposed to.

It continues on when the "cleanroom" resolves.  But the cleanroom resolves before the Pouch command is finished.

Is there a way to prevent that?

**Comment by tshad** [comment]
I also noticed that the "then" of the allDocs function happens before the for loop does.  Isn't the "then" supposed to happen when the allDocs promise is done???

**Comment by mnewmedia** [comment]
```js
let cleanRoom = function () {
   return new Promise(function (resolve, reject) { // PM: only make a new promise for a asynchron function that's not already a promise. But allDocs is already promise based, so instead of creating a new promise return the promise from the allDocs function

      console.log("starting cleanRoom");
      console.log("starting DB_WorkIssue.alldocs");
      // you still mix, decide if you wanna use callback style or promises. allDocs(options, callback),
      // don't use the second parameter from allDocs and instead use the .then(callback)
      DB_WorkIssues.allDocs({ include_docs: true, descending: false }, function (err, response) {
         data = response.rows;
         itemp = 0;

         console.log("at For Loop in allDocs");
Attach files by dragging & dropping,  Dateien auswählen selecting them, or pasting from the clipboard.
         for (var i = 0; i < response.total_rows; i++) {
            if (data[i].doc.IsDeleted || data[i].doc.IsWorkIssueInserted || data[i].doc.IsWorkIssueUpdated || data[i].doc.IsLogInserted) {
               // what's this? you call this allDocs function to get this boolean value? then return it with the promise
               DirtyFlag = true;
            }
         }
         console.log("exiting allDocs");

         return; // why are you returning undefined here? there is no reason for that
      }).then(function () { // this is promise style, decide if you wanna use callback or promise style..
         console.log("inside then function after alldocs");
      }).catch(function (err) {
         console.log("inside catch");
         showMsg("Error in cleanRoom/allDocs: " + err);
      });

      console.log("exiting cleanRoom")
      resolve('Cleaned The Room');
   });
};
```

```js
let cleanRoom = function () {

      console.log("starting cleanRoom");
      console.log("starting DB_WorkIssue.alldocs");
      return DB_WorkIssues.allDocs({ include_docs: true, descending: false }).then(function (err, response) {
         data = response.rows;
         itemp = 0;

         console.log("at For Loop in allDocs");

         for (var i = 0; i < response.total_rows; i++) {
            if (data[i].doc.IsDeleted || data[i].doc.IsWorkIssueInserted || data[i].doc.IsWorkIssueUpdated || data[i].doc.IsLogInserted) {
               DirtyFlag = true;
            }
         }
         return DirtyFlag;
         console.log("exiting allDocs");
      }).catch(function (err) {
         console.log("inside catch");
         showMsg("Error in cleanRoom/allDocs: " + err);
      });

      console.log("exiting cleanRoom")
};
```

So your code shows you are still struggling with promises. They really are very super crazy to understand, you really should read more about them.

**Comment by tshad** [comment]
That helps a lot.

Everyone keeps saying to read more about them.  Believe me I am.

I missed the part about the 2nd parameter being a callback.  I had actually figured that out just before you responded but was still confused on setting it up for my scenario.

My scenario has a chain and one of the promises in the chain is handling two promises (if something do one pouch call and if another do another pouch call).  Each pouch call can have it's own chain.  So you have one promise with two promises (pouch calls) chains. 

The outside chain would call this promise and then go to method that would display the results.  The problem was that each of the promise chains (pouch chains) would follow their own chains fine.  But when the pouch call happened, it would then jump out of the promise to the method the displayed the result before the pouch call was done.

The only way I could get it to work was to put the same result method on the end of each pouch chain inside the original promise.  Not the best way but solved the problem.

I am going to revisit the issue after reading  your answer.

Thanks,

Tom

**Comment by tshad** [comment]
OK.

I was looking at your code and I am still confused.  I don't want to use the callbacks as we mentioned.

You say not to create the promise for cleanroom.

My aim is to not go to removeGarbage until cleanRoom is done.

cleanRoom has to get the records and then go through them before removeGarbage is called.  This was why I made (or tried to make) cleanRoom a promise.

```
   }).then(function () {
      return initialize();
   }).then(function (prMessage) {
      **return cleanRoom();**   <--- my promise
   }).then(function (result) {
      return removeGarbage(result);
   }).then(function (result) {

```
Maybe that can't be done but as I mentioned above, I can't do the allDocs as part of the above chain because it may another pouch promise I call based on some variable.  This was why I need something like cleanRoom to house both pouch commands and call the appropriate one but not jump to removeGarbage until done.

In your changes, I believe, that the dropping of the callback and using .then would help the promise inside the cleanRoom function but I don't think it would stop the program from jumping to the removeGarbage function before it was done.  Or maybe I am wrong here.

Thanks,

Tom
