### ISSUE TITLE
Broken link in API documentation

### ISSUE THREAD

**Issue by flimzy** [pouchdb/pouchdb#6306]
### Issue
The documentation for ajax options refers to a broken link.

Specifically [here](https://github.com/pouchdb/pouchdb/blob/45a0c15d5ecdf29631af3b1a39f4b68d2acb24c8/docs/_includes/api/create_database.html#L21) refers to the URL `https://github.com/pouchdb/pouchdb/blob/master/lib/deps/request-browser.js`, which results in a 404.  I'd submit a PR to fix it directly, but I'm not entirely sure where that functionality has moved to.

**Comment by nolanlawson** [comment]
The new link is https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-ajax/src/request-browser.js ; I'd be happy if someone submitted a PR to fix the page. :D

**Comment by flimzy** [comment]
I can do that shortly.
