### ISSUE TITLE
Replication cancel() does not work after HTTP 401

### ISSUE THREAD

**Issue by t-knapp** [pouchdb/pouchdb#6307]
### Issue
I'm working with replication between Pouch / Couch. My business logic forces me to block all PouchDB Clients that do replication by changing the password in CouchDB.
The clients then cancel replication. (Like here: https://pouchdb.com/guides/replication.html#canceling—replication)

The issue is: The password change deliver a HTTP 401 in Pouch - okay. But canceling the replication does not work. That means: The 'complete' event is never fired after calling .cancel() on a synchandler.

### Info
- Environment: PouchDB 6.1.0.
- Platform: Chrome & Android
- Adapter: default
- Server: CouchDB 2.0.0

### Reproduce
Start Replication with Pouch <-> Couch.
Provoke a HTTP 401 (By changing CouchDB Users password)
Cancel Replication in PouchDB

**Comment by nolanlawson** [comment]
Thanks, this appears to be a dup of https://github.com/pouchdb/pouchdb/issues/5607 ; please reopen if I'm mistaken.
