### ISSUE TITLE
RFC: ideas for replication performance improvements

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6316]
I've been looking into the performance of replication from remote to local for 1) CouchDB 1 vs 2) CouchDB 2 vs 3) CouchDB 2 with an HTTP/2 proxy. It's a bit hard to measure because I can't find a reliable H2 proxy, but initial results seem to be:

1. CouchDB 2 only slightly improves perf over CouchDB 1, because `_bulk_get` is actually only used in cases of conflicts now (_edit: also attachments and non-gen-1 docs, thanks @willholley_), since we use `_all_docs` whenever possible. In my test set of npm skimdb docs, the vast majority of docs can be fetched with `_all_docs` rather than `_bulk_get`.
2. H2 does not seem to improve much over HTTP1, because we're not extremely chatty and we're not hitting 6-parallel-requests-per-origin limits or other standard H1 problems.

Here's an annotated timeline example:

![screenshot 2017-02-28 20 22 00](https://cloud.githubusercontent.com/assets/283842/23446253/9b32b0ae-fdf6-11e6-964a-e5fd9f637815.png)

Some potential opportunities for improvement that I see here:

### 1. start fetching next batch while writing the current one

To do this, we parallelize `_changes`/`_all_docs` with the ongoing IDB write. In other words, we start fetching the next batch while writing the current one. In theory this should ensure we're maximizing CPU usage and not doing sequential "write to disk, wait on network, write to disk, wait on network, etc."

Some potential downsides:

1. More memory pressure, worst-case scenario is `batch_size x 2` docs are kept in memory at once
2. Doesn't guarantee we will actually maximize CPU usage throughout replication unless we do adaptive batch sizing; in other words if users choose a sufficiently high batch size then we'll still be waiting on the network

### 2. Run `_all_docs` concurrently with `_bulk_get`

Looking at the code, I have no idea why we don't already do this. The two requests are independent.

### 3. Parallellize remote checkpointing

Once again, I don't see why this couldn't be done concurrently with the ongoing `_changes`/`_all_docs`/`_bulk_get`. No need to wait for the response before sending out the next request.

### 4. Adaptive batch sizing?

See # 1 above. If we could be smart enough to choose the ideal batch size for the user based on average doc size, network quality, etc., then we could ideally do a good job managing memory pressure while also ensuring optimal CPU and network usage while also giving the user one less thing they have to manually configure. But this could potentially be very difficult.

### conclusion

So overall, I don't see HTTP/2 as a magic pill that's going to fix all our performance problems (sadly). No doubt it removes the overhead of HTTP headers, connection latency, etc., but to really get good replication perf I think we need to overhaul the replication algorithm itself.

**Comment by willholley** [comment]
Thanks for kicking this off @nolanlawson. A couple of thoughts:

1. As I understand it, `_bulk_get` should be used for any non rev-1 doc - not just conflicted documents. Ideally we should profile with a few different datasets, e.g. a database with a relatively small number of documents (say 10k) but lots of churn would likely have a pretty different replication profile.

2. It'd be interesting to look at H2 without the `_all_docs` or `_bulk_get` optimisations, though perhaps we'd then be bottlenecked on the server.

Regarding your proposed improvements:

1. Seems solid to me.

2. I'm not sure they are independent, though they are mutually exclusive. If the server supports `_bulk_get`, the `_all_docs` optimisation is redundant. If we don't already, we should skip the `_all_docs` optimisation when we know `_bulk_get` is available.

3. Seems like a quick win.

4. Picking batch size seems like a bit of a black art at the moment but it sounds like an area worth exploring. (1) seems like it may go some way to addressing throughput issues with smaller batch sizes.

**Comment by daleharvey** [comment]
Yeh improving the replicator would be nice

We have had quite a few people file bugs about the amount of checkpoints we write and an open bug on making it configurable (https://github.com/pouchdb/pouchdb/issues/6308) I would much rather see us vastly reduce the number of checkpoint requests we make. I think our current eagerness was mostly in getting tests passing however it seems like in real life we do not need to send so many requests, maybe once per 50 docs or when we start polling or similiar, if couchdb fixes the _local docs in bulkdocs bug as well I think we can avoid checkpoints being extra requests at all

I also think we could make a new replication protocol that is vastly less chatty, its still just a thought and havent fleshed it out, unlikely to do so until `idb-next` is done but briefly outlined it @  https://github.com/janl/couchdb-next/issues/10#issuecomment-278935183

**Comment by janl** [comment]
@nolanlawson thank you for starting this off. Did you test the H2 option with adverse network connections (simulated)? I didn't get to that bit in my endeavour.

**Comment by nolanlawson** [comment]
@janl No, I tried Caddy but it kept generating socket refused errors after a bit, so I gave up. Can't find an H2 proxy that works well with CouchDB.

@daleharvey Gregor's concern about the checkpoints is not just speed but also cost because of how Cloudant charges per request. Also TBF checkpoints can be reduced by increasing batch size, but that also has other trade-offs. I think the optional checkpointing is reasonable.

@willholley Yup I think you're right about everything. I could take some time to try to create a more representative skimdb subset, e.g. all docs that start with a certain letter.

I'll share my benchmark; just need a sec to upload it.

**Comment by nolanlawson** [comment]
- [Replication benchmark](http://bl.ocks.org/nolanlawson/raw/4e2fe3881ddef4546a67963bad68ba77/) ([source](https://gist.github.com/nolanlawson/4e2fe3881ddef4546a67963bad68ba77))
- [Script to replicate from skimdb to local Couch/Pouch](https://gist.github.com/nolanlawson/6d15c482d8bef1b542f243acfaeff3ae)

**Comment by hermitdemschoenenleben** [comment]
Hello,

I investigated pouchdb sync performance a while ago and noticed that longpoll two-way sync creates one useless (at least I think it is) _refs_diff request after receiving a document. (I just have couchbase sync gateway for testing here, but I can't see a reason why the behavior would be different with couchdb)

The problem occurs in a situation where a longpoll two-way sync is idling and the remote server pushes a document to pouchdb. Then, the _changes receives this:

`
Payload: {"results":[
{"seq":56607,"id":"msg/120157878387203/1293236327357395/1489735600/6A0A6E03","changes":[{"rev":"1-61b24c57d8099500820e1e629637a98d"}]}
],
"last_seq":"56607"}
`

Afterwards, the _all_docs request fetches the document. Then comes the _revs_diff request I consider not useful:
```
URL: http://192.168.178.36:4984/data/_revs_diff
Payload: {"msg/120157878387203/1293236327357395/1489735600/6A0A6E03":["1-61b24c57d8099500820e1e629637a98d"]}
```
As far as I understood it, pouchdb has noticed that there is a new document in the local database and tries to push it back to the remote server, ignoring that this is the server that sent exactly the same document with the same revision.

In my code I implemented a wrapper around the sync function as a work-around to get rid of these _revs_diff calls:
```
import {sync} from './sync/sync';

var store = {};

function docToKey(doc) {
  return JSON.stringify([doc._id, doc._rev]);
}

function filterPush(doc) {
  if (docToKey(doc) in store) {
    return false;
  }
  return true;
}

function addDocsToStore(docs, seq) {
  for (let doc of docs) {
    store[docToKey(doc)] = seq;
  }
}

function clearStorage(seq) {
  window.setTimeout(() => {
    for (let key in Object.assign({}, store)) {
      if (store[key] < seq) {
        delete store[key];
      }
    }
  }, 2000);
}

export function thriftySync(src, target, options={}, callback) {
  options.push = options.push || {};
  let oldFilter = options.push.filter || (() => true);
  options.push.filter = doc => oldFilter(doc) && filterPush(doc);

  let handle = sync(src, target, options, callback),
      last_seq = 0;

  handle.on('change', change => {
    if (change.direction == 'pull') {
      addDocsToStore(change.change.docs, last_seq);
    } else if (change.direction == 'push') {
      last_seq = change.change.last_seq;
      clearStorage(last_seq);
    }
  });
  return handle;
}
```
However, it would be nice if a solution for this could be included into pouchdb (given that the _revs_diff call really does not make sense in this case)

**Comment by willholley** [comment]
@hermitdemschoenenleben I think the `_revs_diff` is required. `_changes` will tell you what documents have changed, but not necessarily what revisions are available for that document. The `_revs_diff` call is needed to figure out which revisions of the document are available on the source and missing on the target. 

Whilst this is a relatively unlikely situation during continuous replication, it's still possible, so `_revs_diff` is needed for correctness in the general case.

**Comment by daleharvey** [comment]
@willholley Arent the revisions that have changed included in the changes result? if so then the pull replication knows what revisions its changed so we could skip that revs_diff. Ultimately if the replication was bidirectionally aware I think it would be possible to shave off a few requests however in terms of complexity vs improvement I think its on the high hanging fruit

**Comment by willholley** [comment]
@daleharvey hmm - maybe :) Does it include conflicted revs as well? I can believe that there are specific cases where it's a redundant call but would be wary of cutting requests from the standard protocol without input from the wider CouchDB dev community.

**Comment by hermitdemschoenenleben** [comment]
> Arent the revisions that have changed included in the changes result?

That's what I thought, too.

> Does it include conflicted revs as well?

As Pouchdb calls _changes with style=all_docs, it does (CouchDB docs):

> all_docs will return all leaf revisions (including conflicts and deleted former conflicts).

I just did some tests to see what the impact of these additional _revs_diff calls is and found out that when doing an initial sync with a lot of documents, it can really make the performance much worse. The problem is, that _revs_diff doesn't use the same batch_size as the other calls:
In my case, I was initially pulling 1000 documents from the server with a batch size of 200 --> in the ideal case I would have about 10 requests in total. However, the revs_diff calls are made for chunks of between 1-10 docs, resulting in about 110 extra requests. But yes, I understand that finding a clean solution for this problem is not easy...

**Comment by nolanlawson** [comment]
Just took a look at this, realized there's a reason we do `_all_docs` before `_bulk_get` – we need to check the `_all_docs` response to see if there are any deleted docs, docs with attachments, or docs with conflicts, because those need to be fetched with `_bulk_get`.

If we knew in advance whether or not the database supported `_bulk_get` then we could just do a single `_bulk_get`, but such an API is not currently exposed. Perhaps it should be.
