### ISSUE TITLE
FruitDOWN adapter in WKWebView on iOS sometimes freezes

### ISSUE THREAD

**Issue by dsc-peterssoftwarede** [pouchdb/pouchdb#6318]
### Issue
FruitDOWN adapter in WKWebView on iOS 9/10 sometimes freezes

### Info
- Environment: WKWebView
- Platform: iOS 9/10
- Adapter: FruitDOWN
- Server: CouchDB

### Reproduce
After reading and storing data the FruitDOWN sometimes freezes, does no longer respond to any query. This is only reproducible with the FruitDOWN adapter. The In-memory and LocalStorage adapters work fine.

**Comment by nolanlawson** [comment]
Can you provide a reproducible test case? Most likely it is a bug in iOS Safari, and we would love to file an issue on the WebKit team.

**Comment by nolanlawson** [comment]
Also FWIW iOS IndexedDB is vastly improved in Safari 10.1+.

**Comment by dsc-peterssoftwarede** [comment]
It took some time to build an example that freezes in the same way as our application.

[Example.zip](https://github.com/pouchdb/pouchdb/files/841981/Example.zip)

This example freezes in Safari for macOS, Version 10.0.3 (11602.4.8.0.1) and WKWebView on iOS 10.2 (14C89).

Steps to reproduce:

- Open index.html in Safari on macOS or within WKWebView on iOS
- Click "Start Me!"
- Wait a few seconds (3-4) and click "Start Me!" again.
- Wait a few seconds (3-4) and click "Start Me!" again.
- Wait a few seconds (3-4) and click "Start Me!" again.

At some point the FruitDOWN adapter stops working. If it does not freeze try again from the start and click more times on "Start Me!" or wait longer till it freezes.

In the FruitDOWN adapter writeLock() and readLock() are still called but executeNext() is never called again. So it seems that the execution queue just died.

We also tested the example with Google Chrome where it does not freeze. So there is maybe a problem with the IndexDB implementation in Safari/WKWebView.

**Comment by nolanlawson** [comment]
Thank you for the test case!

**Comment by daleharvey** [comment]
Closing issues without PR's in unsupported envs
