### ISSUE TITLE
websql throw an error: "unable to begin transaction (5 database is locked)"

### ISSUE THREAD

**Issue by daifee** [pouchdb/pouchdb#6324]
### Issue
to run a few day later, the app throw an error:
![image](https://cloud.githubusercontent.com/assets/5410503/23512062/4e68517a-ff9a-11e6-8220-a88572cbc661.png)

### Info
- Environment: hybrid app
- Platform: iOS
- Adapter: WebSQL
- Server: CouchDB

**Comment by nolanlawson** [comment]
Could you please provide a few more details?

- iOS version
- Cordova/Ionic/PhoneGap version
- Using the SQLite plugin? which one?
- Steps to reproduce?

**Comment by daifee** [comment]
@nolanlawson 

* iOS(10.1.1)
* Cordova(3.8.0)
* don't use SQLite plugin

I don't know how to reproduce.

I think the flowing information is useful:

My app open two *webview*, each webview has an instance of PouchDB(`var db = new PouchDB('trip')`). sometimes, two instances will write/read the same DB at the same time, throw error and lock the DB. I had tried for my guess, but it didn't happend.

**Comment by rdwoodring** [comment]
I know this is marked as stale, but I'd like to reopen. Ran into this on a project at work and it took a while, but I think I nailed down steps to repro.  Basically looks like opening multiple WebSQL databases with the same name (say two in a main frame and two in an embedded iFrame) and then writing to 'em causes WebSQL to deadlock or something.

**Steps to reproduce**

1. Create a page with PouchDB pulled in
2. Create a database with the name "test"
3. Write to the database 100 times in a loop
4. Create a database with the name "test2"
5. Write to the database 100 times in a loop
6. Create an iFrame
7. Repeat 1-5 in the iFrame

**Expected result**
The databases should be updated just fine

**Actual result**
WebSQL blows up. Javascript console displays the message "WebSQL threw an error", "unable to begin transaction (5 database is locked)"

Windows 10
Chrome Version 63.0.3239.84 (Official Build) (64-bit)

Test case to reproduce is attached. It's happening every time for me, but if it doesn't happen, you should just be able to refresh and get it pretty easily.

Happy to take a look and work on resolving this (if it's resolvable) but I'll need some major guidance from someone.

Test case: [pouchdb.zip](https://github.com/pouchdb/pouchdb/files/1605281/pouchdb.zip)

Thanks

**Comment by bgold0** [comment]
Has anyone figured out how to mitigate against this or at least unlock the database? The only way I can fix this issue is completely closing the app and restarting it.
