### ISSUE TITLE
Use selector as replication filter

### ISSUE THREAD

**Issue by buhrmi** [pouchdb/pouchdb#6329]
### Issue
CouchDB 2.0 seems to accept a selector at the `_changes` API endpoint which they say is an order of magnitude faster than using a javascript filter function. Would it be possible to have pouchdb pass this through to Couch for live and one-shot replication?

For example

    localDB.replicate.from(remoteDB, {filter: "_selector", selector: {assignees: "my-username"}})

**Comment by garrensmith** [comment]
This is the same as #5717
