### ISSUE TITLE
 ASSIGNMENT: Develop new features, Documentation Uni-Project

### ISSUE THREAD

**Issue by vassilisgeo** [pouchdb/pouchdb#6335]
Good afternoon PouchDB,

@(SergiuUngureanu) and I are students of Athens University of Economics and Business in the Department of Management Science & Technology. In the context of the course Software Engineering in Practice we will choose a project to contribute in its source code.

We would like to contribute to PouchDB so we can work on developing new features, contribute to documentation or any suggestions.

Thank you in advance,
Your sincerely,
Georgopoulos Vassilis

**Comment by daleharvey** [comment]
Hi, welcome, very glad to hear you have chosen to help out with PouchDB :)

There are plenty of issues and feel entirely free to pick up ones that you are particularly interested in, if either of you has an area of interest also feel free to say.

I went through and picked out a few bugs that seem particularly suitable for first patches, if you need help or clarification please feel free to ask on the bug or IRC / Slack. Also dont miss https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md that has some helpful guides about contributing 

https://github.com/pouchdb/pouchdb/issues/6230
https://github.com/pouchdb/pouchdb/issues/6025
https://github.com/pouchdb/pouchdb/issues/5782
https://github.com/pouchdb/pouchdb/issues/5490

Cheers
Dale

**Comment by nolanlawson** [comment]
Hey, if you're still interesting in this, we could probably do a Skype call or something to help you out. The Slack channel is also a great way to get in touch. :smiley:

**Comment by vassilisgeo** [comment]
Hey! We are fully interested in contributing to pouchDB it would be great for us to have a Skype call so we could clarify how we can help.

**Comment by garrensmith** [comment]
Great. What timezone are you in?

All misspelling thanks to my iPhone.
________________________________

**Comment by SergiuUngureanu** [comment]
Hey, we are located in Greece so our timezone is Eastern European Time Zone
