### ISSUE TITLE
Adding index in typescript/angular2 

### ISSUE THREAD

**Issue by karruma** [pouchdb/pouchdb#6336]
Hi, I am trying to add an index to pouch db in my angular2 project, but I am getting the following problem when trying to do it:

` Cannot read property 'put' of undefined`

I have no problems executing temporary queries such as 

```
 this.db.query((doc, emit) => {
          for (let configElement of doc.data) {
            if (configElement.id === 1961006) {
              emit(configElement);
            }
          }
        }).then((result) => {
          for (let row of result.rows) {
            console.log(row.key);
          }
        }).catch((error) => {
          console.log(error);
        });
```
The thing is that I would like to make this a permanent query, so add an index and then do a query.
Any ideas why am I getting this error?

### Info
- Environment: (browser)
- Platform: (Chrome)
- Adapter: (IndexedDB)
- Angular2/typescript

### Reproduce

```
import * as PouchDB from 'pouchdb';
import * as PouchDBFind from 'pouchdb-find';

@Injectable()
export class SomeService {

private db: any;

constructor(public http: Http) {
  PouchDB.plugin(PouchDBFind);
  PouchDB.debug.enable('pouchdb:find');
  this.db = new PouchDB('db');
}

public executeQuery() {
 let index = {
      _id: '_design/my_index',
      views: {
        by_id: {
          map: function (doc, emit) {
                emit(doc);
            }
          }
        }
    };

this.db.put(index).then(function () {    
}).catch(function (err) {
    
});

this.db.query('my_index/by_id', {startkey: 1}).then(function (result) {
      for (let row of result.rows) {
        console.log(row.key);
      }
    }).catch(function (err) {
      // some error
    });
}
```

**Comment by nolanlawson** [comment]
This is not a TypeScript problem but rather appears to be because `this.db` is undefined when you call `put()`. You would need to call your `constructor` function first before calling `this.db.put()`. Hope that helps – if not, please try your question on StackOverflow or https://slack.pouchdb.com :)
