### ISSUE TITLE
pouchdb-find: not using index when using $exists selector AND sorting by this key

### ISSUE THREAD

**Issue by plepe** [pouchdb/pouchdb#6337]
### Issue
I found an issue that pouchdb-find won't use an index when using a $exists selector for a key and the result will be sorted by this key. This should work, because even the README has the following example:
```js
db.find({
  selector: {
    debut: {'$exists': true}
  },
  sort: [{debut: 'desc'}]
});
```

I'm using the current version 0.10.5.

### Detailed description
On your demo page http://nolanlawson.github.io/pouchdb-find/ I used the following code:
```js
db.createIndex({
  index: {fields: ['debut']}
}).then(function () {
  return db.find({
    selector: {debut: {$exists: true}},
    sort: ['debut']
  });
});
```

I get the following error:
```
Error: Cannot sort on field(s) "debut" when using the default index
    at m (https://unpkg.com/pouchdb-find@0.10.5/dist/pouchdb.find.min.js:1:26173)
    at https://unpkg.com/pouchdb-find@0.10.5/dist/pouchdb.find.min.js:1:18166
```

If I replace `{'$exists': true}` by `{'$gt': null}`, everything is alright:
```js
db.createIndex({
  index: {fields: ['debut']}
}).then(function () {
  return db.find({
    selector: {debut: {$gt: null}},
    sort: ['debut']
  });
});
```

**Comment by nolanlawson** [comment]
Thanks for the detailed bug! By any chance have you tested Cloudant/Couch2 to see if they have the same behavior? We try to exactly imitate their behavior.

**Comment by rweng** [comment]
same in version 6.2.0
