### ISSUE TITLE
Indexes created on mobiles are replicated on server

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6341]
_From @larryaubstore on March 14, 2017 15:42_

Hi, it it possible that indexes created on mobile devices are replicated on CouchDB server ? My database on CouchDB server is getting bigger. At the beginning, the database was taking 100M and now it goes to 16GB. 

Is it possible to create indexes on the mobile side only ?

_Copied from original issue: nolanlawson/pouchdb-find#258_

**Comment by willholley** [comment]
@larryaubstore - there's no way to specify when creating an index that it shouldn't replicate to the server, but you could add a replication filter to reject `_design` documents. For example:

```
local.replicate.to(remote, {
  filter: function (doc) {
    return doc.substr(0,7) !== '_design';
  }
});
```

**Comment by larryaubstore** [comment]
@willholley Thank you. I will use this filter.
