### ISSUE TITLE
'A module cannot import itself' error when bundling pouchdb-adapter-websql with Rollup

### ISSUE THREAD

**Issue by tabrindle** [pouchdb/pouchdb#6345]
### Issue

There seems to be a new bug between release 6.1.1 and 6.1.2 where the websql adapter will cause rollup to crash while bundling:

```shell
A module cannot import itself (/Users/tabrindle/Developer/media-hybrid/node_modules/pouchdb-adapter-websql/node_modules/pouchdb-utils/lib/index-browser.es.js)
Error: A module cannot import itself (/Users/tabrindle/Developer/media-hybrid/node_modules/pouchdb-adapter-websql/node_modules/pouchdb-utils/lib/index-browser.es.js)
    at /Users/tabrindle/Developer/media-hybrid/node_modules/rollup/src/Bundle.js:335:14
```

The error suggests this is the culprit: `import { nextTick } from 'pouchdb-utils';` from inside pouchdb-utils/lib/index-browser.es.js

This file is not present in 6.1.1.

Here is my rollup config:
```
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import uglify from 'rollup-plugin-uglify';
import builtins from 'rollup-plugin-node-builtins';
import globals from 'rollup-plugin-node-globals';
import { minify } from 'uglify-js';

export default {
    entry: 'resources/libs/index-rollup.js',
    dest: 'resources/libs/bundle.js',
    format: 'iife',
    moduleName: 'bundle',
    plugins: [
        builtins(),
        resolve({
            jsnext: true,
            main: true,
            browser: true,
            preferBuiltins: false
        }),
        commonjs({
            include: 'node_modules/**'
        }),
        globals(),
        uglify({
            compress: {
               unused: false
            }
        }, minify)
    ]
};
```

Based on the resolves I have configured, I realize that rollup will select this new file over the old, but what I dont understand is why rollup has an issue with it. 

Just a shot in the dark, I'm guessing this may have to do with @nolanlawson 's pulls #6162 (Make polyfills extractable) or #6170 (dont expost src to npm) based on the commit logs to these files, and the changelog from this release. 

This may not actually be a bug, just an unintended side effect of how I am using the package - Of note, I am using Pouchy 11.0.3, which uses pouchdb-core 6.0.6. Will also crosspost this issue to Pouchy. 

### Info
- Environment: Node.js v6.10.0
- Adapter: WebSQL

### Reproduce
Install Pouchy 11.0.3 and pouchdb-adapter-websql@6.1.2 and attempt to bundle them with rollup

**Comment by nolanlawson** [comment]
I believe in 6.1.2 we also started exposing our own jsnext:main so that is probably also contributing to this issue. Before that we just exported CommonJS. In any case it seems we have a test case here.

**Comment by tabrindle** [comment]
Please let me know if I can help here. I'm not really familiar with this packages architecture, but if it's a relatively simple fix I'll try to make a PR.

**Comment by nolanlawson** [comment]
No worries – the fix was pretty simple. Just need to make sure pouchdb-utils didn't try to import itself: #6348

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/375a7dca19ce37f613b916693155fe988271244c
