### ISSUE TITLE
Initial call to pouch doesn't seem to follow chain

### ISSUE THREAD

**Issue by tshad** [pouchdb/pouchdb#6357]
In the following code I am testing how to handle a new device that does not have any pouch databases defined.  So I am deleting all of them, which works fine.

But on the very first destroy (DB_Categories.destroy()), it 
1. does the destroy
2. then jumps to the end of the callDBDestroy function.
3. then jumps to the end of the DropPouch function
4. then jumps the 2nd destroy in the "then" (DB_Equipment.destroy())
5. From there is continues down the chain.

I tried putting a return on the first destroy, but that did exactly the same thing.

```
function DropPouch(checkok) {
      callDBDestroy();
}

function callDBDestroy() {
   var db;

   DB_Categories.destroy().then(function () {
      return DB_Equipment.destroy();
   }).catch(function (err) {
      showMsg("Error in callDBDestroy: " + err);
   }).then(function () {
      return DB_Certificates.destroy();
   }).catch(function (err) {
      showMsg("Error in callDBDestroy: " + err);
   }).then(function () {
      return DB_Locations.destroy();
   }).catch(function (err) {
      showMsg("Error in callDBDestroy: " + err);
   })
}

```

Am I doing something wrong here or is this how it is supposed to work?

Thanks,

Tom

**Comment by nolanlawson** [comment]
It seems your `DropPouch()` function is never called. If you just want a promise to destroy multiple dbs, you can do:

```js
Promise.all([
  db1.destroy(),
  db2.destroy(),
  db3.destroy,
  /* etc. */
]).then(/* ... */).catch(*/ ... */)
```

Also btw this seems like a good question for StackOverflow or slack.pouchdb.com rather than GitHub issues. :)
