### ISSUE TITLE
find() should throw unsupported_mixed_sort error for mixed asc/desc

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6359]
Here's a test that succeeds for CouchDB 2.0 but fails for PouchDB (e.g. when added to `tests/find/test-suite-1/test.errors.js`):

```js
    it('throws an error for incompatible sort', function () {
      var db = context.db;
      return db.createIndex({
        index: {
          fields: ['harry', 'sally']
        },
      }).then(function () {
        return db.find({
          selector: { harry: 1, sally: 1 },
          sort: [ { harry: 'asc' }, { sally: 'desc' }]
        }).then(function () {
          throw new Error('expected an error');
        }, function (err) {
          // reason: "Sorts currently only support a single direction for all fields."
          err.error.should.equal('unsupported_mixed_sort');
        });
      });
    });
```

Since our goal is to be 1-to-1 compatible with CouchDB 2.0 we should probably do the same thing. I'm not sure, though, what we actually do in the case of mixed asc/desc sort, but I'd guess we return the wrong result. (If not, then maybe it's okay that we're not compatible?)

**Comment by fenglianxu** [comment]
We have come across the same issue on unsupported_mixed_sort.  what is the plan with this issue in couchdb?

**Comment by garrensmith** [comment]
Unfortunately at this stage CouchDB is not going to support mixed sort. This is really difficult to do with a distributed database.
