### ISSUE TITLE
.info not a function

### ISSUE THREAD

**Issue by tshad** [pouchdb/pouchdb#6361]
I am trying to get the number of records in this database.  But I am getting an error:

TypeError: DB_WorkIssues.info is not a function

Isn't this a fuction?

```
   return DB_WorkIssues = new PouchDB('pouch-Tasks-WorkIssues', { auto_compaction: true }).then(function () {

      DB_WorkIssues.info().then(function (details) {
         if (details.doc_count == 0 && details.update_seq == 0) {
            console.log('WorkIssues DB empty');
            reload = true;
         }
         else console.log('WorkIssues DB has records');
      }).catch(function (err) {
         console.log('WorkIssues error: ' + err);
      });
   }).then(function () {

```

Thanks,

Tom

**Comment by tshad** [comment]
I found out what the problem was but am not sure why.

Event though the I am in the "then" clause, DB_WorkIssues is still a promise.  I need another then to be able to use DB_WorkIssues as the DB object.

I am trying to find out if a device has the pouch DB's on it yet and was using the .info to tell me by letting me know if there are zero records in the db.

```
   DB_Equipment = new PouchDB(DBNAME_Equipment, { auto_compaction: true }).then(function () {
      return DB_Certificates = new PouchDB(DBNAME_Certificates, { auto_compaction: true });
   }).then(function(){
      return DB_LookupTables = new PouchDB(DBNAME_LookupTables, { auto_compaction: true });
   }).then(function(){
      return DB_Locations = new PouchDB(DBNAME_Locations, { auto_compaction: true });
   }).then(function(){
   }).catch(function () {
   })

```
I want to be able to check the first database (DB_Equipment) to see if I need to load the data before going on.  At the DB_Certificates line, the DB_Equipment is still a promise so I can't use the .info yet.  I have to get to the DB_LookupTables line to do it and at that point both DB_Equipment and DB_Certificates are DB objects and not promises.  From this point on, each then has a new DB object.

I don't understand why DB_equipment is still a promise after the first "then".

**Comment by garrensmith** [comment]
I think again it comes down to your understanding of promises. Another thing is don't do this:

```
new PouchDB(DBNAME_Equipment, { auto_compaction: true }).then(...)
```

Rather something like this:
```
DB_Equipment = new PouchDB();
DB_Equipment.info().then(....);
```
