### ISSUE TITLE
Whitespace around built-in reduce functions

### ISSUE THREAD

**Issue by fehrenbach** [pouchdb/pouchdb#6364]
PouchDB seems to only recognize the built-in reduce functions if they are exactly the strings `'_sum'`, ...

When using a tool to write a design doc, e.g. erica, it can easily happen that there's a final newline in the file which then ends up in the reduce function string.

According to the internet CouchDB used to be strict about this, but now strips whitespace.

Should PouchDB do the same? That is, recognize `' _sum\n'` as the built-in _sum function?

As for a fix, would it be enough to change this line to strip whitespace? I could probably open a PR for that. https://github.com/pouchdb/pouchdb/blob/4e0c46894e588ed414e7fbac9c822633ce2628ca/packages/node_modules/pouchdb-mapreduce/src/index.js#L49

PS: Thanks for PouchDB. It's awesome!

**Comment by nolanlawson** [comment]
If CouchDB strips whitespace for these built-in functions, then we should strip whitespace. :) When in doubt, we usually opt to maintain compat with Couch.

Also this would be a fairly easy change that would also have no impact on reduce functions provided as strings... if you would like to provide the patch, I recommend adding a test to `test.mapreduce.js` and modifying the code in `packages/node_modules/pouchdb-mapreduce/src`. Thanks for reporting!

**Comment by fehrenbach** [comment]
> When in doubt, we usually opt to maintain compat with Couch.

Alright, I tracked down what Couch does. This is the commit: https://github.com/apache/couchdb-couch/commit/8423c897041aabf192789c2e640c5c4c91a07fe7
I don't really read Erlang, but I guess that's pattern matching on a binary string with prefix (e.g.) `_sum` and ignoring the tail.

I'll open a PR (soon-ish) with a test and trimming whitespace on both ends, unless someone is really keen on strict compatibility with Couch.

**Comment by nolanlawson** [comment]
Hmmmm, the problem with not adhering strictly to CouchDB is that you'll need to write two different tests – one for Pouch and one for Couch. Also that test will likely fail when tested against various server flavors (CouchDB 1 vs 2, Cloudant, PouchDB Server).

I think it'd be most prudent to be conservative and do whatever CouchDB does here. If that means ignoring trailing whitespace but not leading whitespace... then I'd prefer to do that. We can also open an issue on CouchDB to fix the issue of leading whitespace.

**Comment by daleharvey** [comment]
Merged in https://github.com/pouchdb/pouchdb/commit/97b8b0f8ce12d0ec7aeb411222b30ab11ad69152, thanks tons :)
