### ISSUE TITLE
$or not working with find plugin

### ISSUE THREAD

**Issue by RevillWeb** [pouchdb/pouchdb#6366]
### Issue
When using the find plugin the $or operation doesn't appear to work and returns ` Error: unknown operator "0" - should be one of $eq, $lte, $lt, $gt, $gte, $exists, $ne, $in, $nin, $size, $mod, $regex, $elemMatch, $type or $all`.

Maybe I am missing something or it isn't implemented yet (but it says it is in the repo README) or perhaps some features only work if you are connected to a remote DB?

### Info
- Environment: Browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: None

### Reproduce
This is easily reproducible, head over to: http://nolanlawson.github.io/pouchdb-find/ and enter the following code into the demo and press the "Run Code!" button.

```
db.find({
  selector: {
    "$or": [
      { "name": "Link" },
      { "series": "Mario" }
    ]
  }
});
```
Thank you very much! (PouchDB is awesome!)

**Comment by nolanlawson** [comment]
Thanks for the test case. I have a fix and will PR soon.

**Comment by RevillWeb** [comment]
Amazing, thank you for your time!

**Comment by nolanlawson** [comment]
fixed in https://github.com/pouchdb/pouchdb/pull/6368

**Comment by fenglianxu** [comment]
I have found the similar issue with this error message:
Error: unknown operator "0" - should be one of $eq, $lte, $lt, $gt, $gte, $exists, $ne, $in, $nin, $size, $mod, $regex, $elemMatch, $type or $all

The test case is with the **and ** or **or** operator, you can not use more than two properties.  Have you fixed this issue yet?  if you have,which version of pouchdb  has supported this feature.

**Comment by hishtadlut** [comment]
i'm facing this problem in version 7.2.2.

`Error: unknown operator "$or" - should be one of $eq, $lte, $lt, $gt, $gte, $exists, $ne, $in, $nin, $size, $mod, $regex, $elemMatch, $type, $allMatch or $all`

i'm wase trying to do this:
`
const isAppropriateLevelsQuery = [{ "isAppropriate": "true"} , { "isAppropriate":"false" }];
selector: {
    isAppropriate: { $or: isAppropriateLevelsQuery }
}`
