### ISSUE TITLE
Tutorials and examples of integrating PouchDB with other frameworks

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6367]
This is one issue I see frequently when I browse StackOverflow, GitHub Issues, etc.: people have a hard time just _getting started_ with PouchDB, using their framework of choice. Sometimes they don't even get past the install step.

I've tried to solve this in a somewhat haphazard way, by creating a few demos/tutorials using popular frameworks:

* [pouchdb-ionic](https://github.com/nolanlawson/pouchdb-ionic)
* [pouchdb-cordova-sqlite-demo](https://github.com/nolanlawson/pouchdb-adapter-cordova-sqlite-demo)
* [pouchdb-phonegap-cordova](https://github.com/nolanlawson/pouchdb-phonegap-cordova)
* [pouchdb-electron](https://github.com/nolanlawson/pouchdb-electron)
* [pouchdb-nw](https://github.com/nolanlawson/pouchdb-nw)

There are lots of problems with this approach, though:

1. It quickly gets out of date. For instance, my Ionic demos only work with Ionic v1 and old versions of Cordova. Some of them might still be using PouchDB v5. Updating them is a time-consuming process.
2. There are many technologies out there that aren't covered (React, React Native, NativeScript, VueJS, Ionic Native, _&lt;insert 200 more JavaScript frameworks here&gt;_).
3. Sometimes the most popular tutorials don't get updated fast enough, which means they are a minefield for beginners. For instance, [this extremely popular tutorial](https://gonehybrid.com/how-to-use-pouchdb-sqlite-for-local-storage-in-ionic-2/) originally used PouchDB v5 instead of v6, and because of a breaking change in v6 it didn't work for awhile, leading to GitHub issues and SO questions.

What I would like is to have a larger community effort to create tutorials and "hello world" demos, and to keep them up to date. Unfortunately I have no idea how to lead such an effort, or what it would involve. Some ideas:

1. Keep the documentation in the PouchDB docs, add a new section like "integrating PouchDB with other frameworks"
2. Keep the demo code _outside_ of PouchDB, so it can quickly be updated by whoever is maintaining it.
3. Solicit help from the community for missing frameworks (e.g. do we have React Native but not NativeScript? Angular 1 but not Angular 2? React but not Vue? TypeScript but not Flow? Electron but not NW.js? Ask those communities for help!)
4. Link generously to outside blog posts and tutorials, when they are high-quality.

Very open to ideas on this one. :smiley:

**Comment by pubkey** [comment]
Great idea. Can we build a consensus on what the example-demos should do?
I think it would be great if they all implement the same ui/logic, just with a different framework.

Maybe a todo-list or the pokedex.

**Comment by nolanlawson** [comment]
I'd vote todo-list just because it's a very well-understood example.

**Comment by balupton** [comment]
Should probably just a be a `awesome-pouchdb` list. With tutorials, and samples, then plugins and adapters, etc all being category of lists in the repo.

**Comment by nolanlawson** [comment]
I like the idea of `awesome-pouchdb`!
