### ISSUE TITLE
Safari fall back not working

### ISSUE THREAD

**Issue by waqarprojectinertia** [pouchdb/pouchdb#6374]
While testing my app in safari, it seems it is creating webSql database and tables but they are '-' seperated like 
'attach-sequence-store' , local-store
but no data is inserted into it, i don't know if it falls back to webSql correctly, what need be done to make it work?
i'm using it with sencha touch, it works fine in chrome but chrome has indexDb
but not safari
I think the fall back database has some issues

**Comment by nolanlawson** [comment]
What do you mean by "not working"? We've been using hyphen-separated table names for years and not seen any issues with Safari, Chrome WebSQL, Node SQLite, Cordova SQLite, or various other WebSQL and WebSQL-like environments.
