### ISSUE TITLE
RFC: "lite" build of PouchDB with minimal features

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6377]
It just occurred to me that there's no need to wait for v7.0 for a smaller browser build (#6356). We can add a new package, let's call it `pouchdb-browser-lite`, which contains fewer packages and a more optimized build. We could even put it in `pouchdb/dist` as `pouchdb.lite.js` and `pouchdb.lite.min.js`.

Some things we can do in `pouchdb-browser-lite`:

- no `pouchdb-mapreduce`
- no `pouchdb-changes-filter`
- no `pouchdb-debug`
- no `pouchdb-adapter-websql`
- no polyfills (Promise, Object.assign, Map, Set)
- remove `guardedConsole()` (i.e. dev warnings) with a custom rollup plugin
- remove migrations (IDB in particular)
- etc.

We can ship this in 5.x without needing to ship any breaking changes. :smiley:

**Comment by nickcolley** [comment]
Would be a good way to get feedback on what people would expect from a smaller build.

We'd want to make sure we don't confuse newcomers when they have a thousand and one choices though.

**Comment by nolanlawson** [comment]
I think our custom build system is probably already baffling to newcomers, but it's designed for power users anyway. I am worried about potential confuion from this new"lite" build, but jQuery already does a similar thing, so that gives me some confidence 

You're right though that it'd be good to ask users what they want!

**Comment by nolanlawson** [comment]
BTW this PR contains some stats (https://github.com/pouchdb/pouchdb/pull/6376#issue-217078836) about how much we can save by removing `pouchdb-mapreduce`, `pouchdb-changes-filter`, and `pouchdb-debug`. It's already down from ~47KB min+gz to ~38KB, but I think we can do better.

My rough estimates of what further removals could get us:

* no pouchdb-websql (~5KB)
* no polyfills (~1-2KB)
* no guardedConsole warnings (~1KB)
* no migrations (~1KB)
* removing XHR impl of `pouchdb-ajax` in favor of `fetch()` (~1-2KB)

So at that point we'd be looking at around 30KB which is pretty good, but still not "lite" in my opinion. Can we remove more? Other non-essentials:

* attachments
* `PouchDB.defaults()`
* other ideas?

**Comment by nolanlawson** [comment]
Question: if the package were called `pouchdb-lite` instead of `pouchdb-browser-lite`, would this be clearer? I think a lot of people avoid `pouchdb-browser` because the name is ambiguous, even though it's the most appropriate choice for 99% of PouchDB users (including Cordova users).

I think `npm install pouchdb-lite` communicates very clearly what it is. It could just be an implementation detail that it doesn't work in Node, and that those who want Node support should use `pouchdb` or `pouchdb-node`.

**Comment by garrensmith** [comment]
+1 on pouchdb-lite

**Comment by nolanlawson** [comment]
I've got a branch where I'm testing this idea out ([pouchdb-lite-2](https://github.com/pouchdb/pouchdb/tree/pouchdb-lite-2)), and I'm down to 30255 bytes min+gz (92372 min) by removing migrations, XHR, BlobBuilder, polyfills, pouchdb-adapter-websql, pouchdb-mapreduce, pouchdb-debug, pouchdb-changes-filter, and guardedConsole calls. (That's compared to 47141 min+gz, 147273 min in master.)

I'm kind of surprised that I still can't crack 30KB even after removing all that stuff, but I'll keep digging to see what's still taking up space. :confused:

**Comment by nolanlawson** [comment]
OK, down to 29919 / 91499 by replacing `immediate` with `Promise.resolve().then()` …

**Comment by nolanlawson** [comment]
Down to 28899 / 88606 by removing pouchdb-collate and vuvuzela ([pouchdb-lite-3](https://github.com/pouchdb/pouchdb/tree/pouchdb-lite-3)).

**Comment by wamoyo** [comment]
I just need to create a db, get & put docs and sync to a couchdb.

**Comment by bbuhler** [comment]
I tested your pouchdb-lite package (index-es) from pouchdb-lite-3 branch with my project. 
Everything still works as expected and I save up to 13kb (gz).

I have the same expectations like @wamoyo. That are definitely the basic which a lite package should contain. 

Im a fan of not having bundled polyfills and make use of modern APIs like fetch.
