### ISSUE TITLE
CSG Sync never sync some change

### ISSUE THREAD

**Issue by gine** [pouchdb/pouchdb#6380]
### Issue
Sync in CSG whit channel() and access()

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: Couchbase

### Reproduce
```
var that = this;

this.remote.options = {
    include_docs: true,
    attachments: false,
    crossDomain: true,
    withCredentials: true,
};

this.sync.options = {
    live: true,
    retry: true
};

this.change.options = {
    live: true, 
    since: 'now', 
    include_docs: true, 
    attachments:false
};

this.local.db = new PouchDB(this.local.bucket);
this.remote.db = new PouchDB(this.remote.bucket, this.remote.options);

this.sync.handler = this.local.db.sync(this.remote.db, this.sync.options);

//(1)
this.local.reactToChanges = function(callback) {
    that.local.db.changes(that.change.options).on('change', function (change) {
        //manage view array
    });
};

//(2)
this.remote.reactToChanges = function(callback) {
    that.remote.db.changes(that.change.options).on('change', function (change) {
        console.log(change);
    });
};
```

Now create 2 users X and Y. X with channel = * (admin) and Y without any channel.
Create with admin 2 documents: 

```
{ _id: a, type: a }
{ _id: b, type: b, rel: a }
```

Now on CSG func:
```

if(doc.type == a)
  access(doc.members,doc._id);
  channel(doc._id);
} else if (doc.type) {
  channel(doc.rel);
}
```

Now log-in with X and wait.
Now set on doc the attribute `members = [ "Y" ]`

X receives on (1) only the documents (a) but on (2) X receive (b) too. On X app (b) will never synced  on local db and if i try to save on local.db this file i get a conflict because it propagate on server too.

Thanks,
g.

**Comment by daleharvey** [comment]
We dont 100% support couchbase - https://github.com/pouchdb/pouchdb/issues/5820
