### ISSUE TITLE
Speed up test suite

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6384]
Right now our tests take about 8 hours to run on Travis – spread over 5 concurrent threads, but still, that's about 2 hours. This makes development really painful, since you have to wait a long time for PRs to go green, and sometimes Travis gets so backed up (e.g. with GreenKeeper PRs) that it takes a whole day to recover.

I think we could speed this up by using 1) random DB names, and 2) migrating to [Ava](https://github.com/avajs/ava) which AFAICT is largely Mocha-compatible but allows us to run tests concurrently.

This would need to be configurable, since some tests probably need to run in isolation (Ava supports this), and also we have to limit our random DB names to avoid storage limits in Safari (their algo isn't purely based on usage but also based on unique DB names). But I think this may be doable.

Much of the time in our tests, we are just waiting on network or waiting on IDB, and this can be improved.

**Comment by janl** [comment]
Would it be hard to get a rough performance profile of the test suite, e.g. how much time is spent where, so we can see what the biggest-bang-for-the-buck speedups we could work on?

**Comment by nolanlawson** [comment]
The HTTP latency is definitely the biggest problem. That's clear from the fact that our Travis-only tests run much faster than our SauceLabs tests. E.g. in [this build](https://travis-ci.org/pouchdb/pouchdb/builds/217294043):

- PhantomJS: 19 minutes
- Firefox: 17 minutes
- Chrome: 22 minutes
- Safari: 23 minutes

So we are paying about 3-5 extra minutes per test that runs in SauceLabs.

**Comment by nename0** [comment]
The time spent in saucelabs for PRs has been reduced a bit by: #6880

**Comment by daleharvey** [comment]
A possibly small change that would half the test times right now is if someone could figure out and prevent travis from running 2 full test suite runs on PR's (https://github.com/pouchdb/pouchdb/pull/6907), it does it mostly on greenkeeper PR's and not users, but still not certain why

**Comment by nename0** [comment]
Seems like this is somehow intentional: [Source](https://github.com/greenkeeperio/greenkeeper/issues/221#issuecomment-226721625)

**Comment by daleharvey** [comment]
Filed a bug @ https://github.com/greenkeeperio/greenkeeper/issues/561

**Comment by daleharvey** [comment]
@nename0 in general I would like to avoid using `pinned` as it defeats the purpose of the stalebot (we can just comment if we want to keeps bugs open). However most definitely pinned is for straight up bugs, make the test suite faster is a vague goal that will be true forever, its only useful as an open bug to track current work so should be closed if there is none. cheers

**Comment by daleharvey** [comment]
Closing out, test suite can always be faster but not focus of current work
