### ISSUE TITLE
find custom mapping strategy for index

### ISSUE THREAD

**Issue by nerumo** [pouchdb/pouchdb#6387]
The mapping strategy for index is quite basic and can't be controlled from outside. I'd like to have the ability to define a custom mapping function per field.
E.g.
```
{
  _id: 'foo',
  referenced: [1,2,3]
}
```
To create the index:
```
{
  index: {
    fields: [{
      referenced: function(doc) { 
        if (doc.referenced) 
           doc.referenced.forEach(function(r) { emit(r, doc); });
      }
    }]
  }
}
```

**Comment by nolanlawson** [comment]
I'm sorry, but I'm having trouble understanding. How is this not possible today using map/reduce? What kinds of behavior do you want to be "controlled from outside"?

**Comment by nerumo** [comment]
Sorry for the delay. So, you're right, I can control it with map/reduce. Now I understand the concept of the find api a little bit better, so I understand that it's basically designed for simple field indexing and everything else must be achieved by map/reduce.
In the first place I thought of the find api as a full replacement for the query api, but it's more an addition which runs side by side with the query api. Please correct me if I assumed wrong.

Since the find api is much easier to work with I'd like to do as much as possible with it. Also the find api offers more functionality like in memory search etc. That's the reason why I mostly want to use the find api instead of map/reduce. 
I'd like to control the methods in the abstract-mapper.js module of the find api so that I could control how the index is actually built and still have the advantages of the find api.

But I see the conflict with the mango api definition which wouldn't align anymore. What do you think?
