### ISSUE TITLE
How to update an attachment

### ISSUE THREAD

**Issue by tshad** [pouchdb/pouchdb#6391]
I have an attachments table where there are multiple attachments per ID.  You're examples don't seem to show how to update or delete an attachment from a doc.

One of the things I am doing first is trying to add a field to an attachment that signifies that the attachment, not all the attachments for a record, need to be deleted.

For example, if I have an ID of "006", which has 3 attachments, I may want to delete one of them later. So I want to add a field (IsDeleted = true) to the attachment like I do with my other databases,

```
function deleteAttachment(id, fileName) {
   return DB_TaskImages.get(id, { attachments: true }).then(function (doc) {

      doc._attachments[fileName]["IsDeleted"] = true;

      return DB_TaskImages.put(doc);
   }).then(function () {
      return;
   }).catch(function (err) {
      showMsg("Error in deleteTask: " + err);
   });
}
```
This goes through as if it worked, but when I look at the database, none of the attachments have that field in them.  But before I do the put, if I look at the doc, it is there.

Can you add a field to the attachment other than the predefined fields?

If so, how would you go about doing that?

Thanks,

Tom

**Comment by garrensmith** [comment]
Issues isn't the place to ask these kinds of questions. Rather use one of these:

[Mailing list](https://groups.google.com/forum/#!forum/pouchdb)
[Slack](http://slack.pouchdb.com/)
[Stackoverflow](http://stackoverflow.com/questions/tagged/pouchdb)

**Comment by tshad** [comment]
Not sure why you closed this.

I did post this on Stackoverflow and no one answered.  My question seems pretty logical to go here.  I just wanted to know if you can add other fields to the attachment record other than those that Pouch puts there.  This is not covered in your documentation (everything else seems to be).  If you cannot, fine.  This has to do specifically with pouch and not promises.

Thanks.

**Comment by karlwestin** [comment]
Hi!
It looks to me like we're selecting a few keys that we allow on attachments, see here https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/adapter.js#L68-L69 Anything else will be removed.

Here's an example on how to delete an attachment in PouchDB: https://pouchdb.com/api.html#delete_attachment
