### ISSUE TITLE
Undefined values for pouches-find keys return 0 results

### ISSUE THREAD

**Issue by splodingsocks** [pouchdb/pouchdb#6392]
### Issue
I'm using pouchdb-find version `0.10.5` and pouch version `6.1.2`.
I've got a function which builds up a query to be passed to `.find`. Optionally the caller can pass skip and limit values as function parameters. When those function parameters aren't passed, I just set the values on the query object to `undefined`, like so:

```
{
    selector: { name: { $gte: null } }
    , sort: ["name"]
    , skip: undefined
    , limit: undefined
}
```

According to my experimentation, that query finds the correct index, but returns 0 results.
But if I remove skip and limit entirely from the object, the expected results are returned.

### Info
- Environment: Browser
- Platform: Safari 10.0.3
- Adapter: Unspecified
- Server: N/A

### Reproduce
Visit https://nolanlawson.github.io/pouchdb-find/
and run the query:

```
db.find({
  selector: {name: {$gte: null}},
  sort: ['name'],
  skip: undefined,
  limit: undefined
});
```

EDIT: I just realized that the reproduction steps above just make the page return an error, not 0 results. I hope I've given you enough to go on here. Sorry if it isn't sufficient.

**Comment by nolanlawson** [comment]
I don't think we've ever been consistent in any of our APIs about the difference between `undefined` values and unspecified keys (e.g. for limit/skip/etc. in map/reduce or in pouchdb-find).

Most likely what's happening here is that `limit` is being coerced to a 0 and thus you get zero results. My recommendation is to only pass in `skip` or `limit` when you're sure it's a number.

OTOH maybe we should have a consistent policy about this. arguably `undefined` should just be treated as if the key had not been included in the first place.

**Comment by garrensmith** [comment]
> arguably undefined should just be treated as if the key had not been included in the first place.

I agree with that. I'll try and get a fix in for this.
