### ISSUE TITLE
RFC: April release

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6396]
It's been awhile since a release; we should do 6.2.0. I imagine it's a minor release because the "new feature" is that pouchdb-find is being taken out of beta.

This isn't to say that pouchdb-find is perfect yet, but it is fairly well fleshed-out, and any bugs can be fixed quickly without affecting user data since all of the bugs I'm aware of are in the runtime query engine and not in the indexer.

**Comment by garrensmith** [comment]
+1

All misspelling thanks to my iPhone.
________________________________

**Comment by willholley** [comment]
+1. We'll also have selector support in replication/_changes in this release.

**Comment by garrensmith** [comment]
Done https://pouchdb.com/2017/04/20/pouchdb-6.2.0.html
