### ISSUE TITLE
Limit rev is not working

### ISSUE THREAD

**Issue by pekubu** [pouchdb/pouchdb#6397]
### Issue
Hi.
I use this.db = new PouchDB(this.get_source(),{revs_limit: 1});
but pouchdb create many rev in database, I don't use sync, pls help me.
Thanks all.
`"KH0000001::10-fe8d372818a4de54965b401690741f32"	1009	Object
"KH0000001::11-9dbf185c136d2aab6eaad85403688398"	1010	Object
"KH0000001::12-e6bbb98b13e7a880372122c37cd69362"	1011	Object
"KH0000001::13-9edbfb16876b94de23e9482a7beee054"	1012	Object
"KH0000001::14-abd9458e08acc8a24e7235c75f5e4219"	1013	Object
"KH0000001::15-ea63e14b6fad23b2e7613660926e38e1"	1014	Object
"KH0000001::16-ecd10cb4a2b7b30f71d0137512508367"	1015	Object
"KH0000001::17-447f1122a2bb5c97aaf29c48498adcaa"	1016	Object
"KH0000001::18-9f3f8e4876d9821552f798ab79aef43f"	1017	Object
"KH0000001::19-77b445bd5e79cb00548f5c5e9e252da3"	1018	Object
"KH0000001::20-fde397a68274695664dc190ab8dabe57"	1025	Object
"KH0000001::21-12d2e4282f9495b79a1bc0bc75bbf0b9"	1026	Object`
### Info
- Environment: Angular2
- Platform: ALL
- Adapter:  ALL
- Server: No Sync

### Reproduce
Write the steps for others to reproduce issue here. Providing a code example, links to a repository or a live example (JSBin etc) are even more helpful.

**Comment by karlwestin** [comment]
I'm not sure i understand your question right so bear with me :)

The `revs_limit` option does not mean that new revisions are not created, it limits the number of revisions that are kept in the database. A new revision is always created when updating a document. I made this example to show revs_limit in action http://jsbin.com/yocopoyeci/edit?js,output

It would be super helpful if you could post a JSBin and more explanation of what you expected to happen! Thanks!

**Comment by pekubu** [comment]
how to stop it

**Comment by karlwestin** [comment]
I understand you're frustrated by a feature that does not work as you expected it to, I'm sorry about that but it's a little bit hard to understand what you want to achieve? 

Is it that...

a) you want to update a document without creating new revisions? (this is not possible)
b) you're writing the document once but some bug creates the other 20 revisions?
c) something else?

Like i said above, it would be super helpful if you could post a little bit of the code you're having!

**Comment by pekubu** [comment]
I want to update a document without creating new revisions
my code 
`public save() {
    let db = this.get_db();
    let data = this.get_data();
    let t = this;
    console.log('Save:' + this._id);
    db.get(this._id, {conflicts: false})
      .then(function (doc) {
        data._rev = doc._rev;
        return db.put(data);   // put updated doc, will create new revision
      }).then(function (res) {

    }).catch(function (err) {
      if (err.status === 409) {
        return t.save();
      } else if (err.status == 404) {
        db.put(data).then(function (response) {
        }).catch(function (err) {
          console.log(err);
        });
      } else {
        console.log(err);
      }
    });
  }`

**Comment by karlwestin** [comment]
Thanks for posting the example!
Unfortunately it's not possible to update a document without creating new revisions in PouchDB

I understand it's frustrating with the bookkeeping that is needed with revisions, but i think you're code looked pretty fine! If you want to, you can change the flow a little bit like this, https://gist.github.com/karlwestin/81fa111781350e2f77010f10c9e94cc1 then you don't have to duplicate the put

I'm gonna be back in a few hours but feel free to post any follow up here

**Comment by pekubu** [comment]
thank you.

**Comment by karlwestin** [comment]
@pekubu i'm closing this one for now, feel free to open again if there's any more related questions!
