### ISSUE TITLE
Cannot sort on field(s) "XXX" when using the default index

### ISSUE THREAD

**Issue by leolivier** [pouchdb/pouchdb#6399]
### Issue
In PouchDB-find (0.10.5) I get an error message 

Cannot sort on field(s) "order" when using the default index

The query is as follow:
```
that.db.createIndex({
        index: {fields: ['notebookid', 'order']}
      }).then(function () {
        that.db.find ({
          selector: {
            $and: [
              {notebookid: {$exists: true}},
              {notebookid: {$eq: notebookid}}
             ]},
          sort: [{order: 'desc'}]
        })
```
### Info
- Environment: Angular 2 app including PouchDB 6.1.2, NodeJS 7.8 only for building
- Platform: Chrome 57 on Linux Mint.
- Adapter: IndexedDB afaik
- Server: CouchDB

### Reproduce
See the query above.
If needed, I can provide the full code.

**Comment by na-ji** [comment]
Hello @leolivier,

I had the same issue as you, but I re-read the doc on the other repo and I finally found a solution: `Note that sorted fields also have to be selected in the selector.` So I think you should add `order` to your selector with a condition that is always true.

**Comment by leolivier** [comment]
Hi na-ji, thanks for the trick but I tried this:
```
      that.db.createIndex({
        index: {fields: ['notebookid', 'order']}
      }).then(function () {
        that.db.find ({
          selector: {
            $and: [
              {notebookid: {$exists: true}},
              {notebookid: {$eq: notebookid}},
              {order: {$exists: true}}
             ]},
          sort: [{'order': 'desc'}]
        })

```
and I still get the same error:
`Cannot sort on field(s) "order" when using the default index`

**Comment by raphadko** [comment]
Having exactly the same problem here. Any updates on this?

**Comment by siiar** [comment]
@leolivier @raphadko Replace "{order: {$exists: true}}" with "{order: {$gt: null}}" and it should work.
#https://github.com/nolanlawson/pouchdb-find/issues/204

I will elaborate a little more on this because it didn't work for me in the beginning. I was creating the indexes in my pouchdb handler class but after creating the index separately and using the find method inside its callback function, everything worked fine. Now even after removing the createIndex method, it works just fine. Here is what worked for me:
```
     that.db.createIndex({
        index: {fields: ['notebookid']}
      }).then(function () {
        that.db.find ({
          selector: {
            $and: [
              {notebookid: {$exists: true}},
              {notebookid: {$eq: notebookid}},
              {order: {$gt: true}}
             ]},
          sort: [{'order': 'desc'}]
        })
```

Following is the code that failed:
Creating indexes in a one class
```
that.db.createIndex({
   index:{
      fields:[notebookid,order]
   }
})
```
Then calling the find method from a different class:

```
that.db.find ({
          selector: {
            $and: [
              {notebookid: {$exists: true}},
              {notebookid: {$eq: notebookid}},
              {order: {$exists: true}}
             ]},
          sort: [{'order': 'desc'}]
        })
```

**Comment by leolivier** [comment]
Thanks siiar, it works!

(Nevertheless, I think that must be fixed in the plugin...)

**Comment by garrensmith** [comment]
@leolivier this will most likely not be fixed in pouchdb-find. We follow CouchDB's design and it won't be fixed there either. The best reason to explain why is to look at an example:

Say we have a database with 10 million documents in it. Then we do a query that retrieves 3 million documents using a predefined index. Now we want to sort the documents using a field that is not in the index. This would require CouchDB/PouchDB to load all those documents into memory and sort them. There is a large chance this would cause an out of memory operation and cause CouchDB to crash. Or in PouchDB's situation, your browser to crash. We want to avoid this. So the only way sorting can happen is via the map/reduce index that is the start of the pouchdb-find. The sort then happens in the B-tree on disk and doesn't require the whole database to be read into memory.

I hope that helps explain this situation a little more.

**Comment by leolivier** [comment]
@garrensmith, I can understand that you want to mimic CouchDb but replacing
{ order: {$exists:true}}
By
{ order: {$gt:true}}
To get things working looks weird to me (or there's something I didn't get) and I'm not sure it comes from CouchDb...
(And also it was tagged as bug by you :)

**Comment by wende60** [comment]
@garrensmith this behaviour should be explained more clear in the documatation incl. working examples, as it is hard to understand. I gues many people - like me - end up beeing really frustrated while trying to sort data.

**Comment by garrensmith** [comment]
@wende60 I'm sorry you found this frustrating. I totally agree, this information needs to be in the docs. We are an opensource, volunteer community. So we don't always have time to make everything perfect. It would be great if you could help us by adding the information in the docs.

**Comment by RevillWeb** [comment]
Hi All, I am still having this issue in PouchDB 6.2.0. Any help would be greatly appreciated. Here is my `createIndex` and `find` code:

```
db.createIndex({
  index: {
    fields: ["title", "amount"]
  }
}).then(function (result) {
  db.find({
      selector: { title: { $eq: "Mr" }, amount: { $gt: 0 } },
      sort: ["amount"]
    }).then(function (result) {
      console.log("RESULT:", result);
    }).catch(function (err) {
      console.log(err);
    });
}).catch(function (err) {
  console.log(err);
});
```

I always get the error "Cannot sort on field(s) "amount" when using the default index", what am I doing wrong here? I've also tried `amount: { $gt: true }` and `amount: { $exists: true }`. I'm using Chrome 59.

If there isn't an obvious mistake here let me know and I can create a working example.

Thank you!

**Comment by garrensmith** [comment]
@RevillWeb that could be a bug. Could you try changing your index to be:

```
db.createIndex({
  index: {
    fields: ["amount", "title"]
  }
})
```

**Comment by RevillWeb** [comment]
Yes the works! Thank you. So until the bug is fixed do the order by fields need to be first?

**Comment by RevillWeb** [comment]
I also get the same issues when I try and use an $or selector:

```
db.createIndex({
  index: {
    fields: ["amount", "title"]
  }
}).then(function (result) {
  db.find({
      selector: { $or: [ { title: "Mr." }, { title: "Mrs." } ] },
      sort: ["amount"]
    }).then(function (result) {
      console.log("RESULT:", result);
    }).catch(function (err) {
      console.log(err);
    });
}).catch(function (err) {
  console.log(err);
});
```

**Comment by bekand** [comment]
This is still an issue as of today. You can't sort or search on any index except __id_ and the first one created by _createIndex_. Rebuilding the indexes for each search is not a feasible workaround for large datasets

**Comment by lukechilds** [comment]
@bekand also just ran into this. Tracking this specific bug here: https://github.com/pouchdb/pouchdb/issues/7207

**Comment by ednsinf** [comment]
This issue not solved at this current version ("pouchdb-find": "^7.2.2"):
Cannot sort on field(s) "price" when using the default index
[...]node_modules\pouchdb-find\lib\index.js:1250:5

**Comment by devmetal** [comment]
Sure thing. I have the same issue. :/

 ```TypeScript
export const createIndex = () =>
  db.createIndex({
    index: { fields: ['kind', 'createdAt'] },
  });
```

Later in the app:

```TypeScript
const result = await db.find({
    selector: {
      kind: 'foo',
    },
    sort: ['createdAt'],
  });
```

Error: Cannot sort on field(s) "createdAt" when using the default index

**Comment by sudhirbitsgoa** [comment]
same issue here

**Comment by luco** [comment]
Same here

**Comment by SuperKirik** [comment]
The same issue 
`"pouchdb-find": "^7.2.2",`

**Comment by fishfitz** [comment]
Reading the plugin code:
```js
// e.g. ['a'], ['a', 'b'] is true, but ['b'], ['a', 'b'] is false
function oneArrayIsSubArrayOfOther(left, right) {

// check that at least one field in the user's query is represented
// in the index. order matters in the case of sorts
function checkIndexFieldsMatch(indexFields, sortOrder, fields) {
```

Seems like the order of the index fields matter... Putting the order field first do work. I have not seen that documented anywhere but it works.

```js
await db.createIndex({
  index: { fields: ['createdAt', 'kind'] }, // createdAt must be first
});

await db.find({
  selector: { kind: 'foo' },
  sort: ['createdAt']
});
```

**Comment by wxfred** [comment]
await db.createIndex({ index: { fields: ['create_at', 'id'] }})
