### ISSUE TITLE
Is it possible to have PouchDB both inside and outside of a worker on the same database?

### ISSUE THREAD

**Issue by jackkleeman** [pouchdb/pouchdb#6401]
### Issue
We currently have pouchdb inside a worker doing replication and almost all operations on a single database. We were hoping to be able to set up an instance in the main thread too, primarily just for reading the same database and providing state to the UI (all non-UI operations happen in the worker). It seems that when we try to create the PouchDB instance in the main thread, when the one in the worker is already created, the main thread PouchDB instance falls back to webSQL (occasionally with an adapter idb not valid error, we think), and doesn't use indexeddb like the one in the worker, so they are two different databases with the same name, effectively. Is this expected behaviour? Is it possible to read the same database across different threads? I know that sounds like race condition territory (although the pouchdb revision ids should mitigate a lot of this), but if this is the reason it's disabled, could it be overriden, given we only need read access in the main thread? Of course, we can always proxy all the read requests to the worker using postmessage if we need to, but one of the advantages to indexeddb is the ability to share information across threads, so it would be cool for pouchdb to support this.

If this is expected behaviour, I think there should be an error of some kind, as it is very easy to think that you have succeeded, but then you get 404s trying to read documents you know exist.

### Info
- Environment: Browser
- Platform: Experienced on Chrome and Safari, may occur elsewhere
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
1. Create a database using PouchDB in a web worker
2. Create a database with the same name in the main thread
3. Run db.info() on both and see that they are using different adaptors.

cc @JustinDrake

**Comment by JustinDrake** [comment]
The situation we were in seems to be that IndexedDB was succeeding in a WebWorker, but failing in the main thread (possibly because IndexedDB was full). This created a strange situation were the same database (as identified by name) was actually two separate databases.

I'm now forcing the adapter with `new PouchDB(dbName, {adapter: 'idb'});` but maybe having both a worker and the main thread read the same DB is bad practice anyway.

**Comment by nolanlawson** [comment]
IndexedDB is threadsafe so you should be able to use it both in a worker and on the main thread. In the case of WebSQL it was [https://html5workertest.com](removed from both Safari and Chrome) so for Safari you would have to use something like [pseudo-worker](https://github.com/nolanlawson/pseudo-worker) to work around this, at least until we add Safari 10.3+ IDB support. Let me know if that helps!
