### ISSUE TITLE
Provide a ES6 Modules custom build

### ISSUE THREAD

**Issue by balupton** [pouchdb/pouchdb#6404]
As ES6 Modules has landed in Safari now. It would be nice if `pouchdb-browser` came in a custom browser that pre-converted the Node.js Module format to the ES6 Module format, such that we can just do a:

```
<script src="cdn.com/pouchdb-browser-module.js" type="module"></script>
```

Yes, we can use rollup or some build tool. But as browsers are becoming more capable, and as HTTP2 and caching rewards multiple requests, the benefit of bundlers gets less.

**Comment by nolanlawson** [comment]
Yep, this is available on unpkg for those who want it: https://unpkg.com/pouchdb@6.2.0/lib/index-browser.es.js

**Comment by thmarti** [comment]
Maybe I'm understanding this wrong, but I get 
`Uncaught TypeError: Failed to resolve module specifier 'lie'`
with 
`<script type="module" src="https://unpkg.com/pouchdb@6.2.0/lib/index-browser.es.js"></script>`

Any hints?

**Comment by rjsteinert** [comment]
Hi @nolanlawson - What is the timeline for getting the ES6 Module compatible build into the npm package for PouchDB? ES6 modules FTW!

**Comment by rjsteinert** [comment]
It seems like the new development here is that projects like Polymer are migrating from Bower to using Yarn `"flat": true` and getting dependencies from the NPM registry only to find that things in the NPM registry don't always play nicely with the new ES6 module way of doing things. Even if PouchDB published the build that puts PouchDB in the global namespace that would be helpful. Our solution for now is to __keep using bower__ for packages like pouchdb that haven't caught up with this bower to yarn migration.

**Comment by rjsteinert** [comment]
Relevant Polymer announcement here -> https://www.polymer-project.org/blog/2017-08-22-npm-modules

**Comment by rjsteinert** [comment]
I created a new issue for this in case this issue is flying under the radar https://github.com/pouchdb/pouchdb/issues/6926

**Comment by m59peacemaker** [comment]
Is it not possible to use pouchdb with rollup for the browser? I have tried every kind of import/require and config and plugin I can think of. Every combination has some kind of a problem. Same with `pouchdb-browser`.

**Comment by m59peacemaker** [comment]
At last, I am doing this and it works:

```js
import PouchDB from 'pouchdb-core'
import idb from 'pouchdb-adapter-idb'
import http from 'pouchdb-adapter-http'
import replication from 'pouchdb-replication'

PouchDB
  .plugin(idb)
  .plugin(http)
  .plugin(replication)

export default PouchDB
```

```js
  // rollup plugins I'm using
  commonjs(),
  nodeGlobals(),
  nodeBuiltins(),
  resolve({
    module: true,
    browser: true,
    jsnext: true,
    main: true,
    extensions: [ '.js', '.json', '.mjs', '.es' ]
```

**Comment by jarrodek** [comment]
The "https://unpkg.com/pouchdb@6.2.0/lib/index-browser.es.js" has invalid syntax for ES modules. Imports has to start with `./` or `../` according to spec. This requires using additional tools to convert paths when in development mode.

**Comment by djlauk** [comment]
unpkg.com can rewrite the bare module specifiers, but you need to add `?module` to the URL. The correct URL would then be: https://unpkg.com/pouchdb@6.2.0/lib/index-browser.es.js?module

This should then be rewriting all the module specifiers.
