### ISSUE TITLE
Deleting a non-existing attachment neither succeeds nor fails

### ISSUE THREAD

**Issue by flimzy** [pouchdb/pouchdb#6409]
### Issue
When I try to delete an attachment that does not exist, I neither get an error message (which I would expect), nor a successful response.

### Info
- Environment: Node.js 6.10.0
- Adapter: default

### Reproduce
Execute the following code in nodejs:

    var PouchDB = require('pouchdb');
    var db = new PouchDB('foo');
    db.put({ _id: 'foo' }, function(e,r) {
        if ( e ) {
            return console.log(e);
        }
        db.removeAttachment('foo','foo.txt',r.rev,function(e,r) {
            console.log('error: ' + e);
            console.log('result: ' + r);
        })
    });

And observe the following output:

    error: null
    result: undefined

I would have expected a "not_found" error.

**Comment by flimzy** [comment]
For whatever it's worth, PouchDB is in good company here. CouchDB has similar problems. :)

- https://issues.apache.org/jira/browse/COUCHDB-3362
- https://issues.apache.org/jira/browse/COUCHDB-3363

**Comment by flimzy** [comment]
Why is the bot auto-closing legitimate, acknowledge issues? :(

**Comment by daleharvey** [comment]
That's what the bot does, if there is nobody working on the issue then it being tracked just gets in the way of tracking active work
