### ISSUE TITLE
Same database in multiple tabs?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#6413]
When running several tabs working against the same database I get a lot of errors... is this normal?

![screen shot 2017-04-07 at 15 19 19](https://cloud.githubusercontent.com/assets/3065230/24801713/a43ed4bc-1ba5-11e7-8df9-d4ea62d2f074.png)

Chrome  57.0.2987.133 (64-bit)
MacOS

**Comment by nolanlawson** [comment]
This is not normal, no. Do you have a reproducible test case?
