### ISSUE TITLE
Electron w/ PouchDb (PouchDB Server)

### ISSUE THREAD

**Issue by flamusdiu** [pouchdb/pouchdb#6414]
### Issue
I am working on an application which I need to pre-stage a DB to ship with this application in some way. Using either PouchDB Server or serving a NodeJS PouchDB object through globals to Electron both seem to be the way to do this. 

Which way is the recommended way to access both PouchDB inside Electron and outside of it (for pre-shipping and updating). 

I know that [gr2m/spawn-pouchdb-server](https://github.com/gr2m/spawn-pouchdb-server)  is not maintained and it doesn't work well with PouchDB Server 2.x from my testing. I assume if I would use the PouchDB server, then I'll need to create my own spawn function to use within the preload.js script.

### Info
- Environment: Node/Electron
- Platform: Windows
- Adapter: LevelDB
- Server: PouchDB

**Comment by flamusdiu** [comment]
I managed to do a rewire with https://github.com/gr2m/spawn-pouchdb-server and I am using that with electron for now unless there is a better way to do what I am doing. Either way, it's working. =)

**Comment by flamusdiu** [comment]
Well, now looks like I have to abandon that way. Some reason, when I spawn the DB, it causes a major memory leak. It hangs before it DB is created. It stopped working reliably.

**Comment by Rainbow-Unicorn-Oo** [comment]
Have you ever found a way to spawn a pouchdb server from inside an electron app?

**Comment by Rainbow-Unicorn-Oo** [comment]
Or any other method to have a reactive database across your entire electron app?
