### ISSUE TITLE
Sync in parallel, get overall progress percentage

### ISSUE THREAD

**Issue by YuantongL** [pouchdb/pouchdb#6416]
I have several PouchDB sync with remote in parallel when my application starts, how do I get the overall progress of the sync?

I'm using something like Promise.all to make them sync at the same time...

Any ideas? Thanks!

**Comment by akircher** [comment]
CYA: I am not an expert and there probably is a better way to do this.

I calculate an overall percentage manually in my code
https://github.com/dscsa/pouch/blob/master/pouchdb-client.js#L33-L60

Hope that helps
