### ISSUE TITLE
So what about attachments now?

### ISSUE THREAD

**Issue by tseck** [pouchdb/pouchdb#6418]
Hi there,

so I've tried the attachments and am getting a ETIMEDOUT-Error on getAttachments(..) and the attachments are not downloaded/synced automatically.
 I am syncing the remote to the local db and getting the documents with db.allDocs({include_docs: true, limit: null, attachments: true}), still no attachments.
Via curl it goes, it can download attachments.

Is there anything else I would need to do, like adding attachments: true to the sync-command or should this be functioning then?

I have about 300 attachments á 20kb each.

Running version 6.1.2 of pouch and 6.1.26 of pouchdb-react-native.

Do I have to set any CORS or alike?

Or are attachments still not recommended (even only those some MB of data which is, sorry, but ridiculous nowadays)? 

People are spending lot of time trying to implement this possibly wasted.

Regards

**Comment by karlwestin** [comment]
Hello!
The attachments are usually working fine, i've been using them in several projects myself, 20kb shouldn't be out of limit for this.

I understand that your setup looks like this, is this correct?

A. A server CouchDB, lets say in this example served from localhost:5984

B. A browser webpage served from a different origin, lets say localhost:3000

If i understand your problem correctly, you have the attachments in A, and you have confirmed that through the CouchDB user interface. You are then replicating A into B via PouchDB 
`B.replicate.to(A)`, and when you read documents from B like `B.allDocs({ include_docs: true, attachments: true })` the attachments are not included?

There's a few tricky setups around attachments, whether you use binary, base64 or just text attachments.
It would be awesome if you could post some example code (please use jsbin.com or something similar), so we can investigate this issue further!

Thanks

**Comment by der-ede** [comment]
Hi @karlwestin ,

thank you for the fast response. As this is a customer project I would have to set up a new database on cloudant to try out. 
Also it is in react-native (pouchdb-react-native) but we  can try with plain web, probably it is not the react-native side that leads to the error.
So how about this:  I check if I can find the bug myself in a short term since it is some effort to put everything on jsbin, but if I don't find it, I will get back at your offer, ok?

Regards

**Comment by karlwestin** [comment]
oh i didn't know this was react native

i think there's a little bit different story with attachments there
I don't know react-native at all myself, but there have been issues and i'm not sure we're entirely in the clear there yet. Please search our past issues about react native and maybe you'll find some tips.

**Comment by der-ede** [comment]
Ok, thought so. Thanks anyway.
