### ISSUE TITLE
bulkDocs() trigger the "change" event multiple times

### ISSUE THREAD

**Issue by raphadko** [pouchdb/pouchdb#6424]
Using bulkDocs() trigger the changes() function multiple times. In medium to big data sets this will run the callback function  (in my case, redraw the UI)  hundreds or even thousands of times making the frontent unresponsive.

I'm not sure if this is the expected behavior, but since bulk will often deal with large data sets, it would probably be a good idea to insert a "singleChange" option on bulkDocs() or a "bulkSingleChange" option on changes().

**Comment by daleharvey** [comment]
This is expected behaviour, the changes api has the same semantics regardless of what is being used to write, if you need to throttle the changes its simple to do in your own code so I dont think we want to implement it inside pouchdb, cheers
