### ISSUE TITLE
pouchdb-find: $in does not use index on array field

### ISSUE THREAD

**Issue by ethanroday** [pouchdb/pouchdb#6425]
### Issue
Using the `$in` selector to query on an array-valued field results in the `no matching index found...` warning, despite the fact that the field has been indexed.

### Info
- Environment: browser extension
- Platform: Chrome
- Adapter: IndexedDB
- Server: None

### Reproduce
Create a set of documents with the following structure (for each document):
```
{
  type: 'webpage',
  tags: ['a','b,'c',...]
}
```
Create the following index:
```
db.createIndex({
    index: {
      fields: ['tags', 'type']
    }
  });
```
Run the following query:
```
db.find({
  selector: {
    type: "webpage",
    tags: {
      $in: ['a']
    }
  },
  fields: ["_id"]
});
```
The query works, but the result includes the `no matching index found...` warning, event though the `tags` field has been indexed. (Removing the `tags` portion of the query selector makes the warning go away.)

I arrived at this syntax based on [this Cloudant blog post](https://cloudant.com/blog/cloudant-query-grows-up-to-handle-ad-hoc-queries/#.WPD5UNLytaQ) (see the query by genre under "match value is in array"). From what I can gather there, the expected behavior is that the index be used. In that post, though, the index type is `text`, so that may change things.

I also tried `$elemMatch` but ran into the same error as #6327.

Is there a correct way to query on an array field that uses the index? The map/reduce equivalent for this is fairly straightforward.

**Comment by jefbarn** [comment]
You've run into the major hole in the pouchdb/couchdb find implementation. Currently couchdb find does not support indexing array members (https://issues.apache.org/jira/browse/COUCHDB-2867). Pouchdb is matching Couchdb's implementation here.
Cloudant works around this by using Lucene, which isn't available on couch/pouch

**Comment by ethanroday** [comment]
I see. Is there a straightforward way to set a more informative warning for this scenario?

**Comment by eolant** [comment]
In my case query is not running displaying
`{error: "no_usable_index", message: "There is no index available for this selector."}`
Is there a way to query documents with a matching tag?

**Comment by dyrkow** [comment]
You can use `$all` operator from MQL

For example

```
db.find({
  selector: {
    tags: {
      $all: ['a']
    }
  }
});
```
