### ISSUE TITLE
destroy on safari on IPhone and Pouch.

### ISSUE THREAD

**Issue by tshad** [pouchdb/pouchdb#6428]
I am getting an error when I try to do a destroy on my attachment table.  This works fine on safari on the desktop and chrome but not on the IPhone safari.

When do the following:

```
   }).then(function () {
      if (DB_TaskImages != null)
         return DB_TaskImages.destroy();
   }).then(function () {

```
It goes to the catch with this error:

{“status”:500 “name”:”web-sql-went-bad”,”message”:”undknown”,”reason”:”Security:Error”:”DOM Exception 18”}

I had a different error before I had increased the size of the database to 100 MB.  Even that was strange as I had set it as: 

 DB_TaskImages = new PouchDB(DBNAME_TaskImages, { auto_compaction: true, size: 100});

But the dialog box that came up asked if I wanted to change the size to 500 MB.

Not sure if that is related.

Thanks,

Tom

**Comment by tshad** [comment]
I was getting the above error on my IPhone 4s.  On the IPhone 6s, I was getting: 

"QuotaExceeded" error.

I don't know why this is causing an error, but when I take the "size" parameter off, it work fine.  Of course, now I hit the 5MB limit real quick since I am dealing with images.

**Comment by mnewmedia** [comment]
You got it, it's because of the 5mb limit, when creating the db use the options `{adapter: 'cordova-sqlite'}` and the plugin [cordova-plugin-sqlite-2](https://github.com/nolanlawson/cordova-plugin-sqlite-2). To avoid any problem on IOS.

**Comment by tshad** [comment]
Would this same plug-in and option work on all devices?  This app may be used by desktops, iphones, ipads, androids using safari, chrome or firefox.

Thanks.

**Comment by mnewmedia** [comment]
this adapter and plugin only works in a [cordova](https://cordova.apache.org/) envoirment. But you can do something like:
```js
let dbOptions = {adapter: 'cordova-sqlite'};
if (!cordova) {
  delete dbOptions.adapter;
}
```

**Comment by mnewmedia** [comment]
Please close the issue if it's solved.
