### ISSUE TITLE
Cloudant replication best practice

### ISSUE THREAD

**Issue by chino23** [pouchdb/pouchdb#6429]
I love this library and the ability to sync with Cloudant API.

However, it creates kind of a problem for me with the way Cloudant charges for requests. On a single user, having a few hundred documents, syncing every other day creates that many requests that it's absolutely not economically viable to use it as a backend. I end up paying a few bucks a months for every user, with thousands and thousands of requests, including a lot of tombstones I think.

Is there a way to drastically reduce the requests or does someone have something working already to greatly reduce the needed requests? Just one way syncing either way it just goes through everything, and I cant stop thinking that there must be a better way.

**Comment by sagarkm** [comment]
If initial download is a concern for you, then I would recommend you perform a daily / weekly pouchdump on your cloudant DB and host the dump file on any web server.
Then on every fresh install user would directly download the dump and create the pouch db form it.

Also unless you to-the-minute updated data locally you can decide on the frequency of how often you want to perform a sync of pouchdb. You can store the last sync time on your local storage and only when the difference with current timestamp is more than the threshold so can perform a sync, else work with slight slate data on the pouch.

**Comment by willholley** [comment]
@chino23 you can also look at Cloudant pricing in [Bluemix](https://cloudant.com/bluemix/) instead of cloudant.com. The Bluemix pricing is based on reserved throughput rather than charges per request, so is generally more economical for sync use cases and allows you to cap your exposure.

**Comment by chino23** [comment]
Thanks, I'll check out the Bluemix offers
