### ISSUE TITLE
PouchDB not working on Ipad Chrome browser

### ISSUE THREAD

**Issue by sumedhm-iprogrammer** [pouchdb/pouchdb#6430]
### Issue
new PouchDB("db_name") is not working on Ipad chrome browser, it is throwing an error "Error: Invalid Adapater: undefined"

### Info
- Environment: browser
- Platform: Ipad Chrome browser
- Adapter: All
- Server: PouchDB

**Comment by nolanlawson** [comment]
This is most likely a known issue: https://github.com/pouchdb/pouchdb/issues/3382
