### ISSUE TITLE
Use replicate for bi-directional sync

### ISSUE THREAD

**Issue by YuantongL** [pouchdb/pouchdb#6431]
I have one local PouchDB and one remote CouchDB. I want the local one always pulling the latest update from remote, but push local updates only when I call it. 

So I set up something like
"PouchDB.replicate(remoteDB, localDB, {live:true, retry:true})" when both DB is initiated.

And then I have a function to call upload
function replicateUpload () {
  PouchDB.replicate(localDB, remoteDB, {live:false, retry:false})
}

Remote to local replication works fine, but when I call replicateUpload function, it always says
Error: ETIMEDOUT
    at XMLHttpRequest.r.onreadystatechange (index-browser.js:7368)
    at o (index-browser.js:7272)

What is the right way to do bi-directional replication? Or I have to use sync() instead?

**Comment by willholley** [comment]
@YuantongL that should work. It's hard to say what the problem is from the error message alone - do you know what request is failing (e.g. looking in the browser dev tools)?

**Comment by YuantongL** [comment]
That's the only failing request shown in the network, thoughts?

-General
Request URL:************
Referrer Policy:no-referrer-when-downgrade

-Request Headers
Provisional headers are shown
Accept:application/json
Referer:http://************:3000/
User-Agent:Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

**Comment by willholley** [comment]
@YuantongL the URL is the main thing I need - can you mask the hostname if it's sensitive?

**Comment by YuantongL** [comment]
@willholley Updated the url.

**Comment by ermouth** [comment]
If you use nginx as a proxym probably you need to increase timeouts and disable buffering. Like
```
keepalive_timeout       300s;
proxy_read_timeout      300s;
proxy_buffering off;
```
