### ISSUE TITLE
pouchdb-find Promise is not a constructor

### ISSUE THREAD

**Issue by semiautomatix** [pouchdb/pouchdb#6433]
I'm receiving and issue with a simple pouchdb-find query.

Error:

```
taskqueue.js?b66b:9 Uncaught (in promise) TypeError: Promise is not a constructor
    at new TaskQueue (eval at ./node_modules/pouchdb-find/lib/abstract-mapreduce/taskqueue.js (0.chunk.js:364), <anonymous>:9:18)
    at Object.eval (eval at ./node_modules/pouchdb-find/lib/abstract-mapreduce/index.js (0.chunk.js:356), <anonymous>:22:21)
    at eval (eval at ./node_modules/pouchdb-find/lib/abstract-mapreduce/index.js (0.chunk.js:356), <anonymous>:701:30)
    at Object../node_modules/pouchdb-find/lib/abstract-mapreduce/index.js (0.chunk.js:356)
    at __webpack_require__ (main.js:687)
    at fn (main.js:110)
    at eval (eval at ./node_modules/pouchdb-find/lib/adapters/local/abstract-mapper.js (0.chunk.js:396), <anonymous>:4:25)
    at Object../node_modules/pouchdb-find/lib/adapters/local/abstract-mapper.js (0.chunk.js:396)
    at __webpack_require__ (main.js:687)
    at fn (main.js:110)

Uncaught (in promise) TypeError: Promise is not a constructor
    at new TaskQueue (eval at ./node_modules/pouchdb-find/lib/abstract-mapreduce/taskqueue.js (0.chunk.js:364), <anonymous>:9:18)
    at Object.eval (eval at ./node_modules/pouchdb-find/lib/abstract-mapreduce/index.js (0.chunk.js:356), <anonymous>:22:21)
    at eval (eval at ./node_modules/pouchdb-find/lib/abstract-mapreduce/index.js (0.chunk.js:356), <anonymous>:701:30)
    at Object../node_modules/pouchdb-find/lib/abstract-mapreduce/index.js (0.chunk.js:356)
    at __webpack_require__ (main.js:687)
    at fn (main.js:110)
    at eval (eval at ./node_modules/pouchdb-find/lib/adapters/local/abstract-mapper.js (0.chunk.js:396), <anonymous>:4:25)
    at Object../node_modules/pouchdb-find/lib/adapters/local/abstract-mapper.js (0.chunk.js:396)
    at __webpack_require__ (main.js:687)
    at fn (main.js:110)
```

- Environment: ReactJS, Babel, Webpack
- Platform: Testing on Chrome
- Server: CouchDB/PouchDB Local
- pouchdb version 6.1.2
- pouchdb-find version 0.10.5

Steps:

```
import PouchDB from 'pouchdb';
import PouchFind from 'pouchdb-find';
PouchDB.plugin(PouchFind);
```

```
const db = new PouchDB(dbName, {skipSetup: true});	

db.find({
  selector: {name: 'Mario'},
  fields: ['_id', 'name'],
  sort: ['name']
}).then(function (result) {
  // yo, a result
}).catch(function (err) {
  // ouch, an error
});
```
Is this possibly an issue because of Webpack and Babel?

EDIT: the problem seems to stem from the pouchdb-promise import

EDIT2: works correctly with pouchdb 6.2.0

**Comment by semiautomatix** [comment]
I'm also receiving this issue with the pouchdb-authentication plugin.

**Comment by karlwestin** [comment]
i have seen something similar, it was a while ago but if i remember right it was because i was using npm 2 instead of npm 3. What's your versions?

**Comment by semiautomatix** [comment]
@karlwestin thanks for the swift reply.

```
>npm -version
3.10.5
```

**Comment by karlwestin** [comment]
then you're probably not seeing the same issue as i did :( sorry.

**Comment by semiautomatix** [comment]
Thanks for effort!

**Comment by karlwestin** [comment]
can you just try runnning this example in your browser? http://jsbin.com/ribeheguwa/edit?js,output

**Comment by semiautomatix** [comment]
@karlwestin 

Seems to run correctly:

```
"success"
[object Object] {
  docs: []
}

```

**Comment by karlwestin** [comment]
yeah im sorry it really sounds like there's smth going on with webpack/babel here

**Comment by semiautomatix** [comment]
Thanks, I'm going to ask on the boilerplate github page, too.

**Comment by karlwestin** [comment]
good luck! please post any follow-up here!

**Comment by semiautomatix** [comment]
I've managed to get pouchdb-find working by removing any reference to 'pouchdb-promise' and forcing native Promises. So the problem seems to be in that module, or possibly in the 'lie' module.

**Comment by semiautomatix** [comment]
Glorious news! The update (whilst I was sleeping) to pouchdb 6.2.0 appears to have resolved this issue for me.  Unfortunately pouchdb-authentication has yet to be updated, I will have to fork and maintain myself.

**Comment by karlwestin** [comment]
Nice!
I would like to take one more look at this... are you using some boilerplate setup? Would you mind sharing package.json and webpack/babel config?

Cheers

**Comment by semiautomatix** [comment]
Thanks @karlwestin. I've been using [https://github.com/react-boilerplate/react-boilerplate](react-boilerplate) for my React project. A straight forward installation, and then adding

`import PouchDB from 'pouchdb';
import PouchFind from 'pouchdb-find';
PouchDB.plugin(PouchFind);`

to the HomePage causes the error to occur, prior to 6.2.0

**Comment by semiautomatix** [comment]
I've managed to update pouchdb-authentication by updating the necessary pouchdb modules 

[package.zip](https://github.com/pouchdb/pouchdb/files/946539/package.zip)

Then I've altered \lib\utils.js

`var Promise = require('pouchdb-promise');`

to

`var Promise = require('pouchdb-promise').default;`

and 

`exports.ajax = require('pouchdb-ajax');`

to

`exports.ajax = require('pouchdb-ajax').default;`

**Comment by karlwestin** [comment]
There must be something more to it, i did the following:

1. Cloned the `react-boilerplate` repo
2. `USE_YARN=false npm run setup`
3. `npm install --save pouchdb@6.1.2 pouchdb-find`
4. Added the following lines to `app/app.js`
```javascript
import PouchDB from 'pouchdb'
import pdFind from 'pouchdb-find'

PouchDB.plugin(pdFind)

const db = new PouchDB('myDB', {skipSetup: true});

db.createIndex({
  index: {
    fields: ['name']
  }
})
.then(function () {
  return db.find({
    selector: {name: 'Mario'},
    fields: ['_id', 'name'],
    sort: ['name']
  })
}).then(function (result) {
  // yo, a result
  console.log('success', result)
}).catch(function (err) {
  // ouch, an error
    console.log('error', err)
});
```
5. `npm start`

When i go to `localhost:3000` i see 'success' in my console

I understand this is really frustrating for you, since you're in the middle of your project and things are not working. But if we're gonna be able to figure it out, we need a complete reproduction of the problem.

**Comment by semiautomatix** [comment]
Thank for checking it out. I note that you installed the latest version of pouchdb-find; I neglected to mention this was updated along with pouchdb yesterday and I was not using that version. Please try pouchdb-find@0.10.5 (which will install along with pouchdb-promise@5.4.0) - I suspect the update to this plugin (or possibly pouchdb-promise) is why it is now working (rather than the pouchdb update).

Note: pouchdb-authentication (which is still displaying the problem) uses pouchdb-promise@6.0.3

**Comment by karlwestin** [comment]
indeed it breaks with 0.10.5 just like you say!
since there's a new release out i feel like the case is closed here, right?
if you have some time, i'm sure nolan would be happy for a PR to pouchdb-authentication :)

**Comment by semiautomatix** [comment]
Thanks. 

I'm not 100% comfortable closing without knowing what the exact fix is - yes my fix for pouchdb-authentication works, but that doesn't appear to be the fix for pouchdb-find. So is it some other update or some other logic that is the definitive fix for all other plugins, especially for third parties? Once we can give that info the I feel we have a solution and case closed. 

I'll upload my pouchdb-authentication fork and let nolan know.

**Comment by semiautomatix** [comment]
Okay, decided I'm going to close. But will update if we get some new info on the best fix for the error.

**Comment by semiautomatix** [comment]
@karlwestin, the pouchdb-authentication changes are working correctly. I will need to ensure they don't adversely affect the plugin outside of the boilerplate before creating a PR.
