### ISSUE TITLE
Attachment added as blob but get returns a Base64

### ISSUE THREAD

**Issue by tshad** [pouchdb/pouchdb#6437]
I was trying to change my storage from Base64 to Blobs.  I have been having problems with safari that may have been due to size issues so I am trying to change the storage type.  But I am writing the image as a Blob but it is being returned as a Base64.

I write it out as:

`    DB_TaskImages.putAttachment(id, imageName, image, "image/jpeg").then(function () {`

image" is a blob.

When I try to get it back and do the following, it works fine.  But this is getting a Base64 string:

```
  return DB_TaskImages.get(id, {
      attachments: true
   }).then(function (doc) {
      return Promise.all(Object.keys(doc._attachments)
          .map(function (key) {
             return blobUtil.base64StringToBlob(doc._attachments[key].data)
             .then(blobUtil.createObjectURL)
             //return blobUtil.createObjectURL(doc._attachments[key].data)
             .then(function (myUrl) {
                console.log("Before resizeImageToImgPromise key: " + key);
                return resizeImageToImgPromise("80", "50", myUrl, key);
             });
          })
      );
   }).then(function (images) {
```
If I do this instead, it doesn't seem to work.  The only change I made was uncomment the part that deals with a blob and commented out the two lines that deal with base64 -> blob.

```
   return DB_TaskImages.get(id, {
      attachments: true
   }).then(function (doc) {
      return Promise.all(Object.keys(doc._attachments)
          .map(function (key) {
             //return blobUtil.base64StringToBlob(doc._attachments[key].data)
             //.then(blobUtil.createObjectURL)
             return blobUtil.createObjectURL(doc._attachments[key].data)
             .then(function (myUrl) {
                console.log("Before resizeImageToImgPromise key: " + key);
                return resizeImageToImgPromise("80", "50", myUrl, key);
             });
          })
      );
   }).then(function (images) {
```
The .get jumps to the catch and gets the following error:

`TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
`

That would make sense since it was returned as a base64 (or it looked that way and since the other code worked, I assume it was).

Thanks.

**Comment by mnewmedia** [comment]
getAttachment returns blob, but if you use get or allDocs with  {attachments: true} then it will ever be returned as base64.

I am almost afraid to say this, but this is the wrong place to ask questions.  This is to track issues about pouchdb. Questions are welcome at for example stackoverflow or slack.
