### ISSUE TITLE
Please update CouchDB logo

### ISSUE THREAD

**Issue by wohali** [pouchdb/pouchdb#6438]
### Issue
The main pouchdb website (and possibly documentation) uses the old CouchDB logo. Please update to use our new logo: http://couchdb.apache.org/image/couch@2x.png

### Reproduce
Browse to http://pouchdb.com/ and scroll down. :wink:

**Comment by nickcolley** [comment]
@wohali we use SVG for our logos, do you have that?

**Comment by wohali** [comment]
Yup! All the formats we have on hand are here: https://github.com/apache/couchdb-www/tree/asf-site/CouchDB-visual-identity/logo/ as CouchDB-couch-symbol.*
