### ISSUE TITLE
defaults() ineffective for setting {db: require('memdown')}

### ISSUE THREAD

**Issue by flimzy** [pouchdb/pouchdb#6441]
### Issue
Setting the 'db' parameter via `PouchDB.defaults()` appears to be ineffective.

### Info
- Environment: Node.js v6.10.2, PouchDB 6.2.0
- Adapter: memdown (attempted)

### Reproduce
To demonstrate the problem, run this code in Node.js:

    var fs = require('fs');
    var PouchDB = require('pouchdb');
    var memdown = require('memdown');
    var db = new PouchDB('foo', {db: memdown});
    if (fs.existsSync('foo')) {
        console.log("foo exists after explicit memdown instantiation");
    } else {
        console.log("foo does not exist after explicit memdown instantiation")
    }
    PouchDB.defaults({db: memdown});
    db = new PouchDB('foo');
    if (fs.existsSync('foo')) {
        console.log("foo exists after defaults memdown instantiation");
    } else {
        console.log("foo does not exist after defaults memdown instantiation")
    }

Output on my system:

    foo does not exist after explicit memdown instantiation
    foo exists after defaults memdown instantiation

Expected output:

    foo does not exist after explicit memdown instantiation
    foo does not exist after defaults memdown instantiation

**Comment by daleharvey** [comment]
As described in https://pouchdb.com/api.html#defaults, `.defaults` returns a new constructor, 
```
var MyMemPouch = PouchDB.defaults({
  db: memdown
});
```

**Comment by flimzy** [comment]
Thanks for pointing out my obvious oversight.
