### ISSUE TITLE
Travis is running tests twice

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#6445]
Looks like one run for the PR, one for the new branch

**Comment by daleharvey** [comment]
So one is for the branch, the other is the new commit on top of master (https://github.com/travis-ci/travis-ci/issues/3241)

I have turned off "build pull request updates" which seems to be the fix, will keep an eye on this though

**Comment by daleharvey** [comment]
@nolanlawson @willholley Someone seems to have changed this back, did it break anything / anyone know what happened here?

Back to building twice per PR

**Comment by willholley** [comment]
I found that Travis wasn't building updates to my PR (because branch builds are restricted to `master` and `greenkeeper` branches, so I did change this to get things moving. Is the preferred option to resubmit the PR?

**Comment by daleharvey** [comment]
Ah, yeh nah we should get it 'just working' as before, just not quite sure how yet, will look a bit more into it, maybe turn off pull request updates and remove the branch restrictions?

**Comment by daleharvey** [comment]
I have turned off "branch updates" lets see what that does after a few PR's feel free to turn it back on if it breaks something

**Comment by daleharvey** [comment]
ok seems to be fixed
