### ISSUE TITLE
Error adding an image to a record with no images

### ISSUE THREAD

**Issue by tshad** [pouchdb/pouchdb#6448]
I get the following error when I have deleted all my images from this record, but the record is still there with only an "_id" and a "_rev".  All the attachments are gone but this record is still there.

In the Chrome debugger, looking at my images database, for this id I see this:

{
  "_id": "6411580b-57b4-4585-b797-8cc0361ee6af",
  "_rev": "2-6dae118e48f25281a011882939a7a7f0"
}

But no "_attachments".

If I do a get on this id:

DB_TaskImages.get(id, { attachments: true }).then(function (doc)

it goes to the catch and there is no err.status but the err shows this:

message:Cannot convert undefined or null to object"
Stack: "TypeError: Cannot convert undefined or null to object↵    at Function.keys (<anonymous>)↵    at http://localhost:12531/Scripts/Tasks/tasksimage.js:87:39"

I also noticed in the debugger, the checkbox on the left of the record is checked.  What is that for?
Why does this happen and how do I handle this.

Thanks.

**Comment by tshad** [comment]
I found the issue.

It was my mistake. It turns out it was the next line that was giving the error.  This only happens when there are no attachments but it worked as it should.

Thanks,

**Comment by mnewmedia** [comment]
Then feel free to close the issue.. =)
