### ISSUE TITLE
Warning: db.type() is deprecated and will be removed

### ISSUE THREAD

**Issue by rehannawab** [pouchdb/pouchdb#6449]
### Issue
I understand that db.type() has been deprecated. Just wanted to confirm if this warning I am getting is because of reference in pouchdb or any adapters/plugins, and any steps I need to follow to be safe not to break code when db.type() is finally removed?

I am using pouchdb-adapter-cordova-sqlite (adapter: 'cordova-sqlite').

Thanks in advance.

**Comment by muelmx** [comment]
Same error here when using pouchdb-find

**Comment by garrensmith** [comment]
What version of pouchdb-find are you using?

**Comment by muelmx** [comment]
6.2.0

**Comment by rehannawab** [comment]
pouchdb 6.2.0
