### ISSUE TITLE
$gt: -Infinity not working since version 6.2.0

### ISSUE THREAD

**Issue by pubkey** [pouchdb/pouchdb#6454]
### Issue
After the update to version 6.2.0, selectors can no more contain the comparison of values to greater than minus Infinity.

### Info
- Environment: nodejs
- Adapter: memory

### Reproduce
Create a pouchdb-instance and make a pouch-find-query like this one:

```js
pouch.find({
  selector: {
    _id: {},
    'other.age': {
      '$gt': -Infinity   // <- this worked before version 6.2.0
    }
  },
  sort: [{
    'other.age': 'asc'
  }]
});
```

error: 
```bash
     TypeError: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at objectCollate (node_modules/pouchdb-collate/lib/index.js:293:19)
      at Object.collate (node_modules/pouchdb-collate/lib/index.js:46:50)
      at filterInclusiveStart (node_modules/pouchdb-find/lib/index.js:429:33)
      at node_modules/pouchdb-find/lib/index.js:1195:20
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

The `-Infinity` is important to use when sorting on a non-index number-field because it must always be in the selector or `Error: Cannot sort on field(s)  when using the default index` will throw.

**Comment by garrensmith** [comment]
@pubkey is it not possible to use null?
What does your index look like?
I think you could just create an index on `other.age` and do a selector like this:

```
pouch.find({
  selector: {
    _id: {},
    'other.age': {
      '$gt': null
    }
  },
  sort: [{
    'other.age': 'asc'
  }]
});
```
