### ISSUE TITLE
Map/reduce error behaviour changes in CouchDB master

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#6458]
### Issue
In CouchDB 1.x and PouchDB, if an invalid value was fed into a built-in reduce function in a view, any view requests would fail with a 500 error. This has been fixed in CouchDB master so that now view requests will return successful values where possible. For example, given the database:

```
{"id":"1","key":1,"value":1},
{"id":"2","key":2,"value":2},
{"id":"3","key":"baz","value":"baz"}
```

and a view:
```
"map": "function(doc){emit(doc.val, doc.val);}",
"reduce": "_sum"
```

A query to the view with `reduce=true` will now return:

```
HTTP/1.1 200 OK

{"rows":[
{"key":null,"value":{"error":"builtin_reduce_error","reason":"The _sum function requires that map values be numbers, arrays of numbers, or objects. Objects cannot be mixed with other data structures. Objects can be arbitrarily nested, provided that the values for all fields are themselves numbers, arrays of numbers, or objects.","caused_by":"baz"}}
]}
```

and with `reduce=true&group=true` it returns:

```
HTTP/1.1 200 OK

{"rows":[
{"key":1,"value":1},
{"key":2,"value":2},
{"key":"baz","value":{"error":"builtin_reduce_error","reason":"The _sum function requires that map values be numbers, arrays of numbers, or objects. Objects cannot be mixed with other data structures. Objects can be arbitrarily nested, provided that the values for all fields are themselves numbers, arrays of numbers, or objects.","caused_by":"baz"}}
]}
```

The PouchDB mapreduce module currently expects invalid reduces to result in a request/promise failure, and so the tests fail against CouchDB master.

It feels like PouchDB should either copy the CouchDB 2.x behaviour or add a shim to detect the error in the response and fail the function call on the client to maintain the current client behaviour. Given that mapreduce is less useful on the client now we have PouchDB-find, I'm leaning towards the latter as it's less work and does not create a breaking change.

**Comment by garrensmith** [comment]
I'm ok with either.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/e648d1fe9bea28ab8aaa740cebc4027ab9b21c34
