### ISSUE TITLE
connect to my couch database on Smileupps but get a http 405 error

### ISSUE THREAD

**Issue by Ihresearch** [pouchdb/pouchdb#6461]
### Issue
I am trying to connect to my database on Smileupps but get a http 405 error, CORS settings are all correct.

I might be doing completely wrong .... i am new to using pouchdb - howvere it works fine on localdatabase and also my local pc database if I setup http://locahost:port/database.

### Info
- Environment: (Javscript)
- Platform: (Chrome)
- Adapter: (http)
- Server: (Smileupps)

### Reproduce
  dbConvention = new PouchDB('https://couchdb-xxxxxx.smileupps.com/rcdatabase', {skip_setup: 'true'});

message in browser debugger Chrome.
XMLHttpRequest cannot load https://couchdb-xxxxxx.smileupps.com/rcdatabase/?_nonce=1493230782191. Response for preflight has invalid HTTP status code 405

**Comment by garrensmith** [comment]
I think you need to take this up with smileupps. This should work
