### ISSUE TITLE
allDocs not returning data

### ISSUE THREAD

**Issue by kplatter** [pouchdb/pouchdb#6465]
I am using pouchdb 6.2.0 in node 6.10.2, I have data loaded into a pouchdb/leveldb database, with keys like the following

_id: 'MSCD:mfe-file2_0_0_mo_pdu-fixed_complete_u_20170201.zip'

When I use:

pdb.allDocs({ startkey: 'MSCD:mfe-file', endkey: 'mfe-file\\uffff', include_docs: true })
or
pdb.allDocs({ startkey: 'MSCD:mfe-file2_', endkey: 'mfe-file2_\\uffff', include_docs: true })

I get the data I expect, 

When I use 

pdb.allDocs({ startkey: 'MSCD:mfe-file2', endkey: 'mfe-file2\\uffff', include_docs: true })

no data is returned.

**Comment by willholley** [comment]
@kplatter in your examples above, should the endkey values include a `MSCD` prefix?

**Comment by kplatter** [comment]
Yes, thanks.  I edited the string for example but did not include actual code.  The actual code is 

`pdb.allDocs({ startkey: program.key, endkey: program.key + '\\uffff', include_docs: true })`

and the variable program.key would be MSCD:mf3-file
