### ISSUE TITLE
Old Topic - DB.put() into _id:_security

### ISSUE THREAD

**Issue by dodomui87** [pouchdb/pouchdb#6468]
### Issue
Write the description of the issue here
Search through the previous issue regarding db.put _security document. Didn't find solution yet.
I need the features else we need manually setup new user database permission.

Appreciate if anyone could eliminate me the solution.

### Info
- Environment: (hybrid app - ionic)
- Platform: (Chrome/iOS/Android/)
- Adapter: (IndexedDB/WebSQL)
- Server: (Cloudant)

### Reproduce
Write the steps for others to reproduce issue here. Providing a code example, links to a repository or a live example (JSBin etc) are even more helpful.
As long as you db.put _security, it will prompt error code 400.
Only reserved document ids may start with underscore.

**Comment by willholley** [comment]
@dodomui87 PouchDB doesn't natively have support for multiple users like CouchDB. Are you attempting to change the security object on the local database or the remote Cloudant database?

**Comment by dodomui87** [comment]
@willholley Thanks for the info.
I would like to change the security object for remote cloudant database.

**Comment by willholley** [comment]
@dodomui87 I think that should work, using PouchDB as a client against CouchDB or Cloudant. Can you post a code example that fails?

**Comment by dodomui87** [comment]
error:true
message:"Only reserved document ids may start with underscore."
name:"bad_request"
status:400

**Comment by willholley** [comment]
@dodomui87 you'll need to make a regular ajax `PUT` to Cloudant database directly, or consider using [pouchdb-security-helper](https://www.npmjs.com/package/pouchdb-security-helper).

**Comment by willholley** [comment]
see #3529 for a broader discussion around this.
