### ISSUE TITLE
indexedDB.webkitGetDatabaseNames() is deprecated and will be removed in Chrome 60

### ISSUE THREAD

**Issue by leolivier** [pouchdb/pouchdb#6469]
### Issue
Running PouchDB 6.2.0 on Chrome 58 says:
eval.js:42 [Deprecation] indexedDB.webkitGetDatabaseNames() is deprecated and will be removed in M60, around August 2017. See https://www.chromestatus.com/features/5725741740195840 for more details.

**Comment by daleharvey** [comment]
Are you using the allDbs plugin? (possibly using the pouchdb inspector?) specifically because its not a standard we do not use that code inside pouchdb anywhere so its not coming from pouch core

**Comment by leolivier** [comment]
Hi daleharvey
Yes you're right, I'm using pouchdb inspector.
Hard to see this comes from there... but thanks I'll create the issue here.
