### ISSUE TITLE
Unit Testing in angular 2+

### ISSUE THREAD

**Issue by nerumo** [pouchdb/pouchdb#6471]
I'm using pouchdb in a angular 2+ stack. angular is relying on zone.js which monkey patches all async operations to keep the "context" between all the async calls. At every end of a zone, angular performs change detection.
With pouchdb I now get the problem that any pouchdb operation resolves the promise/callback in a different zone than the caller was (since its queue architecture). Example: the queue is created in zone 'A' and therefor the MutationObserver always resolves the callback within zone 'A'. If I now (on a button click handler or similar) have a pouchdb opertion in zone 'B', the resolve handler of that operation will be in zone 'A'.
This isn't a big deal in many angular applications since the application will perform global change detection (not optimal, but working). The bigger problem is within unit tests with the angular `async(..)` which is recommended for component rendering tests.

Do you have any idea how to avoid the loss of a zone? Would it be possible to extract the queue implementation to make it replaceable with something more zone.js friendly?

**Comment by daleharvey** [comment]
Honestly not sure how to fix this, but either way I think its angular / zone.js responsibility to monkey patch things in an compatible manner
