### ISSUE TITLE
db.type() is depreciated

### ISSUE THREAD

**Issue by tseck** [pouchdb/pouchdb#6477]
Hi there,

since upgrading and downgrading again (did not want react alpha version) I am getting this annoying warning
```
db.type() is depreciated and will be removed in future versions of PouchDB
```

Since I don't use this command directly I suppose it is somewhere in the source code of pouchdb's packages.

How can I get rid of this warning?

**Comment by daleharvey** [comment]
Closing as dupe https://github.com/pouchdb/pouchdb/issues/6449

**Comment by tseck** [comment]
ok thx

**Comment by LarryEitel** [comment]
I am running with:
```
    "pouchdb": "^6.3.4",
    "pouchdb-browser": "^6.3.4",
    "pouchdb-find": "^6.3.4",
```
Still getting:
```
db.type() is deprecated and will be removed in a future version of PouchDB
@index-browser.es.js?0e1b:486 
```

**Comment by tomshaw** [comment]
Currently running:

```
    "pouch-vue": "^0.3.4",
    "pouchdb": "^7.1.1",
    "pouchdb-authentication": "^1.1.3",
    "pouchdb-browser": "^7.1.1",
    "pouchdb-debug": "^7.1.1",
    "pouchdb-find": "^7.1.1",
    "pouchdb-live-find": "^0.4.0",
```

Relevant error message:

`db.type() is deprecated and will be removed in a future version of PouchDB`
