### ISSUE TITLE
Descending replication

### ISSUE THREAD

**Issue by jo** [pouchdb/pouchdb#6480]
I'd like to discuss an idea that came up during Offline Camp: descending replication.

Initial replication performance is still an issue, it's intrinsic to huge data sets.

When you initially replicate its often the new data that's the most interesting to the user. And that one arrives at latest. It would be good to be able to replicate in descending order. That way the user would see new data instantly, while the rest drops in later.
Also, the app could decide to stop replication at some point based on a memory limit. Sometimes you don't want to sync an entire dataset (for example for event based data).

Descending Replication would give us:

1. Relevant data first (improved UX)
2. Requests like "Give me 200MB of (latest) data"

Do you see any generic problems? Wouldn't this be an easy change?

**Comment by garrensmith** [comment]
This is an interesting idea @jo. Could you send an email to the CouchDB dev mailing list about this as well. It would be great to get some traction from the CouchDB side as well.

**Comment by daleharvey** [comment]
I dont think this would be very hard to support in our replicator and I do think things like this could be great improvements. I am slightly worried about the change in semantics of the couchdb cluster driven changes feed making this harder so I think its a good call to get it on the couchdb list fairly soon

**Comment by significance** [comment]
hey guys, i do have a use case for this at the moment, trying to manage data flow and need to get changed docs by most recent. seems couchdb have implemented this [in their changes feed](https://docs.couchdb.org/en/stable/api/database/changes.html) with the 'descending' query parameter. would this be a relatively easy thing to implement? if so perhaps we could give it a try? 😄

**Comment by significance** [comment]
@daleharvey @jo @garrensmith would any of you be able to help suggest a way forward?

**Comment by TylerHallPureEngineering** [comment]
Why is this considered closed? This inherently has so many use cases.

Want to make a chatroom? Sync the most recent messages now, and be able to keep scrolling back in time. I don't get it.
Seems like nearly most all use cases i have in my head using pouch db relates to a time series events that you can sync most important to leat important. You almost always are going to care about current events more than past events.

**Comment by jo** [comment]
Currently, [CouchDB does not support the `since` parameter of the `_changes` feed with `decending:true`](https://github.com/apache/couchdb/issues/2733). This would be a requirement for this feature.

What might work right now is to implement some kind of `get the last n changes` replication method, where `n` is basically `options.batch_size`. I don`t know how useful this would be though.

**Comment by Koulwa** [comment]
Yeah, that makes sense. I was reading up on the couch DB docs to see if there would be something to solve.
I had implemented a batch reverse time updater by getting all keys only, working backward in batches by syncing with those key batches. It works but, it was a little over-complicated. I slept on it and came up with my now used workaround.

It's important my keys are being sorted and synced by time newest first. So using epoch, I subtract from a future date so, counting down to a known date a few hundred years into the future. This allows me to use a timestamp that is easily translated back into the current time, its increments "down" instead of up and allows me to sync. 

Sync is happy, I'm happy, easily synced by most recent.

**Comment by anuragvohraec** [comment]
> Sync is happy, I'm happy, easily synced by most recent.
I tried the method suggested by you (FutureDate-currentTimeStamp). But the change feed though would sync upto a given date in reverse order, but it won't be neccessarily be recived in descending order. Do you have a mitigation for this ?
