### ISSUE TITLE
Remove non-node deps from dependencies

### ISSUE THREAD

**Issue by natew** [pouchdb/pouchdb#6481]
This is a simple request as it's causing a lot of pain in a Docker alpine image.

The dependencies for leveldown/leveldb are requiring a large amount of work for our CI, and require adding a lot of stuff to the image to be able to build it all.

Further, it may be that pouchdb-find has some weird stuff. I see the async package it uses has fb-esprima, and the tree gets pretty big.

Just a heads up as it's affecting us./

**Comment by daleharvey** [comment]
Do you only need the browser version of pouchdb? If so then https://www.npmjs.com/package/pouchdb-browser does not contain the level deps

(if thats not exactly what you need then https://pouchdb.com/2016/06/06/introducing-pouchdb-custom-builds.html may help)

Cheers
