### ISSUE TITLE
PouchDB is awesome, thank you so much to everyone working on it

### ISSUE THREAD

**Issue by estellecomment** [pouchdb/pouchdb#6488]
### Not-an-Issue
I use PouchDB and have not contributed, so I'm in debt here. Thank you to the people who contribute so that I can use it. It's a tremendously useful project. I know hard work went into it, good job. 

We're using it to bring health care to the last mile in the developing world. https://www.medicmobile.org/ Be proud of your work!!!

### Info
In reaction to https://nolanlawson.com/2017/03/05/what-it-feels-like-to-be-an-open-source-maintainer/

### Reproduce
Moaar awesome open source projects!

**Comment by garrensmith** [comment]
Thanks @estellecomment, that means a lot to us. We appreciate the feedback

**Comment by daleharvey** [comment]
Closing not an  issue, thanks so much :) and awesome job with Medic Mobile, it looks great
