### ISSUE TITLE
Wildly different allDocs() load times - from 54ms to 16000ms iOS / Cordova / SqlLite Plugin

### ISSUE THREAD

**Issue by brandoncorbin** [pouchdb/pouchdb#6492]
### Issue
Wildly different allDocs() load times - from 54ms to 16000ms

Each time my App launches, I query the documents created today... An example key:  epochTime|itemHash , for example:  12300030303|ddde442d0504dd3

Sometimes the results load in ~54ms, other times ~16000ms - and I cannot seem to find anyway to predictably reproduce it. 

This database contains 100,000 documents, all containing a few little data points. For the last month I've been trying every possible thing I can - and I'm now at a complete loss. 

Here's what I know:
- No problem on Android. 
- I've tried every version of Pouch 5.4.5 and the latest  
- I've tried every cordova-sqlite-plugin-2 1.1 
- I can manually write an allDocs() query in the console, and the results are still completely speratic (removing the potential of my own higher level class causing the issue)

Anyone have any suggestions on where to even begin at this point? 

### Info
- Environment: Hybrid App / Cordova
- Platform: iOS
- Adapter: WebSQL (cordova-sqllite-plugin-2
- Server: N/A

### Reproduce
Unable to reliably reproduce.

**Comment by brandoncorbin** [comment]
Narrowing it down... In an effort to work around this slowness, I've opted to replace allDocs() with going straight to the sqlite database. 

Querying 99,500 records
Direct to sqlite:  1821ms
Via Pouch allDocs():  13,034ms

Still not sure what would be causing the slow down

**Comment by willholley** [comment]
@brandoncorbin I'm not familiar with the profiling tools available in Cordova but, if you can run the app in Firefox or Chome, the [dev tools can help](https://developers.google.com/web/tools/chrome-devtools/rendering-tools/js-execution) narrow down the problem. If that's not an option the [PouchDB debug mode](https://pouchdb.com/api.html#debug_mode) might offer some insight as to where time is being spent.

**Comment by johnnybegood** [comment]
I have simular problems with our cordova app on iOS. It looks like the doc count query is taking a long time. Because the doc count query is not needed every call, the timing is different between calls. Anybody any thoughts on how to fix/bypass this?
