### ISSUE TITLE
Pouch stopped saving docs

### ISSUE THREAD

**Issue by xcarlo31** [pouchdb/pouchdb#6493]
### Issue
Cannot save new docs after 65Mb iOs app document & data

### Info
- Environment: (hybrid app(ionic 1)
- Platform: (iOs)
- Adapter: (WebSQL)
- Server: (no replication process yet.)

### Reproduce
I'm currently using pouchdb-3.4.0.min.js, and my app does a checklist and save every list on my pouchdb storage with WebSQL adapter, doesn't do any replication yet, but suddenly after the app documents and data reach roughly 50mb to 65mb, it stops saving docs.

And it throws storage qouta reached.

Anyone can give me advice? should i update to pouchdb-6.2.0? and use different adapter? currently im running test on pouchdb-6.2.0 and tried cordova-SQLite adapter..

**Comment by brandoncorbin** [comment]
I ran into the same exact problem about a year ago. Unfortunately Webkit only allows up to 50mb when using the websql adapter. If this is for Cordova, use https://github.com/nolanlawson/pouchdb-adapter-cordova-sqlite - this will remove the storage limit.

**Comment by xcarlo31** [comment]
Thank you @brandoncorbin! currently im testing the cordova-sqlite adapter. :)
