### ISSUE TITLE
Ionic2 prod build custom view error on iOS and Android

### ISSUE THREAD

**Issue by derksacklowski** [pouchdb/pouchdb#6496]
### Issue
I got an "The user's map/reduce function threw an uncaught error." followed by an understandable "Cannot read property 'doc' of undefined" while trying to access data using a custom view build with "--prod" flag on android. I guess the issue is caused by  angular2 ahead-of-time compilation.

### Info
- Environment: Ionic2, Cordova
- Platform: Android and iOS, both working without "--prod" flag
- Adapter: cordova-sqlite (cordova-sqlite-storage 2.0.4 tried without -> no difference)
- Server: custom OData 4.0 backend

### Reproduce
- Create an ionic2 project
- Include pouchdb
- Fill db with data 
- run ```ionic run android/ios --prod```
- Try to access data using a custom view

```
this.db
    .put({
        _id: '_design/index',
        views: {
            by_key_name: {
                map: function (doc: any): any { emit(doc.KeyName); }.toString(),
            },
        },
    });
```
```
public getByKeyName(key: string): Observable<any> {
    return Observable
        .fromPromise(this.db.query('index/by_key_name', {
            key: key,
            include_docs: true,
            attachments: true,
        }));
}
```
[issue1](https://ibb.co/gybUgQ)
[issue2](https://ibb.co/etOmT5)

**Comment by derksacklowski** [comment]
I updated the issue as it occurs also on iOS with --prod flag

**Comment by willholley** [comment]
@derksacklowski can you fetch the content of `_design/index` and post the JSON here?

**Comment by derksacklowski** [comment]
@willholley 
![views](https://cloud.githubusercontent.com/assets/13031051/26301555/d2f4c208-3ee1-11e7-923c-6692d24dd49b.png)
