### ISSUE TITLE
problem with $in in pouchdb-find

### ISSUE THREAD

**Issue by leolivier** [pouchdb/pouchdb#6498]
### Issue
I'm using $in in a pouchdb-find query like this:
```
    db.createIndex({
      index: { fields: ['notebookid'] }
    });
```
and later:
```
db.find({
        selector: {
          $and: [
            { notebookid: { $exists: true } },
            { notebookid:  { $in: notebookids } }
          ]
        },
      }).then(result => {
...
      });
```
When I execute the query, I get a warning telling me that it can't find an index and it uses _all_docs. But it works: I get the right documents
Looking at older issues, I  saw that I should maybe replace:
`{ notebookid: { $exists: true } }`
by
`{ notebookid: { $gt: null } }`
but then I get no warning on the index but the query fetches all documents ignoring the $in operator !!!

### Info
- PouchDB 6.2.0
- Environment: browser
- Platform: Chrome
- Adapter: none thus IndexedDB
- Server: CouchDB

### Reproduce
See steps above

**Comment by garrensmith** [comment]
This blogpost will explain what is happening https://www.bennadel.com/blog/3258-understanding-the-query-plan-explained-by-the-find-plugin-in-pouchdb-6-2-0.htm

But there could also be a bug here as well when you are using `{ notebookid: { $gt: null } }`

**Comment by leolivier** [comment]
Ok, I rolled back to $exists instead of $gt and I read the blog post above and saw that $in implies in memory search. 
As I have not much elements in my $in array, and as

> only equality-based operators can be run against an index

I tried to replace:
`{field: {$in: [a, b]}}`
by 
{`$or: [{field: a}, {field: b }]}`
but, there also, _all_docs is used... 
I surrender...  :'(

**Comment by nerumo** [comment]
It's actually the same underlying issue as [6371](https://github.com/pouchdb/pouchdb/issues/6371). But as well, no solution in sight
