### ISSUE TITLE
IndexedDB in iOS 10.3

### ISSUE THREAD

**Issue by tom501** [pouchdb/pouchdb#6501]
### Issue
Hi everybody, 
I have a question about the latest version of Pouchdb: the policy for iOS 10.3.1 is still the same that I just read in the documentation (https://pouchdb.com/adapters.html) or now it changed?

> Safari 7.1+ and iOS 8+ supposedly support IndexedDB, but their implementation has many bugs, so PouchDB currently ignores it.

### Info
- Environment: cordova app
- Platform: iOS 10.3.1

Thank you.

**Comment by iNViTiON** [comment]
This also my issue too. I develop Angular 4 web app that need IndexedDB but PouchDB still ignore pouchdb-adapter-idb on iOS 10.3 that IndexedDB now can completely work both on Safari and Pinned to Home Screen app.

**Comment by tom501** [comment]
Thank you so much @iNViTiON for the answer!

@nolanlawson it will be un update of Pouch with this implementation or for some reason (maybe bugs mentioned in docs) IndexedDB will not be supported in future releases?

Thanks in advance
