### ISSUE TITLE
PouchDB is awesome!!!

### ISSUE THREAD

**Issue by gyetvan-andras** [pouchdb/pouchdb#6503]
I can't express enough how delightful is to work with PouchDB. It is a piece of the most perfect software I used so far! This is the heart of my offline first app. 

But there is an issue, which is not a bug, but I would like to elaborate on sync timing. As I understand PouchDB is polling remote peers for changes on a timely  manner with some logic behind it. For example it seems to me, if there is no change then the interval will be increased. If any change occurred, then the polling interval decreased. In my app it leads to a few minutes delay. 

After this long prelude, my question is that how can I force sync?  For example, when the app becomes online, I would like to force a sync.

(I am using (P/C)ouch DB in a client/server like setup, where clients (mobile app) syncs a subset of the whole DB)

**Comment by willholley** [comment]
@gyetvan-andras how are you calling `sync` today? If you make an explicit call to `db.replicate` or `db.sync` it should initiate sync immediately. If you are using `{live: true, continuous: true}` then Pouch will be long-polling the `_changes` endpoint on CouchDB, waiting for a change. If no changes occur after a timeout, Pouch re-initiates the connection.

**Comment by gyetvan-andras** [comment]
Yes, when my app starts it will call sync with ```{live: true, retry: true}``` (I don't know ```continues``` option) and at that moment everything is synced ( I have an option to start/stop sync, but it is user driven). However when a I leave it as is, the sync timeout increasing. Everything is working fine, but the delay is too high. This is why I am looking for a solution to force.

**Comment by gyetvan-andras** [comment]
To make it more clear: for example, my app has a Scheduling module, where the user is able to create a new appointment. OK. The appointment is created and saved to the local DB. This change is propagated to the server. Everything is fine. Server has the good data. 
I have another client, which is looking for a change, with a polling delay. As I experienced, the polling delay is increasing based on a ```"not known" algorithm```, caused that the update can arrive minutes later. What I want is to override the ```"not known" algorithm``` and force the update checking by, for example , every 10 secs.

**Comment by gyetvan-andras** [comment]
Okay! It seems that I cannot describe well my problem, so I try to do it by example.
Please forget offline, timeout and other network realted problems. All my clients and servers are online.

Here is my setup:
1. server: it is a (P/C)ouch DB. For development, it is a PouchDB inside a NodeJS app.
2. clients: React Native clients on Android, iPhone, iPad and emulator. They share the same subset of the server DB (clients, for example) using PouchDB. Replication is enabled.

All clients are online, connected to the server DB.

The problem:
1. client A makes some change, and publish it to its local Pouch DB. Local DB is propageting the change to the server. FINE.
2. client B and C receive the change. FINE.
3. client A, B and C are sit in silence, nobody makes any change for example for 10 minutes.
4. then let say client A make some change, save it to local DB, which propagate its changes to the server DB. FINE.
5. client B and C will receive change notification after several (sometimes it is 5) minutes.WRONG!!!!

All the clients are online. When I restart sync on client B and C, all the changes will arrive.

Based on my experience, there is some logic behind polling (clients) for change.  This is what I would like to overwite.

**Comment by willholley** [comment]
@gyetvan-andras thanks for the detail. As mentioned above, I don't know of any code in PouchDB that would result in the backoff you describe - it polls continuously, waiting for the server to return a change to the client. Essentially, even if there are no changes, you should see all clients A B and C making requests to `_changes`, timing out after a period (usually 30 seconds), and then re-initiating the request.

If you are seeing long gaps between the requests to `_changes` then something odd is going on - turning on the PouchDB [debug mode ](https://pouchdb.com/api.html#debug_mode) may shed some light on what's going on.

If you can provide a debug log and/or network trace for the client experiencing the delay, I can try and help debug the problem.

**Comment by willholley** [comment]
this sounds like the same issue as #6510

**Comment by gyetvan-andras** [comment]
Yes, absolutely. Will check the custom backoff function workaround. Thank you!!!

**Comment by gyetvan-andras** [comment]
@willholley the custom backoff completely solved my problem. Thank you!

**Comment by gyetvan-andras** [comment]
I cannot resist :) I was so afraid that I must use other than PouchDB as a solution for my app backend service due to the above problem. Now it works like a dream: I have a handful of devices, I make a change  on one of them and it just synced to everywhere. Of course some of them are offline, no problemo, when became online, the change is here :D

**Comment by willholley** [comment]
thanks @gyetvan-andras - glad the workaround resolved your issue!
