### ISSUE TITLE
The _changes feed being timed out due to lack of data causes the backoff function to be called

### ISSUE THREAD

**Issue by mjosephd** [pouchdb/pouchdb#6510]
### Issue
The issue is that the "_changes" feed being timed out due to lack of any new changes in the longpoll request the backoff function is getting called. As far as I know I only believed that hte backoff function gets called when an error happens to the "_changes" feed call. However timeout seems to also call the backoff function. Additionally a custom backoff function was used for testing and it was also called when the "_changes" call was timed out then as well.

The use case that this affects is the following
If a user leaves a device on for a couple of hours and for each "_changes" call there are no new changes the backoff function will get repeatedly called. And after some hours the when there is an actual change the user will need to wait upto 10 mins (I believe the defualt backoff function has a max limit of 10 minutes) to get the change, whereas the change should come instantly as soon as possible when it is available.

### Info
- Environment: Browser, but we are developing for a hybrid application
- Platform: Chrome for testing this issue, but again since hybrid will use the Chrome/Safari browser webview
- Adapter: default so far, Indexeddb
- Server: Couchdb for testing if the issue exists (however we noticed it on couchbase sync gateway originally which is what the app we are developing is using).

### Reproduce
1) Checkout todo sample app
2) Change CDN version to 6.2.0
3) Test change feed calling backoff function

![testing](https://cloud.githubusercontent.com/assets/422345/26193392/d668100a-3bd2-11e7-81f7-17edd96a4f6f.gif)

**Comment by mjosephd** [comment]
@willholley just to clarify, this means I should consider that this functionality as an issue correct?
And the immediate remedy would be to put a custom backoff function?

**Comment by mjosephd** [comment]
@willholley the current backoff function uses a random value. I remember reading somewhere it was said it was to avoid two requests being sent at the same time or something like that (couldn't find source). Would there be any implications of using a custom backoff function which returned 10 seconds as a hardcoded value (without any randomness selection logic and such)?

**Comment by willholley** [comment]
@mjosephd only that PouchDB would continue to retry in the case of errors - I think that's an acceptable workaround. I'll try and look at why this is happening in this week.

**Comment by mjosephd** [comment]
Also I forgot to test offline scenarios, what is the expected outcome of pouchdb being unable to do the "_changes" call, is it to call the backoff function or treat it as normal and not call the backoff function then.

**Comment by willholley** [comment]
@mjosephd I believe it would call the backoff function if `retry: true` is specified.

**Comment by willholley** [comment]
@daleharvey can you confirm the expected behaviour here?

**Comment by willholley** [comment]
so what's happening is that when `timeout` is specified in the `changes()` call, this is implemented as a client side timeout in Pouch, and therefore an error (which triggers the backoff). I suppose the question is whether a _changes timeout is a special case which shouldnt' be classed as an error, or whether the heartbeart should be keeping the connection alive.

**Comment by daleharvey** [comment]
So a timeout that we specifically trigger, as you said yup should not be treated as an error and trigger backoff, thats a bug, however given that hearbeat makes timeouts very rare and xhr supports timeouts itself, maybe we should remove the manual timeout code completely?

heartbeat should be keeping the connection open long enough for timeout to never apply. It may be that couchbase doesnt implement heartbeat? if so not much wrong

**Comment by willholley** [comment]
@daleharvey I can reproduce this against couchdb, so I think we're at fault. We obviously want to catch genuine cases where the server is unreachable / not responding - perhaps a client side timeout that's always longer than the heartbeat / timeout would work?

**Comment by willholley** [comment]
aha - found the bug, I think...
