### ISSUE TITLE
Missing checking if the callback is valid in the bulkDocs.

### ISSUE THREAD

**Issue by PrzemekGonera** [pouchdb/pouchdb#6511]
I noticed that based on your example from the page https://pouchdb.com/api.html#example-plugin-intercept-updates where we can decorate the bulkDocs causes the issue when I try call the `bulkDocs` function without providing the callback (optional parameter as you know).

### Info
- Platform:
  - Chrome v.58.0.3029.110
  - Safari v. 10.1.1 (12603.2.4)

### Reproduce
Please take a look on my example - http://plnkr.co/edit/sE16EJ3LLHVy7RWZniYu?p=preview.
You should get the error on the console (attached below the screenshot of this) if you call `db.bulkDocs([newItem]);`
Although that issue can be fixed by providing the empty function - 
`db.bulkDocs([newItem], function () {});`
but it's workaround so I suggest to add into `bulkDocs` checking before calling the callback if it's valid.

![screen shot 2017-05-18 at 14 12 02](https://cloud.githubusercontent.com/assets/9800507/26201602/16c4e85c-3bd4-11e7-826d-8895f539a537.png)

**Comment by daleharvey** [comment]
You are specifically overriding the bulkDocs function and calling callback without a check, the error is coming from your own code? `bulkDocs` without a callback works fine in pouchdb (its tested @ https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.basics.js#L429)
