### ISSUE TITLE
Cannot use pouchdb-replication with React SSR

### ISSUE THREAD

**Issue by albinekb** [pouchdb/pouchdb#6512]
### Issue
Currently when using with https://github.com/zeit/next.js/ (server rendered react) 

I get this error:
```sh
TypeError: Cannot redefine property: replicate
    at Function.defineProperty (<anonymous>)
    at replication (../node_modules/pouchdb-replication/lib/index.js:979:10)
```

I've made a fix in this PR: #6508

### Info
- Environment: Node.js & Browser
- Platform: Chrome/V8
- Adapter: WebSQL
- Server: PouchDB Server

### Reproduce
use https://github.com/zeit/next.js/
with https://pouchdb.com/guides/replication.html

**Comment by daleharvey** [comment]
bug with react ssr

**Comment by albinekb** [comment]
Can you elaborate @daleharvey  🤔 How is this a bug with React SSR?

**Comment by daleharvey** [comment]
Because in node.js nor any browser environment we see any error with redefining replicate, this has been the sole report so assuming its down to whatever different in the next / react ssr envionment

**Comment by tmende** [comment]
I see the same error message in node (8.9) - the issue can be reproduced with 

```const PouchDb = require("pouchdb-core")
const pouchdbReplication = require("pouchdb-replication")
PouchDb.plugin(pouchdbReplication)
PouchDb.plugin(pouchdbReplication)```

This happened for us due to multiple files with independent dependencies to PouchDB that were imported in the same project. 

@daleharvey I assume this is on purpose or should I open another/reopen this bug for this?

**Comment by daleharvey** [comment]
Nope not on purpose, it seems like if there is something we can do to avoid it being repeated we should probably do that, but otherwise I dont mind this being writeable: true or whatever the appropriate fix for it it
