### ISSUE TITLE
Webpack Error ! (Electron-Angular4)

### ISSUE THREAD

**Issue by ozgursel** [pouchdb/pouchdb#6515]
### Issue
 
Hello, I am getting this errors from webpack console,

```
WARNING in ./~/bindings/bindings.js
76:22-40 Critical dependency: the request of a dependency is an expression

WARNING in ./~/bindings/bindings.js
76:43-53 Critical dependency: the request of a dependency is an expression

WARNING in ./~/har-validator/~/ajv/lib/compile/index.js
13:21-34 Critical dependency: the request of a dependency is an expression

WARNING in ./~/har-validator/~/ajv/lib/async.js
96:20-33 Critical dependency: the request of a dependency is an expression

WARNING in ./~/har-validator/~/ajv/lib/async.js
119:15-28 Critical dependency: the request of a dependency is an expression

```
and i tried to add this line to my webpack.config.js then webpack gives no error

```
  "module": {
    "noParse": /lie\.js$|\/leveldown|ajv\//,
 }
```
but my application console giving error like this

```
Uncaught Error: Cannot find module './compile'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/hayvan/Masaüstü/QDesktop/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

```
### Info
- Environment: (Angular4/Electron/)
- Platform: (Windows,Ubuntu)
- Adapter: (IndexedDB/WebSQL)
- Server: (CouchDB)

**Comment by Hayvanimal** [comment]
Whatever i solved this problem with diffrent way

in my webpack.config.json i added pouchdb as external library.

```
module.exports = {
  "externals": {
    "pouchdb": 'require(\'pouchdb\')'
  },
```
and delete this stupit line below (my mistake)
  
```
"module": {
    "noParse": /lie\.js$|\/leveldown|ajv\//,
 }
```
and i used `pouchdb-browser` instead of `pouchdb` like this and it works.

`import * as PouchDB   from 'pouchdb-browser';`

but i think it caused by leveldb and nodejs versions.
With `pouchdb` its still gives error in dev-console

**Comment by avickers** [comment]
Have you taken a look at [this repo](https://github.com/nolanlawson/pouchdb-electron) for info about using pouchdb with LevelDB in Electron?

**Comment by daleharvey** [comment]
Yup not tracking electron / angular bugs here
