### ISSUE TITLE
Selector property not found in PouchDB.Core.ChangesOptions

### ISSUE THREAD

**Issue by hadrien-toma** [pouchdb/pouchdb#6516]
## Description
Hi there, in the [_changes_ section](https://pouchdb.com/api.html#changes) of the PouchDB website, it seems that a `selector` option is available in the filtering options of the method `PouchDB.Database<any>.changes(options?: PouchDB.Core.ChangesOptions)`. In the latest definition types (cf. Versions details) I can see other options (`filter`, `doc_ids`, `query_params` and `view`) but not the `selector` one, maybe you have an idea why?

## Versions details
* `@types/pouchdb`: `6.1.0`
* `@types/pouchdb-find`: `0.10.0`
* `pouchdb`: `6.2.0`
* `pouchdb-changes-filter`: `6.2.0` (I don't know if I need this one or if it is already packaged with `pouchdb`?)

**Comment by willholley** [comment]
@hadrien-toma I don't think those definitions are part of the core project - perhaps file an issue/PR at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/pouchdb?

**Comment by hadrien-toma** [comment]
Okay, so do you confirm that this option really exists? I only pointed out an inconsistency but I didn't test anything. Nevertheless, If this option effectively exists, I will propose a PR in DefinitelyTyped repository with pleasure ;).

**Comment by willholley** [comment]
It exists in PouchDB 6.2 - see the api docs for reference
