### ISSUE TITLE
Slow createIndex when index already exists

### ISSUE THREAD

**Issue by natew** [pouchdb/pouchdb#6518]
### Issue
I noticed that creating indexes was running slowly. I added console.time and saw 50-80ms per database I was adding, even when it was already created!

I "fixed it" by just checking myself using getIndexes like this:

```js
      const { indexes } = await this.collection.pouch.getIndexes()
      const alreadyIndexedFields = flatten(indexes.map(i => i.def.fields)).map(
        field => Object.keys(field)[0]
      )
      // if we have not indexed every field
      if (
        intersection(this.settings.index, alreadyIndexedFields).length !==
        this.settings.index.length
      ) {
        await this.collection.pouch.createIndex({ fields: this.settings.index })
      }
```

After this change it went from 50 => 2-3ms 🎉 

### Info
- Environment: Chrome 58
- Adapter: IndexedDB

**Comment by natew** [comment]
@willholley looks like you may have added some testing... probably worth keeping open.

**Comment by daleharvey** [comment]
Code landed so closing out, cheer
