### ISSUE TITLE
Ionic app with PouchDB throws SQLError on iOS

### ISSUE THREAD

**Issue by altgov3en** [pouchdb/pouchdb#6522]
Hi , I've developed an Ionic application (using angular-pouchdb wrapper) which is supposed to run on iOS iPads. The application syncs with 4 Couch DBs  as following:

`self.databases[options.dbName] = pouchDB(options.dbName); `

then I'm syncing them with CouchDB as following:

`self.databases[options.dbName].sync(remoteServerDB, options).on(...).on()...`
At first, the options object contains the following attributes:

`{retry: true,live: false,batch_size: 100}`

I'm initializing PouchDB with attribute `live: false` because otherwise I'm not getting to:

`.on('complete', function(){...})` 

which indicates for me that the PouchDB has synced with CouchDB. When `live: true` the application never invokes the `.on('complete', function(){...})` function.

Because two of the DBs has about 40K documents I intend to show to user an loading screen which will be hidden when the replication process will invoke the  `.on('complete', function(){...})` event. As I sad, the event invoked only when the attr. `live `is `false`.

After replication invokes the `.on('complete', function(){...})` I'm closing the completely synced pouch db and reopening it with `{retry: true,live: true,batch_size: 10}`. And from now on the db is syncing flawlessly in Chrome but not in iOS.

When I'm deploying the app on iPad, the application begins to work fine (connecting, syncing, etc.) but at some point the following error appears in Xcode console: 

> ERROR: WebSQL threw an error [object SQLError]

I don't know what else details to support. It is a complicated application, and it includes a lot of moving parts and I don't think this is good idea to flood the question with irrelevant information.

Here is the log of the app. working on iOS:

<details><summary>Stack trace here</summary>
> 14:57:23.322575  Syncing all DBs...
> 14:57:23.322828  Fetching 'util' file...
> 14:57:23.322950  State changed: 1 > 3
> 14:57:23.884397  'util' file fetched succeessfully
> 14:57:23.884574  Checking if first time run...
> 14:57:23.884689  Fetching 'exclusiveFile' file...
> 14:57:25.543333  Failed to fetch 'exclusiveFile'. Probably first time run. Closing 'exclusiveDb'...
> 14:57:25.543534  'exclusiveDb' closed successfully. Rejecting the function...
> 14:57:25.632296  App running first time or not all DBs were synced
> 14:57:25.632638  Initializing PouchdDBs with following  options: {"retry":true,"live":false,"batch_size":100}
> 14:57:26.830620  State changed: 1 > 4
> 14:57:27.031021  t-myorders :[onActive]: Syncing...
> 14:57:27.125219  t-myorders :[onActive]: Syncing...
> 14:57:27.125648  'initPouchDb' resolved with DB: t-myorders
> 14:57:27.211877  t-orders :[onActive]: Syncing...
> 14:57:27.212070  t-gendata :[onActive]: Syncing...
> 14:57:27.239245  t-orders :[onActive]: Syncing...
> 14:57:27.239532  'initPouchDb' resolved with DB: t-orders
> 14:57:27.239681  t-gendata :[onActive]: Syncing...
> 14:57:27.239820  'initPouchDb' resolved with DB: t-gendata
> 14:57:28.093380  Pulling t-orders data (100)
> 14:57:28.411297  Pulling t-gendata (100)
> 14:57:28.529898  Pulling t-myorders data (100)
> 14:57:29.880190  Pulling t-orders data (200)
> 14:57:30.032869  Pulling t-gendata (200)
> 14:57:30.131282  Pulling t-myorders data (155)
> 14:57:30.574666  t-myorders :[onPaused]: Syncing paused
> 14:57:30.574874  t-myorders :[onComplete]: first time sync. completed
> 14:57:30.575010  Updating 'exclusiveDb' file when 't-myorders' completed syncing
> 14:57:30.619125  'exclusiveFile' not found. File will be created and updated with 't-myorders'
> 14:57:30.635064  'exclusiveFile' successfully updated with 't-myorders'. Closing 'exclusiveDb'...
> 14:57:30.635315  'exclusiveDb'closed. Resolving the call...
> 14:57:30.665316  Closing 't-myorders' DB...
> 14:57:30.665514  Reopening 't-myorders' with: {"dbName":"t-myorders","retry":true,"live":true,"batch_size":10}
> 14:57:31.189256  t-myorders :[onActive]: Syncing...
> 14:57:31.189431  t-myorders :[onActive]: Syncing...
> 14:57:31.189548  'initPouchDb' resolved with DB: t-myorders
> 14:57:31.189660  Indexing 't-myorders'...
> 14:57:31.237343  Indexing 't-myorders': 100% completed
> 14:57:31.800247  Pulling t-orders data (300)
> 14:57:31.946003  Pulling t-gendata (300)
> 14:57:33.405985  Pulling t-orders data (400)
> 14:57:33.553263  Pulling t-gendata (400)
> 14:57:34.939881  Pulling t-orders data (500)
> 14:57:35.321584  Pulling t-gendata (500)
> 14:57:36.382365  Pulling t-orders data (600)
> 14:57:36.760144  Pulling t-gendata (600)
> 14:57:37.670150  Pulling t-orders data (700)
> 14:57:38.360886  Pulling t-gendata (700)
> 14:57:39.290220  Pulling t-orders data (800)
> 14:57:39.626805  Pulling t-gendata (800)
> 14:57:40.609893  Pulling t-orders data (900)
> 14:57:41.289835  Pulling t-gendata (900)
> 14:57:41.347719  t-myorders :[onPaused]: Syncing paused
> 14:57:42.197296  Pulling t-orders data (1000)
> 14:57:45.348932  State changed: 1 > 3
> 14:57:45.793766  Pulling t-gendata (1000)
> 14:57:46.526594  Pulling t-orders data (1100)
> 14:57:47.323562  Pulling t-gendata (1100)
> 14:57:47.987649  Pulling t-orders data (1200)
> .
> .
> .
> 15:07:42.869070  Pulling t-orders data (35400)
> 15:07:44.296239  Pulling t-gendata (34700)
> 15:07:45.087058  Pulling t-orders data (35500)
> 15:07:45.793439  Pulling t-gendata (34737)
> 15:07:46.433589  t-gendata :[onPaused]: Syncing paused
> 15:07:46.433770  t-gendata :[onComplete]: first time sync. completed
> 15:07:46.433895  Updating 'exclusiveDb' file when 't-gendata' completed syncing
> 15:07:46.458336  'exclusiveDb' file found and fetched successfullly
> 15:07:46.458497  t-gendatafirst time completing syncing. 'exclusiveFile' will be updated.
> 15:07:46.766508  'exclusiveFile' successfully updated with 't-gendata'. Closing 'exclusiveDb'...
> 15:07:46.766689  'exclusiveDb'closed. Resolving the call...
> 15:07:46.789873  Closing 't-gendata' DB...
> 15:07:46.790088  Reopening 't-gendata' with: {"dbName":"t-gendata","retry":true,"live":true,"batch_size":10}
> 15:07:47.673565  Pulling t-orders data (35600)
> 15:07:47.721658  t-gendata :[onActive]: Syncing...
> 15:07:47.729935  t-gendata :[onActive]: Syncing...
> 15:07:47.730119  'initPouchDb' resolved with DB: t-gendata
> 15:07:47.730244  Indexing 't-gendata'...
> 15:07:56.785542  Indexing 't-gendata': 100% completed
> 15:07:58.297407  Pulling t-orders data (35700)
> 15:07:59.818477  Pulling t-orders data (35800)
> 15:08:01.391289  Pulling t-orders data (35900)
> 15:08:02.814749  Pulling t-orders data (36000)
> 15:08:04.711306  Pulling t-orders data (36100)
> 15:08:06.131567  Pulling t-orders data (36200).
> .
> .
> .
> 15:09:16.389573  Pulling t-orders data (40500)
> 15:09:18.080333  Pulling t-orders data (40600)
> 15:09:19.688108  Pulling t-orders data (40700)
> 15:09:21.674377  Pulling t-orders data (40800)
> 15:09:23.255323  Pulling t-orders data (40900)
> 15:09:25.015147  Pulling t-orders data (41000)
> 15:09:26.793778  ERROR: WebSQL threw an error [object SQLError]
> 15:09:26.820956  t-orders :[onPaused]: Syncing paused
> 15:09:28.062170  t-orders :[onActive]: Syncing...
> 15:09:28.859576  ERROR: WebSQL threw an error [object SQLError]
> 15:09:28.866137  t-orders :[onPaused]: Syncing paused
> 15:09:29.064463  t-orders :[onActive]: Syncing...
> 15:09:31.052181  ERROR: WebSQL threw an error [object SQLError]
> 15:09:31.057107  t-orders :[onPaused]: Syncing paused
> 15:09:31.296406  t-orders :[onActive]: Syncing...
> 15:09:33.842619  ERROR: WebSQL threw an error [object SQLError]
> 15:09:33.848113  t-orders :[onPaused]: Syncing paused
> 15:09:33.909316  t-orders :[onActive]: Syncing...
> 15:09:37.577624  ERROR: WebSQL threw an error [object SQLError]
> 15:09:37.583570  t-orders :[onPaused]: Syncing paused
> 15:09:37.673989  t-orders :[onActive]: Syncing...
> 15:09:40.339962  ERROR: WebSQL threw an error [object SQLError]
> 15:09:40.348071  t-orders :[onPaused]: Syncing paused
> 15:09:40.426914  t-orders :[onActive]: Syncing...
> 15:09:43.134165  ERROR: WebSQL threw an error [object SQLError]
> 15:09:43.139505  t-orders :[onPaused]: Syncing paused
> 15:09:43.226513  t-orders :[onActive]: Syncing...
> .
> .
> .
> 15:25:38.421471  ERROR: WebSQL threw an error [object SQLError]
> 15:25:38.428253  t-orders :[onPaused]: Syncing paused
> 15:25:38.449027  t-orders :[onActive]: Syncing...
> 15:25:41.110190  ERROR: WebSQL threw an error [object SQLError]
> 15:25:41.116702  t-orders :[onPaused]: Syncing paused
> 15:25:41.244346  t-orders :[onActive]: Syncing...
> 15:25:43.245937  ERROR: WebSQL threw an error [object SQLError]
> 15:25:43.250190  t-orders :[onPaused]: Syncing paused
> 15:25:43.285293  t-orders :[onActive]: Syncing...
> 15:25:46.152822  ERROR: WebSQL threw an error [object SQLError]
> 15:25:46.164527  t-orders :[onPaused]: Syncing paused
> 15:25:46.256982  t-orders :[onActive]: Syncing...
> 

</details>

**Comment by nolanlawson** [comment]
By any chance are you able to find the SQL error itself? Otherwise it's hard to debug.

Safari uses WebSQL and Chrome uses IDB so it's quite possible they have different behavior. My guess is that your app is exceeding the max size limit: https://pouchdb.com/errors.html#not_enough_space

**Comment by daleharvey** [comment]
Closing out bugs in unsupported env (ionic)
