### ISSUE TITLE
PouchDb refused to be install because leveldown is still required even though the --no-optional was used

### ISSUE THREAD

**Issue by toyssamurai** [pouchdb/pouchdb#6526]
### Issue
I was trying to install PouchDb and encountered an error with levelDown. After doing some researches, I found that levelDown was changed to be an optional dependency from this page: https://pouchdb.com/errors.html . So, I re-tried npm install with --no-optional , but to my surprise, I got exactly the same error. Does levelDown become mandatory dependent again? As far as I can tell, it is still a dependency according to the package.json file.

### Info
- Environment: Node
- Platform: Linux
- Adapter: Not applicable
- Server: not applicable

### Reproduce
Doing npm install with --no-optional from a system that wouldn't build levelDown properly should reproduce this problem

**Comment by nolanlawson** [comment]
We don't use optional dependencies anymore. If you don't want leveldown, you can install `pouchdb-browser` or `pouchdb-core` and include the modules you want: https://pouchdb.com/custom.html
