### ISSUE TITLE
"Uncaught ReferenceError: PouchDB is not defined" after trying pouchdb in my Google Chrome Extension

### ISSUE THREAD

**Issue by mojorero** [pouchdb/pouchdb#6530]
### Error while using PouchDB in a Google Chrome extension

I receive "Uncaught ReferenceError: PouchDB is not defined" after trying to load PouchDB in my Google Chrome extension.

### Info
- Environment: Google Chrome
- Platform: Chrome
- Adapter: 
- Server:

### Reproduce
Add following line to manifest.json: "scripts/pouchdb.min.js",
Copy pouchdb.min.js into scripts directory.
Add following permission: "storage"
In the extension code, add this line: var db = new PouchDB('testdb');

After trying to execute my extension, ir gives the following, already mentioned error: "Uncaught ReferenceError: PouchDB is not defined".

**Comment by nolanlawson** [comment]
If PouchDB is not defined then the library has not loaded, which doesn't sound like a PouchDB bug. I don't know Chrome extensions but I don't believe manifest.json is where you place dependencies. Maybe try this question on StackOverflow instead?

**Comment by mojorero** [comment]
Thank you for your fast answer. In case it can help somebody else, I found out that the problem really was: the declaration order of the scripts in the exntesion manifest. The PouchDB library was being loaded after the extension JS was.
