### ISSUE TITLE
master failing tests against node-websql

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#6534]
### Issue
It looks as though the master branch is [failing consistently](https://travis-ci.org/pouchdb/pouchdb/jobs/236955777) against WebSQL. The most likely culprit appears to be https://github.com/pouchdb/pouchdb/pull/5981 but it needs investigation.

### Info
- Environment: Node
- Platform: 
- Adapter: WebSQL
- Server: CouchDB

**Comment by nolanlawson** [comment]
So only node-websql? Or WebSQL in the browser too?

**Comment by willholley** [comment]
Seems to be only node websql..

**Comment by daleharvey** [comment]
Yup definitely #5981 and seems intermittent

**Comment by daleharvey** [comment]
Given its not a core use case (node-websql mostly helps us test the websql code easier) I will move this to allowed failures so we can carry on development while taking a look at fixing this

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/4eb3290d5b3c4e5cbf5c182f043923abfeaf8284
