### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by avickers** [pouchdb/pouchdb#6546]
### Issue
It's probably time to update the Adapters page to more accurately reflect major browser support (and existence).  I'd submit a pull request, but I don't see a repo for the website.

### Info
RE: 
> As of 2015, the browser support looks like this:

Even staid Safari has now joined the IndexDB train, and @nolanlawson held [a wake](https://nolanlawson.com/2014/04/26/web-sql-database-in-memoriam/) for WebSQL 3 years ago.  Also, I can't quite think of the name of it, but there's rumor of this new bleeding Edge browser from Microsoft.  Rumor has it one of the maintainers here even works on that team, and yet... :)

PS: And maybe mention worker-pouch explicitly, since Google and Microsoft seem pretty serious about promoting PWAs.

**Comment by willholley** [comment]
@avickers a PR would be fantastic. The website / documentation is a subdirectory of the main PouchDB repo - https://github.com/pouchdb/pouchdb/tree/master/docs.
