### ISSUE TITLE
Changes query not working when using a selector

### ISSUE THREAD

**Issue by Sebi55** [pouchdb/pouchdb#6548]
### Issue
I am trying to use the pouchdb-find selector in a "changes" query. According to the documentation I should be able to use changes and then just a selector to "filter" the results. When the selector exists no query is sent at all without any error in the console.

### Info
I am running couchdb 2.0 on Ubuntu 16.04 with the latest pouchdb version and pouchdb-find version.

### Reproduce
This is my query:
```
this.noteService.notes.changes({
    live: true,
    include_docs: true,
    filter: '_view',
    view: 'noteFilterAndSort/noteFilterAndSort',
    selector: {
         project: this.id
    }
})
```
The service looks like this:

```
import { Injectable } from '@angular/core';
import PouchDB from 'pouchdb';
import Authentication from 'pouchdb-authentication';
import PouchTransform from 'transform-pouch';
import PouchFind from 'pouchdb-find';
PouchDB.plugin(Authentication);
PouchDB.plugin(PouchTransform);
PouchDB.plugin(PouchFind);

@Injectable()
export class Notes {
    public notes = new PouchDB('http://abc.com:5984/notes', {skipSetup: true});

    constructor() {
        this.notes.transform({
            incoming(doc) {
                if (typeof doc.created_at === typeof undefined) {
                    doc.created_at = new Date();
                }
                doc.updated_at = new Date();
                return doc;
            },
            outgoing(doc) {
                return doc;
            }
        });
    }
}
```

**Comment by willholley** [comment]
@Sebi55 it looks like you're using a view filter instead of selector. Can you show the code which initiates the `changes` request with the selector? Enabling [debug mode ](https://pouchdb.com/api.html#debug_mode) might also show you where the issue is.

**Comment by Sebi55** [comment]
@willholley Sorry I posted the version which worked. I have updated my question. Now I am using a view filter and a selector.

**Comment by willholley** [comment]
@Sebi55  `selector` is a more performant replacement for JavaScript filters (including _view filters) when fetching changes from a CouchDB server - you should use one or the other. We could probably throw an Error on the client if both are specified.

**Comment by Sebi55** [comment]
@willholley So it is not possible to use both? Just to clarify this. Then the best would be to mention this in the documentation too.
Throwing an error would be great!

**Comment by willholley** [comment]
@Sebi55 correct - `selector` is a new type of filter (see http://docs.couchdb.org/en/2.0.0/api/database/changes.html#selector). PRs to the documentation always welcome ;)
