### ISSUE TITLE
Feature request: add "added" property to changes feed

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb#6552]
For apps that listen to the `.changes()` feed in order to update the UI there is currently no way to differentiate changes that created a new document to changes that updated a document, which is a big challenge. Previous attempts to differentiate `create` and `update` have been removed (https://github.com/pouchdb/pouchdb/releases/tag/5.0.0), and rightfully so, they only differentiated based on the `_rev` number.

The only way for an app to know when a change is an update to a previously existing document in the database or was added to the database (e.g. via a replication coming from a remote database) is to keep track of what exists in the database and check against that for each `change` event. 

I wonder if it would be possible to add an `"added"` property to the changes feed the same way there is a `"deleted"` property today. I know that this means to diverge from what CouchDB does, but I think the `"added"` event does not make sense in a CouchDB cluster while it makes a lot of sense in a client. It’s also just an added property and is not changing existing behavior beyond that.

Let me know what you all think :)

**Comment by nolanlawson** [comment]
The only way to determine if a doc was added is to check that the revision number starts with `1-`. Even this isn't foolproof, though, since you can have generation-1 conflicts and thus multiple documents that start with `1-`.

This is something that it would be technically possible for PouchDB to expose, but it's also something that the developer themselves can reasonably infer from the changes feed – i.e. use `changes()` with `{style: 'all_docs'}`, check the `seq` of any `1-` documents, and see if they're lower than the `seq` of the `1-` document you just saw. Is there any reason that this would be an infeasible solution for you?

**Comment by gr2m** [comment]
sorry I don’t mean to differentiate between create and update from a document’s perspective.

I want to differentiate between when a document revision added to a document to my database and when it was updating a document that existed in my database before.

Say I replicate from a remote database, a document with revision `3-abcdef...` should be marked as "added" in the changes feed, because this revision is when it was added to this database. 

I wonder if we could implement that on PouchDB’s changes feed somehow.

**Comment by gr2m** [comment]
To add some context, this is a major problem we have with Hoodie. We want to emit an `add` event when a document gets to a database, no matter its revision. From a developer perspective I want to know when a new document was added to my store so I can update my view correctly

**Comment by gr2m** [comment]
I looked a bit trough the code and it looks like PouchDB is already checking if a document exists to calculate changes: https://github.com/pouchdb/pouchdb/blob/843e1f0eb102537551b295c37f9f343b26fb4db4/packages/node_modules/pouchdb-adapter-utils/src/processDocs.js#L93-L103

If I understand it correctly, the `insertDoc` function gets only run if the change is new, so that could be the place where we set the `"added": true` flag, no?

**Comment by gr2m** [comment]
It looks like the required change is very trivial, or am I missing something?

```diff
diff --git a/packages/node_modules/pouchdb-adapter-utils/src/processDocs.js b/packages/node_modules/pouchdb-adapter-utils/src/processDocs.js
index 2fc661c..5c17d29 100644
--- a/packages/node_modules/pouchdb-adapter-utils/src/processDocs.js
+++ b/packages/node_modules/pouchdb-adapter-utils/src/processDocs.js
@@ -37,6 +37,8 @@ function processDocs(revLimit, docInfos, api, fetchedDocs, tx, results,
 
     var delta = deleted ? 0 : 1;
 
+    docInfo.metadata.added = true
+
     writeDoc(docInfo, winningRev, deleted, deleted, false,
       delta, resultsIdx, callback);
   }
diff --git a/packages/node_modules/pouchdb-adapter-utils/src/updateDoc.js b/packages/node_modules/pouchdb-adapter-utils/src/updateDoc.js
index e007454..6ce964f 100644
--- a/packages/node_modules/pouchdb-adapter-utils/src/updateDoc.js
+++ b/packages/node_modules/pouchdb-adapter-utils/src/updateDoc.js
@@ -69,6 +69,8 @@ function updateDoc(revLimit, prev, docInfo, results,
     newRevIsDeleted = isDeleted(docInfo.metadata, newRev);
   }
 
+  docInfo.metadata.added = false
+
   writeDoc(docInfo, winningRev, winningRevIsDeleted, newRevIsDeleted,
     true, delta, i, cb);
 }
```

**Comment by gr2m** [comment]
given its nature, this would not work with the http adapter

**Comment by nolanlawson** [comment]
This sounds like you essentially want to know whether a document was created locally or synced remotely. I don't believe this is something PouchDB actually knows given the structure of the API? The `sync()`/`replicate()` APIs use exactly the same user-facing APIs to create documents.

The other way you could know would be to use `get()` to get the entire revision tree, and if you see `3-` but not `2-` or `1-` then you know it's the first.

**Comment by gr2m** [comment]
> This sounds like you essentially want to know whether a document was created locally or synced remotely

yeah but I only need that information for the changes feed so that I can emit the right event with hoodie.store. Have you seen my PR? The change is trivial, but it only works for non-http databases, which is fine for Hoodie.

**Comment by gr2m** [comment]
to be very concrete, what I want is fix how [Hoodie is calculating `add` vs `update` events](https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/lib/helpers/start-listen-to-changes.js). Using the `_rev` number or how we do it with the `.updatedAt` timestamp (gets added on first update) does not help, because if a document that was previously updated somewhere else gets replicated to the local store, it emits `update` while it should emit `add`

If we released the PouchDB change in https://github.com/pouchdb/pouchdb/issues/6553 I could make the change below in hoodie and the events would be accurate

```diff
diff --git a/lib/helpers/start-listen-to-changes.js b/lib/helpers/start-listen-to-changes.js
index 4478416..da42c5d 100644
--- a/lib/helpers/start-listen-to-changes.js
+++ b/lib/helpers/start-listen-to-changes.js
@@ -13,7 +13,7 @@ function startListenToChanges (state) {
       doc.hoodie = {}
     }
 
-    var eventName = doc.hoodie.deletedAt ? 'remove' : doc.hoodie.updatedAt ? 'update' : 'add'
+    var eventName = change.deleted ? 'remove' : change.added ? 'add' : 'update'
     state.emitter.emit(eventName, doc)
     state.emitter.emit('change', eventName, doc)
   })
```

**Comment by nolanlawson** [comment]
Hmmm so looking over #6553 I have a few thoughts:

1. Historically we've been reluctant to add extensions to CouchDB's behavior because the assumption is that if something is valuable for PouchDB then it's valuable for CouchDB too
2. The change you propose would also require a migration if it were to work correctly
3. I see the difficulty in what you're trying to do but I think there may be a simpler workaround that doesn't require an internal change to PouchDB

For instance, you could 1) generate a UUID for the local DB, 2) store it in a `_local` document, 3) add it as a field to each document, then 4) you can check if the revision is the earliest known (`1-`, `2-`, `3-`, etc.) and then also check if it was created locally or not. If it was created locally, then you can reliably use the timestamp, whereas if it was added remotely, then you have to use the "earliest known rev" technique.

That said, if all of this sounds like a lot of work and if it's still not a reliable way to detect local additions vs updates, then maybe this would be a good thing to pitch to the CouchDB JIRA? If CouchDB adds it then we'll add it. :)

**Comment by gr2m** [comment]
can you explain what you mean with 

> you can check if the revision is the earliest known

Say I would store the `uuid` for my db in each document. A document from remote has a different `uuid` and gets replicated to my local store, which would cause an `add` event. Now the remote document gets updated, it still has a different `uuid`, how would I know to emit an `update` event this time?

> That said, if all of this sounds like a lot of work and if it's still not a reliable way to detect local additions vs updates, then maybe this would be a good thing to pitch to the CouchDB JIRA? If CouchDB adds it then we'll add it. :)

I pitched it to Jan but I think saw a problem with the cluster setup. I’m a big fan of staying close to what CouchDB does. But there are some cases for the "edge" DBs which do not make sense for the central DBs and I’d argue this would be one of them

**Comment by avickers** [comment]
How widely federated is this going to be?  Why not just make _local an array containing all the local databases that a document has landed in?  If the local UUID is in the array, it's an update; otherwise, push the uuid and emit added.

**Comment by daleharvey** [comment]
So I think this sounds like a nice addition, however to repeat Nolan's point of caution, I would be 100% on board with adding this via CouchDB, however fairly unlikely to add it without CouchDB support, we have worked pretty hard to ensure that if you write pouchdb code it works despite what adapter you use, its an extremely important property

**Comment by gr2m** [comment]
yes I understand :( it will be hard to add to CouchDB because of the clustering. I tried to workaround it but it’s very, very hard. 

I wonder if we could find a way to add an option that would somehow make this possible with a hook or something like that. It also wouldn’t be nice I’m just out of ideas :/

**Comment by gr2m** [comment]
I _think_ I found a workaround, but it's not extensively tested yet. It adds quite some complexity and I’m not sure about the performance impact. 

- The first part is loading all documents on start and populating a map of document ids we know.
- start listen to changes. If there are changes while loading the docs from the step above, queue them up and handle once bootstrapping is done

[hoodie-store-client/lib/helpers/bootstrap.js](https://github.com/hoodiehq/hoodie-store-client/blob/12bc33c6e8a1de94d75078730e5d34a5b4ae5b85/lib/helpers/bootstrap.js)

The 2nd part is to make sure that `db.put` and `db.bulkDocs` does only resolve after the event is emitted:
[hoodie-store-client/lib/helpers/db-put.js)](https://github.com/hoodiehq/hoodie-store-client/blob/12bc33c6e8a1de94d75078730e5d34a5b4ae5b85/lib/helpers/db-put.js) and [hoodie-store-client/lib/helpers/db-bulk-docs.js](https://github.com/hoodiehq/hoodie-store-client/blob/12bc33c6e8a1de94d75078730e5d34a5b4ae5b85/lib/helpers/db-bulk-docs.js)

This is because otherwise if a user subscribes to the changes feed the promise resolves of e.g. `db.bulkDocs` then they would get the changes feed of the call above which is very confusing, see a test at [hoodie-store-client/tests/integration/events.js](https://github.com/hoodiehq/hoodie-store-client/blob/119bdca2f62b0c88b87c10094575a9800214e777/tests/integration/events.js#L423-L438)

To be fair, the "added" property in the changes feed wouldn’t help with the 2nd point about the order of promise resolves and events order.

I would love to hear your thoughts on this. Feel free to close this issue and the according PR, I can understand that this is not a good fit for PouchDB right now, and it seems clear that CouchDB will not add it any time soon

**Comment by daleharvey** [comment]
Yeh my usual way to deal with this is to draw a UI with all items and data-id=id, then when I see change events I check if data-id exists. If we could get this working via CouchDB as well would definitely be happy to support but for now will close out, cheers
