### ISSUE TITLE
How PouchDb handles auth by default

### ISSUE THREAD

**Issue by danielo515** [pouchdb/pouchdb#6558]
### Issue
How PouchDb handles auth by default

### Info
- Environment:  browser/hybrid app
- Platform: Chrome/FF/Edge/Android
- Server: CouchDB/Cloudant

I just want to know how pouchdb handles authentication when configured to synchronize with remote databases. I don't know why, but I took for granted that it makes a post request with the credentials and then relies on the cookie. However, my experience tells me that this is not true.

If you could specify the exact behavior (basic auth? cookie auth?) I will be very grateful. 
I tried inspecting the network tab, but I can not see any request to `_session`

This is my current way of doing this:

```js
/* authOptions: {
      username: 'mysecretusername',
      password: 'mysecretpassword'

online = new Pouchdb('https://remote.sever.com/database',{ auth: authOptions })

```

If I want to make it use the cookie, what's the correct way? Make a post request myself and configure the database without credentials?

```js
// POST REQUEST HERE TO _session
online = new Pouchdb('https://remote.sever.com/database')
```

**Comment by willholley** [comment]
@danielo515 PouchDB doesn't use _session by default - you'd need to use [pouchdb-authentication](https://github.com/pouchdb-community/pouchdb-authentication) and the `login` method for that.

**Comment by willholley** [comment]
@danielo515 you can also call the `_session` endpoint yourself if you don't want to pull in all of pouchdb-authentication - Pouch will just use the cookie if it's present.

**Comment by danielo515** [comment]
> @danielo515 you can also call the _session endpoint yourself if you don't want to pull in all of pouchdb-authentication - Pouch will just use the cookie if it's present.

That is more or less the answer that I was looking for. So, by default, pouchdb uses basic authentication if credentials are provided. As you said, looks like you have to make the request yourself and **don't provide credentials to pouchdb** if you want to use a cookie. I think this deserve more attention on the documentation, or at least a clarification message.

**Comment by dhavaln** [comment]
@danielo515 Did you find the solution for this.

I am having the similar problem, where one of the application is using the pouchdb-authenticaion but we need to replace that now with a cookie based authentication and it it not able to connect. I am passing the cookie in ajex option, which I have created from Admin port via a reverse proxy.

**Comment by danielo515** [comment]
@dhavaln I was not using pouchdb-authentication at all. What I do is make a call to `_session` and handle the response. If the user is logged, then I create a remote pouchdb, if not, I ask the user for logging, and then I make a post to `_session` and when it completes I create a remote pouchdb. What is your use-case exactly?

**Comment by dhavaln** [comment]
@danielo515 right the app gets username/password from the login screen, but need to replace that with Auth0 OAuth, so need to replace the user/pass combination with token or cookie.

**Comment by danielo515** [comment]
As I said,pouchdb will use basic auth by default. If you want it to use a cookie you have to set the cookie yourself first (actually the server must) and then instantiate a remote pouchdb database without providing credentials to it

**Comment by dhavaln** [comment]
@danielo515 I finally fixed that with a reverse proxy in nodejs. Previously I was connecting to sync gateway directly, but now I am routing all the requests through nodejs and that is working fine.

**Comment by danielo515** [comment]
Cool. I don't understand what is your scenario, and now I'm intrigued about the role of the proxy.

**Comment by dhavaln** [comment]
https://developer.couchbase.com/documentation/mobile/1.4/guides/authentication/custom-authentication/index.html

Similar to what is explained in the diagram, but instead of NodeJS connecting to Google, I have app connecting to Auth0, which if returns success, I create session in the NodeJS and in SG. As the cookies are forwarded, all the communication between pouchdb and SG is through the NodeJS rather with direct SG URL.

**Comment by vardas-bill** [comment]
@danielo515  I am struggling (failing) to get pouchdb-authentication to work properly so I am intrigued about your solution. Could you elaborate on what you are doing exactly? I am happy to just use PouchDB with basic auth to CouchDB if possible. I am tearing my hair out here :)

**Comment by danielo515** [comment]
Hello @vardas-bill
I just make an authentication request to _session ,let the cookie be set and then I instantiate the remote PouchDB database and start using it

**Comment by vardas-bill** [comment]
Many thanks for replying to my question it is hugely appreciated!

Thanks @danielo515 

Unfortunately I have no experience of _session and cookies for authentication. Would you be able to share some code snippets?

Thanks again for your help.

**Comment by marten-de-vries** [comment]
@vardas-bill https://github.com/pouchdb/pouchdb-auth/blob/master/lib/sessionapi.js#L51
where httpQuery is:
https://github.com/pouchdb/pouchdb-req-http-query/blob/master/index.js#L30

There's a lot of extra stuff you probably won't need for just logging in, but it should give you an idea on how to build an xmlhttprequest and what properties to set on it.

**Comment by vardas-bill** [comment]
Thanks @marten-de-vries those links are very useful. I will try out using _session.

**Comment by vardas-bill** [comment]
@marten-de-vries once I have got the cookie via _session how do I ensure that PouchDB uses it?

**Comment by marten-de-vries** [comment]
@vardas-bill The browser will automatically send any cookie the server sets. So no need to do anything, just start using PouchDB and your requests should automatically be authorized.

**Comment by vardas-bill** [comment]
@marten-de-vries is that also true for Cordova/ionic Apps?

**Comment by garrensmith** [comment]
Yes it will be

All misspelling thanks to my iPhone.
________________________________

**Comment by vardas-bill** [comment]
Thanks @garrensmith

**Comment by dhavaln** [comment]
If it helps, I have put together a simple demo app which uses Auth0 for authentication and then uses cookies to connect pouchdb with sync gateway

https://github.com/dhavaln/auth0-pouchdb-syncgateway

**Comment by vardas-bill** [comment]
Thanks Dhaval.

 

Bill
