### ISSUE TITLE
Change API not including changed documents

### ISSUE THREAD

**Issue by danielo515** [pouchdb/pouchdb#6568]
### Issue
The `on change` event of the replication is not working as expected

### Info
- Environment: browser
- Platform: Chrome
- Adapter: not sure
- Server: Cloudant

Hello,

Reading the replication API I expected the `on change` event to include certain metadata about the changed document. This it's explained here:

https://pouchdb.com/api.html#example-response-10

I know that is the api for replication, but the documentation at sync refers to it, so I will take it as source of truth. As you can see, according to documentation I will get an array of changed documents, so far so good.
However, instead, I'm getting the following:

```js
{
    "direction": "pull",
    "change": {
        "ok": true,
        "start_time": "2017-06-24T18:14:39.290Z",
        "docs_read": 4,
        "docs_written": 4,
        "doc_write_failures": 0,
        "errors": [],
        "last_seq": "389-g1AAAAGjeJzLYWBgYMlgTmGQT0lKzi9KdUhJstDLSs1LLUst0kvOyS9NScwr0ctLLckBKmRKZEiy____f1YGc6J6LlCAPc0ixdQoOZWwdlQrzHBbkeQAJJPqobacANtimWJmYp5iRtgEoj2SxwIkGRqAFNCi_SCbfME2mRhYphmYG1PRPxCbDkBsAvvJE2yThaGlZappKmFTsgDmlIlz"
    }
}
```

The advantage is that I know the direction, the disadvantage is that I have to make my view to re-read all the documents just to get the most fresh version of the changes. There is no `docs` array anywhere

The way I'm triggering the replication is as follows:

```js
database.sync(remoteDB, {
        live: true,
        retry: true,
        filter: 'filtered_replication/only_tiddlers'
      }).on('change', function (info) {

        log( '===SYNC Change===');
        if (info.direction === 'pull'){
        // Refresh the full view because we don't know which documents should be updated
        }
      })
```

**Comment by daleharvey** [comment]
Will take a look at this, have you tried `include_docs`?

**Comment by danielo515** [comment]
Not, I didn't tried include docs. I thought small version of docs is included by default and the include docs flag was for complete docs. Besides that, I think the include docs feature it's a bit hidden.

**Comment by danielo515** [comment]
Have you just updated the docs ? They're much clearer now

**Comment by daleharvey** [comment]
Looks fixed, cheers
