### ISSUE TITLE
RFC: July release (v6.3)

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#6579]
It's been a while since we released 6.2 and we have a few useful bug fixes to get out. The changeset since 6.2:

- (#6308) - Add option to disable checkpoints
- (#6510) - Prevent timeouts due to invalid parameters when calling _changes
- (#6545) - Throw Errors, not Strings
- (#6529) - Include doc ID in 404 (not_found) errors for IDB adapter
- (#6504) - Fix possible "EventEmitter memory leak detected"
- (#6487) - Change Chrome extension to better supported / rated version
- (#5981) - Ensure `close()` doesn't block `destroyed` events
- (#5832) - New Feature: force update
- (#6452) - Add support for use_index in `pouchdb-find`
- (#6495) - Add explain endpoint for `pouchdb-find`
- (#6472) - Don't return design docs with all_docs index
- (#6443) - Add $allMatch support for `pouchdb-find`
- (#6458) - Consistent error handling for mapreduce indexes
- (#6364) - Accept trailing garbage when recognizing built-in reduce functions

Are there any pending PRs that need merging prior to release? #6544, #6574 and #6565 perhaps.

**Comment by garrensmith** [comment]
+1 from me

**Comment by nickcolley** [comment]
Nice 👍

**Comment by daleharvey** [comment]
And done, thanks @willholley 👍
