### ISSUE TITLE
Load plugin with requireJs.  

### ISSUE THREAD

**Issue by Nikonov** [pouchdb/pouchdb#6581]
### Issue
How load localStorage adapter with requirejs? I use TypeScript (v2.3.4) to compile my source to es5. When loaded my application I have error:
*localstorage adapter plugin error: Cannot find global "PouchDB" object! Did you remember to include pouchdb.js?* 

### Info
- Environment: browser
- Platform: WebKit
- Adapter: LocalStorage
- Server: None

### Reproduce
My config:
```

require.config({
    paths: {
        'pouchdb': '/libs/pouchdb.min',
        'pouchdb-adapter-localstorage': '/libs/pouchdb.localstorage.min'
    },
    shim: {
        'pouchdb': {
            exports: 'PouchDB'
        },
        'pouchdb-adapter-localstorage': {
            deps: ['pouchdb']
        }
    }
});

```
My class which use  pouchDb.

```
import * as PouchDB from "pouchdb";
import * as local from "pouchdb-adapter-localstorage";

export class PouchDBDataProvider implements MainDataProvider {

    constructor() {
        console.log(' constructor started ');
        PouchDB.plugin(local);
        let db = new PouchDB('mydb', {adapter: 'localstorage'});
        console.log(' DB inited ');
        console.log(db);
    } 
}

```
Output console I see only line:
*constructor started*

How correct load plugin with requirejs ?

**Comment by caracal7** [comment]
I have the same problem :(

**Comment by daleharvey** [comment]
Closing out typescript bugs, we do not use typescript for this repo and if typescript projects cant use other javascript projects then I would suggest that they fix that
