### ISSUE TITLE
Problem with pouchdb-find

### ISSUE THREAD

**Issue by zinnen** [pouchdb/pouchdb#6584]
### Issue
A query-command (Map/Reduce) using a view as index will return deleted documents. Is this normal behaviour? Do I have to reindex after deleting a document?  This fact leads to following issue with pouchdb-find: 

Pouchdb-find is running into trouble with deleted documents synced from Cloudant Server: 
- Database "test" on Cloudant (2 Attributes per entry: familyname, age)
    e.g.  {"familyname": "meyer","age": 38}  {"familyname": "meyer","age": 55} {"familyname": "jansson","age": 45}
- Sync to/from local pouchdb database "test": all entries are synced correctly
- Deletion of an meyer entry (using "_deleted":true) on the cloudant server is synchronized correctly to local DB (checked with alldocs on local pouchdb)
- Running a find using familyname and age as index (see code below) will result in TypeError after deletion, and run correctly when inserting the document again
      - TypeError: Cannot read property 'familyname' of undefined(...)
- Running a query on local DB will also list deleted documents
- It seems that the find-query is accessing the via sync deleted document
- After inserting the document again, the pouchdb-find works fine again

Comment: The pouchdb-find works fine (even after deletion) when directly accessing the Cloudant DB. The error occurs only when accessing the local DB the deletion was synced to. The error messages when accessing the deleted document using fetch and _id are different on the 2 DBs (Maybe this will help?): 

- Error when accessing deleted document on Cloudant: CustomPouchError {status: 404, name: "not_found", message: "missing", error: true, reason: "missing_rev_check"}
-  Error when accessing deleted document on local DB: Object {status: 404, name: "not_found", message: "deleted", error: "not_found", reason: "deleted"}

### Info
- Environment: (React Native)
  - "pouchdb-find": "^6.2.0",
  - "pouchdb-react-native": "^6.2.6",
  - "react": "16.0.0-alpha.12",
  - "react-native": "0.45.1",
- Platform: (Android)
- DB-Server: (Cloudant)

### Reproduce

db = new PouchDB('test');
dbRemote = new PouchDB('cloudantServer/test/');
db.sync(dbRemote, {live: true,retry: true});
        
// This code does not work anymore after deleting one document (on Cloudant) with "_deleted": true
// ... but works again when inserting the document (using the same _id)
db.createIndex ({index: {fields: ['familyname', 'age']}})
            .then (result => {
                db.find({
                    selector: {familyname: 'meyer', age: {$gt: 20}}
                }) .then((res)=>{
                      console.log(res);
                    })
                    .catch((err)=>{
                        console.log(err);
                    });
            });

// This code does work after deleting one document (on Cloudant) with "_deleted": true
dbRemote.createIndex ({index: {fields: ['familyname', 'age']}})
            .then (result => {
                dbRemote.find({
                    selector: {familyname: 'meyer', age: {$gt: 20}}
                }) .then((res)=>{
                      console.log(res);
                    })
                    .catch((err)=>{
                        console.log(err);
                    });
            });

**Comment by bgold0** [comment]
I'm having this issue as well with it finding deleted documents.
