### ISSUE TITLE
Connection `cancelled` after timeout despite data being sent from Sync-gateway

### ISSUE THREAD

**Issue by cyberjar09** [pouchdb/pouchdb#6587]
### Issue
When streaming data to an app (offline-first requirement, 2MB data & combined with slow network), the network tab shows that the connection was `cancelled` after some time indicating that PouchDB client is closing the connection to Sync-gateway (server)

### Info
- Environment: (static single page app/browser)
- Platform: (Chrome 59)
- Adapter: (IndexedDB)
- Server: (Sync gateway, couchbase)

### Reproduce
introduce network latency using chrome dev tools. The link that takes really long has the path: `http://<hostname>/<bucket_name>/_all_docs?conflicts=true&include_docs=true`

I am not comfortable extending the timeout value on PouchDB because thats a stop gap measure IMHO. The client should not be closing the connection if the sync-gateway is still sending data.

**Comment by daleharvey** [comment]
Closed due to https://github.com/pouchdb/pouchdb/issues/5820
