### ISSUE TITLE
pouchdb-adapter-websql does not work out of the electron

### ISSUE THREAD

**Issue by undefinedESC** [pouchdb/pouchdb#6588]
### Issue
pouchdb-adapter-websql does not work out of the electron

### Info
- Environment: (Node.js/Electron)
- Platform: (mac osx)
- Adapter: (WebSQL.)
- Server: (None)

### Reproduce
```
// import PouchDB from 'pouchdb-browser';
let PouchDB = require('pouchdb-core').plugin(require('pouchdb-adapter-websql'));  
let db = new PouchDB('mydb',  {adapter: 'websql'});
```
### Error

```
Error: Invalid Adapter: websql
    at new PouchDB$2 (/Users/macbook/Documents/git/ESCMAScript/node_modules/pouchdb-core/lib/index.js:1263:11)
    at /Users/macbook/Documents/git/ESCMAScript/app/main.js:27:1
    at Object.<anonymous> (/Users/macbook/Documents/git/ESCMAScript/app/main.js:128:2)
    at Object.<anonymous> (/Users/macbook/Documents/git/ESCMAScript/app/main.js:130:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (/Users/macbook/Documents/git/ESCMAScript/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:283:12)
```

**Comment by shmendo** [comment]
I just ran into this recently and had to install in a very specific version. I cannot get it to run correctly inside electron but it will get you past your current error.

**Install pouchdb-adapter-node-websql**
```
npm install --save pouchdb-adapter-node-websql
```

**NOTE:** Make sure the full path to the db exists, or it will fail silently.

**Configure websql adapted (requires more arguments)**
```
const db = new PouchDB('/tmp/db', {
  adapter: 'websql',
  version: '1.0',
  description: 'a description',
  size: 1
});
```

**Comment by undefinedESC** [comment]
@shmendo thx, have you tried sync data？

**Comment by shmendo** [comment]
@undefinedESC, no, I have not. Actually, we were able to figure out the problems. 

Apparently a lot of the errors in pouch/leveldb/websql return an empty error without any information. In our case at least one was just making sure the folder containing the DB existed. 

Error messages that provide some information would be helpful instead of the totally empty ones being provided. I can now get it working on my mac fine now... just can't quite get it working on windows. If you want to create a private gist with your code and send it to me I may be able to help you out.

**Comment by shmendo** [comment]
@undefinedESC Some interesting behavior we've observed is that WINDOWS will always create the missing folder while *nix (including mac) will not. Were you able to figure anything else out or create a gist showing the problem?

**Comment by daleharvey** [comment]
Bug in electron, happy to take a fix if possible nut not tracking here
