### ISSUE TITLE
Direct Download in 6.3.0++ version cannot work

### ISSUE THREAD

**Issue by dodomui** [pouchdb/pouchdb#6605]
### Issue
After pouchdb 6.3.0 receive below error.
1. `pouchdb-6.3.0.min.js:7 Uncaught SyntaxError: Unexpected token <`
2. therefore while i call pouchdb receive error `ReferenceError: PouchDB is not defined`

### Info
- Environment: hybrid app ionic
- Platform: chrome / ios / android
- Adapter: WebSQL
- Server: Cloudant

### Reproduce
Direct download and include the script.
<script src="pouchdb-6.3.2.min.js"></script>

It is working fine with 6.3.2 version and previous.

**Comment by daleharvey** [comment]
Yup 6.3.0 was a broken release, 6.3.2 was the fix, I have marked this on https://github.com/pouchdb/pouchdb/releases/tag/6.3.0
