### ISSUE TITLE
Sync work same as replication? Stop after 10mins offline?

### ISSUE THREAD

**Issue by dodomui** [pouchdb/pouchdb#6606]
### Issue
I face the sync drop randomly after device idling for certain time.

### Info
- Environment: hybrid
- Platform: chrome / ios / android
- Adapter: WebSQL
- Server: Cloudant

### Reproduce
Will sync() work same as replication? which stop after 10mins offline?
If yes, how could I let it retry forever?

Due to it is happens randomly I couldn't provide any example / step.

Anyone got ideas what is the problem? is it be

**Comment by willholley** [comment]
In PouchDB prior to version 6.3, live replication would progressively back-off when devices were offline and not get re-triggered immediately when connectivity was restored. This should be fixed in 6.3 - can you try updating to 6.3.4 and retesting?

**Comment by vinidalmagro** [comment]
I have this same problem and I use v6.3.4
I've phrased a function that re-sync within the event that listens to the status of the network

`
isOnline = ->
      PersistService.cancelSync()
      PersistService.beginSync(user)

if window.addEventListener
       window.addEventListener('online', isOnline, false)
       window.addEventListener('offline', isOnline, false)
`

**Comment by dodomui** [comment]
This problem seem solved.
I am using 6.3.4 and applied method like @vinidalmagro using.
