### ISSUE TITLE
Introduce commit hook to enforce commit message format

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#6608]
Our commit message format (copied from mozilla) is there to help diagnose issues in the future by giving us a pointer to discussion about every bit of code that is committed 

https://github.com/pouchdb/pouchdb/commit/f4f1dbf29c310db9b092fe9f520c16293a81dae3 should point to https://github.com/pouchdb/pouchdb/issues/6579, https://github.com/pouchdb/pouchdb/commit/4ceb1bd9e3e3ab45467f4a4c688d345c0f29bea6 to https://github.com/pouchdb/pouchdb/issues/6600 etc

Sometimes these pointers are just back to the PR number and there is no discussion, but the majority of the time they are very useful so I would like to preserve / enforce this

**Comment by gr2m** [comment]
@daleharvey happy to build a github app that enforces it on GitHub Pull Requests using the status API :) I build a few of these lately, so much fun.

**Comment by daleharvey** [comment]
Most of these commits are done through the command line, not just PR's, do pre commit hooks work for stuff pushed through github or would we need both to be sure?

**Comment by janl** [comment]
GitHub can't support pre commit hooks for cli commits based on the distributed nature of git. Contributors will have to set up the hooks themselves.

The same code that makes PRs fail could run as part of CI. In fact, if `npm t` were to lint commit messages, it'd be available everywhere.

**Comment by gr2m** [comment]
> In fact, if npm t were to lint commit messages, it'd be available everywhere.

that’s a good point 👍
