### ISSUE TITLE
No Network Requests in Chrome Dev Tools

### ISSUE THREAD

**Issue by psamim** [pouchdb/pouchdb#6611]
### Issue
Hi, 
I use PouchDB as a client to a remote CouchDB using http adapter but I see no network request in dev tools. It also connects to the server even I choose to be offline in dev tools. Is it an expected behaviour?

### Info
- Environment: Electron
- Platform: Electron (Linux)
- Adapter: http
- Server: CouchDB

### Reproduce
1- `db = new PouchDB('http://localhost:5948/db');`
2- `db.allDocs()`

**Comment by willholley** [comment]
I've never seen a problem with PouchDB in Chrome dev tools - perhaps it's an electron thing?

**Comment by psamim** [comment]
It probably is.

**Comment by daleharvey** [comment]
Yeh we dont do anything weird here o fairly certain it isnt pouch, gonna close this out cheers
