### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by bioleyl** [pouchdb/pouchdb#6612]
Hello,

I'm new with pouchdb and I'm trying to make a mobile app (cordova) with it.

I have a big perfomance problem with the initial replication. For 18000 records it takes more than 3 min.

What I'm doing wrong because it's not usable at that speed. When I query all docs on my remote couch, (http://127.0.0.1:5984/{mydb}/_all_docs?include_docs=true) it takes less than 2 seconds to get all the 18000 records.

Here is my code:
```
let remoteCouch = `http://${conf.server.username}:${conf.server.password}@${conf.server.serverAddress}:${conf.server.serverPort}/${dbName}`
let db = new PouchDB(dbName, {revs_limit: 1, adapter: 'websql'})

if (remoteCouch) {
  let opts = {
    live: true,
    retry: true,
    batch_size: 2000,
    batches_limit: 10,
    timeout: 60000
  }
  db.replicate.to(remoteCouch, opts, syncError)
  db.replicate.from(remoteCouch, opts, syncError)
}
```
I was trying with a lot of different batch_size but it's not changing a lot.

I also have a query to find article by code

```
art_by_num: { map: function (doc) { if (doc.type === 'article') { emit(doc.noart) } }.toString() }
```
And the first search after initial replication take 5 minutes!!!. Since the second query it's almost direct. Why? Is there a caching function running in back? Can we trigger it during replication?

Best regards

**Comment by bioleyl** [comment]
I have to specify one thing. The remote couch is a fresh one. The records has no revisions.
About the android device it's a android 5.1, 8 core processor, 2Gb RAM so I don't think it's a device performance problem.

**Comment by willholley** [comment]
@bioleyl 18k records is a lot to sync in one go - you might want to consider using [pouchdb-dump](https://pouchdb.com/2016/04/28/prebuilt-databases-with-pouchdb.html) if the database is going to be static.

If not, consider:
1. do not configure local -> remote replication until the initial remote -> local replication has completed for the first time.
2. disabling remote checkpoints (new in 6.3). This isn't really necessary when the remote is CouchDB 2.0 or Cloudant.

Regarding your query to find article by code, the index `art_by_num` builds the first time it is queried - after that, subsequent queries will be fast (subject to the number of new documents/changes that need to be indexed since the last query). You could define the index before you replicate and periodically query it (e.g. every 500 changes) to keep it up to date as you replicate. I'd also suggest looking at `pouchdb-find` as a more flexible querying option, though the same principle of keeping the index up to date applies.

**Comment by bioleyl** [comment]
Hello and thanks for your answer.

I have a server part with node js so I try using https://github.com/pouchdb-community/pouchdb-replication-stream to make a dump file.

Problem is sometimes (completely random) 4/10 dump ends with an error

```
oh no an error { [unknown_error: badarg]
  error: 'unknown_error',
  reason: 'badarg',
  ref: 2871698149,
  name: 'unknown_error',
  status: 500,
  message: 'badarg',
  result: 
   { ok: false,
     start_time: 2017-07-18T09:12:04.500Z,
     docs_read: 7050,
     docs_written: 7050,
     doc_write_failures: 0,
     errors: [],
     last_seq: '7050-g1AAAAJ7eJyd0D8OgjAUBvAGSHD1BHiElhahk4zeQvsHQ0iVGHXWwXvo5OoR9AxeQG-CpSWyEBNYvpe8l-83PAUAGOWuBGNRHkQueapKwVRe7vZKnxwGeFBVVZG7HABvvtY7n0rIYwK7On8kPtHJZy0WGCyiCFJM-2JpjS1-mPsyWEJREoa4L7assWOLbS0mIMyI7IltPJ3gpIf2Lg14MyAOiRAoGwReLfhoQN-AU8h4RMQg8GnBtwWduwE5QyvE4kHgx4LND52zAbOYYEhQV7X4AnnQwsw',
     status: 'aborting',
     end_time: 2017-07-18T09:12:12.344Z } }
```
Sometimes it read 3000 docs befor crash, sometime 8000 it's completely random.

I did try to reduce the concurent requests

```
import Http from 'http'

// Set maximum concurent requests
Http.globalAgent.maxSockets = 5
```

but no changes. Any idea?

Here is my dump function

```
export let dump = () => {
  let dumpedString = ''
  let stream = new MemoryStream()
  stream.on('data', function(chunk) {
    dumpedString += chunk.toString()
  })

  db.dump(stream).then(() => {
    console.log('dump finished')
    fs.writeFile('./db/dump.txt', dumpedString, (err) => {
      if (err) {
        console.log(err)
      }
      console.log('dump saved')
    })
  }).catch((err) => {
    console.log('oh no an error', err)
  })

}
```

**Comment by willholley** [comment]
@bioleyl CouchDB shouldn't be returning a 500 error - is there anything in the CouchDB logs?

**Comment by bioleyl** [comment]
The problem was my Couchdb. Fresh install work fine!

One last question:
During the dump it fires that line thousand times in the console

```
db.type() is deprecated and will be removed in a future version of PouchDB
```
Any idea to avoid that?

Great thanks for your help.

**Comment by willholley** [comment]
@bioleyl I think that would need addressing in `pouchdb-dump` - perhaps worth filing an issue with the project.

**Comment by bioleyl** [comment]
Thanks for everything.

I continue here:
https://github.com/pouchdb-community/pouchdb-replication-stream/issues/63
