### ISSUE TITLE
6.3.* gives TypeError: PouchDB is not a constructor 

### ISSUE THREAD

**Issue by SearchingSoul** [pouchdb/pouchdb#6614]
### Issue
After upgrading from 6.2.0 to 6.3.2, * is not a constructor shows up.

### Info
- Environment: hybrid app using Ionic Framework 
- Platform: Chrome/Safari in dev
- Adapter: IndexedDB
- Server: none

### Reproduce
upgrade to 6.3.2

I don't think I found this issue &/or any breaking changes in the release notes. Current resolution I use is to stick with 6.2.0.

**Comment by daleharvey** [comment]
6.3.X was broken up until 6.3.4, upgrading should resolve the issue, apologies

**Comment by jcpc91** [comment]
this works for me
var PouchDB = require('pouchdb-browser');
-------------------------------
let pouchdb = PouchDB.default.defaults();
let db = new pouchdb('mydb');
db.info().then(info => console.log(info));

**Comment by alirezatav** [comment]
tnx ,works
