### ISSUE TITLE
We need to be testing much closer to release

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#6616]

**Comment by daleharvey** [comment]
The last release had 2 seperate issues which went unnoticed in testing and we have various bugs filed against us which are not functional bugs but testing issues

We need to be more confident that a release isnt broken which means we need to get our testing closer to our release, by either extending our test capability or my preference by a long way, removing a lot of the extra complexity we do during release (auto calculating deps etc)

**Comment by daleharvey** [comment]
https://github.com/pouchdb/pouchdb/issues/6615
https://github.com/pouchdb/pouchdb/issues/6603
https://github.com/pouchdb/pouchdb/issues/6607
https://github.com/pouchdb/pouchdb/issues/6600

Basically we need to make sure that these errors are caught before release

**Comment by jure** [comment]
My personal preference would also be the latter. Releases often go funky for one reason or another and the more steps there are in a release, the more likely that is to happen. With 6.3.0 missing deps, it was the auto-dep builder thingy that failed, and failed silently at that. As an outsider, hit with a freshly broken PouchDB release, I had no idea where to actually look to see what has gone wrong; the magic overhead was quite staggering.

**Comment by daleharvey** [comment]
As a pouchdb insider I also have no idea where to look :) it seems like the build tools around having an es6 multi module codebase that publishes node + browser distributions should be standardising around now so maybe there is a common tested build system we can use as opposed to out large number of homebrew scripts

**Comment by jure** [comment]
:+1: Are you still settled on using a monorepo?

**Comment by daleharvey** [comment]
Yup, developing and testing across repositories is a huge hassle
