### ISSUE TITLE
How to exclude leveldown from dependencies

### ISSUE THREAD

**Issue by stanleyxu2005** [pouchdb/pouchdb#6620]
### Info
- Environment: Node.js 8.x

We need pouchdb as client. For production we will connect client to a real CouchDB instance. For testing a in-memory db is already quite handy. `punchdb --port=5984 --level-backend=memdown`. But when I install punchdb, it tries to download the Nodejs header and rebuild leveldown from scratch (roughly 100mb size). 

Usually this is not a big problem, but due to some network restrictions, I have never built leveldown successfully. And now if I simply add some node dependencies using `yarn add foo`, it tries to rebuild leveldown. This is really annoying. 

Is it possible to make leveldown optional?

**Comment by ewnd9** [comment]
You can achieve this by copying [`pouchdb-node/src/index.js`](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-node/src/index.js) to your project without `pouchdb-adapter-leveldb`

**Comment by daleharvey** [comment]
Yup, more info on that is @ https://pouchdb.com/custom.html

**Comment by stanleyxu2005** [comment]
Fair enough. I'm expecting the official package.json provide some flexibility not to install leveldown.

**Comment by stanleyxu2005** [comment]
The major reason I raise this issue is also that `npm install pouchdb-server` tries to build `leveldown` from scratch -> Download node header etc by nodegyp, However this is almost impossible for China mainland user or user behind a corporate firewall. If it is defined as peer dependency or optional dependency, it will be much handy. Like me, I use redisdown which does not need any nodegyp build.

**Comment by daleharvey** [comment]
Again, thats exactly what custom builds are for, we used to use it as an optional dependency but the ambiguity other problems

**Comment by ewnd9** [comment]
Forking `pouchdb-server` and publish as a user-scoped package on npm seems to be a viable solution (usually it's simpler to just use fork directly from GitHub url without publishing to npm, but if I recall correctly npm cli doesn't support installing from a monorepo)

**Comment by stanleyxu2005** [comment]
Thank you all. I finally created a minimal pouchdb server manually.
