### ISSUE TITLE
Types/TypeScript update

### ISSUE THREAD

**Issue by riddla** [pouchdb/pouchdb#6627]
Hello (and thanks for a great library!).

Do you have any plans on updating https://www.npmjs.com/package/@types/pouchdb-browser, which is still on 6.1.1? If not, how can someone help?

**Comment by willholley** [comment]
@riddla the Typescript definitions are maintained externally, I think. https://github.com/pouchdb/pouchdb/issues/5389 perhaps worth following up on.

**Comment by WebField** [comment]
It would be a pleasure if we could use PouchDB and its plugins in Angular 2/TypeScript projects easily.

I actually got PouchDB working in my Angular 2 project but the PouchDB-Find plugin doesn't.

**Comment by riddla** [comment]
@WebField: I got the find plugin working in Angular 2/TypeScript, though "untyped". Maybe I can help?

**Comment by WebField** [comment]
@riddla 
My PouchDB import is actually undefined too. But it works.
I've already opened a [questions on Stackoverflow](https://stackoverflow.com/questions/45165990/angular-and-pouchdbfind-plugin): 
I would appreciate it very much if you could help me :)

**Comment by riddla** [comment]
I did, see https://stackoverflow.com/a/45170496/341983.
