### ISSUE TITLE
Size of PouchDB when bundling using Webpack3

### ISSUE THREAD

**Issue by peteruithoven** [pouchdb/pouchdb#6631]
### Issue
We're trying to migrate from JSPM to Webpack3, but we noticed that PouchDB is taking up a very big chunk of our bundle. Usually about 1 MB. 

### Reproduce
I've created the example where I'm compiling the same code using JSPM and Webpack3.

JSPM bundle: 164K
Webpack3 bundle: 1,1M

https://github.com/peteruithoven/bundling-pouchdb-example

I'm curious is others experience the same issues and whether there are solutions or workarounds. 

I found the following article interesting, especially since PouchDB already adds a `jsnext:main`, although that still seems pre-transpiled? 
[Delivering untranspiled source code via npm](http://2ality.com/2017/06/pkg-esnext.html)

**Comment by peteruithoven** [comment]
Totally my fault. I used  a source map type not suitable for production. 
I used `eval-source-map` instead of for example `source-map`, see: https://webpack.js.org/configuration/devtool/

JSPM bundle: 164K
Webpack3 bundle: 156K

**Comment by nolanlawson** [comment]
You can also use the `pouchdb-browser` package instead of the `pouchdb` package to avoid installing leveldb, which is not needed if you're only using PouchDB in the browser. I also note that you're running babel-loader on PouchDB because you're not excluding node_modules, which is unnecessary because PouchDB is already shipped as valid ES5. Hope that helps!

**Comment by peteruithoven** [comment]
Thanks for the `pouchdb-browser` tip!. 
I'm indead running babel, but that was mostly to simulate my regular usage, where I need to transpile my own code. All the node_modules should be excluded though, by defining: https://github.com/peteruithoven/bundling-pouchdb-example/blob/master/webpack3/webpack.config.js#L18. So are you sure I'm running it on PouchDB?
