### ISSUE TITLE
use seq_interval when fetching _changes against CouchDB 2.x

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#6643]
CouchDB 2.0 adds a `seq_interval` parameter to `_changes` which allows skipping calculation of sequence values when returning changes. This can significantly improve latency (computing seq across many shards is expensive), and `last_seq` is always included, so I think we can take advantage of this when fetching a batch of changes via the HTTP endpoint.

In CouchDB 1.x the `seq_interval` is safely ignored.

**Comment by willholley** [comment]
running a few performance tests to replicate a local CouchDB 2.0 db with 70k documents, I see a ~20% improvement in replication time when using the `seq_interval` parameter to skip seq calculation completely (it always sends `last_seq` which is all we need for checkpointing):

```
pouchdb 6.3.4, 70k docs, q=2:

76 seconds
73 seconds
76 seconds

pouchdb 6.3.4, 70k docs, q=8:

73 seconds
75 seconds
79 seconds

seq_interval patch, 70k docs, q=2:
55 seconds
56 seconds
59 seconds

seq_interval patch, 70k docs, q=8:

60 seconds
58 seconds
47 seconds
```

**Comment by garrensmith** [comment]
Awesome. This is a pretty nice improvement
