### ISSUE TITLE
Upgrading to 6.3.4 from 6.2.0: Error PouchDB.plugin is not a function

### ISSUE THREAD

**Issue by antonyRoberts** [pouchdb/pouchdb#6645]
### Issue
In version 6.3.4 

>import * as PouchDB from 'pouchdb';
PouchDB.plugin(require('pouchdb-quick-search'));
PouchDB.plugin(require('pouchdb-find'));

will error in the browser with
>pouchDB.service.ts:10 Uncaught TypeError: PouchDB.plugin is not a function
    at Object.module.exports.ctor.super_ (pouchDB.service.ts:10)
    at __webpack_require__ (bootstrap db10cb0…:49)
    at Object.<anonymous> (postsMain.component.ts:43)
    at __webpack_require__ (bootstrap db10cb0…:49)
    at Object.defineProperty.value (posts.module.ts:15)
    at __webpack_require__ (bootstrap db10cb0…:49)
    at Object.defineProperty.value (app-MainBrowser.module.ts:18)
    at __webpack_require__ (bootstrap db10cb0…:49)
    at Object.c (browser-app.module.ts:6)
    at __webpack_require__ (bootstrap db10cb0…:49)

Am unable to import Pouch DB using
>import PouchDB from 'pouchdb';
import PouchFind from 'pouchdb-find';

Because of  [ts] Module ''pouchdb'' has no default export.

### Info
- Environment: Angular 4 Application
- Platform: Chrome, Firefox, etc
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

### Reproduce
Upgrade to 6.3.4 from 6.2.0

**Comment by willholley** [comment]
looks like a duplicate of https://github.com/pouchdb/pouchdb/issues/6615

**Comment by garrensmith** [comment]
@antonyRoberts could you try something like this:

```
import PouchDB from 'pouchdb';
import PouchdbFind from 'pouchdb-find';

 PouchDB.plugin(PouchdbFind);
```

**Comment by antonyRoberts** [comment]
@garrensmith That does not change anything unless you change the index.d.ts file for Pouch to
>declare module 'pouchdb' { 
    const plugin: PouchDB.Static; 
    export default plugin;
}

**Comment by antonyRoberts** [comment]
```
var PouchDB = require('pouchdb').default
PouchDB.plugin(require('pouchdb-find'));
PouchDB.adapter('socket', require('socket-pouch/client'));
```
@michael42 suggestion for, https://github.com/pouchdb/pouchdb/issues/6615#issuecomment-318453778 var PouchDB = require('pouchdb').default  is the only thing to work with plugins and adapters, with the current state of @types for pouchDB

**Comment by antonyRoberts** [comment]
Update: The new version of @types for pouchdb resolves this issue

**Comment by tbolis** [comment]
Hello @antonyRoberts I'm facing this problem can you be more specific with the update you mention that @types for pouchdb resolves this? thank you!

**Comment by vinz243** [comment]
@antonyRoberts please explain

**Comment by webnoob** [comment]
@antonyRoberts Same here please.

**Comment by wormling** [comment]
In Ionic 3.9.2/Angular 5.0.1 the following works for me:

```
import * as PouchDB from 'pouchdb/dist/pouchdb';
PouchDB.plugin(require('pouchdb-find').default);
PouchDB.plugin(require('pouchdb-live-find'));
PouchDB.plugin(require('pouchdb-upsert'));
```

Related portions of package.json:

```
  ... 
  "devDependencies": {
    ...
    "@types/pouchdb": "6.3.1",
    "@types/pouchdb-find": "6.3.0",
    "@types/pouchdb-upsert": "2.2.1",
    ...
    "pouchdb": "6.3.4",
    "pouchdb-adapter-cordova-sqlite": "2.0.2",
    "pouchdb-find": "6.3.4",
    "pouchdb-live-find": "0.4.0",
    "pouchdb-promise": "6.3.4",
    "pouchdb-upsert": "2.2.0",
```

**Comment by ShadowManu** [comment]
We have a project with `webpack` and typescript and we ended up doing 'dirty-fixing' the `import` and `plugin` calls. If it works for anyone, this is what we did:

```
import * as rawPouch from 'pouchdb';
import * as rawFind from 'pouchdb-find';
import * as rawUpsert from 'pouchdb-upsert';

const Pouch: PouchDB.Static = (rawPouch as any).default;
const find: PouchDB.Plugin = (rawFind as any).default;
const upsert: PouchDB.Plugin = (rawUpsert as any);

Pouch.plugin(find);
Pouch.plugin(upsert);
```

**Comment by vinz243** [comment]
I recommend using the flag tho, works like a charm and is by far the cleanest

**Comment by brice-prunier-dev** [comment]
Thanks @ShadowManu your trick saved me : I've been struggling with this for more than a week.
@vinz243 i also tryed your setting in  tsconfig but it didn't work (_FYI "moduleResolution": "node", "target": "es5".."lib": [ "es2017",   "dom" ]_). 

As many i plan to work on the bundle **angular/angular-cli+webpack/pouchdb/typescript+@types** so it will be great to have a clear answer on why module export is not working on pouchdb with angular-cli+webpack. 
@ShadowManu trick is very helpfull on short term but i would like a cleanner solution for long term.

**Comment by ShadowManu** [comment]
Sure. Not the clean solution we woul like as final, but this helps on making explicit there are problems with the module systems on Pouch packages. At the moment, it seems webpack recognizes the newest `pouchdb` and `pouchdb-find` packages with ES6 default exports and `pouchdb-upsert` as a CommonJS package.

**Comment by ptitjes** [comment]
@ShadowManu @brice-prunier-dev, I believe the correct way to do it is:
```js
import PouchDB from 'pouchdb';
import PouchFind from 'pouchdb-find';
PouchDB.plugin(PouchFind);
```

Well that's how I do it for months in my Ionic3/Angular5 + TypeScript app (the bundling uses Webpage) and that works perfectly without glitches.

**Comment by ShadowManu** [comment]
Indeed, if those are the current recognized exports, that will work too, since both ways are basically equivalent. The problems are, however:

* Those exports doesn't seem stable, they were different in <6.3 and we weren't understanding why. Our way is a deliberate code explanataion that the exports have some issues.
* Typings are not in sync with these changes, and anyway it may be hard to get it right from version to version.

**Comment by ptitjes** [comment]
@ShadowManu, I believe the problem was not coming from PouchDB but from the typings (which are not maintained by the PouchDB community) and the way Ionic app are bundled with Webpack. You should stick to the way I showed above because differences of module packaging is what Webpack is supposed to resolve. Indeed, by explicitly dereferencing 'default', you will be bothered again if the packaging changes again.

**Comment by ShadowManu** [comment]
It's not simply about the typings. The runtime itself is wrong. The typings is just the tip of the iceberg.
