### ISSUE TITLE
How much data can PouchDB store?

### ISSUE THREAD

**Issue by sm2017** [pouchdb/pouchdb#6661]
I see https://pouchdb.com/faq.html#data_limits before but the question is "Is these limit per database or not"

> In Firefox, PouchDB uses IndexedDB. Though Firefox has no upper limit besides disk space, if your application wishes to store more than 50MB locally, Firefox will ask the user using a non-modal dialog to confirm that this is okay.

If my application has 10 databases , The 50MB limitation before user confirmation is for all 10 databases or not , if I have 10 databases each hast 49MB data there is no confirmation needed

**Comment by sm2017** [comment]
Any idea?

**Comment by sm2017** [comment]
Help please

**Comment by KlausTrainer** [comment]
Hi!

Those limits generally apply on a per-origin (i.e. scheme, host name, and port) basis.

But note that some additional limits may apply. For instance, Firefox also imposes a global and a so-called group limit: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria

**Comment by KlausTrainer** [comment]
Also note that the exact numbers and the behavior we specified in the FAQ may be out of date, as this is an area where some browser vendors are currently actively working on.

Please feel free to suggest updates or other improvements to our documentation, e.g. by making a pull request to this document: https://github.com/pouchdb/pouchdb/blob/master/docs/faq.md :)

**Comment by sm2017** [comment]
What about none-browser environments?

**Comment by daleharvey** [comment]
Non browser environments rarely enforce a limit, either way the limit is enforced by the storage engine and not pouchdb itself, pouchdb gives no limits to what can be stored
