### ISSUE TITLE
Design pattern

### ISSUE THREAD

**Issue by sm2017** [pouchdb/pouchdb#6662]
Is `database` in pouchdb equivalent to `table` in sql?

In other words if in sql we have `author` , `profile` and `post` tables , What is the recommended pattern in pouchdb ? We must create  `author` , `profile` and `post` databases ? or just one `main` database and put documents on it? how?

Another question is , If I have `author` field in `post` documents , and always I filter `author` , in other words ALWAYS I want to get all posts from specific author , is it better to create separate database for each author 
`post_1` for author 1 , `post_2` for author 2 ,... and use `allDocs()` or create a single `post` database and use Mango queries to filter author 

```js
db.createIndex({
  index: {fields: ['author']}
});
db.find({
  selector: {
    author: {$eq: 1}
  }
});

```

**Comment by garrensmith** [comment]
@sm2017 a database in pouchdb is the same as a database in sql world. So for `author`, `profile` etc you would create one database and create docs for `author`, `profile` etc. It might be a good idea to create a `type` field on each document. e.g `type: `author`. Then you can get better filtering when you do queries.

In terms of your second question. Its best to actually test your use case and design. Database per author will work nicely but keeping them all in one database will also work depending on how many docs you have.

**Comment by sm2017** [comment]
@garrensmith Can you compare `allDocs` (Each document type has their own database) and `Mango queries` that filter `type` (One database and each document has a `type` field)?
I just need a rough role of thumbs , Can you compare the performance , for example `Mango queries` has 10% less performance

**Comment by garrensmith** [comment]
Mango is just nice syntactic sugar on top of map-reduce. For pouchdb often the fastest queries are when you use `allDocs`. So combining pouchdb-find with `allDocs` will give you a pretty decent query performance. But  you going to have to try it out for your use case. 

For CouchDB it is better to create indexes, and use mango to query those indexes.
