### ISSUE TITLE
Replication since options not working as expected

### ISSUE THREAD

**Issue by andresmijares** [pouchdb/pouchdb#6663]
### Issue
I'm trying to replicate to the local db, however, since my docs are huge, I cannot use all_docs when replicating, I took a look at the docs and found that the sync option uses a `since` option, however, it's not clear enough for me how this supposes to work, i need to count by the number of docs, not the change sequences.

Can i work like, sync something `since` 3 months ago? or what is the best way to manage this? maybe since this is a `allDocs` operation, can I set a limit in here? I'm just doing a basic:

```javascript
localDB.sync({
   live: true,
   retry: true,
})
```

**Comment by willholley** [comment]
@andresmijares. It's probably worth reading an overview about how replication works - http://docs.couchdb.org/en/2.0.0/replication/intro.html is a good one. Essentially, CouchDB/PouchDB exposes an endpoint - `_changes` which returns a set of documents that have changed. It's important to note that this is a set - the order is not guaranteed - and it is a set of documents and not a set of changes. For example, if a document changes multiple times, it might only appear in the set once.

Each result from `_changes` is associated with a sequence value (the `seq` field). This is like a bookmark - it can be passed as a parameter to subsequent `_changes` requests to continue from where the previous response ended. Again, `_changes` isn't fully ordered so this doesn't guarantee anything about *when* the documents changed - simply that they have changed and that the replicator should compare the results against any local copies.

If you want to only sync documents that are < 3 months old, you could use a [filtered replication](https://pouchdb.com/api.html#replication) - using a `selector` is provides the best performance -
 assuming you have a timestamp in your documents that could be used to filter against. Note that if you change the filter criteria / selector, the replication needs to re-evaluate all the documents in the database against the new selector. Another strategy would be to partition your documents on the server into time-based databases (e.g. database per month) and replicate only those months you need.

**Comment by andresmijares** [comment]
thank u for answer, i will try with the filters since the sequence numbers definitively dont match my use cases.
