### ISSUE TITLE
Online-deleted documents are recreated by offline devices when being edited offline

### ISSUE THREAD

**Issue by daweedm** [pouchdb/pouchdb#6666]
### Issue
Online-deleted documents are recreated by offline devices when being edited offline

### Info
- Environment: hybrid app
- Platform: All
- Adapter: Default
- Server: CouchDB

### Reproduce
Taking two devices, the first one is online, the other one is offline. They have exactly the same local database (freshly synced).

I delete the document A from the device being online.
I edit the same document from the offline device and save it (always being offline).

When the offline device come back online, the document A is recreated although it should be ignored since the online device deleted it. (The revision number is not reset)

Shouldn't putting a document (with a rev number higher than 1) having no history in database be forbidden and so ignored by the replication process ? What am I missing ?
Thanks for your help

**Comment by daweedm** [comment]
I've done some tests and I have neither _deleted flag when getting the "deleted revision" nor any conflict on the affected document

**Comment by daweedm** [comment]
Same as #4932

**Comment by daweedm** [comment]
The solution in #4932 doesn't really help me, I think we should be informed when this kind of "conflict" happens

**Comment by willholley** [comment]
@daweedm to understand why this happens, you'll likely need to read a bit of background about how documents are represented in Couch/Pouch - http://docs.couchdb.org/en/2.1.0/replication/conflicts.html has a comprehensive overview.

In short, it sounds like you have the following scenario. 2 devices have the same db which contains a document which both are editing. Device a is online, device b is offline. The sequence of operations and resulting revision trees for the document would be:

1. Initial sync. Documents are in the same state. Let's assume it's at revision 1:
```
device a: {rev-1}
device b: {rev-1}
```

2. device a deletes the document:
```
device a: {rev-1}->{rev-2a, deleted}
device b: {rev-1}
```

3. device b edits the document
```
device a: {rev-1}->{rev-2a, deleted}
device b: {rev-1}->{rev-2b}
```

4. device b comes online. Both devices sync.
```
device a: {rev-1}->{rev-2a, deleted}
                           ->{rev-2b}
device b: {rev-1}->{rev-2a, deleted}
                           ->{rev-2b}
```
Non-deleted versions are preferred to deleted versions, so `rev-2b` trumps `rev-2a` and so the document appears to have been re-created to device a.

This is intended, though potentially unintuitive, behaviour and there are many documented strategies for handling conflicts. Resolving conflicts on the clients can be a little problematic (see discussion #4642), so it's best to resolve them on the server if possible. If you expect conflicts to be generated regularly, you might investigate using immutable documents instead.

**Comment by daweedm** [comment]
@willholley Thanks for your help
