### ISSUE TITLE
How can I put a new Document with _REV?

### ISSUE THREAD

**Issue by darshantejani007** [pouchdb/pouchdb#6667]
Hi,
I am trying to create a new Document in my local pouchdb. 
The trick here is, I want to provide my own _rev id, so that in future, when I sync this local db with remote db, it won't cause any problem.
Currently it throws "document update conflict" if I provide _rev while creating new document.
So is there any way I can approach this issue? Any help would be appreciated.

**Comment by willholley** [comment]
@darshantejani007 you can use the `force` option when PUTting a document to use your own rev. However, providing your own revs can lead to unexpected behaviour - what problems are you anticipating with the default UUID revs that Pouch generates?

**Comment by darshantejani007** [comment]
Well, I was manually GETting some documents from another remote `couchdb` and trying to put them in my Local pouchdb with same `_rev`. So that after this step, I can keep both these DBs in sync (since the docs have same _REV id). That was my use-case. Nonetheless I am now approaching this use-case using `doc_ids`. Thanks anyways, it helped.

**Comment by karlwestin** [comment]
It seems to me that this was resolved so I'm closing. Cheers!
