### ISSUE TITLE
Not able to import pouchdb in angular4

### ISSUE THREAD

**Issue by ali4ever4** [pouchdb/pouchdb#6672]
### Issue
Not able to import pouchdb in angular4
running ng serve in angular cli (that should compile the typescripts and make the page run) gives the error 

when using pouchddb
> Cannot find module 'pouchdb'.   webpack: Failed to compile.
and when using pouchdb-browswer

> Cannot find module 'pouchdb-browser'. webpack: Failed to compile.

### Info
- Environment: browswer
- Platform: chrome

### Reproduce
1- install angular cli 
npm install angluar-cli -g

2- create angular project 
ng new project

3- in the project install pouch
either
npm install pouchdb --save
or 
npm install pouchdb-browser --save

in the code import pouch db

tried all these  but all gave the same error

import PouchDB from 'pouchdb';
import PouchDB from 'pouchdb-browser';
import * as PouchDB from 'pouchdb-browser';
import * as PouchDB from 'pouchdb';

### Note
installing @ types/pouchdb  don't help infact it gives more compilation errors

**Comment by garrensmith** [comment]
`npm install pouchdb-browser --save`

and 
`import PouchDB from 'pouchdb-browser'; 

Should be all you need.

**Comment by ali4ever4** [comment]
Dear Garrensmith  thanks i tried that but


still getting


```
ERROR in C:/Users/aallawati/Development/pro1/src/app/dbtool.service.ts (3,21): Cannot find module 'pouchdb-browser'.

ERROR in C:/Users/aallawati/Development/pro1/src/app/dbtool.service.ts (3,21): Cannot find module 'pouchdb-browser'. webpack: Failed to compile.
```

**Comment by garrensmith** [comment]
That looks like a typescript error. I’m not familiar with how typescript works.

**Comment by ali4ever4** [comment]
I tried to import pouchdb in plain typescript and compile it with tsc and that worked perfectly fine 

I guess the issue is with angular-cli or webpack 
But the resolution should be done from pouchdb or angular-cli?

**Comment by luanmm** [comment]
I don't have a clue in what is going on with PouchDB + Angular, but it's really messy. When I am able to compile the code, I'm unable to run it. Even with the "new import", it just doesn't works.

**Comment by luanmm** [comment]
@ali4ever4 I was able to work with PouchDB + Angular 4 after some work efforts. Unfortunately, I ended up discovering that a plugin that I used was messing up a lot of things (WorkerPouch, in my case).

The following steps should help you get things working:
- `npm install pouchdb --save` (to install version 6.3.4, as of today)
- `npm install @types/pouchdb --save-dev` (to install version 6.3.0, as of today)
- `import PouchDB from 'pouchdb';` (to import it in your Angular components)

I couldn't get it working using the 'pouchdb-browser' module as stated by @garrensmith and others here (in other issues). I think the main reason for this is because this package is not updated in npm registry and/or doesn't have updated typings.

Good luck in your project!

**Comment by ali4ever4** [comment]
Hello @luanmm 

thanks for you help
but for me once i add  @ type/pouchdb

i get  errors a lot of them , this is just few lines from them 


```
ERROR in C:/Users/aallawati/Development/pro1/node_modules/@types/pouchdb-core/index.d.ts (765,30): Cannot find namespace 'Core'.

ERROR in C:/Users/aallawati/Development/pro1/node_modules/@types/pouchdb-core/index.d.ts (766,37): Cannot find namespace 'Core'.

ERROR in C:/Users/aallawati/Development/pro1/node_modules/@types/pouchdb-core/index.d.ts (767,40): Cannot find namespace 'Core'.

ERROR in C:/Users/aallawati/Development/pro1/node_modules/@types/pouchdb-core/index.d.ts (768,33): Cannot find namespace 'Core'.

ERROR in C:/Users/aallawati/Development/pro1/node_modules/@types/pouchdb-core/index.d.ts (771,30): Cannot find namespace 'Core'.

ERROR in C:/Users/aallawati/Development/pro1/node_modules/@types/pouchdb-core/index.d.ts (772,37): Cannot find namespace 'Core'.

ERROR in C:/Users/aallawati/Development/pro1/node_modules/@types/pouchdb-core/index.d.ts (773,41): Cannot find namespace 'Core'.

ERROR in C:/Users/aallawati/Development/pro1/node_modules/@types/pouchdb-core/index.d.ts (776,30): Cannot find namespace 'Core'.

ERROR in C:/Users/aallawati/Development/pro1/node_modules/@types/pouchdb-core/index.d.ts (777,37): Cannot find namespace 'Core'.

ERROR in C:/Users/aallawati/Development/pro1/node_modules/@types/pouchdb-core/index.d.ts (778,33): Cannot find namespace 'Core'.


```

**Comment by ali4ever4** [comment]
OMG i can't believe this.
All my issue was because of CLI verson i was using angular-cli  
the one you get by 
` npm install angular-cli -g`
i.e. version 1.0.0 

Just now i changed to @angular/cli instead of angular-cli 
so i got version 1.2.7

and it is working perfectly fine with pouchdb now

**Comment by luanmm** [comment]
Nice, @ali4ever4. Angular CLI has been updated constantly, so it has a lot of impact in this kind of building operation indeed.

Happy that you could get your project working!

**Comment by priyabratap** [comment]
Hi All,
I am facing the same issue and tried all of your suggested solutions, but It does not work at all.

The pouchdb.js file is not coming at all with these bundles (vendor.bundle.js, main.bundle.js,inline.bundle.js)

I am using below things and tried all commented code also

"@angular/cli": "1.4.7",
"pouchdb": "^6.3.4",

app.module.ts
import { PouchDB } from 'pouchdb';
//import PouchDB from 'pouchdb';
//import PouchDB from 'pouchdb-browser';
//import * as PouchDB from 'pouchdb-browser';
//import * as PouchDB from 'pouchdb';

my.service.ts
import { PouchDB } from 'pouchdb';
//import PouchDB from 'pouchdb';
//import PouchDB from 'pouchdb-browser';
//import * as PouchDB from 'pouchdb-browser';
//import * as PouchDB from 'pouchdb';

Could you please guide me or paste your sample code?

**Comment by brice-prunier-dev** [comment]
Hi,

I'm facing the same issue as@priyabratap with : Angular@4.4.4, angular/cli@1.4.9 and pouchdb@6.3.4 using @types/pouchdb:
_import * as PouchDB from 'pouchdb-browser';
or 
import * as PouchDB from 'pouchdb';_
works at compile  but when i launch the app the pouchdb module is missing...

I solved the problem by falling back to pouchdb@6.2.0. what is not a long term solution for me.

Does someone have project running with 
Angular@4.4.4, angular/cli@1.4.9 and pouchdb@6.3.4 using @types/pouchdb...

Thank for your help.

**Comment by big-r81** [comment]
Hi,

today running into the same problem after creating a new project.
Did you use Lazy Loading for your pages?
Hi,

in my old projects (ionic) I always used `import { PouchDB } from 'pouchdb';` and today i changed it to `import PouchDB from 'pouchdb';` and it works again. Very strange. Maybe it is a lazy loading "problem", but this is only a guess.

**Comment by daleharvey** [comment]
Closing out typescript bugs, we do not use typescript for this repo and if typescript projects cant use other javascript projects then I would suggest that they fix that

**Comment by brice-prunier-dev** [comment]
With all the respect that i have for **Pouchdb** team. 
It is from my point of view a bad move: **Typescript** means **Angular** what means a large scope off potential **Pouchdb** user. Making **Pouchdb** more **Typescript** compliant is a feature you should think about.
Anyway good continuation to **Pouchdb** team.

**Comment by priyabratap** [comment]
Hi All,

I got the solution and it's working fine with angular 4

- I have added this line **_"scripts": ["../node_modules/pouchdb/dist/pouchdb.js"]_** in /var/www/html/angular4/**.angular-cli.json**

```
      "styles": [
        "styles.css"
      ],
      "scripts": ["../node_modules/pouchdb/dist/pouchdb.js"],
      "environmentSource": "environments/environment.ts",
```

-  Created a Service file for poucdb communication

/var/www/html/angular4/src/app/services/pouchdb.service.ts

```
import { Injectable, EventEmitter } from '@angular/core';
import PouchDB from 'pouchdb';

@Injectable()
export class PouchdbService {
	private isInstantiated: boolean;
	private db:any;
	private listener: EventEmitter<any> = new EventEmitter();
	constructor() {
		if(!this.isInstantiated) {
	            this.db = new PouchDB('http://localhost:5984/aaki');
	            this.isInstantiated = true;
	        }
		
		this.db.info().then(function (result) {
			console.log(result);
		}).catch(function (err) {
			console.log(err);
		});
	}
	public fetch() {
		return this.db.allDocs({include_docs: true});
	}

	public get(id: string) {
		return this.db.get(id);
	}
	public sync(remote: string) {
		let remoteDatabase = new PouchDB(remote);
		this.db.sync(remoteDatabase, {
		    live: true
		}).on('change', change => {
		    this.listener.emit(change);
		}).on('error', error => {
		    console.error(JSON.stringify(error));
		});
	}

	public getChangeListener() {
		return this.listener;
	}
}
```

I hope it will help to all. I am very happy to be part of this discussion.

**Comment by juangabreil** [comment]
Not very clean but I solved it by doing:

import * as $PouchDB from 'pouchdb';
const PouchDB = $PouchDB['default'];

and then work normally.

**Comment by alex-schmitt** [comment]
Add  `{ "allowSyntheticDefaultImports": true } ` to tsconfig.json

Then use `import PouchDB from 'pouchdb;`
