### ISSUE TITLE
API docs defaults section: wrong name for db

### ISSUE THREAD

**Issue by patriciagarcia** [pouchdb/pouchdb#6676]
### Issue
From the [Default settings](https://pouchdb.com/api.html#defaults) section of the API

```js
var HTTPPouch = PouchDB.defaults({
  prefix: 'http://example.org'
});

// db will be located at 'http://example.org/testdb'
var myHttpPouch = new HTTPPouch('dbname');
```

It seems that comment should read: `db will be located at http://example.org/dbname'`

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/c1cd67e74416430ca67a941283104eccaa99a56f, thanks so much
