### ISSUE TITLE
Translate the docs

### ISSUE THREAD

**Issue by jorgeluisrezende** [pouchdb/pouchdb#6679]
I've been thinking. Are you able to translate the docs to Brazilian Portuguese?

**Comment by mnewmedia** [comment]
We already had this discussion and the outcome was, that we currently have not enough manpower to support Internationalization. 

You can read more about it at #3112.

**Comment by jorgeluisrezende** [comment]
What if, can i help tô translate tô pt-br

Em 11 de ago de 2017 11:44, "Pablo Maurer" <notifications@github.com>
escreveu:
