### ISSUE TITLE
Cookie credentials remote db ignored

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [pouchdb/pouchdb#6683]
### Issue
I have an electron app, I managed to login to couchdb with cookie auth.
I also manage to retrieve the correct session. I used the `fetch` api so far to handle the requests.
For cookie storage in electron I use `electron-cookies` and this is working, if I do a get request with `credentials: 'include'` and `'withCredentials' : true` options it makes the request with the cookie.
Whenever a user is created a corresponding database is created too with the new user being the admin of the database. So far so good.

However, if I try to connect to the remote DB with PouchDB this does not work, I get an `unauthorized`.

My guess is that the authentification cookie is ignored somehow.

I tried it the normal way:
```
remoteDB = new PouchDB('http://somecorrecturl/userDBName');
```
and also like this:
```
remoteDB = new PouchDB('http://somecorrecturl/userDBName', {
    ajax: {
      method: 'POST',
      mode: 'cors',
      headers: {
        'Content-Type': 'application/json',
        'withCredentials' : true
      },
      credentials: 'include',
      withCredentials: true,
    }
  });
```
without success.

Is there some special option I have to include? Using the `fetch api` for example I had to add `credentials: 'include'` before it would use the cookie.

Doing the exact same thing with the same auth-cookie but using postman works.
So my bet is that the cookie is ignored by pouchdb.

### Info
- Environment: Node.js / Electron
- Platform: Chromium / Electron
- Adapter: PouchDB
- Server: CouchDB

Thank you for your help!

**Comment by ThibaultJanBeyer** [comment]
Major tom? Is anyone here? :octocat:

**Comment by arpban** [comment]
i am facing the same problem. did you find any solution.

**Comment by ThibaultJanBeyer** [comment]
Unfortunately not... and it doesn’t seem to interest anyone here :(

**Comment by ThibaultJanBeyer** [comment]
So there was a similar issue #6814 which was fixed. That might also fix this issue, I’ll try it again later and close the issue if fixed.

**Comment by ThibaultJanBeyer** [comment]
Unfortunately, this is **NOT** resolved. The issue should be reopened. Otherwise, I’ll create a new one.

**Comment by adrienverge** [comment]
@ThibaultJanBeyer have you tried with PouchDB 7 and:
```js
remoteDB = new PouchDB('http://somecorrecturl/userDBName', {
  fetch: (url, opts) => {
    opts.credentials = 'include';
    return PouchDB.fetch(url, opts);
  },
});
```
?

**Comment by rokgfx** [comment]
I had exactly the same issue with sync. The code by @adrienverge above fixed it.

**Comment by asci** [comment]
for me it does not fixed, cookies simply not sent to couchdb server after succesfull session POST. The only workaround I found is to send creds with every request, which is not ideal from security point of view
