### ISSUE TITLE
Question: how to "best" do a group count?

### ISSUE THREAD

**Issue by spacepope** [pouchdb/pouchdb#6684]
### Issue / Question
I am trying to doing a simple group count over documents by a specific property.
This can be done with map/reduce by creating a design doc with a view map function emitting the property and reduce option set to _count and then query this view with setting query options group and reduce to true.
This is getting complex if one wants to do this dynamically on a specific property: an index hash according to the property name(s) grouped by has to be calculated (like MD5) and then the index has to be created or fetched to query it.

I am normally using pouchdb-find with mango queries, but group counting doesn't seem to be possible - or am i missing something? (the generated design documents at least have reduce already set to _count...)

I thought, i could make use of pouchdb-finds method createIndex() to create the view, but executing pouchdb.query() on an index created by pouchdb-find results in an error "ddoc _design/idx-27dca78ff5f984d6eb7e8547012755d2 has no string view named idx-27dca78ff5f984d6eb7e8547012755d2, instead found object of type: object".
Why are pouchdb-find index design docs not compatible with pouchdb map/reduce view design docs?

### Info
- Environment: Ionic 3.7.0
- Platform: Chrome (ionic serve)
- Adapter: WebSQL (SQLite fallback)
- Server: only local PouchDB
- PouchDB: 6.2.0

### Reproduce
```javascript
db.createIndex({
	index: {
		fields: ["MyFieldToGroupBy"]
	}
}).then((response: any) => {
	// typescript definition doesn't let us know about name property, so we have to cast it as any
	return db.query(response.name, {
		group: true,
		reduce: true
	});
}).then((result) => {
	// not getting a result
}).catch ((err) => {
	// err: ddoc _design/... has no string view named ..., instead found object of type: object
});
```

**Comment by willholley** [comment]
That 'pouchdb-find' utilizes a map/reduce index under the hood is an implementation detail. Aggregations is something various people have been thinking about for _find but it's a difficult problem to solve when you need to cater for different index backends, including pure `_all_docs` (i.e. no index). If your problem is solved with map/reduce, why not just use that?

**Comment by spacepope** [comment]
>If your problem is solved with map/reduce, why not just use that?

I am i fact using that because i don't know another way to do this.
But as i already said, i have to do nearly the same kind of preprocessing as createIndex of pouchdb-find does internally (generating a hash representing the group fields, the code for the map function, doing the views design doc upsert, etc..). And since i noticed that the pouchdb-find generated index docs also had reduce already set to _count, i thought it would be much easier to reuse these and do a normal query() on that. Thats why i asked how to "best" achieve aggregation..
I still don't get why those two are not compatible (or to be more precise: how does pouchdb-find works using some kind of index design document which differs from the api description of pouchdb map/reduce?)

I don't know who has done some kind of empircal research on query language use cases, but you should consider getting rid of the subclause in the following map/reduce documentation paragraph:
>Finally, it's important to understand that Mango queries are much easier to use than map/reduce queries, **and they can usually satisfy 99% of use cases**.

If aggregation cannot be done with Mango queries, the 99% is a silly number..
