### ISSUE TITLE
Pouchdb doesn't replicate running phonegap desktop on an android phone but works fine on Chrome.

### ISSUE THREAD

**Issue by rdsgi** [pouchdb/pouchdb#6689]
<!--
     Hello! 
I'm having a problem with the Phonegap app i'm using to test PouchDB and CouchDB as a server DB for replication. The app is not working when I use the Phonegap Desktop app and run the app on my android phone ut works when I run it on chrome or the NOX emulator. I added a delete DB button to destroy the DB and a sync button to retrieve it from the CouchDb server. Again on the android phone it now gives an error:
 "error: {"status":0,"name":"Error","message":""}  
but on the chrome it reloads the DB fine. Here is the code for the app:
--------------------------------------------------------------------------------------------------------------------
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="msapplication-tap-highlight" content="no" />
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />
<meta http-equiv="Content-Security-Policy" 
          content="default-src * http://* 'self' data: gap: ws: https://ssl.gstatic.com 'unsafe-inline' 
            'unsafe-eval; 
            style-src * 'unsafe-inline'; 
            script-src * 'unsafe-inline' 'unsafe-eval'; 
            media-src *;
            connect-src * 'self' http://* blob: data:;
            img-src * data:;" />    <title>PouchDB</title>
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript" src="pouchdb-6.3.4.min.js"></script>
   
    <script>
        var db = new PouchDB('product');
        var remotedb = new PouchDB("http://192.168.1.114:5984/product");
        db.replicate.from(remotedb).on('complete', function () {
                             }).on('error', function (err) {
                                   console.log('error: ' + err)
                                   });
        console.log("replication done");
        
        
        function addProduct( ) {
            var upc   = $('#upcCode').val();
            var prod = $('#prodNum').val();
            var desc = $('#description').val();
        var updt = new Date();
        var jprod = {
            _id: upc,
            product: prod,
            proddesc: desc,
            lastupdate: updt
            };
            db.put(jprod, function callback(error, result)  {
                if (!error) {
                    clearfields();
            document.getElementById("message").innerHTML =
                "Product added successfully";
                }
        });
        }
        function clearfields() {
            $('#upcCode').val('');
            $('#prodNum').val('');
            $('#description').val('');
        }
        function showprods() {
            db.allDocs( {include_docs: true, ascending: true},
            function(err, doc) {
                showTableOfProds(doc.rows);
            });
        }
        function showTableOfProds(data){
            var div = document.getElementById("message");
            var str = '<table border="1" align="left"><tr><th>UPC</th>'+'<th>Product</th>'+
            '<th>Description</th></tr>';
            for(var i=0; i<data.length; i++) {
                str += "<tr><td>"+data[i].doc._id+
                            "</td><td>"+data[i].doc.product+
                            "</td><td>"+data[i].doc.proddesc+"</td></tr>"
            }
            str += "</table>";
            div.innerHTML = str;
        }
        function deletedb() {
            db.destroy().then(
            function(response) {
                return alert("db Deleted:" + response);
            }).catch(function(err) {
                alert("error deleting: " + err);
                 })
        }
        function syncdb() {
            db.replicate.from(remotedb).on('complete', function () {
                console.log("sync successfull");
                }).on('error', function (err) {
                    console.log('error: ' + err)
           });
            console.log("sync complete");
         }

  </script>
    
</head>

<body>
    <div class="app">
        <h1>PouchDB</h1>
        <div id="deviceready" class="blink">
            <p class="event listening">Connecting to Device</p>
            <p class="event received">Device is Ready</p>
        </div>
    </div>
        <form name="productform">
        <input type="text" id="upcCode" />UPC Code<br/>
        <input type="text" id="prodNum" />Product No<br/>
        <input type="text" id="description" />Description<br/>
        <input type="button" value="Add Product" onClick="addProduct()" />
        <input type="button" value="Show Product" onClick="showprods()" />
        <input type="button" value="Delete DB" onClick="deletedb()" />
        <input type="button" value="Sync DB" onClick="syncdb()" />
    </form>
    <div id="message"></div>

</body>

</html>
-----------------------------------------------------------------------------------------------------------
Phonegap Log

undefined Content Security Policy has been added: <meta http-equiv="Content-Security-Policy" content="default-src * gap: ws: https://ssl.gstatic.com;img-src * 'self' data: content:;style-src 'self' 'unsafe-inline' data: blob:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">
undefined Content Security Policy has been added: <meta http-equiv="Content-Security-Policy" content="default-src * gap: ws: https://ssl.gstatic.com;img-src * 'self' data: content:;style-src 'self' 'unsafe-inline' data: blob:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">
200 /__api__/appzip
200 /socket.io/socket.io.js
200 /socket.io/?EIO=3&transport=polling&t=LtNBKFi
200 /socket.io/?EIO=3&transport=polling&t=LtNBKGr&sid=I5Bi3-ZOC_dfS7aaAAAL
 replicateion done
200 /socket.io/?EIO=3&transport=polling&t=LtNBKPK&sid=I5Bi3-ZOC_dfS7aaAAAL
200 /socket.io/?EIO=3&transport=polling&t=LtNBKPO&sid=I5Bi3-ZOC_dfS7aaAAAL
 error: {"status":0,"name":"Error","message":""}
 sync complete
 error: {"status":0,"name":"Error","message":""}
 sync complete
 error: {"status":0,"name":"Error","message":""}

**Comment by shmendo** [comment]
I'm not a developer on this project but you should consider reading what it says in the box when you clicked `new issue`. here it is in case you ever want someone to even consider investigating the bug you reported.

### Issue
Write the description of the issue here

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

### Reproduce
Write the steps for others to reproduce issue here. Providing a code example, links to a repository or a live example (JSBin etc) are even more helpful.

**Comment by rdsgi** [comment]
I resolved the issue. I had not opened the ports on the firewall so the local replication worked but when it ran on the phone the firewall was blocking the replication.....Thanks.
