### ISSUE TITLE
Link in Get Started Guide isn't up-to-date

### ISSUE THREAD

**Issue by AngeloKai** [pouchdb/pouchdb#6690]
### Issue
The link in the Get Started Guide should be "//cdn.jsdelivr.net/pouchdb/6.2.0/pouchdb.min.js" instead of "//cdn.jsdelivr.net/pouchdb/6.3.4/pouchdb.min.js". The latter is reported as not found.

**Comment by jimaek** [comment]
This is the correct new link http://cdn.jsdelivr.net/npm/pouchdb@6.3.4/dist/pouchdb.min.js

**Comment by AngeloKai** [comment]
The markdown file appears to be doing the right thing: https://github.com/AngeloKai/pouchdb/blob/master/docs/getting-started.md. But the website doesn't seem to render correctly.

**Comment by daleharvey** [comment]
Was fixed in https://github.com/pouchdb/pouchdb/commit/4f383772d7e4a205cc4912a19bf36c289d54abc2 but hadnt published the site yet, published now, thanks
