### ISSUE TITLE
Uncaught TypeError: PouchDB is not a constructor(…) using PouchDB 6.3.4

### ISSUE THREAD

**Issue by PadaliaRushabh** [pouchdb/pouchdb#6692]
### Issue
Getting error Uncaught TypeError: PouchDB is not a constructor(…) using PouchDB 6.3.4

```
bootstrap.js?5e63:21Uncaught TypeError: PouchDB is not a constructor
    at eval (eval at <anonymous> (http://192.168.42.204:8000/js/app.js:860:1), <anonymous>:21:13)
    at Object.<anonymous> (http://192.168.42.204:8000/js/app.js:860:1)
    at __webpack_require__ (http://192.168.42.204:8000/js/app.js:20:30)
    at eval (eval at <anonymous> (http://192.168.42.204:8000/js/app.js:1674:1), <anonymous>:8:1)
    at Object.<anonymous> (http://192.168.42.204:8000/js/app.js:1674:1)
    at __webpack_require__ (http://192.168.42.204:8000/js/app.js:20:30)
    at http://192.168.42.204:8000/js/app.js:64:18
    at http://192.168.42.204:8000/js/app.js:67:10
```

### Info
- Environment: (browser)
- Platform: (Chrome/FireFox.)

### Reproduce
Install pouchDB@6.3.4 using NPM and init PouchDB object
```
var PouchDB = require('pouchdb-browser');
window.db = new PouchDB('my_db');
```

**Comment by willholley** [comment]
@PadaliaRushabh can you try `import PouchDB from 'pouchdb'`?

**Comment by rasdaniil** [comment]
Same story on node.js :-(

![image](https://user-images.githubusercontent.com/24467138/29534130-8483017e-86bd-11e7-9504-9c93d6dac909.png)

**Comment by rasdaniil** [comment]
For some reason now only importing as 
`const PouchDB = require('pouchdb');`
works for me 

https://stackoverflow.com/questions/45805307/pouchdb-typeerror-pouchdb-1-default-is-not-a-constructor

**Comment by hungle88** [comment]
I'm using PouchDB for an Electron app and I ran into this problem today as well. 

**Package.json**

```
"electron": "^1.7.8",
"pouchdb": "^6.3.4",
"pouchdb-browser": "^6.3.4",
"webpack": "^3.6.0",
"webpack-dev-server": "^2.9.0"
```

**Code**

```
const PouchDB = require('pouchdb-browser');
const db = new PouchDB('my_db');
```

The strange thing is everything was fine when I was developing the app with `electron-prebuilt-compile` (follow suggestion from the Slack folks) but then when I decided to switch to Webpack this error suddenly appear

<img width="443" alt="screen shot 2017-09-28 at 16 01 19" src="https://user-images.githubusercontent.com/2544327/30958108-5a1f4fde-a466-11e7-8b17-d857d7d03a64.png">

**Comment by hungle88** [comment]
I [followed this instruction](https://github.com/react-boilerplate/react-boilerplate/issues/1714#issuecomment-316163368) to use an older version of PouchDB and everything is now working as expected:

```
yarn add pouchdb-browser@6.2.0
```
or

```
npm install pouchdb-browser@6.2.0 --save --save-exact
```

My code is still like this though

```
const PouchDB = require('pouchdb-browser');
const db = new PouchDB('my_db');
```

Hope this helps!

**Comment by socialcode-rob1** [comment]
I am was seeing the same issue while building an Electron/Angular app.

First it was hidden by StoreDevtools.  I was seeing a ..
`
Uncaught (In Promise)".
`

After disabling StoreDevtools  I received the 
`
Uncaught TypeError:  PouchDB is not a constructor 
`

It was resolved by reverting back to pouched-browser@6.2.0

**Comment by LordAlastair** [comment]
I was able to solve this problem by following the steps below:
npm install --save @types/node
npm install --save @types/pouchdb

in tsconfig.app.json file add those lines: 
    "types": [ "node" ],
    "typeRoots": [ "../node_modules/@types" ],

**Comment by daleharvey** [comment]
Sounds like various problems being reported in various other libraries here, closing this out

**Comment by elhenro** [comment]
I am also getting the same error in Angular 4. @LordAlastair 's fix didnt work for me..

**Comment by ptitjes** [comment]
@elhenro Can you try that : https://pouchdb.com/guides/setup-pouchdb.html#typescript

**Comment by elhenro** [comment]
@ptitjes thank you, that worked! :)

**Comment by madcorp206** [comment]
Had the same problem and solved it with this : 
`const PouchDB = require('pouchdb').default;`

**Comment by fugroup** [comment]
Both `import PouchDB from 'pouchdb'` and what @madcorp206 said works. Using VueJS.

**Comment by jcpc91** [comment]
this works for me
var PouchDB = require('pouchdb-browser');
------------

let pouchdb = PouchDB.default.defaults();
let db = new pouchdb('mydb');
db.info().then(info => console.log(info));

**Comment by isaaclevi** [comment]
make sure that your json file that you are trying to enter to the database is a valid json. if you did already tried to enter a json file to the database

**Comment by dravenk** [comment]
In polymer 3, this is introduced and used
```
import 'pouchdb/dist/pouchdb';
...
 let db = new PouchDB('db_name');
...
```

**Comment by wayahead** [comment]
I followed the guide at https://pouchdb.com/guides/setup-pouchdb.html#typescript, but "import PouchDB from 'pouchdb'" does not work as the issue described. Here is my env:

npm i pouchdb
npm i -D @types/pouchdb
typescript: 3.1.6
tsconfig.json: target-es2016

BUT the below works:
const PouchDB = require('pouchdb');
let db: any = new PouchDB('movies');

**Comment by BillMeyerRSA** [comment]
Had the same problem - using vue and pouchdb 
 madcorp206  solution seemed to solve it: 
const PouchDB = require('pouchdb').default;

**Comment by frknasir** [comment]
> Had the same problem and solved it with this :
> `const PouchDB = require('pouchdb').default;`

This did it for me...Thank yous!!!

**Comment by Ashersam** [comment]
> Both `import PouchDB from 'pouchdb'` and what @madcorp206 said works. Using VueJS.

this works for the newer version of node
