### ISSUE TITLE
Sync error causes Chrome 401 "Authentication required" popup

### ISSUE THREAD

**Issue by gillez** [pouchdb/pouchdb#6694]
### Issue
Write the description of the issue here
See this previous issue: https://github.com/pouchdb/pouchdb/issues/5534

I am posting this as a new issue as that one is closed as "fixed".  However, I am seeing the exact same issue: when a pouchDB replication to a couchbase-sync-gateway service fails, I get a 401 message in the console and also get the "Authentication required" popup on Chrome.  I don't want to see this popup - how can I catch the 401 error and provide my own error handling?

The issue that I've linked says that this is fixed in v5.4.6.  However, I still see it on v6.3.4

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
Browser
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
Chrome 59.0.3071.115

- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)

IndexedDB

- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

Couchbase Sync Gateway

### Reproduce
Write the steps for others to reproduce issue here. Providing a code example, links to a repository or a live example (JSBin etc) are even more helpful.

See issue description.  Issue is happening during replication when there is an SSL certificate error.

**Comment by willholley** [comment]
@gillez do you know which request generates the 401? You may be able to intercept the response by passing options to request (see the constructor options in https://pouchdb.com/api.html#create_database).
