### ISSUE TITLE
{status: 0, name: "unknown", message: "changes rejected", result: {…}}

### ISSUE THREAD

**Issue by GeorgeAppleton** [pouchdb/pouchdb#6697]
### Issue
Creating a phonegap app I'm trying to sync to my pouchDB localhost. But as soon as I try to run my app it returns the error in the title and points to the line with my db.sync function. The strange thing is that this reports instantly in console even though all of the prior functions in my promise chain haven't run yet. It has been confusing me for most of today.

### Info
- Environment: Browser
- Platform: Chrome
- Adapter: IndexedDB I assume
- Server: CouchDB

### Reproduce
I have no idea how to reproduce this, I'm honestly just rather confused by it

I'm not sure how to be helpful with this but I'll try to reply informatively to any questions.

**Comment by willholley** [comment]
@GeorgeAppleton do you have any details about the network requests made (e.g. network tab in a browser)? Also, you could try replacing `db.sync` with explicit `db.replicate.from` and `db.replicate.to` calls to see which is failing.

**Comment by GeorgeAppleton** [comment]
Hi @willholley , so I'm running a loop which currently only runs twice, this syncs to my customers and products databases (well it should). So what I'm saying is that i was running sync twice, to different databases each time. Originally it was erroring twice, if I change it to replicate.from by itself then it errors twice, but if I change it to replicate from it either doesnt error, errors once, or errors twice. It isn't consistent. The errors are the exact same though.

Looking at the network tab seems to be a bit of a revelation though. Seems like the sync is working anyway despite the errors, it's just taking a long time, so it previously appeared to not be working at all.

**Comment by GeorgeAppleton** [comment]
Checking on PhoneGap server log it seems to actually run in the correct order (dur) just the console seems to report the error before anything else for some reason

**Comment by GeorgeAppleton** [comment]
Found the cause

```
function syncToDB(db,remote) {
	return new Promise ((resolve,reject) => {
		// syncDom.setAttribute('data-sync-state', 'syncing');
		var opts = {live: true};
		console.log("trying to sync to remote: "+remote);
		// db = new PouchDB('test');remote = 'http://localhost:5984/test';
		db.replicate.from(remote, opts, syncError).then(function(){
			console.log("have synced to remote: "+remote);
		});
	});
}
```

I don't know what it is about that but if I replace my use of syncToDB(db,remote) with db.replicate.from(remote,opts,syncError) directly then it works.

**Comment by GeorgeAppleton** [comment]
```
var test = new PouchDB('test');
test.replicate.from('http://localhost:5984/test',{live:false}, syncError)
.on('change', function(info){
	console.log('change: '+info);
})
.on('complete',function(info){
	console.log('complete '+info);
})
.then(function(){
	test.allDocs({include_docs: true, descending: true}, function(err, doc) {
		console.log(JSON.stringify(doc.rows));
		console.log(JSON.stringify(err));
	});
});
```

So to isolate everything, running a test, this still just throws the error {"status":0,"name":"unknown","message":"getCheckpoint rejected with "}

**Comment by GeorgeAppleton** [comment]
Issue solved, having syncError in the replicate.from or sync function breaks it. If you use .on('error',function(err){}); instead then it works perfectly

**Comment by GeorgeAppleton** [comment]
My mistake, works on browser now but not mobile, I'll assume this is an issue with whitelisting or similar though, unlikely to be related to pouchdb

**Comment by avijeetnpi** [comment]
@Shardj : Did you find any solution as I am facing same issue. It works on browser but not on mobile.

**Comment by Shardj** [comment]
@avijeetnpi presumably what I wrote above. This was a long time ago so I don't remember much of it.

> Issue solved, having syncError in the replicate.from or sync function breaks it. If you use .on('error',function(err){}); instead then it works perfectly
