### ISSUE TITLE
Status 0 error

### ISSUE THREAD

**Issue by GeorgeAppleton** [pouchdb/pouchdb#6705]
### Issue
Trying to access my couchDB server remotely from my PhoneGap developer mobile app throws the following error: {"status":0,"name":"Error","message":""}

CORS is enabled, bind_address is set to 0.0.0.0 oh httpd and chttpd, connecting from my browser at localhost works perfectly fine so it's an issue with connecting remotely. The lack of a properly reported error is worrying.

### Info
- Environment: 
- Platform: Android PhoneGap developer app
- Adapter: IndexedDV
- Server: CouchDB

### Reproduce
Try to sync to a remote CouchDB server from a PhoneGap app using either port 5984 or 5986 (with or without auth)

Thanks for any help

**Comment by willholley** [comment]
@GeorgeAppleton do you have a network trace from the client or anything in the CouchDB log? Also be aware that you shouldn't expose 5986 to clients - always use the CouchDB front end interface (5984 by default).

**Comment by GeorgeAppleton** [comment]
@willholley so using a different remote device instead of the mobile I checked the log and network tab, it's timing out after 10 seconds, the question is why.

Then checking the couchDB logs, the problem becomes more clear. Now I feel foolish aha, so I need to add users to the database I'm trying to access.

2017-08-22T08:33:32.666000Z couchdb@localhost emulator -------- Error in process <0.28838.0> on node couchdb@localhost with exit value:
`{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,403}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,378}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,407}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,91}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,187}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,134}]}]}`

**Comment by willholley** [comment]
@GeorgeAppleton nw - I think if you use the CouchDB single node setup wizard in Fauxton it should create those system databases for you.

**Comment by GeorgeAppleton** [comment]
To clarify what you said about ports 5986 and 5984, so should I only have the bind address at chttpd set to 0.0.0.0 and the http bind address should just be 127.0.0.1?

And thanks @willholley I'll give the single node setup a go

**Comment by GeorgeAppleton** [comment]
@willholley yep it set up the system databases for me, what's the best way to create a user and their permissions?

**Comment by GeorgeAppleton** [comment]
@willholley unfortunately I still get the same error, although now the couchdb log is throwing

```
alarm_handler: {set,{system_memory_high_watermark,[]}}
[info] 2017-08-22T09:04:17.725000Z couchdb@localhost <0.52.0> -------- alarm_handler: {clear,system_memory_high_watermark}
```

**Comment by willholley** [comment]
@GeorgeAppleton the 5986 interface is for admin operations (compaction, etc) and doesn't support the full HTTP API exposed over 5984. I suggest asking about the CouchDB error on the couchdb-user mailing list (see http://mail-archives.apache.org/mod_mbox/couchdb-user/).

**Comment by GeorgeAppleton** [comment]
@willholley that's an archive site isn't it? How could I post there

**Comment by willholley** [comment]
@GeorgeAppleton send an email to `user-subscribe@couchdb.apache.org` to subscribe. To post, email `user@couchdb.apache.org`.

**Comment by GeorgeAppleton** [comment]
This is seeming more and more likely to be a couchdb issue instead of pouchdb so I'll close this, although I do think something other than status 0 should be returned if possible
