### ISSUE TITLE
Sync stopped working (pushing modifications) on android.

### ISSUE THREAD

**Issue by brunoreis** [pouchdb/pouchdb#6709]
I opened this issue on pouchdb-react-native project, but it does not seem related to that specific module. 

So I reopened it here. Please let me know where it should really stay:
https://github.com/stockulus/pouchdb-react-native/issues/78

It's very annoying because it fails so silently. 

Most of the required info is there. The adapter is "asyncstorage".

**Comment by froatsnook** [comment]
Were you able to figure out what was going on?  I am also experiencing this issue.  I noticed that it works fine in the simulator but not in release mode on device.  There are some differences in the javascript environment on device and in the simulator.  I'll let you know if I find something.

**Comment by froatsnook** [comment]
@brunoreis I was able to reproduce this bug with [pouchdb-adapter-react-native-sqlite](https://github.com/craftzdog/pouchdb-adapter-react-native-sqlite), so it definitely doesn't have anything to do with the react-native-asyncstorage adapter.

@nolanlawson do you have any pointers on where to dig in the pouchdb code?  Somehow writes are not triggering replication.

**Comment by brunoreis** [comment]
@froatsnook, I did not dig deeper on this yet. I'm indeed working on an app with pouch and RN and I might need to do it soon. I hope this wont be a blocker.

**Comment by froatsnook** [comment]
@brunoreis I was wrong before.  When I switched to pouchdb-adapter-react-native-sqlite, I thought it wasn't working, but it looks like it does work.

When I created my remote database, there was an uncaught exception, because `window.btoa` (or `atob`? don't remember) didn't exist.  So it was failing to sync, but only because my call to `sync` never happened.  After I shimmed in `window.btoa` and `window.atob`, bi-directional sync started working.  So I guess the problem really is with `pouchdb-adapter-asyncstorage` somehow.

I find this all a bit perplexing, because some things were working sometimes (i.e. I have some data despite a new adapter and my Release app always throwing before setting up the sync).  But I think it's because I ran it in Debug on the device, and that's when it got data.

**Comment by daleharvey** [comment]
Yup looks like the correct place for this issue is react-native / asyncstorage adapter, not part of core pouchdb, hope you get it fixed

**Comment by brunoreis** [comment]
@froatsnook, any updates on this one? Are you still using pouch with the sqlite addapter?

**Comment by froatsnook** [comment]
@brunoreis I am using `"pouchdb-adapter-react-native-sqlite": "^1.0.3"` and it is working.  I have polyfilled `process.nextTick`, `window.atob`, and `window.btoa`.  Be sure to `require("react-native")` before requiring other stuff since it does some environment setup.

**Comment by f4z3k4s** [comment]
I also experience issues with `db.sync(remoteDb, { live:true })` with `"pouchdb-adapter-react-native-sqlite": "^1.0.3"` on react-native. Everything works fine (db syncs correctly) if I run the app in debug mode, but as soon as I build a release and try it out, live sync does not work on Android (haven't tried iOS yet). I can see that the `.on('active', ...)` events are firing, but `.on('change', ...)` events are never fired in release. @froatsnook do you have any idea that could help me out? Could you give me a little bit more detail how you made it working? I'd really appreciate any help.

**Comment by froatsnook** [comment]
Hey @f4z3k4s.

Make sure you add the `atob`, `btoa`, and `process.nextTick` shims as I mentioned above.

I'm not sure what else it could be, but here are some other changes I made:

* I gave the database a size of 50MB:

```java
    @Override
    protected List<ReactPackage> getPackages() {
      long size = 50L * 1024L * 1024L; // 50 MB
      com.facebook.react.modules.storage.ReactDatabaseSupplier.getInstance(getApplicationContext()).setMaximumSize(size);
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new RNSqlite2Package()
      );
    }
  };
```

```javascript
const db = new PouchDB(name, { size: 50 });
```

* I sync with retry:

```javascript
db.sync(remoteDB, {
  live: true,
  retry: true,
  batch_size: 100,
});
```

**Comment by f4z3k4s** [comment]
Greetings @froatsnook,

Thanks for the quick answer. I just got back to this project. I did as you mention: 

- I checked my Android settings from your previous answer, I have an almost identical setup
- `import 'react-native'` - the first import in my `app.js`
- I polyfilled `atob`, `btoa` (from this package: https://github.com/davidchambers/Base64.js/ ) and `process.nextTick` (with `setImmediate`) - although I logged the original values out in release environment and none of those were `undefined`.

Sync is still not working in release, although I noticed this error, which is unfortunately not that verbose and I only get it in release mode, at `db.sync(remoteDb, { live:true }).on('error', ...)`

```'{"line":401,"column":7063,"sourceURL":"index.android.bundle","result":{"ok":false,"start_time":"2018-02-20T15:31:11.414Z","docs_read":0,"docs_written":0,"doc_write_failures":0,"errors":[],"status":"aborting","end_time":"2018-02-20T15:31:12.006Z","last_seq":0}}'```

If anybody has any further tips on this, I would be grateful. :) I guess it is indeed some difference between the two environments... :)

**Comment by froatsnook** [comment]
@f4z3k4s Which permissions do you have in your AndroidManifest.xml?

**Comment by f4z3k4s** [comment]
@froatsnook I have these permissions:
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> 
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
```

**Comment by f4z3k4s** [comment]
To anybody that may run into this problem: for me, the solution seemed to be to upgrade `react-native: 0.47` to `0.52` and `react: 16.0.0-alpha.12` to `16.2.0`. It even works with the default `asyncstorage` adapter that `pouchdb-react-native: 6.4.0` ships with. Thanks @froatsnook for the effort. :)

**Comment by froatsnook** [comment]
@f4z3k4s Interesting! I am on react-native 0.48 and react 16.0.0

**Comment by gloaec** [comment]
Encountered similar problem with `react@16.3.0-alpha.1` and `react-native@0.54.0`. And beware guys, I hope you like yellow because `componentWillMount` and friends are now deprecated :+1:

**Comment by MrGurns** [comment]
Encountering a similar problem as well.
```"react": "16.3.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-27.0.2.tar.gz",
"expo": "^27.0.1",
"pouchdb-authentication": "^1.1.3",
"pouchdb-find": "6.4.3",
"pouchdb-react-native": "6.4.1",
```

**Comment by greenais** [comment]
@froatsnook could you please elaborate on how you polifilled process.nextTick?
I'm experiencing similar issue: PDB replicate works like a charm for 32-bit android (both debug and release app), works for 64-bit in debug (even on real device) but stops replication for 64-bit release, totally same code. Already weeks of googling-trying-failng, maybe the last resort, please.
I'm using [sqlite](https://dev.to/craftzdog/hacking-pouchdb-to-use-on-react-native-1gjh) version but seems old childhood illnesses reappeared in quite new 64-bit world...
