### ISSUE TITLE
Replication failure to CouchDB from pouchdb running in Windows 10 webview

### ISSUE THREAD

**Issue by MikeIsh** [pouchdb/pouchdb#6710]
### Issue
I have been using pouchdb and Couchdb for a little under a year now, and have found them to be great tools for web apps. I have run into an issue now in one particular environment, and it has to do with replication failing. The app I am running is a local JavaScript Web App that runs inside of a webview in a Windows 10 UWP. This particular web app is used to conduct a survey and capture the results. At the end of the survey a document with the survey responses is saved in pouchdb locally, and then the I try to replicate to the CouchDB database. 

If I run this in a webview in iOS it works fine. If I run it from Safari or Chrome on a Mac, it works fine. If I run it from Chrome or Edge on a Windows 10 device, it works fine. If I run the app inside a webview on a Windows 10 UWP app, the replication fails with a message that says "getcheckpoint rejected with". The local pouchdb database is seems to be saving documents just fine. It is the replication request that fails. It only fails inside the webview. All other scenarios I have tested, as previously referenced work fine.  

From what I have read, people seem to think this error is related to CORS. I have the CouchDB setup with the normal CORS setup, and it works in every other environment, just not in the Windows webview. Would certainly appreciate some assistance.

### Info
- Environment: (JavaScript app in Windows 10 webview. Using PouchDB 6.0.7 with pouchdb.min.js)
- Platform: (Fails on in Windows 10 webview)
- Adapter: (I am not specifying a database adapter so whatever the default is in Windows is what it is probably using.)
- Server: (The CouchDB Server is 1.6.1 on Apache running on linux.)
- CORS Configuration on server: 
credentials: true
headers: accept, authorization, content-type, origin, referer, x-csrf-token
methods: GET, PUT, POST, HEAD, DELETE
origins: *

### Reproduce
I am setting up the local pouchdb database with something similar to the following:
`var surveyResultsDB = new PouchDB('surveyResults');`

All local writing, etc. to pouchdb seems to work just fine.

When I issue the following to cause a replication I get a failure:
`surveyResultsDB.replicate.to('https://userid:password@hostname.domain.com:6984/survey_results_db');`

The message I get back references "getcheckpoint rejected with".

Thanks for any assistance or direction.

**Comment by MikeIsh** [comment]
Finally figured out what is going on here. This replication works just fine in Windows 10 Version 1607 (Anniversary Edition). Using the same code in Windows 10 Version 1703 (Creators Edition) the replication fails. Something related to webviews clearly changed in Windows 10 between those versions. Everything works fine in various browsers in both versions of Windows 10, but running the code inside a webview on Windows 10 Version 1703 does not work. Anybody know what is different in those two versions that would be related to webviews? This seems like it might be a bug since it works inside of regular browsers on both versions of Windows 10.

**Comment by daleharvey** [comment]
Happy to take a fix but sounds like a bug in windows webview so not tracking here

**Comment by OutsourceNow** [comment]
Is there any workaround to this problem? I am currently facing this same challenge. The app works great on android and in the browser, but not in Windows 10 UWP app. It fails to sync with `JavaScript runtime error: Uncaught (in promise): TypeError: Failed to fetch`

**Comment by MikeIsh** [comment]
@OutsourceNow your problem is different from the one I was experiencing. My error message was totally different. The error I experienced was tied to changes made in a specific release of Windows 10. That issue has long since been rectified by Microsoft, and the code I was using has been functioning correctly for quite some time. I will say that is definitely seems to matter how you define the remote PouchDB database and the way you invoke the replication. I my experience not all mechanism seem to work well in Windows. Haven't had much issue with web applications running in iOS, thought that environment is not perfect either.
