### ISSUE TITLE
npm install pouchdb fails 

### ISSUE THREAD

**Issue by KrishnakumarBala** [pouchdb/pouchdb#6714]
### Issue
npm install pouchdb fails 

### Info
- Environment: Node.js
- Platform: Windows 7
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

### Reproduce
Install of pouchdb package using npm install pouchdb

###Logs
[pouch-error.txt](https://github.com/pouchdb/pouchdb/files/1253587/pouch-error.txt)

**Comment by pubkey** [comment]
Which node-version do you have?

**Comment by cquillen2003** [comment]
I am having the same issue.  I'm on Node v8.4.0 on macOS Sierra v10.12.6.

**Comment by cquillen2003** [comment]
I fixed the problem by running Homebrew's brew doctor command which instructed me to run the following:

```sh
sudo xcodebuild -license accept
```
