### ISSUE TITLE
PouchDb not using expected index despite matching fields

### ISSUE THREAD

**Issue by andyto** [pouchdb/pouchdb#6716]
### Issue
I am trying to get PouchDb to sort using a field "updatedAt". I have created an index with the relevant field but PouchDb just refuse to use that index, thus failing for the sort.

### Info
- Environment: browser
- Platform: Chrome

### Reproduce
```js
await localDb.createIndex({
    index: {
      fields: ['type', 'level', 'isDeleted', 'updatedAt']
    }
  })

await localDb.find({
    selector: {
      isDeleted: {$exists: false},
      level: 2,
      type: "note",
      updatedAt: {$gte: null}
    },
    sort: ['updatedAt']
  })
```

PouchDb Debug messages:
![screenshot 2017-08-28 16 58 39](https://user-images.githubusercontent.com/990517/29766748-69b8dc56-8c12-11e7-8107-7d233514b8e9.png)

**Comment by arcadius** [comment]
Hello @andyto 
Are you aware that ```$exists``` does not take advantage of indexes?

**Comment by andyto** [comment]
Hi @arcadius, I have tried to remove ``isDeleted`` from the index and ``isDeleted`` from the selector, unfortunately, it still does not use the index.

**Comment by andyto** [comment]
Managed to solve this by changing the index to
```
   fields: ['updatedAt', 'type', 'level', 'isDeleted']
```

It appears that the `sort` field needs to be the first element in the index. Not sure if this is a bug.
