### ISSUE TITLE
website: unpkg link on downloads page goes to wrong version

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#6724]
On https://pouchdb.com/download.html#cdn, the `unpkg` link goes to version `6.0.4` but the latest pouch version is `6.3.4`.

**Comment by daleharvey** [comment]
Good catch cheers, for anyone that wanted to fix this, going to https://github.com/pouchdb/pouchdb/blame/master/docs/download.md#L57 and changing the 6.0.4 to {{site.version}} will mean the current latest version will get updated in there

**Comment by daleharvey** [comment]
Fixed by https://github.com/pouchdb/pouchdb/commit/c12babc67543c5eb8bddf59cc91b98dbe32ff4a9
