### ISSUE TITLE
website: slack link broken

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#6725]
At https://pouchdb.com/, the `slack` link at the bottom of the page points to http://slack.pouchdb.com/

That site gives me a 502 error:
<img width="517" alt="screen shot 2017-09-01 at 14 11 27" src="https://user-images.githubusercontent.com/191496/29969224-7b8929da-8f1f-11e7-9aa9-cccb974ed70f.png">

This was also the case when I last checked, about 4 weeks ago: https://pouchdb.slack.com/archives/C03FEASK8/p1501757986281488

**Comment by daleharvey** [comment]
Fixed, its supposed to restart every night to ensure it stays up, not sure what happened here but the server needed a restart so might have lost the cron

Maintaining slack support as opposed to just IRC (which requires no maintenance) is taking time away from maintaining pouchdb at this point, fixed this time but may want to rethink using slack in the future

**Comment by garrensmith** [comment]
For CouchDB I setup an invite using now and so far it's been pretty reliable. We could possibly switch to that.

All misspelling thanks to my iPhone.
________________________________

**Comment by wesleymostien** [comment]
it's broken again ?

**Comment by CelsoSantos** [comment]
Seems to broken again. I also can't use the link as I get a 502 error
