### ISSUE TITLE
website: jsdelivr code example is broken

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#6726]
In the [Quick Start section of the Downloads page](https://pouchdb.com/download.html#file), the `jsdelivr` CDN link for couch is given as `//cdn.jsdelivr.net/pouchdb/6.3.4/pouchdb.min.js`:
<img width="509" alt="screen shot 2017-09-01 at 14 15 24" src="https://user-images.githubusercontent.com/191496/29969360-04deba56-8f20-11e7-8d2d-1012c453738a.png">

However, this URL gives 404 (with curl) for both HTTP and HTTPS:
* http://cdn.jsdelivr.net/pouchdb/6.3.4/pouchdb.min.js
* https://cdn.jsdelivr.net/pouchdb/6.3.4/pouchdb.min.js

I clicked the link further down the page for `jsdelivr`, and the top download listed (https://cdn.jsdelivr.net/npm/pouchdb@6.3.4/lib/index.min.js) appears to be a node module, and does not work in my browser.

**Comment by MartinKolarik** [comment]
The correct link for newer versions is: https://cdn.jsdelivr.net/npm/pouchdb@6.3.4/dist/pouchdb.min.js
jsDelivr package landing page: https://www.jsdelivr.com/package/npm/pouchdb

The default/recommended link (which our website shows first) can be configured by setting `main`, `browser`, `cdn`, or `jsdelivr` field in `package.json`.

**Comment by daleharvey** [comment]
This was fixed in https://github.com/pouchdb/pouchdb/commit/3f89873eb0eaee85e3fe526f5e4694e24d1d2f49 but I hadnt published a new site, done now thanks
