### ISSUE TITLE
Resuming a "checkpoint: target" replication will seek from the beginning

### ISSUE THREAD

**Issue by afinne** [pouchdb/pouchdb#6730]
### Issue
Situation: Replicating from a CouchDB over http to a PouchDB, and having the replication settings to only write checkpoints in the target PouchDB. If the replication is interrupted, and later resumed, it will not find the correct checkpoint, so it will seek the _changes feed from the beginning. 

### Info
- PouchDB 6.3.4 in Cordova app
- CouchDB 2.0 (macOS app)

The relevant parts should be around here: https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-checkpointer/src/index.js#L137

It seems like `getCheckpoint` is not aware of the checkpointer options.

**Comment by BrunoDeBarros** [comment]
I'm having problems with this as well; not doing remote checkpoints saves a huge amount of time on the first load but PouchDB ends up just re-checking every change ever anyway, which defeats the point of it.

**Comment by daleharvey** [comment]
and fixed
