### ISSUE TITLE
Pouchdb find return design documents

### ISSUE THREAD

**Issue by Prabuganesan** [pouchdb/pouchdb#6733]
### Issue
Pouchdb find return design documents for first time.
### Info

This is pouchdb and pouchdb find versions

"pouchdb": "^6.3.4",
 "pouchdb-find": "^6.3.4"

cli packages:
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 2.2.0

System:

    ios-deploy : 1.9.1
    Node       : v6.11.0
    npm        : 4.5.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002

### Reproduce
```
 getAllData() {
        return this._db.createIndex({
            index: { fields: ["Name"] }
        }).then(index => {
            var selectorjson = { };
            selectorjson["Name"] = { $gt: null };
            return this._db.find({
                selector: selectorjson,
                sort: ["Name"]
            }).then(resultData => {
                this._studentList = resultData.docs.map(row => {
                    return row;
                });                
                this._db.changes({ live: true, since: 'now', include_docs: true })
                .on('change', this.onDatabaseChange);
            });
        });
    } 
```

This is my code.If I call this method first time index result is 'created'. This time design doc also returned in resultData.(Index not worked)

```
{ 
"id":"_design/idx-9374122a4cd96c254c56a45d91e5399c",
"name":"idx-9374122a4cd96c254c56a45d91e5399c",
"result":"created"
}
```
After kill the app and call now index result is 'exists'. Now design doc not in resultData. (Index worked fine)

```
{
  "id": "_design/idx-9374122a4cd96c254c56a45d91e5399c",
  "name": "idx-9374122a4cd96c254c56a45d91e5399c",
  "result": "exists"
}
```

**Comment by pubkey** [comment]
Same problem here.
I now added `language: { $ne: 'query'}` to each query as a workaround so it does not find design-docs.

**Comment by Prabuganesan** [comment]
Thanks @pubkey. I have added language:{$ne:'query'} in my selector but no use. Because first time index not worked.

**Comment by timbophillips** [comment]
surely this needs to be fixed or do we just manipulate either mango query or its output to dump the design docs?

**Comment by daleharvey** [comment]
Does mango return design documents here or is this pouchdb only?

**Comment by garrensmith** [comment]
Pouchdb-find and mango shouldn't return design docs

**Comment by garrensmith** [comment]
I think we wanted to add a fix for this in pouchdb-find once the fix was in mango. Which it is now in.

**Comment by garrensmith** [comment]
This is already fixed in PouchDB

**Comment by jozsi** [comment]
Still happens here, with latest versions.
