### ISSUE TITLE
invalid Adapter: idb and allDocs not woking

### ISSUE THREAD

**Issue by sachiner** [pouchdb/pouchdb#6741]
### Issue
Pouchdb not working on when I hosted my project, but runs fine on Loca host.
Some times also on local host gives error = invalid Adapter: idb
When I used all docs locally it is giving all docs but when hosted link opened is was not woking at all.

### Info
- Environment: (React.js/browser)
- Platform: (Chrome/iOS/Android)
- Adapter: used the default settings for adapter as mentioned in the docs.
- Server: No server just built own functions for firebase

### Reproduce
const PouchDB = require('pouchdb');
PouchDB.plugin(require('pouchdb-find'));
const FirebaseToPouch1 = new PouchDB('FirebaseToPouch');
const Pouch2ToFirebase = new PouchDB('PouchToFirebase');
const CashCollectorDetails = new PouchDB('CashCollectorDetails');

firstly when page loads, every time same data is comming so to the function 

export function addDataFirebaseToPouch1(data,Maincallback){  
    let dataCount = 0;
    for (let key in data) 
    {
      data[key]._id = data[key].id;
      data[key]._rev = new Date();
      
      FirebaseToPouch1.put(data[key],function callback(err, result) {
        if (!err) 
        {
          dataCount++;
          
          if(dataCount === data.length)
          {
            Maincallback(true);
          }
        }
        if(err)
        {
          console.log(err)
        }
        
      });
    }   
}

Which in return gives error of duplicate entry like this : {status: 409, name: "conflict", message: "Document update conflict", error: true, id: "-KozVHD3AUsnjO5lJV08", …}

after that when I tried to fetch the older enteries like this

export function getAllTaskFromPouch1(callback) {
  FirebaseToPouch1.allDocs({include_docs: true}).then(function (response) {
     console.log(response)
     callback(response);})
    .catch(function (err)
    {
        console.log(err);
    });
} 
but gives 0 docs but as far according to error there are some records in the pouch due to which 409 occured

**Comment by willholley** [comment]
A 409 error is returned when a user attempts to update a document without providing a `_rev` value that matches what is currently the "winning" revision in the database. It could be that the "winning" revision is deleted, in which case it would not be returned by `_all_docs` (incidentally, `_changes` is a better bet for getting a complete list of documents, including those that are deleted - that's how PouchDB [replication/sync](http://docs.couchdb.org/en/2.1.0/replication/protocol.html) works).

**Comment by luiseduardobrito** [comment]
I'm also getting the occasional "Invalid Adapter: idb" errors. The only workaround I could find so far is to clear the browser data. Some times a simply reloading the page also fixes the problem, but is not 100% effective,
