### ISSUE TITLE
ascend/descend data in pouch db

### ISSUE THREAD

**Issue by lakinmohapatra** [pouchdb/pouchdb#6743]
### Issue
How to ascend/descend data in pouch db ? 

### Info
- Environment: browser
- Platform: Chrome
- Adapter: Indexeddb
- Server: CouchDB

**Comment by willholley** [comment]
I'm not sure what you mean by this? [_find](https://pouchdb.com/api.html#query_index) provides the ability to sort, skip and limit.

**Comment by vividhsv** [comment]
It is not clear in the documentation on how to specify sort order ascending or descending.
Looks like only sort field can be specified but not the order.

**Comment by vividhsv** [comment]
Looks the documentation point to couch documentation for more info on the syntax.
http://docs.couchdb.org/en/2.0.0/api/database/find.html#find-sort

Sort order can be specified like so sort: [{'created_on': 'desc'}] or sort: [{'created_on': 'asc'}]
