### ISSUE TITLE
Typescript support ? 

### ISSUE THREAD

**Issue by lakinmohapatra** [pouchdb/pouchdb#6744]
We need typescript support for pouch db so that we can use it inside angular 2

**Comment by willholley** [comment]
@lakinmohapatra I think the answer provided by Max in https://stackoverflow.com/questions/37611327/how-do-i-use-pouchdb-with-typescript should work.

**Comment by bradcypert** [comment]
Hi @lakinmohapatra! I'm using pouchdb inside an Angular project already. I recommend checking out the @types/pouchdb definition files. You should be able to use both pouchdb and the definition files to build your angular app with ease!

**Comment by lakinmohapatra** [comment]
Thanks. I m using the same.

**Comment by daleharvey** [comment]
Closing out typescript bugs, we do not use typescript for this repo and if typescript projects cant use other javascript projects then I would suggest that they fix that
