### ISSUE TITLE
Include pouchdb.js in pouchdb-browser package

### ISSUE THREAD

**Issue by H--o-l** [pouchdb/pouchdb#6745]
### Issue
Pouchdb submodules are really great. 

They allow to reduce time of `npm install` first execution and give the possibility of choosing exactly which pouchdb part you need for your project, but they only include node.js `lib/index.js` version, not row javascript directly usable in browser (`pouchdb/dist/pouchdb.js`).

It's particulary sad for the pouchdb-browser submodule.

If I'm not mistaken this part of the build chain create the `dist/pouchdb.js` file:
https://github.com/pouchdb/pouchdb/blob/9fa045c13438ca440d73e904af8ef8302e6faa7a/bin/build-pouchdb.js#L128-L138

The ouput of this code is set in the global pouchdb `dist` folder and then not present if you only do `npm install pouch-browser`.

It greatly reduce the interest of submodules for me as I need this file for e2e tests and so I need to install the global pouchdb release in the developpement environment (while otherwise pouchdb-browser would have been enought).

Do you believed it would be possible to include `pouchdb.js` in pouchdb-browser package ?

### Info
- Environment: browser
- Platform: all browsers
- Adapter: non relevant
- Server: all

### Reproduce
```sh
npm install pouchdb-browser
```
and then try to find a .js file to inject directly in a browser.

### More info 
https://stackoverflow.com/questions/46112773/how-to-inject-pouchdb-browser

**Comment by H--o-l** [comment]
Up for this one !
I would love to do it myself but I am not sure:
- you agreed
- I would succed to understand the build process

**Comment by H--o-l** [comment]
Hello !
Up or the issue will be closed.
I can't try to fix it if I have no help :-/

**Comment by daleharvey** [comment]
Hey, so in all honesty the pouchdb build system is the part that I know the least about and something I plan on looking more into soon, however if you were to provide a patch for this I would be happy to merge. It sounds like something that would be useful
