### ISSUE TITLE
Multi user system for pouch db ? 

### ISSUE THREAD

**Issue by lakinmohapatra** [pouchdb/pouchdb#6757]
I am developing one web app with multiple users. 

I have some isolated data which should be shared among users only .

Also i have some data which needs to be shared among multiple people. 

Please advise , 
whether i should go with one database per user or filtered replication at initial stage ? 
If i need to make filtered replication , i need to add user id to each and every document. 

Please suggest.

**Comment by daleharvey** [comment]
There are tradeoffs with each approach, a db per user is generally a good approach as long as the data is completely isolated and you do not need cross database queries, if you do then filtered replication is usually best, but either way these things are implemented at a higher level than pouchdb and not within the library itself so closing this out, cheers
