### ISSUE TITLE
buffer-from is listed as a dependency instead of devDependency

### ISSUE THREAD

**Issue by bbenezech** [pouchdb/pouchdb#6761]
https://github.com/pouchdb/pouchdb/search?utf8=%E2%9C%93&q=buffer-from&type=

It is an inconvenience, the dependency tree of buffer-from is quite insane.

**Comment by daleharvey** [comment]
Seems like it should be easy to rewrite that test to not use buffer-from as well, would be nice to get either fix for that

**Comment by daleharvey** [comment]
So githubs search ignores most of our code, we actually use buffer-from, we could probably do some work to remove it but its not in devDependencies 

If anyone wants to remove the buffer-from dep, I got it mostly working in https://github.com/pouchdb/pouchdb/pull/6923 but dont have time to check the fruitdown issue
