### ISSUE TITLE
Syncing Multiple DB's in iOS11

### ISSUE THREAD

**Issue by alexmills** [pouchdb/pouchdb#6768]
### Issue
I've got an issue with PouchDB that's only affecting my react app when run on iOS11, iOS10 is not affected. It appears to be something to do with home screen apps now using WKWebView.

So with a fresh iOS10 device and iOS11 device, the app doesn't start syncing the following databases until it's installed on the home screen:

* trips: 2.2MB - 2775 docs
* locations: 73KB - 335 Docs
* clients: 74Kb - 258 Docs
* drivers: 74KB - 156 Docs

All normal docs, no attachments.

After the app has loaded and sync has completed, I have the following databases:

<img width="670" alt="screen shot 2017-09-26 at 9 27 46 pm" src="https://user-images.githubusercontent.com/661414/30862924-27e454e8-a302-11e7-96c6-8a2d9f6ecb3f.png">

The __iOS10__ device has all the documents synced perfectly as normal. The __iOS11__ device has the locations, clients and drivers synced completely but only about 60% of trips before the sync is paused as if it's complete. __No errors, just stops__. If I refresh the app, each time it will sync 10-20 more docs and then pauses the sync.

I figured this may be a storage issue but if I disable the sync on the other databases, trips will suddenly catch up and finish syncing and updating with live changes. So I did the following tests to see how many databases I could sync (with a fresh device each time) before trips would stop syncing again.

Trips | Locations | Clients | Drivers | Trips Working | Notes
-----|-----------|--------|---------|-------------|---------
__ON__ | Off | Off | Off | __YES__
__ON__  | __ON__ | Off | Off | __YES__
__ON__  | __ON__ | __ON__ | Off | __YES__
__ON__  | __ON__ | __ON__ | __ON__ | __NO__ | No local changes from any database are synced until refresh
__ON__  | Off | __ON__ | __ON__ | __YES__
__ON__  | __ON__ |  Off | __ON__ | __YES__
__ON__  | __ON__ |  __ON__ | Off | __YES__

So no matter the combination of databases, as long as you're syncing no more than 3, you're fine which doesn't make sense. The results are the same when reducing `batch_size` and `batches_limit`, it just happens slower.

To verify that this isn't a WebSQL issue, I forced PouchDB to use IndexedDB on iOS11 and got the same results as above.

The app continues to work fine on Chrome (desktop/android) and the beefy AWS server hosting CouchDB never goes over 3% load.

I understand that syncing so many databases isn't a common use case, but have you guys seen anything like this with iOS11 yet?

### Info
- Environment: Browser/iOS Home Screen App
- Platform: iOS/Safari
- Adapter: IndexedDB/WebSQL (pouchdb-browser@6.3.4)
- Server: CouchDB

**Comment by willholley** [comment]
@alexmills this sounds like you're running into a concurrent requests limit. Do you have a network trace which shows any connection failures? Do you know whether the PouchDB [retry](https://pouchdb.com/api.html#customizing-retry-replication) behaviour is getting triggered?

**Comment by alexmills** [comment]
@willholley no network errors and no dropped connections on the server. When you reload the app, each database performs a couple request and then stop like normal. In total about 5 requests are made when the app is reloaded.

**Comment by alexmills** [comment]
Looks like the issue is that iOS 11 (or WKWebView) is much stricter at enforcing the `4 maximum concurrent connections to the same host`.

[NSURLSession](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1407597-httpmaximumconnectionsperhost?language=objc)

If I split my DB's over two different URL's (to the same CouchDB server) it all works perfectly.
