### ISSUE TITLE
Is it possible to view DB created by node-websql-adapter using regular sqlite3 viewers

### ISSUE THREAD

**Issue by walleXD** [pouchdb/pouchdb#6769]
### Issue
Hi, I am currently using ` node-websql-adapter`. Given that pouchdb-inspector has been deprecated, I wanted to see my data using sqlite3 viewers but the dbs show that there are no data in them even though I can query them and get the data I added. Is this an expected behavior?

### Info
- Environment: electron 1.7.8
- Adapter: node-websql

**Comment by daleharvey** [comment]
Sounds like an issue to take up with the viewers, cheers

**Comment by walleXD** [comment]
@daleharvey I tried to use multiple sqlite viewers but all of them showed empty db w/o any data even though I am able to save & use data using `node-websql`. So, is it possible that it's related to the adapter?
