### ISSUE TITLE
Initial Bulk Docs Performance

### ISSUE THREAD

**Issue by nerumo** [pouchdb/pouchdb#6771]
### Issue
I insert 20k of data into a database through pouchdb load. The total of the load/insert takes around 2.5s. Since it isn't the only table with such amount of data, I was curious where the process spends time.

#### JSONParse
Of course, a lot of time (1s) is spent in parsing the json. This is fine for me, since it's built well with first splitting to avoid memory peaks. But still, it's a big piece of the cake, so if you have any suggestions, please let me know.

#### Cloning
The next big thing is something I was wondering about: it spends about 500ms with cloning. I looked into the code and it's the `getArguments` call in the `toPromise` hook of the `bulkDocs` operations.
![image](https://user-images.githubusercontent.com/8597645/31053580-0cb9d092-a6a1-11e7-956d-df8c2857f1c7.png)
I understand that from the moment you pass an object to a pouchdb operation, it shouldn't respond to any other changes on that object. But in this (IMHO very common) scenario of initially filling the db with data, this cloning isn't necessary and just spoils 20% of the initial sync time.
Is there a way to avoid this? Would not using promises circumvent the issue or would the cloning also happen?

#### Bulk Docs on the idb adapter
1s for saving the docs actually isn't bad. But if I look at how the time is spent, I still wonder if we have room improvement.
First, 500ms are used for parsing. Most of the time is spent in the `parseDoc` method. ~~I'm no expert to v8 (or general) JS vm optimizations, but I recently read an article about when the v8 compiler has to deoptimize JS code. There might be some quick wins hidden.~~ I'm no expert to v8! :) I checked and nodejs 8.4 optimizes it perfectly. I tried to test which part of the method takes the most time and it's the for-in loop with `reservedWords` and `dataWords` that slows the method down. But no clue if this can be optimized. (I tried a Map object with `has(..)` lookup but no improvements)

Next thing I noticed is, that fetching the (in this case not) existing documents takes around 500ms. I know that in normal scenario, we must load the existing docs. Is there a way to skip this check? Like a force bulkDocs? Or could we even use the `new_edits` parameter for that?

So altogether I think there's a lot of potential to optimize initial load/sync time for usages with pouchdb load (or maybe classic replication as well).

I'd like to hear you thoughts about it. Thank you

### graph
![image](https://user-images.githubusercontent.com/8597645/31053958-3bf254fe-a6a8-11e7-94eb-0233a7b42f54.png)

### Info
- Environment: browser
- Platform: Chrome (latest stable)
- Adapter: IndexedDB
- Server: Nodejs with express-pouchdb

### Reproduce
Use pouchdb load to import 20k of documents from JSON into a idb database

**Comment by alexpirine** [comment]
Please reopen…

**Comment by mqtik** [comment]
This should be reopen.
For me it takes a minute or two, maybe more sometimes, to builk 23 rows.

I'd also like to know how to get only certain attributes, for not overload proccess..
