### ISSUE TITLE
Data usage very high (I guess)

### ISSUE THREAD

**Issue by JCKodel** [pouchdb/pouchdb#6773]
I've written a Cordova app that pulls two databases from a remote couchdb installation (using pouchdb locally, of course).

There is a local.sync(remote) to make things off-line first. Everything works better than I antecipated, including conflicts, except one thing:

The data usage of my app is 474Mb (going to Android settings, data option, usage, my app)!!! (I know that cordova hot loading updates contribute to this, and everytime I change my project, webpack compiles it and send through the wire to update the cordova shell)

There are only one record in each database: a user (with name, email, and a 50x50 PNG) and a social network post, including tags, date and an attachment of a 512x512 JPG. In Chrome (I'm using cordova browser as well), the local storage is:

![image](https://user-images.githubusercontent.com/379339/31058596-a239b5f8-a6cc-11e7-9a27-b92389c65637.png)

I've noticed that pouchdb uses long polling to sync databases.

Is there anything that you guys can share with me regarding high data usage on sync? Maybe websocket implementations, or some non-automatic sync behavior...

Thank you all in advance.

P.S.: CouchDB sizes:
![image](https://user-images.githubusercontent.com/379339/31058617-09283532-a6cd-11e7-844f-7e0de7146757.png)

**Comment by willholley** [comment]
@JCKodel have you compacted your PouchDB database (or enabled [auto compaction](https://pouchdb.com/api.html#create_database))?
