### ISSUE TITLE
PouchDB typescript results in TS2351 errors (cannot use 'new' with an expression whose type lacks a call or construct signature)

### ISSUE THREAD

**Issue by G-Rath** [pouchdb/pouchdb#6775]
I've been trying to use PouchDB with a typescript project, with no luck.

I tried it a couple of ways, some worked *fantastically*, where I could do `new PouchDB<DBTypes.ServerDoc>(DataManager.DB_SERVERS)` and get type completion on methods like `.allDocs()` - All sorts of fun things.

However TypeScript won't generate 'valid' js code: it generates `new pouchdb_1.default(DataManager.DB_SERVERS)` instead of `new pouchdb_1(DataManager.DB_SERVERS)`

That was when I use: `import PouchDB from 'pouchdb';`.

The method I've been using with all my other requires (since I'm converting a small existing project) is `import PouchDB = require('pouchdb');`, but that gives me this error:

> TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.

Overall, I'm very confused on how to use PouchDB property with TypeScript :/

**Comment by G-Rath** [comment]
I did find [this git project](https://github.com/nolanlawson/pouchdb-ionic-2-typescript-demo/pull/1) that seems to suggest the PouchDB typing has a mistake in how it exports it's module?

**Comment by G-Rath** [comment]
I applied the code suggested in the pull request, and it fixed my problem, resulting in correctly generated code that worked with auto-completion and type resolving. 

So I guess that the PouchDB typescript files should be updated to include this fix?

**Comment by mlegenhausen** [comment]
I don't see any further progress. For everyone struggling the same you can simple patch your typings via postinstall hook. It's ugly but working:

```sh
#!/bin/sh

# The types you want to patch without pouchdb- prefix
declare -a types=(
  "adapter-fruitdown"
  "adapter-http"
  "adapter-idb"
  "core"
  "replication"
)

for t in "${types[@]}"
do
  echo "Patching @types/pouchdb-${t}"
  sed -i '' 's/export = /export default /' "node_modules/@types/pouchdb-${t}/index.d.ts"
done

```

**Comment by daleharvey** [comment]
Closing out typescript bugs, we do not use typescript for this repo and if typescript projects cant use other javascript projects then I would suggest that they fix that

**Comment by creativecoder** [comment]
I was getting this error until I followed the instructions for setting up PouchDB with Typescript: https://pouchdb.com/guides/setup-pouchdb.html#typescript

After setting `"allowSyntheticDefaultImports": true` in my typescript compiler options, I no longer saw this error.

**Comment by tagpfauenauge** [comment]
I had the same error using pouchdb and typescript: 
  _This expression is not constructable._
at a line with
`  const db=new PouchDB("dbname");`

I had to change my import from
`import * as PouchDB from "pouchdb"`
to
`import PouchDB from "pouchdb"`

I hope that could help.

**Comment by roninee** [comment]
> allowSyntheticDefaultImports

worked for me! Thanks
