### ISSUE TITLE
Export 'default' even in CommonJS output for ESM transition

### ISSUE THREAD

**Issue by WorldMaker** [pouchdb/pouchdb#6776]
Related to #6775 and spinning out of research I did for a longer comment in [DefinitelyTyped/DefinitelyTyped#19691](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19691#issuecomment-334349501), one obvious actionable item that I see that may help in the CommonJS to jsnext/ES Module transition would be if the CommonJS builds of PouchDB also exported a `default`.

This is something that has caught on in Babel transpilation especially where you see a lot more of variants of things like `exports['default'] = exports = PouchDB`. A cursory skim doesn't seem like Rollup currently supports this, but it might be a good option.

(Alternatively, consider leaning further into the transition and dropping the non-default `exports = PouchDB` entirely for named exports or just `exports['default'] = PouchDB`.)

**Comment by bbenezech** [comment]
@daleharvey

Please read have a look at https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19691#issuecomment-334349501 for why we have so many reported issues over Typescript problems. 

It's not `them`, it's `us` :(

`export = Module` is off-spec and should be changed to `export["default"] = Module` wherever we export defaults.

@WorldMaker Thanks for the detailed comment.
