### ISSUE TITLE
pouchdb-find does not have update_after/stale option

### ISSUE THREAD

**Issue by BrunoDeBarros** [pouchdb/pouchdb#6777]
I'm not using the default 'new issue' template because this isn't an issue for reproducing. No jsfiddle can be provided. I hope that's OK.

With db.query(), it's possible to specify that you're OK with a stale result, to get results faster. I've found that with db.find(), though, that's not possible. There's no mention anywhere in the API of something like this. Given that Mango indexes are stored in the DB like normal views/design docs, it doesn't seem like there's a reason not to have that option.

I'm specifically referring to local PouchDB databases.

Is this on purpose, or is it just something that was never added in? Is it supposed to always be up to date and always fast (in which case I'll open up a proper issue for it, JSFiddle and all)?

**Comment by daleharvey** [comment]
Our future plans for pouchdb-find is that they will use native indexes under the hood, they wont be stored like map reduce results and need updated so its not in the api, cheers
