### ISSUE TITLE
Using pouchdb-find against CouchDB 1.6

### ISSUE THREAD

**Issue by vrymel** [pouchdb/pouchdb#6779]
### Question
I guess my concern here is how does PouchDB indexing work on pouchdb-find? Is it just the same indexing when I use map/reduce? Cause I have a remote CouchDB 1.6 instance which still does not support the `find` API. If I use pouchdb-find on a mobile application setup, does that affect or cause any problems during syncing?

### Info
- Environment: hybrid app
- Platform: iOS/Android
- Server: CouchDB 1.6

**Comment by willholley** [comment]
@vrymel it's fine to use PouchDB-find against locally stored data even if the server doesn't support it. Indexes are not replicated during sync - they are built locally to each database. You might chose to sync index definitions (i.e. design documents) though this is a bit unusual, in which case the server would just reject or ignore those and continue syncing everything else.

**Comment by vrymel** [comment]
Thanks for the clarification @willholley
