### ISSUE TITLE
could you give me gui application that let me review my database?

### ISSUE THREAD

**Issue by anlexN** [pouchdb/pouchdb#6780]
windows x64 pro,  pouchdb 6.3.4, node 8.6.0.
i code that generate first_database, how can i review my first_database through gui ? pouchdb-server don't give to me data about first_database. 
![3](https://user-images.githubusercontent.com/8686739/31308614-51c71752-abac-11e7-8398-598e8712e29f.PNG)

**Comment by pubkey** [comment]
if you use pouchdb in the browser, you can open the dev-console and see the pouchdb-content under Application->Storage.

**Comment by singhshashi** [comment]
Alternatively, you could sync your pouchdb with a couchdb and then use Futon/Fauxton to view the synced pouchdb data in Couch.

**Comment by daleharvey** [comment]
Yup, there is also https://github.com/pouchdb/pouchdb-fauxton-chrome-extension but would need work to get running again
