### ISSUE TITLE
Slow put() on chrome browser

### ISSUE THREAD

**Issue by fredericgermain** [pouchdb/pouchdb#6781]
### Issue
I planned to used pouchdb, read some documentation, and stumbled unto these projects.
* https://github.com/nolanlawson/database-comparison
* https://github.com/nolanlawson/database-comparison-worker-pouch

I found really really bad performance on Chrome more than 200s for "PouchDB put()", 1000 docs, normal environment.

When digging into the code to profile what was wrong in the packaged pouchdb.js, I found there was a lot of time in idbBulkDocs between the metaStore.put in updateDocCountIfReady and the transaction complete() callback.
I then decided to try firefox, and I found it to be around 100x faster (less than 2s).
The "LocalForage" test gives similar results, so it's probably a implementation difference between browsers. Maybe it's related to the optimization note we can find here : https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction

https://github.com/pouchdb/pouchdb/issues/6093 could be related.

Maybe have an option to avoid using a transaction on Chrome ?
Maybe the Chrome team could have a look as it could impact offline apps ?

### Info
- Environment: browser
- Platform: Chrome Version 61.0.3163.100 (Official Build) (64-bit) on Linux (updated stable version)
- Adapter: IndexedDB

### Reproduce
Run the test on http://nolanlawson.github.io/database-comparison/

**Comment by bradcypert** [comment]
@fredericgermain That's a pretty fair assessment for inserting 1 (unique) document 1000 times. Without digging too much into Indexeddb's transaction management, I'd say that you're probably right about that being the cause. Have you tried profiling `bulkDocs` instead of a `put` for larger collections?
