### ISSUE TITLE
PouchDB two way sync with CouchDB fails in iOS 11

### ISSUE THREAD

**Issue by anilchinnu21** [pouchdb/pouchdb#6782]
### Issue
In our app, we have two-way sync between PouchDB and CouchDB which works fine in iOS 10.3 or in any other desktop browsers. Recently when we upgraded our devices to iOS 11, two-way replication has stopped working. Updated done on the server are not synced back to the client.

### Info
- Environment: browser
- Platform: iOS 11
- Adapter: WebSQL
- Server: CouchDB

### Reproduce
1. Added an object to PouchDB and that got sync to CouchDB 
2. Next updated object in CouchDB programmatically and then allowed it to Sync back to client
3. Observed that the changes are not getting synced to client in iOS 11. its working fine in iOS 10.3

**Comment by ARChilton** [comment]
Are you using https? I'd read that the latest ios was restricting what could be sent too and from the iPhone over http. I had a similar issue and we assumed it was this but couldn't test it. So just got everyone to use android for the event.

Im planning to test again soon. 

Have you found that replicate.to and replicate.from work? As a secondary option?
