### ISSUE TITLE
10 second delay on PouchDB first sync with local instance of CouchDB when using Electron

### ISSUE THREAD

**Issue by alexParkes** [pouchdb/pouchdb#6784]
### Issue
If PouchDB 6.3.4 is used in Electron (1.8.1) there is a strange 10 second delay on first sync with an external CouchDB instance (run locally in this case). The problem seems to occur whether you run the 'electron-rebuild' package or not (rebuilds leveldown for me).

I think this is a bug (or misconfiguration) as:
1. Almost identical code run in plan Node does not seem to exhibit this, despite using the same version of PouchDB.
2. The wait is almost always exactly 10 seconds (or occasionally 20 seconds) - I suspect this figure could be some sort of timeout.

I would expect the sync of the code running in Electron to take the same amount of time as the code running in plain Node.

Apologies if there is already an issue covering this (couldn't find one, but I could have missed it), or if it looks like I've just made a simple config error.

### Info
- Environment: Electron 1.8.1; PouchDB sync attempted in Electron main process. Node 8.2.1 (both through Electron & on its own) Machine: Fedora 26.
- Platform: Electron/Node
- Adapter: LevelDB
- Server: CouchDB 2.1.0, compiled from source and run locally on Fedora 26.

### Reproduce
1. Compile or install CouchDB 2.1.0 to be run locally; enable CORS and anything else you need for unfettered access to the server.
2. Running CouchDB locally, create yourself a DB (e.g. 'test-db').
3. Add a simple document to your DB. E.g.:
```bash
$ curl -X PUT \
  http://localhost:5984/test-db/test-document \
  -d '{
	"title": "I'\''m a test!"
}'
```
4. Download and extract test bundle ```pouchdb-electron-bug-test.tar.gz```.
5. Switch to Node 8.2.1.
6. In electron-test directory, run ```npm install```
7. Open main.js. Configure lines 11-15 to match your environment.
8. Run:
```bash
$ npm run pouchdb-sync-debug
```
9. Take copy of the console output - look out for the 10s wait. I saw a line similar to:
```
pouchdb:api http://localhost:5984/test-db put success { ok: true, id: '_local/cEq.WgZP6mSTHKZXi7SkrQ==', rev: '0-1' } +10s
```
10. OPTIONAL: Run:
```bash
$ ./node_modules/.bin/electron-rebuild
```
11. Repeat steps 7-9.
12. Go to the plain-node-test directory.
13. Make sure you're still using Node 8.2.1.
14. Run ```npm install```
15. Configure lines 8-12 to match your environment (and what was used in step 7).
16. Run ```npm run-pouchdb-debug```
17. Take a copy of the console output.
18. I found that if I diffed the two console outputs (aside from the obvious differences in generated IDs etc.), the main difference seemed to be the final 'put success' to the test-db.

[pouchdb-electron-bug-test.tar.gz](https://github.com/pouchdb/pouchdb/files/1369821/pouchdb-electron-bug-test.tar.gz)

**Comment by alexParkes** [comment]
Should have mentioned above - I realise that Electron 1.8.1 is only in Beta at the moment, but I was trying this using Electron 1.7.8 before. With 1.7.8., I think I saw more 20 second waits with the sync when running Pouch through Electron.

I guess if things are getting better in Electron 1.8.1 (10 seconds vs 20 seconds), then it might point to a problem in Electron rather than Pouch.

Anyways - would be great if some one could cast an eye over it to see if there are any easy fixes.

Cheers

**Comment by daleharvey** [comment]
Happy to take a fix but sounds like a bug in electron
