### ISSUE TITLE
Cannot create new local pouchdb databases with a new name.  Can only create 3 that I have already been using.

### ISSUE THREAD

**Issue by irvins** [pouchdb/pouchdb#6785]
### Issue
I can only create local databases for 3 previously created database names.  This is confusing because those databases were named arbitrarily: "disc_users", "disc_projects", "disc_log" .  But if i try to create a new database : "disc_attachments"  or any arbitrary name like "abcxyz"  i get the following errors when i try to put a row of data to them 

var data = {"_id" : "test_123_xyz" , "project_code" : 19}

"websql errors either "status: 500
name: web_sql_went_bad
message: unknown
reason: reason: The quota has been exceeded." 
if i try "[ANYTHING]"  

and 

"status: 500
name: web_sql_went_bad
message: unknown
reason: there was not enough remaining storage space, or the storage quota was reached and the user declined to allow more space" 
if i try "disc_attachments"

i thought maybe the db names cant be too long so i tried "disc_abc" 
or since "disc_users" works, im trying "disc_user"
for everything but 'disc_attachments' i get the "The quota has been exceeded".  Something tells me that the errors aren't really accurate.

i try destroying the current local databases, and localstorage.clear()  to make sure i have a clean slate.

It is driving me mad, trying to figure out why i can only create databases for 3 names, but not for anything new.  It almost feels like there is something hardcoded somewhere, but i do not reference those names anywhere else in the code besides where the the instances of the local database are instantiated.

### Info
- Environment: Cordova
- Platform: iOS 
- Adapter: SQLite
- Server: Cordova App + CouchDB for syncing

### Reproduce
my pouchdb start up function looks like this:

,startupDB: function(dbname){
        var db  = new PouchDB(dbname, {iosDatabaseLocation: 'default', auto_compaction: true, adapter: 'cordova-sqlite'});
        if (!db.adapter) {
          db = new PouchDB(dbname);
        }
        return db;
    }

in my "deviceready()"  i have nothing but these lines

//working
var localusersdb                 = datastore.startupDB("disc_users"); 
var localprojdb                   = datastore.startupDB("disc_projects);
var locallogdb                    = datastore.startupDB("disc_log");

//trying to add new one
var localattachmentsdb     = datastore.startupDB("disc_attachments");

when i look under the "resources" tab in the weinre inspector page.
i see that the first 3 local databases look fine. 

but the disc_attachments data base has no meta information with it
no "attach-seq-store" , no "sqlite-sequence"  etc .

![screen shot 2017-10-09 at 12 50 54 pm](https://user-images.githubusercontent.com/2185128/31362026-41d08bf2-ad0b-11e7-8b71-ca74d0260260.png)

**Comment by pubkey** [comment]
The error clearly says `The quota has been exceeded`
- Is your hard-drive full?

**Comment by irvins** [comment]
Thats what it says yes.  But it most definitely is not.  The only code i put in the "deviceready" block are the new Pouch("disc_users"), new Pouch("disc_projects"), new Pouch("disc_log")  ... etc.
if i try to save a sample data {"_id" : "test_123_xyz","project_id" : "19" } to these, they save fine.

but as soon as i try a new name like new Pouch("disc_user") singular, new Pouch("disc_project"), or the one i really want to do is new Pouch("disc_attachments")   i will get those errors "The quota has been exceeded."   but weirdly the error when i try to use "disc_attachments" is differently worded .. i get "there was not enough remaining storage space, or the storage quota was reached and the user declined to allow more space"

ive been working on this project for a while and have been using the names "disc_users", "disc_log" and "disc_projects" since the beginning.    they are only stored in a config object.   the names are arbitrary.   Im baffled why i can not create a new database with a name other than these three.   Is there some kind of set up step? or some invisible .gitignore type file that i forgot about?

when i grep my whole project , those names are only stored in that one config object in one place.

i can destroy them ... and i can recreate them.. but i cannot create databases named anything other than those 3.

**Comment by daleharvey** [comment]
Sounds like a super weird bug with cordova, but yeh there is nothing in pouchdb that would cause that
