### ISSUE TITLE
 PouchDB is just checking if a remote checkpoint exists.

### ISSUE THREAD

**Issue by saty932** [pouchdb/pouchdb#6789]
Error:
192.168.0.51:5984/cmsdata/_local/8RgcAxGnEnpZLCScwQMNHw%3D%3D?_nonce=1507725343736 Failed to load resource: the server responded with a status of 404 (Object Not Found)
The above 404 is totally normal. PouchDB is just checking if a remote checkpoint exists.

i am trying get the data from remote db somehow it's unable to get the data it's showing above error 
can anyone help me how to solve this issue with ionic app.
This is my code:
		this.remote = 'http://192.168.0.51:5984/cmsdata';
		this.db = new PouchDB('cmsdata');
		let options = {
			live: true,
			continuous: true
		};
		
		this.db.sync(this.remote, options);

		if (this.data) {
			return Promise.resolve(this.data);
		}

		return new Promise(resolve => {
			this.db.allDocs({
				include_docs: true
			}).then((result) => {
				this.data = [];	
				let docs = result.rows.map((row) => {
					//console.log(row.doc);
					this.data.push(row.doc);
				});
				resolve(this.data);
				console.log(this.data);
				this.db.changes({live: true, since: 'now', include_docs: true}).on('change', (change) => {
					this.handleChange(change);
				});
				
			}).catch((error) => {
				console.log(error);
			});

		});

### Info
- Environment: hybrid app
- Platform::iOS/Android
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: CouchDB.

**Comment by pubkey** [comment]
In your code you start `.sync()` and do not wait until the first replication is done. Directly afterwards your call `allDocs()` which than of course directly runs the query without waiting for the sync and so does not have documents.

**Comment by saty932** [comment]
how can i reduce the syncing time and is there any option to know when the syncing is done.I have one more doubt it's working fine in web browser but when i am debugging in mobile then only i am facing error with this one.

**Comment by pubkey** [comment]
If you do a one-time-sync. The complete-event is fired which tells you that the initial sync is done.

**Comment by saty932** [comment]
Thanks @pubkey it worked fine.
