### ISSUE TITLE
ipfs/orbit-db support

### ISSUE THREAD

**Issue by spaceywolfi** [pouchdb/pouchdb#6790]
i think it would be really cool if orbit-db could be used with pouchdb, although this is not directly related to pouchdb, maybe there are people here also interested in decentralization and want to help make this possible.

relate issue
https://github.com/orbitdb/orbit-db/issues/4

if this is not the write place for discussions then feel free to close this issue

**Comment by daleharvey** [comment]
Feel free to ping me on the other disucssion thread if yall have questions but seems like it got picked up there more than here, cheers
