### ISSUE TITLE
Simultaneous/concurrent find calls are slow.

### ISSUE THREAD

**Issue by mleduque** [pouchdb/pouchdb#6796]
### Issue
Simultaneous/concurrent find calls are slow.

### Info
- Environment: not sure, react-native
- Platform: Android
- Adapter: pouchdb-adapter-react-native-sqlite
- Server: no server part, this is purely a local db

### Reproduce

I use  the pouchdb-find plugin on a database with an secondary index:

```javascript
  await db.createIndex({
    index: {
      name: 'by_ref',
      fields: ['is_article', 'ref'],
    },
  });
```
I have two queries launches simultaneously
db.find({
  selector: {
    is_article: true,
    ref: {
      $gt: null,
    },
  },
  sort: ['is_article', 'ref'],
  limit: 20,
  skip: XX,
});

I checked I have an index-backed query plan (with pouchdb-find debug).
The database itself contains around 17 000 small entries (15 properties, integers, small strings, and one 0-5 array of integers).

The first query to finish takes 2 500ms (on the emulator with debugging), the second takes 5 500ms.
The duration is roughly of the the same order on a release build on the emulator.

I'm actually trying to replace the current database in my application, based on the ill-fated react-native-couchbase-lite with pouchdb + react-native adapter. I had query responses in <500ms so this seems a bit slow, and both queries where finished at the same time.

We can't use the asynctorage backend as we have multiple base that each go beyond the default size limit.

Is there a limitation on concurrent queries?

**Comment by pubkey** [comment]
Have you tried other asyncstorage-adapters?
It would be interesting to see if the performance changes in a significant way.

**Comment by mleduque** [comment]
I tried to use pouchdb-adapter-asyncstorage from https://github.com/stockulus/pouchdb-react-native.
I was suprised because the application became unsufferably slow, even before the queries themselves. As soon as the database is created it seems very slow (like something is using the whole cpu time).

I'd try other adapters too, what are the other ones you know ?

**Comment by froatsnook** [comment]
I had very bad performance with this adapter for pouchdb-find as well as for compact operations (although when I glanced at the source code it looked like compact was a no-op).  My solution was to stop using find, and instead call allDocs once on app startup which is pretty fast, and then stick all the documents in my redux store and work with them directly.

**Comment by pubkey** [comment]
You could also replicate the asyncstorage pouch-instance with an in-memory instance.

**Comment by mleduque** [comment]
I'll have to try that, but that doesn't seem intuitive. Thanks for the
advice.

2017-10-25 12:49 GMT+02:00 Daniel M <notifications@github.com>:
