### ISSUE TITLE
Is it possible to reopen DB's connection after db.close() ?

### ISSUE THREAD

**Issue by efratyo** [pouchdb/pouchdb#6806]
I have an app with multiple DBs and an option to switch between them.
I'm using `db.close()` for the current DB when switching to another, in order to avoid memory leaks.
I thought that using `new PouchDB(uniqueId)` will 'reopen' the closed DB when I'm switching back to it.
But still when switching back to the first DB, I can't get it's replication back working.
I can't find an option in the documentation for 'reopening' DB's connection.
Is it possible?
Help will be so appreciated.

**Comment by pubkey** [comment]
Which adapter are you using?
I tried to reopen a closed instance with the indexeddb-adapter but never got it to work.

**Comment by gkiko** [comment]
@pubkey If you create `new PouchDB('name')` where _name_ is old database name won't it be reopened?

**Comment by uinstinct** [comment]
Can somebody please answer this question?

**Comment by pubkey** [comment]
@gkiko  reopening the database by creating it again, will throw with the error `Database not open`

**Comment by pubkey** [comment]
@gkiko creating the same database again will throw with `PouchError: database is closed`
