### ISSUE TITLE
db.close() not really free the file usage?

### ISSUE THREAD

**Issue by apolkingg8** [pouchdb/pouchdb#6808]
### Issue
I'm doing a feature like 'move db folder', logic like this:
```js
try {
    await imageDB.closeDB()
    await folderDB.closeDB()
    await settingDB.closeDB()
    await graveDB.closeDB()
} catch (err) {
    ipcSender.error('close db error')
    ipcSender.error(err)
    return false
}

try {
    fse.moveSync(this.config.dbDirPath, targetPath)
} catch (err) {
    ipcSender.error('move db folder error')
    ipcSender.error(err)
    return false
}
```
The `db.close()` works without error, but when I try to move the leveldb file, it's error with `EBUSY: resource busy or locked, unlink **\db\folder\LOG'`. Seams leveldb still using the file after `db.close()`.

### Info
- Environment: Electron 1.7.6 (node 7.8.0)
- Platform: Windows 10
- Adapter: LevelDB
- Server: none

**Comment by singhshashi** [comment]
What is the exact code inside closeDB() methods?

**Comment by apolkingg8** [comment]
@singhshashi as simple as native like that:
```js
class ImageDB {
    
    db = null

    constructor() {
        this.initDB()
    }

    initDB = ()=> {
        PouchDB.plugin(require('pouchdb-upsert'))
        PouchDB.plugin(require('pouchdb-find'))
        this.db = new PouchDB(dbPath, {
            adapter: 'leveldb',
            revs_limit: 1,
        })
    }

    closeDB = ()=> {
        this.db.close()
    }
}
```

**Comment by singhshashi** [comment]
I think that  `await ImageDB.closeDB()` will work if the closeDB returns a promise, which is not the case here. 

Try
```

closeDB = () => {
  return this.db.close();
}
```

or 

```
closeDB = () => {
   return new Promise(function(fulfill,reject) {
       this.db.close().then(function(){
        fulfill();
       }).catch(function(err){
          reject(err);
      });
});
}
```
See if that works.

**Comment by apolkingg8** [comment]
sorry I had typo, it's
```js
closeDB = () => {
  return this.db.close();
}
```
just like you said.

**Comment by singhshashi** [comment]
You mentioned electron. Where is this code getting called from main or renderer? Could it be that another renderer process has a lock on the file?

**Comment by apolkingg8** [comment]
It's all from `main` process. I don't think I did any db access from `render` process without `ipc` (is it possible?). I will try reproduce this issue with a clean project.

**Comment by daleharvey** [comment]
Similiarly we call leveldb's close method from ours @ https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-leveldb-core/src/index.js#L1169, I cant see any other open connections we maintain so seems like an issue with level / electron
