### ISSUE TITLE
doc_ids and batch_size bug during replication

### ISSUE THREAD

**Issue by mikeymckay** [pouchdb/pouchdb#6809]
### Issue
If the number of docs in doc_ids is larger than batch size, then not all docs will be replicated

### Info
- Environment: browser
- Platform: Chrome
- Adapter: default, replicating with http
- Server: CouchDB

### Reproduce
cloudDB.replicate.to database,
  doc_ids: [
    "user.mmckay"
    "user.hmkali"
    "user.mtash"
  ]
  batch_size: 1
.on "complete", (r) ->
  console.log r

This results in:
Object {ok: true, start_time: Tue Oct 24 2017 11:26:58 GMT+0300 (EAT), docs_read: 1, docs_written: 1, doc_write_failures: 0…}

Change the batch_size to 3 and you get:
Object {ok: true, start_time: Tue Oct 24 2017 11:27:29 GMT+0300 (EAT), docs_read: 3, docs_written: 3, doc_write_failures: 0…}

**Comment by jjal** [comment]
This is painful for us at the moment, don't know if anyone has time for a fix
