### ISSUE TITLE
Strategy for dealing with conflicts around deletions

### ISSUE THREAD

**Issue by froatsnook** [pouchdb/pouchdb#6810]
### Issue
I have an app using pouchdb which syncs with Cloudant.  Since documents are modified both by the users and the system, and sometimes users are offline, I have somewhat frequent conflicts.  Here's my problem:

* Document 1-a is modified on laptop generating 2-b
* Document 1-a is _manually deleted_ on PC, generating 2-c (`{ _deleted: true }`)
* Replication happens
* Document reappears on PC confusing the user (for my app, manual deletions should always win in conflict resolution!)

What confused me is that pouchdb didn't show me any conflicts.  I figured out that this is because `_deleted: true` looks the same as a resolved conflict.

This led me to realize that the difference between `doc._conflicts` and the results of `open_revs: "all"` is that open_revs shows the `_deleted: true` "tombstones" which could either be resolved conflicts or manual deletions.

What is the normal strategy for dealing with this type of conflict?  One idea I had was to put `{ _deleted: true, manuallyDeleted: true }` instead of just `{ _deleted: true }` when the user deletes a document, and then after a sync I could go through the database and delete any winning conflicts when the user attempted to delete that document.

Thanks for reading.

### Info
- Environment: browser/react native
- Platform: N/A
- Adapter: IndexedDB/WebSQL
- Server: Cloudant

### Reproduce
* Sync between A and B
* Take A offline and modify a document
* Delete document on B
* Sync between A and B

**Comment by daleharvey** [comment]
Yup, the way to currently fix this is to use your own deleted flag, in pouchdb and couchdb conflicts are non deleted leafs and conflicts are resolved by deleting them, once the deletion happens they are not in conflict

**Comment by froatsnook** [comment]
Thanks @daleharvey
