### ISSUE TITLE
Invalid Adaptor: websql in IOS Xamarin web view application

### ISSUE THREAD

**Issue by ashokkumar863** [pouchdb/pouchdb#6811]
### Issue
Pouch DB
Invalid Adaptor: websql in IOS Xamarin web view application

### Info
- Environment: (hybrid node js App)
- Platform: (IOS 11 safari)
- Adapter: (WebSQL)

### Reproduce
 PouchDB.plugin(require('pouchdb-adapter-node-websql'));
         var db = new PouchDB('mydb', {adapter: 'websql'});

if I leave specifying the adaptor, it is throwing "Invalid Adapto: Undefined"

**Comment by daleharvey** [comment]
Happy to take a fix but sounds like a bug in xamarin
