### ISSUE TITLE
pouchdb-ajax: support storing cookies on Node.js

### ISSUE THREAD

**Issue by ptitjes** [pouchdb/pouchdb#6814]
### Issue
On Node.js, PouchDB does not hold a cookie jar for cookies received from server during authentication. It uses the `request` Node.js module to make HTTP requests but it does not configure it correctly to hold a cookie jar.

For cookies to be stored on Node.js, `pouchdb-ajax`'s line https://github.com/pouchdb/pouchdb/blob/4bd9c087402102994f6cec6bfc54caaebafffb25/packages/node_modules/pouchdb-ajax/src/request.js#L3 should at least be
```js
export default require('request').defaults({
  jar: true
});
```

### Info
- Environment: Node.js server (not on same host as CouchDB)
- Platform: Node.js + Express
- Adapter: Http
- Server: Private remote CouchDB with SSL proxy, cookie authentication and properly configured CORS

### Reproduce

1. Connect from a Node.js server to a remote CouchDB with cookie authentication.
2. Make a simple get query to see that the AuthSession cookie is not transmitted.

I don't know how I could setup a jsbin or such to demonstrate it, because I have no idea how I should mock a CouchDB. Please tell me if and how it is possible to do that.

**Comment by ThibaultJanBeyer** [comment]
Nice, this is a fix I was looking for for a long time now! I’ll try it out the upcoming days.
If it works, I think it could potentially also close #6683 .
