### ISSUE TITLE
Find() performance problem

### ISSUE THREAD

**Issue by pixelarbeit** [pouchdb/pouchdb#6822]
### Issue
PouchDBs find function is pretty slow running in a hybrid app on a mobile phone. 

**pouchdb.find()**
- 1s: limit 20, selector {type: 'properties'}
- 20s: limit 20, selector {type: 'properties', title: {$gt: null}}

**pouchdb.query()**
- .6s: limit 20, view by type, including docs

**pouchdb.allDocs()**
- 4s: include_docs, array.filter, array.sort

takes 20s to get 20 files out of 3000 (index already created).
pouchdb.query() takes only about 20 second for getting a view filtered for the type. Am I doing anything wrong?

### Info
- Environment: hybrid app (ionic)
- Platform: Android/etc.
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce

    this.db.createIndex({
        index: {fields: ['type', 'title']}
    }).then((e) => {
        console.log('Index created.')
        return this.db.find({
            selector: {
                    type: 'properties',
                    title: {$gt: null}
                ]
            },
            sort: ['title'],
            limit: 10,
        })
    })

**Comment by pixelarbeit** [comment]
Just compared PouchDB to SQLite for Cordova. Actually I thought PouchDB wolud be faster, because it's using IndexedDB which is implemented natively by the browser manufacturers.

    SELECT * FROM properties ORDER BY title;

Runs in 0.23s retrieving the whole set of 3000 rows. So it's even faster than pouchdb.query() and selectors are not decreasing the speed as with pouchdb.find().

**Comment by dharders** [comment]
@pixelarbeit Are you using cordova-plugin-sqlite-2 or similar?

Check out [https://pouchdb.com/adapters.html#pouchdb_in_the_browser](https://pouchdb.com/adapters.html#pouchdb_in_the_browser) [https://github.com/litehelpers/Cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage) and the pouch adapter [https://github.com/pouchdb-community/pouchdb-adapter-cordova-sqlite](https://github.com/pouchdb-community/pouchdb-adapter-cordova-sqlite)

**Comment by pixelarbeit** [comment]
I was using PouchDB with IndexedDB which was pretty slow. I compared it to pure cordova-sqlite-storage plugin which was way faster. Didn't get the adapter to work, so I couldn't check if this would improve the PouchDB performance.

**Comment by nerumo** [comment]
I'm also facing similar issues. With aprox. 20'000 records, on a tablet it takes like >3 minutes to query the index for the first time. I'm still investigating, but it doesn't look good :(

**Comment by pixelarbeit** [comment]
@nerumo Is it only the first query when creating the index? I think this may take some time. But for me the problem remained even after creating the index.

**Comment by nerumo** [comment]
@pixelarbeit yes, my issues is around indexing. The query time wasn't a problem so far. Just that I get you correctly: after the createIndex call, only the design document is created. No data has been indexed yet. When you say "after creating the index", you mean that the data has already been indexed?

**Comment by pixelarbeit** [comment]
@nerumo I think when "createIndex" is done, your index should be already created. So first call of "createIndex" will take some time. After that every createIndex-Call will use the index created before. My problem was, that even after createIndex ran, it took 20secs to query that index.

**Comment by garrensmith** [comment]
@pixelarbeit its worth running the test again. But don't create an index first. Just do the query. Just let it default to using _all_docs.

**Comment by pixelarbeit** [comment]
@garrensmith I already changed my projects db, so I cannot test it right now. I did test pouch.allDocs() as mentioned in the first post, but I did not try pouchdb.find() without an index.

**Comment by cepm-nate** [comment]
Pixelarbiet, do you have any comparisons between indexedDB adapter and cordova-sqlite-storage plugin? I'm using indexedDB and it is horribly slow compared to raw SQL. For now I'm using LokiJS as a front-end to query the latest data, but it's a PITA to make sure that LokiJS is always up-to-date. (The feed from PouchDB seems to fail when the app resumes from standby sometimes).

so I'd be interested in seeing if cordova-sqlite-storage plugin is a lot faster.

**Comment by pixelarbeit** [comment]
@cepm-nate As I stated here https://github.com/pouchdb/pouchdb/issues/6822#issuecomment-341880062 I switched from PouchDB to SQLite Plugin (not SQL-Adapter). So I can't tell whether PouchDB would be faster with SQL Adapter, but SQLite Plugin is way faster than PouchDB when doing searches.

**Comment by cepm-nate** [comment]
@pixelarbeit. Thanks for replying. I've done a few queries in both, and here are my results 

**(iPhone s5) (5700K records):**

- PDB + iDB on non-indexed field=1441ms. 
- PDB + iDB indexed on that field: 1521ms.
- PDB + SQLite on non-indexed field: 1449 ms (same speeds as iDB)
- PDB + SQLite indexed on field: 500ms! (3x faster than the other methods).
- LokiJS without index on field: 15-18ms. 
- LokiJS indexed on the field: 1.2-1.5ms. Yes, 1.2 - 1.5 ms.

**Below: Raw SQLite DB: same 5700K records, plus another 400K non-related records**
- Same query: non-indexed: 35ms. 
- With an index on that field: 28ms.

Perhaps they will help someone else. :-)

**Comment by dnhyde** [comment]
Reopen this issue! Same problem here

**Comment by alokps6295** [comment]
i have to fetch single document from 18000 rec. I am using pouchdb with sqliteadaptor but it taking too much time.

**Comment by rasgo-cc** [comment]
Shall I assume that some of the performance issues with pouchdb-find come from the fact it always`include_docs`? See here: https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-find/src/adapters/local/find/index.js#L87

Can't grasp why this is necessary if an index is previously created.
In my specifc case, I would like to retrieve only the _ids of the documents so I can fetch the actual docs later on.

For example, for pagination:
I'd like to use find() to filter/sort data by some keys. Let's say I have 100k docs but I only show 100 docs per page.  find() would give me all the _ids in the right order and I would do a `bulkGet()` for each slice/page of the _ids.

Any thoughs on this?
