### ISSUE TITLE
In pouchdb-utils guardedConsole, should `console === 'undefined'` be `typeof console === 'undefined`?

### ISSUE THREAD

**Issue by browndav** [pouchdb/pouchdb#6823]
### Issue

In https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-utils/src/guardedConsole.js#L3, it looks like there's an attempt to test for the existence of `console`, but – as far as I can tell – a `typeof` operator should be present.

The code in git tests `console === 'undefined'`, but looks like it should test `typeof console === 'undefined'`.

### Info
- Environment: Node.js, Rollup, PhantomJS, Mocha/Chai
- Platform: Mac OS X 10.12.6
- Adapter: WebSQL (PhantomJS)
- Server: Local only

### Reproduce
REPL> delete console;
REPL> console === 'undefined'
ReferenceError: console is not defined
REPL> typeof console === 'undefined'
true

**Comment by alxndrsn** [comment]
Or `console !== undefined` 🙂

**Comment by daleharvey** [comment]
If you wanted to PR this to typeof console I would be happy to merge, havent seen this cause any problems but I am more comfortable with typeof

**Comment by alxndrsn** [comment]
@browndav PR submitted 🙂

**Comment by daleharvey** [comment]
And fixed, cheers
