### ISSUE TITLE
Replication thrashing on large sequence histories

### ISSUE THREAD

**Issue by jacwright** [pouchdb/pouchdb#6827]
### Issue
When the database passes a certain number of revisions replication thrashes and the database can't finish replicating to pouchdb.

### Info
- Environment: browser
- Platform: Chrome/FF/Safari
- Adapter: IndexedDB
- Server: Cloudant

### Reproduce
I've not put together a test-bed for reproducing. The use-case is for high-update traffic, the sequence number for two of these databases is 1619-*** and 4502-***. When the data is already on disk it is fine. When it tries to replicate to a fresh pouchdb thrashing occurs and it freezes up for a time. It doesn't seem to ever finish replicating.

Here is a screenshot of a performance recording on Chrome to show what is going on. Is this a known issue? Are there any workarounds?

![screen shot 2017-11-06 at 10 20 04 am](https://user-images.githubusercontent.com/120294/32454995-2388269e-c2de-11e7-806a-f102667f673c.png)

Thank you!!!

**Comment by willholley** [comment]
@jacwright it looks like stemming is hurting performance - you could try reducing the revs_limit to e.g. 50 on the Cloudant side (1000 is the default), though this might increase the chance of conflicts being generated if writes are distributed between PouchDB instances.

A few questions:
 * How rapid are the updates on the Cloudant side? 
 * Are the documents highly conflicted already?
 * If documents are continuously updated, when do you expect replication to finish?

**Comment by jacwright** [comment]
Thanks for replying @willholley!

The app is an offline-first novel-writing app, and documents are saved every 30 seconds as an author writes their app in order to keep things synced and avoid data loss. Each person has their own database in Cloudant, so the updates aren't very rapid per-user. The main issue is when they login on another computer (especially a fresh login without any existing local data) the sync has this thrashing. This is happening to users who have been using the app for just a couple of weeks (of heavy writing though).

There may be an occasional conflict, but generally they aren't conflicted.

On app startup I run an initial 1-time replication and present a progress dialog if it is more than 100 updates to track the progress. Once done, the dialog goes away if it was presented. After the initial replication, I then set up continuous replication starting with "since: 'now'" just for keeping things in sync.

In the above situation, the initial replication never finishes. The dialog freezes in its progress tracking. If I refresh the page, the dialog never shows and the fans kick in. After a few minutes (forever in user-time with a less-responsive app), the thrashing stops and things quiet down, but the initial non-continuous replication never finishes. There is still missing data. And another refresh of the browser causes the high CPU cycle over again. The initial replication doesn't ever finish.

**Comment by jacwright** [comment]
I have fixed one customer experiencing this issue by creating a new database for them with all their documents copied (not replicated) over from their existing database in cloudant, and then deleting and replicating their local pouchdb with the fresh database that has no history. This obviously isn't an ideal solution.

One thing to note, this is happening on a fresh replication from cloudant to a new pouchdb database. There is no conflicting going on.

Existing conflicts are handled by the app, deleting the unwanted conflicts and saving the correct revision as a new version. So conflicted leaf nodes shouldn't be hanging around either, though it is possible there might be some.

Is there a way to fix the data rather than starting with a fresh database? Would finding and fixing conflicts in Cloudant solve it?

**Comment by jacwright** [comment]
Putting the revs_limit to 100 helped. I will go with that for now since there isn't high likelihood for many conflicts. Do you have any other recommendations for my situation to keep things running smoothly?

**Comment by jacwright** [comment]
Although putting the revs_limit down helps, I still have issues replicating. Even putting it at 10 doesn't help some cases. Still getting high CPU, fans kicking in, etc. I'm not the first to experience this am I?

**Comment by avickers** [comment]
Have you tried lowering the batch_size and batches_limit for the replication?

**Comment by jacwright** [comment]
I have not. I will look to see about doing that if it can help. Thank you.

**Comment by janl** [comment]
@jacwright can you tell us a little bit about your docs? Do you happen to have few docs that are relatively large? Like 10s or 100s (or more) of kbs? Or is it just a few dbs with long revision histories?
