### ISSUE TITLE
cannot set size option on typescript implementation 

### ISSUE THREAD

**Issue by intersides** [pouchdb/pouchdb#6830]
### Issue
I am using the typescript version of couchdb in a ionic application and when trying to increase the database size according to the link: [https://pouchdb.com/errors.html#not_enough_space](https://pouchdb.com/errors.html#not_enough_space)  I received the following error:
" Argument of type '{ size:number} ' is not assignable to parameter of type 'DatabaseConfiguration'. Object literal may only specify know properties, and 'size' does not exist in type 'DatabaseConfiguration'. "

### Info
- Environment: (ionic hybrid app)

### Reproduce
```
import PouchDB from 'pouchdb';

this.db = new PouchDB('user_${userId}', {size: 50});
```

**Comment by daleharvey** [comment]
Closing out typescript bugs, we do not use typescript for this repo and if typescript projects cant use other javascript projects then I would suggest that they fix that

**Comment by intersides** [comment]
I see... thanks.

**Comment by CarlosAyala** [comment]
@intersides 
Any luck? I have a similar issue.

**Comment by intersides** [comment]
Yes, I did a push request and I updated the repo . It should be now fixed on the latest version. Let me know if it is not the case.

**Comment by intersides** [comment]
@CarlosAyala I did not find the update but you can for now modify your definition file by adding...

`size?: number;`

around  line 516 of index.d.ts (node_modules/@types/pouchdb-core/index.d.ts), inside the interface declaration.

from 

`          

    interface LocalDatabaseConfiguration extends CommonDatabaseConfiguration {
            auto_compaction?: boolean;
            revs_limit?: number;
        }
`
to 

`          

    interface LocalDatabaseConfiguration extends CommonDatabaseConfiguration {
            auto_compaction?: boolean;
            revs_limit?: number;
            size?: number;
}
`
