### ISSUE TITLE
Single integration test causing occasional CI failures (selenium:firefox)

### ISSUE THREAD

**Issue by dharders** [pouchdb/pouchdb#6835]
### Issue
Tests have been flaky lately, see issue #6831

I believe a single test in `test.attachments.js`, "_3961 Many attachments on same doc_", is the cause.

The test saturates the browser connections, as designed, with replication of many attachments. However, it sometimes leads to selenium:firefox failures (mostly unhandled timeout exceptions) and blocks other development/tests. 

Under the advice of @daleharvey, we intend to skip the test so CI can hopefully become stable again and leave this issue open until the bug/test is resolved.

### Info
CI Test Suite
Most failures seem to be in combination of selenium:firefox and CouchDB 1.6.x

### Reproduce
Submit a PR and watch the failures rain...

**Comment by alxndrsn** [comment]
Re-opening: the test is still skipped.

**Comment by SourceR85** [comment]
Imo this can be closed:
#8569 un-skiped the test
