### ISSUE TITLE
[question] Should database's _security docs not to be in sync? 

### ISSUE THREAD

**Issue by MtDalPizzol** [pouchdb/pouchdb#6840]
Sorry for asking this here, but I tried StackOverflow for the last 3 questions about PouchDB and got no answer. Feel free to to close this.

So, I have a use case where one user can grant access to others, adding them to the `members` array of the `_security` document of a database. I'd like to enable users to be added as members while the app is offline. So, everything is OK with my remote DB, but the local one doesn't have the `_security` document, which seems not to be syncing between both DBs, even with the user logged in and with the right permissions. Is this the expected behavior? If yes, is there another way to approach this, or will I have to only allow users to be added while online?

**Comment by daleharvey** [comment]
So people more involved with couch will likely be able to answer this better however I will take a guess that `_security` documents are not real documents and do not show in changes / sync, @willholley @janl sound right?

One option would be to not call it `_security`, give it another document name and have a little process on the server that writes `security` whenever it sees / validates changes to your security template document?

**Comment by MtDalPizzol** [comment]
Thanks, Dale! Actually, I went through the docs again and I found some important statements:

If you're not in an Admin Party, **only server admins can PUT `_security` documents**. So, I'll need a proxy server with admin credentials to CouchDB anyway. And, because of this, there's no reason to keep `_security` in sync.

So, I'll have another document describing which users can access the database. When this document syncs, I'll trigger a request to update the `_security` document accordingly. Something like this:

```javascript
localUserDB
  .sync(remoteUserDB, {
    live: true,
    retry: true,
    include_docs: true
  })
  .on('change', function (change) {
    if (change.direction === 'pull') {
      return;
    }

    var bucketDoc = _.find(change.change.docs, '_id', 'buckets');

    if (bucketDoc) {
      console.log('Sync change: handle _security coument here!', bucketDoc);
    }
  })
  .on('error', function (error) {
    console.log('Couldn\'t sync databases due to: ', error);
  });
```

**Comment by willholley** [comment]
Just to add to this, @daleharvey is correct that `_security` objects are not documents and so will not get sync'd, even as an admin.

**Comment by daleharvey** [comment]
Great, sounds sorted cheers
