### ISSUE TITLE
Find Mango query to remote database returns no results

### ISSUE THREAD

**Issue by faizanahemad** [pouchdb/pouchdb#6843]
### Issue
While using db.find with a remote database and supplying regex for any fields it does not return any result.

### Info
- Environment: Node.js and chrome browser
- Platform: Chrome
- Adapter: NA
- Server: CouchDB
- PouchDB version: 6.3.4

### Reproduce
- Setup local CouchDB
- create database in it named `history`
- Insert some entries of the form below. 1 is enough to test.
```json
{
  "_id": "3W46wCqDhELOtCdS",
  "href": "http://www.geeksforgeeks.org/efficient-search-in-an-array-where-difference-between-adjacent-is-1/",
  "title": "efficient search in an array where difference between adjacent is 1"
}
```
- Setup PouchDB with PouchDB find plugin
- Connect to couchDB by using pouchDB in your node script / browser and try doing find query.
```javascript
var remoteDB = new PouchDB('http://localhost:5984/history')
var regex=new RegExp("difference", "i");

remoteDB.find({selector:{href: {$regex:regex}}}).then(r=>r.docs).then(console.log)

// Above will fail with 400 (Bad Request)

remoteDB.find({selector:{href: {$regex:/difference/i}}}).then(r=>r.docs).then(console.log)

// Above will fail with 400 (Bad Request)

remoteDB.find({selector:{href: {$regex:regex.toString()}}}).then(r=>r.docs).then(console.log)

// Above will not throw 400, but return empty results.

remoteDB.find({selector:{href: {$regex:"(?i)difference"}}}).then(r=>r.docs).then(console.log)

// above works
remoteDB.find({selector:{href: {$regex:"difference"}}}).then(r=>r.docs).then(console.log)

// also works
```

### Further Investigation
- On seeing `pouchdb.js` non minified file, that I downloaded. I find that on line 10884 `options.body = JSON.stringify(options.body);` to serialize the request for sending we use `JSON.stringify` which produces `{}` for regexes.

**Comment by daleharvey** [comment]
Yup

> JSON.stringify({test:/testing/});
> "{\"test\":{}}"

will need to send as a string, but we can fix up that case

**Comment by JohnOllhorn** [comment]
I'm trying to receive a document with a specific value.

It's not a standard value, so I use indexes, but I really get this error every time, no matter what I do.

```
Object { error: "unknown_error", reason: "undef", ref: 1520140480, status: 500, name: "unknown_error", message: "undef" } new.vue:249
```


My last state is:

```
var db = new PouchDB('http://localhost:5984/addressdata')
      db.createIndex({ index: { fields: ['cid'] } })
        .then(function () {
          db.find(JSON.stringify({ selector: { cid: {$eq: 'b0c31dcd-9d92-b4ed-5b81-42870e493337'} } }))
            .then(r => r.docs)
            .then(console.log)
            .catch(function (err) { console.log(err) })
        })
        .catch(function (err) { console.log(err) })
```

Please write me something I should do.

**Comment by garrensmith** [comment]
Hi @JohnOllhorn 

You don't need to do the `JONS.stringify({selector})`. Just do

```
var db = new PouchDB('http://localhost:5984/addressdata')
      db.createIndex({ index: { fields: ['cid'] } })
        .then(function () {
          db.find({ selector: { cid: {$eq: 'b0c31dcd-9d92-b4ed-5b81-42870e493337'} } })
            .then(r => r.docs)
            .then(console.log)
            .catch(function (err) { console.log(err) })
        })
        .catch(function (err) { console.log(err) })

```

**Comment by JohnOllhorn** [comment]
does not change anything
