### ISSUE TITLE
Reopening issue #2448 (bulkDocs documentation wrong in pouchdb.com API)

### ISSUE THREAD

**Issue by group131** [pouchdb/pouchdb#6845]
### Issue
I have a similar behavior with issue #2448. I use bulkDocs to upload files. If json starts with 

> {"docs":[{
>   "_id": "2017-11-13T10:47:17.643Z_1",... 

It works OK.

If I use 
>{ "_id": "2017-11-13T10:47:17.643Z_1",... 

I get error message "Missing JSON list of 'docs'"...

Am I doing something wrong or has this issue returned from the tomb?

### Info
- PouchDB version 6.3.4
- Environment: browser
- Platform: Any
- Adapter: IndexedDB
- Server: CouchDB

**Comment by daleharvey** [comment]
It either needs `{docs: []}` or `[]`, just a plain object will fail
