### ISSUE TITLE
Failed at the leveldown@1.5.0 install script.

### ISSUE THREAD

**Issue by arpecop** [pouchdb/pouchdb#6850]
Failed at the leveldown@1.5.0 install script.
Node 9.2.0 latest
OS: Linux / OSX
Should I downgrade Node or there is some sort of workaround ?

**Comment by singhshashi** [comment]
What failed? What were you trying to do? What was the error message?

**Comment by arpecop** [comment]
`prebuild ERR! build error
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/tmp/node_modules/node-gyp/lib/build.js:258:23)
prebuild ERR! stack     at ChildProcess.emit (events.js:159:13)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
prebuild ERR! not ok
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/tmp/node_modules/node-gyp/lib/build.js:258:23)
prebuild ERR! build     at ChildProcess.emit (events.js:159:13)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! leveldown@1.5.0 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the leveldown@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by daleharvey** [comment]
You may want to try this again, we are on leveldown 2.0.2 now which may help, otherwise you will want to take it up with level* as we dont do anything special, just a dep
