### ISSUE TITLE
allDocs with keys and IndexedDB should create only one transaction

### ISSUE THREAD

**Issue by nename0** [pouchdb/pouchdb#6854]
### Issue
Currently when calling allDocs with the `keys` option `pouchdb-core`([source](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/adapter.js#L751)) splits them into allDocs calls with one `key`. On the indexDB adapters this will create as many transactions as keys. From a bit of pure IndexedDB testing I found out that this can be made more perfomant when using just one transaction.
Test Results with 10000 entries in IndexDB and fetching 500 keys:
Chrome: 8x faster
Firefox: 2x faster

### Info
- Platform: Chrome 62 / FF 57

### Reproduce
I wrote the test with the pouchdb performance tests. If you want to reproduce them, I put them [here ](https://pastebin.com/2stvqXfi). (The code is not perfect; I should use `transaction.oncomplete` to know when its finished)

**Comment by daleharvey** [comment]
Fixed

**Comment by alxndrsn** [comment]
From brief profiling:

Fetching all docs from a production db containing 20,000 docs, `6.4.2` is about 100-400 times faster in Chrome than `6.3.4` and `6.1.2`.

I suspect this fix is the cause of the speedup.  Thanks to all involved!

**Comment by nename0** [comment]
Yeah, It really depends on the amount of keys you query. I even optimized my project (using pouchdb) to batch up key queries
