### ISSUE TITLE
_bulk_docs POST objects order on body missmatch the objects sequence order

### ISSUE THREAD

**Issue by agsv83** [pouchdb/pouchdb#6857]
### Issue
The order of the objects sent in the _bulk_docs POST request to remote, does not have the objects sequence order. This happens sometimes, and seems to happen randomly.

This is an issue when using the Couchbase Sync Gateway in our use case. We have some ACL objects that will grant permissions to users and roles on channels; if the object using the channels is sent before the ACL then it returns a 403.

If this is intended and it is not going to be fixed, becouse is not supposed to be a bug; please, I would like to know how to make this modification myself on the PouchDB library. Any points on how to do it will be appreciated.

### Info
- Environment: (browser)
- Platform: (Chrome)
- Adapter: (default)
- Server: (Couchbase, sync_gateway)

### Reproduce
Just write some objects and wait for the bulk operation to happen.

Here is the exact case
![image](https://user-images.githubusercontent.com/10196996/33074351-280d88fa-cec6-11e7-95c1-c9904fff0bc6.png)

The object "B55EA10F-6075-D095-8004-59E339918BB8" has local sequence "5", while the ACL object "74CC98E7-5DE1-6355-9728-EC38A91CD589", has local sequence of "3". But the message is sent the first on the _bulk_docs array body request.

To catch the requests bodys I added this code, maybe not the best way to do it:

`(function(send) {
  XMLHttpRequest.prototype.send = function() {
    var args = arguments
    this.addEventListener("readystatechange", function() {
      if (this.readyState == 4 && this.responseURL.match(/_bulk_docs/gi)) {
        if (args && args.length > 0) {
          var body = JSON.parse(args[0]);
          var docTypes = body.docs.map(function(item){ return item.type+'('+item._id+')'; });
          console.log('SEND-REQUEST-STATUS::_bulk_docs', docTypes);
        }
      }
    }, false);
    return send.apply(this, arguments);
  };
})(XMLHttpRequest.prototype.send);`

**Comment by janl** [comment]
This is not something CouchDB guarantees. The same would apply to _design/ docs including a validate_doc_update function. Say the _design doc has seq 3 and blocks docs of the type `foo` which got written with seq 5. Due to replication execution/scheduling/network-errors, etc. it could happen that the doc `foo` on seq 5 arrives on the target CouchDB before the _design doc blocking this arrives on the server, allowing the write.

If you want to make sure that ddocs/acls are on the server before you replicate, best to POST them yourself, or sync/replicate with the `ids` option, before doing a general sync.

**Comment by agsv83** [comment]
Hi janl,

thanks for your quick response. I think I understad what you mean there, and I see the point of it when there are multiple _bulk_docs requests, so the ACL objects could not be in the same request as the permission relative objects. In this particular case, there are all sent on the same _bulk_docs request; so there should not be any problem derived from connection errors, because all will fail at the same time.

I think the same about calling replicate with this ids if there is no connection, because it will fail too; also I don't know how to fetch which acl objects are missing replication on the remote database, to make this replication by ids.

I'm not totaly sure about this, but I think that the "couchbase-lite" sdk already does this kind of order by local sequence number when it sends the request to the gateway, because we are not facing this issue with it. Only when the ACL and the relative permission objects are in different _bulk_docs requests (this is going to be reported to the CSG support). Maybe this is a problem very specific to the CSG.

Forgive me if I sound stupid, I just want to fully undestand what is going on, and how can I achive the same results as the "couchbase-lite" on the gateway, in this particular case. Having different behaviours in the sdk and pouchdb is being a bit problematic.

Thanks again for your help on this.

**Comment by agsv83** [comment]
Hi again,

following janl's proposal on my tests did the trick as spected, with a stable connection.

For now, it could be enought. The steps are:
1) stop the life push replicator before creating the local documents
2) after every required document is created (acl, etc) localy start de push replicator as oneshot
3) then start the replicator as life
4) write every permission related object here.

Anyway, if there is a way to order the objects by seq number on push to remote db, it will be nice to now where it should be done and how.

Thanks.

**Comment by daleharvey** [comment]
Yup as mentioned on IRC for this type of change we would definitely want to be matching behaviour on couchdb, doing acl updates seperately and prior to replication sounds like a sensible way to resolve this, cheers
