### ISSUE TITLE
Losing Typescript definitions because of named default export

### ISSUE THREAD

**Issue by selfrefactor** [pouchdb/pouchdb#6862]
### Issue
Currently an ugly hack is required to use `PouchDB` within Typescript project and I lose the typing definitions along the way.

```
import * as PouchDBLib from 'pouchdb'

const {default:PouchDB} = PouchDBLib as any

PouchDB.plugin(require('pouchdb-authentication'))
```

### Info
- Environment: (Node.js/browser/hybrid app/etc.) - Node 9.0.0
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.) - Ubuntu
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.) - default
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.) - no server involved yet

### Reproduce
Write the steps for others to reproduce issue here. Providing a code example, links to a repository or a live example (JSBin etc) are even more helpful.

I stumbled across this bug in this file, which is part of a Typescript project: [https://github.com/selfrefactor/admin-panel/blob/typescript/src/main/sagas/checkPouchLoginSaga.ts](https://github.com/selfrefactor/admin-panel/blob/typescript/src/main/sagas/checkPouchLoginSaga.ts)

**Comment by daleharvey** [comment]
This is one of many bugs where typescript cant handle using javascript libraries, happy to accept any PR's to improve the situation but not tracking typescripts inabilities to work with javascript in this project, cheers

**Comment by selfrefactor** [comment]
Can you just clarify the status of the issue?
I see lots of typescript definitions and yet they are unusable. Is that means that this is the current state, i.e. not workable?

**Comment by daleharvey** [comment]
PouchDB does not use typescript in any way, I believe there is another project attempting to create typescript binding seperately but not part of core pouchdb which is a plain js project
