### ISSUE TITLE
Missing return on allDocs of indexeddb adapter

### ISSUE THREAD

**Issue by nename0** [pouchdb/pouchdb#6864]
In @dharders PR there is a return missing in the [allDocs implementation of indexeddb adapter](https://github.com/pouchdb/pouchdb/pull/6833/files#diff-dbb317186915d268eca5f85f5456363dR49). When running the integration tests in chrome I noticed this. It will throw this error `once called more than once`, because callback is called multiple times on allDocs

**Comment by nename0** [comment]
And another one [here](https://github.com/dharders/pouchdb/blob/b34bd432f5699da8e56ab9f5ef0c581afa7d60ed/packages/node_modules/pouchdb-adapter-indexeddb/src/allDocs.js#L49)

**Comment by nename0** [comment]
Ok a bit of investigation yielded that this error is only detected on chrome because firefox does not support [`unhandledrejection`](https://developer.mozilla.org/de/docs/Web/API/WindowEventHandlers/onunhandledrejection) which we use [here](https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.setup_global_hooks.js#L11). Therefore in travis this error is not detected and the build goes on.

**Comment by dharders** [comment]
Thanks @nename0 . Yeah, simple mistake must have slipped through after I rebased and had to manually copy/paste some code from another local branch.

See PR #6873
