### ISSUE TITLE
unhandledrejection not supported in firefox but required for integration tests

### ISSUE THREAD

**Issue by nename0** [pouchdb/pouchdb#6869]
### Issue
Ok a bit of investigation for #6864 yielded that this error is only detected on chrome because firefox does not support [`unhandledrejection`](https://developer.mozilla.org/de/docs/Web/API/WindowEventHandlers/onunhandledrejection) which we use [here](https://github.com/pouchdb/pouchdb/blob/f4ccbcc1b22484baf418602f1b8096ab544e5309/tests/integration/test.setup_global_hooks.js). Therefore in travis this error is not detected and the build goes on.

### Info
- Platform: FF

### Reproduce
Run the NEXT=1 integration test on `test.all_docs.js` (to get it working see #6870) in chrome and firefox, Both will get the #6864 error but only in chrome mocha will fail due to the set hooks

**Comment by nename0** [comment]
This might be fixed by using a Promise Polyfill. `lie` does support unhandledrejection only in node. However the lie code could be copied and changed for out needs.

**Comment by daleharvey** [comment]
This will be fixed in firefox (it just got prioritised) so while it is a genuine problem I would not worry too much about it, I think we should remove `lie` from our codebase and expect people who are using Pouchdb on platforms without Promise to polyfill it themselves

**Comment by nename0** [comment]
So this is something we should look into when firefox supports it: [Mozilla BugTracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1362272)

**Comment by daleharvey** [comment]
So we won't release pouchdb-next or any official pouch without testing in chrome, with unhandledrejection so

**Comment by daleharvey** [comment]
No need to track, at some.point Firefox will support it and our coverage will go up
