### ISSUE TITLE
$or in $and behaves unexpected

### ISSUE THREAD

**Issue by konradjurk** [pouchdb/pouchdb#6879]
Example code to be executed on your website http://nolanlawson.github.io/pouchdb-find/

```
db.find({
  selector: {
    $and: [
      {
        $or: [
          {
            name: 'Donkey Kong'
          },
          {
            name: 'Captain Falcon'
          }
          ]
      },
      {
        $or: [
          {
            debut: 1981
          },
          {
            debut: 1982
          }
          ]
      }
      ]
  },
  sort: ['_id']
});
```

This equals to the logic expression `((name == 'Donkey Kong' || name == 'Captain Falcon') && (deput == 1981 || deput == 1982))` which would resolve as `false` if `name` is Mario, hower the result of PouchDB as you can see on the website includes a record named Mario.

If this is a bug, how can we fix this? If not, how do I achieve something equal to the logic expression?

**Comment by fenglianxu** [comment]
I have done many tests in pouchDB with a combination of $and and $or, as well with nested of both operators.  I have found a common pattern that the explicit $and does not work in PouchDB.
When you change the **$and** to be an implicit format such as  {$and[ {x > y}, {u <z}] }==>
{ x > y ,
  u < z
}
This implicit format works, however this needs each CouchDB client to change their code and it's very time consuming to make effort to make the more complex of mixture of the $and and $or operators.
It would be nice for PouchDB to support this explicit $and in the query so it behaves same as CouchDB.

**Comment by tomjmul** [comment]
This does look like a bug. 

```
{
 "selector": {
   "$and": [
   {
     "$or": [
       {"a": 1},
       {"a": 2}
     ]
   },
   {
     "$or": [
       {"b": 1},
       {"b": 2}
     ]
   }]
 }
}
```

The above query gets rewritten to an implicit $and, and in so doing, the first $or key gets overwritten by the second:

{
 "selector": {
   "$or": [
       {"b": 1},
       {"b": 2}
     ]
 }
}

**Comment by konradjurk** [comment]
Programmatically adding a "wontfix" label to a bug in one of the most basic query functionalities a database can have (and/or) is a big joke from my point of view. Thats probably why there are 3k closed issues...

**Comment by konradjurk** [comment]
Oh it got removed. Intelligent bot
