### ISSUE TITLE
\u0000 in document IDs

### ISSUE THREAD

**Issue by ig3** [pouchdb/pouchdb#6881]
### Issue
An old application running pouchdb 5.3.2-prerelease, which has been running without problems for many months is failing to sync/replicate recently after many documents with \u0000 in their IDs have been introduced. They are on the server and sync is now failing with 404 errors whenever one of the docs with \u0000 in the ID is requested.

The format of the ID is very much like that described for collate: https://github.com/pouchdb/collate

I haven't checked exhaustively but the docs with \u0000 in the IDs appear to be copies of existing docs that do not have the \u0000 in the IDs. I am not aware of anything the app does intentionally to generate such IDs. In general, the IDs are all guids generated in the client. 

It is a very old version of pouchdb and I should probably try updating to current, but if anyone can suggest where I might look to find the source of these document IDs, it would be appreciated. I would prefer to understand what has gone wrong before introducing changes.

### Info
- Environment: (browser)
- Platform: (Chrome/FF/various)
- Adapter: (IndexedDB/WebSQL/etc. - I'm not sure as various browsers are used by different users)
- Server: (CouchDB 1.6)

### Reproduce
I don't know how it happened or how to reproduce it. It may relate to someone trying a different browser. One user recently was trying to get the application working on a tablet or smartphone.

**Comment by ig3** [comment]
An example of a problematic ID is "54cja78ustk00003m5i6kdedip8\u00004cja78ustk00003m5i6kdedip8\u0000\u0000".

**Comment by daleharvey** [comment]
this vaguelly sounds like another bug where map reduce documents were being writting to the wrong database,I cant really remember if it was a bug with us or with the underlying storage, definitely shouldnt happen

**Comment by ig3** [comment]
Thanks Dale. Looking through the code, the id looks like something toIndexableString might produce, possibly as called from updateViewInQueue. Whatever it is, it has only occurred twice in about two years of application use so quite a rare event. Given one of the users recently testing alternate devices and browsers, a bug in the underlying storage of something tested seems likely.

At this point, I think I'll get on with updating PouchDB, which would be a good thing anyway and, with a bit of luck, will prevent this happening again.
