### ISSUE TITLE
use_index doesn't work even when the index exists

### ISSUE THREAD

**Issue by visylvius** [pouchdb/pouchdb#6882]
### Issue
Write the description of the issue here
Im currently using the db.find method and providing the optional key of use_index, I've even checked to make sure that index exists. However it throws an error saying that the index can't be found.
### Info
- Environment: Mobile
- Platform: React Native
- Adapter: WebSQL
- Server: PouchDB

### Reproduce
Write the steps for others to reproduce issue here. Providing a code example, links to a repository or a live example (JSBin etc) are even more helpful.
```
constructor () {
    super()
    this.db.createIndex({
      index: {
        fields: ['title', 'created_at', 'updated_at', 'id', 'version'],
        ddoc: 'process-index',
        name: 'process-index',
      },
    }).then((result) => {
      console.log(result)
    })
  }

try {
      const doc = await this.db.get(id)
      console.log({doc})
      await this.db.put({
        _id: id,
        _rev: doc._rev,
        data,
        meta_data: doc.meta_data,
        last_looked_at: isUpdate ? new Date().toISOString() : doc.last_looked_at,
      })
      const otherResults = await this.db.getIndexes()
      console.log(otherResults)
      const results = await this.db.find({
        selector: {
          'data.id': {
            $eq: id,
          },
        },
        use_index: 'process-index',
      })
```
![screen shot 2017-11-28 at 5 03 17 pm](https://user-images.githubusercontent.com/11020847/33352518-18a53212-d45e-11e7-9d42-606b1663100a.png)

can't give a live example as its using company code.

**Comment by ptitjes** [comment]
@visylvius Could you try with the full form of `use_index`, just to narrow the problem please ?
> use_index (Optional) Set which index to use for the query. It can be “design-doc-name” or “[‘design-doc-name’, ‘name’]”.

**Comment by visylvius** [comment]
Hi @ptitjes. Thanks for responding to my post so quickly. My apologies, I forgot to mention that I had already tried using the use_index with the array format, and ran into the same error

**Comment by ptitjes** [comment]
@visylvius Then I'm dry :p

**Comment by visylvius** [comment]
Haha. Fair. Its certainly a weird error.

**Comment by avickers** [comment]
Try `fields: ['data.title', 'data.created_at', 'data.updated_at', 'data.id', 'data.version'],`

Notice your selector is for data.id, but your index field is id.

**Comment by visylvius** [comment]
Ill give that a try. Thanks!
