### ISSUE TITLE
Changes feed includes object having seq same as since passed

### ISSUE THREAD

**Issue by vnt-github** [pouchdb/pouchdb#6883]
### Issue
In changes API, when since is passed as string then PouchDB returns response including document having "**seq** equals **options.since**".

since is passed as string when we expose PouchDB externally to another PouchDB. This caused the replication to never end cos the results of changes is never empty.

### Info
- Environment: Node.js
- Platform: Chrome,FF
- Adapter: LevelDB
- Server: PouchDB Server

### Reproduce
Hit changes with since as string

### Example
**API:**
db.changes({ since: "809", limit: 2 })

**Response:**
{
    "results": [
        {
            "id": "1234",
            "changes": [{  "rev": "1-20f99004cd74d129e073e490eb02c344" }],
            "seq": 809
        },
        {
            "id": "_design/replication",
            "changes": [{"rev": "2-6c8d737e56b84ef7935e72e1bf5cb569"}],
            "seq": 811
        }
    ],
    "last_seq": 811
}

**Comment by daleharvey** [comment]
Just a heads up, will need more than this is will have to close

**Comment by daleharvey** [comment]
So took a look at this, you need to maintain the type of since and cant just pass it around as a string as "1" and 1 collate differently
