### ISSUE TITLE
Enable stale issue closer on pouchdb

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#6884]
I would like to enable https://github.com/probot/stale on pouchdb, there are huge amounts of old feature requests / discussions / bugs that are no longer relevant in the 270 long list and it takes too much time and arbitrary decision making to prune them all, time that I would rather spend on current issues people are having.

If there are issues you feel strongly should still be tracked, the bot will give a 7 day warning on an issue being closed and simply commenting will keep it open (we can use special labels for issues that we never want to close), the bot by default marks inactive after 60 days of inactivity and closes 7 days later, I think the defaults sound fine.

Speak now or forever hold your peace :)

**Comment by willholley** [comment]
+1

**Comment by daleharvey** [comment]
ok done, expect a bit of an influx of traffic over the next few days but then will die down and will have a much cleaner and easier to follow set of issues, cheers
