### ISSUE TITLE
Node Modules installation For React js app but getting the following error . Please help on the same

### ISSUE THREAD

**Issue by maiharun98444** [pouchdb/pouchdb#6891]
### Issue
Have existing package.json, When i try to do npm install, getting the following error

D:\project\click-frontend>npm install

> protagonist@1.6.8 install D:\project\click-frontend\node_modules\protagonist
> node-gyp rebuild

D:\project\click-frontend\node_modules\protagonist>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\project\click-frontend\node_modules\protagonist
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> node-zopfli@2.0.2 install D:\project\click-frontend\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@8.2.1 (node-v57 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\project\click-frontend\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\project\click-frontend\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\project\click-frontend\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\project\\click-frontend\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\project\\click-frontend\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=D:\\project\\click-frontend\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64"
gyp ERR! cwd D:\project\click-frontend\node_modules\node-zopfli
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe D:\project\click-frontend\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\project\click-frontend\node_modules\node-zopfli\lib\binding\node-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=D:\project\click-frontend\node_modules\node-zopfli\lib\binding\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\project\click-frontend\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:921:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\project\\click-frontend\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\project\click-frontend\node_modules\node-zopfli
node-pre-gyp ERR! node -v v8.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe D:\project\click-frontend\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\project\click-frontend\node_modules\node-zopfli\lib\binding\node-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=D:\project\click-frontend\node_modules\node-zopfli\lib\binding\node-v57-win32-x64' (1)

> leveldown@1.5.0 install D:\project\click-frontend\node_modules\leveldown
> prebuild --install

prebuild info begin Prebuild version 4.5.0
prebuild info looking for local prebuild @ prebuilds\leveldown-v1.5.0-node-v57-win32-x64.tar.gz
prebuild info looking for cached prebuild @ C:\Users\M1041415\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.5.0-leveldown-v1.5.0-node-v57-win32-x64.tar.gz
prebuild http request GET https://github.com/level/leveldown/releases/download/v1.5.0/leveldown-v1.5.0-node-v57-win32-x64.tar.gz
prebuild WARN install connect ETIMEDOUT 192.30.255.113:443
prebuild info install We will now try to compile from source.
prebuild verb starting node-gyp process
prebuild verb execute node-gyp with `node index.js rebuild --target=v8.2.1 --target_arch=x64`
prebuild verb ok
prebuild verb ok
prebuild ERR! configure error
prebuild ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
prebuild ERR! stack     at PythonFinder.failNoPython (D:\project\click-frontend\node_modules\node-gyp\lib\configure.js:483:19)
prebuild ERR! stack     at PythonFinder.<anonymous> (D:\project\click-frontend\node_modules\node-gyp\lib\configure.js:508:16)
prebuild ERR! stack     at D:\project\click-frontend\node_modules\graceful-fs\polyfills.js:284:29
prebuild ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
prebuild ERR! not ok
prebuild ERR! build Error: Can't find Python executable "python", you can set the PYTHON env variable.
prebuild ERR! build     at PythonFinder.failNoPython (D:\project\click-frontend\node_modules\node-gyp\lib\configure.js:483:19)
prebuild ERR! build     at PythonFinder.<anonymous> (D:\project\click-frontend\node_modules\node-gyp\lib\configure.js:508:16)
prebuild ERR! build     at D:\project\click-frontend\node_modules\graceful-fs\polyfills.js:284:29
prebuild ERR! build     at FSReqWrap.oncomplete (fs.js:152:21)
npm WARN react-test-renderer@15.6.2 requires a peer of react@^15.6.2 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: protagonist@1.6.8 (node_modules\protagonist):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: protagonist@1.6.8 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.2 (node_modules\node-zopfli):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.2 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! leveldown@1.5.0 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the leveldown@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\M1041415\AppData\Roaming\npm-cache\_logs\2017-11-30T13_04_13_345Z-debug.log

### Info
$ npm version
{ npm: '5.3.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  node: '8.2.1',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.13.1',
  v8: '5.8.283.41',
  zlib: '1.2.11' }

**Comment by daleharvey** [comment]
The error is that is cant find python

    gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

according to https://github.com/nodejs/node-gyp/issues/1268 it also needs to be python 3, if you continue to have problems these are leveldown / node-gyp issues, not pouchdb, we just have it as a dep
