### ISSUE TITLE
Memory adapter in React Native

### ISSUE THREAD

**Issue by chmac** [pouchdb/pouchdb#6894]
I tried to use the `pouchdb-adapter-memory` in React Native, but I got this error:

    error: bundling failed: UnableToResolveError: Unable to resolve module `stream` from `app/node_modules/sublevel-pouchdb/node_modules/readable-stream/readable.js`: Module does not exist in the module map

It looks like `stream` is not available in React Native. I tried adding the `react-native-stream` package into the `node_modules/stream` directory, but that also produced another error.

Should the memory adapter work in react-native? Can we somehow tell it to behave as if it was running in a browser, and if so, could that help?

**Comment by daleharvey** [comment]
Can you depend on `pouchdb-browser`? to use the browser only version, there is also https://github.com/stockulus/pouchdb-react-native which looks specifically for react native

**Comment by chmac** [comment]
Will check `pouchdb-browser`. We're using the `pouchdb-react-native` package with `pouchdb-adapter-react-native-sqlite` and `react-native-sqlite-2`. I wonder if `pouchdb-browser` will place nicely with those other packages. Will test.

Replication is taking 10-20s to insert 100 docs of about 100KB each. Fetching them is fast, but the insert process with the setup above is taking up to 20 minutes to get our 9k documents. Read performance is also pretty slow. It can take 4s to get the full database of 9k documents. I was considering the memory adapter as a performance improvement, to put it in front of the sqlite adapter.

PS> Ahoy from Edinburgh today @daleharvey! :-)

**Comment by chmac** [comment]
Today, copying the `react-native-streams` package from `node_modules/react-native-stream` to `node_modules/stream` appears to work. Problem solved.
