### ISSUE TITLE
[Question] Understanding performance of the memory adapter

### ISSUE THREAD

**Issue by chmac** [pouchdb/pouchdb#6896]
I'm using the `pouchdb-adapter-memory` in React Native. #6894

I'm trying to understand the performance of the memory adapter. I was hoping to use it as a performance enhancement replicated from a local sqlite database.

If I run `Db.allDocs({include_docs: true})` it consistently takes >1s to return 9k documents of about 100KB each. If I save the result into a javascript array and use lodash to filter like `_.find(docs, {...})` that operation takes about 5ms. It seems like PouchDB with the memory adapter is two orders of magnitude slower.

I'm just starting with PouchDB, so I could well be doing something horribly wrong. Do these numbers sound "normal" for PouchDB? Any advice on how to improve performance any further?

I've spent a couple of days on this performance issue now. I assumed that PouchDB in React Native would be highly performant. So far most approaches that I've tried are significantly slower than fetching data via GraphQL / HTTP. Somehow I feel like getting data locally from the disk ought to be nearly instant, and that I must be badly abusing PouchDB for it to be so slow. But perhaps I'm missing some bigger point, and this kind of performance is normal for PouchDB. I'd be grateful for any input from those with more PouchDB experience.

**Comment by efratyo** [comment]
Hi  @chmac , 
I'm also facing performance issues with pouchdb on react-native.
I have tried to install pouchdb-adapter-memory but I'm getting errors regarding a package of 'levelup'.
Were you facing the same problem? 
What RN version are you using, if I may ask?

**Comment by chmac** [comment]
@efratyo We're running `0.50.3`. I did have to do a lot of hacking to get the memory adapter working, although I don't remember the precise steps. In the end we had to abandon PouchDB altogether, the performance we were seeing was so atrocious web requests were faster. We're using request-graphql, noramlizr, redux, and redux-persist now to store our data offline. It's not as elegant for updates and sync, but it performs as you'd expect from disk on the device. Good luck. :-)

**Comment by daleharvey** [comment]
So the memory adapter is built as a level adapter and so while I haven't looked at the code I would expect it to have some overhead involved for that reason, also pouchdb will likely always have some performance being traded off for the ability to sync that things like iodash do not need to worry about. That said for alldocs requests I would expect a direct memory adapter for pouchdb (not via level) should probably get close to the same performance. Raw memory speed is not a huge priority at the moment as the focus is on pouchdb find performance, as you have moved away from this will close out, cheers
