### ISSUE TITLE
PouchDB in a WebExtension (requests from https to http)

### ISSUE THREAD

**Issue by mauro-belgiovine** [pouchdb/pouchdb#6904]
### Issue
This is my very first attempt to use PouchDB/CouchDB, so apologize if this will sound trivial to you.
I managed to set up CouchDB locally on my MBPro and PouchDB for a WebExtension in Firefox 57 and Google Chrome 62. Local DB is working perfectly in the webpage context, but when I try to replicate the local DB on it's remote counterpart, the sync request always results in a "canceled" status. This is the sync output in this case:

> _events: Object { newListener: [17]</</ro/<(), removeListener: [17]</</ro/<() }
> **canceled: true**
> catch: function [17]</</ro/this.catch()
> pull: Object { cancelled: true, state: "cancelled", _readyCalled: true, … }
> pullPaused: true
> push: Object { cancelled: true, state: "cancelled", _readyCalled: true, … }
> pushPaused: true
> then: function [17]</</ro/this.then()
> __proto__: Object { cancel: [17]</</ro.prototype.cancel(), … }

 I tried to replicate my code in a standalone html file and synchronization works without any issue with the remote server (even without setting up the http server). sync output is the following:

> _events: Object { newListener: ro/<(), removeListener: ro/<() }
> **canceled: false**
> catch: function ro/this.catch()
> pull: Object { cancelled: false, state: "pending", _readyCalled: true, … }
> pullPaused: true
> push: Object { cancelled: false, state: "pending", _readyCalled: true, … }
> pushPaused: true
> then: function ro/this.then()
> __proto__: Object { cancel: [17]</</ro.prototype.cancel(), … }

The part in bold is the only clear difference I've been able to notice between the two cases. Can you tell me what's going on? Is it a protocol issue related to the fact that I'm running the extension on a website that uses https and I'm making calls to one that uses http?

### Info
- Environment: plain JS and PouchDB
- Platform: FF 57 & GC 62 on MacBook Pro (OSX High Sierra)
- Adapter: none
- Server: local PouchDB server (using the Mac App)

### Reproduce
This is the code ivolving PuchDB I'm using in both WebExtension and standalone page:
```
function showMittens(db) {
        console.log(db);
    }
    function pushDoc(db,doc) {
        db.put(doc);
    }
    function sync(db, remote) {
        var sync = db.sync(remote);
        console.log(sync);
    }

    var db = new PouchDB("mittens");
    var remoteCouch = new PouchDB("http://localhost:5984/mittens");
    
    db.changes({
       since: "now",
       live: true
    }).on('change', showMittens);
    
   var node = {
       _id: new Date().toISOString(),
       title: "this is a test",
       completed: false
   };

    pushDoc(db,node);
    sync(db, remoteCouch);
```

**Comment by daleharvey** [comment]
If its working a webpage but not a webextension, sounds like a webextension issue, I believe webextensions requires that you ask for permission to make requests to urls in the extension manifest, have you done that?

**Comment by mauro-belgiovine** [comment]
> I believe webextensions requires that you ask for permission to make requests to urls in the extension manifest, have you done that?

You are right, I was missing both manifest permissions and user authentication. 
If anyone will find it useful, in order to make the web extension work with my local CouchDB I fixed manifest.js adding this:
```
"permissions": [
                    "*://127.0.0.1/"
                    ]
```
and, after the single-node CouchDB setup, modified the JS code for remote db object creation like this:
```
var user = {
    name: 'adminusername',
    password: 'adminpassword'
};

var remoteCouch = new PouchDB('http://127.0.0.1:5984/kittens',{
                              auth: {
                              username: user.name,
                              password: user.password
                              }
                    });
```



Everything works now!
