### ISSUE TITLE
Remove References in Docs to PouchDB Inspector Chrome Extension

### ISSUE THREAD

**Issue by shennan** [pouchdb/pouchdb#6908]
### Issue
Although [the Chrome Extension for inspecting PouchDB is now gone](https://github.com/pouchdb/pouchdb-fauxton-chrome-extension/issues/17), a reference to it still remains in the docs.

### Info
N/A

### Reproduce
Go to the [databases page](https://pouchdb.com/guides/databases.html#debugging) to see references to the now-gone PouchDB Inspector.

<img width="740" alt="screen shot 2017-12-03 at 11 37 20" src="https://user-images.githubusercontent.com/1840398/33525105-9333f714-d820-11e7-9cfd-9702d1c68e7a.png">

**Comment by shennan** [comment]
[Pull request here](https://github.com/pouchdb/pouchdb/pull/6909)

**Comment by daleharvey** [comment]
And fixed, thank you :)

**Comment by dheimoz** [comment]
hey @LifeIsStrange will take a look and reach you in case I have questions.
Thanks for the effort.
