### ISSUE TITLE
Upgrade leveldown

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#6910]
It looks like this is going to be a bit of a challenge so opening its own issue

**Comment by daleharvey** [comment]
See https://github.com/pouchdb/pouchdb/pull/6906

**Comment by ralphtheninja** [comment]
@daleharvey Remind me again, what's the simplest way of running the tests locally for PouchDB? I forget.

**Comment by daleharvey** [comment]
Its no bother, I keep meaning to get it to the point to where `npm test` just works, but you need to install a server right now first, easiest way is `npm install pouchdb-server && ./node_modules/.bin/pouchdb-server` then `GREP=migration npm test` should just work (fail with the level upgrades)

**Comment by ZeeCoder** [comment]
So this issue is about the leveldown 2.1.1 version, right?
But doesn't it work with 1.7.2, as that is merged in already?

Couldn't that be released before the bigger upgrade to v2?

**Comment by ralphtheninja** [comment]
> So this issue is about the leveldown 2.1.1 version, right?

Yes.

**Comment by ralphtheninja** [comment]
I could take a stab at this, but might need someone to hold my hand.

**Comment by daleharvey** [comment]
I would be happy to, can't schedule much IRC time but will make sure to get back to any questions in here
