### ISSUE TITLE
Update Sauce Labs logo

### ISSUE THREAD

**Issue by billmcgee** [pouchdb/pouchdb#6911]
### Issue
Sauce Labs is providing PouchDB with an Open Sauce testing account and we would like to request an update to the logo that appears on https://pouchdb.com/. The logo should link to http://saucelabs.com

### Info
- Environment: all
- Platform: all
- Adapter: n/a
- Server: n/a

### Reproduce
Visit https://pouchdb.com/

Thanks!
![saucelabs_41x41](https://user-images.githubusercontent.com/6098022/33566987-933bb52e-d8d6-11e7-9d6a-e755232d36da.png)

**Comment by daleharvey** [comment]
Hey @billmcgee 
Yup definitely didnt notice the logo change, could you point me to an svg copy of the new logo?
Cheers

**Comment by nickcolley** [comment]
@daleharvey I'll pick this up if you fancy, once we've got the SVG version.

**Comment by billmcgee** [comment]
Thank you @nickcolley and @daleharvey, SVG version is attached.

[badge-41x41.svg.zip](https://github.com/pouchdb/pouchdb/files/1532861/badge-41x41.svg.zip)

Please to let me know if we need to provide anything further.

**Comment by nickcolley** [comment]
Optimised with https://jakearchibald.github.io/svgomg/

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 41 41">
  <path fill="#e12826" d="M5.32 26.31a16.3 16.3 0 0 1 17.5-21.9L21 6.25l-.5-.01A14.28 14.28 0 0 0 6.77 24.38h12.48l-5.21 9.82 12.61-12.73H9.5L28.76 2.2a20.07 20.07 0 0 0-18.73 35.41l6-11.3H5.33z"/>
  <path fill="#e12826" d="M30.96 3.38l-6 11.3h10.7a16.24 16.24 0 0 1-17.54 21.9l1.82-1.83h.56A14.28 14.28 0 0 0 34.76 20.5s0-2.08-.54-3.88H21.75l5.2-9.84-12.8 12.75h17.2L12.23 38.79A20.07 20.07 0 0 0 30.96 3.38z"/>
</svg>
```

**Comment by daleharvey** [comment]
Awesome, @nickcolley definitely be happy for you to do the PR

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/pull/6928
