### ISSUE TITLE
Pouch not syncing local changes on iOS 11

### ISSUE THREAD

**Issue by alexmills** [pouchdb/pouchdb#6912]
### Issue

I have a React/Redux app that's been working fine in production. Since iOS 11 has come out, PouchDB has been having some significant issues. The main one I haven't been able to solve is that PouchDB no longer syncs local changes made on iOS 11 devices.

In the normal world, this is what happens: 

#### Chrome (Mac/Android) / iOS 10 - Works Perfect
*Launch App*
`Sync Resumed`
`Sync Paused`
*Make a change to db*
`Sync Resumed`
`Sync Change - { direction: 'push'...}`
`Sync Paused`

But on the new iOS, it's not working

#### iOS 11 Safari/Home Screen (iPhone/iPad) - Broken

*Launch App*
`Sync Resumed`
`Sync Paused`
*Make a change to db*
`...` Nothing Happens

Have you guys seen anything similar with your projects? No errors are thrown and changes made remotely are pulled down correctly, just nothing local is submitted.

### Info
- Environment: (Browser)
- Platform: (Chrome/FF/Safari/iOS/Android)
- Server: (CouchDB)

**Comment by alexmills** [comment]
Looks like the issue is that iOS 11 (or WKWebView) is much stricter at enforcing the `4 maximum concurrent connections to the same host`.

[NSURLSession](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1407597-httpmaximumconnectionsperhost?language=objc)

If I split my DB's over two different URL's (to the same CouchDB server) it all works perfectly.

I'll leave this open a little longer until I've completed extensive testing.

**Comment by mohshraim** [comment]
About sync problem
what is Pouch adapter you are using?
I think i face this problem before and solve it with **fruitdown** adapter..
and now its stable on my development environment.

**Comment by daleharvey** [comment]
Sounds fixed
