### ISSUE TITLE
pouchDb last sync requests taking too long to respond

### ISSUE THREAD

**Issue by satheeshck17** [pouchdb/pouchdb#6913]
I've made an application in ionic V1 using pouchDb and couchDb databases. Everything was working fine, except for some loading problem. When I initially start the application, pouchDb tries to fetch changes from couchDb, but the last sync request is taking too long to finish, sometimes more than 10 minutes or so. Due to this, all operations on pouchDb are also taking too much time.
`couchDb version is 1.6.1`
`pouchDb version is 6.1.1`

![capture](https://user-images.githubusercontent.com/34262019/33591481-cf399232-d9ab-11e7-8932-85cb2c965928.JPG)
Is this a problem with pouchDb/couchDb? Did anyone experienced this problem?

Thank You

**Comment by daleharvey** [comment]
You are doing a `live: true` replication right? this request is a longpoll request that is waiting for changes to appear on the server, its not affecting the local database. If you dont want to wait for changes then remove `live: true`

**Comment by satheeshck17** [comment]
Thanks for that info. But Still it's taking too long for the pouchDB to respond during startup.
When I had less documents, it was faster. But now there are almost 1000 documents (without counting revisions and deleted documents),

**Comment by daleharvey** [comment]
ok,if you want investigate what your startup issue is, possible causes and fixes etc and file a bug on that it would be great, cheers
