### ISSUE TITLE
Help Wanted, Sync sub data from huge one

### ISSUE THREAD

**Issue by mohshraim** [pouchdb/pouchdb#6919]
I want to help for this scenario if someone guide me please.

I have a CouchDB with **over 1 mill doc.**
Web, Mobile users have local offline sub data with **around 1K doc** that should be kept replicated...

Have already implement my filter function on CouchDB and its works fine.. something like filter `doc.type =='item'`

but the problem **on first load** that user when start sync, i cant include `since` option that i want all the docs of type items to be stored locally offline,,  **THIS will load the server and push him to read the whole 1 mill doc to filter my target doc.** 

--> while i only need 1k docs that i can fitch with `dbremote.allDocs({ startkey: item, endkey: item\ufff0})`   --> but after this i need a work around to insert it on my localDB and start sync without adding a new revision and push it as changes to server again...

-and i cant use Pouch-load as there is no options for filter doc ids or attributes like type...!

any guide appreciated 
Thanks

**Comment by qwe123wsx** [comment]
you can try using pouchdb replication selector filtering options

options.selector: Filter using a query/pouchdb-find selector. Note: Selectors are not supported in CouchDB 1.x.

**Comment by daleharvey** [comment]
Yup thats the correct solution here, or to take a look at adding filtering support for pouchdb dump / load, they definitely have some type of filtering support, but may be able to improve if they dont currently cover your needs

**Comment by mohshraim** [comment]
Thanks @qwe123wsx , 

I mentioned that i Have already implement my filter function on CouchDB and its works fine.. something like filter doc.type =='item'
this good for continues sync..

but the problem on first load that user when start sync, i cant include since option that i want all the docs of type items to be stored locally offline,, 
**-> THIS will consume server resources and push him to read the whole 1 mill doc to filter my target doc.**
**-> another drawback user will have a big delay getting his data until server read the whole db** 

Solving this from CouchDB are work around like another filtered DB,, this not practical on big data to keep splitting.. not a real solution.

Really getting confused if there is any big products with SAS using CouchDB.. its amazing but very limited.

And Thanks @daleharvey, i have read the whole documentation and found the pouchLoad, but need implementation to filter, i am not sure !! 
but really still evaluating CouchDB from several months so i can't work on filter before a final decision on CouchDB.
