### ISSUE TITLE
The great Bower to NPM migration is here ☸ 🚂

### ISSUE THREAD

**Issue by rjsteinert** [pouchdb/pouchdb#6926]
Projects such as Polymer are migrating from Bower to using Yarn with a package.json that has `"flat": true` and getting dependencies from the NPM registry only to find that things in the NPM registry don't always play nicely with the new ES6 module way of doing things. A possible nice first step would be if PouchDB published on npm the build that puts PouchDB in the global namespace. Our solution for now is to __keep using bower__ for packages like pouchdb that haven't caught up with this bower to npm migration.

Relevant Polymer announcement here -> https://www.polymer-project.org/blog/2017-08-22-npm-modules

![oregon_trail_1280w2](https://user-images.githubusercontent.com/156575/33770705-ad32291c-dbfc-11e7-99d6-8049ef448079.jpg)

**Comment by nickcolley** [comment]
We'd also want to consider removing bower as an option potentially.

@rjsteinert would this be solved by publishing the build referenced by Nolan here? https://github.com/pouchdb/pouchdb/issues/6404#issuecomment-304727759
