### ISSUE TITLE
To slack or not to slack

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#6931]
So my hosting is now broken again and will need me to spend hours resetting up certificates etc to get http://slack.pouchdb.com/ up and running again, never mind the ongoing maintenance of running the slack bot

Given that Slacks usage looks to be decreasing, its a minority of our users and requires not insignificant maintenance to make it even possible to use for newcomers, I am not sure its suitable to be recommending for communication in an open source project

If slack has fixed this and provides the ability to do open signup, or there is some solution that doesnt require maintaining then happy to support / integrate that, just dont want to be doing any more server admin :)

**Comment by avickers** [comment]
Most OSS projects seem to be using either Gitter or Discord these days.

**Comment by pubkey** [comment]
I also think gitter is a better solution for this. The usability to stay up-to-date when discussing on more than on OSS-Project is better because I don't have to check many slacks per day.

**Comment by daleharvey** [comment]
Gitter looked pretty nice when I found it, and happy for people to use whichever platform they would like to discuss thing, was just looking to not do slack server maintenance anymore however @janl has very kindly offered to do so, Jan should we organise it in here?

**Comment by scriptjs** [comment]
gitter please

**Comment by daleharvey** [comment]
So asking other people to do slack maintenance doesnt 1. resolve me of being ultimately resposible for it if its linked here and 2. change the fact it is not an appropriate tool for OSS projects and I do not feel comfortable promoting it as so. removed the slack links @ https://github.com/pouchdb/pouchdb/commit/d1ec9c5fb977c8c5733b475d15cb035c52a9af47, the site / bridge will stay up until they stop working
