### ISSUE TITLE
Release 6.4

### ISSUE THREAD

**Issue by ZeeCoder** [pouchdb/pouchdb#6935]
As mentioned in this PR: https://github.com/pouchdb/pouchdb/pull/6906#issuecomment-349948449

I need 1.7.x leveldown version to compile pouchdb with our CI setup.

Is there any plan to make a release, or otherwise how could I get it in the meantime?

**Comment by daleharvey** [comment]
So yup, I plan on doing a bunch of completely breaking (although hopefully wont actually break anyone) changes soon, so good to do a release asap, will get to work on one

**Comment by ZeeCoder** [comment]
Thank you! 🎉 
I'll keep a close eye on this issue then. ;)

**Comment by daleharvey** [comment]
And the release is done :)

**Comment by ZeeCoder** [comment]
Thank you so much @daleharvey !
I'll try it out as soon as possible!

**Comment by garrensmith** [comment]
Well done everyone. Thank you for this release

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ZeeCoder** [comment]
I can confirm the new release can be installed on CentOS, so our CI is finally running the tests 👍
Only issue I found is that since most dependencies in the package.json are fixed version numbers instead of ranges, at first I was getting both 6.3.4 and 6.4.0 in my lock file. 🤔

It's ok now though.
