### ISSUE TITLE
Switch HTTP Adapters to use fetch

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#6944]
Requirement for https://github.com/pouchdb/pouchdb/issues/5322

Now that browsers have implemented the fetch api with cancellation, switch to using that in the http adapters, this removes all of pouchdb-ajax dependency. 

We will try to avoid polyfilling it, ie 11 is the only major holdout and people can polyfill themselves for that.

**Comment by loic** [comment]
What's the plan on Node / `pouchdb-server`? I'm especially concerned about the cookies story.

**Comment by Magellol** [comment]
@daleharvey 
>browsers have implemented the fetch api with cancellation

Didn't know fetch was cancellable natively. Are we sure about that, I wouldn't think native promises are cancellable in any way.

**Comment by daleharvey** [comment]
Yup https://developers.google.com/web/updates/2017/09/abortable-fetch, I have a working implementation @ https://github.com/pouchdb/pouchdb/pull/7059

**Comment by gr2m** [comment]
what do you plan to use for the fetch implementation in Node?

**Comment by ptitjes** [comment]
@daleharvey I did not follow your latest developments so I ask. Does dropping cookie support on Node.js will make [tests/component/test.ajax.js](https://github.com/pouchdb/pouchdb/blob/master/tests/component/test.ajax.js) fail ? (I don't see it failing yet in CI on you WIP.)

Do you have any ideas yet about what actions we will have to take for authentication plugins, and other plugins that requires to share cookies with PouchDB itself, to still work with PouchDB 7.0 ?

**Comment by daleharvey** [comment]
Yeh I don't think we can drop that test / cookies working out of the box, was assuming that there would be a working fetch + cookies module in mode but we may need to fix / write one ourselves, will probably leave it last. But plugin authors should mostly only need to service from Ajax to fetch

**Comment by daleharvey** [comment]
https://github.com/pouchdb/pouchdb/commit/e35f949d1948913e4bb6a7f226de8b1af1c5d5c5
