### ISSUE TITLE
AssertionError ".status required, old abstract-leveldown"

### ISSUE THREAD

**Issue by pubkey** [pouchdb/pouchdb#6949]
### Issue
Using the localstorage-adapter does not work since 6.4.0.
It throws the following error when creating the db-instance:
```bash
AssertionError {name: "AssertionError", actual: "undefined", expected: "string", operator: "==", message: ".status required, old abstract-leveldown"…}
  actual: "undefined"
  expected: "string"
  generatedMessage: false
  message: ".status required, old abstract-leveldown"
  name: "AssertionError"
  operator: "=="
  stack: "AssertionError: .status required, old abstract-leveldown....

```

### Info
- Environment: browser
- Platform: Chrome/FF
- Adapter: localstorage

### Reproduce
1. Create a pouchdb-instance with the localstorage-adapter:
```js
const db = new PouchDB('mydb', {adapter:'localstorage'});
```

[Fiddle](https://jsfiddle.net/9wo8fLcq/1/)

**Comment by daleharvey** [comment]
Yup this was recently added to allowed failures due to https://github.com/pouchdb/pouchdb/pull/6941#issuecomment-352166744

**Comment by Nikonov** [comment]
Could you please, give more information? Can't use localstorage adapter since 6.4.0 ? How supports old browsers ?
