### ISSUE TITLE
Issue when device low on storage

### ISSUE THREAD

**Issue by jamie7893** [pouchdb/pouchdb#6954]
<img width="1433" alt="screen shot 2017-12-19 at 11 13 50 am" src="https://user-images.githubusercontent.com/15333506/34169685-cdf9162e-e4ad-11e7-8f95-351013cd7308.png">

### Issue

When a IOS device is low on storage, pouch stops working, the errror in the console says "LOADED DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
### Info
- Environment: (Node.js/browser/hybrid app/etc.)
 Mac Book Pro IOS 10.12.6 

- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
 Chrome - Version - 63.0.3239.84
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
IndexedDB - requested 50MB
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

### Reproduce
Fill up the storage of the device, until you get the 'Your disk is almost full' message (I had around 3GB left), refresh chrome, and try to access the database. Clearing up space makes the issue go away, and everything works fine. We have had this problem reported on multiple IOS devices as well.

this.db.get(documentId).then(function (result) {
     console.log(result)
}).catch(function (err) { 
    console.log(err);
});

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/e7790ac4f483311cde19983673a1bf89cd5871c3

**Comment by gbtec-michaelhoppe** [comment]
Hey @daleharvey,

any idea when this fix will be released?
