### ISSUE TITLE
'paused' callback is always called without arguments when using db.sync

### ISSUE THREAD

**Issue by n-e** [pouchdb/pouchdb#6959]
The API Reference says:

> paused (err) - This event fires when the replication is paused, either because a live replication is waiting for changes, or replication has temporarily failed, with err, and is attempting to resume.

When using db.replicate.from and db.replicate.to, the callback is called as described.
When using db.sync, the callback is always called without arguments.

I would have expected db.sync to work the same way as db.replicate

**Comment by akowald** [comment]
I am seeing this when sync is paused due to lost connection as well. Now there's no way to tell why a sync has paused. :disappointed:

**Comment by n-e** [comment]
Hi,

You can replace your call to sync with a call to replicate.to and another to replicate.from pending the resolution.
