### ISSUE TITLE
website is down :(

### ISSUE THREAD

**Issue by Niggler** [pouchdb/pouchdb#6965]
https://pouchdb.com/ "This site can't be reached"

http://downforeveryoneorjustme.com/pouchdb.com also confirms that pouchdb website is down.

**Comment by miguelrincon** [comment]
+1

**Comment by rytyr** [comment]
+1

**Comment by SkullMasher** [comment]
If a maintainer is reading this. Stay in vacation enjoy the Christmas break really. Have a good time for me.
For the Others you can go to the site as it was on December 7 2017 by clicking [this magic wayback machine link](https://web.archive.org/web/20171207112405/https://pouchdb.com/).

**Comment by daleharvey** [comment]
Cheers, fixed and hopefully next time the server randomly restarts nginx should start again

**Comment by iamjay** [comment]
It's down again.

**Comment by ritenv** [comment]
It is down again.

**Comment by jcplessis** [comment]
Down again ?

**Comment by TheDadi** [comment]
+1

**Comment by mcoquet** [comment]
https://pouchdb.com is down again :(

**Comment by daleharvey** [comment]
rebuilding the server so it doesnt go down again, working now?

**Comment by mcoquet** [comment]
@daleharvey sorry for the delay, only saw your message now. Its back up.
