### ISSUE TITLE
Incorrect offline message for PouchDB 5.0.0 (blog post) link

### ISSUE THREAD

**Issue by anaran** [pouchdb/pouchdb#6968]
See these links:

https://pouchdb.com/2015/10/06/pouchdb-5.0.0-five-years-of-pouchdb.html

  referenced from

https://github.com/pouchdb/pouchdb/wiki/Breaking-changes

Details:

Clicking the link in
PouchDB 5.0.0 (blog post)

results in a page claiming

```
Looks like you're offline...

You need to be online to see this page, once you've seen it once it'll be available offline in the future!
```

I am not offline and can view to 6.0.0 blog post just fine.

http://mzl.la/1vxCDgA

**Comment by michaeljota** [comment]
pouch page is down currently. See #6965

**Comment by daleharvey** [comment]
Fixed @ https://github.com/pouchdb/pouchdb/issues/6965
