### ISSUE TITLE
allDocs on indexedDB with keys and limit < keys.length

### ISSUE THREAD

**Issue by s-diez** [pouchdb/pouchdb#6971]
### Issue
If PouchDB().allDocs is executed with a "keys" option and a limit greater than the length of the array in the "keys" option the function will crash with the following error.

> index.es.js:909 Uncaught TypeError: cursor.continue is not a function
>    at onBatch (index.es.js:909)
>    at IDBRequest.docStore.get.onsuccess (index.es.js:739)

I could trace the problem to the function ["allDocsKeys"](https://github.com/nename0/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-idb/src/allDocs.js#L20). In Line 33 onBatch is called with an object as cursor instead of a valid cursor object. But under the described conditions cursor.continue would be called. 

### Info
- Environment: browser
- Platform: Chrome 63
- Adapter: IndexedDB

### Reproduce
Create a PouchDB-database with some documents. Query the database with "allDocs" with a "keys" option and a limit greater than the length of the array in the "keys" option.

**Comment by nename0** [comment]
Yeah thats probaply my fault: #6858

**Comment by nename0** [comment]
@s-diez Thanks for the report!
