### ISSUE TITLE
[Question] PouchDB single-file mode

### ISSUE THREAD

**Issue by s-panferov** [pouchdb/pouchdb#6972]
Hello. Is it possible to incorporate all pouchdb databases (including internal one like _replicator, _users, pouch__all_dbs__) into a single file? It's easier for user to open or backup a single file instead a folder with cryptic names inside. 

Ideal scenario for my app is when user just can click on a file with a custom extension (associated with an app) and it will open a database from the inside.

**Comment by garrensmith** [comment]
You most likely would have to write a custom backend plugin for that. You could use RocksDB with column families.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by daleharvey** [comment]
Yup none of the default adapters support that, although level does put it all in one folder, may be possible to turn that folder into some type of osx type package

**Comment by s-panferov** [comment]
Thanks, maybe I'll come up with some custom adapter if it is not very complicated.
