### ISSUE TITLE
(Critical) PouchDB Website has been DOWN for days

### ISSUE THREAD

**Issue by redcodered** [pouchdb/pouchdb#6979]
# PouchDB.com appears to be offline

* Severity: **CRITICAL**

At the time of this writing (2 Jan 18), `pouchdb.com` is offline, and as far as I can tell, has been down for a few days at least now. Full documentation and other content found on the website is unavailable.

**Comment by daleharvey** [comment]
Ugh, I keep restarting this, added it to init.d but seems like it must be crashing at this point

**Comment by daleharvey** [comment]
Yup, full hard drive, cleared it out and restarted, thanks

**Comment by nickcolley** [comment]
Thanks Dale :)

**Comment by ritenv** [comment]
It is down again.

**Comment by petegerhat** [comment]
Down again....
