### ISSUE TITLE
IE10 error with missing `btoa` function call

### ISSUE THREAD

**Issue by ZeeCoder** [pouchdb/pouchdb#6980]
### Issue
I'm getting the following error, when I try to sync data from one db to the other:
```
Failed to move logs from in-memory storage: {"name":"ReferenceError","message":"'btoa' is undefined"}. 
```

### Info
- Environment: (browser)
- Platform: IE10, potentially above
- Adapter: In-memory and IndexedDB

**Comment by daleharvey** [comment]
These seems very strange, ie10 has btoa

**Comment by ZeeCoder** [comment]
Yeah I know 🤔

**Comment by daleharvey** [comment]
Not only that but our test suite runs ie10 and is passing, are you sure there isn't something specific to your situation?

**Comment by ZeeCoder** [comment]
That sounds fishy, I'll double check to make sure.

**Comment by daleharvey** [comment]
So https://pouchdb-bug-helper.glitch.me/ is working in ie10, this sounds like a bug elsewhere or need more info

**Comment by ZeeCoder** [comment]
Does that use syncing from one DB to the other?
I sync from in-memory to IndexedDb in IE10, and that's when I got the error.
