### ISSUE TITLE
Need Help - Can someone do a Hangout code review, consulting in my App?

### ISSUE THREAD

**Issue by jrvlima** [pouchdb/pouchdb#6981]
### Issue
I was hired, as a freelancer, to do an environmental diagnostics in an area that suffered an environmental disaster here in Brazil. App users are visiting rural properties to collect information using the App, I'm new in PouchDB and in the first round of visits some users lost data. I did a lot of refactors, did more research, studied more PouchDB docs and I'm releasing a new version to improve stability. I was under if you guys can help me doing a code review in my PouchDB related code and give me some consulting. All issues I had I  researched in issues, docs, and forums about PouchDB.
 
### Info
- Environment: hybrid app
- Platform: Chrome/Android
- Adapter: IndexedDB
- Server: CouchDB

**Comment by daleharvey** [comment]
How you get someone to help review your code, but not an issue for us to track

**Comment by daleharvey** [comment]
*hope
