### ISSUE TITLE
Issues with attachments

### ISSUE THREAD

**Issue by jrvlima** [pouchdb/pouchdb#6985]
### Issue
I'm facing issues fetching attachments in production, I save the attachment, for the first time I'm able to see it, but them when I open the form again, I'm not able anymore.

### Info
- Environment: hybrid app
- Platform: Chrome/Android
- Adapter: IndexedDB
- Server: CouchDB
- Plugins: pouchdb-relational, pouchdb-find

#### Saving Attachment

https://gist.github.com/jrvlima/10c715a061031d301b6ffbfb6f3673d2
https://gist.github.com/jrvlima/f289b7bdd5daa20f29159f45de1ea3a7

#### Getting Attachments

https://gist.github.com/jrvlima/718f372c9c8fc51cedcd413b19b9fbd7

**Comment by daleharvey** [comment]
Hey, I have created a little demo that lets you upload filess, view them and delete them @ https://intelligent-judo.glitch.me/, its all working fine for me here, could you test on your platform or edit it to show the bug you are seeing? cheers

**Comment by daleharvey** [comment]
Need more information to debug
