### ISSUE TITLE
web site [pouchdb.com] may be hung up

### ISSUE THREAD

**Issue by 74sharlock** [pouchdb/pouchdb#6993]
![image](https://user-images.githubusercontent.com/7920399/34663830-c4f140ce-f493-11e7-80dc-b50871daac80.png)

**Comment by jakallergis** [comment]
same here. (Greece)

**Comment by nickcolley** [comment]
As far as I know @daleharvey has access to fix problems like this.

I'd be willing to help out with these kinds of issues in the future if it makes sense. @daleharvey ?

**Comment by nueko** [comment]
same here. (Indonesia)
isup.me/pouchdb.com

**Comment by daleharvey** [comment]
@nickcolley Yeh Nolan has access too, send me your public key and I can add you

nginx keeps crashing. it was out of disk space before but thats fixed, cant see anything in the logs that would be causing it to crash

**Comment by 74sharlock** [comment]
fixed already! nice!
