### ISSUE TITLE
Feature request - Option to Include Conflicts for PouchDB.find

### ISSUE THREAD

**Issue by kgathuru** [pouchdb/pouchdb#6996]
### Feature Request
Please add include conflicts option ({conflicts: true}) to find() api.

allDocs() and get() both have an option for including conflicts ({conflicts: true}) However, pouch db find does not. I have a project has moved all data loading responsibilities to pouchDb.find, but have no way to tell if the documents have errors or not.

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

**Comment by daleharvey** [comment]
So yeh I have seen a few people ask for this, it most definitely needs discussed at the couchdb level as we would want to have matching API here. pinging @willholley @garrensmith @janl to see if this is something already in discussion or possible to happen on the couch side, cheers

**Comment by daleharvey** [comment]
So I think most times people are expected to see and resolve conflicts via changes, I would be very happy to take a look at implementing this but it needs to have concensus on the CouchDB side, please consider emailing the couchdb mailing list and seeing if we can get it implemented there and pouchdb will follow that api
