### ISSUE TITLE
Live Sync Disabled by Additional Tab

### ISSUE THREAD

**Issue by rj919** [pouchdb/pouchdb#6997]
### Issue
Whenever a new tab attempts to instantiate a sync process, it not only fails, it also seems to disable the same sync process in a previous tab. There is an [issue similar](https://github.com/pouchdb/pouchdb/issues/2493) to this which has been closed/merged due to inactivity, but there seems to be no actual resolution regarding how to workaround this problem. More details can be found here:
https://stackoverflow.com/questions/48174616/pouchdb-live-sync-disabled-in-all-tabs

### Info
- Environment: Browser
- Platform: Chrome
- Adapter: IndexedDB/WebSQL
- Server: Sync Gateway

### Reproduce
var sync_options = { live: true, retry: true }
var remote_options = {
        ajax: {
            cache: false,
            timeout: 12000,
            crossDomain: true
        },
        skip_setup: true
    }
var local_db = new PouchDB('mydb')
var remote_db = new PouchDB('http://localhost:4984/mydb', remote_options)
var sync_process = PouchDB.sync('mydb', 'http://localhost:4984/mydb', sync_options)

[open up app in multiple tabs]

**Comment by daleharvey** [comment]
So the only cross tab communication we do in pouch is to ensure the changes feed works which shouldn't affect this. It does sound however that you would very easily hit browser origin request limits with multiple syncs running, this would look a lot like a stalled replication

**Comment by rj919** [comment]
When a second tab tries to initiate a sync, it does produce an error and aborts the attempt similar to the one posted here: https://stackoverflow.com/questions/29173889/how-to-handle-multiple-pouchdb-instances-in-the-browser-that-sync-with-the-same

However, it also disables any existing synchronization (at least on my system) and the existing synchronization process does not throw any error or event that can be handled (I've tried .on('change', .on('error', on('active', etc...) Likewise, there's no way to check to see if synchronization is already running other than to try to start it and have it abort (but in so doing disable the previous synchronization in the other tab).

It would be nice to have a way to either check before it disables the other process or have an event that can be caught. 

Otherwise, the only reliable workaround for continuous synchronization appears to be to use localstorage to check to see if it is already running and include an .unload event listener to destroy the localstorage records on an exit... perhaps in tandem with an Page Active API listener to reinitiate synchronization if one tab is closed. This process seems liable to break though if there is ever an event which closes the tab without first removing local storage (non-responsive program or power failure)... and because there is no way to poll to see if synchronization is currently working without disabling it in the process... it might never restart.

Which seems to mean that there is no real fool-proof way to use continuous synchronization in a real user environment.

Or am I missing something obvious regarding how to handle this problem?

**Comment by rj919** [comment]
Thanks for the analysis and workaround. In my environment, the original replication (specifically sync) is in fact disabled when another tab tries to start one (and is aborted). And I am not sure what it causing this behavior because the original replication simply stalls. 

The original replication process neither replicates changes which I know have happened in the intervening time in Sync Gateway nor emits any event that can be caught. All the event catching methods in the documentation ('complete', 'error', 'paused' etc...) are attached to the process but none are triggered... so the exact cause of the error seems to be upstream.

It is possible that it is an origin request limit, as there are multiple buckets being synchronized simultaneously in my environment. Is there any place where this limitation and how it causes errors is explained better?

**Comment by daleharvey** [comment]
https://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser

Talks about it, in general browsers will just start pausing requests in a queue, fulfilling the request once another one completes. Combined with long poll requests this can look like replication has stalled with no errer

**Comment by rj919** [comment]
That explains it. Tested out multi-tab syncing with only two processes running (instead of the +6 that were running before) and it no longer disables the sync process. In fact, ironically, both tabs now sync (and cause conflicts)... but that is a different matter. 

Based upon my current build with many buckets, it sounds like I will need to use spot syncing rather than continuous ones. But, at least it's good to know now why there is no error reported. The problem lies with browser architecture rather than PouchDB.

Thanks.
