### ISSUE TITLE
allDocs by any keys return all docs

### ISSUE THREAD

**Issue by andig89** [pouchdb/pouchdb#7007]
### Issue
allDocs with any keys return always all docs.

### Info
- Environment: (hybrid app - Cordova)
- Platform: (Android)
- Adapter: (Native by pouchdb.cordova-sqlite and cordova-sqlite-storage)
- Server: (Cordova)

### Reproduce
```
var DBApplication = new PouchDB('dbname', {
    adapter: 'cordova-sqlite',
    skip_setup: false,
    location: 'default'
});
DBApplication.put({
        _id: 'mydoc',
        title: 'Heroes'
    })
    .then(function(response) {
        DBApplication.put({
                _id: 'mydoc2',
                title: 'Heroes2'
            })
            .then(function(response) {
                DBApplication.allDocs({
                    include_docs: true,
                    keys: ['s']
                }).then(function(result) {
                    console.log(result);
                }).catch(function(err) {
                    console.log(err);
                });
            }).catch(function(err) {
                console.log(err);
            });
    }).catch(function(err) {
        console.log(err);
    });
```

**Comment by daleharvey** [comment]
Thanks for the bug report and code to reproduce, I have made a runnable example @ https://outstanding-tiger.glitch.me/, as you can see the output of that allDocs for me is 

    {"total_rows":2,"offset":0,"rows":[{"key":"s","error":"not_found"}]}

Which looks to be as expected on firefox desktop here, so possibly a sqlite bug

**Comment by daleharvey** [comment]
also not seeing this with websql

**Comment by andig89** [comment]
In Chrome works too of course without adapter and cordova-sqlite-storage plugin. If it's work without plugins it can't be pouchDB bug. I think that it's not a problem with adapter but with cordova-sqlite-storage bug or as you wrote - some sqlite bug on device 😕. I'm reporting it on cordova-sqlite-storage git repo. Sorry for choosing  wrong repo.

**Comment by daleharvey** [comment]
Thats completely fine its hard to know where the bug actually lies, closing out, cheers

**Comment by andig89** [comment]
Hmm... one more thing - I remembered why I thought it was PouchDB bug - it's work on v. 6.3.4 PouchDB. Now i don't khnow where report this bug 😕.

**Comment by daleharvey** [comment]
Things are very often between the cracks of pouchdb and a plugin, I can accept a PR if you find the issue and it can be fixed in pouchdb code however in general unless it can be reproduced in a browser or node then its not really considered a pouch bug

**Comment by andig89** [comment]
Problem is with allDocsKeysParse and pouchdb.cordova-sqlite adapter. In v. 6.3.4 allDocsKeysParse is allDocsKeysQuery. allDocsKeysQuery return key and deleted = 'ok', allDocsKeysParse return only keys. In pouchdb.cordova-sqlite in api._allDocs `var key = 'key' in opts ? opts.key : false;` return `false`, and `opts.deleted !== 'ok'` return `true` so final query is `"SELECT 'by-sequence'.seq AS seq, 'by-sequence'.deleted AS deleted, 'by-sequence'.json AS data, 'by-sequence'.rev AS rev, 'document-store'.json AS metadata FROM 'document-store' JOIN 'by-sequence' ON 'by-sequence'.seq = 'document-store'.winningseq WHERE 'by-sequence'.deleted = 0 ORDER BY 'document-store'.id ASC LIMIT -1 OFFSET 0"` instead of `"SELECT 'by-sequence'.seq AS seq, 'by-sequence'.deleted AS deleted, 'by-sequence'.json AS data, 'by-sequence'.rev AS rev, 'document-store'.json AS metadata FROM 'document-store' JOIN 'by-sequence' ON 'by-sequence'.seq = 'document-store'.winningseq WHERE 'document-store'.id = ? ORDER BY 'document-store'.id ASC LIMIT -1 OFFSET 0"`. Besides I don't know why allDocsKeysQuery has line `var subOpts = $inject_Object_assign({key: key, deleted: 'ok'}, opts);`. It's not have any sense for me.
