### ISSUE TITLE
WebSQL throws an error when pouchdb tries to get documents by keys: could not prepare statement (1 too many SQL variables)

### ISSUE THREAD

**Issue by Thor-** [pouchdb/pouchdb#7011]
### Issue
WebSQL throws an error when pouchdb tries to get documents by keys:
*could not prepare statement (1 too many SQL variables)*

After investigation I've found out that it happens when pouch tries execute sql query with IN operator and when length of keys array > 1000

### Info
- Environment: browser/hybrid app
- Platform: Chrome/Android
- Adapter: WebSQL/SQLite

### Reproduce
```
var db = new PouchDB('test-db', {adapter: 'websql'});
var keys = []
for (var i = 0; i < 1000; i++)
    keys.push('doc.' + i);

db.bulkDocs(keys.map(function (k) {
        return {_id: k, type: 'doc', name: k}
    }))
    .then(function () {
        db.allDocs({keys: keys})
            .then(console.log);
    });
```

**Comment by Thor-** [comment]
Temp solution:
Replace code in pouchdb.js file (line: 10319 - 10326):
```
var destinctKeys = [];
      var bindingStr = "";
      keys.forEach(function (key) {
        if (destinctKeys.indexOf(key) === -1) {
          destinctKeys.push(key);
          bindingStr += '?,';
        }
      });
      bindingStr = bindingStr.substring(0, bindingStr.length - 1); // keys is never empty
      criteria.push(DOC_STORE$1 + '.id IN (' + bindingStr + ')');
      sqlArgs = sqlArgs.concat(destinctKeys);
```

on:

```
var bindingStr = "'" + keys.join("','") + "'";
criteria.push(DOC_STORE$1 + '.id IN (' + bindingStr + ')');
```

**Comment by daleharvey** [comment]
Happy to accept a pr for this, however worth mentioning we are only doing one more release with websql support, specifically to deprecate it.

**Comment by daleharvey** [comment]
Nope SQLite isnt officially supported / part of our test suite, our core target is browsers + node.js

**Comment by nename0** [comment]
I used the bound variables because the other conditions (like `startkey`and `endkey`) also used it. I have no idea if there is any performance increase using them or not. The whole `keys` thing could be optimized for perfomance much more, but I didn't do it because the increase of using `IN` query was already quite high and I don't use WebSql myself. For Example:
Use some kind of index lookup map instead of this:
https://github.com/pouchdb/pouchdb/blob/d1ec9c5fb977c8c5733b475d15cb035c52a9af47/packages/node_modules/pouchdb-adapter-websql-core/src/index.js#L781-L785

**Comment by taxilian** [comment]
I'm confused why sqlite support is being dropped; as of today (Oct 1, 2018) I still need to use SQLite on iOS devices as indexeddb is not reliable in cordova *even using the wkwebview plugin*.

Why are you dropping sqlite support when there isn't an alternative that works?

**Comment by daleharvey** [comment]
This is an OSS project and I barely have time to maintain the IndexedDB adapter. The main factor in what platforms we support is whether there is enough people working to support it, in SQLites case nobody has even resurrected the existing code to make it available as a plugin.

In my case I want to support PouchDB working in all web environments, that means the 'web like' things should be supported if they work on being web compatible

**Comment by garrensmith** [comment]
@taxilian could you give us any error reports on why IndexedDB doesn't work in Cordova. Is that related to PouchDB or is it an IndexedDB thing?

**Comment by gaodeng** [comment]
@daleharvey where I can find the web sql adapter source now? we use it in RN. I 'd like to maintain it.

**Comment by gaodeng** [comment]
Since pouchdb-adapter-websql-core has been removed from the pouchdb repository, I have created a new repository and fixed this issue in that repository.  

https://github.com/gaodeng/pouchdb-adapter-websql-core
