### ISSUE TITLE
pouchdb-6.4.1.min.js link on download page returns 404 

### ISSUE THREAD

**Issue by nkronlage** [pouchdb/pouchdb#7016]
The pouchdb-6.4.1.min.js link on https://pouchdb.com/download.html returns 404. It is pointing at: https://github.com/pouchdb/pouchdb/releases/download/6.4.1/pouchdb-6.4.1.min.js

The non-min version works ok.

**Comment by Gonzalo933** [comment]
Same problem here, it seems that the correct link is:
https://github.com/pouchdb/pouchdb/releases/download/6.4.1/pouchdb.min-6.4.1.js

**Comment by daleharvey** [comment]
My mistake, fixed now thanks
