### ISSUE TITLE
Crash after have empty response in some xhr request in pouchDB

### ISSUE THREAD

**Issue by artemmorozov7** [pouchdb/pouchdb#7019]
## Issue
I have many crashes in app after some actions with pouchDB. I have problems to reproduce, but I have stack trace: 
errorStack":"TypeError: Cannot create property 'status' on string ''\n    at XMLHttpRequest.n.onreadystatechange (file:..../libs/pouchdb-6.1.2.release.js:9:20973"

I looked to stack trace, and can found place where I have exception:
https://github.com/pouchdb/pouchdb/blob/07dc369113d495d43f3ed415ba31f50cb734e283/packages/node_modules/pouchdb-ajax/src/request-browser.js#L221
I figured out what the problem was and realized that sometimes the response in this request(xhr) comes in the form of an empty string (""). In this case, JSON.parse does not work correctly and an error occurs.

Please, add check to this situation in line - 
https://github.com/pouchdb/pouchdb/blob/07dc369113d495d43f3ed415ba31f50cb734e283/packages/node_modules/pouchdb-ajax/src/request-browser.js#L216

**`} else if (typeof xhr.response === 'string' && xhr.response !== '') {`**
of some another check for empty string

## Info
- Environment: hybrid app
- Platform: Android
- Adapter: WebSQL

## Reproduce
 I have problems to reproduce, but I have stack trace: 
errorStack":"TypeError: Cannot create property 'status' on string ''\n    at XMLHttpRequest.n.onreadystatechange (file:..../libs/pouchdb-6.1.2.release.js:9:20973"

**Comment by daleharvey** [comment]
Looks like you have done the investigation here and happy to accept a PR, there is a release coming soon and if the PR doesnt make it then this will be fixed by the switch to fetch anyway. If you have the time a test for this would be very helpful. Happy to help with it

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/42ca86e17fea182aaf3695484a83595fb68a718d
