### ISSUE TITLE
Attempted to assign to readonly property

### ISSUE THREAD

**Issue by pjschmidt3** [pouchdb/pouchdb#7021]
### Issue
calling db.find in iOS Safari using the sqlite-2 adapter throws "attempted to assign to readonly property" in parseDoc in pouchdb-adapter-utils.

It looks like parseDoc is passing two ints to pouchdbUtils.uuid, which is apparently just uuid/v4.

Here is a stack trace:

```
TypeError: Attempted to assign to readonly property. (cordova.js, line 1731)
v4 — v4.js:22

parseDoc — index.js:96

(anonymous function) — index.js:271

map
websqlBulkDocs — index.js:267

_bulkDocs — index.js:1117

(anonymous function) — index-browser.es.js:142

initializePromise
Promise
(anonymous function) — index-browser.es.js:129
promiseReactionJob
```

Looks like maybe it's missing the "option" param to uuid.

### Info
- Environment: cordova
- Platform: iOS
- Adapter: cordova-sqlite

### Reproduce

Just calling find() does it for me..

```
import PouchDB from 'pouchdb'
import PouchFind from 'pouchdb-find'

PouchDB
      .plugin(require('pouchdb-adapter-cordova-sqlite'))
      .plugin(PouchFind)

let db = new PouchDB(db, { adapter: 'cordova-sqlite' })

db.bulkDocs()
    .then(docs => {
      // make money and stuff
    }).catch(err => {
     // think of excuses for late project
    })
```

**Comment by daleharvey** [comment]
This is only with the cordova plugin right? need to file on https://github.com/pouchdb-community/pouchdb-adapter-cordova-sqlite unless its broken in any browsers, but https://ribbon-knee.glitch.me/ is working in safari / websql for me so sounds like a cordova issue
