### ISSUE TITLE
Expose HTTP client used for remote database

### ISSUE THREAD

**Issue by loic** [pouchdb/pouchdb#7022]
### Issue
It's currently impossible to share cookies on node between `pouchdb` and plugins, which makes `pouchdb-auth` unusable on node.

The [current recommendation](https://github.com/pouchdb/pouchdb/issues/3525#issuecomment-224667722) doesn't allow accessing the `request` client, its configuration, or its cookie jar. It's made even worse by the fact that `request` is vendored during the ES6 transpilation, which means that we even can't rely on the global cookie jar enabled by https://github.com/pouchdb/pouchdb/commit/17db84f54d3bf432a60faeb632ce383e8464d3b1 as doing a regular `require('request')` would return a different instance of `request`.

If we account for both configuration and cookie jar, I think it makes sense to expose publicly the http client on the DBs itself.

There is already `db.request()` and `db._ajax` both of which are private APIs, but those are IMO too high level already as they process the response.

Background information: https://github.com/pouchdb/pouchdb-server/issues/280

cc @marten-de-vries

### Info
- Environment: Node.js

**Comment by marten-de-vries** [comment]
So essentially, you're proposing an undocumented ``PouchDB._request`` function? I see only one other possibility, which is to not use ``request.defaults`` but instead to enable the cookie jar globally. That will likely conflict with 3rd party libraries, though.

**Comment by daleharvey** [comment]
Between https://github.com/pouchdb/pouchdb/issues/6944 and https://github.com/pouchdb/pouchdb/issues/5322 we are going to switch to fetch and allow people to override the requests so you can use whatever client you want to make the requests as long as it accepts and returns data in a way that is compatible with fetch

That makes sure we can reuse the same request instance etc although it might not be the most convenient, we may also want to consider something like passing a cookiejar into the contructor?

**Comment by marten-de-vries** [comment]
That's an elegant solution from a PouchDB perspective, but it does require switching around the APIs of all plugins trying to re-use its cookies/headers/request function. The request function would need to be passed in everywhere:

```js
var PouchDB = require('pouchdb');
PouchDB.plugin(require('pouchdb-authentication-or-auth-or-whatever'))
var request = require('request').defaults(/*enable-cookie-stuff*/);

var db = new PouchDB('name', {req: request});
db.logIn({req: request}) // pass in again. Requires an API change.
```

So I think that at least the request function passed in through the constructor should be exposed in some way on the ``PouchDB`` object. Fine if it's undocumented, as long as plugins can access it in some way.

**Comment by loic** [comment]
I would go with this:

```javascript
var PouchDB = require('pouchdb');
PouchDB.plugin(require('pouchdb-authentication-or-auth-or-whatever'))
var request = require('request').defaults(/*enable-cookie-stuff*/);

var db = new PouchDB('https://example.com/', {http_client: request});

db.http_client()
db.logIn() // The plugin uses `db.http_client` and benefits of all the user defined conf:
           // cookie jar on Node, timeouts, custom CA?, etc.
```

In this snippet `request` is just a placeholder for whatever JS API we settle on.

I think we should shoot for a public API, every time the internal http APIs change they break the plugin ecosystem and `pouchdb-server`.

**Comment by loic** [comment]
@daleharvey it looks like the Node reference implementation of `fetch` doesn't support server side cookie stores (https://github.com/bitinn/node-fetch/blob/master/LIMITS.md) at the moment.

I really wonder what we can do on the `pouchdb-server` side to move forward.

**Comment by ptitjes** [comment]
That would be neat if we could reuse a shared instance of the http client used by `pouchdb`. That would be even neater if we can provide it/contribute to its configuration.

Currently in `pouchdb-authentication`, we use `require('pouchdb-ajax')`. So we did PR `pouchdb` to have the cookie jar enabled by default in `pouchdb-ajax`'s use of `request` to get authentication working on Node. Being able to finely configure it (per database) would enable us to have multiple databases with different cookie jars, which is really important for us on Node.

**Comment by daleharvey** [comment]
Would be interested to know if @mikeal has any thoughts on this, I would like to avoid adding a public api here as this is for a specific adapter on a specific platform. Our core api is symetric and options are used for platform specific enhancements / options

I think pretty close to what @marten-de-vries posted seems like the best solution

```
var fetch = require('fetch').defaults(/*enable-cookie-stuff*/);

var PouchDB = require('pouchdb');
PouchDB.plugin(require('pouchdb-authentication-or-auth-or-whatever')({fetch:  fetch}))

var db = new PouchDB('name', {fetch: fetch});
db.logIn();
```

This does as mentioned push an API change onto the plugins, but api changes on plugins are cheaper than api changes to core

**Comment by ptitjes** [comment]
@daleharvey I'm not sure I understand correctly what you propose. Looking at your code snippet, this looks like this will make simple uses of plugins more complicated for basic users ?

I'd rather like that `PouchDB` provide the `fetch` instance to the plugins (via a `_fetch` property or similar) making that transparent to the user. Then expert users can provide their own `fetch` instance to the PouchDB constructor.

Also, in your code snippet, the plugin has a unique `fetch` instance for all `PouchDB` instances but each `PouchDB` instance can have a different `fetch` instance. I consider this a very dangerous design.

**Comment by daleharvey** [comment]
@ptitjes I understand that you would prefer the core api to expose a http client, I explained why I would prefer it to not, while I would like things to be as simple as possible for everyone, keeping complexity away from the core API is very important as that impacts every single pouchdb user.

This is not only for plugins, core users also want to make http requests that share credentials with PouchDB and I think its important that PouchDB gets in the way of making those requests as little as possible, someone building a large complicated application should not be required to use PouchDB's http client in order to interoperate

So this is what works in the browser right now

```js

var PouchDB = require('pouchdb');
PouchDB.plugin(require('pouchdb-authentication-or-auth-or-whatever'))

var db = new PouchDB('name');
db.logIn().then(function() { 
  return fetch(stuff);
}).then(function() { 
  ....
});
```

I would like to see this work in node as we all expect with as little hassle as possible to the user, passing opts is not ideal but beats having to use a different api

Having Pouch and plugins / users be able to opt in to a request / fetch module that has global cookies enabled by default could work?

**Comment by daleharvey** [comment]
So basically `var fetch = require('pouchdb-fetch')` has a shared cookiejar for anyone who requires it?

**Comment by marten-de-vries** [comment]
> it looks like the Node reference implementation of fetch doesn't support server side cookie stores (https://github.com/bitinn/node-fetch/blob/master/LIMITS.md) at the moment.

There's https://www.npmjs.com/package/fetch-cookie.

> So basically var fetch = require('pouchdb-fetch') has a shared cookiejar for anyone who requires it?

I think it would not work, just as we currently cannot get a copy of the ``pouchdb-ajax`` instance pouchdb uses using ``require``: Rollup gives PouchDB an inlined copy which others cannot access.

---

I like passing in ``fetch`` for customization, but the problem as I see it is that plugins should not have to be aware if ``fetch`` was customized. It's not their concern.

The basic issue here we've encountered multiple times before, I think. When a plugin cannot access some of the information passed into the constructor, it has to either work around that by asking for its own copy (ugly API) or lobby for a new property on the db object. Perhaps we could just expose something like ``_constructor_args`` on the database object (undocumented is fine, but default values should be filled in), and (hopefully) be done with the general problem 'for forever'?

**Comment by loic** [comment]
> I would like things to be as simple as possible for everyone, keeping complexity away from the core API is very important as that impacts every single pouchdb user.

I don't totally understand this argument, surely we can expose the http client only when the `remote` adapter is used, in which case it's only gonna impacts pouchdb user that actually have a use for it.

If it's about purity of the APIs, we could namespace adapter specific options and methods and each adapter is responsible of maintaining its own.

The `remote` adapter could expose the following:
```javascript

var db = new PouchDB('https://example.com/', {
    adapterOpts: {
        timeout: 42,
        cookiejar: request.jar()
    }
});
db.adapter.opts      // adapter specific options so they don't pollute the global namespace the way the current `ajax` option does.
db.adapter.fetch()   // fully configured http client used internally and by plugin ecosystem.
db.adapter.cookiejar // accessor to cookiejar so advanced user can use any http client they want
```
Django does this for many subsystem that have multiple backends (databases, cache engines, templates, authentication, etc.):
- https://docs.djangoproject.com/en/2.0/ref/databases/#connecting-to-the-database
- https://docs.djangoproject.com/en/2.0/ref/settings/#std:setting-OPTIONS

> someone building a large complicated application should not be required to use PouchDB's http client in order to interoperate

I agree PouchDB should aim at staying out of the way, but to be honest I don't see the use case for someone who would want to use a different HTTP client *only* for their own query, I only see those 2 use cases:
- They would want PouchDB to use their own http client, so PouchDB interoperate with the rest of their code and not the other way around.
- They want their code to use the same client as PouchDB when they talk to the underlying database.

But regardless, if all the user defined options that are fed to the PouchDB client can be introspected later and there is an accessor to the cookie jar, I think we are as out of the way as we can be.

**Comment by daleharvey** [comment]
> I don't totally understand this argument, surely we can expose the http client only when the 
> remote adapter is used, in which case it's only gonna impacts pouchdb 
> user that actually have a use for it.

So my initial worry about exposing this is that it would (is already as `db.request`) part of the http adapter, this goes against oneof the core principles of the api in that it doesnt matter what adapter you are using your code that uses the core PouchDB API should work. This is why almost all of the adapter specific things are options that can simply be ignored if they are not relevant. However I would be less worried about that if either db.fetch / PouchDB.fetch was just a global option we always exposed regardless of adapter

> Django does this for many subsystems that have multiple 
> backends (databases, cache engines, templates, authentication, etc.):

Django is the framework that surrounds those subsystems, using django to configure and share your configuration sounds like a perfectly good idea, PouchDB is not a framework and that is my second worry is that PouchDB's capabilities grow beyond its core focus which is something that happened to CouchDB and became imo a big fustration when using it. I want PouchDB to be a great storage / sync engine not also a mediocre HTTP client.

> They would want PouchDB to use their chosen http client, so PouchDB interoperate 
> with the rest of their code and not the other way around.

This is exactly how I would like this to work, as I posted in https://github.com/pouchdb/pouchdb/issues/7022#issuecomment-359198569 thats the best case for the user and I would like to figure out how to get as close to that as possible

**Comment by daleharvey** [comment]
So working on https://github.com/pouchdb/pouchdb/pull/7059 I am working specifically on this now, I didnt realise map reduce is already using db.request and have rewritten that to use a new `db.fetch`. still hoping we can avoid that but its looking likely that it will be needed

**Comment by daleharvey** [comment]
ok so if anyone has any comments on the implementation they can go in the PR, we now have a `db.fetch(path, opts)` and `PouchDB.fetch(url, opts)` exposed that are used by mapreduce / pouchdb-find and expost for users + plugins and will share cookies etc (cookies arent working yet, but will), closing as a dupe

**Comment by ThibaultJanBeyer** [comment]
@daleharvey Is this still not working on my side using `localDB.sync(remoteDB …)`. I still get the unauthorized issue. What was changed? What do I have to change?

See: https://github.com/pouchdb/pouchdb/issues/7018

Thank you
