### ISSUE TITLE
Consider losing the node_modules directory in the "repo/packages/node_modules"

### ISSUE THREAD

**Issue by loic** [pouchdb/pouchdb#7028]
### Issue

Lots of applications assume that the `node_modules` directory should be ignored in their default configuration which can makes working with the `pouchdb` and `pouchdb-server` monorepos a bit unfriendly.

Github for instance ignores `node_modules` inside repositories, which means pouchdb packages are invisible in Github code searches.

Is there a specific reason to have this hierarchy?

**Comment by daleharvey** [comment]
I believe this was done to support the monorepo and greenkeeper, its annoying to lose github code search and I would like to simplify the build process, we were very early adopters with es6 + node monorepos and so some of our stuff is a bit homebrew and complicated, I am hoping we can move to a more standardised / adopted way of doing things

**Comment by daleharvey** [comment]
https://github.com/greenkeeperio/greenkeeper/issues/594 relevant

**Comment by loic** [comment]
It just occurred to me that it's probably why diffs in PRs are collapsed by default on the pouchdb repos:

![screen shot 2018-01-25 at 14 00 24](https://user-images.githubusercontent.com/36160/35375090-417d72c4-01d8-11e8-8ff7-22e06a14497b.png)
