### ISSUE TITLE
Figure out why nginx keep crashing

### ISSUE THREAD

**Issue by figalex** [pouchdb/pouchdb#7032]
I can't open https://pouchdb.com at all.

**Comment by daleharvey** [comment]
ok, anyone with nginx expertise able to know how I can tell why this thing keeps crashing? it ran out of disk space at one point but has plenty now

**Comment by daleharvey** [comment]
Put it on a crontab to restart while I investigate

**Comment by dharders** [comment]
Hey @daleharvey, What does your `/var/log/nginx/error.log.1` (or equivalent) look like ?

If it doesn't hold any clues, you may have to set your `error_log` level higher, the **warn** level should catch the errors.  Check your ` /etc/nginx/nginx.conf`
```
user  nginx;
worker_processes  2;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;
...
```
and `pouchdb.com.conf` file too, maybe under `/etc/nginx/sites-available/...` depending on your directory structure. 

Post the config & log and I can take a look if you'd like?

**Comment by daleharvey** [comment]
I cant see anything in the logs that would cause a crash @ https://gist.github.com/daleharvey/3f3db8e9ef2647e0b9e4e24ad780ad85

nginx.conf is empty, adding the warn level to the pouchdb config file

**Comment by dharders** [comment]
Do those timestamps in the logs match with the times the site was down?

Also, your logs suggest your server is also hosting `arandomurl.com` and it’s upstream end point isn’t running/connecting. ie a server/service is not running in the background (which leads to 502 bad gateways) you need to check your `arandomurl.com` conf file to find the upstream port/service it’s looking for and make sure it’s working in the background 

Generally speaking though, this shouldn’t lead to nginx crashing but it’s worth a look, or simply disable the other site temporarily to see if that resolves the issue (it’s 502ing anyway, so no harm in disabling it)

**Comment by daleharvey** [comment]
found a gap where the server must have been down, no indication of why 

> 2018/01/22 02:27:13 [error] 3479#0: *176241 open() "/home/pouchdb/www/pouchdb.com/wp-login.php" failed (2: No such file or directory), client: 14.1.227.29, server: pouchdb.com, request: "GET /wp-login.php HTTP/1.1", host: "pouchdb.com"
> 2018/01/22 11:00:00 [warn] 20221#0: conflicting server name "arandomurl.com" on 0.0.0.0:80, ignored

It seems like if nging is crashing it wouldnt be logging it and i should look elsewhere but not sure? taking off the cron so its easier to debug if it happens again

**Comment by dharders** [comment]
Are you running wordpress or was the wp-login.php just a site probe (most likely a bot) ?

If you are running wordpress, there are a fair few known issues with php-fpm and nginx crashing to do with file descriptor limits etc and wp_update.

If you aren't running wordpress, I'd check the cronlog or syslog to see if that has any clues when it restarts nginx after a crash. `sudo grep -i CRON /var/log/syslog`

Another suggestion is to add a manual log within the cron job to get the output, because sometimes cronlog etc only gives start/stop info. i.e. `* * * (schedule)    /yournginxcommand >> /var/log/nginx.custom.log 2>&1`

**Comment by dharders** [comment]
Also worth trying

`sudo grep -i nginx /var/log/syslog`
`sudo grep -i nginx /var/log/syslog.1`
`sudo grep -i nginx /var/log/syslog.2` etc

**Comment by daleharvey** [comment]
> Are you running wordpress or was the wp-login.php just a site probe (most likely a bot) ?

Yeh they are just probes, not running wordpress

Hopefully what we have done is enough to stop it crashing, if not I should be able to debug from there, thanks loads @dharders
