### ISSUE TITLE
Docs with rev greater than 1-* not transforming when replicating from remote

### ISSUE THREAD

**Issue by czarcismok** [pouchdb/pouchdb#7034]
Hi everyone!
Working with PouchDB for some time now and come across this problem.

### Issue
Documents with revision greater than 1-* are not transforming when replicating from remote-CouchDB.

`_changes?style=all_docs&seq_interval=100&since=0&limit=100` gets all changes, but in
`_all_docs?conflicts=true&include_docs=true` request payload are only keys of docs with rev = 1.*

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
1. Put document in remote (rev 1).
2. Modify doc and put it in remote (rev 2).
3. Set some transformation on an outgoing docs (ie.: doc.local = true; doc.remote = false;).
4. Start replication to local PouchDB.
5. List local docs (should not contain changes from transformation).

Can't get glitch to work with transform-pouch (any ideas?):
https://glitch.com/edit/#!/understood-ear
or
https://glitch.com/edit/#!/cautious-icon

I've been struggling with this for almost a week now and don't know if I'm doing something awfully wrong or this is a bug / desired behavior. Help, please? :)

**Comment by daleharvey** [comment]
So you need to include pouchdb-transform into glitch, uploading the js file or linking to a cdn somewhere. this is fairly certainly a pouchdb-transform bug and should be filed over there, but if you can get transform working with glitch then we can take a look

**Comment by czarcismok** [comment]
Thanks for attention!
Glitch updated - previously had bad transform-pouch file linked - working, buggy, test case: https://understood-ear.glitch.me/

Remote DB is at cloudant  - with pouchdb-express-router everythink went well.
The difference between these two cases was that pouch-express-router was getting 404 on `_bulk_get?revs=true&latest=true` and then fell back to each document implicite:
`modified1?revs=true&latest=true&open_revs=%5B%222-a57e918c45da4cc099ab8d7f5233f54d%22%5D`, `deleted1?revs=true&latest=true&open_revs=%5B%222-140e15ce37474adcbc7474f10550e123%22%5D`, etc. whereas cloudant `_bulk_get` respond properly.

**Comment by marten-de-vries** [comment]
Closing in favour of https://github.com/pouchdb-community/transform-pouch/issues/50 ; It seems this error is due to ``bulkGet`` not being supported in ``transform-pouch`` and ``pouchdb-wrappers``, so no changes in PouchDB should be necessary.
