### ISSUE TITLE
Not going to my put method

### ISSUE THREAD

**Issue by mehrajpasha** [pouchdb/pouchdb#7043]
db.get('mydoc').then(function(doc) {
console.log("hello");
  return db.put({
    _id: 'mydoc',
    _rev: doc._rev,
    title: "Let's Dance"
  });

### Issue
I'm getting get as success but it's not going to put  method..I'm following pouch db guide

**Comment by daleharvey** [comment]
@mehrajpasha Hi, you need to explain what you expect to happen and what is going wrong. I cant figure out from your post sorry

**Comment by mehrajpasha** [comment]
I'm just updating that doc.. I'm getting the doc but not able to update the doc..i.e it's not going to that put method

**Comment by daleharvey** [comment]
Why how do you know its not getting to the put method? you arent doing anything after the put method is called. Here is a code example updating a document @ https://brief-surprise.glitch.me/

**Comment by daleharvey** [comment]
Seems like an issue with promises or callbacks and not a pouchdb bug, feel free to follow up but closing this out
