### ISSUE TITLE
Performance tests don't run on latest chrome

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#7045]
In Chrome 63, following instructions at https://github.com/pouchdb/pouchdb/blob/master/TESTING.md#performance-tests, performance tests fail to complete:

<img width="1275" alt="screen shot 2018-01-26" src="https://user-images.githubusercontent.com/191496/35431984-aa5258a2-028f-11e8-9996-529d2de6a80b.png">

Error is specifically:
```
{
  "status": 0,
  "name": "unknown",
  "message": "getCheckpoint rejected with ",
  "result": {
    "ok": false,
    "start_time": "2018-01-26T08:53:45.899Z",
    "docs_read": 0,
    "docs_written": 0,
    "doc_write_failures": 0,
    "errors": [],
    "status": "aborting",
    "end_time": "2018-01-26T08:53:45.962Z",
    "last_seq": 0
  }
}
```

**Comment by daleharvey** [comment]
That's a bit of a surprise, they are tested in ci with Firefox we just don't do a lot with the result

**Comment by daleharvey** [comment]
Yeh the first thing all tests need is a cors enabled server (https://github.com/pouchdb/pouchdb/blob/master/TESTING.md#running-pouchdb-tests), just tested in 63 and with cors enabled they are working fine. Can see in your console its a cors issue

**Comment by alxndrsn** [comment]
It's true!  Thanks 🙂 

I think that documentation has a typo (PR at https://github.com/pouchdb/pouchdb/pull/7176).
