### ISSUE TITLE
The absent-minded replicate() / sync() #issue

### ISSUE THREAD

**Issue by dariush-alipour** [pouchdb/pouchdb#7049]
Hi, thanks for the extra ordinary great work you guys do, i found an odd issue recently..
### Issue
There's a Sync Gateway used in a 'https' adapted PouchDB, and a local 'idb' adapter for a local PouchDB. remote PouchDB always receives the right data (i can tell by doing a `remotePouch.allDocs()`), but sometimes doing replicate/sync function on those two pouch instances, does not do the job and my local database is still empty.

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: Couchbase/Couchbase Sync Gateway

### Reproduce
Unfortunately it's almost a heisenbug which happens a lot but not always. but i can explain and send screenshots of the situation.

sometimes it works just like this:
```javascript
await getLocal().allDocs()
{total_rows: 17, offset: 0, rows: Array(17)}
await getRemote().allDocs()
{rows: Array(17), total_rows: 17, update_seq: 81}
```

but sometimes its like:
```javascript
await getRemote().allDocs()
{rows: Array(8), total_rows: 8, update_seq: 19}

await getLocal().allDocs()
{total_rows: 4, offset: 0, rows: Array(4)}

await PouchDB.sync(getLocal(), getRemote())
{
pull: {ok: true, start_time: Sat Jan 27 2018 11:56:17 GMT+0330 (+0330), docs_read: 0, docs_written: 0, doc_write_failures: 0, …}
push: {ok: true, start_time: Sat Jan 27 2018 11:56:17 GMT+0330 (+0330), docs_read: 0, docs_written: 0, doc_write_failures: 0, …}
}

await getRemote().allDocs()
{rows: Array(8), total_rows: 8, update_seq: 19}

await getLocal().allDocs()
{total_rows: 4, offset: 0, rows: Array(4)}
```
<img width="928" alt="screen shot 2018-01-27 at 11 59 19 am" src="https://user-images.githubusercontent.com/14793529/35470284-f0d936ac-035b-11e8-8ce5-f0b0bfbcc582.png">

**Comment by daleharvey** [comment]
Sync gateway isnt tested or fully supported by PouchDB, couchbase claim interoperability with CouchDB and if that is so it should work, however unless a bug can be reproduced with CouchDB / PouchDB Server (here is a little helper for reproducing bugs) https://pouchdb-bug-helper.glitch.me/) then its a bug with sync gateway, Cheers 

(old issue @ https://github.com/pouchdb/pouchdb/issues/5820)
