### ISSUE TITLE
db.changes doesn't work

### ISSUE THREAD

**Issue by vinz243** [pouchdb/pouchdb#7055]
### Issue

`db.changes` doesn't fire when a document is modified

### Info
- Environment: Node v8.5.0
- Platform: Windows 10
- Adapter: LevelDB/Memory
- Version: 6.4.2

### Reproduce

```js
const pouch = require('pouchdb');

//pouch.plugin(require('pouchdb-adapter-memory'));
const PouchDB = pouch//.defaults({adapter: 'memory'});

const db = new PouchDB('mydb');

(async () => {
  const test = await db.put({_id: 'foo', foo: 'bar'});
  db.changes({
    live: true,
    since: 'now',
    include_docs: true
  }).on('changes', (changes) => {
    console.log('got changes', changes);
  }).on('complete', () => {
    console.log('complete', arguments)
  }).on('error', () => {
    console.log('error', arguments)
  }); 

  await db.put({
    _id: test.id,
    _rev: test.rev,
    foo: 'barz'
  });

  console.log(await db.get(test.id));
})()
```

**Comment by tmende** [comment]
Try to change 
`.on('changes', (changes) => {`
to 
`.on('change', (changes) => {`

**Comment by vinz243** [comment]
It does fix it, however in my app it was already `change`, and still not working:

```js
this._changes = this.database.changes({
      since: 'now',
      live: true,
      include_docs: true,
    }).on('change', ({doc, deleted, id}) => {
      console.log(arguments)
      if (doc.name !== this._name) {
        const props = this.props;
        this._name = doc.name;
        this.fireOnPropsChanged('name', doc, props);
        return;
      }
      if (deleted) {
        this._status = Status.DELETED;
        this.fireOnDelete(id);
        return;
      }
      console.log('Unable to see change', arguments);
    })
```

the callback is never called in my tests

**Comment by daleharvey** [comment]
@vinz243  as with the first comment we would need more information to be able to debug, ideally as an isolated node script or shown at https://pouchdb-bug-helper.glitch.me/, your example code as is works fine

**Comment by vinz243** [comment]
After trying tons of stuff, I finally fixed although I have  no clue how

**Comment by W1M0R** [comment]
I am experiencing the same issue, using `pouchdb-core: 7.0.0` with `pouchdb-adapter-memory: 7.0.0`, inside an Electron render process.
