### ISSUE TITLE
pouchdb-adapter-http Maximum call stack size exceeded ;

### ISSUE THREAD

**Issue by Jimmysh** [pouchdb/pouchdb#7061]
### Issue

Unhandled Promise rejection: Maximum call stack size exceeded ;
pouchdb-adapter-http  6.4.2  index.es.js  line 226-235

```
  function adapterFun(name, fun) {
    return adapterFun(name, getArguments(function (args) {
      setup().then(function () {
        return fun.apply(this, args);
      }).catch(function (e) {
        var callback = args.pop();
        callback(e);
      });
    }));
  }
```

### Info
- Environment: browser
- Platform: Chrome

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by daleharvey** [comment]
@Jimmysh Would need a lot more information about how to reproduce this than we currently have, as the comment says if you can reproduce on glitch that would be ideal

**Comment by Jimmysh** [comment]
this code is copy from pouchdb-adapter-http 6.4.2 lib/index.es.js. The function adapterFun will recursive call self forever. but pouchdb-adapter-http 6.4.1 is ok.

**Comment by daleharvey** [comment]
Oh wow that's dumb, looks like the same rollup bug as https://github.com/pouchdb/pouchdb/issues/7054

**Comment by daleharvey** [comment]
Yeh will close as dupe, going to be getting a release out shortly to fix
