### ISSUE TITLE
.info() method is not creating remote databases in android released apps

### ISSUE THREAD

**Issue by bilelmoulahi** [pouchdb/pouchdb#7068]
### Issue
Creating remote databases is not working when adding the --release tag to build ionic applications. 

### Info
- Environment: Ionic 3
- Platform: Android
- Adapter: cordova-sqlite
- Plugin: cordova-plugin-sqlite-2
- Server: CouchDB v. 2.1.1
- PouchDB: 6.4.1

### Reproduce
Any simple ionic app, with the code: 

```
let remotex = new PouchDB('https://' + auth + '@' + 'xxx.xx:6984/' + xx + '_xx');
return remotex
  .info()
  .then((res) => {
    console.log(res);
    return res;
  })
  .catch(function(err) {
    console.log('error : ', err);
    return err;
  });
```
using: 
"pouchdb": "^6.4.1",
"pouchdb-adapter-cordova-sqlite": "git+https://github.com/SnceGroup/pouchdb-adapter-cordova-sqlite.git"
"@types/pouchdb": "^6.3.2",

Then build the app using the --release flag (--buildConfig to sign the app)

`ionic cordova build android --prod --release --buildConfig`

### Expected Result
The database should be created in the remote server. 

According to the [documentation](https://pouchdb.com/guides/databases.html#remote-databases):
> note: The remote database will not be created until you do an API call, e.g.: db.info(). The reason behind that is that the PouchDB constructor is completely synchronous, for ease of error handling (i.e. no asynchronous errors).

### Actual Result
The database is not created in the remote server, and the info() command is returning: 
`{"status":0, "name":"unknown"}`

- Note that when building in the --debug mode, everything worked fine: 
`ionic cordova build android --prod  --buildConfig`
- Also, everything is just fine when using an android emulator or a browser.

**Comment by daleharvey** [comment]
This is a cordova issue, not core pouchdb and looks to be reported at https://github.com/pouchdb-community/pouchdb-adapter-cordova-sqlite, been a little inaction there but will try to see about getting it fixed there, cheers

**Comment by bilelmoulahi** [comment]
Do you have any link to the issue there ? I didn't find it.

**Comment by bilelmoulahi** [comment]
Can I report this there or it will be considered as duplicated ?
