### ISSUE TITLE
Ionic app is frozen while adding huge amount of data in pouchdb

### ISSUE THREAD

**Issue by wiadev** [pouchdb/pouchdb#7069]
### Issue
Hi
I'm using the pouchdb in ionic v1 and I needs to update a huge amount of data in IndexDB via pouchdb.
But Ionic app is frozen while adding huge amount of data in pouchdb

### Info
- Environment: Ionic v1
- Platform: Chrome/FF/Safari/Edge/iOS/Android/etc.
- Adapter: IndexedDB/WebSQL

**Comment by daleharvey** [comment]
I don't think there is anything we can do on the pouchdb side to help with that, async io should be enough for ionic to be able to not block UI but if it isn't then you will probably need to throttle it yourself, having pouch purposefully write slower isn't really an option

**Comment by wiadev** [comment]
@daleharvey I'm using async and pouchdb.put is a promise itself. but the browser is frozen while the data is actually written in indexDB even if I'm waiting for a response in a callback.

**Comment by daleharvey** [comment]
Do you have any indication what is causing the freeze, a profile etc? the only thing I could see possibly causing this is https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-idb/src/utils.js#L37 maybe try replacing that with a plain JSON stringify? can reopen if it seems like there is something pouchdb could do to help but would need more info to know
