### ISSUE TITLE
Website offline?

### ISSUE THREAD

**Issue by synapse** [pouchdb/pouchdb#7078]
### Issue
Can't reach the website. Is there any way I could read the docs?

**Comment by gcox** [comment]
@synapse If you're on a Mac you could use Dash to view the docs

**Comment by raarts** [comment]
Or use this: https://web.archive.org/web/20180124110933/https://pouchdb.com

**Comment by daleharvey** [comment]
ok, I have rebuilt the server so we shoulnt have issues with this going down now
