### ISSUE TITLE
[Docs] Missing put/post's options argument documentation

### ISSUE THREAD

**Issue by juancampa** [pouchdb/pouchdb#7081]
### Issue
The API reference for `put` and `post` mentions the `options` argument but has no documentation:

https://github.com/pouchdb/pouchdb/blob/master/docs/_includes/api/create_document.html#L5

**Comment by muqadar-ali-jamali** [comment]
I am a beginner, can you guide me on this? I want to contribute to this

**Comment by daleharvey** [comment]
So in currently is possible to send ajax options in any request which is the only thing these options are used for at the moment afaik, we may actually be removing that in https://github.com/pouchdb/pouchdb/pull/7059 so it may be that we want to take out the `[options]` if they arent used for anything although that might be too much of an annoyance just for cleanliness

**Comment by juancampa** [comment]
Wouldn't `options` be useful to, for example, add an Authorization header? I think we should keep some form of it

**Comment by daleharvey** [comment]
If you specify options in the pouchdb constructor it will send the Authorization header, similarly with the linked pr it is trivial to send or modify the headers with any request, the ability to specify Ajax options per API call and how they interact when conflicting with constructor options can be confusing and I can't think of any compelling use case to maintain it

**Comment by marten-de-vries** [comment]
I think ``pouchdb-wrappers`` adds an ``options`` object to pretty much every API method for usage by plugins. E.g. ``pouchdb-validation`` uses it so you can pass in the ``userCtx``/``secObj`` to be used for validating the ``post``/``put``ed document.

That said, that should continue to work even if 'vanilla' PouchDB dropped the argument. For consistency, that might be a reason to keep it documented, though.

**Comment by daleharvey** [comment]
Yeh honestly even though we may not use it everywhere, I would rather keep it there for consistency and future proofing (we may want to add options in future) closing out

**Comment by codebycarlos** [comment]
Hi just some feedback, as a new user of PouchDB this is a bit confusing as it makes the impression that put/post methods allow for options (I'm aware only of the force option only)
