### ISSUE TITLE
avoid 404s on remote checkpoint checks

### ISSUE THREAD

**Issue by artin-phares** [pouchdb/pouchdb#7091]
Any time my local databases replicate with server databases I see error flood in the console:

```
The above 404 is totally normal. PouchDB is just checking if a remote checkpoint exists.
```

Well those are not "totally normal" for me, since im' getting alerted every time my console turns red.  
I need to focus on the console, hoping there is no some sneaky little *real* error among that flood.

Is there any chance `pouchdb` can avoid hitting 404`s?  
Eg. by requesting necessary meta-data through some common endpoint that always exists...

---

![53ee9dca6e6e0fa3102a582acecec1c3](https://user-images.githubusercontent.com/671082/36339802-555963ee-13de-11e8-8abc-05b0c4f85b77.png)

**Comment by daleharvey** [comment]
We have tried to figure out ways to avoid this, however there isnt really any, there isnt an existing resource that exists until we make it, one solution if you know you are not going to wipe the server database is to use `{checkpoint: 'source'}` in your replication options, then it will only use local checkpoints

**Comment by artin-phares** [comment]
@daleharvey

I've tried to replicate with `{checkpoint: 'source'}` and it works with no errors.  

But after I've done initial server-to-client replication I'm starting both-way replication (sync).  
With sync I've tried `{checkpoint: false}` to disable checkpointing on both sides, but still receiving 404s.  
Btw, I'm not seeing "The above 404 is totally normal" log message in this case.  

Is this a bug? What's my options with `sync`?

**Comment by daleharvey** [comment]
`{checkpoint: 'source'}` should ideally work with sync, `false` should definitely not 404 so that sounds like a bug, if you wanna confirm with https://pouchdb-bug-helper.glitch.me/ and file a new bug that would be great

**Comment by artin-phares** [comment]
I've tried more cases and believe we should use `{checkpoint: 'target'}` instead of `source`, since local checkpoints are on target (`replicate(remote, local)`).  
It worked for me because I've mixed up source and target.  

filed #7094
