### ISSUE TITLE
Pouch DB Ionic and IOS delete database when storage is low

### ISSUE THREAD

**Issue by pedro3900** [pouchdb/pouchdb#7093]
### Issue
I have implemented pouch DB with websql configuration and sqlite plugin in ionic, but in ios when  the storage is full the system delete de information of the database.
### Info
- Environment: hybrid app - Ionic
- Platform: iOS
- Adapter: WebSQL
- Server: PouchDB

### Reproduce
This is very complicated to reproduce happend when you have an IOS device with storage full.

**Comment by daleharvey** [comment]
There is nothing we can do about that, is an ionic / ios issue afaik

**Comment by pedro3900** [comment]
How you know that is it an ionic ios issue and not a problem with couchdb?

**Comment by daleharvey** [comment]
because pouchdb doesnt delete the data

**Comment by daleharvey** [comment]
If there was a way to tell the ios / ionic to not delete the database from pouchdb, happy to merge any PR's, heard of this issue before but not aware of anything we can do about it at the pouch level

**Comment by daleharvey** [comment]
Its very dependent on the platforms, in the browsers firefox and chrome on desktop they will wipe indexeddb on low storage space but users can ask for persistent storage, we try to specify as much as we can @ https://pouchdb.com/faq.html#data_limits but its changing constantly and there are a lot of platforms to keep track of
