### ISSUE TITLE
Sync doesnt handle checkpoint option

### ISSUE THREAD

**Issue by artin-phares** [pouchdb/pouchdb#7094]
Trying to avoid 404 checkpoint request errors when replicating databases with `checkpoint` option.  

```
The above 404 is totally normal. PouchDB is just checking if a remote checkpoint exists.
```

1.  (as expected) `.replicate(remote, db)` - error
https://habitual-writer.glitch.me/

2. (as expected) `.replicate(remote, db, {checkpoint: 'target'})` - no error
https://lucky-wildflower.glitch.me/

3.  (as expected) `.replicate(remote, db, {checkpoint: false})` - no error
https://hushed-windshield.glitch.me/

5. (bug?) `.sync(remote, db, {checkpoint: 'target'})` - error
https://sunrise-carrot.glitch.me/

4.  (bug) `.sync(remote, db, {checkpoint: false})`  - error (no "totally normal" log message)
https://empty-linen.glitch.me/

Chrome 64, win7

**Comment by artin-phares** [comment]
btw, what are the downsides of disabling checkpoints?  
because I do not want to overkill console errors if checkpoints are something very important.  

am i right that checkpoints are created during each replication process, so in case one failed, it can retry starting from last checkpoint, instead of re-doing entire replication from the start?

**Comment by daleharvey** [comment]
checkpoints last for the entire replication, not just session so if you disable them every time a user opens your app / site they will try to replicate the entire database again. checkpoints happen on server + client for safety but if you know you will never delete your server database you can safely checkpoint  on the client only

**Comment by daleharvey** [comment]
So this issue here is sync doesnt take the checkpoint option at all, you can workaround this by specifying `.sync({push: {checkpoint: false}, pull: {checkpoint: false}})`, sync could take the checkpoint option and pass the relevant options to replicate, more a new feature than a bug

**Comment by artin-phares** [comment]
i'm just wondering, if sync starts both-side replication, than what would be the `target`  (client/local checkpoints) in that case?..

should i ideally use something like `.sync({push: {checkpoint: 'source'}, pull: {checkpoint: 'target'}})`?

btw, I've tried workaround and it does not work for me  
https://immense-fish.glitch.me/
