### ISSUE TITLE
Replication get stuck on FileReader

### ISSUE THREAD

**Issue by paolosanchi** [pouchdb/pouchdb#7099]
### Issue
I use pouch db on an ionic 2 app, so there is Angular and Cordova involved.
On android devices (at least two different phone with chrome installed) it happens that the db pull freezes when a document with and attachment is received, no error is thrown and the replication doesn't complete.
I've verified that that's not about the specific attachment, it happens for every type.
The point is that this behaviour is not predictable, so, if I restart the app can happen that it can go on, and complete the replication.
I found the reason is that the the event "onloadend" is not fired by the file reader. The point in the source is the following:

```
// simplified API. universal browser support is assumed
function readAsArrayBuffer(blob, callback) {
  if (typeof FileReader === 'undefined') {
    // fix for Firefox in a web worker:
    // https://bugzilla.mozilla.org/show_bug.cgi?id=901097
    return callback(new FileReaderSync().readAsArrayBuffer(blob));
  }

  var reader = new FileReader();
  reader.onloadend = function (e) {
    var result = e.target.result || new ArrayBuffer(0);
    callback(result);
  };
  reader.readAsArrayBuffer(blob);
}
```

I couldn't find any article won the web about this, everything I found is related to solved issues.

### Info
- Environment: Ionic 2 / Angular / Codova
- Platform: Chrome 64.0.32.82.137 / Android 7.0.0;SM-A310F Build NRD90M / Samsung A3 2016 mini
- Adapter: IndexedDB 6.3.2
- Server: Cloudant

### Reproduce
As I said before, it happens sometimes. What I do is a simple db.replicate.from ().
If there is an attachment, it may stop with no error. Maybe in some case it takes a different polyfill, but this is just my guess. What it seems is that if it works, it still can read files for the whole session.

Update1:
I found when it freeze and when it doesn't. Sometime the FileReader comes from the plugin "cordova-plugin-file". In that case it works, but if it comes from the polyfill it doesen't fire the onloadend event.
I don't know why is chosen one on the other, but it seems that the polyfill created by ionic is the source of the issue.

**Comment by paolosanchi** [comment]
I think I found something and as it seemed, it's not related to pouchdb at all (and not sure it's already fixed).
Here is a reference for whose who will get struggled with this
#https://github.com/ionic-team/ionic-native/issues/505

**Comment by daleharvey** [comment]
Thanks for the updates, closing out
