### ISSUE TITLE
pouchdb-find always shows 「no matching index found」

### ISSUE THREAD

**Issue by goddyZhao** [pouchdb/pouchdb#7105]
my docs are something like:

```json
[
  {
    "type": "POST",
    "_id": "2017-12-12T06:00:32.646Z"
  },
  {
     "type": "xxx",
    "_id": "2017-12-13T06:00:32.646Z"
  }
  ...
]
```

I try to find the docs whose type = POST and sorted by _id (desc).

So, I try to do that with the following code:

```javascript
await db.createIndex({
  index: [ fields: ['type', '_id']]
});
await db.find({
  selector: { type: 'POST' },
  sort: [{_ id: 'desc'}]
});
```

but it shows that `no matching index found`.

Anyone knows how to create the correct index for such query? Thanks!

**Comment by pubkey** [comment]
Isnt the default sort-oder the _id field?

**Comment by garrensmith** [comment]
It will default sort by _id. So you don't actually need that sort.
The other thing is to try

```
await db.find({
  selector: { type: 'POST' },
  sort: [{type: 'desc', _ id: 'desc'}]
});
```
