### ISSUE TITLE
Sync works on Desktop, does not on Mobile

### ISSUE THREAD

**Issue by AlpineTech** [pouchdb/pouchdb#7106]
[www.zip](https://github.com/pouchdb/pouchdb/files/1744957/www.zip)

### Issue

The attached application will download over 400 documents with over 50 photo attachments when running in Chrome on a desktop, but will not when running in Cordova on Android.

### Info
- Environment:  Using cordova-fetch for cordova-android@~6.3.0 with PouchDB v6.4.3
- Platform: Android
- Adapter: none
- Server: CouchDB 1.6.1

### Reproduce

On a desktop unzip the attached www.zip file and then run the index.html file in Chrome.  When the page opens, click the sync button.  Expect the app to successfully download over 400 documents from the remote CouchDB, with over 50 photo attachments via PouchDB.replicate.

Repeat the same test, but add the www and config.xml to a cordova Android project (mine was too big to attach).  Expect the Android version of the Cordova App to run the  PouchDB.replicate successfully, but not download anything.

**Comment by Rolence** [comment]
Hello,
I have the same issue with my ionic 3 app. The documents sync on browsers when i serve the app but doesn't work when i deploy the app in an android device. I can't get or put documents from the Couchbase server to my android phone

**Comment by OutsourceNow** [comment]
Having this issue anyone solved this, syncs ok in browser but not in real devices tried android

**Comment by jetamartin** [comment]
I'm having this same issue as well....anybody have a suggested solution. I'm using the exact same js code in my webapp as the code I use in my cordova solution for Android platform.  In my "catch" for the replication the results object indicates "doc_write_failures: 0, docs_read: 0, docs_written: 0",  errors: [], las_seq: 0, ok: false, status: aborting". These are the relevant values from the returned results object. 

Any thoughts?
