### ISSUE TITLE
replicate to Remote DB is always code: "ETIMEDOUT" in pouchdb 6.4.3

### ISSUE THREAD

**Issue by vjijardar** [pouchdb/pouchdb#7108]
Hello,

I'm using pouch-db 6.4.3  with angular 5.x.x. when i'm call db.replicate() or db.replicate.to() it's always go in error callback. error is ETIMEOUT

CustomPouchError {code: "ETIMEDOUT", status: 0, docId: "_local/Kzm11seQseTks09rJAGRmQ%3D%3D"}
![screenshot 73](https://user-images.githubusercontent.com/19422534/36534325-3ebfcc7e-17ec-11e8-81f0-b9b2b309eb53.png)

### Info
- Environment: (Angular 5.x.x)
- Platform: (Chrome)
- Adapter: (IndexedDB)
- Server: (CouchDB)

**Comment by daleharvey** [comment]
Looks like something is wrong with your network settings, are you sure the server is accessible and has CORS enabled, check the network tab

**Comment by daleharvey** [comment]
With no more information, everything suggests this is a setup issue so closing out

**Comment by vjijardar** [comment]
See the Network call is all canceled after **ETIMEDOUT**
![screenshot 74](https://user-images.githubusercontent.com/19422534/36671625-535682f2-1b22-11e8-8cab-aa00b392bbf3.png)
