### ISSUE TITLE
Live replication has inconsistent updates

### ISSUE THREAD

**Issue by aguynamedben** [pouchdb/pouchdb#7116]
Hi, thanks for all the work you do on PouchDB. I love it an it's making a project very fun to work on. Thanks.

### Issue
I'm using 1-way replication from an upstream database to a downstream database.  If I update docs in the upstream database, changes make it into the upstream database reliably, but they're not replicated down to the downstream database reliably. This leaves the downstream database in an inconsistent state. I also observe that the changes feed for the downstream database first updates, indicating updated documents, but the documents given are not updated with the expected change.

### Info
- Environment: Node.js
- Platform: MacOS
- Adapter: Default
- Server: N/A

### Reproduce
I've created a reproduction with a detailed account of what is happening here: https://github.com/aguynamedben/pouchdb-bug

Basically, I insert data in the downstream database, then setup replication from the upstream database to the downstream database. I expect to change a value in the upstream database (i.e. `url`) and see that reflected in (1) the downstream database, and (2) the changes feed for the downstream database. Instead, I see inconsistent results.

This was noticed while working on a more complicated app. My app depends on the changes feed of a downstream database to know when to re-index data in a search index. I noticed that the search index was inconsistent, and that updates were not making it into the index. Then I hunted down that data was going into the upstream database correctly but for some reason not making it into the downstream database's changes feed.

I'd be happy to help debug this if you can point me in the right direction. Thanks again for your hard work and any leads you can provide on what might be causing this.

Here's the output of my test run:

```
Sequence!ben:/Users/ben/code/pouchdb-bug$ yarn build && yarn test
yarn run v1.3.2
$ babel src -d lib
src/Tester.js -> lib/Tester.js
src/index.js -> lib/index.js
✨  Done in 0.57s.
yarn run v1.3.2
$ node ./lib/index.js
Tester inited
========== initialIndexing() ==========
Upserted doc 1 in this.downstreamDB { updated: true, rev: '1-b7460083bb3843febd5290d459600144' }
Upserted doc 2 in this.downstreamDB { updated: true, rev: '1-43c574ac83bb452e87b5f83417e7b887' }
Upserted doc 3 in this.downstreamDB { updated: true, rev: '1-e9caabbc78ef412f9b947749acf79136' }
Initial indexing finished
========== startReplication() ==========
========== createUpstreamDBChanges() ==========
Upserted doc 1 in this.upstreamDB { updated: true, rev: '1-502322b86df84f8c9fbc438b8af32a04' }
Upserted doc 2 in this.upstreamDB { updated: true, rev: '1-485cd706cf2f42efb0386f1677033ba4' }
Upserted doc 3 in this.upstreamDB { updated: true, rev: '1-cc66469291cd4ec9808a47f22a47ccae' }
Done creating upstream changes
CHANGE -  { title: 'Doc 1',
  url: 'http://mysite.com/doc1',
  _id: '1',
  _rev: '1-b7460083bb3843febd5290d459600144' }
CHANGE -  { title: 'Doc 2',
  url: 'http://mysite.com/changed/doc2',
  _id: '2',
  _rev: '1-485cd706cf2f42efb0386f1677033ba4' }
CHANGE -  { title: 'Doc 3',
  url: 'http://mysite.com/doc3',
  _id: '3',
  _rev: '1-e9caabbc78ef412f9b947749acf79136' }
========== analyzeData() ==========
===== Showing upstreamDB docs =====
UPSTREAM DOC { title: 'Doc 1',
  url: 'http://mysite.com/changed/doc1',
  _id: '1',
  _rev: '1-502322b86df84f8c9fbc438b8af32a04' }
UPSTREAM DOC { title: 'Doc 2',
  url: 'http://mysite.com/changed/doc2',
  _id: '2',
  _rev: '1-485cd706cf2f42efb0386f1677033ba4' }
UPSTREAM DOC { title: 'Doc 3',
  url: 'http://mysite.com/changed/doc3',
  _id: '3',
  _rev: '1-cc66469291cd4ec9808a47f22a47ccae' }
===== Showing downstreamDB docs =====
DOWNSTREAM DOC { title: 'Doc 1',
  url: 'http://mysite.com/doc1',
  _id: '1',
  _rev: '1-b7460083bb3843febd5290d459600144' }
DOWNSTREAM DOC { title: 'Doc 2',
  url: 'http://mysite.com/changed/doc2',
  _id: '2',
  _rev: '1-485cd706cf2f42efb0386f1677033ba4' }
DOWNSTREAM DOC { title: 'Doc 3',
  url: 'http://mysite.com/doc3',
  _id: '3',
  _rev: '1-e9caabbc78ef412f9b947749acf79136' }
✨  Done in 3.41s.
Sequence!ben:/Users/ben/code/pouchdb-bug$
```

**Comment by aguynamedben** [comment]
To be clear, what I expect is for all of the downstream docs to have the new URL structure as seen in the upstream database (i.e. http://mysite.com/changed/doc3 instead of http://mysite.com/doc3). I also expect the changes feed on the downstream database to emit events with docs that have the update included.

**Comment by daleharvey** [comment]
Sorry haven't had the chance to run your reproduction, will when I get time on a computer, but from your log it looks a lot like you are writing the same document to different databases then replicating between them, this will create conflicts and with conflicts you may not get the document you expect when reading it

**Comment by aguynamedben** [comment]
@daleharvey Thanks. I guess I assumed upserting into the upstream database would cause updates to go downstream.

- Insert v1 documents in `downstream`, then wait until those writes finish.
- Insert v2 documents in `upstream`
- Documents in downstream are a mix of `v1` and `v2`. I expected them to be all `v2` documents. Maybe there's some more learning about PouchDB replication and versioning I need to do.

I think I might try a different method of storing loading docs that relies on replication less. I'll close this for now and let you know if I further determine this is an issue. Thanks for looking at the logs.
