### ISSUE TITLE
Replications is paused due to error {"status":0,"name":"unknown","message":"changes rejected"}

### ISSUE THREAD

**Issue by jahtalab** [pouchdb/pouchdb#7119]
### Issue
Replications is paused due to error {"status":0,"name":"unknown","message":"changes rejected"}, Even though there are no changes to be replicated.

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
It happens If the webpage using Pouchdb is kept open while the OS goes to sleep (or after it wakes up). I'm testing this on macOS and it happens when I close the lid and open it later.

**Comment by daleharvey** [comment]
I think I have seen this before although not entirely sure what the bug is here, are you expecting it to resume and if so are you using retry:true ?

**Comment by jahtalab** [comment]
@daleharvey , I'm not sure if it should resume, at least replicating from local to remote should not be resume since I haven't made any changes to the local instance. But I guess checking if there are any changes in the remote that needs to be replicated to the local, should be resumed and paused again (without error) if there are no new changes.

My configuration is something like:
```
PouchDB.replicate(local, remote, {
      live: true,
      retry: true
    });

PouchDB.replicate(remote, local, {
      live: true,
      retry: true
    });
```

**Comment by daleharvey** [comment]
Seeing that error is not a bug itself, are later changes being replicated? / What is happening that you aren't expecting?

**Comment by daleharvey** [comment]
Unclear if there is a bug here
