### ISSUE TITLE
process.nextTick() in shipped browser code for pouchdb-find

### ISSUE THREAD

**Issue by mkubilayk** [pouchdb/pouchdb#7120]
### Issue
Both `pouchdb-find/lib/index-browser.es.js` and `pouchdb-find/lib/index-browser.js` seem to have `process.nextTick` which is not available in the browsers. 

It looks like other uses of `process.nextTick()` were removed in #5898. This probably precedes `pouchdb-find`. 

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: Cloudant

### Reproduce
```
yarn add pouchdb-find@6.4.3
```

See `node_modules/pouchdb-find/lib/index-browser.es.js#115`.

**Comment by daleharvey** [comment]
I thought we would expect browserify to polyfill that, we aren't seeing test failures but still likely best to replace vwith settimeout

**Comment by mkubilayk** [comment]
Thanks!
