### ISSUE TITLE
Not able to run npm test successfully on newest build

### ISSUE THREAD

**Issue by mishraak** [pouchdb/pouchdb#7123]
I am not able to run npm test successfully on the newly cloned repository.  I am using Mac OS High Sierra 10.13 and running Couch DB successfully on 5984

It fails after throwing below error. I have followed guide from https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md 

  169 passing (12s)
  1 failing

  1) suite2 test.attachments.js-http Measures length correctly after put():

      AssertionError: expected md5-JE5r7hHlsT2wUwP3vU+WVg== to be in: ["md5-qUUYqS41RhwF0TrCsTAxFg==","md5-aEI7pOYCRBLTRQvvqYrrJQ==","md5-jeLnIuUvK7d+6gya044lVA=="]: expected -1 to not equal -1
      + expected - actual

      
      at tests/integration/test.attachments.js:1294:49
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pouchdb-monorepo@7.0.0-prerelease test-node: `npm run build-node && bash bin/test-node.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pouchdb-monorepo@7.0.0-prerelease test-node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mishraak/.npm/_logs/2018-03-05T07_53_31_244Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pouchdb-monorepo@7.0.0-prerelease test: `bash bin/run-test.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pouchdb-monorepo@7.0.0-prerelease test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mishraak/.npm/_logs/2018-03-05T07_53_31_289Z-debug.log
pouchdb $ 

Please suggest what I am doing wrong?

**Comment by daleharvey** [comment]
Have you run the tests multiple times and seeing the same failure? And what version of couchdb are you running, we generally only test against latest stable

**Comment by mishraak** [comment]
Apache CouchDB version is 2.1.1. Yes, I ran it multiple times but saw same error. Cleaned the repo and ran again but same error.

**Comment by daleharvey** [comment]
hrm, is there anything about your configuration that may change how md5's get generated? how are you actually running 2.1.1, just from the download? 

There are other bugs that will come up against 2.1.1 that I am fixing in https://github.com/pouchdb/pouchdb/issues/7160, however this is not one of them, curious as to whats happening, basically we are testing that your couch generated the md5 of an attachment that we expect and for some reason its different

**Comment by daleharvey** [comment]
Also if you could try with `SERVER=couchdb-master npm test` just to see what happens?

**Comment by daleharvey** [comment]
@mishraak So all tests should be passing by default now, could you try with / without `SERVER=couchdb-master` on an up to date build, and if still failing give me the couch version / how you install it, what platform and the node / npm versions please? cheers

**Comment by daleharvey** [comment]
So pretty sure I will have fixed this issue in https://github.com/pouchdb/pouchdb/issues/7160, without setting SERVER the tests did not use cycled database names and that caused 2.1.1 to fail often on the same test, file a new issue if you are still having problems cheers
