### ISSUE TITLE
query() defaults to reduce

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#7127]
### Issue

When calling `db.query()`, `options.reduce: true` defaults to `true`.  [According to the docs](https://pouchdb.com/api.html#query_database):

> Defaults to `false` (no reduce). 

### Info
- Environment: browser, Pouch 6.4.3
- Platform: Chrome
- Adapter: IndexedDB
- Server: none

### Reproduce

```
const db = new PouchDB('reduced-to-tears');

db
  .put({
    _id: '_design/mapred',
    views: {
      mapred: {
        map: function(doc) { emit(doc._id); }.toString(),
        reduce: function() { return 666; }.toString(),
      }
    }
  })

  .then(() => db.query('mapred'))
  .then(console.log)

  .then(() => db.query('mapred', { reduce:true }))
  .then(console.log)

  .then(() => db.query('mapred', { reduce:false }))
  .then(console.log)

  .catch(console.log);
```

->

![screen shot 2018-03-06 at 09 29 49](https://user-images.githubusercontent.com/191496/37021755-f468a5e0-2120-11e8-8eee-0a02c80b41ed.png)

### Fix

**_IMO_** the documentation is correct, and the code should be fixed.

**Comment by daleharvey** [comment]
I think when Couch is obviously wrong (like changing continious to live) we can break compatibility to improve, however map reduce is fairly non obvious in the first place so I think keeping compat and fixing the docs is the right thing here, we can hopefully just replace it all with find anyway :)
