### ISSUE TITLE
Errorr syncing data from pouchdb to couchbase server via the Couchbase-sync-gateway

### ISSUE THREAD

**Issue by Rolence** [pouchdb/pouchdb#7132]
### Issue
This is the Typescript method to sync the data to couchbase-syncgateway
public sync(remote: string) {
    let remoteDatabase = new PouchDB(remote);
    this.database.sync(remoteDatabase, {
        live: true
    }).on('change', change => {
        this.listener.emit(change);
    }).on('error', error => {
        console.error(JSON.stringify(error));
    });
}

When you call the method on importing the provider in page like
ionViewDidLoad(){
this.db.sync("http://localhost:4984") //This is aimed at syncing all documents available
}

When the page loads this error message is seen in the console of the browser

{"status":0,"name":"unknown","message":"getCheckpoint rejected with ","result":{"ok":false,"start_time":"2018-03-07T09:36:44.083Z","docs_read":0,"docs_written":0,"doc_write_failures":0,"errors":[],"status":"aborting","end_time":"2018-03-07T09:36:44.207Z","last_seq":0},"__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","cancelFn":null,"runCount":0}}

### Info
- Environment: (Node.js/browser/Ionic 3 app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Couchbase/Couchbase-Syncgateway/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by daleharvey** [comment]
We dont support couchbase @ https://github.com/pouchdb/pouchdb/issues/5820

**Comment by mark-ellul** [comment]
@Rolence did you ever figure out the issue?

**Comment by Rolence** [comment]
Yes I did
