### ISSUE TITLE
Removing storage option

### ISSUE THREAD

**Issue by annevk** [pouchdb/pouchdb#7134]
We're removing the storage option from Firefox as per 
https://www.fxsitecompat.com/en-CA/docs/2018/storage-option-for-indexeddb-open-has-been-deprecated/. You might want to remove "IndexedDB-only options" from the documentation therefore (or mark it obsolete).

**Comment by daleharvey** [comment]
Yup seen the intent to unship, firefox only and rarely used plus we have a point release coming up so good time to remove, cheers

**Comment by annevk** [comment]
Thanks @daleharvey!

**Comment by danielo515** [comment]
Sorry I'm confused. Isn't indexedDB the only storage option after the removal of webSQL?

**Comment by annevk** [comment]
`storage` here refers to an initialization member used when constructing a database. It's not that generic.

**Comment by danielo515** [comment]
Thanks for the clarification
