### ISSUE TITLE
Remove websql

### ISSUE THREAD

**Issue by garrensmith** [pouchdb/pouchdb#7135]
### Issue
Safari 10.1 onwards has a good implementation of IndexedDB, we no longer need to support the fruitdown adapter. Nolan has also stopped maintaining [fruitdown](https://github.com/nolanlawson/fruitdown)

I propose we either just delete the fruitdown adapter or move it to pouchdb-community. I think its nice to try and keep the pouchdb repo to just the packages that are maintained.

### Info
- Environment: Browser
- Platform: Browser
- Adapter: Fruitdown

**Comment by daleharvey** [comment]
I agree although I would like to see https://github.com/pouchdb/pouchdb/issues/7057 fixed and the dust settle on the 7.0 release before we get into a position where we need to do a lot of work to reenable ios if idb is still not actually usable

**Comment by daleharvey** [comment]
To make a start on this however, removing phantom to clean some things up and save precious travis cycles

**Comment by daleharvey** [comment]
pingbot
