### ISSUE TITLE
Possible to write local doc without knowing rev?

### ISSUE THREAD

**Issue by akowald** [pouchdb/pouchdb#7139]
I noticed in couchdb 2.1.1 you can PUT local docs without the revision id and it always updates the latest doc. Try this in pouchdb 6.4.3 and you get 409s. If there's no revision history stored in local docs, shouldn't there be a way to write them without having to fetch them first? Thanks!

Edit: This is the behavior observed from couchdb:
> curl -X GET https://couchdb/db/_local/test
{"error":"not_found","reason":"missing"}
curl -X PUT https://couchdb/db/_local/test -d '{"hi":"there"}'
{"ok":true,"id":"_local/test","rev":"0-1"}
curl -X GET https://couchdb/db/_local/test
{"_id":"_local/test","_rev":"0-1","hi":"there"}
curl -X PUT https://couchdb/db/_local/test -d '{"hi":"thereeee"}'
{"ok":true,"id":"_local/test","rev":"0-1"}
curl -X GET https://couchdb/db/_local/test
{"_id":"_local/test","_rev":"0-1","hi":"thereeee"}
curl -X PUT https://couchdb/db/_local/test -d '{"hi":"last_one","_rev":"0-100"}'
{"ok":true,"id":"_local/test","rev":"0-101"}
curl -X GET https://couchdb/db/_local/test
{"_id":"_local/test","_rev":"0-101","hi":"last_one"}

**Comment by daleharvey** [comment]
@willholley @rnewson is this true? seems to "conflict" with the documentation @ http://docs.couchdb.org/en/2.1.1/api/local.html#put--db-_local-docid

**Comment by rnewson** [comment]
local docs are a bit weird, we don't do all the MVCC stuff for them. I thought we did check for matching _rev but perhaps that was silently broken in 2.0? (cc @davisp)

**Comment by davisp** [comment]
Docs are wrong. We've had revision checking disabled there for a long long time cause it broke internal replication if there was an error (because the docs aren't replicated). Though for source of truth on that you'd want to ask @kocolosk for precise details.

https://github.com/cloudant/bigcouch/blob/master/apps/couch/src/couch_db_updater.erl#L703-L710

**Comment by davisp** [comment]
Hah. That's also the infamous grab bag commit as well.

https://github.com/cloudant/bigcouch/commit/7393d62b7b630bee50f609d0ae8125d33f7cda2b

So nothing to track any other discussion further.

**Comment by davisp** [comment]
However, the docs are still wrong even if we hadn't done that long ago. Local docs have integer id revisions that are a much different format and the old "revision" checking just compared the integer is `Curr + 1` basically.
