### ISSUE TITLE
Trigger Replication failing on iOS with WebSql and Android with cordova-sqlite

### ISSUE THREAD

**Issue by webnoob** [pouchdb/pouchdb#7144]
### Issue
I've had my app deployed to browser and Android for a couple of weeks without issue (letting pouch decide on a default adapter), upon deploying to iOS the replication won't work properly. I'm sync'ing about 8000 docs (6mb) and at some point I will get a response like:

```
{
  "result": {
    "ok": false,
    "start_time": "2018-03-11T08:40:15.432Z",
    "docs_read": 100,
    "docs_written": 100,
    "doc_write_failures": 0,
    "errors": [
      
    ],
    "last_seq": "108-g1AAAAJjeJydz10KwjAMAODiBEVFFA-gJ5D-2HV9cjfRtV0ZY-qTz3oTvYneRG9S-zMQYQgbgQQS8pFUAIBhESkwl6ezLJRIEWZraANVdtTLgFgaY8oiyhYH2xgQFQueo6aFP4xY2Sy2tTTzEoaM54S3lVIn7Wpp6iWJGU4obSvtnXT5uUlLSRBSLaVj32ZwtcViN6dNvMaQ5hpuOmn3oD2cNvZaRhNKdDftGbSX00bhU6K4VHEn7R0089U4x1Akommv_ACnCZ8M",
    "status": "aborting",
    "end_time": "2018-03-11T08:40:17.254Z"
  }
}
```

On iOS the adapter being chosen is WebSQL (not looked at on Android as it was working).

I thought this might be an issue with DB size so I've moved over to using the `cordova-sqlite` adapter but now I am getting the same symptoms on android as well.

I really don't know where to go from here. Initially I had the doc batch count at 500 and have changed it to 100 to see if that helps - That helped on Android and it didn't fail on the first download of the batch but did eventually (after about 4000 docs) fail.

I also tried forcing the `idb` adapter but that just fell over in iOS.

These are my packages:

```
    "pouchdb": "6.2.0",
    "pouchdb-adapter-cordova-sqlite": "^2.0.2",
    "pouchdb-authentication": "^0.5.5",
    "pouchdb-find": "^0.10.5",
    "pouchdb-quick-search": "^1.2.0",
    "pouchdb-utils": "^6.4.3",
    "raven-js": "^3.20.1",
    "relational-pouch": "github:webnoob/relational-pouch",
```

Worth noting, I had to manually add the `pouchdb-utils` package otherwise I got an error about `pouchdbutils.assign` is not a function.

At this point I really don't know where to go next - I'm on the cusp of being able to launch my app and am being thwarted by Apple 😠 

Edit: Interestingly, I've just seen this issue happen on the `idb` adapter as well now on my cordova android app ...

### Info
- Environment: hybrid app
- Platform: iOS/Android
- Adapter: WebSQL/cordova-sqlite
- Server: CouchDB

### Reproduce
Unable as it's mobile builds

**Comment by webnoob** [comment]
Ok, so for some reason now, this appears to be happening all the time on Android and iOS.

**Comment by webnoob** [comment]
I've just updated to the latest packages so that iOS is using `idb` and am still getting the same error.

**Comment by webnoob** [comment]
Ok, it seems that if I keep triggering the replication, it will at some point catch up and sync all the documents.

**Comment by webnoob** [comment]
I've had to implement a hacky workaround on this for now. When the replication fails with this error, I retry up to 3 times (the first one normally gets it working a little more), then when it eventually fails (which it will), I log the user out of the couch db, log them back in and kick start the replication again and it manages to get through all the data.

If someone could help me understand what `"status": "aborting"` actually refers to, I might be able to sort something out properly ...

**Comment by daleharvey** [comment]
`"status": "aborting"` just means its been unexpectedly stopped, its hardcoded. if you do `replication.on('error', console.error.bind(console));` you should hopefully get more information about what is causing it, also are you using retry: true?

**Comment by webnoob** [comment]
Ah, right. I'll give that a go!

No, not on retry. I'm triggering this manually before the user enters my app to make sure they have latest info.

**Comment by daleharvey** [comment]
If you retry: true you can cancel when you get a paused() with no error, that way it will retry failures and call paused once its caught up

**Comment by webnoob** [comment]
Good to know, thanks. I'll give it a go and report back if it's something I'm unsure of.

**Comment by webnoob** [comment]
Ok, I've just tried binding to the error and don't get much more information except it's in object form instead of JSON.

![image](https://user-images.githubusercontent.com/10404747/37418341-e58219e6-27a9-11e8-875e-09a72f215987.png)

**Comment by cfz42** [comment]
Not sure if your problem is the same but I remember some unicode characters completely broke my application with cordova-sqlite.
After I cleaned the database from these "invisible" characters, everything worked again, but as far as I remember the error was different.. who knows maybe this can help.

**Comment by webnoob** [comment]
Just thought I'd add more to this as I've come back to it today. This started happening on desktop as well for some reason. Setting `retry: true` did actually sort it out though which is great.

I'd still be interested to know why it happens but it seems to handle it Ok when re-trying so no major issue.
