### ISSUE TITLE
Discussion about PouchDB Attachment-Performance

### ISSUE THREAD

**Issue by clooudch** [pouchdb/pouchdb#7152]
Hello PouchDB-Members

I intend to use PouchDB as the main storage for a music library. So there are a few points that i am worried about and i want to hear the opinion of PouchDB-Developers, as they are very familiar with the PouchDB-Architecture and the best practices while using PouchDB.

So first, my music library solution should be portable and capable of being used on many devices simultaneously and the option to replicate the library from one device to another is important. (Replication is gonna happen over WLAN by using a mDNS).

At first i thought about using Couchbase Lite as it seems to have a better performance especially with large attachments (audio/image files). But my main concern with Couchbase is that no all features are available in the Community-Edition (P2P Replication is Enterprise exclusive).

My plan is to develop the music library for 2 environments:
- Desktop (Windows/macOS/Linux) | over Electron (by GitHub)
- Mobile (iOS/Android) | over React Native (by Facebook)

I am planning to implement the business logic on a simple rest api node.js server which will be running in the background, so the user interface (electron -> natively  and react-native -> [node.js mobile](https://github.com/janeasystems/nodejs-mobile)) can manipulate/fetch data over a rest api. That simple node.js server will be using PouchDB as the storage for the data. This approach has the main advantage that both user interfaces are capable of using the same backend and streaming the audio/images over HTTP seems to be the best (platform independent) solution.

So here are my concerns (especially about attachments) about the usage of PouchDB in my scenario:
- **Performance/Replication:** I expect 1'000 to 10'000 (max) songs in the database (on average). In have a strange feeling that PouchDB won't be able to handle that many documents. PouchDB seems to be great but i am unsure how well it is going to perform. Also i think replication in the worst case (10'000 songs replicating to an empty device) is gonna be very slow and unstable as it is going to be a huge amount of data (mainly media files). Does anybody have experience with PouchDB under such a load? Can replication with maybe 100GB of data be considered stable (but slow?).
- **Streaming:** CouchDB itself is capable of streaming media as the http rest api handles byte serving very well. Media files can be streamed like static files which makes CouchDB a great solution for my scenario. But sadly PouchDB is not that great at streaming. the rest api (pouchdb-express) does not handle byte-serving and streaming so streaming is kinda limited. Can we do something about that? I think to implement byte handling we need a way to stream attachments out of the underlying PouchDB-Storage-Adapter, but can we achieve this?
- **Storage:** Currently i am not very satisfied with the way that PouchDB stores attachments. I am not quite sure but i think PouchDB (leveldown adapter) stores the attachments in a separate leveldown database. Which seems kind of bad, especially with many larger attachments. There should be a better solution to handle this...  A better example for attachment storing is Couchbase as it stores every attachment in a separate file in a dedicated folder next to the document storage. I think for PouchDB this should also be the favoured way of storing attachments as it hopefully perform better and allows streaming over node.js Streams natively by using the fs-module. I am currently not quite sure how we can achieve this. But i am guessing that we integrate this small change into the leveldown adapter or maybe even create a new adapter (based on the leveldown adapter) for this.

I hope someone has time to help me with my project. I only need some advises and guides as i am currently not sure which steps i want to take next. I am also temped to fork the PouchDB repository and implement those chances on my own, but i think it would be better to integrate this into PouchDB itself as others could profit from these changes as well.

Of course i am gonna open source my music library solution to the public once it is finished. If someone has time and is interested in helping me, then dont hesitate to contact me :)

Thank you for reading this and dont forget to write a comment. ;)

Greetings from Switzerland

**Comment by garrensmith** [comment]
@clooudch I'm not an expert on this, but storing lots of images in CouchDB/PouchDB really isn't a good idea. It's better to save them separately and then link to them in your PouchDB documents. But its also better to test your use case before coming to any decisions. So I would recommend building a simple concept that saves lots files to Pouchdb and replicate it and see if it is a problem in your use case or not.

**Comment by clooudch** [comment]
@garrensmith Thank you for your comment. I know that CouchDB and PouchDB are not really designed to contain many larger attachments in there. I also thought about storing the media files outside of PouchDB but sadly, i would then lose all the replication/revision functionality that comes with PouchDB.  To store the media files outside of PouchDB i would have to implement all the replication/revision logic (that comes with PouchDB) by myself and i do not really believe that this is the best solution. PouchDB already has replication/revision features built in, so why should i not use them?

I am talking about adding better attachment support to PouchDB by extending the api spec with streaming capabilities.

I am aware that testing the performance of PouchDB by myself with a simple conceptional application would be best, and this is probably also my next step, but the performance is not my only concern:

Better attachment storage and streaming capabilities would be very appreciated. So my main questions are: How could we integrated these into PouchDB and why aren't these features available yet in the first place?

**Comment by clooudch** [comment]
Theoretically it should be very easy to integrate these features at least into the [leveldb-adapter](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-leveldb-core/src/index.js). I am not quite sure yet, but i think we would just have to replace the binaryStore for the attachments with a folder and use the node-js-native fs-module to read/write/stream them. That folder could then contain all attachments named after the digest (md5 hash) of the attachment content (that hash is already known). This would also be optimized in the case where two files with the same content are saved twice to the database. They would then only appear once in the folder.

Well i think for the leveldb-adapter at least it should be no problem to implement this. The main problem is: How are we gonna take advantage of these new streaming capabilites? We could add another method to the spec. But I am afraid that other adapters would not be able to implement these new streaming capabilites. Maybe we need a way to also implement attachment streaming into the browser environment, so every adapter would then be able to implement the new api spec.

I think streaming capabilites would give us a huge performance improvement when working with large attachments and this would make PouchDB even more advanced and useful for much more usecases. For example we could then use the attachment streaming capabilites in the pouchdb-server and allow http byte streaming which would be gorgeous.

**Comment by clooudch** [comment]
Maybe the best solution to implement this is by allowing the adapter to chose whether it wants to return a stream or a buffer, or maybe it can return both depending on the parameters. I do not believe that it would be possible to implement attachment streams in the browser. Even with blobs it's kinda [difficult](https://github.com/nolanlawson/state-of-binary-data-in-the-browser). So streaming attachments will probably be exclusive to node.js.

**Comment by clooudch** [comment]
@daleharvey As the author of the pouchdb-adapter-leveldb-core module, what do you think about attachment streaming?

**Comment by clooudch** [comment]
It seems like pouchdb-adapter-leveldb-core is designed to work in the browser too. As you can pass in other LevelDown compliant implementations as well (fruitdown for example). It will be kinda difficult to implement attachment streaming without breaking the browser part.

So i think the only solid solution to implement attachment streaming is creating a completly seperate (node.js only) adapter which uses leveldown and a folder for attachment files. This could then be purely optimized for node.js. Attachment streaming can then be used as an extra feature on top of the normal api spec. And also the express-pouchdb module can take advantage of these features (as it is also node.js only) to enable http byte streaming.

But sadly i do not think that we could use the attachment streaming feature to improve replication as the replication module needs to support the browser (and browsers will never support attachment streaming, i guess). So to take advantage of attachment streaming inside of the replication module we would need to create a separate replication module which needs to be again node.js exclusive.

I am not quite sure how much attachment streaming would improve the replication process and if it's even worth the effort to make all these changes to the pouchdb source. I will probably dig deeper into the topic and maybe I will soon do some testing to find out how much attachment streaming could potentially improve replication and overall speed.

For now i will do some testing with a separate pouchdb-adapter (node.js only).

**Comment by daleharvey** [comment]
So as you have noticed, PouchDB's main focus is on the browser where there is no canonical streaming APIs, I dont believe we can pull a stream out of indexeddb yet, so its unlikely we want to add any API's for streaming, we could consider an option but would also want to look at solutions that dont mean changes to our api.

You keep mention streaming without talking about the reason for streaming, the replication process is pretty complicated and there is no reason for thinking about using streaming in it (and a lot of reasons to not), for a media player I would image streaming is useful for trying to play some music before the entire song has downloaded but that isnt something we are going to be able to support in a generic replicator, nor is it something likely enabled by having a streaming api at all, but more something that the media elements you use in electron / <audio> tag need to support

A new adapter or option to have attachments stored on the fs and then you can access those directly is an option, we already need to write a new level adapter in the same style as idb-next (simplifies the underlying schema) and if you are going to want to do adhoc quieries  over 10000 documents you are probably going to want native pouchdb-find support

Dropping browser support for the leveldb adapter I am not that worried about, we are already about to drop fruitdown and dont see a huge gain in having the pluggable backends for level, I at one point considered writing a level adapter that was just .json files in a folder

Sounds like you need to experiment a bit, happy to help out with any more questions

**Comment by clooudch** [comment]
Hello @daleharvey. Thank you for your response and your time.

Yes, i looked through the source code of pouchdb and found out many things on myself. Like you said, the main goal of pouchdb is bringen a syncable offline database to the browser and it was not designed to contain lots of documents (and especially lots of media files). But i think we can use it as a backend (node.js based) for small to medium peer-to-peer applications. Sadly there are not many „embedded“ databases out there that work platformindependent and support peer-to-peer replication, so I consider pouchdb the only solution.

I know that replication is very complicated and i do not know very much about the way it works in pouchdb/couchdb. that‘s the reason why i want to avoid writing replication logic by myself. i am better gonna leave that to the professionals and stop reinventing the wheel.

Like i said i am unsure how streaming attachments could potentially improve replication. You said, it wont and there‘s no reason to do it. But won‘t streaming large attachments improve memory usage and maybe even performance? i dont know (yet).

I am not quite sure what you mean by „electron / tag need to suport streaming“. I am not talking about using pouchdb in electron. I would rather use it in a node.js backend and allow http byte streaming over a rest api. That api could then be used in the html tag (src attribute). Did i confuse you or did you mean something else?

What do you mean by „native pouchdb-find“ support? Can you give me a link or a simple explanation on that topic?

i will try to write a new leveldb adapter (as with idb-next). As i am gonna experiment with attachments in the fs (as separate files) anyway.

But do you generally agree that the idea of storing each attachments in a separate file would by a huge improvement over storing them in the leveldb database?

**Comment by daleharvey** [comment]
> What do you mean by „native pouchdb-find“ support? Can you give me a 
> link or a simple explanation on that topic?

https://github.com/pouchdb/pouchdb/issues/6543 has some discussion, basically doing arbitrary quiries right now with pouch can be too slow and cumbersome, idb-next aims to fix that for indexeddb, equivalent needs done for level

> But do you generally agree that the idea of storing each attachments 
> in a separate file would by a huge improvement over storing them in the leveldb database?

Its a tradeoff, using multiple different ways to store things (level + fs) means more complexity, but it may perform better and enable new use cases

**Comment by clooudch** [comment]
Thank you for your help.

I am currently trying to get more familiar with the codebase of pouchdb. I am very new to pouchdb, so please excuse me when i ask "stupid" questions.

> #6543 has some discussion, basically doing arbitrary quiries right now with pouch can be too slow and cumbersome, idb-next aims to fix that for indexeddb, equivalent needs done for level

By `idb-next`, you mean the adapter `pouchdb-adapter-indexeddb`, right? I can not find anything about `native pouchdb-find support`. As i have seen in the source of `pouchdb-find`, it is using custom design documents for creating/deleting/querying indexes, so the whole find method seems to rely heavily on map/reduce which seems in turn to be implemented in `pouchdb-abstract-mapreduce`. I am not quite sure yet, but i think by `native pouchdb-find support`, you mean implementing custom query/viewCleanup functions (as proposed here #3775)? These functions then will get executed from the `pouchdb-abstrac-mapreduce` module. Is that correct? That would somehow make sense, as it would maintain backwards compatibility, but what i do not understand is that the `pouchdb-adapter-indexeddb` adapter does not implement these custom query/viewCleanup methods. Soo where exactly is the `nativ-pouchdb-find support` implemented in `idb-next`?

**Comment by daleharvey** [comment]
No bother, no stupid questions

> By idb-next, you mean the adapter pouchdb-adapter-indexeddb, right?

Yup

> As i have seen in the source of pouchdb-find, it is using custom design documents 
> for creating/deleting/querying indexes, so the whole find method seems to rely 
> heavily on map/reduce

We (Nolan) built pouchdb-find on top of mapreduce because we already had a method for building indexes, it could share a bunch of code and get started faster and didnt involve rewriting the entire codebase for an experiment, however meant it had all the limitations of mapreduce, my plan is to implement the pouch-find syntax in idb-next without using mapreduce and using indexedDB indexes directly. This is why I wrote idb-next as it needed a new underlying storage mechanism in order to use indexes, leveldb is going to need the same work done to get native pouchdb-find support as well. Its not a huge amount of work and I mention it because if you were to write a new level adapter, I would base it off idb-next and not the level adapter

**Comment by clooudch** [comment]
> This is why I wrote idb-next as it needed a new underlying storage mechanism in order to use indexes, leveldb is going to need the same work done to get native pouchdb-find support as well. Its not a huge amount of work

Yeah. I understand that, but i do not understand where this new `native pouchdb-find` feature is implemented? I am somehow unable to find it in the source code of `idb-next`. The `pouchdb-adapter-indexeddb` does not export any query/viewCleanup methods, which could then be called from `pouchdb-abstract-mapreduce`. Where is it?

> and I mention it because if you were to write a new level adapter, I would base it off idb-next and not the level adapter

I will probably need inspiration from both adapter implementations ^^. But yeah, basing it from `pouchdb-adapter-indexeddb` makes more sense, because also the code architecture and readability is much better than in the other ones.

I will just experiment with it a 'new' leveldb adapter a little bit. Let's see if I can implement attachments in the fs and `native pouchdb-find` support.

**Comment by daleharvey** [comment]
> Yeah. I understand that, but i do not understand where this new native pouchdb-find feature is implemented? 

It isnt implemented at all, https://github.com/pouchdb/pouchdb/issues/6543 is the open issue about implementing it. And it wont use query / viewCleanup or pouchdb-abstract-maprduce in anyway, it will just export `.find`

**Comment by clooudch** [comment]
> It isnt implemented at all, #6543 is the open issue about implementing it. And it wont use query / viewCleanup or pouchdb-abstract-maprduce in anyway, it will just export .find

Ohh, sorry. It sounded like it was already implemented. What is blocking you right now (despite of not having enought time)?

Okay, I think I understand now. So you want to go around using `pouchdb-find` at all? So `.find` would then be a adatper api and not part of a plugin? 

I am not quite sure how indexes are implemented in pouchdb/couchdb. But i think they are strongly bound to the `_design/*` documents in the document store, aren't they? So do you wanna build your own indexing system or do you wanna just implement the the `_design/*` documents natively in the adapter (for better performance)? Would the `_design/*` documents somehow be coupled to the native indexing system or do you want to create your own indexing system without using `_design/*` documents at all?

**Comment by daleharvey** [comment]
> (despite of not having enought time)?
Not having enough time :)

> Okay, I think I understand now. So you want to go around using 
> pouchdb-find at all? So .find would then be a adatper api and not part of a plugin?
Yup exactly

> I am not quite sure how indexes are implemented in pouchdb/couchdb. 
> But i think they are strongly bound to the _design/* documents in the 
> document store, aren't they?

The design documents are part of the map reduce api, they are used under the hood for pouchdb-find currently but pouchdb-find doesnt expose them and have `createIndex` in which the user doesnt know anything about `design/` (can see them in action at https://nolanlawson.github.io/pouchdb-find/), plan is to not use design document under the hood and use the native indexing from the datastore we are using (level / index) and keep the pouchdb-find api the same / close as possible

**Comment by clooudch** [comment]
> The design documents are part of the map reduce api, they are used under the hood for pouchdb-find currently but pouchdb-find doesnt expose them and have createIndex in which the user doesnt know anything about design/ (can see them in action at https://nolanlawson.github.io/pouchdb-find/)

I know that, the user does not see that when he is purely using the pouchdb api, but `_design/*` documents also get replicated and are part of the couchdb "spec". Isn't the main goal of pouchdb to bring couchdb to the browser and doesnt creating a completly decoupled indexing system (based upon native indexes) break the semantics of couchdb which uses `_design/*` documents for index/creation/query.

I not sure how pouchdb-abstract-mapreduce works. Where is the index currently stored? It doesnt all happen in memory, does it? It looks like it creates for each view a completly separate pouchdb instance with `Adaper.prototype.registerDependentDatabase()`.

I am not sure how leveldb works but i think you have to create for each index a separate store, which would (for leveldb at least) not be a huge performance improvement (despite of all the abstractions by `pouchdb-find`/`pouchdb-abstract-mapreduce` and the overhead of a completly separate pouchdb instance that will get removed).

**Comment by daleharvey** [comment]
> doesnt creating a completly decoupled indexing system

CouchDB supports `find` (http://docs.couchdb.org/en/2.1.1/api/database/find.html) which does not require design documents for indexing, design documents are used for map reduce which we will still support as a plugin, but its not a very good api so it wont be our default.

We will maintain compatibility since we both support find, however pouchdb does not implement every part of couchdb, quite a lot of it doesnt make sense in a different context and some of it just isnt a good idea to copy, we mostly make sure for compatibility in the core api and replication.

> Where is the index currently stored?

As you found, they are stored as seperate databases preceeded with `mrview_`

> I am not sure how leveldb works but i think you have to create for each index a separate store. 

Neither am I, although we dont need to be restricted to leveldb if it doesnt support what we need

**Comment by clooudch** [comment]
Thank you very much for your attention and your help. It‘s very appreciated.

I am sorry, but i am new to pouchdb/couchdb, thank you for clearifying my missunderstanding about the _find api. I will have to get a better understanding for pouchdb (couchdb), so i will probably read through the whole codebase.

I am very interested in creating a new adapter for pouchdb for my own needs. PouchDB is great, but i a think there is currently no high performance node.js adapter for large databases with lots of attachments. I am gonna work towards such an adapter as i need this for my own project. But of course i will publish it if it‘s actually useful for others as well.

My current plan is to use either leveldb or nedb for storing documents. I am probably going for nedb as it supports indexing and is very fast because it works with append only files and compaction does not seem to be an issue since it can be easily integrated into pouchdb which also needs compaction. For the attachments i will use the native fs-module since it is more flexibel and probably performs better as well.

I will keep you informed about my progress. You will hear of me again. I will close this issue now, since my original question got answered.

Thank you.
