### ISSUE TITLE
DB goes bad from time to time. How to avoid or restore it?

### ISSUE THREAD

**Issue by group131** [pouchdb/pouchdb#7153]
### Issue
Hello again. I have a small web application (just html and javascript), which makes use of 3 pouchDB instances to store json documents locally and from time to time replicate some of them to a CouchDB server. Works like a charm (most of the times). From time to time, something goes wrong and I get weird messages in console such as:

> Database has a global failure DOMException: Failed to read large IndexedDB value

> Uncaught (in promise) CustomPouchError {status: 500, name: "indexed_db_went_bad", message: "unknown", error: true, reason: "DataError"}

> pouchdb-6.4.3.min.js:7 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

I tried to search for a solution on how to either avoid this condition or fix broken db. Came up with an interesting link [https://forum.webscraper.io/t/after-dec-21-update-all-sitemaps-disappeared/56]( https://forum.webscraper.io/t/after-dec-21-update-all-sitemaps-disappeared/56), which seems quite similar. Followed directions and tried to use a script that uses native database client instead of pouchdb wrapper to access my broken indexedDB. This led me to find out that my broken indexedDB does not have any values in 'by-sequence' table (whereas my other 2 'good' indexedDBs have values there).

Obviously, if I delete and recreate my broken pouchDB, it works again, but I have lost my saved data...

So, any ideas?

### Info
- Environment: browser (pouchDB version 6.4.3)
- Platform: Chrome
- Adapter: IndexedDB (Default)
- Server: CouchDB

### Reproduce
Unfortunately, this issue comes up from time to time, thus I do not have a specific use case.

**Comment by group131** [comment]
Attaching relevant screenshots:
![image](https://user-images.githubusercontent.com/1705358/37338963-b328044e-26c1-11e8-8b37-9483af24101c.png)
![image](https://user-images.githubusercontent.com/1705358/37339004-d2327bf8-26c1-11e8-834c-37ff52f2149a.png)
![image](https://user-images.githubusercontent.com/1705358/37339020-e34da886-26c1-11e8-87e0-ee0a5182457a.png)

**Comment by group131** [comment]
Update: Exceptions are thrown whenever I try to fetch all docs from broken db using:
`db.allDocs({
  include_docs: true,
          descending: false...` 

If I try using: 
`db.allDocs({
  include_docs: false,
          descending: false...` 

It works, but of course I do not get the actual docs...

**Comment by daleharvey** [comment]
This us super strange, it seems only the browser could be doing this, if you could find any consistent way to reproduce it then I can debug, but I couldnt even guess why that would happen without it

**Comment by group131** [comment]
Thanks dale. I looked into it a bit more. My broken pouchDB has 5 files. If I try to get them one by one, I manage to isolate the problem to just one file. Tried to delete it, but to no avail. Is there a way to delete it from the Chrome inspector to see if this restores the DB?

**Comment by daleharvey** [comment]
So I know under the hood chrome uses leve, but thats about as much as I know and that there isnt any official support for swapping out underlying files, it usually breaks stuff, gonna dupe this to https://github.com/pouchdb/pouchdb/issues/7098 as its the same issue people are seeing, like to get all the info in one place
