### ISSUE TITLE
Cannot import the pouchdb-browser in a Stencil App

### ISSUE THREAD

**Issue by jepiqueau** [pouchdb/pouchdb#7154]
### Issue
Due to the use of debug, we cannot import pouchdb-browser. in fact a build time it always load the node.js implementation and then failed  at runtime with 
Uncaught (in promise) TypeError: Cannot read property 'fd' of undefined
Can we have a lighter browser release without the debug module and having a uuid module working for browser as crypto is a nodejs feature

### Info
- Environment: (server Node.js and CouchDB client Ionic PWA Application)
- Platform: (Chrome/iOS/Android/etc.)
- Adapter: (IndexedDB.)
- Server: (localhost)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by daleharvey** [comment]
So we actually already removed the debug dependency, however it sounds like your import is wrong, pouchdb-browser (and pouchdb) work in the browser, we use browserify to switch between node and browser api usage and it sounds like however you are set up makes it think its node when it isnt

**Comment by daleharvey** [comment]
http://cdn.jsdelivr.net/npm/pouchdb@6.4.3/dist/pouchdb.js no usage of fd, crypto or any other nodejs only api in there

**Comment by daleharvey** [comment]
Closing, sounds like an import issue, if there is anything we can do to help import then post, but nothing mentioned so far

**Comment by jepiqueau** [comment]
hi, i am working on a Stencil PWA CouchDB/PouchDB app starter sees https://github.com/jepiqueau/stencil-pwa-couchdb-pouchdb-app-starter.git
i am using  in the index.html of the application this 
<script src="//cdn.jsdelivr.net/npm/pouchdb@6.4.3/dist/pouchdb.min.js"></script> 
this make the application works fine
but when i remove this line and try to import in the app-pouchdb component 
import PouchDB from 'pouchdb-browser'; // doesn't work problem with debug not selecting browser and crypto in uuid
and comment the following declare var PouchDB; i got the issue
so can you tell me how i should import it
many thanks
