### ISSUE TITLE
What is mrview?

### ISSUE THREAD

**Issue by dogenius01** [pouchdb/pouchdb#7158]
### Issue

Hi, I'm testing PouchDB for my app's local imdb.
and have question. 
when i load my node app with pouchdb, some folders are made.

dbname/
dbname-mrview-89cb6a6a79aacb71378762e9aab6e31b/

I want to know what is this for.

### Info
- Environment: Node.js
- Platform: 
- Adapter: 
- Server:

**Comment by group131** [comment]
I think mrview labeled DBs are created to store any index you have defined... Quoting from documentation:

> For the database geeks: implementation details If you want to know how map/reduce works in PouchDB, it's actually exceedingly easy: just open up your browser's developer tools, head over to "Resources," and see where we've created a bonus database to store the index.

**Comment by daleharvey** [comment]
Yup, it stores the result of the map function

**Comment by dogenius01** [comment]
Thank you guys!

**Comment by jsgv** [comment]
Should they be deleted as well when issuing `db.destroy()` ? 
What is the proper way to remove the `mrview` database?

**Comment by garrensmith** [comment]
It should be removed when you delete your database


________________________________
