### ISSUE TITLE
Unable to create index of 157187 documents

### ISSUE THREAD

**Issue by Tkd-Alex** [pouchdb/pouchdb#7169]
### Issue
Hi! I have a mobile application build with _Ionic-Cordova_. I've set-up PouchDB as well. My application replicate from a CouchDB and I've no problem to create index with **pouchdb.createIndex()** and **pouchdb.query()** (using map function). Lately I found myself working with db bigger and bigger. For example at the moment I've a CouchDB with over 150k of documents. I speed up replication of database using filter and increase the batchsize  (saving about 4 hours), but when i start indexing the application was die after 6 hours without positive result. I've try to createIndex only for one find, it's end after 1h but the find() function doesn't return anything. With smallest database my application works perfectly anyone have idea how to optimize this? 

I've also think to split CouchDB in a smallest PouchDBs for speed-up indexing but the replication becomes too slower because to split the db i scanning every 150k documents per x smallest db.

**Comment by garrensmith** [comment]
At the moment, pouchdb-find can be really slow with large databases because it doesn't save the index between queries. So it recreates it each time. Try using find without an index on pouchdb, you should get better results.

**Comment by Tkd-Alex** [comment]
There is no solution with using map query function? 
```
"article_code_list": {
	"map": "function(doc) { 
		if (!doc._deleted && doc.type == 'articolo') 
			for (var i in doc.dettagli) 
				for (var x in doc.prezzi) 
					emit([ parseFloat(doc.codice).toString(), doc.prezzi[x].listino_id], { custom_object }); 
	}"
},
```
This is an example of my function.

**Comment by daleharvey** [comment]
@garrensmith I thought via abstract map reduce pouchdb-find would persist the index (as a view)?

@Tkd-Alex Are there any errors thrown? even without splitting up the databases it may be an idea to split up the processing, do 50k changes, build the index, do the next 50k see if you can get it working that way, if you could get a working example showing the problem (https://pouchdb-bug-helper.glitch.me/ is handy for that) would help a lot

**Comment by Tkd-Alex** [comment]
> even without splitting up the databases it may be an idea to split up the processing, do 50k changes, build the index, do the next 50k 

@daleharvey Ok, ty! You suggest to create index every on('change') emitter of replication?
Something like this:
```javascript
var rep = PouchDB.replicate('mydb', 'http://localhost:5984/mydb', {
	retry: true,
	batch_size: 50000,
  	batches_limit: 5000,
	filter: '_view',
     view: 'myfilter/replication'
}).on('change', function (info) {
	db.createIndex({
		index: {
			fields: ['foo']
		}
	}).then(function (result) {
		// handle result
	}).catch(function (err) {
		console.log(err);
	});
}).on('complete', function (info) {
	// handle complete
}).on('error', function (err) {
	// handle error
});
```
Or it's possible to pause replication every 50k, start index and retry replication?

**Comment by daleharvey** [comment]
Definitely not every change, but maybe every 10k or such, and yeh if you count the changes and cancel it every X, query the index then start again should be good.

So I am not 100% familiar with find, but making an assumption that you only need to `createIndex` once and every while you should query that index as its actually the query that does the index building, looking back at your question its quite likely that your query is running fine, its just taking far longer than expected because the first time you do the query its building the full index (subsequent queries should be faster). Making some assumptions about pouchdb-find but those are definitely true for map/reduce

**Comment by garrensmith** [comment]
I’ve actually forgotten if we persist the index, I some how think we don’t. I need to look again. Could you try querying without createIndex and see how that goes?

**Comment by Tkd-Alex** [comment]
@daleharvey your idea is awesome! :bomb:
In more or less 3 hours I've replicate and init index for 90k documents. Every 3500 docs i do a query with limit:1 for start and save index, then re-start replication.
But i can't complete the replication beacause he exceeds 91/92k the application freeze. Only output in console from **pouchdb.debug** is the following. I thinks this is a problem with my database and some document. But anyone have idea? Maybe is the SyntaxError?
```
[.......]
pouchdb:api http://127.0.0.1:5984/ross +6ms get error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at onSuccess (index-browser.es.js:8454)
    at index-browser.es.js:8514
    at XMLHttpRequest.xhr.onreadystatechange (index-browser.es.js:8381)
    at XMLHttpRequest.W (polyfills.js:3)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.es5.js:3881)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
browser.js:123 pouchdb:api http://127.0.0.1:5984/ross +6ms get error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at onSuccess (index-browser.es.js:8454)
    at index-browser.es.js:8514
    at XMLHttpRequest.xhr.onreadystatechange (index-browser.es.js:8381)
    at XMLHttpRequest.W (polyfills.js:3)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.es5.js:3881)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
browser.js:123 pouchdb:api http://127.0.0.1:5984/ross +9ms get error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at onSuccess (index-browser.es.js:8454)
    at index-browser.es.js:8514
    at XMLHttpRequest.xhr.onreadystatechange (index-browser.es.js:8381)
    at XMLHttpRequest.W (polyfills.js:3)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.es5.js:3881)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
browser.js:123 pouchdb:api http://127.0.0.1:5984/ross +55ms get success (43) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
browser.js:123 pouchdb:api http://127.0.0.1:5984/ross +5ms get success (43) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
browser.js:123 pouchdb:http GET +48ms http://127.0.0.1:5984/ross/_changes?style=all_docs&filter=_view&view=mobile%2Freplication&since=98031&limit=3500
browser.js:123 pouchdb:http GET +1ms http://127.0.0.1:5984/ross/_changes?style=all_docs&filter=_view&view=mobile%2Freplication&since=98031&limit=3500
browser.js:123 pouchdb:api http://127.0.0.1:5984/ross +9ms get error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at onSuccess (index-browser.es.js:8454)
    at index-browser.es.js:8514
    at XMLHttpRequest.xhr.onreadystatechange (index-browser.es.js:8381)
    at XMLHttpRequest.W (polyfills.js:3)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.es5.js:3881)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
browser.js:123 pouchdb:api http://127.0.0.1:5984/ross +7ms get error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at onSuccess (index-browser.es.js:8454)
    at index-browser.es.js:8514
    at XMLHttpRequest.xhr.onreadystatechange (index-browser.es.js:8381)
    at XMLHttpRequest.W (polyfills.js:3)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.es5.js:3881)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
```
![image](https://user-images.githubusercontent.com/14061593/37849095-b081eff8-2ed6-11e8-8a1c-3be83144c1fd.png)
