### ISSUE TITLE
How to manage npm permissions better

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#7177]
When we add a new maintainer on github we just add them as an owner, on npm we have to individually add them to each module some of which only have one owner

Lets figure out a better way to do this

**Comment by daleharvey** [comment]
Partially in reference to https://github.com/pouchdb-community/pouchdb-adapter-cordova-sqlite/issues/86, which I dont have permissions to publish either

**Comment by daleharvey** [comment]
@gr2m @janl This a problem any of yall have had to solve?

**Comment by gr2m** [comment]
I just use semantic-release and usually a separate bot account on npm for that package only. Semantic-release wouldn’t work with PouchDB out of the box because of its monorepo setup, but I think it’s modular enough now to make it work, because PouchDB’s setup is comparably simple.
