### ISSUE TITLE
Query not working correctly after modifying doc

### ISSUE THREAD

**Issue by joshdhenry** [pouchdb/pouchdb#7188]
### Issue
I create a database, add records to it, perform a Mango query (search for docs with a specific event ID), and the query works as expected. I then modify one record, perform the same query as before, and the results are not correct. It seems to just return the document I just modified, but none of the other documents that should be returned.  If I print all docs afterwards, it shows all the documents as they should be including the new modification.

Can anyone figure out why my queries stop working correctly after modifying a doc?

### Info
- Environment: React Native v0.46.2
- Platform: iOS
- Adapter: Happens with default asyncStorage and with sqlite plugin.
- Server: Running database locally on device

### Reproduce
I've created the sample data code below to demonstrate the issue. I do the following actions in this order: 

1. Create index 
2. index db with blank query
3. add bulkdocs to db
4. perform query
5. modify doc
6. perform query again.

`testFunction() {
        //Dummy data
        let mockData = 
            [{
                    '_id': '1',
                    'event_id': '136471',
                },
                {
                    '_id': '2',
                    'event_id': '136471',
                },
                {
                    '_id': '3',
                    'event_id': '136471',
                },
                {
                    '_id': '4',
                    'event_id': '136472',
                }];

        //Create DB
        console.log('**********TESTING************');

        this.testDB = new PouchDB('DBTest');

        let thisTestDB = this.testDB;

        this.testDB.createIndex({
            index: {
                fields: ['event_id'],
                ddoc: 'testTicketsDesignDoc',
            },
        })
        .then(
            (result) => {
                console.log('Indexing for Mango complete');

                //Index mango with initial blank query
                thisTestDB.find({
                    selector: {},
                    use_index: 'testTicketsDesignDoc',
                    limit: 0,
                })
                .then(
                    (result) => {
                        console.log('Indexing with blank Mango query complete');

                        //Add docs to database
                        thisTestDB.bulkDocs(mockData)
                        .then(
                            (result) => {
                                console.log('Bulkdocs successfully added to database.');

                                //Perform 1st query before modifying docs
                                thisTestDB.find({
                                    selector: {
                                        'event_id': '136471',
                                    },
                                    use_index: 'testTicketsDesignDoc',
                                })
                                .then(
                                    (searchResult) => {
                                        console.log('1st Mango query complete');
                                        console.log(searchResult);

                                        //Now modify a doc
                                        thisTestDB.get('1')
                                        .then(
                                            (doc) => {
                                                //Make any modifications to doc here

                                                thisTestDB.put(doc)
                                                .then (
                                                    (putResult) => {
                                                        console.log(`Modifying doc successful: ${JSON.stringify(putResult)}`);

                                                        //Perform second query after modifying docs
                                                        thisTestDB.find({
                                                            selector: {
                                                                'event_id': '136471',
                                                            },
                                                            use_index: 'testTicketsDesignDoc',
                                                        })
                                                        .then(
                                                            (searchResult) => {
                                                                console.log('2nd Mango query complete');
                                                                console.log(searchResult);
                                                            }
                                                        );
                                                    }
                                                )
                                                .catch(
                                                    (error) => {
                                                        console.log(`Error modifying doc: ${error}`);
                                                    }
                                                );
                                            }
                                        )
                                        .catch(
                                            (error) => {
                                                console.log(`Error modifying doc: ${error}`);
                                            }
                                        );
                                    }
                                )
                                .catch(
                                    (error) => {
                                        console.log(`Error performing first query: ${error.message}`);
                                    }
                                );
                            }
                        )
                        .catch(
                            (error) => {
                                console.log(`Error adding bulk docs: ${error}`);
                            }
                        );
                    }
                )
                .catch(
                    (error) => {
                        console.log(`Error performing initial indexing query: ${error}`);
                    }
                );
            }
        )
        .catch(
            (err) => {
                console.log(`Error - ${JSON.stringify(err)}`);
            }
        );
    }`

**Comment by joshdhenry** [comment]
It looks like even if I define my selector to retrieve all documents, it still only returns the one that was last modified:

```
selector: {
   'event_id': {$gte: null},
}
```

**Comment by garrensmith** [comment]
Can you try without doing a createIndex

**Comment by joshdhenry** [comment]
It does indeed work without the index.  I'm not sure what this means though.  Am I creating the index wrong?

**Comment by garrensmith** [comment]
We need to improve the way PouchDB-find indexes docs. With idb next this should be better. If you don’t create an index it uses all docs.

**Comment by joshdhenry** [comment]
I've been experimenting further with this but still no luck.  

I've tried to delete the existing doc, compact the DB, then put a modified copy of the doc back in. But queries still don't return the correct result unless I disable the index.  We're going to be storing and querying 20k+ records so an index is much needed.  

Is idb-next an adapter?  Should I be trying out different adapters to rectify this problem, or is the adapter not relevant to this issue?  Know of any workarounds that might work? I'm running out of ideas but really need to get some kind of indexing going.

**Comment by warrenbell** [comment]
joshdhenry I never got this to work. I ended up using the package pouchdb-live-find which I believe is using pouchdb-find under the hood. So the pouchdb-live-find guys have gotten find() to work for them correctly. Plus pouchdb-live-find added some extra features I have found useful.

I stripped everything I could out of my code and just had a basic find() with a simple selector and index then a put() that just changed an extraneous existing field and then the same find() again. No luck.

I still would like to know what was wrong. I am sure I will need to use this type of code again somewhere.

**Comment by joshdhenry** [comment]
@warrenbell I tried using pouchdb-live-find with the same code but experienced the same issue.  Also tried creating a new blank project with just the code.  Are you using the same code, just with pouchdb-live-find implemented?  Or did you change something?

**Comment by warrenbell** [comment]
@joshdhenry I am using pouchdb-live-find with the aggregate setting set to true. The aggregate array, so far, has returned all of the correct docs. I also have live-find updating my Redux store. I have not poked around in the live-find code yet. The answer to the original issue may be in there somewhere. As far as the same code, I can't say for sure. I kind of just jumped ahead once I got live-find to do what I wanted. Live-find has reduced the amount of code I have needed to write.

**Comment by joshdhenry** [comment]
The pouchdb-live-find aggregate array is working for me when adding, updating, and deleting.  Still trying to figure out how to get that aggregate array when I just need to query and not make any modifications to docs.  Perhaps I will just make some kind of throwaway doc that I can update so I can get that aggregate array returned to me. This can act as my "query".  I'll experiment  some more and see what can be done because I absolutely need fast queries working for PouchDB.  Thanks for your help.

**Comment by warrenbell** [comment]
@joshdhenry The way I do it is with Redux. I guess it also depends on how much data you are talking about. I will make my create, update and deletes directly on PouchDB or via replicate/synch of my remote couchDB. This triggers live-find "on update" where I take the aggregate docs call a Redux action which sets the aggregate docs to the Redux store which updates my UI. Also when you set-up live-find initially, it returns the aggregate array even with out modifying PouchDB first. I use this array to initialize my Redux store. Seems to be working pretty nicely, but I am not dealing with large data sets. I know there will soon be a use case where find will make more sense. So I still would like to find an answer to this issue.

**Comment by daleharvey** [comment]
Yup a bunch of reports of this, dupping them to 1 bug @ https://github.com/pouchdb/pouchdb/issues/7293
