### ISSUE TITLE
db.find is much slower when using index

### ISSUE THREAD

**Issue by z543** [pouchdb/pouchdb#7189]
### Issue
db.find is much slower when using index

### Info
- Environment: browser
- Platform: Chrome 67.0.3371.0 (Official Build) dev (64-bit)
- Adapter: IndexedDB
- Server: n/a

### Reproduce
demo: https://codesandbox.io/s/81w1378l72
see the output of console

**Comment by z543** [comment]
just one call, 
but planning query 1000 items using 399ms is very very slow 
in in-memory db

**Comment by daleharvey** [comment]
Yup, the way its currently set up means it does a lot of work to create the index, however it should be faster after the first call, and https://github.com/pouchdb/pouchdb/issues/6543 is work to speed it up in the end so closing out
