### ISSUE TITLE
'express-pouchdb' with IndexedDB ?

### ISSUE THREAD

**Issue by ozgursel** [pouchdb/pouchdb#7191]
### Issue
Hi, i want to know, is there any way to use 'express-pouchdb' with IndexedDB ?
When i use adapter as 'idb' in Main process of Electron i'm getting this error below.

`A JavaScript error occurred in the main process
Uncaught Exception:
Error: Invalid Adapter: idb`

### Info
- Environment: (Node.js/Electron)
- Platform: (Chrome)
- Adapter: (IndexedDB)
- Server: (CouchDB)

**Comment by daleharvey** [comment]
Looks like the same issue as https://github.com/pouchdb/pouchdb/issues/7197#issuecomment-376922736
