### ISSUE TITLE
Unable to successfully send a request from karma / jasmine integration test.

### ISSUE THREAD

**Issue by jkndrkn** [pouchdb/pouchdb#7196]
### Issue
When using karma / jasmine, requests from PouchDB are appearing as OPTIONS HTTP requests instead of as the expected GET HTTP requests. My understanding is that a CORS issue may be involved.

I am using karma / jasmine to create integration tests for my system. I have followed discussion [here](https://github.com/pouchdb/pouchdb/issues/4657) for how to get promises to fire correctly when using PouchDB within karma / jasmine. Promises *do* appear to be firing. I have also run `add-cors-to-pouchdb` and this has not helped.

### Info
- Environment: Mac OS X 10.13.3, node 9.9.0, pouchdb 6.3.4
- Platform: phantomjs
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: CouchDB 2.0.0

### Reproduce
My local webserver is running on http://localhost:8080/ and my CouchDB instance is accessible via http://localhost:8080/db/ to prevent CORS issues within my web-app.

The CouchDB instance is also running at http://localhost:5984/

### Details

Here is a request from my broken karma / jasmine setup:

Mar 26 18:40:38 localhost docker: [notice] 2018-03-26T18:40:38.800522Z nonode@nohost <0.2259.130> 18ed4899e3 127.0.0.1:5984 172.17.0.1 e2e%40example.com OPTIONS /q-21test/_design/dgf/_view/surgery_case_by_dtstart?include_docs=true&startkey=%222018-04-08T00%3A00%3A00-04%3A00T00%3A00%3A00.000Z%22&endkey=%222018-02-25T00%3A00%3A00-05%3A00T00%3A00%3A00.000Z%22&_nonce=1522089638846 405 ok 4

And an equivalent request from my web app:

Mar 26 18:41:07 localhost docker: [notice] 2018-03-26T18:41:07.740658Z nonode@nohost <0.3328.130> d1fefff6ad 127.0.0.1:5984 172.17.0.1 rep1%40example.com GET /q-21test/_design/dgf/_view/surgery_case_by_dtstart?include_docs=true&startkey=%222018-02-25T00%3A00%3A00.000Z%22&endkey=%222018-04-08T00%3A00%3A00.000Z%22 200 ok 9

As you can see, the karma request has an OPTIONS header and a 405 response code.

**Comment by janl** [comment]
can you share `http://localhost:5984/_config` (or `http://localhost:5984/_node/_local/_config` if you are on 2.x)?

**Comment by jkndrkn** [comment]
Hi @janl! Here is my config. I am running on a single-node CouchDB instance used for development purposes.

https://gist.github.com/jkndrkn/096e5e7b855d13ecb88569e24df26212

**Comment by daleharvey** [comment]
Your requests are going to 127.0.0.1:5984, not localhost:8080/db/ so they arent avoiding cors checks, as for the failing cors check (and that is only happens in jasmine) I would check the couchdb log, set logging to verbose, try to recreate the request with curl and see whats up, it may be a non default header jasmine sends

**Comment by jkndrkn** [comment]
> Your requests are going to 127.0.0.1:5984, not localhost:8080/db/ so they arent avoiding cors checks

I should mention that my webserver and CouchDB server are hosted within vagrant using nginx. A request to localhost:8080/db/ gets forwarded to 127.0.0.1:5984.

Thanks, I will try verbose logging and recreating the request using curl.

**Comment by daleharvey** [comment]
> localhost:8080/db/ gets forwarded to 127.0.0.1:5984

That wont avoid CORS, and may even complicate the issue, you should probably either change it to a proxy instead of a redirect, or just talk directly to couch without the redirect

**Comment by jkndrkn** [comment]
I double-checked the nginx config and a proxy *is* in use. Will try to talk directly to couch without going through the nginx proxy.

**Comment by jkndrkn** [comment]
@daleharvey 

Per your suggestion I bypassed my nginx proxy and connected from Jasmine directly to localhost:5984. I continue to see the OPTIONS method and 405 status code in CouchDB logs.

I also increased the verbosity of CouchDB logging to `debug` but my logs are not showing me the HTTP headers.

**Comment by jkndrkn** [comment]
According to +rnewson the #couchdb IRC channel setting logging to `debug` does not log HTTP headers. This contradicts what is in the official docs (http://docs.couchdb.org/en/2.0.0/config/logging.html).

@daleharvey, what configuration options did you use to log HTTP headers?

**Comment by daleharvey** [comment]
PouchDB does not make OPTIONS requests, your browser does and CouchDB can accept OPTIONS requests, its error is confusing

Your first snippets seem to be GET requests from `http://localhost:8080/testing/app/` to `http://localhost:8080//db/q-21test/_de....` which is not going to trigger CORS checks, your karma setup is completely different making requests from `http://localhost:9876` to `localhost:5984` which will trigger CORS checks

The `x-pouchdb` in `Access-Control-Request-Headers: accept, x-pouchdb, origin.` looks suspect, as I mentioned earlier I think its a header karma / jasmine or whatever part of your test setup is adding, I would add `x-pouchdb` to your cors.headers in https://gist.github.com/jkndrkn/096e5e7b855d13ecb88569e24df26212 and see if stuff works, if not as said recreate the failure in curl, the issue is nothing to do with pouchdb, its between how your browser and couchdb are configured, reading up on CORS will also help debug https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
