### ISSUE TITLE
iOS11 idb adapter not available (indexeddb)

### ISSUE THREAD

**Issue by silverbackdan** [pouchdb/pouchdb#7197]
### Issue
I can't set the adapter to idb as the error I get is 'Invalid Adapter: idb' I've tried finding an existing issue that's current related to this but couldn't see anything open.

### Info
- Environment: Ionic/Cordova (edited)
- Platform: iOS11
- Adapter: IndexedDB
- Server: CouchDB (but not relevant)

### Reproduce
Before I write a reproduction, I'm just wondering if this is known? I am also running my app in a debug build with a live reload feature on. I don't know if that'd change how the app runs and means IndexedDB isn't available - but in the Safari console when debugging the app I can see the IndexedDB does exist.

**Comment by akowald** [comment]
Yeah, it's been broken for months: https://github.com/pouchdb/pouchdb/issues/7057 :(

**Comment by daleharvey** [comment]
It isnt a known issue not has it been broken for months, https://github.com/pouchdb/pouchdb/issues/7057 is a completely different issue

@silverbackdan It means the function @ https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-idb/src/index.js#L796 failed, we have simplified this a lot recently, could you check against the latest nightly and see if you still have the same problem?

**Comment by silverbackdan** [comment]
Ah, I have a feeling that in ionic it may need to check if IndexDB exists on the window variable. Thanks for showing the function, I'll do some tests now and see what's going on :) Thanks!

**Comment by silverbackdan** [comment]
Sorry to be stupid but how can I install the latest commit for the idb adapter - it doesn't look like I can specify this in my package.json. Still trying to work it out and I'll update here if I manage to before I get a reply.

The function in the previous release 2 months ago is of course very different.

Do I still need to install the idb adapter deparately?

**Comment by silverbackdan** [comment]
The new function works perfectly. I just updated in my local node_modules in the end just to see.

I did then get 'An unknown error occurred within IndexedDB' error, but this would be a separate issue and until I can use the very latest code there's probably not much point in mentioning any other issues that may arise.

Are there any docs on using the latest development builds instead of releases?

**Comment by silverbackdan** [comment]
OK, the error I've come across is now what is in https://github.com/pouchdb/pouchdb/issues/7057 - I'll close this issue and perhaps await a comment if anyone gets a moment to help with installing unreleased versions.

**Comment by daleharvey** [comment]
So yeh I imagine github urls are out the question, doesnt seem like they work with a build system? (not entirely sure here) so looks like you would have to do a local build and create a release tarball @ https://docs.npmjs.com/files/package.json#urls-as-dependencies

Not sure if the build system or the monorepo is the problem here, es6 modules in node may improve things, been meaning to look into the build system soon, sorry couldnt be more help, building a .js has been serving me ok up till now

**Comment by silverbackdan** [comment]
@daleharvey Thanks very much for the help. It is annoying that npm won't support sub directories, but yarn looks like it may do in the future as the issue there isn't closed...yet.

It's the package manager system :) Monorepos are everywhere, it's ridiculous IMO that the maintainers don't consider it a worthy new feature that should be address.

I've had a look and can see the build commands in the package.json so I will clone the repo and work with that creating builds as you've said if I need to work with the latest release.

Thanks again.
