### ISSUE TITLE
4.8mb database grows to 647mb after compact() call on iOS

### ISSUE THREAD

**Issue by webnoob** [pouchdb/pouchdb#7201]
### Issue
I've got a 4.8mb database in couchDB that when sync'd with pouch and compact called, it grows to 647mb when on iOS. When on PC and we log in, it's 8.4mb.

Any ideas what could be causing this?

### Info
- Environment: Cordova App
- Platform: iOS application
- Adapter: IndexedDB (I assume)
- Server: CouchDB

**Comment by daleharvey** [comment]
Thats large, and shouldnt happen, unlike couchdb we dont copy into a new file for compaction, compaction is just straight deletes, would definitely look into the inspector to figure out why, how are you measuring size?
