### ISSUE TITLE
Database 'created' event not fired across multiple tabs

### ISSUE THREAD

**Issue by xMartin** [pouchdb/pouchdb#7203]
I set up an event handler like that:
```javascript
PouchDB.on('created', function (dbName) {
  console.log(dbName, 'created');
});
```
Works fine in one browser tab. When I create a new database (`new PouchDB('name');`) the event is fired and the message logged. But opening the same app in a separate browser tab/window doesn't fire there, too. Nothing is logged although the database got created.

Is this supposed to work?

- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB

**Comment by daleharvey** [comment]
It was never really made / planned to, it gets confusing particularly when referring to node support. The `on('created` was a bit of a hack to support `all_dbs` in PouchDB server and not entirely sure we wouldnt be better moving it out of core and into a plugin, its some of the most complicated code in pouchdb, having it not work across tabs isnt ideal but supporting cross tab notifications is going to be a fair bit of more complicated code thats still likely to not work completely (web/service workers?)

**Comment by xMartin** [comment]
I see. Thanks a lot for the explanation!

I think it would make sense to remove it, then.

I am using the allDbs plugin in the browser but I had to add a `noCache` option so I am able to poll for new/deleted dbs across tabs.
