### ISSUE TITLE
PouchDB requires multiple indexes to be able to order by a property

### ISSUE THREAD

**Issue by lukechilds** [pouchdb/pouchdb#7205]
### Issue
I'm not sure if this is expected behaviour or a bug. But if you have three fields, `date`, `foo`, `bar`. You need to have two separate indexes, one for `date`+`foo` and one for `date`+`bar`.

I expected to be able to have a single index on `date`+`foo`+`bar` but this results in `Error: Cannot sort on field(s) "date" when using the default index` when querying `bar` but works ok for `foo`

### Info
- Environment: Browser
- Platform: Chrome
- Adapter: IndexedDB
- Plugin: PouchDB Find

### Reproduce

Fails with a single index on `['date', 'foo', 'bar']`:

```js
const db = new PouchDB('singleindex', {adapter: 'idb'});

await db.createIndex({index: {fields: ['date', 'foo', 'bar']}});

await db.post({date: Date.now(), foo: 1, bar: 1});
await db.post({date: Date.now(), foo: 2, bar: 2});

await db.find({
	selector: {
		foo: 1,
		date: {$gt: true},
	},
	sort: [{date: 'desc'}],
});
// => Success

await db.find({
	selector: {
		bar: 1,
		date: {$gt: true},
	},
	sort: [{date: 'desc'}],
});
// => Error: Cannot sort on field(s) "date" when using the default index
```

Works with two indexes on `['date', 'foo']` and `['date', 'bar']`:

```js
const db = new PouchDB('doubleindex', {adapter: 'idb'});

await db.createIndex({index: {fields: ['date', 'foo']}});
await db.createIndex({index: {fields: ['date', 'bar']}});

await db.post({date: Date.now(), foo: 1, bar: 1});
await db.post({date: Date.now(), foo: 2, bar: 2});

await db.find({
	selector: {
		foo: 1,
		date: {$gt: true},
	},
	sort: [{date: 'desc'}],
});
// => Success

await db.find({
	selector: {
		bar: 1,
		date: {$gt: true},
	},
	sort: [{date: 'desc'}],
});
// => Success
```

**Comment by erik127** [comment]
Have you tried the following:
```
db.find({
  selector: {
    foo: {$gte: null},
    bar: 1,
    date: {$gt: true},
  },
  sort: [{date: 'desc'}],
})
```
I think I read somewhere recently that the fields in the selector need to match the ones in the selector. Can't remember where I read that though.

**Comment by duytq94** [comment]
> Have you tried the following:
> 
> ```
> db.find({
>   selector: {
>     foo: {$gte: null},
>     bar: 1,
>     date: {$gt: true},
>   },
>   sort: [{date: 'desc'}],
> })
> ```
> 
> I think I read somewhere recently that the fields in the selector need to match the ones in the selector. Can't remember where I read that though.

I tested, it's not working, still throw error `Error: Cannot sort on field(s) "date" when using the default index`

**Comment by sis-dk** [comment]
Did you find any fix?
