### ISSUE TITLE
Sorting fails if the property isn't the first item in the index array

### ISSUE THREAD

**Issue by lukechilds** [pouchdb/pouchdb#7207]
### Issue
To be able to sort by a property it needs to be the first item in the index. This isn't intuitive and isn't specified anywhere in [the docs](https://github.com/pouchdb/pouchdb/tree/master/packages/node_modules/pouchdb-find)

Not sure if this is an error in the docs or the code, but either way, it's quite confusing.

### Info
- Environment: Browser
- Platform: Chrome
- Adapter: IndexedDB
- Plugin: PouchDB Find

### Reproduce

This doesn't work because `'date'` isn't specified first in the array:

```js
const db = new PouchDB('test-index-order', {adapter: 'idb'});

await db.createIndex({index: {fields: ['id', 'date']}});

await db.post({id: 1, date: Date.now()});
await db.post({id: 2, date: Date.now()});

const result = await db.find({
	selector: {
		date: {$gt: true},
	},
	sort: [{date: 'asc'}],
});
// => Error: Cannot sort on field(s) "date" when using the default index
```

This works because `'date'` is the first item in the array:

```js
const db = new PouchDB('test-index-order', {adapter: 'idb'});

await db.createIndex({index: {fields: ['date', 'id']}});

await db.post({id: 1, date: Date.now()});
await db.post({id: 2, date: Date.now()});

const result = await db.find({
	selector: {
		date: {$gt: true},
	},
	sort: [{date: 'asc'}],
});
// => {docs: Array(2)}
```

**Comment by Megidd** [comment]
This is how CouchDB indexing of *array keys* or *compound keys* work. So, this is more of a CouchDB thing. Take a look at [this Couchbase explanation](https://blog.couchbase.com/understanding-grouplevel-view-queries-compound-keys/). I know it is a Couchbase explanation, but it applies to CouchDB too.

**Comment by daleharvey** [comment]
This is documented @ https://pouchdb.com/guides/mango-queries.html#more-than-one-field and @ http://docs.couchdb.org/en/2.1.1/api/database/find.html#sort-syntax

**Comment by badbod99** [comment]
This is now fixed on CouchDB 2.2.  See https://github.com/apache/couchdb/issues/1371.

The following now works on CouchDB 2.2/2.3:

Index as:
```
{
   "index": {
      "fields": [
         "type",
         "position.grade.abbr",
         "dateFrom"
      ]
   },
   "name": "grade-json-index",
   "type": "json"
}
```

Selector as:
```
{
   "selector": {
      "type": "job",
      "position.grade.abbr": "Con",
      "dateFrom": {
         "$gt": "2018-12-01",
         "$lt": "2019-01-30"
      }
   },
   "sort": [
      "dateFrom"
   ],
   "limit": 10000
}
```

Or even:

```
{
   "selector": {
      "type": "job",
      "position.grade.abbr": "Con"
   },
   "sort": [
      "dateFrom"
   ],
   "limit": 10000
}
```

**Comment by EtienneBourque** [comment]
From what I see, this is fixed in CouchDB but it's still a problem in PouchDB. We cannot sort by anything but the first item in the index.

**Comment by garrensmith** [comment]
This isn't true for CouchDB or PouchDB. The reason it works in CouchDB is because I added an optimisation here CouchDB https://github.com/apache/couchdb/commit/5b5c8a1dcb196eb461dcab17a52c3c27998c5372#diff-6bf254d8ea16ad041fc3213991692fa6R517
I left a comment in that commit to explain what we doing. 

In CouchDB and PouchDB you need to include all the fields in the index in the sort field. 
So for this to first initial error to work, you need to change it to:
```
await db.createIndex({index: {fields: ['id', 'date']}});

await db.post({id: 1, date: Date.now()});
await db.post({id: 2, date: Date.now()});

const result = await db.find({
	selector: {
		date: {$gt: true},
	},
	sort: [{id: 'asc'}, {date: 'asc'}],
});
```

The only difference with CouchDB is that it sees that the value of the first value in the index won't affect how things are sorted so it can ignore it. PouchDB doesn't have that optimisation.
