### ISSUE TITLE
Changes feed - add retry option

### ISSUE THREAD

**Issue by winuxue** [pouchdb/pouchdb#7209]
### Issue
It would be great to add retry option to changes, similar like replicate and sync methods.

### Info
- Environment: browser
- Platform: All browsers
- Adapter: HTTP
- Server: PouchDB, and any other I think.

### Reproduce
1. create an pouchdb using http adapter
2. add .changes code with live option
3. run app and pouchdb server
4. test if .changes is working (works)
5. stop pouchdb server for a pair of seconds
6. test if .changes is working (won't work)

### Workaround
I'm using as workaround womething like this:
```js
function feed(){
var changes = db.changes({since: "now", live: true,});
changes.on('error',function(){ feed() });
}

**Comment by jareware** [comment]
This has been answered before (#6151), and it's something you need to implement yourself, unfortunately.

**Comment by daleharvey** [comment]
Yeh, retry for replication is complicated enough without applying it to all http requests, a generic retry needs mechinisms, configuration, a new way to surface errors etc, for now best done above pouchdb (or via a pluggable fetch replacement that does them transparently)

**Comment by mikeymckay** [comment]
Here is what I ended up using. A standalone robust changes feed follower:
https://www.npmjs.com/package/follow
