### ISSUE TITLE
I'm trying to implement ionic app with pouchdb-list Plugin was installed successfully and paameters are passing to list method and  returns error promie.all() is not a function

### ISSUE THREAD

**Issue by isuruSameera** [pouchdb/pouchdb#7213]
### Issue
Write the description of the issue here

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by daleharvey** [comment]
Guessing you mean `Promise.all` not sure whats up with ionic, seems like it should have a standard promise implementation but maybe you need to polyfill Promise as pouchdb definitely expects it. If its an issue with pouchdb-list then that repo is @ https://github.com/pouchdb/pouchdb-list, certain not a core pouchdb issue
