### ISSUE TITLE
PouchDB Adapters, why?

### ISSUE THREAD

**Issue by fransyozef** [pouchdb/pouchdb#7214]
So I've been using PouchDB in my IONIC3 app and it rocks. I see PouchDB offers adapters for example sqllite. 

What would be the bennefit to use an extra adapter? Is it speed? Better storage?

### Issue
Write the description of the issue here

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by daleharvey** [comment]
Adapters are for supporting different platforms, some platforms dont support indexeddb / websql so someone wrote a sqlite adapter, memory adapter has been used for testing, occasionally they can offer benefits of no bypassing storage limits depending on the platform.

In general if the core adapters work and there isnt a compelling reason to switch, they are the best tested by far
