### ISSUE TITLE
find() only returns doc that changed after put().

### ISSUE THREAD

**Issue by warrenbell** [pouchdb/pouchdb#7219]
### Issue
This issue happens when I do a find() that returns the correct six docs. Then I do a put() on one of those docs that changes just one existing field in that one doc. The put() works correctly. Then I run the same find() above and I only get the one doc back that I changed instead of six docs with one of those docs changed. I want to think this is by design and I just don't understand how put() or find() works and there is some option I have to set to get all six docs back.

This issue originally surfaced for me when I set _deleted = true in the one doc I put(). I realized that it happens if I change any field.

I have the original post up at stackoverflow at:

[https://stackoverflow.com/questions/49719678/pouchdb-find-returns-empty-array-after-delete-1-of-6-objects-from-db](url)

Thanks

Warren Bell

### Info
- Environment: (React Native app)
- Platform: (React Native)
- Adapter: (AsynchStorage)
- Server: (PouchDB on iPhone 6 simulator via pouchdb-react-native)

**Comment by platov** [comment]
Please, provide code snippets of query selectors you do.

**Comment by warrenbell** [comment]
Here is the index:

db.createIndex({
  index: {
    fields: ['username', 'date'],
    ddoc: "usernameDateIndex"
  }
})

Here is the find with selector:

db.find({
   selector: {
     username: {$eq: 'org.couchdb.user:' + username},
        date: {$gte: null}
      },
      sort: [{username: 'desc'}, {date:'desc'}],
      use_index: 'usernameDateIndex'
    }).then(result => {
      // Before put() I get 6 docs. After put() of one doc I get only the doc that changed
    }).catch(error => {
    });


The put modifies one existing field named "note" in one doc. It does not modify any field used in the index.

**Comment by joshdhenry** [comment]
I'm experiencing this, too. #7188 Would love to know if you can get around it.

**Comment by warrenbell** [comment]
Here is another issue on stackoverflow which seems to be identical to this issue:

[https://stackoverflow.com/questions/49785164/pouchdb-find-query-stops-working-after-modifying-docs-when-using-an-index/49789266?noredirect=1#comment86612439_49789266](url)

**Comment by warrenbell** [comment]
Here is a code sample that reproduces this problem. I also tried this with a selector that only has one field with no sort and I still have the same issue. It also can be reproduced without the initial find(), just a put() and a find() within the put().then()

``` 
db.find({
    selector: {
    username: username,
    date: {$gte: null}
  },
  sort: [{username: 'desc'}, {date:'desc'}],
  use_index: 'usernameDateIndex'
}).then(result => {
  // Works fine. result has many docs and is what I expect
  someDocInResult.someExistingField = 'changed';
  db.put(someDocInResult)
  .then(result => {
    // db.allDocs(...) returns all the correct docs
    db.find({
      selector: {
        username: username,
        date: {$gte: null}
      },
      sort: [{username: 'desc'}, {date:'desc'}],
      use_index: 'usernameDateIndex'
    }).then(result => {
      // Does not work. result only has the one doc that I changed and not the others
    }).catch(error => {
    });
  }).catch(error => {
  })
}).catch(error => {
});
```

Here is my PouchDB package versions.

```
├─ pouchdb-abstract-mapreduce@6.4.3
├─ pouchdb-adapter-asyncstorage@6.4.1
├─ pouchdb-adapter-http@6.4.3
├─ pouchdb-adapter-utils@6.4.3
├─ pouchdb-ajax@6.4.3
├─ pouchdb-binary-utils@6.4.3
├─ pouchdb-changes-filter@6.4.3
├─ pouchdb-checkpointer@6.4.3
├─ pouchdb-collate@6.4.3
├─ pouchdb-collections@6.4.3
├─ pouchdb-core@6.4.3
├─ pouchdb-debug@6.4.3
├─ pouchdb-errors@6.4.3
├─ pouchdb-find@6.4.3
├─ pouchdb-generate-replication-id@6.4.3
├─ pouchdb-json@6.4.3
├─ pouchdb-mapreduce-utils@6.4.3
├─ pouchdb-mapreduce@6.4.3
├─ pouchdb-md5@6.4.3
├─ pouchdb-merge@6.4.3
├─ pouchdb-promise@6.4.3
├─ pouchdb-react-native@6.4.1
├─ pouchdb-replication@6.4.3
├─ pouchdb-selector-core@6.4.3
├─ pouchdb-utils@6.4.3
```

**Comment by daleharvey** [comment]
Yup a bunch of reports of this, dupping them to 1 bug @ #7293
