### ISSUE TITLE
String collation is not CouchDB compatible.

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#7224]
There was an issue for this in the past which I can't find and is referred to in the code. The string collation in PouchDB is not compatible with CouchDB.

Maybe we should at least document what this means in practice?

**Comment by platov** [comment]
May You provide more details about your issue ?

**Comment by ronag** [comment]
https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-collate/src/index.js#L276

**Comment by daleharvey** [comment]
Happy for a PR to update the docs to mention how our collation differs

**Comment by ronag** [comment]
> mention how our collation differs

I don't actually know how it differs. Only that it differs based on that comment :).

**Comment by daleharvey** [comment]
CouchDB uses the ICU library which tl;dr stores a bunch of data about characters in different languages so they can be compared / sorted propery

PouchDB just uses JavaScript comparison, so just sorts them in ascii order

**Comment by daleharvey** [comment]
Actually this is documented @ https://pouchdb.com/faq.html#couchdb_differences, so closing out
