### ISSUE TITLE
Database has a global failure DOMException: Failed to read large IndexedDB value

### ISSUE THREAD

**Issue by cbonnissent** [pouchdb/pouchdb#7228]
### Issue

Sometimes I have this message, I cannot access to the content of the base.

> index-browser.es.js:588 Database has a global failure DOMException: Failed to read large IndexedDB value
guardedConsole @ index-browser.es.js:588
req.onsuccess.idb.onabort @ index-browser.es.js:6395
14:55:27.390 

### Info
- Environment: Browser
- Platform: Chrome 65
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce

It seems it append after many replications (x100) of a base with frequent modifications with documents with attachments

**Comment by platov** [comment]
Please read this topic https://github.com/pouchdb/pouchdb/issues/7098

**Comment by cbonnissent** [comment]
Thank you, it's the same issue I have the auto_compaction activated.

I close this issue
