### ISSUE TITLE
Not an issue, but it would be usefull to be able to tweak the replication speed...

### ISSUE THREAD

**Issue by trollanfer** [pouchdb/pouchdb#7229]
Cloudant has limited free plans to 20 queries/second. Is there a way to slow down the replication to avoid 429 errors ?
I tried the live replication with retry option, but it doesn't help, since cloudant refuses to answer at this rate.

**Comment by jareware** [comment]
The live replication should back off incrementally until it CAN get another batch through.

Another thing you can try is to decrease the `batches_limit` and increase the `batch_size` option. If your documents are small it seems quite safe to replicate with e.g. `batch_size: 1000`, and if you're not in a rush, `batches_limit: 1` might get you under the Cloudant limits.

**Comment by daleharvey** [comment]
@rnewson Hey would be good to hear from cloudant about this, is this a strict limit thats going to stick around, are a lot of people not having issues with replication due to it?

**Comment by trollanfer** [comment]
cloudant has a limit for free plans of 20 queries/s.

I try to replicate my database only once (not using live option) (the
database is rarely updated).
What puzzles me is that replication of my "text" database works, but my
"images" database fails, due to this query limit...

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-05-30 20:20 GMT+02:00 Dale Harvey <notifications@github.com>:

**Comment by daleharvey** [comment]
hm, do attachments hinder our ability to use the bulk_get api? I know that we do attachment requests seperately although I would have thought they might take longer than 20 per second
