### ISSUE TITLE
Couldn't find the requested release version 6.4.3.

### ISSUE THREAD

**Issue by abelardolg** [pouchdb/pouchdb#7232]
### Issue
When I visit https://cdn.jsdelivr.net/pouchdb/6.4.3/pouchdb.min.js the above message is displayed.

### Info
- Environment: -
- Platform: -
- Adapter: -
- Server: -

### Reproduce
Visit https://cdn.jsdelivr.net/pouchdb/6.4.3/pouchdb.min.js and it displays.

**Comment by MartinKolarik** [comment]
https://cdn.jsdelivr.net/npm/pouchdb@6.4.3/dist/pouchdb.min.js is the correct link. There was a PR to fix it some time ago but for some reason it got closed (#6753).

**Comment by daleharvey** [comment]
Apologies, didnt realise the fix was correct, merged now will be fixed in next release / site update - https://github.com/pouchdb/pouchdb/commit/b541f2089c492445884e8720e5eaab171893c2fa

**Comment by MartinKolarik** [comment]
@daleharvey  👍
