### ISSUE TITLE
slack.pouchdb.com nginx default page, no invite available

### ISSUE THREAD

**Issue by optio** [pouchdb/pouchdb#7234]
http://slack.pouchdb.com shows the nginx default page.
New users can't request an invite for pouchdb.slack.com

**Comment by daleharvey** [comment]
We do not use slack any more and removed it from the website / documentation, its only linked in an old blog post, [irc](https://www.irccloud.com/invite?channel=pouchdb&hostname=irc.freenode.net&port=6697&ssl=1) is recommended

**Comment by alxndrsn** [comment]
@daleharvey this is still an "issue" - DNS is still pointing to one of your servers :slightly_smiling_face:
