### ISSUE TITLE
The way PouchDB replicates attachments means view generation takes twice as long

### ISSUE THREAD

**Issue by SCdF** [pouchdb/pouchdb#7248]
### Issue
View generation takes significantly longer if the documents that are having the view generated over them have an attachment. This happens because:
 - When PouchDB replicates it writes the document once with the JSON data, and then writes it again with the attachment (as they are fetched separately)
 - View generation appears to perform relative to the number of writes to the changes feed, not the number of documents you have

### Info
- Version: 6.4.3. No evidence this is a regression
- Environment: browser, MacOS
- Platform: Chrome and FF, latest versions
- Adapter: IndexedDB

### Reproduce
Host the following gist locally (eg `python -m SimpleHTTPServer` in the same dir) to see this for yourself: https://gist.github.com/11b850ea065df28ef6f6a707544e87a7

Typical numbers I'm seeing is that without attachments it takes 500-700ms, and with attachments it takes 1000-3000ms, so 2-3x performance difference.

Background for this: we have actually worked to push some larger pieces of data into attachments because they aren't used for view generation, and CouchDB view generation is (in part) based on how much JSON you feed it. I'm surprised to see that PouchDB works in the opposite way.

**Comment by SCdF** [comment]
Looking into this more, this seems entirely because writing attachments takes two writes as opposed to one.

I've updated the gist to reflect this, by adding another case where we write a doc, then make a modification to that doc, which _also_ causes PouchDB to take twice as long to generate views.

This explains why I can't find any attachment-specific code that is wrong, but this still doesn't seem like correct performance to me. My changes feed should be the same "length" (because if I generate 1000 documents and then edit them there should still only 1000 entries in the changes feed, as the original creates are now invalid) and there are the same number of documents to process.

**Comment by SCdF** [comment]
I've updated the title and description to be a more accurate representation of the problem

**Comment by alxndrsn** [comment]
> When PouchDB replicates it writes the document once with the JSON data, and then writes it again with the attachment (as they are fetched separately)

I'm not sure this is true, at least in the browser with two `idb`-backed pouch instances.  The code below suggests that when creating 3 docs with attachments, there are three items appearing in the changes feed:

```
src = new PouchDB(`source-${Date.now()}`);
tgt = new PouchDB(`target-${Date.now()}`);

docWithAttachment = {
  a_doc: true,
  _attachments: {
    attachment: {
      content_type: 'text/plain',
      data: btoa('this is some data'),
    },
  },
};

Promise.resolve()
  .then(() => src.post(docWithAttachment))
  .then(() => src.post(docWithAttachment))
  .then(() => src.post(docWithAttachment))
  .then(() => src.replicate.to(tgt))
  .then(() => tgt.changes())
  .then(changes => console.log(`changes=${changes.results.length}; last_seq=${changes.last_seq}`))
  .catch(console.log);
```

Looking at the PouchDB source, I can't see why this would be different when replicating over HTTP, but I'll check.

**Comment by daleharvey** [comment]
So yeh as @alxndrsn said, attachments dont cause extra items in the changes feed, we pull down attachments in a seperate request but they still get written in the same transaction and cause a single change event. 

Attachments do take extra work, we write attachments to a seperate table in indexeddb so each attachment doubles the number of writes, if you dont want attachments in your map / reduce view you should delete them

Closing out since the premise of this bug isnt correct, it still is slower and work could be done to make map reduce faster, happy to take patches, however my focus is on https://github.com/pouchdb/pouchdb/issues/6543 to make faster and easier querying
