### ISSUE TITLE
Checking for valid CloudDB before a replicate.from? 

### ISSUE THREAD

**Issue by simonkincaidkintronix** [pouchdb/pouchdb#7251]
### Issue
My app requires admin users to be able to change the CloudDB address i.e. hostname / port.
I am totally able to do replication normally, but now I am trying to catch errors where a replicate.from() is executed on an incorrect hostname (i.e. the user has either a typo or just the wrong URL). 

It seems like a replicate.from() basically allows anything to pass as an address and it just hits 'complete' rather than 'denied' or 'error' like I would probably expect. 

Is this just a consequence of PouchDB being an offline capable, as in it just assumes it doesn't have connectivity to the database?

### Info
- Environment: WebView / Ionic / Angular
- Platform: Android
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
return new Promise( (resolve, reject) => {
let x = this.getDbConfig(dbName);
this.dbStatus[dbName] = 'downloading';
let host = 'I can type anything here really :-|';
	console.log('Using host ' + host);

			this.dbArray[x.name].replicate.from(host, dbOptions)
			.on('active', info => 	{ 
				console.log(dbName + ' active' + info);
				this.dbStatus[dbName] = 'downloading'; 
			})
			.on('error', err => 	{ 
				console.log(dbName + ' error' + err);
				//reject(err); 
			})
			.on('change', info => {
				console.log(dbName + ' complete' + info);
			})
			.on('denied', err => {
				console.log(dbName + ' DENIED' + err);
			})
			.on('complete', info => { 
				console.log(dbName + ' complete' + info);
				console.log(info.doc_write_failures);
				console.log(info.docs_read);
				console.log(info.docs_written);
				console.log(info.end_time);
				console.log(info.errors);
				console.log(info.last_seq);
				console.log(info.ok);
				console.log(info.start_time);
				console.log(info.status);

				/*
				"doc_write_failures": 0,
				"docs_read": 2,
				"docs_written": 2,
				"end_time": "Fri May 16 2014 18:26:00 GMT-0700 (PDT)",
				"errors": [],
				"last_seq": 2,
				"ok": true,
				"start_time": "Fri May 16 2014 18:26:00 GMT-0700 (PDT)",
				"status": "complete"*/
				this.dbStatus[dbName] = 'completed'; 
				resolve(true); 
			});

		});

**Comment by simonkincaidkintronix** [comment]
I've just seen that if I change the host to something like:
let host = 'http://www.pouchdb.com/whatever/';
I do get an error {"status":0,"name":"unknown","message":"getCheckpoint rejected with "}
This is a slightly better outcome, because at least I get an error. But then I would expect it to do a complete as well. 

Apologies, I am sort of new to PouchDB so grateful for any help

**Comment by daleharvey** [comment]
So only `complete` or `error` should fire, either it completes successfully or in error, have an example up at https://sugar-axolotl.glitch.me/ and confirms the bug you are seeing that `replicate.from("randomstring")` fires `on("complete"` which is a bug

**Comment by simonkincaidkintronix** [comment]
Thanks Dale, how do we fix it then?

**Comment by daleharvey** [comment]
Well the test is pretty easy just copy and paste https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/changes.js#L163 but  change the url to randomstring, as for the fix it sounds like either https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-replication/src/replicate.js#L8 or maybe https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-replication/src/replicateWrapper.js arent catching the error correctly, would find out where and make sure it triggers the error path instead of just competeReplication

**Comment by daleharvey** [comment]
lol, so spent too long debugging this, it isnt actually a bug. If the database you are replicating from doesnt start with `http://` then it isnt recognised as a http adapter, just a local database which is subsequently created and successfully replicated from, you can do the check yourself, `new PouchDB("randomname", {adapter: "http"})` I think should also force an error
