### ISSUE TITLE
custom sort order/collation for index?

### ISSUE THREAD

**Issue by adueck** [pouchdb/pouchdb#7254]
I've scoured the documentation, and can't find anything on this, and I know this is a long shot... but is it possible to use a custom sort order/collation in indexes?

I ask this because I need to be able to make `$gte` queries in an alphabetical listing based on a rare foreign alphabet. Is there a way to compare strings differently based on different locales? (Like [this ICU collation demo](https://ssl.icu-project.org/icu-bin/collation.htm))

CouchDB uses the ICU Library for sorting which does support sorting based on foreign or custom alphabets. But it seems that CouchDB has this feature disabled. (see: [CouchDB Finnish/Swedish collation view](https://stackoverflow.com/questions/36197600/couchdb-finnish-swedish-collation-view)) 

Is there any chance this could be available in PouchDB ??

**Comment by daleharvey** [comment]
It isnt right now, obviously ICU is huge and we couldnt depend on it in the browser so we have just used ascii ordering @ https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-collate/src/index.js#L275

I think it would be fine to make this pluggable, not entirely sure if the best way for us to do that but happy to figure out a nice way

**Comment by adueck** [comment]
That would be phenomenal if it could be pluggable. It would put this great product even further ahead.

**Comment by adueck** [comment]
I was asking the loki.js people about this issue and @obeliskos found a nice way to expose and override the traditional sort function. See [this issue](https://github.com/techfort/LokiJS/issues/672) and [this Loki sandbox gist](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/cd7c219e348780f294e23a2ac292e1f3/raw/643f292fefeb91b797addf5b7c2c83f6b12c544d/LokiJS%2520Comparators)

You're absolutely right, including something as big as ICU would be ridiculous, but if you could expose the comparison function in a similar way it would be really nice to be able to add in a custom sort function.

It turns out that JavaScript does have a very nice, easy to use locale-based sorting using the [localeCompare()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#Checking_for_support_for_locales_and_options_arguments) method and [Intl.Collator()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator) object. Unfortunately specifying a custom locale for `localeCompare()` isn't fully for all mobile browsers... still though, if something like the above [loki.js gist example](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/cd7c219e348780f294e23a2ac292e1f3/raw/643f292fefeb91b797addf5b7c2c83f6b12c544d/LokiJS%2520Comparators) were possible, people could easily plug in their own sort functions with something [like this](https://stackoverflow.com/questions/3630645/how-to-compare-unicode-strings-in-javascript#3631861) perhaps.

With the [loki.js sandbox gist](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/cd7c219e348780f294e23a2ac292e1f3/raw/643f292fefeb91b797addf5b7c2c83f6b12c544d/LokiJS%2520Comparators) I was able to get it to do just what I needed by replacing the traditional sort function:
```
var cmp = function(a, b) {
  if (a == b) return 0;
  if (a < b) return -1;
  return 1;
}
```
With:
```
var cmp = function(a, b) {
  return a.localeCompare(b, 'locale-HERE');
}
```
