### ISSUE TITLE
this is not scoped in toPromise()

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#7259]
### Issue
`pouch-utils` complains if PouchDB functions are not bound to the pouchdb instance.

### Info
- PouchDB 6.4.3

#### `PouchDB.get()`
```
db = new PouchDB(`test-${Date.now()}`);
Promise.resolve('some-doc-id').then(db.get);
-> TypeError: this is undefined
```
#### `PouchDB.put()`
```
db = new PouchDB(`test-${Date.now()}`);
Promise.resolve({}).then(db.put);
-> TypeError: this is undefined
```

**Comment by daleharvey** [comment]
File is @ https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-utils/src/toPromise.js, anyone cleverer than me know how to fix this off hand? trying to get a clean sweep of the issues before release
