### ISSUE TITLE
Create classes, handle docs as objects like Realm

### ISSUE THREAD

**Issue by to175** [pouchdb/pouchdb#7265]
### Issue
I need to have more explicit code like Realm (classes etc).

### Info
- Environment: React Native
- Platform: iOS and Android
- Adapter: default
- Server: local

### Reproduce
This is not an "issue" but a question.
How to create classes like Realm one's please ? Because I need explicit code. Moreover if I have an error and the doc is a class, it will be easier because the error will be explicit. It there a way to do that please ? See realm.io, in swift I have already created classes. Now I wanna use PouchDB with React Native so I need to make it working.  :)

**Comment by willholley** [comment]
I'm not familiar with Realm but this seems like a general Javascript question rather than a PouchDB-specific issue. Perhaps try asking the Javascript community on StackOverflow?
