### ISSUE TITLE
Sycing against multiple remote databases

### ISSUE THREAD

**Issue by pokyworld** [pouchdb/pouchdb#7266]
### Issue

I'm using React/Redux with redux-pouchdb-plus managing persistence to PouchDB (all of which seems to be working correctly) and then syncing to CouchDb, a single database (per user) with a document for each Reducer. All works fine until you try to switch to a different user.

At this point the local data can be trashed/reset and the remoteDb needs setting to a different database, and replicate data FROM the server to create an initial/local/persisted state, before THEN activating sync() once again.

 After first calling sync.cancel(), and redefining the remoteDb, db.replicate.from() doesn't seem to work, but sync() does, except it replaces the server data with whatever I have in local state, wiping any data previously held. So I must replace local state on login with the server version of the truth.

Even if I manually get() the document, update the localDb, The CouchDB data for the "previous" db/document gets updated instead of the newly defined one. Oddly, the logs show the http request is going to the correct (new) db/document and there is no log data for the old db/document.

It appears that when checking revs it is finding the old database mentioned in local IndexedDb and getting confused. I've tried using db.destroy() to kill the PouchDB's but this also doesn't seem to clear old data.

The attached image shows the "mix-up" occurring with pouch-api lines (green) being where it happens most. In this example, I have logged out of user 799254 and logged in as 474424, but the 799254 has been trashed on CouchDb and "moved" to the new account effectively.

### Info
- Environment: ReactJS/Redux with redux-pouchdb-plus (for persisted store and reducers)
- Platform: (Chrome/Safari)
- Adapter: (IndexedDB)
- Server: (CouchDB
![screen shot 2018-05-08 at 17 07 31](https://user-images.githubusercontent.com/13939328/39752324-45a1a826-52e5-11e8-98d3-dab1dc481b96.png)
)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by willholley** [comment]
@pokyworld can you provide some sample code and/or a minimal reproduction? It's difficult to debug the issue with http logs alone but it sounds like PouchDB isn't getting destroyed correctly when you switch users.

**Comment by daleharvey** [comment]
Yeh hard to debug without a repro, but at a stab in the dark are you waiting for `.on('complete` before setting up your new replication? if you just `sync.cancel(); startNewSync();` you may get them mixed up

```
sync.on('complete', startNewSync);
sync.cancel();
```

**Comment by daleharvey** [comment]
Also needs more information to do anything with
