### ISSUE TITLE
Suggestions on pagination and query optimisation

### ISSUE THREAD

**Issue by iosfitness** [pouchdb/pouchdb#7269]
### Issue
 How to do a pagination on a specific type of documents.
All docs do not provide a parameter for filtered search

pouch.allDocs({startkey : 'doc05', endkey : 'doc06'}, function (err, response) {
  // handle err or response
});
Reference Link: https://pouchdb.com/2014/04/14/pagination-strategies-with-pouchdb.html

 I have a set of documents with one of the type **My Inspections**. I want to fetch the records of type **My Inspections** with pagination. I am using bulk upsert to insert the data

To fetch the data :
let query = {};
   let selector = {};
   selector.userId = { $eq: userId };
   if (current_status != '') {
       selector.current_status = { $eq: current_status }
   }
   if (type_of_inspection != '') {
       selector.type_of_inspection = { $eq: type_of_inspection }
   }

   query.selector = selector;
   db.find(query).then(function (result) {
       callback({ data: result })
   }).catch(function (err) {
       console.log('AlertCalled', '3')
       callback({ error: err })
       alert(err);
   });

Also, can you suggest a better approach to achieve this?

### Observation

As per my requirement, I need to fetch few additional data like locations and customer details along with listing. Now if I make multiple queries, the performance lags. As of now, I have only tested for 50 records. Not sure how it will behave when the list size increases.
Any inputs on how I can optimize the query?

### Info
- Environment: hybrid app
- Platform: iOS and Android
- Adapter: IndexedDB
- Server: NA

**Comment by willholley** [comment]
@iosfitness what indexes have you created to support the query? It looks like you'd benefit from an index on `["userId", "current_status", " type_of_inspection"]`, though that will only be effective when all 3 fields are specified in the query. You could create additional indexes on `["userId", "current_status"]` and `["userId"]` to support optional parameters.

Regarding fetching additional data, the only approach besides multiple queries is to change the data model so that data is denormalised - there isn't any join support.

**Comment by iosfitness** [comment]
@willholley  Thanks for the reply..

I have not used indexing as we I was facing an issue while sorting something like #7206

My req is to search records on type with pagination wherein "Key-type" : **LIST_INSPECTION**
I have a different type of records like INSPECTION_DETAILS , etc stored in my DB

Any other plugin/adapter which I can make use of?

Reference Link : 
https://pouchdb.com/2014/04/14/pagination-strategies-with-pouchdb.html

**Comment by daleharvey** [comment]
So there is a workaround for the sort problem mentioned in the linked bug, you definitely want to be making sure your index is created / used for performance. 

If you get your indexes working and it still isnt fast enough, then the work in https://github.com/pouchdb/pouchdb/issues/6543 should be a big difference
