### ISSUE TITLE
PouchDB doesn't get datas if custom server is down

### ISSUE THREAD

**Issue by etiks3** [pouchdb/pouchdb#7270]
### Issue
Hi there,
we use offline-peristence-toolkit in a JET(4.1.0) hybrid app for Android and iOS. Pouchdb is set properly and does the job in the browser when offline and when REST server is down.
It does the job in real device after build for the offline part, but we can't get any data if our REST server is down. Like if PouchDB/persistence toolkit making a difference if we are offline or if our REST is not accessible. Did you had this kind of issue before?

### Info
Environment: (hybrid app)
Versions:
- pouchdb: 6.3.4
- pouchdb-find: 6.3.4
Platform: (iOS/Android)
Adapter: (IndexedDB)
Server: (Custom service REST)

**Comment by daleharvey** [comment]
I dont know what the persistence toolkit or JET are and unlikely to get any help about them here. If you have an issue with pouchdb can you give more information about what you are trying and what doesnt work relating to pouchdb only, cheers

**Comment by daleharvey** [comment]
Not enough information here to do anything
