### ISSUE TITLE
can't make it work with a rollup setup

### ISSUE THREAD

**Issue by cmnstmntmn** [pouchdb/pouchdb#7286]
### Issue
i can't make it work in browser using a rollup setup;
i get `process is not defined`;  i tryed to fix with following @Rich-Harris's [comment](https://github.com/rollup/rollup/issues/487) by using **rollup-plugin-replace** without any luck

### Info
- Environment: browser

### Reproduce
1. add `pouchdb-browser` to this setup [rollup setup](https://github.com/ArthurClemens/mithril-starter-rollup)

```
yarn add pouchdb-browser
```

2. Import PuchDB into the project
```
//src/index.js

import PouchDB from 'pouchdb-browser';
const db = new PouchDB('my_database');
```
3. Make use of it
```
function addTodo('test') {
  var todo = {
    _id: new Date().toISOString(),
    title: text,
    completed: false
  };
  db.put(todo, function callback(err, result) {
    if (!err) {
      console.log('Successfully posted a todo!');
    }
  });
}

// hook the function to oninit

const Index = {
  oninit: addTodo
}
```

4. build the project and run it
```
yarn dev
```

**Comment by daleharvey** [comment]
This sounds a lot like https://github.com/pouchdb/pouchdb/issues/7263, its using our source files without switching the node implementations for the browser ones?

**Comment by daleharvey** [comment]
Yeh going to close as a dupe and have the other bug cover both - https://github.com/pouchdb/pouchdb/issues/7263
