### ISSUE TITLE
pouchdb-find does not support null in selector

### ISSUE THREAD

**Issue by Arman92** [pouchdb/pouchdb#7290]
### Issue
When using a null value compare in selector for pouchdb-find I get 
```
Cannot convert undefined or null to object
```

### Info
- Environment: (Node.js/Angular/TypeScript.)
- Platform: (Chrome)
- Adapter: (IndexedDB)
- Server: (CouchDB)

### Reproduce

```typescript
    getAllProducts(): Promise<Array<Product>> {
        const db = this._pouchDbAdapter.getPouchDBInstance();
        return new Promise((resolve, reject) => {
            db.createIndex({
                index: { fields: ["productName"] }
            }).then(() => {
                return db.find({
                    selector: { productName: { $gt: null } }, // Here if I change null to something else, (e.g. 0) it work fine
                    sort: ["productName"]
                });
            }).then((response => {
                resolve(response.docs);
            }))
                .catch((error) => {
                    reject(error);
                });
        });
    }
```
and then call it:
```typescript
this.productService.getProducts().then(products => {
   console.log("received products:", products);
}).catch(err => {
   console.log("error:", err);
});
```

The official [doc](https://pouchdb.com/guides/mango-queries.html) uses null to just filter certain documents by a field (or sort according to the field), but seems there is a problem with that.

**Comment by daleharvey** [comment]
Do you get a line number from that, are you still seeing it? something seems up here, the selector is the exact code that runs on https://nolanlawson.github.io/pouchdb-find/ (sort by name) and is working fine as well as. with the testing I am doing
