### ISSUE TITLE
The PouchDB data is not save in my Cordova base app after  "hard" close on iOS  -- only on first install

### ISSUE THREAD

**Issue by premtemp1** [pouchdb/pouchdb#7301]
### Issue
The PouchDB data is not save in my Cordova base app after "hard" close on iOS . This only happen on first install.  I have enough space on the device

Here are the steps :

Install the app on Iphone
save some data in PouchDB name test
verify that the data is saved
close the app (on iOS double click the hone button)
reopen the app
Verify that saved lost
This only happen on the first install

If I remove app and reinstall , I get the same flow,,, The data is save , on hard close the data is lost. Then if  I reopen the app again  and save data , Now the data is persistent,,,

### Info
- Environment: Node.js//hybrid app.)
- Platform: Cordova (iOS/Android.)
- Adapter: IndexedDB
- Server: PouchDB 6.4.1
ios version: 4.5.4 cordova :6.5 pouch : 6.4.1

### Reproduce
$scope.saveme=function(){
       var db =new PouchDB("test");
       var todo = {
         _id: new Date().toISOString(),
         title: "test",
         completed: false
       };
       db.put(todo, function callback(err, result) {
         if (!err) {
            alert('Successfully posted a todo!');
         }
         else{
            alert(err);
         }
      });
    }
$scope.showme = function(){
   var db =new PouchDB("test");
   db.allDocs({include_docs: true, descending: true}, function(err, doc) 
      {
          alert(JSON.stringify(doc));
      });
     }

**Comment by daleharvey** [comment]
Hi, yeh I have seen something like this reported before however as far as I understand there is nothing pouchdb can do, we save the data its up to cordova + ios how it persists it. If you investigate and found out that there is something we can do to tell ios to not delete the data then happy to take a look at that but as far as I can tell there isnt

**Comment by premtemp1** [comment]
Thanks. 
It would be good if you can add this problem somewhere in the documentation as an IOs bug not PouchDB

**Comment by jspblm** [comment]
I have the same issue. Is there a solution or workaround today?
