### ISSUE TITLE
How to use the same pouchdb data in all subdomains?

### ISSUE THREAD

**Issue by nepaul** [pouchdb/pouchdb#7306]
1. within `first.domain.com`: create a pouchdb and save some data
2. within `senond.domain.com`: can i get pouchdb-data in `first.domain.com`?

**Comment by daleharvey** [comment]
The easiest way is just to replicate via a server, otherwise https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy "Changing origin" may work, but I have never tried it, either way pouchdb is restricted to indexeddb restrictions, cheers
