### ISSUE TITLE
Programatically react to an idb abortion

### ISSUE THREAD

**Issue by vhmolinar** [pouchdb/pouchdb#7313]
### Issue
I'd like to programatically react to an idb abortion. Let me explain myself better... If Idb abortion callback is fired, I'd like to fall back to a in memory db adapter and warns users that something went bad.

Context: Recently my cordova project started to fail due to a full disk device problem. It wouldnt happen before march, but it seems that one recent chrome version has triggered such issue on my side. As users sometimes run into disk full, my app can't break.

I've read the pouchdb code a little and couldn't find yet an way to do it.
As I remember, in the past fall back adapters were possible to choose, but current documentation doesnt seems to include that.

### Info
- Environment: Cordova
- Platform: Chrome/Android 7
- Adapter: idb

### Reproduce
The problem occurs when user has a high usage of device disk.
-> _Database has a global failure DOMException_

Error:
{
    error: true,
    message: "unknown",
    name: "indexed_db_went_bad",
    reason: "QuotaExceededError",
    status: 500
}

**Comment by daleharvey** [comment]
The fallback adapters only works on what adapters are currently available on construction, it wasnt a mechanism to fall back from a database in use, the chrome change / bug was talked about @ https://github.com/pouchdb/pouchdb/issues/7241, hopefully more recent versions should cause this to happen less

As for a fallback database, it seems like catching failures and dropping to the fallback when you detect would be the best way to do things?

```
var db;

function pouchError(err) {
  if (err.reason === 'QuotaExceededError') { 
    warnTheUser();
    db = new PouchDB('name', {adapter: 'memory'});
  }
}

db.post(data).then(yay).catch(pouchError);
```
You could try replicating the database into the memory one or such, I cant see this being something we would provide inside pouchdb though
