### ISSUE TITLE
Pouch DB find plugin sorts based on ascii 

### ISSUE THREAD

**Issue by lakinmohapatra** [pouchdb/pouchdb#7318]
We have names as both capital & small letters . 
But when we are sorting names by asc, its showing capital letters first and then small letters .
Please help

**Comment by daleharvey** [comment]
Yup sort is ascii, issue @ https://github.com/pouchdb/pouchdb/issues/7224 to document it, and https://github.com/pouchdb/pouchdb/issues/7254 to be able to customise it
