### ISSUE TITLE
Incompatible with Node 10

### ISSUE THREAD

**Issue by jjosef** [pouchdb/pouchdb#7319]
### Issue
Cannot install on Node 10 because of inconsistencies with leveldown and sqlite package dependencies

### Info
- Environment: Node 10.2.0
- Platform: OS X
- Adapter: CouchDB
- Server: CouchDB

### Reproduce
Switch to Node 10.x and try to install. It fails on 6.4.3 and if you try to install from master it fails then too.

**Comment by daleharvey** [comment]
https://travis-ci.org/pouchdb/pouchdb/jobs/387333958 we run node 10 in CI and its passing, something with your setup?

**Comment by jjosef** [comment]
Must have been something locally causing a conflict. Appears to be fixed on 10.4.0 and npm 6.1.0
