### ISSUE TITLE
regex case insensitive

### ISSUE THREAD

**Issue by manikandan07081995** [pouchdb/pouchdb#7321]
### Issue
db.find({
 selector: {series: {$regex: RegExp('mario', "i")}}
});

**same code taken selector as** 

db.find({
 selector: {series: {}}
});

But when I use breakpoint   **/eh/i** showing.

### Info
- Environment: 8.11
- Platform: chrome
- Adapter: vscode
- Server: couchDB/PouchDB

**Comment by daleharvey** [comment]
3rd time you have opened this issue, happy to accept what is probably a simple patch but please dont keep opening the same issue
