### ISSUE TITLE
Async initialize step

### ISSUE THREAD

**Issue by sindresorhus** [pouchdb/pouchdb#7323]
### Issue

I would like the ability to asynchronously initialize the DB before any methods can be run against it.

My specific use-case is modifying some data before any methods like `.find()` or `.allDocs()` can be run.

This is what I currently do:

```js
class FooDB {
	constructor() {
		this.db = new PouchDB('foo', {
			adapter: 'idb'
		});

		this.ready = (async () => {
			await doSomeStuffToTheDb(this.db);
		})();
	}

	async getData() {
		await this.ready;

		const {docs} = await this.db.find({
			selector: {timeStarted: {$gt: true}},
			sort: [{timeStarted: 'desc'}],
		});

		return docs;
	}
}
```

And this is what I would like to see:

```js
class FooDB {
	constructor() {
		this.db = new PouchDB('foo', {
			adapter: 'idb',
			initialize: async db => {
				// Methods on `this.db` will not run until the `initialize()` promise resolves
				// However, you can run any methods on `db` here.
				// This is great for modifying the database on init before any other methods can access it, like doing migrations, etc.
				await doSomeStuffToTheDb(db);
			}
		});
	}

	async getData() {
		const {docs} = await this.db.find({
			selector: {timeStarted: {$gt: true}},
			sort: [{timeStarted: 'desc'}],
		});

		return docs;
	}
}
```

This way I don't have to `await this.ready` on everything that access the database.

### Info
- Environment: Browser
- Platform: (Chrome
- Adapter: IndexedDB
- Server: None

**Comment by daleharvey** [comment]
So not quite sure how we would block api calls from the rest of your app but not block api calls from the initialise function? I think this is best done in userland as you have done, especially given how unfeasible it would be to maintain these contracts across multiple databases + tabs

**Comment by sindresorhus** [comment]
@daleharvey You wrap the `db` instance used in the public PouchDB methods in a `Proxy` that makes the `db` methods await the `initialize` option method before returning its real Promise. The `db` instance passed to `initialize` doesn't have this `Proxy` wrapper and get the real Promise right away.

**Comment by daleharvey** [comment]
The userland solution I keep seeing to this (not specific to pouchdb, just db handling in general) is to control access to your database handle via a function `getDatabase(name).then(function(db) { `

We actually do a very similiar thing to your proxy solution under the hood (https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/taskqueue.js) and are slowly replacing it with wrapping the db handle (https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-indexeddb/src/index.js#L31)

**Comment by sindresorhus** [comment]
> The userland solution I keep seeing to this (not specific to pouchdb, just db handling in general) is to control access to your database handle via a function getDatabase(name).then(function(db) {

But that's almost the same as what I'm currently doing with `await this.ready`. I was hoping to reduce the boilerplate somehow.

**Comment by daleharvey** [comment]
So yeh understandable, however I dont think we want to be maintaining what can be quite complicated code to support what is quite a small style choice, in practice I have found the getDatabase() method to be clean and clear and I know the taskqueue version has complicated things a lot more (especially when it comes to error handling etc), cheers
