### ISSUE TITLE
Unintended behavior with find, deep fields, and $exists?

### ISSUE THREAD

**Issue by mercuito** [pouchdb/pouchdb#7324]
### Issue
This is kind of not so simple, so please let me just start with an example.
Say I have an object like this:

```javascript
{
  lessonIds: null
}
```
and I do this
```javascript
pouchdb.find({'lessonIds.1': {$exists: true}})
```
I expect the given object to not be returned. It does get returned. This is because, and this is only from my own digging, so bear with me, in your code (index.es.js line 498), you have this

```javascript
  '$exists': function (doc, userValue, parsedField, docFieldValue) {
    //a field that is null is still considered to exist
    if (userValue) {
      return fieldIsNotUndefined(docFieldValue);
    }
```

This seems ok, but for this example you pass in the value of lessonIds, not 'lessonIds.1', which doesn't exist (undefined) because lessonIds is null. The reason why you pass null instead of undefined is here 

```javascript
function getFieldFromDoc(doc, parsedField) {
  var value = doc;
  for (var i = 0, len = parsedField.length; i < len; i++) {
    var key = parsedField[i];
    value = value[key];
    if (!value) {
      break;
    }
  }
  return value;
}
```
You simply break on the first null/undefined value. In this case you are breaking on lessonIds's value of null, not the deep field's assumed value of undefined.  
In essence, you are aliasing two separate questions into one answer.

Does the object have the field lessonIds?
Yes, the value is null, but it exists.

Does the object have the field lessonIds.1?
Yes, lessonIds is null, therefore any and all subfields must also exists and be null.

This inference doesn't make sense. Is this actually intended? I don't see much use for aliasing these two questions.

I think the best fix would be to change the 
getFieldFromDoc function to handle deep fields explicitly, like so

```javascript
function getFieldFromDoc(doc, parsedField) {
  var value = doc;
  for (var i = 0, len = parsedField.length; i < len; i++) {
    var key = parsedField[i];
    value = value[key];
    if (!value) {
      if(i != parsedField.length - 1){
        //we haven't actually reached the field yet, but we cannot continue
        value = undefined;
      }
      break;
    }
  }
  return value;
}
```

### Info
- Environment: any
- Platform: any
- Adapter: any
- Server:  any

### Reproduce
see above

**Comment by daleharvey** [comment]
Awesome explanation, many thanks, I think what you have posted makes sense, would you like to make a PR for this?
