### ISSUE TITLE
Pouch db info API returns invalid document count 

### ISSUE THREAD

**Issue by manikandan07081995** [pouchdb/pouchdb#7325]
### Issue
Am using pouch db info API, to get the pouch db document count in my application. In some cases, doc_count key returns 0 even pouch db has more than one document.

### Info
- Environment: hybrid app
- Platform: iOS/Android
- Adapter: IndexedDB/WebSQL
- Server: PouchDB Server

### Reproduce
I can't recreate the issue, but it happens unexpected moment. Tell me this is known issue or new one. Please someone help me on this.

**Comment by daleharvey** [comment]
which adapter are you using? its not a known issue, never seen it reported so I would definitely check your usage

**Comment by manikandan07081995** [comment]
For iOS it takes WebSQL and for Android it takes indexedDB as adapter.

**Comment by manikandan07081995** [comment]
Based on platform it takes these adapters as default.

**Comment by daleharvey** [comment]
So you see this with a specific adapter, what circumstance are you seeing it? need a lot more information to be able to debug this

**Comment by daleharvey** [comment]
Not enough information to debug
