### ISSUE TITLE
node crashes on error in pouchdb through if invalid ldb file

### ISSUE THREAD

**Issue by julianhille** [pouchdb/pouchdb#7332]
### Issue
If there is an `Error: Corruption: bad entry in block` error node is unable to catch that error and crashes completely.

### Info
- Environment: node
- Platform: macos
- Adapter: leveldb
- Server: pouchdb

### Reproduce
- Create a database
- exit process
- use vim and change the very first char in the `databasePath/000${number}.ldb` file to any ascii char
- start process again see error: `Error: Corruption: bad entry in block`

**Comment by daleharvey** [comment]
Closing as a bug with level
