### ISSUE TITLE
PouchDB not running at all in Safari

### ISSUE THREAD

**Issue by nielsjakob** [pouchdb/pouchdb#7334]
Hi, I've been running PouchDB in Chrome for a while and really love it!

Now I launched it in Safari and I get the following:
"SecurityError: IDBFactory.open() called in an invalid security context"

<img width="813" alt="screen shot 2018-06-15 at 22 11 16" src="https://user-images.githubusercontent.com/37240226/41487504-3e279a70-70e9-11e8-849d-e7bfb2d107c1.png">

The above is from a totally clean setup, just the following index.html:

```
<script type="text/javascript" src="pouchdb-6.4.3.min.js"></script>

<script>

  PouchDB.debug.enable('*');

  db = new PouchDB('test');
  
</script>
```

Any code after `db = new PouchDB('test');` is ignored entirely (even a `console.log('hi');`)

SYSTEM
I'm using
Safari Version 11.1.1 (13605.2.8)
on
macOS High Sierra Version 10.13.5 (17F77)

**Comment by daleharvey** [comment]
It sounds like you are using pouchdb inside an frame? safari seems to block this

**Comment by pkienzle** [comment]
Still failing with the same error on the latest release:

    PouchDB Version 7.1.1  
    Safari Version 13.0.5 (14608.5.12)  
    macOS Mojave Version 10.14.6

No frames used in index.html:
```html
<html><head>
<script src="//cdn.jsdelivr.net/npm/pouchdb@7.1.1/dist/pouchdb.min.js"></script>
<script>
console.log("Trying to create db");
db = new PouchDB('test');
console.log("success!");
</script>
</head></html>
```

Console output:

    [Log] Trying to create db (0.0.0.0, line 4)
    [Error] SecurityError: IDBFactory.open() called in an invalid security context
	open (pouchdb.min.js:7:83684)
	(anonymous function) (pouchdb.min.js:7:83684)
	(anonymous function) (pouchdb.min.js:7:85955)
	(anonymous function) (pouchdb.min.js:7:77688)
	an (pouchdb.min.js:7:75850)
	(anonymous function) (pouchdb.min.js:7:77803)
	dn (pouchdb.min.js:7:77806)
	We (pouchdb.min.js:7:40035)
	Global Code (0.0.0.0:5)

**Comment by pkienzle** [comment]
Finally got it to work by adjusting Safari preferences.  

Needed to unblock "Cookies and website data" on the Privacy tab:

<img width="842" alt="Screen Shot 2020-01-29 at 8 36 00 PM" src="https://user-images.githubusercontent.com/473456/73412674-63eb7a80-42d7-11ea-8851-0c600dc5deb2.png">

I couldn't figure out how to enable them for specific sites.  

Maybe catch and throw the error with a clearer message?  I guess that has to happen at the application level rather than within PouchDB.
