### ISSUE TITLE
Can't select first object from array of objects

### ISSUE THREAD

**Issue by iozeen** [pouchdb/pouchdb#7335]
I can't find a way to select objects at 0 position in array. Basically, I was looking for functionality to get this **`attributes.prices[0].UnitPrice`** done everywhere and couldn't find an answer. Opening an issue in case someone got similar case:
```
prices: [
  {
    ...,
    UnitPrice: 5
  },
  ...
]
```
Tried this, but it returns error:
```
...
$and: 
[
   { 'attributes.prices': { $elemMatch: { $gte: price.from } } },
   { 'attributes.prices': { $elemMatch: { $lte: price.to } } }
]
```

**Error: unknown operator "0" - should be one of $eq, $lte, $lt, $gt, $gte, $exists, $ne, $in, $nin, $size, $mod, $regex, $elemMatch, $type, $allMatch or $all**

**Comment by daleharvey** [comment]
I am going to guess this isnt supported in mango, but not certain, @garrensmith ?

**Comment by iozeen** [comment]
I've received an answer from stackoverflow: https://stackoverflow.com/questions/50898256/cant-select-first-object-from-array-of-objects/50910944#50910944

**Comment by daleharvey** [comment]
oh awesome, cheers for the update, closing out
