### ISSUE TITLE
Database Compaction for IndexedDB does not work.

### ISSUE THREAD

**Issue by MrGurns** [pouchdb/pouchdb#7336]
### Issue
Remote/Local DB Compaction does not seem to be working for IndexedDB solutions.

### Info
- Environment: React Native on Expo SDK 27.0.1
- Platform: Android/iOS (React Native)
- Server: CouchDB
- Adapter: asyncstorage (local) / HTTPS (remote) (IndexedDB iirc)

### Additional Info
- PouchDB Version: (from package.json)
    "pouchdb-authentication": "^1.1.3",
    "pouchdb-find": "6.4.3",
    "pouchdb-react-native": "6.4.1",

- Background: Android asyncstorage 
iOS looks like it is unlimited.
I was constantly getting replication issues, as items were not flowing from android to Project fauxton but were showing up in the local db (auto compaction turned on).
iOS did not have this issue.

### Reproduce
On Project Fauxton, DB sizes were showing around 120mb-240mb in size, much beyond the limits of Android's asyncstorage ([has a limit of 6mb](https://github.com/facebook/react-native/issues/3387#issuecomment-148042923)).
<img width="1602" alt="screen shot 2018-06-15 at 2 05 50 pm" src="https://user-images.githubusercontent.com/15333090/41509485-a4feb35e-7211-11e8-975c-7fb563097c27.png">
<img width="1605" alt="screen shot 2018-06-15 at 2 21 13 pm" src="https://user-images.githubusercontent.com/15333090/41509488-c7693be4-7211-11e8-86ff-c174023efe7c.png">

My compaction parameters on  Project Fauxton: 
compaction_daemon
check_interval: 300
min_file_size: 131072
compactions
compactions: [{db_fragmentation, "70%"}, {view_fragmentation, "60%"}, {from, "00:00"}, {to, "04:00"}, {strict_window, true}]

(for some reason that i have yet to figure out, the server is not running compactions of it's own, even with those limits set.)

In my React Native project, after connecting to the remote and prior to syncing my changes to my local copy I run the following code:

```
this.remoteDB.compact(function (err, result) {
  if (err) { 
    return console.log('Error Compacting Remote DB: ' + JSON.stringify(err)); 
  } else { 
    console.log('Compacted Remote DB: ' + JSON.stringify(result)); 
  }
});
```
It returns the following result: 
Compacted Remote DB: {"ok":true}

After which I print out the info of the local and remote dbs:
Local DB Info: {"doc_count":483,"update_seq":554,"db_name":"localDB-family-burton-1521607461-85ad91a8-2cc2-11e8-a033-da60d26d4275-development","auto_compaction":true,"adapter":"asyncstorage"}

Remote DB Info: {"db_name":"family-burton-1521607461-85ad91a8-2cc2-11e8-a033-da60d26d4275","update_seq":"1777-g1AAAAFZeJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____sxI_4VGUpAAkk-xB6pIYGBjn4VPqAFIaDzZyBj51CSB19WB17_Coy2MBkgwNQAqodD7Y-mKCyhdAlO_PSqwlqPYARO39rERPgmofQNQCnbwoCwCx7mOD","sizes":{"file":48195129,"external":1609011,"active":40609196},"purge_seq":0,"other":{"data_size":1609011},"doc_del_count":57,"doc_count":195,"disk_size":48195129,"disk_format_version":6,"data_size":40609196,"compact_running":false,"cluster":{"q":8,"n":1,"w":1,"r":1},"instance_start_time":"0","host":"*Endpoint*/family-burton-1521607461-85ad91a8-2cc2-11e8-a033-da60d26d4275/",,"auto_compaction":false,"adapter":"https”}

The sizes do not look like they have shrunk at all.

Then I call the api directly for compaction specified [here](http://docs.couchdb.org/en/2.1.1/api/database/compact.html).

![screen shot 2018-06-15 at 2 16 20 pm](https://user-images.githubusercontent.com/15333090/41509625-1b2465b8-7214-11e8-915b-9dc10caac068.png)

Project Fauxton results after making the API call:
<img width="1635" alt="screen shot 2018-06-15 at 2 16 34 pm" src="https://user-images.githubusercontent.com/15333090/41509632-2d363218-7214-11e8-82dd-0ccc7a493851.png">

<img width="1642" alt="screen shot 2018-06-15 at 2 59 08 pm" src="https://user-images.githubusercontent.com/15333090/41509644-345ea976-7214-11e8-9d44-8f333b4f3fb7.png">

**Comment by daleharvey** [comment]
This is a fairly confusing report, you talk about the sizes you see reported in fauxton, but mention indexeddb / asyncstorage, fauxton reports the servers disk size and have nothing to do with indexeddb

For remote databases we literally just send a http call to _compact, its up to the database to do its compaction, if you arent seeing the numbers you expect when compacting on the server then you need to discuss / file a bug on CouchDB

**Comment by MrGurns** [comment]
That's the thing, it is as if your call to _compact isn't working. I make the api call from Insomnia and it works, i make the call from the client and it doesn't.
