### ISSUE TITLE
Is pouchdb-find supposed to getting deleted documents?

### ISSUE THREAD

**Issue by bgold0** [pouchdb/pouchdb#7338]
### Issue
When I do the following, it is returning deleted documents. So when I do a `db.get()`, I end up getting an error like so: `{error: "not_found", reason: "deleted", status: 404, name: "not_found", message: "deleted"}`. Is there something I can do to not retrieve the deleted documents?

	var db = new PouchDB(url, {ajax: {timeout: 5000}});

	return db.find({selector:{$and: [{type:"user"},{entry:true}]}})
	.then((data) => {

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: iOS
- Adapter: default
- Server: Cloudant

**Comment by bgold0** [comment]
To give a little more context this occurs after I do a CURL `DELETE` command to a Cloudant endpoint. `http://URL/{db_name}/{id}?rev={rev}`

Because you can't control Cloudant's compaction schedule, it appears `db.find()` isn't filtering out things that aren't compacted? That would be my best guess.

**Comment by daleharvey** [comment]
oh wait a second, you are doing a remote query? then its nothing to do with us, we just send http requests, its cloudant that is not updating the query correctly (not sure how cloudant / couch ensure consistency in mango queiries, you may need to do something to ensure the index has caught the delete)

**Comment by bgold0** [comment]
Damn Cloudant. Sorry bout the confusion, you're right, this did occur when I was hitting a Cloudant endpoint and not a pouchDB local database. My mistake. @daleharvey (I appreciate the response)
