### ISSUE TITLE
Wrong blob URL on Android

### ISSUE THREAD

**Issue by Wndrr** [pouchdb/pouchdb#7339]
### Issue
Get a wrong URL attachment on mobile application

### Info
- Environment: Cordova
- Cordova plugins: Cordova-Media-Plugin, Cordova PLugin SQLite 2 
- Platform:  Android
- Adapter: IndexedDB (tried WebSQL too)
- Server: CouchDB

### Reproduce
When testing in browsers, I get this URL : 

`blob:http://localhost:4400/0386f19b-bdb7-47d7-a9aa-4fb8545116bb`

It works nice, I can play my audio file.

When deploying in an Android device, I get this URL : 

`blob:file:///03b8e5bf-2709-4254-9464-50d53758c897`

and can't play my audio file. There are no warning or error in console.

How I create URL : 

```
 db.getAttachment(row.doc._id, 'file').then(function (blob) {
                        var a = URL.createObjectURL(blob);
                        console.log(a);
                        res.data.push({
                            "identifier": row.doc.identifier,
                            "title": row.doc.title,
                            "subtitle": row.doc.subtitle,
                            "url": a
                        });
})
```
Anyone facing similar issue? How can I get my audio attachment on mobile platforms ?

**Comment by daleharvey** [comment]
PouchDB returns the blob, how that is played / accessed isnt a pouchdb issue
