### ISSUE TITLE
Are partial indexes supported when passing a selector to replication?

### ISSUE THREAD

**Issue by aneeshd16** [pouchdb/pouchdb#7342]
### Issue
CouchDB supports creating a Partial Index for mango queries as documented here: http://docs.couchdb.org/en/2.1.1/api/database/find.html#partial-indexes
While querying with a selector, we are required to pass the `use_index` parameter which contains the name of the design document where the index is defined.

I am using a selector for filtered replication from Couch -> Pouch. Is there an option to pass `use_index` here?

```
const selector = {"a": "b"} // some selector

localDB.replicate.from(remoteDB, {
    live: true,
    retry: true,
    selector,
    use_index: '_design/my-partial-index' // Will this work?
  });
```

I inspected the network request which hits the `/_changes` endpoint. The selector was passed in the request body, but the `use_index` parameter was not.

Thanks!

### Info
- Environment: (browser)
- Platform: (Chrome)
- Adapter: (IndexedDB)
- Server: (CouchDB)

**Comment by garrensmith** [comment]
No it isn’t supported. Partial indexes are only supported for querying for CouchDB not for replication.

________________________________

**Comment by garrensmith** [comment]
It would need to be implemented in CouchDB first

________________________________

**Comment by Prabuganesan** [comment]
Is there any updates regards this?
