### ISSUE TITLE
skip_setup parameter not working?

### ISSUE THREAD

**Issue by wgrhstf** [pouchdb/pouchdb#7344]
### Issue
I tried to stop my clients from creating old databases they might have into CouchDB, but despite using `skip_setup: true` they still appear at my server. Is this feature broken, or did I misunderstand the syncing process?
At the moment my call looks like this:

```
let db = new PouchDB('ClientDB', {adapter: 'idb'}); 
let remoteDB = new PouchDB('http://'+ServerIP+':5984/id-do.not-exist');
db.sync(remoteDB, {
    live: true,
    retry: true,
    skip_setup: true,
    back_off_function: function (delay) {
        return 1000;
    });
```

### Info
- Environment: Electron
- Platform: any
- Adapter: IndexedDB
- Server: CouchDB

**Comment by daleharvey** [comment]
The skip_setup is part of database options, not sync options

```let remoteDB = new PouchDB('http://'+ServerIP+':5984/id-do.not-exist', {skip_setup: true});```

Just to be clear this means the sync will fail unless you have already created `id-do.not-exist' on the server
