### ISSUE TITLE
Setting cookie on fetch function

### ISSUE THREAD

**Issue by gine** [pouchdb/pouchdb#7358]
### Issue

I need to set cookie on my application and to do that i try like explained on your documentation and on [whatwg-fetch](https://www.npmjs.com/package/whatwg-fetch#sending-cookies) documentation:

```
var db = new PouchDB('http://example.com/dbname', {
  fetch: function (url, opts) {
    opts.headers.set('credentials', 'same-origin');
    return PouchDB.fetch(url, opts);
  }
});
```

but this doesn't happens.

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: Couchbase
- Pouchdb version: 7.0

**Comment by daleharvey** [comment]
The fetch documentation doesnt say to send a header, its an option to the fetch call: 

```
var db = new PouchDB('http://example.com/dbname', {
  fetch: function (url, opts) {
    opts.credentials = 'same-origin';
    return PouchDB.fetch(url, opts);
  }
});
```
