### ISSUE TITLE
PouchDB-find - Failed to compile on Vue.js

### ISSUE THREAD

**Issue by trojek** [pouchdb/pouchdb#7363]
### PouchDB-find - Failed to compile on Vue.js
I want to use pouchdb-find in an application based on Vue.JS but I got a Failed to compile error

.

### Info
- Environment: Vue.js

### Reproduce
I installed both 'pouchdb-browser and pouchdb-find.
When I execute above code:

```
import PouchDB from 'pouchdb-browser'
PouchDB.plugin(require('pouchdb-find'));
```

I got an error:

`./node_modules/pouchdb-find/node_modules/pouchdb-collate/lib/index.js Module build failed: Error: ENOENT: no such file or directory, open '/home/tomek/Projects/sample/node_modules/pouchdb-find/node_modules/pouchdb-collate/lib/index.js'`

**Comment by aprixon01112017** [comment]
I am doing this (Vue.js):

`import PouchDB from 'pouchdb-browser';

PouchDB.plugin(require('pouchdb-upsert'));
PouchDB.plugin(require('pouchdb-find'));

...

db.find()
`

and I am getting "TypeError: db.find is not a function"

Maybe it is related

**Comment by garrensmith** [comment]
Could you try:

```js
import PouchDB from 'pouchdb-browser';
import * as PouchDBFind from 'pouchdb-find';
PouchDB.plugin(PouchDBFind);
```

and 

```js
import PouchDB from 'pouchdb-browser';
import PouchDBFind from 'pouchdb-find';
PouchDB.plugin(PouchDBFind);
```

**Comment by trojek** [comment]
I tried to add code as @garrensmith  suggested, but I got an error `TypeError: db.find is not a function`. Then I run one more time `npm install --save pouchdb-find` and then I got an error:

`./node_modules/pouchdb-find/node_modules/pouchdb-errors/lib/index.es.js Module build failed: Error: ENOENT: no such file or directory, open '/home/tomek/Projects/sample/node_modules/pouchdb-find/node_modules/pouchdb-errors/lib/index.es.js'`

**Comment by trojek** [comment]
I solved the problem by removing node_modules folder (`rm -rf node_modules`) and then install all dependencies (`npm install`)

**Comment by daleharvey** [comment]
Awesome then fixed, cheers
