### ISSUE TITLE
docuemntation titles are not always on separate lines

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#7366]
### Issue

<img width="591" alt="screen shot 2018-07-02 at 10 07 31" src="https://user-images.githubusercontent.com/191496/42152459-719331ae-7de0-11e8-90e7-ec58774a3748.png">

^ _Plugins_ and _PouchDB allDbs()_ should be on separate lines.

### Info
- Environment: Firefox, Chrome
- Platform: OSX

### Reproduce

https://pouchdb.com/external.html

**Comment by daleharvey** [comment]
Fixed, cheers for the heads up
