### ISSUE TITLE
JavaScript runtime error: 'fetch' is undefined in IE11

### ISSUE THREAD

**Issue by zviredler** [pouchdb/pouchdb#7370]
Hi, i get this error in IE11:
**'fetch' is undefined**
On this line:
`var f$1 = fetch;`
 [pouchdb-7.0.0.js] Line 4838
In pouchdb-6.4.3 everything works...
Thx!

**Comment by garrensmith** [comment]
We have switched to using the fetch api for PouchDB 7.0. You will need to use a fetch polyfill for IE11 https://www.npmjs.com/package/whatwg-fetch
