### ISSUE TITLE
Typescript losts all type info in VSCode

### ISSUE THREAD

**Issue by naivefun** [pouchdb/pouchdb#7375]
With `import PouchDB from 'pouchdb'` (7.0) in TS, the type info is lost in VSCode.

If I do `const db = new PouchDB('db')` the type shows db is `any` type where I expect `Database` type.

Another question is how I import type from correct package? I see `Database` in `pouchdb-mapreduce` package but I cannot import it so that I can force type on db: `db: Database` ?

**Comment by daleharvey** [comment]
Happy for pr's to get ts working. However we don't use TS and I know nothing about it so can't help sorry

**Comment by ptitjes** [comment]
@naivefun See https://pouchdb.com/guides/setup-pouchdb.html#typescript
