### ISSUE TITLE
Changes feed does not work with karma tests

### ISSUE THREAD

**Issue by jkndrkn** [pouchdb/pouchdb#7379]
### Issue
I have a set of karma integration tests that DO NOT mock PouchDB. These tests intentionally *do* use PouchDB because their purpose is to test database code. These tests currently work fine for most of my PouchDB code but they do not work with the changes feed. They timeout instead of executing to completion.

### Info
- Environment: karma 2.0.2, pouchdb 6.3.4, 
- Platform: macOS 10.13.5
- Server: CouchDB

### Reproduce
In order to get karma tests containing PouchDB code to pass, I have to run the following code:

    // Capture and ignore request initiated by angular-mocks
    let requestHandler = this.$httpBackend.when('GET', 'partials/common/home.html').respond({});

    // Re-run digest to fire non-angular promises in PouchDB
    let interval = 20;

    setInterval(() => {
      this.$rootScope.$digest();
    }, interval);

This code, however, does not enable code that contains calls to PouchDB changes to pass. What can I do to prevent the PouchDB changes feed from causing my tests to timeout?

**Comment by daleharvey** [comment]
Sorry but dont understand this at all, can you describe what you think the bug is without any reference to karma, with the full code to reproduce would be much easier as well (https://pouchdb-bug-helper.glitch.me/)

**Comment by daleharvey** [comment]
Just at a guess, do you cancel the changes call and ensure the complete event has been fired before ending the test, this has caused problems in tests before, test.changes.js should have an example

**Comment by jkndrkn** [comment]
No, I do not cancel the changes call. I will see if that fixes that issue. Thanks!
