### ISSUE TITLE
Leveldown as optionalDependencies

### ISSUE THREAD

**Issue by op01** [pouchdb/pouchdb#7381]
### Issue
Leveldown package is not an optional dependency defined in package.json as described [here](https://pouchdb.com/errors.html#windows_leveldown)

> Since v3.2.1 leveldown was changed to be an optional dependency: this way, npm will not refuse installing PouchDB even when having compiling errors. That way, you can use PouchDB normally, and will get an error only when trying to use leveldown as the backend

### Info
- Environment: Node.js
- Platform: Windows
- Adapter: Leveldown

**Comment by daleharvey** [comment]
Yeh that got replaced by custom builds like pouchdb-browser, or roll your own https://pouchdb.com/custom.html

**Comment by daleharvey** [comment]
The docs should be updated however

**Comment by daleharvey** [comment]
Removed the whole section since it is outdated @ https://github.com/pouchdb/pouchdb/commit/1a47e9758f4a999cfd89b1737dc13e617682986c
