### ISSUE TITLE
PouchDB 7.0.0 special header not working

### ISSUE THREAD

**Issue by trainingnote** [pouchdb/pouchdb#7383]
### Issue
With PouchDB 6.4.3 I was using the following code to connect to a remote couchDB database behind a proxy using a special header

```
        this.remoteDB = new PouchDB(url, {
            skip_setup: true,
            ajax: {
                headers: {
                    'X-Auth-MySpecial-Token': token
                },
                withCredentials: false,
            }
        })
```
With pouchdb 7.0.0 I have some trouble of doing the same thing, I understand that I have to use the fetch API so I tried the following [(using fetch doc options)](https://github.github.io/fetch/#options) : 
```
 this.remoteDB = new PouchDB(url, {
            fetch: function (url, opts) {
                opts.headers.set('X-Auth-MySpecial-Token', token);
                opts.credentials = 'omit';
                return PouchDB.fetch(url, opts);
            },
            skip_setup: true,
        })

```

But I am not able to access the database, getting a `not allowed` error, and the following message : 

`Failed to load https://myurl.com/userdb-706cfsd6c/_local/eUXcRThraR4yMIuMwIWi1g%3D%3D?: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:8100' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute`

**Comment by ulshv** [comment]
@trainingnote, try
```
$ npm install -g add-cors-to-couchdb
$ add-cors-to-couchdb
```
https://pouchdb.com/guides/setup-couchdb.html#set-up-cors

**Comment by daleharvey** [comment]
You also need credentials = 'include'; which is the new default since https://github.com/pouchdb/pouchdb/commit/b666cfc51c375d8fbb49f8323c180bdbfbd9a5d5

**Comment by trainingnote** [comment]
@ulshv Thank you for your messages but I don't get it, CORS is enable on my couchdb ( and I am able to connect using pouchdb 6.4.3 via the code of my first message above ).

@daleharvey thanks but no success there either.
