### ISSUE TITLE
withCredentials default true in 6.4.3, credentials = 'same-origin' in 7.0.0

### ISSUE THREAD

**Issue by jlami** [pouchdb/pouchdb#7391]
The move to `fetch` has changed the default behavior for cross-domain requests: where cookies were sent in 6.4.3, in 7.0.0 they are not.

I don't know if `credentials = 'include'` would be a safe default value. But this would fix any issues.

Otherwise it might be prudent to document this change.

default 6.4.3: https://github.com/pouchdb/pouchdb/blob/6.4.3/lib/index-browser.es.js#L8408

**Comment by daleharvey** [comment]
Yeh we should match the fact we set withCredentials in previous releases, good call, cheers
