### ISSUE TITLE
Remove donation where

### ISSUE THREAD

**Issue by broerse** [pouchdb/pouchdb#7392]
### Issue
It seems PouchDB 7.0.0 sponsors donation where. Can we remove level ? 

### Info
```
Thank you for using level!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/level/donate
```

**Comment by daleharvey** [comment]
We cannot remove level

**Comment by broerse** [comment]
Then I hope we don't get 40 other modules that start asking for money when you npm install PouchDB.

**Comment by broerse** [comment]
It seems the donationwhere is coming from [opencollective-postinstall](https://www.npmjs.com/package/opencollective-postinstall) and we can create a [shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) file to a dummy to disable this.
