### ISSUE TITLE
Optimizing network traffic

### ISSUE THREAD

**Issue by tudordumitriu** [pouchdb/pouchdb#7394]
### Issue
When updating a larger number of docs (around 10 let's say), there seems to be a LOT of network traffic.
https://www.screencast.com/t/vja8aY3t0t
https://www.screencast.com/t/U5Nd9lWMS70
So a call to CouchDB and the userDB info seems to be multiplied according to the number of documents being saved,
Also, there are 5 _changes calls, and lots of _local calls.

This is somehow related to https://github.com/pouchdb/pouchdb/issues/7329 (which I missed @daleharvey's response but got to pause/resume sync anyways).

So, we are pausing sync and resuming immediately after, which seems to be doing only one _bulk updated which is great.
Now the rest of the calls raise a strong question.
Couch and User DB info calls, _changes and _local.

In the above referred post @daleharvey suggested that reduce the amount of checkpointing by doing 2 replications (which from the docs seems to be doing anyways) so we'll try that or even write the patch. 
Am I correct in assuming it will reduce the _local calls?

What can be done about the rest of the calls?

I am very concerned that on a mobile device this large amount of calls will create major issues so I'd like to keep them to a minimum.

### Info
Pouch 6.4.3 (We tried upgrading to 7.0.0 but we have authentication issues)
Environment: Web and Cordova hybrid app
Platform: Chrome
Adapter: IndexedDB
Server: CouchDB 2.1.1

**Comment by daleharvey** [comment]
I previously suggested to use the `checkpoint` option to replication to reduce the number of local checkpoints.

Having lots of calls has an impact on performance, but will not create major issues

Please read the replies to your previous bug instead of opening another one

**Comment by tudordumitriu** [comment]
Hi @daleharvey 
First, sorry for opening another bug, but I saw these somehow as different issues, and I mentioned as well that we shall try they checkpoints solution.
But my concern this time was the large amounts of calls to the DB info and _changes
Or if you suggest that applying those fixes will actually fix the above as well..then pls accept my appologies.

Thanks
