### ISSUE TITLE
Firefox only: "Failed to open indexedDB, are you in private browsing mode?"

### ISSUE THREAD

**Issue by odungern** [pouchdb/pouchdb#7401]
### Issue
While the tutorial works fine with Chrome and Edge, it does not with FF. The console says "Failed to open indexedDB, are you in private browsing mode?" but this is not the case and we could not find any special setting. Any idea?

### Info
- Environment: browser
- Platform: FF 61.0.1 (64-Bit), on Windows 10
- Version: pouchdb-7.0.0.js
- Adapter: IndexedDB
- Server: None

### Reproduce
- Implement the "Getting started" (https://pouchdb.com/getting-started.html) without changes on local disk, without Server Connection
- run it with EDGE or Chrome: works nicely
- run it with FF ends with "Failed to open indexedDB, are you in private browsing mode?" ... but it was not started in a private mode, also checking the settings, there is no restriction (except for popups).
- trace:
	guardedConsole file:///C:/.../Javascript/pouchdb/pouchdb-7.0.0.js:2526:5
	init/req.onerror file:///C:/.../Javascript/pouchdb/pouchdb-7.0.0.js:8421:5

**Comment by daleharvey** [comment]
You need a server, as mentioned at the start of the tutorial https://pouchdb.com/getting-started.html#download. IndexedDB (and various other things) do not work well without a host

**Comment by odungern** [comment]
Thanks a lot - confirmed!
