### ISSUE TITLE
Error when requesting all_docs and their attachments in a binary blob if one doc doesn't exist in db

### ISSUE THREAD

**Issue by Blafy** [pouchdb/pouchdb#7403]
### Log

```
allDocs [{…}]
    0: attachments: true
        binary: true
        include_docs: true
        keys: (6) ["a_r", "a_z", "b_r", "b_z", "c_r", "c_z"]
        __proto__: Object
        length: 1
        __proto__: Array(0) 
TypeError: Cannot read property '_attachments' of undefined
    at readAttachmentsAsBlobOrBuffer (index-browser.es.js:8703)
    at Array.forEach (<anonymous>)
    at eval (index-browser.es.js:9435)
    at ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:4745)
    at ZoneDelegate.invoke (zone.js:387)
    at Zone.run (zone.js:138)
    at eval (zone.js:858)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4736)
```

### Issue
The above error occurs when requesting all_docs and their attachments in a binary blob, if one of the docs does not exist ( here ‘b_z’ is inexistant ).
Therefore the entire request fails, even if the other docs are present.
It looks like the `readAttachmentsAsBlobOrBuffer` function is assuming the document always exists.

### Reproduce
Send a request with the following parameters : 
```
attachments: true
binary: true
include_docs: true
keys: (2) ["thisDocExists", "thisOneDoesnt"]
```

### Possible fix

A possible fix might be to verify `doc` before `doc._attachments` in `pouchdb-adapter-http/src/index.js`, the way it was before this commit https://github.com/pouchdb/pouchdb/commit/f00b62e50abe0a0d51d778452e139b4465ef7767

```
-- var atts = doc._attachments;
++ var atts = doc && doc._attachments;
```

**Comment by Blafy** [comment]
Ok, working on it ! :)

**Comment by Blafy** [comment]
Ok, I'm working on it !

**Comment by daleharvey** [comment]
Fixed in ^, many thanks
