### ISSUE TITLE
Make the supported max ES version clear

### ISSUE THREAD

**Issue by SCdF** [pouchdb/pouchdb#7406]
It's not clear to me, as someone who wants to contribute to PouchDB, what the max ES version supported is. Ideally I want to avoid writing a bunch of code and then having it rejected because it's the wrong style.

From reading the code it looks like ES5 is our max, but the ESLint config is set to ES6.

So it could be that ESLint's config is wrong, or that the code is written in a way that is presumed to be performant / low level, or is just someone's personal style.

Can we confirm what our current max ES version we want to support is, and align the ESLInt file to be the same as this if it isn't already? Ideally if we want to support ES6 but *don't* want people to use arrow functions we can setup ESLint to error on that too.

**Comment by daleharvey** [comment]
We use es5 + modules, want to avoid having to transpile any code but we use modules for bundling. If there is a way to make the eslint config reflect that would be a nice change

**Comment by SCdF** [comment]
@daleharvey I had a play around, and ESLint actually ignores the `es` property of it's config file if you have modules selected, which is a shame. We could set this to ES5 instead of ES6 just to make it clearer that it's our intention, but eslint still won't complain if you use an arrow function or something. There is an ESLint ticket about it: https://github.com/eslint/eslint/issues/9687
