### ISSUE TITLE
Allow transformation of _rev in plugins

### ISSUE THREAD

**Issue by sreejithkrishnanr** [pouchdb/pouchdb#7408]
### Issue
I am trying to develop a plugin which can transparently encrypt / decrypt data in PouchDB.

Currently the best way to transform incoming documents is to wrap bulkDocs method. But the problem in here is that `_rev` is generated only after calling `_bulkDocs` method in adapter. This means the transformer method (encryptor) will not have `_rev` available for encryption.

`_id` and `_rev`, even though need not be encrypted, should be passed as associated data to encryption algorithm so that we can prevent tampering of data.

For example consider two revisions of an encrypted document
``` javascript
const doc1rev1 = {
  _id: 'confidential/doc1',
  _rev: '1-79724066dad4e81aa3bdb9fb78dfc446',
  field1: 'encrypted-confidential-field1-of-doc1-rev1',
  field2: 'encrypted-confidential-field2-of-doc1-rev1',
}

const doc1rev2 = {
  _id: 'confidential/doc1',
  _rev: '2-2ca98325fa224adab345cd14fff16d1d',
  field1: 'encrypted-confidential-field1-of-doc1-rev2',
  field2: 'encrypted-confidential-field2-of-doc1-rev2',
}
```

The data for revision 2 of the document (`doc1rev2`) can be tampered by replacing data from previous revision (`doc1rev1`). For example the below document is also perfectly valid for encryption algorithm because both the revisions are encrypted using the same key.

``` javascript
const doc1rev2 = {
  _id: 'confidential/doc1',
  _rev: '1-2ca98325fa224adab345cd14fff16d1d',
  field1: 'encrypted-confidential-field1-of-doc1-rev1',  // Tampered field using data from previous revision
  field2: 'encrypted-confidential-field2-of-doc1-rev2',
}
```

To prevent such kind of attacks, `_rev` of each document should be given to encryption algorithm along with the document as associated data. The algorithm will compute a hash using _rev and other data so that when the data is moved to other document with different `_rev` value, it can be detected.

**Comment by daleharvey** [comment]
> To prevent such kind of attacks, _rev of each document should be given to encryption 
> algorithm along with the document as associated data. The algorithm will compute a 
> hash using _rev and other data so that when the data is moved to other document 
> with different _rev value, it can be detected.

From https://github.com/pouchdb/pouchdb/pull/7136 we know use deterministic revs for database writes, also as long as a plugin is intercepting data before it is written, it should be able to specify its own revision data (with new_edits=false), I believe thats what https://github.com/calvinmetcalf/crypto-pouch does if I remember

Do those cover your needs, or can you describe a little more in terms of what changes you would need from pouchdb, cheers

**Comment by sreejithkrishnanr** [comment]
Thanks, `new_edits=false` is exactly what I need. 

Crypto pouch include only `_id` in associated data. Reference https://github.com/calvinmetcalf/crypto-pouch/blob/b068df024fb2028fb3933acf17dd4e63c3fad7de/index.js#L151. We need to include at least `_id`, `_rev` and `_deleted` in associated data to prevent tampering of data. Including `_id` and `_deleted` is direct. `new_edits` solves the problem of including `_rev`.

Thanks for support. Cheers.

**Comment by sreejithkrishnanr** [comment]
With `new_edits=false`, conflicts are allowed. Hence if the plugin intercepts `bulkDocs` call and adds `new_edits=false` option, we will get unexpected result when conflicts are present.

Is there any way to override this behaviour.
