### ISSUE TITLE
how to get size of pouchdb - client solution- cordova sqllite2

### ISSUE THREAD

**Issue by saber13812002** [pouchdb/pouchdb#7409]
### Issue
get size pouchdb 

### Info
- Environment: ionic3
- Platform: iOS/Android/Desktop (developers)
- Adapter: on mobile: cordova sqlite2, on dekstop: browser
- Server: CouchDB

### Reproduce
i cant use : this npm package https://github.com/pouchdb/pouchdb-size
in my ionic project

i need to get the size of pouchdb programming

**Comment by daleharvey** [comment]
PouchDB doesnt have an api to expose the size of the data stored, mostly as most environments dont have a way to access that, if you are using ionic / cordova etc then they may provide a way and you can access that directly
