### ISSUE TITLE
DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing

### ISSUE THREAD

**Issue by Celludriel** [pouchdb/pouchdb#7412]
### Issue
Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at openTransactionSafely (C:\Workspaces\CardgameDeckBuilder\node_modules\pouchdb-adapter-idb\lib\index.js:241:16)
    at PouchDB.idb_get [as _get] (C:\Workspaces\CardgameDeckBuilder\node_modules\pouchdb-adapter-idb\lib\index.js:1495:23)
    at PouchDB.<anonymous> (C:\Workspaces\CardgameDeckBuilder\node_modules\pouchdb-core\lib\index.js:759:15)
    at PouchDB.<anonymous> (C:\Workspaces\CardgameDeckBuilder\node_modules\pouchdb-utils\lib\index.js:178:21)
    at PouchDB.<anonymous> (C:\Workspaces\CardgameDeckBuilder\node_modules\argsarray\index.js:14:18)
    at C:\Workspaces\CardgameDeckBuilder\node_modules\pouchdb-utils\lib\index.js:117:21
    at new Promise (<anonymous>)
    at PouchDB.<anonymous> (C:\Workspaces\CardgameDeckBuilder\node_modules\pouchdb-utils\lib\index.js:104:19)
    at PouchDB.get (C:\Workspaces\CardgameDeckBuilder\node_modules\argsarray\index.js:14:18)
    at queryPromised (C:\Workspaces\CardgameDeckBuilder\node_modules\pouchdb-abstract-mapreduce\lib\index.js:970:17)
openTransactionSafely @ C:\Workspaces\CardgameDeckBuilder\node_modules\pouchdb-adapter-idb\lib\index.js:241
idb_get @ C:\Workspaces\CardgameDeckBuilder\node_modules\pouchdb-adapter-idb\lib\index.js:1495
(anonymous) @ C:\Workspaces\CardgameDeckBuilder\node_modules\pouchdb-core\lib\index.js:759
(anonymous) @ C:\Workspaces\CardgameDeckBuilder\node_modules\pouchdb-utils\lib\index.js:178
(anonymous) @ C:\Workspaces\CardgameDeckBuilder\node_modules\argsarray\index.js:14
(anonymous) @ C:\Workspaces\CardgameDeckBuilder\node_modules\pouchdb-utils\lib\index.js:117
(anonymous) @ C:\Workspaces\CardgameDeckBuilder\node_modules\pouchdb-utils\lib\index.js:104
(anonymous) @ C:\Workspaces\CardgameDeckBuilder\node_modules\argsarray\index.js:14
queryPromised @ C:\Workspaces\CardgameDeckBuilder\node_modules\pouchdb-abstract-mapreduce\lib\index.js:970
(anonymous) @ C:\Workspaces\CardgameDeckBuilder\node_modules\pouchdb-abstract-mapreduce\lib\index.js:1020
Promise rejected (async)
step @ operations.js:2
(anonymous) @ operations.js:2

At startup of my application I remove the previous database and reload it from a json file on disk.  However when I close my application and reopen it the above stacktrace pops up.  When I close it again and reopen the app it works as expected again.  This cycle continues with subsequent close and reopenings.  I'm not sure if its an RxDb bug or Pouch bug but the stacktrace is on pouch classes which is why I'm opening the issue here.

I have a branch with my application containing this behavior (it's still in prototyping stage), npm start should start it up, it's using electron-forge to launch.

all code is in src/state/pokemon/operations.js, I'm calling this by means of a saga if it would make a difference

### Info
- Environment: (Node.js/Electron/React)
- Platform: (Chrome)
- Adapter: (IndexedDB)
- Server: (PouchDB Server, RxDb)

### Reproduce
https://github.com/Celludriel/CardgameDeckBuilder/tree/feature/Create_Saga_For_Loading_In_The_Database

**Comment by Celludriel** [comment]
I forgot to write an await, closing the db is an async operation and without await this behavior was happening.

Entirely my fault , closing this issue

**Comment by daweedm** [comment]
If it could help someone in the future, this error can also happen when first you try to put a document that could not be cloned (for example, a complex object). 

Then you receive an error from IndexedDB telling you the clone could not be done but in the same time, it will close silently the database preventing you to not be able to do any further action on that database.

**Comment by SimonsXue** [comment]
I have the same question now.It occured when I clear site data and then db.put().

**Comment by tudordumitriu** [comment]
Hi there
We are getting the same error "InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing." and this is happening in when we are trying to get a document from the DB, and it happens with a disturbing frequency (once in a day under standard usage - let's say approximately few thousands db crud calls).
Also we saw it happening on Chrome Desktop and on iOS WkWebVIew Safari (cordova)
Since this is closed I will open a new one

**Comment by daflodedeing** [comment]
@Celludriel Do still have a minimal code snippet in order to reproduce the error? I have a similar issue and want to compare your previous problem to mine.

**Comment by dmorfav** [comment]
We are encountering an issue in our Ionic Angular application that uses PouchDB as its database. The problem mainly occurs on iOS devices running versions 17.x and 18.x.

Context:
After analyzing the reported cases, we have identified a consistent pattern:

The user interacts with the app normally.
The device enters a prolonged suspension state (several hours).
Upon resuming usage, the app fails when attempting to insert documents into the PouchDB database.

The following error is logged:

```typescript
Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
```
Specific Example:

- Last usage: January 16th at 4:00 PM.
- The user resumed work on January 17th at 10:30 AM, and the app started failing when interacting with PouchDB.

This behavior seems to align with the [comment in ticket #7954](https://github.com/pouchdb/pouchdb/issues/7954#issuecomment-563439333), which mentions that IndexedDB connections might automatically close on iOS devices after extended periods of inactivity.

Questions and Possible Solutions:

- Is there a way to implement an automatic reconnection mechanism to prevent these failures?
- Are there any best practices for managing IndexedDB connections in such scenarios?

We appreciate any guidance or suggestions to resolve this issue.
