### ISSUE TITLE
live replicating HTTP databases keeps something open and the process hangs

### ISSUE THREAD

**Issue by tyler-johnson** [pouchdb/pouchdb#7417]
After writing some replication tests for my application I began having some weird issues with the tests never completing. Jest kept giving me `Jest did not exit one second after the test run has completed.` After a lot of head scratching, I decided to work backwards and discovered this appears to be an issue with HTTP databases and live replication.

To demonstrate the issue, I have put to together a small project with the absolute minimum needed to reproduce: https://github.com/tyler-johnson/pouchdb-sync-issues

This comes with two js files `no-destroy.js` and `with-destroy.js`. Both these files are almost identical, they create a local in-memory database and a remote HTTP database and then sync them with each other. When the sync becomes "paused" (all caught up), I cancel the sync. 

`no-destroy.js` does not destroy the remote database and as a result this file will never exit. `with-destroy.js`, on the other hand, does destroy the remote database after canceling and this file exits immediately afterwards.

### Info
- Environment: Node.js
- Platform: Mac OS X
- Adapter: HTTP and LevelDB (memdown)
- Server: CouchDB

**Comment by tyler-johnson** [comment]
I decided to see if this was just PouchDB 7 with the problem. Turns out that it is, testing with PouchDB 6, both files exited properly.

https://github.com/tyler-johnson/pouchdb-sync-issues/tree/pouch-6

**Comment by tyler-johnson** [comment]
Alright so I've determined the issue. This is specific to the Changes API on Node.js. Since PouchDB now uses node-fetch to make requests, [the changes API relies on AbortController](https://github.com/pouchdb/pouchdb/blob/b666cfc51c375d8fbb49f8323c180bdbfbd9a5d5/packages/node_modules/pouchdb-adapter-http/src/index.js#L925) to cancel the longpoll request. BUT, node-fetch hasn't implemented the abort API (see https://github.com/bitinn/node-fetch/issues/95 and https://github.com/bitinn/node-fetch/pull/437) and right now PouchDB is using [a stub AbortController](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-fetch/src/fetch.js#L10) that does nothing.

So I'm not sure what to do until the patch lands on node-fetch. This seems like kind of a big issue given that this is effectively a memory leak in Node.js applications.

Pinging @daleharvey @nolanlawson for guidance.

**Comment by gkiko** [comment]
I downgraded to Pouchdb 6.4.3(indexeddb) which solved my issue. Previously I used Pouchdb 7.0.0(indexeddb or websql) and even `db.destroy()` didn't release browser connection.

**Comment by gaodeng** [comment]
any news on this?

**Comment by DonovanBoddy** [comment]
anyone have a fix for this yet? I am experiencing the same issue

**Comment by gaodeng** [comment]
It seems that this project has been abandoned, and basically no one is maintaining it.

**Comment by DonovanBoddy** [comment]
The project has over 12k stars, how can it be abandoned?

i see there is a pull request that may fix it #7806, are you able to review and merge it?
