### ISSUE TITLE
PouchDB _revs_diff call getting cancelled

### ISSUE THREAD

**Issue by mjosephd** [pouchdb/pouchdb#7424]
### Issue
We have a hybrid mobile application based on ionic, we are using pouchdb.

We noticed that we had some synchronization issues and upon inspection we noticed that the _revs_diff was getting cancelled by pouchdb. This gets timed out about approximately 10 seconds, when we send the same request by postman we get a response in about 15 seconds.

How can we avoid the request timeout for _revs_diff then.

### Info
- Environment: Ionic Hybrid
- Platform: Chrome
- Adapter: IndexedDB
- Server: Couchbase

![image](https://user-images.githubusercontent.com/422345/43952845-b9459eae-9cb4-11e8-928b-79234e68ac6c.png)

**Comment by christopher-howard** [comment]
I had the same issue and I think it boiled down to me using up all the remote server's disk space allowance. Came also with a one-off 'net::ERR_SPDY_PROTOCOL_ERROR' error and then just _revs_diff canceled repeatedly after.
