### ISSUE TITLE
[Question] - Read / Write Images under Android 4.4+ and iOS8+

### ISSUE THREAD

**Issue by angel1st** [pouchdb/pouchdb#7432]
### Issue
As stated above, this is actually a question rather than issue. I have read few startup guides which illustrate CRUD under Phonegap / Ionic. I didn't find however even one, which shows how images are handled. Looking into [PouchDB documentation](https://pouchdb.com/guides/attachments.html) it shouldn't be a problem. 
The tricky moment I found is - if I use PouchDB w/o [Cordova SQLite Plugin](https://github.com/litehelpers/Cordova-sqlite-storage), I guess the images will be processed flawlessly, **however**, the DB will suffer from [DB limits](https://pouchdb.com/faq.html#data_limits).
My question is - if I use SQLite Plugin as PouchDB `adapter` how the Attachments will be handled, since SQLite Plugin does not support BLOB writing?

Any shared example would be greatly appreciated!

### Info
- Environment: hybrid app
- Platform: iOS/Android
- Adapter: [Cordova SQLite Plugin](https://github.com/litehelpers/Cordova-sqlite-storage)
- Server: None, only local copy will be stored.

**Comment by karlwestin** [comment]
Yeah this is tricky. A few years ago i wrote an app that was using the SQLite plugin and using base64-encoded images. This worked ok but not great, we had like 10k docs with a 20kb jpg image each.

One thing i really recommend is to save the attachments on separate docs. This saves time when replicating changes to image meta data. 

I wish i had more detailed info but i could not find the source for this project any more.
