### ISSUE TITLE
PouchDB causes blank screen in Ionic app on iOS.

### ISSUE THREAD

**Issue by ambarth** [pouchdb/pouchdb#7434]
Hi, I am facing a problem when using pouchdb with an Ionic app on iOS. I'd be more than happy to hear your opinion what the problem could be.

### Issue
I can build and run the Ionic starter 'tabs' project fine on my iPhone 5S running iOS 10.2, but as soon as I try to create a pouch db it will only show a blank screen (after the splashscreen). I cannot see any useful error logs so unfortunately I have no idea what the problem is.

### Info
- Environment: hybrid mobile app (ionic) 
- Platform: iOS
- Adapter: default (indexeddb)
- Server: offline

### Reproduce
I have commited the Ionic starter 'tabs' project that you can create using `ionic start tabs` with an additional commit that simply calls `new PouchDB('whatever')` here:
https://github.com/ambarth/ionic_pouch_problem

I am building this project using `ionic cordova build ios --prod` and then run it on iPhone 5S/iOS 10.2.
I am using node `8.11.4` and ionic-cli `3.20.0`

I know that the same setup works with iPhone5 and iOS 10.3.3

**Comment by karlwestin** [comment]
It's possible you need to use another adapter than indexeddb for iOS < 10.3. Lots of changes happened in that version and before that, PouchDB w/ indexedDB wasn't not working well iOS. 
Did you try using the old websql adapter or something like that?

**Comment by thanhnh-infinity** [comment]
PouchDB adapter engine does not work perfectly in iOS 12 especially on 'idb'. You should try to 'websql'  instead. However, 'websql' will be deprecated soon so a little bit constraints to make sure it works well.
