### ISSUE TITLE
How to match on nested attribute (subfield)?

### ISSUE THREAD

**Issue by martinhbramwell** [pouchdb/pouchdb#7446]
This is a generic question, independent of platform.
I'm using the latest version from NPM: `"pouchdb-find": "^7.0.0"`

I have some records like this:

    {
      "_id": "Movement_1_000000180828112434013019",
      "data": {
        "type": "movement",
        "inOut": "out",
        "widgets": [
          100043
        ],
        "customer": 13019,
        "inventory": 12345
      }
    }

This query succeeds with selector:

    this.$pouch.find({
      selector: { _id: 'Movement_1_000000180828110654013019' },
    }).then((res) => {
      console.log('== Result ==');
      console.log(res);
    });

I get ZERO results with a selector like this ...

    selector: { 'data.type': 'movement' },

... and, with a selector ...

    selector: { data: { type: 'movement' } },

... I get the error `Uncaught (in promise) Error: unknown operator "type" - should be one of $eq, $lte, $lt, $gt, $gte, $exists, $ne, $in, $nin, $size, $mod, $regex, $elemMatch, $type, $allMatch or $all`

Is matching nested attributes not possible?

Following [the note at the end of the ReadMe section, Examples](https://www.npmjs.com/package/pouchdb-find#examples), I tried to "refer to [Cloudant's _find documentation](https://docs.cloudant.com/api.html#finding-documents-using-an-index)", but **that link is dead.** [This page](https://console.bluemix.net/docs/services/Cloudant/api/cloudant_query.html#subfields) seems to be equivalent, and implies that both the methods I tried ought to work.

**Comment by daleharvey** [comment]
It looks like this is something broken and was being worked on in https://github.com/pouchdb/pouchdb/pull/7384

**Comment by martinhbramwell** [comment]
I am a bit mystified.  The code changes @ultravail submitted, unsuccessfully, are there in the master branch verbatim. So it appears someone else submitted a PR that includes his fix.

However, if it's part of the master branch, my problem must have a different cause, since I am using 7.0.0. and still cannot use subfield selectors. Or am I missing something here?

**Comment by martinhbramwell** [comment]
@daleharvey -- I asked a further question in the PR 7384, but no one answers.  I'm beginning to worry that  PouchDB is slowly being abandoned.  Is that what's happening?
