### ISSUE TITLE
Pouchdb-find ignores a selector

### ISSUE THREAD

**Issue by juancampa** [pouchdb/pouchdb#7451]
### Issue

I started using `pouchdb-find` and found some weird behavior with `find`. I expected this selector to work:

```javascript
  const result = await db.find({
    selector: {
      $and: [{ num: { $gt: 2 }}],
      type: "thing"
    }
  });
```

But `type: "thing"` is completely ignored. Are you not supposed to use other selectors when using `$and`/`$or`?

### Info
- Environment: Node 10 and browser
- Platform: Chrome
- Adapter: default (IndexedDB)
- Server: N/A

### Reproduce
Here's a live, minimal repro:
https://codesandbox.io/s/mz1194yzlx

### Note
I understand there's no use in `$and` with just one operand, but I would expect this to work. In my specific use-case selectors are auto-generated and sometimes they end up looking like this

**Comment by dravenk** [comment]
I had a similar problem and then added "" to fix it. "$and"
