### ISSUE TITLE
[Question] Does bulkGet() have the same guarantee as bulkDocs()?

### ISSUE THREAD

**Issue by rafamel** [pouchdb/pouchdb#7453]
### Issue
From the PouchDB docs:

> The best way to intercept all updates to a PouchDB database is to override the bulkDocs() method. All changes to PouchDB documents ultimately pass through the bulkDocs() method. For example, a call to put() will become a bulkDocs() call with a “batch” of one document.

Do we have such guarantee for read operations - so we could also intercept all reads by overriding a single method? If so, it would be great to have it documented.

**Comment by daleharvey** [comment]
Nope, its something I would like to happen but not yet, all the different methods of reading data are wildly different in terms of the options and semantics but the plan is to expand the capability of pouchdb-find to consume the other methods
