### ISSUE TITLE
Headers not working as expected in v7.0.0

### ISSUE THREAD

**Issue by mahnuh** [pouchdb/pouchdb#7454]
### Issue
I am trying to add a custom access token using fetch like explained in the docs:
````
    this.db = new PouchDB('foodb');
    const remote = new PouchDB('http://foo-proxy.local/foodb', {
      fetch: (url, opts) => {
        opts.headers.set('X-Custom-Token', 'foo');
        return PouchDB.fetch(url, opts);
      }
    });

    this.sync = PouchDB.sync('foodb', remote);
````
Unfortunately the X-Custom-Token is missing in the request and CouchDB responds with 405 (Method Not Allowed):
```
{ connection: 'upgrade',
  host: 'bdgt-proxy.hacking',
  'access-control-request-method': 'GET',
  origin: 'http://localhost:8100',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36',
  dnt: '1',
  'access-control-request-headers': 'content-type,x-custom-token',
  accept: '*/*',
  referer: 'http://localhost:8100/',
  'accept-encoding': 'gzip, deflate',
  'accept-language': 'de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7' }
```
When using Authorization instead of X-Custom-Token, the header is present most of the time, but not always.

The expected behaviour would be the custom header to be present at all times.

### Info
- Environment: browser
- Platform: Chrome on macOS
- Adapter: IndexedDB
- Server: CouchDB 2.2.0

**Comment by mahnuh** [comment]
Just realised that the Authorization header is only missing on OPTIONS requests, which is expected.

**Comment by daleharvey** [comment]
Cool cheers

**Comment by mahnuh** [comment]
@daleharvey The other issue persists, only the Authorization header is working.
