### ISSUE TITLE
Nested $and not working in pouchdb-find.

### ISSUE THREAD

**Issue by Prabuganesan** [pouchdb/pouchdb#7458]
### Issue
Nested $and not working in pouchdb-find.
### Info
- Using pouchdb-find 6.3.4

### Reproduce
I have call this query in pouchdb but not working. But this query working in couchdb(2.2.0) mango.

```
let option = { "selector": {
      "$or": [
        {
           "data.city":{ "$eq": "madurai"}
        },{
          "$and": [
            {
               "data.city":{ "$eq": "chennai"}
            },
            {
               "data.state": {"$eq":"TN"}
            }
         ]    
        }
      ]
    }
    }

this.db.find(option).then(result => {
        console.log(result)
    }).catch(err=>{
        console.log("err" + err)
    })
```

It was throw following error

**unknown operator "0" - should be one of $eq, $lte, $lt, $gt, $gte, $exists, $ne, $in, $nin, $size, $mod, $regex, $elemMatch, $type, $allMatch or $all**

**Comment by BarboraNovotna** [comment]
Hi, I would like to work on this issue, is the issue still relevant?

**Comment by Prabuganesan** [comment]
Still available this issue. We have managed like this.

```
let option = { "selector": {
      "$or": [
        {
           "data.city":{ "$eq": "madurai"}
        },{
               "data.city":{ "$eq": "chennai"},
               "data.state": {"$eq":"TN"}
        }
      ]
    }
    }
```

**Comment by dfulgham** [comment]
See pull request #7791
