### ISSUE TITLE
PouchDB .find() only finding changes after replication

### ISSUE THREAD

**Issue by jwheat** [pouchdb/pouchdb#7462]
### Issue
I'm using React Native, and I am preloading a local pouchDB database on first run using the dump file method outlined here - https://pouchdb.com/2016/04/28/prebuilt-databases-with-pouchdb.html  After the file is loaded, I create an index, spin through the database with a .find() and add the records to state for each day (its a conference application).  My UI generates a FlatList of records based on that state array for each day.

I have a Refresh button on my UI and when tapped it performs a "replicate-from" pulling down any changes made on the server's CouchDB from a web admin screen.  Dumping the database to the console after this happens, I can see the changes have been made and the updates are in the local pouchDB.

I then update the UI with the changes finding the index in the FlatList and updating without re-rendering the list, and all seems well.

I then close the app.  When opening the app again, it detects the dump file has been previously loaded, it skips that part, creates an index and does a find to populate the UI.  However, it only displays the changed document it pulled down after the refresh.  If I dump the database to the console, it displays all the documents with the updated changes I saw before the restart.

The result is viewing a list of say 10 records, clicking refresh, viewing the changes and everything is fine.  If I close / open the app, only 1 record displays.  Dumping the database to the console at that time shows all the documents are still present.

It seems that the .find() after a replication is limited to finding only the new record(s)

### Info
- Environment: React Native
- Platform: iOS
- Adapter: asyncStorage
- Server: CouchDB

Here are some versions of things if that will help.
    "pouchdb-find": "^7.0.0",
    "pouchdb-load": "^1.4.6",
    "pouchdb-react-native": "^6.4.1",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-navigation": "^2.11.2"

### Reproduce
Here's a gist for my Home.js where everything I've explained happens.  I apologize for all the console.log entries, they'll be removed once I figure out what is happening.

https://gist.github.com/jwheat/54c1a8c8132961755d2b9bc9185c01ad

**Comment by jwheat** [comment]
I have a workaround for now - I changed my $eq to $in and that works.

          db.find({
            selector: {
              $and: [
                { type: { $exists: true } },
                { type: { $in: ["sessions"] } },
                { start_date: { $gt: true } },
                { start_date: { $in: ["2018-10-21"] } }
              ]
            }
          })

**Comment by mintproduct** [comment]
I've encountered the same issue in my project.
The local adapter I using is SQLiteAdapter instead of @jwheat 's  asyncStorage.

And this issue perhaps is not connected to replication. After turning down the replication mechanism, this issue still existed.
