### ISSUE TITLE
Implement partial_filter_selector.

### ISSUE THREAD

**Issue by garbados** [pouchdb/pouchdb#7467]
### Issue

The index attribute `partial_filter_selector`, which CouchDB uses to implement [partial indexes](http://docs.couchdb.org/en/stable/api/database/find.html#find-partial-indexes) is not present in PouchDB-Find. Indexes created with this attribute do not apply this selector to the index prior to querying.

### Info
- Environment: Node.js v10.7.0
- Platform: Ubuntu 18.04.1 LTS
- Adapter: LevelDB
- Server: N/A

### Reproduce
Consider this index:

```javascript
await this.createIndex({
  index: {
    partial_filter_selector: {
      _id: {
        $regex: '^bookmark:.+$'
      }
    },
    fields: ['tags']
  },
  ddoc: 'bookmark-tag-search'
})
```

Queries against this index, forced using the `ddoc` query attribute, will return results which do not pass the partial filter selector.

**Comment by garbados** [comment]
Here is a script for reproducing the error:

```javascript
const PouchDB = require('pouchdb')
PouchDB.plugin(require('pouchdb-find'))

async function test () {
  const db = new PouchDB('.test')
  await db.createIndex({
    index: {
      partial_filter_selector: {
        _id: {
          $regex: '^bookmark:.+$'
        }
      },
      fields: ['_id']
    },
    ddoc: 'bookmark-tag-search'
  })
  await db.bulkDocs([{
    _id: 'bookmark:1',
  }, {
    _id: 'list:1',
  }])
  const docs = await db.find({
    selector: {
      _id: {
        $gt: null
      }
    },
    use_index: 'bookmark-tag-search'
  })
  // should only contain the one bookmark
  return docs.length === 1
}

test().then((ok) => {
  console.log(ok)
}).catch((error) => {
  console.error(error)
})
```

**Comment by detroitenglish** [comment]
![image](https://user-images.githubusercontent.com/18492423/45612459-43fd4300-ba63-11e8-9a59-8ebadc61887f.png)

**Comment by garbados** [comment]
I'm sorry, I'm not sure I understand. That image indicates, "all of the fields in a candidate index must exist in a query's selector." In the example script, only `_id` is specified in the selector, and it is the only field which is indexed or used by the partial_filter_selector.

Can you explain what you mean?

**Comment by garrensmith** [comment]
@garbados it is not working purely because this hasn't been implemented in PouchDB yet.

**Comment by ptitjes** [comment]
Nope stale bot !

**Comment by garrensmith** [comment]
I was thinking about this today. Could you add some performance tests for this. It would be nice to prove that partial filters would be significantly better for a query.


________________________________

**Comment by ptitjes** [comment]
@garrensmith Good idea! I will think about how to test it.

**Comment by nicolas-albert** [comment]
Hi here !
I use server side Mango Queries with CouchDB. The **partial_filter_selector** is mandatory to have better performances.
I want to use the same algorithm client side, using PouchDB.
The **partial_filter_selector** allow to split a huge set of documents to sub-set of documents (separate type of documents). With this, the **selector** part of the query is done on the sub-set instead of the whole database.

Do you think about to plan this feature again ?

**Comment by garbados** [comment]
Yeah this issue should *not* be closed. An implementation [here](https://github.com/pouchdb/pouchdb/pull/8277) is still in review.
