### ISSUE TITLE
Selectors using `$elemMatch` are rejected even when valid.

### ISSUE THREAD

**Issue by garbados** [pouchdb/pouchdb#7468]
### Issue

Selectors using the `$elemMatch` operator are rejected for not being a 'logical operator'. I say this because I traced this rejection decision to [this line](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-find/src/adapters/local/find/query-planner.js#L132). Adding `$elemMatch` to this array causes PouchDB to use the appropriate index, but leads to other problems such as returning irrelevant results.

### Info
- Environment: Node.js v10.7.0
- Platform: Ubuntu 18.04.1 LTS
- Adapter: LevelDB
- Server: N/A

### Reproduce

Here is a script that reproduces this error:

```javascript
const PouchDB = require('pouchdb')
PouchDB.plugin(require('pouchdb-find'))

const db = new PouchDB('.test')

async function test () {
  await db.createIndex({
    index: {
      fields: ['tags']
    },
    ddoc: 'tag-search'
  })
  await db.bulkDocs([{
    _id: 'bookmark:1',
    tags: ['hello', 'world']
  }, {
    _id: 'list:1',
    tags: ['uh', 'oh']
  }])
  const docs = await db.find({
    selector: {
      tags: {
        $elemMatch: {
          $in: ['hello']
        }
      }
    },
    use_index: 'tag-search'
  })
  // should only contain the one bookmark
  return docs.length === 1
}

test().then((ok) => {
  console.log(ok)
}).catch((error) => {
  console.error(error)
}).then(() => {
  return db.destroy()
})
```

**Comment by detroitenglish** [comment]
Add `_id` to the indexed fields, include `_id: { $gt: null }` in your selector, and return the `docs` property from the query:
```javascript
async function test() {
  await db.createIndex({
    index: {
      fields: ['_id', 'tags'],
    },
    ddoc: 'tag-search',
  })
  await db.bulkDocs([
    {
      _id: 'bookmark:1',
      tags: ['hello', 'world'],
    },
    {
      _id: 'list:1',
      tags: ['uh', 'oh'],
    },
  ])
  const { docs } = await db.find({
    selector: {
      _id: { $gt: null },
      tags: {
        $elemMatch: {
          $in: ['hello'],
        },
      },
    },
    use_index: 'tag-search',
  })
  // should only contain the one bookmark
  return docs.length === 1
}
```

Check out [When JSON Syntax Gets Tricky](https://developer.ibm.com/dwblog/2015/mango-json-vs-text-indexes/) for an explanation as to why the `_id` field is required for the index and query selector 👍

**Comment by garbados** [comment]
That works! Thanks for your help. Closing the issue...
