### ISSUE TITLE
Update @types for pouchdb-core to support new fetch API

### ISSUE THREAD

**Issue by stcleezy** [pouchdb/pouchdb#7475]
### Issue
Types definition is still on 6.4 and doesn't support some new 7.0 changes, including fetch
https://www.npmjs.com/package/@types/pouchdb-core

**Comment by garrensmith** [comment]
We don’t maintain the type definitions. They are I the official types repo. If you are able to update them that would be amazing.

________________________________

**Comment by daleharvey** [comment]
Yup, closing out, cheers
