### ISSUE TITLE
App User Data Keeps Growing

### ISSUE THREAD

**Issue by ganeshmogare** [pouchdb/pouchdb#7478]
### Issue
Hi, 
In my cordova app , I'm replicating data from remote couchdb to local pouchdb . When i launch the app for the first time it works fine , but when close the app and relaunch it , app's user data grows to 2X(doubles) , this size grows only for the second launch . Please Help me out
I'm Using : Server - couchdb , local - pouchdb , adapter : cordova-sqlite , ionic , cordova 

### Info
- Environment: Cordova
- Platform: Android
- Adapter: Cordova-sqlite
- Server: PouchDB/CouchDB

### Reproduce
1.Build an cordova android app , in which create pouchdb instances of localdb (target) and remotedb(source) , and replicate from remotedb to couchdb 
2. Open application , let it sync completely 
3. Once it syncs  completely close the application and reopen it again 
4. Now you can see the app data size keep increasing (almost  2x of size)

**Comment by mnewmedia** [comment]
Can you provide a reproducable sample?
