### ISSUE TITLE
Replicate to Remote and Pull from Remote Very Very Slow Sync gateway /Couchbase - Pouchdb 7.0.0

### ISSUE THREAD

**Issue by vjijardar** [pouchdb/pouchdb#7485]
### Issue
**CouchbaseLite Take milli-Seconds** 
**PouchDB Take more 30sec or a Minute or Failed to push**

**Note: Tested When more 5K doc on Couchbase Bucket**

Replication to Localdb to Remote DB is very very Slow when more than 5 Sync gateway. As compare to Couchbase lite Pouchdb take more  >40sec sometime and sometimes it's failed to replicate the document on the server.

**this.database = new PouchDB("scheduler",{auto_compaction: true});**
 **private remoteDatabase = new PouchDB(AppSettings.SYNC_ENDPOINT+'schedular',{cache : false})**

Sync From Remote
It's Also slow.
startup the application is fast after sometime its take delay or failed ( Reload the page its worked)

**this.database.replicate.from(this.remoteDatabase, { 
         live: true, 
         retry: true, 
         since: 'now',
         filter: "sync_gateway/bychannel",
         query_params: {"channels": "id"},
        }).**

Replicate Local to Remote

**this.database.replicate.to(this.remoteDatabase,{
              live: true,
              retry: true
           });**

When After Put the Localdb after calling the replicate function the data never post on the server immediately its take more 40sec,1min and sometimes its failed why don't no.

### Info
- Environment: (Node.js 8.9.4/Angular 5.x.x)
- Platform: (Chrome)
- Adapter: (IndexedDB.)
- Server: (Couchbase 5.x.x/Sync Gateway 2.x.x)
- Pouchdb: (7.0.0)
- Cloud Server : (AWS Couchbase server 32GB / Couchbase Node server 32GB / Sync gateway 16GB )

**Comment by daleharvey** [comment]
We dont support couchbase - https://github.com/pouchdb/pouchdb/issues/5820
