### ISSUE TITLE
No channel option for replicate/sync to Couchbase/Sync Gateway

### ISSUE THREAD

**Issue by lvbesien** [pouchdb/pouchdb#7487]
### Issue
There is no option to replicate/sync by channel to couchbase/sync gateway. 

See[ sync gateway documentation
](https://docs.couchbase.com/sync-gateway/2.1/rest-api.html#/database/get__db___changes)
### Info
- Environment: Any
- Platform: Any
- Adapter: Any
- Server: Couchbase

### Reproduce
N/A

**Comment by daleharvey** [comment]
Sorry we don't support couchbase, or upcoming to make that clearer

**Comment by asiFarran** [comment]
Check out this [easy recipe](https://medium.com/@asi_73084/pouchdb-syncgateway-for-saas-web-apps-the-missing-guide-22e33e148277) to get this working.
