### ISSUE TITLE
[FR] Implement selector on server

### ISSUE THREAD

**Issue by rafamel** [pouchdb/pouchdb#7489]
### Issue
When using PouchDB replication with a `pouchdb-server` instance, if a selector is used ([`options.selector`](https://pouchdb.com/api.html#replication)), replication will fail.

Particularly, PouchDB will be trying to access the url `protocol://host/db/_changes?style=all_docs&filter=_selector&since=0&limit=100`, which responds with `{"error":"not_found","reason":"missing"}`.

I'm assuming this is just not implemented in `pouchdb-server`, as it all works as expected when replicating to a CouchDB 2 instance. Implementation of `selector` would be truly helpful as there are several PouchDB dependent libraries that use `selector` ([1](https://github.com/pubkey/rxdb/issues/758), [2](https://github.com/rafamel/rxdb-utils/issues/2)), which makes them not compatible with PouchDB server.

### Info
- Environment: Node.js
- Server: PouchDB Server

**Comment by gaodeng** [comment]
+1 same issue here .

**Comment by motin** [comment]
+1

**Comment by dionysiusmarquis** [comment]
+1 related: https://github.com/pouchdb/pouchdb-server/issues/266

**Comment by bdombro** [comment]
+1. Woudl this be easy since there's already a pouchdb find plugin?
