### ISSUE TITLE
[FR] Add conflict fetching for pouchdb-find

### ISSUE THREAD

**Issue by rafamel** [pouchdb/pouchdb#7490]
### Issue
`pouchdb-find` doesn't currently allow to define `{ conflicts: true }` as an option, like we would with `get()` and `bulkDocs()`. Doing `db.explain()` will always return the following regardles of whether the query to `db.find()` had a `conflicts`, `opts.conflicts`, or `options.conflicts` key as `true`:

```javascript
({
  // ....
  opts: {
    // ...
    conflicts: false
    // ....
  }
  // ....
})
```

### Info
- Environment: Browser
- Platform: Chrome
- Adapter: Any
- Server: PouchDB

**Comment by nspaeth** [comment]
[This line](https://github.com/pouchdb/pouchdb/blob/7a0f56e57126dd27edc9fa0f2a99caccb7e10d01/packages/node_modules/pouchdb-find/src/adapters/local/find/index.js#L179) looks responsible.

**Comment by nspaeth** [comment]
Also see this issue: [Feature request - Option to Include Conflicts for PouchDB.find](https://github.com/pouchdb/pouchdb/issues/6996).
