### ISSUE TITLE
PouchDB - CouchDB replication passing through a Nodejs proxy send all the documents and not just the modified ones

### ISSUE THREAD

**Issue by alexbonaffini** [pouchdb/pouchdb#7497]
### Issue
I have an Ionic (version 1) application that run PouchDB and communicate with a remote CouchDB with the replication.

Between the two there is a Nodejs proxy that check the document and do some additional operations before store it remotely, so I can see all the documents in upload passing through it.

Since a few weeks I se pass not only the modified documents but all the document stored in the local db of the app, even when the modified document is only one. All the document not modified pass with the same revision in the remote db so they do not involve real modifications but they obviously burden and slow down the proxy.

### Info
- Environment: Node.js / browser / hybrid app Ionic 1
- Platform:Chrome / iOS / Android
- Server: CouchDB

### Reproduce
This problem occurs only from real devices, while when I try to run the application simulating it from the browser does not happen.

**Comment by mnewmedia** [comment]
Does not sound like a pouchdb Issue to me, more like a bug in your system somewhere. If you can make a small reproducible example, we may can look into it.
