### ISSUE TITLE
Dynamics of live replication (documentation request, Android)

### ISSUE THREAD

**Issue by acutetech** [pouchdb/pouchdb#7501]
I observe that the replication latency (time between a document changing on the server and on my Android phone) varies depending on the state of my phone and its app. If the app is running in the foreground latency is low (a small number of seconds max) but if in the background it is much slower and unresponsive.

Do you have anything published on this topic, to set expectations and to make suggestions for developers?

How does your code work under the hood, and is it affected by changes to background processing in Android 8/9? For context see this for limitation on [background detection of BLE Beacons](http://www.davidgyoungtech.com/2017/08/07/beacon-detection-with-android-8). Where does Doze mode fit in? Should we use particular versions of PouchDB or Cordova?

 Finally, any pointers for reducing latency? For example, should I look at Firebase Cloud Messaging or similar?

**Comment by daleharvey** [comment]
Hey, sorry for not getting to this, but basically we do not do anything special to handle background processing on android, we do a long polling request @ https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-http/src/index.js#L815, if the page is backgrounded we dont do anything until we are resumed at which point things should start happening immediately (if they dont, restarting replication should certainly work)

Dealing with androids app lifecycle is very much out of the scope of pouchdb, once you use android to get the page resumed pouchdb should do things straight away
