### ISSUE TITLE
PouchDB with LevelDB database

### ISSUE THREAD

**Issue by cheranrj** [pouchdb/pouchdb#7508]
Hi, how to setup LevelDB adapter with  PouchDB instead of IndexedDB because i want to store offline data about 1GB approximately in Electron .exe file, so i go for LevelDB adapter but i dont know how to start with LevelDB after seen this note : ( https://pouchdb.com/adapters.html#pouchdb_in_node_js ) .
Can anybody help to setup LevelDB database

Im using CouchDB as remote Database if the internet is available. Local Database as LevelDB for Windows Desktop application using Electron and Node.js. Written in Vuex with Quasar framework

**Comment by mnewmedia** [comment]
To use pouchdb in nodejs install this package:
```npm install pouchdb-node```

To create/open the database with pouchdb write this line:
```var pouch = new PouchDB('./path/to/db');```

**Comment by cheranrj** [comment]
@mnewmedia Thanks. I installed the **pouchdb-node** that  tried the ` `var pouch = new PouchDB('./path/to/db')` 
Im getting the error below in the console:

> Uncaught TypeError: exists is not a function
    at Function.getRoot (bindings.js?f3ff:158)
    at bindings (bindings.js?f3ff:60)
    at eval (leveldown.js?42be:4)
    at Object../node_modules/level/node_modules/leveldown/leveldown.js (app.js:2421)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (level.js?ad23:1)
    at Object../node_modules/level/level.js (app.js:2400)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)

My code:
`import pouch from 'pouchdb-node'`
`var db = new pouch('./static/usersdb');`

**Comment by mnewmedia** [comment]
I think this has to do with your build step (maybe webpack).

But if you have problem using it with electron there is:
https://github.com/nolanlawson/pouchdb-electron
https://github.com/nolanlawson/hello-electron-with-pouchdb
