### ISSUE TITLE
Is it possible to have local design documents?

### ISSUE THREAD

**Issue by tudordumitriu** [pouchdb/pouchdb#7509]
This is a generic question, because we would totally benefit out of having some client design docs - views, that don't get replicated to the server (and add inherent performance penalties) because they are only used / needed on the client.

**Comment by karlwestin** [comment]
Did you look into using [filtered replication](https://pouchdb.com/api.html#filtered-replication) for this?
It's probably easiest to not use `db.sync` but to have one (unfiltered) replication up from the server and one (filtered) down from client to server.

Hope it helps :)

**Comment by daleharvey** [comment]
Yeh filtered replication is the way to do this right now, I would like to see `design_docs: false` as an option we can pass to the replicator but doesnt currently exist
