### ISSUE TITLE
pouchdb-adapter-node-websql is not working

### ISSUE THREAD

**Issue by cheranrj** [pouchdb/pouchdb#7520]
Hi.. In my Project i want to use **pouchdb-adapter-node-websql** for [Prebuilt databases with PouchDB](https://pouchdb.com/2016/04/28/prebuilt-databases-with-pouchdb.html) to make sqlite DB file while installing with Electron .exe file.

After npm install pouchdb-adapter-node-websql , 

`import pouchdb from 'pouchdb' `
`import pouchdba from 'pouchdb-adapter-node-websql' `

It says :
This dependency was not found:

* websql in ./node_modules/pouchdb-adapter-node-websql/lib/index.es.js

To install it, you can run: npm install --save websql

But In my node_modules & package.json the websql dependency is there.

### Info
- Environment: Node.js,Electron,Vuejs
- Platform: Windows , IOS
- Adapter: pouchdb-adapter-node-websql

**Comment by daleharvey** [comment]
`pouchdb-adapter-node-websql` has been removed from pouchdb core, if you want to use it you would need to revive the code and publish it. Would be happy to have this done under - https://github.com/pouchdb-community

**Comment by sadra-barikbin** [comment]
Hi, I'm having the same problem now.
@daleharvey  I did'nt understand what you mean? What should I do to fix the issue?
