### ISSUE TITLE
UpdateHandlers of couchdb

### ISSUE THREAD

**Issue by bishal1994** [pouchdb/pouchdb#7524]
### Issue
Write the description of the issue here

### Info
- Environment: Hybrid App
- Platform: Android
- Adapter: IndexedDB
- Server: CouchDB&PouchDB Server

Hello , I have been trying to implement the design document for update handler in couchdb 

      {
         "_id": "_design/secure",
         "_rev": "27-d7fbdd8ea925df711d2d4329dbb032c2",
         "language": "javascript",
         "updates": {
         "update": "function(doc,req){if(!doc)return[null,'Doc doesnt exists! Please Create a new 
               document']doc.secured = doc.secured == false?true:false;return [doc,'Ok,Secured']}"
                }
       }

And I want to invoke it to modifiy my docs once it is stored in couchdb . The docs will be syncing from the  pouchdb that is running in a cordova app background . This is what I have tried to implement including POUCHDB-UPDATE plugin.

        var argv = require('minimist')(process.argv.slice(2));

        var logLocation=argv.pouchlog;
        var controlFileHandler=argv.controlfh;

        var express = require('express')
        var app = express()
        var PouchDB = require('pouchdb').plugin('pouchdb-update');
        let InMemPouchDB = PouchDB.defaults({db: require("memdown"), migrate: false})
        app.use('', require('express-pouchdb')(InMemPouchDB, 
        {mode:'minimumForPouchDB',logPath:logLocation}))
        app.listen(3005)
        var db = new InMemPouchDB('todos',{revs_limits: 1});
        var remoteCouch = 'http://127.0.0.1:5984/todos';
        db.changes({live: true}).on('change', function(){
        db.sync(remoteCouch,{live:true,retry:true}).on('active',function(){
        db.update('_design/secure', function(res){
        console.log("Data Secured");
        console.log(res);
              })
         })

But its not working I am having problem to invoke the updates function on the couchdb, Please can you guys help me in the implementation . The aim is to trigger the update_handler function only when the data is stored in the Couchdb ( and indicates the data syncing between multiple pouchdb is not secure unless it is stored in the couchdb ). Please help me solve the issue or if there is any simpler way to achieve this, any help will be deeply appreciated.

**Comment by daleharvey** [comment]
This is the wrong repo, need to file against https://github.com/pouchdb/pouchdb-server, thanks
