### ISSUE TITLE
pouchdb-adapter-leveldb showing error in leveldown.js

### ISSUE THREAD

**Issue by cheranrj** [pouchdb/pouchdb#7528]
Hi Im trying to use **pouchdb-adapter-leveldb** to create local DB file for synch & store  cloud data in offline in electron with Node.js & Vuejs . After installing pouchdb-adapter-leveldb am importing pouchDB to use levelDB adapter.
       I have used also **npm install pouchdb-node**  to set levelDB  adapter but it shows the same error in below.

### Info
- Environment:  Node.js,Electron,Vuejs,Webpack
- Platform: Windows , IOS
- Adapter: pouchdb-adapter-node-websql,LevelDB

**My Code:**
`import pouchdb from 'pouchdb'`
`pouchdb.plugin(require('pouchdb-adapter-leveldb'));`
`var db = new PouchDB('mydb', {`
`adapter: 'leveldb'`
`});`
`console.log(db.adapter);`

**Im getting the error below in the console:**

> Uncaught TypeError: exists is not a function
> at Function.getRoot (bindings.js?f3ff:158)
> at bindings (bindings.js?f3ff:60)
> at eval (leveldown.js?42be:4)
> at Object../node_modules/level/node_modules/leveldown/leveldown.js (app.js:2421)
> at webpack_require (app.js:679)
> at fn (app.js:89)
> at eval (level.js?ad23:1)
> at Object../node_modules/level/level.js (app.js:2400)
> at webpack_require (app.js:679)
> at fn (app.js:89)

Im using this pouchdb cdn link: https://cdn.jsdelivr.net/npm/pouchdb@7.0.0/dist/pouchdb.min.js

can anybody help to get this thing clear?

**Comment by daleharvey** [comment]
Closing as dupe
