### ISSUE TITLE
Sync stopped while see the print preview.

### ISSUE THREAD

**Issue by Prabuganesan** [pouchdb/pouchdb#7541]
### Issue
Sync stopped while see the print preview.
### Info
- Environment: (browser)
- Platform: (Chrome)
- Adapter: (IndexedDB)
- Server: (CouchDB)

### Reproduce
When I have launch print preview then pouchdb  sync stopped. 
In my app I have created sales order. Every order I save Header document and Line documents in pouchdb. After save Line docs I invoke print receipt. In this case pouchdb and couchdb sync stopped. When I close the print preview screen then sync started.

**Comment by karlwestin** [comment]
Wow this sounds tricky, i can understand this is really annoying
Can you set up a test case to try, like in JSBin or similar?
Do you see if other requests keep going while the print preview is up?
Also, hows the behavior in other browsers?

**Comment by karlwestin** [comment]
When i test promise behavior in different browsers i see firefox continue resolving promises while the print preview is open, and chrome pauses resolving promises. Our http calls are using promises, so in case you're seeing sync continuing in Firefox, while pausing in Chrome, this would be very hard to work around.

Here's a test page with promise resolution: https://jsbin.com/gohimiboxa/edit?html,js,output, if you open the console, you can see promises keeping going in Firefox, while they pause in Chrome when you open the Print Preview Dialog.

**Comment by Prabuganesan** [comment]
I have tested in safari and chrome. Both browser have same issue.

**Comment by karlwestin** [comment]
ok cool
let me know when you've had time to look at the other questions :)

**Comment by Prabuganesan** [comment]
In network panel _changes and _bulk_get api's in pending state while print preview showing. After close print preview screen _changes and _bulk_get api's call finished. And also some network calls done there. After all this finished I have see my data in couchdb.

**Comment by Prabuganesan** [comment]
OMG.This url not pauses for me when i open print dialog. I have tested in chrome (70.0.3538.110 (Official Build) (64-bit)) and safari (12.0 (14606.1.36.1.9)). I don't have firefox.

**Comment by daleharvey** [comment]
are you calling `window.print()`? thats a sync modal dialog and will block all requests, it looks like this may apply to pressing ctrl+p as well, I cant see an async api for it

https://stackoverflow.com/questions/40972000/print-preview-freezes-javascript-in-chrome

**Comment by Prabuganesan** [comment]
No I am using **printjs** library.

**Comment by daleharvey** [comment]
Yeh even if you arent calling it directly it sounds like printjs will call it, there doesnt seem to be an async way to print a page (which makes a little sense, dont want to page to change maybe?) but fairly certain there is nothing we can do here

**Comment by daleharvey** [comment]
So yeh, print preview is a modal dialog (alert / confirm are the same), nothing we can do
