### ISSUE TITLE
Event for successful sync connection made (before changes)

### ISSUE THREAD

**Issue by adueck** [pouchdb/pouchdb#7542]
It would be really nice to have **an event for `PouchDB.sync()` that fires when a successful connection to a remote database is made**.  

As far as I can see, [the available events](https://pouchdb.com/api.html#replication) `changed`, `active`, `complete` only fire when there is actual replication/syncing going on, or the db is called. It would be very helpful to have an event that fired as soon as a connection to the remote db is successfully made.  

In my use case, I have the database initialization and syncing in a module, and I want to be able to call it from a separate module and hear back from it if the connection was successful, before any database activity or changes take place.  

To do this, I wrap the `db.sync()` function in a promise and resolve/reject as the events are fired.  

```
export function attachSync() {
  return new Promise((resolve, reject) => {
    const options = {
      live: true,
      auth: {
        username: cloudantApikey,
        password: cloudantPassword
      }
    };
    db.sync(cloudantUrl, options).on('error', function (err) {
      if (err.status === 401 || err.status === 403) {
        reject("invalid credentials/url");
      }
      else reject("probably offline");
    });
    // Can't resolve("connected") ?
  });
}
```

And then I call this in the main App module:  

```
attachSync().then(res => {
    // nothing to listen for here  :-(
}).catch(err => {
  if (err === "invalid credentials/url") {
    // Handle bad credentials error
  }
  else console.log(err);
});
```

With this setup, _I just have to assume that the database connected unless the promise throws an error_. This is not ideal, because the event listener for the error just hangs there with the promise unresolved.  (Unless I want to handle something based on `changed`, `active`, or `complete` that will get fired when there are changes/replication/db call going on later).  

Would it be possible to have an event like `connected` that fires when a successful sync connection is set up?  

For example:

```
var sync = PouchDB.sync('mydb', 'http://remotedb.example.com/mydb', {
  live: true,
  retry: true
}).on('connected', function (info) {
  // THERE WAS A CONNECTION MADE
  // TELL THE APPLICATION THAT THE CONNECTION TO REMOTE DB IS GOOD
}).on('error', function (err) {
  // handle connection error
});  
```

**Comment by daleharvey** [comment]
What do you think about calling `db.info()` before you start `sync`, that will allow you to verify a successful connection can be made.

These types of events are usually quite hard to implement since everyone has slightly different use cases for them, if we can do what you want to with the current API that is usually best unless we hear from a few people looking for the same thing

**Comment by adueck** [comment]
Hmm, I don't see how calling `db.info()` can let me know if a successful connection can been made? All I see in the response object is info about the local db. Can you explain a little more?

```
{ 
    adapter: "idb"
    auto_compaction: false
    db_name: "myDb"
    doc_count: 74
    idb_attachment_format: "binary"
    update_seq: 99
}
```

How would it be possible to tell if a connection can be made from this response of `db.info` ? Of course, before initializing the sync with `db.sync(cloudantUrl, options)` I haven't given any information about the remote db, so I am a little puzzled by the suggestion.

Thanks for your help, and if others do have a similar need, hopefully this will help improve this great product.

**Comment by daleharvey** [comment]
Sorry, `new PouchDB(cloudantUrl).info()` will check that you can successfully connect to cloudant, if it succeeds you connected, it will throw if not. That is the correct way to sync

**Comment by adueck** [comment]
Thank you. That works great if I'm trying to create and sync a db at the same time, ie:

```
var myNewDatabase = new PouchDB(cloudUrl, options).info()
  .then(info => {
    console.log("You connected");
    console.log(info)
  }).catch(err => {
    console.log("Failed to connect");
    console.log(err);
});
```

However, in my case, I have an local PouchDB already active and running on the app. If the user signs in and wants to sync their database, then I want to be able to start the syncing. In this, case I can't seem to use `.info()` in the same way you described. For example, this doesn't work: 

```
const localDbSync = PouchDB.sync("localDb", cloudUrl, options).info()
  .then(info => {
    // This does not execute
    console.log("You connected");
    console.log(info)
  }).catch(err => {
    console.log("Error connecting");
    console.log(err);
});
```

**Comment by daleharvey** [comment]
I dont know what your localDb function does, but `PouchDB.sync("localDb", cloudUrl, options).info()` isnt going to work, `PouchDB.sync` returns a sync object not a database (also if localDb is a database object you shouldnt quote it)

```js
var local = new PouchDB("localDB");
var remote = new PouchDB(cloudUrl);

... do whatever you want with local

remote.info().then(info => {
  console.log("You connected", info);
  local.sync(remote, options);
}).catch(err => {
  console.log("Failed to connect");
  console.log(err);
});
```
