### ISSUE TITLE
Improve `map/reduce` performance on the first time 

### ISSUE THREAD

**Issue by zhaoyi0113** [pouchdb/pouchdb#7543]
### Issue
Write the description of the issue here

I use below code to build database index but it runs out of memory if I load 20K document. I am running the code inside webview of an Android application. The webview is using chrome `indexdb`. I wonder whether below code builds the index on the whole document. Is there a way for me to reduce the memory it uses? If I only want to build the index for a few fields on the db how can I do that?

```
db.query('product_index', {
                             startkey: ["1111"],
                             endkey: ["1111", {}],
                             include_docs: false
                         });
```

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by zhaoyi0113** [comment]
Hi @karlweastin thanks for your reply. I didn't specify a design document. What is the design doing? Does it tell pouchdb what to index? If I didn't create design document will it read everything into memory and build a full index on the whole database?

**Comment by zhaoyi0113** [comment]
The reason I didn't use pouchdb-find is that I need to build index on an array field. It doesn't support it does it?

**Comment by karlwestin** [comment]
Awesome ok, i'll try to post some pointers here:
A design document is specifying how the index should be built. If you call `db.query` without any corresponding design document in your db, PouchDB will retreive all docs in memory and do the query there.

a design document looks like this (short story, there's much more to it)
```javascript
{
  "_id": "_design/myview",
  "views": {
    "by-something": function (doc) {
        // example of how to emit an array
        // "emit" is built in
        doc.tags.forEach(function(tag) { emit(tag, null) }
    }.toString() // functions need to be provided as strings
  }
}
```

by creating a view, you can get all documents tagged 'DesignDocs' something like this:
db.query('myview/by-tags', { 'startkey': 'DesignDocs', 'endkey': 'DesignDocs' })

Please read more here:
https://pouchdb.com/2014/05/01/secondary-indexes-have-landed-in-pouchdb.html
http://docs.couchdb.org/en/2.2.0/ddocs/views/index.html

**Comment by zhaoyi0113** [comment]
Thanks a lot for this information. One last thing I want to confirm is that I can't use createIndex for array field right? I won't use map reduce api if pouchdb-find support array index.

**Comment by karlwestin** [comment]
> I can't use createIndex for array field right

i tried to look this up but i could not find any answer, does anyone else know?

**Comment by zhaoyi0113** [comment]
Whether design doc can be put on couchdb side and sync to pouchdb? Do I have to build design doc on pouchdb?

**Comment by karlwestin** [comment]
> Whether design doc can be put on couchdb side and sync to pouchdb
this works fine too

good luck ;)

**Comment by zhaoyi0113** [comment]
OK thanks
