### ISSUE TITLE
Enable CORS on express-pouch server

### ISSUE THREAD

**Issue by bishal1994** [pouchdb/pouchdb#7548]
### Issue
Unable to enable CORS on pouchdb running a express-pouch server in the backend of cordova-android

### Info
- Environment: (Node.js/hybrid app)
- Platform: (Android)
- Adapter: (ILevelDB)
- Server: (CouchDB/PouchDB Server.)
-Backend_Adapter:MemDOWN

Hello , I am creating a Cordova-Android app that runs express-pouch server in its backend. After going through all the issues and discussions, I tried to implement the  
         
            overrideMode: {
             include: ['routes/fauxton']
             }
I got the fauxton but the configuration tab is blank , for which I am unable to enable the CORS.
Then I tried to provide the config.json file enabling the CORS but still CORS was not activated. 
I tried to download the pouchdb-fauxton and did the npm link and also linked to the express-pouch but no luck.

config.json
--------------
     {
        "httpd": {
        "enable_cors": true
     },
     "cors": {
        "credentials": true,
        "methods": "GET, PUT, POST, HEAD, DELETE, OPTIONS",
        "origins": "*",
       "headers": "accept, authorization, content-type, origin, referer, x-csrf-token"
      },
    "httpd":{"Bind_address":"0.0.0.0"}
     }

Tried to use CORS package and tried to activate in express 
    
   main.js
------------
    var argv = require('minimist')(process.argv.slice(2));
    var logLocation=argv.pouchlog; 
    var express = require('express');
    var app = express(); 
    var PouchDB = require('pouchdb');
    var cors = require('cors');

       let InMemPouchDB = PouchDB.defaults({db: require("memdown"), migrate: true})
       let pouchHandle = require('express-pouchdb')(InMemPouchDB, 
       {mode:'minimumForPouchDB',configPath:'./config.json',logPath:logLocation });
       app.use("/",cors(corsConfig),pouchdbHandle);
       app.listen(3000);
       let db = new InMemPouchDB('test');
       db.changes({live:true}).on('change',console.log);

Please can anyone help me with activating the CORS on the express-pouch server ? Any help will be greatly appreciated.

**Comment by daleharvey** [comment]
This is for pouchdb-core only, you should file this against https://github.com/pouchdb/pouchdb-server, cheers

**Comment by bishal1994** [comment]
I have opened an issue in pouch-server but haven't got any response yet . I
really need help in this please.
