### ISSUE TITLE
Optimal index for mango query with multiple fields & sorting

### ISSUE THREAD

**Issue by alexfedoseev** [pouchdb/pouchdb#7550]
I'm pretty sure that there's no bug here but I want to make sure that I get all the things right and it might be useful for other folks who struggle w/ similar issues. 

### Issue
I have a docs of the following shape:

```js
{
  "entity": string,
  "deleted": bool,
  "completed": bool,
  "position": float
}
```

And I want to select sorted array of entities of specific type using created index via mango query.

First attempt w/o sorting:
Index: `["entity", "deleted", "completed", "position"]`
Result: no in-memory fields, all good so far.
![image](https://user-images.githubusercontent.com/4244251/49336910-9ce17e00-f645-11e8-9e26-d2115efbee84.png)

Then I added `sort` to query:
Index: same as above.
Result: doh! `find` failed.
![image](https://user-images.githubusercontent.com/4244251/49336946-44f74700-f646-11e8-8a0d-27c957c737d3.png)

After reading docs I guessed that to make it work my index should start w/ `position` thus selection for this index will be sorted by the first key. So I made this change:

Index: `["position", "entity", "deleted", "completed"]`
Result: it worked, BUT now I get 3 in-memory fields.
![image](https://user-images.githubusercontent.com/4244251/49337020-31001500-f647-11e8-8a6a-979f3de93c21.png)

AFAIU in-memory sorting is being applied b/c index initially sorted by position, so `entity` column contains mixed values, so it can't just take a slice of the index in this case, e.g.:

```
position    entity    deleted    completed
------------------------------------------
1           PROJECT   false      false
1           OTHER     true       false
1           PROJECT   true       true
2           OTHER     false      false
2           PROJECT   true       false
3           OTHER     true       true
3           PROJECT   false      true
```

So my question is what's the optimal way to handle such case? Is having in-memory fields unavoidable or there's a way to optimize current index/query?

P.S. Also, I spotted one more gotcha: position of key in selector object must match position of corresponding field in index array. It's a bit weird since AFAIK it's unsafe to rely on position of a key in js object. Not sure if it's by design or not.

![image](https://user-images.githubusercontent.com/4244251/49337136-67d72a80-f649-11e8-91b5-f9e3e1a638d3.png)

**Comment by garrensmith** [comment]
@alexfedoseev There isn't anything wrong with having in memory filtering. So its not the worst thing to have. I guess the tradeoff you have here is using only the index and minimal in memory filtering versus perfectly sorted. 

> P.S. Also, I spotted one more gotcha: position of key in selector object must match position of corresponding field in index array. It's a bit weird since AFAIK it's unsafe to rely on position of a key in js object. Not sure if it's by design or not.

This is a bit weird, we need to look at that.

**Comment by alexfedoseev** [comment]
Thanks for response! Should I create separate issue for position of key in selector issue?
