### ISSUE TITLE
Pouchdb websql/ riak in node

### ISSUE THREAD

**Issue by mavericksthinker** [pouchdb/pouchdb#7551]
### Issue
Unable to implement websql/riak on nodejs cordova android app . Leveldown which is by default is unsupported for platform android.

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
Hybrid app
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
Cordova android
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
Websql/riak
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)
Express-pouchdb

Hello , I have a Cordova android app that runs express-pouchdb server in it's backend . I was able to implement memdown which currently stores the data in memory and is lost once the app is restarted . So I tried to implement pouchdb adapter node websql but during the runtime it has error in leveldown.node which is 64bit but requires a 32bit on android . When I rebuilt the leveldown to 32bit it still shows error and leveldown doesnt support android .

Is there a way to change to levelup with websql adapter or help in implementation of levelup riak ? Or is there any better way to make it suitable for production? 
Any help will be appreciated.

**Comment by daleharvey** [comment]
Sorry, I dont know and webSQL isnt part of PouchDB core, https://github.com/pouchdb-community/pouchdb-adapter-cordova-sqlite may possibly help
