### ISSUE TITLE
where can I find design_doc from IndexedDB?

### ISSUE THREAD

**Issue by zhaoyi0113** [pouchdb/pouchdb#7553]
### Issue
Write the description of the issue here
I followed this instruction (https://pouchdb.com/2014/05/01/secondary-indexes-have-landed-in-pouchdb.html) to build a design doc in pouchdb(using IndexedDB in browser). When I inspect the `IndexedDB` through chrome dev tool, I can't see the design doc there. Instead I see something like `attach-store`, `by-sequence`, `document-store` etc. I wonder whether design doc is supposed to be shown there. What does these tables mean? Is there any document describe these structure?

### Info
- Environment: (Node.js/browser/hybrid app/etc.)   Chrome Browser
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)   Android
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)   IndexedDB
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.) PouchdDB

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by daleharvey** [comment]
The contents of documents (including the design document) will be stored in the by-sequence table, those are internal structures and not documented, if you want to understand them happy to answer specific questions or you can read the source at https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-idb/src/index.js

**Comment by zhaoyi0113** [comment]
Thanks for your answer. The reason I ask is because my query runs a long time and consume a lot of memory. I want to check whether the design doc is created correctly or not. Could you let me know how I can search the design doc in `by-sequence` table?

**Comment by daleharvey** [comment]
The document-store will have a listing for each documents id, including the design document, it will have a reference to the by-seq id that you can use to look up the document

However the document is going to be the same thing that you get back from `db.get('_design/doc')`

**Comment by zhaoyi0113** [comment]
Where can I look at the `views` created by map/reduce query? Is it a separate table or inside another table?

**Comment by daleharvey** [comment]
The views data are different databases that have -mr-view in the name
