### ISSUE TITLE
Sync calling endpoint without {DatabaseName}

### ISSUE THREAD

**Issue by baartho** [pouchdb/pouchdb#7557]
### Issue
I've setup my CosmosDB (which is acting like CouchDB) on the endpoint `http://localhost:29405/db/{DbName}/`

So this is my sync code on PouchDB. As you can see I'm making calls to a DB named 123.

```
sync() {
        var cosmosDbUrl = 'http://localhost:29405/db/123';

        this._db.sync(cosmosDbUrl
        ).on('complete', function () {
            console.log("synced");
        }).on('error', function (err) {
            console.log(err);
        });
    }
```

When I'm calling `sync()` there is one call being made to `http://localhost:29405/db/123` which is basically [retrieving info](http://docs.couchdb.org/en/stable/api/database/common.html#get--db) about my DB. 

But there is also a second call being made to `http://localhost:29405/db/` (without the DB name, which is **123**). 

I'm not sure why this second call is being made. If I return the **123** database info, I'm able to sync data both ways successfully. But I had to create a "hack" just for that, and if I require info about a database other than **123** my hack will no longer work.

has anyone faced a similar issue? Thank you!

![image](https://user-images.githubusercontent.com/19720384/49474968-27201280-f7fd-11e8-8dac-4a1a5e8e9d8b.png)

![image](https://user-images.githubusercontent.com/19720384/49474979-2be4c680-f7fd-11e8-938a-6210a775641c.png)

![image](https://user-images.githubusercontent.com/19720384/49474985-3010e400-f7fd-11e8-8ef0-c9741873bc5a.png)

### Info
Environment: (browser)
Platform: (Chrome)
Adapter: (IndexedDB, PouchDB 7.0)
Server: (CosmosDB)

### Reproduce
1 - Install PouchDB 7.0
2 - call the sync() method above

**Comment by daleharvey** [comment]
The call to `http://localhost:29405/db/` is to fetch the database info in order to create checkpoints, In the last release we broke support for when that url failed to return data and we have fixed that for the next release. You are recommended to return the db info though

**Comment by daleharvey** [comment]
Sorry not the db info, the server info, the documentation for the request is @ http://docs.couchdb.org/en/2.2.0/api/server/common.html, we use the uuid to generate the checkpoint, other server implementations just send a welcome json - https://github.com/pouchdb/pouchdb-express-router/blob/master/index.js#L24
