### ISSUE TITLE
Replication Issue - One Way Sync is still doing bi-directional sync

### ISSUE THREAD

**Issue by jkeczan** [pouchdb/pouchdb#7560]
### Issue
I am working on setting up a batch sync style based on some customer specifications that I received. The goal is that users can make local changes and batch sync them up per the user request. This works fine as long as any replication is turned off by firing a one time sync with live: false.

However, I have an additional requirement that says any changes from the server must be pulled down in real time. So I attempted to setup a one way "from" remote sync ONLY and a one time PUSH sync method.

### Info
- Environment: Angular
- Platform: All Platforms
- Adapter: IDB
- Server: CouchDB

### Reproduce
Setup a local pouch with db.replication.from(remoteDB, {live: true})
Open the application in two browsers
Make a change in either browser and the changes replication between them EVEN though the live feed is only suppose to be a pull sync. 

Is this use case not possible in this case or is this a bug?

**Comment by daleharvey** [comment]
Fairly sure something else must be going on with your application, the use case you describe should work as you stated ands its not really possible for pouch to be replicating data it hasnt been told to

If you could reproduce on https://pouchdb-bug-helper.glitch.me/ it would be very helpful

**Comment by jkeczan** [comment]
Thank you for the quick response. Working on it now.

**Comment by jkeczan** [comment]
While I am working on it, this is my init code for my DB. It is only called once AND is the only syncing setup for the entire application. This is the only place it is called.

`javascript

  db = new PouchDB('timekeeper');
  remoteDB = new PouchDB('URL TO DB'); //removed for security

  this.currentSync = db.replicate.from(this.remoteDB, {live: true})
            .on('change', (event) => {
              $this.syncChangeHandler(event);
            })
            .on('paused', (event) => {
              $this.syncPausedHandler(event);
            })
            .on('error', (event) => {
              $this.syncErrorHandler(event);
            });
`

**Comment by jkeczan** [comment]
I got it, we can close this. 

We had one case where the DB was actually getting overrode to target the remote db for a put request instead of the local one. 

My apologies for wasting your time.
