### ISSUE TITLE
delete with bulkDocs and new_edits = false not working

### ISSUE THREAD

**Issue by kkbhav** [pouchdb/pouchdb#7562]
### Issue
When updating an existing document with _deleted=true and rev from remote database using bulkDocs api and setting new_edits=false, then bulkDocs api gives success result but the document does not get deleted.

### Info
- Environment: Node.js
- Platform: Chrome
- Adapter: LevelDB
- Server: PouchDB Server

### Reproduce
1. Put a document in remote database and sync with local database
2. delete the document from remote database 
3. use the rev from previous result and update the localDB using bulkDocs with new_edits = false
4. query the document again, which results in document with older revision.

### Sample Code
const localDB1 = new PouchDB('http://example.com/remotedb');
const localDB2 = new PouchDB('localDB');
const obj = { _id: 'random1', info: 'test1' };
const res = await localDB1.put(obj);
obj._rev = res.rev;
const res2 = await localDB2.bulkDocs([obj], { new_edits: false });
obj._deleted = true;
const res3 = await localDB1.put(obj);
obj._rev = res3.rev;
const res4 = await localDB2.bulkDocs([obj], { new_edits: false });
const res5 = await localDB1.allDocs({ include_docs: true });
const res6 = await localDB2.allDocs({ include_docs: true });

res5 will not have the document in the result, but res6 will have that document in the result

**Comment by daleharvey** [comment]
reproduced the failure @ https://sticky-magician.glitch.me/

A little confused, I think this should work as you expect, assumed it would be a conflict but not immediately obvious whats up

**Comment by kkbhav** [comment]
I tried to debug this a little and found out that everything goes inside the database but the winningRev entry is wrong for the case of new_edits=false, which causes it to return wrong revision for the documentID.

The wrong rev is returned from the `winningRev` function of pouchdb-merge library. Have a look in these functions for the sample code.

**Comment by kkbhav** [comment]
Any updates on this?

**Comment by kkbhav** [comment]
Is this solved?

**Comment by charleswritescode** [comment]
Check my workaround on @pubkey issue https://github.com/pouchdb/pouchdb/issues/7841#issuecomment-651103704
