### ISSUE TITLE
sync immediately broken if network is disconnected

### ISSUE THREAD

**Issue by dravenk** [pouchdb/pouchdb#7567]
### Issue
Write the description of the issue here
I write a custom tool in golang that call the CouchDB _changes api. I notice that I turn off my computer wi-fi, the http stream is still holding. but pouchdb will immediately broken. Why is PouchDB synchronization interrupted when the network just down?

The api call like that
```
http://couchdb.xxxxxxx.com:5984/b1/_changes?style=all_docs&feed=longpoll&limit=100&heartbeat=60000&since=5253-g1AAAAFLeJzLYWBg4MhgTmHgzcvPy09JdcjLz8gvLskBCjMlMiTJ____PysJyPbGoSZJAUgm2cOUHcWlzAGkLB6qjJkHl7IEkLJ6mGntOJTlsQBJhgYgBVQ5H6y0H6_SBRCl-8FKA_AqPQBReh-stA2v0gcQpRC31mYBAKbJZpQ
```
here is the script 
<details><summary>main.go </summary>
<p>
  
```
package main

import (
	"net/http"
	"strings"
	"io/ioutil"
	"encoding/json"
	"log"
	"os"
)

type Couch struct {
	Host string
	User string
	Pass string
}

var couchDB = &Couch{}

var (
	// CouchDB in remote server
	Host   = "http://couchdb.xxxxxxxxxx.com:5984" // change this 
	User   = "admin" // change this 
	Pass   = "password" // change this 
	FeedDB = "aaa" // change this 
)

func init() {
	couchDB = &Couch{
		Host: Host,
		User: User,
		Pass: Pass,
	}
	since, _ := couchDB.LastSeq(FeedDB)
	SetSince(since)
}

func main() {
	for {
		Feed()
	}
}
func Feed() {
	log.Println("Feed() ... ")
	options := map[string]string{
		"style":        "all_docs",
		"feed":         "longpoll",
		"limit":     "100",
		"since":     Since(),
		"heartbeat": "60000",
	}

	cs, code := couchDB.Changes(FeedDB, options)
	if code != http.StatusOK {
		log.Println(code)
	}
	if cs != nil {
		log.Println("CouchDB Change!", code)
	}

	type data struct {
		LastSeq string `json:"last_seq"`
	}
	d := &data{}
	err := json.Unmarshal(cs, d)
	checkErr(err)
	SetSince(d.LastSeq)
}

func (c *Couch) Get(path string) (body []byte, code int) {
	return c.Request(http.MethodGet, path, "")
}

func (c *Couch) Changes(db string, options map[string]string) (body []byte, code int) {
	var value string
	for d, k := range options {
		value += d + "="
		value += k + "&"
	}
	path := db + "/_changes?" + strings.TrimSuffix(value, "&")
	return c.Request(http.MethodGet, path, "")
}

func (c *Couch) Request(method, path, data string) (body []byte, code int) {
	req, _ := http.NewRequest(method, c.Host+"/"+path, strings.NewReader(data))
	req.SetBasicAuth(c.User, c.Pass)
	req.Header.Set("Content-Type", "application/json;charset=utf-8")
	log.Println(req)
	res, err := http.DefaultClient.Do(req)
	checkErr(err)
	defer res.Body.Close()
	body, err = ioutil.ReadAll(res.Body)
	checkErr(err)
	return body, res.StatusCode
}

func checkErr(err error) {
	if err != nil {
		panic(err)
	}
}

func (c *Couch) LastSeq(db string) (lastSeq string, code int) {
	path := db + "/_changes?descending=true&limit=0"
	body, code := c.Request(http.MethodGet, path, "")
	type data struct {
		LastSeq string `json:"last_seq"`
	}
	d := &data{}
	json.Unmarshal(body, d)
	return string(d.LastSeq), code
}

func Since() string {
	b, err := ioutil.ReadFile("since.txt")
	if err != nil {
		SetSince("") // init
		log.Println("Since() ...",err)
	}
	str := string(b)
	log.Println("Since() ...",str)
	return str
}

func SetSince(since string) {
	err := ioutil.WriteFile("since.txt", []byte(since), os.ModePerm)
	if err != nil {
		log.Println("SetSince() ...",err)
	}
}

```
</p>
</details>

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by daleharvey** [comment]
I do not know how go works, but the couchdb changes feed 1. Uses browser connections that will be killed once the connection is killed 2. Uses polling so even if the connection stays, the next connection wont be able to be made.

This is expected behaviour, you cant sync with a server when you cant connect to it, retry: true on the replication is designed to ensure it will resume once the connection can be reestablished

**Comment by dravenk** [comment]
I mean if client not broken the sync immediately when the network just down, the synchronization process will not trigger the backoff function. After, the connection is reconnected and the synchronization remains normal. Like that below.
<img width="1679" alt="002" src="https://user-images.githubusercontent.com/14295318/50167274-c8da5000-0323-11e9-8284-a0b98f9773ba.png">
<img width="1679" alt="003" src="https://user-images.githubusercontent.com/14295318/50167287-cf68c780-0323-11e9-8fc4-f4eb711657d6.png">
