### ISSUE TITLE
Links to couchdb wiki need updating, when available

### ISSUE THREAD

**Issue by anaran** [pouchdb/pouchdb#7571]
### Issue
See apache/couchdb#1813

Also, some still use http: instead of https:, but are upgraded to https.

**Comment by k-j-kleist** [comment]
Please, stale bot, leave this open.

**Comment by k-j-kleist** [comment]
I believe that this issue can be closed.

I have checked all `.md` files in `docs/`: no references to `wiki.apache.org` are left.

**Comment by daleharvey** [comment]
Awesome job thank you
