### ISSUE TITLE
bulkDocs conflicts on empty database, returns empty result with new_edits:false

### ISSUE THREAD

**Issue by anaran** [pouchdb/pouchdb#7572]
### Issue
When trying to import docs from a local file into an empty local pouchdb database I get conflicts for every single document.

I slimmed to down to a single doc to import and got the same:

```
{
  "docs": [
    {
      "activity": "I create one entry manually in Brave dev on localhost before trying import of file exported from Firefox Nightly.",
      "_id": "2018-12-15T21:21:02.000Z822e69c89316",
      "_rev": "2-b0be3157f1994b6e907055f534b63c72"
    }
  ]
}
```

I succeed to insert the document when using `{ new_edits: false }` but bulkDocs resolved to an empty array for a result.

The empty result is surprising given the bulk insert worked (also an a large dataset I used).

Are there any knows issues matching what I describe here? I swear I had the import functionality working in earlier versions of pouchdb and browsers (without new_edits:false).

I have looked for breaking changes in the release notes but have not found any.

I read 7.0 has conflict resolution implications (#4642) but I have not upgraded yet. Is it recommended to upgrade yet?

Inserting into an empty database should not result in any conflicts, right? The _rev values stem from another browser I exported the database from.

Would be thankful for any ideas to try.

### Info
- Environment: browser/pouchdb 6.4.3
- Platform: FF/Chrome/Brave
- Adapter: IndexedDB
- Server: CouchDB, but not used in this use case

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by daleharvey** [comment]
What you described is expected behaviour, `new_edits: true` will match the revs and if they dont match its a conflict, `new_edits: true` will let you specify a rev that doesnt match, but the result is always an empty array (purely for compatibility with CouchDB

**Comment by daleharvey** [comment]
I meant: 

    `new_edits: false` will let you specify a rev that doesnt match, but the result is always an empty array (purely for compatibility with CouchDB)

**Comment by anaran** [comment]
Thanks @daleharvey ! My concern is how would bulkDocs in pouchdb report errors occurring with `new_edits: false`, e.g. out of memory due to huge input data? Would it return a non-empty results array? Can I rely on an empty result array meaning successful insert of all documents?
