### ISSUE TITLE
When using a map/reduce index on PouchDB, with the keys option, the limit option is not respected

### ISSUE THREAD

**Issue by badbod99** [pouchdb/pouchdb#7573]
### Issue
When using a map/reduce index on PouchDB, with the _keys_ option, the limit option is not respected.  When using the _key_ option the limit is respected.  _allDocs_ does respect the limit option when using the _keys_ option.  The issue only seems the be present with PouchDB map/reduce indexes.

### Info
- Environment: Browser, local database with PouchDB 7
- Platform: Chrome 71 (latest)
- Adapter: IndexedDB
- Server: CouchDB (but issue reproducible without server).

### Reproduce
https://meadow-motorcycle.glitch.me/

**Comment by jasonxia23** [comment]
IMO, problem happened in `onMapResultsReady` which should filter param `rows` according to `limit` option.

If this is correct, I can make a PR.

**Comment by badbod99** [comment]
I would hope this would happen adapter side rather than in memory, otherwise there is not much point to the limit, we could just do `slice(0,5)` in JavaScript after it returns.

**Comment by badbod99** [comment]
This is still a bug and should not be closed

**Comment by bidwej** [comment]
I think this may be a bug as well. If I set a 'limit' I get the same documents regardless of my 'startkey'.

**Comment by badbod99** [comment]
Still an issue, still needs fixing.

**Comment by badbod99** [comment]
Still a bug.

**Comment by badbod99** [comment]
Still an issue

**Comment by AlbaHerrerias** [comment]
This issue has been addressed and merged to master in https://github.com/pouchdb/pouchdb/pull/8404. A new release will land soon. Thank you
