### ISSUE TITLE
Implement sync peer connected/disconnected events

### ISSUE THREAD

**Issue by DanRuderman** [pouchdb/pouchdb#7576]
I'm using PouchDB in a real time browser application while synced to a remote CouchDB. It would be useful to know the status of the connection, for example by getting events when it drops and when an automatic retry established a new connection. The events `paused` and `active` do not seem to be specific to losing/re-establishing connections.

I'll be glad to implement, if someone could provide guidance.

**Comment by juusor** [comment]
I would also appreciate the functionality to know whether the live mode sync is in 'ready state' (i.e. that all current changes have been successfully synchronized to/from the remote).

I guess the easiest way would be to modify the `paused` event such that it would also tell the reason why the synchronization has paused. Currently identical `paused `event is fired at least in the following cases:
 1. There are no more changes to synchronize. I.e. the 'ready state'
 2. The connection to remote server has failed.

So, currently the library user has no way to separate these cases...
