### ISSUE TITLE
Feature request about live-finding with PouchDB

### ISSUE THREAD

**Issue by hadrien-toma** [pouchdb/pouchdb#7583]
Might it be possible to imagine having [pouchdb-live-find](https://github.com/colinskow/pouchdb-live-find) merged in this repository? Or can I suggest a feature request about live-finding? It is likely to be one of the best features discovered in my PouchDB user experience and it could even be better if maintained as a PouchDB feature :heart_eyes:.

**Comment by daleharvey** [comment]
At this point we are already stretched maintaining the the current functionality and are definitely not looking for more things to support, we do have https://github.com/pouchdb-community as a venue for semi official things that arent in core and you could ask Colin if they want to move it there. If you want to do a feature request then the repo is the best place to do that, cheers
