### ISSUE TITLE
Replicate failing (aborting) without error

### ISSUE THREAD

**Issue by badbod99** [pouchdb/pouchdb#7588]
### Background
I'm trying to sort out the PouchDB React Native build.  [pouchdb-react-native](https://github.com/stockulus/pouchdb-react-native) is no longer maintained, this currently leaves no working, up to date version of PouchDB for React-Native.  I've started from a clean slate and created a custom build of PouchDB with the required modules.  The standard build I've gone for is with SQLite (since the AsyncStorage adapter is no longer maintained and has limitations anyway).  Almost everything works with the latest 7.0.0 packages (find, map/reduce, etc...).

### Issue
The one thorn in the side is replication.  Running with remote JS debugging (via Chrome), replication works fine.  Running without the browser in-between, it fails.  No useful error is returned.  It even fails remote-to-remote, ruling out any SQLite or websql-core issue.  Unfortunately, expo doesn't give me a more detailed stack trace (as it's not actually an exception).

The JSON of the error response is:
```
    ok:false
    start_time:"2018-12-30T21:55:10.707Z"
    docs_read:0
    docs_written:0
    doc_write_failures:0
    errors:[]
    status:"aborting"
    end_time:"2018-12-30T21:55:10.710Z"
    last_seq:0
```

All these scenarios fail in the same way:
1. Local<->Local
2. Local->Remote
3. Local<-Remote
4. Remote<->Remote

### Info
- Expo 3.1 (React-Native)
- Android via Expo App
- HttpAdapter
- CouchDB (although occurs with just PouchDB->PouchDB)

### Reproduce
I've created a simple starter project that demonstrates the issue at https://github.com/badbod99/pouchdb-expo-example.  Any help on how to debug this or why the call is being aborted greatly appreciated.

**Comment by badbod99** [comment]
Some further investigation I've managed to get an error message.  There is a bug in the pouchdb-errors module which is failing to add the `message `property in `CustomPouchError`.  I'll submit a PR for that.

The error I can now see is: `getCheckpoint rejected with: Can't find variable: btoa`

I've added the btoa package to my project, but still no luck.  Also tried [base64](https://github.com/mathiasbynens/base64) JavaScript library.  I suspect it's coming from PouchDBBinaryUtils, but struggling to track down where btoa is being used.

**Comment by badbod99** [comment]
For anyone who comes across this in future, the issue is that the browser implementation of _pouchdb-md5_ (binaryMd5-browser.js) uses _btoa_.  It sources this from _pouchdb-binary-utils_.  pouchdb-binary-utils uses btoa global which resolves to window.btoa on a browser.  In React Native, it does not resolve.  

The solution is to add btoa and atob to global.  You need a javascript atob and btoa implementation and the following to add it to global:
```
import {btoa, atob} from './base64'
if (!global.btoa) {
    global.btoa = btoa;
}

if (!global.atob) {
    global.atob = atob;
}
```
Do this where you initialise your PouchDB plugins.

I'll do a pull request for the error handling fix.

**Comment by knubie** [comment]
I'm running into a similar issue.

In my case, replication works in Chrome, but fails with no error in Electron, so there must be something about the Electron environment that's causing the error, similar to the missing `btoa` variable in React Native.

Another thing to note is that the failure only happens if there are attachments in the remote database.

**Comment by USMANONLINE** [comment]
How about this error, its failing to replicate documents

"error": {
    "stack": "TypeError: Failed to fetch",
    "message": "Failed to fetch",
    "result": {
      "ok": false,
      "start_time": "2022-05-22T08:53:22.264Z",
      "docs_read": 23,
      "docs_written": 0,
      "doc_write_failures": 23,
      "errors": [],
      "status": "aborting",
      "end_time": "2022-05-22T08:53:30.307Z",
      "last_seq": 23397
    }
  }
