### ISSUE TITLE
IDBNext: migration from idb plan

### ISSUE THREAD

**Issue by SCdF** [pouchdb/pouchdb#7591]
The current adapter based on IndexedDB is called `idb`. We are working on a better one, called `indexeddb`. See: https://github.com/pouchdb/pouchdb/issues/5207

Once that's done we'll have two adapters based on IndexedDB, and we should consider how we're going to deal with that in terms of migrating from `idb` to `indexeddb`.

Here are the options I can think of: given `old-db`, an `idb`-based PouchDB <=7.x database, being opened on PouchDB 8.0 (where `indexeddb` is the default adapter):
 - Write manual, internal data migrations into the native indexeddb migrations that happen whenever `indexeddb` databases are opened, so handle opening (ie to get a transaction) is blocked on the data migration happening
 - When instantiating (`new PouchDB('old-db')`), hit the DB, detect it's the old format and use replication to convert the DB to the new format. Probably also removing the immediate instantiation seen here, and instead returning an instance safely via async.
 - Don't migrate at all: support both the old adapter and the new one in the same codebase side by side. New dbs use `indexeddb`. Opening `idb` dbs writes a warning to the console that they are deprecated, finally in PouchDB 9.0 remove `idb` completely. Either just allow for replication (since you have both adapters) or support some kind of function you call to migrate old to new manually.
 - Don't migrate at all: only support the new one, and error when you try to open the old one. Support some kind of function you call to migrate old to new manually.

## Internal DB migration

This is the most seamless. The almost certain downside is that even though we *could* write the migration code to emit events that you could follow to eg show a progress bar, since "no one reads the instructions" is a good rule to follow many application makers will probably just upgrade to 8.0, not wire up those events and just have their app awkwardly block for ages and ages.

I *think* the current structure will handle it (eg everything will block correctly, so if you perform 10 find requests on the new DB none of them will break), but it would need to be tested.

## Replication-based DB migration

There is here because it's similar to `Internal DB Migration`, but it involves writing far less code and is more likely to be "correct" (because it's exercising the code correctly). However, it would be much slower (more abstractions to work through), would do externally visible things like change the seq numbers, and we'd have to do some work to delete the old DB and rename etc, to keep it consistent. I don't like it :-)

## No migration

There is a good argument to be made to ship like this. It's very seamless, and it lets the application makers decide how and when they want to perform the migration. It also gives slower groups an entire major semver to add the migration work.

However, it makes the web build larger, and could be confusing, as old users of an app would be on `idb` and new users would be on `indexeddb`.

## Hard break

Near identical core logic code to the first option, except instead of automatically doing it on migration we require that the application makers manually call the function at their convenience. This is bad because it means that we will hard break people between PouchDB 7.x and 8.0, and it's good because the application maker is forced to deal with it, which will hopefully mean they'll handle it in a way that isn't confusing to their users.

Interested in people's thoughts, cc. @daleharvey, @garrensmith.

**Comment by SCdF** [comment]
Since 3/4 of the options above need or can use an internal migration (eg not just replicating between two repos) I'm going to look into that now.

**Comment by garrensmith** [comment]
This is pretty tough to decide, but I'm not a fan of "magic" happening internally and I worry that having an internal migration happening without the user knowing is a bit of magic. I would rather that a user has to manually migrate it using standard replication. That way if the replication fails or any issues occur they still have there original db. We can then look to not ship the old indexeddb in 9.0

**Comment by SCdF** [comment]
@garrensmith right. So if we went that route, a resolution for this ticket would be:

PouchDB 7.x.x
 - For both `idb` and `indexeddb` correctly detect when you are opening a db made with the other adapter and cleanly error
 - Allow people to intentionally require in the `indexeddb` adapter and use it in their projects, but don't have it as part of the `pouchdb.js`, the default shipping browser 

PouchDB 8.0.0
 - Change the default from `idb` to `indexeddb`
 - Change the shipping browser artefact to contain both the `idb` and `indexeddb` adapter, unfortunately bloating it a little
 - Add a logged warning when you ask for the `idb` adapter, stating it will be removed in PouchDB 9

PouchDB 9.0.0
 - Remove the `idb` adapter as part of the default bundle. People can still manually pull it from npm if they need to.

**Comment by garrensmith** [comment]
Yes, It seems the easiest in my mind. We should add documentation that you need to replicate between db's to update your database.

**Comment by daleharvey** [comment]
Garren reminded me that you arent a committer btw @SCdF so I have invited you to have commit access to @pouchdb, thanks so much for your work

**Comment by daleharvey** [comment]
I am a little worried about releasing both of these in the same build, a full internal migration would be very nice but as mentioned if you have a large database it could be prohibitive. 

I would be leaning towards a hard break, ensure that we arent going to try opening the wrong type of database in either type of adapter and screwing things up, then releasing `indexeddb` as `pouchdb 9`. We can continue to release `idb` as `pouchdb.compat` or something and give instructions for users on how to replicate their code across (like in https://pouchdb.com/2018/01/23/pouchdb-6.4.2.html)

I think we would like to avoid new users of pouchdb be given a bundle size that includes an entire previous version that they dont need at all, this puts a little extra work on the users but I do think they are in the best position to be making tradeoffs that make sense for them.

**Comment by garrensmith** [comment]
+1 to what @daleharvey says

**Comment by garrensmith** [comment]
Don’t close yet

________________________________

**Comment by SCdF** [comment]
Not yet stale bot!

**Comment by garrensmith** [comment]
Not yet

**Comment by SCdF** [comment]
No yet

**Comment by SCdF** [comment]
Not yet please

**Comment by garbados** [comment]
Should this have been closed?
