### ISSUE TITLE
Requires multiple indexes to be able to order by a property

### ISSUE THREAD

**Issue by sindresorhus** [pouchdb/pouchdb#7593]
Reopening #7205 as a new issue, since it was auto-closed by a bot.

> ### Issue
> I'm not sure if this is expected behaviour or a bug. But if you have three fields, `date`, `foo`, `bar`. You need to have two separate indexes, one for `date`+`foo` and one for `date`+`bar`.
> 
> I expected to be able to have a single index on `date`+`foo`+`bar` but this results in `Error: Cannot sort on field(s) "date" when using the default index` when querying `bar` but works ok for `foo`
> 
> ### Info
> * Environment: Browser
> * Platform: Chrome
> * Adapter: IndexedDB
> * Plugin: PouchDB Find
> 
> ### Reproduce
> Fails with a single index on `['date', 'foo', 'bar']`:
> 
> ```js
> const db = new PouchDB('singleindex', {adapter: 'idb'});
> 
> await db.createIndex({index: {fields: ['date', 'foo', 'bar']}});
> 
> await db.post({date: Date.now(), foo: 1, bar: 1});
> await db.post({date: Date.now(), foo: 2, bar: 2});
> 
> await db.find({
> 	selector: {
> 		foo: 1,
> 		date: {$gt: true},
> 	},
> 	sort: [{date: 'desc'}],
> });
> // => Success
> 
> await db.find({
> 	selector: {
> 		bar: 1,
> 		date: {$gt: true},
> 	},
> 	sort: [{date: 'desc'}],
> });
> // => Error: Cannot sort on field(s) "date" when using the default index
> ```
> 
> Works with two indexes on `['date', 'foo']` and `['date', 'bar']`:
> 
> ```js
> const db = new PouchDB('doubleindex', {adapter: 'idb'});
> 
> await db.createIndex({index: {fields: ['date', 'foo']}});
> await db.createIndex({index: {fields: ['date', 'bar']}});
> 
> await db.post({date: Date.now(), foo: 1, bar: 1});
> await db.post({date: Date.now(), foo: 2, bar: 2});
> 
> await db.find({
> 	selector: {
> 		foo: 1,
> 		date: {$gt: true},
> 	},
> 	sort: [{date: 'desc'}],
> });
> // => Success
> 
> await db.find({
> 	selector: {
> 		bar: 1,
> 		date: {$gt: true},
> 	},
> 	sort: [{date: 'desc'}],
> });
> // => Success
> ```

**Comment by rdewolff** [comment]
Thanks for following up on that issue. Am facing the same issue.
Any plan to fix this ?
