### ISSUE TITLE
Don't apply plugins to the global PouchDB reference

### ISSUE THREAD

**Issue by sindresorhus** [pouchdb/pouchdb#7594]
Reopening #7198 as a new issue, since it was auto-closed by a bot. It was already accepted.

> Why are plugins applied to the global `PouchDB` reference? Shouldn't they be applied to individual instances.
> 
> With the current setup, it looks like if I'm using a third-party lib that also uses pouch and they use a plugin, my app is forced to also use that plugin.
> 
> Is that correct?
> 
> If so, is there any interest in changing this behaviour.
> 
> I think instead of:
> 
> ```js
> const PouchDB = require('pouchdb');
> const pouchPlugin = require('pouchdb-plugin');
> 
> PouchDB.plugin(pouchPlugin);
> 
> // Uses pouchPlugin :)
> const db = new PouchDB('plugin-db');
> 
> // Also uses pouchPlugin :(
> const db = new PouchDB('no-plugin-db');
> ```
> 
> it should be:
> 
> ```js
> const PouchDB = require('pouchdb');
> const pouchPlugin = require('pouchdb-plugin');
> 
> // Uses pouchPlugin :)
> const db = new PouchDB('plugin-db');
> db.plugin(pouchPlugin);
> 
> // Doesn't use pouchPlugin :)
> const db = new PouchDB('no-plugin-db');
> ```

**Comment by karlwestin** [comment]
That issue does not seem accepted at all. Rather it was explained that it would be a breaking change and the contributor was not providing many reasons for doing the breaking change.

If anyone is interested in this, please go back to the original issue and try to start a discussion about reasons for making this change, and if it could be made in a non-breaking way somehow... like adding a `PouchDB.core()` method that would include a non-plugined version.
