### ISSUE TITLE
No way to keep pouchdb from eventually eating up all memory?

### ISSUE THREAD

**Issue by Kitanotori** [pouchdb/pouchdb#7598]
### Issue

I have an app that creates large amount of new documents to a pouchdb database per day. The documents are synced to a couchdb from where they are taken regularly for further processing. After the processing is completed, the documents are not needed anymore.

In order to avoid the database expanding indefinitely, potentially causing memory issues with the browser, I want to regularly delete old documents that are no longer needed. However, pouchdb seems to only support physical deletion of old revisions, via compact, always leaving the latest revision to eat up memory.

Is there no way to keep pouchdb from expanding indefinitely and eventually eating up all memory?

Seems to be related to https://github.com/pouchdb/pouchdb/issues/802.

**Comment by aneeshd16** [comment]
@Kitanotori We have a similar use case, our application could not efficiently query the database after approx 2000 documents. To solve for this, we did the following:
1. Have separate filters for `from` and `to` replication to Couch. You'll probably want to sync all docs from pouch -> couch, and not sync anything from couch -> pouch.
2. You can figure out if all docs have synced by checking the sequence no (I can post this code here if required)
3. If all docs have been synced, simply destroy the local database. Or, if you want to keep some docs but delete others, you can do a filtered replication from your local DB to another local DB and then destroy the original DB.

**Comment by marcinmajkowski** [comment]
I'm facing similar challenge and that is what I came up with for a purge substitute:
- create new PouchDB instance along the one you're using
- replicate all documents you want to keep to the new instance
- destroy original instance, effectively purging all documents omitted in previous step
- use new instance in place of the original one

Also setup CouchDB replication so purged documents won't come back.

I haven't implemented this yet. Do you think it's a viable solution or maybe can notice shortcomings? The one I can think of is that you need to have free storage to perform this process.

**Comment by daleharvey** [comment]
Yup rolling databases are the best solution right now, purge which will be implemented reasonably soon will fix this better
