### ISSUE TITLE
Fetch error with the changes feed connected to a remote couchdb server

### ISSUE THREAD

**Issue by daweedm** [pouchdb/pouchdb#7601]
### Issue
Error with the `changes` method as a direct remote client to a couchdb server.

Sometimes (maybe due to a networking problem), the changes feed crashes with the following message (got from the `error` event):

```js
{ FetchError: invalid json response body at https://XXXXXXXX/_changes?feed=longpoll&heartbeat=10000&since=486-g1AAAAIjeJyV0UsKwjAQANBgBd14Bt2LkMaMTd3YE3gFTUxCKTVZ6F5vojfRm-hNaj5dKUK7mYEhecynRgiNy0SiibHGSlUYW9rTuXblAUdi2jRNVSZ8fnSFESY5EODfj_98FzMXxaYVtkEQGCjJdFeh8MKuFVQQZEpB5qSrsPfCpRXWQchSRlLddQozdBFdXXLIzStZUEAzzWDZS7lH5eEVFhTOBQgFvZRnVF5eIUHJKZZk1a-Xd1TCXhZxIsCKHX5uU30AGd-pDw&limit=25 reason: Unexpected end of JSON input
XXXXXXXX    |     at /usr/src/XXXXXXXX/node_modules/node-fetch/lib/index.js:239:32
XXXXXXXX    |     at <anonymous>
XXXXXXXX   |     at process._tickCallback (internal/process/next_tick.js:189:7)
XXXXXXXX    |   message: 'invalid json response body at https://XXXXXXXX/_changes?feed=longpoll&heartbeat=10000&since=486-g1AAAAIjeJyV0UsKwjAQANBgBd14Bt2LkMaMTd3YE3gFTUxCKTVZ6F5vojfRm-hNaj5dKUK7mYEhecynRgiNy0SiibHGSlUYW9rTuXblAUdi2jRNVSZ8fnSFESY5EODfj_98FzMXxaYVtkEQGCjJdFeh8MKuFVQQZEpB5qSrsPfCpRXWQchSRlLddQozdBFdXXLIzStZUEAzzWDZS7lH5eEVFhTOBQgFvZRnVF5eIUHJKZZk1a-Xd1TCXhZxIsCKHX5uU30AGd-pDw&limit=25 reason: Unexpected end of JSON input',
```

### Info
- Environment: Node.js
- Platform: Docker
- Adapter: Default
- Server: CouchDB

**Comment by nytamin** [comment]
I'm experiencing this issue as well.
I haven't been able to conclude exactly what's wrong, but I'm listing my findings below, I hope they will help with the troubleshooting:

* The error comes when the long-polled response is an empty response.
* I'm guessing that the error originates from around here:
https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-http/src/index.js#L220
* The error only comes in version 7.0.0. Version 0.4.6 seems to work fine for me.

**Comment by RAACosta** [comment]
I am having the same problem with 7.1.1.

Options to subscribe to **changes** are:

`{
since: "now",
live: true,
include_docs: true
}`

**Comment by BenLiyanage** [comment]
I'm also getting this error.

**Comment by drschwabe** [comment]
same error but remote db is a pouchb-server

**Comment by komorebi-san** [comment]
Same. 

How do you guys resolve this?
