### ISSUE TITLE
After remove conflicts and purge in couchdb pouchdb give an error in client side

### ISSUE THREAD

**Issue by goltra** [pouchdb/pouchdb#7603]
### Info
- Environment: (Node.js/browser/Ionic/Angular)
- Platform: (Chrome/FF)
- Adapter: (IndexedDB)
- Server: (CouchDB)

Hello, we have an app / web app which sync with couchdb throw pouchdb. Some databases have grown due to delete documents and conflicts. We are trying to implement a system for clean databases. First idea was backup up db, cleaning deleted document and rev_trees at server but when the client connect with phone or browser it sync again all information.
 
After this we thought should be better remove conflicts throw couch api, purge and compact (fortunatly purge is again available in couch). With this we achive reduce, at server, a db from 100Mb to 3Mb but we have a problem when we acceess with phone or browser who have to sync. The problem is different than "first idea". Remove documents don't sync and it is good. The problem is the app goes so so slow and sometimes this never finish load data. I think the problem is related with indexes.
When I access to my app with Chrome some times I get this error:

> DOMException: Failed to execute 'index' on 'IDBObjectStore': The transaction has  finished
 
Other times I get this error:

![imagen](https://user-images.githubusercontent.com/1634767/51070948-2f643c80-164a-11e9-93d9-795dbb9044b9.png)
And I have seen "status:missing" in values of array in this function:
![imagen](https://user-images.githubusercontent.com/1634767/51070964-5f134480-164a-11e9-8467-53c831dd0d54.png)

I'm going mad with this problem. I don't know if is a problem with pouchdb.

I hope you can help me.
Thanks so much.

**Comment by daleharvey** [comment]
If you were able to give us a failing reproducable case with https://pouchdb-bug-helper.glitch.me/ it would help debug the issue
