### ISSUE TITLE
Performance issue while replicating huge dataset 

### ISSUE THREAD

**Issue by mavericksthinker** [pouchdb/pouchdb#7609]
### Issue
Write the description of the issue here

### Info
- Environment: (Node.js/Hybrid apps.)
- Platform: (Android)
- Adapter: (WebSQL)
- Server: (CouchDB/Cloudant/PouchDB Server)

Hello , I am working on a project which includes replicating the localDB to cloudant. I have some issues with it:
1.As I am using websql as adapter and the nodejs on the backend of an android app , I need to use prefix to navigate the database to the data directory to be able to open the db file. Because of that when I am trying to replicate to cloudant or to any other remote pocuhDB compatible database it is not working unless I use the pouchdb,replication(local,remote,opts); This way the replication is possible but is there any way to make the replication possible from the fauxton rather than hardcoding?

Sample
----------

     let opts = {live:true,retry:true},
           Promise = require('bluebird'),
           fs = require('fs'),
           path = require('path'),
           express = require('express'),
           app = express(),
           PouchDB = require('pouchdb-core'),
           replicationStream = require('pouchdb-replication-stream'),
           memoryStream = require('memorystream'),
           log = path.join(cordova.app.datadir(),"log.txt"),
           backup = path.join(cordova.app.datadir(),"backup.txt"),
           prefix = path.join(cordova.app.datadir(),"db"),
           pouchdb = PouchDB.plugin(require('pouchdb-adapter-node-websql')).plugin(require('pouchdb- 
           adapter-http')).plugin(require('pouchdb-mapreduce')).plugin(require('pouchdb- replication')).plugin(replicationStream.plugin);
           pouchDB = pouchdb.defaults({prefix:prefix});
      let pouchHandle = require('express-pouchdb')(pouchDB,{logPath:log});
           PouchDB.adapter('writableStream',replicationStream.adapters.writableStream);
      let stream = new memoryStream();
      
     let config = pouchHandle.couchConfig;
           app.use(cors(config));
           console.log("Config file set");
           app.use('/',pouchHandle);
           server = app.listen(port).on('error',console.log);
     let db = new pouchDB('posdemo',{adapter:'websql'});
           db.changes({live: true, since:'now'}).on('change',console.log);
           pouchdb.replicate(remote,db,opts);
           pouchdb.replicate(db,remote,opts);

2.The initial replication is very slow for 100k(no attachments size of 100mb) docs it takes around 1hr 45mins to sync(through replication API of pouchDB). I went through the issues and tried to implement pouchDB replicaton stream and used memory stream replication (dump/load). It took around 45 mins by changing the batch_limit and batch_size . Is there a way to make the initial replication faster and effective. As the doc count can go way higher.

3.When I am using the db.dump(stream).Let say the doc count is 35000 it only dumps 2800 docs.This is my code for dumping:

      var backup = path.join(cordova.app.datadir(),"backup.txt");
      var ws = fs.createWriteStream(backup);
            db.dump(ws,{since:0}).then(function(res){
            console.log(res);
         }).catch(function(err){
            console.log(err)
        });

Can anyone suggest me an efficient way for this?

Any help or suggestion will be appreciated

**Comment by mavericksthinker** [comment]
Hello can anyone provide me a way?

**Comment by mavericksthinker** [comment]
@daleharvey, please can you help me with this issue?

**Comment by karlwestin** [comment]
Without looking at your app, it's hard to give you any ideas but 100k is a lot, even if the docs are small. To sync to a mobile phone it is pretty massive :)

Try to think if there are any ways you can limit the size of the data you sync?

**Comment by HarelM** [comment]
I hope this is the right place...
I'm having a similar problem, kinda.
The problem I'm facing is the following: I have a zip file which contains 127k documents - all of them are attachments.
The zip file of all of the docs is around 200Mb.
It takes around 30 minutes to populate the database - so far I have no complaints.
The problem I'm facing is the fact that after I insert all of these documents it takes around 5-10 seconds to get a document out of PouchDB - just by calling `getAttachemnt(id, id)`.
Note that it takes this amount of time on an android device. on a desktop PC it behaves well.
Below is an example of part of the data.
[IHM_00000000.txt](https://github.com/pouchdb/pouchdb/files/3429971/IHM_00000000.txt)
Are you guys aware of such performance problems when there're a lot of documents?
I'm wondering if using different wrapper to IndexDB will improve this...?

**Comment by HarelM** [comment]
I have switched to dexie and the performance has improved significantly. Import process is now a few minutes and fetch from DB is a few milliseconds. It also supports compound index which allows showing all the points that are on a map, which is very important for my app. No easy sync with the server though :-( I'll probably need to write it...

**Comment by mqtik** [comment]
I should say this with a sign:
NEVER store attachments on a database. FileSystem will do that a thousand times better.

Storing attachments in a database (any database) will constantly keep trading your old problems for a whole set of new ones.

**Comment by HarelM** [comment]
That's nice in theory, but when you need to support the offline first approach in the browser where you don't have access to the file system I can't think of another way to solve this. If you are familiar with a way to access the file system from the browser please enlighten me.
NEVER is something I would avoid saying (note here I didn't use never :-)). There are case when it's needed...
