### ISSUE TITLE
EventEmitter Possible memory leak detected.

### ISSUE THREAD

**Issue by Imogynn** [pouchdb/pouchdb#7613]
### Issue
EventEmitter Possible memory leak detected.

I have a couch that I'm syncing with. It works most of the time. I added an update rule though and I'm getting event emitter errors.

### Info
- Environment: React-Native using Expo
- Platform: Android
- Server: Couchdb

### Reproduce
My synch code:

const reservationDb = new PouchDb('reservations')
reservationDb.setMaxListeners(500)
const db = new PouchDb(`http://${base}/reservations`)

My design document:
{
  "_id": "_design/reservations",
  "_rev": "3-6d06299ebe7c65aa052d925f2da75ae2",
  "language": "javascript",
  "validate_doc_update": "\nfunction(newDoc, oldDoc, userCtx, secObj) {if (userCtx.name === 'admin') return true \n if (userCtx.name!==oldDoc.owner) \n throw({forbidden: 'You don't own this offer}) \n}\n"
}

Let me know if you'd like to me to create a small app or something. Not sure the best way to pass reasct native code to you.

Thanks

**Comment by rominf** [comment]
I think your issue deserves a better title!
