### ISSUE TITLE
Replication by selector not using index

### ISSUE THREAD

**Issue by Prabuganesan** [pouchdb/pouchdb#7615]
### Issue
In Pouchdb replication by selector not using index
### Info
- Environment: (browser/hybrid app)
- Platform: (Chrome/iOS/Android)
- Adapter: (IndexedDB)
- Server: (CouchDB)

### Reproduce
I have used selector for replication from couchdb. It is faster way compare to javascript function. But here time is problem because this selector replication not using my **index** doc. For example,I need 500 docs from 5000 couch docs then replication will complete in 5s , if couch doc count is 50000 then it will complete in 20s. Always I am filter 500 doc only but based couch doc count time will increase.
I need fixed time for filter docs from couchdb.

Any possible way is available?

This is my code 

```
let options = {
            live: false,
            retry: true,
            filter: '_selector',
            selector: selector,
            include_docs: true,
            ajax: {
                headers: {
                    Authorization: 'Basic ' + window.btoa(user.name
                        + ':' + user.password)
                }
            }
        }

        return this.db.replicate.from(this.remote, options);
```

**Comment by mjafarpour** [comment]
I have the same problem...

**Comment by sudhirvolteo** [comment]
This issue costing me lot of outage...
