### ISSUE TITLE
TypeError: Promise.resolve is not a function on pouchdb-auth

### ISSUE THREAD

**Issue by semiautomatix** [pouchdb/pouchdb#7617]
### Issue
I'm receiving the following error when using pouchdb-auth:

```
TypeError: Promise.resolve is not a function

PouchDB../node_modules/pouchdb-auth/lib/index.js.exports.useAsAuthenticationDB
/PWAProjects/pwa-tna/node_modules/pouchdb-auth/lib/index.js:63

  60 | }
  61 | 
  62 | 
> 63 | return utils.nodify(Promise.resolve().then(function () {
  64 |   // add wrappers and make system db
  65 |   if (!info.isOnlineAuthDB) {
  66 |     wrappers.installWrapperMethods(args.db, writeWrappers);

```
### Info
- Environment: React.js
- Platform: Chrome
- Adapter: n/a
- Server: CouchDB

### Reproduce
My code is as below:

```
import PouchDB from 'pouchdb';
import pouchDBAuth from 'pouchdb-auth'; 
PouchDB.plugin(pouchDBAuth);

const db = new PouchDB(
    'http://localhost:5984/accord-tna',
    {
        skip_setup: true,
        auth: {
            username: 'admin',
            password: 'password',
        }
    }
  );
db.useAsAuthenticationDB();
```

As quick check does indeed reveal Promise.resolve to be undefined using the pouchdb-promise import.

**Comment by daleharvey** [comment]
If you can reproduce a bug using pouchdb only (https://pouchdb-bug-helper.glitch.me/) then we can take a look, otherwise sounds like an issue with pouchdb-auth - https://github.com/pouchdb/pouchdb-auth

**Comment by semiautomatix** [comment]
My concern, and reason for posting here, was due to the fact that it involved two modules in the "monorepo". I'll ask on the pouchdb-auth page, though the last issue was closed two years ago.
