### ISSUE TITLE
Use with Electron: leveldown.node error: A dynamic-link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by AlexVFornazieri** [pouchdb/pouchdb#7619]
Hey guys,
Should Pouchdb work well with the electron?
How can i solve it? Thanks for any help.

### Issue
Uncaught Error: A dynamic-link library (DLL) initialization routine failed.
\\?\C:\Users\alexv\my-project\node_modules\level\node_modules\leveldown\build\Release\leveldown.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at bindings (C:\Users\alexv\my-project\node_modules\bindings\bindings.js:84:48)
    at Object.<anonymous> (C:\Users\alexv\my-project\node_modules\level\node_modules\leveldown\leveldown.js:4:46)

### Info
- Environment: node.js/renderer (browser)
- Platform: Chrome/Electron

### Reproduce
Create new electron project (or use an existing one), and try use pouchdb on renderer process
I use that boilerplate: https://github.com/SimulatedGREG/electron-vue

After install boilerplate's dependencies (with Yarn) i install pounchdb using:
```shell
yarn add pouchdb
```
and import it using:
```javascript
import PouchDB from 'pouchdb'
```

**Comment by Alecyrus** [comment]
if you want to use pouchDB in electron, you'd better use `pouchdb-node` rather than `pouchdb`. I faied thousands times to install `leveldown` when I run `yarn add pouchdb`.

**Comment by karlwestin** [comment]
Hi!
We get a lot of issues that are related to electron builds, and it's highly likely that the issue is in the build system. Unfortunately these are very hard for us to reproduce and help out with

If you're using PouchDB in the app process and not the node one, did you try using [pouchdb-browser](https://www.npmjs.com/package/pouchdb-browser) instead? It builds without leveldown 

Hope that can help you!
If not, please search other issues here, there are tons of posts where helpful people have posted what works for them

**Comment by AlexVFornazieri** [comment]
Hey @karlwestin,

I am new with PounchDB ecosystem and i a not knew about pouchdb-browser, i tried use it, and works!
I don't see need of use in main/system process of Electron, just working on renderer/app looks great!

Thanks for the tip, you helped me a lot!

**Comment by karlwestin** [comment]
Awesome! Good luck with your project!
