### ISSUE TITLE
Attachments saved from Couchbase-lite-ios v2.1.3 crashes pouchdb changes feed

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [pouchdb/pouchdb#7621]
### Issue

We are facing an issue if we add/update a document with attachments from Couchbase-lite-ios sdk v2.1.3

Error log, 

> Access to fetch at 'https://development.xxxxx.xx/xxxxsync/-mhCt_3_ukvnnadeDM2aNiY/blob_/54bfe584-4828-47ca-80bc-ecdbc4c889ff.jpg?rev=3-02ff16f1091c456018f8ac9851ec19f5d5ba509a' from origin 'https://xxxx.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
17:37:46.192 

### Info
- Environment: (Reacj.js)
- Platform: (Chrome/FF/Safari/Edge/etc.)
- Adapter: (n/a)
- Server: (CouchDB/PouchDB Server/etc.)

### Reproduce

Add an attachments from Couchbase-lite-ios sdk v2.1.3 app and unable to see the changes in desktop application which is using puchdb. But, it's working fine with the older version of couchbase-lite-ios sdk 1.4.1.

 I think it's because of blobs that we are saving from newer version.

**Comment by daleharvey** [comment]
We dont support couchbase

**Comment by ThiyagarajanShivSankaran** [comment]
@daleharvey,  If we replace the attachmentID like this then it's working,`blob_%2F54bfe584-4828-47ca-80bc-ecdbc4c889ff.jpg`. `blob_/` to `blob_%2F`.

> 'https://development.xxxxx.xx/xxxxsync/-mhCt_3_ukvnnadeDM2aNiY/blob_%2F54bfe584-4828-47ca-80bc-ecdbc4c889ff.jpg?rev=3-02ff16f1091c456018f8ac9851ec19f5d5ba509a'
