### ISSUE TITLE
PouchDB IndexedDB implementation breaks on Angular 7.2.2, Safari/Mobile Safari

### ISSUE THREAD

**Issue by jpike88** [pouchdb/pouchdb#7631]
I've raised issues:

https://github.com/angular/angular/issues/28397
https://github.com/angular/zone.js/issues/1183

Issue reproduced below (obviously, you'll need Safari to see the error)

https://stackblitz.com/edit/angular-issue-repro2-bo2cgs

Opening an IndexedDB database works, but performing a transaction on it fails with the below error:

```Error: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.```

This appears to be related to how Zone.js interacts with EventTarget. Not sure if it was worth mentioning here

**Comment by vagsa2** [comment]
@jpike88, can you provide more information about your problem and fix, because I also get this errors and didn't understand your solve in angular/angular#28397 issue?

**Comment by jpike88** [comment]
Honestly I'm not sure how I fixed it. I reinstalled dependencies, and ensured polyfills.ts was kicking in properly. I use fusebox which is way better than webpack in my opinion, made tweaking things related to globals and polyfills easy enough. If you still have issues try reproducing it and I'll see if I can identify the issue you're having
