### ISSUE TITLE
phonegap 8.2.2 build android apk not creating remote pouchdb

### ISSUE THREAD

**Issue by anilroopnarine** [pouchdb/pouchdb#7632]
### Issue
phonegap 8.2.2 build android apk not creating remote pouchdb database. both debug and signed release apks. However it works when using phonegap desktop with either chrome or developer app.

### Info
- Environment: Both windows 10 and ubuntu phonegap cli build android. 
- Platform: Android phone running Lineage OS, Fire Tablet.
- Adapter: IndexedDB
- Server: CouchDB  1.5 and 2.3
 
### Reproduce
fresh install of phonegap.
phonegap create --template hello-world

<script type="text/javascript" src="js/pouchdb-7.0.0.min.js"></script>
    <script type="text/javascript">
        app.initialize();
        var db = new PouchDB('http://triniware.com:5984/kittens');
        db.info().then(function (info) {
          console.log(info);
        })

added to index.html

phonegap build android
install debug apk and run.

database does not get created.

**Comment by anilroopnarine** [comment]
cordova-plugin-whitelist is required.
geez 2 days wasted...

**Comment by karlwestin** [comment]
wow that must have been annoying :(
thank you for posting the fix for others to find! it's really helpful!

**Comment by codegreenie** [comment]
Previous versions of Phonegap add whitelist by default. I was amused my app did not connect to the internet as well. Now i have to manually install whitelist. Too Bad Adobe.
