### ISSUE TITLE
CouchDB - PouchDB initial replication is very slow

### ISSUE THREAD

**Issue by alexpirine** [pouchdb/pouchdb#7634]
### Issue

The initial replication between CouchDB and PouchDB is very, very slow.

It seems to become very slow not because we have a lot of documents, but because these documents change frequently and have a lot of revisions.

It currently takes us about a minute. Even if the database is empty.

We tried to set `_revs_limit` to 1, compact, and we didn't notice any performance change.

What we see:

- Initially PouchDB makes a bunch of `db/_changes` queries. I don't understand: what are these for? 
- After that, it does a bunch of `db/_bulk_get` queries, with up to a few thousands of documents / revisions requests
- These `_bulk_get` queries are very slow server-side. The CPU is getting up to 100% and it takes a while to process these requests.

Why not simply query `_all_docs/include_docs=true`?

From what I understand, creating a `_bulk_get` request with thousands of ids is inefficient because it creates thousands of CouchDB queries… So why do we use it for the initial replication? Simply getting the last revision ID from `_all_docs` should be enough, shouldn't it?

### Info
- Environment: Browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB

**Comment by Lazzaretti** [comment]
I observed the same thing and in my case the problem was the change listener (`localDb.changes()`) during the sync

I got a work around for me:
1. replicate the remote db
2. then subscribe for changes
3. now sync the database with the live option
 `localDb.replicate.from(remoteDb)`

```
localDb.replicate.from(remoteDb).then(() => {
  localDb.changes({since: 'now', live: true}).on('change', ...);
  localDb.sync(remoteDb, {live: true})
})
```

In my case this change dropped the initial sync time for 400 documents from 70 seconds to 1 second

**Comment by alexpirine** [comment]
Could we reopen this?

**Comment by boaz-lachman** [comment]
Could this issue please be reopened. I have been using pouchdb for a year and the initial replication takes about 2 minutes, while using the exact same cloned db created a month ago the initial replication takes 20 seconds

**Comment by alexpirine** [comment]
Maybe we can fundraise to invest in this replication technology? We already vastly improved our first sync time by downloading read-only documents “on our own” (by bypassing PouchDB and using the continuous feed) from a separate CouchDB view.

The problem I see with PouchDB the way it is currently used, is that the syncing protocol is very generic to fit all use cases, but because of that it is extremely slow when the DB has lots of daily changes and about 10k-100k documents. And it just doesn't scale well.

**Comment by craftzdog** [comment]
I found a bottleneck in the replication process. Here is my hack.
https://dev.to/craftzdog/improve-pouchdb-s-initial-sync-with-couchdb-3x-faster-14m4

**Comment by claritysoftwaregroup** [comment]
Hi there, could you please re-open this and look at it. We are experiencing the same problem as everyone else. Any help would be welcome.

**Comment by tingyuchang** [comment]
I have the same issue. My app(extension) will get very high CPU/Mem usage on the first initialization and even daily change. The PouchDB instance was bused on handling updates. even I delete all revisions on the server-side, it does not work.

But when I updated to v7.3.0, reducing the batch size seems to help, although it will increase conflict chance, it's ok in our case

**Comment by Viatorus** [comment]
Same issue. Takes very long. There aren't multiple revisions on the server. But takes over 2 Minutes to replicate 30000 docs into an empy local DB.

**Comment by knubie** [comment]
It looks like there has been some work done in this area in [RxDB](https://rxdb.info/replication-couchdb-new.html). Perhaps this can be used to implement a custom sync method for PouchDB as well.
