### ISSUE TITLE
How do pouch users handle CouchDB authentication? [Question]

### ISSUE THREAD

**Issue by dantman** [pouchdb/pouchdb#7638]
How is everyone using pouch handling user auth?

pouchdb-authentication is missing basic things like "forgot password" and doesn't work with social logins.

superlogin is well featured and seems to work great. However due to maintenance issues it doesn't work out of the box on current Node.js. Also it's not setup to make CouchDB secure for the publicly exposed pattern that PouchDB requires.

**Comment by daleharvey** [comment]
I use https://github.com/pouchdb/pouchdb-express-router, expose the server to authenticated clients and authenticate those the same way I would do in any web app (I like passwordless logins in general), theres some examples @ https://github.com/pouchdb/pouchbase
