### ISSUE TITLE
Choice location for pouchdb-adapter-leveldb

### ISSUE THREAD

**Issue by baptistedonaux** [pouchdb/pouchdb#7640]
### Issue

I use **pouchdb-node** with **LevelDB** storage implementation. I can't find option to determine location to store database. Currently, database folder is created in current working directory.

### Info
- Environment: Node.js
- Adapter: LevelDB
- Server: CouchDB

**Comment by k-j-kleist** [comment]
Duplicate of #214 ?

**Comment by baptistedonaux** [comment]
Thanks !
