### ISSUE TITLE
Contributing: Want to use Prettier?

### ISSUE THREAD

**Issue by phil-lgr** [pouchdb/pouchdb#7650]
IMO prettier with or without eslint is a no brainer (https://github.com/prettier/prettier-eslint), it saves so much time

If you are interested... we could apply it to the repo!

we could start with something like:

```js
// .prettier.rc.js

module.exports = {
  printWidth: 80,
  useTabs: true,
    tabWidth: 2,
    overrides: [
	  {
	    files: "*.json",
	    options: {
	  	  useTabs: false
	    }
	  }
    ]
};
```

**Comment by garrensmith** [comment]
I like prettier its really cool. But at this stage we need to simplify our build process and remove some of the tooling we have. Once we have done that we can look at adding in more useful tools again.
