### ISSUE TITLE
[documentation] The Wiki page "Google Query Language Documentation" seems outdated

### ISSUE THREAD

**Issue by k-j-kleist** [pouchdb/pouchdb#7664]
https://github.com/pouchdb/pouchdb/wiki/Google-Query-Language-Documentation

seems outdated, and is probably no longer needed because of

https://github.com/pouchdb/GQL/blob/master/readme.md.

**Comment by dinaelhanan** [comment]
deleted 👍

**Comment by daleharvey** [comment]
Yeh we havent really touched the wiki in a long time, but thanks for cleaning up
