### ISSUE TITLE
PouchDb : _remote property is not properly initialized when creating multiple databases

### ISSUE THREAD

**Issue by liqueurdetoile** [pouchdb/pouchdb#7675]
### Issue
Hello,

Issue is related to #6106 db.type() deprecation

We're using "pouchdb": "^7.0.0" and "pouchdb-find": "^7.0.0" with multiple databases and a light home made ORM. The whole is in a SPA based on Vue. There's no remote sync with a CouchDB server. Databases are stored under IndexedDB. Live data is centralized in the Vuex store with local offline data stored in CouchDB. Remote data is accessible through a REST API and stored in Mysql.

When loading models, the ORM check indexes on databases to ensure databases are following schema requirements for searchable fields (obviously needed in dev and for migrations in production).

The check is made inside a Vuex async action : 
```javascript
async function initialize({state}, schema) {
  if (state.initializing || state.ready) return;

  state.initializing = true;

  let db = state.pouchdb;
  let indexes = Object.keys(schema)
    .filter(key => schema[key].searchable)
    .map(key => schema[key].key || key);
  let rawDbIndexes = await db.getIndexes(); // Here's the culprit line
  let indexed = [];

  // Fetch current index and delete them in not in model map
  for (let index of rawDbIndexes.indexes) {
    if (index.type !== 'json') continue;

    if (!indexes.includes(index.name)) db.deleteIndex(index);
    else indexed.push(index.name);
  }

  // Revive or add new indexes
  for (let index of indexes) {
    if (!indexed.includes(index)) {
      db.createIndex({
        name: index,
        index: {fields: [index]}
      });
    }
  }

  state.initializing = false;
  state.ready = true;
}
```
All is working fine except the call to `await db.getIndexes()` which triggers a deprecation warning : `db.type() is deprecated and will be removed in a future version of PouchDB`

Following stack trace, `db.getIndexes` is currently calling `isRemote` that triggers the deprecation message.

It appears that the _remote property is not properly initialized when creating more than one database at once. I presume the issue is coming from a promise because when halting with breakpoint and step process in `isRemot`e function, the problem doesn't occurs.

We have to create multiple databases because we want to enable offline mode in a multi user environment while indexing differents models schema.

### Info
- Environment: (browser)
- Platform: (Chrome)
- Adapter: (IndexedDB)
- Server: none

### Reproduce
See [https://tan-desert.glitch.me/](https://tan-desert.glitch.me/)

**Comment by lgarron** [comment]
Looks like this is still an issue?

I see it manifesting as https://github.com/pouchdb/pouchdb/issues/6449

**Comment by liqueurdetoile** [comment]
I really don't know. Due to `wontfix` status, we've dropped using indexes and we're loading data in memory to perform search.
