### ISSUE TITLE
Callback is not triggered in Google Query Language (GQL) fetch

### ISSUE THREAD

**Issue by Murugan1778** [pouchdb/pouchdb#7678]
Hi all,
       I am using the Google Query Language (GQL) for fetching the single object count in pouchdb.But callback is not triggered .My sample code looks like
   `   this.pouchdb.gql({select: "count(objectName)"}, function (err, res) {})`

**Comment by daleharvey** [comment]
GQL isnt part of core, please file against https://github.com/pouchdb/GQL, cheers
