### ISSUE TITLE
Update FAQ with leveldown info for Windows

### ISSUE THREAD

**Issue by shreeshbhat** [pouchdb/pouchdb#7680]
### Issue
While trying to do npm install pouchdb in windows, getting an error and unable to proceed with install.

### Info
- Environment: (Node.js : 10.13.0 / npm : 6.4.1 / Windows : 10.0.17763 )
- Platform: Firefox 65.0.2

### Error log
```
npm install pouchdb --save

> leveldown@3.0.0 install C:\Data\Projects\project\node_modules\leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.13.0 runtime=node arch=x64 platform=win32)

C:\Data\Projects\project\node_modules\leveldown>if not defined npm_config_node_gyp 
(node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\shreesh\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:606:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Data\Projects\project\node_modules\leveldown
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by abhinavsagar** [comment]
Just use
`npm install`

**Comment by shreeshbhat** [comment]
Added the following line to my package.json and still getting the same error.
``` "pouchdb": "^7.0.0"```
Download page from main website mentioned to do npm install --save pouchdb.

**Comment by dinaelhanan** [comment]
@shreeshbhat maybe try sudo? I know its basic but it usually works

**Comment by shreeshbhat** [comment]
I believe there is no sudo in windows.

**Comment by dinaelhanan** [comment]
@shreeshbhat Yes but you can run as admin by searching cmd in the search bar, right click command prompt and select run as administrator

**Comment by shreeshbhat** [comment]
Aah good suggestion!
Tried that and got the same error.

**Comment by dinaelhanan** [comment]
:( try reinstalling node. I get the same type of errors and using sudo/admin or reinstalling node usually fixes it. Let me know how it goes

**Comment by shreeshbhat** [comment]
:( 
Thank you so much for quick responses! Really appreciate it.
I did read somewhere that downgrading node version helps. 
I just wanted to try to work with LTS one.
Will work with pouchdb-browser till this is resolved.
This issue should be mentioned in download page or FAQ section I feel.

**Comment by dinaelhanan** [comment]
Downgrading node does help, but I agree this should be on the FAQ. We might need more contributors to put in their thoughts/tips on how to resolve this though as I'm pretty new to this. Hope it works out :) @shreeshbhat

**Comment by karlwestin** [comment]
yeah no this problem is a bit more complicated unfortunately
I haven't dug too deep but it's related to the python version you have installed. Node-Gyp, which builds native extensions (leveldown is a native extension) uses python for something. So what's happening here is that leveldown fails to build because [node-gyp is only compatible with python 2.7](https://github.com/nodejs/node-gyp#on-windows)

If you have time, they make the suggestion to install windows build tools (`npm install --global --production windows-build-tools`, *has to be ran as admin*)

Listing this in a FAQ sounds great, including the error message so people can google it, point to that place in the node gyp docs and suggest the alternative to use `pouchdb-browser` if the user is not able to make it work.

**Comment by shreeshbhat** [comment]
Great news!
Running ``` npm install --global --production windows-build-tools``` helped! 🎉 
It successfully downloaded & installed python2.7 and configured Visual Studio Build Tools.
I was able to execute ```npm install pouchdb --save``` without any issues.
I had python3 earlier and maybe that's why it was not working.
Thank you, karlwestin.
Please update download page / FAQ with this info.

**Comment by shreeshbhat** [comment]
You can go ahead and close this issue once that page is updated.
I noticed that there was a similar issue #7595 reported under closed issues.
It was bit hard to find. Thanks again for the prompt replies. 
Happy pouching!

**Comment by karlwestin** [comment]
Awesome! Glad to hear it worked! Gonna see if i can get around to this later today or if anyone else is first :)

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/fdc32782ca574d0b7e9c9de284c10c68a7bad689

**Comment by shreeshbhat** [comment]
@daleharvey : Wow, a fix already got merged into master for docs? Awesome!
Just a heads up, I think there might be something wrong with the way cache is being handled for docs.
This section about windows error is not showing up for me.

![Screen Shot 2019-03-14 at 9 28 28 AM](https://user-images.githubusercontent.com/13938682/54360724-dca00480-463b-11e9-8952-73a063ff4f1e.png)
