### ISSUE TITLE
Sync attachments from CouchDB : Error in fetchData function response.buffer() not a function

### ISSUE THREAD

**Issue by jsantacruz-go** [pouchdb/pouchdb#7688]
### Issue
Sync with attachments fails-->
fetchData throws error at calling response.buffer()

### Info
- Environment: Ionic 4, PouchDB 7.0, CouchDB 2.3.1 on Ubuntu Server
- Platform: Android
- Adapter: IndexedDB
- Server: CouchDB 2.3.1

### Reproduce
To reproduce this issue you have to follow this steps:

1. Enable any DB Remote CouchdDB 
2. Save an attachment in Android PouchDB
3 Call PouchDB.replicate.to ionic app to replicate document to Remote CouchDB
4 Erase PouchDB on Android
5 Replicate to new PouchDB the documents with attachments from CouchDB

I found this on the code 

function fetchData(filename) {
        var att = atts[filename];
        var path = encodeDocId(doc._id) + '/' + encodeAttachmentId(filename) +
            '?rev=' + doc._rev;
        return ourFetch(genDBUrl(host, path)).then(function (response) {
          if (typeof process !== 'undefined' && !process.browser) {
            return response.buffer();
          } else {
            /* istanbul ignore next */
            return response.blob();
          }

So I solve this issue on my environment by forcing the response to be a blob(), I don't know if this could be a problem in other platforms, but for Ionic it works.

Also had to change (remove) some code that has a TODO comment, // TODO: Can we remove this?

For me this solve everything, my app is working fine but I think you should check that part so we can have a official working version of PouchDB for Ionic 4.

Hope I can help you in the future.

**Comment by CharlesGrimont** [comment]
Hi !

Any update about this ??????

**Comment by sansato** [comment]
See #7727

**Comment by juanes1511** [comment]
Hi, I haven't tried the solution of #7727 that posts @sansato. I think it will works.. 
The thing here is that I found some commented code and todo's that can be removed or changed to works with Ionic and probably other platforms.
I think the use of attachments should work no matter what, so why don't change it?

I don't know I'm kind of newbie in pouchdb so maybe you people know better about this kind of changes..

Anyway, just want to help the community..
