### ISSUE TITLE
pouchdb-find createIndex adds the index as doc in the db

### ISSUE THREAD

**Issue by dnhyde** [pouchdb/pouchdb#7696]
### Issue
createIndex() of pouchdb-find is creating the desired indexes
 *BUT*
 it also adds the index as a doc to the collection on which it creates the index. 

### Info
- Environment: browser
- Platform: FF
- Adapter: IndexedDB

Is this an intended behaviour?
Am I missing something?
Is there some pouchdb-find docs where this behaviour is documented?

If this is unclear I can provide a codesandbox.
Thanks!

**Comment by dnhyde** [comment]
Should have done more research sorry... Apparently this is a [known issue](https://stackoverflow.com/questions/25728903/pouchdb-exclude-design-documents-when-using-autogenerated-uuid). Can you consider adding it to the documentation when explaining createIndex?

**Comment by garrensmith** [comment]
Every index is stored as a design doc. That is how pouchdb-find works. Are you saying that when you do a query with pouchdb-find that the design doc for that index also appears in the results or rather that the design doc is not returned as part of allDocs?

**Comment by dnhyde** [comment]
I am saying that allDocs is said to be the "unsung hero" of pouchDB but there is no strategy to avoid to return the design docs.
I have 5 indexes, but I can't give them custom names (since pouchdb-find APIs allows to change at most the ddoc) and I definitely don't want to filter them out with separate queries using "startKey" and "endKey".
As a consequence allDocs() is not so useful in my case, maybe I am misunderstanding allDocs... What I wanted was a way to query with allDocs() that does not return the design docs.

**Comment by garrensmith** [comment]
The design docs shouldn't be returned for a pouchdb-find query. I did do a fix awhile ago to stop that happening. So could you check you have the latest pouchdb-find. Then if you have the latest and its still a bug could you create a reproducible setup

**Comment by dnhyde** [comment]
I have the latest pouchdb-find, and the pouchdb-find query does not return the design docs so this works fine.
However a custom `findAll()` method with pouchdb-find is slower than `allDocs()` from pouchdb. That is why I was trying to use `allDocs()` from pouchdb but `allDocs()` does return the design docs.

**Comment by sansato** [comment]
Does the "slower" symptom persist after the first query?  It's expected that the first find can't resolve until all the documents have been processed through the indexer.  I'd hope it would be faster after that, as long as your query is searching for something that can resolve efficiently with the indexed values.

(just as with any data indexer... by example: don't expect to search by the second-indexed-field only, but field-1 + field-2 equality searches, or field-1 equality should be fast).

**Comment by dnhyde** [comment]
Ok still quite slow but thanks for you help!

**Comment by sansato** [comment]
I heard there was a problem discovered ( @daleharvey ?) where intended design for findAll() wasn't executed right , would explain the performance issue described here
