### ISSUE TITLE
Documentation error: use and abuse (mostly abuse) of _id

### ISSUE THREAD

**Issue by Richie765** [pouchdb/pouchdb#7697]
### Issue
I admire very much this project, and I think it should be used more often than it does. However every time when I read the Guides and Docs I cringe when I read we should take "advantage" of the `_id` and set it to `new Date().toJSON()`. I think it's obvious that this is a terrible idea since this will invariably create duplicate keys.

Also using the `_id` for one-many relationships is usually a bad idea because `_id` cannot be changed afterwards.

Are these recommendations leftovers from when there were no proper secondary indexes? Is there a reasons why secondary indexes should not be used for it instead?

IMHO any field should have only one single purpose. In this case identifying a record. In my experience, any added "smartness" will invariably bite sooner rather than later.

I'm not trying to open a can of worms here :fearful:.  But I think the docs could be updated a bit so it would send us in a better direction. If appropriate it could be modified to recommend secondary indexes instead?

### Reproduce
Running the following on the browser console:
```
{let last, conflicts = 0; for(let i = 0; i< 1000; i++) { const id = new Date().toJSON(); if(last === id) conflicts++; last = id; }; console.log(conflicts);}
```
On my laptop shows around 997 conflicts so a failure guarantee.

**Comment by garrensmith** [comment]
Can you provide an example of where it recommends using a date for Id.

Any changes to the documentation would be appreciated. The documentation is stored in the main repo. It’s all markdown.


________________________________

**Comment by Richie765** [comment]
Sure, here are a few that I could find:
* https://pouchdb.com/guides/bulk-operations.html - the example here has no chance of working
* https://pouchdb.com/2014/05/01/secondary-indexes-have-landed-in-pouchdb.html
* https://pouchdb.com/getting-started.html
* https://pouchdb.com/2014/06/17/12-pro-tips-for-better-code-with-pouchdb.html - Point #7, recommends way too much `_id` smartness IMHO

I wouldn't mind changing the docs, but I think it's good to share some ideas first about how it should look like and if secondary indexes are the way to go.

**Comment by Richie765** [comment]
Oh well, the first one actually does work, as I just saw in the live example. However there is only 2ms room on my computer. With a different faster computer or faster DB backend this would fail. Also when the records are generated up-front (not one by one) it would also fail.

**Comment by garrensmith** [comment]
I've given these a quick look. For https://pouchdb.com/guides/bulk-operations.html we can probably change it. 

The other ones I don't really see a problem. The pro tips is a little extravagant but it is a good way for using all docs.
