### ISSUE TITLE
Replication missing documents

### ISSUE THREAD

**Issue by ahallez** [pouchdb/pouchdb#7700]
### Issue
I'm using pouchdb to set up filtered replication between two couchdb database, one running in the cloud (source) and the other on the local machine.
It happens quite often that the replication finishes without error, but after checking the replicated data, some documents are missing.

When this happens, repeating the replication from scratch, again finishes with missing documents, but typically other documents than the previous try.
Until now I haven't been able to find a logical explanation for the missing documents as they seem to be random.

This is the code for the replication process:

`const db = new PouchDB(app.get('scoreExpress.sync.localDB'));
    const remoteDB = new PouchDB(app.get('scoreExpress.sync.remoteDB'));

    const selector = {
      '$or': [{
        'eventId': ctx.req.params.eventId,
      }, {
        '_id': {'$in': [ctx.req.params.eventId, ctx.req.params.userId]},
      }],
    };

    remoteDB.replicate.to(db, {
      selector: selector,
    }).on('complete', function(ee) {
      console.log(ee);
      ctx.send('successfully imported');
    }).on('error', function(err) {
      console.log(err);
    });`

### Info
- Environment: nodejs 9
- Platform: windows 10
- Adapter: Not applicable
- Server: CouchDB

**Comment by karlwestin** [comment]
There's always a chance that there's a bug with using filtered replications this way.

For us to be able to help, we really need some more things from you:

- How do the documents look?
- What are examples of actual parameters you provide in the selector?
    that is.. "from this set of 10 docs, if i provide parameters a, b and c, i expect those 3 docs to be replicated but i only see those 2"?
- Does this bug happen when you run the replication PouchDB -> PouchDB as well?
- Does it happen when you run against a CouchDB instance (not using the cloud provider)

**Comment by BeatriceThalo** [comment]
Is there a way to filter replication from couch to couch through fauxton?
Using fauxton to replicate the entire gp3-proposal_db to a new local couch database successfully copies all 9,660 + 11,011.
Our couch server has only filled 60% of its storage space.
We just started seeing the incomplete filtered replication this week.

Below are my mismatched filtered replication results, using a similar chunk of code to OP:

![db stats](https://user-images.githubusercontent.com/17069266/56691410-e04c8f80-66ad-11e9-8e6e-374ec041bec6.png)
![fauxton query result](https://user-images.githubusercontent.com/17069266/56690410-63b8b180-66ab-11e9-8ae2-e9944c79a53c.png)
![web replication result](https://user-images.githubusercontent.com/17069266/56690422-687d6580-66ab-11e9-81d5-25cd2af665b0.png)
![web missing ids](https://user-images.githubusercontent.com/17069266/56690426-6a472900-66ab-11e9-9bab-9777252a2158.png)
![android replication result](https://user-images.githubusercontent.com/17069266/56690429-6c10ec80-66ab-11e9-86e8-4b7db621e288.png)
![replicate command](https://user-images.githubusercontent.com/17069266/56690991-c52d5000-66ac-11e9-9a1b-fd463836d297.png)

**Comment by BeatriceThalo** [comment]
Googling from May 2015 [question](https://forums.couchbase.com/t/string-seq-breaks-couchdb-compatibility/3881/3), similar symptoms:
"Looks like the recent-changes cache gets out of date, since that doc should be showing up (and does after restarting the gateway, you say.)"

**Comment by BeatriceThalo** [comment]
More trial results:

Having 144 local out of 170 remote documents, then raising the `batch_size` to 33 (`batches_limit`=7) still completes with 0 docs_written, but

having 0 local out of 170 remote documents, and using that higher `batch_size` completes with 170 docs_written, then

repeating the 0/170 but with throttled down network speed to fast 3G, only writes 162.

**Comment by BeatriceThalo** [comment]
Is the last fauxton changes feed seq so low (402 vs 35648) just because there is no pagination in the UI?

![fauxton changes log](https://user-images.githubusercontent.com/17069266/56746196-bb0d5f00-6749-11e9-805a-cd7d4e2dd65a.png)

**Comment by BeatriceThalo** [comment]
"By default NGINX responds with status code 503 (Service Temporarily Unavailable) when a client exceeds its rate limit." But I am not getting any 503s or errors.

What is the default replicate `timeout` length and what happens if it does timeout?

![replication options](https://user-images.githubusercontent.com/17069266/56750866-b5684700-6752-11e9-90ef-1c2acbcb08a8.png)

**Comment by BeatriceThalo** [comment]
I'm not manually setting any _changes checkpoints, like issue #3999, although may be relevant

**Comment by BeatriceThalo** [comment]
Perhaps I'll just try splitting my data up into a smaller current working db and an archive db to reduce the document count needing to be synced.

**Comment by soubhikchatterjee** [comment]
I am also facing the same issue of missing documents when trying to sync my local data using pouchdb to my remote couchdb server. The data also disappears from the remote couchdb.

It looks like a bug in the sync function.
