### ISSUE TITLE
Not working on iOS with Ionic 4

### ISSUE THREAD

**Issue by matthiasunt** [pouchdb/pouchdb#7701]
### Issue
It seems that PouchDB is not working on an iOS emulator (probably neither on a real device) using Ionic 4 with [Capacitor](https://capacitor.ionicframework.com/docs/ios/). However everything works as expected on Android and in the browser.

The replication **pauses** and returns the following object:
```
{  
   "result":{  
      "ok":false,
      "start_time":"2019-03-26T17:39:22.136Z",
      "docs_read":0,
      "docs_written":0,
      "doc_write_failures":0,
      "errors":[  

      ],
      "status":"aborting",
      "end_time":"2019-03-26T17:39:24.247Z",
      "last_seq":0
   }
}
```
I tried to find out more via the `PouchDB.debug()` module, but I am only getting the following error:
`pouchdb:api https://user:password@couchdbhost/database +422ms id error`

### Info
- Environment: hybrid app (Ionic 4.1.2)
- Platform: iOS with Capacitor (1.0.0-beta.19)
- Adapter: IndexedDB
- Server: CouchDB (2.3.0)

### Reproduce
`ionic start pouchcap blank`
`cd pouchcap`
`npm run build`
`npm install --save @capacitor/cli @capacitor/core`
`npx cap init pouchcap com.pouchcap.app`
`npx cap add ios`

_Install and add PouchDB to the project_
_Sync local- with remote DB_

`ng build`
`npx cap sync`
`npx cap open ios`

_Run App on Emulator_

What else could I try/what could be the issue?

#### Edit
- Same issues with cordova-sqlite-storage
- Same issues with Cordova

**Comment by BDAinc** [comment]
I understand you need to use one of the SQLite adapters
https://pouchdb.com/adapters.html

**Comment by matthiasunt** [comment]
> I understand you need to use one of the SQLite adapters
> https://pouchdb.com/adapters.html

I tried it with [cordova-sqlite-storage](https://github.com/xpbrew/cordova-sqlite-storage) with no success (same issue).

**Comment by BDAinc** [comment]
For Ionic, use the Ionic CLI:
ionic plugin add cordova-plugin-sqlite-2

You use it?

https://www.npmjs.com/package/cordova-plugin-sqlite-2

**Comment by matthiasunt** [comment]
> For Ionic, use the Ionic CLI:
> ionic plugin add cordova-plugin-sqlite-2
> 
> You use it?
> 
> https://www.npmjs.com/package/cordova-plugin-sqlite-2

I tried. I still get the following error: `id error {"status":0,"name":"unknown"}`.
Apart from this I assume, that indexed db should work without any problems.

**Comment by BDAinc** [comment]
> > For Ionic, use the Ionic CLI:
> > ionic plugin add cordova-plugin-sqlite-2
> > You use it?
> > https://www.npmjs.com/package/cordova-plugin-sqlite-2
> 
> I tried. I still get the following error: `id error {"status":0,"name":"unknown"}`.
> Apart from this I assume, that indexed db should work without any problems.


I think we should try to deploy on another framework other than ionic. If the problem in cordova is sad, because there is a possibility that I will also come across with it

**Comment by matthiasunt** [comment]
This issue can be closed. Everything worked as expected after I ran `add-cors-to-couchdb` again.
However, a more meaningful error message would have been helpful.

**Comment by BDAinc** [comment]
> Эта проблема может быть закрыта. Все заработало, как и ожидалось, после того, как я `add-cors-to-couchdb`снова побежал . 
> Тем не менее, более значимое сообщение об ошибке было бы полезно. 
> @BDAinc все отлично работает с PouchDB 7.0.0, индексированными БД и Ionic.

nice!

**Comment by BDAinc** [comment]
maybe you know how solve my problem?
https://github.com/pouchdb/pouchdb/issues/7711

**Comment by pubkey** [comment]
@matthiasunt which pouchdb adapter did work for you?

**Comment by matthiasunt** [comment]
> @matthiasunt which pouchdb adapter did work for you?

I did not specify any adapter (so PouchDB selects an adapter depending on the platform). I'm currently using PouchDB 7.2.2
