### ISSUE TITLE
How to remove error while installing pouchdb?

### ISSUE THREAD

**Issue by BDAinc** [pouchdb/pouchdb#7703]
I find an error during installation

`sudo npm install --save pouchdb`

```
npm ERR! code 1
npm ERR! Command failed: git clone --mirror -q git://github.com/xiangpingmeng/plist.js.git /home/anonim/.npm/_cacache/tmp/git-clone-9b3562f2/.git
npm ERR! /home/anonim/.npm/_cacache/tmp/git-clone-9b3562f2/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anonim/.npm/_logs/2019-03-28T14_26_33_208Z-debug.log

```
I was trying to reinstall npm and clean the hash. Without results
How to solve my problem?

**Comment by karlwestin** [comment]
There's many things going on here and i'm not sure it's PouchDBs fault.

One thing seems to be that your `npm` might be misconfigured.
Do you have any special reason to run `npm install` with sudo? That's a bit unexpected and not recommended by npm themselves

As a first step, i'd recommend you to look into configuring npm without sudo. This is really system specific so we can't help you much here, but [maybe this link is useful](https://timonweb.com/posts/install-npm-packages-without-sudo/)?

Hope that helps, please post back after!

Thanks :)

As a sidenote, that dependency does not seem to be a part of PouchDBs tree. I wonder if it could possible be a part of NaN somehow? Anyone else knows?
