### ISSUE TITLE
How import cordova-plugin-sqlite-2?

### ISSUE THREAD

**Issue by BDAinc** [pouchdb/pouchdb#7711]
I use monaca / cordova based on vuejs. After installing the plugin cordova-plugin-sqlite-2, I try to connect it, but I see an import error. What can be the problem?

**Comment by matthiasunt** [comment]
Can you add the error?

**Comment by BDAinc** [comment]
> Вы можете добавить ошибку?

I suspect that this problem is due to the fact that Cordova plugins do not work in the browser
