### ISSUE TITLE
Invalid SSL certificate for https://pouchdb.com/static/favicon.ico

### ISSUE THREAD

**Issue by akiyanovskiy** [pouchdb/pouchdb#7726]
### Issue
When I try to load pouchdb.com favicon (in my tab management extension), is gives an error:
Failed to load resource: net::ERR_CERT_DATE_INVALID

The same can be reproduced when loading the [favicon URL](https://pouchdb.com/static/favicon.ico) in a browser:

[Chrome](https://i.imgur.com/qq8K7Zs.png)
[Firefox](https://i.imgur.com/DE3rNnq.png)

Best regards,
Andrey.

**Comment by assemblethis** [comment]
Yes, the certificate expired April 12th, 2019. Can someone look into this and renew it, please?

**Comment by daleharvey** [comment]
Thanks for the heads up, updated and set up autorenew so hopefully should be good now
