### ISSUE TITLE
PouchDB did not sync docs with attachments

### ISSUE THREAD

**Issue by nofear87** [pouchdb/pouchdb#7727]
As soon as my doc has an attachments pouchdb did not sync it. As soons as I delete the attachment from doc via fauxton the sync is done correctly.

I always see a pending request to the relating database changes feed.

After enable debug I found the following:

> pouchdb:api http://192.168.21.155:35986/jobs_9303 +64ms getAttachment error TypeError: response.buffer is not a function
>     at index-browser.es.js:7100
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
>     at Object.onInvoke (core.js:4749)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)
>     at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:141)
>     at zone.js:831
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
>     at Object.onInvokeTask (core.js:4740)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
>     at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:191)

 I use V7.0 with CouchDB V2.3.0

**Comment by CharlesGrimont** [comment]
if you are using angular 6 & 7 or Ionic 4  you have to declare into your polyfill.ts the following code

```
(window as any).global = window;
(window as any).process = {};
(window as any).process.nextTick = setTimeout; 
window["browser"] = true;
```

This will prevent pouchDB from using response.buffer() and it will use repsonse.blob() instead.

**Comment by paolosanchi** [comment]
instead of
window["browser"] = true;
i added this and worked:
(window as any).process.browser= true;
