### ISSUE TITLE
Where can I get all error code list of pouchDB?

### ISSUE THREAD

**Issue by zhaoyi0113** [pouchdb/pouchdb#7729]
It is more like a question rather than issues.
I am using `pouchDB` 7.0 and I wonder where I can get all error code list. I don't see that in the doc.

**Comment by daleharvey** [comment]
@zhaoyi0113 https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-errors/src/index.js is the full list

**Comment by zhaoyi0113** [comment]
I got an error like below but I don't see code 11 defined in the list. 

```
code: 11
message: "Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing."
name: "InvalidStateError"
```
