### ISSUE TITLE
Lets do automated releases

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#7733]
So it will be coming up a year since a release which is not great, when we devised the rather hefty release process including a blog post etc it was when this project had much higher traffic.

Given the traffic these days I think it makes much more sense for us to to a release on every commit, probably using something like https://github.com/semantic-release/semantic-release

**Comment by garrensmith** [comment]
+1 on that


________________________________

**Comment by k-j-kleist** [comment]
Aside: If the world has passed "peak pouchdb" - what is used instead nowadays?
