### ISSUE TITLE
Dynamic headers

### ISSUE THREAD

**Issue by Estman** [pouchdb/pouchdb#7736]
Hello,
I'm trying to find a way to add headers dynamically. Our authentication scheme requires headers adjustment periodically. 

```typescript
let db = new PouchDB('MyLocalDb');
let remoteUrl = new PouchDB(remoteUrl, { headers: { authorization: 'Bearer ' + token });
db.replicate.to(remoteUrl, {live: true});
```

Thank you.

**Comment by daleharvey** [comment]
You can specify a fetch function when you open a db @ https://pouchdb.com/api.html#create_database
