### ISSUE TITLE
Why I'm having leveldown@3.0.0 in my package-lock.json?

### ISSUE THREAD

**Issue by wintercounter** [pouchdb/pouchdb#7752]
### Issue
`5.0.1` should be the included version
Contents of my `package-lock.json`:
```
{
   "pouchdb": {
      "version": "7.0.0",
      "resolved": "https://registry.npmjs.org/pouchdb/-/pouchdb-7.0.0.tgz",
      "integrity": "sha512-vVZyn6SmVxYLbUmzQwU5nW1APIq/sAJ13DlYZqIJRJUUUtGy3X0F79G9/3d9StvJwfWBA/aMGPnRV2eQAp+MKA==",
      "requires": {
        "argsarray": "0.0.1",
        "buffer-from": "1.1.0",
        "clone-buffer": "1.0.0",
        "double-ended-queue": "2.1.0-0",
        "fetch-cookie": "0.7.0",
        "immediate": "3.0.6",
        "inherits": "2.0.3",
        "level": "3.0.2",
        "level-codec": "7.0.1",
        "level-write-stream": "1.0.0",
        "leveldown": "3.0.0",
        "levelup": "3.0.1",
        "ltgt": "2.2.1",
        "node-fetch": "^2.0.0",
        "readable-stream": "1.0.33",
        "spark-md5": "3.0.0",
        "through2": "2.0.3",
        "uuid": "3.2.1",
        "vuvuzela": "1.0.3"
      },
}
```

Because `3.0.0` is failing to build on Node 12 and I can't seem to figure out what is causing it. Any ideas?

### Info
- Environment: Node.js 12

### Reproduce
For me it's just a simple install. Might be some other dependency is interfering somehow?

**Comment by jeremad** [comment]
https://github.com/pouchdb/pouchdb/issues/7746

**Comment by taschana** [comment]
https://github.com/pouchdb/pouchdb/issues/7754#issuecomment-490027073

**Comment by garrensmith** [comment]
This is fixed in master https://github.com/pouchdb/pouchdb/issues/7752

**Comment by wintercounter** [comment]
Yeah, but it seems like it's really hard to release 7.0.1 with it...

**Comment by taschana** [comment]
Exactly. I have stopped trying to work with PouchDB until the installation problems (old dependencies that don't compile with newest NodeJS) aren't fixed.
