### ISSUE TITLE
pouchdb-server crashes due to request containing invalid rev

### ISSUE THREAD

**Issue by kwpeters** [pouchdb/pouchdb#7756]
### Issue
When POSTing to `_bulk_get`, an invalid rev causes PouchDB Server to crash.

### Info
- Environment: Node.js v8.11.1
- Platform: No browser involved. Both client and server running in Node.js v8.11.1.
- Adapter: LevelDB
- Server: PouchDB Server

### Reproduce

All of the code needed to reproduce this issue can be found in [this repo](https://github.com/kwpeters/pouchdbserver-invalid-rev).  I did not use glitch.me in order to demonstrate the server crash.

1.  Start PouchDB Server.
    ```
    pouchdb-server --port 3030 --dir ./dbs
    ```
    In the sample repo, this can be done with `npm run start-server`.

2.  Run the code found in [this file](https://github.com/kwpeters/pouchdbserver-invalid-rev/blob/master/src/invalid_rev_post.js)

    This code sends a POST request to the `_bulk_get` endpoint.  The code demonstrates that when `rev` is set to a valid value, the request succeeds. But, when `rev` is set to an invalid value, it causes the PouchDB Server to crash.

3.  Observe that the second POST request causes the PouchDB Server to crash with the following error and stack trace:
    ```
    Error: Unable to resolve latest revision for id person_1, rev 1-ecdf613faa5b4ba68c610c4d54dc0bca
        at Object.latest (/Users/kwpeters/dev/pouchdb_invalid_rev/node_modules/pouchdb-merge/lib/index.js:462:9)
        at /Users/kwpeters/dev/pouchdb_invalid_rev/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:445:42
        at /Users/kwpeters/dev/pouchdb_invalid_rev/node_modules/sublevel-pouchdb/lib/index.js:245:9
        at /Users/kwpeters/dev/pouchdb_invalid_rev/node_modules/sublevel-pouchdb/lib/index.js:76:13
    ```

    Granted, the request is invalid, but I would expect the server to return an appropriate error rather than crash.

I have created [a duplicate issue in the pouchdb-server repo](https://github.com/pouchdb/pouchdb-server/issues/391), because that is probably the more appropriate place for it.

**Comment by garrensmith** [comment]
I'm closing this based on the pouchdb-server issue.

**Comment by mohlsen** [comment]
See https://github.com/mohlsen/pouchdb/commit/38fefe4ddf330494500d8fcde6b8b7ede0fc324e commit above for a proposed fix here in PouchDB as opposed to in pouchdb-server.

We tried to fix it in https://github.com/pouchdb/pouchdb-server/issues/391#issuecomment-507383847 but that proved to be a dead end. I did add some [UT's to pouchdb-server](https://github.com/mohlsen/pouchdb-server/commit/78ce9679d4eea41b3ae87c5eef579cad9f60e194) to illustrate the issue.  

Note in the unit test expectations in https://github.com/mohlsen/pouchdb/commit/38fefe4ddf330494500d8fcde6b8b7ede0fc324e , the results from the `http` and `local` adapters is different for [bad revisions](https://github.com/mohlsen/pouchdb/commit/38fefe4ddf330494500d8fcde6b8b7ede0fc324e#diff-e75ff53009a5cccb6379eea89b26a646R88) and also for these [non-existing revisions](https://github.com/mohlsen/pouchdb/commit/38fefe4ddf330494500d8fcde6b8b7ede0fc324e#diff-e75ff53009a5cccb6379eea89b26a646R134). These responses should be the same I imagine, but that is a much larger issue to fix, and would have backwards compatibility issues (people with code expecting the bad behavior).

Does this seems like the right fix? Thoughts? Suggestions? Did I miss anything?

**Comment by garrensmith** [comment]
I'm going to reopen this ticket for more discussion

**Comment by mohlsen** [comment]
So @garrensmith what are the thoughts on this fix in PouchDB itself? I'll submit PR so it might be easier to see.  Can update if necessary.
