### ISSUE TITLE
Pouchdb + CouchDB document changed event is missing some documents actually got changed

### ISSUE THREAD

**Issue by freakeinstein** [pouchdb/pouchdb#7758]
### Issue
Pouchdb is missing some documents to trigger "change" event. I am using CouchDB backend. When I insert new documents, I expect the change event to happen. I was inserting documents at a rate of 100 docs/second. PouchDB fails to generate event for all documents. But when I did insert at a rate of 50 docs/second, pouchDB correctly generates events. My point is, pouchDB shouldn't be missing data to keep up, instead it can slow down the process, I think that's the right way. 

### Info
- Environment: Node.js
- Platform: Mac OS Mojave
- Adapter: 
- Server: CouchDB

### Reproduce
Insert bulk documents say, 100 docs / sec. Listen to `change` event and count documents. Compare it with count of docs in DB.

**Comment by sansato** [comment]
Can you reproduce with batch of 100 or 200 (minimal) documents?  Did you verify api calls sent to the couchdb server don't have filter settings?

With smaller reproduce, find a way to call the couchdb http api's changes endpoint directly and verify whether you see all the expected changes coming from server (without pouchdb).  Maybe you need to find client/request combination like SSE to have clear access to the data.

BTW, you should report the server version number.  If the couchdb changes API misses events, you should report it to the couchdb project, not here.  If PouchDB is missing events found in the raw changes API response, go verify your replication/_changes listener doesn't have filtering implied by its settings. 

Once you've done troubleshooting as above, you'll either have a solution or important details for further followup.  Please post your findings.
