### ISSUE TITLE
How I can using pouchdb in windows?

### ISSUE THREAD

**Issue by BDAinc** [pouchdb/pouchdb#7759]
I am trying to install pouchdb using npm for my Monaca project. But I encounter errors during installation. In particular, when compiling levelodown3.0

What can I do to run pouchDB on windows?

**Comment by pubkey** [comment]
Which node-version do you have?
Might be related to https://github.com/pouchdb/pouchdb/issues/7754

**Comment by BDAinc** [comment]
> Which node-version do you have?
> Might be related to #7754

v10.13.0

**Comment by broerse** [comment]
I have the same problem but can do `npm install leveldown` by hand so it seems the version specified by PouchDB does not include the compatible binary for node 10 on Windows. Can we release a PouchDB version with the correct leveldown version for windows users?

**Comment by garrensmith** [comment]
Should be fixed in master and I'll try and get a release out soon.

**Comment by BDAinc** [comment]
> I have the same problem but can do `npm install leveldown` by hand so it seems the version specified by PouchDB does not include the compatible binary for node 10 on Windows. Can we release a PouchDB version with the correct leveldown version for windows users?

```
npm install -g node-gyp
npm install -g leveldown
npm install --save pouchdb
```

Solve problem in win10

**Comment by garrensmith** [comment]
New release is out and should fix this.
