### ISSUE TITLE
alternatives to CORS PUT for _local ?

### ISSUE THREAD

**Issue by jnorthrup** [pouchdb/pouchdb#7760]
why must replication store _local records via PUT to the source db?

is there a pouchdb option setting or a hook i can substitute for the _local records to reside somewhere else?

syncronizing thousands of updates per month across thousands of users seems like a great offline-first usecase, except the 6+ zeros of local PUT implications.

**Comment by garrensmith** [comment]
You can say where checkpoints are stored, either source or on target. YOu do have to have a checkpoint saved somewhere so that when replication continues it doesn't start from the beginning.
