### ISSUE TITLE
undefined is not an object(evaluating 'value[key]')

### ISSUE THREAD

**Issue by gaodeng** [pouchdb/pouchdb#7761]
call pouchdb.find on change callback cause this issue
![Simulator Screen Shot - iPhone X - 2019-05-16 at 19 30 44](https://user-images.githubusercontent.com/1118249/57850757-53f73d80-7811-11e9-8c74-1fe21a4fa00b.png)

**Comment by gaodeng** [comment]
?

**Comment by gaodeng** [comment]
?

**Comment by gaodeng** [comment]
bot

**Comment by karlwestin** [comment]
closing because there's no more info coming
seems like our stalebot is misconfigured
