### ISSUE TITLE
Unable to access same SQLite databases from UIWebView and WKWebview

### ISSUE THREAD

**Issue by omargon** [pouchdb/pouchdb#7770]
### Issue
We are in the process of migrating our mobile app from Ionic v1 to the latest version of Ionic. We are planning the following migration steps:

1. Migrate our existing stored data from WebSQL or IDB to SQLite in both IOS and Android for  stored data continuity
2. Switch to WKWebview from UIWebview for IOS builds
3. Full migration and re-write to the latest Angular/TypeScript/Ionic versions

When testing step 1 of this migration process without switching IOS web view everything seems to work fine. We can continue to access the existing data via PouchDB specifying the SQLite adapter. But after we switch to WKWebview when we try to access the existing databases we can't. It seems like a different instance is created or kept for different web views even though we have moved on to native storage before executing this 2nd step switch.

We have tried switching the cordova plugins from `cordova-plugin-sqlite-2` to `cordova-sqlite-storage`, from passing the different `location` parameter options to specific `iosDatabaseLocation` options. But always landing in the same results that after we switch to WKWebView we can't get the data from the UIWebView SQLite database instance.

### Info

PouchDB 6.4.3
pouchdb-adapter-cordova-sqlite 2.0.5

Cordova plugins: (One or the other but not at the same time)

cordova-sqlite-storage 3.2.0
cordova-plugin-sqlite-2 1.0.6

cli packages:

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    Cordova Platforms : android 6.3.0 ios 4.5.4
    Ionic Framework   : ionic1 1.3.3

System:

    ios-deploy : 1.9.4 
    ios-sim    : 8.0.0 
    Node       : v6.11.4
    npm        : 3.10.10 
    OS         : macOS
    Xcode      : Xcode 10.2.1 Build version 10E1001

**Comment by dlwsacrez** [comment]
Following, I'm having the same issue

**Comment by cujo30227** [comment]
Hi, I have exactly the same issue. Migrating from UIWebView to WKWebView in iOS , and loosing access to the indexedDB.sqlite3 database with PouchDB. I tried several migration tools to move files around, but all unsuccessful. Did the OP find a solution ?
Thanks
