### ISSUE TITLE
Documentation of the expected adapter interface

### ISSUE THREAD

**Issue by whitfin** [pouchdb/pouchdb#7772]
Hi everyone! 

I'm looking for documentation on adapters, specifically the API I need to provide when writing a custom one. I'm looking to write a custom adapter for the Titanium SDK (which was previously mentioned in https://github.com/pouchdb/pouchdb/issues/3016). 

As a lot of the adapters delegate through to LevelDB, it's kinda hard to figure out exactly what you need to provide. Should I assume that everything exposed in the IndexedDB adapter is what is expected?

Thanks in advance!

**Comment by garrensmith** [comment]
The best here is to read the code. This is the latest indexeddb adapter so might be the most helpful https://github.com/pouchdb/pouchdb/tree/master/packages/node_modules/pouchdb-adapter-indexeddb/src
