### ISSUE TITLE
Remove or relicense argsarray dependency

### ISSUE THREAD

**Issue by lindner** [pouchdb/pouchdb#7775]
### Issue

The `argsarray` package used by PouchDb is released under the WTFPL license.  Usages can probably be modernized to use  [Rest Parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters).

This WTFPL license has a large number of issues (lack of warranty disclaimer, very vague rights grant), and was also rejected as an open source license by OSI.

**Comment by garrensmith** [comment]
@calvinmetcalf would you be able to relicense argsarray, or should we look to replace it?

**Comment by lindner** [comment]
Anyone up for looking at 

https://github.com/pouchdb/pouchdb/pull/7779
