### ISSUE TITLE
sort and limit not returning the latest entry based on date

### ISSUE THREAD

**Issue by sammysium** [pouchdb/pouchdb#7776]
### Issue
I have a document with date field and I want to get the latest entry by date. As we speak, there are 1022 records but it is not retrieving the latest payment that was made. It picks up the same record if I apply limit : 1 and I don't know why that record, which is 1 year before the most recent date, gets picked up.

I have tried to do a design doc for it but it made no difference. My design doc was:

  repaymentDateIndex: {
    map : function (doc) {
      if (doc.type === "payemnt") {
        emit(doc);
      }
    }
  }

then use it with query().

If it makes a big difference, the _id is:

   payments_GUID_FROM_COUCH_BASE

### Info
- Environment: Angular 5
- Platform: Chrome
- Adapter: IndexDB
- Server: CouchBase

### Reproduce
I have failed to put it online but here is the code I am using:

public getLastDate(): Observable<any> {

    let vm: any = this;

    return new Observable(observer => {

      vm.db.allDocs(
        {
          startkey: "payments_",
          endkey: "payments_" + "\uffff",
          include_docs: true,
          limit : 1,
          sort : [{"paidOn" : "desc"}]
        },
        function(err, response) {
          // handle err or response

          if (!err) {
            console.log("pouchdb paydata data ", response);
           // returns one record of course but it is not the latest
           // record based on paidOn
            observer.next(response);

            observer.complete();
          } else {

            observer.error(err);
            observer.complete();
          }
        }
      );
    });
  }

**Comment by sammysium** [comment]
Oh it is not a bug, sorry. Solved.

**Comment by travbus** [comment]
Try mango queries and indexs purhaps
