### ISSUE TITLE
pouchdb-core assumes Node.js environments

### ISSUE THREAD

**Issue by whitfin** [pouchdb/pouchdb#7777]
The docs for installing `pouchdb-core` state that it's minimal and without plugins, but if I install it I can see that it has a whole bunch of dependencies:

```
    "argsarray": "0.0.1",
    "inherits": "2.0.3",
    "pouchdb-changes-filter": "7.0.0",
    "pouchdb-collections": "7.0.0",
    "pouchdb-errors": "7.0.0",
    "pouchdb-fetch": "7.0.0",
    "pouchdb-merge": "7.0.0",
    "pouchdb-utils": "7.0.0"
```

Transitively, I get several modules which are assuming I'm in a Node.js environment (and I am not). One of them in particular (`clone-buffer`) requires `buffer` from Node core which makes the core unusable outside of Node.js environments.

To reproduce, go into an empty directory and `npm i pouchdb-core`. You'll see that there's a whole bunch of modules installed, which are non-optional.

**Comment by MichaelJCole** [comment]
"The core of PouchDB as a standalone package. This is a preset designed to be combined with other plugins to create new presets. By itself, it is not very useful."

I don't get how this is a bug.  Have you tried the "pouchdb-browser" package?
