### ISSUE TITLE
Support partial update by new API 'patch'

### ISSUE THREAD

**Issue by yanggf8** [pouchdb/pouchdb#7780]
### Issue
Write the description of the issue here
CouchDB has started to support partial update with standard rest api verb: patch.
Can PouchDB support same function.
### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by karlwestin** [comment]
I'm not finding this documented here https://docs.couchdb.org/en/stable/api/document/common.html#db-doc
Can you point to the documentation for that?

**Comment by yanggoufang** [comment]
I am sorry, I checked the information again. And found out it is still under work. [https://github.com/apache/couchdb/issues/1559](https://github.com/apache/couchdb/issues/1559)

**Comment by karlwestin** [comment]
Alright! I'll close this issue now and we'll re-open it when they are getting closer
thanks for writing in about this, pouchdb should definitely be able to support this when couchdb does!
