### ISSUE TITLE
The attachment objects are mutated after calling `put` method.

### ISSUE THREAD

**Issue by jahtalab** [pouchdb/pouchdb#7781]
### Issue
The attachment objects are mutated after calling `put` method. This introduces bugs into applications that expect the document to be immutable. 

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
In the following example the `doc._attachments.test.data` is being removed after the `put` call.

```js
var doc = {
  _id: "id",
  _attachments: {
    test: {
      content_type: 'text/plain',
      data: 'content'
    }
  }
}

db.put(doc)

console.log(doc._attachments.test)
```

**Comment by garrensmith** [comment]
I'm a little rusty on the attachment code, but I think we have to add in the md5 checksum etc. This is expected
