### ISSUE TITLE
Advertising as PWA database

### ISSUE THREAD

**Issue by ShalokShalom** [pouchdb/pouchdb#7788]
Hi :hugs: 

I spend a couple of hours reading up on PWA`s and thinking the whole time, Indexed.db (idb) is the only choice for PWA developers. Luckily, I found out that Pouchdb is also capable of doing that. 

So, since I consider others in the same position as mine, so I think that it is beneficial for this project to explicitly state compatibility in that perspective.

**Comment by garrensmith** [comment]
PouchDB runs on top of indexeddb. You welcome to submit a PR to the documentation that states this.
