### ISSUE TITLE
Internal error in private mode

### ISSUE THREAD

**Issue by neojski** [pouchdb/pouchdb#779]
When I start a project using pouchdb in private mode it fails with InvalidStateError thrown from context:

```
var name = opts.name;
var req = indexedDB.open(name, POUCH_VERSION);
var meta = {
 id: 'meta-store',
 updateSeq: 0
};
```

(you can experience that here http://neojski.github.io/js-introduction/)

We should inform our users more gently that pouch won't work.

**Comment by 5minpause** [comment]
Hey there. Thank you for PouchDB. It's been great to work with.
I am trying to quite some errors my users experience. The `InvalidStateError` keeps popping up again and again. Do you have any idea how to deal with this?
Is it somehow possible to catch this one? I am stuck and any help would be appreciated.
Thank you.

**Comment by nolanlawson** [comment]
@5minpause if you could provide steps to reproduce, browser, etc. as a new issue, that would be helpful. :)

**Comment by 5minpause** [comment]
@nolanlawson Thanks for requesting that. I actually did create a clean repository and put it on Heroku for you to investigate. While doing that, I noticed my error and could fix it in my code. So everything is fine here for me now. Thanks again.
