### ISSUE TITLE
pouchdb-selector-core - matchSelect function - There is nothing stoping matchSelector recursion

### ISSUE THREAD

**Issue by dfulgham** [pouchdb/pouchdb#7790]
https://github.com/pouchdb/pouchdb/blob/a864168274b6ec3a6758f60ae7d38dfc5e50951a/packages/node_modules/pouchdb-selector-core/src/in-memory-filter.js#L72

Once you enter the object recursion there is nothing stopping it, and thus it starts delving into the final key as and array of characters and fails with:

Error: unknown operator "0" - should be one of $eq, $lte, $lt, $gt, $gte, $exists, $ne, $in, $nin, $size, $mod, $regex, $elemMatch, $type, $allMatch or $all

Here is a patched matchSelect function that will fix the issue with $elemMatch and other deep nested matching operators:

```
function matchSelector(matcher, doc, parsedField, docFieldValue) {
  if (!matcher) {
    // no filtering necessary; this field is just needed for sorting
    return true;
  }

  if (typeof matcher === 'object') {
    return Object.keys(matcher).every(function(userOperator) {
      var userValue = matcher[userOperator];
      return match(userOperator, doc, userValue, parsedField, docFieldValue);
    });
  }

  // No need to recurse further
  return matcher === docFieldValue
}
```

**Comment by garrensmith** [comment]
Fixed in #7791
