### ISSUE TITLE
Replicating From Couchbase aborts with Attachments

### ISSUE THREAD

**Issue by GoodnatureBeacon** [pouchdb/pouchdb#7793]
### Issue
PouchDB replication from Couchbase Sync Gateway fails on attachments.

I am using PouchDB to display data from a Couchbase Server, at this stage it is read-only, so I start by replicating the data from the Couchbase Server. 

(I am using Couchbase as the data is provided from an app which uses Couchbase Lite as the backend, and the sync-gateway can't point to CouchDB)

This all worked until I recently added the ability to add a photo in the app. Now the replication fails due to this issue: https://forums.couchbase.com/t/how-get-blobs-url/18396/6
Is there anyway PouchDB replication could be updated to match this requirement of using %2F rather than a forward slash in the URL during replication?

### Info
- Environment: Node.js
- Platform: Chrome
- Adapter: Unsure
- Server: Couchbase Sync Gateway

### Reproduce
Connect to a Couchbase Server through Sync Gateway and try to replicate an attachment

**Comment by garrensmith** [comment]
We don't currently support syncing to Couchbase server.
