### ISSUE TITLE
Query- couch db to the pouch db  data-size concern

### ISSUE THREAD

**Issue by nraghuwanshi25** [pouchdb/pouchdb#7795]
### Issue

 while syncing data from couchdb to pouchdb  the actual data size is 130mb  but after complete sync in network  is showing 286mb transferred at pouchdb.Due to this it is taking more time in sync.

![sync](https://user-images.githubusercontent.com/20335442/59414295-d823ed00-8dde-11e9-9b32-1ab695e4b9e8.png)

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by garrensmith** [comment]
What size is the database? The sync http calls are a little noisy

**Comment by nraghuwanshi25** [comment]
we  are using couchdb at server side and client side we have tried with  indexdb,websql,sqllite  using pouchdb library but the result is same.

what time it should take to download 300mb data on common network.
