### ISSUE TITLE
Release 7.1

### ISSUE THREAD

**Issue by garrensmith** [pouchdb/pouchdb#7799]
# Release 7.1

Hi all, I would like to get another PouchDB release out. It will just contain all bug fixes and dependency updates since the last one. 

I'm just waiting on a decision for the following PR's:
- [x] Pin node-fetch https://github.com/pouchdb/pouchdb/pull/7798
- [x] Remove argsarray https://github.com/pouchdb/pouchdb/pull/7779
- [x] Expose FetchJSON https://github.com/pouchdb/pouchdb/pull/7768
- [ ] Expose new indexeddb adapter https://github.com/pouchdb/pouchdb/pull/7618

I'm really short on time, so I'm going to do this as quickly as possible. If I can't get those issues fixed in the next week, I will have to do the release without them. I will probably keep the blog post really short as well and not list all the fixes.

**Comment by garrensmith** [comment]
I'm going to make a release now. We can do #7618 and #7779 in the next release

**Comment by garrensmith** [comment]
Ok I've tried to push a release. But I don't have access to https://www.npmjs.com/package/pouchdb-fetch. Once I have that I will be able to publish everywhere.

**Comment by garrensmith** [comment]
@daleharvey when you get a chance could you give me access to https://www.npmjs.com/package/pouchdb-fetch

**Comment by tyler-johnson** [comment]
Yep PouchDB installs are super broken right now:

```
Couldn't find any versions for "pouchdb-fetch" that matches "7.1.0"
```

**Comment by garrensmith** [comment]
Release is now all done. Latest is `7.1.1`.
