### ISSUE TITLE
Safe to use plugins (e.g. pouchdb-adapter-websql) with different versions?

### ISSUE THREAD

**Issue by adrienverge** [pouchdb/pouchdb#7803]
PouchDB version 7.0.0 moved WebSQL support to a dedicated plugin, that now needs to be registered with `PouchDB.plugin(require('pouchdb-adapter-websql'))`.

PouchDB 7.1.1 was released yesterday (thanks @garrensmith!), but `pouchdb-adapter-websql` is only available in version 7.0.0.

Is it safe to use PouchDB `7.x` + a plugin `7.y`, with `x > y`? Or should we wait for `pouchdb-adapter-websql` 7.1.1 to be out (if ever planned)?

I couldn't find anything about this in documentation. If you want, I can try to add something useful in https://pouchdb.com/api.html#plugins.

**Comment by garrensmith** [comment]
Yes it will be fine

________________________________

**Comment by adrienverge** [comment]
Thanks!
