### ISSUE TITLE
find with overlapping fields not picked correctly

### ISSUE THREAD

**Issue by jlami** [pouchdb/pouchdb#7811]
### Issue
sample document:
```
{
  _id: 'test',
  data: {
    name: 'name',
    email: 'info@example.com',
  }
}
```

`db.find({selector: {_id: 'test' }, fields: ['data.name', 'data.email']});`

This will result in only the last field being returned.

### Info
- any local adapter
- remote http adapter works

I think the `setFieldInDoc` function in `pick` does not preserve the old values correctly.       https://github.com/pouchdb/pouchdb/blob/3b29a41ff7305318d261cf9ae587c071198f2fb8/packages/node_modules/pouchdb-find/src/utils.js#L123-L133

https://github.com/pouchdb/pouchdb/blob/3b29a41ff7305318d261cf9ae587c071198f2fb8/packages/node_modules/pouchdb-selector-core/src/utils.js#L17-L23

`doc = doc[elem] = {};` could become `doc = doc[elem] = doc[elem] || {};`

But I don't know if this behaviour is expected anywhere else.

**Comment by garrensmith** [comment]
Could you test it against CouchDB if it’s wrong a PR would be appreciated


________________________________

**Comment by jlami** [comment]
The remote http-adapter works as expected.

I'll try if my solution works and doesn't break any tests.

**Comment by jlami** [comment]
failing test breaks only on local adapter: https://travis-ci.org/jlami/pouchdb/jobs/551330208#L2259

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/afa098df33d8feb67161879d124554844525afc6
