### ISSUE TITLE
Sync between tabs in the same browser & longpoll is too long

### ISSUE THREAD

**Issue by alexfedoseev** [pouchdb/pouchdb#7816]
### Issue
I'm testing just implemented two-way synchronization and faced few issues:

**1. Sync between tabs in the same browser**
When changes are made in one of the opened tabs, those get pushed to the server and all other clients are notified. All, except opened tabs in the same browser. I understand why it happens (b/c those share same db) but can't figure out a good way to handle UI updates in inactive tabs (besides using page visibility api and such).

I think I read somewhere that there should be emitted event when indexed db is changed but not sure how to listen for this event (and not sure if it gets emitted at all). I tried to listen via `localDb.changes()` but no luck. Also, I noticed that after refresh, when I push something from one tab, in another tab `active` event gets fired with `direction: pull`. But: this happens only until this tab pushes something. After that, no `active` event is emitted.

I recorded a demo of this: https://cl.ly/7597c52418ba

**2. Longpoll is too long**
I tested few scenarios using Chrome desktop client (macOS) and Safari on mobile (iOS). When I refresh both clients and make a change on one of the devices—all works. But if I leave clients inactive for short period (2-5 min), then:
- when I make a change on the mobile Safari, desktop Chrome receives pull after ~10 minutes
- when I make changes in Chrome on desktop, mobile Safari never gets update (I stopped timer after 20 minutes).

Pushed changes are available almost immediately: if I refresh one device after the push from another, changes are available.

### Info
- Environment: browser
- Platform: Chrome & iOS
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
The live version is available here: https://minima.app (it will require login)

**Comment by pubkey** [comment]
Hi @alexfedoseev 
When the speed of the cross-tab communication is that relevant for your app, I recommend to use a broadcast-channel instead of waiting for pouchdb to send changes.
See https://github.com/pubkey/broadcast-channel

The problem with the polling of pouchdb is, that chrome will throttle down setTimeout and setInterval on inactive tabs [source](https://content.pivotal.io/blog/chrome-and-firefox-throttle-settimeout-setinterval-in-inactive-tabs)

**Comment by alexfedoseev** [comment]
Hey @pubkey, thanks for suggestion! I solved it by pausing/restoring sync process on focus/visibility change which works pretty good AFAICT considering that users shouldn't be using more than one tab most of the time.
