### ISSUE TITLE
Yarn on macOS: MaxListenersExceededWarning

### ISSUE THREAD

**Issue by tiloio** [pouchdb/pouchdb#7819]
### Issue
Can't run PouchDB node.js with yarn on macOS. 
It is working on Windows 10.

### Info
- Environment: Node.js v11.9.0
- Platform: macOS Mojave Version 10.14.3 (18D109)
- Server: PouchDB Version 7.1.1

### Reproduce
See repository to reproduce: https://github.com/tiloio/yarn-macos-pouchdb-error

Short reproduce.
Content of index.js file:
```
var PouchDB = require('pouchdb');
var db = new PouchDB('dbname');

db.put({
  _id: 'dave@gmail.com',
  name: 'David',
  age: 69
});

db.changes().on('change', function() {
  console.log('Ch-Ch-Changes');
});
```

Run `yarn add pouchdb && node index.js` on MacOS and get following error:
```
$ node index.js
(node:56044) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:56044) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
Ch-Ch-Changes
Ch-Ch-Changes
Ch-Ch-Changes
/Users/Tilo/Documents/workspace/test/node_modules/readable-stream/lib/_stream_transform.js:82
    return this.emit('error', new ERR_MULTIPLE_CALLBACK());
                              ^

Error: Callback called multiple times
    at DestroyableTransform.afterTransform (/Users/Tilo/Documents/workspace/test/node_modules/readable-stream/lib/_stream_transform.js:82:31)
    at onGetWinningDoc (/Users/Tilo/Documents/workspace/test/node_modules/pouchdb/lib/index.js:5829:11)
    at onGetMetadata (/Users/Tilo/Documents/workspace/test/node_modules/pouchdb/lib/index.js:5840:18)
    at /Users/Tilo/Documents/workspace/test/node_modules/pouchdb/lib/index.js:5864:9
    at /Users/Tilo/Documents/workspace/test/node_modules/pouchdb/lib/index.js:4142:9
    at /Users/Tilo/Documents/workspace/test/node_modules/pouchdb/lib/index.js:3973:13
Emitted 'error' event at:
    at DestroyableTransform.onerror (/Users/Tilo/Documents/workspace/test/node_modules/pouchdb/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at DestroyableTransform.emit (events.js:197:13)
    at DestroyableTransform.afterTransform (/Users/Tilo/Documents/workspace/test/node_modules/readable-stream/lib/_stream_transform.js:82:17)
    at onGetWinningDoc (/Users/Tilo/Documents/workspace/test/node_modules/pouchdb/lib/index.js:5829:11)
    [... lines matching original stack trace ...]
    at /Users/Tilo/Documents/workspace/test/node_modules/pouchdb/lib/index.js:3973:13
```

**Comment by taylorfinnell** [comment]
Saw a similar issue, could not narrow it down. However, after downgrading to `7.0.0` it seemed to go away. For what that's worth

**Comment by danielweck** [comment]
Similar issue:
https://github.com/pouchdb/pouchdb/issues/7825

I am getting this on MacOS:
```
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
```

```
Uncaught Exception:
Error: once called more than once
    at x/node_modules/pouchdb-core/node_modules/pouchdb-utils/lib/index.js:88:13
    at x/node_modules/argsarray/index.js:14:18
    at x/node_modules/pouchdb-core/lib/index.js:769:14
    at x/dist/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:350:18
    at x/dist/node_modules/argsarray/index.js:14:18
    at x/dist/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:429:16
    at x/dist/node_modules/sublevel-pouchdb/lib/index.js:243:9
    at x/dist/node_modules/sublevel-pouchdb/lib/index.js:74:13
```

**Comment by danielweck** [comment]
Reverting back to version `7.0.0` (for both PouchDB core and the LevelDB adapter) fixes this for me.

**Comment by danielweck** [comment]
Reverting back to version `7.0.0` (for both PouchDB core and the LevelDB adapter) fixes this for me.

**Comment by rgeber** [comment]
Same problem here. Version `7.1.1` works when switching from `yarn` to `npm` but the problem appears when having more then 4 change listeners (using adapter `memory`).

A downgrade to 7.0.0 did not solve the issue.

Additional note for anyone looking to downgrade: Make sure Python 2.7 is the default `python` command, otherwise the installation will fail.

**Comment by rgeber** [comment]
Found a workaround:

```
require('events').defaultMaxListeners = 15;
```

Based on: https://stackoverflow.com/questions/8313628/node-js-request-how-to-emitter-setmaxlisteners

**Comment by SearchingSoul** [comment]
try using the following in package.json
`  "resolutions": {
    "leveldown": "5.0.2",
    "levelup": "4.0.2"
  },`

worked for me. 
cant tell if this is a yarn issue or pouchdb issue by looking at the multiple versions of dependencies that seem to install.

**Comment by danielweck** [comment]
After revisiting this issue, I have narrowed-down the bug to the `leveldown` transition from version `5.0.2` to `5.0.3` (ALL other package versions are `latest`, currently `levelup` = `4.3.2`, `pouchdb-adapter-leveldb` = `7.1.1`, `pouchdb-adapter-leveldb` = `7.1.1`, etc.)

In other words, ONLY `leveldown` needs to be pinned to version `5.0.2`. In my case, the `package.json` looks like:

```
  "optionalDependencies": {
    "leveldown": "5.0.2",
    "pouchdb-adapter-leveldb": "^7.1.1"
  },
  "resolutions": {
    "leveldown": "5.0.2"
  }
```

**Comment by danielweck** [comment]
For what it's worth, I posted an issue in the LevelDown tracker:
https://github.com/Level/leveldown/issues/686

**Comment by danielweck** [comment]
Prompt feedback from a LevelDown developer:
https://github.com/Level/leveldown/issues/686#issuecomment-541435974

> I don't recommend pinning to 5.0.2; that version suffers from segfaults

Well, that's a concerning statement, because it would seem that PouchDB + LevelDown version > `5.0.2` crashes on MacOS, and the only known remediation is to force version `5.0.2` (via `package.json` `resolutions` or some other NPM `node_modules` trick)

> * `sublevel-pouchdb` is outdated, as it was forked from `level-sublevel` which is no longer maintained and is known to have several compatibility issues with latest `level*` modules. The preferred solution is now `subleveldown`.

I must admit not being familiar with this, so I cannot comment on how this piece of advice could be used. Any idea?

**Comment by danielweck** [comment]
Hello again, I hate to cross-post, but I want to make sure PouchDB users / developers affected by the LevelDown bug are notified. I will therefore post this message in all 3 issues in this GitHub tracker. Sorry.

I am now using a workaround that does not require pinning to version `5.0.2` (which suffers from segfaults issues). Instead, I use the latest version (`^5.3.0`) but I make sure to delete the de-duped `leveldown` NPM package in `./node_modules/pouchdb-adapter-leveldb/node_modules/leveldown` (which contains `build/Release/leveldown.node`)

It's that simple. I just added a `rimraf` statement in my `package.json`'s `postinstall` script.
