### ISSUE TITLE
Mobile Safari: changes feed not working after waking up

### ISSUE THREAD

**Issue by bidigo** [pouchdb/pouchdb#7821]
### Issue
A webpage with continuous changes feed stops working when:
* switching between the browser and another app
* the device wakes up after going to sleep (and the browser in the background)

After waking up, everything seems to work except changes feed.

### Info
- Environment: browser (Safari, Chrome)
- Platform: iOS (12.3.1)
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
* Make a sample app with continuous changes feed (live: true, retry: true)
* Let the iOS device go to sleep mode
* Wake the device up, the changes feed doesn't work anymore

I believe the current behavior is somewhat expected, given that after waking up the original socket is not available anymore. Nonetheless, it would be nice if the behavior could be made more robust, similar to what has been done with the "retry" flag for handling online/offline situations.

When we could specify the "normal" feed mode (instead of the "longpoll" which seems to be hardcoded), we could at least handle it manually, since there is never a semi-permanent TCP/IP connection open.

**Comment by mohlsen** [comment]
I think this also is seen if the server goes offline, and then comes back.  Syncs will not start again.  We're seeing that on iOS in a cordova app (using UIWebView) and in Mobile Safari (WKWebView).

**Comment by gaodeng** [comment]
？
