### ISSUE TITLE
syncing aborts immediately with status "aborting"

### ISSUE THREAD

**Issue by sammysium** [pouchdb/pouchdb#7823]
### Issue
After syncing starts, it immediately aborts for no specific reason and worse, no error message whatsoever. I been at it for days and still couldn't figure out the problem. It was working perfectly fine all along and just started last week. I am in dev machine running localhost:4200 while deployed app is working fine.

The error I am getting is:

```
result:
doc_write_failures: 0
docs_read: 0
docs_written: 0
end_time: "2019-07-02T09:54:45.997Z"
errors: []
last_seq: 0
ok: false
start_time: "2019-07-02T09:54:45.972Z"
status: "aborting"
__proto__: Object
__proto__: Error
```
Expanding the _proto_:Error gives a repetitive message:

```
toString: ƒ ()
constructor: ƒ PouchError(status, error, reason)
super_: ƒ Error()
arguments: (...)
caller: (...)
length: 3
name: "PouchError"
```

In case it matters, the code that replicates is (partly):

```
vm.local.replicate
      .from(this.remote, { live: true, retry: true })
      .on("paused", err => {
      console.log(err)
```

it pauses cos of the error and doesn't attempt to sync a single document.

### Info
- Environment: (Angular 5/ pouchdb-browser 7.1.1)
- Platform: (Chrome)
- Adapter: (IndexedDB)
- Server: (CouchDB)

**Comment by iconicsammy** [comment]
Likely corrupted pouchdb. Copying a working node_modules fixed it.
