### ISSUE TITLE
Noticed live sync not updating for ios 

### ISSUE THREAD

**Issue by Imogynn** [pouchdb/pouchdb#7824]
### Issue
Live Syncs stopped occuring on ios.

### Info
- Environment: react-native under expo
- Platform: ios
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

### Reproduce
 db.replicate.to(localDB, { live: true, retry: true }).on('change', () => {
      onOffersChanged()
    })

That works great for us in android, but was only syncing the first time on ios. We ended up writing our own replication by monitoring the changes feed. Not sure what the issue was, and don't really anticipate a fix. I'm leaving this here in case anyone else runs into a similar problem or has suggestions on how we could improve monitoring changes. Our fix:

export const liveUpdateCouch = async (fromCouch, toCouch, callback ) =>
{
  
  if (constants.ios) {
    fromCouch.replicate.to(toCouch).on('change', async () => await callback())
    fromCouch.changes({ live: true, include_docs: true, style: 'all_docs' })
      .on('change', async change => {
        try {
          const newDoc = change.doc
          await toCouch.put(newDoc, {force: true})
        } catch (err) {
          console.log('error:', err)
        }
        await callback()
      })
  } else {
    fromCouch.replicate.to(toCouch, { live: true, retry: true }).on('change', async () => await callback())
  }
  await callback()
}

**Comment by knubie** [comment]
Possible dupe of #7887
