### ISSUE TITLE
once called more than once. in node.js

### ISSUE THREAD

**Issue by zicjin** [pouchdb/pouchdb#7825]
### Issue
I can't run a basic demo in node.js. this is my test.js:
```
const PouchDB = require('pouchdb');

(async () => {
  console.info("init data...")
  var dbtest = new PouchDB('dbtest')
  try {
    await dbtest.put({
      _id: '1234324',
      title: "zdsdasd"
    })
    console.info("line 11")
    const docs = await dbtest.allDocs({ include_docs: true, descending: true })
    console.info("docs.rows:" + JSON.stringify(docs.rows))
  } catch (err) {
    console.error(`PouchDB: ${err}`)
  }
})()
```
result:
```
⋊> ~/w/ultron on master ⨯ node test.js                                                                                                                                                            17:53:41
init data...
(node:89578) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added to [PouchDB]. Use emitter.setMaxListeners() to increase limit
(node:89578) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added to [PouchDB]. Use emitter.setMaxListeners() to increase limit
/Users/jin/work/ultron/node_modules/pouchdb/lib/index.js:198
      throw new Error('once called more than once');
      ^

Error: once called more than once
    at /Users/jin/work/ultron/node_modules/pouchdb/lib/index.js:198:13
    at /Users/jin/work/ultron/node_modules/argsarray/index.js:14:18
    at /Users/jin/work/ultron/node_modules/pouchdb/lib/index.js:2439:5
    at /Users/jin/work/ultron/node_modules/pouchdb/lib/index.js:5043:16
    at /Users/jin/work/ultron/node_modules/argsarray/index.js:14:18
    at /Users/jin/work/ultron/node_modules/pouchdb/lib/index.js:5550:11
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
```

### Info
- node version: 12.6.0
- pouchdb version: 7.1.1
- Platform: macos

**Comment by danielweck** [comment]
Same problem on MacOS!
```
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
(node:687) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
```

```
Uncaught Exception:
Error: once called more than once
   at /Applications/Reader.app/Contents/Resources/app.asar/main.js:41:34698
   at /Applications/Reader.app/Contents/Resources/app.asar/main.js:16:42984
   at /Applications/Reader.app/Contents/Resources/app.asar/main.js:41:54481
   at /Applications/Reader.app/Contents/Resources/app.asar/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:349:18
   at /Applications/Reader.app/Contents/Resources/app.asar/node_modules/argsarray/index.js:14:18
   at /Applications/Reader.app/Contents/Resources/app.asar/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:428:16
   at /Applications/Reader.app/Contents/Resources/app.asar/node_modules/sublevel-pouchdb/lib/index.js:243:9
   at /Applications/Reader.app/Contents/Resources/app.asar/node_modules/sublevel-pouchdb/lib/index.js:74:13
```

**Comment by danielweck** [comment]
Similar issue: https://github.com/pouchdb/pouchdb/issues/7819

**Comment by danielweck** [comment]
Reverting back to version `7.0.0` (for both PouchDB core and the LevelDB adapter) fixes this for me.

**Comment by rgeber** [comment]
Same problem on Mac OS. Works fine on Linux

Happens during database creation. Nothing connected to `changes`.

Mac OS 10.14.5  
node: 12.6.0
PouchDB: 7.1.1

**Comment by zicjin** [comment]
My environment problem. the node-gyp installed by yarn has a problem, just change to npm.

**Comment by danielweck** [comment]
This `package.json` tweak seems to work:
```
 "resolutions": { "leveldown": "5.0.2", "levelup": "4.0.2" },
```

Credits:
https://github.com/pouchdb/pouchdb/issues/7819#issuecomment-516551035

**Comment by danielweck** [comment]
After revisiting this issue, I have narrowed-down the bug to the `leveldown` transition from version `5.0.2` to `5.0.3` (ALL other package versions are `latest`, currently `levelup` = `4.3.2`, `pouchdb-adapter-leveldb` = `7.1.1`, `pouchdb-adapter-leveldb` = `7.1.1`, etc.)

In other words, ONLY `leveldown` needs to be pinned to version `5.0.2`. In my case, the `package.json` looks like:

```
  "optionalDependencies": {
    "leveldown": "5.0.2",
    "pouchdb-adapter-leveldb": "^7.1.1"
  },
  "resolutions": {
    "leveldown": "5.0.2"
  }
```

LevelDown diff between version `5.0.2` and `5.0.3`:
https://github.com/Level/leveldown/compare/v5.0.2...v5.0.3

**Comment by danielweck** [comment]
For what it's worth, I posted an issue in the LevelDown tracker:
https://github.com/Level/leveldown/issues/686

**Comment by danielweck** [comment]
Prompt feedback from a LevelDown developer:
https://github.com/Level/leveldown/issues/686#issuecomment-541435974

> I don't recommend pinning to 5.0.2; that version suffers from segfaults

Well, that's a concerning statement, because it would seem that PouchDB + LevelDown version > `5.0.2` crashes on MacOS, and the only known remediation is to force version `5.0.2` (via `package.json` `resolutions` or some other NPM `node_modules` trick)

> * `sublevel-pouchdb` is outdated, as it was forked from `level-sublevel` which is no longer maintained and is known to have several compatibility issues with latest `level*` modules. The preferred solution is now `subleveldown`.

I must admit not being familiar with this, so I cannot comment on how this piece of advice could be used. Any idea?

**Comment by danielweck** [comment]
Hello again, I hate to cross-post, but I want to make sure PouchDB users / developers affected by the LevelDown bug are notified. I will therefore post this message in all 3 issues in this GitHub tracker. Sorry.

I am now using a workaround that does not require pinning to version `5.0.2` (which suffers from segfaults issues). Instead, I use the latest version (`^5.3.0`) but I make sure to delete the de-duped `leveldown` NPM package in `./node_modules/pouchdb-adapter-leveldb/node_modules/leveldown` (which contains `build/Release/leveldown.node`)

It's that simple. I just added a `rimraf` statement in my `package.json`'s `postinstall` script.
