### ISSUE TITLE
can't use index with $in operator et al

### ISSUE THREAD

**Issue by trik** [pouchdb/pouchdb#7838]
### Issue
Using $in operator (and any other operator $nin: [$eq, $lte, $gte, $lt, $gt]) with multi field indexes fails with error
`TypeError: Cannot use 'in' operator to search for 'startkey' in undefined`

[getMultiFieldCoreQueryPlan](https://github.com/pouchdb/pouchdb/blob/aa3ff5e47c816baee3ae11144681a11661269d37/packages/node_modules/pouchdb-find/src/adapters/local/find/query-planner.js#L311-L337) method in query-planner doesn't return a default value, the exception is raised [here](https://github.com/pouchdb/pouchdb/blob/aa3ff5e47c816baee3ae11144681a11661269d37/packages/node_modules/pouchdb-find/src/adapters/local/find/query-planner.js#L406-L407)

Tried to patch using `{startkey: COLLATE_LO}` as default value (as in [getSingleFieldQueryOptsFor](https://github.com/pouchdb/pouchdb/blob/aa3ff5e47c816baee3ae11144681a11661269d37/packages/node_modules/pouchdb-find/src/adapters/local/find/query-planner.js#L272-L274)) but it's not working (see [failing test case](https://github.com/trik/pouchdb/blob/bca59e325f835de00b5a2d68cc49dc3d772d4ce4/tests/find/test-suite-1/test.use-index.js#L131-L147))

### Info
- Environment: Browse/Hybrid app
- Platform: Chrome/Android
- Adapter: IndexedDB
- Server: CouchDB/PouchDB Server

### Reproduce
[https://pouchdb-find-in-index.glitch.me/](https://pouchdb-find-in-index.glitch.me/)
[https://github.com/trik/pouchdb/tree/find-multi-field-index](https://github.com/trik/pouchdb/tree/find-multi-field-index)

**Comment by akana** [comment]
i also face the same issue. Any help would be appreciated. 

### System

- PouchDB : v7.1.1
- PouchDB Find : v7.1.1
- Chrome v75.0

**Comment by MaximumCrash** [comment]
Also facing this issue with this plan: 

```
selector: {
   month: {$in: ['11','12']},
   year: {$eq: '2018'}
}
```

PouchDB: v7.1.1
PouchDB Find: v7.1.1
Chrome: v77.0

**Comment by MaximumCrash** [comment]
@trik @akana I had a little bit of an epiphany last night. Since this fix might be on hold for a little bit my solution to getting $in functionality is to instead use $regex and pipe the values I need. 

For example this returns results that have a year of 2010, 2011, or 2012 based on the needs of the regex:
```
selector: {
   'year': {
        $regex: new RegExp('(2010|2011|2012)', gm)
   }
}
```

Hope this helps.

**Comment by trik** [comment]
@MaximumCrash could you please share also the indexes defined on the db?
multi fields indexes seem to work only when using $eq, $lt, $lte, $gt and $gte operators in selectors..
take look at the glitch in my first message, i tried using your solution
`db.find({selector: {name: {$regex: /mario|luigi/g}, series: 'mario'}});`
but i'm get the same error

**Comment by MaximumCrash** [comment]
@trik Your example may be failing due to the structure of your regex. Here's a working example using the Smash bros example: 

```
let nameRegex = new RegExp('(Mario|Luigi)','gm');
let debutRegex = new RegExp('(1983)','gm'); 

db.createIndex(
  {fields: ['name']}
).then(function (result) {
  return db.find({
      selector: {
            name: {$regex: nameRegex},
            debut: {$regex: debutRegex}
      }
  });
```

Do note that my Regex string uses parenthesis '(' and ')' to capture the string value in a group and that the names in the Smash bros db are uppercase (Mario instead of mario).

Lmk how it goes.

**Comment by trik** [comment]
@MaximumCrash mmh probably i was not clear and you didn't get the point..
if the index is built on one field (only "name" in your example), you can use $in or any other operator without any problem.. https://pouchdb-find-in-index-good.glitch.me/
when your index is on multiple fields ("name" and "series" in my example) and you use a selector that matches the index, you can use only $eq, $gt, $gte, $lt, $lte operators. modified https://pouchdb-find-in-index.glitch.me/ as you suggested but i get the same errore

**Comment by MaximumCrash** [comment]
@trik Ah I see what you mean. It's strange that you're seeing this error, since I can't reproduce in my own project, but can reproduce in your own glitch.me I'll do a little more research and see how I'm getting it to work exactly on my end.

**Comment by awtkeithlin** [comment]
The reason is that there is no $in  in getMultiFieldCoreQueryPlan() with  "pouchdb-browser"
function getMultiFieldCoreQueryPlan(userOperator, userValue) {
  switch (userOperator) {
    case '$eq':
      return {
        startkey: userValue,
        endkey: userValue
      };
    case '$lte':
      return {
        endkey: userValue
      };
    case '$gte':
      return {
        startkey: userValue
      };
    case '$lt':
      return {
        endkey: userValue,
        inclusive_end: false
      };
    case '$gt':
      return {
        startkey: userValue,
        inclusive_start: false
      };
  }
}


    "pouchdb-browser": "^7.1.1",
    "pouchdb-find": "^7.1.1",
