### ISSUE TITLE
Email as username will make pouchdb try to connect to emails domain, instead of server domain.

### ISSUE THREAD

**Issue by maxxafari** [pouchdb/pouchdb#7839]
### Issue
If the username is an email, it tries to connect to the domain in the username and not the domain name for the server.

### Info
- Environment: NODE v10.13.0
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: ?
- Server: CouchDB

### Reproduce
This test will always fail, but the error message will show that the wrong URL was called:

When it should  give the error 

```
const PouchDB = require('pouchdb');
test('It can connect if username is email', async () => {
  const db = new PouchDB(
    'http://myemail@thisisnotthecorrectdomain.com:password@mydomain.com:5984'
  );
  const info = await db.info();
});
```
Will give the error: `FetchError: request to http://thisisnotthecorrectdomain.com/password%40mydomain.com%3A5984/ failed, ...`

Wen it should fail with the message: ` FetchError: request to http://mydomain.com:5984// failed, ...` 

replacing the **@** sign in the username will give the expected error.

An email is a valid username in couchdb

**Comment by karlwestin** [comment]
ha wow, that seems annoying as hell
FWIW there's a work around in case you're blocked by this:

https://pouchdb.com/api.html#create_database
```
  const db = new PouchDB('http://mydomain.com:5984/dbname, {
    auth: {
       username: 'myemail@thisisnotthecorrectdomain.com',
       password: 'password'
    }
  });
  const info = await db.info();
```

**Comment by maxxafari** [comment]
Thanks, @karlwestin it works.
