### ISSUE TITLE
allDocs with startkey error

### ISSUE THREAD

**Issue by maicWorkGithub** [pouchdb/pouchdb#7840]
```
const db = new PouchDB('test')
const doc = {_id: 'user_111', username: 'someone'}
await db.put(doc)

await db.allDocs({startkey: 'user1_'})
// this will get the `doc` above, which should not
```

tested in FireFox 70, chrome 75, same performance.

**Comment by karlwestin** [comment]
Just wanna add a little bit more info,
you can play around with this here http://jsbin.com/lotaroqila/edit?html,js,output
The behavior is the same in all pouchdb versions back to 3.6.0 (could not test earlier right now) 

Seems unexpected for sure!

**Comment by maicWorkGithub** [comment]
@karlwestin Why use such robot rules?
