### ISSUE TITLE
find is not a function

### ISSUE THREAD

**Issue by derek-baker** [pouchdb/pouchdb#7843]
### Issue
I've got an Apache-Cordova project I'm running in a browser and an Android WebView, and I can't get the PouchDB-Find plugin to work.

More details [here](https://stackoverflow.com/questions/57085088/why-is-pouchdb-find-not-a-function)

In addition to what I tried above, I also tried the stuff from [here](https://github.com/pouchdb/pouchdb/issues/6630)

### Info
- Environment: browser/hybrid app(Android-only)
- Platform: Windows Firefox and Android WebView/Chrome
- Adapter: IndexedDB
- Server: None

### Reproduce
I created a minimal reproducible example [here](https://github.com/derek-baker/PouchDB_Bug_Repro)
If you git clone, npm install, npm run start, open a browser to the appropriate port on localhost, and open the DevTools, you should see a 'find is not a function' error.

**Comment by karlwestin** [comment]
that example is super valuable, thank you for that!
i wonder if there's not a slight quirk in your build system here (i have not had time to run this, sorry)
you call
`var PouchDB = require('pouchdb').default`
but then you use `require('pouchdb-find`)

Does it make a difference if you change this line https://github.com/derek-baker/PouchDB_Bug_Repro/blob/master/hello/www/js/pouchdb-find-test.js#L2 to 
```
PouchDB.plugin(require('pouchdb-find').default);
```
?

**Comment by derek-baker** [comment]
If I change the line as you suggest, the error changes to: 'Invalid plugin: got "undefined", expected an object or a function'
