### ISSUE TITLE
PouchDB data missing after period of time

### ISSUE THREAD

**Issue by jkeczan** [pouchdb/pouchdb#7847]
### Issue
We are using PouchDB to handle the offline/online paradigm. Everything is working as intended. However, we have found that there is an odd edge we are encountering that we cannot track down. I cannot confirm it is in Pouch or Couch so I thought I would start here. The issue is VERY hard to reproduce, but each time it happens, we have traced it back down to the pouchDB library. 

### Info
- Environment: Ionic/Angular 6 App
- Platform: Chrome, Mobile iOS Safari
- Adapter: IndexedDB
- Server: Docker CouchDB 2.3 / Pouch ^7.0.0

### Reproduce
1. Sync up a PouchDB (live, retry set to true) to a CouchDB server
2. While leaving the tab open, leave the computer alone for up to 3 days
3. On the 3rd day, simply refresh your browser
4. The data in pouch is gone. In addition, PouchDB doesn't detect any data to sync down anymore resulting in an empty db.

I am leaning towards the data being evicted from the IndexedDB but I cannot confirm that for sure. Even more so, once evicted, it appears that the only resolution is to destroy the PouchDB and re-create/re-sync.

This does occur sporadically and we CANNOT reproduce it consistently but this pattern will duplicate it the most.

Update:
We are NOT seeing any quota errors or storage limits messages in the console when this occurs. Just a blank DB in the indexedDB viewer

**Comment by pubkey** [comment]
Have you tried this with different browsers?

**Comment by jkeczan** [comment]
Yes, I have seen the behavior in Firefox but we only attempt to test/determine the cause on Chrome because that is all my company supports.

**Comment by jkeczan** [comment]
Reviewing this documentation, it does appear that IndexedDB is treated as transient data by Chrome rather than persistent. It is possible it seems for Chrome to clear to the data. 

https://developer.chrome.com/apps/offline_storage#temporary

I guess from my perspective, if the data is cleared, why does PouchDB not simply re-sync it down when the sync is activated?

**Comment by gaodeng** [comment]
?

**Comment by omidazm94** [comment]
i'm expirienicng the same issue.

**Comment by dheimoz** [comment]
hey @omidazm94 hope you are doing great.
Just to understand the problem, have the reproduced the issue following the very same steps?
Or is there any other trigger that needs to be considered.
As you might know, issued hard to reproduce, are hard to debug and harder to fix.
Thanks

**Comment by omidazm94** [comment]
hey @dheimoz , thanks, i hope you're doing well too.
no i haven't done the steps. actually i'm working on a PWA project that uses pouchdb for draft some orders and after some days it's gone, and based on @jkeczan answer, i realized that it's an issue that this package has.
i will work more on it and report back if i figure out something. 
thanks for your answer

**Comment by raz0229** [comment]
@omidazm94 Experiencing the same issue as of April 2023. Please report back on what you've found or were you able to resolve it
