### ISSUE TITLE
Problem with PouchDB - Next.js

### ISSUE THREAD

**Issue by youssef3wi** [pouchdb/pouchdb#7848]
### Issue
Hi,
I'm running into problems with pouch.

```
(node:7690) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added to [PouchDB]. Use emitter.setMaxListeners() to increase limit
```

even when i increase listeners

```
db.setMaxListeners(20);
```

give me

```
21 destroyed listeners added to [PouchDB]
```

I've been searching around for a few hours, and can't find anything relevant. I think this might have something to do with PouchDB in next.js.config or can i have some suggestion or example of PouchDB using next.js

### Info
- Environment: (Node.js/browser/Next.js)
- Platform: (Safari)
- Adapter: (LevelDB)
- Server: (PouchDB Server)

**Comment by osenvosem** [comment]
@youssef3wi I have the same issue in electron environment. Could you please tell me how you solved this?

**Comment by youssef3wi** [comment]
I create a Context (+ Provider) with 
```useEffect( (...) => {
if (!BD) {
            PouchDB.plugin(PouchDBFind)
            const db = new PouchDB('prd', { skip_setup: true });
            //update state
}
}

```

**Comment by danielweck** [comment]
After revisiting this issue, I have narrowed-down the bug to the `leveldown` transition from version `5.0.2` to `5.0.3` (ALL other package versions are `latest`, currently `levelup` = `4.3.2`, `pouchdb-adapter-leveldb` = `7.1.1`, `pouchdb-adapter-leveldb` = `7.1.1`, etc.)

In other words, ONLY `leveldown` needs to be pinned to version `5.0.2`. In my case, the `package.json` looks like:

```
  "optionalDependencies": {
    "leveldown": "5.0.2",
    "pouchdb-adapter-leveldb": "^7.1.1"
  },
  "resolutions": {
    "leveldown": "5.0.2"
  }
```

LevelDown diff between version `5.0.2` and `5.0.3`:
https://github.com/Level/leveldown/compare/v5.0.2...v5.0.3

**Comment by danielweck** [comment]
For what it's worth, I posted an issue in the LevelDown tracker:
https://github.com/Level/leveldown/issues/686

**Comment by danielweck** [comment]
Prompt feedback from a LevelDown developer:
https://github.com/Level/leveldown/issues/686#issuecomment-541435974

> I don't recommend pinning to 5.0.2; that version suffers from segfaults

Well, that's a concerning statement, because it would seem that PouchDB + LevelDown version > `5.0.2` crashes on MacOS, and the only known remediation is to force version `5.0.2` (via `package.json` `resolutions` or some other NPM `node_modules` trick)

> * `sublevel-pouchdb` is outdated, as it was forked from `level-sublevel` which is no longer maintained and is known to have several compatibility issues with latest `level*` modules. The preferred solution is now `subleveldown`.

I must admit not being familiar with this, so I cannot comment on how this piece of advice could be used. Any idea?
