### ISSUE TITLE
Changes feed fail randomly when connected to a remote couchdb server

### ISSUE THREAD

**Issue by RAACosta** [pouchdb/pouchdb#7850]
### Issue
This is the same error reported at [#7601] and similar to [#6491]. 

> invalid json response body at [DB_URL]/_changes?include_docs=true&feed=longpoll&heartbeat=10000&since=2429-g1AAAAP3eJzLYWBgEMhgTmFQT0lKzi9KdUhJMjTSS8rVTU7WTS3VTUnVNTTQS87JL01JzCvRy0styQFqYMpjAZIMH4DUfyDISlwEMkENbgKxBjyAGPA-K7EN1QATIg24ADHgflbiPFQDLIg04ADEgPNZiV1kBsIGiAn7sxJnkBcICyAGrM9K7CYvECZADJiflTibvEBogBjQn5W4geRASCoAkkn14FQwldQASEoAac4Ha55FqueTAkCa48Ga-0n1eJIDSLM_WPNk0j1tANJtD9Y9l2RPK4A064M1LybZ0wIgzfJgzX2kejqRIYkfrHNBFgDVWU0q&limit=25 reason: Unexpected end of JSON input

I am having the same problem with 7.1.1. Options to subscribe to changes are: 
`{ since: "now", live: true, include_docs: true }`

### Info
- Environment: Node.js
- Platform: Electron
- Adapter: HTTP
- Server: Cloudant
- PouchDB: 7.1.1

### Reproduce
Yo reproduce usually I start the app which will subscribe to database changes and leave it in open for a while without using it. It happens randomly so far.

**Comment by cbrittingham** [comment]
I am seeing this same error with PouchDB 7.1.1 (in electron) connecting to a local pouchdb-server.  It throws the error exactly every 120 seconds.  This happens even though no changes are happening.  

Setting timeout and heartbeat on the change listener does not affect the timing of the error.

**Comment by daleharvey** [comment]
an error every 120 seconds is fairly certainly the changes feed timing it, we cancel it and refresh it after a while because some browsers didnt handle it well being left open indefinitely

**Comment by inator** [comment]
Same issue for me, except in my case it's only happening when use express-pouchdb v 4.1.0 as a couch server via localhost.  If I instantiate against a legit remote couchdb instance, no error.

**Comment by freakeinstein** [comment]
I have the same issue when I connect pouchDB to pouchdb-server. 
`FetchError: invalid json response body at http://localhost:5984/default_docsdb/_changes?include_docs=true&feed=longpoll&heartbeat=10000&since=110&limit=25 reason: Unexpected end of JSON input`

**Comment by BenLiyanage** [comment]
I also have this issue using:

    "express-pouchdb": "^4.2.0"

**Comment by gnujeremie** [comment]
Same error here with Couchdb 3.2 and pouchdb 7.3
