### ISSUE TITLE
PouchDB.debug() documentation outdated

### ISSUE THREAD

**Issue by UncleSamSwiss** [pouchdb/pouchdb#7851]
### Issue
Documentation on the ```PouchDB.debug()``` API is outdated as of 7.0.0:
- The NPM page for ```pouchdb-debug``` still states:
> This module is currently part of PouchDB core; you don't need to do anything to use it. However, in PouchDB v7.0.0 the debug() API will be moved to a separate plugin.
- The API reference still mentioned the old way without referring to the new plugin location (but it contains the same disclaimer as above):
https://github.com/pouchdb/pouchdb/blob/master/docs/_includes/api/debug_mode.html

### Info
n/a (as this relates to documentation)

### Reproduce
See: https://www.npmjs.com/package/pouchdb-debug
See: https://pouchdb.com/api.html#debug_mode

**Comment by carlbennettnz** [comment]
The [introductory guides](https://pouchdb.com/guides/databases.html#debugging) also appear to be outdated.

**Comment by carlbennettnz** [comment]
This still needs fixing
