### ISSUE TITLE
Replication immediately aborted in Android 9 devices.

### ISSUE THREAD

**Issue by joserelloso** [pouchdb/pouchdb#7855]
### Issue
Replication immediately aborted in Android 9 devices.

### Info
- Environment: Ionic App
- Platform: Android
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
Create pouch local db, and try to replicate from couch remote db.

this.businessDB = new _PouchDB('db_name', {
      auto_compaction: true    
});

this.businessDB.replicate.from(remote_db_url, {
      batches_limit: 10,
      batch_size: 100
});

### Error Detail
system: Android 9 
device: motorola moto g(6) play

system: Android 9 
device: samsung SM-J600G

same results in different devices, same Android version

{ result: 
   { ok: false,
     start_time: '2019-07-29T12:51:12.648Z',
     docs_read: 0,
     docs_written: 0,
     doc_write_failures: 0,
     errors: [],
     status: 'aborting',
     end_time: '2019-07-29T12:51:12.851Z',
     last_seq: 0 } 
}

**Comment by karlwestin** [comment]
Here's a few questions that might help you get further with this

- does this create any network traffic at all?
- can you make non-pouchdb fetch calls to your remote db?
- does the thing work on other android versions or iphone?

It's probably helpful to look at permissions for your app, you need to whitelist all urls your app is gonna call if i remember it right
Also please look in other issues related to cordova/ionic here, other devs have posted a lot of information that might help you
good luck!

Please look through older issues with cordova/ionic here

**Comment by joserelloso** [comment]
Hi @karlwestin, thanks for the help!
The app is working in other Android devices, seems to be a version specific error.

Here's the permissions i've in the manifest.
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

**Comment by joserelloso** [comment]
Hi @karlwestin, 
I've updated the url whitelist, but it's still not working on Android 9 devices.
Is there something I can do to get more info in the errors array.
Thanks for the help!

**Comment by karlwestin** [comment]
Maybe debug mode can give you more info? https://pouchdb.com/api.html#debug_mode
Also try making normal [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) calls to your database.. can you reach it that way?

**Comment by MichaelJCole** [comment]
Are you using npm's 'pouchdb' or 'pouchdb-browser' module?

**Comment by joserelloso** [comment]
Hi guys, thanks for the help! 
It seems Android 9 is more strict with security.
I have to set a configuration to allow clear text traffic (or buy SSL certificate) **cleartextTrafficPermitted**.

This link explains how to change this configuration 
[](https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6 )

**Comment by karlwestin** [comment]
thank you for posting the solution so others can find it @joserelloso! good luck with the project!
