### ISSUE TITLE
How to copy local db via alldocs to another?

### ISSUE THREAD

**Issue by adjenks** [pouchdb/pouchdb#7857]
### Issue
Can't copy 1 local db to another.
I must be doing something wrong, but it seems like it's complaining about conflicts when there should be no conflicts because I'm adding data to an entirely separate indexeddb. Shouldn't id's and revisions be unique between databases?

### Info
- Environment: browser
- Platform: FF
- Adapter: IndexedDB
- Server: None

### Reproduce

https://glitch.com/~fifth-color

Or just run this in a browser with pouch loaded:

```JS
var db = new PouchDB('wow');
var db2 = new PouchDB('wow2');
db.put({'_id':'test1','test':1});
db.allDocs().then(o=>console.log(o));
db.allDocs({include_docs: true, attachments: true}).then(o=>{
	o.rows.forEach((row)=>{
		console.log(row.doc);
		db2.put(row.doc).then(function(a){
			console.log(a);
		}).catch(function(e){
			console.log(e);
		});
	});
});

```

> Promise { <state>: "pending" }
> Object { total_rows: 1, offset: 0, rows: (1) […] }
> debugger eval code:4:30
> Object { test: 1, _id: "test1", _rev: "1-56e17fe1cb767d26e17d41cc41f8b09e" }
> debugger eval code:7:11
> Object { status: 409, name: "conflict", message: "Document update conflict", error: true, id: "test1", stack: "" }
> debugger eval code:11:12

**Comment by karlwestin** [comment]
you can write them all at once with `bulkDocs`
if you include `{ new_edits: false }` they will have the same revision as the original docs
https://pouchdb.com/api.html#batch_create

```javascript
const docs = o.rows.map(r => r.doc)
return db.bulkDocs(docs, { new_edits: false })
```

**Comment by MichaelJCole** [comment]
Your code is async, but makes sync assumptions, which will cause race conditions:

```
var db = new PouchDB('wow');
var db2 = new PouchDB('wow2');
db.put({'_id':'test1','test':1});    // Async
db.allDocs().then(...);             // Async - race condition - starts before previous statement finishes
db.allDocs(...).then(...)         // Async - race condition w/ both previous statements
```

Try .then()ing them all together

```
db.put({'_id':'test1','test':1})    // Async
.then(() => {
   return db.allDocs().then(...);             // return promise to then()
})
.then(() => {
  return db.allDocs(...).then(...)         // return promise to then()
})
```

**Comment by adjenks** [comment]
@karlwestin your suggestion of using the "new_edits" option worked, so this worked:

```JavaScript
var db = new PouchDB('wow');
var db2 = new PouchDB('wow2');
db.put({'_id':'test1','test':1});
db.allDocs().then(o=>console.log(o));
var docs;
db.allDocs({include_docs: true, attachments: true}).then(o=>{
	docs = o.rows.map(r => r.doc);
});
db2.bulkDocs(docs, { new_edits: false });
```

I tried to do as you suggested @MichaelJCole by chaining the async functions together properly so that there are no race conditions, but this still seemed to throw an error for some reason:

```JavaScript
var db = new PouchDB('wow');
var db2 = new PouchDB('wow2');
db.put({'_id':'test1','test':1})
	.then((response)=>{
		console.log("Response:",response);
		return db.allDocs({include_docs: true, attachments: true})
			.then((all)=>{
				console.log("All docs object:",all);
				return all;
			});
	})
	.then((all)=>{
		console.log("AllDocs object again:",all);
		all.rows.forEach((row)=>{
			console.log("row.doc",row.doc);
			db2.put(row.doc).then((response)=>{
				console.log('Put response 2:',response)
			}).catch((e)=>{
				console.log('Threw Inner:',e);
			});
		});
	})
	.catch((e)=>{
		console.log('Threw Final:',e);
	});
```
This threw an error though:

> Response:  Object { ok: true, id: "test1", rev: "1-f5680485fe05746a4fea99e76b43fc00" }
> All docs object:  Object { total_rows: 1, offset: 0, rows: (1) […] }
> AllDocs object again:  Object { total_rows: 1, offset: 0, rows: (1) […] }
> row.doc  Object { test: 1, _id: "test1", _rev: "1-f5680485fe05746a4fea99e76b43fc00" }
> Threw Inner:  Object { status: 409, name: "conflict", message: "Document update conflict", error: true, id: "test1", stack: "" }

I also tried using bulkDocs without the "new_edits" option set to false, but this did not work either. I don't understand why the option is displayed in the documentation at the very end of the section as a side note. It says:

> Note: If you set a new_edits property on the options object to false, you can post existing documents from other databases without having new revision IDs assigned to them. Normally, only the replication algorithm needs to do this.

If you compare this to other sections, like the section for `allDocs`, it has a large list of options right near the top. Why does bulkDocs not have a section of options in a similar format? Even if there is only one option, it should follow the same format. I may have otherwise found this option when trying things in the very beginning.

**Comment by adjenks** [comment]
Opened a ticket about the documentation here: https://github.com/pouchdb/pouchdb/issues/7878
