### ISSUE TITLE
401 unauthorized with Pouch DB 7.0.0 communicate to Couch DB

### ISSUE THREAD

**Issue by sundaramoorthyjeeva** [pouchdb/pouchdb#7858]
### Issue
We have developed the ionic application with Pouch DB and Couch DB. We have installed the pouch db npm version 7.0.0 and trying to replicate from Couch DB. It throws 401 unauthorized access to this user error. But when I downgraded the version of pouch db npm to below 7, It is working fine without any issues. What is the root cause of this issue ? If anyone knows, do the needful.

### Info
- Environment: (Ionic/browser/mobile)
- Platform: (Chrome/Android)
- Adapter: (IndexedDB.)
- Server: (CouchDB/PouchDB)

### Reproduce
Just create a simple ionic application with Pouch(7.0.0) and Couch DB. Then make a connection with Couch DB and try to replicate the data from Couch to Pouch DB. It throws 401 error. Just downgrade the pouch db npm and try the same, replicate will be working fine without any issues.

**Comment by karlwestin** [comment]
Can you look in the devtools and see what headers are sent in the requests?
Is there a difference in what headers that are sent in 7.0.0 and 7.1.1?
