### ISSUE TITLE
Sort direction ignored for secondary sorting field

### ISSUE THREAD

**Issue by Procrat** [pouchdb/pouchdb#7863]
### Issue
Doing a Mango query with multiple sorting fields can leave the direction of a second sorting field ignored. (At least, that's what I think is happening.)

### Info
- Environment: browser
- Platform: at least the latest versions of Chrome and Firefox
- Adapter: IndexedDB
- Server: N/A

### Reproduce
I want to do the equivalent of the SQL query `SELECT * FROM db WHERE z = 'y' ORDER BY 'x' ASC, 'y' DESC`.

After reading [the guide on Mango queries](https://pouchdb.com/guides/mango-queries.html#more-than-one-field) a few times, I figured this would work:
```js
let db = new PouchDB('db');
await db.bulkDocs([{x: 1, y: 1, z: 'y'}, {x: 2, y: 2, z: 'y'}, {x: 1, y: 2, z: 'y'}, {z: 'n'}]);
await db.createIndex({ index: { fields: ['z', 'x', 'y'] }, ddoc: 'my-index' });
await db.find({
      selector: { z: 'y', x: { $gte: null }, y: { $gte: null } },
      sort: [{ x: 'asc' }, { y: 'desc' }],
      use_index: 'my-index',
});
```
This resulted in an error: `{error: "no_usable_index", message: "There is no index available for this selector."}`

After playing around with the index, the only time when I wouldn't get an error, was when I did the following:
```js
let db = new PouchDB('db');
await db.bulkDocs([{x: 1, y: 1, z: 'y'}, {x: 2, y: 2, z: 'y'}, {x: 1, y: 2, z: 'y'}, {z: 'n'}]);
await db.createIndex({ index: { fields: ['x', 'y', 'z'] }, ddoc: 'my-index' });
await db.find({
  selector: { z: 'y', x: { $gte: null }, y: { $gte: null } },
  sort: [{ x: 'asc' }, { y: 'desc' }],
  use_index: 'my-index',
});
```
However, this returns
```js
{ docs: [
  {x: 1, y: 1, z: "y", _id: "...", _rev: "..."},
  {x: 1, y: 2, z: "y", _id: "...", _rev: "..."},
  {x: 2, y: 2, z: "y", _id: "...", _rev: "..."}
] }
```
As you can see, it sorts "y" ascendingly rather than descendingly.

**Comment by Procrat** [comment]
It seems similar to issue #7549, although I wouldn't know how to solve it.

**Comment by garrensmith** [comment]
Unfortunately, mango doesn't support mixed sorting.

**Comment by Procrat** [comment]
So how would you do this?
