### ISSUE TITLE
Accessing the request body in the fetch function

### ISSUE THREAD

**Issue by cintolas** [pouchdb/pouchdb#7869]
### Issue
When using PouchDB.sync, I want to be able to access the request body in the fetch function.  Right now it gives url and opts.  Is there any way to overwrite the fetch with the body?  

My use case.  I have 2 Pouch servers behind express proxies that need to communicate with each other.
I want to be able to take the body of an http request, sign it and put the signature in the http header.  During a sync, the remote database url verifies the signature and allows access to the pouch server  If the signature is invalid it rejects the request.

### Info
- Environment: nodejs, pouch-server, http adapter, couchdb 
- Platform: Linux
- Adapter: http
- Server: pouchdb-server using a couchdb http backend

### Reproduce
```
let remoteDB = new PouchDB (dburl, {
        adapter: 'http',
        skip_setup: true,
        fetch: (url, opts) => {
            
            let sig = ''; //HOW DO I GET THE REQUEST DATA SO I CAN SIGN IT WITH MY PRIVATE KEY
            opts.headers.set(X-SIGNATURE, sig);
            return PouchDB.fetch (url, opts);
        },
    });
```

**Comment by karlwestin** [comment]
[From reading the source](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-http/src/index.js) it seems you should have the body as `opts.body`.. is it not available there?

Please note that not all requests will have a body, there's a lot of `GETs` too, and some posts don't have a body either.

**Comment by daleharvey** [comment]
Yup as Karl said, most of the writes are going to go through https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-http/src/index.js#L700 which populates opts.body
