### ISSUE TITLE
$or does not behave like the mango query $or 

### ISSUE THREAD

**Issue by CodeBast4rd** [pouchdb/pouchdb#7872]
### Issue
`$or` does not behave correctly with undefined properties and with `$or` arrays with only one entry.

### Info
- Environment: (Node.js)
- Platform: (Chrome)
- Adapter: (Local-Adapter)
- Server: (CouchDB)

### Reproduce
1. `$or` on undefined properties (in cases where optional properties are used/needed) with `$ne` does not work (also with known workaround `$nin`)
2. `$or` with one entry returns an empty array
3. empty `$or` does not return any result at all

Merge-request containing tests for reproduction can be found here: #7873
Cheers!

**Comment by gaodeng** [comment]
?
