### ISSUE TITLE
db.all_docs very slow -  But fast if browser is offline

### ISSUE THREAD

**Issue by remisteen** [pouchdb/pouchdb#7874]
### Issue
I have a database with 81 documents. When using db.all_docs to get all documents it takes around 2000 ms the first run. When I go to another route on my SPA (Angular) and then back again the db.all_docs uses 18000ms to fetch all documents. What can be causing this? 

Also if i try to set my browser to offline mode i Developer tools we are talking performance around 200ms?! How can this affect the performance of the all_docs api?

When testing Online/Offline using the find() api. The same query takes around 8000ms online, but only 300ms offline

### Info
- Environment: (Node.js/browser.)
- Platform: (Chrome)
- Adapter: (IndexedDB.)
- Server: (CouchDB)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by remisteen** [comment]
Also when I build a new Angular application and connect to the same database and run the same query its finished after around 150 ms.

Is it so that the sync functionality can slow down queries?

**Comment by remisteen** [comment]
Can be closed. Problem was not related to pouchDb

**Comment by Morched23MJ** [comment]
I bet it was a change detection issue. :D
