### ISSUE TITLE
where is the pouchdb-adapter-websql-core repo?

### ISSUE THREAD

**Issue by gaodeng** [pouchdb/pouchdb#7885]
### Issue
Jun 21, 2018  7.0.0 release notes says
it will no longer be available as part of a default PouchDB build and will eventually be moved to the pouchdb-community repo.

@daleharvey

**Comment by gaodeng** [comment]
?

**Comment by TDola** [comment]
I can't seem to find it either.  It's got bugs I want to fix, but can't find it

**Comment by daleharvey** [comment]
Yeh nobody moved the code to the community repo so if you want the code now have to pull it out of the git history here

If you want to make a community repo to maintain it, ping me and happy to give you permissions

**Comment by sofiageo** [comment]
@gaodeng Are you still [interested](https://github.com/pouchdb/pouchdb/issues/7011#issuecomment-497897682) to maintain the project on the community repo? 

If yes, can you ping here so @daleharvey can see it and give you permissions? That would help with projects like https://github.com/craftzdog/pouchdb-adapter-react-native-sqlite to use a pouchdb community repository. Thanks

**Comment by gaodeng** [comment]
@sofiageo 
Since the main code repository seems to have been abandoned, it doesn't make much sense to maintain a submodule
