### ISSUE TITLE
On Safari, live sync with a remote database does not resume after the remote server is restarted

### ISSUE THREAD

**Issue by kwpeters** [pouchdb/pouchdb#7887]
# Issue

In Safari, if a live sync is successfully established between a local and and remote database and then connectivity is lost to the remote database and then restored, the sync stalls.  After this point, documents written to the remote database no longer sync into the local database.

- This issue exists on mobile Safari as well.
- This issue may be related to issue #7824.

# Info

Environment
- Node.js: v10.13.0
- Safari:  12.1 (13607.1.40.1.5)
- PouchDB: 7.1.1

Adapter: IndexDB (Safari default)

Server: [pouchdb-server](https://www.npmjs.com/package/pouchdb-server) (installed as a dependency is the referenced repository's package.json)

# Reproduce

In order to reproduce this issue in a minimal way,[this repo](https://github.com/kwpeters/pouchdb_stops_syncing) has been created.

1. Clone [this repo](https://github.com/kwpeters/pouchdb_stops_syncing)
    ```
    git clone https://github.com/kwpeters/pouchdb_stops_syncing.git
    ```
2. Install dependencies.
    ```
    npm install
    ```
3. In a Terminal window, start the pouchdb-server that will host the remote
   database.
    ```
    npm run start-db-server
    ```
4. In another Terminal window, start a http server that will host the demo web page.
    ```
    npm run start-http-server
    ```
5. Open Safari and navigate to [http://localhost:8000](http://localhost:8000).  This web page will setup a sync between a local (browser) database and a remote database on the server.  Then, it will attempt to update a document in the __remote__ database every 3 seconds.
5. Observe that the sync has been successfully established.  You should see messages stating that the document was successfully written, followed by messages that the sync object has emitted the "active", "change" and "pause" events.
6. Stop the pouchdb-server running in the server Terminal window by pressing Ctrl-C.  At this point, you will start seeing messages in the browser stating that it cannot update the document in the remote database.  This is expected.
7. Start the pouchdb-server again (the same command as in step 3).
    ```
    npm run start-db-server
    ```
8. Observe that the web page is now able to successfully update the document in the remote database.  Also observe that the sync is no longer working.  The document is being updated, but the sync object is no longer emitting the "active", "change" and "pause" events.

If the above procedure is performed with the Chrome browser, the sync resumes working in step 8 (the "active", "change" and "pause" events resume).

Note:  Once in the state described in step 8, if a document is written to Safari's __local__ database, it seems to "kick start" the sync, and it starts working once again.  I don't feel this should be necessary, though.

**Comment by SCdF** [comment]
For clarity, does this still occur with other backends (ie CouchDB)?

**Comment by kwpeters** [comment]
This problem appears to be even worse when running a CouchDB backend.  When following my steps above, I get to step 5 and see the document being written to the remote database, but I never see the log messages showing that the sync object has emitted the "active", "change" and "pause" events.  This is all before shutting down the backend and then restarting it.

If I replace the Safari browser with Chrome, everything works as expected using this CouchDB backend.  The sync properly resumes after shutting down the CouchDB backend and restarting it.

**Comment by mohlsen** [comment]
is this observed in Desktop and mobile safari?

**Comment by kwpeters** [comment]
These are the results I am currently seeing:

| Backend         | Client         | Behavior   |
| -------------   | -------------  | -------------   |
| pouchdb-browser | Desktop Safari | Sync starts but does not resume following server restart       |
| pouchdb-browser | Mobile Safari  | Sync starts but does not resume following server restart       |
| CouchDB         | Desktop Safari | Sync events are never observed even before server is restarted |
| CouchDB         | Mobile Safari  | Sync starts properly and resumes following server restart      |


I'm not sure I trust the CouchDB/Desktop Safari results listed above, because in this case, Safari is logging the error message "Failed to open indexedDB, are you in private browsing mode?".  BTW, I am not in private browsing mode.

**Comment by knubie** [comment]
I'm experiencing the same issue now. After investigating for a few hours I came up empty handed.

At first I thought that maybe Safari is handling `fetch` differently, and isn't triggering the correct callbacks, but I'm pretty sure that's being polyfilled.

**Comment by knubie** [comment]
It seems that this is related to the heartbeat.

When the connection is lost *before* the first heartbeat is received, `fetch` is caught and the retry function is called.

When the connection is lost *after* the first heartbeat is received, `fetch` is never caught, and the retry function is never called, so the connection is never re-established.

Disabling the heartbeat seems to resolve the issue for me.

@kwpeters Thanks for the reproduction repo.

**Comment by kwpeters** [comment]
@knubie, I appreciate you digging into this a little further and am interested to know more about how you resolved the issue by disabling the heartbeat.

Based on your suggestion, I have attempted to disable the heartbeat on branch `disable-heartbeat` of the reproduction repo (commit 6f86e15bbc5006ea8f657fdb5745ce81fcae4bc0), but I still see the same problem when running in Safari.  Did you somehow disable the heartbeat differently?

**Comment by knubie** [comment]
@kwpeters After carefully re-reading your reproduction steps, I think we were experience two different bugs.

On my end I was listening for changes from the server (CouchDB). If no changes were received before the first heartbeat, and the connection was lost to the server, then **_the retry function failed to initiate_**.

It seems that in your original post, **_pushing to the server_** worked, but was not emitting the correct events from the sync object. I actually wasn't able to reproduce that issue with or without `heartbeat: false`.

Here's a sample output from my latest test. Is this different from what you're seeing?

```
Log Messages

Document updated: ok=true

sync event 'paused'

sync event 'change'

sync event 'active':

Document updated: ok=true

sync event 'paused'

sync event 'change'

sync event 'active':

Document updated: ok=true

sync event 'paused'

Not updating document in remote db. It appears to be offline.

Not updating document in remote db. It appears to be offline.

sync event 'paused' <------- Turned off CouchDB here.

sync event 'paused'

sync event 'change'

sync event 'active':

Document updated: ok=true

sync event 'paused'

sync event 'change'

sync event 'active':
```
