### ISSUE TITLE
Getting "SCRIPT5009: 'Promise' is undefined" on IE 11

### ISSUE THREAD

**Issue by ptomblin** [pouchdb/pouchdb#7889]
### Issue
Trying to make a stand-alone browser app and it doesn't work in IE 11 (it works on Firefox and Chrome) because it gives this error:

SCRIPT5009: 'Promise' is undefined pouchdb-7.1.1.min.js (7,98264)
SCRIPT5009: 'PouchDB' is undefined app.js (12,5)

I'm already including the fetch polyfill using <script src="js/fetch.umd.js">.

### Info
- Environment: Browser
- Platform: IE 11
- Adapter: None
- Server: None

### Reproduce
Dropbox of my program at https://www.dropbox.com/sh/5h2jbiqx4wv64cx/AADELIpKrKMO6JmIN5iPnjFBa?dl=0
Open index.html in IE. Enter anything on the entry form. Click "Save".

**Comment by Spudley** [comment]
Since PouchDB v7.0, you also need a promise polyfill.

See this for more info: https://pouchdb.com/2018/01/23/pouchdb-6.4.2.html

**Comment by ptomblin** [comment]
Turns out you can't make a stand-alone app to work in IE 11 because IE 11 doesn't allow IndexDB access unless you load it through a http url instead of a file url. So problem solved, but more problems happened.
