### ISSUE TITLE
Replication hangs on iOS

### ISSUE THREAD

**Issue by dandybudach** [pouchdb/pouchdb#7890]
### Issue
The single-shot replication from a remote Couchdb to the local pouchdb occasionally hangs on iOS Safari without any message.
When doing an initial replication from the CouchDB master to pouch, the process sometimes will not continue after a bunch of requests, meaning no more request is sent to the CouchDB, although the replication is not finished yet.
In total about 80MB have to be transferred. The issue is not related to the amount or requests or stored data (it can happen after 200 requests or 2k).
I noticed that, in case of the issue, the last successfull request is a "_changes" one and then nothing else happens, especially the complete callback is never called.

I can imagine that it has something to do with the IDBTransactions. Maybe the _changes request (re)uses a transaction at the wrong moment, so a wrong onsuccess callback is issued.

### Info
- Environment: Browser
- Platform: iOS 12.4 Safari
- Adapter: idb
- Server: CouchDB

### Reproduce
I hope to get some public data to reproduce. If you need some logs, we can reproduce the issue and modify the pouchdb.js to print to the console whenever it's needed.
For now I can only tell what we are doing:
 1. clean Safari Data
 2. start initial replication by logging in to the website (the user is getting a screen telling "initialization in progress ...")
 3. every fourth or fifth time the replication hangs as described above (the screen "init in progress" will never disappear because the complete event is not fired)
 
We are doing a db.replicate.from(remoteDB) with the following options
{timeout: 60000,
batch_size: 1,
batches_limit: 1,
filter: 'userDocFilter/by_user_group',
query_params: ...}

Best regards,
Dandy

**Comment by gaodeng** [comment]
?

**Comment by dandybudach** [comment]
The issue was caused due to a compaction starting while the synchronization was still in progress.
Problem is solved by configuration.
