### ISSUE TITLE
Ability to get properties on allDocs

### ISSUE THREAD

**Issue by davidhernandeze** [pouchdb/pouchdb#7893]
### Issue
Hi, I'm looking for the better way to retrieve a bunch of documents and their names, I want to call `allDocs()`, and fetch_id, _rev and the property `name` (which is in all my documents) I'm currently using the `include_docs: true` but I think that it can be inefficient when my docs get bigger, because I just need to show the name in my UI, and if the user wants to access that document, it will be fetched on click.
Thanks ! and good job making PouchDB!

**Comment by wizzard0** [comment]
@davidhernandeze it looks like a view is what you're after

* http://docs.couchdb.org/en/stable/ddocs/views/intro.html
