### ISSUE TITLE
[want help] How to backup database?

### ISSUE THREAD

**Issue by yikuo123** [pouchdb/pouchdb#7899]
### Issue
Could anyone tell me how to export database to filesystem?
I use pouchdb with Electron App, and I want to backup and export data to my local disk.

### Info
- Environment: Node.js/Electron
- Platform: Chrome
- Adapter: IndexedDB
- Server: None

**Comment by SCdF** [comment]
It depends on what you mean by "backup".

If you want a copy of all of your replicatable records you could use the changes feed or allDocs as the basis of a batch query that gives you the JSON objects of each record, and then you can do whatever you like with it (save it to disk for example).

If you want a carbon copy of the PouchDB database that contains its exact state (for example, how far along it is in replicating to some other server etc etc) that is more complicated: you'd need to look into backing up IndexedDB itself (along with a tiny amount of localstorage I believe).
