### ISSUE TITLE
Returned promise from db.changes is stuck in pending state

### ISSUE THREAD

**Issue by inator** [pouchdb/pouchdb#7902]
### Issue
When db.changes is used against a remote http db, the returned promise is never resolved (stuck in a pending state).

With `live: true`, thus there's no way to invoke `cancel()` on the changes feed.

I also tried against non-remote http db (`new PouchDB('db');`) and experienced the same result.

### Info
- Environment: Reproduced on Node and Browser
- Platform: Chrome & Safari
- Adapter: http
- Server: CouchDB & PouchDB Server (express-pouchdb)

### Reproduce
```
const db = new PouchDB('http://localhost:5000/pouch/db');

const changes = db.changes({
    since: 'now',
    live: true,
    include_docs: true
}).on('change', change => {
    // Do something
}).catch(error => {
    console.log('caught error', error)
});

// Sometime later
console.log(changes); // Promise { status: "pending" } 
```

**Comment by daleharvey** [comment]
If I remember, the promise still has a `.cancel()` function on it, which is technically not allowed but I think still works

**Comment by inator** [comment]
@daleharvey `.cancel` is undefined.

**Comment by KevinSjoberg** [comment]
I'm seeing this even without `{ live: true }`.

```javascript
const rep = local.replicate.from(remote);
return rep.then(() => console.log(rep));
```

Reports state as `pending`.
