### ISSUE TITLE
CORS on mobile device

### ISSUE THREAD

**Issue by marcelx180** [pouchdb/pouchdb#7908]
# Issue
Hey guys! My website works fine, CORS is working and everything is perfect. But if I try to use my site on a mobile device, JavaScript throws a CORS exception, 

I'm confused, cause everything works fine on PC..

How is that possible?

Thanks for your help!

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by karlwestin** [comment]
you'll need to provide more info - how to reproduce, the error message, screenshots, if the error happens in the browser or in an application, etc to get help but i can tell you one thing

one common problem people have when they package a webapp in ionic/cordova is that the database url needs to be whitelisted in the app. Please look this up in the ionic/cordova documentation and see if it can help you.
