### ISSUE TITLE
Paginating documents using Mango query over index is broken

### ISSUE THREAD

**Issue by KevinSjoberg** [pouchdb/pouchdb#7909]
### Issue
I'm paginating documents using the following Mango query over an index (`type`, `_id`).

```javascript
{
  selector: {
    type: { $eq: 'style' },
    _id: { $gt: "id-here" }
  },
  limit: 100
}
```

This works well for the first page (`{ _id: { $gt: null }`). Given the last document of the first 100 documents has the id `123`, I retrieve the next batch of 100 using `{ _id: $gt: '123' }`. This returns `99` documents instead of `100` and seems to be due to some bug in the relevant adapter for my environment.

Running the same query in Cloudant, returns the next 100 documents as expected. Running the query without an index in place also returns the next 100 documents as expected (but has the drawback of being slow).

It looks like the second query evaluates to running `allDocs` with `keys` including the offset (`123` in this case) and then filters it out, leaving us with `99` documents as a result.

### Info
- Environment: Node.js
- Platform: 
- Adapter: LevelDB
- Server:

### Reproduce
I've created a [repo](https://github.com/KevinSjoberg/pouchdb-index-limit-bug) containing a small reproducible example of what I'm seeing. See the README for details on how to set it up.

The example can be run using `npm start` and `DEBUG=pouchdb:* npm start` with debugging enabled.

**Comment by KevinSjoberg** [comment]
Debugging this further it looks like we're filtering the result of running `allDocs` manually here.

https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-find/src/adapters/local/find/index.js#L131

This seem to be due to the fact that CouchDB does not implement a `inclusiveStart` option. Since we're filtering the records **afterwards**, I guess the limit must be adjusted by one if `inclusiveStart` is `false`. Perhaps here. Maybe in other places as well.

https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-find/src/adapters/local/find/index.js#L112

**Comment by KevinSjoberg** [comment]
Ping @daleharvey. I'd be happy to submit a pull request for it if you're interested. 🙂

**Comment by MaximumCrash** [comment]
@KevinSjoberg I can confirm a similar situation of pagination inconsistencies using find() on my end with a simple query of 

```
find({
selector: {score: {$gt: X}},
sort: [{ score: 'desc' }],
limit: 10
})
```

Limit 10 returns 9 results consistently.

**Comment by garrensmith** [comment]
I think it would be better to use limit and skip to paginate. Otherwise what happens if you use `gte` instead of `gt` that would give you a inclusive start.

**Comment by KevinSjoberg** [comment]
@garrensmith my example is directly taken from the [guides](https://pouchdb.com/guides/mango-queries.html#pagination). What I've described is most definitely a bug and I've also demonstrated why it's happening.

As I've stated before, I'd be happy to submit a fix for it as long as everyone is onboard with the suggested fix.

**Comment by MaximumCrash** [comment]
@garrensmith I would also add that pagination using skip has performance concerns over larger dbs. For example the "Skipping into a trap" section: [https://pouchdb.com/2014/04/14/pagination-strategies-with-pouchdb.html](https://pouchdb.com/2014/04/14/pagination-strategies-with-pouchdb.html)

**Comment by KevinSjoberg** [comment]
I'm not sure who to ping to get the ball moving on this one...

**Comment by garethbowen** [comment]
@KevinSjoberg The best way to get the ball rolling is to submit a PR if you have the time. I can help out with reviewing and merging.

**Comment by KevinSjoberg** [comment]
@garethbowen thanks a lot for the input. I'd be happy to submit the pull request. 🙂
