### ISSUE TITLE
Add Chrome sync storage adapter for extensions

### ISSUE THREAD

**Issue by Sawtaytoes** [pouchdb/pouchdb#7919]
### Issue
No adapter for Chrome's [sync storage](https://developer.chrome.com/extensions/storage#using-sync).

### Info
- Environment: Extensions
- Platform: Chrome and Firefox
- Adapter: Doesn't exist
- Server: None

I use sync storage in chrome and firefox extensions. This is the only way to access it. There's also a local storage for extensions as well which uses the exact same API as sync storage.

I would like to use PouchDB, but there's no adapter present for this scenario even though there's an adapter present for `localStorage`.

Unlike `localStorage`, `chrome.storage.sync` is entirely async and utilizes callbacks. There's also a change listener just like with `localStorage` except that this version responds to every change (including ones from this machine) instead of just those from other tabs.

I tried implementing a solution myself by exporting the DB, using a `machineId` to designate which machine made an update, and importing the entire DB when this occurs. While this functions per-say, it's not ideal. I also have to randomize some part of the `machineId`, as it won't say there was a change if the `machineId` didn't change from the last update.

### Reproduce
Create a [`manifest.json`](https://developer.chrome.com/extensions/manifest) and a [`background.js`](https://developer.chrome.com/extensions/background_pages) file. From there, you have a Chrome extension.

Enable developer mode and click "load unpacked":
![image](https://user-images.githubusercontent.com/3948069/65936843-9ba6ec00-e3e3-11e9-8050-0404a036d7aa.png)

From here, point to the directly your `manifest.json` is located, and it will load your script.

It will show an "inspect views" area. If you click "background page", it will allow you to debug using a standard Chrome console:
![image](https://user-images.githubusercontent.com/3948069/65936933-df015a80-e3e3-11e9-94f3-a3d3ef0fc2dd.png)
![image](https://user-images.githubusercontent.com/3948069/65936921-cd1fb780-e3e3-11e9-85c6-041fca5bfaff.png)

**Comment by akashsark** [comment]
i can work on it

**Comment by Sawtaytoes** [comment]
This is a fairly difficult task. I tried something myself as well without PouchDB. Sync storage in Chrome takes up to 2 minutes to transmit that change to other clients.
