### ISSUE TITLE
Map/reduce with non-existent _id provides wrong doc

### ISSUE THREAD

**Issue by SamuelWeibel** [pouchdb/pouchdb#7922]
# Issue
When using a map/reduce function that emits `{ _id: null }`, the returned `doc` is the "emitting" document instead of `null`.

The result is what I would expect when `_id` is *not* defined; but `_id` is defined and set to `null`.

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB 2.3.1

### Reproduce
The following design doc (modified to not contain confidential info):
```
{
  "_id": "_design/foo",
  "views": {
    "bars": {
      "map": "function (doc) {\n  if (doc.$doctype == 'bar') {\n    emit(doc.fooId|| null, { _id: doc.fooId|| null, name: doc.name });\n  }\n}"
    }
  },
  "language": "javascript"
}
```
Returns this on CouchDB 2.3.1 `http://localhost:5984/db/_design/foo/_view/bars?include_docs=true`:
```
{"total_rows":2,"offset":0,"rows":[
{"id":"two","key":null,"value":{"_id":null,"name":"Two"},"doc":null},
{"id":"one","key":"selun","value":{"_id":"selun","name":"One"},"doc":{"_id":"selun","_rev":"1-xxx","$doctype":"foo","name":"Selun"}}
]}
```
But returns this on PouchDB (see the *wrong* document in the first row):
```
{"total_rows":2,"offset":0,"rows":[
{"key":null,"id":"two","value":{"_id":null,"name":"Two"},"doc":{"$doctype":"bar","name":"Two","_id":"two","_rev":"1-yyy"}},
{"key":"selun","id":"one","value":{"_id":"selun","name":"One"},"doc":{"$doctype":"foo","name":"Selun","_id":"selun","_rev":"1-xxx"}}
]}
```
The documents are:
```
{"$doctype":"foo","name":"Selun","_id":"selun"}
{"$doctype":"bar","name":"One","_id":"one","fooId":"selun"}
{"$doctype":"bar","name":"Two","_id":"two"}
```

**Comment by frknasir** [comment]
Its confusing what you are trying to achieve but i think what's worth remembering is that with emit functions, the first argument is the key...which can be an attribute that is not even from the doc. think of view map function as a way of grouping documents in a sorted order according to the key. hope that helps!

**Comment by SamuelWeibel** [comment]
I'm not sure what you're trying to say. I know that the first argument is the key. The problem is, I'm mapping a 0..1 to n relationship; so the "reference" (in this case `fooId`) can be `undefined`. Since I don't want to use `undefined` but rather `null`, we do the `|| null`. I know, I could just _not emit_ the document, but I need to be able to find all documents that don't have a "reference".

Having all this said, it is is a fact that CouchDB handles the `null` reference correctly (not showing a document) while PouchDB doesn't (showing the wrong document).

**Comment by frknasir** [comment]
then what you want to do is wrap the emit in an `if` block checking for documents with no reference.

**Comment by SamuelWeibel** [comment]
If you look at the results that I'm getting from CouchDB, this is exactly what I want: all documents id's with `$doctype == 'bar'`:
```
{"total_rows":2,"offset":0,"rows":[
{"id":"two","key":null,"value":{"_id":null,"name":"Two"},"doc":null},
{"id":"one","key":"selun","value":{"_id":"selun","name":"One"},"doc":{"_id":"selun","_rev":"1-xxx","$doctype":"foo","name":"Selun"}}
]}
```

What I would get with your suggestion is only all document ids of documents that have `fooId` set (see the missing id `'two'`:
```
{"total_rows":2,"offset":0,"rows":[
{"id":"one","key":"selun","value":{"_id":"selun","name":"One"},"doc":{"_id":"selun","_rev":"1-xxx","$doctype":"foo","name":"Selun"}}
]}
```

**Comment by frknasir** [comment]
if i understand you correctly,  the code below should work for you. you don't need to specify `null` or otherwise

```
{
  "_id": "_design/foo",
  "views": {
    "bars": {
      "map": "function (doc) {\n  if (doc.$doctype == 'bar') {\n emit(doc.fooId, { _id: doc.fooId, name: doc.name });}"
    }
  },
  "language": "javascript"
}
```

**Comment by SamuelWeibel** [comment]
This seems correct. I can't test it right now, but I'm assuming you will see the same discrepancy between CouchDB and PouchDB.

**Comment by frknasir** [comment]
hmm....but the above code should produce the same behaviour in both couchdb and pouchdb!
