### ISSUE TITLE
Data loss during iOS 13 upgrade

### ISSUE THREAD

**Issue by rtholmes** [pouchdb/pouchdb#7925]
### Issue

When upgrading to iOS 13, my Cordova-based app loses its database.

### Info
- Environment: Cordova, PouchDB 7.0
- Platform: Cordova on iOS 13
- Adapter: idb
- Server: N/A, local only

### Reproduce

* Create a PouchDB on device running iOS 12 within a Cordova app (my code for this is below):

```
const name = "myDb";
const db = new PouchDB(name);
console.log("PouchStore::getDB( " + name + " ) - iOS; adapter: " + db.adapter);
db.info().then(function (result) {
    console.log("PouchStore::getDB() - iOS info: " + JSON.stringify(result));
}).catch(function (err) {
    console.log("PouchStore::getDB() - iOS info ERROR: " + err.message);
});
```

This emits the following, and reading/writing to the DB proceeds as usual:

```
2019-10-04 12:19:58.255465-0700 Retrace[662:107603] PouchStore::getDB( myDb ) - iOS; adapter: idb
2019-10-04 12:19:58.360706-0700 Retrace[662:107603] PouchStore::getDB() - ios info: {"doc_count":288,"update_seq":288,"idb_attachment_format":"binary","db_name":"myDb","auto_compaction":false,"adapter":"idb"}
```

* Update device to iOS 13. Database is now empty.

Note: For prior major iOS upgrades this has not been a problem and the database has maintained all of its data between OS upgrades. I have also tried this through the iOS 13 upgrade with an alternative database instantiation (`const db = new PouchDB(name, {auto_compaction: true, iosDatabaseLocation: 'Library'}); `) but the data also does not persist then either. Is this a problem with how I create the database, or is it expected that the data will have been lost between iOS updates?

**Comment by etiks3** [comment]
I have the same issue here, after device's upgrade with iOS13 all data were lost on all devices. I'm waiting for some more info from user to reproduce the exact behavior and will report info here asap.
