### ISSUE TITLE
[pouchdb-find] Crash with $in using two-field index

### ISSUE THREAD

**Issue by wwoods** [pouchdb/pouchdb#7927]
### Issue
Using the `$in` query with an index containing more than one field leads to a crash.  The below MWE demonstrates the issue, and that the problem does not have a simple workaround in user code.

```js
var PouchDb = require('pouchdb');
PouchDb.plugin(require('pouchdb-find'));

var db = new PouchDb('test');
(async () => {
  // OK if only one field in index, CRASH if two fields
  await db.createIndex({index: {fields: ['type', 'other']}});
  // Creating both types of indexes still results in the crash, even though the more narrow index might be reasonably selected to avoid the issue.
  await db.createIndex({index: {fields: ['type']}});

  await db.post({type: 'a', other: 1});
  await db.post({type: 'b', other: 2});
  await db.post({type: 'c', other: 3});

  var response = await db.find({selector: {type: {$in: ['a', 'b']}}});
  console.log(response);
})().catch(console.log);
```

```
TypeError: Cannot use 'in' operator to search for 'startkey' in undefined
    at getMultiFieldQueryOpts (/node_modules/pouchdb-find/lib/index.js:1082:30)
    at getCoreQueryPlan (/node_modules/pouchdb-find/lib/index.js:1128:10)
    at planQuery (/node_modules/pouchdb-find/lib/index.js:1142:23)
    at /node_modules/pouchdb-find/lib/index.js:1214:21
```

### Info
- Environment: Node.js and browser - confirmed in both.
- Platform: Chrome / FF / Node.
- Adapter: IndexedDB or LevelDB.
- Server: None.

### Reproduce
Glitch link with above example set up using PouchDB 7.1.1: https://uneven-oxygen.glitch.me

**Comment by MaximumCrash** [comment]
@wwoods I had a little bit of an epiphany last night. Since this fix might be on hold for a little bit my solution to getting $in functionality is to instead use $regex and pipe the values I need.

For example this returns results that have a year of 2010, 2011, or 2012 based on the needs of the regex:

selector: {
   'year': {
        $regex: new RegExp('(2010|2011|2012)', gm)
   }
}
 Only downside is it won't work if your selector datatype is an array. Hope this helps.

**Comment by wwoods** [comment]
Still an issue, stale-bot.
