### ISSUE TITLE
iOS 13 indexed db creation is slow

### ISSUE THREAD

**Issue by justinbarry** [pouchdb/pouchdb#7928]
### Issue
Safari on iOS 13 seems to take forever to initialize/load databases.

### Info
- Environment: Browser
- Platform: Mobile
- Adapter: IndexedDB
- Server: N/A

### Reproduce
I'm pretty sure this is not a pouchdb problem. I'm just not sure where to complain. Please advise.

See: 
https://github.com/AugurProject/pouchdb-perf
https://augurproject.github.io/pouchdb-perf/

And my results using a simulator.
<img width="882" alt="image" src="https://user-images.githubusercontent.com/328965/66679803-fa5e3800-ec23-11e9-9074-4fdf28d068cd.png">

In "private" browsing mode the results are more similar:
![image](https://user-images.githubusercontent.com/328965/66680573-b53b0580-ec25-11e9-99df-da4231ebb762.png)

**Comment by PeterBWu** [comment]
This chart is the performance of indexedDB's dbRequest.get(key) function and PouchDB's pouch.find(selector) function.![perf_chart](https://user-images.githubusercontent.com/23109224/76785493-ca870380-6772-11ea-8596-62782bd7dcb2.png)
Performance Issues seem to be related to safari 13 itself and the number of stores that are created. It appears that safari 12 did not have this same issue.
