### ISSUE TITLE
bulkDocs slow

### ISSUE THREAD

**Issue by alexpirine** [pouchdb/pouchdb#7930]
### Issue

The bulkDocs API is a bit slow. Is there a workaround to make it faster?

I need to insert 40,000 new documents (that I already have in memory) in an empty local PouchDB database (with IndexedDB storage).

Is there anything I can do to speed-up the process?

Maybe something like generating random revs beforehand and using the `new_edits` flag?

I'm trying to find a shortcut…

Any performance tip would be highly appreciated.

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: irrelevant

**Comment by jcalixte** [comment]
Hi, have you tried spliting these documents and doing multiple `bulkDocs` ? With 500 for example.
