### ISSUE TITLE
[question]Can you help me to escape those async function hell without async/await?

### ISSUE THREAD

**Issue by kybetter** [pouchdb/pouchdb#7945]
### Issue
I have to set a global id, and then set a primary document, at first run.
So I write the code below, Can you help me to escape those async function hell, without async/await?
because I can't use async/await in nodeJS.

```js
const PouchDB = require('pouchdb');
const db = new PouchDB('mydb');
db.get('global_id').then(res => {
  console.log('1', res);
  db.get(`${res.id}`).then(res => {
    console.log(res);
  }).catch(err => {
    console.log(err);
  });
}).catch(err => {
  console.log('2', err);
  db.put({ _id: 'global_id', id: 0}).then(res => {
    console.log('3', res);
    db.get('global_id').then(res => {
      console.log(4, res);
      db.put({
        _id: `${res.id}`,
        content: 'set some primary data, at first enter.',
      }).then(res => {
        console.log('5', res);
      }).catch(err => {
        console.log(6, err);
      })
    }).catch(err => {
      console.log(7, err);
    })
  }).catch(err => {
    console.log(8, err);
  })
})
```

### Info
- Environment: Node.js
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by SCdF** [comment]
Firstly, you definitely can use async / await in NodeJS, it just requires 7.10.x and above.

Secondly, promises are a chain, and so as long as you return results from promises to not break the chain, you don't need to catch like you're doing: you only have to catch once:

```js
return ifThisFnErrors()
  .then(() => orThisFn())
  .then(() => {
    orThisFnIfItThrowsAnError(); // because it's inside a promise chain

    return orThisFnIfItIsAPromise()
      .then(() => orThisFnAsWell());
  }).catch(err => {
    // Then all following code will be skipped and this block will run with
    // the error.
  }).then(() => thisWillRunEvenIfStuffBeforeItErrorsBecauseOfTheCatchBlock())
  .then(() => {
    thisWontBeCaughtIfItReturnsAPromise()
  })
  .catch(err => {
    // this will catch the:
    //   thisWillRunEvenIfStuffBeforeItErrorsBecauseOfTheCatchBlock
    // function, but
    //   thisWontBeCaughtIfItReturnsAPromise
    // Won't be, because we're throwing away the returned Promise.
  })
```

**Comment by karlwestin** [comment]
Also, Nolan wrote this amazing article a few years back, it's all still relevant https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html

It's long, but it really helped me sort my thinking about promises out, hope it can help you too!

**Comment by kybetter** [comment]
Thank you very much.
I know how to use Promise now.
Blessing.
