### ISSUE TITLE
Database is not accessible after the packaging app.asar file (electron) 

### ISSUE THREAD

**Issue by damianIMLS** [pouchdb/pouchdb#7950]
### Issue

Database is not accessible after packaging it into app.asar file.

Here is the call:
```
const resourcepath = apppath + path.sep + 'Resources' + path.sep
Db = new PouchDB(resourcepath+'lsDB');

```
And the error:

> "IO error: /Users/damian/playground/.../app.asar/Resources/lsDB/LOCK: Not a directory", stack: "OpenError: IO error: /Users/Damian/playgro…es/abstract-leveldown/abstract-leveldown.js:30:14"}"

I know the directory exists, as I can access and read its content from the same .js file I open the pouchDb, including the content of the database directory itself:

`fs.readdir(resourcepath, function (err, files){console.log(files)})`

> 000249.log
> 000250.ldb
> CURRENT
> LOCK
> LOG
> LOG.old
> MANIFEST-000247

If I simply include the global path to the db directory anywhere outside the app.asar file everything works as it should.  It seems for me like leveldown.js can't read into the the app.asar package.

Any clue what may have happened there?
Sorry, I'm a noob with node.js/electron

### Info
- Environment: (Node.js/electron (7.1.0))
- Platform: (Mac Mojave)
- Adapter: (None)
- Server: (PouchDB (7.1.1))

### Reproduce.
I'm using  electron-builder + yarn to package it the app.

**Comment by damianIMLS** [comment]
Solution:
require('pouchdb-browser') instead of require('pouchdb')

**Comment by damianIMLS** [comment]
update: Pouchdb-browser is using different adapter (IndexDb instead of levelDb) and does not initiate the database in the directory specified in the name. Therefore it seems to work (it doesn't throw the error at least), but it is not the intended outcome.

The real reason for the error was that packaged asar file are read-only. Therefore when packaging pouchdb the database location has to be specified as extraResources (which are not packaged in asar). This works perfectly.

**Comment by karlwestin** [comment]
thank you for commenting on what the fix was! it's really helpful for all those out there working on electron apps
side note - You can decide what adapter to use in the pouchdb constructor https://pouchdb.com/api.html#create_database
