### ISSUE TITLE
Windows 32 Bit Not working

### ISSUE THREAD

**Issue by Mhmetengineer** [pouchdb/pouchdb#7959]
Firstly, thanks for app.
I am using pouchdb in electron . APP working on  Windows 64 bit  but not working 32 bit. 
How can i solve it ?

**Comment by TDola** [comment]
use pouchdb-browser instead.  Electron has to recompile native dependencies and standard pouchdb uses leveldown for node integration.  You don't need this unless you plan to use pouchdb from your main process (and you shouldn't do that).  Pouchdb-browser works perfect in the renderer process and excludes leveldown.
