### ISSUE TITLE
Release 7.2

### ISSUE THREAD

**Issue by garethbowen** [pouchdb/pouchdb#7964]
# Release 7.2

I'd like to get a release out so the new indexeddb adapter is published to npm and we can start putting it through its paces.

- [x] Expose new indexeddb adapter https://github.com/pouchdb/pouchdb/pull/7618

This would also include the usual crop of bug fixes, dependency updates, and documentation improvements.

Please reply with comments, reservations, suggestions for other things to include, or just a thumbs up if you approve!

**Comment by daleharvey** [comment]
Would love to, anything you need me to do? I think we can forego blog posts if its slows down the release

**Comment by endyjasmi** [comment]
I'm sorry but any news on this?

**Comment by garethbowen** [comment]
@daleharvey It turns out I don't have permission on npm. Can you grant me access to publish all the packages so I can get this release out?

**Comment by daleharvey** [comment]
@garethbowen sorry about that, added you to every pouch-repo so should be good now

**Comment by garethbowen** [comment]
@daleharvey @garrensmith I think there are a few packages that I still don't have permission to, and unfortunately I succeeded in publishing `pouchdb@7.2.0` so I think this is now more urgent - anyone using 7.2.0 will get an error. I've attempted to `unpublish` from npm but I don't think it's worked...

I think these are the ones I'm missing:

- pouchdb-abstract-mapreduce
- pouchdb-collections
- pouchdb-fetch
- pouchdb-debug
- pouchdb-mapreduce

If you could please grant me permissions on those I'll get a 7.2.0 (or 7.2.1 if necessary) out ASAP.

**Comment by daleharvey** [comment]
There is like 50 packages there, sorry about that, would be a nice situation to fix if anyone fancied a stab at it. 

But added you to those repos for now

**Comment by garethbowen** [comment]
@daleharvey Thanks! 7.2.1 is now released.

There's just one step left which is to `npm run publish-site`. When I run it it prompts me for `pouchdb@pouchdb.com's password:`. Can someone send this to me, or run `publish-site` on my behalf? Then we can close this off.

**Comment by garethbowen** [comment]
@daleharvey @garrensmith Can I get a hand on this? There's only one small step left then we can close this off.

**Comment by daleharvey** [comment]
Ah sorry, yeh can you send me your public key to dale@arandomurl.com and will add it to the server

**Comment by lochehong** [comment]
Whats the state of the 7.2 release? i'm not able to test it without npm.

**Comment by DrJume** [comment]
The website is still showing release 7.1.1. I think someone forgot to update the website.

**Comment by daleharvey** [comment]
Updated the website finally - https://pouchdb.com/
