### ISSUE TITLE
Memory Adapter Not working with PocuchDB find (Data not fetching )

### ISSUE THREAD

**Issue by ervijjusty** [pouchdb/pouchdb#7967]
### Issue

I'm using PouchDB with IDB with PouchDB find using Index. But In a large Document and large DB, the performance of the app is getting very slow. so I'm switching the adapter to Memory. so we start the app first time the data will display properly when I'm refreshing the app the data went missing and the error was log in the console 

this.database = new PouchDB('demoDB',{adapter: 'memory'});

**ERROR Error: Uncaught (in promise): Object: {"error":"no_usable_index","message":"There is no index available for this selector."}**

level DB adapter also not worked with electronJS
But the indexes are working properly when I'm not using the memory adapter.

Please help me out from here either please let me with adapter is best for the large database and also performance-wise

### Info
- Environment: (Node.js/ Angular 8 / ElectronJS)
- Platform: (Chrome)
- Adapter: (Memory)
- Server: (CouchDB)

**Comment by uvlek** [comment]
Also have this problem
