### ISSUE TITLE
PouchDB 7, immediate and web workers

### ISSUE THREAD

**Issue by matticala** [pouchdb/pouchdb#7973]
### Issue
Hello! I know this has been asked before but it was way long ago.
I am trying to offload `pouchdb-browser` to a web worker but I am hitting against `immediate.js` hard reference to `global`. The library had seen its last commit in 2016 and there has been an issue opened there since 2017: https://github.com/calvinmetcalf/immediate/issues/27

Any idea on how to use PouchDb in a web worker?

`worker-pouch` hasn't been updated in 1.5 years (still referencing 6.2.0) and, I think, it wouldn't be able to create a PouchDb inside a web worker anyway because of immediate.

### Info
- Environment: hybrid app
- Platform: electron
- Adapter: web worker

### Reproduce

Inside a web worker:
```js
import PouchDB from 'pouchdb-browser'

const instance = new PouchDB('foo', { adapter: 'idb' })

const receive = ({ data }) => instance.put(data).then(postMessage)

onmessage = receive
onmessageerror = console.error
```

running, you will see:
```
Uncaught ReferenceError: global is not defined
    at eval (browser.js?49b8:2)
    at Object../node_modules/pouchdb-browser/node_modules/immediate/lib/browser.js (6c62753….worker.js:133)
    at __webpack_require__ (6c62753….worker.js:20)
    at eval (index.es.js?d6e1:1)
    at Module../node_modules/pouchdb-browser/lib/index.es.js (6c62753….worker.js:121)
    at __webpack_require__ (6c62753….worker.js:20)
    ...
```

Thank you in advance for any answer you will provide :)

**Comment by daleharvey** [comment]
We used immediate as a promise polyfill, I thought it was removed, but if not, could remove it?

**Comment by matticala** [comment]
@daleharvey that would be great. I tried working around this but `immediate` is brought in by many different dependencies.

**Comment by pschild** [comment]
I recently had the same issue. Is there any news on removing the `immediate` dependency?

**Comment by shahidul-brur** [comment]
Is there any update on removing the `immediate` dependency?

**Comment by Anchakor** [comment]
FYI I've managed to use PouchDB from service worker using bundles and importing them in the worker script file:

```typescript
///<reference path="../node_modules/@types/pouchdb/index.d.ts" />
///<reference path="../node_modules/@types/pouchdb-find/index.d.ts" />
importScripts('scripts/pouchdb-7.3.0.js');
importScripts('scripts/pouchdb-find-7.3.0.js');
```

https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts
