### ISSUE TITLE
Feature request/enhancement: replication via background sync

### ISSUE THREAD

**Issue by ianengelbrecht** [pouchdb/pouchdb#7974]
[This great blog post](https://medium.com/offline-camp/hack-time-service-workers-background-sync-and-pouchdb-3c8b71535823) outlines some considerations for implementing this, but I haven't found anything on progress implementing it as a feature of Pouch or a plugin since then. It would be great to have - "syncs from your pocket" would be the in-app seller.

**Comment by mqtik** [comment]
In apps, I'm syncing PouchDB in the background using RnBgTask, and boost quite a lot the performance, since it does not uses the main thread.
