### ISSUE TITLE
Limit not working for query with keys option specified

### ISSUE THREAD

**Issue by NikolayMakhonin** [pouchdb/pouchdb#7976]
### Issue
If I specify `key` it work correctly:
```js
var docs = await db.query(function mapFunc(doc, emit) {
	if (doc.type) {
		emit(doc.type)
	}
}, {
	limit: 2,
	key: 'tag',
})

docs.rows.length === 2
```
If I specify `keys` it return all rows filtered by keys (ignore `limit`):
```js
var docs = await db.query(function mapFunc(doc, emit) {
	if (doc.type) {
		emit(doc.type)
	}
}, {
	limit: 2,
	keys: ['tag'],
})

docs.rows.length === 5
```

### Info
- Environment: Node.js
- Npm package: pouchdb v7.1.1
- Adapter: Default
- Server: PouchDB

**Comment by AlbaHerrerias** [comment]
This issue has been addressed and merged to master in https://github.com/pouchdb/pouchdb/pull/8404. A new release will land soon. Thank you
