### ISSUE TITLE
Compaction does not work with indexdb

### ISSUE THREAD

**Issue by gautambt** [pouchdb/pouchdb#7978]
### Issue
Initializing PouchDB with auto_compaction set to true seems to have no effect on number of revisions stored

### Info
- Environment: Browser
- Platform: Chrome
- Adapter: Indexdb
- Server: None

### Reproduce
Open https://dust-zebu.glitch.me/ & Hit Run. This sample does a random update every second. You can see that the number of revisions goes up to 1000 (which is the default revs_limit) and then stops. I would have expected the number of revisions to be 1.

**Comment by klues** [comment]
seems to be related to my issue: https://github.com/pouchdb/pouchdb/issues/7784
Unfortunately no answer since more than a year.

**Comment by klues** [comment]
*bump*

**Comment by klues** [comment]
...

**Comment by daleharvey** [comment]
compaction doesnt change the amount of revisions we keep track of (that is revs_limit), just the amount we store the data of
