### ISSUE TITLE
Support for CouchDB 3.0

### ISSUE THREAD

**Issue by natcohen** [pouchdb/pouchdb#7987]
Is there any plan to support CouchDB 3.0 when it’s released? AFAIK, the release is around the corner!

**Comment by willholley** [comment]
Are there any specific changes that you are thinking of? There aren't any changes to the replication API and the user-facing API changes are minimal; OTOH I can't think of anything that would impact PouchDB.

**Comment by natcohen** [comment]
@willholley What about the shared database? I read somewhere they will add an _access key to documents to allow limited access. Not sure it impacts in any way PouchDB...

I also wanted to make sure PouchDB becomes a bottleneck when the new version is released.
