### ISSUE TITLE
Issue while creating PouchDB on Firefox version 72.0.1 

### ISSUE THREAD

**Issue by k-pranav862** [pouchdb/pouchdb#7988]
### Issue
**Failed to open indexedDB, are you in private browsing mode? after enabling "Don't remember history" (not working in firefox Private browsing)**

### Info
- Environment: (**browser**)
- Platform: (**FF**)
- Adapter: (**IndexedDB**)
- Server: (**PouchDB Server**)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/
![pouch_issue](https://user-images.githubusercontent.com/59817702/72237455-848db200-3600-11ea-89aa-b9b15e016140.JPG)

**Comment by birtles** [comment]
I'm pretty sure the root cause is still Firefox not supporting IndexedDB in Private browsing mode ([Mozilla bug 781982](https://bugzilla.mozilla.org/show_bug.cgi?id=781982)). I don't think there's anything Pouch can do for "Don't remember history" mode.
