### ISSUE TITLE
www subdomain is flagged as insecure and pointing to some random server

### ISSUE THREAD

**Issue by danielo515** [pouchdb/pouchdb#7992]
### Issue
http and https versions of www subdomains point to random servers

### Info

I just clicked on an old link that was pointing to www.puchdb.com and I saw a "welcome to ngix" white screen, exactly the same as reported on #207
Seems that the subdomain is again directed to a wrong instance.
The https version (https://www.pouchdb.com/) is even weirder, it first shows the usual screen that the certificate is not trusted, and if you decide to open the page anyway, well, this is what you get:

![image](https://user-images.githubusercontent.com/2270425/72635599-71ab1280-395d-11ea-90a8-801d5c82542c.png)

I will call this phishing if the content was even remotely related to pouchdb, but seems like just some random internet page.

**Comment by daleharvey** [comment]
lol thats another site on my server, I have just never setup www subdomains, nowhere should link to them but will see if dokku will deal with that automatically for me

**Comment by danielo515** [comment]
This has not been fixed yet @stale

**Comment by danielo515** [comment]
The problem is still present today, it's up to you to fix it, but I think it is harmful for the project.

**Comment by danielo515** [comment]
I don't want to insist, but I think it's important to at least keep the issue open
