### ISSUE TITLE
No matching index found, create an index to optimize query time

### ISSUE THREAD

**Issue by manikandankumaran** [pouchdb/pouchdb#8003]
### Issue
Response I got : 
{
  "docs": [
    {
      "name": "Donkey Kong",
      "series": "Mario",
      "debut": 1981,
      "_id": "dk",
      "_rev": "1-fcd440e1689c1542681c87bb784d7c8d"
    },
    {
      "name": "Fox",
      "series": "Star Fox",
      "debut": 1993,
      "_id": "fox",
      "_rev": "1-41edf1b732f533f56c0a81cf9a263984"
    }
  ],
  "warning": "no matching index found, create an index to optimize query time"
}

I can't able to use for $or operator in pouchdb find. 
Please do the needful.

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

### Reproduce
URL For Reproduce :  **http://nolanlawson.github.io/pouchdb-find/**

db.find({
  selector: {
    $or : [{
    name : 'Donkey Kong'
  },
  {
    name : 'Fox'
  }]}
});

**Comment by jhonnattan123** [comment]
in the test page is not posibly create and index. but if you want to create a index use this before find
db.createIndex({
    index:{
       fields:["name"]
    }
 });
   
![image](https://user-images.githubusercontent.com/31730855/77844404-ecbe4f80-717c-11ea-875b-699cfdce4091.png)
