### ISSUE TITLE
angular view did not update on sync change

### ISSUE THREAD

**Issue by nofear87** [pouchdb/pouchdb#8007]
Any ideas why the value (7) triggered in on change hook is never updated in angular view?

this first value (5) works like a charme.

```
init() {
    this.changes.next(5);
    this.pouch = new PouchDB('app', {});
    const remoteDB = new PouchDB('http://127.0.0.1:5984/app', {
      skip_setup: true,
      auth: {
        username: 'root',
        password: 'root'
      }
    });
    const sync = this.pouch
        .sync(remoteDB, {
          live: true,
          retry: true
        })
        .on('change', info => {
          console.log(info);
          this.changes.next(7)
        })
  }
```

**Comment by garethbowen** [comment]
Which version of Angular are you using?

For AngularJS v1, you have to trigger a digest after the `this.changes.next(7)` line in order to update the UI. Use this package to do this automatically: https://www.npmjs.com/package/angular-pouchdb

**Comment by nofear87** [comment]
@garethbowen  no. I'am using angular 9.
