### ISSUE TITLE
PouchDB using _all_docs during replication

### ISSUE THREAD

**Issue by paulund** [pouchdb/pouchdb#8009]
### Issue
When using pouchdb replication with cloudant we're reaching global queries limit very quickly during replication.

I think this is coming from using the `_all_docs` endpoint is places such as https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-replication/src/getDocs.js#L135

Is there another way of doing this possibly using the `_bulk_get` endpoint instead?

**Comment by willholley** [comment]
IIRC the `_all_docs` optimization predates the `_bulk_get` endpoint so it's somewhat less useful than it used to be. The least controversial fix is probably just to have a replication option to bypass the optimization but leave the default behaviour as is. Without benchmarking, it's difficult to know whether there's a significant improvement now that `_bulk_get` is widely supported.
