### ISSUE TITLE
Error: Invalid Adapter: idb

### ISSUE THREAD

**Issue by bluelovers** [pouchdb/pouchdb#8012]
### Issue

https://pouchdb.com/api.html#create_database

```ts
import PouchDB from 'pouchdb';

const myPouchDB = PouchDB.defaults({
	// @ts-ignore
	adapter: 'idb'
});

var myPouch = new myPouchDB('foo');
```

### Info

- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by garethbowen** [comment]
@bluelovers What version are you using?

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/74977844-797f3a80-5466-11ea-916f-8dad95977644.png)

**Comment by garethbowen** [comment]
@bluelovers Can you try 7.1.1 to work out if it's a bug in the 7.2.1 release or an issue with your bundling?
