### ISSUE TITLE
pouchdb-http: unmaintained

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#8014]
When running i live changes feed using the http adaptor there seem to be a memory leak here, https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-http/src/index.js#L1009

Looks like the http adapter will default to `return_docs: true` even when running in "live" mode which means that it will eventually run out of memory.

**Comment by ronag** [comment]
```js
db
              .changes({
                since: seq || 'now',
                live: true
              })
              .on('change', change => o.next(change))
              .on('error', err => o.error(err))

```

**Comment by ronag** [comment]
The problem is we are using `pouchdb-http` which is no longer maintained.... that's going to be a problem going forwards...

**Comment by seigel** [comment]
Ideas on fixes?  Is the path going forward replacing `pouchdb-http` with something else or find a maintainer of `pouchdb-http`?

**Comment by ronag** [comment]
Is it possible to add a deprecation warning to the package?

**Comment by AGrzes** [comment]
`pouchdb-http` contains 2 lines of code 

```javascript
module.exports = require('pouchdb-core')
  .plugin(require('pouchdb-adapter-http'))
```

and 2 dependecnies

```json
    "pouchdb-adapter-http": "^6.0.3",
    "pouchdb-core": "^6.0.3"
```

so reproducing those 2 lines of code inside Your project but using PouchDB 7 would be a solution.

Essentially follow instructions on [this](https://pouchdb.com/custom.htm) page.

**Comment by ronag** [comment]
@AGrzes: Yes, we don't use this package anymore. However, other people might be using it, thinking they have the latest version of pouch not knowing this package is no longer maintained.

**Comment by AGrzes** [comment]
@ronag You are right - and I believe @nolanlawson is both maintainer of the package github repository and collaborator on the npm package so can we please get [deprecation warning](https://docs.npmjs.com/cli/deprecate)

**Comment by NotMoni** [comment]
You can’t close a issue that’s a problem
