### ISSUE TITLE
PouchDB compatibility with Couchbase Sync Gateway

### ISSUE THREAD

**Issue by newlegendmedia** [pouchdb/pouchdb#8015]
### Issue
Is PouchDB compatible with recent versions of Couchbase Sync Gateway ?
 I have a couchbase database that is up to date and I am looking for something like PouchDb for a web app client. The current Couchbase Mobile cannot be used from Javascript without a Cordova or Electron plugin. Your answer would be greatly appreciated.

### Info
- Environment: Browser
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: indexedDB
- Server: Couchbase Server 6.5

**Comment by hermitdemschoenenleben** [comment]
I am working on a app where PouchDB is used with couchbase sync gateway and it works well. There is one issue, though: CSG's _bulk_get returns a multipart response which cannot be handled by browsers. This results in additional requests than necessary, but works fine.

In my app I have access to native HTTP of Android / iOS and wrote a plugin that uses these native methods for _bulk_get: https://github.com/hermitdemschoenenleben/pouchdb-csg/

**Comment by daleharvey** [comment]
We dont test or aim for Couchbase support, if Couchbase has CouchDB compatibility then we would but they broke it in various ways previously
