### ISSUE TITLE
indexed db sync with remote, maximum call stack

### ISSUE THREAD

**Issue by feedmepos** [pouchdb/pouchdb#8021]
#4360 # Issue
I'm trying to use the new indexeddb adapter to perform syn with remote couch db.
There're around 1k of doc, when the syncing reach 300+, I get the following error
![image](https://user-images.githubusercontent.com/54831515/76081527-469b8180-5fe4-11ea-8443-a44ebcfb3a5d.png)
```javascript
// Error happen at this line
    txn.objectStore(DOC_STORE).put(doc).onsuccess = function () {
      results[i] = {
        ok: true,
        id: doc.id,
        rev: writtenRev
      };
      updateSeq(i);
    };
  }
```

However, i have no issue with old idb adapter

### Info
- Environment: Browser
- Platform: Chrome
- Adapter: indexeddb
- Server: CouchDB

**Comment by SCdF** [comment]
Hey @feedmepos I don't think the code linked is where the issue is occurring, as the issues as I read them from your stacktrace is inside some eval'd code (eg if you're doing filtered replication maybe, or if you have a validate_doc_update function).

What is your replication setup?

**Comment by feedmepos** [comment]
Hi, as below is my replication setup
```javascript
connections.remote.replicate.to(connections.main, {
   batch_size: 25,
   filter: doc => !doc._id.includes("_design/")
});
```
