### ISSUE TITLE
Invalid Adapter: indexeddb

### ISSUE THREAD

**Issue by AlexKolesnik** [pouchdb/pouchdb#8029]
I wanted to switch to the indexeddb adapter and use that instead of the idb adapter. 

So I have installed the adapter with

    npm install pouchdb-adapter-indexeddb@7.2.1 --save

and have imported it with

        PouchDB.plugin(require('pouchdb-adapter-indexeddb'));

        let options: PouchDB.Configuration.DatabaseConfiguration = {
            adapter: "indexeddb" // vs "idb" which works
        };

        this.db = new PouchDB(this.dbName, options);  // throws "Invalid Adapter: indexeddb"

        PouchDB.plugin(PouchdbFind);

        ...

The instantiation with new PouchDB() throws the error. Any help is appreciated. 

### Info
- Environment: browser
- Platform: Chrome 80
- Adapter: IndexedDB vs IDB

PouchDB 7.2.1

### Reproduce
I am working on it.

**Comment by AlexKolesnik** [comment]
The installation would work with 

     PouchDB.plugin( require('pouchdb-adapter-indexeddb').default);

**Comment by lochehong** [comment]
i'm not using npm. how can i get the adapter?
