### ISSUE TITLE
pouchdb-find: don't include_docs ?

### ISSUE THREAD

**Issue by rasgo-cc** [pouchdb/pouchdb#8038]
Shall I assume that some of the performance issues with pouchdb-find come from the fact that it always `include_docs`? See here: https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-find/src/adapters/local/find/index.js#L87
Looks like there's no option to not include the docs and I can't grasp why including docs is necessary if indexes are created before calling `find()`.

In my specifc case, I would like to retrieve only the _ids of the documents so I can fetch the actual docs later on.

A pagination example:
I'd like to use find() to filter/sort data by some keys. Let's say I have 100k docs but I only show 100 docs per page.  find() would give me all the _ids in the right order and I would do a `bulkGet()` for each slice/page of the _ids.

Any thougths on this?

**Comment by eauchat** [comment]
Maybe I misunderstood something, but I think if you don't want to fetch the whole entry, just the ids, you could use the following find option: `fields: ['_id']`.

**Comment by rasgo-cc** [comment]
Right. Rookie mistake here. Thanks for the input @eauchat.

I don't even remember what kind of test I was doing but it was extremely slow. I came back to this now and I guess I have a better Idea now how pouchdb-find can be leaveraged, and it's pretty impressive.
