### ISSUE TITLE
Tried pouchDB 7.2.1 but can't get adapter to be 'indexeddb'

### ISSUE THREAD

**Issue by lochehong** [pouchdb/pouchdb#8039]
### Issue
I upgraded to pouchDB 7.2.1 but after reset of the application the new database created is still with idb type. and i tried to change adapter to indexeddb it throws an error

### Info
- Environment: (browser)
- Platform: (Chrome)
- Adapter: (IndexedDB)
- Server: (CouchDB)

### Reproduce
this._database = new PouchDB(dbName, {auto_compaction: true});

this._database = new PouchDB(dbName, {auto_compaction: true, adapter: 'indexeddb'});

**Comment by garethbowen** [comment]
Possibly related: https://github.com/pouchdb/pouchdb/issues/8029

**Comment by lochehong** [comment]
My app doesn't use NPM. can i download the adapter JS somewhere?

**Comment by thebigh2014** [comment]
While there is no pre-packaged download, you can build one using the source by making the following modifications (once you download the repo):

1. in **bin/build-pouchdb.js** - add `, 'indexeddb'` to the `plugins` var on line ~31.
2. also in **bin/build-pouchdb.js** - add a value to the `comments` var for indexeddb a few paragraphs down, like `'indexeddb': ''` *(I copied the text from one of the prior comments and altered the name in it.)*
3. [OPTIONAL] copy and paste the `IdbPouch.valid` function from the **idb** adapter (**packages/node_modules/pouchdb-adapter-idb/src/index.js**) to the IndexedDB adapter's **index.js**  *(Not necessary if you don't care about/use the `valid` function.)*
4. create a new file called **indexeddb.js** in the **packages/node_modules/pouchdb/src/plugins/** directory and paste in this code:
```import IndexedDBPouchPlugin from 'pouchdb-adapter-indexeddb';
import { guardedConsole } from 'pouchdb-utils';

if (typeof PouchDB === 'undefined') {
  guardedConsole('error', 'indexeddb adapter plugin error: ' +
    'Cannot find global "PouchDB" object! ' +
    'Did you remember to include pouchdb.js?');
} else {
  PouchDB.plugin(IndexedDBPouchPlugin);
}
```

Then all you have to do to build it is run `npm i` in the repo's root directory.  You will find the built dist files (minified and non-minified) in **packages/node_modules/pouchdb/dist/**.

**Comment by seanlinsley** [comment]
As another person who doesn't use a JS package manager, I'd really appreciate if this could get its own .js file.

**Comment by seanlinsley** [comment]
I was able to hack together a solution using Browserify:
```bash
npm install -g browserify
npm install pouchdb-adapter-indexeddb

browserify node_modules/pouchdb-adapter-indexeddb/lib/index.js \
  -o pouchdb.indexeddb.js -s PouchDB.IndexedDB
rm -rf node_modules
```
```html
<script src="lib/pouchdb.js"></script>
<script src="lib/pouchdb.indexeddb.js"></script>
```
```js
PouchDB.plugin(PouchDB.IndexedDB)
db = new PouchDB('example', {adapter: 'indexeddb', auto_compaction: true})
```

**Comment by subz390** [comment]
## What happened to the release?
- The release says this `We are excited to announce the **release** of a new adapter for indexeddb`
- So I did this `let db = new PouchDB('db', {adapter: 'indexeddb'})`
- and got this `Uncaught Error: Invalid Adapter: indexeddb`

So? where is the release, why is everyone hacking stuff to get at it?  I don't understand please explain.

**Comment by thebigh2014** [comment]
The authors have not yet included it in the main build, likely because it is still in the experimental phase/stage.  It's being made available through package manager(s) for broader testing and to get feedback and the like.  I certainly agree that the wording should be changed as it is certainly not an official release.

**Comment by seanlinsley** [comment]
still an issue as far as I know

**Comment by seanlinsley** [comment]
❓ 
>Remove stale label or comment or this will be closed in 5 days

**Comment by subz390** [comment]
Yeah I know right... bot gives a sht like what ever mate who cares gonna close it anyway.
