### ISSUE TITLE
I can see no way to use the debug feature ( the pouchdb-debug plugin ) on non-node projects

### ISSUE THREAD

**Issue by TheOtherRealm** [pouchdb/pouchdb#8043]
### Issue
I can see no way to use the debug feature ( the pouchdb-debug plugin ) on non-node projects.   There may be a way to do it, but I cannot see a way to use " `PouchDB.debug.enable('*');` without using `require('pouchdb-debug');` .

### Info
- Environment: (browser/hybrid app)
- Platform: (Chrome/FF)
- Adapter: (IndexedDB.)
- Server: (PouchDB Server)

### Reproduce
Create a html page, include some javascript and a referace to the pouchdb code, then try to enable debug: `PouchDB.debug.enable('*');` it will give you a error message saying: `TypeError: PouchDB.debug is undefined` adding the npm module `pouchdb-debug` and including any of the  index*.js files does not change this.
The files:
```
	<script src="node_modules/pouchdb/dist/pouchdb.js"></script>
	<script src="node_modules/pouchdb-debug/lib/index.js"></script>
```
The code:
```
//obviously won't work when not using node.js:
var pouchdbDebug = require('pouchdb-debug');
PouchDB.plugin(pouchdbDebug);

//What is told in the documentation should work:
PouchDB.debug.enable('*');

**Comment by TheOtherRealm** [comment]
Well, in ../pouchdb-debug/src/index.js there is the comment:
```
// TODO: add a window.PouchDB.plugin() call for the benefit of <script> users before we
// release this as a separate plugin in PouchDB 7.0.0.
```
so apparently this is still to do?

**Comment by markusmo** [comment]
I would second this ... I stumbled upon the same issue.

**Comment by bozhidarc** [comment]
I manage to workaround it 
```
import debugPouch from "pouchdb-debug";
import PouchDB from "pouchdb";
debugPouch(PouchDB);
```

**Comment by TheOtherRealm** [comment]
That doesn't address the issue that this is about, accessing the debug function using the <script> tag.  When I get back to working on the project I have that uses pouchdb, I will convert it using node.

**Comment by daleharvey** [comment]
We removed the debug dependency in 7.0 but left the docs in there, they have been cleaned up now @ https://github.com/pouchdb/pouchdb/issues/8102

**Comment by jithin-karanath** [comment]
`import PouchDB from 'pouchdb';
import PouchDBDebug from 'pouchdb-debug';

PouchDB.plugin(PouchDBDebug);
PouchDB.debug.enable('*');`
