### ISSUE TITLE
Scaling a containerized Pouchdb instance

### ISSUE THREAD

**Issue by antosant1981** [pouchdb/pouchdb#8046]
### Issue
I've read about Pouchdb replication concepts and I've understood that replication and synchronization are feasible by leveraging the related APIs. So, it becomes easy, for instance, to configure a multi-master architecture with automatic sync. 
In my case I have a Pouchdb instance running on my web browser (a simple client application Python2, javascript and HTML5 based) and I configured a remote Pouchdb server instance running on a Docker container. The two databases are configured to be synchronized and always up to date.
Now, I created three Pouchdb container replicas by using the docker-compose tool as I need to scale the database server instance in order to improve my application's performances.
I have a couple of questions: 
1. How can I configure the synchronization between the local Pouchdb instance (that one running on my browser) and every replicas of my scaled Pouchdb server instance. Is it possible since I cannot configure a range of tcp ports on the async APIs?
2. Is this approach to be considered as a good practice? Is it to be considered as an alternative to the native Pouchdb replication approach?

### Info
- Environment: local machine environment with Ubuntu 19.10
- Platform: Chrome/Client application Python 2 based/Docker/Docker compose 
- Adapter: IndexedDB/LevelDB/HTTP
- Server: PouchDB Server running on a Docker container

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by willholley** [comment]
I'm curious why you'd want to run PouchDB server this way instead of CouchDB? CouchDB is designed to be clustered / scaled out and there are lots of people running it this way in a containerized fashion.

**Comment by antosant1981** [comment]
Thanks for your question Will.
Actually this in only a local development just to try to understand some concepts about document databases and scaling.
Do you think it's possible to have a containerized environment with an orchestrator managing all the issues by using CouchDB?
Why not using Pouch?

**Comment by willholley** [comment]
You can certainly run CouchDB in a containerized environment such as Docker Compose or Kubernetes. 

I'd strongly recommend CouchDB as the server side database in production; it's battle tested in that scenario (significantly more so than PouchDB server) and you'll likely find the community more supportive when it comes to scaling issues. PouchDB server is fine for dev/test but I wouldn't use it in scenarios where I cared about data loss.

**Comment by antosant1981** [comment]
Another question.
From my understanding about microservices architectures and containerization, in a context where I have a microservice that reads/writes on a document database, it makes sense to deploy the microservice into a container and the database into another one.
Is it a good practice to scale the container where the database instance is deployed in? Since the database is a layer for pure I/O operations I think it's better not to scale it at all and to focus scaling the microservice instead.
Thank you.

**Comment by willholley** [comment]
In general I'd advise deploying the database outside of your container orchestration system. As you say, databases generally work best on relatively static infrastructure and are I/O intensive so should be placed as close as possible to the backend storage.

If you do choose to deploy the database to containers, it's a good idea to separate the database from the application so that you can scale them independently. CouchDB can scale horizontally but clustering require a bit of up-front sizing - it's not straightforward to re-balance data across nodes so resizing clusters is not something you want to be doing regularly.

**Comment by antosant1981** [comment]
Thank you very much.
If I choose to deploy the database to container, who is responsible to manage the load-balancing and other issues, the orchestrator or CouchDB framework itself?

**Comment by willholley** [comment]
it's probably a better to ask this question in CouchDB support channels but the usual approach is to have either the orchestrator load balance over CouchDB pods (which themselves are configured as a cluster) or explicitly deploy a load balancer such as HAProxy in front of the CouchDB cluster and have that perform the load balancing.

**Comment by antosant1981** [comment]
Thank you very much for your explanations Will. I really appreciate your professionalism. 
I close this issue if you agree.

**Comment by antosant1981** [comment]
Thank you very much @willholley for the valuable explanation.
