### ISSUE TITLE
I want to contribute. New here can anyone help?

### ISSUE THREAD

**Issue by alihamuh** [pouchdb/pouchdb#8047]
### Issue
Write the description of the issue here

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by garethbowen** [comment]
@alihamuh Welcome! Depending on your interests and experience you can contribute PRs or just help by creating and/or responding to GitHub issues. There's some information about contributing in [this doc](https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md).

**Comment by daleharvey** [comment]
Hey, things have been quiet but trying to keep on top of them these days, feel free to ask in any issues that you want to pick up, also going to be marking good-first-patch 's to bugs when I see them @ https://github.com/pouchdb/pouchdb/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+patch%22
