### ISSUE TITLE
wrong database getting synced in couchdb

### ISSUE THREAD

**Issue by soubhikchatterjee** [pouchdb/pouchdb#8048]
I am using chrome and pouchdb to sync data to a remote couchdb data. I have a remote dev couchdb database that i use for testing purpose and a remote production CouchDB.

when I run chrome, my application syncs the data from the remote db and store in local electron's pouchdb and vice versa.

Things are fine but when I change the remote database URL from dev to prod, the locally stored dev data gets synced to prod db.

Is there any way (programmatically) I can stop this from happening?

PS: I know this is not a pouchdb issue, but i couldn't find a better place to ask this and maybe someone here has already fixed this.

**Comment by SCdF** [comment]
You're looking for the two to be completely different right? Or do you expect the local db to stay the same and have the remote db change?

If you're looking for the former just use two local dbs: name them based on what you're connecting to.

If you're looking for the latter I don't _really_ understand what you're trying to achieve. How would you expect this to work?

**Comment by soubhikchatterjee** [comment]
I was looking for the former. Thanks so much for sharing the idea. I think that will solve my problem.
