### ISSUE TITLE
'emit' is not defined

### ISSUE THREAD

**Issue by mcgtech** [pouchdb/pouchdb#8049]
### Issue
I am trying to run the map/reduce example found here: https://pouchdb.com/api.html#query_database (part of the example code is shown below).

But in my chrome browser console if am getting the following error: 'emit' is not defined  no-undef

Is there something that I need to setup to let me use the eval fn when creating an index?

```js
// create a design doc
var ddoc = {
  _id: '_design/index',
  views: {
    index: {
      map: function mapFun(doc) {
        if (doc.title) {
          emit(doc.title);
        }
      }.toString()
    }
  }
}

// save the design doc
db.put(ddoc).catch(function (err) {
  if (err.name !== 'conflict') {
    throw err;
  }
  // ignore if doc already exists
})
```

### Info
- Environment: Node.js in Mac OS terminal
- Platform: Chrome
- Adapter: IndexedDB
- Server: PouchDB Server

**Comment by garethbowen** [comment]
I suspect the problem is to do with the `toString()` on the map function. Try simply manually creating the string so Node doesn't have to evaluate the function, eg:

```js
var ddoc = {
  _id: '_design/index',
  views: {
    index: {
      map: "function (doc) { if (doc.title) { emit(doc.title); } }"
    }
  }
}
```

**Comment by mcgtech** [comment]
Perfect that seems to sort it!
