### ISSUE TITLE
Bi-directionnal replication broken after CouchDB remote connection lost

### ISSUE THREAD

**Issue by baptistedonaux** [pouchdb/pouchdb#8050]
### Issue
I have a problem with bidirectional replication after remote CouchDB connection has been lost.

Initially, I start a bi-directional replication with method `sync`. The replication works correctly. At this moment, I can create/update/delete document from local (PouchDB) or remote (CouchDB) and see event thrown by `change` event. Event indicate me the direction associated (`pull` or `push`). 

When I stop CouchDB server and start again, the bi-directional replication isn't fully restored. At this moment, I can only see `change` event with `push` direction. If I update a document on CouchDB, I receive no event...

### Info
- PouchDB 7.2.1
- Environment: Node.js
- Platform: Node.js v13
- Adapter: LevelDB
- Server: CouchDB (v3.0.0)

### Reproduce
```js
const pouchdb = new PouchDB(<local db>)

pouchdb.sync(<remote database>, {live: true, retry: true).on('change', console.log)
```

Steps:
1. Start CouchDB
2. Open PouchDB database and start replication
3. Stop CouchDB
4. Start CouchDB
5. Generate a CouchDB event through document create, update or delete 

At step 5, no event will be displayed by script for changes generated by CouchDB.

**Comment by rjharmon** [comment]
Have you tried to observe some of the other events (paused / active / error) on the replication?  Do the emitted events clarify what's happening?  

How much time is passing at step 3/4?  How long are you waiting after step 5 before giving up?  Have you tried implementing a simple back_off_function that causes retries on a timeline you can easily predict/control?

If there's a defect here, any resulting details may be helpful for someone identifying the cause.

**Comment by baptistedonaux** [comment]
Yes, I have tried many ways to understand comportment.

* I have tried to observe all events available.
    * `error` is never thrown - probably because the replication is running with `retry` option
    * `denied` is never thrown
    * `active` and `paused` are observed. They are observed while CouchDB is running. When CouchDB is stopped, `active` event is observed. `paused` event comes after few seconds (~5 seconds, probably a timeout). These events are observed **only once** after stopped CouchDB. 

* About time between step 3 and 4, I have tried a "long" time (10 secondes - he seems me that it's sufficient to determine a network connection lost) and a short time with only a CouchDB restart (I'm using Docker so just the time to restart my container)

* I waited 1 minute more after have produced step 5 without success. I have implement `back_off_function` too which returns the value `1000` systematically.

I send you more data with logs and script about this process to reproduce easily this issue tomorrow.

**Comment by baptistedonaux** [comment]
I have written a script and package it into Docker environment.

### Steps to configure
* Extract archive
* `docker-compose up --no-start couch`
* `docker-compose ps -q`
* Copy ID displayed (couch container) and paste into `src/index.js` at line 8 into variable `couchContainer`

To reproduce error, you can start environment with `docker-compose up`.

[pouch-8050.zip](https://github.com/pouchdb/pouchdb/files/4508795/pouch-8050.zip)

**Comment by baptistedonaux** [comment]
I'm confused... I have try again and replication works perfectly.

Sorry for wrong report...
