### ISSUE TITLE
PouchDB stop replicating if there is an attachment in the DB

### ISSUE THREAD

**Issue by Kaendor** [pouchdb/pouchdb#8051]
### Issue
Hello,

My collegues and I found this little bug while developping our App. Whenever we add an attachment to one of our document, replication stops across all clients and restart only if we remove said attachment.

There is however some debug info in the console : 
`{
  result: {
    ok: false,
    start_time: '2020-03-11T20:01:04.542Z',
    docs_read: 0,
    docs_written: 0,
    doc_write_failures: 0,
    errors: [],
    status: 'aborting',
    end_time: '2020-03-11T20:01:06.053Z',
    last_seq: 0
  }`

I can see in the network tab that the remote DB is fetched but i believe it is not transmitted to the local one.

Thanks to the wonder of the internet i've found a little workaround on [SO](https://stackoverflow.com/questions/54595908/pouchdb-not-syncing-when-there-are-attachments), but it seems like a hack and a temporary solution.
In index-browser.es.js from PouchDB around line 7100 i replaced : 

`
if (typeof process !== 'undefined' && !process.browser) {
  return response.buffer();
}
`

By

`if (typeof process !== 'undefined' && !process.browser) {
  return response.blob();
}`

And commented around line 7110 : 

`if (typeof process !== 'undefined' && !process.browser) {
    //blob.type = contentType;
}`

### Info
- Environment: Electron
- Platform: Linux and iOS
- Adapter: IndexedDB
- Server:PouchDB Server

### Reproduce

Have an empty DB then put a document with an attachment. 
It then stops to replicate on Electron development environement.

**Comment by bozhidarc** [comment]
Same problem here. 

```
pouchdb:api http://... +19ms getAttachment error TypeError: Cannot assign to read only property 'type' of object '[object Blob]'
    at index-browser.es.js:7170
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.js:26256)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at zone.js:910
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:26247)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
```

**Comment by pejman1** [comment]
Same issue. when I add attachment to a document . replication form couchdb to pouchdb won't work anymore ! 
environment : Electron . reactjs  and typescript

**Comment by dianabarsan** [comment]
I ran into this problem as well. 

The quickest fix I found was adding this polyfill:
```
(window as any).process = {
  browser: true,
}
```

**Comment by knubie** [comment]
May be related to #8154
