### ISSUE TITLE
"indexed_db_went_bad", "AbortError" keeps occurring on some database

### ISSUE THREAD

**Issue by eauchat** [pouchdb/pouchdb#8054]
### Issue
I've found some similar issues here and more globally on the internet, but they always seem somewhat different, or related to a specific version of chrome... so I thought maybe there is something else going on.

When I'm trying to save (PUT) an entry in a database, I regularly get the following error:
```
id: "some-long-uuid"
error: true
message: "unknown"
name: "indexed_db_went_bad"
reason: "AbortError"
stack: ""
status: 500
```
and `Database has a global failure DOMException: "A request was aborted, for example through a call to IDBTransaction.abort."`

When this happens, I can't put any entry in the database anymore and keep getting errors when I try to.
The error sometimes turns into: `DOMException: "IDBDatabase.transaction: Can't start a transaction on a closed database"`.

This doesn't seem to affect getting of entries.

Eventually, if I come back to the database later, I can make use of it again, and put entries. But I couldn't figure out a pattern about what amount of time solves the issue, sometimes a few minutes, sometimes the day after the problem is still there (or bursts again).

Sometimes when this problem occurred, I also had issues replicating the database to couch, the replication would keep trying but never finish, and I would get CORS errors (which makes no sense to me since CORS is properly configured, and I'm running couch on localhost so no network issues should arise).

### Info
- Environment: browser
- Platform: reproduced both in Chromium and Firefox
- Adapter: default (which if I understood well is IndexedDB)
- Server: CouchDB

### Reproduce
I'm struggling myself understanding how to reproduce the issue, since it can happen after many modifications to the database, or just when doing a single one. So far it occurred to me only on a databases containing specific set of entries. I even exported all those entries as JSON, removed their _rev and reimported them in another database, and the problem keeps coming up in the new database.
This set of entries contain about 1000 entries, with a few hundreds of them having one or multiple attachments.
Maybe this means it's related to one or a few entries having contents that cause this issues, but I don't understand how that could be.
Any help/suggestions would be very appreciated.

**Comment by tudordumitriu** [comment]
Hi @eauchat 
The attachments might be responsible and also as far as I've seen they seem to be having issues with replication (if used). We are NOT using attachments because of the space and replication issues.

Still, we have encountered the same error and usually it happened:
1. On mobile (cordova hybrid app) and we have switched from idb to cordova-sqlite adapter
2. In browser (Chrome) in Incognito - here we don't have a solution and in Chrome at least in Incognito it seems that the storage is limited to 100M (ish) and when it was reaching that we started getting the error.
Dunno if it helps but maybe it will narrow down a bit the path for you

**Comment by eauchat** [comment]
Thanks @tudordumitriu for the advises.
So in the end, I realized something in the app was attaching a function to the entry to put, I corrected this bug and the problem doesn't occur anymore.
So I think it's just my mistake and not a pouch bug at all.
I'm still getting errors in replication (probably because of attachment), but that's different issue, and I've posted another ticket for that.

**Comment by Alan1034** [comment]
May cause by the lack of encrypted
