### ISSUE TITLE
Update blog post link

### ISSUE THREAD

**Issue by bean5** [pouchdb/pouchdb#8063]
https://pouchdb.com/2015/09/01/pouchdb-4.0.1-gotta-go-fast.html links to https://medium.com/@kentcdodds/first-timers-only-78281ea47455.

That page is a 404.

**Comment by daleharvey** [comment]
This is now @ https://kentcdodds.com/blog/first-timers-only

**Comment by daleharvey** [comment]
Fixed by https://github.com/pouchdb/pouchdb/pull/8093
