### ISSUE TITLE
CORS error on some databases when CORS are properly setup in couch

### ISSUE THREAD

**Issue by eauchat** [pouchdb/pouchdb#8064]
### Issue
Frequently, I get the following error logged in the browser console:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://couchdomain.tld/somedatabase/_bulk_docs. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

I've setup CORS properly in couchdb, and I'm able to synchronize many databases on that couch server.
Usually, I would get those logs when offline (I don't know if that's inherent to firefox, but it's quite misleading).
Recently I started getting this error on a database with as low as 10-20 entries and some attachments (not many, like 5-10), and it prevents the database from synchronizing successfully.

### Info
- Environment: browser
- Platform: Firefox
- Adapter: default (which if I understood well is IndexedDB)
- Server: CouchDB

### Reproduce
Setup a pouchdb, make it synchronize with a remote couchdb, setup properly CORS in couchdb, add entries and attachments to them in pouchdb. Or just go offline.

**Comment by eauchat** [comment]
Enabling debug mode, I notice that before each request that throws a CORS error, I have one previous request that seem to have succeeded.
It looks like this:
```
pouchdb:api https://user:password@couchdomain.tld/somedatabase/ +3ms bulkDocs
Object { docs: (16) […], new_edits: false } Object {  }
pouchdb:api https://user:password@couchdomain.tld/somedatabase/ +2s bulkDocs error TypeError: "NetworkError when attempting to fetch resource."
```

The only idea I can come with now, is that a request times out, because of the "voluminous" (~3MB) attachments.

Anyone has an idea/suggestion on how to solve this?

**Comment by eauchat** [comment]
After a deeper investigation, it seems that the problem came from nginx refusing the request because it was too big.
I managed to solve the issue increasing "client_max_body_size" in the nginx config for the couch domain.

I keep the issue opened however, because it's subject is that the message logged both by firefox and pouch debug are misleading and don't really inform about the situation. I don't know if that's improvable, hopefully it is :)

**Comment by tjrobinson** [comment]
Related: https://stackoverflow.com/questions/56227666/sudden-change-to-have-cors-bulkdocs-couchdb-error
