### ISSUE TITLE
Update pouchdb-getting-started-todo assets to use pouchdb/ repo

### ISSUE THREAD

**Issue by bean5** [pouchdb/pouchdb#8070]
If you download the zipped project on the tutorial page, then unzip, you'll end up with a project with a git remote of `git@github.com:daleharvey/pouchdb-getting-started-todo.git`

But at the head of the tutorial, it says to use `https://github.com/nickcolley/getting-started-todo`.

When I wanted to propose a change (because I'm old in git, but new to PouchDB), I automatically went to the first! But the second seems more active. In fact, the first had 0 issues and 0 pull requests until I proposed changes.

**Comment by bean5** [comment]
To avoid this same problem in the future, should we invite those @daleharvey to fork the other and then have pouchdb org fork it as well and then reference the Github page.

And maintaining a fork of your own would allow you to host the tutorial without issues of external shift.

Granted, you probably want to all coordinate and make sure legally this is all possible. Plus, I'm probably overthinking it. You probably notice I'm already in post-mortem mode trying to avoid the problem the next time around.

Furthermore, Github itself allows for downloading zip files, so you wouldn't have to host the zip file anymore. (Although the Github zip doesn't come with the `.git`--but users who prefer zip probably don't know Git, so it is kind of a good thing.)

Maintaining a fork is probably easier than wondering whether/when you should update a zip file.

**Comment by daleharvey** [comment]
Cheers, didnt really think about the .git being in the zip file, I have forked the repo @ https://github.com/pouchdb/pouchdb-getting-started-todo if you want to make any changes. And updated the download to use the .zip from there directly
