### ISSUE TITLE
AllDocs slow performances

### ISSUE THREAD

**Issue by oltreseba** [pouchdb/pouchdb#8075]
### Issue
I'm testing pouchDB for an electron app. I'm planning to insert quite a lot documents into it and i'm hitting performances issues. I'm wondering if i'm doing something wrong or i'm actually reaching the limitations of pouchdb, and therefor I should just look for something else and not trying to optimize it.

My purpose is to extract all documents and then filter them using js (i've tried doing this using couchbase-find, but is has been even worse).

The number of documents i'm trying to read are 100k (just for the purpose of this test, but i think user may have up to 500k documents).

These are some results, compared with inserting and extracting the same data from a normal sqlite db.

Edit: extraction is done with "include_docs at true"

**Inserting 100k items**
- sqlite ~4000ms
- pouchdb in memory ~3000ms
- pouchdb leveldb ~3000ms

**extracting 100k items**
- sqlite ~200ms
- pouchdb in memory ~ 22000ms (more than 100x)
- pouchdb leveldb ~ 24000ms (almost 100x)

If i then try to search for all the documents that have the letter "a" in the title, sqlite performances are event better, (around 60ms) while of course pouchdb are more or less the same, around 22-24s to extract all documents and about 40ms to apply a js filter function. Performance with pouchdb find were even worse.

### Info
- Environment: (Node.js)
- Platform: (electron)
- Adapter: (LevelDB and memory)
- Server: (None.)

I can accept worse performances in some occasions, but 100x more is not doable for me. Even if i build my own in memory index for search on top of pouchdb i still need to extract all the docs to actually build this index, and this is taking a lot of time. (i cannot have my application stuck for 24s at startup while i extract data and then build index)

So I'm wondering: i'm asking too much from pouch and using if for the wrong use case or i'm doing something wrong? (if this is the wrong use case, are there any similar alternatives given that i can install any node package?)

Thank you.

**Comment by lukevp** [comment]
@oltreseba Do you have a sample that reproduces this?  If you track this in chrome performance profiler (you can install the chrome devtools in your electron app if you don't already have them) you can look at a flamegraph of where the time is being spent.  It's usually best not to speculate on something like this and to just pinpoint the slow part directly, especially when the performance is so much worse.

**Comment by oltreseba** [comment]
That's a great idea, but unfortunately we already move to something else (sqlite). I'll try to check if i can rollback to a previous commit just to try it.

Anyhow the meaning of my first post was really to understand if these are the expected performances, not to accuse pouchdb of being slow.
