### ISSUE TITLE
BulkDocs 100000 small objects need 500MB memory

### ISSUE THREAD

**Issue by blueye** [pouchdb/pouchdb#8078]
When I put 100000 small objects in a for loop, the memory increases to 500MB.
Here are my code:

```javascript
var db = new PouchDB('kittens');
var docs = new Array()
for (i = 0; i < 1000000; i++) {
  var doc = {
    "_id": "keyx" + i,
    "name": "name",
  }
  docs[i] = doc;
}
db.bulkDocs(docs).then(function(res) {
}).catch(function(err) {
  console.log(err);
});
```
In my opinion, 100000 objects need about 30M memory total. If putting 1000000 objects, heap error may occur! Could you explain why the memory is so large?

**Comment by lukevp** [comment]
@blueye your example code is putting 1 million objects, but all your references in your comment say 100k objects.  Which one are you testing that's using 500 MB of memory, 1M or 100k?

**Comment by blueye** [comment]
@lukevp Sorry for inconsistant object numbers. When I put 100k objects, memory usage is about 500MB. When I put 1 million objects, the memory increased to 2GB.

**Comment by deissh** [comment]
https://gist.github.com/deissh/5bfb70a80858260ba864b830054b546a
This code requires about 3GB of memory
