### ISSUE TITLE
Cannot read property 'once' of undefined at Replication.ready

### ISSUE THREAD

**Issue by temharay** [pouchdb/pouchdb#8079]
### Issue
I can't pinpoint the exact cause but I believe it happens when replication is started again when the previous/existing one is cancelled. Is that a possiblity to start with? Regardless, I have a syncing indicator icon that goes on forever if the above error happens.

Is there a way to catch the above error so I turn off the spinning?

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by sammysium** [comment]
@nolanlawson @temharay any solution to this? On how to handle it gracefully at least? It is rendering out app useless basically
