### ISSUE TITLE
React & PouchDb, caching issue, it still increases even when deleting and compacting

### ISSUE THREAD

**Issue by matthieusibille** [pouchdb/pouchdb#8081]
I'm using PouchDB in React and I have an issue: my browser cache size still increases even when i'm clearing all site data (on Chrome) and even with compacting pouchDb database.

here is my function that i use to compact: 

`export const compactDb = async (db) => {
  try {
    var result = await db.compact();
    console.log("CONSOLE UTILZ compact", result);
  } catch (err) {
    console.log(err);
  }
}`

the log returns `{ok: true}`

here is the full useEffect where i use this function: 

`useEffect(() => {

    let graphQlIsLoaded = new Promise(
      function(resolve, reject) {       
            if(!modules.loading && !questions.loading){
              resolve({
                modules: modules.data && modules.data.modules,
                questions: questions.data && questions.data.questions
              });
            }
      });
      db.get('modules').catch(function (err) {
        if (err.name === 'not_found') {
            graphQlIsLoaded.then((data)=> {
              setData("modules", data.modules)
              .then(() => {
                let a = utils.getAllQuestionsMedia(data.questions);
                setData("questions", a)
              })
            })
        } else {
          throw err;
        }
      }).then( () => {
        if(!modules.loading && !questions.loading && !isLoaded){
          setIsLoaded(true)
          UtilzPouchDB.compactDb(db)
        }
      }).catch(function (err) {
      });
  },[modules.loading, questions.loading])`

and here is the setData function that i use to PUT data in pouchDB:

`const setData = async (id, data) => {
    try {
      let res = await db.put({
        _id: id,
        data: data
      });
      return res
    } catch (err) {
      console.log(err);
    }
  }`

I must do something wrong or there is something that i don't understand. How can i delete all pouchDB data cache?

### Info
- Environment: React 16.12.0, Node v12.16.1, PouchDB 7.2.1, React-PouchDB 2.0.0
- Platform: Chrome  81.0.4044.138
- Adapter: IndexedDB

**Comment by lukevp** [comment]
have you tried using auto compaction instead?

**Comment by matthieusibille** [comment]
It seems that after testing the database doesn't increase anymore.

I think that when i made the change and added the compacting, PouchDB had to be completly reset (in my local environment at least) in order to reflect the change. By that i mean start from scratch with no residual data.
