### ISSUE TITLE
Problem with replication under Electron 9.0.0

### ISSUE THREAD

**Issue by wgrhstf** [pouchdb/pouchdb#8082]
### Issue
When updating my App to Electron 9.0.0 PouchDB stopped syncing with my remote CouchDB. I use `pochdb-browser` and everything worked flawless until updating to Version 9.0.0 of Electron. Now  it syncs only on the first page load, but any changes made afterwards are not transferred. Reverting back to Electron 8.3.0 made the Problem disappear.

### Info
- Environment: Electron 9.0.0
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
I use a slightly adapted Version of Nolan Lawsons brilliant [Efficiently managing UI state with PouchDB ](https://pouchdb.com/2015/02/28/efficiently-managing-ui-state-in-pouchdb.html) script for the updates. So:

```
const PouchDB = require('pouchdb-browser');
const db = new PouchDB('myDB', {adapter: 'idb'});
const remoteDB = new PouchDB('http://login:pass@localhost:5984/myActualDB');
db.sync(remoteDB, {
    live: true,
    retry: true
}).on('change', function (change) {
    // yo, something changed!
    console.log('Change: ' + change);
}).on('paused', function (info) {
    // replication was paused, usually because of a lost connection
    console.log('Pause: ' + info)
}).on('active', function (info) {
    // replication was resumed
    console.log('active: ' + info)
}).on('complete', function (info) {
    // handle complete
    console.log('Complete: ' + info);
}).on('error', function (err) {
    // totally unhandled error (shouldn't happen)
});

fetchInitialDocs().then(renderDocsSomehow).then(reactToChanges).catch(console.log.bind(console));

function fetchInitialDocs() {
    return db.allDocs({
        include_docs: true,
    }).then(function (result) {
        docs = result.rows.map(function (row) {
            return row.doc;
        });
    }).catch(function (err) {
        console.log(err);
    })

}
```

**Comment by lukevp** [comment]
@wgrhstf did you also update pouchdb at the same time?  I also built off of this sample code, and I noticed in the latest version w/ TypeScript, on('active') is not valid. Perhaps that's causing you an issue and when you reverted to the electron 8.x version you also reverted pouchdb?

**Comment by wgrhstf** [comment]
No, my PouchDB-Browser Version was 7.2.1 before and after the update. I just updated again to electron 9.0.0 to make sure,  and the PouchDB version did not change. But I'm not using TypeScript in my project. Just plain old Javascript.
