### ISSUE TITLE
Attachment data is replicated even when attachment is marked as 'stub'

### ISSUE THREAD

**Issue by kripper** [pouchdb/pouchdb#8088]
### Issue

Attachment data is replicated even when attachment is marked as 'stub'.

### Info

PouchDB 7.0.0 (with default options)

### Reproduce

- Pull a document with an attachment from remote CouchDB to local PouchDB
- Mark attachment with 'stub' = true
- OPTIONAL: Remove 'data' from attachment (shouldn't be necessary since we marked as 'stub')
- Put the document into local PouchDB with _id and _rev to update.
- Replicate local PouchDB to remote CouchDB

- Check network tab in Chrome Developer tools

### Results

You will see that the "_bulk_docs" POST is sending the attachments with all the "data" (see "Request Payload").

### Expected Results

Attachment data shouldn't be sent from PouchDB to CouchDB since we marked the attachment as 'stub'

Is this possible?

**Comment by daleharvey** [comment]
Nope, we have had attempts to support optional attachments over the time, not a very simple feature to implement but its not currently supported
