### ISSUE TITLE
pouchdb-adapter-indexeddb not working in IE11

### ISSUE THREAD

**Issue by n9** [pouchdb/pouchdb#8091]
### Issue
`pouchdb-adapter-indexeddb` not working in IE11

### Info
- Environment: browser
- Platform: IE11
- Adapter: IndexedDB (new)
- Server: N/A

### Reproduce
IE11 fails to load script with:
> SCRIPT1004: Expected ';'

It's seems to be caused by `for of` in `needsRewrite()` of `rewrite.js`.

**Comment by SCdF** [comment]
Yep, there is no IE11 support for the new adapter. Unfortunately this isn't a case of using `for of`, this is core to how the new adapter works and bugs in IE11's indexeddb implementation.

Unfortunately users who require IE11 have to use the old adapter.

**Comment by daleharvey** [comment]
Yup, happy if someone else wanted to fix this but if I remember it was extremely complicated, for now no plans for supporting
