### ISSUE TITLE
RemoteDatabaseConfiguration auth and fetch not working in PouchDB-browser 

### ISSUE THREAD

**Issue by gbshpeteja** [pouchdb/pouchdb#8092]
### Issue
In my Angular 9 application I have a local PouchDB and a remote one configured and they sync. 
1. Currently the remote PouchDB is a CouchDB that needs basic authentication with user and password.
2. Later the CouchDB will be secured with jwt access token.

For 1. the [PouchDB API documentation](https://pouchdb.com/api.html#create_database) says to do the following:
`auth.username + auth.password: You can specify HTTP auth parameters either by using a database with a name in the form http://user:pass@host/name or via the auth.username + auth.password options.`
Implementing the basic authentication with http://user:pass@host/name works fine (the requests have the authorization header). But using the auth property in RemoteDatabaseConfiguration ends up with 401 Unauthorized (the requests do **not** have the authorization header). Using NodeJS the auth property works like in the documentation described but not on browser environment.

For 2. the [PouchDB API documentation](https://pouchdb.com/api.html#create_database) shows the following example to be able to customize headers in requests: 
`var db = new PouchDB('http://example.com/dbname', {
  fetch: function (url, opts) {
    opts.headers.set('X-Some-Special-Header', 'foo');
    return PouchDB.fetch(url, opts);
  }
});` 
So I should be able to set Bearer token with 
`opts.headers.set('Authorization', 'Bearer xyz');`
But like this it does not add authorization header to request. I am not able to add any request header with this customization of the fetch method. It looks like the custom fetch method doesn't get executed.
I have some problems reproducing it. Yesterday console.log(url, opts) worked but today I cannot get console.logs to work in custom fetch request. But adding a custom header never worked on browser.
On NodeJS environment the custom fetch works. There you can add custom headers to the requests. _Actually as a demonstration you can use basic authentication without user:pass in url and auth property. You can use custom fetch and add the hashed basic token to the headers and everything works too **but** only on NodeJS.._

Can you guys help me out here?

### Info
- Environment: browser (pouchdb-browser v.7.2.1)
- Platform: Chrome/FF/Edge
- Adapter: IndexedDB and http
- Server: CouchDB

### Reproduce
- Use PouchDB in browser env
- Create a CouchDB server with basic authentication
- Try to create remote PouchDB with auth property (auth.username and auth.password in constructor) -> You will face described issue 1.
- Try to add custom header in customized fetch requests for remote PouchDB -> You will see that requests does not have custom header. Issue 2.

**Comment by daleharvey** [comment]
So tried to reproduce and seeing something like this, with 

https://glitch.com/edit/#!/right-amethyst-packet

The first request is made without the auth header, but all subsequent requests have the auth header, given the code path used to generate the header that seems very strange

**Comment by daleharvey** [comment]
Actually my test above is working fine, the request that doesnt have the Auth header is from the DELETE request that doesnt have auth specified, the requests spawned from 

``` let remote = new PouchDB(REMOTE_DB_URL, {
    auth: {
      username: "user", 
      password: "password"
    }
  });```

All had the auth header, @gbshpeteja can you double check on that, it seems to be working fine here

Both your bugs seems to say it works as expected in node and not the browser, the codepaths for these 2 features are very similiar in node and the browser and its seeming like there is something wrong with your testing

**Comment by gbshpeteja** [comment]
Okay so in the morning I started working on this issue again. Sorry for waiting.

I double checked it and it the auth property in remote db config object does not allow me to connect to remote db but the user:pass in remote db address does. And a custom fetch method is not getting used after defining a custom one in remote db config object.

This is my code:
`this.couchDB = new PouchDB('http://127.0.0.1:5984/recorder', {
  auth: {
    username: 'admin',
    password: 'milabo'
  },
  fetch: function(url, opts) {
      console.log('hello world');
      alert('hello world');
      return PouchDB.fetch(url, opts);
    }
});`
and in browser console I do not get the console.logs from custom fetch and I defined alerts() does not pop up but I get following error:
`GET http://127.0.0.1:5984/recorder/ 401 (Unauthorized)`
and in network tab you can see that there is no authentication header:
![image](https://user-images.githubusercontent.com/46595285/86013738-c29c5800-ba1f-11ea-8d30-3fd7e13af633.png)

And I tried it again in NodeJS and everything works just fine. Console.logs() coming to stdout and auth property allows me to authenticate to remote db.

In my browser env authenticating to remote db only works with adding user:pass to remote CouchDB address.

**BREAKING NEWS**

**I found the issue in my code**. After initializing local PouchDB and creating PouchDB Object with remote couchdb address and remote db config that should sync I accedentially did not use these two objects in the PouchDB.sync(). I was using `PouchDB.sync(this.pouchDbName, remoteCouchDBAddress, {
    live: true,
    retry: true,
  })` instead of 
`PouchDB.sync(this.pouch, this.couchdb, {
    live: true,
    retry: true,
  })`
This little issue was too obvious for me, so we can close this issue. Your browser module works as expected and I love it. 😄
