### ISSUE TITLE
[meta] Fix all the build things

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#8097]
Hey all, long time :) so got an unspecified period of time I have some time to commit to pouchdb, now mostly I havent been contributing because I dont have time but I also find the current setup / build extremely confusing and intimidating. Now I would like to rectify this, PouchDB (Nolan) was somewhat of an innovator in publishing ES6 modules in monorepos and am hoping that the situation is a little more settled these days. 

So things I would like to do

 * Remove `-browser.js` switches, I would like to write code that works in the browser then have node polyfill as needed
 * Reduce https://github.com/pouchdb/pouchdb/tree/master/packages/node_modules, this is too many packages, the nesting is confusing, every file is called `index.js`, we need to release `pouchdb` and `pouchdb-browser`
 * Write + publish in ES6 - People that dont support es6 can have something transpile themselves these days right?
 * Reduce the tools and buildscripts used to develop and release down to a minimum, right now we have browserify + webpack + a lot of custom scripting

Not sure how possible it is to do these changes incrementally, I am probably doing to experiment doing it from scratch then see what a migration looks like, suggestions welcome for monorepo type javascript libraries and build tools to look at etc

**Comment by daleharvey** [comment]
Related, if building our code fails as in https://github.com/pouchdb/pouchdb/pull/8060, it should fail and not build empty files. Lucky to have the build-verify catch it

**Comment by nono** [comment]
Maybe you can look at [@pika/pack](https://github.com/pikapkg/pack)

**Comment by shadow81627** [comment]
[Typescript](https://www.typescriptlang.org/) offers support for the latest and evolving JavaScript features, including those from ECMAScript 2015 and future proposals, like async functions and decorators, these features compile to clean, simple JavaScript code which runs on any browser, in Node.js, or in any JavaScript engine that supports ECMAScript 3 (or newer). Types are optional, and type inference allows a few type annotations to make a big difference to the static verification of your code.

[Lerna](https://lerna.js.org/) is a pretty common tool for managing mono repo JavaScript projects with multiple packages.

[Semantic Release](https://github.com/semantic-release/semantic-release) automates the whole package release workflow including: determining the next version number, generating the release notes and publishing the package.

**Comment by shadow81627** [comment]
My favorite way to use pouchdb is with [rxdb](https://github.com/pubkey/rxdb) and they are looking at [tools for managing monorepos](https://github.com/pubkey/rxdb/issues/2510). Looks like [Nwrl Nx](https://nx.dev/node) is a good tool to replace lerna for managing monorepos.

It would be nice to replace lerna rather than having a custom monorepo setup.

The monorepo and build setup seem to be a long running major problem for first time contributors getting involved.
Simplify build process #7651
