### ISSUE TITLE
Guide about revision numbers being nondeterministic is incorrect

### ISSUE THREAD

**Issue by safareli** [pouchdb/pouchdb#8121]
As https://github.com/pouchdb/pouchdb/pull/7136 is merged this should be incorrect:
<img width="713" alt="Screen Shot 2020-06-24 at 11 38 31 PM" src="https://user-images.githubusercontent.com/1932383/85619782-d50b4000-b673-11ea-97b4-7bfb40dd5f73.png">
https://pouchdb.com/guides/conflicts.html#accountants-dont-use-erasers

**Comment by daleharvey** [comment]
So yup the file to update is https://github.com/pouchdb/pouchdb/blob/master/docs/_guides/conflicts.md#eventual-conflicts. Need to remove the `{%alert` part
