### ISSUE TITLE
`index-browser.es.js` breaks ES bundling

### ISSUE THREAD

**Issue by bradobro** [pouchdb/pouchdb#8124]
### Issue
When trying to bundle for the browser with an es6-module-aware bundler, the packaged `pouchdb/lib/index-browser.es.js` causes the bundler to fail because it imports `events`, a node module, without (AFAICT) providing a shim for `events`:

```sh
../../node_modules/pouchdb/lib/index-browser.es.js:7:29: error: Could not resolve "events"
import { EventEmitter } from 'events';
                             ~~~~~~~~
1 error
```

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: none (client-side only)

### Reproduce

Create an es6 file: `bundle-me.js`:

```es6
import PouchDB from "pouchdb";

function main(){
    const db = new PouchDB("example");
}

main();
```

Attempt to bundle it:

```
npm i -g esbuild
esbuild --bundle bundle-me.js
```

**Comment by bradobro** [comment]
Maybe most people bundle in a library to provide `events` in the browser. If so, I'd love to know which one works best with PouchDB and, if possible, listed in `package.devDependencies`;

**Comment by daleharvey** [comment]
Have you tried this with a local build that has https://github.com/pouchdb/pouchdb/issues/8089 ?

**Comment by bradobro** [comment]
No, I'll try that. Thanks.

**Comment by daleharvey** [comment]
Hoping the above has fixed the issue

**Comment by coldino** [comment]
This issue is still relevant, even with #8082.

Note that some of the big bundlers like webpack automatically include `events` when referenced, which is why this issue isn't terminal in all cases. The npm package `events` is widely used and seems to work, so should probably be added as a dependency.

**Comment by elijahdorman** [comment]
I'm having this issue with esbuild. Installing `events` just kick it down the road creating runtime errors attempting to access `global`.

**Comment by jo** [comment]
installing `events` along pouch solved this issue for me
