### ISSUE TITLE
pouchdb-adapter-memory in a cluster setup

### ISSUE THREAD

**Issue by Rechdan** [pouchdb/pouchdb#8126]
My question is the following:
Does `pouchdb-adapter-memory` works in a nodejs cluster environment? And by that I mean if I could use it to share informations between master and workers?

Thanks!

**Comment by daleharvey** [comment]
I dont believe node clusters do shared memory out of the box and if so then pouchdb-adapter-memory almost certainly doesnt use it, it just stores all the data in a local variable.
