### ISSUE TITLE
Next release ETA

### ISSUE THREAD

**Issue by jpike88** [pouchdb/pouchdb#8137]
Just want to get an idea of when the next release is going out?

I'm waiting on this to come out, it's easy to accidentally update our `uuid` library right now which breaks things, would like to stop having to pin `uuid` to such an old version

Thanks!

#8060

**Comment by daleharvey** [comment]
I will try to do a release today, cheers

**Comment by daleharvey** [comment]
ok the release has been updated on NPM + https://github.com/pouchdb/pouchdb/releases/tag/7.2.2, the website is currently broken so cant be update quite yet, but will work on it

**Comment by jpike88** [comment]
Thanks, you're a legend
