### ISSUE TITLE
how to do a full text search?

### ISSUE THREAD

**Issue by hoogw** [pouchdb/pouchdb#8138]
how to do a full text search?

**Comment by Terreii** [comment]
PouchDB doesn't support text search out of the box. But this plugin might help: [PouchDB Quick Search](https://github.com/pouchdb-community/pouchdb-quick-search). I haven't used it yet, so I can't help you with it.
There is also a list of other plugins for PouchDB: [Plugins](https://pouchdb.com/external.html).

**Comment by daleharvey** [comment]
Cheers for that, as @Terreii said not something built into PouchDB, but some 3rd party ideas to look at
