### ISSUE TITLE
React Native combined with pouchDB, Do i still need a backend like php if i can code App logic with react native?

### ISSUE THREAD

**Issue by wilson382** [pouchdb/pouchdb#8139]
### Issue
Write the description of the issue here

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by daleharvey** [comment]
I dont fully understand the question but nope, if you can write the logic you need in the client you dont need a server
