### ISSUE TITLE
Can PouchDB handle lot of docs >1000 now?

### ISSUE THREAD

**Issue by ayushcsi** [pouchdb/pouchdb#8142]
### Issue
I have to maintain large amount of data around 40000 docs. Can it now handle that much data efficiently. 

Found this article where it is told to prefer it up to range within 1000 docs. https://pouchdb.com/2015/09/01/pouchdb-4.0.1-gotta-go-fast.html

However library has updated a lot. So can it handle docs around 40000 now?

### Info
- Environment: (browser)
- Platform: (windows)
- Adapter: (IndexedDB)

**Comment by karlwestin** [comment]
This is just a hunch based on my current observation (using the old indexeddb adapter, not the new one)
- i've found ~10000 docs to be a good guideline, but i'm building a view, so if you're avoiding view/find calls and stick with allDocs queries you can probably get away with a higher document count.
- Document count is not the only issue, it's also a tradeoff with document size. Smaller docs = higher limit. We try to keep the data under 40mb. (In the application panel in google chrome)

These numbers are based on our userbase, we have occasional mobile users but mostly laptop usage. It's probably good to have some kind of "benchmark device" which represents what you test on. There are several strategies to not sync the entire database if you don't have to, i hope [this talk my colleague gave last year](https://2019.jsconf.eu/kevin-doran/offline-first-data-getting-bigger.html) can provide some inspiration.
