### ISSUE TITLE
Providing an IndexedDB factory method for custom indexedDB implementations

### ISSUE THREAD

**Issue by ismail-codar** [pouchdb/pouchdb#8143]
This is a statement of opinion for newly developed pouchdb-adapter-indexeddb also old pouchdb-adapter-idb.

For example: https://github.com/dumbmatter/fakeIndexedDB is an  in-memory implementation of the IndexedDB api. 

If a way is provided in pouchdb-adapter-indexeddb or pouchdb-adapter-idb for using fakeIndexedDB rather than native IndexedDB we can have a lightweight and fast pouchdb-adapter-memory alternative.

Note: Dexie has this like feature: https://github.com/dumbmatter/fakeIndexedDB/tree/master#with-dexie-and-other-indexeddb-api-wrappers

**Comment by daleharvey** [comment]
I have also been looking at this for https://github.com/pouchdb/pouchdb/issues/8099, I think its worth keeping in mind while working on the build system

**Comment by ismail-codar** [comment]
No! Mr bot please don't close this.
