### ISSUE TITLE
Main site says 46kb, while downloading 7.2.1.min.js gets 126kb

### ISSUE THREAD

**Issue by DiegoJArg** [pouchdb/pouchdb#8148]
# Issue
Main site says 46kb, while downloading 7.2.1.min.js gets 126kb

### Info
I know it is not significant, but either the compression has changed, or the library got bigger and mainsite should be updated.

### Reproduce
Download the file

**Comment by darkowic** [comment]
It is even less when gzipped ;) See https://bundlephobia.com/result?p=pouchdb@7.2.1

**Comment by jacobidiego** [comment]
bundlephobia, nice tool, actually I may have this phobia ^^

But, then I am missing something, if it is publicited as 46kb gzipped,
shouldn't it be downloaded and linked in gzip format?

The links lines goes to unzipped files
//cdn.jsdelivr.net/npm/pouchdb@7.2.1/dist/pouchdb.min.js
https://github.com/pouchdb/pouchdb/releases/download/7.2.1/pouchdb-7.2.1.min.js

Again, not big deal, just close the issue ^^
Thanks for the answer. One step higher in the learning ladder.

**Comment by darkowic** [comment]
@jacobidiego this is how browsers work - when there is `content-encoding: gzip` header on a source, browser with automatically decompress the resource.
