### ISSUE TITLE
Switch Jekyll site to JS static site builder

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#8149]
So building the website has always been a comlicated task for something so simple, however now redcarpet is no longer supported on modern versions of ruby (https://github.com/jekyll/jekyll/issues/7838) its time to fix it up

**Comment by lybekk** [comment]
If you need any help, I got time to spare

**Comment by shadow81627** [comment]
I would love to help migrate the docs to a JS static site. Have you decided on a static site generator yet? My favorite static site generator is [Nuxt](https://nuxtjs.org/). The [Nuxt content](https://content.nuxtjs.org/) module makes managing markdown files simple and powerful. I just wish it used pouchdb rather than lokidb.

**Comment by daleharvey** [comment]
Nope, historically we used Jekyll because the site was hosted on `gh-pages`, however nowaways its just pushed to a server so no restriction. 

I think something that was able to work with the current data without having to do any conversion (ie https://raw.githubusercontent.com/pouchdb/pouchdb/master/docs/_posts/2014-04-01-pouchdb-2.1.0.md) would give me quite a good level of confidence that 1. We didnt break anything during conversion and 2. The tool we were using was flexible enough to be sustainable. I would like to avoid having to 'buy in' to another ecosystem for what is some fairly basic string conversions

**Comment by nickcolley** [comment]
I've had success converting my personal site from Jekyll to Eleventy as it has the same architectural goals as Jekyll but in JavaScript world.

**Comment by nickcolley** [comment]
I'm going to have a go spiking this as a throwback to my previous PouchDB website work and will share where I get up to.

**Comment by shadow81627** [comment]
With the recent release of [Nuxt content docs theme](https://content.nuxtjs.org/themes-docs/) I think it would be worth using. I can create a pull request for a new docs site with minimal changes to the markdown files. There are some nice default components included for example using https://raw.githubusercontent.com/pouchdb/pouchdb/master/docs/_posts/2014-04-01-pouchdb-2.1.0.md

```md
{% include alert/start.html variant="warning"%}
This release contains a database migration, which means that once you upgrade you will no longer be able to use previous versions of PouchDB on the same databases.
{% include alert/end.html %}
```

would become

```html
<alert type="warning">
This release contains a database migration, which means that once you upgrade you will no longer be able to use previous versions of PouchDB on the same databases.
</alert>
```

Everything else in the file should hopefully be unchanged and all of the styling comes out of the box to generate a performant search optimised docs site.

> I would like to avoid having to 'buy in' to another ecosystem for what is some fairly basic string conversions.

Would the 'buy in' be worth it? or should I create a pull request with the changes to see if it works?

**Comment by nickcolley** [comment]
Alright here's the scrappy WIP I ended up with:

https://github.com/pouchdb/pouchdb/compare/master...nickcolley:jeykll-to-eleventy?expand=1

It runs, but lots of work needs doing, I think it'd probably take a day or two to finish but it is definitely worth a go if you decide to go with Eleventy.

I can try to chip away at it over time if interested or someone else may want to pick it up. @shadow81627 's proposal looks interesting too.

Let me know what you think.
