### ISSUE TITLE
Query search on partial match for multiple fields

### ISSUE THREAD

**Issue by wcastand** [pouchdb/pouchdb#8152]
### Issue
Hi, not sure it's the right place to ask but i keep looking and can't find the answer.
I'm trying to build an autocomplete search for my users and i want to search on firstname and lastname,

#### What i'm trying to do:
if in the input i type `will`: i want a list of all the client where the firstname or lastname starts with `will`
if in the input i type `william cast`: i want a list of all the client where the firstname or lastname starts with `william` or 'cast'

I tried to use query, pouch-find, pouch-quick-search, reduce/map, ...

I tried to get a view with complex keys too : 
```
function map(doc) {
  // sort by last name, first name, and age
  emit([doc.firstname, doc.lastname]);
}
try {
  var result = await db.query(map);
} catch (err) {
  console.log(err);
}
```
and then query : 
```
await db.query(map, {
  startkey: ['will', 'will'],
  endkey: ['will\ufff0', 'will\ufff0' ]
});
```
but it only work on firstname and never filter/show the partial match on lastname too.

So i thought about doing 2 view (one for firstname and one for lastname) but then i couldn't find a way to use both view in the same query. so i would have to make a query for each and then make an union while removing duplicate entries. Seems a bit much for a simple search.

Am i missing something?

thanks for taking the time to read and happy to answer more question :)

### Info
- Environment: NextJS app
- Platform: Chrome
- Adapter: IndexedDB
- Server: No server for now

EDIT: 
This what i ended up with for now : 
```
async (query: string) => {
      const data = new Set()
      await Promise.all([
        db.query('lastname', {
          startkey: query,
          endkey: `${query}\ufff0`,
          include_docs: true,
          limit: 5,
        }),
        db.query('firstname', {
          startkey: query,
          endkey: `${query}\ufff0`,
          include_docs: true,
          limit: 5,
        }),
      ]).then(([last, first]) => {
        last.rows.map((row) => data.add(row.doc))
        first.rows.map((row) => data.add(row.doc))
        setResult(Array.from(data))
      })
    },
```

EDIT 2:
Just realised my solution doesn't quite work.

if i look for the user called `William` and type `willia`, it shows but if i type `william`, then it doesn't show up anymore. the escape `endkey`: `\ufff0` seems to be fucking up when you put the full value :/

EDIT 3:

Still looking into this so i update as i go, trying to use the allDocs with `_id`
with an `_id` like this : `_id: ```client_${firstname.toString().toLowerCase()}_${lastname.toString().toLowerCase()}_${dobb.toUTCString()}```

seems to be able to use it to filter on firstname : 
```db.allDocs({ startkey: `client_${query}`, endkey: `client_${query}\uffff_${query}` })```

but i don't see how to also filter on lastname and do the logic of "query is either in firstname or lastname"

**Comment by Terreii** [comment]
You are correct in that you have to use two querys.

In the Mango Queries guide [section for "Indexing on more than one field"](https://pouchdb.com/guides/mango-queries.html#more-than-one-field) it is explained why. The same rules apply also to Map/Reduce-Queries, as I have described in an [answer to a CouchDB Question](https://github.com/apache/couchdb/discussions/3029).
