### ISSUE TITLE
Can the Map/Reduce API be made non-blocking?

### ISSUE THREAD

**Issue by tom-sherman** [pouchdb/pouchdb#8153]
The map/reduce API blocks the main thread, meaning any queries that are non-trival (or backed by indexes) block the browser from rendering on initial calculation.

Are there any solutions that builds these views without blocking the main thread? Can it be done in a web worker? If not, can we yield between documents?

**Comment by Terreii** [comment]
You can use PouchDB in a worker (even a service worker).
So as a workaround, you can run your the initial indexing in a worker.
