### ISSUE TITLE
PouchDB stop replicating if there is an attachment in the DB

### ISSUE THREAD

**Issue by Tucsky** [pouchdb/pouchdb#8154]
![image](https://user-images.githubusercontent.com/5738336/89317983-7972a000-d67e-11ea-8988-a47895515ee5.png)

![image](https://user-images.githubusercontent.com/5738336/89317991-7d9ebd80-d67e-11ea-9ab7-68af70b6eef1.png)

TypeError: Cannot assign to read only property 'type' of object '#'

![image](https://user-images.githubusercontent.com/5738336/89319599-a1fb9980-d680-11ea-940a-dd4aa8b66b54.png)

Info
Environment: Electron
Platform: Linux and iOS
Adapter: IndexedDB
Server:PouchDB Server

**Comment by arclaxton** [comment]
I'm seeing this same thing, with electron+windows but not osx. It does not happen with v6.4.3.

**Comment by knubie** [comment]
Could be related to https://github.com/pouchdb/pouchdb/issues/7836

When `nodeIntegration` is set to `true` in electron, a `process` variable is created, but `process.browser` is falsey.
