### ISSUE TITLE
Pouchdb guide doesn't actually explain or has an example on how to update a doc

### ISSUE THREAD

**Issue by monxas** [pouchdb/pouchdb#8159]
# Issue
The guide of the page https://pouchdb.com/guides/updating-deleting.html is supossed to explain how to update and it explains some theory about _rev and such, but it never explains or shows an example on how to do an update. I'd do it myself but I'm too new to provide with proper docs about it.

**Comment by joni1802** [comment]
You can find it under [https://pouchdb.com/guides/documents.html#updating-documents–correctly](https://pouchdb.com/guides/documents.html#updating-documents–correctly).

**Comment by lybekk** [comment]
@monxas do you remember where (on what page) you were when looking for it?

**Comment by monxas** [comment]
> You can find it under [https://pouchdb.com/guides/documents.html#updating-documents–correctly](https://pouchdb.com/guides/documents.html#updating-documents%E2%80%93correctly).

It's true and I followed that. What I meant is that in a page where the title is "Updating and deleting documents" there is not a single mention of it in the content. you can even search for the word "updat" and there is actually 0 results in the content, and not an example on how to do it.

**Comment by lybekk** [comment]
@monxas Ah, I see what you mean. Perhaps a short explanation on how to get, update (like a regular JavaScript object), and put back into the db, under a heading a la "Updating an existing document", with a link to 'Updating documents correctly'.

I'll suggest an edit

**Comment by monxas** [comment]
Sounds perfect! @lybekk

**Comment by lybekk** [comment]
Proposed a change on https://pouchdb.com/guides/updating-deleting.html
Pull request #8178
