### ISSUE TITLE
Automatic Conflict Resolution

### ISSUE THREAD

**Issue by MentalGear** [pouchdb/pouchdb#8163]
Just a quick tip, since automatic conflict resolution is something that would make this awesome lib even better.

This is a ready to go implementation of a robost automerge JSON Conflict-Free Replicated Data Type (CRDT) library ready for implementation.
https://github.com/automerge/automerge

**Comment by shadow81627** [comment]
There is a plugin for pouchdb that helps with conflict resolution [pouchdb/upsert](https://github.com/pouchdb/upsert). There is also a [guide in the pouchdb docs](https://pouchdb.com/guides/conflicts.html) about using upserts to help manage conflicts. Is this similar to the functionality automerge provides?

**Comment by MentalGear** [comment]
There's a big difference. C/PouchDB's Conflict system is to use an arbitrary version of two conflicting items. Ex: JSON Item A and JSON Item B have both the same rev number when they want to be added to the main database. Since both have different changes, only one item can be used (like the last submitted). In contrast, automerge would look for the differences in the actual JSON objects, and automatically merge both, so that the latest changes of each version is added to the database.

I advise you to read their excellent [academic essay "Local-first software"](https://www.inkandswitch.com/local-first.html) that showcases many different appraoches and from which the automerge solution is actually spawn (it's beyond me, why it's not linked in the automerge readme).

Im my opinion, it would be a very valuable feature to have in any database.

> Automatic merging. Automerge is a Conflict-Free Replicated Data Type (CRDT), which allows concurrent changes on different devices to be merged automatically without requiring any central server. It is based on academic research on JSON CRDTs [...]

**Comment by Terreii** [comment]
This looks to me like what [redgeoff/delta-pouch](https://github.com/redgeoff/delta-pouch) does. It saves the changes in order and syncs the changes. The data is a result of all changes applied in order. It is mentioned in [PouchDB Conflicts guide](https://pouchdb.com/guides/conflicts.html#accountants-dont-use-erasers).
