### ISSUE TITLE
Unable to build PouchDB documentation

### ISSUE THREAD

**Issue by waitem** [pouchdb/pouchdb#8167]
### Issue
I was unable to build the documentation following the instructions in the [Building PouchDB Documentation section in the  CONTRIBUTING guide](https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md#building-pouchdb-documentation).

I will raise a PR to show how I resolved the issue (which included reverting to jekyll version 3.9)

### Info
- Environment: Ubuntu 20.04

### Reproduce
Follow instructions on the CONTRIBUTING.md page

**Comment by shadow81627** [comment]
https://github.com/pouchdb/pouchdb/issues/8149
