### ISSUE TITLE
I'm trying to create "FIRST" and "LAST" links for the slider (to go to the beginning and end of the slide), and for the "FIRST" value, a simple

### ISSUE THREAD

**Issue by anubes19** [pouchdb/pouchdb#8179]
I'm trying to create "FIRST" and "LAST" links for the slider (to go to the beginning and end of the slide), and for the "FIRST" value, a simple 

`flexsliderMain.flexslider(0);` 

does the trick.

But for "LAST" link, when I try something like this doesn't work, and just returns "2" (attributes.length that is), no matter what (whether I have 10 slides or 200):

`flexsliderMain.flexslider( flexsliderMain[0].attributes.length );`

and it just ends advancing the slide to the next set of slides, instead of forwarding it all the way to the end.

What am I missing?!

__Originally posted by @crazyserb in https://github.com/woocommerce/FlexSlider/issues/1782__

**Comment by crazyserb** [comment]
Is there an answer/solution to this that I've missed here?
