### ISSUE TITLE
Couchdb & pouchdb go out of sync

### ISSUE THREAD

**Issue by sureshvv** [pouchdb/pouchdb#8183]
Occasionally I find that the local pouchdb accumulates documents that never get sent to the Couchdb server.

What is causing this and how can I fix it?

**Comment by wgrhstf** [comment]
What's your setup? Do you work with Electron?

**Comment by sureshvv** [comment]
pouchdb on browser & couchdb on server.

Many times the document contents are the same except for the _rev.
