### ISSUE TITLE
Pouch.find Sort error

### ISSUE THREAD

**Issue by ericksent** [pouchdb/pouchdb#8184]
Hello experts!
I'm trying to adpt my web app to use pouchdb as I need a good offline/sync feature.
At this time, in my first query, I faced the sort error and a warning.
### Issue
The warning is:
warning: "no matching index found, create an index to optimize query time"
To have this warning I removed the sort option to get something. I had the data but sort is needed.
With the sort option I get this error:
Error: Cannot sort on field(s) "comprimento" when using the default index
    at validateSort (pouchdb.find.js:4849)
    at pouchdb.find.js:5559

The code:

```
db.createIndex({
    index: {
      fields: [
          "comprimento",
          "_id",
          "código_barras",
          "obra",
          "referência",
          "cor",
          "ang_esq",
          "ang_dir",
          "vão"
        ]
    }
  }).then(function (result) {
    return db
      .find({
        selector: {
          $and: [
            { obra: "09732019" },
            { referência: "L65502" },
            { timestamp_corte: "FALSE" }
          ]
        },
        fields: [
          "_id",
          "código_barras",
          "obra",
          "referência",
          "cor",
          "comprimento",
          "ang_esq",
          "ang_dir",
          "vão"
        ]//,
        //sort: ['comprimento']
      })
      .then(function (res) {
        console.log(res);
        
      })
      .catch(function (err) {
        console.log(err);
      });
  })
  .catch(function (err) {
        console.log(err);
      });
```

I searched on every place and tryed everything to have this working, and nothing... I realy want to use pouchdb.

### Info
- Environment: browser
- Platform: Chrome
- Adapter: 
- Server: CouchDB (will be)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by ericksent** [comment]
So, I alread made some changes and I think it's working (no warning and now sorting). The problem I have now is the sorting sequency, as 'comprimento' is a number, it's been sorting like 5212, 4582, 354, 2584. The number 354 isn't higher than 2584.
Any idea?

```
db.createIndex({
    index: {
      fields: [
          "comprimento",
          "obra",
          "referência",
          "timestamp_corte"
        ]
    }
  }).then(function (result) {
    return db
      .find({
        selector: {
          $and: [
            { obra: "09732019" },
            { referência: "L65502" },
            { timestamp_corte: "FALSE" },
            {comprimento: {'$gte': 0}}
          ]
        },
        fields: [
          "_id",
          "código_barras",
          "obra",
          "referência",
          "cor",
          "comprimento",
          "ang_esq",
          "ang_dir",
          "vão"
        ],
        sort: [{comprimento: 'desc'}]
      })
      .then(function (res) {
        console.log(res);
        
      })
      .catch(function (err) {
        console.log(err);
      });
  })
  .catch(function (err) {
        console.log(err);
      });
```

**Comment by contiforza** [comment]
Change the sort line to:

sort:  ['comprimento']

Please reply if the results are as you desire.

**Comment by ericksent** [comment]
> Change the sort line to:
> 
> sort: ['comprimento']
> 
> Please reply if the results are as you desire.

Hello Marconi,
I'm already sorting this way:
sort: [{comprimento: 'desc'}]
The problem is the sequency like 5212, 4582, 354, 2584. 

Thank you!
