### ISSUE TITLE
RangeError: invalid date

### ISSUE THREAD

**Issue by cyberquito** [pouchdb/pouchdb#8185]
### Issue
I got the following error, when using bulkDocs with data I don't control:
RangeError: invalid date.

### Info
- Environment: (Node.js)
- Platform: (Mac OS X 10.15.6 )
- Adapter: (RocksDB)

### Fixes

I've added && isFinite(object) into two files to fix this:

@ pouchdb-node/lib/index.js:167
if (object instanceof Date && isFinite(object)) {

@ pouchdb-utils/lib/index.js:57
if (object instanceof Date && isFinite(object)) {

I'm not a maintainer, but I hope it helps.

**Comment by seigel** [comment]
Maybe submit your pull request for that..might be an easy merge for it...is there original data that was causing it so one could potentially add a test to verify the fix?

**Comment by cyberquito** [comment]
Thank you for responding,

I will trace the anomaly on the data set, then submit a pull request with the cause.

regards,

Quito
