### ISSUE TITLE
UIWebView to WKWebView migration

### ISSUE THREAD

**Issue by cujo30227** [pouchdb/pouchdb#8194]
### Issue
I have a Cordova app storing data in a SQLite database using PouchDB. The app is currently using UIWebView on iOS (Cordova 4.5.1) and we are working on migrating to WKWebView (Cordova 6.1.1). The database must be migrated to. However , after numerous tries, we cannot seem to just copy the database over. When testing on the Simulator , an indexedDB database is present in WebKit/Localstorage in the UIWebView scenario. When we copy this over to WebKit/WebsiteData it works. 
However , on a device things are much different. Here , we only find Database.db (websql?) with a subdirectory with files that look like SQLite files , and have a long hex as name (.db extention). 
We have tried several Cordova plugins that are supposed to copy data over for UIWebView to WKWebView migration. Nothing worked. 

##
- Environment: app
- Platform: iOS
- Adapter: IndexedDB/WebSQL
- Server: PouchDB

### Reproduce
Ideally, there would be a way to
1) copy the UIWebView database environment to the Documents storage. 
2) point WKWebView to access the Documents storage site y.

**Comment by cujo30227** [comment]
As info: it seems to be the same issue as this thread: #7770

**Comment by LarsVoith** [comment]
I have not had a chance to do this before, but I'm gonna take a shot at your questions. If you can use couchDB on the server side maybe it's possible to set up a database per user. In this way maybe possible to replicate their data to the server then back again and into indexDB.  Check out this link [https://titrias.com/how-to-pouchdb-couchdb-database-per-user-made-simple/](url)

Also, I know Cloudant (IBM) provides a free database up to one gig

**Comment by cujo30227** [comment]
Thanks for the suggestion, I will look into this.

Just as info for other affected developers:
When building my app with Xcode 11.7, and using UIWebView, I could open the existing WebSQL Database with pouchdb. When building with Xcode 12.0 and UIWebView, I could **not** open WebSQL Databases anymore.

So what I did now for the app app date is:
- Build with Xcode 11.7
- Check whether an IDB is present in the local browser storage
- If not: open an UIWebView with CGRectZero, open the existing WebSQL, convert it to IDB using the code provided in https://github.com/pouchdb/pouchdb/releases/tag/6.4.2 , and then put the resulting IDB in the appropriate location for a WKWebView to access.
- Now open the regular app in WKWebView

This at least gives a few months for all users to migrate to WKWebView until UIWebView will be banned completely. 

Thanks
