### ISSUE TITLE
CouchDB 4.0 + FoundationDB

### ISSUE THREAD

**Issue by mqtik** [pouchdb/pouchdb#8195]
The community recently voted to adopt FoundationDB as the data core of CouchDB 4.0
CouchDB + PouchDB are the core of a lot of projects, and while I take the FoundationDB switch as a good sign, I wonder how it will impact the PouchDB world.

https://forums.foundationdb.org/t/update-couchdb-4-0-on-foundationdb/1690
https://forums.foundationdb.org/t/couchdb-considering-rearchitecting-as-an-fdb-layer/1088

I think it's something we need to consider in case of major changes (which I take there will be).
Any more information on this it's highly appreciated.

**Comment by LarsVoith** [comment]
We are pretty heavily invested in CouchDB/PouchDB with multiple projects at work. Like to understand more how this could affect us.

**Comment by willholley** [comment]
Most of the changes in 4.x are around the implementation - the CouchDB API is mostly the same but with stronger consistency guarantees. For example, the `_changes` feed in CouchDB 4.x adheres to the old CouchDB 1.x semantics in that it is ordered and clients will not suffer rewinds if the server configuration changes.

Bearing in mind 4.x is still a work in progress, it's probably too early to say whether there would be any breaking changes in the API other than what has already been flagged for deprecation in 3.xx, but I wouldn't expect any changes to be required in PouchDB to stay compatible with replication and the core API.

**Comment by LarsVoith** [comment]
Thank you very much,  I'm looking into upgrading our servers to v3 from v2, can you elaborate on attachments?  My understanding is that size limit is changing, are they being handled differently?

**Comment by willholley** [comment]
@LarsVoith that's probably worth an email to the CouchDB mailing list - I don't know what the plan is for attachments in 4.x and can't find any decisions in the rfcs.

**Comment by shadow81627** [comment]
>For now, the only limit we’ve added is max_document_size, it drops from 4GB, which was a theoretical limit to begin with, to 8MB, which is much more reasonable in terms of CouchDB performance.

https://blog.couchdb.org/2020/02/26/the-road-to-couchdb-3-0-prepare-for-4-0/

**Comment by LarsVoith** [comment]
Thanks for the reply, having a hard limit for attachments of 8 MB is really a hard sell and I really hope they don't do this. If this is truly the case couchDB 4.0 would not be a viable option for us.

**Comment by LarsVoith** [comment]
Just for clarification document size and attachment size are differentiated, so it appears like the hard limit of 8 MB does not apply to attachments, a lest for couchDB 3.0

"Limit maximum document body size. Size is calculated based on the serialized Erlang representation of the JSON document body, because that reflects more accurately the amount of storage consumed on disk. In particular, **this limit does not include attachments."**
[https://docs.couchdb.org/en/stable/config/couchdb.html#couchdb/max_document_size](url)

**Comment by willholley** [comment]
@LarsVoith as far as I'm aware there isn't a design for attachments in CouchDB 4.x. I mentioned the couchdb-users mailing list above but forgot that the community has moved to https://github.com/apache/couchdb/discussions - you could start a thread there if you want to get the thoughts of the dev team?

**Comment by mqtik** [comment]
@LarsVoith why not use the filesystem instead of attachments?
Storing binaries in databases has always been a bad idea.

**Comment by LarsVoith** [comment]
@mqtik So, I think for us the end to end solution and the same attachment API's that work both within PouchDB and CouchDB was pretty nice. How is the support for the file system in the browser today?  I still see some  "experimental technology", "Non-standard", "Obsolete"  warnings which kind of concerns me.  Have you tried the filesystem, what are your thoughts? 

[https://developer.mozilla.org/en-US/docs/Web/API/FileSystem](url)

**Comment by mqtik** [comment]
My thoughts would be to get out of attachments as soon as possible. It's not a CouchDB problem. It's a binary-on-database problem.
In any database you might attempt this, it's a bad idea.

Attachments would only lead to memory leaks, deep performance problem regarding indexes (binaries can't be indexed), overload, oversize, ...

Using the operating-filesystem it's always best, because a database would not be able to outperform the FileSystem API in terms of performance and speed.

**Comment by dheimoz** [comment]
Hello @mqtik, first of all, thank you for your take on this. For me Pouchdb is the greatest piece of technology ever written. I can thank enough all the efforts that all the people have done so far. Offline first was just a dream before pouchdb and attachments have played an important part for this equation.
With that being said, I am also aware the performance implications, I have suffered the consequences of utilizing large attachments. I strongly believe that the trade of can be sorted out with filtered replication at client. That way, you can store attachments offline and when back on line send all those attachments to a cloud storage like cloudinary. 

Sorry for the long read, what I am trying to say is that attachments are extremely important and have their place, if only have them in pouchdb and not replicate them to Couchdb. 

Hope this makes sense.

**Comment by mqtik** [comment]
That can be done as a plugin..

Store all images/so on/.. on local, and when doing replicating.to, write a plugin to handle all those uploads and get URL.

That would be real hacky though, and can be easily be avoided by just using Cloudinary directly, and store the URL path on your doc.

Personally, I have another local database to store attachments for offline use. I assign them the URL as the _id, and then when I query it by URL (using .get(), since we know the ID), return { _id: 'https://.../image.png', _attachments...}, do you follow?

**Comment by dheimoz** [comment]
For a Project I am working on I am giving a try localforage https://localforage.github.io/localForage/ for offline storage. Then store the index in Pouchdb. When I am online I upload the document to cloudinary. This way, the document is not stored in Pouchdb and no revision is needed.

Hope this can bring some ideas.  Another option would be https://github.com/jakearchibald/idb

**Comment by mqtik** [comment]
.

**Comment by wizzard0** [comment]
let's try to remove this stale label)) also my 5 cents: while CouchDB/PouchDB obviously isn't a CDN, I found attachments to be still definitely useful in cases like user avatars or previews of large media files stored elsewhere.

And CouchApps are *built* from attachments after all :)

**Comment by wizzard0** [comment]
there it is, rise of the machines

**Comment by jnorthrup** [comment]
in the space of physical modelling and simulation couch 1.x  and maven installs were relatively idiot proof remote deployment requirements providing the following:

benefits of early couchdb; having spent an afternoon writing an "rsync" functionality to attachment hierarchies from local directories:

 * conflict resolution coupled with long-polling work-queues 
 * webapp deployment of source-to-source (gwt) js app from java code/persistence giving live app updates via replication
 * project code/artifacts, and potentially git repo on m2m 
 * fully built and tested features replicated to the sale laptops 
 * '' big iron servers

this locality of reference for all the moving parts of a batch-oriented production system and analytical/command gui  requires constant "new" best practices from "progress" but i just wanted to remark on what was once possible with pre-CORS admin-party VPN topologies as the one and only couchdb server becomes a one-of-many driver layer.

**Comment by jnorthrup** [comment]
does this project need a robot PM ?
