### ISSUE TITLE
Plan for next major release?

### ISSUE THREAD

**Issue by shadow81627** [pouchdb/pouchdb#8196]
@daleharvey  What is the plan for CouchDB 4.0 + FoundationDB #8195?
The current state of this project doesn't seem to be able to support the coming [CouchDB 3.2.0](https://github.com/apache/couchdb/issues/1524#issuecomment-678417452) (#8171) - Allow _access field in documents #8172

It would be nice to have an issue pinned or a github project to track features planned for the next major release. Some thing like the[ CouchDB roadmap](https://github.com/apache/couchdb/projects/1)?

### Tests are failing

> the test can't connect to a browser.
https://github.com/pouchdb/pouchdb/pull/8172#issuecomment-690673347

### Dependencies are outdated

- [Snyk] Security upgrade node-fetch from 2.6.0 to 2.6.1 #8174
- [Snyk] Upgrade uuid from 8.1.0 to 8.3.0 #8160

Using Semantic Release for automated release we could add [Renovate bot](https://github.com/renovatebot/renovate) to auto merge dependency updates when tests pass?

- Lets do automated releases #7733
- [meta] Fix all the build things #8097

### Documentation doesn't build

- Switch Jekyll site to JS static site builder #8149
- (#8167) - revert Jekyll to 3.9.0 to be able to build doumentation #8168

**Comment by shadow81627** [comment]
@daleharvey @garrensmith there doesn't seem to be many active maintainers for this project. Is there something we can do to help keep pouchdb maintained and have security fixes merged in and released?

If there is a lack of time or money for the project could we consider setting up an [open collective for dontaintions](https://opencollective.com/) or some other way to help keep the project maintained?

Are there more maintainers required that can merge in security fixes?

**Comment by dheimoz** [comment]
I second @shadow81627 Daniel. I wonder if there anything from our side that we can help you to keep pouchdb alive. It is a great technology.

**Comment by daleharvey** [comment]
Hey, So very sorry for the lack of action around here, I have had a busy few months.

Over the next few months I have some time to get Pouch back to be maintained and hope to grow the group of maintainers so that we can keep up to date with the incoming PR's

If anyone is interested please say so, I am going to spend a week or so cleaning up issues / PRS then will take a look at doing a release

**Comment by dheimoz** [comment]
Hey @daleharvey thanks for stepping in. Count me in. I love Pouchdb. I do not consider myself as a senior developer but I can help with anything I can.

**Comment by garethbowen** [comment]
@daleharvey I'm keen but short on time.

**Comment by daleharvey** [comment]
I am going to do some cleaning up, make sure the current PR's have had some time then will to a release. I am doing to do some work on increasing the maintainers list as well, if anyone is interested in contributing some time here and there I would be happy to hear from you

**Comment by dheimoz** [comment]
> I am going to do some cleaning up, make sure the current PR's have had some time then will to a release. I am doing to do some work on increasing the maintainers list as well, if anyone is interested in contributing some time here and there I would be happy to hear from you

@daleharvey ready to help in any capacity needed. Pouchdb deserves it!

**Comment by geoidesic** [comment]
I've started testing out PouchDB. It seems to be the only contender out there for offline-first as far as I can tell? If I can get my prototype working I'd be happy to become a contributor but currently I can't get out of the starting blocks: https://github.com/pouchdb/pouchdb/issues/8238

**Comment by brodybits** [comment]
Hey is there any chance that someone could look into #8090, with the `u0000` character in generated keys?

It has let to issues with Cordova plugins and I had to make a workaround for a major client last summer.

**Comment by LyteFM** [comment]
Hi, I maintain [superlogin-next](https://github.com/sl-nx/superlogin-next/tree/minimal), have been a heavy user of PouchDB for Offline-first apps for 2 1/2 years now and could spare some time to get involved with PouchDB maintenance/ecosystem from Feb 15 2021 onwards.

**Comment by jpbourgeon** [comment]
Happy new year PouchDB !

I'm willing to help too. With some guidance I can contribute to basic code maintenance, dependencies updates, codebase refactoring / modernization, etc.

@daleharvey and maintainers
How about opening a github project with various actions/tasks ? We could then prioritize and volunteer on actual issues, depending on our proficiency and/or available time ?

**Comment by sureshvv** [comment]
I am ready to help in  any way I can, May need some hand holding initially.

**Comment by dheimoz** [comment]
Hello @daleharvey considering that Node 10 end of life is on April 2021.
https://github.com/nodejs/Release

It might be worth considering targeting Node 12 as it has full ESM support.
https://github.com/sindresorhus/meta/discussions/15

Hope it makes sense.

**Comment by dheimoz** [comment]
Hi @daleharvey . Ready to start whenever it is possible for you. I empathize that we are all running out of time. Most of us have formal jobs and a schedule to finish. 

For me, Pouchdb has been and will always be the greatest technology ever written.

Thanks.

**Comment by daleharvey** [comment]
OK yeh apologies, there is some work happening behind these scenes that should hopefully mean that Pouch will be getting more actively maintained and even some possible feature development shortly, hopefully more news coming up on that soon.

But lets get a release out once we have addressed (either pushed or closed all the remaining PR's), I think one needs the coverage investigating, one possible needs test failures debugged, checking the rest now

**Comment by paolosanchi** [comment]
What about typescript? I wandered if a porting to typescript would be feasible, I think it would make the code more readable, cleaning up most of the boilerplate, make it typesafe, easy to navigate with vscode (or similar) and attract more casual contributors. I find a bit hard to spot how the overall architecture is made (maybe just because I just missed the plugin stuff until now... see below).

So I got deepen in the code and I found that PouchDb is totally plugin based and strongly based on a sort of polymorphism which is not really supported by a typed language.
What is your through about this?

**Comment by dheimoz** [comment]
Please @daleharvey do not close this issue.
Thanks.

**Comment by dheimoz** [comment]
Hey @daleharvey I wonder if you can consider open this issue again.

Thanks.

**Comment by daleharvey** [comment]
Cheers for the ping, promise this is getting cleaned up soon :)

**Comment by dheimoz** [comment]
No problem @daleharvey, let me know if I can be of any assistance.

**Comment by dheimoz** [comment]
For all folks interested in collaborate and talk about Pouchdb. I invite you to join the channel at the Official Couchdb workspace:
https://couchdb.slack.com/archives/C016TJAE7A4

**Comment by lgourain** [comment]
Hello,

What about supporting Deno for the next major release ?

It is supporting Typescript natively and has a lot of cool features shipped in (standard library, modern javascript and compilation into one executable especially is something I am really interested in for deployment purposes) . A discussion is opened here : #8158 

It could be great to have a way to use PouchDB with Deno.

Thanks,

**Comment by seigel** [comment]
I do not have a ton of time, but would like to contribute where I can.  Any specific issues you want another set of eyes on?

**Comment by sureshvv** [comment]
Correct me If I am wrong, but I am not sure we do proper triageing of issues. Issues get closed as they become "stale". Just flagging valid issues so that they don't get stale could be a good idea.

**Comment by dheimoz** [comment]
hey @seigel , thanks for the good will.  Will help a lot if you can comment your experience and ideas on open issues.

@sureshvv as this is an Open Source Project and the members offers their assistance whenever they have availability, the stale bot was configured in order to keep track of those issues that were documented. I know it is not ideal and agree with you we can do better.

Hope that eventually we might clean up some redundant code and update the documentation.

There are some excellent PR's waiting to be reviewed. As you might expect there are tons of work to be done.

**Comment by gaodeng** [comment]
?

**Comment by shadow81627** [comment]
Exciting to see a new release https://github.com/pouchdb/pouchdb/releases/tag/7.3.0
