### ISSUE TITLE
package-lock.json

### ISSUE THREAD

**Issue by shadow81627** [pouchdb/pouchdb#8203]
### Issue

`package-lock.json` is generated by `npm install` but not committed or added to `.gitignore` file.

### Reproduce

```bash
$ npm install
```

### Solution

Commit `package-lock.json` or add it to `.gitignore` file.

**Comment by sennahLessert** [comment]
i'll do this

**Comment by sennahLessert** [comment]
could you please tag this issue with hacktoberfest tag? Thank you
