### ISSUE TITLE
Bug: pouchdb-adapter-memory does not work with Angular v10

### ISSUE THREAD

**Issue by thefliik** [pouchdb/pouchdb#8206]
_This issue was originally filed in the [rxdb repo](https://github.com/pubkey/rxdb/issues/2563) but I think it is more appropriate here._

## Issue
When attempting to use `pouchdb-adapter-memory` inside an Angular v10 app with [rxdb](https://github.com/pubkey/rxdb), the following errors are thrown during compilation:

```
ERROR in ./node_modules/sublevel-pouchdb/node_modules/readable-stream/readable.js
Module not found: Error: Can't resolve 'stream' in '/workspaces/rxdb/examples/angular/node_modules/sublevel-pouchdb/node_modules/readable-stream'

ERROR in ./node_modules/sublevel-pouchdb/node_modules/readable-stream/lib/_stream_readable.js
Module not found: Error: Can't resolve 'stream' in '/workspaces/rxdb/examples/angular/node_modules/sublevel-pouchdb/node_modules/readable-stream/lib'

ERROR in ./node_modules/sublevel-pouchdb/node_modules/readable-stream/lib/_stream_writable.js
Module not found: Error: Can't resolve 'stream' in '/workspaces/rxdb/examples/angular/node_modules/sublevel-pouchdb/node_modules/readable-stream/lib'
```

While these errors don't prevent compilation from completing, attempting to load the app in a web browser results in an error.

## Info
  - Environment: browser (Chrome 85) though the error is thrown during compilation (Node 12)
  - Adapter: Memory
  - Stack: Angular v10

## Code
See this reproduction of the issue using the rxdb Angular example app: https://github.com/thefliik/rxdb/tree/ng-in-memory-db/examples/angular

**Comment by LyteFM** [comment]
This isn't a problem of PouchDB either, it arises because Angular has been removing support for nodejs libraries in its last few releases. You need to polyfill them if you use a package that depends on these libraries. For exapmle, in order to get your repo running:

``` bash
npm i stream-browserify process buffer
```

in `tsconfig.json`, add to `compilerOptions`:
``` json
"paths": {
      "stream": ["node_modules/stream-browserify"],
      "process": ["node_modules/process"]
    }
```

replace the top of your `polyfill.ts` with:
``` js
(window as any).global = window;

/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.
(window as any).global = window;
global.Buffer = global.Buffer || require('buffer').Buffer;
global.process = global.process || require('process')
```
