### ISSUE TITLE
Pull request template

### ISSUE THREAD

**Issue by shadow81627** [pouchdb/pouchdb#8210]
### Issue
The [contributing guide](https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md#guide-to-contributions) describes the form pull requests should take. But not everyone is following this template. Github allows [pull request templates](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) so that when a pull request is opened it has the boilerplate structure filled out. It would be helpful to add a [issue link](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) section in the pull request to enable automatic closing of issues when a pull request is merged.

```
(#8210) - A brief one line description < 50 chars

Followed by further explanation if needed, this should be wrapped at
around 72 characters. Most commits should reference an existing
issue

closes #8210
```

**Comment by dheimoz** [comment]
I could not agree more.
