### ISSUE TITLE
Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.

### ISSUE THREAD

**Issue by codeHysteria28** [pouchdb/pouchdb#8214]
### Issue

I doing react app photo gallery. Uploading files and retrieving them as result into console from local or remote database it's working I have only problem with converting the blob into url to populate the images because I'm getting above error. I will put here my code snippet to clarify. Thanks

`db.allDocs({
        include_docs: true,
        attachments: true
    }).then(function (result) {
        const res = result.rows;
        console.log(res);
        res.forEach(el => {
            // return db.get(el.doc._id);
            return db.getAttachment(el.doc._id);
        })
    })
    .then(function(blob){
        const url = URL.createObjectURL(blob);
        console.log(url);
    })
    .catch(function (err) {
        console.log(err);
    });`

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by daleharvey** [comment]
It seems `createObjectURL` is deprecated, and if there is a bug there is not enough information here to determine what it is, if you could make reliable steps to reproduce that would be great,  https://pouchdb-bug-helper.glitch.me/ can help as a start
