### ISSUE TITLE
React Native support?

### ISSUE THREAD

**Issue by danieldeev** [pouchdb/pouchdb#8216]
Does **PouchDB** work well on **React Native** projects? I currently use **Redux Persist** for such a task that at its core uses **AsyncStorage** as a storage base.

**Comment by jcalixte** [comment]
Hi, I think the last thing I remember is this blog [post](https://dev.to/craftzdog/hacking-pouchdb-to-use-on-react-native-1gjh), it seems the react native [adapter](https://github.com/stockulus/pouchdb-react-native) works fine if you're not interested to use attachments.

**Comment by Ngomana** [comment]
Will there be any support for react native in the near future?

**Comment by Ngomana** [comment]
> Does **PouchDB** work well on **React Native** projects? I currently use **Redux Persist** for such a task that at its core uses **AsyncStorage** as a storage base.

Try realm from mongodb
