### ISSUE TITLE
search with pouchdb-find with $or in selector and sort result in a "no_usable_index" error

### ISSUE THREAD

**Issue by florianroulet** [pouchdb/pouchdb#8217]
### Issue

error : "no_usable_index","message":"There is no index available for this selector.
Getting this error when searching with pouchdb-find with a $or in selector and a sort

### Info

- Environment: Node.js/browser
- Platform: Chrome (ElectronJs)
- Adapter: localstorage
- Server: none

### Reproduce

https://fluoridated-innovative-tanker.glitch.me/
the example should return the 2 lasts element recorded sorted on foo field.

**Comment by florianroulet** [comment]
From my debug, I think the issue is from the "getUserFields" method which is returning the '$or' as a selectorField.
I try to find a way to submit a PR.

**Comment by daleharvey** [comment]
Awesome thanks so much for the reproduction that will help it get fixed a lot. Happy to take a look at any PR

**Comment by florianroulet** [comment]
Sadly, i spent some time trying to fix but i could not get it to work ! 
Each time i fixed a test, another one broke ! 
If you need more info, don't hesitate to ask !

**Comment by florianroulet** [comment]
Any news ?
