### ISSUE TITLE
How many Maximum Live Sync Pouchdb/Couchdb?

### ISSUE THREAD

**Issue by a0fzide** [pouchdb/pouchdb#8218]
### Issue
I saw this issue. https://github.com/pouchdb/pouchdb/issues/5012

### Info
- Environment: browser/hybrid app
- Platform: Android
- Adapter: -
- Server: CouchDB & PouchDB Client

### Reproduce
I try to use pouchdb realtime sync but for more than 5 connection sync. The new one cannot be get data from couchdb with live sync function.

**Comment by daleharvey** [comment]
This depends entirely on the environment, in node you open a lot of connections, according to https://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser most browsers are at around 6 at the moment

**Comment by mbret** [comment]
I worked around this issue by using http2. Took me three line of change of my express server with spdy. If you have control on that you can try it too. Http2 doesn't have the 6 concurrent limitation
