### ISSUE TITLE
Update stale bot

### ISSUE THREAD

**Issue by shadow81627** [pouchdb/pouchdb#8219]
The stale bot isn't marking issues as unstale when commented on. Issue #8196 was marked as stale, commented on and then closed without having the stale tag removed.

**Comment by daleharvey** [comment]
So the stalebot has some strange behaviour and possible bugs @ https://github.com/actions/stale/issues/86, we may want to switch bots but it wasnt a configuration issue, will manually fix any errors for now and have updated the workflow at the above PR

**Comment by daleharvey** [comment]
Merged some updates to the stale configuration, if anyone sees it not removing stale when it should be give me a ping, cheers
