### ISSUE TITLE
Ionic Capacitor, Pouch DB replication halts after receiving a Blob attachment

### ISSUE THREAD

**Issue by pete-mcwilliams** [pouchdb/pouchdb#8220]
### Issue
I'm in the process of upgrading from Cordova to Capacitor in an Angular project that uses Pouch DB to provide offline storage of a Couch DB server.

The Cordova version of the application works fine.
The ionic serve desktop version is working fine, storing into IndexedDB.
The Capacitor version looks to be stalling at bulkDocs (does not error or report success) after retrieving a blob via getAttachment which does report success.

On mobile devices we first replicate the https database to local Pouch DB before starting sync.  I am not receiving the complete callback for replicate (or an error).

setting batch_size: 1 and batches_limit: 1 has allowed me to narrow down the issue to the first doc that has an attachment of type blob.

enabling debug for pouch is showing the following in the log, with the bulkDocs line being the final pouchdb:api line.
```
pouchdb:api https://[sic]/mobilesync +116ms getAttachment success Blob 
size: 66216
type: "image/jpeg"

pouchdb:api mobilesync +11ms bulkDocs Object Object
```

Has anyone came across similar issue?

### Info
- Environment: npx ionic info
```
Ionic:

   Ionic CLI                     : 6.12.0
   Ionic Framework               : @ionic/angular 5.4.1
   @angular-devkit/build-angular : 0.1002.0
   @angular-devkit/schematics    : 10.2.0
   @angular/cli                  : 10.2.0
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : not installed
   native-run  : 1.2.2

System:

   NodeJS : v15.0.1
   npm    : 7.0.3
   OS     : macOS Catalina
```
- Platform: iOS and Android
- Adapter: neither work on mobile IndexedDB or SQLite
- Server: CouchDB to PouchDB

**Comment by mduriancik** [comment]
Hi, maybe I have a similar issue #8225 .

Milan

**Comment by pete-mcwilliams** [comment]
> Hi, maybe I have a similar issue #8225 .
> 
> Milan

Thanks for your suggestion, however, I think the issue is different.

process.browser evaluates to true so the code is not stepping into 
```
     if (typeof process !== 'undefined' && !process.browser) {
        blob.type = contentType;
      }
```

**Comment by daleharvey** [comment]
Dont know off the top of my head what could causse that, but sounds like a bug in Capacitor, probably worth trying to make a simple reproduable test case and seeing whats causing the failure

**Comment by pete-mcwilliams** [comment]
I've discovered an issue with FileReader zone.js and capacitor 

https://github.com/ionic-team/capacitor/issues/1564

Placing the fix mentioned on that page resolved my issue with PouchDB, specifically adding this to the app.module.ts file.
```
export class FileReaderA extends window.FileReader {
  constructor() {
    super();
    const zoneOriginalInstance = (this as any)['__zone_symbol__originalInstance'];
    return zoneOriginalInstance || this;
  }
}

window.FileReader = FileReaderA;
```
