### ISSUE TITLE
pouchdb-find, $and and multiple $regex conditions

### ISSUE THREAD

**Issue by bogenpirat** [pouchdb/pouchdb#8222]
### Issue
using pouchdb with pouchdb-find, i can prepare a selector with two or more `$regex` conditions in an `$and` array and only the *last* of those conditions is ever respected.

### Info
- Environment: plain node (v12.18.4) script
- Platform: Windows
- Adapter: seems to affect both IndexedDB in Electron as well as LevelDB in node
- Server: pouchdb embedded code

### Reproduce
1. set up a db
2. insert some docs with an attribute that has minor overlap
3. create a selector similar to this in structure:
```javascript
{
  '$and': [
    { text: { $regex: '.*foo.*' } }, // condition1
    // [...] further conditions
    { text: { $regex: '.*bar.*' } } // conditionN
  ]
}
```
4. `condition1`...`conditionN-1` are ignored, only `conditionN` is used to return documents

i wrote a small example reproducing the behavior [here](https://gist.github.com/bogenpirat/63c5452cd43b7cbd10f6df7ffcf3158f)

is this a bug or limitation? is there a workaround?

**Comment by AlansCodeLog** [comment]
I too recently ran into this and am working on a fix. It seems to have been an issue for a long time (see #6260). Ran into this issue just now looking searching for that one! lol.

Anyways there's a fix described there but it's not very clean. The better thing seems to handle the operator like `$ne` is handled. I'll be submitting a PR soon, just want to make sure everything is working.
