### ISSUE TITLE
Remove setting blob type in http adapter

### ISSUE THREAD

**Issue by mduriancik** [pouchdb/pouchdb#8225]
### Issue

When synchronizing documents with attachements (replicateFrom) in our Electron application we get a TypeError on a Blob.
The code is running in the RenderProcess with NodeIntegration enabled (webPreferences: {nodeIntegration: true, enableRemoteModule: true, webSecurity: false}).

### Info

Windows 10
Angular 9.1.12 / Ionic 5.4.1
Electron 10.1.5 
Adapter: IndexedDB
CouchDB 2.3

### Details

The error occurs in [/pouchdb-adapter-http/src/index.js:632](https://github.com/pouchdb/pouchdb/blob/1ba879709fdf6306dc3f8e9d2d67f4060ade6e50/packages/node_modules/pouchdb-adapter-http/src/index.js#L632)

```javascript
   // TODO: also remove
   if (typeof process !== 'undefined' && !process.browser) {
     blob.type = contentType;
   }
```

In fact with Electron/RenderProcess blob is a standard Blob type, which is [read only](https://developer.mozilla.org/en-US/docs/Web/API/Blob).
(The condition `typeof process !== 'undefined' && !process.browser` in our Electron with NodeIntegration evaluates to true)

Possible solutions:

1. the code should be removed (I think this is what the comment meant)

2. if 1. is not possible please change the condition to something like:

`typeof process !== 'undefined' && window === undifined` or  `typeof process !== 'undefined' && process.versions.electron`

or make sure that "blob" type is not Blob (to differentiate it from Buffer, I suppose it is when using node-fetch) 

`! (blob instanceof Blob)`

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

Milan

**Comment by pete-mcwilliams** [comment]
Have you seen these two issues?
https://github.com/pouchdb/pouchdb/issues/8154
https://github.com/pouchdb/pouchdb/issues/7836

**Comment by daleharvey** [comment]
Happy to take a PR to remove that code, if I remember we were trying to have code that used blobs and buffers interchangably that we ended up removing anyway. 

I suspect there is a test that will check for this property, but if you make a PR with it removed we can see what the tests say

**Comment by saschwarz** [comment]
FWIW - I get the error reported in https://github.com/pouchdb/pouchdb/issues/7021 when running an ionic angular app in the browser using pouchdb with the indexeddb adapter (not Cordova). A local edit removing the code indicated by @mduriancik resolves that issue.

**Comment by ajboni** [comment]
Is this fixed? I'm getting same error on Electron + nodeIntegration:true

**Comment by pturner1989** [comment]
I also ran into this issue yesterday which prevented me from synchronising any attachments from a http CouchDB instance to a local PouchDB instance.

The same problem has been avoided on line 517 of pouchdb-adapter-http by checking the blob.type has a setter before setting the contentType.
