### ISSUE TITLE
PouchDb does not pass custom headers to remote when making 'OPTIONS' request.

### ISSUE THREAD

**Issue by willemodendaal** [pouchdb/pouchdb#8226]
### Issue
I configure a PouchDb remote with the "fetch" option, so that I can append custom headers that should be send to the remote.

However, when PouchDb makes the request, the request fails and I can see that my headers were not appended. Do I need to do anything special to pass along headers to the server?

My couchDb configuration looks like follows:

```
[couchdb] 
single_node=true ; We set this, so that system dbs are created automatically.

[httpd]
enable_cors = true

[chttpd]
port = 31986

[cors]
; List of origins, separated by a comma (protocol, host, optional port)
; refer to http://tools.ietf.org/html/rfc6454 for specification
; //todo: these should differ based on environment. "localhost" is only for local dev.
credentials = true
origins = http://localhost:3000, https://localhost:31984
```

The javascript code that attempts to send the custom headers ([based on the pouchDb api docs](https://pouchdb.com/api.html#create_database)).

```
    const createDbDocument = async () => {
        if (!familyDbCreated) return;

        console.log('Save document to local pouchDb...');
        const localPouchDb = new PouchDB(state.familyDbName);
        await localPouchDb.post({
            timestamp: new Date(),
            createdByUser: state.userName
        });

        console.log('Replicating to server...');
        const remoteCouch = new PouchDB(
            'http://localhost:31986/' + state.familyDbName,
            {
                fetch: (url, opts) => {
                    const headers: any = opts.headers; // Casting headers to any, because typescript can't find the 'set' method, but it is there.
                    headers.set('X-CouchDB-WWW-Authenticate', 'Cookie');
                    headers.set('A-RANDOM-123', '!23');
                    headers.set('Cookie', 'AuthSession=' + state.couchDbToken);
                    opts.credentials = 'include';
                    return PouchDB.fetch(url, opts);
                }
            });
        await localPouchDb.replicate.to(remoteCouch);
        await localPouchDb.replicate.from(remoteCouch);
        console.log('Replicated.');
        updateDbContentsList(localPouchDb);
    }
```

The 'options' request made by PouchDb/browser...  (this fails with 401 unauthorized, because the auth cookie is not appended)

```
Request URL: http://localhost:31986/familydb2020o11o17t13o51o15o999z/
Request Method: OPTIONS
Status Code: 401 Unauthorized
Remote Address: [::1]:31986
Referrer Policy: strict-origin-when-cross-origin

*** Request headers:
OPTIONS /familydb2020o11o17t13o51o15o999z/ HTTP/1.1
Host: localhost:31986
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: */*
Access-Control-Request-Method: GET
Access-Control-Request-Headers: a-random-123,content-type,x-couchdb-www-authenticate
Origin: http://localhost:3000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-Fetch-Dest: empty
Referer: http://localhost:3000/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,af;q=0.7

*** Response headers:
HTTP/1.1 401 Unauthorized
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Expose-Headers: content-type, cache-control, accept-ranges, etag, server, x-couch-request-id, x-couch-update-newrev, x-couchdb-body-time
Cache-Control: must-revalidate
Content-Length: 78
Content-Type: application/json
Date: Tue, 17 Nov 2020 13:51:41 GMT
Server: CouchDB/3.1.1 (Erlang OTP/20)
X-Couch-Request-ID: 4c23f79d1a
X-CouchDB-Body-Time: 0
```

I also had a look at the [CouchDb cors documentation](https://docs.couchdb.org/en/1.3.0/cors.html), but did not see anything special regarding headers.

Am I missing something obvious?

### Info
- Environment: Browser
- Platform: Chrome Version 86.0.4240.198 (Official Build) (64-bit)
- Adapter: Default (I'm not sure which one gets chosen by default?)
- Server: CouchDb running in a container.

**Comment by daleharvey** [comment]
Tests are passing and this is a fairly simple code path so I would be surprised if something is broken on this end.

I can see you have to do some mangling with TypeScript, does TS do anything strange with pass by reference vs value? are you certain the opts.headers object contains your headers?

**Comment by daleharvey** [comment]
So weirdly I cant actually find the tests for this feature, however where you have `return PouchDB.fetch(url, opts);` you dont actually need to use PouchDB.fetch, you can just call fetch directly, that would help you debug where the headers are going

**Comment by cesine** [comment]
I can reproduce this case as well, here is a screenshot that shows what i think is  root cause: 

![Screen Shot 2020-11-29 at 2 33 03 PM](https://user-images.githubusercontent.com/196199/100551729-9b58e980-3250-11eb-829b-2962b482e647.png)


Steps to reproduce

1. set up couch on a given url (purple.org) with cors support
2. login to couch successfully (via fetch or pouch) using the console on another domain (blue.com) 
```
fetch('https://purple.org/_session', {
    method: 'POST',
    mode: 'cors',
    cache: 'no-cache',
    credentials: 'include',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
    },
    redirect: 'error', // manual, *follow, error
    referrerPolicy: 'no-referrer-when-downgrade',
    body: JSON.stringify({ name: 'myuser', password: 'mypass' }),
  }).then((response) => {
    const data = response.json();
    console.log('data', data);
    return data;
  }).then((data) => {
    console.log('data', data);
    return data;
  });

Promise {<pending>}
VM2949:15 data Promise {<pending>}
VM2949:18 data {ok: true, name: "myuser", roles: Array(104)}
```
3. in the screenshot observe the headers are correct, the login works, but there is a warning on the `Set-Cookie` response

> This Set-Cookie didn't specify a  "SameSite" attribute and was defaulted to "SameSite=Lax" and  was blocked because it came  from a cross-site response which  was not the response to  a top level navigation. The Set-Cookie had to have been set with "SameSite=none" to enable cross-site  usage.

4. observe subsequent pouch get  will be missing  the AuthSession too

I'll report  back after I do some header changes on my couch to see if i can get it working with the new chrome security policy.

Docs about when this enforcement started: 

* https://blog.chromium.org/2020/04/temporarily-rolling-back-samesite.html
> With the stable release of Chrome 80 in February, Chrome began enforcing secure-by-default handling of third-party cookies as part of our ongoing effort to improve privacy and security across the web. We’ve been gradually rolling out this change since February and have been closely monitoring and evaluating ecosystem impact, including proactively reaching out to individual websites and services to ensure their cookies are labeled correctly.
* https://www.chromium.org/updates/same-site/faq
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by dheimoz** [comment]
thanks @cesine

**Comment by daleharvey** [comment]
Thats a very helpful investigation @cesine, thanks a lot, closing this out as not a pouchdb issue
