### ISSUE TITLE
Stored FontFile cannot be loaded

### ISSUE THREAD

**Issue by uinstinct** [pouchdb/pouchdb#8236]
### Issue
I am trying to use PouchDB to store a font file in the browser's db and then load it. But the fontFace does not seem to be read when I am changing the font-family.
My `addFontFace` function works fine with `event.target.files[0]` but not with the blob from PouchDB.
I can't understand where I am going wrong.

### Info
- Environment: Browser
- Platform: Firefox
- Adapter: IndexedDB
- Server: None

### Reproduce

This is my helper function to read and write in PouchDB:

```js
import PouchDB from "pouchdb";

const db = new PouchDB("font-file");

export function saveFont(data) {

    const doc = {
        "_id": "font-family-id",
        "title": "FontFamily",
        "_attachments": {
            "font-file-id": {
                "content_type": "font/ttf",
                "data": data
            }
        }
    };

    db.put(doc)
        .then(res => {
            console.log(res);
        })
        .catch(err => console.log(err));
}

export function loadFont() {
    return db.getAttachment("font-family-id", "font-file-id")
        .then(blob => {
            return blob;
        })
        .catch(err => console.log(err));
}
```

This is my function which reads the fontFile and adds the font to the `document`:
(`fileObj` is just `event.target.files[0]` when the font is being uploaded by the user)
```js
function addFontFromFile(fileObj) {
    const reader = new FileReader();
    saveFont(fileObj);
    reader.readAsArrayBuffer(fileObj);
    reader.onload = (e) => {
        const newFont = new FontFace('loadedFont', e.target.result);
        newFont.load().then((loadedFace) => {
            document.fonts.add(loadedFace);
        });
    };
}
```

and then _window.onload_, I am just reading the font from the database:
*Note - I already have the font in the database from the above step*
```js
loadFont()
           .then((blob) => {
               console.log(blob);
               addFontFromFile(blob);
           })
       .catch(err=>console.log(err))
```
The fontface does not seem to load in this case when I set the font-family to `loadedFont`.

I would be really grateful if someone could tell me where am I going wrong?

**Comment by daleharvey** [comment]
Nothing seems obviously wrong from your code, will need to be able to reproduce this to debug it further - https://pouchdb-bug-helper.glitch.me/

**Comment by uinstinct** [comment]
@daleharvey Should I post some screenshots?
Any other approach is welcome, just that it works.

**Comment by oxygen** [comment]
I remember Chrome had some issues with loading fonts early at on load. That is, loaded custom fonts would be overwritten later because font loading and rendering is somehow delayed a lot for performance reasons I would guess.

**Comment by daleharvey** [comment]
Cheers @oxygen that sounds like a good place to look

@uinstinct screenshots probably wont help much, if you checkout that website I linked (or use jsbin etc) you can write some code that stores a font in pouchdb then attempts to load it, when you have a standalone example of it failing it will be possible to debug

**Comment by uinstinct** [comment]
I will do as directed tomorrow.
And post here if I encounter any further problems.

**Comment by uinstinct** [comment]
I have resolved it.
You can check [it out here](https://codesandbox.io/s/fontfile-issue-pouchdb-resolved-mkewn?file=/src/App.js)

It seems that the following code was not working:
```js
const doc = {
        _id: 'font-family-id',
        title: 'FontFamily',
        _attachments: {
            'font-file-id': {
                content_type: 'font/ttf',
                data,
            },
        },
    };
 db.put(doc)
        .then((res) => {
            console.log(res);
        })
        .catch((err) => console.log(err));
```

**But this worked:**

```js
db.putAttachment('doc-id-1', 'attachment-id-1', rev, data, 'font/ttf')
        .then((resp) => (!!resp.ok))
        .catch(() => false);
```

**Comment by daleharvey** [comment]
Great! glad you got it working
