### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by richard457** [pouchdb/pouchdb#8239]
### Issue
Try to sync database and I am getting 401 unauthorized yet have been using recently and this error shows up

### Info
- Angular & electron

### Reproduce
Try to sync the database with couchbase and sync gateway then flush data from the remote database and the issue show up.

**Comment by daleharvey** [comment]
Sync Gateway is not a supported server - https://pouchdb.com/faq.html#what_can_pouchdb_sync_with

If you have another problem, we would need far more information in order to be able to debug it, a reproducable example @ https://glitch.com/~pouchdb-bug-helper would be ideal. Thanks

**Comment by richard457** [comment]
My bad I wanted to mean sync with Couchbase Lite for Android and yes it is supported

**Comment by richard457** [comment]
Also, I think you are wrong @daleharvey this https://pouchdb.com/2015/04/07/better-late-than-never.html clearly says that it is supported and I have been using it for a while, I am not sure why you closed this issue with no answer

**Comment by daleharvey** [comment]
That blog post was written in 2015 by me, we explicitly removed support due to ongoing compatibility issues in 2018 @ https://github.com/pouchdb/pouchdb/issues/5820

**Comment by richard457** [comment]
Great, I see, as I have been experimenting with pouchdb latest version and to some extent, it worked, so I am wondering what is the known last version that did perform well??

**Comment by richard457** [comment]
I love to contribute to adding it back to make it work, this is very big and to me seems a lot of work is already done, only a piece of cake is remaining, if there can be resources that can help me please point me to those so I can gear, Let me know what you think,, is it possible to add it back? What are technical challenges and where we can draw the line regarding the incompatibility issue mentioned with couchbase sync gateway.
