### ISSUE TITLE
Trying to create a postgresql adapter, but falling to create mango Index

### ISSUE THREAD

**Issue by jmdiazlr** [pouchdb/pouchdb#8245]
### Issue
I rewrote the websql for sqlite to use postgresql (via node-postgresql)... all websql tests passed.
Then I rewrote the pouchdb-websql adapter.
My first simple tests passed.... (put, get, allDocs)
My trouble starts when creating a mango Index:

```
db.createIndex({
  index: {
    fields: ['name'], 
    name: 'myNameIndex',
    ddoc: 'myNameIndex'
  }
}
```
and received received:

`ERROR: invalid byte sequence for encoding "UTF8": 0x00`

I traced it to this query and parameter:

```
SELECT json FROM document_store WHERE id = $1 [
  '54Juan ManuelFri Dec 04 2020 14:05:57 GMT-0600 (GMT-06:00)Fri Dec 04 2020 14:08:27 GMT-0600 (GMT-06:00)\u00004juan\u0000\u0000'
] 
```
This is some query executes by pouchdb-find, but postgresql does not support  \u00 in text/varchar column values neither in query parameters.

Is there any way to avoid using this characters in pouchdb-find ?.

Any other direction ?

### Info
- Environment: (Node.js)
- Platform: Ubutu, Linux
- Adapter: WebSQL Over Postgresql
- Server: planning PouchDB Server

### Reproduce
This is not posibble as I am writing a new adapter.

**Comment by jmdiazlr** [comment]
I reviewes the sources... and found the source of error at pouchdb.find->pouchdb-abstract-mapreduce -> pouchdb-collate. The thing is that \u0000 is being used as field separtor in serialize several fields as a string... I made a dirty change to pouchdb-collate to use character \u0003 in place of \u0003 as field separator... all is working now, but I think it is not a total solution, it should fail it any value serialized already have this character... but I think this unlikely to occur.

Does anybody have a better idea ? Or better strategy ?

By now, my adapter is working fine... indexes, mapreduce, replication, etc... but  it is early to publish it.

**Comment by revington** [comment]
hey @jmdiazlr I'm also interested in adapting postgresql to pouchdb. Any plans to release your changes?
