### ISSUE TITLE
Replication checkpoints are done too late ?

### ISSUE THREAD

**Issue by jmdiazlr** [pouchdb/pouchdb#8247]
### Issue
I am trying to reduce time for initial load on mobile db via replication. It takes 65 segs form 28,000 docs in local environment (couddb server and browser in same development machine).

Reviewing then network traffic in the browser, I see that all remote check points are done at the very end of the replication processs... after replicating then 28000 docs... **I think this way of checkpointing is neglecting their porpoise*. Or I am misssing something ?

return db.replicate.from(remoteDB, {batch_size: 500})
   .then( () => {
      return db.sync(remoteDB);
   })

The image shows the networks traffic, all checkpoints are done after 45000 ms... all real data interchange is done before that time. 

![imagen](https://user-images.githubusercontent.com/13573695/101533912-1199d200-395c-11eb-8186-cfb9d83fb0ac.png)

### Info
- Environment: Browser Chrome/firefox (with no initial db), server CouchDB 3.11 (with initial data)
- Platform: Ubuntu Linux
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by jmdiazlr** [comment]
I was wrong:  there are to replication actions: replicate(), the sync.. the traffic I was looking were from the sync()... the checkpoints are done well for the replicate part.

Any way, the sync() part generate too much network traffic, because it rechecks the all newly received docs for diffs with the remote db, and this is taking almost 20% of total time on initial replication. I do not know it it is possible, but initial replication should avoid this revisions. 

Thanks.

**Comment by dheimoz** [comment]
Hello  @jmdiazlr , I believe the best way to handle this kind of traffic problem is first a one way replication from the Server and after is complete a sync between them.

Hope this make sense.
