### ISSUE TITLE
Forever stuck on first _local lookup

### ISSUE THREAD

**Issue by mbret** [pouchdb/pouchdb#8250]
### Issue
Looping over _local lookup and 404 forever when running in production

### Info
- Environment: (Node.js/browser)
- Platform: (Chrome)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB)

### Reproduce
So when running in development I have the normal 404 for the _local but then shortly after pouchdb will make a PUT and the replication stabilize. 

![image](https://user-images.githubusercontent.com/1911240/101984370-6921a000-3cc4-11eb-801f-b86f153a70c2.png)

However when running in production, pouchdb will forever block on the 404
![image](https://user-images.githubusercontent.com/1911240/101984597-dbdf4b00-3cc5-11eb-8a05-6566fb7299d5.png)

Could this be because of some misconfiguration of couchdb on my production server ?

**Comment by dheimoz** [comment]
Hello @mbret , which version of Couchdb are you using? Starting version 3 the "admin party" is no more. With that being said, you need to provide a valid Couchdb user for Pouchdb to connect. The easiest way is through:
 "http://MYUSERNAME:MYPASSWORD@localhost:5984"

Provided that you are using a local instance in port 5984 and MyUsername and MyPassword with  correct credentials, for instance the admin user.


Hope this helps.

**Comment by mbret** [comment]
I am using the latest version to date. I have indeed set up an admin account on both my local and production db and using the same way to connect to both for the client (through a proxy server and authentication). I have yet to find the reason of this weird behavior with the production one. I came to think it has nothing to do with my local pouchdb since even my local app have the same problem as the production one. There must be something different on the server but I am a bit lost at this point. Tomorrow I will try to debug the pouchdb package to debug the sync process and see why it skip the `put` part.

**Comment by dheimoz** [comment]
Hey @mbret is there any firewall in the server? It is strange because it seems Pouchdb is not reaching it.

**Comment by mbret** [comment]
No firewall and I seem to have access to the db since the response is the same as the local db. You can see the headers that come from couch and the response format

![image](https://user-images.githubusercontent.com/1911240/102028891-96b73800-3def-11eb-95a3-5272a824d2a8.png)

![image](https://user-images.githubusercontent.com/1911240/102028894-9dde4600-3def-11eb-8848-22f5e1f8fe96.png)

it just keep looping forever on thoses checkpoint
![image](https://user-images.githubusercontent.com/1911240/102028923-b51d3380-3def-11eb-919e-d7db87f3c4f4.png)

**Comment by mbret** [comment]
I made some digging and it seems that my code end up looping here https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-checkpointer/src/index.js#L193. It will always return 404 and therefore go into that catch and returns `LOWEST_SEQ` which is always 0 I guess.
