### ISSUE TITLE
Custom header not working

### ISSUE THREAD

**Issue by pavellzubkov** [pouchdb/pouchdb#8251]
### Issue
when i try use example from API 

```
var db = new PouchDB('http://example.com/dbname', {
  fetch: function (url, opts) {
    opts.headers.set('X-Some-Special-Header', 'foo');
    return PouchDB.fetch(url, opts);
  }
});
```

i get 

> has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

### Info
- Environment: (browser)
- Platform: (Chrome)
- Adapter: (IndexedDB)
- Server: (CouchDB)

### Reproduce
try to create remote db wih custom header

**Comment by dheimoz** [comment]
hello @pavellzubkov are you using a local Couchdb? provided this is the case, have you enable CORS?
https://docs.couchdb.org/en/3.1.1/config/http.html#httpd/enable_cors

You can do it in Faxuton in Configuration -> Config -> CORS -> Enable CORS
![image](https://user-images.githubusercontent.com/382153/101987968-86228880-3c5c-11eb-8930-dc79df828b90.png)

**Comment by pavellzubkov** [comment]
hi dheimoz ! yes i use local couchdb with enabled cors. when i comment string `opts.headers.set('X-Some-Special-Header', 'foo');`
all works. when i use `opts.headers.set['X-Some-Special-Header']='foo'` all works but header not set

**Comment by pavellzubkov** [comment]
i think it not work when using pouchdb-authentication plugin... i'll try to check

**Comment by pavellzubkov** [comment]
ok. it not problem with pouchdb. couch db reject response with not allowed headers by 'Access-Control-Expose-Headers'...
