### ISSUE TITLE
Remote URL

### ISSUE THREAD

**Issue by niteraven7** [pouchdb/pouchdb#8253]
Quick question, please excuse me if this is in the wrong place. What logic does PouchDB use to determine what is a remote vs local database? I tried looking in the source code but couldn't find it. Does it look for http, https or // ?

I'm trying to sync a remote and local database. Due to a complication with my development environment (google shell) I have to rewrite my request urls and proxy them in Vue.js. Is there a way I can force PouchDB to treat a database to be remote even if I call it '/fake_db_segment/real_db_name'? It thinks I'm trying to create a local database even though that is my remote database url...

Sorry for being difficult!

/not my fault

**Comment by niteraven7** [comment]
I found a way to trick it but seems sub-optimal:

`var remoteUserDB = new PouchDB('https://remote/'+ context.getters.remoteUserDatabaseName, {
				fetch: function (url, opts) {
					opts.credentials = 'include';

					console.log(url, opts);

					return PouchDB.fetch(url.replace('https://remote', '/db'), opts);
				},
				skip_setup: true
			});`

**Comment by marten-de-vries** [comment]
@niteraven7 Just in case you haven't solved this yet, the code that determines which adapter to use can be found in: https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/parseAdapter.js

It seems you should be able to pass in something like {adapter: 'http'} as second argument in your contructor, but I haven't actually tested that.
