### ISSUE TITLE
Broken link in guide

### ISSUE THREAD

**Issue by fozy81** [pouchdb/pouchdb#8259]
### Issue
Link to 'Clear Recent History+' addon no longer working / addon not available. 

### Info / Reproduce
See [working with database](https://pouchdb.com/guides/databases.html#deleting-your-local-database) section in guide. 

### PR
Changed link to different addon which provides similar functionality:
https://github.com/pouchdb/pouchdb/pull/8258/files

**Comment by garethbowen** [comment]
This has been merged.

**Comment by fozy81** [comment]
Hi @garethbowen, I'm not seeing this updated link on the documentation page: 
https://pouchdb.com/guides/databases.html#deleting-your-local-database (link still broken)

:thinking:  Does the documentation need refreshing/re-deploy before this change is visible?

**Comment by garethbowen** [comment]
Yes. The website is updated as part of the product release cycle, so it should happen automatically then.

**Comment by fozy81** [comment]
Thanks for info and for merging, I'll look out for the next release.  :+1:
