### ISSUE TITLE
Getting a document revision fails

### ISSUE THREAD

**Issue by thomascenni** [pouchdb/pouchdb#8264]
### Issue
If have a document called 'config' and I want to get a particular revision, so I'm using:

`db.get('config', options)`

where options is:

```
var options = {
    _rev: "10-d39450e9779d522b4c83a5dc95c03c75",
    revs_info: true,
}
```
(I tried with options.rev as in the documentation, but it doesn't work; it's options._rev)

and the result is (cutting some other fields with no interest):

```
vencimento: "2021-02-07"
_id: "config"
_rev: "12-ca3ba3a317f5792bc441a498a640fcfa"
_revs_info: Array(12)
0: {rev: "12-ca3ba3a317f5792bc441a498a640fcfa", status: "available"}
1: {rev: "11-2cf750cca9e5fc3e80a6e744c8774351", status: "missing"}
2: {rev: "10-d39450e9779d522b4c83a5dc95c03c75", status: "missing"}
3: {rev: "9-b0a860cd1be501f983aacc007de42ca5", status: "missing"}
4: {rev: "8-6d377a05c19e694aefb61260b45860f7", status: "missing"}
5: {rev: "7-63dab8c981ecea4f6e7914a5df9ee32d", status: "missing"}
6: {rev: "6-f8f3f00146bd20d30f8399ac22575bdc", status: "missing"}
7: {rev: "5-89b4c50caed983cb804ec356b14a17d6", status: "missing"}
8: {rev: "4-5e5ac4eda2e56141d9d1bce9d18aff6b", status: "missing"}
9: {rev: "3-91a590562681f9e67272b7e3243c1522", status: "missing"}
10: {rev: "2-40d06493ad253a1200157c8eb753757b", status: "missing"}
11: {rev: "1-2325f9be758f29c9528464455d9c5fd7", status: "missing"}
length: 12
```
The local db has been created with
`var db = new PouchDB('dbname');`

so as per documentation revs_limit is 1000.
The local and remote db are synced with live:true, retry:true, so I don't understand why I am not able to get the revision.
Thanks, any help is really appreciated.

### Info
- Environment: Hybrid app
- Platform: Chrome/Android
- Adapter: IndexedDB
- Server: CouchDB 3.1.0
- PouchDB version 7.2.2

**Comment by janl** [comment]
`revs_limit` only states how many revision IDS are kept. no document bodies other than the latest revision are kept. The revision system is _not_ a revision control mechanism you can use for versioning.
