### ISSUE TITLE
Unexpected $and operator behavior

### ISSUE THREAD

**Issue by cvara** [pouchdb/pouchdb#8265]
### Issue
pouchddb-find's $and operator behaves unexpectedly when combining multiple conditions on the same property using the same operator.

### Example
```javascript
// Trying to fetch docs that contain "bananas" and "apples"
// at the same time inside the "likes" array property.
const { docs } = await db.find({
  selector: {
    $and: [
      {
        likes: { $elemMatch: { $eq: 'bananas' } },
      },
      {
        // 👇 overrides first condition, "bananas" is ignored
        likes: { $elemMatch: { $eq: 'apples' } },
      },
    ],
  },
});
```

### Info
Has been reproduced consistently on browser/js-dom environments over idb/memory adapters using `pouchdb@7.2.2` & `pouchdb-find@7.2.2`

### Reproduce
I've put together a [simple test repo](https://github.com/cvara/pouchdb-find-and-test) showcasing the above behaviour:

1. `git clone git@github.com:cvara/pouchdb-find-and-test.git`
2. `cd pouchdb-find-and-test`
3. `yarn install`
4. `yarn test`

**Comment by DDoerner** [comment]
I was met with the same problem when using multiple $or statements.

### Example
```
const results = await db.find({
  selector: {
    $and: [
      {
        $or: [
          { prop1: { $eq: 'a' } },
          { prop1: { $eq: 'b' } },
        ]
      },
      {
        $or: [
          { prop2: { $eq: 'c' } },
          { prop2: { $eq: 'd' } },
        ]
      }
    ]
  }
})
```

Similarly, the first $or condition was ignored in the resulting data set.

It might be possible that internally the $and array gets reduced to a single object, so the latter statement with the same property key overwrites the first one. I haven't looked at the code however, so it's just an assumption. I also wasn't able to find a workaround yet.

**Comment by andrewmunsell** [comment]
I believe this is related: https://github.com/pouchdb/pouchdb/issues/6264

I confirmed this by stepping through the code with the debugger, the second "$or" will take precedence and completely eliminate the first.

**Comment by dheimoz** [comment]
hey @andrewmunsell would you mind trying a PR?

**Comment by BuXXe** [comment]
I ran into this issue today. Don't have the time to write a PR currently and will postpone my need for the feature. I hope to come back to this problem when my deadlines allow it.

**Comment by kiawin** [comment]
Hi @dheimoz, if it's ok with you, I would like to give it a try this weekend to fix the issue. Thanks :)

**Comment by dheimoz** [comment]
please be my guest @kiawin , thank you.
