### ISSUE TITLE
Pagination of join using view collation

### ISSUE THREAD

**Issue by zacharylawson** [pouchdb/pouchdb#8272]
### Issue
I'm currently using view collation to request all the associated documents in a single request and trying to paginate the response as the requests have begun to timeout due to the db size. For example my `startkey` is `["d-29-"]` and the `endkey` is `["d-29-[]"]` allowing me to fetch the user, folder, comments and doc in one request.

When using the ["Dumb method" mentioned here](https://pouchdb.com/2014/04/14/pagination-strategies-with-pouchdb.html) I'm able to properly paginate all the docs. When I try the suggested ["Smart method" here](https://pouchdb.com/2014/04/14/pagination-strategies-with-pouchdb.html) I'm no longer able to paginate the response.  It seems to just return the same doc set?

I couldn't find any examples of paginating a join view in the excellent documentation. Is this a bug or should I be approaching pagination differently when using view collation? 

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
The view looks similar to the [CouchDB example here](https://docs.couchdb.org/en/stable/ddocs/views/joins.html#optimization-using-the-power-of-view-collation):

```
function(doc) {
    if (doc.type == "post") {
        emit([doc._id, 0], null);
    } else if (doc.type == "comment") {
        emit([doc.post, 1], null);
    }
}
```

**Comment by zacharylawson** [comment]
Found the issue, my mistake.

**Comment by zacharylawson** [comment]
Found the issue, my mistake.

**Comment by dryu99** [comment]
@zacharylawson do you recall how you addressed the issue? I'm experiencing a similar issue right now.
