### ISSUE TITLE
AllDocs slow performances

### ISSUE THREAD

**Issue by dxwts** [pouchdb/pouchdb#8273]
### Issue
I'm use pouchdb sync data from couchbase,  then query data via allDocs method is slow, it takes 6011ms to query 70k(documents count) documents, how to optimization query performance.

### Info
- Environment: browser
- Platform: Chrome/FF/Safari/Edge
- Adapter: IndexedDB
- Server: couchbase server/sync gateway

### Reproduce
use pouchdb sync 100k data from couchbase server, then query data use allDocs method

**Comment by garbados** [comment]
> 6011ms to query 70k (documents count)

How large are your documents? I am able to query against 70k documents in the browser in <1000ms. If your documents are large, it might be that your latency is caused by how much data is moving from disk into memory.

**Comment by dheimoz** [comment]
Hello @dxwts:

Do you have the details asked by @garbados or is it ok to close this issue?

Thanks.
