### ISSUE TITLE
conflicts: true option to allDocs does not seem to work.

### ISSUE THREAD

**Issue by sureshvv** [pouchdb/pouchdb#8275]
### Issue
conflicts: true option to allDocs does not seem to work.

### Info
- Environment: browser
- Platform: Chrome

### Reproduce
Seems to return all the docs regardless of conflicts and _conflicts missing on the rows returned.

**Comment by sleidig** [comment]
You can use a [query](https://pouchdb.com/guides/queries.html) to get all docs with conflicts:

`db.query((doc, emit) => { if (doc._conflicts) { emit(doc) } });`

and to see the actual conflicting document version you then have to get the document with the revision from the `_conflicts` array:

`db.get(conflictDoc._id, { rev: conflictDoc._conflicts[0] })`

**Comment by amazingmarvin** [comment]
I'm using:

```javascript
  const res = db.allDocs({
    include_docs: true,
    conflicts: true,
  });
```

pouchdb 7.1.1 with idb adapter and conflicts work! It returns all rows (not just those with conflicts), and only rows that have conflicts have the _conflicts field. If you're just looking for docs with conflicts, call filter on the returned array (in `res.rows`).

**Comment by sureshvv** [comment]
Is `include_docs` required? I do not want the data for all the documents as there is a large number of them

**Comment by karlwestin** [comment]
Yes `include_docs` is required to see conflicts
In the 2nd example in the place you link they are requesting a single document, that's why they don't need all_docs.

This does not seem to be a bug, so i'm closing this for now. Feel free keep posting here if you have questions. Thanks!

**Comment by sureshvv** [comment]
> (doc, emit) => { if (doc._conflicts) { emit(doc) } });

Temporary views are not supported in CouchDB
