### ISSUE TITLE
2 Way Sync with Filters not working

### ISSUE THREAD

**Issue by lvendramini** [pouchdb/pouchdb#8280]
### Issue
Cannot 2 way sync using a filter.  If the design document has a filter on the server side, but no client side (pouchdb), then it complains that the design document is not found.  If the design document is added to the client side as well, then there is a conflict.

### Info
- Environment: Node.js / hybrid app with angular 11 & electron 
- Platform: Electron or Chrome
- Adapter: LevelDB
- Server: CouchDB

### Reproduce
Within couchdb a design document

{
  "_id": "_design/business-city",
  "_rev": "9-73bca5fc8acd28020622aafd853ea202",
  "filters": {
    "bycity": "function(doc, req){ if (doc.city === 'Richmond Hill' || doc._id === '_design/business-city') return true; else return false }"
  }
}

In our sync service

` PouchDB.plugin(SecurePouch);
  PouchDB.plugin(PouchFind);
  var remoteDB = new PouchDB(this.couchDbUrl + 'business');
  var localDb = new PouchDB('.db/business.db');

 remoteDB.sync(localDb, {
      filter: 'business-city/bycity'
    })
      .on('change', function (result) {
        console.log("data changed! " + result);

      })
      .on('error', function (err) {
        debugger
        **console.log("Sync failed for business!  " + err.name + " " + err)** //--> lands here with 'not found' if not in pouch db, or 'conflict' if in couch db and pouch db
        if (err.name === 'conflict') {

        } else {
          // some other error
        }
        reject(false)
      })
      .on('complete', function (info) {

        console.log("Sync is successful for business!")
        resolve(true)
      });
`

**Comment by amazingmarvin** [comment]
I have a similar setup that's working. For sure you need the design document locally and on the server (or else you get `not_found`).  I avoided a conflict by not syncing design documents up or down, but rather just creating the design document on the client if necessary. In fact, I have a different design document on the client than on the server, (this lets me have different data syncing up than down, which happens to be useful in my use case).

Here's my code:

```javascript
      let designDoc;
      try {
        designDoc = await currentDB.get("_design/app");
      } catch (err) { // eslint-disable-line
        // Expected not_found: missing Error
      }

      if (!designDoc) {
          await currentDB.put({
            _id: "_design/app",
            _rev: designDoc._rev,
            filters: {
              example: "function(doc) { return doc._id[0] !== '_'; }"
            },
          });
      }
```

and the design doc on the server has `doc._id[0] !== "_"` in addition to other checks.

**Comment by dheimoz** [comment]
Hello @lvendramini  I wonder if the fantastic solution provided by @amazingmarvin worked the way you needed.

Thanks.
