### ISSUE TITLE
Adapter-specific document purge

### ISSUE THREAD

**Issue by amazingmarvin** [pouchdb/pouchdb#8282]
### Issue
I am having a problem with an ever-growing database (of tasks). I have successfully setup archiving old tasks so that a server-side filter prevents them from syncing down, but this only helps for fresh syncs. Why not just leave them? It causes slow slow startup performance since I need to call allDocs on startup (on the phone app 😅). I could destroy the database and force the client to re-sync, but this takes a while (especially on the phone app 😅)! Would it be possible to instead just use the native browser IDB API to delete all revisions of documents that have been archived?

I believe it would need to be deleted in:

* by-sequence (and _doc_id_rev index)
* document-store (and deletedOrLocal index)

Do you know of anything that could prevent such a devious plan from working? The first thing that jumps out at me as a potential problem is that it would generate holes in the sequence, in by-sequence. I haven't looked into the idb code yet to reason if that would be an issue.

This seems like a generally useful feature for IDB users. Could this be merged in as an IDB-only extension?

And I guess in my case on mobile this would have to be done using react-native-sqlite-2, but something similar should be possible there as well, I guess.

### Info
- Environment: browser/react native with IDB
- Platform: Browser/react native
- Adapter: IndexedDB
- Server: Cloudant

### Reproduce
There's no bug here.

**Comment by dheimoz** [comment]
Hey @amazingmarvin , great idea you are implementing. So far, the only way that I found to permanently delete documents is to perform a replication of not deleted documents. I have followed a process similar like these:

https://eclipsesource.com/blogs/2015/04/20/how-to-finally-delete-documents-in-couchdb/

As you are using Cloudant I suggest you to schedule a monthly or weekly purge.

Hope this helps.
