### ISSUE TITLE
indexed_db_went_bad 

### ISSUE THREAD

**Issue by pejman1** [pouchdb/pouchdb#8284]
### Issue
randomly  specially by closing and lunching the app fast, pouchdb throws this errors and app crashes 
  Internal error opening backing store for indexedDB.open. (pouchdb-browser/lib/index.es.js)
err form pouchdb e {status: 500, name: "indexed_db_went_bad", message: "unknown", error: true, reason: "Internal error opening backing store for indexedDB.open."}  (pouchdb-utils)
it is really critical issue which has not been fix yet

### Info
- Environment: Electron version 12
- Platform: (Windows 10)
- Adapter: (IndexedDB / idb)
- Server: (CouchDB v 3.1.1)
- Pouchdb 7.2.2
### Reproduce

I replicate db from couchdb to pouchdb in my app.  this error happens randomly . specially when I open and close the app fast more than 3 or 4 times .

**Comment by dheimoz** [comment]
hello @pejman1 

Reading that this is Electron ver 12 I have a couple of questions:

1) Cold start (when Pouchdb is empty) works as expected?
2) Have you tried another adapter?
3) What you consider fast? Open and closing the desktop app 5 times within a minute and after the fifth the error is shown?

**Comment by pejman1** [comment]
> hello @pejman1
> 
> Reading that this is Electron ver 12 I have a couple of questions:
> 
> 1. Cold start (when Pouchdb is empty) works as expected?

> 2. Have you tried another adapter?
> 3. What you consider fast? Open and closing the desktop app 5 times within a minute and after the fifth the error is shown?

I use idp adaptor  

I found the main reason. when we launch to instance of the electron app. the second one crashes and indexeddb throws the error. in my application I use  gotTheLock = app.requestSingleInstanceLock(); to prevent launching second instance but in some cases 
when I close the application and run it again fast the previous one has not completely closed and it causes this issue. to sum up, I should consider pouch db crashes while we run to instance of one applicaiton together.

**Comment by dheimoz** [comment]
Hey @pejman1 thanks for the follow up. Makes perfect sense. 
How much information is replicated from Couchdb? More than 10 MB?

Assuming you are using replication, maybe it could work cancelling the replication before closing the application:
https://pouchdb.com/guides/replication.html#canceling%E2%80%94replication

**Comment by pejman1** [comment]
it is about

> Hey @pejman1 thanks for the follow up. Makes perfect sense.
> How much information is replicated from Couchdb? More than 10 MB?
> 
> Assuming you are using replication, maybe it could work cancelling the replication before closing the application:
> https://pouchdb.com/guides/replication.html#canceling%E2%80%94replication

It is about 5 MB with 100 recored with attachments . 
it does not related to replication. I just fetch data from db after launching the app . Even if I cancel the replication it throws this error when I launch two instance of the app
