### ISSUE TITLE
Support for partitioned databases?

### ISSUE THREAD

**Issue by NBroomfield** [pouchdb/pouchdb#8285]
### Issue
I'm trying to work out if pouch db supports partitioned databases as per the couchdb spec https://docs.couchdb.org/en/stable/partitioned-dbs/index.html and what this would entail?

### Info
- Environment: hybrid app
- Platform: Ionic PWA (Chrome, iOS, Android)
- Adapter: Na
- Server: CouchDB

**Comment by dheimoz** [comment]
Hello @NBroomfield , what is your use case? I have been using Couchdb 3.X and Cloudant both with partitioned databases and PouchDB syncs and replicates just fine. Are you looking into some specific feature of partitioned DB's?

Thanks.

**Comment by NBroomfield** [comment]
@dheimoz that's good to hear thanks, no particular specific feature, I just need to sync to a couchdb partitioned DB, I searched the code but couldn't see any reference to "partitioned", I guess the only thing that may be of concern is if the dB didn't already exist and pouchdb tried to create it but didn't pass the query parameter partitioned=true.

**Comment by dheimoz** [comment]
@NBroomfield then use the "skip_setup" flag. That way the database is not created.
https://pouchdb.com/api.html
Options for remote databases

This even increase performance initialization at first run.

**Comment by NBroomfield** [comment]
Thanks, that looks great.
