### ISSUE TITLE
SvelteKit Support?

### ISSUE THREAD

**Issue by RobertoOrtis** [pouchdb/pouchdb#8286]
Hello,

I am wondering if SvelteKit will be supported. I just migrated from sapper to sveltekit and pouchdb is broken.

**Comment by hangtwenty** [comment]
@RobertoOrtis I'm interested in this issue, thank you for opening it. But, it does not follow pouchdb's issue template, namely how to reproduce:

> ### Reproduce
> Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
> live example of the bug @ https://pouchdb-bug-helper.glitch.me/

It would be **awesome** if you could reproduce it [with that helper, which is on glitch, so it is in-browser](https://pouchdb-bug-helper.glitch.me/), and then share it here.

**Comment by hangtwenty** [comment]
Question: **Have you checked your `src/lib` to confirm you still have `pouchdb`?** ([sveltekit migration docs](https://kit.svelte.dev/migrating))

**Comment by hangtwenty** [comment]
If reproducing is not an option, here are some other questions:

* Do you have enough information to tell if this is is really `pouchdb`'s issue -- vs `sveltekit` or `vite`? (I'm inclined to think it would be an issue with the migration from `rollup` to `vite`)
    * If you paste some error information, it would help us answer this question
* When you [followed the Sapper to SvelteKit migrations documents](https://kit.svelte.dev/migrating), which steps did you follow?
    * `package.json`: _"Add `"type": "module"` to your package.json"_
    * dependencies: _"Remove polka or express, if you're using one of those, and any middleware such as sirv or compression."_
    * devDependencies / Configuration: _"Remove sapper from your devDependencies and replace it with @sveltejs/kit, vite, and whichever you plan to use"_ — did anything change about `pouchdb` when you switched from `rollup` to `vite`? (were you doing `pouchdb` related build steps?)
   * `vite` requires you to migrate from `src/node_modules` to [`src/lib`](https://kit.svelte.dev/docs#modules-lib). If you have not completed this migration, maybe you are just missing `pouchdb` as a dependency? **Can you double-check that `pouchdb` is in your `src/lib`?**
   * [`preload` renamed to `load`](https://kit.svelte.dev/migrating#pages-and-layouts-preload) - did you apply this change?
   * Svelte stores: anything of note here? Were you using pouchdb together with svelte stores?

ℹ️  While these are sveltekit-specific questions, I'm posting them here in case it helps triage the issue. In the process, we might identify a caveat to `pouchdb`'s compatibility with `vite`, or another interesting finding. Else, we might find this is not a `pouchdb` issue.

**Comment by hangtwenty** [comment]
Last note for now: if anybody wants to take a crack at [making an official sveltekit integration for pouchdb](https://github.com/sveltejs/integrations#sveltekit), that would be awesome. I may do so myself but first I need to get more familiar with PouchDB.

**Comment by hangtwenty** [comment]
I'm leaning towards this being an issue from `vite` specifically, because of https://github.com/pouchdb/pouchdb/issues/8266

**Comment by hangtwenty** [comment]
Community links that may be of use:

* [ViteJS chat](https://chat.vitejs.dev/) 
* Svelte chat; [here is the link from svelte.dev site](https://discord.com/invite/yy75DKs). Plus, [svelte topic on dev.to](https://dev.to/t/svelte)

**Comment by gevera** [comment]
Any progress on this? I believe that PouchDB and SvelteKit are a perfect match for offline-first webapps.

**Comment by CodeDoes** [comment]
It worked when I used the following `import PouchDB from "pouchdb/dist/pouchdb.js";`

**Comment by fredguth** [comment]
If you have problems with `global` or `process`, you can just add them in your `svelte.config.js`.  This is what I did and worked:
```svelte.config.js
import adapter from '@sveltejs/adapter-auto';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		adapter: adapter(),
		vite: {
			define: {
				global: 'window',
				process: { env: {} }
			}
		}
	}
};

export default config;
```

**Comment by matfire** [comment]
> If you have problems with `global` or `process`, you can just add them in your `svelte.config.js`. This is what I did and worked:
> 
> ```js
> import adapter from '@sveltejs/adapter-auto';
> import preprocess from 'svelte-preprocess';
> 
> /** @type {import('@sveltejs/kit').Config} */
> const config = {
> 	// Consult https://github.com/sveltejs/svelte-preprocess
> 	// for more information about preprocessors
> 	preprocess: preprocess(),
> 
> 	kit: {
> 		adapter: adapter(),
> 		vite: {
> 			define: {
> 				global: 'window',
> 				process: { env: {} }
> 			}
> 		}
> 	}
> };
> 
> export default config;
> ```

This no longer works, unfortunately; sveltekit no longer supports these parameters in their config file, and putting them in the vite config breaks other stuff (lucia, in my case)
