### ISSUE TITLE
PouchDB don't work with a custom CA

### ISSUE THREAD

**Issue by ebanDev** [pouchdb/pouchdb#8289]
### Issue
Hi, I tried to use PouchDB (with React Native) to connect to my db, my CouchDB is behind an nginx reverse proxy with a custom CA, when I try to replicate from the db I get this error 
![Error](https://user-images.githubusercontent.com/57091497/114390886-159e6080-9b97-11eb-8264-8d2d7abbdc25.png).
I tried to fix with [this](https://github.com/pouchdb/pouchdb/issues/3504) solution :
```js
var remoteHabits = new PouchDB('https://url/', {
  ajax: {
    rejectUnauthorized: false,
    requestCert: true,
    agent: false
  }
})
```
But I still get the same error :/ I tried in plain HTTP and it works...

### Info
- Environment: React Native
- Platform: Android
- Server: CouchDB

Thanks :)

**Comment by dheimoz** [comment]
hey @ebanDev 

I wonder if you are still facing the same problem?

**Comment by ebanDev** [comment]
Hi, I'm not able to try to reproduce the issue for now... Sorry :/

**Comment by dheimoz** [comment]
Understood @ebanDev, do you want to keep the issue open?

**Comment by ebanDev** [comment]
I don't think so
