### ISSUE TITLE
Add Doc id/ current keys to the error message of a failing map reduce function

### ISSUE THREAD

**Issue by paolosanchi** [pouchdb/pouchdb#8291]
### Issue
When a map/reduce function throws an error, the function name and the doc which caused the error are not provided with the error, making very hard to spot what caused the issue.

I get this error: (please, ignore console-log-viewer.js, it's a log wrapper I use)
```
console-log-viewer.js:158 The user's map/reduce function threw an uncaught error.
You can debug this error by doing:
myDatabase.on('error', function (err) { debugger; });
Please double-check your map/reduce function.
```
and from `myDatabase.on('error', function (err) { debugger; });`
```
console-log-viewer.js:158 TypeError: Cannot read property '' of null
    at searchEmitRecursive (eval at scopeEval (index-browser.es.js:868), <anonymous>:20:52)
    at searchEmitRecursive (eval at scopeEval (index-browser.es.js:868), <anonymous>:28:41)
    at searchEmit (eval at scopeEval (index-browser.es.js:868), <anonymous>:13:33)
    at eval (eval at scopeEval (index-browser.es.js:868), <anonymous>:69:29)
    at tryMap (index-browser.es.js:7973)
    at createDocIdsToChangesAndEmits (index-browser.es.js:8427)
    at processBatch (index-browser.es.js:8410)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:28301)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:28289)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
```
When the error is rethrown there is the document, or the keys involved. It could be a good idea to attach them to the comment. 
This wouldn't affect performance, since it's a point where this seems important. The function which caused the problem could be spotted easily activating the debug mode, or with a custom log before the command, so the doc id should be enough for further  analisys.

https://github.com/pouchdb/pouchdb/blob/c3f066930c62045783e7c0f51f9cfb690104d595/packages/node_modules/pouchdb-abstract-mapreduce/src/index.js#L98
https://github.com/pouchdb/pouchdb/blob/c3f066930c62045783e7c0f51f9cfb690104d595/packages/node_modules/pouchdb-abstract-mapreduce/src/index.js#L110

### Info
- Environment: (browser)
- Platform: (Chrome)
- Adapter: (IndexedDB)
- Server: (CouchDB)

### Reproduce
Create a map/reduce function which throws an error

**Comment by seigel** [comment]
Enhancement request?

**Comment by paolosanchi** [comment]
> Enhancement request?

I think so, it's a simple change that can help in scoping the problems

**Comment by dheimoz** [comment]
PR's are always welcome.

**Comment by seigel** [comment]
@paolosanchi Just wondering if you ever were able to get a patch together for that.

**Comment by paolosanchi** [comment]
@seigel Sure, I can make a base wording, so someone can fix it in case. I had some work to do and completely forgot about this, sorry. I'll make a fix as soon as possible

**Comment by paolosanchi** [comment]
I'm looking into this, actually you can get the problematic document/function with the debugger: you can reach the tryMap() call in the stack and check the local variables.
The problem is that if it happen with production data, you have to get that data first, copy to a debug env and debug it. Not the ideal scenario.
I use sentry to track the production error (I think many of us use something similar), and i can get the data thrown by the errors.

Because of this my proposal is the following:

```
  function tryMap(db, fun, doc) {
    // emit an event if there was an error thrown by a map function.
    // putting try/catches in a single function also avoids deoptimizations.
    try {
      fun(doc);
    } catch (e) {
      emitError(db, e, {fun: fun, doc: doc});
    }
  }

  function tryReduce(db, fun, keys, values, rereduce) {
    // same as above, but returning the result or an error. there are two separate
    // functions to avoid extra memory allocations since the tryCode() case is used
    // for custom map functions (common) vs this function, which is only used for
    // custom reduce functions (rare)
    try {
      return {output : fun(keys, values, rereduce)};
    } catch (e) {
      emitError(db, e, {fun: fun, keys: keys, values: values, rereduce: rereduce});
      return {error: e};
    }
  }

function emitError(db, e, data) {
  try {
    db.emit('error', e);
  } catch (err) {
    guardedConsole('error',
      'The user\'s map/reduce function threw an uncaught error.\n' +
      'You can debug this error by doing:\n' +
      'myDatabase.on(\'error\', function (err) { debugger; });\n' +
      'Please double-check your map/reduce function.');
    guardedConsole('error', e, data);
  }
}
```

this way the data are attached to the console (and sent to sentry in my case).
A new object is created with a very little memory usage, but error should not happen, especially here.
If the doc or func is big, the console can receive a big amount of data, but this should't be a problem.

What do you think? I'd like to have a feedback before doing the commit
