### ISSUE TITLE
Electron with Pouchdb [Level Db ] insert error

### ISSUE THREAD

**Issue by Dinesh101041** [pouchdb/pouchdb#8296]
### Issue
not a  issue just a  question on pouchdb with leveldb in electron 
full question link  :  https://stackoverflow.com/questions/67472024/electron-with-pouchdb-level-db-insert-error

### Info
- Environment: (Node.js - electron js)
- Platform: (Chrome.)
- Adapter: (LevelDB)

can any one help me with the answer for the question

**Comment by dheimoz** [comment]
hello @Dinesh101041 , have you sorted out the problem? If so, do you mind sharing the solution?
Thanks.

**Comment by Dinesh101041** [comment]
Sure here is the link of Solution sir
[code](https://stackoverflow.com/questions/67472024/update-drop-down-with-javascript)

**Comment by dheimoz** [comment]
thanks
