### ISSUE TITLE
Browser<->browser sync without a server

### ISSUE THREAD

**Issue by deepmouse** [pouchdb/pouchdb#8297]
This seems highly doable, and might not even be that much work!

- WebRTC allows two browsers to connect to each other and send data without a server in between
- p2p networks that allow browsers to find each other in order to establish a WebRTC connection already exist: https://gun.eco/ (so no need to install a server if you don't want, you can use someone elses)
- if direct connection between browsers fail, the data can be synced indirectly through peers on the p2p network (you could e2e encrypt your data with WebCrypto if it's sensitive, of course)

**Comment by deepmouse** [comment]
Other links relating to serverless data transfer over IP:

https://holochain.org/
https://hypercore-protocol.org/

**Comment by deepmouse** [comment]
Advantages:

- users can sync app data between devices even when the central backend is down
- same thing goes for if your cloud provider has an outage
- using p2p network for data sync can reduce server costs
- can write apps that persist data over IP without ever setting up, configuring or maintaining your own database server

**Comment by dheimoz** [comment]
Intriguing, thanks for the idea @deepmouse 

What do you think about this @garbados ?

**Comment by garbados** [comment]
Practically speaking, we're talking about adding new adapters. Imagine this code snippet that replicates between a hypercore and a CouchDB installation:

```javascript
PouchDB.replicate('hypercore://[key]', 'http://[user]:[pass]@localhost:5984/my-db')
```

Internally, PouchDB would try and use a hypercore adapter to read the entries stored in its log, and then send them to the indicated CouchDB installation. If you add a `hypercore` adapter, PouchDB will [automatically](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/parseAdapter.js#L5-L12) associate it with `hypercore://` addresses.

P2P technologies often have specific environmental requirements, like access to networking capabilities that aren't available in browsers without a lot of tooling, or require bundling software that could have a significant impact on the size of PouchDB in its transpiled form. For this reason I'd recommend writing protocol-specific adapter plugins that you might use like this:

```javascript
PouchDB.plugin(require('your-hypercore-plugin'))
```

Then you can include these adapters in your application as needed.

I would not recommend bundling such adapters into PouchDB itself at this time, as the P2P protocol ecosystem is... very chaotic.

**Comment by garbados** [comment]
@RangerMauve wrote [pouchdb-adapter-hyperbee](https://github.com/RangerMauve/pouchdb-adapter-hyperbee), a great example P2P adapter plugin. It allows you to use `hyper://` addresses, though hypercore archives [can only have one writer](https://github.com/hypercore-protocol/hyperbee/issues/27#issue-823522019) which means that if you aren't the author of a hypercore archive, write methods like `.put()` will fail. (It is possible to instrument [multi-writer hypercores](https://github.com/kappa-db/multifeed) but the tooling for it is a bit limited at the moment.)

If you'd like to try writing some P2P protocol adapters, I'd recommend starting with that example :)

**Comment by garbados** [comment]
In my experience, mapping objects like distributed log entries to PouchDB documents requires asserting [some opinions](https://github.com/garbados/pouchdb-hypercore/blob/master/index.js#L14-L18). This makes it hard to say that there is one correct way to do that mapping, which makes this problem perfect for plugin developers to handle as they have the freedom to form and apply those opinions.

**Comment by dheimoz** [comment]
Great insights as always Diana @garbados , your feedback is greatly appreciated.
What do you think @deepmouse ?

**Comment by deepmouse** [comment]
P2P protocol ecosystem being chaotic, I am not sure what that means. There's plenty of choices out there that are stable, and even if they move fast, the support can be pinned to a stable version that is known to work.

Regarding bundle size, some of these implementations are only a few kB, which would not be much compared to the bundle size of PouchDB itself. Alternatively, PouchDB could include its own adapter that talks to the P2P network without any external code introduced as a dependency. Of course, if the P2P adapter is not used, it's 0 bytes.

Regarding reliability of P2P networks:
- You can run your own P2P node if you want. You would be in as much control of it as a regular database server
- You don't have to choose between P2P and central server. You can mix and match, use central server and fall back to P2P if it goes down or vice versa.
- If you cannot run your own P2P node or your own central server, right now you cannot share data between devices at all. Even in the worst case scenario of P2P connection not being reliable, a non-reliable way of sharing data is preferable to not being able to share data at all.

Many people have implemented various adapters for different databases that demonstrate how P2P sync works. The problem is, as long as they are not officially supported, they tend to break or the author moves on to other projects, leaving it abandoned. Very different from a first-party support that "just works" because it is supported.

Obviously it's the choice of the main contributors to PouchDB to decide whether to include a browser<->browser sync strategy and if so, how to do it. The value for app authors and users is clearly there, and it seems that all the building blocks are ready. It's just a matter of putting them together. Might not be PouchDB today, but I bet this functionality will be soon in many databases as offline-first becomes bigger, people are getting skeptical about hosting everything on big cloud providers and are worried about data privacy.

**Comment by deepmouse** [comment]
Also, I am not quite sure what was meant by "having to be opinionated". The P2P protocol would be only responsible for establishing the connection between two browsers. Whatever goes through that connection would be up to PouchDB

**Comment by dheimoz** [comment]
Hey @deepmouse 
Thank you very much for taking the time to document this. All of us are learning and obviously, can't say we know everything.
I do appreciate your input. 
Pouchdb is planning a major release and hope that this kind of ideas could improve the technology.
I have to be very honest with you, this would not be easy or fast. We must have a realistic expectation, maybe this will be scrapped, but taken into account.
Cheers.

**Comment by drewschu** [comment]
@deepmouse Have you found a solution to this?

**Comment by antris** [comment]
Nope, I've moved on from this problem. But would be cool to see p2p syncing :)

**Comment by deepmouse** [comment]
Nope, I've moved on. But would be cool to see this implemented nonetheless :)
