### ISSUE TITLE
PouchDB stops synching to CouchDB

### ISSUE THREAD

**Issue by daflodedeing** [pouchdb/pouchdb#8298]
### Issue
We have built a pwa with Angular using a service worker. As our users must be able to enter data even when there are offline we decided to use PouchDB in the browser and CouchDb as a database on the server side to synchronize our data to it.

From time to time it happens that the client (browser with PouchDB) does not synchronize its data anymore to CouchDB.

We observed that when everything works we see _revs_diff, _bulk_docs, _changes requests in the network tab (part of replication protocol).

When no data is synchronized (we are online) the request are not even made but the data was put into IndexedDB.

Worth to mention are also two things:

- we changed the style for the _changes request that PouchDB makes from "all_docs" to "main_only"
- sometimes it happens that synchronization does not work for days and then it works again for some time

### Info
- Environment: PWA built with Angular using a service worker
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
Unfortunately, we cannot reliable reproduce the issue. If we can I will immediately provide the needed steps.

**Comment by daflodedeing** [comment]
Additional remark:

When we delete the IndexedDBs created by PouchDB the data gets synchronized again from CouchDB to PouchDB. 

(Of course that's not a solution for us in production environment)

I also stumbled across that issue https://github.com/pouchdb/pouchdb/issues/7098. 
Maybe IndexedDB is somehow damaged and PouchDB cannot read data from it anymore and thus cannot repliate to CouchDB anymore.

**Comment by dheimoz** [comment]
Hello @daflodedeing I suggest you to check "Customizing retry replication" that is part of the options either Replicating or Syncing:
https://pouchdb.com/api.html#replication

I have been using this Options so far with stable results:
```js
const syncOptions = {
  batch_size: 5,
  batches_limit: 2,
  live: true,
  retry: true,
  back_off_function(delay) {
    if (delay === 27000 || delay === 0) {
      return 1000;
    }
    return delay * 3;
  },
};
```

**Comment by daflodedeing** [comment]
@dheimoz Thanks for the hint - will try that as soon as possible.

Another information I can provide:

When I export the data stored in IndexedDB by PouchDB (using these snippets https://gist.github.com/loilo/ed43739361ec718129a15ae5d531095b) from the client (Chrome Browser) that does not sync anymore and import it onto my machine, PouchDB cannot load all documents:

I debugged into the sources of PouchDB and observed the following:

- from IndexedDB everything could be loaded. I had a look at the following piece of code of PouchDB:
` function onGetAll(e) {
    valuesBatch = e.target.result;
    if (keysBatch) {
      onBatch(keysBatch, valuesBatch, pseudoCursor);
    }
  }`

  'e.target.result' contained everything.

- but calling _allDocs on PouchDB "dropped" some documents

Maybe that informations helps. Unfortunately, I cannot provide the data here as it is production data, I am looking forward to provide sample data.

**Comment by sureshvv** [comment]
This is now happening to me with Chrome version 91. It appears that some particular document is the culprit. Any way I can locate the particular document?

**Comment by sureshvv** [comment]
@dheimoz 3.1.1 Thank you. Will look into it. Have you been able to find a solution for your problem?

**Comment by dheimoz** [comment]
Hey @sureshvv 

I wonder if there is a possibility to share the Database. Else the only option that I see is to use the Changes endpoint to narrow down.

Another option that I can think of, is to create a filtered replication to have only the "live" documents (this replication needs to happen in Couchdb, then you will have the original Database and the filtered Database)
https://eclipsesource.com/blogs/2015/04/20/how-to-finally-delete-documents-in-couchdb/#:~:text=%20How%20to%20finally%20delete%20documents%20in%20CouchDB,different%20approach%20to%20get%20rid%20of...%20More%20

And then replicate the Filtered Database to Pouchdb.

Last option is to review the conflicts that the original Database has.

**Comment by sureshvv** [comment]
@dheimoz Actually I did a purge thinking it may be because of a whole bunch of deleted documents that I had as a first step to try to solve this problem.

So I don't think it is deleted documents.

I also deleted localstorage from the chrome settings to reload the documents.

But I found one strange thing. Even after I deleted localstorage, it seems some of the old ids were showing up when I ran allDocs(). As if pouchdb was using a stale cache. Have run out of ideas at this point.

But will pursue the changes feed route.

**Comment by daflodedeing** [comment]
Hey guy, I discovered that a proxy from us between PouchDB and CouchDB refused the following request and return 403 and "Forbidden" in its body:

https://docs.couchdb.org/en/stable/api/local.html#db-local-id

If I tell the proxy to pass the request, it is synchronizing again.

I was able to see the problem with:

https://github.com/pouchdb/pouchdb#readme

But still I am not 100% percent sure if the problem described above is the root cause; on the other side I had no error messages related to IndexedDB.

@sureshvv Have you discovered the document that causes the problems? I am really interested in your issue as maybe I have the same.

**Comment by sureshvv** [comment]
@dheimoz I pursued the changes feed but the last_seq that showed up in my replicate (with batch_size=1, batches_limit=1) never showed up in my changes feed (limit=1).

So am back to square 1.

**Comment by sureshvv** [comment]
I tried using pouchdb-dump/load but same problem seems to persist.

**Comment by daflodedeing** [comment]
But how can you use pouchdb-dump to export data from IndexedDB?

**Comment by sureshvv** [comment]
Actually I am using https://github.com/pouchdb-community/pouchdb-replication-stream

Was not aware of the limitation of pouchdb-load.

Think replication-stream works with IndexedDB also.

**Comment by sureshvv** [comment]
Still fighting with this problem. 

Is there any extra data pertaining to indexes in the replicated database? Could that be causing the issue? I deleted all the design docs on the couchdb side and removed the create index calls to see if that would help. But has not made a difference.

**Comment by sureshvv** [comment]
Thanks to this presumptuous poster

https://github.com/pouchdb/pouchdb/issues/7100

I was able to get the replication working.

I changed auto_compaction: true to revs_liimit: 1

Not sure of any other repercussions of this.

**Comment by dheimoz** [comment]
hey @sureshvv . Auto compactation will make sure to get rid of rev leaves not needed. However, rev_limit to 1 defeats the purpose of replication. Essentially you will work with only the latest revision.

I do not know if that is what you are looking for. Any chance to share your db?

**Comment by sureshvv** [comment]
Will a later version from the server be able to update the local db with revs_limit: 1? If so that is enough replication for me. le t
Can you give me an instance of replication that will not work correctly with revs_limit: 1?

I can always reopen the database once replication is complete with auto_compaction instead.

Unfortunately it is medical data. So cannot share db. But not doing anything special.

**Comment by dheimoz** [comment]
The main problem you will face is conflicts. That will happen when 2 people work with the very same document at the same time. In essence you might lose data.
In the event that documents are not shared or processed by more than one individual, you are good to go.

We can keep the issue open to monitor your experience.

Every now and then take a look at your conflicts
https://docs.couchdb.org/en/stable/replication/conflicts.html
https://www.blog4js.com/2020/01/25/couchdb-document-conflicts/

Just to make sure you are not losing information.

**Comment by sureshvv** [comment]
May be I should make it revs_limit: 2. Default is 1000 I think.

A lot of time was spent by pouchdb churning mid way thru the replication (the violation success handler took xxx ms messages).

Will monitor my conflicts closely.

**Comment by sureshvv** [comment]
I just found out about this:

`PouchDB.debug.enable('*');`

Would have been useful a week ago.

**Comment by sureshvv** [comment]
It has been about 10 days with my change of revs_limit: 1

> The main problem you will face is conflicts. 

Yes. Seems like a lot more conflicts. Which I am resolving automatically picking the default winning revision.

> 
> Just to make sure you are not losing information. 

Thankfully no loss of data except for 1 case. But looking good so far
.

**Comment by dheimoz** [comment]
Hey @sureshvv 
Thanks for follow up.

how many conflicts have you seen by document? I assume that depends on how many users work with the same document.
