### ISSUE TITLE
Table with pouch DB

### ISSUE THREAD

**Issue by Dinesh101041** [pouchdb/pouchdb#8299]
Not a issue a small doubt 
My question is how to insert the html table data into pouch db database and retrieve it  

Here is my html code 
```
<div>                 
  <input type="date" name="Date" id="Expdate"> 

    <table id="customers">
        <tbody id="mytbody">
            <tr>                                  
                <th>Descritption</th> 
                <th>Investment</th>
                <th>Expenses</th>                                                                
            </tr>
            <tr>
                <td><input type="text" name="yourname" /> </td> 
                <td><input type="number" name="yourname" /></td>
                <td><input type="number" name="yourname" /></td>                                   
            </tr>
            <tr>
                <td><input type="text" name="yourname" /> </td> 
                <td><input type="number" name="yourname" /></td>
                <td><input type="number" name="yourname" /></td>                                   
            </tr>    
        </tbody>
    </table>
    
  <input type="button" id="save" value ="save" name="save" onclick="day()">
</div>
```

 JavaScript code 
```
var PouchDB = require("pouchdb");
var db = new PouchDB("DB/Expense", { adapter: "leveldb" });
console.log("Database created Successfully.");

function day(){
    var table = document.getElementById('customers');
    var getdate = document.getElementById('Expdate').value;
    for (var i = 1; i < table.rows.length; i++) {
        Description = table.rows[i].cells[0].firstChild.value,
        Investment = table.rows[i].cells[1].firstChild.value,
        Expenses = table.rows[i].cells[2].firstChild.value,
        
        console.log(Description)
        console.log(Investment)
        console.log(Expenses)
 
    }
}
```
I got all values from table but i am stuck with inserting into database and i want insert this all data based on date  and retrieve it based on date

can any one help me with a code
here is a Reproduce link of html and js code
[code](https://html-css-js.com/?html=%3Cdiv%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%3Cinput%20type=%22date%22%20name=%22Date%22%20i$*$d=%22Expdate%22%3E%20%0A%0A%20%20%20%20%3Ctable%20i$*$d=%22customers%22%3E%0A%20%20%20%20%20%20%20%20%3Ctbody%20i$*$d=%22mytbody%22%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cth%3EDescritption%3C/th%3E%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cth%3EInvestment%3C/th%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cth%3EExpenses%3C/th%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C/tr%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%3Cinput%20type=%22text%22%20name=%22yourname%22%20/%3E%20%3C/td%3E%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%3Cinput%20type=%22number%22%20name=%22yourname%22%20/%3E%3C/td%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%3Cinput%20type=%22number%22%20name=%22yourname%22%20/%3E%3C/td%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C/tr%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%3Cinput%20type=%22text%22%20name=%22yourname%22%20/%3E%20%3C/td%3E%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%3Cinput%20type=%22number%22%20name=%22yourname%22%20/%3E%3C/td%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%3Cinput%20type=%22number%22%20name=%22yourname%22%20/%3E%3C/td%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C/tr%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%3C/tbody%3E%0A%20%20%20%20%3C/table%3E%0A%20%20%20%20%0A%20%20%0A%0A%20%20%3Cinput%20type=%22button%22%20i$*$d=%22save%22%20value%20=%22save%22%20name=%22save%22%20onclick=%22day()%22%3E%0A%20%20%0A%3C/div%3E&css=%20%20table,%20th,%20td%20%7B%0A%20%20%20%20%20%20border:%201px%20soli$*$d%20black;%0A%20%20%20%20%20%20border-collapse:%20collapse;%0A%20%20%20%20%7D%0A%20%20%20%20input%7B%0A%20%20%20%20%20%20border:%20none;%0A%20%20%20%20%7D&js=function%20day()%7B%0A%20%20%20%20var%20table%20=%20document.getElementById(%27customers%27);%0A%20%20%20%20var%20getdate%20=%20document.getElementById(%27Expdate%27).value;%0A%20%20%20%20for%20(var%20i%20=%201;%20i%20%3C%20table.rows.length;%20i++)%20%7B%0A%20%20%20%20%20%20%20%20Description%20=%20table.rows%5Bi%5D.cells%5B0%5D.firstChild.value,%0A%20%20%20%20%20%20%20%20Investment%20=%20table.rows%5Bi%5D.cells%5B1%5D.firstChild.value,%0A%20%20%20%20%20%20%20%20Expenses%20=%20table.rows%5Bi%5D.cells%5B2%5D.firstChild.value,%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20console.log(Description)%0A%20%20%20%20%20%20%20%20console.log(Investment)%0A%20%20%20%20%20%20%20%20console.log(Expenses)%0A%20%0A%20%20%20%20%7D%0A%7D)

### Info
- Environment: (Node.js/javascript)
- Platform: (Chrome)
- Adapter: (LevelDB)

**Comment by dheimoz** [comment]
hey @Dinesh101041 thanks for giving a try Pouchdb.

Have you seen the basic tutorial?
https://pouchdb.com/getting-started.html

I suggest you start with that in order to understand the concepts.

**Comment by Dinesh101041** [comment]
yes i seen doubt cleared thank you i am closing this issue
