### ISSUE TITLE
Uncaught DOMException: Failed to execute 'index' on 'IDBObjectStore': The transaction has finished. at IDBRequest.S.m.onerror 

### ISSUE THREAD

**Issue by sureshvv** [pouchdb/pouchdb#8302]
### Issue
On replication from remote, I get an exception as follows:

Uncaught DOMException: Failed to execute 'index' on 'IDBObjectStore': The transaction has finished.
    at IDBRequest.S.m.onerror 

### Info
- Ubuntu 20.04 LTS
- Chrome 91.0
- IndexedDB
- CouchDB

### Reproduce
My database is fairly large (200 Mb). Could this be causing the problem?

status: 500
name: indexed_db_went_bad
message: Unknown
error: true
reason: Timeout error
result:
    doc_write_failures: 452
    docs_read: 452
    docs_written: 0
   errors: []
   status: aborting
   ok: false
   last_seq: xxxxxxxxxxxxx

**Comment by dheimoz** [comment]
Hello @sureshvv 

You mentioned your database is large, how many documents has? and are there any attachments?

**Comment by sureshvv** [comment]
@dheimoz about 450 docs... No attachments

**Comment by sureshvv** [comment]
I made some more progress on this. Turns on the last_seq is not the culprit. I made batch_size: 1, batches_limit: 1 and then logged the on('change') event to get the document id. It is the document right after the last_seq. Is there any way I can identify it?
:

**Comment by sureshvv** [comment]
Changing auto_compaction: true to revs_limit: 1 fixed this problem which caused the replication to hang and timeout. May be someone can explain why this was happening.

**Comment by janl** [comment]
to clarify, does this happen with `pouchdb-adapter-idb` or `pouchdb-adapter-indexeddb`?
