### ISSUE TITLE
Pouchdb.find is not a function

### ISSUE THREAD

**Issue by krishna-404** [pouchdb/pouchdb#8303]
### Issue
Cant using the mango query find. Getting error
```PouchDB.find is not a function```

### Info
- Environment: Browser - Reactjs
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
I not able to use mango queries with pouchDB in reactjs. I have scoured the whole internet for a suitable answer but couldn't find one.

For example the docs here https://pouchdb.com/guides/mango-queries.html is outdated as mentioned here https://github.com/nolanlawson/pouchdb-find that pouchdb-find is now merged with pouchdb.

So I tried using pouchdb-find plugin with both pouchdb & pouchdb-browser. It just doesnt work. Any help will be really great. Thanks!

Options tried so far:

Option1
```
import PouchDB from 'pouchdb';
import pouchAuth from 'pouchdb-authentication';
PouchDB.plugin(pouchAuth);
PouchDB.plugin(require('pouchdb-find').default);
```

Option2
```
import PouchDB from 'pouchdb';
import pouchAuth from 'pouchdb-authentication';
import pouchFind from 'pouchdb-find';
PouchDB.plugin(pouchAuth);
PouchDB.plugin(pouchFind');
```

Option3
```
import PouchDB from 'pouchdb-browser';
import pouchAuth from 'pouchdb-authentication';
import pouchFind from 'pouchdb-find';
PouchDB.plugin(pouchAuth);
PouchDB.plugin(pouchFind');
```

Option4
```
import PouchDB from 'pouchdb';
import pouchAuth from 'pouchdb-authentication';
PouchDB.plugin(pouchAuth);
```

Is there a discord/slack channel where the community hangs? Thanks!

**Comment by sureshvv** [comment]
Option 2 works for me.

What versions are u using?

**Comment by krishna-404** [comment]
Tried without authentication. Still doesnt work.

Here are the versions:
```
    "pouchdb": "^7.2.2",
    "pouchdb-authentication": "^1.1.3",
    "pouchdb-browser": "^7.2.2",
    "pouchdb-find": "^7.2.2",
```

**Comment by sureshvv** [comment]
May be you are using it wrong.

What does your code look like where you set up the db and call the find?

**Comment by dheimoz** [comment]
hey @krishna-404 
This is the slack channel for Pouchdb
https://couchdb.slack.com/archives/C016TJAE7A4

**Comment by dheimoz** [comment]
I would ask the same as @sureshvv 

Would need to see the code or a replication repo to sort it out.

**Comment by krishna-404** [comment]
Here is the repo replication
https://github.com/krishna-404/temp

you will find the database files in `temp\src\database` folder.

I need an invite to be able to join the couchdb channel. Can you please send me an invite at agarwalbalkrishnaindia [at] gmail [dot] com

Thanks for all the help.

**Comment by sureshvv** [comment]
Just need to look at 2 lines of the code. Will be easier on us if you can copy/paste.

Here is how I do it.

    this.db = new PouchDB(db_name, {auto_compaction: true})

and later:

    var res = await this.db.find({selector: selector})

**Comment by krishna-404** [comment]
Alright there are 2 components

Component 1
```
import PouchDB from 'pouchdb-browser';

import pouchAuth from 'pouchdb-authentication';
import pouchFind from 'pouchdb-find';
PouchDB.plugin(pouchAuth);
PouchDB.plugin(pouchFind); 

import {dbName, couchURL} from './constants';

const getMasterDB = async (input) => {
 
        const localDB = new PouchDB(dbName, {auto_compaction: true});
        
        const remoteDB = new PouchDB(
                                `${couchURL}/${dbName}`, 
                                { skip_setup: true });

        localDB.sync(remoteDB, {
                live: true,
                heartbeat: false,
                timeout: false,
                retry: true
                // filter: 'app/by_agent',
                // query_params: { "agent": agent }
                // Can use to filter out the deleted docs. More here: https://pouchdb.com/2015/04/05/filtered-replication.html
            }).on('change', function(change){
                console.log(change);
            }).on('paused', function(info){
                console.log(info);
            }).on('active', function(info){
                console.log(info)
            }).on('err', function({err}){
                console.error(err);
            });

           return localDB
}

export default getMasterDB;
```

Here is the component 2

```
import React ....
import getMasterDB from 'dbFile.js'

const Component2 = () => {

let res = await getMasterDB().find({
                selector: {
                    type: { $eq: props[2]}
                },
                limit: 1
            }).then((db) => db.docs[0]);
...
}

export default Component2;
```

**Comment by sureshvv** [comment]
await in combination with then is not right.

**Comment by krishna-404** [comment]
Changed it to 

```
let res = await getMasterDB().find({
                selector: {
                    type: { $eq: props[2]}
                },
                limit: 1
            });

res = res.docs[0];
```

& it didnot work.

Breaking it further like you mentioned
```
let res = await getMasterDB()
let res2 = await res.find({
            selector: {
                type: { $eq: props[2]}
            },
            limit: 1
        })
```

Made it work. makes me wonder why! Thanks a ton for this. 🙌

I will mark this closed now.

**Comment by dheimoz** [comment]
@krishna-404 great you sort it out and thank you very much for sharing the solution.

Cheers!
