### ISSUE TITLE
How can I reduce the 10 minute timeout before I get Replication Error?

### ISSUE THREAD

**Issue by sureshvv** [pouchdb/pouchdb#8304]
### Issue
Pouchdb replicate() takes 10 minutes and then times out with indexed_db_gone_bad. How do I lower this timeout? Setting timeout in the options did not make a difference. Do I have a throw in the back_off_function?

### Info

- Ubuntu 20.04 LTS
- Chrome 91.0
- IndexedDB
- CouchDB

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by dheimoz** [comment]
hey @sureshvv I assume this is a very specific use case with your Database. How many documents does it have?

10 minutes for me is an eternity. Have you considered using filtered replication?

https://pouchdb.com/api.html#replication

and then look at the Filtered replication examples

**Comment by sureshvv** [comment]
10 minutes is an eternity for me too. Thankfully this does not happen in practice.

But once after 2 years, the replication hung for 10 minutes and then failed with Timeout error indexed_db_gone_bad. Was able to reproduce consistently.

And I would like to catch this particular error sooner than after 10 minutes.

**Comment by sureshvv** [comment]
The documentation states:

    options.back_off_function: backoff function to be used in retry replication. This is a function that takes the current backoff
    as input (or 0 the first time) and returns a new backoff in milliseconds. You can use this to tweak when and how replication
    will try to reconnect to a remote database when the user goes offline. Defaults to a function that chooses a random
    backoff between 0 and 2 seconds and doubles every time it fails to connect. The default delay will never exceed 10 minutes. 
    (See Customizing retry replication below.)

10 minutes is way too long. How can I get out sooner?

**Comment by dheimoz** [comment]
Hello @sureshvv 
This is my syncOptions that I use for my custom replication:
```js
const syncOptions = {
  batch_size: 5,
  batches_limit: 2,
  live: true,
  retry: true,
  back_off_function(delay) {
    if (delay === 27000 || delay === 0) {
      return 1000;
    }
    return delay * 3;
  },
};
```

There is an example in documentation
https://pouchdb.com/api.html#replication
and then look for 
Customizing retry replication

Please let me know if this works.

**Comment by sureshvv** [comment]
Yes. I tried this already (copied from your prev. msg.) but that did not cut down the 10 minute timeout.

I was wondering if I should throw from the back_off_function.
