### ISSUE TITLE
Import Database to JS file

### ISSUE THREAD

**Issue by Dinesh101041** [pouchdb/pouchdb#8305]
### Issue
Not a issue a small doubt
I am working on electron js application and pouchdb<br>
i want to import the created database to another js file and want to retrieve the data

Here is a File structure 

     -JS
        - impotdb.js        // want to import db here

     -DB                    // this folder contains all db
        -DB1
        -DB2

      db.js                //this is main db.js file where db is created 

here is db.js code
  ```
var PouchDB = require("pouchdb");
var db = new PouchDB("DB/Db1", { adapter: "leveldb" });
console.log("Database created Successfully.");
  ```

i tried with [pouchdb-all-dbs][1] plugin but for me it returned as empty array

  [1]: https://github.com/pouchdb-community/pouchdb-all-dbs

code for plugin in importdb.js file
```
var PouchDB = require("pouchdb");
require('pouchdb-all-dbs')(PouchDB);

PouchDB.allDbs().then(function (dbs) {
   // dbs is an array of strings, e.g. ['mydb1', 'mydb2']
    console.log(dbs)
  }).catch(function (err) {
    // handle err
    console.log(err)
});
```
on console log dbs it returned as empty array <br>
can any one help me to import and  use created dbs in importdb.js

**Comment by dheimoz** [comment]
hey @Dinesh101041 

If I understand correctly your doubt, do you want to create a backup of your Database?
I believe the easiest would be something like this
https://www.quora.com/How-do-I-create-a-txt-file-in-javascript

But that is not related to Pouchdb.

I know there are some efforts about exporting and importing an Indexeddb, but as stated, that is not related to Pouchdb.

**Comment by Dinesh101041** [comment]
no i don't want to backup 
i want to get the all docs and data of DB1 or DB2 from importdb.js file

or how to replicate two local database DB1 or DB2 in importdb.js file [ platform - Electron js, offline pouchdb ]
i hope you get my question correctly

**Comment by sureshvv** [comment]
Check out pouchdb-dump and pouchdb-load plugins.
