### ISSUE TITLE
Update the Glitch.me example to use the latest PouchDB release

### ISSUE THREAD

**Issue by seigel** [pouchdb/pouchdb#8306]
### Issue
While exploring ideas and issues, I noticed that the amazing (https://pouchdb-bug-helper.glitch.me/) is using 6.4.1 PouchDB.  May I suggest updating this glitch to 7.2.1?

### Info
- Environment: https://pouchdb-bug-helper.glitch.me/
- Platform: Any
- Server: PouchDB Server

### Reproduce
https://pouchdb-bug-helper.glitch.me/

https://github.com/pouchdb/pouchdb-bug-helper/pull/3

**Comment by dheimoz** [comment]
hey @seigel thanks for bringing this up. Let's check what can be done,

**Comment by seigel** [comment]
I think I have a PR that fixes it somewhere in here.  Ahh...here it is if it wasn't obvious.  
PR -> https://github.com/pouchdb/pouchdb-bug-helper/pull/3

**Comment by dheimoz** [comment]
waiting to be merged

**Comment by dheimoz** [comment]
hey @daleharvey Hope you are doing great. I do not have access, could you help us with the contribution.
