### ISSUE TITLE
Uncaught TypeError: Cannot read property 'seq' of undefined

### ISSUE THREAD

**Issue by IanMayo** [pouchdb/pouchdb#8308]
### Issue
I'm running PouchDb in a node/express backend.

PouchDb is using websql to persist data to a SQLite database.

If I open the database in `DB Browser for SQLite`, I can make manual changes to documents in the PouchDb database.  This has no impact on PouchDb.  

But, if there is a pending change in the SQLite database, PouchDb takes down the node server.

```
 /node_modules/pouchdb-adapter-websql-core/lib/index.js:400
@serge/server:           var seq = res.rows.item(0).seq;
@serge/server:                                     ^
@serge/server: TypeError: Cannot read property 'seq' of undefined
@serge/server:     at SQLTask.sqlCallback (/node_modules/pouchdb-adapter-websql-core/lib/index.js:400:37)
@serge/server:     at /node_modules/websql/lib/websql/WebSQLTransaction.js:70:19
@serge/server:     at checkDone (/node_modules/websql/lib/sqlite/SQLiteDatabase.js:50:7)
@serge/server:     at /node_modules/websql/lib/sqlite/SQLiteDatabase.js:59:7
@serge/server:     at Statement.<anonymous> (/node_modules/websql/lib/sqlite/SQLiteDatabase.js:21:5)
@serge/server: error Command failed with exit code 1.
@serge/server: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Pending changes for a SQLite database called `backend.sqlite` introduce a journal rollback file called `backend.sqlite-journal'.

### Info
- Environment: Node.js
- Platform: Chrome/Macos or Chrome/Windows
- Adapter: WebSQL/
- Server: Node

### Reproduce
* Create PouchDb database, with websql/sqlite backend
* 'put' document to database
* open database in `DB Browser for SQLite`
* open document from `by-sequence` table
* make minor change to document (still use valid JSON)
* click on `Apply`, then `Write Changes`
* `put` another document - works fine
* make another change to document
* click on `Apply` but NOT `Write Changes`
* `put` another document - above error displayed, node exits

**Comment by seigel** [comment]
Just so I understand what is happening, you are changing the underlying data store that pouchDB is using from a tool that is NOT PouchDB.   I am curious what the use case for this is?

Cheers

**Comment by IanMayo** [comment]
Hello @seigel  & @dheimoz - I understand your concerns.

My use case is that I have a browser-based UI that is capable of editing most aspects of the JSON documents stored in JSON.  But, occasionally there is an edge case where a field needs to be modified that the browser-based editor is unaware of.

So, my "ultimate fallback" for the last 2 years has been to manually edit the JSON document within the SQLite database (using a SQLite client app).  This works quite reliably, and doesn't involve creating or removing any documents (or modifying `_id` or `_rev`).  Note: the database isn't replicated/synced.  We've chosen PouchDb due to its support for [Event Sourcing](https://martinfowler.com/eaaDev/EventSourcing.html)

But, as described above, PouchDB takes down the node server if a new document is submitted to PouchDB while there is a pending change in the client.   A more graceful response would be to throw an existing PouchDB (or http) error, that the browser client can then handle as needed.

**Comment by seigel** [comment]
Quick question, which `Node` server is crashing as a result if this is a browser base UI and a browser based storage solution.  Is the PouchDB running in the browser? Or is this PouchDb running in a node instance on the server side?

As an aside, often,  most databases behave very poorly when the integrity of the files they manage are modified outside of their control.  Sometimes failing fast is a reasonable solution when this happens.  I am sure there are unexpected results happening when this editing happens.  If you have an idea of where this is failing (in the code) that might help me potentially propose a solution.

**Comment by IanMayo** [comment]
Hello @seigel,
a node server is being run from the command line, serving pages to browser-based clients.  When the browser-based client tries to `put` a document to PouchDb instance, the PouchDb crashes the node server (stack trace in original posting). Once the server process has terminated, the `put` operation reports `net::ERR_CONNECTION_REFUSED` the client.

Aah, another observation.  If there is a pending change to a `local document` in PouchDb, then PouchDb returns `409 (Conflict)`.  PouchDb only crashes when there is a pending change to a document in the `by-sequence` table.  I believe the `409 (Conflict)` response would be the preferred way of handling the pending change in the `by-sequence` table.  

I guess the 'pending change' could be interpreted as the SQLite database being locked.

**Comment by seigel** [comment]
Interesting, maybe the improvements on pouchDB side might be for better unexpected error handling.  Any chance you can share a simple code example (strip out your business logic), then I can recreate with your versions and scenario in consideration. 

Cheers

**Comment by IanMayo** [comment]
Hello @seigel , sorry for the delay.

It would be too complex to pull out the code from my app.  I've made a demonstrator for the issue here:
https://github.com/serge-web/PouchDb_Demonstrator

![screencast](https://gyazo.com/51213cb488ca377bb4d9bb197b9f1357)

More detailed video feed [here](https://i.gyazo.com/51213cb488ca377bb4d9bb197b9f1357.mp4) 

As the video shows: if there is a pending change in the database we get a `409` conflict status returned if we try to push a local document. But, node exits if we try to push a normal document. Ideally we'd get this `409` error instead of node exit.

**Comment by IanMayo** [comment]
Hello @seigel - I did fund a developer to investigate a fix to the PouchDb driver using the above repo, but his unfamiliarity with PouchDb codebase meant he was unable to identify the fix.

If you're able to give pointers to where/how PouchDb could return an error code instead of exiting - then I'll carry on trying to sponsor a fix.  Alternatively, I'd be happy to discuss sponsoring you fixing it, via DM.

**Comment by seigel** [comment]
Let me find some time to see if I can reproduce it and see what is broken and a suggested fix. 

I’ll try to get to that in the next day or two if that works for you. :)

**Comment by seigel** [comment]
Okay...recreated it...now figuring out what it means and what the right thing to assume at that location -> what code should do...

**Comment by seigel** [comment]
Still feels very wrong playing with the underlying datastructure.  In your application is it not possible to manipulate the data you want to manipulate through another pouch mechanism?  Feels like the fact that we are using websql should be a private blackbox type thing.  

All that aside, I am still spelunking through a bit to see if I can reason about what a good scenario is at this point, and how a recovery could be affected rather than crashing...

**Comment by seigel** [comment]
Okay, if you want it to fail more gracefully you could add this to your version of the websql adapter...in line 409 of the websql.js file in the adapter code you can protect against the seq not being there with something like this `          var seq = res.rows && res.rows.length > 0 && res.rows.item(0).seq || 0;
` and then it throws the error that the sqllite db is READONLY, and some other hilarity.  Maybe if you had an idea of what you'd want to see there, we could guide it in that direction.

NOTE: this code is no longer in active development and has been removed from the repo, so it is a bit of a side adventure for sure :D

**Comment by IanMayo** [comment]
Thanks for all that @seigel 

> NOTE: this code ... has been removed from the repo

Oh, I didn't know that. Does that mean there's a newer/alternative way of creating a PouchDb in Node?

**Comment by seigel** [comment]
Sounds good.  If for some reason you are set on using this and feel like poking around some more...the block that we were playing in was really a constraint error block which takes an argument.  If you put one in there...replace
`      }, function () {
` with
`      }, function (error) {
`
And then log that error out you will see that you are in some sort of transaction.  Anyway, I stopped there and didn't investigate as to why the DB seems read only now, nor how to get around that, and if I want to get around that :D

Well good luck...I hope that investigation helped a bit. 

General guidance...don't have two managers/owners/responsible actors for a foundational element.  Usually results in ..... "FUN" :D

Cheers

If you had some of the bounty money to allocate still, please consider donating to the Canadian Brain Tumour Foundation.  Here is a shortcut link to my donation page .  [shortcut re-direct to donation page](http://cgul.live)

**Comment by IanMayo** [comment]
Closing issue. Cannot justify investigating issue related to deprecated capability.

Sadly, there aren't many `indexedDb` database clients around - so for now we'll stick with `sqlite`.
