### ISSUE TITLE
Errors when aborting replication

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [pouchdb/pouchdb#8309]
### Issue
I'm using pouchdb in a mobile application. When the app is in background mode for some time, replication doesn't work anymore (which is to be expected, I think). Therefore, after app resume I check whether replication still works, and if it doesn't work I cancel the old replication and start a new one.

This solution seems to work fine. However I sometimes see

* `Cannot read property 'filter' of undefined` thrown in  https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/adapter.js#L887
* or `undefined is not an object (evaluating 'r.length')` in https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/adapter.js#L893

when cancelling the replication.

In both cases, the callback is called from here: https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-indexeddb/src/bulkDocs.js#L375

Apparently, `error` in `onabort` is undefined when cancelling replication manually, which then causes the error in the callback function.

### Possible fix

I think the issue should be quite simple to fix:
 ```
txn.onabort = function () {
  callback(error || someDefaultError);
}
```

Problem is: I don't know enough of pouchdb's internals to know what `someDefaultError` should be. Any suggestions?

**Comment by sureshvv** [comment]
> Therefore, after app resume I check whether replication still works, and if it doesn't work I cancel the old replication and start a new one.
> 

How do you check if the replication "still works"?

**Comment by hermitdemschoenenleben** [comment]
> > Therefore, after app resume I check whether replication still works, and if it doesn't work I cancel the old replication and start a new one.
> 
> How do you check if the replication "still works"?

I'm  using [https://github.com/hermitdemschoenenleben/pouchdb-csg/](pouchdb-csg) in order to retrieve the changes feed using websockets. When opening the application I send a "ping" doc to the server and expect a websocket message within the next few seconds. If I don't receive a message I assume that replication doesn't work anymore, cancel the old one and start a new one.

As the problem is quite hard to debug (happens only when the app has been in background for a long time) I did not investigate in detail what exactly happens in the case of an unresponsive replication; as android / ios put the application in a network-isolated sandbox when in background, I suppose that either a HTTP request or the changes feed can't recover and just hangs without an error mesage when re-opening the app.

However, as I understand it, the error messages I find in the logs are not related to what exactly happens when the app is in background mode / is opened again. I think they are just a consequence of cancelling a replication, which causes `txn.onabort` to be called with `error` being undefined, and this call can't be properly handled in the callback for `_bulkDocs`.

**Comment by sureshvv** [comment]
Very hoaky :d

Are you tracking the last_seq and then restarting replication at that point ?

**Comment by hermitdemschoenenleben** [comment]
well... I assumed that pouchdb does this for me, because as far as I understand the protocol this is what replication checkpoints are for?

**Comment by hermitdemschoenenleben** [comment]
I just double checked: when cancelling and resuming the replication, the "since" parameter that is sent to the `_changes` endpoint of the server is updated indeed.

From my understanding, cancelling and resuming a replication should work. I mean, an app may be closed by the user any time, so the replication has to be able to resume an incomplete replication anyway. Or is there something that I'm missing? :)

**Comment by sureshvv** [comment]
When you cancel the current replication, does your "complete" handler get fired?

**Comment by hermitdemschoenenleben** [comment]
normally yes. I wait until I receive the "complete" event before starting a new replication. If the bug I described above occurs, however, I do never receive a "complete" event and my replication never restarts --> this is why I want to fix the problem :)

**Comment by hermitdemschoenenleben** [comment]
oh, in fact I found out that I did not properly wait for "complete" event... I tried to, but the code was buggy :( Maybe this is the reason that `txn.onabort` is called at all?

**Comment by sureshvv** [comment]
If a replication error happens, can we assume that the replication is dead and no cancellation is needed and/or further events will be emitted? This is not explicitly spelled out in the documentation AFAIR.

**Comment by hermitdemschoenenleben** [comment]
> If a replication error happens, can we assume that the replication is dead and no cancellation is needed and/or further events will be emitted? This is not explicitly spelled out in the documentation AFAIR.

After digging around in the source code a bit, I'm not quite sure about this... So to be on the safe side, I prefer explicit cancelling of the replication in order to not having two running replications.

In the last days I published a new version of my app that does the following on app resume:
* writes something to the remote db to trigger a message in the changes feed
* wait 5 seconds whether changes feed returns something
* if it doesn't: cancel replication and wait for
  * "complete" event
  * or timeout of another 5 seconds
* start a new replication

So far, this seems to work fine (although I probably may reduce the timeout of 5 seconds to a lower value).

**However**: I again see the errors of my first posts in the error log (`Cannot read property 'filter' of undefined`). This error happens directly after resuming the app, before I detect that replication is not working anymore (i.e. it is not related to me calling `.cancel()`). Apparently the cause is that an indexeddb transaction is cancelled because the app is suspended. This cancelling is not properly handled by pouchdb.

What do you think of the possible fix I included in my first post?

**Comment by hermitdemschoenenleben** [comment]
@sureshvv do you have any opinion on whether the fix I suggested in the first post is ok? It does not fix the root of the problem (transaction is aborted for some reason), but at least it allows pouchdb to properly handle the error.

btw: I'm kinda sure that cancelling / restarting the sync isn't the root of the problem at all. Apparently the transaction is cancelled for some other reason that I'm still investigating

**Comment by sureshvv** [comment]
@hermitdemschoenenleben I am not an expert on pouchdb internals but have a question.

1. Have you identified what error you want to use (for someDefaultError)?

**Comment by hermitdemschoenenleben** [comment]
hi! For the pull request, I chose UnknownError: https://github.com/pouchdb/pouchdb/pull/8316/files

After some research, I believe the root cause of the issue are bugs in safari that cause indexeddb to throw errors after an app has been in background for a while: https://bugs.webkit.org/show_bug.cgi?id=197050 (there are multiple similar bugs that may be triggered in this case). Unfortunately, there is no way to fix these issues (except reloading the page). So it makes sense that pouchdb just throws an error which in my testing then causes a "Database has a global failure" exception of pouchdb.

**Comment by sureshvv** [comment]
The safari bug seems to be about Firebase. My users have not encountered this with pouchdb.

**Comment by hermitdemschoenenleben** [comment]
You're right that the bug is about firebase, but I suspect that it has the same cause as the pouchdb bug: when the app is in background for some time, safari aborts transactions. In my app I also use @ionic/storage based on indexeddb and I see quite some errors in my logs where @ionic/storage fails because of closed indexeddb transactions ("Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing." and some similar messages). So I think that the same thing happens to the pouchdb transaction which then triggers the pouchdb bug that this issue is about.

May I ask what environment you use pouchdb in? Is it also a mobile app with capacitor?

**Comment by sureshvv** [comment]
Mine is a progressive web app that runs inside the browser (chrome/safari/firefox). The browser stays open all the time.

**Comment by hermitdemschoenenleben** [comment]
thanks for merging the PR and thanks for your help, @sureshvv!
