### ISSUE TITLE
Change Freenode IRC links to point to libera.chat

### ISSUE THREAD

**Issue by garbados** [pouchdb/pouchdb#8312]
Given the hostile change in management of the Freenode network, it would likely be best to change IRC links to point to a [libera.chat](https://libera.chat/) server.

**Comment by dheimoz** [comment]
Hey @garbados understood. This needs to be done.

I am not well versed in IRC, but will give it a try.

**Comment by janl** [comment]
I’d be happy to merge a PR to that effect. I already have secured the channel in anticipation of this.

**Comment by dheimoz** [comment]
hey @janl if you have the time, your help would be invaluable.

**Comment by janl** [comment]
this looks like it, no? https://github.com/pouchdb/pouchdb/tree/master/docs all the main repo readme
