### ISSUE TITLE
Safari 14 IndexedDB Bug

### ISSUE THREAD

**Issue by janl** [pouchdb/pouchdb#8313]
This is not an issue per se, but Safari 14 has a bad IndexedDB bug (https://bugs.webkit.org/show_bug.cgi?id=226547).

In our early testing, PouchDB is not affected, possibly because of how it uses IndexedDB today.

However, should anyone find any issues (and subsequent fixes or workarounds [like this](https://www.npmjs.com/package/safari-14-idb-fix)), we can collect them here.

**Comment by AlbaHerrerias** [comment]
Nobody reported until now, so we don't think this is an issue
