### ISSUE TITLE
Find doc data by date

### ISSUE THREAD

**Issue by Dinesh101041** [pouchdb/pouchdb#8314]
### Issue
Not an issue small doubt
i created the db and inserted the records below is my doc 
```
 var doc = {
      _id: Sno,
      Date:date,
      time:Time,
      trip : Trip,
      triptype:TripType,
      vechicleNo: VechicleNo,
      customer: Customer,
      vechicletType: VechicleType,
     
   };
```

now i want to get the values based on date selection <br>
![image](https://user-images.githubusercontent.com/59551894/122949269-24747100-d399-11eb-82d4-5f37109cc08b.png)

on selecting date i want to get all values based on date 
i used the find plugin but it display doc as 0 even if there is data in particular date

here is my find plugin code
```
\\getting the date value on select
var saledate = document.getElementById('startdate').value;
   console.log(saledate);

   db.createIndex({
      index: {
        fields: ['Date']
      }
   });

   db.find({
        selector: {
          Date: saledate,  // assigning date value to the selector
        },
      });
   }).then(function (response) {
      console.log(response);
   }).catch(function (err) {
      console.log(err);
   });
```
can any any one help me with code 

and also on creating index the `mrview` is directory is created and the id dropdown is updated like below 

this image is the id dropdown before the index is created <br>
 
![122950867-6fdb4f00-d39a-11eb-80d3-00571c19481b](https://user-images.githubusercontent.com/59551894/122961422-03644e00-d3a2-11eb-97cb-c9ae028e1202.png)

after creating index the id dropdown in updated like this
![122951305-cfd1f580-d39a-11eb-8cb4-08e16b12b018](https://user-images.githubusercontent.com/59551894/122961678-40304500-d3a2-11eb-93d9-33fb87a07c7e.png)
can anyone help me why this happening 

platform : electron js

**Comment by technicool** [comment]
`NaN` means Not A Number. So the format of the data somewhere is possibly wrong.

You need to store the date in a valid format. You could either use an ISO date formatted string, such as "2020-12-31" or a number based format, such as the number of seconds since epoch: `let Date = Math.floor(Date.now() / 1000)` if you are converting to a number intentionally.

This doesn't appear to be an issue related to pouch, as it doesn't support a native date type.

**Comment by Dinesh101041** [comment]
Thank you for kind reply on changing date format find is perfectly working  but now the only problem is the id drop down is updated with  NAN on creating index  like above image
here is code of id drop down only one values is hard coded and next values are generating dynamically based on db docs
```
   <select name="sno" id="number" onchange="val()">
            <option value="1">1</option>
     </select>
```
dropdown dynamic code
```
db.allDocs({
   include_docs: true,
   attachments: true,
}).then(function (dbdoc) { 
   //  getting id from db and appending to dropdown on refreshing application
   if (dbdoc.rows && dbdoc.rows.length) {
      var result = dbdoc.rows.map(({ doc }) => doc._id);
      var select = document.getElementById("number");
      for (var i = 1; i <= result.length; i++) {
         var opt = result[i];
         var el = document.createElement("option");
         el.value = opt;
         el.innerHTML = el.value;
         select.appendChild(el);e
         el.selected = true;
      }
      // get last element from the above result array and increment and append to 
      // document for getting next number in dropdown on load
      var last_element = result[result.length - 1];
      el.value = ++last_element;
      el.innerHTML = el.value;
      select.appendChild(el);
      el.selected = true;
   }
   console.log(dbdoc);
})
.catch(function (err) {
   console.log(err);
});

```
can you please elaborate why  _designidx/e97755 and NAN is appending to dropdown on creating index in for date

**Comment by Dinesh101041** [comment]
can any one help to solve this

**Comment by dheimoz** [comment]
Hello @Dinesh101041 
As this is not a but. I suggest you to check the Couchdb Slack community
https://join.slack.com/t/couchdb/shared_invite/zt-fa9zim0j-H04m4o_KcLdWeOxEAcwM8g

There is a Pouchdb channel were we all can collaborate.

My first question here is, as you using only Pouchdb, or are you synching to Couchdb or Cloudant?
Then, can you take a look at your Dev Tools -> Application-> Indexeddb -> _pouch_your_db_name
And then "_doc_id_rev"

You should see your Documents. Confirm please if that NAN document is there.

If positive I guess the problem lays in the way you are storing documents.
Dates need to be converted to strings as Pouchdb/Couchdb work with JSON.

I usually prefer filtering at the client of front end with javascript. But that is my approach.

And then doc

**Comment by Dinesh101041** [comment]
Sorry for late reply 
The date problem is solved  by changing  format of date 

but on creating index on date for searching the doc the `_designidx/e97755 `and `NAN ` is inserted into doc 
here is the images of doc
Before creating the index the doc caontains only the form submitted  values only [submitted only two values] 
![image](https://user-images.githubusercontent.com/59551894/123673363-022d9800-d85e-11eb-8bea-b5c91dd2b754.png)
after creating index on date with this code and selecting the date on sales page the table in sales page is perfectly updating with data 
```
//index creating code to find a doc with particular value [ according to doc]
 db.createIndex({
      index: {
        fields: ['Date']
      }
   }).then(function (response) {
      // Search on two fields
      return db.find({
        selector: {
          Date: saledate,
          language: { $ne: 'query'}
        },
      });
   }).then(function (response) {
     // for the array of object and display in table
      response.docs.forEach((element, ) => {
         // console.log(element.Fweight); 
         var id = element._id;
         var name = element.vechicleNo;
         var empty_cost = element.Vechicleempty;
         var Load_cost = element.VechicleLoad;
         table.innerHTML+=`<tr  class="jst"><td>${id}</td> 
         <td>${name}</td><td>${empty_cost}</td><td>${Load_cost}</td></tr>`; 
       });
      console.log(response)
   }).catch(function (err) {
      console.log(err);
   });
```
on selecting date the find code is perfectly working and get the data based on find value
![image](https://user-images.githubusercontent.com/59551894/123674066-d0690100-d85e-11eb-8ad8-cc506edb5a64.png)

but after this when we console the doc the doc is inserted with `_designidx/e97755 `and `NAN ` i
here is the image of doc after date selection
![image](https://user-images.githubusercontent.com/59551894/123674405-35245b80-d85f-11eb-88ec-4212a2fb63dc.png)

but when find the value with out creating index the doc is not update with `nan` the query   just display the warring
![image](https://user-images.githubusercontent.com/59551894/123674795-a532e180-d85f-11eb-8a15-17af9cd33a6c.png)


is a good way of code? or want to create the index
