### ISSUE TITLE
createIndex no options parameter

### ISSUE THREAD

**Issue by ronelvcabrera** [pouchdb/pouchdb#8315]
Among all the methods that are available on pouchdb, why is `createIndex` without an `options` parameter.

My use case is that I want a certain user only can create index, hence I use the `auth` option to fill those credentials, not the current user, because I also used `pouchdb-authenticate`.

Wanna know why and can we add that in?

**Comment by dheimoz** [comment]
Hello @ronelvcabrera 
I wonder if you can provide more details for your use case. An example would suffice.
As far as I know, Pouchdb tries to be complaint with the Couchdb API

Cannot see if there is an option paramenter:

https://docs.couchdb.org/en/latest/api/database/find.html#db-index

Maybe Update Functions can be hepful:
https://docs.couchdb.org/en/stable/ddocs/ddocs.html?highlight=update%20function#update-functions

**Comment by ronelvcabrera** [comment]
@dheimoz Like I mentioned above, I want to be able to execute `createIndex` using a different credentials from the current user used at `pouchdb-authenticate` with `logIn` method. If I do `createIndex` the auth-cookie will be used for verfication of the user, and the user needs a `_admin` access to be able to create such document. And I dont want all user having a `_admin` access rights. I want a few only and maybe place that credentials on my `.env` and use that whenever I need it and on this case would be great.


So your saying, couchDB itself does not required or have that option to have a Basic Auth on creating index?

**Comment by dheimoz** [comment]
Hello @ronelvcabrera 

As far as I know, Pouchdb does not have that granularity to specify a user for a specific operation, neither Couchdb. Answering your last question, every operation with Couchdb need to be authenticated. 

What I usually do is using a node server and depending on user rol node communicates with Couchdb and performs the operation with an admin user.

Maybe not seamless but it is the safest way I have found for that kind of scenarios.

Hope the idea makes sense.
