### ISSUE TITLE
pouchdb-find - is there no way to modify an existing index?

### ISSUE THREAD

**Issue by Cure4Life** [pouchdb/pouchdb#8317]
### Issue
Hello, 
I have searched and searched for an answer to this and there is literally nothing I can find so either I am just not entirely up-to-speed on the concept as it applies to PouchDB/CouchDB and this is something that everyone just inherently knows and the need to document this isn't considered necessary, or possibly that the keywords used in my searches are returning too many results for unrelated topics.

When using indexes with pouchdb-find (or any DB for that matter) , one ultimately needs to modify an index once a need arises for that. Is it not possible to update an index on-the-fly? Is the only way to achieve this a manual find-index/delete-index/create-new-index process?

I should note that I am using PouchDB on a distributed app, not on a website. All data needs to be kept local to the device with an option for a "cloud backup", which is why PouchDB is the best fit for this. But also why index maintenance must be done from within the code via app updates.

### Reproduce
1. create an index on a database
`await DB.createIndex({
	index: {
		fields: ['name'],
		name: 'accountNamesIndex',
		ddoc: 'ddoc-account-names'
	}
})`

2. later, change the index but keep the name and ddoc fields unchanged with the idea that it would see that a new index is being created with the same name as an existing one but with different parameters, and replace the old one with the new one.
`await DB.createIndex({
	index: {
		fields: ['name', 'type'],
		name: 'accountNamesIndex',
		ddoc: 'ddoc-account-names'
	}
})`

After this change, I would expect the design doc to get updated but it seems that it does not check for any changes to the actual index properties, but rather sees that an index of the same name and/or ddoc exists and stops there because after attempting the createIndex with the changes to the index properties (adding 'type' to the fields list), nothing gets changed. The only way I have been able to see this work is by manually deleting the index prior to issuing the createIndex with the new parameters, which is a lengthy process of listing all indexes (getIndexes), finding the one needing updated (manual process), using that to issue a delete (deleteIndex), since according to the docs, one must pass the entirety of the getIndexes result for the index in question to the deleteIndex method as opposed to just being able to pass the index name or ddoc value. This could be made much easier if, for example, there were at least a `delete index by ddoc or name` feature but ideally an `updateIndex` process. 

Without explicit documentation on how to go about this process, I feel like I am missing something here so any advice is greatly appreciated!

Thanks in advance

**Comment by LyteFM** [comment]
I'd say that both the [CouchDB docs](https://docs.couchdb.org/en/stable/api/database/find.html#db-index) and the PouchDB docs [here](https://pouchdb.com/api.html#delete_index) and [here](https://pouchdb.com/api.html#create_index) clearly only provide an API to create and to delete an index.

PouchDB simply follows CouchDBs behaviour and I doubt that there is demand to change the functionality. If different docs are affected by an index after a modification, it conceptually is no longer the same index anymore and cached computations aren't valid.
