### ISSUE TITLE
`$keyMapMatch` Mango operator not available

### ISSUE THREAD

**Issue by jbriales** [pouchdb/pouchdb#8318]
It seems the `$keyMapMatch` operator defined in https://docs.couchdb.org/en/latest/api/database/find.html for CouchDB does not exist in PouchDB.
Is there any concrete reason or limitation for it? Or it is just lacking the implementation? Would it be worth/doable implementing and submitting a pull request for it?

**Comment by dheimoz** [comment]
Hey @jbriales PR's are always welcome. 

I do not recall if there are any limitations.
