### ISSUE TITLE
How to limit pouchdb memory usage

### ISSUE THREAD

**Issue by bennylu** [pouchdb/pouchdb#8330]
### Issue
Hello,

I have a pouchdb server running inside a docker container, which crashed frequently due to nodejs heap size not enough.
I can easily reproduce it by an allDocs api reading lots of docs until the pouchdb eat up to 1.5G memory.

To solve the above problem, I rebuilt the pouchdb server docker container with the following CMD.

`CMD ["node", "--max-old-space-size=10240", "/usr/local/bin/pouchdb-server", "--host", "0.0.0.0"]`

The above command works and my pouchdb server stop crashing.

However, after 3 days of usage, the pouchdb eat up to 14GB memory out of the16GB VM memory, and I can't even SSH into the VM to shutdown the pouchdb.

Is there a way for limiting the pouchdb memory usage?

After investigation, I believe there was a memory leakage mentioned in [https://github.com/pouchdb/pouchdb-server/issues/187](url), because there were lots of long poll timeout and reconnects. 

Thanks you.

### Info
- Environment: Node 10
- Platform: Docker 19.03.8 on Ubuntu 20.04
- Server: PouchDB Server

**Comment by dheimoz** [comment]
hey @bennylu are you referring to 
https://github.com/pouchdb/pouchdb-server
?
Any reason for not using Couchdb?

**Comment by bennylu** [comment]
@dheimoz 

Thanks.

We decided to use PouchDB because we thought it has better javascript integration,
but now we are planing to migrate to Mongodb for several reasons.

1. The secondary index does not support $in and $or operator, we have to query large documents and filter them by ourselves.
2. Build indexes on queries happened, the waiting time makes users unhappy.
