### ISSUE TITLE
Support ArrayBuffer for attachment data

### ISSUE THREAD

**Issue by jahtalab** [pouchdb/pouchdb#8333]
### Issue
Currently [if data property of an attachment is not a string, it is assumed that data is a blob](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-utils/src/preprocessAttachments.js#L66). However the `preprocessAttachment` function should check for the type of data property and throw an exception if the type is not support. It would also be in this function that we can add the ArrayBuffer support since other parts of the code seems to be handling ArrayBuffer (or convert blobs to ArrayBuffer).

Note: Even though converting ArrayBuffers to Blobs is possible, this step seems redundant especially since pouchdb will convert the blob to ArrayBuffer again in [`binaryMd5`](https://github.com/pouchdb/pouchdb/blob/8b3ed08952b314236b1c7ce0f87abeca27478d6f/packages/node_modules/pouchdb-md5/src/binaryMd5-browser.js#L37) function.

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: -

### Reproduce
Supply an ArrayBuffer to the data property of an attachment.

**Comment by dheimoz** [comment]
hey @jahtalab mind creating a PR?

Thanks.

**Comment by samwillis** [comment]
Just came across this, its worth noting that there is an issue with handling blobs that can create a sync conflict: https://github.com/pouchdb/pouchdb/issues/8257

**Comment by jahtalab** [comment]
Please reopen the issue.

**Comment by hmd-ai** [comment]
@dheimoz Would you please reopen this issue since it hasn't been addressed?
