### ISSUE TITLE
Can we enable github discussions for pouchdb?

### ISSUE THREAD

**Issue by sureshvv** [pouchdb/pouchdb#8334]
https://docs.github.com/en/discussions

seems to be a better alternative than using issues which we have been doing lately.

**Comment by dheimoz** [comment]
hey @sureshvv great suggestion. Will take a look.
I do not recall if I you are part of the Pouchdb Channel at Couchdb Slack space?
https://couchdb.slack.com/archives/C016TJAE7A4

**Comment by sureshvv** [comment]
Had joined a couple of months back but did not notice the pouchdb channel. Just joined. Thank you,

**Comment by sureshvv** [comment]
@dheimoz  Any update on this?

**Comment by sureshvv** [comment]
Can someone click on the needed buttons please?

**Comment by dheimoz** [comment]
Hello @sureshvv 
Thanks for the reminder. Will take a careful look at weekend. Just skimming sounds great.

**Comment by sureshvv** [comment]
See this https://github.com/allinurl/goaccess/issues/2192

**Comment by AlbaHerrerias** [comment]
I think this is a good idea and it could be beneficial. Is anyone against it? Thanks

**Comment by janl** [comment]
Discussions are now enabled: https://github.com/pouchdb/pouchdb/discussions/8452
