### ISSUE TITLE
Same document has different revs but no conflicts. How can I continue sync?

### ISSUE THREAD

**Issue by sureshvv** [pouchdb/pouchdb#8337]
### Issue
I have a Couchdb server and pouchdb running in the browser. I have a DB with two way replication. 
I have ended up with the same document at different revs. on the server and the browser without a conflict on either side.
The replication has stopped for this document. How can I resume the replication?

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB

**Comment by dheimoz** [comment]
Hey @sureshvv , mind share a reproduction repo or a sample code?
It is odd what you are describing.

**Comment by sureshvv** [comment]
Unfortunately the repo is private and I am not able to share it. But consider the following:

1. couchdb is being compacted (only leaf revisions kept) on a regular basis
2. Multiple pouchdb clients may push/pull changes
3. Each pouchdb client is being compacted

Under these circumstances, it is very possible that my stated scenario happens. How does one recover from it?

**Comment by sureshvv** [comment]
This could be a consequence of keeping revs_limit to 1 or 2.
