### ISSUE TITLE
Checkpoint events test failing against CouchDB

### ISSUE THREAD

**Issue by jaydoane** [pouchdb/pouchdb#8339]
### Issue

The [recently](https://github.com/pouchdb/pouchdb/commit/fe9bd0281707fc91f598724211af4af56cc6707a) [added](https://github.com/pouchdb/pouchdb/commit/9f5da871ac5748bca187f97b3926326cdbddcce5) checkpoint events test is failing against latest [3.x](https://github.com/apache/couchdb/commit/a247b7db3cbf0a6a65581136d3c982022c3be279) and [main](https://github.com/apache/couchdb/commit/23f012e7a1c45d9f9325a99e15103b4589f26d32) CouchDB development branches:

```
$ COUCH_HOST=http://adm:pass@127.0.0.1:15984 GREP=test.replication_events.js npm test

  suite2 test.replication_events.js-local-http
    ✓ #3852 Test basic starting empty (254ms)
    ✓ #3852 Test basic starting with docs (192ms)
    ✓ #5710 Test pending property support (124ms)
    ✓ #3852 Test errors (114ms)
    ✓ #4627 Test no duplicate changes in live replication (2080ms)
    1) Test checkpoint events

  5 passing (3s)
  1 failing

  1) suite2 test.replication_events.js-local-http Test checkpoint events:
     AssertionError: expected '0000203602b2f88e00000000' to equal 1
      at Context.<anonymous> (tests/integration/test.replication_events.js:420:51)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

returned 1
```

Is this expected to pass?

### Info
- Environment: Node.js
- Platform: macOS 10.15.7
- Adapter: N/A
- Server: CouchDB, Cloudant

### Reproduce
Should be reproducible on either 3.x or main development branches, and am guessing older versions as well.

**Comment by janl** [comment]
@jaydoane we’re currently working hard on getting PouchDB CI back into shape with GHA and also have tests run against real couch instances, so these things should be caught earlier next time.

**Comment by janl** [comment]
@jaydoane is this running against the transactional storage engine (i.e. future Couch 4)? That update_seq looks suspicious :)

**Comment by jaydoane** [comment]
> @jaydoane is this running against the transactional storage engine (i.e. future Couch 4)? That update_seq looks suspicious :)

@janl I first noticed this issue against main (future Couch 4), but the tests also failed against 3.x last I tested.

**Comment by janl** [comment]
@jaydoane we have fixes incoming for clustered couches, but not 4.x yet
