### ISSUE TITLE
[Docs] Setup CouchDB - Can't install couchdb with current setup guide

### ISSUE THREAD

**Issue by jayjayjpg** [pouchdb/pouchdb#8354]
### Issue

Currently, if I follow the installation instructions of the  [CouchDB setup guide](https://pouchdb.com/guides/setup-couchdb.html#installing-couchdb):

```bash
$ sudo apt-get install couchdb
```

I run into the following error:

```bash
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package couchdb is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'couchdb' has no installation candidate
```

On the following machine (without any previous installation of couchdb):

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

If I run [this preliminary installation step from the Apache couchdb docs](https://docs.couchdb.org/en/stable/install/unix.html#enabling-the-apache-couchdb-package-repository):

```bash
sudo apt update && sudo apt install -y curl apt-transport-https gnupg
curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/share/keyrings/couchdb-archive-keyring.gpg >/dev/null 2>&1
source /etc/os-release
echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ ${VERSION_CODENAME} main" \
    | sudo tee /etc/apt/sources.list.d/couchdb.list >/dev/null
```

I can successfully install couchdb as follows:

```bash
sudo apt update
sudo apt install -y couchdb
```

I think it would be helpful to add this additional installation step to the [couchdb setup guide](https://pouchdb.com/guides/setup-couchdb.html#installing-couchdb) as well.

### Info

Machine: Ubuntu 20.04.2 LTS, x86_64, GNU/Linux

### How to reproduce

- Create a fresh install of Ubuntu 20.04.2
- run `sudo apt-get install couchdb` in your terminal
=> the installation should fail with the warning `E: Package 'couchdb' has no installation candidate`

**Comment by mikkimichaelis** [comment]
How is this closed?  Fresh 22.04:

`ubuntu@ip-172-31-35-195:~$ sudo apt install -y couchdb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package couchdb is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'couchdb' has no installation candidate`
