### ISSUE TITLE
Poor write performance and unexpected conflicts

### ISSUE THREAD

**Issue by pepijndevos** [pouchdb/pouchdb#8356]
I'm writing a library and an app, and am trying to understand the issues I'm seeing before fully committing. My library is a ClojureScript wrapper that provides a cached upsert abstraction where you supply an update function and it deals with the revisions. This should resolve local conflicts, but obviously not conflicts from replication. https://github.com/NyanCAD/hipflask/

To demonstrate my library I built a silly game that is like an offline-first collaborative cookie clicker. Each user generates a unique UUID that they use to update their cookie document, which is replicated to a Cloudant instance. A live version is running here http://wishfulcoding.nl/gcc/ and the code is in the Hipflask repo.

The first alarming and confusing issue is that users reported lost cookies! And sure enough I found conflicts in the database. Why am I having conflicts if every user only updates their own documents? My understanding is you get conflicts when two sides edit the same document. What's puzzling is that the revision numbers are SUPER far apart.

![image](https://user-images.githubusercontent.com/168609/132186099-b9161fe6-78fd-4597-a21f-b1efa0ce09ab.png)

My vague theory is that maybe a race condition in replication could lead to conflicts? Due to the performance issues I'll get to next everything slowed to a crawl, so maybe interleaved and starved callbacks lead to an older local revision that was waaay backed up to be pushed after a newer revision, causing a conflict.

Now in terms of performance it's not looking super great. At first I was using live replication, but from the browser network tab it looks like every single change results in 8 HTTP request being made. That seems quite excessive. Each local user has one write per second, but for every other user, that's another 8 HTTP requests per second, and you can imagine this does not end well. The system appears to be overwhelmed by as little as 4 users. I've since changed to periodic replication which helped a bit, but is not as fun as a racing counter.

I figured replication was the main bottleneck, but when I disable replication, and just open a few tabs on the same local PouchDB, it starts to get backed up by 4 tabs doing 4 updates per second. Is PouchDB unable to handle a dozen writes per second? That seems abysmal for any database. Here is a profile of one of 4 Chromium tabs grinding to a halt.

[Profile-20210906T105437.zip](https://github.com/pouchdb/pouchdb/files/7114621/Profile-20210906T105437.zip)

Feel free to completely destroy the live demo and (password-less) Cloudant database. This might come in handy: `const timer1 = setInterval(() => document.querySelector("button").click(), 250)` Is there a nice query to see all the conflicting documents? In case someone wants to really dive into it the example can be run with `npx shadow-cljs  watch :frontend`

I would really like to understand these issues better. Conflict resolution is a core part of CouchDB, but I don't see why I would be having any conflicts with my particular usage. CouchDB was never the weapon of choice for write-heavy workloads, but CouchDB can still do hundreds if not thousands of writes per seconds, not dozens, as I'm seeing.

**Comment by janl** [comment]
we discussed this in Slack for bit and OP is going to debug the client app before moving on. Closing for now. Please reopen with new info

**Comment by pepijndevos** [comment]
Yes. Meanwhile I've improved my library to not step on its own toes, which resolved the write performance issue. What was happening is once 409s started to happen throughout went down and a ton of callbacks would build up all retrying at top speed.

I have yet to reproduce and debug the actual conflicts, so I'll reopen if I can reproduce conflicts happening while only one side has been updated.
