### ISSUE TITLE
Is this a "bug" in the Mango Queries Guide's Pagination section?

### ISSUE THREAD

**Issue by toyssamurai** [pouchdb/pouchdb#8362]
### Issue
While I was reading the Pagination section of the [Mango Queries](https://pouchdb.com/guides/mango-queries.html) guide, I found something not very reassuring. The guide starts with the following query:

```
db.find({
  selector: {
    name: {$gte: null}
  },
  sort: ['name'],
  limit: 10
});
```
The query above will then produce the following result:

```
[
  'abby', 'bertrand', 'clarice', 'don', 'emily',
  'fumiko', 'gunther', 'horatio', 'ike', 'joy'
]

```

Then, the guide goes on and states that we can use the following query to fetch the next batch:

```
db.find({
  selector: {
    name: {$gt: 'joy'}
  },
  sort: ['name'],
  limit: 10
});
```
This query will then produce:
```
[
  'kim', 'lin', 'maria', 'nell', 'oliver',
  'pat', 'quincy', 'roy', 'sam', 'tanya'
]
```
The guide then goes on and says,
> Because we are now specifying that the name must be greater than 'joy', we are guaranteed to get the next-highest result after 'joy'

Here's the problem -- what if there's more than one "joy"? Sure, the first one will be included in the first batch. But the next query will omit all the other "joy"s!

**Comment by dheimoz** [comment]
Hello @toyssamurai, I am positive that it is the way Mongo works. Do you thinks the implementation is wrong?
