### ISSUE TITLE
`limit` and `skip` view query options are ignored when `keys` are used, if the adapter is not http

### ISSUE THREAD

**Issue by dianabarsan** [pouchdb/pouchdb#8370]
### Issue
When running a `query` request, passing `keys` will always return the full set of results that match these keys, regardless of the passed `skip` and `limit` parameters. 

Relevant code: https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-abstract-mapreduce/src/index.js#L757

### Info
- Environment: node.js
- Platform: Linux
- Adapter: memory

### Reproduce

Setup:
- create a database using the memory adapter
- create a simple view and add some docs 
- query the view with `keys` and `limit` and notice that results are not limited
- query the view with `keys` and `skip` and notice the results are not skipped

Running the same code over a remote database works as expected. 

gist: https://gist.github.com/dianabarsan/ab9b903e3eae42089e730438e384e1da

**Comment by dianabarsan** [comment]
This has been already reported several times: https://github.com/pouchdb/pouchdb/issues/7976 and https://github.com/pouchdb/pouchdb/issues/7573

**Comment by ramblin-rose** [comment]
No stale-bot!

**Comment by ramblin-rose** [comment]
No stale-bot, no!

**Comment by AlbaHerrerias** [comment]
This issue was addressed by @ramblin-rose  in https://github.com/pouchdb/pouchdb/pull/8404. It has been merged to master and a new release will land soon. Thank you
