### ISSUE TITLE
Find query does not work when indexing on _id with indexeddb adapter 

### ISSUE THREAD

**Issue by paultranvan** [pouchdb/pouchdb#8384]
### Issue
After creating an index including `_id` in the fields, trying to query on this index with `find` always return `docs: []`, even though there are documents matching the query.

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB

### Reproduce

```
await db.post({name: 'test'})
await db.createIndex({index: { fields: ['name', '_id']}, ddoc: 'by-name-and-id'})
await db.find({selector: { name: 'test', _id: { $gt: null}}, use_index: '_design/by-name-id', sort: [{'name': 'asc'}]})
```
This will always return: `docs: []`

Note I reproduce the issue with the `indexeddb` adapter but not `idb`.

**Comment by dheimoz** [comment]
hey @paultranvan , would you mind creating a repo?
Thanks.
