### ISSUE TITLE
Find queries do not have the same behaviour than CouchDB on multi-fields index

### ISSUE THREAD

**Issue by paultranvan** [pouchdb/pouchdb#8385]
### Issue
There is a different behaviour between PouchDB and CouchDB when querying multi-fields index on a selector that does not include all the indexed fields. 
With PouchDB, it is expected that all the indexed fields exist in the selector, otherwise an error is returned.
With CouchDB, it is expected that all the indexed fields exist in the selector OR in the sort. Typically, with a `['foo', 'bar']` index, it is accepted to execute a find query with a selector including only `bar`, as long as `foo` is expressed in the sort.

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB 7.2.2
- Server: CouchDB 2.3.1

### Reproduce
```
await db.post({name: 'test', age: 42})
await db.createIndex({index: { fields: ['name', 'age']}, ddoc: 'by-name-and-age'})
await db.find({selector: { age: { $gt: null}}, use_index: '_design/by-name-and-age', sort: [{'name': 'asc'}]})
```
This will return an error: `{error: 'no_usable_index', message: 'There is no index available for this selector.'}`. 

However, the same query with the same index will successfully return the document on CouchDB.

**Comment by dheimoz** [comment]
hey @paultranvan thanks for reporting this. Will take a look.
I believe there are unresolved issues regarding this very same problem.

**Comment by Crash--** [comment]
Since you added `indexeddb` in the default package in order to get feedbacks and bugs. 

Is there a macro issue where we can link all the closed but not fixed issues related to `indexeddb`?
