### ISSUE TITLE
PouchDB-find with multi-layer

### ISSUE THREAD

**Issue by rcffc** [pouchdb/pouchdb#8386]
Suppose we have a couchdb document structured like this:
```
{
  "_id": "4234",
  "properties": {
      "active": "true",
  }
}
```
I have managed to use createIndex and find to access the `_id` field, which is quite trivial.

But how would I go about querying for example the property `active`? 
I unfortunately haven't found info about this on the web.

Help is appreciated, many thanks.

**Comment by dheimoz** [comment]
thanks @ramblin-rose
