### ISSUE TITLE
`_changes` heartbeat not timing out in PouchDB

### ISSUE THREAD

**Issue by adipascu** [pouchdb/pouchdb#8391]
### Issue
`_changes` heartbeat not timing out in PouchDB, if the HTTP TCP connection is kept open but no heartbeat (endlines) are being sent, PouchDB does keeps on waiting. I think it should timeout the connection.

This has the side effect of not establishing a fresh connection to get further changes, thus PouchDB is stuck with stale data.

### Info
- PouchDB: 7.2.2
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
I am using a CouchDB behind a reverse HTTP proxy ([koa-proxies](https://www.npmjs.com/package/koa-proxies)), I kill the CouchDB instance and my PouchDB live replication keeps the HTTP connection open waiting for data.

**Comment by dheimoz** [comment]
hey @adipascu 
To make sure I understand, even if you configure the "options.timeout" either at your Replication or Sync, do you still see the connection open?
https://pouchdb.com/api.html#replication
Advance Options -> options.timeout

I usually configure my options like this:

```js
const syncOptions = {
  batch_size: 5,
  timeout:30000,
  batches_limit: 2,
  live: true,
  retry: true,
  back_off_function(delay) {
    if (delay === 27000 || delay === 0) {
      return 1000;
    }
    return delay * 3;
  },
};
```
