### ISSUE TITLE
On Sync and Replication set conflicts=false

### ISSUE THREAD

**Issue by goltra** [pouchdb/pouchdb#8407]
I make a Sync from remote database to local and always get conflicts documents despite I set conflicts=true in Sync options

I'm not sure if is possible to do this. I don't want conflicts information en local database.

**Comment by dheimoz** [comment]
hello @goltra  should you need replication between a local db and a remote db, conflicts will arise. It is part of the nature of the Couchdb protocol and we always need to address them with a good strategy.
