### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by Bessonov** [pouchdb/pouchdb#8408]
Hello guys!

Last release was long time ago. There are security updates (like for node-fetch) and important fixes for `pouchdb-adapter-indexeddb`, which I'm awaiting. Is there any chance to release a new version?

**Comment by 4321ip** [comment]
7.2.2 version is incompatible with webPack5 because of uuid last version (uuid@8.3.2 required)

**Comment by strife-cloud** [comment]
I had the same problem as @4321ip, I had to tweak package.json and rebuild the package

**Comment by rasgo-cc** [comment]
Also looking forward to a new release, quite a lot of PRs already merged into master but not published yet.

On a side but related note: how could this be improved so releases at lest keep up with already merged PRs on a more frequent time basis? /cc @daleharvey @garrensmith @willholley @nolanlawson

**Comment by dheimoz** [comment]
Hello @rasgo-cc, thank you very much for the enthusiasm. I personally would love to have all suite test working before publishing a new release. Assisting with the missing tests would be the best way to speed up things here.
Cheers.

**Comment by janl** [comment]
I’ve started a Project™ to help us track which Issues/PRs we want to look at before calling it a release.

I started with what looked reasonable to me to see if we can get all these in, but it might be too big an effort, so I’d be open to dropping a few of these if we see they need more work that nobody wants to step up for: 

I propose that we plan two releases:

1. 7.3.0 that includes current `master` and a few more bugfixes / dep updates: https://github.com/orgs/pouchdb/projects/1/views/1
2. 8.0.0. which includes partial rewrites to ES6 syntax: https://github.com/orgs/pouchdb/projects/2/views/1

Does this make sense? Do you have more candidates to add to, or remove from 7.3.0 or 8.0.0?

**Comment by millette** [comment]
@janl Weird, https://github.com/pouchdb/pouchdb/projects shows 0 projects but the direct links to projects/1 and projects/2 (linked above) work.

**Comment by janl** [comment]
@millette super weird. I used the new Beta. That seems to have been a mistake. I’ll switch this over if issues persist.

**Comment by millette** [comment]
@janl Figured it out. The projects appear for the org, not the pouchdb project.

See https://github.com/orgs/pouchdb/projects?type=beta
