### ISSUE TITLE
[Question] Reduce default `revs_limit`

### ISSUE THREAD

**Issue by janl** [pouchdb/pouchdb#8409]
Hi all,

This is more often an open question than an issue:

How do we feel about reducing the default `revs_limit`?

`revs_limit` is used to figure out if different updates to the same document are ancestors of each other or not. If they can be found as ancestors, Pouch/Couch won’t create conflicts for them. If not, we get conflicts. The higher the `revs_limit`, the more conflicts can be avoided, especially for documents that get updated a lot on two independent instances).

CouchDB chose `1000` as the default `revs_limit` to cover a broad variety of use cases, including, someone takes a database offline on a sailing trip around the world and keeps using it, and after a year they replicate with a peer and no artificial conflicts are created.

That’s a very rare use-case and in practice, documents in PouchDB usually receive two orders of magnitude fewer updates between replications.

The downside of carrying around lots of revision ids is that network traffic for replication increases with every document update, and sometimes we even see runtime issues with long revision lists (see related issues below).

PouchDB usually copies CouchDB defaults and that has served it very well, but I feel this is one where we could deviate.

How do you all feel about reducing `rev_limit` to, say, `50` to take into account the realities of folks’s installations.

I would require a major version bump for this, and allow folks who have a reasonable case for longer rev lists to increase it again.

Related:
- https://github.com/pouchdb/pouchdb/issues/8298
- https://github.com/pouchdb/pouchdb/issues/8398
- Maybe: https://github.com/pouchdb/pouchdb/issues/8398

**Comment by ramblin-rose** [comment]
I agree a default of 1000 is a ton 'o revs and can result in some really sluggish scenarios.  However `rev_limits` is user configurable so it's not clear to me how this improves pouchDB.  Is the motivation to mitigate novice mistakes?

**Comment by dheimoz** [comment]
Hello +1 on lower the default revs_limit @janl 
As @ramblin-rose stated, it is configurable but it definitely makes sense for new users.
