### ISSUE TITLE
Bring back support for the chromium extension

### ISSUE THREAD

**Issue by LifeIsStrange** [pouchdb/pouchdb#8410]
Hi!
Can PouchDB developpers consider reviewing my pull request for bringing back the extension? The fix is quite simple.
https://github.com/pouchdb/pouchdb-fauxton-logic/pull/2
https://github.com/pouchdb/pouchdb-fauxton-chrome-extension/issues/17
(see also [my fork](https://github.com/LifeIsStrange/pouchdb-fauxton-logic), with the fix included on master)

**This extention could greatly improve the observability of PouchDB.**

the extension should be published back in the chrome store.
friendly pings:
@janl @jcoglan 

BTW there is a version of the extension online:
https://ma.rtendevri.es/fauxton/

here's a demo of it working:
![image](https://user-images.githubusercontent.com/12934716/141182021-9fa73649-3d7f-4019-b218-e0a3328a6e58.png)

**Comment by LifeIsStrange** [comment]
The extension can be used directly in chrome with this repository
https://github.com/LifeIsStrange/pouchdb-fauxton-chrome-extension
until the extension pass chrome webstore review

**Comment by dheimoz** [comment]
@LifeIsStrange added to the TODO list. Please, be patient. Thanks for the hard work, definitively it is worthy.

**Comment by LifeIsStrange** [comment]
update btw:
The chrome extension store has rejected my submisssion for the following reason:
> Violation reference ID: Purple Potassium
Violation: The following permission(s) need not be requested for the methods/properties implemented by the item:
tabs
How to rectify: Remove the above permission(s). The properties used by the items will continue to function even without requesting these permissions.
Relevant section of the program policy: Request access to the narrowest permissions necessary to implement your Product's features or services. Don't attempt to "future proof" your Product by requesting a permission that might benefit services or features that have not yet been implemented. (learn more)

I don't know wether the "tab" permission was needed in the first place.

**Comment by LifeIsStrange** [comment]
Thanks :) Unfortunately, I am busy with many projects so I won't actively improve the existing extension but sure I can maintain it if by maintaining it we mean keep it working as it was before.

**Comment by marten-de-vries** [comment]
No worries, I just wanted you to have the ability to push any changes you already made to the repo's without having to wait for me or someone else to merge your PRs.

If you want to use it to maintain the extension going forward that's great, but please don't in any way feel obligated to do so. :smile:
