### ISSUE TITLE
Feature Request: include a way to determine whether a local database exists without creating it

### ISSUE THREAD

**Issue by adipascu** [pouchdb/pouchdb#8411]
### Issue
Write the description of the issue here

### Info
- PouchDB: 7.2.2
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
```js
new PouchDB('test', {
  skip_setup: true,
});
```
This creates the IndexedDB named `_pouch_test`.

I looking how to check if a local database exists.
Also see: https://stackoverflow.com/a/40641635

**Comment by ramblin-rose** [comment]
The documentation clearly states that `skip_setup` only applies to *remote databases*. In other words `skip_setup` will prevent a remote client from creating a remote database. Nothing in the documentation states the call applies to local databases.

See [Options for remote databases](https://pouchdb.com/api.html#create_database)

**Comment by adipascu** [comment]
@ramblin-rose you are absolutely right, I misread the docs.

Should we keep this issue open as a feature suggestion?
Is a PR welcome for this?

**Comment by ramblin-rose** [comment]
I suppose any feature would be welcome? I agree this functionality would be very nice to have in that it may be useful to know if a database using a particular adapter exists, the latter being a complexity as it seems to me (but I could be wrong!) all adapters would need to implement the feature.  In the meantime if your use-case permits, consider the [allDbs plugin](https://github.com/pouchdb-community/pouchdb-all-dbs).

**Comment by dheimoz** [comment]
hello @adipascu as @ramblin-rose suggested, all PR are welcome. We might take a time to review them, because bandwidth problems, but the best way to keep Pouchdb alive is by contributing with PR's and fixes.
Thanks.
