### ISSUE TITLE
Remote Only Hangs

### ISSUE THREAD

**Issue by roociferSonOfTheMorning** [pouchdb/pouchdb#8412]
### Issue
I have pouchdb configured as described here https://rajsm139.medium.com/offline-first-app-using-ionic-pouchdb-couchdb-61ba14cace28 and it all works great. 

Get Call 1 -> return 1
Get Call 2 -> return 2
Get Call 3 -> return 3

```js
const remoteURL = "http://localhost:5984";

constructor(name) {
    this.remote = remoteURL + "/" + name;
    this.docCnt = 0;
    this.db = new PouchDB(this.name);

    let options = {
      live: true,
      retry: true,
      continuous: true,
      auto_compaction: true,
    };
    this.db.sync(this.remote, options);
 }
```

However when I configure the pouchdb to be only remote, the first get call is successful, but a following get calls hang indefinitely.
Calling the get again will then will flush the second call and return the third.  

Get Call 1 -> return 1
Get Call 2 -> Pending
Get Call 3 -> return 2 && return 3

```js
const remoteURL = "http://localhost:5984";

constructor(name) {
    this.remote = remoteURL + "/" + name;
    this.docCnt = 0;
    this.db = new PouchDB(this.remote);
 }
```

### Info
- Environment: Node.js
- Platform: Chrome / Electron
- Adapter: IndexedDB (w/e the default is)
- Server: CouchDB && PouchDB Server

**Comment by roociferSonOfTheMorning** [comment]
I used a boiler plate project to recreate the issue, https://github.com/roociferSonOfTheMorning/svelte-electron-boilerplate

./electron/collections/pouchdb.js  is where the code lives. 

If you run it as is, it has the issue, If you change the constructor back to the sync then it works great.

**Comment by roociferSonOfTheMorning** [comment]
I added: ```console.log("thie.remote", this.remote);``` and the result was: >this.remote http://localhost:5984/letterPositions

There is no proxy in between. My couchdb remote server is running locally on my ubuntu machine where I am running my electron app.

**Comment by dheimoz** [comment]
hey @roociferSonOfTheMorning so if I understand correctly, you are using Pouchdb as a Proxy or wrapper connection for a remote Couchdb, am I right? 
Are you doing a local replication?

**Comment by roociferSonOfTheMorning** [comment]
Correct, as a wrapper for a remote Couchdb without local replication.

**Comment by dheimoz** [comment]
Have you give it a try to nano?
https://www.npmjs.com/package/nano 

Or just the REST api. 
https://docs.couchdb.org/en/stable/api/index.html

For non-replication scenarios I believe the best way to handle communication is directly talking to Couchdb.

However, I have seen that we are missing some pieces to have Pouchdb working with Svelte. This is something we need to address in the near future.

**Comment by roociferSonOfTheMorning** [comment]
Thank you for the response! We did use the REST api, we did not find nano but that is very neat, thank you for linking that. 
We ended up moving the pouchdb interactions to the frontend and out of the electron and that was able to work for us.

**Comment by dheimoz** [comment]
@roociferSonOfTheMorning good to know. Do you need something else to review?

**Comment by roociferSonOfTheMorning** [comment]
Nope, thank you for your guidance!
