### ISSUE TITLE
🌟  Feature Proposal/Discussion: ActiveTasks

### ISSUE THREAD

**Issue by espy** [pouchdb/pouchdb#8422]
Hello PouchDB maintainers 👋

We (neighbourhood.ie) would like to propose a new PouchDB feature and use this space to discuss details with you.

## What
We would like to implement an `activeTasks` feature within PouchDB, analogous to the `_active_tasks` feature in CouchDB. 

## Why
Currently, there is little visibility into what PouchDB is doing with regard to (potentially) long-running tasks such as index building and replication. While it is possible to subscribe to sync events, we feel it would be helpful for developers to have a place where they can get instant answers to the question “what is PouchDB busy with and how long is it actually taking?” CouchDB’s Fauxton offers the active tasks page which is helpful in answering these questions, and we feel it would be useful if PouchDB did something similar.

## How
As a baseline, we want to make this as tiny and unobtrusive with as little performance overhead as possible. Our current idea is that there should be a registry on `PouchDB` that other modules can CRUD tasks to. This is purposely not an event emitter, but just an in-memory collection of task objects that you can read (poll) whenever you need to. In addition, we would make it opt-in, meaning that modules should only use `activeTasks` if it is explicitly enabled via `PouchDB.activeTasks.enable()`, which is similar to how `PouchDB.debug` is activated. 

If people want this to be subscribable, this functionality can be added via a plugin later.

### What is an active task?
A pojo with the following properties:
- `id`: a string set automatically on creation and passed back to the creator, a UUID for example
- `name`: a required string settable on creation, eg. “Building index `by-director` for database `studio-ghibli`”
- `started_at`: an ISO 8601 date string, set automatically on creation
- `updated_at`: an ISO 8601 date string, automatically updated on update
- `total_items`: a positive integer or zero, settable on create/update
- `completed_items`: a positive integer or zero, settable on create/update

### What can you do with an active task?
The registry is public on the `PouchDB` global, any module, plugin or adapter can use it. However, any consumers of this API should respect when `PouchDB.activeTasks.enabled` is `false` and not use it in that case. Additionally, the implementation can also ignore attempts to use it.

You can:

**1. Create** an active task by passing an object without an id to `create()`: 
```javascript
const myTaskId = PouchDB.activeTasks.create({
  name: 'Building index ABC for database XYZ',
  total_items: 133
})
```
This returns the task id for reference and future updates. It will ignore the keys `id`, `started_at` and `updated_at` if they are passed in. It is explicitly possible to create multiple tasks with the exact same name, since their existence might expose the fact that something in the calling module isn’t working as expected. If no name is passed in, no task is created.

**2. Update** an active task by passing in a partial activeTask object with an id to `update`:
```javascript
PouchDB.activeTasks.update(myTaskId, {
  completed_items: 4
})
```
This will merge the update payload with the existing task, overwriting existing values. It will ignore changes to `name`, `started_at` and `updated_at`. The feature should offer as few opportunities to break things as possible, therefore it might be worth just failing silently if an invalid id is passed in, in any case this should not throw any errors that might go unhandled and stop execution.

**3. Delete** an active task by passing in its id to `delete()`:
```javascript
PouchDB.activeTasks.delete(myTaskId)
```
This removes the task from the registry, if it exists. Same considerations about errors apply as in `update()` above.

**4. Read** all currently active tasks by calling `list()`:
```javascript
const tasks = PouchDB.activeTasks.list()
```
This returns an array of activeTask objects

### Where will `activeTasks` be used?
We would like to extend the index building and sync processes to report their progress to the new `activeTasks` API as part of this proposal.

### Additional Considerations
We want to provide the bare-bones functionality to make debugging and performance monitoring simpler. If necessary, nicer wrappers/plugins can be written on top of this implementation that observe or poll `activeTasks` and provide a prettier, more real-timey output. For now, all we aim for is a central registry to hold info about (long running) tasks.

### Request for Feedback, Next Steps
We’d be grateful for feedback on the proposal, both to implementation detail and overall intent. If there are no Very Strong Objections™ to the feature in general by this time next week, we would start the implementation then.

Thanks! 👋

**Comment by dheimoz** [comment]
hello @espy , I got the feeling this will be very beneficial for Pouchdb. 
https://docs.couchdb.org/en/stable/api/server/common.html#active-tasks

+1
