### ISSUE TITLE
Old versions of documents re-appearing

### ISSUE THREAD

**Issue by Daniel-Olivier** [pouchdb/pouchdb#8427]
### Issue
We delete documents a week after we finish processing them but then older versions of the document are re-appearing. This only effects some of the deleted documents

### Info
- Environment: hybrid (express-pouchdb running on a NodeJS server with multiple pouchdb instances in browsers syncing with it)
- Platform: Android Webview (Chromium)
- Adapter: IndexedDB
- Server: PouchDB Server running on NodeJS 14 with the LevelDB adapter

### Reproduce
We are still working on reproducing the issue

**Comment by Daniel-Olivier** [comment]
Is there any way of tracing which client synced a document through to the express-pouchdb server so we can then isolate troubleshooting to that client?

**Comment by sureshvv** [comment]
Are you purging the database too?

**Comment by dheimoz** [comment]
hello @Daniel-Olivier 
Please, take a look at this:

https://pouchdb.com/guides/conflicts.html#:~:text=In%20CouchDB%2C%20conflicts%20can%20occur%20in%20two%20places%3A,Let%27s%20call%20these%20immediate%20conflicts%20and%20eventual%20conflicts.

Hope it helps
