### ISSUE TITLE
Unable to fetch attachments using pouchdb.find

### ISSUE THREAD

**Issue by yashaswinibprasad87** [pouchdb/pouchdb#8429]
provide an example or documentaion to use attachments with selector
as below doesnot work

this.devDB.find({  selector: { type: "xyz" }})

**Comment by dheimoz** [comment]
Hello @yashaswinibprasad87 
Remember that Attachments are part of a Document. As the name implies, the attachments lives inside the documents. I wonder if you could elaborate your use case? Maybe you could store the attachments as stand alone documents and then use selectors to find the attachment.

https://www.javatpoint.com/pouchdb-add-attachment#:~:text=The%20putAttachment%20%28%29%20method%20is%20used%20to%20add,object%20is%20used%20to%20prepare%20attachment%20with%20documents.

**Comment by yashaswinibprasad87** [comment]
> Hello @yashaswinibprasad87 Remember that Attachments are part of a Document. As the name implies, the attachments lives inside the documents. I wonder if you could elaborate your use case? Maybe you could store the attachments as stand alone documents and then use selectors to find the attachment.
> 
> https://www.javatpoint.com/pouchdb-add-attachment#:~:text=The%20putAttachment%20%28%29%20method%20is%20used%20to%20add,object%20is%20used%20to%20prepare%20attachment%20with%20documents.

Worked . Thanks
