### ISSUE TITLE
iOS / Safari 401 unauthorized error when syncing 

### ISSUE THREAD

**Issue by sefyas** [pouchdb/pouchdb#8431]
### Issue
I am using PouchDB and CouchDB in an ionic application. While I can successfully sync local and remote databases on Chrome and Android, I get unauthorized error on Safari / iOS when I run the sync command. Below is a simplified version of my database service provider. 

```javascript
import PouchDB from 'pouchdb';
import PouchDBAuthentication from 'pouchdb-authentication';

@Injectable()
export class CouchDbServiceProvider {
    private db: any;
    private remote: any;
    constructor() {
      PouchDB.plugin(PouchDBAuthentication);
      this.db = new PouchDB('localdb', {skip_setup: true});
    }
    ...
    login(credentials) {
      let couchDBurl = 'URL of my couchDB database';
      this.remote = new PouchDB(couchDBurl); 
      this.remote.logIn(credentials.username, credentials.password, function (err, response) {
            if (err) { concole.log('login error') }
            else {
                let options = { live: true, retry: true, continuous: true };
                this.db.sync(this.remote, options).on('error', (err_) => { console.log('sync error')});
            }
      })
    }
    ...
}
```

In the code above, `this.remote.logIn(...)` is successful but `this.db.sync(...)` fails. I have checked the requests via the network tab of developer tools and I believe the issue is that the cookie that's retruned in the response header of `this.remote.logIn(...)` is not used by the subsequent calls (thus the unauthorized error). The issue is fixed once third-party cookies are enabled on Safari, which is not an option on iOS.

How can I fix this problem?

One potential solution I'm considering is overriding `fetch` to use native http client (i.e., an instance of `HTTP` from `@ionic-native/http`). It seems modifying http clients is a possibility (e.g., according to this [conversation](https://github.com/pouchdb/pouchdb/issues/7022#issuecomment-358642135)) but I'm not sure how to achieve that. 

### Info
- Environment: ionic/Angular
- Platform: Chrome/Safari/iOS/Android
- Server: CouchDB

**Comment by burotica49** [comment]
Hello,

I have the same problem with pouchDB authentication and VueJS.
Everything works fine except on Safari and iOS.

this.remote.login returns me the correct information, but this.remote.getsession returns me an empty userCtx.

I tested with Axios, when I query the getsession the first time it works and the second time userCtx empty

Best regard

**Comment by sefyas** [comment]
I posted the same question on [StackOverflow](https://stackoverflow.com/questions/70658479/how-to-change-the-http-client-used-by-pouchdb/70712452#70712452). The accepted answer does not address the core problem but it helped me get the authentication working.

**Comment by burotica49** [comment]
Do you have any code to share with me so that I understand how to solve the problem.

Indeed the cookie is not saved on Safari and iOS. It also doesn't seem to register on Chrome even with the "same_site=None" option, but sync and query works on Chrome but not on Safari and iOS

Best regard
