### ISSUE TITLE
Unable to sort with fields with default Index

### ISSUE THREAD

**Issue by yashaswinibprasad87** [pouchdb/pouchdb#8432]
this.devDB.createIndex({
            index: {
                fields: ['name', 'type', 'lastModifiedDate']
            }
        })

this.devDB.find({
                selector: { type: "xyz",  lastModifiedDate: {$gte: null} },
                sort:['lastModifiedDate']
            })

Result is below Error:

Error: Cannot sort on field(s) "lastModifiedDate" when using the default index
    at validateSort (index-browser.es.js:505)
    at index-browser.es.js:1246

Provide a solution to fix it, also it would be great help if any date sort example can be given , as date is not sortable if in this format ('2022-01-12T00:23:24.871020')

**Comment by janl** [comment]
it looks like your index is not being used. The error message suggests it falls back to the the default index instead of your index.
