### ISSUE TITLE
PouchDB Find

### ISSUE THREAD

**Issue by cpgb85** [pouchdb/pouchdb#8434]
I'm a bit confused about the pouchdb find library.  On the website for pouch, it says to do mango queries, do make sure you use the PouchDB find library, when you go to the github for it, it says it's no longer maintained for 7 years, and that was merged into the PouchDB library, but it hasn't been.  What am I missing here?

**Comment by ramblin-rose** [comment]
As noted under the [Changelog ](https://github.com/pouchdb/pouchdb#changelog) section of the README, visit the [Github releases page](https://github.com/pouchdb/pouchdb/releases) which is handy for the browser.  If you are using node then `npm i pouchdb` is all you need.

I believe by "merged" it is meant that it is not maintained as a separate plugin - it is now part of the mainline build.

**Comment by natcohen** [comment]
AFAIK, plugins are maintained within this repo (https://github.com/pouchdb/pouchdb/tree/master/packages/node_modules) and still need to be added as a plugin: `PouchDB.plugin(require('pouchdb-find'));`

**Comment by Guilleanto** [comment]
Hello, Following the advice I find this error in the log

Can't find variable: self

similar to this image

![image](https://user-images.githubusercontent.com/18471149/155040679-1d646913-595f-41e2-808a-747594b10dec.png)
