### ISSUE TITLE
uuid@8.1.0 TypeError

### ISSUE THREAD

**Issue by roman-int3** [pouchdb/pouchdb#8435]
### Issue
Please upgrade uuid for latest version for prevent errors:
TypeError: Cannot read properties of undefined (reading 'v1') at eval pouchdb-utils

### Info
https://github.com/quasarframework/quasar/discussions/10471

### Reproduce
https://github.com/roman-int3/app

**Comment by AlbaHerrerias** [comment]
The package `uuid` was upgraded to the latest `8.3.2` in this PR https://github.com/pouchdb/pouchdb/pull/8254 and merged to master, therefore I'm closing this issue. We're working in a new release, it will land soon. Thank you.
