### ISSUE TITLE
PouchDB relying on vulnerable version of node-fetch

### ISSUE THREAD

**Issue by rdwoodring** [pouchdb/pouchdb#8440]
### Issue
PouchDB relies upon a [vulnerable]( https://github.com/advisories/GHSA-r683-j2x4-v87g
) version of node-fetch. PouchDB's package.json has the node-fetch dependency pinned at 2.6.0 as of v7.2.2. It looks like master has it pinned at 2.6.4. The vulnerability was patched in node-fetch 2.6.7

### Info
- Environment: Node & browser
- Platform: All
- Adapter: All
- Server: All
- Version: 7.2.2

### Reproduce
1. Run `npm audit`

Expected: No vulnerabilities
Actual: node-fetch vulnerabilities in pouchdb, pouchdb-find, pouchdb-fetch, and pouchdb-abstract-mapreduce

**Comment by joemc11** [comment]
This is a high vulnerability, so would be great to get this fixed and published.  What is the estimated time frame for this fix.

**Comment by rdwoodring** [comment]
@karlwestin it might not really be up to you, but do you have any idea when we might get a release with [the PR that resolves this issue](https://github.com/pouchdb/pouchdb/pull/8448)?

Thanks

**Comment by AuracleTech** [comment]
> Any idea when we might get a release with [the PR that resolves this issue](https://github.com/pouchdb/pouchdb/pull/8448)?

Same. I am waiting for this update to update my apparatus.

**Comment by lgarron** [comment]
> > Any idea when we might get a release with [the PR that resolves this issue](https://github.com/pouchdb/pouchdb/pull/8448)?
> 
> Same. I am waiting for this update to update my apparatus.

Also would love to see a fix. Given that the "hard" part (fixing it in the codebase) is already done, it's a little hard not to see the current situation as `pouchdb` effectively being unmaintained. :-/

Node that `npm audit fix --force` would actually *downgrade* to `pouch-db@7.0.0`, which doesn't sound great.

**Comment by AlbaHerrerias** [comment]
`node-fetch` was upgraded to `2.6.7` in this PR https://github.com/pouchdb/pouchdb/pull/8448 and merged to master, therefore I'm closing this issue. We're working in a new release, it will land soon. Thank you.

**Comment by lgarron** [comment]
Any update on that release? 😃

**Comment by lgarron** [comment]
> We're working in a new release, it will land soon. Thank you.

*poke* 🥺
Is this still planned?

**Comment by garethbowen** [comment]
It's landed: https://pouchdb.com/2022/04/13/pouchdb-7.3.0.html
