### ISSUE TITLE
Pouch DB PUT doc insert issue  -  question

### ISSUE THREAD

**Issue by Dinesh101041** [pouchdb/pouchdb#8446]
### Issue

i am working on small form in electron and pouch db

when we inserting a data to db , until the nineth  doc it inserting perfectly , but on 10 the doc  it is inserting and second position of doc instead on inserting into last

images :

form ui

<img width="459" alt="Screenshot 2022-01-29 at 7 25 30 PM" src="https://user-images.githubusercontent.com/59551894/151663728-14de0020-16bf-49f9-905a-0e81e723b4be.png">

before inserting the 10th doc

<img width="690" alt="Screenshot 2022-01-29 at 7 27 07 PM" src="https://user-images.githubusercontent.com/59551894/151663780-bb5d5917-0919-4d79-b6c3-f908e8861225.png">

After inserting 10 th doc

<img width="606" alt="Screenshot 2022-01-29 at 7 26 26 PM" src="https://user-images.githubusercontent.com/59551894/151663755-61030b9d-8e78-4847-83d5-751d61ef1bd5.png">

here attached the js code 

```
// form submit
const form = document.getElementById("form1");
form.addEventListener("submit", dbsubmit);

function dbsubmit(e) {
   e.preventDefault();
   //   getting values from form
   var Sno = document.getElementById("number").value
   var date = document.getElementById("date").value;
   var Time = document.getElementById("time").value;
   var Trip = document.querySelector('input[name="Trip"]:checked').value;
   var TripType = document.querySelector('input[name="Type"]:checked').value;
  


   // assigning form values to db table names
   var doc = {
       _id: Sno,
       Date: date,
       time: Time,
       trip: Trip,
       triptype: TripType,
   };

   // inserting to db
   db.put(doc, function(err, response) {
       if (err) {
           return console.log(err);
       } else {
           console.log("Document created Successfully", response);
           }
   });

}

```

inserting until nineth 9th doc its perfectly inserting 
but when we insert the 10 th doc it is inserting in second position

i debuged  , but cannot able to find solution can anyone help me with the solution 

Thank you

### Info
- Environment: Electron js
- Adapter: leveldb
- Server: PouchDB Server

**Comment by ramblin-rose** [comment]
What you are observing is correct.  This is explained thoroughly in the CouchDB documentation [3.2.2.5. Collation Specification](https://docs.couchdb.org/en/stable/ddocs/views/collation.html?highlight=collation#collation-specification)

> Comparison of strings is done using ICU which implements the Unicode Collation Algorithm, giving a dictionary sorting of keys. **This can give surprising results if you were expecting ASCII ordering.**

<sup>_emphasis mine_</sup>

A thorough read of that section will provide a solid grasp of the collation rules.

**Comment by Dinesh101041** [comment]
> What you are observing is correct. This is explained thoroughly in the CouchDB documentation [3.2.2.5. Collation Specification](https://docs.couchdb.org/en/stable/ddocs/views/collation.html?highlight=collation#collation-specification)
> 
> > Comparison of strings is done using ICU which implements the Unicode Collation Algorithm, giving a dictionary sorting of keys. **This can give surprising results if you were expecting ASCII ordering.**
> 
> _emphasis mine_
> 
> A thorough read of that section will provide a solid grasp of the collation rules.

any way to solve this i cant able to find the correct way to sort the numbers in correct order can you help me with that

**Comment by ramblin-rose** [comment]
Best asked on https://stackoverflow.com

**Comment by janl** [comment]
In PouchDB, document ids must be strings, they can not be numbers.

In order to do what you want, you need to create a view with a map function that looks like this:

```js
function (doc) {
  emit(Number(doc._id)
}
```

this will give you a view query result that is sorted by the number value of the document `_id`
