### ISSUE TITLE
pouchdb-replication - Replication does not check integrity of attachments

### ISSUE THREAD

**Issue by pturner1989** [pouchdb/pouchdb#8466]
### Issue
When replicating from remote to local, PouchDB generates a new digest and saves it to the database without comparison against the digest reported by remote. This means that corrupted downloads are saved to the database, which has happened to me in production on a few occasions now.

I hope to do some work on this next week, but any suggestions would be most welcome. I'm not sure the best place to compare the digests yet, or if there's a reason it's not being done already?

### Info
- Environment: All
- Platform: All
- Adapter: indexeddb, leveldb, idb
- Server: All

### Reproduce
Have added repo to reproduce the error here [pturner1989/pouchdb-issue8466](https://github.com/pturner1989/pouchdb-issue8466)

The "test" database (PouchDB SQLite) in this repo contains a document with an attachment which has a false digest. When replicating into PouchDB the attachment will be given a new digest instead of failing.

You will see the document replicates successfully but the digests do not match. In the event this was a corrupted transfer a new revision (or full resync) is required to rectify.

**Comment by jo** [comment]
We just have to keep in mind that calculating checksums for attachments during replication will have a negative impact on replication performance.

Would it perhaps be feasible to make this optional?

I don't know exactly how CouchDB itself behaves here, that would be interesting to find out as well. As far as I know, at least the digests are overwritten when documents with attachment stubs and attachments are uploaded via the '/db/doc` api. But that would have to be checked again as well.
