### ISSUE TITLE
Cannot set property type of #<Blob> which has only a getter

### ISSUE THREAD

**Issue by TechplexEngineer** [pouchdb/pouchdb#8469]
### Issue
When attempting to sync attachments I'm getting `Cannot set property type of #<Blob> which has only a getter` in the browser console.

Tracing the error back into the code it seems the problematic bit is:
https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-http/src/index.js#L630-L633

If I modify the files in node_modules in my project and remove the code index.js#L630-L633 that seems to be marked for removal the sync works as expected.

Another workaround is to set `process.browser = true` execute the sync then restore with `process.browser = undefined`

### Info
- Environment: svelte-kit browser single page application
- Platform: chrome 100 and android web view
- Adapter: idb
- Server: CouchDB
- Plugin: pouch-adapter-http

<!--
### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/
--!>

**Comment by pturner1989** [comment]
This has a PR in the pipeline: https://github.com/pouchdb/pouchdb/pull/8336

Just waiting for the next release.

**Comment by AlbaHerrerias** [comment]
Thanks to @pturner1989 a fix has been merged to master in PR https://github.com/pouchdb/pouchdb/pull/8336, therefore I'm closing this issue.
