### ISSUE TITLE
bulkDocs API doesn't accept sparse arrays of docs

### ISSUE THREAD

**Issue by enquora** [pouchdb/pouchdb#8475]
### Issue
The `bulkDocs` API throws an error when invoked with a sparse array
(items which have been removed using the `delete` keyword and are thus undefined).

### Info
Without yet looking at the code, this seems to apply to all platforms and adaptors

While the docs array can be condensed in user code prior to invoking `bulkDocs`, there isn't an obvious reason for PouchDB not to do so itself.
It is likely this can easily be patched, if there is no reason not to do so.

**Comment by janl** [comment]
I would agree that PouchDB should handle this gracefully. This is a great beginners Issue.

**Comment by subhadipghs** [comment]
I would like to see this issue. Thank you
