### ISSUE TITLE
What happened to pouchdb-debug?

### ISSUE THREAD

**Issue by pubkey** [pouchdb/pouchdb#8485]
During the last pouchdb release `7.3.0`, the module `pouchdb-debug` was not updated to version `7.3.0`.
Also the package is no longer in https://github.com/pouchdb/pouchdb/tree/master/packages/node_modules

Is it deprecated now or should we just use the old version of it?

**Comment by AlbaHerrerias** [comment]
Looks like it was removed in a previous release https://github.com/pouchdb/pouchdb/commit/262d751d55357aad238dd219bae5b8e203af473a
