### ISSUE TITLE
Is there support for the view "multiple queries" endpoint?

### ISSUE THREAD

**Issue by lyonzy** [pouchdb/pouchdb#8500]
Every so often I find myself in a position to get good use out of getting a set of start/end pairs from a view. This is implemented in the REST API:
https://docs.couchdb.org/en/latest/api/ddoc/views.html#api-ddoc-view-multiple-queries

```

POST /db/_design/ddoc/_view/viewname/queries HTTP/2
Host: couchdb

 {
   "queries": [
     { "startkey": "r1p", "endkey": "r1r" },
     { "startkey": "r2", "endkey": "r3" }
   ]
 }
```

But I can't see support for it in PouchDB. Is it implemented somewhere I haven't found yet?

Related CouchDB PR: https://github.com/apache/couchdb/pull/2173

**Comment by Terreii** [comment]
No, it is not yet implemented.
