### ISSUE TITLE
how to delete all revisions of a document known by its id

### ISSUE THREAD

**Issue by pedefe** [pouchdb/pouchdb#8502]
Hello,

I know the 'id', but not the list of existing revisions.
But I wish to delete all in one instruction.
How to ?

Best regards.

**Comment by souvik666** [comment]
@pedefe  hello, please refer this [updating-deleting ](https://pouchdb.com/guides/updating-deleting.html)

**Comment by pedefe** [comment]
Ok, I will use this solution.
Thanks.
