### ISSUE TITLE
New IndexedDB Adapter save two more  attachments with same MD5, the backend file system will save multiple version

### ISSUE THREAD

**Issue by suziwen** [pouchdb/pouchdb#8504]
New IndexedDB Adapter save two more  attachments with same md5, the backend file system will save two version.

And idb Adapter will deduplicated same MD5 attachments to one version.  Is it new IndexedD Adapter also support this feature?

[What data types does PouchDB support?](https://pouchdb.com/faq.html#data_types)

>  Attachments are deduplicated based on their MD5 sum, so duplicate attachments won't take up extra space.
> To truly remove an attachment from the data store, you will need to use [compaction](http://pouchdb.com/api.html#compaction) to remove document revisions that reference that attachment.

**Comment by jo** [comment]
The new indexeddb adapter does not deduplicate attachments across documents.
