### ISSUE TITLE
How to detect IDB adapter for existing DB?

### ISSUE THREAD

**Issue by kiyanovsky** [pouchdb/pouchdb#8510]
### Issue
I have an existing user base using 'idb' adapter. For new users, I want to create DB with 'indexeddb' adapter. I need to find a way to figure out what adapter is used for the existing DB, as it may be either of those two.

So, the idea is to open it via 'indexeddb' and if there is an error, then open it with 'idb'. The thing is, I can't catch the error with invalid adapter, this one:
`Uncaught Error: Incorrect adapter: you should specify the "idb" adapter to open this DB
    at IDBOpenDBRequest.openReq.onupgradeneeded`

Instead, I'm catching the error:
`DOMException: Version change transaction was aborted in upgradeneeded event handler`

1. I don't know if the caught error is always an evidence of an incorrect adapter.
2. Even though, I don't want to have uncaught errors in the program.

**Question**
How do I catch the "Incorrect adapter" error?
or
Is there a different way to determine the existing DB's adapter?

### Info
- Environment: (browser)
- Platform: (Chrome)
- Adapter: (idb/indexeddb)

### Reproduce
Code is on [codepen](https://codepen.io/kiyanovsky/pen/JjpyyLJ?editors=0010)

**Comment by kiyanovsky** [comment]
Thank you a lot, @filionf, I'd never get it done by myself!  The example is very detailed and commented. Do you mind if I ask this question on Stackoverflow, and then you put this answer there as well, if it makes sense?

The only thing, I can't figure out how Math.pow is the maxIdbVersion? Could you please elaborate?

**Comment by filionf** [comment]
Sure, go ahead with StackOverflow and let me know.

The maxIdbVersion value is coming from this file within the indexeddb adapter: https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-indexeddb/src/setup.js

Basically, PouchDB databases that are created with the indexeddb adapter have their version higher the Math.pow(10, 13).
Perhaps I should have named that variable minIndexedDbVersion instead.

**Comment by kiyanovsky** [comment]
I've posted this question on [Stackoverflow](https://stackoverflow.com/questions/72482111/how-to-detect-pouchdb-indexeddb-adapter-for-existing-db). Thank you for the prompt reply, @filionf, and please feel free to close this issue.
