### ISSUE TITLE
M1 support

### ISSUE THREAD

**Issue by sirily11** [pouchdb/pouchdb#8526]
### Issue
Hi I encountered the following issue when i trying to install pouchdb.
`node_modules/.pnpm/leveldown@5.6.0/node_modules/leveldown: Running install script, failed in 766ms`

### Info
- Environment: Browser on MacOS M1 Max with pnpm
- Node Version: v16.3.0

Full error log
```
node_modules/.pnpm/leveldown@5.6.0/node_modules/leveldown: Running install script, failed in 766ms
.../node_modules/leveldown install$ node-gyp-build
│ node:events:371
│       throw er; // Unhandled 'error' event
│       ^
│ Error: spawn node-gyp ENOENT
│     at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
│     at onErrorNT (node:internal/child_process:480:16)
│     at processTicksAndRejections (node:internal/process/task_queues:83:21)
│ Emitted 'error' event on ChildProcess instance at:
│     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
│     at onErrorNT (node:internal/child_process:480:16)
│     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
│   errno: -2,
│   code: 'ENOENT',
│   syscall: 'spawn node-gyp',
│   path: 'node-gyp',
│   spawnargs: [ 'rebuild' ]
│ }
└─ Failed in 766ms
Progress: resolved 1035, reused 1011, downloaded 0, added 0, done
 ELIFECYCLE  Command failed with exit code 1.
```
### Fix

I tried manually installing the leveldown v5 and shows exactly the same error. However,  after I install the latest version of leveldown, the error is gone.

**Comment by anmavrid** [comment]
Similar issue: Pouchdb does not run on Apple M1 architectures. To run it successfully we need leveldown version ^6.0.3 but pouchdb requires leveldown version 5.6.0 (as listed in the package.json file).

**Comment by rmdstudio** [comment]
Same here; we have been having problems getting PouchDB to work on our new Mac M1 machines.

**Comment by taratatach** [comment]
This is still relevant.

**Comment by garethbowen** [comment]
I don't have an M1 to test. If one of you could get it working on your hardware and submit a PR that'd be very helpful.

**Comment by taratatach** [comment]
I don't have that either sadly.

**Comment by adueck** [comment]
It's working fine for me using a M1 MacBook Air with `node v18.13.0` and yarn.

**Comment by taratatach** [comment]
@adueck are you sure you're not running an x86_64 version with the compatibility layer?

**Comment by adueck** [comment]
Yes just checked `process.arch` is `arm64`, I'm running it natively. Interesting when using `create-react-app` w/ `webpack` I have to use `node@16`. But with `vite` (which [I have to heavily shim for PouchDB](https://github.com/vitejs/vite/issues/9703#issuecomment-1418261670)) I can use `node@18`.

**Comment by lunedam-git** [comment]
I got round this - eventually - by following some tips from the NVM github readme. Basically I'd been stuck using Node 14 for some time when using Pouchdb due to the leveldown problem but the likes of Angular (which I use pouchdb in) started requiring more recent Node versions.

Anyway. I ended up installing an x64 version of Node 18 which is happy with everything:

Used nvm and uninstalled the arm64 node 18 version I had.
Temporarily changed to x64 in zsh by "arch -x86_64 zsh"
Installed node 18 again with "nvm install v18.16.0 --shared-zlib"

Now my zsh 'arch' is arm64 whilst my Node process.arch is x64.

Just as a footnote though. I know of a friend who also has an M1 and the arm64 version of Node 18 and they have no problem at all with installing Pouch and its required version of leveldown.

**Comment by an9949an** [comment]
Any news?
Probably the only thing should be done is updating leveldown to 6. Current version is 5.6 which don't support mac arm, but starting from 6.x macos arm prebuilds was added.

**Comment by ki0** [comment]
Same issue here.

**Comment by shanghaikid** [comment]
same issue here

**Comment by an9949an** [comment]
> same issue here

I temporally fixed it by manual putting universal binary of `leveldb` instead of x86 on building step. But problem is versions mismatch (`leveldb` support it from v6 only). I checked `leveldb` commits and looks like nothing breaking. I feel uncomfortable because of that, but it works for now.

**Comment by shanghaikid** [comment]
I follow this, it works:

1. Use Rosetta 2: You can try running your terminal under Rosetta 2, which allows a Mac with Apple silicon to use apps built for an Intel-based Mac. To open Terminal through Rosetta, find Terminal in Finder (usually in the /Applications/Utilities folder), press Command+I to get info, then check the box labeled "Open using Rosetta."

2. You might need to reinstall Node.js and npm  or yarn while Terminal is running under Rosetta 2.

3. `yarn add pouchdb` works.

**Comment by an9949an** [comment]
@shanghaikid Of course it works thru Rosetta but the main problem is native ARM support for app which is not possible for now without horrible hacks like I described previously.

**Comment by shanghaikid** [comment]
> @shanghaikid Of course it works thru Rosetta but the main problem is native ARM support for app which is not possible for now without horrible hacks like I described previously.

Yeah, but all I need is that I am able to do some development on my mac, our app is usually running on Linux, so that is enough for me.

**Comment by danielberndt** [comment]
In case you're not relying on leveldb for your use case you can either user `pouchdb-browser` which runs fine on M1.

For testing purposes I'm using this setup:

```js
import {expect, test} from "vitest";
import PouchDB from "pouchdb-core";
import memory from "pouchdb-adapter-memory";

PouchDB.plugin(memory);

test("do it", async () => {
  const db = new PouchDB("test", {adapter: "memory"});
  ...
```

**Comment by an9949an** [comment]
Are there any plans to resolve this? Probably the only thing needed is leveldown updating. Am I wrong?

**Comment by garethbowen** [comment]
@an9949an Are you able to submit a PR to update leveldown? If you can test it on your M1 and verify it works, and it passes the test suite, we can get it merged and released.

**Comment by an9949an** [comment]
@garethbowen I tried to do something but stuck at the point where I don't have enough project knowledge to decide what to do. Everything I found available here https://github.com/pouchdb/pouchdb/pull/8845

**Comment by garethbowen** [comment]
Merged ready for release.
