### ISSUE TITLE
pouchdb and pouchdb-node both fail to build and/or run via webpack

### ISSUE THREAD

**Issue by elverskog** [pouchdb/pouchdb#8527]
### Issue
I'm experiencing problems getting a server side version of pouch running.
My dream is largely polymorphic web-app code (with SSR) where client and server use their own pouchdb instance and both sync to a couchdb instance. To me this seems to be the "killer app" for pouch but maybe I misunderstand how it is intended to work.

I suspect the below may be considered an environment issue (and not an issue in the code) but as much as I love pouch I have been having trouble with getting it working server-side inside any framework. I can get it built/running with the zero other dependencies as esentiall a test in just node and webpack but outside that it has become a dead end so far. Any feedback would be much appreciated.

### Info
pouchdb fails with _on node run_ with:
```
Error: No native build was found for platform=linux arch=x64 runtime=node abi=108 uv=1 libc=glibc
...
at /home/ee/code/marko-test/build/index.js:42482:3
Node.js v18.4.0
```
_I've read that pouchdb (the main version) may not support some later versions of node. Is this correct_?

pouchdb-node fails _on build_ with a long series of polyfill errors
`webpack < 5 used to include polyfills for node.js core modules by default`
...for a a long list of native node modules

It is possible to get it to build by setting resolve>fallbacks in webpack's config...or target=node seems to also work.
But I'm trying to avoid overwriting the frameworks build config (currently marko but he same applies elsewhere).

**Comment by treestructure** [comment]
for me it helped alot adding this to my webpack.config.json:

    externals: {
        'pouchdb': "require('pouchdb')"
    },
