### ISSUE TITLE
Documentation on implementing PouchDB adapters

### ISSUE THREAD

**Issue by swittk** [pouchdb/pouchdb#8533]
### Issue
Write the description of the issue here
I'm attempting to implement a PouchDB adapter for [abstract-level](https://github.com/Level/abstract-level), which is essentially what the `level` team considers to be the successor to `leveldown`.

However, I can't find much documentation or types as to what methods I need to implement, which ones are required/optional, or the parameters, etc.
``

### Info
- Environment: browser/React-native
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: leveldb

### Reproduce
- not relevant

**Comment by Productivix** [comment]
I do not think that there is a will to develop PouchDB on React-Native : at this time nothing works !

**Comment by swittk** [comment]
I did manage to get PouchDB on RN working by using a `abstract-level` compliant store. Repo's [here](https://github.com/swittk/react-native-leveldb-pouch-adapter), and it's backed by my adapter for `react-native-leveldb`, and a slightly modified source from `pouchdb-adapter-leveldb` to use `Level` database instead of `Leveldown` (which is now obsolete).
