### ISSUE TITLE
Is it possible to ignore special docs for synchronization?

### ISSUE THREAD

**Issue by pigochu** [pouchdb/pouchdb#8538]
I have the following two types of documents.
I want `type1` will sync to couchdb or sync-gateway. `type2`  will ignore sync , but type2 still keep in local.
Is it possible ?

type1
```json
{
    "type": "type1",
   // more ...
}
```
type2
```json
{
    "type": "type2",
   // more ...
}
```

**Comment by endyjasmi** [comment]
maybe you can try filtered replication? you can find more information here https://pouchdb.com/api.html#filtered-replication

**Comment by pigochu** [comment]
@endyjasmi 
thanks for your help
