### ISSUE TITLE
The bots have taken over.

### ISSUE THREAD

**Issue by DarrenCook** [pouchdb/pouchdb#8542]
### Issue

The mindless Github bot keeps marking issues stale and closing them.

### Reproduce

Open an issue.
Wait 60 days. It will be marked stale.
Comment as requested.
Wait 7 days. It will be closed.

### Desired Behaviour

Leave the issues as open, so people can see them, and hopefully add more information (even "works for me with X,Y,Z configuration" is the most basic but most useful way for someone to contribute!)  and so if a new developer joins the project, they can see what is not resolved. 

Don't set the project the unrealistic goal of fixing all bugs within 60 days, when there appear to be no active maintainers currently. It is a mature project, so remaining bugs are likely to be obscure corner cases, that will take time to narrow down.

At the least, don't tell me to comment to stop it being closed, then close it anyway.  (There is no way for me to clear the stale flag.)

**Comment by ramblin-rose** [comment]
(This response also appears on #8525)

The [documentation](https://pouchdb.com/api.html#create_database) for `auto_compaction` states

> auto_compaction: This turns on auto compaction, which means compact() is called after every change to the database. Defaults to false.

That's some deliberate language and answers your questions.  `auto_compaction` is a run-time property (it is not persistent) thus it is enabled or disabled when creating a pouchDB instance.  

Regarding `auto_compaction` do note as [mentioned here](https://pouchdb.com/guides/compact-and-destroy.html#auto-compaction)
>This feature is only available in local databases, not remote ones. On remote databases, the auto_compaction option will do nothing.

**Comment by bean5** [comment]
I agree. Please reopen tickets.

**Comment by alxndrsn** [comment]
Stale-bot has been disabled by https://github.com/pouchdb/pouchdb/commit/8e08a14cb2706ca8ebbd587aa43b055d670b9383 :partying_face:
