### ISSUE TITLE
Replication always starting from 0 when there was a change in the selector

### ISSUE THREAD

**Issue by madhukudala** [pouchdb/pouchdb#8545]
### Info

- Environment: Electron/Angular
- Platform: Windows Desktop Application
- Adapter:  idb
- Server: CouchDB

### Versions
- CouchDB: 7.3.2 
- Electron: 13.0.0 
- CouchDB: 3.2.2
- Angular: 12 

### Issue
Recently we have been receiving a lot of emails from the users saying the application is **performing very slowly** after we start the replication (When users have 50K+ documents). After debugging we came to know that whenever we add a new project to the user it replicates slowly even though there is a **single document change**.

To replicate data from central CouchDB to PouchDb we are using a selector in the replication options which will query and fetch the documents that are related to the user.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/7322186/190392386-0b455879-b5bd-4672-b93c-f081295be8e7.png)

Below is the structure of the selector we are passing in the above image.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/7322186/190392487-fd54edf5-07b6-4d77-96d8-9554d4fa1d55.png)

We observed that whenever there is a change in the selector query the replication of data starts from the beginning. 

The existing _local/id is neglected, and the pouch is creating a new _local/id and trying to get it. As it was a new one it returned the error message as 404 and created a new checkpoint and started replication from the beginning.

There are few users for us whose project list crossed 250 and the total number of docs is more than 2 lakhs. New projects will be added to their list every day. Once they log in it **takes more than 6 hours** for the entire process **to get completed even though there is only one project document added**.  

So, we are requesting PocuhDB team to look at the above issue and help us to solve this major performance issue when there was a change in the selector. 

**_NOTE: IF THERE IS NO CHANGE IN THE SELECTOR IT IS PERFORMING WELL WITHOUT ANY ISSUE_**

### Reproduce
1. Start replication with the selector option
![MicrosoftTeams-image](https://user-images.githubusercontent.com/7322186/190392386-0b455879-b5bd-4672-b93c-f081295be8e7.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/7322186/190392487-fd54edf5-07b6-4d77-96d8-9554d4fa1d55.png)

2. It will create a _local/id  checkpoint and updates it every time until replication completes

3. Now update any one document that doesn't impact the selector.
4. The data will replicate only updated document by reading the checkpoint created before in step 2 and it will update the checkpoint created in step 2

5. Now update the selector and do a change in any one document
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/7322186/190396040-2cec7d74-8d33-4c13-8050-8aef8d00e92c.png)

6. Now you can observe that it will create a new _local/id and replicate all the documents again from the beginning
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/7322186/190399880-5c9e6abc-ba19-4b79-93f1-91010bf38257.png)

7. Here it is creating a new checkpoint and updating it like in before steps and we are not sure it is utilizing the old created checkpoint in step 2

**Comment by SourceR85** [comment]
@madhukudala
this behavior is intended by PouchDB:
To create deterministic "checkpoints", PouchDB computes a hash by the database ids and the replication options.
Source: [pouchdb-generate-replication-id](https://github.com/pouchdb/pouchdb/blob/3fe71b036a37f3cf983f47937bd9ccd0788fead6/packages/node_modules/pouchdb-generate-replication-id/src/index.js#L39)

Changing the selector results in a new IndexedDB database (in your case: whenever the "projectNumber" changes, a new database is created and filled up with `50K+ documents` and then PouchDB derives the _design-docs into indices which will then create even more client-side databases).

My suggestion for your problem is a design change:
- split your database into "general data" related database(s) and "project"-related databases.
- replicate databases that are relevant for your application and the user. (Remember to call `.destroy()` on the local PouchDB instances, after the user is removed from a project).
- loop your queries over all "project" databases (this should be a nice job for a generator function*: loop over the result.docs and yield every doc).

**Comment by madhukudala** [comment]
@SourceR85 Thank you for your reply.

We already divided the general data into the separate master database. Our application DB contains only the project(s) information.

As per your suggestion if we go with the project-wise database below are my concerns 

1. As I mentioned before each user may have a maximum of 250 projects at a time. Is it okay to create 250 databases along with 3 indexes(250*4 = 1000  databases)? 

3. How can we maintain live replication of each project? The only way I can think of for now is that whenever the project was open we have to replicate the data and keep it live as long as the user is performing actions in that project. Here the major problem is that when there are bulk document changes happening in the project it may take approximately 5 min+ to replicate and update the indexes. Which will lead to another performance issue.

FYI, For each project, we may have approximately 5000 documents.

The point which I do not understand is **why we have to replicate everything from the beginning when there was a change in the replication options**. Can't we use it from where it was last synced?

@daleharvey @nolanlawson any suggestions from your side?

**Comment by SourceR85** [comment]
Hi again @madhukudala 

I had to correct my previous comment: replication didn't create a new index...
(I just do this through code-generation in my project to keep the queries fast).

Here's another mind game:
```
create unique selectors for each project (just one `projectNumber` per selector)

for each relevant project:
  replicate the project (not live) with the selector

set a timeout to check project-assignment and repeat that replication loop
```
So, when you add a project, just the first iteration is massive.

**Comment by madhukudala** [comment]
@SourceR85 Let me try this idea and will update you on the results.

**Comment by madhukudala** [comment]
@SourceR85 The solution which you suggested is working fine. We did the changes but need to test the impact points. I will let you know if there are any issues with this approach.

Thank you once again.

**Comment by madhukudala** [comment]
@SourceR85 We noticed a strange issue while doing this change see the below image. Whenever we start the replication it was hitting the changes API and takes too much time and sometimes it did not end also until it receives a change from the remote DB. The above solution solved a problem but we noticed another problem

Do you know why it was taking too much time? See the below image for your reference
Few requests took 1 min+ just to get 500 docs and another request is 14+min(which is not ended until it receives a change)

FYI, It takes time only for the first request after starting the replication. It means to replicate 100 projects it's taking 100 min on average.

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/7322186/191232286-b5289c14-2fc8-4850-b90c-afad3e321ef3.png)

**Comment by SourceR85** [comment]
@madhukudala It's a bug.

Please open a new issue for this (since this problem is barley related to your original issue).

My "quick & dirty" solution for this might be a timeout for each replication/sync., that calls `.cancel` on the replication after a few seconds (should adjust to network speed: e.g. 5s for "slow 3G" profile, 100ms for "fast DSL/fiber", etc.) and a changes-handler, that clears that timeout on the first call.

**Comment by SourceR85** [comment]
@madhukudala did set the `live` or `continuous` option `true`?

Without code, i just can guess it on the `feed=longpoll` argument...

If that's not the problem, try to reproduce that behavior with a minimal example code and share it in a new issue.

**Comment by madhukudala** [comment]
@SourceR85 After replication start pouchdb sending the first request as 

![temp](https://user-images.githubusercontent.com/7322186/191716927-794a3fdb-500f-45c7-969f-47db2bd147de.PNG)

Below is our replication code
`this.applicationFromSyncProjectsHandler = PouchDB.replicate
        .from(remoteDB, {
          retry: true,
          live: true,
          selector: {"projectNumber":"46876-SOUTHTX"},
          batch_size: 500
        })`

One thing I observed is when there is like 3L(Present docs in my remote db) docs in remote db the above first request is taking like 2 min+ to identify the changes.

**Comment by SourceR85** [comment]
@madhukudala As I suspect in my [previous post](https://github.com/pouchdb/pouchdb/issues/8545#issuecomment-1252544447):
The "problem" is found in your replication options:
>  `PouchDB.replicate.from(remoteDB, {` **> `retry: true, live: true,` <** `selector: ...`

Set the options as follows and it should run fine.
```javascript
this.applicationFromSyncProjectsHandler = 
PouchDB.replicate.from(remoteDB, {
	batch_size: 500,
	selector: {
		projectNumber: "XYZ"
	}
})
```
FYI, the `live` and `retry` options are omitted (both properties are set `false` as default).
Read the [replication documentation](https://pouchdb.com/api.html#replication) for a deeper explanation.

**Comment by madhukudala** [comment]
@SourceR85 I don't think that the problem is with retry and live options.

I am thinking that when there is no checkpoint for the first time in the source and target the first request to get the details from the couch is taking time. Maybe in the background, it was doing something and taking the time initially.

When I hit through the postman also it's taking the same time when we use since=0 as a query param in the changes request.

POST Request: `http://localhost:5984/mydb/_changes?style=all_docs&filter=_selector&since=0&limit=250`
Request Body: `{"selector":{"projectNumber":"XYZ"}}`

FYI, In couch db we already have an index for projectNumber. Need to see why it was taking that much time.

**Comment by madhukudala** [comment]
Any suggestions from core team of pouchdb or other team who are using pouchdb?

**Comment by SourceR85** [comment]
Seems like a performance problem on CouchDB, I can reproduce something similar on my machine (100k documents, a year of heavy activity).
After copying (just replicate the db), the query goes from ~70 (on original db) down to ~10 seconds (on replicated db).

Since PouchDB is just the front-end lib,
your questions about database performance/optimization are better at placed the [Apache/CouchDB repo](https://github.com/apache/couchdb)

**Comment by madhukudala** [comment]
@SourceR85 any thoughts about this issue #8595? This is not the correct place to ask about another bug. sorry for that.

**Comment by madhukudala** [comment]
As we haven't find why it is happening we moved to individual db for individual project by removing filtered replication.
So closing this issue as there is no response since ling time from PouchDB core team.
