### ISSUE TITLE
can remove console log in func checkFieldValueType ?

### ISSUE THREAD

**Issue by maskerliu** [pouchdb/pouchdb#8564]
### Issue
console log 'here false' on production env

i found in `function checkFieldValueType(name, value, isHttp) ` will do console log print, can remove this log?
```
if (name === '$regex') {
	if (typeof value !== 'string') {
		console.log("here", isHttp);
		if (isHttp) {
			message = 'Query operator $regex must be a string.';
		} else if (!(value instanceof RegExp)) {
			message = 'Query operator $regex must be a string or an instance ' +
				'of a javascript regular expression.';
		}
	}
}
```

### Info
- Environment: Node.js & browser 
- Platform: Chrome
- Adapter: (idb/indexeddb/memory/leveldb/etc.)
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

### Reproduce
Issues that others can reproduce are far easier to fix, we have a website that may help you provide a
live example of the bug @ https://pouchdb-bug-helper.glitch.me/

**Comment by garethbowen** [comment]
:facepalm:
