### ISSUE TITLE
The error `this.emit is not a function` has been raised while local storage has changed from other windows.

### ISSUE THREAD

**Issue by vrtmrz** [pouchdb/pouchdb#8581]
### Issue
Hi, team! I am always thankful to you for this grateful and excellent database!

I noticed that the error that I wrote in the title became shown on the browser. (It happens both with using `pouchdb-browser` and custom build from the core and some required plugins.). After I checked some behaviour and realise a concern, therefore I made a patch.
The reference to `this` looks has been captured in the function at [packages/node_modules/pouchdb-utils/src/changesHandler.js](https://github.com/pouchdb/pouchdb/blob/0bdb3423acf0cc4fae8747c1bd2cea0b1cf23339/packages/node_modules/pouchdb-utils/src/changesHandler.js#L13).

I made [the patch](https://github.com/vrtmrz/pouchdb/commit/181d3b6dd8adcec9940f60c5bec70540622d316a) and tested it, and looks like works fine.

Would you mind if I make make a pull request?

### Info
- Environment: Browser
- Platform: Chrome
- Adapter: idb
- Server: N/A

### Reproduce
1. Open two windows of pouchdb.com
2. Open devTools in both windows. perform localStorage.setItem("Hello", World")
3. The error appears in the opposite window.

**Comment by steodor** [comment]
+1, we found this issue as well and came up with this exact same bugfix. We are currently monkey-patching the `index.js` and `index-browser.js` files in production so a pull request and official fix would be more than welcome. Thanks!

**Comment by vrtmrz** [comment]
I am relieved to hear that I am not the only one.

I made a pull request, hope it will be reviewed and processed, and PouchDB becomes perfect again!

**Comment by mbret** [comment]
Can confirm the issue, it broke my synchronization as well.

**Comment by ishaiavrahami** [comment]
Hi I’m also getting this error. Is there a solution for this?

**Comment by mbret** [comment]
> 

only downgrading at this point

**Comment by vrtmrz** [comment]
In my opinion, as a temporary solution, we could utilize the temporarily modified package located in our local drive.
Like this: https://github.com/vrtmrz/obsidian-livesync/blob/2c36ec497c5f57093794bbf14914614297670c9d/package.json#L38. 

It might be better to be idempotent.

**Comment by vrtmrz** [comment]
Thank you for merging the PR!

**Comment by AlbaHerrerias** [comment]
The fix was released in 8.0.1. Thank you!
