### ISSUE TITLE
await fetchFun(url, options) -> not returning

### ISSUE THREAD

**Issue by topse** [pouchdb/pouchdb#8618]
### Issue
Hi,
I am writing a quite complex application and stumbling over the following problem:
```
const db = new PouchDB(url);
const doc1 = await db.get(id1);
const doc2 = await db.get(id2);
```
The second await never returns.

I followed in the debugger until a function: 
```
  const ourFetch = async function (url, options) {

    options = options || {};
    options.headers = options.headers || new h();

    options.credentials = 'include';

    if (opts.auth || host.auth) {
      let nAuth = opts.auth || host.auth;
      let str = nAuth.username + ':' + nAuth.password;
      let token = thisBtoa(unescape(encodeURIComponent(str)));
      options.headers.set('Authorization', 'Basic ' + token);
    }

    let headers = opts.headers || {};
    Object.keys(headers).forEach(function (key) {
      options.headers.append(key, headers[key]);
    });

    /* istanbul ignore if */
    if (shouldCacheBust(options)) {
      url += (url.indexOf('?') === -1 ? '?' : '&') + '_nonce=' + Date.now();
    }

    let fetchFun = opts.fetch || f$1;
    return await fetchFun(url, options);
  };
```
In the last line of that function everything seems to be alright: there is a valid fetch-Function (the default one), a valid url (if I copy the value and open it in the browser I immediatly get the requested document) and the options are "normal" (2 headers, "accept" and "content-type" to "application/json".

But that function never returns... I also used Wireshark to get the traffic. The Request for doc1 is "normal" (GET and RESPONSE), for the second request there is nothing in the Wireshark-Log.

The "Network Log" of Firefox is also strange:
![grafik](https://user-images.githubusercontent.com/893695/230185957-9058284e-fd0a-4bdd-9fff-083267b5dd25.png)

Both request show up, but there is no information about the second one. I can click it, but it says no header, no request.

### Info
- Environment:
    - Create-React-Application in Browser
    - createMiddlewareProxy forwards the PouchDB Requests to a CouchDB 3.3.1 Server
- Platform: Firefox, latest; Chrome latest
- Adapter: http
- Server: CouchDB 3.3.1

### Reproduce
I have no idea how to reproduce... the application is in development for some time -- ok as a one person project -- but still there is lots of PouchDB in use... and that is the first time it does not work.

I am prepared to help in every possible way -- but I do not have an idea, what to do next to track the problem down.

**Comment by topse** [comment]
Ok... I found the problem... HTTP1.1 in Firefox only allows 6 concurrent connection to a single server and when using some notifications for changes this limit is reached quite easily... Is there a possibility to force PouchDB to use HTTP/2?

Best Regards,
Tobias

**Comment by garethbowen** [comment]
I'd recommend against having multiple continuous changes feeds running at the same time. You'd be better off having a single changes feed that calls different handlers when a change occurs, then you're only using a single connection.

With regards to http/2, PouchDB will happily use it if the server is set up to provide it. The specific protocol being used is below the level of PouchDB and up to the browser to negotiate with the server.
