### ISSUE TITLE
PouchDB.get(): TypeError when optional argument 'options' is null

### ISSUE THREAD

**Issue by regnete** [pouchdb/pouchdb#8706]
When the API-method 'get' is called  without a callback an unexpected error is thrown:
`TypeError: Cannot read properties of null (reading 'open_revs')`

Environment:
 - Browser: Chrome
 - PouchDB: https://github.com/pouchdb/pouchdb/releases/download/8.0.1/pouchdb-8.0.1.js

Reproducer:

```js
var db = new PouchDB({name: "test"});
var id = "12345678";
db.put({_id: id, content: "test"}).then(function(){

  db.get(id, function(error, result){
    if(error)
      console.error("cannot get with callback", error);
    else
      console.log("get with callback", result)
  });

  db.get(id, null) .then(
  	function(result){
    	  console.log("get with promise", result)
       }, 
       function(error){
  	   console.error("cannot get with promise", error);
	});
});

```

The following line of code should be inserted at https://github.com/pouchdb/pouchdb/blob/980970331b232969824df71df7bf0bf8cf19053f/packages/node_modules/pouchdb-core/src/adapter.js#L496 to avoid the error:

```js
opts = opts || {};
```

**Comment by regnete** [comment]
Thank you for the fast response on this issue. A PR is a large effort for a single line of code. Would be great if someone who modifies the code anyway could apply this little change.

**Comment by garethbowen** [comment]
A PR is the only way code is changed by anyone, even someone who modifies the code anyway.

**Comment by regnete** [comment]
OK. May take a while til I find the time ...

**Comment by AmalChandru** [comment]
@garethbowen I was just going through the project and came across this conversation. Submitted a PR with the suggested modifications. Please let me know if any further details are needed for the commit

**Comment by garethbowen** [comment]
Merged. Thanks @AmalChandru
