### ISSUE TITLE
GitHub Action errors building the master branch

### ISSUE THREAD

**Issue by garethbowen** [pouchdb/pouchdb#8713]
### Issue
GitHub Actions build of the master branch are showing error Annotations but ultimately the build passes with a green check. It appears as if the first try fails on a test failure, then when the retry runs it passes, so the whole build is marked as passing. However when the retry happens nothing is logged which makes me think it's not actually running anything at all.

Logs:
```
// lots of errors

  [29]</</</testUtils.cleanup@utils-bundle.js:15383:7
  @test.issue3646.js:15:17
  



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pouchdb-monorepo@7.0.0-prerelease test-browser: `npm run build-test && node ./bin/test-browser.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pouchdb-monorepo@7.0.0-prerelease test-browser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-07-24T22_34_18_786Z-debug.log
npm ERR! Test failed.  See above for more details.
Error: Process completed with exit code 1.

// First retry

Run npm test
  npm test
  shell: /usr/bin/bash -e {0}
  env:
    NODE_VERSION: 14
    TEST_HOST: localhost
    CLIENT: firefox
    SERVER: pouchdb-server

> pouchdb-monorepo@7.0.0-prerelease test /home/runner/work/pouchdb/pouchdb
> ./bin/run-test.sh

// Cleanup
```

Between the ./bin/run-test.sh and the // Cleanup it should actually run the tests...

Screenshot:

https://user-images.githubusercontent.com/191496/255793747-357c2268-2f88-4e66-b460-d22ae33ab45d.png

Example build: https://github.com/pouchdb/pouchdb/actions/runs/5650289637

There are other examples going back 7 months (or more) so this isn't a recent change.

### Info
- Environment: N/A
- Platform: GitHub
- Adapter: All
- Server: N/A

### Reproduce
Seems to happen frequently on `master` though I haven't seen it on PR builds.

**Comment by alxndrsn** [comment]
Cross-posting from https://github.com/pouchdb/pouchdb/pull/8714:


https://github.com/pouchdb/pouchdb/actions/runs/5653105872/job/15313785258#step:4:4115 First Retry passed like this:

```
##[group]Run TYPE=mapreduce ADAPTERS=http npm test
␛[36;1mTYPE=mapreduce ADAPTERS=http npm test␛[0m
shell: /usr/bin/bash -e {0} 
env:
  NODE_VERSION: 14
  TEST_HOST: localhost
  CLIENT: firefox
  SERVER: pouchdb-server
##[endgroup]

> pouchdb-monorepo@7.0.0-prerelease test /home/runner/work/pouchdb/pouchdb
> ./bin/run-test.sh

+ '[' -z '' -a -z pouchdb-server ']' 
+ : firefox
+ : http://127.0.0.1:5984
+ : memory
+ export VIEW_ADAPTERS
+ [[ ! -z pouchdb-server ]]
+ '[' pouchdb-server == pouchdb-server ']' 
+ export COUCH_HOST=http://127.0.0.1:6984
+ COUCH_HOST=http://127.0.0.1:6984
+ [[ -n pouchdb/pouchdb ]]
+ pouchdb-setup-server
+ '[' -d pouchdb-server-install ']' 
+ exit 0
```

Looks like this issue was introduced by https://github.com/pouchdb/pouchdb/pull/8656
