### ISSUE TITLE
Add a fuzzy test generator for replication

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#872]
We have a bunch of test replication bugs without STR

Testing replication is easy, the 2 databases should be the same once you are done. write a test (probably not enabled by default) that just fires off a bunch of requests, reads / writes / updates / deletes

Then makes sure the databases are the same at the end of it

**Comment by jo** [comment]
random-document-stream is cool but we need a good mix including higher revision docs.

**Comment by daleharvey** [comment]
Can improve this a bunch, but initial version landed in https://github.com/pouchdb/pouchdb/commit/8df1beaa7cda5c5327ec041fd3ec391fa7365406
