### ISSUE TITLE
Overriding default implementations with plugin not working

### ISSUE THREAD

**Issue by louwers** [pouchdb/pouchdb#8737]
### Issue

It doesn't seem to be possible to override default PouchDB implementations anymore. 

Maybe related #8450

This example in the docs doesn't work because of this: https://pouchdb.com/api.html#plugins:~:text=Example%20Plugin%3A%20Intercept%20Updates (also there is a typo, `doc` is undefined).

### Info
- Environment: (Node.js/browser/hybrid app/etc.) Browser
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.) Firefox
- Adapter: (idb/indexeddb/memory/leveldb/etc.) N/A
- Server: (CouchDB/Cloudant/PouchDB Server/etc.) N/A

### Reproduce

```js
  PouchDB.plugin({
    bulkDocs : function () {
      console.log("Hello!");
    }
  });


const localDb = new PouchDB('db')
localDb.bulkDocs() // does not call above method
```

**Comment by garethbowen** [comment]
@louwers Is this a duplicate of [this issue](https://github.com/pouchdb/pouchdb/issues/8594)?

If you think so, could you try the fix in [this PR](https://github.com/pouchdb/pouchdb/pull/8648)?

If that works then we can dust of the PR and get it merged...

**Comment by louwers** [comment]
@garethbowen Looks like it. I think it would work.

I don't know how to try it out though.

**Comment by garethbowen** [comment]
@louwers Well it depends how you're depending on pouchdb. If you use npm you can just go into your node_modules and manually apply the fix. Or you can depend on the branch instead of a released version.

**Comment by louwers** [comment]
When I depend on the branch I get a `pouchdb-monorepo` dependency.

I will try your other suggestion. 👍
