### ISSUE TITLE
TLS cert expired on pouchdb.org

### ISSUE THREAD

**Issue by mrjones-plip** [pouchdb/pouchdb#8852]
### Issue
TLS cert expired on pouchdb.org

I didn't see another repo for the website - this is no doubt the wrong place, but figured better the wrong place than not at all.

### Info
- Environment: browser
- Platform: All: Chrome/FF/Safari/Edge/iOS/Android
- Adapter: NA
- Server: NA

### Reproduce
Go to pouchdb.com

expected: valid cert
actual: invalid cert

> Websites prove their identity via certificates, which are valid for a set time period. The certificate for pouchdb.com expired on 1/22/2024.
> 
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE
> 
> View Certificate

![image](https://github.com/pouchdb/pouchdb/assets/8253488/e6f0034e-e682-49a0-9110-b63855408e71)

**Comment by garethbowen** [comment]
@janl Can you have a look please? cc @daleharvey

**Comment by janl** [comment]
we±’re looking into it

**Comment by janl** [comment]
fixed!
