### ISSUE TITLE
Pouchdb fails to initialize in typescript project "import_events.default is not a constructor"

### ISSUE THREAD

**Issue by antoKeinanen** [pouchdb/pouchdb#8869]
### Issue
Pouchdb fails to initialize in typescript project with the following code:

```ts
import PouchDB from "pouchdb";

export const db = new PouchDB("mydb");
```

### Logs:
Error on chrome:
```
Uncaught TypeError: Class extends value [object Object] is not a constructor or null
    at pouchdb.js?v=2b4915c7:1525:43
```
Error on firefox:
```
Uncaught TypeError: import_events.default is not a constructor
    <anonymous> index-browser.es.js:457
```

### Info
- Environment: browser
- Platform: tested on Firefox `123.0 (64-bit)` and Chrome `122.0.6261.94 (Official Build) (64-bit)`

### Reproduce
[https://github.com/antoKeinanen/pouchdb-test](https://github.com/antoKeinanen/pouchdb-test)

**Comment by antoKeinanen** [comment]
Seems to be a duplicate of #8607

**Comment by cubexy** [comment]
This is fixed by just installing the `events` package. (on NPM: `npm install events`)
