### ISSUE TITLE
Pouchdb@8.0.1, gives a high vulnerability peer dependancy of tough-cookie@4.1.2  when scanned by Veracode Scanner

### ISSUE THREAD

**Issue by Noble-Shiva** [pouchdb/pouchdb#8873]
### Issue
V High vulnerability found during the Veracode Scan for pouchdb@8.0.1
<img width="1159" alt="image" src="https://github.com/pouchdb/pouchdb/assets/25147932/f7008a6c-2e30-4dc0-95dc-988b384784f1">

### Info
- Environment: (Node.js - v16.14.2)
- Platform: (Chrome)
- Adapter: ( indexeddb
    "pouchdb": "^8.0.1",
    "pouchdb-adapter-memory": "^8.0.1",
    "pouchdb-find": "^8.0.1", )
- Attachment
<img width="263" alt="image" src="https://github.com/pouchdb/pouchdb/assets/25147932/bae26192-4757-4cb9-83d1-88125a605f0f">
- React - 
<img width="186" alt="image" src="https://github.com/pouchdb/pouchdb/assets/25147932/972527d9-2e6e-46d7-b4b5-3f423e3b9366">

### Reproduce
Scanned the react project source as a part of org compliance and security policies with "**Veracode**" found that pouchdb@8.0.1 actually has a peer dependancy vulnerability on touch-cookie@4.1.2.

Any helping with resolving this would be appreciated as this is a release blocker.

Any information on when the plugin with the peer dependancy would be updated would also be helpful.

**Comment by garethbowen** [comment]
Thanks for reporting. We can look at bumping this dependency.

However please note that this is not blocking your release - you should be able to manually bump the dependency in your package-lock to use tough-cookie@4.1.3 without requiring a pouchdb release.

**Comment by garethbowen** [comment]
Looking at this some more, it is fixed in `master` pending release. We need to get a release out soon to clean this and other things up. Closing for now.
