### ISSUE TITLE
TLS cert expired on pouchdb.org

### ISSUE THREAD

**Issue by mrjones-plip** [pouchdb/pouchdb#8885]
### Issue
TLS cert expired on pouchdb.org

I didn't see another repo for the website - this is no doubt the wrong place, but figured better the wrong place than not at all.

This happened [two months ago as well](https://github.com/pouchdb/pouchdb/issues/8852).

I note it's a Let's Encrypt cert, so likely the automatic renewal and automatic reloading of the cert isn't working correctly. The `server` header is responding with `nginx` - so [maybe this link will help](https://www.linode.com/docs/guides/enabling-https-using-certbot-with-nginx-on-ubuntu/)? I'm pretty handy with `nginx`, feel free to ask questions if you have 'em!

### Info
- Environment: browser
- Platform: All: Chrome/FF/Safari/Edge/iOS/Android
- Adapter: NA
- Server: NA

### Reproduce
Go to pouchdb.com

expected: valid cert
actual: invalid cert

> Websites prove their identity via certificates, which are valid for a set time period. The certificate for pouchdb.com expired on 3/23/2024.
>  
> Error code: [SEC_ERROR_EXPIRED_CERTIFICATE](about:certerror?e=nssBadCert&u=https%3A//pouchdb.com/&c=UTF-8&d=%20#certificateErrorDebugInformation)
>
> View Certificate

![image](https://github.com/pouchdb/pouchdb/assets/8253488/31e7b9d8-a0d2-4a37-8530-a099e8200719)

**Comment by mrjones-plip** [comment]
cc @janl  @daleharvey

**Comment by janl** [comment]
already fixed yesterday
