### ISSUE TITLE
Improving replication performance, looking at the "_attachment fitting through XMLHttpRequest" bottleneck

### ISSUE THREAD

**Issue by rjsteinert** [pouchdb/pouchdb#889]
Firefox has always seemed to lock up quite dramatically when fitting just a few MB of data through XMLHttpRequest.  Chrome is a little better in this department.  It sure would be handy if there was something in the underlying data storage protocols that downloaded the file directly to disk without having to turn the file into a blob in memory before saving to disk.  Does anyone know of anything like this? Anything even just experimental?  If not something like just mentioned, does anyone have any ideas on improving performance of replication in other ways?

**Comment by daleharvey** [comment]
We now dont base64 attachments and fetch them seperately
