### ISSUE TITLE
Encrypting the database

### ISSUE THREAD

**Issue by danilobatistaqueiroz** [pouchdb/pouchdb#8902]
It's a question. Can I encrypt my database?  
I'm using PouchDB for Node.  
My npm packages:  
cordova-sqlite-storage  
pouchdb  
pouchdb-adapter-cordova-sqlite  

I'm using this command to open my database, and It isn't encrypted:  
```ts
    let options = {adapter:'cordova-sqlite',location:'default',androidDatabaseImplementation:2, key:'123'};
    PouchDB.plugin(require('pouchdb-adapter-cordova-sqlite'));
    this.pdb = new PouchDB('employees.db', options);
```

**Comment by janl** [comment]
Yes https://www.npmjs.com/package/crypto-pouch
