### ISSUE TITLE
DISCUSS: add Node 18, 20 & 22 to CI?

### ISSUE THREAD

**Issue by janl** [pouchdb/pouchdb#8943]
Pro: more testing
Con: slower total test run time, might need work to support newer versions

Alt: only test LTS and move older-than-LTS versions to a weekly “test old” action thing?

**Comment by janl** [comment]
maybe not ahead of 9.0.0 release, but def after

**Comment by garethbowen** [comment]
> Alt: only test LTS and move older-than-LTS versions to a weekly “test old” action thing?

I don't like this because they invariably get ignored when they start failing.

**Comment by janl** [comment]
oops, I’m late to this party: https://github.com/pouchdb/pouchdb/pull/8664
