### ISSUE TITLE
Need support  of Pouchdb sync/replication over Websocket 

### ISSUE THREAD

**Issue by yugamg** [pouchdb/pouchdb#8953]
### Issue
We are encountering issues with replicating/syncing CouchDB and PouchDB using WebSockets. Currently, there is no available adapter that supports WebSockets. We attempted to use the socket-pouch package, but it is outdated (8 years old), unmaintained, and incompatible with the latest version of PouchDB, leading to errors.

### Info
- Environment: App (Browser)
- Platform: Chrome
- Adapter: indexeddb
- Server: CouchDB

### Reproduce
Could not able to achieve websocket support for sync for faster replication on pouch-couchdb.

**Comment by iko-jpmascaro** [comment]
I am also trying to get this functionality as well. ran into the same issues

**Comment by SourceR85** [comment]
https://github.com/pouchdb-community/socket-pouch isn't part of pouchdb.
Please write your issue there and provide your help to maintain the project (if no one is getting involved, nobody is there who cares).
