### ISSUE TITLE
Planning 9.0.0 release on Friday Next Week

### ISSUE THREAD

**Issue by janl** [pouchdb/pouchdb#8955]
Hey all, we are planning for a new PouchDB release Friday next week. It’ll be 9.0.0. If there is anything outstanding not on master yet that you’d like to see in the release, please do link it here.

**Comment by ramiscik** [comment]
[https://github.com/pouchdb/pouchdb/issues/8833](url)

I love PouchDB and CouchDB and use both in production. However, in my next project, I noticed that under "high loads," pouchdb-find leaks memory, and the heap size of the process keeps increasing until it breaks, regardless of the --max-old-space setting.

Other operations like put, post, delete, and upsert work well under high load. I am mostly using 'memdown' and just performing update operations without adding anything new to the database during the operations.

By the way, I tried using leveldb, rocksdb, and memdown as adapters, but the results are the same. I tried to figure it out, but maybe someone else can understand and fix it better.

**Comment by janl** [comment]
thanks for the pointer, we are probably not getting to this for 9.0.0, but we’ll have a look

**Comment by alex-kinokon** [comment]
Is there a list of breaking changes?

**Comment by janl** [comment]
Yes, it is listed in the release notes: https://pouchdb.com/2024/05/24/pouchdb-9.0.0.html

> Introduce a default limit (of 25) to the .find() method. This constitutes a backwards incompatible change and is the reason for the major version bump.

As far as we know, this is the only API BC break.

**Comment by janl** [comment]
woot: https://pouchdb.com/2024/05/24/pouchdb-9.0.0.html
