### ISSUE TITLE
TLS cert expired on pouchdb.com

### ISSUE THREAD

**Issue by mrjones-plip** [pouchdb/pouchdb#8991]
### Issue
TLS cert expired on pouchdb.com

I didn't see another repo for the website - this is no doubt the wrong place, but figured better the wrong place than not at all.

This happened [in late Jan](https://github.com/pouchdb/pouchdb/issues/8852) and again in [late Mar](https://github.com/pouchdb/pouchdb/issues/8885).

I note it's a Let's Encrypt cert, so likely the automatic renewal and automatic reloading of the cert isn't working correctly. The `server` header is responding with `nginx` - so [maybe this link will help](https://www.linode.com/docs/guides/enabling-https-using-certbot-with-nginx-on-ubuntu/)? I'm pretty handy with `nginx`, feel free to ask questions if you have 'em!

### Info
- Environment: browser
- Platform: All: Chrome/FF/Safari/Edge/iOS/Android
- Adapter: NA
- Server: NA

### Reproduce
Go to pouchdb.com

expected: valid cert
actual: invalid cert

> Websites prove their identity via certificates, which are valid for a set time period. The certificate for pouchdb.com expired on 9/20/2024..
>  
> Error code: [SEC_ERROR_EXPIRED_CERTIFICATE](about:certerror?e=nssBadCert&u=https%3A//pouchdb.com/&c=UTF-8&d=%20#certificateErrorDebugInformation)
>
> View Certificate

**Comment by mrjones-plip** [comment]
cc @janl  @daleharvey @garethbowen

**Comment by davidgeary** [comment]
Are you sure you don't mean _pouchdb.com_, rather than _pouchdb.org_?  (_pouchdb.org_ doesn't appear to resolve to anywhere.)  Otherwise, this looks like a duplicate of #8988

**Comment by mrjones-plip** [comment]
Oh - indeed! Thanks @davidgeary .

I've updated this ticket and the two prior clones.  

finally, I see there's now a valid cert, so I'll close this ticket.  I note that the cert showing now is `Not Before: Wed, 21 Aug 2024 11:04:35 GMT` - so I wonder if it was ready and waiting but the server hadn't been restarted to reload the new cert?
