### ISSUE TITLE
adapter-indexeddb: needsRewrite can erroneously return undefined

### ISSUE THREAD

**Issue by maralorn** [pouchdb/pouchdb#9003]
### Issue

`needsRewrite` in adapter-indexeddb `rewrite.js` sometimes erroneously returns `undefined`.

#### Example
```javascript
needsRewrite({year: { 2024: []}})
```
is `true`, because a key can’t begin with a number.
But
```javascript
needsRewrite({anobject: { without: "need to rewrite" }, year: { 2024: []})
```
gives `undefined`. Expected would be `true` because the key `2024` should be rewritten.

Similar to #9002 this can lead to `data` not being correctly sanitized and thus indices to miss entries.

### Info
- Environment: browser
- Platform: Chrome
- Adapter: indexeddb
- Server: CouchDB

**Comment by maralorn** [comment]
Thanks for the reviews!

**Comment by alxndrsn** [comment]
> Thanks for the reviews!

Thanks for the fixes!
